### ISSUE TITLE
If condition in compiler

### ISSUE THREAD

**Issue by vezzo86** [arduino/Arduino#10009]
When you do an error in the code for example:
`if(x=y){x=5;}`
The compilert say that all is ok but = is not correct, the right way is ==.

**Comment by matthijskooijman** [comment]
This is just how C++ works: `if (x=y)` *is* correct, it just does not mean what you intended. An assignment can be used as an expression, which can be a feature in some cases, but is also a source of bugs.

If you enable warnings in the Arduino preferences, the compiler can warn you of this. Alternatively, people sometimes reverse the order of arguments when comparing with constants, e.g. `if (5 == x)` which results in an error if you forget one =.

I don't think there's a bug here, so I'm closing this issue.
