### ISSUE TITLE
[Library Manager] Please add EspBootstrap library to the library manager

### ISSUE THREAD

**Issue by arkhipenko** [arduino/Arduino#10011]
https://github.com/arkhipenko/EspBootstrap.git

Library helps bring new device online and get connected into ecosystem: 1) Define runtime parameters 2) Get initial set of parameters from code or from user (via simple webform in AP mode) and 3) connect and download a simplified json config file + process it. 4) Save all parameters in the EEPROM for future use

**Comment by cmaglie** [comment]
Done.

**Comment by arkhipenko** [comment]
Thank you!
