### ISSUE TITLE
[Library Manager] Blynk_WiFiNINA_WM library for AVR Mega, SAMD, SAM DUE, STM32, Teensy, etc. boards boards

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10013]
https://github.com/khoih-prog/Blynk_WiFiNINA_WM

### New Releases v1.0.0

1. This release of very-easy-to-use will help you to eliminate hardcoding your Wifi and Blynk credentials for Mega/SAMD/Teensy/STM32, etc. boards running WiFiNINA shields, and updating/reflashing every time when you need to change them.
2. Configuration data are stored in configurable location in EEPROM/FlashStorage
3. When WiFi and/or Blynk connection is lost, the WM will try auto-reconnect.
4. `Config Portal Static IP address, Name and Password.`
5. `Static IP address, Gateway, Subnet Mask.`
6. Currently support AVR Mega and SAMD (ZERO, MKR, NANO_33_IOT, M0, M0 Pro, AdaFruit CIRCUITPLAYGROUND_EXPRESS, etc.) boards. Will add more very soon.
7. Enhance GUI.

**Comment by cmaglie** [comment]
Done.
