### ISSUE TITLE
[Library Manager] Please add EasyNextionLibrary library to the library manager

### ISSUE THREAD

**Issue by Seithan** [arduino/Arduino#10012]
https://github.com/Seithan/EasyNextionLibrary

A simple library that uses only four functions. You can easily benefit from Nextion's wide range of features and advantages in just a few easy steps. The library uses a custom protocol that can prove to be a powerful tool for advanced users as it can be easily modified to meet one’s needs.

**Comment by cmaglie** [comment]
Done.
