### ISSUE TITLE
[Library Manager] Please add Dictionary library to the library manager

### ISSUE THREAD

**Issue by arkhipenko** [arduino/Arduino#10021]
https://github.com/arkhipenko/Dictionary.git

A dictionary data type with a fast b-tree based search.
Under the hood is a binary-tree structure based on the CRC32 (or CRC64 if you want) hash of the key strings to make lookups fast. Key collisions are taken care of, so plumless and backeroo will properly create separate entries

**Comment by cmaglie** [comment]
Done.
