### ISSUE TITLE
Found two problems on ArduinoBLE.h with Arduino Nano 33 BLE Sense

### ISSUE THREAD

**Issue by qazqwe345** [arduino/Arduino#10027]
1. Use BLE.setConnectionInterval(40, 40), the theoretical communication rate is 1/(40ms*1.25) = 20 Hz, but I test this funtion physically, its communication rate is actually only 10 Hz.
**setConnectionInterval()
Description
Set the minimum and maximum desired connection intervals in units of 1.25 ms.**

2. Use BLE.setConnectionInterval(8, 8), but the communication rate is limited to 40 Hz maximumly. but  the theoretical communication rate should be 100Hz and the BLE module on Arduino Nano 33 BLE Sense should support up to 800Hz maximumly, even though I set BLE.setConnectionInterval(4, 4) or less connection interval, the communication rate is limited to 40 Hz (already test on Arduino Nano 33 BLE Sense to Arduino Nano 33 BLE Sense, Arduino Nano 33 BLE Sense to win10 PC, Arduino Nano 33 BLE Sense to Raspberry Pi 3 B+, all of them is limited to the communication rate of 40 Hz))

**Comment by per1234** [comment]
Closing because the issue has now been reported to the more appropriate repository:
https://github.com/arduino-libraries/ArduinoBLE/issues/68
