### ISSUE TITLE
Problem in uploading program 

### ISSUE THREAD

**Issue by gaurav4599** [arduino/Arduino#10036]
When i try to uploading program at that time i facing following issue.
Arduino: 1.6.5 Hourly Build 2015/05/22 05:41 (Windows 8.1), Board: "Arduino Uno"

Build options changed, rebuilding all

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Blink.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Blink.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\hooks.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\hooks.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\WInterrupts.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WInterrupts.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\wiring.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\wiring_analog.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_analog.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\wiring_digital.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_digital.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\wiring_pulse.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_pulse.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -c -g -Os -w -ffunction-sections -fdata-sections -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\wiring_shift.c -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_shift.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\abi.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\abi.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\CDC.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\CDC.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HardwareSerial.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HardwareSerial0.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial0.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HardwareSerial1.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial1.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HardwareSerial2.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial2.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HardwareSerial3.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial3.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\HID.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HID.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\IPAddress.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\IPAddress.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\main.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\main.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\new.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\new.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\Print.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Print.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\Stream.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Stream.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\Tone.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Tone.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\USBCore.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\USBCore.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\WMath.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WMath.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino -IE:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\variants\standard E:\Softwear\arduino\arduino-nightly\hardware\arduino\avr\cores\arduino\WString.cpp -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WString.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\hooks.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WInterrupts.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_analog.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_digital.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_pulse.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\wiring_shift.c.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\abi.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\CDC.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial0.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial1.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial2.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HardwareSerial3.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\HID.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\IPAddress.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\main.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\new.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Print.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Stream.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Tone.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\USBCore.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WMath.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-ar rcs C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\WString.cpp.o 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-gcc -w -Os -Wl,--gc-sections -mmcu=atmega328p -o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.elf C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp\Blink.cpp.o C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/core.a -LC:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp -lm 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.elf C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.eep 

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avr-objcopy -O ihex -R .eeprom C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.elf C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.hex 

Sketch uses 1,030 bytes (3%) of program storage space. Maximum is 32,256 bytes.

Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.

E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/bin/avrdude -CE:\Softwear\arduino\arduino-nightly\hardware\tools\avr/etc/avrdude.conf -v -patmega328p -carduino -PCOM3 -b115200 -D -Uflash:w:C:\Users\Gaurav\AppData\Local\Temp\build2965254066575265408.tmp/Blink.cpp.hex:i 

avrdude: Version 6.0.1, compiled on Apr 15 2015 at 19:59:58

         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "E:\Softwear\arduino\arduino-nightly\hardware\tools\avr/etc/avrdude.conf"

         Using Port                    : COM3

         Using Programmer              : arduino

         Overriding Baud Rate          : 115200

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xa0

avrdude: stk500_recv(): programmer is not responding

avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xa0

avrdude done.  Thank you.

How can i overcome this problem.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your full error message.
