### ISSUE TITLE
[Library Manager] Please add ESP32AnalogRead

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#10031]
https://github.com/madhephaestus/ESP32AnalogRead

This library encapsulates the ESP32's calibrated adc read for precise 12 bit ADC reads, by loading the ADC configuration data and scaling the values by it. 

Read values are from 0.1v to 3.1v with 0.01v precision.

**Comment by cmaglie** [comment]
Done.

**Comment by madhephaestus** [comment]
@cmaglie You rock, thanks!
