### ISSUE TITLE
[Library Manager] Please add MIDI_Device_Controller library

### ISSUE THREAD

**Issue by solidsnake745** [arduino/Arduino#10034]
https://github.com/solidsnake745/MIDI_Device_Controller

This library provides a simple MIDI-based interface for primarily controlling stepper motors and voice coils musically. Still needs a lot of documentation work, but functionality is all there.

Same library is used in later videos here: http://youtube.com/mrsolidsnake745

Thanks!

**Comment by cmaglie** [comment]
Done.
