### ISSUE TITLE
Bugs Arduino UNO

### ISSUE THREAD

**Issue by Hugx66** [arduino/Arduino#10048]
Hi, i've a problem about my arduino freenove FNK0041... When the code needs to use LED fonctions, my car is no working... My second problem is my remote : with an IR remote, my car is working but with an other remote (with arduino UNO software), there are bugs (forward and reverse are ok but left and right are reversed). I don't know anything about codes because it's my first arduino.

**Comment by AsherThomasBabu** [comment]
@Hugx66 I don't think this is the right place to report this issue of yours, you should be asking this to the Freenove Support: http://www.freenove.com/support.html
