### ISSUE TITLE
please remove my CStringBuilder library from the Library Manager index

### ISSUE THREAD

**Issue by jandrassy** [arduino/Arduino#10041]
I removed the release tags 3 weeks ago. Last week I deleted the repository, but the library is still in index.

I moved the CStringBuilder class to my StreamLib library two years ago and there it has fixes for the new cores.

Thank you

**Comment by cmaglie** [comment]
Lib removed.

**Comment by per1234** [comment]
@cmaglie this report:
>I removed the release tags 3 weeks ago. ... but the library is still in index.

seems to contradict what the Library Manager FAQ says:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#sorry-i-did-something-wrong-how-can-i-change-or-unpublish-an-already-published-library
>In order to unpublish a library version, delete its related tag/release.
>
>Modified or Deleted library versions are processed every Sunday.

Is this a bug in the indexer code that needs to be fixed, or does the documentation need to be updated?

**Comment by cmaglie** [comment]
@per1234 you're right, due to an internal change to our CDN at the moment to change/remove a previously released library is required an admin. May you change the documentation until we fix it?

**Comment by per1234** [comment]
OK, I have now done so:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ/_compare/2fa4c531f25826297186cd59a9ce6c6da23b0a08...cd96c32966955e3f7bfe11110b2eabf83dedfb39

We should be able to just revert that edit once the previous behavior is restored.
