### ISSUE TITLE
DigiKeyboardFr

### ISSUE THREAD

**Issue by Robotechnic** [arduino/Arduino#10049]
This library is a library to use Digispark with an azerty keyboard
https://github.com/Robotechnic/DigiKeyboardFr
## Release 1.0.0:
* The same functions that the original library (write, sendKeyStroke...)
* Every character of the base original lib have been converted to AZERTY keyboard
* New special key:
KEY_ARROW_RIGHT, 
KEY_ARROW_UP,
KEY_ARROW_DOWN,
KEY_CAPSLOCK,
KEY_NUMLOCK,
KEY_ESC,
and every AZERTY key with the prefix KEY_FR_
* Example

**Comment by cmaglie** [comment]
Done.
