### ISSUE TITLE
[Library Manager] DoubleResetDetector_Generic for AVR, Teensy, SAMD, SAM DUE, STM32, etc.

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10046]
https://github.com/khoih-prog/DoubleResetDetector_Generic

DoubleResetDetector_Generic is a library for the **Arduino AVR, Teensy, SAM-DUE, SAMD, STM32.** etc. boards to enable trigger configure mode by resetting the boards twice within configurable timeout seconds.
   
### Releases v1.0.0

1. Support boards such as AVR, Teensy, SAM DUE, SAMD and STM32, etc.
2. AVR Mega, Teensy, STM32 to save data in EPPROM
3. SAMD to sve data in EEPROM-simulated FlashStorage
4. SAM DUE to save data in DueFlashStorage

**Comment by cmaglie** [comment]
Done.
