### ISSUE TITLE
[new library] Please register new library https://github.com/Yurik72/ESPHap

### ISSUE THREAD

**Issue by Yurik72** [arduino/Arduino#10043]
https://github.com/Yurik72/ESPHap

**Comment by per1234** [comment]
Hi @Yurik72. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Yurik72** [comment]
Hi per1234, I did that , please check and proceed, otherwise let me know what is wrong, i'm doing this first time, thanks

**Comment by cmaglie** [comment]
Done.
