### ISSUE TITLE
Library Manager: please add the esp32-WiFiSettings library

### ISSUE THREAD

**Issue by Kartoffel** [arduino/Arduino#10058]
Please add the esp32-WifiSettings library from https://github.com/Juerd/esp32-WiFiSettings

**Comment by Kartoffel** [comment]
It's come to our attention that there's a naming conflict with `WifiConfig.h`. Please hold this while the new library is being renamed.

**Comment by per1234** [comment]
OK, just comment here when you're ready and I'll remove the "Waiting for feedback" label.

**Comment by Kartoffel** [comment]
It's been renamed to WifiSettings, kindly remove the waiting for feedback label :)

**Comment by cmaglie** [comment]
Done.
