### ISSUE TITLE
[library manager] Please Add LiquidCrystalIO to library manager.

### ISSUE THREAD

**Issue by davetcc** [arduino/Arduino#10054]
Library URL: https://github.com/davetcc/LiquidCrystalIO

## Reason for fork and library info

This library is a highly compatible fork for LiquidCrystal that works better with IoAbstraction by yielding to task manager during delays and working with many different Io Expanders supported by IoAbstraction to allow i2c and shift register operation.

## Dependency

IoAbstraction (already in Library Manager)

## Testing

Fully tested with Uno, MEGA and MKR (SAMD). Tested with 16x2 and 20x4 LCD units both directly connected and via IO expanders. I'll continue to test later on a second Windows machine and my Mac, to ensure the released 1.2.0 version is good

## Summary

I am in the process of re-engineering IoAbstraction and tcMenu to be more standard in the way that they work. At the moment tcMenu Designer UI tries to manage its own libraries within the UI (and that is very wrong), they should be taken from library manager, to reduce risk and improve user experience.

This is the first of two libs, I'll submit TcMenuLib itself once this is listed. Sorry, but I need to make sure these go in order to avoid potential issues as there are quite a few users of it these days.

**Comment by cmaglie** [comment]
Done.
