### ISSUE TITLE
[Library Manager] Please add arduino-ledflasher

### ISSUE THREAD

**Issue by aliafshar** [arduino/Arduino#10091]
https://gitlab.com/virchow-personal/arduino-ledflasher

thanks

**Comment by cmaglie** [comment]
You must create and push a `1.0.0` git tag in your repository:

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager
> How can I add my library to Library Manager?
> * [...]
> * Tag it and push the tag (or create a release if you web hosting offers a way to do it, for example with GitHub "releases")
> * [...]

**Comment by aliafshar** [comment]
Ah, sorry about that. I tagged it.

**Comment by cmaglie** [comment]
Done.
