### ISSUE TITLE
[Arduino website] Tutorial StateChangeDetection error in demo code

### ISSUE THREAD

**Issue by DavidCarreira** [arduino/Arduino#10107]
Hi,

I've found a bug in the tutorial "[State Change Detection (Edge Detection) for pushbutton](https://www.arduino.cc/en/Tutorial/StateChangeDetection)"

In the line 73, this code:

`  if (buttonPushCounter % 4 == 0) {`

should be:

`  if (buttonPushCounter % 2 == 0) {`

to check when the counter is odd or even.

**Comment by per1234** [comment]
The tutorial doesn't intend to check whether the counter is odd or even. It states multiple times that the LED is turned on every four button pushes:
```c++
  // turns on the LED every four button pushes by checking the modulo of the
  // button push counter. the modulo function gives you the remainder of the
  // division of two numbers:
```
So the code does what it was intended to do.
