### ISSUE TITLE
Arduino Uno - stk500_getsync(): not in sync: resp=0x00 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1010]
This is [Issue 1010](http://code.google.com/p/arduino/issues/detail?id=1010) moved from a Google Code project.
Added by 2012-08-20T17:16:56.000Z by [weird.de...@gmail.com](http://code.google.com/u/110168968880113189575/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

Hello,

I have Arduino Uno with ATMEGA328P. I tryed to use it as ATTiny45 ISP programmer but alltime same error: stk500_getsync(): not in sync: resp=0x00.

My setup: 
Sketch: examples>arduino isp
Board: tools>board>arduino uno
Programmer: Arduino as ISP

Burn bootloader or upload not work at all. Tryed version 0022 and new one 101. Followed lots of guides but without success. Resistor or capacitator between reset / gnd not work.

Looks like my arduino is damaged but it work well if I upload normal sketch into it. 

Did you know another way how use arduino as ISP? This was described at arduino.cc not working.

Thank you.

**Comment by per1234** [comment]
It's impossible to say what the cause of the error was 4.5 years later but it's likely to have been user error. If it was a bug somewhere in the Arduino software it was fixed long ago because Arduino as ISP works fine now.
