### ISSUE TITLE
Arduino IDE crashes whenever a window is moved between monitors

### ISSUE THREAD

**Issue by ccohen20** [arduino/Arduino#10104]
I use a 2014 13 inch macbook pro.  Whenever I drag an arduino window from one monitor to another, the IDE (version 1.8.12) crashes.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/9764.

The workaround is to use Arduino IDE 1.8.10. You can download it here:
https://www.arduino.cc/en/Main/OldSoftwareReleases#1.5.x
