### ISSUE TITLE
Right click for information on coloured words

### ISSUE THREAD

**Issue by brycecherry75** [arduino/Arduino#10117]
When I was using the word "position" for a rotary switch position variable, it became coloured meaning it was reserved by a particular library (SD.h in this case) even though I was not using this library.
So can I recommend including the ability to determine what library/libraries (or microcontroller) uses a particular reserved word by right-clicking on it in the editor to avoid unintentional use of such words?

**Comment by per1234** [comment]
We have a related suggestion in https://github.com/arduino/Arduino/issues/8931, which is to only highlight the keywords of the libraries actually in use by the sketch.
