### ISSUE TITLE
Additional padding on left side of sketch area. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1012]
This is [Issue 1012](http://code.google.com/p/arduino/issues/detail?id=1012) moved from a Google Code project.
Added by 2012-08-22T16:26:33.000Z by [nihaop...@gmail.com](http://code.google.com/u/108684571414567306207/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE

### Original description

5px padding on the left of the sketch area in Arduino (only looked at in OSX)

makes practical when full screen or when smaller window when selecting the start of a line, 20% chance you'll hit what ever is behind the window

no, it is a usability enhancement

**Comment by ffissore** [comment]
Editor is padded in 1.6.3
