### ISSUE TITLE
[Library Manager] Please update jm_PCF8574

### ISSUE THREAD

**Issue by jmparatte** [arduino/Arduino#10129]
https://github.com/jmparatte/jm_PCF8574/releases/tag/v1.0.5

**Comment by per1234** [comment]
Hi @jmparatte. The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So you don't need to create an issue report every time you release a new version; they'll be picked up automatically. In fact, I can see that your 1.0.5 release is already available in my Library Manager (though it might take some more time before it propagates through the cache to be available everywhere).

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
