### ISSUE TITLE
Wrong image in Adjuino starter kit Projects book

### ISSUE THREAD

**Issue by MorkB** [arduino/Arduino#10127]
On page 13 in step 3 the board is drawn upside down: it explainse how to install the 4 feet but the drawing of the board is the same as in step 4, where you install the Arduino board. So that's not right. If you follow step 3 as it is drawn know, you install the feet on the wrong side of the wood sheet.

And...it's not a wood sheet - it's plastic

**Comment by arhamshah** [comment]
I wanna edit

**Comment by FunzioneFabio** [comment]
Hello @MorkB Thanks for reporting this. In the last version of the Projects Book we have fixed this issue, so you probably have an old version. Sorry for the error.
