### ISSUE TITLE
[Library Manager] Please add tcMenuLib library to Library Manager

### ISSUE THREAD

**Issue by davetcc** [arduino/Arduino#10139]
Library URL: https://github.com/davetcc/tcMenuLib

## About tcMenuLib

TcMenuLib is part of a wider project for building IoT ready menu structures on many different Arduino boards, starting with Uno right through to larger 32-bit boards. The form designer is a separate download and is even packaged on the Windows Store, also soon also on the Mac store. It is a modular system that supports many displays, inputs, and has IoT capability over Ethernet and various serial devices. It is easy to add another type of display, input or remote capability.

## Dependencies

IoAbstraction (already in Library Manager)
LiquidCrystalIO (already in Library Manager)

## Testing

Fully tested with Uno, MEGA, MKR (SAMD) and ESP. See the testing section in the repository for more details.

## Summary

I am in the process of re-engineering IoAbstraction and tcMenu to be more standard in the way that they work. At the moment tcMenu Designer UI tries to manage its own libraries within the UI (and that is very wrong), they should be taken from library manager, to reduce risk and improve user experience.

**Comment by cmaglie** [comment]
Done.
