### ISSUE TITLE
Missing Links on some reference Stream, communication/stream/

### ISSUE THREAD

**Issue by Ridbnet** [arduino/Arduino#10137]
E.G:

[https://www.arduino.cc/reference/en/language/functions/serial/flush](url) Doesn't work

for instance you should change it by adding the parent folder : **communication:**

[https://www.arduino.cc/reference/en/language/functions/communication/serial/flush](url)

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/reference-en/issues/729

I provide some information about the problem there.
