### ISSUE TITLE
[Library Manager] Please update Nospampls/SchedTask

### ISSUE THREAD

**Issue by Nospampls** [arduino/Arduino#10142]
I've updated library.properties for https://github.com/Nospampls/SchedTask.  I have also moved the Tag to the latest commit.  Please update.  Thanks!

**Comment by cmaglie** [comment]
The release has been regenerated, though it could take several hours for the CDN cache to propagate the update. Probably creating a new release `1.0.1` (even if it has only some metadata change) would have been quicker.
