### ISSUE TITLE
Please add jm_LCM2004A_I2C

### ISSUE THREAD

**Issue by jmparatte** [arduino/Arduino#10148]
https://github.com/jmparatte/jm_LCM2004A_I2C

Thank you very much.

**Comment by jmparatte** [comment]
Sorry, the keywords.txt was incomplete and with a wrong format, now corrected.

**Comment by jmparatte** [comment]
SO, SO SORRY, keywords.txt 2nd reformatted to have <tab> instead of <sp> delimiters...

**Comment by cmaglie** [comment]
Done.
