### ISSUE TITLE
[Library Manager] Please add these libraries for supporting a Tiny85 I2C bootloader

### ISSUE THREAD

**Issue by casanovg** [arduino/Arduino#10150]
Please add these libraries for supporting a Tiny85 I2C bootloader:

- [x] https://github.com/casanovg/nb-twi-cmd.git
- [x] https://github.com/casanovg/Nb_TwiBus.git
- [x] https://github.com/casanovg/Nb_Micro.git
- [x] https://github.com/casanovg/Nb_TimonelTwiM.git

Thank you very much.

#### References:
https://hackaday.com/2018/10/20/i2c-bootloader-for-attiny85-lets-other-micros-push-firmware-updates

https://github.com/casanovg/timonel

**Comment by cmaglie** [comment]
Done.

**Comment by casanovg** [comment]
Grazie Cristian!
