### ISSUE TITLE
WiFiShield library ConnectNoEncryption example whitespace problem [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1016]
This is [Issue 1016](http://code.google.com/p/arduino/issues/detail?id=1016) moved from a Google Code project.
Added by 2012-08-26T10:43:37.000Z by [pmjdebru...@pcode.nl](http://code.google.com/u/107266719206833249190/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

The ConnectNoEncryption example has a whitespace error in it that may prevent it from properly building.

Trivial patch attached.

**Comment by sandeepmistry** [comment]
This has been resolved by https://github.com/arduino/Arduino/commit/b4c68b3dff2847ac635bcf7d5eca5504fc07cc70.
