### ISSUE TITLE
[Library Manager] HPDL1414-74HC595

### ISSUE THREAD

**Issue by sqfmi** [arduino/Arduino#10177]
https://github.com/sqfmi/HPDL1414-74HC595-Arduino

**Comment by per1234** [comment]
Hi @sqfmi. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by sqfmi** [comment]
@per1234 oops, just tagged the release. Thanks!

**Comment by cmaglie** [comment]
Done.

**Comment by sqfmi** [comment]
Thanks @cmaglie!
