### ISSUE TITLE
When external editor option is enabled, no "good" visual cue to read-only state ... fix? [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1017]
This is [Issue 1017](http://code.google.com/p/arduino/issues/detail?id=1017) moved from a Google Code project.
Added by 2012-08-27T20:12:53.000Z by [scottjan...@gmail.com](http://code.google.com/u/110205135056751691458/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

A community member just tweeted about how he couldn't editor code in the Arduino IDE. I knew it was immediately the external editor preference, but he had forgot it was enabled. The dimmed code can be misleading if one forgets that external editor is enabled ...

Currently the code is read-only when external editor is toggled, but perhaps the IDE should display a message some place? Like "read-only mode" text? 

I'm under impression that locking the code in read-only state in the IDE is to prevent versioning issues with two potential editors ...  Would it also be possible to leave the arduino IDE code area editable ... but detect for external changes by another editor and pop up a message confirming to overwrite? or inform the user of external changes. 

I guess those are two approaches ...Again, it's a silly problem. I wouldn't classify this as a bug, but a reminder feature. ;)

There's a simple fix and a more complex one (I think).

**Comment by ffissore** [comment]
Fixed a long time ago with a proper background colour and read-only editor
