### ISSUE TITLE
[Library Manager] Please add SerialWireOutput libary

### ISSUE THREAD

**Issue by koendv** [arduino/Arduino#10182]
url:
https://github.com/koendv/SerialWireOutput

**Comment by per1234** [comment]
Hi @koendv. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by koendv** [comment]
OK, done.

**Comment by cmaglie** [comment]
Done.
