### ISSUE TITLE
Mismatching info about Ethernet and Ethernet2 library in Tutorial

### ISSUE THREAD

**Issue by Spielbros** [arduino/Arduino#10195]
The Tutorial pages for the Ethernet, e.g. [the ChatServer Tutorial](https://www.arduino.cc/en/Tutorial/ChatServer), says: 

> Use _[...]_ Ethernet2.h with the Arduino Ethernet Shield 2

But the [Ethernet2 git repository]( https://github.com/adafruit/Ethernet2) it marked as depreciated: 

>This library _[Ethernet2.h]_ is no longer going to be used, since the official Arduino library has been updated and works great

So it seems that the Arduino Ethernet Tutorials are not up-to-date?

**Comment by nitheesh2008** [comment]
hi
