### ISSUE TITLE
Library Manager addition request

### ISSUE THREAD

**Issue by distrakt** [arduino/Arduino#10198]
https://github.com/distrakt/OmEspHelpers/  
with tag 1.5.20200512

Hi,
I've followed the instructions at https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and I hope I have got it right!

This library has been evolved over 4 years and is ready to share. For esp8266/esp32 very easy&simple web control pages.

**Comment by cmaglie** [comment]
Done.
