### ISSUE TITLE
[Library Manager] Please transfer IridiumSBDi2c

### ISSUE THREAD

**Issue by PaulZC** [arduino/Arduino#10213]
https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library
Hi Cristian and team,
At the moment, the IridiumSBDi2c library points to:
https://github.com/PaulZC/IridiumSBD
We have moved this across into the SparkFun repos too.
Can you please delete the library manager entry for that repo and replace it with this one:
https://github.com/sparkfun/SparkFun_IridiumSBD_I2C_Arduino_Library
This time, we have kept both the name and the code version the same:
name=IridiumSBDi2c
version=3.0.0
Sincere thanks - as always,
Paul Clark (@PaulZC)

**Comment by cmaglie** [comment]
Done.

**Comment by PaulZC** [comment]
Thank you Cristian (and @per1234 too!)
All the best,
Paul
