### ISSUE TITLE
EEPROM.read tutorial: no code

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/Arduino#10224]
See title; error "This sketch is no longer here".

https://www.arduino.cc/en/Tutorial/EEPROMRead

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/9823

For anyone who needs it now, the missing sketch was posted at https://github.com/arduino/Arduino/issues/9823#issuecomment-598941661

**Comment by sterretjeToo** [comment]
Sorry for the duplicate; I did a github search for "read" but probably should have fine-tuned the search.

Anyway, not fixing the issue is not the solution. It should be fixed in the tutorial; 3 minutes work for somebody who has access, I guess.
