### ISSUE TITLE
[Library Manager]Please add this library in library manager for plotting graph on Serial Monitor

### ISSUE THREAD

**Issue by MAINAKMONDAL98** [arduino/Arduino#10225]
Please add the library to Library Manger
https://github.com/MAINAKMONDAL98/MSMPLOTTER
Thanks.

**Comment by MAINAKMONDAL98** [comment]
https://github.com/MAINAKMONDAL98/MSMPLOTTER

**Comment by MAINAKMONDAL98** [comment]
Can you please tell me can I see it on library manager searching its name MSMPLOTTER?
Thanks for labeling.

**Comment by per1234** [comment]
@MAINAKMONDAL98 once your library has been added to the Library Manager index, it can indeed be found by searching Library Manager for the library.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this. There may be a delay of some hours after that for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

**Comment by MAINAKMONDAL98** [comment]
thanks @per1234

**Comment by cmaglie** [comment]
Done.
