### ISSUE TITLE
Warning due to "utility" file in library being added as an include directory [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1023]
This is [Issue 1023](http://code.google.com/p/arduino/issues/detail?id=1023) moved from a Google Code project.
Added by 2012-08-30T20:14:54.000Z by [ryan.pav...@gmail.com](http://code.google.com/u/103131440009871534332/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. In a sketchbook library (doesn't matter what, could just make a sample with sample.h empty inside of it), create a file named "utility".  (For instance, a partial implementation of the standard c++ library is how I found this out, but it doesn't have to actually contain anything.)
2. Add an include to a minimal project ensuring your library is added to the include path. (#include <sample.h>)
3. Try building.

**What is the expected output? What do you see instead?**
It succeeds, but warns excessively:
cc1plus.exe: warning: C:\Users\rpavlik\Desktop\src\nexus-omni4wd-arduino\libraries\StandardCplusplus\utility: not a directory [enabled by default]

The compile line goes something like:
C:\Program Files (x86)\arduino\hardware\tools\avr\bin\avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=101 -IC:\Program Files (x86)\arduino\hardware\arduino\cores\arduino -IC:\Program Files (x86)\arduino\hardware\arduino\variants\standard -IC:\Users\rpavlik\Desktop\src\nexus-omni4wd-arduino\libraries\StandardCplusplus -IC:\Users\rpavlik\Desktop\src\nexus-omni4wd-arduino\libraries\StandardCplusplus\utility C:\Users\rpavlik\Desktop\src\nexus-omni4wd-arduino\libraries\StandardCplusplus\valarray.cpp -o C:\Users\rpavlik\AppData\Local\Temp\build2853684677234630722.tmp\StandardCplusplus\valarray.cpp.o 

So you can see that the _file_ libraries\StandardCplusplus\utility, because it exists, was added to the include path. Instead of just existence, the IDE should check for existence of a directory.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

1.0.1 on Windows 7, building for Uno in this example.

**Comment by sandeepmistry** [comment]
This still occurs with libraries that use the 1.0 structure, however with the [Arduino IDE 1.5: Library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) it is no longer as issue, if a ```utility``` file is included in the ```src``` folder.
