### ISSUE TITLE
[Library Manager] WebSockets_Generic to support many more boards

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10241]
[WebSockets_Generic](https://github.com/khoih-prog/WebSockets_Generic)

This library is based on and modified from WebSockets library [Markus Sattler's WebSockets](https://github.com/Links2004/arduinoWebSockets) to support other boards such as  Arduino SAMD21, Adafruit SAMD21, SAMD51, Adafruit's nRF52 boards, etc.

WebSocket Server and Client for Arduino based on RFC6455.

#### New in v2.2.1

1. Bump up to sync with v2.2.1 of original WebSockets library

#### New in v2.1.3

1. Add support to ***nRF52*** boards, such as ***AdaFruit Feather nRF52832, nRF52840 Express, BlueFruit Sense, Itsy-Bitsy nRF52840 Express, Metro nRF52840 Express, NINA_B30_ublox, etc.***.
2. Add support to ***SAM51 (Itsy-Bitsy M4, Metro M4, Grand Central M4, Feather M4 Express, etc.)***.
3. Add support to ***SAMD21 (ZERO, MKR, NANO_33_IOT, M0, M0 Pro, AdaFruit CIRCUITPLAYGROUND_EXPRESS, etc.)***.

**Comment by cmaglie** [comment]
Done.
