### ISSUE TITLE
TCP connections die after few seconds of inactivity [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1024]
This is [Issue 1024](http://code.google.com/p/arduino/issues/detail?id=1024) moved from a Google Code project.
Added by 2012-08-31T10:45:38.000Z by [mas...@liarco.net](http://code.google.com/u/108198104580353504194/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Hardware:
 - Arduino Leonardo
 - WiFi Shield

Software:
 - Arduino IDE 1.0.1
 - Mac OSX 10.7 / Ubuntu 12.04

Libraries:
 - WiFi Libraries (downloaded from arduino.cc)

**What steps will reproduce the problem?**
1. Code a sketch to open a TCP connection with a simple TCP server (I tried with a Node.js HelloWorld as server)
2. Sending and receiving messages works fine, so wait few seconds and the connection will be closed by the Arduino with a "reset" packet as the last packet sent from the board.
3. Now you can't send/receive anything more and the server is not correctly notified about the connection status until it tries to read/write.

**What is the expected output? What do you see instead?**
I expected the connection to be kept open until it was closed properly by the server/client. No other client (except for Arduino) seems to drop the connection in this way.

I'm gonna attach a wireshark log about the traffic produced by my TCP server and the board.

Kind Regards.
Marco Lipparini

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#21
