### ISSUE TITLE
board update fail--java. lang nullponterexception

### ISSUE THREAD

**Issue by hkspatna** [arduino/Arduino#10247]
When I  update ESP8266 community under BOARD  MANAGEMENT  in TOOLS, it fails with message---JAVA.LANG NULLPOINTER EXCEPTION.
Please help

**Comment by per1234** [comment]
Hi @hkspatna. Thanks so much for reporting this. Without the full and exact error output it will not be possible to do an investigation, so I'm going to close this.

If you're still able to reproduce the error and will comment here with the complete output I'll be happy to reopen this.
