### ISSUE TITLE
feature request: Servo class: servo.write(angle, rotationspeed)

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#10245]
feature request: Servo class: servo.write(int angle, float rotationspeed)
angle: degrees (endpoint)
rotationspeed: degrees per second
e.g.,
```
servo.write(90); // let the servo move to position 90° immediately
delay(1000);
servo.write(180, 10.0); // moves the servo from the current position (90°) to position 180° by a rotation speed of 10°/sec

```
The function must not be blocking, so that a following command can be started immediately before the further movement  has been finished (simultaneous movement)

servo1.write(180, 10.0);
servo2.write(45, 5.0);

**Comment by ernesto-tapia** [comment]
Hello, 
I would like to work on this feature request, is it still available?

**Comment by dsyleixa** [comment]
yes, just make a pull request (PR)!

**Comment by ernesto-tapia** [comment]
This was a little bit too much for my current level, and Im not sure that non blocking can be achieved without the use of another update function running in the code. @per1234, do you have any insight on how I can possibly attack this issue?

**Comment by dsyleixa** [comment]
no one to achieve this...?

**Comment by dsyleixa** [comment]
I'll close it her and move it to github Servo lib issue tracker
