### ISSUE TITLE
"Minion" in the documentation

### ISSUE THREAD

**Issue by rkbi** [arduino/Arduino#10240]
There is a (funny) typo in the documentation page at - https://www.arduino.cc/en/Guide/ArduinoProMini

One title says "Use your Arduino Pro **Minion** the Arduino Desktop IDE". Instead it should be  "Use your Arduino Pro **Mini on** the Arduino Desktop IDE" (Space beetween "Mini" and "on")

**Comment by kengdahl** [comment]
Error fixed
