### ISSUE TITLE
USB flashpen updating [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1025]
This is [Issue 1025](http://code.google.com/p/arduino/issues/detail?id=1025) moved from a Google Code project.
Added by 2012-08-31T21:42:29.000Z by [Bes...@gmail.com](http://code.google.com/u/110985001975663993127/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

Now if you need to upgrate your arduino sw, you need to connect a PC. Interesting to "develop" a small linux flashpen that yuo can use standalone for upgrading the arduino.

**Comment by Testato** [comment]
i do not understand this issue, why it remain Open ?

The user that write it 3 yers ago ask for a "Small Linux Flashpen" for update an Arduino board in the field.
Now is it possible, whit Portable directory feature, create an arduino environment portable on a Flashpen.
So i think that this Issue can be closed.

**Comment by Testato** [comment]
"linux flashpen that yuo can use standalone"

may you explain better this idea ?
Example pendrive whit linux inside attached directly on an Arduino Uno ?
How it can be work ???

**Comment by cmaglie** [comment]
The original issue has been closed as invalid, and this too is marked like that, I guess that we just forget to close it.

As you already pointed out, it could be easily achieved by installing the Arduino IDE into a live linux distro.
