### ISSUE TITLE
[Library Manager] Some libraries to add to the library manager

### ISSUE THREAD

**Issue by wollewald** [arduino/Arduino#10258]
Hi, would you please add the following libraries please:

- [x] https://github.com/wollewald/VL6180X_WE
- [x] https://github.com/wollewald/SI1145_WE
- [x] https://github.com/wollewald/AP3216_WE
- [x] https://github.com/wollewald/BH1750_WE

Many thanks in advance.

**Comment by cmaglie** [comment]
Done.
