### ISSUE TITLE
 ARDUINO NANO 33 BLE SENSE    Technical Support

### ISSUE THREAD

**Issue by mbmchip** [arduino/Arduino#10256]
hello!
     Where can I find MP34DT05 routines.Not found in arduino IDE library manager.

**Comment by facchinm** [comment]
PDM library (shipped with Nano33BLE core) can be used to interact with the microphone (like in this example https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/master/libraries/PDM/examples/PDMSerialPlotter/PDMSerialPlotter.ino)

**Comment by mbmchip** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martino Facchin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 下午3:36
收件人:&nbsp;"arduino/Arduino"<Arduino@noreply.github.com&gt;;
抄送:&nbsp;"JonLee"<mbmchip_web@mbm-chip.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [arduino/Arduino]  ARDUINO NANO 33 BLE SENSE    Technical Support (#10256)





 
PDM library (shipped with Nano33BLE core) can be used to interact with the microphone (like in this example https://github.com/arduino/ArduinoCore-nRF528x-mbedos/blob/master/libraries/PDM/examples/PDMSerialPlotter/PDMSerialPlotter.ino)
