### ISSUE TITLE
If I write preprocesor command #if and press auto-format, IDE crashes

### ISSUE THREAD

**Issue by andz885** [arduino/Arduino#10268]
platform windows 10
steps:
open new sketch,
write #if 
press auto-format
your IDE will crash

**Comment by facchinm** [comment]
Wow, THIS is a bug :slightly_smiling_face: 
From a very fast investigation it looks like libAstyle is crashing with 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare: __pos (which is 18446744073709551615) > this->size() (which is 2)
```
as if it was not finding the end of the file. Surely worth investigating. Thanks for reporting!

**Comment by andz885** [comment]
Totally forgot about this.
