### ISSUE TITLE
[Library Manager] SinricPro_Generic Library to support many more boards

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10267]
Please add the [SinricPro_Generic Library](https://github.com/khoih-prog/SinricPro_Generic) to Library Manager.

---
The [SinricPro library](https://github.com/sinricpro/esp8266-esp32-sdk) is written to support only **ESP32 and ESP8266.**

This library is based on and modified from [SinricPro library](https://github.com/sinricpro/esp8266-esp32-sdk) to support many more boards such as **Arduino SAMD21, Adafruit SAMD21, SAMD51, Adafruit's nRF52 boards, Teensy, SAM DUE, STM32, etc.**

### Releases v2.4.0

1. Add support to :

  - ***Arduino SAMD21 (ZERO, MKR, NANO_33_IOT, M0, M0 Pro, AdaFruit CIRCUITPLAYGROUND_EXPRESS, etc.)***.
  - ***Adafruit SAM21 (Itsy-Bitsy M0, Metro M0, Feather M0, Gemma M0, etc.)***.
  - ***Adafruit SAM51 (Itsy-Bitsy M4, Metro M4, Grand Central M4, Feather M4 Express, etc.)***.
  - ***AdaFruit Feather nRF52832, nRF52840 Express, BlueFruit Sense, Itsy-Bitsy nRF52840 Express, Metro nRF52840 Express, NINA_B30_ublox, etc.***.
  - ***Teensy 4.1, 4.0, 3.6, 3.5, 3.2/3.1, 3.0.***
  - ***STM32 (Nucleo-144, Nucleo-64, Nucleo-32, Discovery, STM32F1, STM32F3, STM32F4, STM32H7, STM32L0, etc.)***.
  - ***SAM DUE***
  
2. Bump up to sync with v2.4.0 of original SinricPro library

**Comment by cmaglie** [comment]
Done.
