### ISSUE TITLE
[Library Manager] Add TSD305Lib (IR Thermopile) library to library manager.

### ISSUE THREAD

**Issue by pranjal-joshi** [arduino/Arduino#10273]
The **TSD305Lib** provides features of interfacing TSD305 IR thermopile sensor with Arduino compatible boards using I2C bus for contactless temperature measurement.

Link to download the library: [https://github.com/pranjal-joshi/TSD305Lib-Arduino](https://github.com/pranjal-joshi/TSD305Lib-Arduino)

**Comment by pranjal-joshi** [comment]
This will be useful for many DIY makers as well as industries who are developing IR thermometer to prevent the spread of Covid-19.

Let's make world a better place!
Happy Hacking!

**Comment by cmaglie** [comment]
Done.
