### ISSUE TITLE
open dialog doesn't appear in Ubuntu 12.04 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1027]
This is [Issue 1027](http://code.google.com/p/arduino/issues/detail?id=1027) moved from a Google Code project.
Added by 2012-09-02T17:10:14.000Z by [robb...@digitalica.nl](http://code.google.com/u/100445136873431457156/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, OpSys-Linux, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. install arduino IDE in ubuntu 12.04 using software center
2. click File -> open
3. No 'open file' dialog visible

**What is the expected output? What do you see instead?**
the open file dialog is not there, i expect it to be there

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0 on Ubuntu 12.04 with Unity in dual screen setup

**Please provide any additional information below.**
Maybe related to dual screen setup and/or unity. Also, it did seem to work first, but doesn't any more. I did manually kill some Arduino process in the past.

**Comment by ffissore** [comment]
Open dialog shows up as expected
