### ISSUE TITLE
[Library Manager] Library add request

### ISSUE THREAD

**Issue by gin66** [arduino/Arduino#10299]
Please add my library to the list, if ok:

    https://github.com/gin66/FastAccelStepper

**Comment by cmaglie** [comment]
Done.

**Comment by gin66** [comment]
Thanks. The library is now visible. But it only offers to install the 0.1.x versions. Latest is 0.3.9

How can I do ?

**Comment by cmaglie** [comment]
I see, the issue is that from a certain version the library contains symlinks:

```
JOB 3079 - 2020/06/09 09:33:17 path=github.com/gin66, archivename=FastAccelStepper-0.3.9
JOB 3079 - 2020/06/09 09:33:17 Error syncing library: Error while zipping library: Symlink not allowed: /home/jenkins/jenkins/jobs/Libraries/workspace/gitclones/github.com/gin66/FastAccelStepper/tests/FastAccelStepper.cpp -> ../src/FastAccelStepper.cpp
```

we do not allow symlinking in library releases, you must find a way to avoid them and publish another release (or update an existing one).

**Comment by gin66** [comment]
Thanks a lot for this clarification. I will update accordingly
