### ISSUE TITLE
WiFi library multi-byte WiFiClient::read seems broken [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1029]
This is [Issue 1029](http://code.google.com/p/arduino/issues/detail?id=1029) moved from a Google Code project.
Added by 2012-09-03T17:23:00.000Z by [adrian.m...@gmail.com](http://code.google.com/u/108388509099941515037/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Looking at the code, part of the problem seems to be that it returns 0 for success and -1 for failure, rather than the number of bytes read (which is what EthernetClient does)

However, trying to amend the WiFiClient code to return the number of bytes also didn't fix the issue.  I haven't had chance to dig into it further yet.

**Comment by sandeepmistry** [comment]
This look good now, ```WiFiClient::read``` returns the number of bytes read. Also, there have been no follow ups since 2012-09-03 so closing.
