### ISSUE TITLE
Arduino IDE 1.8.12 crashing on MacOS when window moved to non-primary monitor

### ISSUE THREAD

**Issue by makermelissa** [arduino/Arduino#10302]
This happens very consistently and I am able to reproduce on my laptop. I start the IDE which loads on my primary external monitor. As soon as I drag the window to the non-primary monitor (the built-in display), the IDE crashes.

**Comment by facchinm** [comment]
Closing as duplicate of #9828 , we are about to release a version of the IDE which fixes this issue

**Comment by makermelissa** [comment]
Ok, thanks. I didn't see that it included this issue with a quick search.
