### ISSUE TITLE
Nano pinout diagram does not match hardware

### ISSUE THREAD

**Issue by ogni4247** [arduino/Arduino#10308]
The pinout diagram [https://content.arduino.cc/assets/Pinout-NANO_latest.png] and related schematic pdf is not showing the connection of PD0 and PD1 properly. 

The connection goes from Pin  31(Port D1) to D0/TX and from Pin 32 (Port D0) to D1/RX. The board file from eagle (NanoV3.3.brd) shows this as well. Unfortunately, the Schematic cannot be opened with the current version of eagle (9.6.2) and reports an error in line 177 columns 25

**Comment by FunzioneFabio** [comment]
Hello @ogni4247 Sorry for the late response, thank you so much for reporting this! You are right, now the pinout are corrected and uploaded to the website.
https://content.arduino.cc/assets/Pinout-NANO_latest.pdf
