### ISSUE TITLE
Programming Arduino due, buzzer on 

### ISSUE THREAD

**Issue by Dysp1** [arduino/Arduino#10303]
I have arduino due with buzzer connect to pin 53.  The buzzer is always on when uploading the sketch (which takes about 45 seconds).  It's a very loud and high pitched voice to listen over and over again when testing and uploading constantly.  The due is part of a bigger project connected to "motherboard" which among others connects the buzzer to the due pin.  Is my only option to change schematics and add a jumper or switch to turn the buzzer off when it's not needed?  Can't the uploader control the pins before/during upload to be down?

I'm using the AVRISP mkII programmer and Due programming port from Ubuntu 18.04.4 LTS.

**Comment by charlesbones** [comment]
It seems like you are having a similar issue as the one described in this forum thread (https://forum.arduino.cc/index.php?topic=391729.0) 

Probably giving a try to use a pull_up resistor in the output might help.
