### ISSUE TITLE
Flat out cant scroll through code in arduino ide

### ISSUE THREAD

**Issue by jmb-555** [arduino/Arduino#10321]
I have done many Arduino projects and this has never been an issue. Two finger scroll fails to work. After rebooting the issue had gone away only to immediately reappear. One time after rebooting, the ability to two finger scroll was working but was unusably sensitive. It scrolled to the bottom of the page immediately. It currently just wont let me scroll at all. 

Update:
Upon further investigation this issue is present in any IDE that I try to use and NO other programs on my computer whatso ever. Browser scrolls fine. Notepad scrolls fine. Everything scrolls fine. Today I tried to do some python work and noticed the same problems with pythons IDLE ide. I downloaded  Pycharm and it worked wonderfully for about 10minutes and then all of the sudden the ability to use the scrollbar completely went away.

**Comment by Avamander** [comment]
This is most likely something wrong with your touchpad's drivers or configuration. Arduino IDE isn't the cause or only thing affected here.

**Comment by jmb-555** [comment]
Forget about it. Is fine. Just checked and its working. Like the other 10
programs I use, any problems that i have seem to just magically disappear
as soon as i write something about it on the website.
