### ISSUE TITLE
MAX6626 Library Release v1.0.2

### ISSUE THREAD

**Issue by TamojitSaha** [arduino/Arduino#10324]
I have made an updated version release of the MAX6626 library. I changed the version in `library.properties` but did not see any change in the arduino library manager.
The link to the release is [here](https://github.com/TamojitSaha/MAX6626/releases/tag/v1.0.2)

**Comment by cmaglie** [comment]
The reason it that you didn't update library.properites:

https://github.com/TamojitSaha/MAX6626/blob/v1.0.2/library.properties#L2

to fix this:

1. update version in library properties to 1.0.2
2. commit & push
3. remove tag 1.0.2
4. re-do the tag 1.0.2 on master

after doing the above, the library should be automatically published as usual.
