### ISSUE TITLE
[Library manager] rename "Adafruit ICM20649" to "Adafruit ICM20X"

### ISSUE THREAD

**Issue by siddacious** [arduino/Arduino#10334]
We've bumped this to 2.0.0 and renamed the library from "Adafruit ICM20649" to "Adafruit ICM20X"

https://github.com/adafruit/Adafruit_ICM20X
https://github.com/adafruit/Adafruit_ICM20X/blob/master/library.properties

Please update the name in the library manager.

Thank you :)

**Comment by cmaglie** [comment]
Done.

@siddacious remember to update the dependencies on "Adafruit Sensor Lab" library, that has a dependency on "Adafruit ICM20649".
