### ISSUE TITLE
RFM69 struct_receive example Arduino Uno SS_FLASHMEM not declared in scope

### ISSUE THREAD

**Issue by Erwin-66** [arduino/Arduino#10348]
RFM69 struct_receive example sketch cannot compile due to error SS_FLASHMEM was not declared in this scope. It seems to fail at line: SPIFlash flash(SS_FLASHMEM, 0xEF30); //EF40 for 16mbit windbond chip

What to fill in their for Arduino Uno

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests for official Arduino software (not for 3rd party libraries). This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
