### ISSUE TITLE
Arduino Due pinout diagram on the website is wrong.

### ISSUE THREAD

**Issue by gitpicard** [arduino/Arduino#10346]
The pinout pdf [here](https://content.arduino.cc/assets/Pinout-Due_latest.pdf) is incorrect. According to the Arduino Due Eagle files, the pins are flipped. The first pin should be on the other side. This matches with the physical board which has the white dot on the other side of where the pinout says the first pin should be. The PDF will probably need an update.

**Comment by per1234** [comment]
Hi @gitpicard thanks so much for reporting this! It's not clear to me what you mean by "first pin". I see a few issues with that document that could be considered related to a "first pin":

- The numbering of the pinout's SPI header is the mirror image of the real SPI header.
- The numbering of the pinout's "debug" header is backwards.
- The cut corner of the ATSAM3X8E on the pinout, which I would expect to indicate pin 1 (as it does on the Arduino Mega's pinout), is actually diagonally opposite from the the ATSAM3X8E's pin 1.

Did you mean one of those issues, or is there yet another problem with the pinout that I didn't spot?

**Comment by gitpicard** [comment]
Yes, the first one. I believe that the pinout's SPI header is a mirror of the real SPI header. The little white dot on the physical board is on the other side of where it would be if the pinout was correct.

**Comment by kjordan3ds** [comment]
I agree with this as the Eagle files and the silkscreen clearly show pin one to be the upper right based on the pdf layout.
This was a fun issue to discover when trying to connect an SPI device and the system ass held in reset.

Any update on when the online document will be corrected?

**Comment by per1234** [comment]
Maybe @FunzioneFabio could help us out with this?

**Comment by FunzioneFabio** [comment]
Thank you @gitpicard for reporting this! Now the pinout is corrected and updated on the website, also with the other corrections from @per1234

**Comment by FunzioneFabio** [comment]
https://content.arduino.cc/assets/Pinout-Due_latest.pdf

**Comment by tttapa** [comment]
I believe there are still some mistakes in the pinout diagram, as well as in the technical specifications listed on the product page.  
There's some discussion going on in this thread on the forum: https://forum.arduino.cc/index.php?topic=695235

The "tech specs" section on the Arduino Due product page (https://store.arduino.cc/arduino-due) claims that the Due has 16 analog input pins, which is not the case. Only 12 analog pins are usable with the ArduinoCore-SAM's `analogRead` function, and the SAM3X only has 15 analog input pins (the 16th ADC channel is connected to an internal temperature sensor).  

The pinout diagrams linked to in the previous comment and the one on the product page also get the ADC pins wrong, it incorrectly labels the DAC and CAN pins as ADC[12] - ADC[15].  
From what I can gather from the datasheet, the actual ADC pins are:
| ADC channel | GPIO port | Digital Arduino pin |
|---|---|---|
| AD8 | PB12 | 20 |
| AD9 | PB13 | 21 |
| AD14 | PB21 | 52 |

AD8 and AD9 share pins with the I²C interface, so they have 1.5kΩ pull-up resistors, which is not ideal for an ADC input.

To support these three extra ADC pins, the following files in the Arduino SAM Core would have to be fixed:
- https://github.com/arduino/ArduinoCore-sam/blob/eed66e7977b4037f49bbcd832437d4bcf72c0f3f/cores/arduino/wiring_analog.c#L133
- https://github.com/arduino/ArduinoCore-sam/blob/c893c62ec9953ed36a256b5243272fda2e473c14/variants/arduino_due_x/variant.cpp#L160

I don't own a Due myself, so I cannot test it.

For now, I think the most important steps are updating the incorrect number of analog inputs on the product page (16→12), and fixing the pinout diagram. If someone who has access to an Arduino Due can test the three extra ADC pins above, maybe they could be added to the Core, so 15 analog inputs can be advertised on the product page.

**Comment by FunzioneFabio** [comment]
Hello @tttapa Thank you so much for reporting this! I have corrected and uploaded the pinout scheme to the website:
https://content.arduino.cc/assets/Pinout-Due_latest.pdf

@kengdahl Can you take care of the "tech specs" section?

**Comment by tttapa** [comment]
Thanks! 

I noticed there are still some "Analog Pin" labels for pins A12-A15 (on the first three pages, the DAC and CAN pins). I think this is confusing since they are not analog inputs, and they are not available as constants in the Arduino IDE (only A0-A11 are defined: https://github.com/arduino/ArduinoCore-sam/blob/c893c62ec9953ed36a256b5243272fda2e473c14/variants/arduino_due_x/variant.h#L182).

Also a suggestion for the product page: This is the first time I noticed your full pinout PDF, I never noticed the "Download the full pinout diagram as PDF here" below the simple pinout diagram.  
I think the full pinout diagram is really valuable, so maybe a larger download button (like the ones for downloading the schematics) would be a good idea?

**Comment by FunzioneFabio** [comment]
Hello again! Thanks for the correction and for the feedback, we are working for improving the general store experience and this aspect will certainly been improved.
The pinout is now corrected and uploaded!
https://content.arduino.cc/assets/Pinout-Due_latest.pdf

**Comment by tttapa** [comment]
Looks good, thanks a lot!

**Comment by kengdahl** [comment]
Are we all good now?

**Comment by FunzioneFabio** [comment]
Yes! The pinout is corrected ;)

**Comment by kengdahl** [comment]
And it looks like the "Tech specs" are correct also.
