### ISSUE TITLE
macOS 10.11.6 Arduino app stops launching at "Initializing packages..."

### ISSUE THREAD

**Issue by systembolaget** [arduino/Arduino#10344]
Yesterday evening everything worked as it did for years. This morning, without a macOS update or installing other software, the Arduino app (13.02.2020) stops launching at "Initializing packages..." and the splash-screen self-closes.

What is this and what should one do?

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/10332.

Please see https://github.com/arduino/Arduino/issues/10332#issuecomment-641830310 for an explanation of the problem and the fix.
