### ISSUE TITLE
[Library Manager] Please Add Library

### ISSUE THREAD

**Issue by IGB-Germany** [arduino/Arduino#10343]
please add this library: 
https://github.com/IGB-Germany/IGB-FlashSst26.git

Thank You !

**Comment by AVRManuelG** [comment]
Hello everyone!!
I downloaded IGB-FlashSst26-master and opened its bookcase 

But I can't open Arduino Ide yet.

I uninstalled the ArduinoIde and reinstalled it and deleted Arduino15 and I can't open anything

Thank you very much and a greeting

**Comment by cmaglie** [comment]
Done.
