### ISSUE TITLE
IDE 1.01 dies upon launch. No messages are displayed. (Windows XP, SP3) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1035]
This is [Issue 1035](http://code.google.com/p/arduino/issues/detail?id=1035) moved from a Google Code project.
Added by 2012-09-05T22:23:30.000Z by [cappy2...@gmail.com](http://code.google.com/u/105159837660030726516/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Launch IDE 1.01 on Windows XP, SP3 32-Bit.
 The IDE dies silently. No messages are displayed
(The Arduino IDE 0.23 works fine.)

>>What is the expected output? What do you see instead?
I expect the IDE to be displayed. Nothing is displayed.

>>What version of the Arduino software are you using? 
1.01

>>On what operating system?
XP, SP3, 32-bit

>>Which Arduino board are you using?
Uno Rev 3

>>Please provide any additional information below.
Is there a way to capture a logfile of this issue?
If so, please tell me how so that I can submit it.

Are others seeing this issue?

The Arduino IDE 0.23 works fine.

**Comment by ffissore** [comment]
OP could hardly reproduce the issue and spot the bug that affected him/her back in 2012. Today we have `arduino_debug.exe` which prints error message on command prompt
