### ISSUE TITLE
[Library Manager] Please add histogram library

### ISSUE THREAD

**Issue by RobTillaart** [arduino/Arduino#10359]
Please add https://github.com/RobTillaart/Histogram
Thanks, 
Rob

**Comment by per1234** [comment]
Hi @RobTillaart. The library is missing the required library.properties file. Although I don't know that it's required by the Library Manager indexer, it's also missing the .h file that would make it a valid library.

Please add the required files, then either create a new release or redo the existing release. After that, comment here to let us know we can proceed. Thanks!

**Comment by RobTillaart** [comment]
Oops my mistake, added the missing files and released library again
Sorry for the inconvenience

**Comment by cmaglie** [comment]
Done.
