### ISSUE TITLE
[Library Manager] Please add ESPpassthrough library

### ISSUE THREAD

**Issue by Saruccio** [arduino/Arduino#10360]
Please add https://github.com/Saruccio/ESPpassthrough
Thanks,
Saruccio

**Comment by per1234** [comment]
Hi @Saruccio. Although your repository is currently compliant with the requirements for addition to the Arduino Library Manager index, it was not at the time of the last tag/release. Please either create a new tag/release or else redo the existing on. After that, comment here so we'll know we can proceed. Thanks!

**Comment by Saruccio** [comment]
Hi @per1234  I made a new release (v1.1) aligned to the master branch.
Thanks

**Comment by cmaglie** [comment]
Done.
