### ISSUE TITLE
Add a new library to control the KT0915 device from KTMicro

### ISSUE THREAD

**Issue by pu2clr** [arduino/Arduino#10366]
Please add the KT0915 library into your library manager.
Link to the repository: [PU2CLR KT0915 Arduino Library](https://github.com/pu2clr/KT0915)

This is an Arduino Library to control the KT0915 DSP device receiver from KTMicro. The KT0915 is an integrated circuit that provides full band receiver on FM and AM (MW/SW/LW).

Github: https://github.com/pu2clr/KT0915

**Comment by cmaglie** [comment]
Done.
