### ISSUE TITLE
New library request (https://github.com/signetica/MoonRise)

### ISSUE THREAD

**Issue by signetica** [arduino/Arduino#10364]
Please add the following library to the library manager:

- [x] https://github.com/signetica/SunRise
- [x] https://github.com/signetica/MoonRise

Thanks.

Addendum:
It probably makes sense to add the other libraries in this set to this request:
https://github.com/signetica/MoonPhase
https://github.com/signetica/SunRise

**Comment by cmaglie** [comment]
Done.
