### ISSUE TITLE
[Library Manager] Please add HMC6352 compass library

### ISSUE THREAD

**Issue by RobTillaart** [arduino/Arduino#10361]
Please add https://github.com/RobTillaart/HMC6352
(did double check)
Thanks,
Rob

**Comment by cmaglie** [comment]
Hi @RobTillaart 
I've added the library to the index but there is a problem, the `depends` field is set to `*`:

https://github.com/RobTillaart/HMC6352/blob/master/library.properties#L11

```
JOB 3082 - 2020/06/13 15:51:52 Scraping https://github.com/RobTillaart/HMC6352.git
JOB 3082 - 2020/06/13 15:51:54 Checking out tag: 0.2.0
JOB 3082 - 2020/06/13 15:51:54 Error syncing library: Error generating library from repo: Invalid 'depends' field: *
```

To fix this:

1. remove `depends` field from library.properties or set it to a correct value.
2. commit & push
3. delete and re-do the git tag.

once done the library will be automatically published within an hour.
