### ISSUE TITLE
[Library Manager] Please add the SparkFun_Qwiic_Power_Switch_Arduino_Library

### ISSUE THREAD

**Issue by PaulZC** [arduino/Arduino#10383]
Hi,
Can you please add the SparkFun_Qwiic_Power_Switch_Arduino_Library to the library manger?
https://github.com/sparkfun/SparkFun_Qwiic_Power_Switch_Arduino_Library
Sincere thanks - as always!
Paul

**Comment by cmaglie** [comment]
Done.
