### ISSUE TITLE
[Library manager] Please add "CSV Parser"

### ISSUE THREAD

**Issue by michalmonday** [arduino/Arduino#10388]
Hi, it would be great if you added the library I wrote: 
https://github.com/michalmonday/CSV-Parser-for-Arduino

I hope the name of the library stated in "library.properties" file doesn't have to match the name of github repository, but please let me know if that's the case. 

I tried to follow the API style guide, but didn't manage to avoid using pointers, I hope the examples provided are straighforward enough to use the library even if someone is not familiar with pointers.

**Comment by cmaglie** [comment]
Done.
