### ISSUE TITLE
[Library Manager] Please add N64Controller library.

### ISSUE THREAD

**Issue by pothos** [arduino/Arduino#10396]
Hello,
please add the N64Controller library in the Library Manager. It allows to connect multiple Nintendo 64 controllers to an Arduino board (tested with UNO). Multiple people have used since I published it but it was always a bit hard to find.

Library Name: `N64Controller`
Git repository URL: https://github.com/pothos/arduino-n64-controller-library

I hope it is ok that the repository name is more descriptive but if needed I will rename the GitHub repository to N64Controller.

Thanks a lot, it's really nice to have a library finder now in the IDE!

**Comment by cmaglie** [comment]
Done.
