### ISSUE TITLE
[Library Manager] Please add the EASE_ArduinoCode Library

### ISSUE THREAD

**Issue by esmacat-hb** [arduino/Arduino#10404]
Please add the EASE_ArduinoCode Library : https://bitbucket.org/harmonicbionics/ease_arduinocode

Thanks,
Esmacat

**Comment by per1234** [comment]
Hi @esmacat-hb. You need to create a [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by esmacat-hb** [comment]
Hi @per1234. A tag with the appropriate version number has been added to the repository. 

Thanks,
Esmacat.

**Comment by cmaglie** [comment]
Done.

**Comment by esmacat-hb** [comment]
Hello! We made an update to our Arduino library (v0.3.0). Please add the update to the library manager whenever possible.

Thanks,
Esmacat
