### ISSUE TITLE
"Arduino is damaged and should be moved to the trash" says OSX 10.8 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1041]
This is [Issue 1041](http://code.google.com/p/arduino/issues/detail?id=1041) moved from a Google Code project.
Added by 2012-09-10T15:28:15.000Z by [tom.i...@gmail.com](http://code.google.com/u/102867599453860860098/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-High

### Original description

**What steps will reproduce the problem?**

I had a report from a reliable fellow teacher on this. HE can't run 1.0.1 under OSX 10.8 because, after download, he gets the above message. 

I have not tried to duplicate it on my own machine, as 1.0.1 is working under Mountain Lion, and I need it to keep working. However, I had the exact same thing happen to me with Processing 2.0b2 today. So I assume the problem is similar, if not the same.

1. Download 2.0b2 on OSX 10.8, unzip
2. Copy to Applications directory
3. open Processing

**What is the expected output? What do you see instead?**

Instead of seeing Processing run, I get an OS dialog saying "Processing is damaged and should be moved to the trash." This is the exact same message that Brian Jones (aforementioned teacher) reported to me when he downloaded Arduino 1.0.1 onto OSX 10.8. I already had 1.0.1 running on my machine before I upgraded to 10.8, so I suspect something in the package permissions.  The old hack of opening in 23-bit mode did not help on either Processing or Arduino.

However, Processing 2.0b1 seems to run fine. Brian has not found a similar solution on Arduino.

What version of the product are you using? On what operating system?

Processing 2.0b2 and OSX 10.8. 2.0b1 seemed to run fine.

Please provide any additional information below.

Note: Please do not link to locations on other sites, such as your own
image site, video site, blog, etc. Include the relevant information here
with the report.

**Comment by ffissore** [comment]
OP could hardly reproduce the issue and spot the bug that affected him/her back in 2012
