### ISSUE TITLE
ATMEGA328P running at internal 8MHz

### ISSUE THREAD

**Issue by PixelTamer** [arduino/Arduino#10419]
I would like to see a boot-loader and a programming configuration specifically designed to use the ATMEGA328P with the internal 8MHz oscillator. The compiler would also have to be aware of the speed difference.  The idea would to have a board selection like "Arduino Nano (internal 8MHz)" 
This would allow using the additional pins for I/O or using a very low frequency crystal, or a custom clock output. It would allow free standing projects (home brew boards) a little more freedom.
 The current method of forcing in an external 8MHz bootloader seems to dominate the IDE and prevents selecting anything else when developing a standard project unless it is unloaded. Also the warnings are cryptic and misleading.
Thanks,
Pixel

**Comment by per1234** [comment]
The excellent 3rd party boards platform MiniCore already provides what you are requesting:
https://github.com/MCUdude/MiniCore#supported-clock-frequencies
