### ISSUE TITLE
I2C Master Reader / Slave Write code in the documentation

### ISSUE THREAD

**Issue by yasirsenator** [arduino/Arduino#10434]
In this page:
https://www.arduino.cc/en/Tutorial/MasterReader

The code attached is for the Slave Read instead of Slave Write.
Needs update!

Cheers

**Comment by per1234** [comment]
Hi @yasirsenator. Thanks for taking the time to report this error. We already have a report of this (https://github.com/arduino/Arduino/issues/9740), so I'll close it as a duplicate.
