### ISSUE TITLE
can't find my arduino board.  

### ISSUE THREAD

**Issue by Castiel73** [arduino/Arduino#10443]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
I been working with creation crate projects.  I am using windows 10.  every time I plug in my board it doesn't see it.  I made my first program and went to sketch it(compile) it doesn't see the board.   How do I fix this?

**Comment by per1234** [comment]
Hi @Castiel73. I'm sorry to hear you're having trouble with your Arduino clone. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post a detailed description of what you mean by "it doesn't see the board".
