### ISSUE TITLE
Integer print in TFT library 

### ISSUE THREAD

**Issue by siinnaaww** [arduino/Arduino#10454]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

**Comment by siinnaaww** [comment]
I don't know how to print integer on ILI9225, I am using the Arduino TFT library. 
I would appreciate it if anyone could help me.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
