### ISSUE TITLE
[Library Manager] Please add ESP_AT_Lib Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10452]
Please add [ESP_AT_Lib](https://github.com/khoih-prog/ESP_AT_Lib) to Library Manager. Thanks.

This is an ESP8266/ESP32 wrapper library for Arduino providing an easy-to-use way to manipulate ESP8266/ESP32-AT shields.

This library is based on, modified and improved from [ITEADLIB_Arduino_WeeESP8266](https://github.com/itead/ITEADLIB_Arduino_WeeESP8266)

---

### Releases v1.0.0

1. Add support to ***nRF52 (AdaFruit Feather nRF52832, nRF52840 Express, BlueFruit Sense, Itsy-Bitsy nRF52840 Express, Metro nRF52840 Express, NINA_B30_ublox, NINA_B112_ublox, etc.)***.
2. Add support to ***Adafruit SAMD21/SAM51 (Itsy-Bitsy M0/M4, Metro M0/M4, Grand Central M4, Feather M0/M4 Express, etc.)***.
3. Add support to ***STM32F, Teensy, SAM DUE***.
4. Add support to **ESP32-AT shields**.
5. Add debug AT command output

**Comment by cmaglie** [comment]
Done.
