### ISSUE TITLE
ARDUINO IDE PORTS ON WINDOWS 10

### ISSUE THREAD

**Issue by zeev1** [arduino/Arduino#10453]
The PORTS options do not appear in Arduino Uno tools when using Windows 10 PC computer. I was expecting to see COM1 or higher. I loaded Arduino IDE on Windows XP computer without an issue. 
![Arduino Port Problem](https://user-images.githubusercontent.com/67684336/86225674-3ca11e00-bb93-11ea-8208-8aa122b4c733.png).
I am using the computer ideacentre AIO 720-241KB

**Comment by dotto59** [comment]
First of all, what release of Arduino IDE you're using? I use Arduino IDE 1.8.12 on regular basis under Win 10 without any problem. I hope you didn't install the IDE from Windows Store, as some people had serious problems with that. And are you using the "installer" or "portable" (zip) version?
Anyway it seems to me you have a problem with the USB-Serial device driver. Check the installation (or try to uninstall then re-install it verifying it "dings" when connecting a board, and then the port is visible under Device manager (so I think it'll be visible on you IDE too..).

**Comment by per1234** [comment]
Closing due to lack of response.

@zeev1 if you'll provide the requested information I'll be happy to re-open this issue.
