### ISSUE TITLE
[Library Manager] Please add Botly-library

### ISSUE THREAD

**Issue by JulesTopart** [arduino/Arduino#10478]
Please add the Botly library to the library manager:
https://github.com/Botly-Studio/Botly-Library
This library allows controlling botly robot (open source pedagogical robot).

Look how cute he his : 

![img](http://www.botly-studio.fr/images/botly.jpg)

We want to simplify access to the lib, wich is claimed by our users
Thank's for your time and for your help!

**Comment by cmaglie** [comment]
Done.
