### ISSUE TITLE
Hangup *** [upload] Error 129 with platformIO

### ISSUE THREAD

**Issue by fishercat503** [arduino/Arduino#10479]
Whenever I try to upload to my teensy the teensyduino app pops op but the code doesn't seem to run. I have the 49-teensy rules installed. It seems a linux error 128 is a refused key. This is the tail of the terminal output;

`configuring upload protocol...
AVAILABLE: jlink, teensy-gui
CURRENT: upload_protocol = teensy-gui
Uploading .pio/build/teensy41/firmware.hex
Hangup
*** [upload] Error 129`

**Comment by cmaglie** [comment]
This is not the issue tracker for Teensy boards, I guess you will find more help here: https://forum.pjrc.com/
(cc @PaulStoffregen)
