### ISSUE TITLE
problem with project # 12 knockLock in Arduino project book

### ISSUE THREAD

**Issue by GabrielM2004** [arduino/Arduino#10484]
Hello, I am very new to programming and I have ran into an issue with the knock Lock. After checking the program before downloading it, the message "checkforKnock was not declared in this scope" pops up. I have verified multiple times that I have not made any typing errors and I cannot seem to comprehend why this message keeps showing up, as I had a similar problem in another project from the book. 
here is the code:
#include <Servo.h>
Servo myServo;
const int piezo = A0;
const int switchPin = 2;
const int yellowLed = 3;
const int greenLed = 4;
const int redLed = 5;
int knockVal;
int switchVal;
const int quietKnock = 10;
const int loudKnock = 100;
boolean locked = false;
int numberofKnocks = 0;
void setup() {
  // put your setup code here, to run once:
myServo.attach(9);
pinMode(yellowLed, OUTPUT);
pinMode(redLed, OUTPUT);
pinMode(greenLed, OUTPUT);
pinMode(switchPin, INPUT);
Serial.begin(9600);
digitalWrite(greenLed, HIGH);
myServo.write(0);
Serial.println("la porte est ouverte");

}

void loop() {

  // put your main code here, to run repeatedly:
if(locked == false){
  switchVal = digitalRead(switchPin);
if(switchVal == HIGH){
  locked = true;
  digitalWrite(greenLed, LOW);
  digitalWrite(redLed, HIGH);
  myServo.write(90);
  Serial.print("the box is locked");
  delay(1000);
  
}
}

if(locked == true){
  knockVal = analogRead(piezo);
  if(numberofKnocks < 3 && knockVal > 0 ){
    if(checkforKnock (knockVal) == true) {
      numberofKnocks ++;
      
    }
    Serial.print(3-numberofKnocks);
    Serial.println("coups restants");
   
  }
  if(numberofKnocks >= 3){
    locked = false;
    myServo.write(0);
    delay(20);
    digitalWrite(greenLed, HIGH);
    digitalWrite(redLed, LOW);
   Serial.println("la boite est débarrée")
   numberofKnocks = 0;
  }
}
}

boolean checkforKnock(int value);
if(value>quietKnock && value<loudKnock){
  digitalWrite(yellowLed, HIGH);
  delay(50);
  digitalWrite(yellowLed, LOW);
  Serial.print("valid Knock of value");
  Serial.println(value);
  
  return true;
  
}

else{
  Serial.print("bad Knock value");
  Serial.println(value);
  return false;
  }
}

I would greatly appreciate any help. 
Thank you.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
