### ISSUE TITLE
[Library Manager] Please add Lego Sensor Adapter library 

### ISSUE THREAD

**Issue by StanislavJochman** [arduino/Arduino#10498]
Source: https://github.com/StanislavJochman/LegoSensorAdapter/
Tag: https://github.com/StanislavJochman/LegoSensorAdapter/releases/tag/1.0.0

Please Lego Sensor Adapter.
Main features:
Reading values from lego EV3 sensors using Arduino.

Best regards
Stanislav Jochman

**Comment by cmaglie** [comment]
Done.
