### ISSUE TITLE
arduino rev 3

### ISSUE THREAD

**Issue by TheNitrogue** [arduino/Arduino#10497]
there is no option for arduino rev 3 in the board selection option in the online editor.
Can i get some help please?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
