### ISSUE TITLE
[Library Manager] Add ULWOS2 library

### ISSUE THREAD

**Issue by fabiopjve** [arduino/Arduino#10499]
Source: https://github.com/fabiopjve/ULWOS2
Tag: https://github.com/fabiopjve/ULWOS2/releases/tag/v0.9.0

Description: ULWOS2 is a super lightweight cooperative thread scheduler written 100% in C, that can run on multiple platforms. It doesn't use a separate stack for each thread and each new thread consumes only 14 bytes of RAM (plus any local variable created within the thread).

**Comment by cmaglie** [comment]
Done.
