### ISSUE TITLE
[Library manager] EMailSender library (Arduino, esp32 and esp8266 with attachments features) 

### ISSUE THREAD

**Issue by xreef** [arduino/Arduino#10505]
Source: https://github.com/xreef/EMailSender
Tag: https://github.com/xreef/EMailSender/releases/tag/v2.0.1

Some peoples ask to me do an update manager for this library, but I think the only system to manage the library via Library Manager is to add here the request.

EMailSender library with support for 

- Arduino (w5100, enc28j60 and SD for attachments)
- esp8266 (SPIFFS and SD for attachments)
- esp32 (SPIFFS and SD for attachments)

Documentation
ENG --> https://www.mischianti.org/category/my-libraries/emailsender-send-email-with-attachments/
ITA --> https://www.mischianti.org/it/category/le-mie-librerie/emailsender-inviare-email-con-allegati/

Bye Renzo

**Comment by cmaglie** [comment]
Done.
