### ISSUE TITLE
Mipi camera record video

### ISSUE THREAD

**Issue by PaulderGraph** [arduino/Arduino#10500]
I would like to record a mipi video, wich is 4k resolution. How can I record it? Which microcontroller do I need?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. You'll be sure to get an answer to your question over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.

**Comment by PaulStoffregen** [comment]
I do not believe any microcontroller on the market today is up to this task.  You probably need a single board computer like nVidia Jetson.  Google search can help you find those products and their forums to ask for help.
