### ISSUE TITLE
Mojave 10.14.6 Arduino port not detected

### ISSUE THREAD

**Issue by paris007** [arduino/Arduino#10507]
I have a MacBook Pro (Retina, 13-inch, Early 2015) running Mojave 10.14.6 . I need to upload code on nRF52840 Express using my Arduino IDE. The OS does not recognize the USB serial ports.

**Comment by per1234** [comment]
Since it's surely the same cause in all cases, I'm going to close this in favor of a single issue report: https://github.com/arduino/Arduino/issues/10508
