### ISSUE TITLE
[Library manager] Remove 1.0 version of Grandeur Cloud Library

### ISSUE THREAD

**Issue by abdullahmahboob** [arduino/Arduino#10518]
When I requested to add the Grandeur Cloud library to Library Manager, I mistakenly added the wrong version number (1.0.0) in library.properties file, even though it was correct (0.1.0) on Github. Now I resolved some bugs in the library and released its 0.1.2 version after correcting the version in library.properties as well. Is there a way I or you guys can remove the previous version aka. 1.0 from the library manager? It is misleading the users because they think 1.0 is the latest version which it is not.

Library URL:
https://github.com/grandeurtech/grandeurcloud-arduino-sdk

Thanks in advance.

**Comment by per1234** [comment]
We can do that, but first you need to delete the [`0.1.0-beta`](https://github.com/grandeurtech/grandeurcloud-arduino-sdk/releases/tag/0.1.0-beta), [`0.1.0`](https://github.com/grandeurtech/grandeurcloud-arduino-sdk/releases/tag/0.1.0), and [`0.1.1`](https://github.com/grandeurtech/grandeurcloud-arduino-sdk/releases/tag/0.1.1) tags (all of which use the incorrect "1.0.0" `version` value in library.properties.

You can do this by going to each of the links in the previous sentence and clicking the "Delete" button.

**Comment by abdullahmahboob** [comment]
Deleted all faulty releases.

**Comment by cmaglie** [comment]
Done.
