### ISSUE TITLE
[Library manager] Request to rename Things IoT to ThingsIoT

### ISSUE THREAD

**Issue by SiddheshNan** [arduino/Arduino#10514]
Hi,
I'm renaming my library from `Things IoT` to `ThingsIoT` (whitespace removed) due to name issue.
Could you please remove my `Things IoT` library from the library manager and add the `ThingsIoT` library instead? 

Repo is here: https://github.com/SiddheshNan/Things-IoT-Arduino-Library
Most recent tag with changed name is here: https://github.com/SiddheshNan/Things-IoT-Arduino-Library/releases/tag/1.2.0

Thanks in advance!

**Comment by cmaglie** [comment]
Done.
