### ISSUE TITLE
How can I do ?

### ISSUE THREAD

**Issue by yiitmustafikarslik** [arduino/Arduino#10512]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

**Comment by yiitmustafikarslik** [comment]
sorry for this how can ı do black screen in arduino IDE
???

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to answer your question over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
