### ISSUE TITLE
USB HID Add support for Caps Lock, Num Lock, Scroll Lock LED status.

### ISSUE THREAD

**Issue by ScaredyCat** [arduino/Arduino#10528]
Support for LED status is missing from the USB HID/Keyboard libraries. This would allow keyboards made using the Arduino platform to react to the status of those LEDs.

Some users have supplied patches and/or downloads to 'fix' this but it would be better to have support in those libraries from the source - as it were. 

Example code modifications: https://forum.arduino.cc/index.php?topic=173583.msg3447862#msg3447862 Also attached 

here:

[USBHID_LedStatus.zip](https://github.com/arduino/Arduino/files/4949367/USBHID_LedStatus.zip)

Based on version 1.8.4 of the editor.

**Comment by facchinm** [comment]
Hi @ScaredyCat ,
can you open a proper pull request on https://github.com/arduino-libraries/Keyboard ? I'm closing this one in the meantime. Thanks!
