### ISSUE TITLE
Web site - motor control errors

### ISSUE THREAD

**Issue by MalcolmBoura** [arduino/Arduino#10530]
https://www.arduino.cc/en/Tutorial/TransistorMotorControl

The article talks about the leads of a junction transistor (base, emitter, collector) but the diagram shows a FET. The TIP120 is actually a darlington pair of junction transistors.

The fundamental process in an electric motor is the motor effect. Induction is a secondary effect which although important is not the thing that makes it turn.

Putting an electric charge through a wire is correct but referring to current is a much clearer way of expressing the concept.

Quote "When a motor stops, there is the potential for a small amount of current to be generated as the shaft continues spinning".   Incorrect. An emf is generated, not current, and the emf from spinning is relatively small, typically a bit less than the supply voltage, and could not damage the TIP120 which is rated for 60V. However the wound components can easily produce back emfs large enough to destroy electronic components. A better approach would be a paragraph on back emfs from wound magnetic components such as motors and relay coils. That makes the article more general and it would be correct.

The diagram would be a lot clearer if it had +9V at the top, 0V at the bottom and the battery vertically between the two. Also, it is a battery (6 cells in series in this case) but the symbol used in the diagram is that of a cell.

I hope that that is helpful. Feel free to contact me if need be.

**Comment by per1234** [comment]
Hi @MalcolmBoura. Thanks for your detailed report.

It seems the article has been deleted at some point since your report. Seeing as it is no longer possible to correct the information, I'll go ahead and close this.

If anyone comes across this information somewhere on the arduino.cc website, please comment here iwth the link and I'll reopen.
