### ISSUE TITLE
Mac hotkeys with non-US keyboards are executed twice, causing paste (and others) to be executed multiple times

### ISSUE THREAD

**Issue by zaneclaes** [arduino/Arduino#10534]
This was also reported [on the forums](https://forum.arduino.cc/index.php?topic=315092.0), but I cannot find an open issue. I use a DVORAK keyboard, and any attempts to paste on Mac cause the text to be pasted twice. Likewise, other hotkeys also trigger duplicate actions. My keyboard even has dedicated copy/cut/paste buttons, which also suffer from this bug.

It may or may not also be related to retina displays (no way of checking).

**Comment by per1234** [comment]
Hi @zaneclaes. Thanks for taking the time to report this bug.

We already have a prior issue report about this at https://github.com/arduino/Arduino/issues/7061.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
If you end up with additional information to share, feel free to comment in the other thread.
