### ISSUE TITLE
FINGERPRINT DOORLOCK

### ISSUE THREAD

**Issue by randy0011x** [arduino/Arduino#10546]
Hello, I am trying to learn how fingerprint doorlock are being designed and developed. I refered a source and tried to implement it practically. I am using ARDUINO UNO R3. My connections are perfect and all other devices and drivers are working normally. When I conncect my fingerprint sensor that is wired with arduino, it says "Did not find fingerprint sensor :(". Please help me with this issue and guide me how to do it properly.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
