### ISSUE TITLE
Wrong controller name in Arduino Due pinout document

### ISSUE THREAD

**Issue by rejoystom** [arduino/Arduino#10551]
The following page: https://content.arduino.cc/assets/Pinout-Due_latest.pdf mentions the controller used on Arduino Due as [ATSAM3X**B**E](https://content.arduino.cc/assets/Pinout-Due_latest.pdf) in 8 places but it's actually [ATSAM3X**8**E](https://datasheet.lcsc.com/szlcsc/Microchip-Tech-ATSAM3X8EA-AU_C79305.pdf).

**Comment by VikasRathore162** [comment]
I can fix the name.

**Comment by FunzioneFabio** [comment]
Hello @rejoystom Thank you so much for the correction! The pinout is now updated on the website.
https://content.arduino.cc/assets/Pinout-Due_latest.pdf
