### ISSUE TITLE
Project 04 in the documentation/projectsbook

### ISSUE THREAD

**Issue by lukasauren** [arduino/Arduino#10550]
Hi,

I believe I have found a mistake that is mainly in the project 4 in the projectsbook for arduino. The photoresistors are going to be connected to power, but the picture showing the connections is wrong as it shows the anode connected to GND. Please check and edit for future versions of the book.

**Comment by FunzioneFabio** [comment]
Hello! Sorry for the inconvenient and thank you for reporting this. We have checked the last version of the Projects Book and the connection is correct, so in the last version of the book is updated.

**Comment by lukasauren** [comment]
Hello! 

Thank you for your reply!
Ok, this is good news then!

Best Regards
