### ISSUE TITLE
DNS library getHostByName doesn't work  [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1056]
This is [Issue 1056](http://code.google.com/p/arduino/issues/detail?id=1056) moved from a Google Code project.
Added by 2012-09-30T18:39:19.000Z by [kapo....@gmail.com](http://code.google.com/u/100327073958337776574/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Ethernet

### Original description

Hi I have a problem with the default dns library.

I found that the problem is in a check that the dns library does to control if the dns server address is not null (0.0.0.0). I commented the line and executed my code without this check and the library worked well.

The code that I executed is the file test_dns.ino attached.

Expected output (seen with my patch):
My IP address: 10.0.1.119
64.131.82.241
64.131.82.241
64.131.82.241
64.131.82.241

Real output (without patch):
My IP address: 10.0.1.119
0.0.0.0
0.0.0.0
0.0.0.0
0.0.0.0

I'm using Arduino 1.0.1 on Debian Sid with an Arduino Uno board.

I attached the patch that I used.

I know that this isn't the right way to correct this error but I'm waiting before changing more code. In fact the problem is related to the == operator of the IPAddress class but first of all I want to check if it is a common problem or not.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#16
