### ISSUE TITLE
[Library Manager] Please add LINE Simple Beacon library

### ISSUE THREAD

**Issue by ukkz** [arduino/Arduino#10562]
Hello,
Could you add my LINE Simple Beacon library?
Repository: [https://github.com/ukkz/line-simple-beacon-esp32](https://github.com/ukkz/line-simple-beacon-esp32)

This supports the ESP32 boards to create BLE beacon device for LINE app.
Thanks,
ukkz

**Comment by cmaglie** [comment]
Done.
