### ISSUE TITLE
[Library Manager] Please add SerialDraw library

### ISSUE THREAD

**Issue by JurijTSL** [arduino/Arduino#10570]
Hi,
I and @TilenS6 have created a new library for Arduino, which allows you to draw pictures onto the Client via serial.

Link to the repository:
https://github.com/TilenS6/SerialDraw-Library

And to library.properties file:
https://github.com/TilenS6/SerialDraw-Library/blob/master/library.properties

Thank you very much.

**Comment by cmaglie** [comment]
Done.
