### ISSUE TITLE
Please add MDNS_Generic Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10581]
Please add [MDNS_Generic](https://github.com/khoih-prog/MDNS_Generic) to Library Manager. Thanks.

This is an mDNS Library to support mDNS (Registering Services) and DNS-SD (Service Discovery).

This [MDNS_Generic library](https://github.com/khoih-prog/MDNS_Generic) is based on and modified from [Dario Pennisi's ArduinoMDNS Library](https://github.com/arduino-libraries/ArduinoMDNS) to provide support to many more boards, such as ***Arduino SAMD21, Adafruit SAMD21/SAMD51, Seeeduino SAMD21/SAMD51, nRF52, STM32F/L/H/G/WB/MP1, Teensy, SAM DUE, AVR Mega, etc.*** and enable those boards to use MDNS services. The currently supported module/shield is ***W5x00 using Ethernet or EthernetLarge library***. The ***WiFiNINA, ENC28J60 and LAN8742A Ethernet modules/shields are not yet supported*** as library modifications are needed.

**Comment by cmaglie** [comment]
Done.
