### ISSUE TITLE
[Library Manager] Please add HeliOS library

### ISSUE THREAD

**Issue by MannyPeterson** [arduino/Arduino#10582]
Please add the HeliOS library

Link to Library Repository
[https://github.com/MannyPeterson/HeliOS](https://github.com/MannyPeterson/HeliOS)

Link To Library Properties File
[https://github.com/MannyPeterson/HeliOS/blob/master/library.properties](https://github.com/MannyPeterson/HeliOS/blob/master/library.properties)

Thank You,

Manny

**Comment by cmaglie** [comment]
Done.
