### ISSUE TITLE
Detection of links in comments should be improved [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1058]
This is [Issue 1058](http://code.google.com/p/arduino/issues/detail?id=1058) moved from a Google Code project.
Added by 2012-10-01T17:07:07.000Z by [Philipp....@gmail.com](http://code.google.com/u/101064601307741766765/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I would like the detection of URLs in the comments to include links with hash (#) symbols.

Currently, URLs containing hash symbols are not converted to links, see the attached file.

**Comment by ffissore** [comment]
Works fine with latest hourly
