### ISSUE TITLE
Writing HEX File for "other" Programmer [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1060]
This is [Issue 1060](http://code.google.com/p/arduino/issues/detail?id=1060) moved from a Google Code project.
Added by 2012-10-05T11:43:23.000Z by [Wilfried...@gmail.com](http://code.google.com/u/104914328976362983260/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
I would like to have an menu entry to generate a hex file only for uploading later or for archiving proposes.

**Why?**
It's not so easy to locate the right dir with the HEX File in the bunch of temp direcrotries. 

Would this cause any incompatibilities with previous versions?  If so, how can these be mitigated?
I think there are no inkompatibilities.

**Comment by facchinm** [comment]
Fixed by 7893654
