### ISSUE TITLE
Arduino Upload Troubleshooting Page Text Overflowing

### ISSUE THREAD

**Issue by TinyCircuits** [arduino/Arduino#10604]
https://www.arduino.cc/en/Guide/Troubleshooting#upload

Viewing using google chrome on a Windows 10 desktop. The text on the right overflows several characters and is not fixable when using zoom in/out.

![image](https://user-images.githubusercontent.com/2231590/89670390-229fdd00-d8af-11ea-99f7-199497ce8bfe.png)
![image](https://user-images.githubusercontent.com/2231590/89670444-36e3da00-d8af-11ea-89c2-0de2e92f5004.png)

**Comment by per1234** [comment]
Thanks so much for the report @TinyCircuits! The bug no longer occurs for me, so I'm going to go ahead and close this. If you're still having this problem, please comment here and I'll investigate reopening.
