### ISSUE TITLE
[Library Manager] Please add Northern Widget MS5803

### ISSUE THREAD

**Issue by SRGDamia1** [arduino/Arduino#10609]
Another library addition request :O) https://github.com/NorthernWidget/MS5803

**Comment by per1234** [comment]
Hi @SRGDamia1. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by per1234** [comment]
Since the library was never brought into compliance, I'm going to go ahead and close this.

@SRGDamia1, if https://github.com/NorthernWidget/MS5803/issues/7 is ever resolved, please comment here and I'll be happy to reopen this.
