### ISSUE TITLE
[Library Manager] Please add EnviroDIY DS3231

### ISSUE THREAD

**Issue by SRGDamia1** [arduino/Arduino#10610]
Another library:  https://github.com/EnviroDIY/Sodaq_DS3231
properties file:  https://raw.githubusercontent.com/EnviroDIY/Sodaq_DS3231/master/library.properties

**Comment by per1234** [comment]
Hi @SRGDamia1. The library repository contains a .exe file:
https://github.com/EnviroDIY/Sodaq_DS3231/blob/master/examples/PCsync/PCsync.exe
Libraries in the Arduino Library Manager index are prohibited from containing .exe files:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-is-the-library-list-generated

So if you want to have the library added to the Arduino Library Manager index, you'll need to remove the .exe file from the repository and then either create a new tag/release or else redo the existing one.

After that, please comment here to let us know we can proceed. If, instead, you no longer wish to add the library to the Arduino Library Manager, you can go ahead and close the issue.

Thanks!

**Comment by SRGDamia1** [comment]
Is there no way to specify which folders or files from the repository to include - something akin to specifying folders for a sparse checkout?

**Comment by per1234** [comment]
The Arduino Library Manager uses the Git tag. Whatever is in the tag must be compliant with the requirements specified in the FAQ.

You can move the .exe file to a different branch, add it as a GitHub release asset, or move it to a different repository, but it can't be anywhere in the repository at the ref the tags point to.

**Comment by SRGDamia1** [comment]
OK, I'll get it moved.

**Comment by cmaglie** [comment]
I've added the library, but until the `exe` is removed the library will be rejected:

```
JOB 3278 - 2020/08/20 16:18:51 Release Sodaq_DS3231:1.3.0 has wrong library name, should be EnviroDIY_DS3231
JOB 3278 - 2020/08/20 16:18:51 Checking out tag: v1.3.2
JOB 3278 - 2020/08/20 16:18:51 Error syncing library: *.exe files found, skipping
```

from now on your repo is automatically checked every hour: just create a release without the .exe and it will be automatically published.
