### ISSUE TITLE
deleting temp files [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1061]
This is [Issue 1061](http://code.google.com/p/arduino/issues/detail?id=1061) moved from a Google Code project.
Added by 2012-10-05T11:48:50.000Z by [Wilfried...@gmail.com](http://code.google.com/u/104914328976362983260/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. OPen the IDE and close it.

**What is the expected output? What do you see instead?**
On opening the ide or the first compile there are generated several dirctories in the users temp directory. (build*.tmp, console*.tmp and untitled*.tmp) After closing the ide all directories with files in where 
left. So after some day's working with the ide you have to delete the directories manually.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0.1 on windows 7.

**Comment by ffissore** [comment]
Fixed with #2980

**Comment by g0ro** [comment]
It is fixed only partially.
Win7, Arduino 1.6.5 deletes build* and untitled* upon exit, but keeps console*
To reproduce: open arduino ide, make sure "verbose output" options are set, open any sketch and build it. Three folders gets created in %temp%. Close the ide. One of the new folders, console*, stays in %temp%.

**Comment by ffissore** [comment]
Fixed with a1e5271015b67f2825fe20012a27960f4c2ffaf6, already available with hourly builds http://www.arduino.cc/en/Main/Software#hourly
