### ISSUE TITLE
[Library Manager]Please add ESPWebDAV v2 library

### ISSUE THREAD

**Issue by d-a-v** [arduino/Arduino#10625]
Hello,

Could you please add this Arduino library,
it proposes a native network-FS providing r/w access to arduino board storage  (esp8266 so far: SPIFFS, LittleFS, SDFat) through network using WebDAV from our every-day computers (windows, mac, linux) *without external clients*.

WebDAV server can also share port 80 with webserver.

https://github.com/d-a-v/ESPWebDAV/releases/tag/2.0.0

Thanks

**Comment by cmaglie** [comment]
Done.
