### ISSUE TITLE
Delete one line in editor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1062]
This is [Issue 1062](http://code.google.com/p/arduino/issues/detail?id=1062) moved from a Google Code project.
Added by 2012-10-06T00:03:25.000Z by [Wilfried...@gmail.com](http://code.google.com/u/104914328976362983260/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
I like to see in the editor to delete the line where the cursor stands or all marked lines. With a keyboard shurcut like CTRL-d (eclipse like) or ctrl-y (z on english keyboards, like delphi, lazarus) 

**Why?**
For convenience only.

Would this cause any incompatibilities with previous versions?  If so, how can these be mitigated?
No incompatibilities.

**Comment by ffissore** [comment]
CTRL+D works fine with latest hourly
