### ISSUE TITLE
Webpage lines too long https://www.arduino.cc/en/Guide/Troubleshooting

### ISSUE THREAD

**Issue by brewmanz** [arduino/Arduino#10628]
Lines on webpage are too long https://www.arduino.cc/en/Guide/Troubleshooting
e.g. 1st line of answer to "Why I can't upload my programs to the Arduino board?" 
displays "There are many pieces involved in getting a program onto your Arduino board, and if any of them aren't right, the upload can fail. They include: the drivers for the board, the board and serial port selections in the Ard" 

but "uino software, access to the serial port, the physical connection to the board, the firmware on the 8U2 (on the Uno and Mega 2560)," is off the right end of screen. 

This is with
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit) 
with 
1920x1080 display full screen
under 
Linux Ubuntu LTS 20.04

![image](https://user-images.githubusercontent.com/300233/89891548-608f5f00-dc29-11ea-87b0-eaee149ae934.png)

**Comment by per1234** [comment]
Hi @brewmanz. Thank you very much for reporting this. We already have an issue for this bug (https://github.com/arduino/Arduino/issues/10604), so I'm going to close this one. You can subscribe to https://github.com/arduino/Arduino/issues/10604 if you want to get notifications on progress that might be made toward fixing this issue.
