### ISSUE TITLE
[Library Manager] Please update repository links

### ISSUE THREAD

**Issue by HendrikVE** [arduino/Arduino#10631]
Some repository names changed. Please update their links:

https://github.com/HendrikVE/ArduinoLiquidCrystalWired => https://github.com/HendrikVE/Arduino-LiquidCrystalWired (name=LiquidCrystalWired)
https://github.com/HendrikVE/ArduinoPCA9633 => https://github.com/HendrikVE/Arduino-PCA9633 (name=NXP PCA9633)
https://github.com/HendrikVE/ArduinoDFR0554 => https://github.com/HendrikVE/Arduino-DFR0554 (name=DFR0554)

Thank you

**Comment by cmaglie** [comment]
Done.
