### ISSUE TITLE
COM PORT URGENT

### ISSUE THREAD

**Issue by Icthyes** [arduino/Arduino#10635]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
Despite trying and restarting my computer countless times, when i tried to run my python code with the Arduino, it indicates that they are unable to open the com port 6, for mine, and I'm in a rush to hand up my project soon

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
