### ISSUE TITLE
Arduino Nano 33 IoT pinout pdf is incorrect

### ISSUE THREAD

**Issue by Fischer-Simon** [arduino/Arduino#10632]
In the pinout pdf of the Arduino Nano 33 IoT the RESET_N pinout of the NINA W102 doesn't match with the one in the schematic. In the schematic it is connected to PA08 but in the pinout it is documented as PB08 which woud conflict with the pinout for SDA of SERCOM4.

**Comment by FunzioneFabio** [comment]
Hello @Fischer-Simon Thank you so much for reporting this! The pinout is now corrected and uploaded on the website.
https://content.arduino.cc/assets/Pinout-NANO33IoT_latest.pdf
