### ISSUE TITLE
[Library Manager] Please add Ticker library 

### ISSUE THREAD

**Issue by combs** [arduino/Arduino#10642]
https://github.com/sstaub/Ticker

Many thanks!

**Comment by per1234** [comment]
Hi @combs. Although the library's repository is currently compliant with the requirements for addition to the Library Manager index, it was not at the time of the release (missing library.properties).

You will need to create a new tag/release that is compliant with all the requirements.

Once you have done this please comment here so we know we can proceed.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by combs** [comment]
Ready now, thank you!

**Comment by cmaglie** [comment]
Done.
