### ISSUE TITLE
Please add MySQL_MariaDB_Generic Library to Library Manager

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10643]
Please add [MySQL_MariaDB_Generic](https://github.com/khoih-prog/MySQL_MariaDB_Generic) to Library Manager. 
Thanks and Regards.

---

This [MySQL_MariaDB_Generic library](https://github.com/khoih-prog/MySQL_MariaDB_Generic) is based on and modified from [Dr. Charles Bell's MySQL_Connector_Arduino Library](https://github.com/ChuckBell/MySQL_Connector_Arduino) to provide support to many more boards and shields, such as ***Arduino SAMD21, Adafruit SAMD21/SAMD51, Seeeduino SAMD21/SAMD51, nRF52, STM32F/L/H/G/WB/MP1, Teensy, SAM DUE, AVR Mega, etc.***. Those supported boards can be used with ***ESP8266/ESP32’s WiFi, WiFiNINA, W5x00/ENC28J60/LAN8742A Ethernet, ESP8266/ESP32-AT modules/shields.***

You can use either Ethernet, Ethernet2, Ethernet3 or EthernetLarge library for W5x00 module/shield. For ESP8266/ESP32-AT shield, you can use either [`WiFiEspAT`](https://github.com/jandrassy/WiFiEspAT) or [`ESP8266_AT_WebServer`](https://github.com/khoih-prog/ESP8266_AT_WebServer)  library.

This [MySQL_MariaDB_Generic library](https://github.com/khoih-prog/MySQL_MariaDB_Generic) help you connect your boards directly to a MySQL / MariaDB server, either local or cloud-based, so that you can store / retrieve data tofrom the server.

**Comment by cmaglie** [comment]
Done.
