### ISSUE TITLE
[Library Manager] Please add Embedded Type-C PID library

### ISSUE THREAD

**Issue by abderraouf-adjal** [arduino/Arduino#10641]
Hello,

I'm requesting to add my new library to your index.
**EPID**: PID controller (Type-C) with a flexible API and errors handling.

**Repository:**
https://github.com/abderraouf-adjal/Embedded-PID

**library.properties:**
https://github.com/abderraouf-adjal/Embedded-PID/blob/master/library.properties

**Tag:**
https://github.com/abderraouf-adjal/Embedded-PID/releases/tag/v1.0.0

Thank you.

**Comment by cmaglie** [comment]
Done.
