### ISSUE TITLE
[Library Manager] Please add RoboCore libraries

### ISSUE THREAD

**Issue by RoboCore** [arduino/Arduino#10640]
Hello,

Please add the following libraries to the library manager of the IDE.

- [x] **RoboCore_MMA8452Q**
Repository: https://github.com/RoboCore/RoboCore_MMA8452Q
Tag: https://github.com/RoboCore/RoboCore_MMA8452Q/releases/tag/v1.0.0

- [x] **RoboCore_SMW-SX1276M0**
Repository: https://github.com/RoboCore/RoboCore_SMW-SX1276M0
Tag: https://github.com/RoboCore/RoboCore_SMW-SX1276M0/releases/tag/v1.0.0

Thank you,

**Comment by cmaglie** [comment]
Done.
