### ISSUE TITLE
[Library Manager] add wpi-32u4-library to the library manager

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#10654]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
This library provides the support classes for the WPI rbe 2001 course materials. It is a modification of the Pololu library, with additional motor support. 

https://github.com/WPIRoboticsEngineering/wpi-32u4-library

**Comment by cmaglie** [comment]
A library called `Romi32U4` is already registered (I guess it's the library that you forked).
You must change the name of the library if you want it added:

1. edit your `library.properties` and change the `name`
2. commit & push
3. delete and redo the latest git tag

**Comment by madhephaestus** [comment]
i made the latest release renamed to establish the fork. THank you!

**Comment by cmaglie** [comment]
One last change:

https://github.com/WPIRoboticsEngineering/wpi-32u4-library/blob/2.0.1/library.properties#L2

you wrote `version=2.0.` instead of `2.0.1` :-)

**Comment by madhephaestus** [comment]
oopsie, fixed. Thanks!

**Comment by cmaglie** [comment]
Ok, done.
