### ISSUE TITLE
[Library Manager] Please add Tone32

### ISSUE THREAD

**Issue by lbernstone** [arduino/Arduino#10653]
Please add Tone32 to library manager
https://github.com/lbernstone/Tone32

**Comment by madhephaestus** [comment]
THis library is provided as part of ESP32Servo, maybe look at that implementation before adding a new one?

**Comment by lbernstone** [comment]
I don't want to reinvent the wheel.  This is a dead simple library.  The issue is that if you search for tone esp32 in the library manager, you get no results. Can you add some keywords in the properties/description so people searching for tone & analogwrite get to your library?

**Comment by madhephaestus** [comment]
I added references to tone and republished 0.9.0, let me know if you would have found that when searching?
