### ISSUE TITLE
ardoino ide is not seeing my arduino uno

### ISSUE THREAD

**Issue by unkown1212** [arduino/Arduino#10657]
i have an Arduino uno connected to esp32 and is connected to computer but the arduino ide is not seeing it in board info or in port  please if any one knows anything tell me

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
