### ISSUE TITLE
[Library Manager] Please add ESPAsync_WiFiManager Library to Library Manager

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10669]
Please add [ESPAsync_WiFiManager](https://github.com/khoih-prog/ESPAsync_WiFiManager) to Library Manager.
Thanks and Regards.

---

### Why do we need this Async [ESPAsync_WiFiManager library](https://github.com/khoih-prog/ESPAsync_WiFiManager)

- Using asynchronous network means that you can handle **more than one connection at the same time**
- You are called once the request is ready and parsed
- When you send the response, you are **immediately ready** to handle other connections while the server is taking care of sending the response in the background
- **Speed is OMG**
- **Easy to use API, HTTP Basic and Digest MD5 Authentication (default), ChunkedResponse**
- Easily extendible to handle **any type of content**
- Supports Continue 100
- Async WebSocket plugin offering different locations without extra servers or ports
- Async EventSource (Server-Sent Events) plugin to send events to the browser
- URL Rewrite plugin for conditional and permanent url rewrites
- ServeStatic plugin that supports cache, Last-Modified, default index and more
- Simple template processing engine to handle templates

---

### Releases 1.0.11

1. Initial coding, based on [ESP_WiFiManager](https://github.com/khoih-prog/ESP_WiFiManager) to use ESPAsyncWebServer instead of (ESP8266)WebServer.
2. Bump up to v1.0.11 to sync with ESP_WiFiManager v1.0.11.

**Comment by cmaglie** [comment]
Done.
