### ISSUE TITLE
[Library Manager] Please add GreenBeacon library, and remove previous one

### ISSUE THREAD

**Issue by ukkz** [arduino/Arduino#10660]
Hello,
Could you add my GreenBeacon library?
Repository: [https://github.com/ukkz/green-beacon-esp32](https://github.com/ukkz/green-beacon-esp32)

Recently, I wrote issue [https://github.com/arduino/Arduino/issues/10562](https://github.com/arduino/Arduino/issues/10562) , and already added. thanks.
But this library had trademark problem, and so I altered library and repository name from "line-simple-beacon-esp32" to "green-beacon-esp32".

After name changed, I updated github repository but not seems to be reflected in Library Manager.
Could you update my library name, or remove previous & add new one? (I don't understand how it works the Library Manager with git repo, sorry)

Thanks,
ukkz

**Comment by cmaglie** [comment]
Done.
