### ISSUE TITLE
[Arduino IDE 1.8.13] Invalid Code Signature - expired code signing certificate

### ISSUE THREAD

**Issue by Daft-Wullie** [arduino/Arduino#10668]
The code signing certificate used to sign the installer for the Arduino IDE v. 1.8.13 is expired and this could be an issue with some AVs flagging it as having an invalid signature.
![expirecodesigncert1](https://user-images.githubusercontent.com/37898858/90936371-59c0d300-e405-11ea-895f-5a4094d2bfc5.JPG)
![expiredcodesigningcert](https://user-images.githubusercontent.com/37898858/90936385-604f4a80-e405-11ea-9b60-fb17dec2611b.JPG)

**Comment by facchinm** [comment]
Hi @Daft-Wullie ,
we already renewed the certificate for next IDE release.
However, certificates used to sign old releases will eventually expire, but the important thing is that they weren't expired at the time of signing.
So no sane antivirus should complain :slightly_smiling_face:
