### ISSUE TITLE
Library for calculating a few basic statistics like average and standard deviation then a few more intermediate to advanced ones like centroid and t-test

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10672]
Hi

Link to the library: https://github.com/LinnesLab/KickMath

This is a library for calculating a few basic statistics like average and standard deviation as well as a few more intermediate to advanced ones like centroid and t-test. The library is optimized for use with arrays of datasets and is templatized to make it more adaptable.

The library was used in this publication:
Publication Title: Kick LL: A Smartwatch for Monitoring Respiration and Heart Rate using Photoplethysmography
Publication link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6448578/

**Comment by cmaglie** [comment]
Done.
