### ISSUE TITLE
Digital Filters Library Optimized for Arrays

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10675]
Hi,

The library is located here: https://github.com/LinnesLab/KickFilters

Library for implementing digital filters such as lowpass, highpass, and notch optimized for working with arrays. Improves on other libraries by including a notch filter (also known as a bandstop filter), using a templated class to allow for ease of use with different numeric types, and using very simple but effective filter implementations for readability and user-friendliness. Also uses familiar terminology such as cutoff frequency which makes it easy to translate from analog filters.

**Comment by cmaglie** [comment]
Done.
