### ISSUE TITLE
New Arduino Library for the Templated FFT Class

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10670]
Hi,

The library is located here: https://github.com/linneslab/kickfft

I created a library for the computing Fourier transforms and power spectrums which are useful for signal processing. The library is templated which allows the user to use multiple variable types. It also relies on look-up tables to compute the trigonometric values to improve speed. The library was used in this publication and resulted in over three orders of magnitude improvement in speed vs. using the trigonometric functions.

Publication Title: Kick LL: A Smartwatch for Monitoring Respiration and Heart Rate using Photoplethysmography
Publication link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6448578/

**Comment by hoilett** [comment]
Any updates on this? As well as my other requests? No rush. Just checking in to make sure I set everything up correctly. Last time I did library manager submission, it was resolved in 2 days.

I also submitted these requests:
https://github.com/arduino/Arduino/issues/10671
https://github.com/arduino/Arduino/issues/10672
https://github.com/arduino/Arduino/issues/10673
https://github.com/arduino/Arduino/issues/10674
https://github.com/arduino/Arduino/issues/10675
https://github.com/arduino/Arduino/issues/10689

**Comment by per1234** [comment]
Hi @hoilett . cmaglie periodically comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. So the delay between making a request and the addition is dependent on where in that cycle you happen to make the request.

I ran all your repos through my DIY Library Manager submission validator script and they all passed. My script isn't 100% accurate, but I'm pretty sure you have everything perfect. If there is a problem, it will be caught by the indexer system and cmaglie will let you know what you need to do to resolve it.

**Comment by hoilett** [comment]
@per1234 Ah. Sounds good. I'll just be more patient then. Thank you.

**Comment by cmaglie** [comment]
Done.
