### ISSUE TITLE
t Distribution Lookup Table

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10673]
Hi,

The library is located here: https://github.com/LinnesLab/tTestTable

Definition file containing look-up tables used for determining t-distribution when running t-tests since it's really difficult to compute the probability density function on an Arduino. Also used as a companion library to this one: https://github.com/arduino/Arduino/issues/10672

Created as a separate library, so it is easier to include in other projects.

**Comment by cmaglie** [comment]
Done.
