### ISSUE TITLE
Name change: Anyleaf

### ISSUE THREAD

**Issue by David-OConnor** [arduino/Arduino#10679]
https://github.com/AnyLeaf/ph-cpp

Hello. I'm requesting a library name change from *anyleaf* to *Anyleaf*, to be more consistent with the convention of other libs. See [this issue](https://github.com/arduino/Arduino/issues/10250#issuecomment-678599068). This should hopefully allow the [0.1.8 release](https://github.com/AnyLeaf/ph-cpp/releases/tag/0.1.8) to be published.

Thank you.

**Comment by cmaglie** [comment]
Done.
