### ISSUE TITLE
New definition file containing look-up tables for Trigonometric Functions

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10671]
Hi,

The library is located here: https://github.com/LinnesLab/TrigDef

This is a definition file containing lookup tables for trigonometric functions that can be used in many different instances. Particularly, it is using in at least one other library (https://github.com/arduino/Arduino/issues/10670) for improving the speed in computer Fourier transforms by decreasing computation times. The library was used in this publication and resulted in over three orders of magnitude improvement in speed vs. using the trigonometric functions.

Publication Title: Kick LL: A Smartwatch for Monitoring Respiration and Heart Rate using Photoplethysmography
Publication link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6448578/

**Comment by cmaglie** [comment]
Done.
