### ISSUE TITLE
Real-Time Digital Filters Library

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10674]
Hi,

The library is located here: https://github.com/LinnesLab/KickFiltersRT

Library for implementing real-time digital filters such as lowpass, highpass, and notch. Improves on other libraries by including a notch filter (also known as a bandstop filter), using a templated class to allow for ease of use with multiple numeric types, runs synchronously with the program (in real-time) without needing to store a large amount of data in an array before the signal can be filtered. Also uses familiar terminology such as cutoff frequency which makes it easy to translate from analog filters.

**Comment by cmaglie** [comment]
Done.
