### ISSUE TITLE
New Sorting Algorithm Library

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#10689]
Hi,

The library is located here: https://github.com/LinnesLab/KickSort

I created a library for different sorting algorithms including quicksort, bubble sort, insertion sort, shell sort, and comb sort. It's also a templated class allowing people to use whatever numerical types they want. I haven't found a library in the library manager that compiles various different sorting implementations as well as using a templated class, so this should fill a nice niche.

**Comment by cmaglie** [comment]
Done.
