### ISSUE TITLE
Request for adding EasyMorse Library

### ISSUE THREAD

**Issue by milador** [arduino/Arduino#10705]
Can you please add the EasyMorse Library?

It's available at : [https://github.com/milador/EasyMorse](https://github.com/milador/EasyMorse)

Thanks

**Comment by per1234** [comment]
Hi @milador. 
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by milador** [comment]
Hi @per1234,

I created the release and it should be good to go. 

[https://github.com/milador/EasyMorse/releases](https://github.com/milador/EasyMorse/releases)

Thanks

**Comment by cmaglie** [comment]
Done.
