### ISSUE TITLE
[Library Manager] Please add KIM Library

### ISSUE THREAD

**Issue by ncassarkineis** [arduino/Arduino#10702]
Please add [KIM library](https://github.com/Kineis/ArduinoKim) to Library Manager.
Thanks and Regards.

**Comment by per1234** [comment]
Hi @ncassarkineis. 
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by William-at-kineis** [comment]
Hi @per1234,

We have just released   https://github.com/Kineis/ArduinoKim/releases/tag/ARDUINO_KIM1_HW2_V3.0.0 .
Is this syntax fine for you or do you need a `v3.0.0` release as well?

**Comment by cmaglie** [comment]
Done.
