### ISSUE TITLE
[Library Manager] SparkFun_ProDriver_TC78H670FTG_Arduino_Library

### ISSUE THREAD

**Issue by lewispg228** [arduino/Arduino#10713]
Hello,

Please add the SparkFun_ProDriver_TC78H670FTG_Arduino_Library to the Library Manager. Here is the link:

https://github.com/sparkfun/SparkFun_ProDriver_TC78H670FTG_Arduino_Library

Thanks!

**Comment by cmaglie** [comment]
Done.

**Comment by lewispg228** [comment]
Thank you!
