### ISSUE TITLE
[Library Manager] Please add LittleFS_esp32 to the library manager

### ISSUE THREAD

**Issue by lorol** [arduino/Arduino#10719]
Please add the LittleFS esp32 wrapper as an Arduino library. The url is:
https://github.com/lorol/LITTLEFS

Here is discussion about it and recommendation to go this way:
https://github.com/espressif/arduino-esp32/pull/4096#issuecomment-646232022

**Comment by cmaglie** [comment]
Done.

**Comment by lorol** [comment]
Thank you!
