### ISSUE TITLE
[Library Manager] Please add cgnuino library

### ISSUE THREAD

**Issue by keimochizuki** [arduino/Arduino#10710]
Hello,

I created a new library [cgnuino](https://github.com/keimochizuki/cgnuino) which help cognitive psychologists and neuroscientists to build behavioral tasks with Arduino. Could you please add this library to Arduino's Library Manager?
If anything is wrong about library.properties, directory arrangement etc., please notice me.

Thank you very much.

https://github.com/keimochizuki/cgnuino

**Comment by cmaglie** [comment]
Done.
