### ISSUE TITLE
Library Manager submission: HM330X by Tomoto

### ISSUE THREAD

**Issue by tomoto** [arduino/Arduino#10728]
Dear Arduino Staff, I hereby submit a sensor library below for Library Manager.
https://github.com/tomoto/Arduino_Tomoto_HM330X

Please kindly review it and give me feedback if you find any issues. I tried to follow the guideline here https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and hope it is going to work out.

Thank you for your support.

**Comment by cmaglie** [comment]
Done.
