### ISSUE TITLE
Function can be referenced as a variable when not passing parametes.

### ISSUE THREAD

**Issue by zerohimself** [arduino/Arduino#10730]
I *think* i found a bug..
I made a typo when assigning the return value of a function to a variable. I know this throws errors in every version of c, or c++ i've ever used..

Arduino version: 1.8.13
Board: (clone) Pro Micro (atmega 32u4)

Sample code:
```
//---------------
#include <Wire.h>
// a bunch of removed code

void setup()
{
  Serial.begin(9600);
 // a bunch of removed code
  while(!Serial) ;
  int test =testFunc; // simple typo.. forgot the ()
  Serial.println(test);
    // ^^ this should not compile unless i'm mistaken..
    
// a bunch of removed code
}

void loop()
{
  // yet more removed code
}

void testFunc(void) 
{
  Serial.println("something");
}

//---------------

```
Output:
-----------
`1076`
-----------
This compiles, and runs... the function does not run, and instead an address is placed into the variable and sent over the Serial line.
Shouldn't this require a typecast of & ? (if not, please explain, to educate me).

**Comment by RobTillaart** [comment]
This is standard behavior as the name of a function is its address.
Similar to the name of an array is the address of its first element.

https://www.geeksforgeeks.org/address-function-c-cpp/

You can do interesting things with it, see some of my experiments 

https://forum.arduino.cc/index.php?topic=206579.0
https://github.com/RobTillaart/avrheap
