### ISSUE TITLE
Arduino IDE hangs at startup on Windows7 Professional 32-bit [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1073]
This is [Issue 1073](http://code.google.com/p/arduino/issues/detail?id=1073) moved from a Google Code project.
Added by 2012-10-17T10:22:38.000Z by [LLJFr...@gmail.com](http://code.google.com/u/100747881708528130226/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Start the IDE
2. Splashscreen shows and after a while the mousecursor can't be moved and the computer hangs.
**3.**

**What is the expected output? What do you see instead?**
The IDE started. Just the splashscreen showed.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0.1 om Windows 7 Professional 32-bit

**Please provide any additional information below.**
It seams like what COM port used has a rule. When installing the Arduino UNO R3, the port got COM20. Had to change it to COM2 in order to get it to work.

**Comment by ffissore** [comment]
Unable to reproduce
