### ISSUE TITLE
[Library Manager] Please add LowPowerAVRZero and RTCAVRZero library

### ISSUE THREAD

**Issue by rocketscream** [arduino/Arduino#10738]
- [x] https://github.com/rocketscream/RocketScream_RTCAVRZero
- [x] https://github.com/rocketscream/RocketScream_LowPowerAVRZero

Please help to add both the [LowPowerAVRZero](https://github.com/rocketscream/RocketScream_LowPowerAVRZero) and [RTCAVRZero](https://github.com/rocketscream/RocketScream_RTCAVRZero) libraries that can be used for megaAVR 0-series MCU that are used on board like Uno WiFi Rev2 and Nano Every. Thank you.

**Comment by cmaglie** [comment]
Done.
