### ISSUE TITLE
"Servo.h" found multiple libraries

### ISSUE THREAD

**Issue by LINYOUWEI0804** [arduino/Arduino#10743]
Hello, what I am doing now is Google's coral dev board development board to send the signal to the arduino, and finally turn the sg90 motor.
Now it is possible to send signals to arduino and arduino alone to control the motor, but there will be this error when the two programs are integrated.
:
"Servo.h" found multiple libraries
已使用: /home/must/下載/arduino-1.8.10-linux64/arduino-1.8.10/libraries/Servo
exit status 1
expected declaration before '}' token

MY code:
sg90.ino is an integrated program and it is also wrong
sg9090.ino controls the motor individually
contro1.ino send signal

[code.zip](https://github.com/arduino/Arduino/files/5194850/code.zip)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
