### ISSUE TITLE
How to add  library.properties to library

### ISSUE THREAD

**Issue by yannisant** [arduino/Arduino#10746]
Hello,

I am trying to upload  the library for the [DFRobot_BME280] to the online editor and I get an error message about the library.properties file missing. Can you please help? Do I generate this file? Or can I find it?

Kind regards,

Yannis

**Comment by matthijskooijman** [comment]
Here's the reference documentation for libraries: https://arduino.github.io/arduino-cli/latest/library-specification/

There might be better, tutorial-style documentation elsewhere, but I"m not sure where so hopefully this will at least get you started.

**Comment by per1234** [comment]
Since Matthijs was kind enough to help you out and we already have an issue for the excellent suggestion of adding information about library.properties to a tutorial at https://github.com/arduino/Arduino/issues/4413, I'm going to go ahead and close this.

**Comment by yannisant** [comment]
thank you
