### ISSUE TITLE
Updated Documentation for Arduino Engineering Kit V.1

### ISSUE THREAD

**Issue by warrenwallis** [arduino/Arduino#10741]
Hello!

I am currently working on the first iteration of the Arduino Engineering Kit and have come across multiple issues with the documentation. To connect to the motor carrier, the code given on the tutorial is "carrier = addon(a, 'Arduino/MKRMotorCarrier')" however, this does not work. Instead I have to use "carrier = mkrMotorCarrier(a)". I am wondering if this is the correct way to go? Or am I missing a download?

Some methods like DutyCycle have been changed to Speed. Some methods, like setSpeed, cannot are not defined (function call can be found under Task3, under function "moveToCounts"). 

I am wondering if there is an updated tutorial of the Engineering Kit, because each change requires research and some research does not give productive results. I am currently working on the Drawing Robot Project and I fear there is going to be many fundamental changes within each task of each project.

**Comment by per1234** [comment]
Hi @warrenwallis. Thanks for taking the time to report this. I see from your forum thread: https://forum.arduino.cc/?topic=703720 that you found the solution to your problem, so I'm going to go ahead and close this as solved.
