### ISSUE TITLE
Arduino Sound Library Reference typo in #include

### ISSUE THREAD

**Issue by TimBeam404** [arduino/Arduino#10758]
on the reference page for the Arduino Sound Library (https://www.arduino.cc/en/Reference/ArduinoSound), there is given a faulty #include name. Instead of 
`#include <AudioSound.h>`
it must be
`#include <ArduinoSound.h>`
as used in the examples.

**Comment by per1234** [comment]
Thanks so much for reporting this error @TimBeam404. It has been fixed by https://github.com/arduino-libraries/ArduinoSound/pull/39
