### ISSUE TITLE
Disable "Replace" and Replace & Find" when nothing is selected. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1075]
This is [Issue 1075](http://code.google.com/p/arduino/issues/detail?id=1075) moved from a Google Code project.
Added by 2012-10-18T07:19:03.000Z by [Jskalky...@gmail.com](http://code.google.com/u/115765294193402783172/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

Had a minor issue when doing a replace & find under the find dialog box. I was replacing the word pwrdbgLED with pdLED, and when it came upon the last entry, clicking "replace & find" only added the text "pdLED".

To recreate this problem, open the bare minimum sketch from the examples. Under the Edit menu, select find. replace "void" with "boid" and click "replace & find" multiple times and you will be able to see the problem. 

Using Arduino 1.0.1 on Windows 7 Professional Service Pack 1 (64-bit) and OSEPP Uno board, however I think the board I'm using is irrelevant.

**Comment by ffissore** [comment]
Fixed a long time ago
