### ISSUE TITLE
Arduino 1.8.13 (win10) - header files not found due to max path length exceeded in ArduinoData/packages

### ISSUE THREAD

**Issue by mduchain** [arduino/Arduino#10754]
**IDE version: 1.8.13 (Windows Store 1.8.42.0)**

Action: Compiling example sketch for Heltec ESP32 Wifi board.
I've found an issue with include files when the path+file is particularly long under ArdiunoData/packages (> 210).
Compiler bails with error "file not found" for some header files. The real reason is the length of the path.
I've modified some of the header files to have shorter names, bringing the size of path+file under 210 chars.
By renaming and shortening the paths, I was able to compile and run the project without issue.

For info, my "user name" under c:\users is 44 char longs. Needless to say I can't change this.
Any workaround, like moving the ArduinoData folder to an arbitrary location?

**Comment by per1234** [comment]
Hi @mduchain. Thanks for taking the time to report this bug. We already have an open issue to track this (https://github.com/arduino/Arduino/issues/10565), so I'm going to go ahead and close this as a duplicate.

You'll be happy to see there is some work in progress to address this issue in Arduino CLI, where the underlying functionality of Arduino IDE is increasingly implemented: https://github.com/arduino/arduino-cli/pull/961
