### ISSUE TITLE
[Library Manager] Libraries moved to new Github account

### ISSUE THREAD

**Issue by obdevel** [arduino/Arduino#10751]
Hi, please update the library registry with the new Github account for these libraries:

obdevel/CBUS -> MERG-DEV/CBUS
obdevel/CBUS2515 -> MERG-DEV/CBUS2515
obdevel/CBUSLED -> MERG-DEV/CBUSLED
obdevel/CBUSswitch -> MERG-DEV/CBUSswitch
obdevel/CBUSconfig -> MERG-DEV/CBUSconfig
obdevel/CBUSBUZZER ->MERG-DEV/CBUSBUZZER

Re: discussion at https://forum.arduino.cc/index.php?topic=704659.0

Thank you.

**Comment by cmaglie** [comment]
CBUSBUZZER is not in the library manager do you want it added too?

**Comment by obdevel** [comment]
Yes please.

**Comment by cmaglie** [comment]
Done.
