### ISSUE TITLE
Please add my libraries from TGP

### ISSUE THREAD

**Issue by TechnoPhysCAL** [arduino/Arduino#10760]
Hello,
Please add the following libraries from TGP : 

- [x] https://github.com/TechnoPhysCAL/TGP_Bouton
- [x] https://github.com/TechnoPhysCAL/TGP_Del
- [x] https://github.com/TechnoPhysCAL/TGP_Ecran
- [x] https://github.com/TechnoPhysCAL/TGP_ProtoTGP
- [x] https://github.com/TechnoPhysCAL/TGP_MenuOLED

Thank you!

**Comment by cmaglie** [comment]
Done.
