### ISSUE TITLE
SerialMonitor (AbstractTextMonitor.java) should honour Backspace (\b, 0x08) character, if (proposed) 'actionBackspace' option is set

### ISSUE THREAD

**Issue by brewmanz** [arduino/Arduino#10765]
Currently (1.8.14), the Arduino IDE Serial Monitor prints Backspace (\b, 0x08) as an empty block character. Ideally, it should move the cursor back one without rubout, but IMO just doing a backspacing rubout would be an improvement anyway. 

There should also be an option box (like AutoScroll & ShowTimestamp) to save the user's choice as 'serial.action_backspace' in preferences.txt, so this new behaviour is optional and persisted. 

Some guidance with where to put Unit Test Sketches would be appreciated. 

![Screenshot from 2020-09-18 13-10-29_ArduinoIdeSerialMonitorBackspace](https://user-images.githubusercontent.com/300233/93543754-89391000-f9b0-11ea-9f31-18b98f1412c9.png)

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/3654
