### ISSUE TITLE
[Library manager]: Name change request from "Quirkbot" to "Strawbees Quirkbot"

### ISSUE THREAD

**Issue by paulobarcelos** [arduino/Arduino#10770]
Hi, I am the maintainer of the Strawbees Quirkbot library (https://github.com/Quirkbot/QuirkbotArduinoLibrary) and recently decided to change the name from  "Quirkbot" to "Strawbees Quirkbot", so that it is easier for folks to find it via the library manager.

Can you please help me out with that?

New releases are not automatically fetched anymore in the library manager...

**Comment by cmaglie** [comment]
Done.
