### ISSUE TITLE
Please Add MkrGsm1400IoT

### ISSUE THREAD

**Issue by phlpjo** [arduino/Arduino#10789]
[Source](https://github.com/phlpjo/MkrGsm1400IoT)
[Tag](https://github.com/phlpjo/MkrGsm1400IoT/releases/tag/MkrGsm1400IoT) 

It's a library to write uint to the sim card phone book and read them.
As long as I am working with the MKR GSM 1400, I will continue to extend this library and add new functions if needed.

Thank you.

**Comment by cmaglie** [comment]
Done.
