### ISSUE TITLE
[Library Manager] Please add sunset to the manager

### ISSUE THREAD

**Issue by buelowp** [arduino/Arduino#10781]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
Library Source: https://github.com/buelowp/sunset

Tagged Release: https://github.com/buelowp/sunset/tree/1.1.4

**Comment by sank-tech** [comment]
View it on GitHub

**Comment by per1234** [comment]
@sank-tech please stop spamming our issue tracker with these "View it on GitHub" comments.

**Comment by cmaglie** [comment]
Done.
