### ISSUE TITLE
Please add library PWMMotorControl

### ISSUE THREAD

**Issue by ArminJo** [arduino/Arduino#10793]
Hello,

I prepared an new Arduino compatible library.
https://github.com/ArminJo/PWMMotorControl

Could you add it to your list of libraries?

Thank you.
Armin

**Comment by per1234** [comment]
Hello @ArminJo. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

Thanks!

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by ArminJo** [comment]
Uuups.
Thanks , I forgot it.
Now the release is ready.

**Comment by ArminJo** [comment]
Hi,
is there a reason for not adding this library into your library set???

**Comment by per1234** [comment]
No reason at all. It will be added for sure.

cmaglie periodically comes through to clear all the outstanding Library Manager inclusion requests at once. You happened to submit this request only a few hours after the last batch addition happened, so you're unlucky enough to be experiencing the maximum delay.

So we'll get to it soon, please be patient. Thanks!

**Comment by ArminJo** [comment]
Thanks, so I must hurry with my next one :-)

**Comment by cmaglie** [comment]
Done, sorry for the long delay!

**Comment by ArminJo** [comment]
Thanks
