### ISSUE TITLE
Broken link to "Arduino as ISP and Arduino Bootloaders" tutorial

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/Arduino#10794]
The link https://www.arduino.cc/en/Tutorial/ArduinoISP/ seems to be broken and did not appear properly under the new search either.  Could someone please fix it.

**Comment by matteosuppo** [comment]
In what page did you find this url?

**Comment by BallscrewBob** [comment]
I was initially using the new SEARCH but it failed to turn up in there.
It was found using other means and then it came up as broken.

It seems to have been fixed now.
