### ISSUE TITLE
[Library Manager] Please add SparkFun Qwiic GPIO Library

### ISSUE THREAD

**Issue by AndyEngland521** [arduino/Arduino#10790]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
https://github.com/sparkfun/SparkFun_Qwiic_GPIO_Library

**Comment by per1234** [comment]
Hi @AndyEngland521. I get a 404 from that URL. Is the repository set to private mode?

**Comment by AndyEngland521** [comment]
You're correct @per1234 everything should be good now.

**Comment by cmaglie** [comment]
You're still missing a release tag, please create a git tag `1.0.0`.

**Comment by AndyEngland521** [comment]
Updated.

**Comment by cmaglie** [comment]
Done.
