### ISSUE TITLE
DMX-55 controller support [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1080]
This is [Issue 1080](http://code.google.com/p/arduino/issues/detail?id=1080) moved from a Google Code project.
Added by 2012-10-22T22:00:13.000Z by [kc9...@gmail.com](http://code.google.com/u/107298153906045216169/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

**What change would like to see?**

I am looking to find a shield/library to send out specific DMX-55 messages to my lighting gear.
[DMX-55 is a very old control language standard, found in most intelligent lighting]

**Why?**
I would like to hack my existing lighting gear together with arduino.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

I don't think there are any issues, this would be an add-on libray/shield event - like the LCD one.

**Comment by per1234** [comment]
This is outside the scope of this repository. The [DmxSimple library](https://github.com/PaulStoffregen/DmxSimple) was recommended in the comment on this issue on Google Code.
