### ISSUE TITLE
Double mentions on IOT kit.

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/Arduino#10806]
Picture says it all for item  https://store.arduino.cc/usa/explore-iot-kit

![2020-09-26 at 17-37-56](https://user-images.githubusercontent.com/8212730/94350754-5da4ce00-001f-11eb-971b-17ef6f1952f1.jpg)

**Comment by per1234** [comment]
Hi @BallscrewBob. Thanks for your report!

The "Plug and play connectors for different sensors" are the connectors shown on the image of the back of the carrier:
![carrier](https://store-cdn.arduino.cc/uni/catalog/product/cache/1/image/1000x750/f8876a31b63532bbba4e781c30024a0a/s/t/store_callout_02_1.jpg)

The "Plug-and-play cables for all the sensors" are the three conductor cables shown in this image:
![kit](https://store-cdn.arduino.cc/uni/catalog/product/cache/1/image/1000x750/f8876a31b63532bbba4e781c30024a0a/a/k/akx00027_unbox-3.jpg)

So you can see the first is a feature of the MKR IoT Carrier, which the second is an accessory included with the kit. So these are two separate, but related, items.
