### ISSUE TITLE
Please add TFLuna-I2C library to the Library Manager

### ISSUE THREAD

**Issue by budryerson** [arduino/Arduino#10801]
https://github.com/budryerson/TFLuna-I2C/releases/tag/0.1.0

To my friends who manage the Arduino Library.  This is the initial release of an Arduino library for the Benewake TFLuna LiDAR device in I2C communication mode.  Please add it to the Library Manager when you get a chance.  I think it will be very helpful to other users.  Thank you,  Bud Ryerson, San Francisco

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
