### ISSUE TITLE
AttinyCore, FastLED and ColorPalette Error

### ISSUE THREAD

**Issue by link0687** [arduino/Arduino#10807]
Hi,
I am using AttinyCore (using an attiny2313a) and FastLED library. Once I've added the blank sketch with the FastLED library included it will compile fine with no errors. As soon as I add the "ColourPalette" example from FastLED library I get a compiler error. I have attached this below in a text file. If you can help me trouble shoot this or point me in the write direction that would be great. I have labeled in the text file where a compiler error begins by using "Orange Error Writing". Please excuse the crudeness I am new.
[Error COde.txt](https://github.com/arduino/Arduino/files/5287829/Error.COde.txt)
. Thanks!

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests for official Arduino software. You are asking for support for your project that uses the 3rd party boards platform ATTinyCore and the 3rd party library FastLED. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code and error output, using code tags (`</>` button on the toolbar).
