### ISSUE TITLE
Mistake in "Audio" library reference

### ISSUE THREAD

**Issue by AlbiBone** [arduino/Arduino#10800]
Hello,
I point out a small bug in [this](https://www.arduino.cc/en/Reference/AudioBegin) official Arduino site reference.

In particular, under "parameters" field:

> rate (int) : the sample rate of the sound file. If stereo, double the rate (ex. 44100Khz stereo = 88200).

Obviously it is not 44100Khz but 44100 Hz (capital H and delete the K, or if you prefer to keep in kHz just add the comma in the right place so 44.1 kHz) since we are talking about audio sampling frequency.
Moreover, please add the unit of measurement to 88200: what is 88200? potatoes? tomatoes? Hz?

Thank you and best regards.

**Comment by Prath06** [comment]
I want to work on this. I have an Idea.
