### ISSUE TITLE
[Library manager] Please update Magellan_BC95 v1.1.0

### ISSUE THREAD

**Issue by AIS-DeviceInnovation** [arduino/Arduino#10811]
Repository:
https://github.com/AIS-DeviceInnovation/Magellan_BC95

Thanks & Regards,
AIS-DeviceInnovation

**Comment by per1234** [comment]
Hi @AIS-DeviceInnovation. The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So once your library has been added to the index (as yours is), the only thing you need to do to make a new version available for installation via Library Manager is:
- Update the `version` value in library.properties (as you did already)
-  Create a new [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) (which you have not done)

After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time.

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
