### ISSUE TITLE
[Library Manager] Please add Ticker library

### ISSUE THREAD

**Issue by vzahradnik** [arduino/Arduino#10823]
Please add https://github.com/JSC-electronics/Ticker library.

Thanks,
Vladimir

**Comment by per1234** [comment]
Hi @vzahradnik. Each library added to the Library Manager index must have a unique library.properties `name` value (regardless of case). The `name` value used in your library has already been taken:
https://github.com/sstaub/Ticker

If you would still like your library added to the index, you'll need to change the `name` value to a unique name, then either update the `version` value in library.properties and make a new release/tag or else redo the existing tag.

After that is done, please comment here to let us know we can proceed. Thanks!

**Comment by vzahradnik** [comment]
@per1234 I changed the name to `SimpleTicker`, and I also created a new release.

Please review the `library.properties`, and let me know if there's anything else to be done.

Thanks!

https://github.com/JSC-electronics/Ticker/blob/master/library.properties

**Comment by cmaglie** [comment]
Done.
