### ISSUE TITLE
directorys [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1082]
This is [Issue 1082](http://code.google.com/p/arduino/issues/detail?id=1082) moved from a Google Code project.
Added by 2012-10-24T13:52:07.000Z by [va3...@gmail.com](http://code.google.com/u/103953991114079045261/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I would like to see the compiled hex file placed in the project directory once completed

With the current version it placed them in a temp folder and changes the directory every time you open and close causing it to be a headache to find the file.

I can see many other users doing the same as I am, once compiled bring the completed file in to a SPICE simulation file to run tests on the code with changes to the schematic.  Finding the correct build directory can be a tedious process.  If it copied once complete to the sketch directory we could link from the other software without changing links to the compiled hex file.

This would not cause problems with other versions as it only involves a file being copied back to a directory for ease of use.

**Comment by ffissore** [comment]
.hex export feature available in latest hourly
