### ISSUE TITLE
[Library Manager] Please update the Blues Wireless Notecard library

### ISSUE THREAD

**Issue by bsatrom** [arduino/Arduino#10824]
Library Source: https://github.com/blues/note-arduino

Tagged Release: https://github.com/blues/note-arduino/releases/tag/v1.2.4

Zip Direct download: https://github.com/blues/note-arduino/archive/v1.2.4.zip

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time.

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by bsatrom** [comment]
ah, great to know, thanks!
