### ISSUE TITLE
String class [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1084]
This is [Issue 1084](http://code.google.com/p/arduino/issues/detail?id=1084) moved from a Google Code project.
Added by 2012-10-27T16:05:56.000Z by [giuseppe...@gmail.com](http://code.google.com/u/105726746689980229986/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

Your String class is very limited.
It does do nothing! It should be like the iPhone or Android one.

**Comment by Chris--A** [comment]
This is quite limited in description. Is there really an issue here?

**Comment by sandeepmistry** [comment]
Closing, as there are no specific API requests.
