### ISSUE TITLE
Feature Request: Add git support in the IDE

### ISSUE THREAD

**Issue by Heisenberg1337x** [arduino/Arduino#10841]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

**Comment by per1234** [comment]
Thanks for taking the time to submit a feature request @Heisenberg1337x. We already have an existing issue about this (https://github.com/arduino/Arduino/issues/4387) and we only need one per topic, so I'll go ahead and close this as a duplicate.
