### ISSUE TITLE
Wrong variable address with new SP on Context switch(or Task switch)

### ISSUE THREAD

**Issue by GYU-JOONG-KIM** [arduino/Arduino#10852]
I am studying OS and kernel.

1. I have a question about stack on MEGA2560 with arduino compiler.  
2. I code context switch. My code copy stack data and changing Stack point to 0x0400
3. After I changed stack point, I declared a local variable i. I checked the i address. i address is 0x21F1. 0x21F1 is around stack point at initialization.
4. Other tasks are had another stack point. Other tasks and function variable address are had around stack point at initialization. Then each variable of each task which are had each SP are collided and corrupted.
5. I know arduino compiler which support freeRTOS.
6. I do not understand this issue.
7. I can code to evade this issue, But it is not C code. It is just like as assemble code.
8. I studied new variable address which get around with stack point.
9. Thank you very much for my question. Please pardon me my poor word in english.
10. I think you don't understand my word. I show you a example blow line.

Question : My code is wrong?  
           I miss some setting?
           Compiler bug?
           no considering in compiler or not support ?
           How can I do get function variable address whit new stack point?

Example
...
...
setup
{
...
...
get_stack();
...
...
}

void get_stack(void)
{

    // child task stack data are copied from parents task stack data.
    // SPH, SPL set on child each task stack
}

void loop(){
   // Execution each task
   ...
   task_1();
   ...
}

//////////////////////////////////////////////
//SP 0x0400
void task_1
{
  unsigned char a;
  ...
   ...
  a = add( b,c);
  ...
  ...
}

unsigned char add(unsigned char d, unsigned char e)
{
     unsigned char f;
     f = d + e;
     return f;
}
d address   0x03F1
e address   0x03F0
f address   0x03EF
 are correct.

But each variable address are show me
d address   0x21F1
e address   0x21F0
f  address   0x21EF

void task_2(void)    // SP  0x1000
{
    unsigned char t;
    ... 
    ...
    ... 
}

t address 0x21Ex

※ Variables are gotten address around new stack point in timer interrupt routine.
ISR(TIMER1_COMPA_vect)
{
     unsigned char i;
     unsigned char k;
     i = 1;
     k = 2;
     k = k + 5 + i;
     i = test_add();
     ...
     ...
     ...
}

unsigned char test_add(void)
{
   unsigned char a,b,c;
   a = 3;
   b = 4;
   c = a + b + 5;
   return c;
}

Variables address on SP(0x0400)
  i address    0x03Ex
  k address    0x03Ex
  a address    0x03Ex
  b address    0x03Ex
  c address    0x03Ex
.

**Comment by alranel** [comment]
Hi @GYU-JOONG-KIM. This issue tracker is reserved to the development of the Arduino IDE. You should go to the [forum](https://forum.arduino.cc) and ask your question there to the other community members. :)
