### ISSUE TITLE
Compiler in Windows 7 takes very long to compile [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1085]
This is [Issue 1085](http://code.google.com/p/arduino/issues/detail?id=1085) moved from a Google Code project.
Added by 2012-10-28T23:28:22.000Z by [cjwu...@gmail.com](http://code.google.com/u/118238120487190978766/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. open any program
2. click "verify" or "upload"

**What is the expected output? What do you see instead?**

I'd expect to see the compiler finish in a matter of seconds. Instead, compiling and uploading takes 5 minutes or more.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

version 1.0.1

Windows 7, 64 bit system

Programming Baby-Orangutan from pololu with modified boards and programmer .txt file

**Please provide any additional information below.**

The software worked for a while, then suddenly (as far as I can tell), it's been taking outrageously long to compile. Others on the internet have had this problem, and no solutions are yet available as far as I can tell from my research.

**Comment by ffissore** [comment]
Mitigated by #2568: windows avr toolchain don't rely on cygwin any more
