### ISSUE TITLE
Please add DS323x_Generic Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#10866]
Please add [**DS323x_Generic library**](https://github.com/khoih-prog/DS323x_Generic) to Library Manager.
Thanks and Regards.

---

### Why do we need this [DS323x_Generic library](https://github.com/khoih-prog/DS323x_Generic)

This is an Arduino library for DS3231/DS3232 Extremely Accurate I2C-Integrated RTC/TCXO/Crystal

The DS323x is a low-cost, extremely accurate I2C real-time clock (RTC) with an integrated temperature-compensated crystal oscillator (TCXO) and crystal. The device incorporates a battery input, and maintains accurate timekeeping when main power to the device is interrupted.

The examples will demonstrate how to get the UTC time from NTP server, then update the RTC to make sure the time is perfectly correct.

This [**DS323x_Generic library**](https://github.com/khoih-prog/DS323x_Generic) is based on and modified from [**Hideaki Tai's DS323x Library**](https://github.com/hideakitai/DS323x) to add functions and support to many boards and shields.

**Comment by cmaglie** [comment]
Done.
