### ISSUE TITLE
When wifi shield goes out of network range for a period of time, the tcpServer dies and does not respawn. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1086]
This is [Issue 1086](http://code.google.com/p/arduino/issues/detail?id=1086) moved from a Google Code project.
Added by 2012-10-29T00:03:28.000Z by [k...@vmfarms.com](http://code.google.com/u/111780692553951632186/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Use any of the example sketches that instantiate the WiFiServer that come with the WiFi shield and load it up. ie. WiFiChatServer
2. Take your arduino+wifi shield out of wifi range and leave it there for a few minutes.
3. Take it back in to wifi range and it will be pingable, you'll be able to open a socket to the server, but it will just hang there. You can observe the TCP packets bouncing back and forth and eventually the wifishield disconnects you.

You should expect that when the wifi server is back in range, it will continue to serve new/old established connections.

I did some very superficial debugging and if you output server.status() you'll notice that at some point it returns 0, instead of 1. This is when you know it's dead. I've tried to add code that runs another server.begin(), to no avail. I've even added a new function to restart the server. Again, to no avail. I've yet to dig deeper.

I'm using the Arduino UNO + Arduino Wifi Shield, using 1.0.1 of the IDE in OS X Mountain Lion.

This function does not restart the server as I would expect when it dies, i've yet to debug why:
void WiFiServer::restart()
{
  uint8_t _sock = WiFiClass::getSocket();
  ServerDrv::startServer(_port, _sock);
}

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#19
