### ISSUE TITLE
Wrong USB to serial chip in Mega 2560 pinout diagram

### ISSUE THREAD

**Issue by oqibidipo** [arduino/Arduino#10867]
https://store.arduino.cc/arduino-mega-2560-rev3 > Documentation > Pinout Diagram
https://content.arduino.cc/assets/Pinout-Mega2560rev3_latest.pdf pages 1 and 2

These have ATmega32u4 instead of 16u2 as the USB to serial chip.
Page 4 of the PDF is correct.

**Comment by FunzioneFabio** [comment]
Hello @oqibidipo ! Thank you so much for reporting this! The pinout is now corrected and uploaded on the website.
https://content.arduino.cc/assets/Pinout-Mega2560rev3_latest.pdf
