### ISSUE TITLE
SoftwareSerial invers logic doesn´t work with Seeduino XIAO

### ISSUE THREAD

**Issue by Flying-Bolt** [arduino/Arduino#10884]
SoftwareSerial invers logic doesn´t work with Seeduino XIAO in single wire mode (Half Duplex)

#include <SoftwareSerial.h>

const byte rxPin = 0;
const byte txPin = 0;
SoftwareSerial mySerial (rxPin, txPin, true);

no signal on PIN 0

**Comment by per1234** [comment]
This issue tracker is only for bug reports and feature requests related to the official Arduino projects. The boards platform of your Seeeduino XIAO is a 3rd party project maintained by Seeed Studio:
https://github.com/Seeed-Studio/ArduinoCore-samd
so bug reports about it are off topic here.
