### ISSUE TITLE
[Library Manager] Library add request

### ISSUE THREAD

**Issue by protocentralashwin** [arduino/Arduino#10899]
Please add our new library to the library manager:

https://github.com/Protocentral/protocentral_mlx90632_arduino

**Comment by per1234** [comment]
Hi @protocentralashwin. Thanks for your interest in contributing to the Arduino Library Manager index!

I get a 404 error from that URL. Is the repository private?

**Comment by protocentralashwin** [comment]
Thank you @per1234 . I'm sorry, it was private, I've made it public now.

**Comment by cmaglie** [comment]
Done.
