### ISSUE TITLE
\arduino-1.5\hardware\tools\avr\bin\avr-ar: WInterrupts.c.o: No such file or directory  [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1089]
This is [Issue 1089](http://code.google.com/p/arduino/issues/detail?id=1089) moved from a Google Code project.
Added by 2012-10-31T12:34:06.000Z by [Flamek...@gmail.com](http://code.google.com/u/112465237133662005088/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

1.i can easy velidate the program and such
but i get this error 

\arduino-1.5\hardware\tools\avr\bin\avr-ar: WInterrupts.c.o: No such file or directory

tried to change directory reinstall even tried the beta 1.5 and i still get this problem

even treide to copy the arduino folder from my freinds computer where the program works 

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

I use 1.01 version for Windows im running windows 7 os

Board Arduino UNO

**Comment by ffissore** [comment]
Can't reproduce
