### ISSUE TITLE
[Library Manager] Request to add a library

### ISSUE THREAD

**Issue by ChrisDinhNZ** [arduino/Arduino#10898]
Request to add the following to the Library Manager:
https://github.com/ChrisDinhNZ/SMoS-cpp

**Comment by cmaglie** [comment]
Done.

**Comment by njh** [comment]
@ChrisDinhNZ looks like this repo has now been deleted.

Any background about why?

**Comment by ChrisDinhNZ** [comment]
@njh Apologies, should be back to normal now?

**Comment by njh** [comment]
Yup, repo is back! There is a link in that repo to this, which is a 404:
https://github.com/ChrisDinhNZ/SMoS

**Comment by ChrisDinhNZ** [comment]
Yep, hopefully all link should be working. Cheers for pointing that out.
