### ISSUE TITLE
[Library Manager]  Please Add ERM19264_UC1609 library

### ISSUE THREAD

**Issue by gavinlyonsrepo** [arduino/Arduino#10909]
Hello,

Please add ERM19264_UC1609 library v1.0.0 to library manager

Source: https://github.com/gavinlyonsrepo/ERM19264_UC1609
Tag: https://github.com/gavinlyonsrepo/ERM19264_UC1609/releases/tag/1.0.0

* Name : ERM19264_UC1609.
* Title : Library for ERM19264-5 v3 LCD  (UC1609C controller) for the Arduino eco-system.
* There is no other library which supports this LCD in the manager index  for this display, AFAIK.

Thank You!

**Comment by cmaglie** [comment]
Done.
