### ISSUE TITLE
in the ide,unable to comment use chinese imd. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1090]
This is [Issue 1090](http://code.google.com/p/arduino/issues/detail?id=1090) moved from a Google Code project.
Added by 2012-10-31T13:38:53.000Z by [kik888](http://code.google.com/u/kik888/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

hi guys,arduino is very cool,but it's little bug for our chinese user.

**What steps will reproduce the problem?**
1.open the ide,try to type something
2.now swith the ime,like chinese ime
3.type show but nothing in the ide

**What is the expected output? What do you see instead?**
before the Arduino 018,everything just fine..so how can we return to fine

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arudino 1.0

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Solving in #3019

**Comment by ffissore** [comment]
Fixed in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
