### ISSUE TITLE
[Library Manager] Pls. add new library

### ISSUE THREAD

**Issue by tuxedo0801** [arduino/Arduino#10901]
Pls. add https://gitlab.com/konnekting/KonnektingFlashStorage

The first release is tagged: https://gitlab.com/konnekting/KonnektingFlashStorage/-/tags/1.0.0
... and released: https://gitlab.com/konnekting/KonnektingFlashStorage/-/releases/1.0.0

**Comment by cmaglie** [comment]
Done.
