### ISSUE TITLE
[Library Manager] Request to add new library

### ISSUE THREAD

**Issue by MrYsLab** [arduino/Arduino#10913]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
Hi. Please this library to the library manager:
[https://github.com/MrYsLab/Telemetrix4Arduino](https://github.com/MrYsLab/Telemetrix4Arduino)

Thanks.

**Comment by MrYsLab** [comment]
@per1234 
Hi. I was not sure if there was an issue with the library or not, but rechecking the library.properties file, I realized that the URL was incorrect and I have corrected it. If there are any other issues that need correction, please let me know. 
Thanks.

**Comment by MrYsLab** [comment]
I have bumped the release number and removed keywords.txt which was unused. Please let me know if I need to make any changes to have this published to the library manager. Thanks.

**Comment by cmaglie** [comment]
Done.
