### ISSUE TITLE
[Library Manager] Please add SparkFun ADXL313 Arduino Library

### ISSUE THREAD

**Issue by lewispg228** [arduino/Arduino#10916]
Hi there,
When you have a chance, please add the new SparkFun_ADXL313_Arduino_Library to the Library Manager. 

https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library

Thanks!

**Comment by cmaglie** [comment]
Done.

**Comment by lewispg228** [comment]
Thank you very much @cmaglie !!
