### ISSUE TITLE
Suggestion: Serial monitor having option to select the port independently.

### ISSUE THREAD

**Issue by rtek1000** [arduino/Arduino#10920]
Hello,

I would like to suggest that the serial monitor has an option to select the port independently of the board.

Many boards currently have a network interface and as the OTA system does not yet include serial monitoring virtualization, so the user can choose which port to use on the serial monitor, while using OTA to upload the sketches.

Thank you.

![Serial_Monitor](https://user-images.githubusercontent.com/8660811/98138755-30f79800-1ea2-11eb-8e14-d6e08cdd904c.png)

**Comment by per1234** [comment]
Thanks for your suggestion @rtek1000! It looks like between https://github.com/arduino/Arduino/issues/5554 and https://github.com/arduino/Arduino/issues/7247 we already have existing issues requesting this functionality so I'll go ahead and close this. You're welcome to comment on the relevant issue if you have additional information to add.
