### ISSUE TITLE
TLC59711 will not run on Arduino Nano Every

### ISSUE THREAD

**Issue by mharriman101** [arduino/Arduino#10926]
Board: Arduino Nano Every
Peripheral: Adafrut TLC59711
Library:  Adafruit_TLC59711
Software: Desktop Install on Win 10 - Arduino 1.8.13

Running supplied test code: Test_TLC59711.ino 
Board resets at setup() - tlc.write().  
Serial output is "TLCTLCTLC" repeating forever as it is trying to send the string "TLC59711 test".
Same code works fine with Arduino Uno.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
