### ISSUE TITLE
[Library Manager] Please add Pixetto library.

### ISSUE THREAD

**Issue by pixetto** [arduino/Arduino#10943]
Please add Pixetto library to Library Manager.
[https://github.com/pixetto/Pixetto](https://github.com/pixetto/Pixetto)
Thanks.

**Comment by per1234** [comment]
Hi @pixetto. Thanks for your interest in contributing to the Arduino Library Manager index!

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by pixetto** [comment]
I added a tag "1.4.0".
Please check it again.
I am sorry for my carelessness.

**Comment by cmaglie** [comment]
Done.
