### ISSUE TITLE
[Boards Manager] Don't reset the 'Type' from "Updatable" to "All" after updating a platform [BUG]

### ISSUE THREAD

**Issue by lnlp** [arduino/Arduino#10968]
### Problem
After updating a platform in Boards Manager, the value of the 'Type' dropdown changes from "Updatable" to "All".
This is incorrect and makes updating multiple platforms cumbersome and annoying because this way one has to instruct the Boards Manager every time to list only updatable platforms for/after each single platform update.

_This issue is similar to issue #10767 but now for Boards Manager._

### How to reproduce
- Open Boards Manager
- Select Type: "Updatable"
- Then update any of the updatable platforms listed.

After the platform is updated the Boards Manager dialog's 'Type' dropdown selection will have changed from "Updatable" to "All" which is incorrect (bug).

### How to fix
After updating a platform the 'Type' value "Updatable" should stay unchanged and only updatable platforms should be listed.

### Tested version
- `Arduino IDE 1.8.13 (Windows)`

**Comment by cmaglie** [comment]
The fix for this issue is already on `master` and will be released for 1.8.14.
