### ISSUE TITLE
Remove LIDAR-Lite v4 Arduino library by SparkFun and replace with new library 

### ISSUE THREAD

**Issue by pmakin-png** [arduino/Arduino#10969]
Hi there,

Can you please remove "LIDAR-Lite v4 Arduino Library" by SparkFun Electronics from the Arduino library manager and please add this library instead:

https://github.com/sparkfun/SparkFun_LIDARLitev4_Arduino_Library

Thanks so much!

**Comment by cmaglie** [comment]
Done.
