### ISSUE TITLE
adding libraries for AD5941

### ISSUE THREAD

**Issue by fereshtehshah** [arduino/Arduino#10983]
I wonder if you could add libraries for AD5940/41. 
here is the URL: 
https://github.com/analogdevicesinc/ad5940-examples

Thank you
Fereshteh

**Comment by per1234** [comment]
Hi @fereshtehshah. None of the code in that repository, or even the submodule (which aren't supported by the Arduino Library Manager indexer) are in the correct format to be used with Arduino.

Here is the Arduino Library Specification:
https://arduino.github.io/arduino-cli/latest/library-specification/
and the Arduino Sketch Specification:
https://arduino.github.io/arduino-cli/latest/sketch-specification/

Here is all the information about the requirements for adding a library to the Arduino Library Manager index:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

If you are able to bring your project into compliance and create a tag or release, please comment here and I'll reopen the issue so we can get that library added to the Library Manager index.
