### ISSUE TITLE
Explore IoT Kit Lesson 4 #include <Arduino_MKRIoTCarrier.h>  'r' not declare in this scope

### ISSUE THREAD

**Issue by Bryanr26** [arduino/Arduino#10988]
I am working through Lesson 4 in the Explore IoT Kit. Following the code and Dashboard instructions closely. 
I am getting     'r' not declared in this Scope  that also goes for the other variables g & b   when executing this code and the library  #include <Arduino_MKRIoTCarrier.h>. I need help... can you help me. 
```
void onSoundDurationChange() {
  // Do something
  rgb.getValue().getRGB(r, g, b);
  if (rgb.getSwitch()){
    for (int i=0; i < 5; i++)
  {
      carrier.leds.setPixelColor(i,g,r,b);
    }
    carrier.leds.show();
  }
  else {
    for (int i = 0; i< 5; i++)
    {
      carrier.leds.setPixelColor(i,0);
    }
   carrier.leds.show();
  }
}
```

EDIT by @per1234:
Also reported at https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/commit/e3b3f4f79c1653fb19245d1f6e78026d115538e3#commitcomment-44433617

**Comment by GDJose** [comment]
@Bryanr26 you are lacking a line of code inside the onRgbChange() function.
The line in which you declare the "r", "g" and "b" variables --> uint8_t r, g, b;
There was an issue with the snippet shown in the platform, but it is fixed now, Thanks for your report! :)
