### ISSUE TITLE
[Library Manager] Please add LiveObjectsSDK 

### ISSUE THREAD

**Issue by Kacp3r3** [arduino/Arduino#10998]
Hello.
LiveObjectsSDK is a library which allows to easy connect and work with Orange LiveObjects iot cloud.
Library was developed by Orange.
It currently support most of Arduino MKR family, esp8266, esp32 and also a few Adafruit boards.

Link to sources
https://github.com/DatavenueLiveObjects/LiveObjects_SDK_for_Arduino

**Comment by cmaglie** [comment]
Done.
