### ISSUE TITLE
[Library Manager] Change of Library Name and URL

### ISSUE THREAD

**Issue by mrfaptastic** [arduino/Arduino#11008]
Hello, a popular Arduino library I maintain is having a name change, it is currently listed in the Library Manager as:
```
ESP32-RGB64x32MatrixPanel-I2S-DMA
https://github.com/mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA.git
```

It is now:
```
ESP32-HUB75-MatrixPanel-I2S-DMA
https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA
```

Please kindly update the Arduino library manager master list. Thank you.

**Comment by cmaglie** [comment]
Done.
