### ISSUE TITLE
[Library Manager] Please update our Inkplate library

### ISSUE THREAD

**Issue by nitko12** [arduino/Arduino#11002]
Hi

Could you please update our Inkplate library to version 1.1.0.
https://github.com/e-radionicacom/Inkplate-Arduino-library

Thanks

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time. In fact, I see that the 1.1.0 release of your library is already available for me from Library Manager:
![Clipboard01](https://user-images.githubusercontent.com/8572152/100480652-bc7dd680-30a6-11eb-8ae2-480b1e60f823.png)

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
