### ISSUE TITLE
[Library Manager] Please add WiThrottle library

### ISSUE THREAD

**Issue by lucadentella** [arduino/Arduino#11001]
Hi

Could you please add my WiThrottle library:
https://github.com/lucadentella/WiThrottle/

It's a library which implements the [WiThrottle protocol](https://www.jmri.org/help/en/package/jmri/jmrit/withrottle/Protocol.shtml), to communicate with model railways applications (designed by JMRI but adopted also by other manufacturers).

Thanks

**Comment by cmaglie** [comment]
Done.
