### ISSUE TITLE
[Library Manager] Question

### ISSUE THREAD

**Issue by gmarty2000** [arduino/Arduino#11003]
Hello, last year I asked you to add some libraries into the "Library Manager" (the request was accepted).
Now I would like to migrate them to another account, and still keep their URLs in the "Library Manager".
What kind of information do you need to update library's URLs?

**Comment by per1234** [comment]
Hi @gmarty2000. Please just let us know the old and the new URL of each library's repository.

**Comment by gmarty2000** [comment]
Thanks for the quick response! Here is the list of OLD and NEW library URLs.
|OLD|NEW|
|---|---|
|https://github.com/gmarty2000/arduino-BUZZER|https://github.com/gmarty2000-ARDUINO/arduino-BUZZER|
|https://github.com/gmarty2000/arduino-JOYSTICK|https://github.com/gmarty2000-ARDUINO/arduino-JOYSTICK|
|https://github.com/gmarty2000/arduino-ULTRASONIC_SENSOR|https://github.com/gmarty2000-ARDUINO/arduino-ULTRASONIC_SENSOR|
|https://github.com/gmarty2000/arduino-SOIL_HYGROMETER|https://github.com/gmarty2000-ARDUINO/arduino-SOIL_HYGROMETER|

**Comment by cmaglie** [comment]
Done.

**Comment by gmarty2000** [comment]
Thank you so much
