### ISSUE TITLE
[Library Manager] add AceCRC library to Arduino Library Manager

### ISSUE THREAD

**Issue by bxparks** [arduino/Arduino#11019]
Please add
https://github.com/bxparks/AceCRC
to the Arduino Library Manager. Thx!

sentence=Cyclic Redundancy Check (CRC) algorithms (e.g. crc32(), crc16ccitt()) that have been programmatically converted from pycrc (https://pycrc.org/) to Arduino to use C++ namespaces and PROGMEM flash memory.
paragraph=For each algorithm, 3 implementation variants have been generated: The 'bit' variant uses brute force bit-by-bit loop (smallest and slowest); the 'nibble' variant uses a 4-bit table (potentially good balance between size and speed); the 'byte' variant uses an 8-bit table (largest but fastest).

**Comment by cmaglie** [comment]
Done.
