### ISSUE TITLE
[Library Manager] Request to add new "HomeSpan" Apple HomeKit library to the Arduino Library Manager

### ISSUE THREAD

**Issue by HomeSpan** [arduino/Arduino#11012]
I have written a library named **HomeSpan** I'd like contribute to the Arduino community through the Arduino Library Manager.  The library is hosted on GitHub at: https://github.com/HomeSpan/HomeSpan

My intro to the library (from library.properties):

* A robust and extremely easy-to-use HomeKit implementation for the Espressif ESP32 running on the Arduino IDE.

Details:

* HomeSpan provides a scratch-built, microcontroller-focused implementation of Apple's HomeKit Accessory Protocol (HAP - Release R2) designed specifically for the ESP32 running on the Arduino IDE. 
* HomeSpan pairs directly to the iOS Home App  via WiFi without the need for any external bridges or components.
* Developers can use the full power of the ESP32's I/O functionality to create custom control software and/or hardware to operate external devices.
* HomeSpan is exhaustively documented and includes 16 heavily-annotated tutorial sketches.

Thanks in advance for the consideration.

**Comment by cmaglie** [comment]
Done.
