### ISSUE TITLE
Website - Example Code Error - Library Documentation - Arduino_MKRIoTCarrier - IMU Sensor Example

### ISSUE THREAD

**Issue by alexandru-cohal** [arduino/Arduino#11010]
The documentation of the _Arduino_MKRIoTCarrier Library_ is available on this page: [https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/](https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/)

In the _"IMU - LSM6DS3"_ section, the syntax example contains the following command for reading the acceleration values:
```
carrier.IMUmodule.getAcceleration(aX, aY, aZ);
```
which generates the following error:
```
error: 'class LSM6DS3Class' has no member named 'getAcceleration'; did you mean 'readAcceleration'?
```
As suggested in the error and also explained in the documentation of the [LSM6DS3 library](https://www.arduino.cc/en/Reference/Arduino_LSM6DS3) of the IMU sensor (the link to this library documentation is also provided in the same section, _"IMU - LSM6DS3"_, of the _Arduino_MKRIoTCarrier Library_ page), the _getAcceleration_ method should be replaced with the _readAcceleration_ method.

I am using the _Arduino Web Editor_ with the _Arduino_MKRIoTCarrier Library_ version _0.9.6_.

**Comment by marqdevx** [comment]
Thanks! @alexandru-cohal
