### ISSUE TITLE
Website - Example Code Error - Library Documentation - Arduino_MKRIoTCarrier - Pressure Sensor Example

### ISSUE THREAD

**Issue by alexandru-cohal** [arduino/Arduino#11011]
The documentation of the _Arduino_MKRIoTCarrier Library_ is available on this page: [https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/](https://www.arduino.cc/reference/en/libraries/arduino_mkriotcarrier/)

In the _"Pressure sensor - LPS22HB (Barometric)"_ section, the syntax example contains the following command for reading the pressure value:
```
pressure = carrier.Light.readPressure()
```
which generates the following error:
```
error: 'class APDS9960' has no member named 'readPressure'; did you mean 'readGesture'?
```
Based on the header file of the [Arduino_MKRIoTCarrier Library](https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/blob/master/src/Arduino_MKRIoTCarrier.h), the class member related with the pressure sensor is _Pressure_ and not _Light_. So, the command should be replaced with:
```
pressure = carrier.Pressure.readPressure();
```

I am using the _Arduino Web Editor_ with the _Arduino_MKRIoTCarrier Library_ version _0.9.6_.

**Comment by marqdevx** [comment]
Thanks! @alexandru-cohal
