### ISSUE TITLE
[Library Manager] Add TelemetryJet library

### ISSUE THREAD

**Issue by chrisdalke** [arduino/Arduino#11015]
Hello, 

Could you please add the following library to the Library Manager: https://github.com/telemetryjet/telemetryjet-arduino-sdk

The TelemetryJet Arduino SDK is a lightweight communication library based on MessagePack that's designed to be easy for beginners to use, and supports some high-level functionality like a key/value cache and subscriptions.

Thanks!

**Comment by cmaglie** [comment]
Done.
