### ISSUE TITLE
Add libraries from pilotak to LibraryManager

### ISSUE THREAD

**Issue by pilotak** [arduino/Arduino#11034]
Please add following libraries to the manager

- [x] https://github.com/pilotak/MCP3X21
- [x] https://github.com/pilotak/LPS35HW
- [x] https://github.com/pilotak/MovingAverageFloat
- [x] https://github.com/pilotak/MovingAverageAngle
- [x] https://github.com/pilotak/MovingAverage
- [x] https://github.com/pilotak/MeteoFunctions
- [x] https://github.com/pilotak/Hysteresis
- [x] https://github.com/pilotak/WeatherMeters

**Comment by pilotak** [comment]
two more
https://github.com/pilotak/Hysteresis
https://github.com/pilotak/WeatherMeters

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
