### ISSUE TITLE
[Library Manager] Please refresh the SparkFun_Ublox_Arduino_Library

### ISSUE THREAD

**Issue by PaulZC** [arduino/Arduino#11039]
Hi @cmaglie / @per1234 ,

Can you please refresh the library manager entry for the SparkFun_Ublox_Arduino_Library?

We changed the "name" from ```name=SparkFun Ublox Arduino Library``` to ```name=SparkFun u-blox Arduino Library``` and the library manager seems to have become stuck at version **1.8.6**. We're now at **1.8.8**.

The URL is still ```url=https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library```. That hasn't changed.

Sincere thanks,

Paul & Nathan

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
