### ISSUE TITLE
[Library Manager]  Moved  existing "MicrochipSRAM" library from "SV-Zanshin" to "Zanduino"

### ISSUE THREAD

**Issue by SV-Zanshin** [arduino/Arduino#11049]
The library "MicrochipSRAM" has been moved from https://github.com/SV-Zanshin to https://github.com/Zanduino.

The contents up the library.properties file have been updated and a new version tag created for this move.

Many thanks,

-Arnd.

**Comment by cmaglie** [comment]
Done.
