### ISSUE TITLE
[Library Manager] Please add ptScheduler Task Scheduler Library

### ISSUE THREAD

**Issue by vishnumaiea** [arduino/Arduino#11040]
**Pretty tiny Scheduler** or **ptScheduler** is a non-preemptive task scheduler for Arduino that helps you to write **non-blocking periodic tasks** easily and effectively without using ordinary delay routines or millis() on your own.

https://github.com/vishnumaiea/ptScheduler

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
