### ISSUE TITLE
[Library Manager] Please add TinyInstruments to Library Manager 

### ISSUE THREAD

**Issue by montoyamoraga** [arduino/Arduino#11041]
https://github.com/montoyamoraga/TinyTrainable

thanks!

**Comment by per1234** [comment]
Hi @montoyamoraga. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by montoyamoraga** [comment]
hi @per1234, i think i just did, is that correct?
thank you :)

**Comment by cmaglie** [comment]
Done. sorry for the long delay!
