### ISSUE TITLE
Arduino IDE 1.8.12 crashes on macOS 10.15.5 when NOT clicking the scroll bar

### ISSUE THREAD

**Issue by jhihn** [arduino/Arduino#11054]
I am experiencing numerous crashes, I can barely use the IDE. They all come back to this though:

> Process:               Arduino [21359]
> Path:                  /Applications/Arduino.app/Contents/MacOS/Arduino
> Identifier:            cc.arduino.Arduino
> Version:               1.8.12 (1.8.12)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Arduino [21359]
> User ID:               501
> 
> Date/Time:             2020-12-10 10:33:38.672 -0500
> OS Version:            Mac OS X 10.15.6 (19G2021)
> Report Version:        12
> Bridge OS Version:     4.6 (17P6610)
> Anonymous UUID:        937F0F88-5143-B492-C93E-4DF2C3E56511
> 
> Sleep/Wake UUID:       0D78C500-BEC8-4583-8BBA-42CD225C9288
> 
> Time Awake Since Boot: 270000 seconds
> Time Since Wake:       2000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        35  Java: Java2D Queue Flusher
> 
> Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)
> Exception Codes:       0x0000000000000001, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> -[NSOpenGLContext setView:] must be called from the main thread.

My setup is a 16" 2019 MBP, with 2 external 4k monitors attached over HDMI.
This reliably happens when I drag the window from the built in panel to an external one.
It happens at other times, seemingly randomly, I don't know what triggers it when not moving between monitors.
Clicking the scroll bar does not trigger it.

This seems to be a bug in Java2D Queue Flusher. I'm. not sure what can be done but it makes Arduino on mac painful.

**Comment by facchinm** [comment]
Hi @jhihn ,
the issue was fixed in IDE 1.8.13, please update and report back if it still happens! Thanks
