### ISSUE TITLE
Please add our library to interface with SFM10R4 modems

### ISSUE THREAD

**Issue by paulporto** [arduino/Arduino#11051]
Please add our library to control and communicate with SFM10R4 modems
https://github.com/TECA-IOT/Tinyfox
thank you

**Comment by per1234** [comment]
Thanks for your interest in contributing to the Arduino Library Manager index @paulporto.

Before we can add your library, you need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by paulporto** [comment]
im sorry, my partner was slow. its released now
thanks

**Comment by paulporto** [comment]
its everything ok now? we are exited for this to be part of the official repo, if there is any problem please write to us. thank you.

**Comment by cmaglie** [comment]
Done.
