### ISSUE TITLE
Library mrm-common published under a wrong name

### ISSUE THREAD

**Issue by PribaNosati** [arduino/Arduino#11057]
I made a mistake in my initial commit, naming library mrm-common wrongly as mrm-can-common so the library managed doesn't update new versions. Reading the remedy, I deleted tag of the faulty commit, made a correct one, and tagged it as version 0.0.7. Can You update? URL: https://github.com/pribaNosati/mrm-common .

**Comment by cmaglie** [comment]
Done.
