### ISSUE TITLE
[Library Manager] Please add WIOTerminal_WiFiManager Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#11066]
Please add [**WIOTerminal_WiFiManager library**](https://github.com/khoih-prog/WIOTerminal_WiFiManager) to Library Manager.

Thanks and Regards.

---

## Features

This is a WiFi Connection manager with fallback web ConfigPortal. It's using a WebServer ConfigPortal, served from the `SeeedStudio SAMD51 WIO-Terminal`, and operating as an access point.

---
---

### Releases v1.2.0

1. Initial Coding for **WIO Terminal**. Sync with [**ESP_WiFiManager v1.2.0**](https://github.com/khoih-prog/ESP_WiFiManager)

#### Supported Boards

  - **SeeedStudio SAMD51 WIO-Terminal**

**Comment by cmaglie** [comment]
Done.
