### ISSUE TITLE
Arduino-IDE 1.8.13 how to change color of braces  () [] {}  they stay black

### ISSUE THREAD

**Issue by StefanL38** [arduino/Arduino#11084]
Hi everybody,

I want to modify the theme of the Arduino-IDE to a more real old-style editor-theme with dark backround.

I tried to find the identifier for braces () \[\] {}  because they stay black. I didn't find any identifier in the theme.txt-file that would be related to the braces. 

I even tried to use a dark-theme from version 1.8.12 where braces are white in the dark theme. Same result in the version 1.8.13 the braces are black.

Is it possible that the braces simply have been forgotten to assign a color?

As long as the backround-color is white a constant black color makes the braces perfectly visible  but not on a dark backround color.

The process of 

*   changing a hexadecimal color-value in this theme.txt-file 
*   re-starting the IDE to watch the result

is very uncomfortable and time-comsuming

I tried to find a complete list or explanation of all the items but I did'nt find anything yet.

So I'm asking here for advice. 

best regards Stefan

**Comment by per1234** [comment]
I see from the associated forum post that @StefanL38 was successful in finding this theme property:
https://forum.arduino.cc/index.php?topic=718917.msg4830165#msg4830165
>So the color of the braces is in the default.xml.
>```
><style token="SEPARATOR" fg="ffffff" />
>```

We already have an issue requesting that the Arduino IDE theme be made easier to modify, or at least have official documentation: https://github.com/arduino/Arduino/issues/6454 so I'll go ahead and close this as resolved.
