### ISSUE TITLE
[Library Manager] Change Github URL for the Embedded Template Library

### ISSUE THREAD

**Issue by jwellbelove** [arduino/Arduino#11086]
I need to change the Github URL for the **Embedded Template Library** from 

https://github.com/ETLCPP/etl.git

to 

https://github.com/ETLCPP/etl-arduino.git

**Comment by jwellbelove** [comment]
The original ETL repository now has a directory layout that is incompatible with the Arduino library manager.
The alternative Github repository also removes the unit test code, so reducing the download size.

**Comment by cmaglie** [comment]
Done.
