### ISSUE TITLE
Editor doesn't let me type in OSX [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1108]
This is [Issue 1108](http://code.google.com/p/arduino/issues/detail?id=1108) moved from a Google Code project.
Added by 2012-11-10T17:06:45.000Z by [Azer...@gmail.com](http://code.google.com/u/101727985085911552967/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Trying to type in textarea
-nothing happens

JTextArea seems to be in read only mode.
Please fix.

**Comment by ffissore** [comment]
Closing for lack of feedback
