### ISSUE TITLE
Call a function in the same file not working. How i can call it?

### ISSUE THREAD

**Issue by Trackhe** [arduino/Arduino#11093]
```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
test();

void test(){
}
```

error: 
```
sketch_dec22a:10:7: error: expected constructor, destructor, or type conversion before ';' token
 test();
       ^
exit status 1
expected constructor, destructor, or type conversion before ';' token
`
``

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
