### ISSUE TITLE
[Library Manager] GDXLib

### ISSUE THREAD

**Issue by dvernier** [arduino/Arduino#11092]
https://github.com/dvernier/GDXLib/releases/tag/0.90

**Comment by cmaglie** [comment]
@dvernier I've added the library but there is a problem, the library.properties file looks corrupted:

https://github.com/dvernier/GDXLib/blob/0.90/library.properties

it seems that all the line endings have been changed to `^M` (that is not a valid line ending for any OS!).
It's the first time that this happens I would suggest the following procedure to fix it:

1. completely remove the library.properties and rewrite it from scratch
2. I suppose that the version of the lib is `0.9.0` and not `0.90` as you wrote? if this is the case change also the version number inside library.properties
3. commit & push
4. delete and redo the git tag 0.9.0

once done the library should be published automatically within an hour.
Feel free to comment here if you need further assistance.
