### ISSUE TITLE
[Library Manager] please add TactileSwitch library

### ISSUE THREAD

**Issue by IGB-Germany** [arduino/Arduino#11091]
Please add our new library to the library manager:

https://github.com/IGB-Germany/IGB-Tactile-Switch

Thank you !

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem, the `depends` field in the `library.propeties` file is set to `*`:
https://github.com/IGB-Germany/IGB-Tactile-Switch/blob/master/library.properties#L10

this is wrong.
To fix it:

1) remove the `depends=*` line from `library.properties`
2) commit & push
3) delete the 1.0.0 tag and redo it on `master`

once done the library will be published within an hour, our indexer will check the repo automatically.
