### ISSUE TITLE
Please add RevEng_PAJ7620 library

### ISSUE THREAD

**Issue by acrandal** [arduino/Arduino#11094]
Dear Arduino team -

Thank you for your hard work. I've been very pleased with the Arduino platform for several years now and I definitely value your efforts to keep bringing everyone these great tools.

I've pulled together a library for the PixArt PAJ7620 (U2 & F2) sensor forked from the Seeed library, but with significantly more features, bugfixes, and OOP principles. Please have a look at my latest 1.3.0 release for addition into the Arduino IDE/CLI libraries here: [https://github.com/acrandal/RevEng_PAJ7620](https://github.com/acrandal/RevEng_PAJ7620).

Thank you - Crandall

**Comment by cmaglie** [comment]
Done.
