### ISSUE TITLE
Add local sketch library support

### ISSUE THREAD

**Issue by forkineye** [arduino/Arduino#11106]
### Feature Request ###
It would be nice if the IDE could enumerate a local sketch library structure and give it precedence to the global library folder.  This would allow larger projects to easily employ git submodules to ensure that all developers are on the same version of libraries.  All dependencies should first be checked in the local library folder.  The directory structure could mimic the global library directory structure.

### Example for MySketch.ino ###
```
\Arduino\MySketch\
\Arduino\MySketch\MySketch.ino
\Arduino\MySketch\libraries\
\Arduino\MySketch\libraries\MyLibrary\     # This is one is used
\Arduino\libraries\
\Arduino\libraries\MyLibrary               # This one is skipped
```

**Comment by per1234** [comment]
Thanks for your feature request @forkineye. We have a previous issue about this: https://github.com/arduino/Arduino/issues/7755

Since it's better to concentrate all the discussion for each distinct topic to a single issue, I'll go ahead and close this as a duplicate.
