### ISSUE TITLE
[Library manager] This library just got updated!

### ISSUE THREAD

**Issue by vittorioexp** [arduino/Arduino#11102]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

This library just got updated, v1.1.8
[https://github.com/vittorioexp/Sim800L-Arduino-Library-revised](https://github.com/vittorioexp/Sim800L-Arduino-Library-revised)

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time. In fact, I already see your 1.1.8 release in my Library Manager (though it might not yet be available everywhere).

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
