### ISSUE TITLE
[Library Manager] Please add ESP_MultiResetDetector Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#11115]
Please add [**ESP_MultiResetDetector library**](https://github.com/khoih-prog/ESP_MultiResetDetector) to Library Manager.

Thanks and Regards.

---
---

#### Features

[**ESP_MultiResetDetector**](https://github.com/khoih-prog/ESP_MultiResetDetector) is a library for the **ESP8266 and ESP32** boards to detects a **configurable multi reset**, within configurable timeout (default 10s) seconds, so that an alternative start-up mode can be used. Example use cases are to allow re-configuration of a device's WiFi / MQTT / Blynk credentials or to count the number of resets within a pre-determined timed.

This library is based on, modified, bug-fixed and improved from

1. [`Stephen Denne's DoubleResetDetector`](https://github.com/datacute/DoubleResetDetector)
2. [`ESP_DoubleResetDetector`](https://github.com/khoih-prog/ESP_DoubleResetDetector)

to add multiple reset detection support to ESP8266 and ESP32 using EEPROM, SPIFFS and LittleFS besides original RTC.

This library can be used to detect a **multi reset within a predetermined time to force the program to enter a special operation** such as Config Portal, Clear Default Data, etc., using :

1. EEPROM, SPIFFS or LittleFS for ESP8266 and ESP32 boards.
2. RTC memory for ESP8266 boards (unadvised).

#### Currently supported Boards

This [**ESP_MultiResetDetector** library](https://github.com/khoih-prog/ESP_MultiResetDetector) currently supports these following boards:

 1. **ESP32 boards using EEPROM, SPIFFS or LittleFS**.
 2. **ESP8266 boards RTC memory, EEPROM, SPIFFS or LittleFS**

---
---

### Releases v1.1.1

1. Initial coding to support Multiple Reset Detection.
2. Sync with ESP_DoubleResetDetector v1.1.1

**Comment by cmaglie** [comment]
Done.
