### ISSUE TITLE
[Library Manager] Please add the following libraries to the Arduino library manager

### ISSUE THREAD

**Issue by 0015** [arduino/Arduino#11114]
Hi,
Please add the following library to Arduino Library manager.

https://github.com/0015/TP_Arduino_DigitalRain_Anim

Thanks in advance

**Comment by cmaglie** [comment]
Done, the library is now published but I see a problem, in the release tag 1.1.0 you forget to update the version in library.properites:

```
JOB 3611 - 2021/01/09 00:02:44 Scraping https://github.com/0015/TP_Arduino_DigitalRain_Anim.git
JOB 3611 - 2021/01/09 00:02:46 Checking out tag: 1.0.0
JOB 3611 - 2021/01/09 00:02:47 path=github.com/0015, archivename=Digital_Rain_Animation_for_TFT_eSPI-1.0.0
JOB 3611 - 2021/01/09 00:02:48 Checking out tag: 1.0.1
JOB 3611 - 2021/01/09 00:02:48 Release Digital Rain Animation for TFT_eSPI:1.0.0 already loaded, skipping
JOB 3611 - 2021/01/09 00:02:48 Checking out tag: 1.1.0
JOB 3611 - 2021/01/09 00:02:48 Release Digital Rain Animation for TFT_eSPI:1.0.0 already loaded, skipping
```

this results in the versions 1.0.1 and 1.1.0 being ignored.
To fix this:

1. update the version field in library.properties
2. commit & push
3. delete the tag 1.1.0 and re-do it on the new master

after doing the above the new version will be published automatically within an hour.
Feel free to comment here if you need further assistance.
