### ISSUE TITLE
[Library Manager] Please Add my SPC Library for analog signal processing in Library Manager

### ISSUE THREAD

**Issue by aaryaapg** [arduino/Arduino#11123]
Please add SPC Library for analog signal processing in Library Manager. SPC stands for Square, Peaks and Counts. This library can be used for signal conditioning, where an Analog input is to be analyzed. The analog signal is converted into a square wave based on the threshold value given by the user, and positive edges are counted. It can be used for any analog sensor.

URL: https://github.com/aaryaapg/SPC-Library

Thank You,
Aaryaa Padhyegurjar

**Comment by cmaglie** [comment]
Done.
