### ISSUE TITLE
[library manager] new library EspNow2Mqtt

### ISSUE THREAD

**Issue by eccnil** [arduino/Arduino#11133]
Please add EspNow2Mqtt library to the manager.
It implements both sides of a comunication to mqtt via espnow:
- the client that publish and subscribes via espnow
- the gateway espNow <-> mqtt

Repo: https://github.com/eccnil/ESPNow2Mqtt
Documentation: https://github.com/eccnil/ESPNow2Mqtt

**Comment by cmaglie** [comment]
I've added the library but there is a problem, we do not support yet version pinning in the `depends` field:

```
depends=Nanopb,Crypto@0.2.0,knolleary/PubSubClient
```

you should write it as:

```
depends=Nanopb,Crypto,PubSubClient
```

once changed remember to:
1. commit & push
2. delete and re-do the latest version tag on the new master

once done the library should be published automatically within an hour.
Please comment here if you need further assistance.
