### ISSUE TITLE
USB FTDI driver conflict with Drivers used by EFILive [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1113]
This is [Issue 1113](http://code.google.com/p/arduino/issues/detail?id=1113) moved from a Google Code project.
Added by 2012-11-14T15:54:17.000Z by [bercar%s...@gtempaccount.com](http://code.google.com/u/117115453569525084251/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. If the USB Driver for arduino is installed first, then I can not use or setup the EFILive Scan tool, as it wont be recognized as a USB Device.
1. If the USB Driver for EFILive is installed first, then I can not use or setup the arduino, as it wont be recognized as a USB Device.

**What is the expected output? What do you see instead?**
Both devices should operate, however i can install the drivers for one or the other.  Once one is installed, the only way i was able to get the other to work was after a fresh install of windows. 

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0.2
Windows Vista
Arduino Mega

**Please provide any additional information below.**

**Comment by sandeepmistry** [comment]
I'm closing this as won't fix for now, as there appears to be no further interest.
