### ISSUE TITLE
"Sketch too big" print includes broken link

### ISSUE THREAD

**Issue by yennster** [arduino/Arduino#11140]
Output when sketch is too big for board flash size:

```
Sketch uses 47908 bytes (146%) of program storage space. Maximum is 32768 bytes.
Global variables use 4828 bytes of dynamic memory.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
text section exceeds available space in board
Error compiling for board XMC1300 Sense2GoL.
```

The link `http://www.arduino.cc/en/Guide/Troubleshooting#size` is broken, I am assuming the correct link is: `https://support.arduino.cc/hc/en-us/articles/360013825179-Tips-to-reduce-the-size-of-a-sketch`

**Comment by matthijskooijman** [comment]
This should probably be fixed by reinstating the old URL (possibly as a redirect), to ensure that also older version in the wild will keep working?
