### ISSUE TITLE
Updated Arduino Uno R3 to v1.8.13

### ISSUE THREAD

**Issue by drummer514** [arduino/Arduino#11146]
I recently installed the lastest version of the IDE and it locks up almost every time it detects an error in anything. V1.8.6 never had this problem. Just wondering if anyone else has had this problem?

**Comment by per1234** [comment]
Hi @drummer514. This issue report is too vague for us to be able to investigate. Please follow the contributing guidelines in order to provide a high quality report:
https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md

**Comment by per1234** [comment]
Closing due to lack of response.

@drummer514  if you'll provide the requested information I'll be happy to re-open this issue.
