### ISSUE TITLE
[Feature Request] Ability to know how many times a library was downloaded from library manager 

### ISSUE THREAD

**Issue by SunitRaut** [arduino/Arduino#11147]
This feature would help library creators to know ow many users are using their libraries.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @SunitRaut. We have a previous issue about this: https://github.com/arduino/Arduino/issues/7265

Since it's better to concentrate all the discussion for each distinct topic in a single issue, I'll go ahead and close this as a duplicate.
