### ISSUE TITLE
[Library manager] pcf8574 library for Arduino, esp32, smt32 and esp8266

### ISSUE THREAD

**Issue by xreef** [arduino/Arduino#11171]
Source: https://github.com/xreef/PCF8574_library
Tag: https://github.com/xreef/PCF8574_library/releases/tag/v2.2.2

It's a complete library to interfacing pcf8574 with encoders support

Documentation
ENG: https://www.mischianti.org/category/my-libraries/pcf8574/
ITA: https://www.mischianti.org/it/category/le-mie-librerie/pcf8574-it/

Bye Renzo

**Comment by cmaglie** [comment]
Done.
