### ISSUE TITLE
[Library manager] EByte LoRa E32 library (Arduino, esp32 and esp8266)

### ISSUE THREAD

**Issue by xreef** [arduino/Arduino#11170]
Source: https://github.com/xreef/LoRa_E32_Series_Library
Tag: https://github.com/xreef/LoRa_E32_Series_Library/releases/tag/v1.5.0

It's a complete library to interfacing EByte LoRa E32 device (from 3km to 8km)

Documentation
ENG: https://www.mischianti.org/category/my-libraries/lora-e32-devices/
ITA: https://www.mischianti.org/it/category/le-mie-librerie/dispositivi-lora-e32/

Bye Renzo

**Comment by cmaglie** [comment]
Done.
