### ISSUE TITLE
[Library Manager] Please add MeteoLabBeacon.

### ISSUE THREAD

**Issue by vladimir-chukin** [arduino/Arduino#11182]
Please add the MeteoLabBeacon library to the library manager:

https://github.com/meteolab/MeteoLabBeacon

Arduino library for Bluetooth Low Energy (BLE) environmental sensor communication using the nRF24L01+

**Comment by per1234** [comment]
Hi @vladimir-chukin. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by vladimir-chukin** [comment]
Thank you for the detailed information. Release is created.

**Comment by cmaglie** [comment]
Done.
