### ISSUE TITLE
[Library Manager] Jeager-One Library

### ISSUE THREAD

**Issue by mchwalfajar** [arduino/Arduino#11186]
**Please add**: https://github.com/mchwalfajar/jeager-one

About this library:
This library is used to transmit sensor data with LoRa, WiFi, and GSM connections

Thanks,
mchwalfajar

**Comment by per1234** [comment]
Hi @mchwalfajar. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by mchwalfajar** [comment]
hi @per1234 done, thanks

**Comment by cmaglie** [comment]
Done.
