### ISSUE TITLE
Arduino Relay Load Capacity.

### ISSUE THREAD

**Issue by sharibtanweer** [arduino/Arduino#11180]
Please Help Me:
Does This Relay Can Take Load Of Air Conditioner On/Off.
Relay:
10A 250VAC/30VDC
12A 125VAC/28VDC
And Connecting Pin With Nodemcu ESP8266 Below:
3V To VCC
G To GND
D3 To IN
Please Help Me What Relay I Can Use To Handle Max Load For Switch.

**Comment by per1234** [comment]
Please see the product page for the specifications on the Arduino relay products:
https://store.arduino.cc/catalogsearch/result/?tab=store&q=relay
