### ISSUE TITLE
[Library Manager] ESP8266RTTTLPlus Library

### ISSUE THREAD

**Issue by StarsoftAnalysis** [arduino/Arduino#11190]
Hello

I've created a new and improved library for parsing and playing RTTTL melodies at:

https://github.com/StarsoftAnalysis/ESP8266RTTTLPlus

Please can you add it to the Arduino library?

**Comment by per1234** [comment]
Hi @StarsoftAnalysis. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by StarsoftAnalysis** [comment]
Updated to version 0.1.2.

**Comment by per1234** [comment]
@StarsoftAnalysis the repository still doesn't have any releases or tags:
https://github.com/StarsoftAnalysis/ESP8266RTTTLPlus/tags
Did you maybe make the tag in your local clone and then forget to push it to GitHub?

**Comment by StarsoftAnalysis** [comment]
Thank you for your patience and quick replies.  I hadn't understood the need to use take extra steps to push tags.  I hope it's right now.

Cheers,

Chris

**Comment by cmaglie** [comment]
Done.

**Comment by StarsoftAnalysis** [comment]
Thank you.
