### ISSUE TITLE
Auto-select correct COM port

### ISSUE THREAD

**Issue by MMartin09** [arduino/Arduino#11196]
In most cases, a "default" user will only use a single Arduino at the time. In Windows, there are usually multiple open COM ports. 
My machine, for example, always has at least two ports. But I think it should be no problem to auto-select the port where the Arduino is connected. In fact, I already implemented this in some of my applications. An auto-selected COM port is a good thing in the IDE i think.

**Comment by per1234** [comment]
There's a proposal to go at in in the opposite direction (select board based on port selection) here: https://github.com/arduino/Arduino/pull/7120.

Arduino Web Editor and Arduino Pro IDE do have this functionality already.

**Comment by MMartin09** [comment]
Thank you. I think this could close the issue.
