### ISSUE TITLE
[Arduino Library Manager] Please add "Simple Web Serial" to the library manager

### ISSUE THREAD

**Issue by fmgrafikdesign** [arduino/Arduino#11208]
As per Library Manager FAQ, I'm asking you to add my "Simple Web Serial" library to the Arduino library manager.

Library URL: https://github.com/fmgrafikdesign/simplewebserial-arduino-library
Release URL: https://github.com/fmgrafikdesign/simplewebserial-arduino-library/releases/tag/0.1.5

If there is any additional information you need, feel free to contact me.
Thank you very much and have a nice day!

Best Regards,
Fabian

**Comment by cmaglie** [comment]
Done.
