### ISSUE TITLE
[Library Manager] Please add FlashStorage_STM32 library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#11210]
Please add [**FlashStorage_STM32 library**](https://github.com/khoih-prog/FlashStorage_STM32) to Library Manager.
Thanks and Regards.

---

### Features

The FlashStorage_STM32 library, inspired from [Cristian Maglie's FlashStorage](https://github.com/cmaglie/FlashStorage), provides a convenient way to store and retrieve user's data using emulated-EEPROM, from the non-volatile flash memory of STM32F/L/H/G/WB/MP1.

The flash memory, generally used to store the firmware code, can also be used to store / retrieve more user's data and faster than from EEPROM. Thanks to the **buffered data writing and reading**, the flash access time is greatly reduced to **increase the life of the flash**.

### Currently supported Boards

1. **STM32F/L/H/G/WB/MP1 boards with / without integrated EEPROM**

- Nucleo-144
- Nucleo-64
- Nucleo-32
- Discovery
- Generic STM32F0, STM32F1, STM32F2, STM32F3, STM32F4, STM32F7
- STM32L0, STM32L1, STM32L4
- STM32G0, STM32G4
- STM32H7
- STM32WB
- STM32MP1
- LoRa boards
- 3-D printer boards
- Generic Flight Controllers
- Midatronics boards

---
---

### Releases v1.0.0

1. Initial release to support STM32F/L/H/G/WB/MP1 board with / without integrated EEPROM

**Comment by cmaglie** [comment]
Done.
