### ISSUE TITLE
Please add Vcc library to Library Manager

### ISSUE THREAD

**Issue by felias-fogg** [arduino/Arduino#11213]
Hi,

could ypu please add my Vcc library to the Library Manager: https://github.com/felias-fogg/Vcc

Cheers,
Bernhard

**Comment by per1234** [comment]
Hi @felias-fogg. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by felias-fogg** [comment]
Sorry. Now I've created a release.

**Comment by cmaglie** [comment]
Done.
