### ISSUE TITLE
Question about version in library.properties 

### ISSUE THREAD

**Issue by RodrigoDornelles** [arduino/Arduino#11215]
I am building a [virtual machine](https://github.com/RodrigoDornelles/3bc-lang) capable of running on Arduino, but I intend to keep **pre-release** for a long time until it is stable, would like to know if I can put it as version with **beta-_number_** in the library properties? 

### Example ###
`library.properties`
```YAML
name = 3BC Language Virtual Machine 
version = beta-4
...
```

**Comment by per1234** [comment]
Hi @RodrigoDornelles. No, this is not a valid version. You should use a semver compliant version. See the semver specification to understand the correct way to specify beta and pre-release status via the version number:
https://semver.org/

For other questions about the library.properties file, please see the Arduino Library Specification:
https://arduino.github.io/arduino-cli/latest/library-specification
