### ISSUE TITLE
Missing constant definition on sample sketch

### ISSUE THREAD

**Issue by ewomack2000** [arduino/Arduino#11228]
The LED sample sketch on https://sensorkit.arduino.cc/sensorkit/module/lessons/lesson/01-the-led doesn't define the constant `#define LED` so as-is it throws the "expected primary-expression before ',' token" error, which could really throw a beginner. Updating the line to `#define LED 6` allows the sketch to compile.

**Comment by per1234** [comment]
Thanks so much for reporting this error @ewomack2000! It has now been corrected.
