### ISSUE TITLE
Request for adding library

### ISSUE THREAD

**Issue by Jan-NiklasB** [arduino/Arduino#11225]
I want to suggest to add my library for using the MH-Z14A CO2-Sensor with Arduino with possebility to use multiple serial interfaces for simultanious communication with the sensor and the serial console.

The library is located here:  https://github.com/Jan-NiklasB/MH-Z14A-Library

**Comment by cmaglie** [comment]
Done.

**Comment by Jan-NiklasB** [comment]
Thanks
