### ISSUE TITLE
Incorrect ICSP header pin numbering on Nano pinout diagram

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#11245]
The pinout diagram downloaded from the "Download the full pinout diagram as PDF [here](https://content.arduino.cc/assets/Pinout-NANO_latest.pdf)." on the "Documentation" tab of the Arduino Nano product page:
https://store.arduino.cc/arduino-nano
has incorrect pin numbering on the ICSP header:
![Clipboard01](https://user-images.githubusercontent.com/8572152/106993411-7e003a00-672f-11eb-979c-b6fbd0e8576d.png)

Pin 1 is at the bottom left corner of the header, as indicated by the white dot on the PCB silkscreen:
![](https://store-cdn.arduino.cc/uni/catalog/product/cache/1/image/500x375/f8876a31b63532bbba4e781c30024a0a/a/0/a000005_front.jpg)
So the header pin numbering is off by 180 degrees.

CC: @FunzioneFabio

Originally reported at https://forum.arduino.cc/index.php?topic=726422

**Comment by FunzioneFabio** [comment]
Thank you @per1234 for finding the error, I will fix this.

**Comment by FunzioneFabio** [comment]
Pinout uploaded and updated online, you can check it here:
https://content.arduino.cc/assets/Pinout-NANO_latest.pdf

@per1234 I think we can close the issue.

**Comment by per1234** [comment]
Looks good. Thanks @FunzioneFabio !
