### ISSUE TITLE
[Library Manager] Add various Sensirion libraries

### ISSUE THREAD

**Issue by rnestler** [arduino/Arduino#11248]
I'd like to add the following libraries:

- [x] "Sensirion UART SFA3x" https://github.com/Sensirion/arduino-uart-sfa3x
- [x] "Sensirion I2C SCD4x": https://github.com/Sensirion/arduino-i2c-scd4x
- [x] "Sensirion I2C SFA3x": https://github.com/Sensirion/arduino-i2c-sfa3x

**Comment by cmaglie** [comment]
Done.
