### ISSUE TITLE
Arduino SDK on linux ARM

### ISSUE THREAD

**Issue by Oygron** [arduino/Arduino#1124]
Hi, 

I work on embedded systems and we use an ARM board with an Arch Linux embedded. This board must be able to reconfigure an Arduino board. 

The problem is I cannot build from sources the Arduino SDK on my board. 
In facts, the file build/build.xml is not able to detect an ARM linux as a linux32. Consequently, the installer fails to find the right folder, and stops. 

I fixed it replacing every ${platform} by linux32 but it is not very clean, and will be overrided on each update. Doing this, the software compiles and run.

Would that be possible to add ARM platforms (mine is armv7h) as detected platforms?

Thanks in advance.

Oygron

**Comment by ffissore** [comment]
Some work on going. See #3549 and #3334. Closing to avoid duplication
