### ISSUE TITLE
recent used boards list

### ISSUE THREAD

**Issue by pavel-b-kr12** [arduino/Arduino#11246]
Having many boards in manager it is very annoying to select (and set settings).

Implementing list of recently used boards (better with used settings) will save a lot of time.
![board list ](https://user-images.githubusercontent.com/28408886/107040202-91f77a80-67c7-11eb-8132-cad70d6196e1.png)

The alternate way that is not as good but faster to implement is highlight in the existing lists recently used items

**Comment by per1234** [comment]
Already done: https://github.com/arduino/Arduino/pull/8607

You can try the beta build of the Arduino IDE if you want to test it out:
https://www.arduino.cc/en/Main/Software#beta

There is also an improved version here: https://github.com/arduino/Arduino/pull/10816 but I don't think there's a pre-built IDE version that has it for testing (though you can always build the IDE from that source code).
