### ISSUE TITLE
Please, add a new library to Library Manager

### ISSUE THREAD

**Issue by pu2clr** [arduino/Arduino#11251]
Please, add a new library to Library Manager.
It is an Arduino Library to control the MCP23008/MCP23S08 8-Bit I/O Expander from MicroChip.
The MCP23008 device provides 8-bit, general purpose, parallel I/O expansion. It can be controlled via I2C bus applications.

Link: https://github.com/pu2clr/MCP23008

**Comment by cmaglie** [comment]
Done.
