### ISSUE TITLE
serial monitor doesn't show anything

### ISSUE THREAD

**Issue by 1Misaka** [arduino/Arduino#11256]
![IMG_20210208_232040.jpg](https://user-images.githubusercontent.com/74802762/107239893-47465e80-6a64-11eb-8ddc-d8f6dbc6a983.jpg)

The arduino serial monitor doesn't show anything.Although i use Serial.begin(115200) and Serial.println(),the monitor even show nothing.

**Comment by 1Misaka** [comment]
In another word,it seems like a white page.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.

**Comment by matthijskooijman** [comment]
Do you mean the serial monitor shows *nothing* at all? Not even an input box, baud rate dropdown, etc.?

**Comment by 1Misaka** [comment]
> Do you mean the serial monitor shows *nothing* at all? Not even an input box, baud rate dropdown, etc.? If those are *not* shown, then this might be a bug, otherwise, it's likely some problem in your setup to be handled as @per1234 suggests.

   Input box and baud rate are all exist.
yes,the monitor like a white page.
