### ISSUE TITLE
Please, add a new library to Library Manager

### ISSUE THREAD

**Issue by mhoseini967** [arduino/Arduino#11254]
this library created for user-friendly access to seven segment

https://github.com/mhoseini967/AdvancedSevenSegment

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by mhoseini967** [comment]
that fixed please review it

**Comment by cmaglie** [comment]
Done.
