### ISSUE TITLE
[Library Manager] Add new library

### ISSUE THREAD

**Issue by djaumann** [arduino/Arduino#11278]
Could you please add this library to the library-manager:
https://github.com/Infineon/arduino-rgb-led-lighting-shield

Thanks a lot already and have a nice week!

BR,
Dominik

**Comment by per1234** [comment]
Hi @djaumann. Thanks for your interest in contributing to the Arduino Library Manager index.

I get a "Page not found" error from that link. Is the repository visibility set to "public"? I do see a similarly named repository:
https://github.com/Infineon/RGB-LED-Lighting-Shield-XMC1202

**Comment by djaumann** [comment]
Hey @per1234,

I'm sorry I totally forgot to make the repository public ...
Now it should be available :)

The other one you mentioned is a old one and will be archived soon.

Thank you already and sorry for the late response!

BR,
Dominik

**Comment by cmaglie** [comment]
Done.

**Comment by djaumann** [comment]
Thank you for doing it so quickly!
