### ISSUE TITLE
Arduino IDE Freezes when saving

### ISSUE THREAD

**Issue by AniketFasate27** [arduino/Arduino#11282]
When I try to save my code in arduino idle it freezes sometimes. So I have to go in task manager and then i have to close it. So every time i am try to save new code freezes. So please give me some solution on it.

**Comment by PaulStoffregen** [comment]
Maybe OneDrive or other network filesystem in play?

**Comment by AniketFasate27** [comment]
No , Nothing working in background.

**Comment by feikname** [comment]
How long does it freeze for?

**Comment by AniketFasate27** [comment]
Infinite time. To close it i have to go task manager then it will close.

**Comment by AniketFasate27** [comment]
please help its happening several times. Now i am fustrated

**Comment by PaulStoffregen** [comment]
How do you imagine anyone could help from only the meager info you've given?

I don't even see which version of Arduino you're using, or whether your computer is Windows, Linux or Macintosh, and which version.  We are (maybe helpful) strangers on the internet.  We can't see your computer, we can't see your screen, we can't know what other software you've installed, or any other info to try guessing what might be different from your computer and ours and every other where this problem does not happen.

I mean, I'd like to help you.  But if you're feeling frustrated, just trying to imagine how anyone who wants to help must feel when reading this no-info github issue?

**Comment by AniketFasate27** [comment]
Thank you for your response.

**Comment by per1234** [comment]
Closing due to lack of enough information to investigate.

@AniketFasate27 if you'll provide the requested information I'll be happy to re-open this issue.

**Comment by Electro-boy** [comment]
Even My IDE freezes when Saving new sketch or while opening new sketch.
IDE freezes and if i click on the window or anywhere on the arduino ide , it plays error sound and no response. I need to manually open task manager and close the application and re-open again to work.

1.8.19 is the Arduino IDE version.
Windows 10

No application running in background including ONEDRIVE.
