### ISSUE TITLE
[Library Manager] Please add the MyDelay library

### ISSUE THREAD

**Issue by mggates39** [arduino/Arduino#11298]
Please add the MyDelay library. https://github.com/mggates39/MyDelay 
 It is currently release v1.0
This is a mills() based delay library that simplifies using delay timers. it can trigger once, for a specific number of times or forever.  It can also call a callback function for every trigger.

**Comment by per1234** [comment]
Hi @mggates39. Thanks for your interest in contributing to the Arduino Library Manager index.

The filename of the library.properties file in your repository is misspelled "ibrary.properties" (note the missing "l"). This will block the addition of your library to the index.

Please fix the filename, then either create a new git tag/GitHub release or else redo the existing tag.

Once that's done, please comment here so we'll know we can proceed.

More information:
https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format

**Comment by mggates39** [comment]
The library properties file has been updated.  Release v.1.0.1 has been published.

**Comment by mggates39** [comment]
I ran Arduin-lint on the library and fixed the issues found.  Latest release is now v1.02

**Comment by cmaglie** [comment]
Done.
