### ISSUE TITLE
Please add IMU KX023-1025 library

### ISSUE THREAD

**Issue by dlyckelid** [arduino/Arduino#11293]
Hi!
Please add my library for the IMU KX023-1025

I have tagged the release v1.0.0

link to github:
https://github.com/dlyckelid/KX023-1025-IMU

**Comment by cmaglie** [comment]
Done! sorry for the long delay...

**Comment by dlyckelid** [comment]
Hi!

Tried the link from arduino IDE and the ":" is missing from https://
Is that something I can fix or just a typo when it was added?

**Comment by cmaglie** [comment]
Just fix the library.properties URL and release an update of the library (and I see that you already did it :+1:)
