### ISSUE TITLE
Please, add a new library to Library Manager

### ISSUE THREAD

**Issue by pu2clr** [arduino/Arduino#11291]
Please, add a new library to Library Manager.
It is an Arduino Library to control the PCF8574 device.
The PCF8574/74A provides general-purpose remote I/O expansion via the two-wire bidirectional I2C-bus (serial clock (SCL), serial data (SDA)).
Link: https://github.com/pu2clr/PCF8574

**Comment by cmaglie** [comment]
Done! sorry for the long delay...
