### ISSUE TITLE
[Library Manager] Please add the NVSRAM library

### ISSUE THREAD

**Issue by gpb01** [arduino/Arduino#11305]
Please add the NVSRAM library

Repository: https://github.com/gpb01/NVSRAM

This library enables you to read and write into Microchip NVSRAM 23LCV512 (64K x 8 bit) and 23LCV1024 (128K x 8 bit), battery-backed SPI RAM.

Thank you.

**Comment by per1234** [comment]
Hi @gpb01. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by gpb01** [comment]
Thanks, release with tag 1.0.0 added.

**Comment by cmaglie** [comment]
Done.
