### ISSUE TITLE
Timeout no uploading no arduino mega 2560

### ISSUE THREAD

**Issue by colp** [arduino/Arduino#1130]
I'm having problem in uploading the sketch to the board Arduino Mega 2560. It seems that this occurs when the sketch exceeds 13,000 bytes. For code with less than 13,000 bytes uploading is successful.

I'm using Windows 7, Arduino Mega 2560 and IDE 1.0.2. I have also tried the 1.0 IDE, and continues with the same error.

Please could someone help me?

Below is the result of uploading:

Binary sketch size: 13.026 bytes (of a 258.048 byte maximum)
avrdude: stk500v2_ReceiveMessage(): timeout
...
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
avrdude: stk500v2_ReceiveMessage(): timeout
...
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
avrdude: stk500v2_command(): failed miserably to execute command 0x13
avrdude: stk500v2_paged_write: write command failed
avrdude: stk500v2_ReceiveMessage(): timeout
...
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
avrdude: stk500v2_command(): failed miserably to execute command 0x1d
avrdude: stk500v2_cmd(): failed to send command
avrdude: stk500v2_ReceiveMessage(): timeout
...
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
avrdude: stk500v2_command(): failed miserably to execute command 0x1d
avrdude: stk500v2_cmd(): failed to send command
avrdude: stk500v2_ReceiveMessage(): timeout

**Comment by Chirag2239** [comment]
How to check whether the bootloader is loaded successfully or not?
And I have seen that Arduino seems that done bootloading when I am trying to bootloading through the Arduino as ISP with ATmega2560 to be programmed and Arduino Duemilanouve as programmer. So is bootloader correctly installed?

If yes, then I am trying to upload the blink code to ATmega2560, then it gives the error of avrdude stk500v2_getsync() timeout  and Receive timeout.

Please help me.

**Comment by facchinm** [comment]
Hi @Chirag2239 , I think your problem can be related to #388, however I have to test it to be sure. 

In the meantime, please give a try to this PR #3500, I don't know it the updated ArduinoISP sketch is enough or if you also need to update `avrdude` to version 6.1 (arduino/toolchain-avr#17). As soon as I can test it I'll post here a proper solution

**Comment by MustafaMta** [comment]
I've had the same problem and the solution is. Download XLoader and upload to your arduino.
