### ISSUE TITLE
[Library Manager] Change of Library Name

### ISSUE THREAD

**Issue by mrfaptastic** [arduino/Arduino#11311]
Library: https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101-LORA

From: "Easy ESP Arduino IoT with CC1101"
To: "Easy IoT with CC1101 (Low-Power Sub-1GHz LORA-like)"

**Comment by per1234** [comment]
Hello again @mrfaptastic. There are restrictions on which characters are allowed in the library.properties `name` value. The characters `(` and `)` in your currently proposed name are prohibited. You can see the rules for the name here:
https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format

After doing that, you'll need to make a new release or tag.

Once everything is in compliance with the library specification and [FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name), please comment here to let us know we can proceed.

**Comment by mrfaptastic** [comment]
Thanks again per1234. Please change name to: "Easy IoT with CC1101 - Sub-1GHz LORA-like"

I have updated the library files and created a new version in the respository.

**Comment by cmaglie** [comment]
Done.
