### ISSUE TITLE
[Library Manager] Please include "Arduino-Charlieplexing" in the Arduino Library Manager

### ISSUE THREAD

**Issue by turn-a-round** [arduino/Arduino#11317]
Library url: https://github.com/turn-a-round/Arduino-Charlieplexing

### Arduino-Charlieplexing

A library for Arduino to control Charlieplexed LED matrices.

Drive (N x (N-1)) number of "Charlieplxed" diode matrices (e.g. LED Matrix) with N number of outputs capable of tri-state.

For more information about this library please visit us at https://github.com/turn-a-round/Arduino-Charlieplexing

**Comment by cmaglie** [comment]
Done.

**Comment by turn-a-round** [comment]
Thanks... :)
