### ISSUE TITLE
[Library Manager] Add SEN and STC drivers to Arduino Library Manager

### ISSUE THREAD

**Issue by MBjoern** [arduino/Arduino#11329]
I would like to add the following libraries to the Arduino Library Manager. They are drivers for Sensirion Environental Sensors.

- [x] https://github.com/Sensirion/arduino-i2c-stc3x
- [x] https://github.com/Sensirion/arduino-uart-sen44
- [x] https://github.com/Sensirion/arduino-i2c-sen44

Thank you

**Comment by cmaglie** [comment]
Done.
