### ISSUE TITLE
[Library Manager] Add the UMIRobot library to Arduino Library Manager

### ISSUE THREAD

**Issue by mmmarinho** [arduino/Arduino#11327]
I would like to add the UMIRobot library to the Arduino Library Manager. 
It is part of an open-source open-hardware education project of the same name.

https://github.com/mmmarinho/umirobot-arduino

Thanks in advance.

**Comment by cmaglie** [comment]
Done.

**Comment by mmmarinho** [comment]
Thank you very much!
