### ISSUE TITLE
[Library Manager] Add ELMo to Library Manager

### ISSUE THREAD

**Issue by rudydelorenzo** [arduino/Arduino#11323]
Hi! Could you please add the ELMo Library to Library Manager?

The GitHub address is [https://github.com/rudydelorenzo/ELMo](https://github.com/rudydelorenzo/ELMo) and I believe it conforms to the Library Manager guidelines.

ELMo is a low-level, synchronous Arduino library to interface with ELM327 OBDII devices.

This library abstracts away some of the quirks of the ELM327 protocol, but still gives the user most of the control. No helper methods such as rpm() are available, this library is intended to simplify the process of sending explicit PID's.

Thank you!

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
