### ISSUE TITLE
[Library Manager] Add Seeed Arduino RTC library into Arduino Library Manager

### ISSUE THREAD

**Issue by lakshanthad** [arduino/Arduino#11326]
Hi, 

Please help to add the following library to Arduino Library Manager:

https://github.com/Seeed-Studio/Seeed_Arduino_RTC

Best Regards,
Lakshantha

**Comment by cmaglie** [comment]
Done, sorry for the long delay!

**Comment by lakshanthad** [comment]
Thank you
