### ISSUE TITLE
[Library Manager] library updated: arduino-display-lcdkeypad

### ISSUE THREAD

**Issue by dniklaus** [arduino/Arduino#11338]
https://github.com/dniklaus/arduino-display-lcdkeypad

Version 5.0.0 was wrong and has to be removed.
After this has been done, the correct version will be released.

Please remove version 5.0.0 of this library.

**Comment by per1234** [comment]
Hi @dniklaus. I believe the Library Manager indexer will handle this automatically.

See this section of the FAQ for details:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#sorry-i-did-something-wrong-how-can-i-change-or-unpublish-an-already-published-library

If you give it a try and it doesn't work as expected, please comment here and we'll investigate.
