### ISSUE TITLE
Initial release of ICOM IC-746 CAT Emulation Library

### ISSUE THREAD

**Issue by kk4das** [arduino/Arduino#11344]
Please add this library to the library manager:

https://github.com/kk4das/IC746CAT/releases/tag/v1.0

This library provides computer aided transceiver control to homebrew amateur radio projects.

Thank you,
Dean Souleles
KK4DAS

**Comment by cmaglie** [comment]
Done.

**Comment by kk4das** [comment]
Hi Cristian –

 

There was a typo in the URL in the library.properties that someone has already reported.  I merged the patch.   Do I need to do a new release to get it corrected?

 

Thank you,

 

Dean
