### ISSUE TITLE
[Library Manager] Please add my IoTWebconf for Arduino and Visuino

### ISSUE THREAD

**Issue by BadASszZ** [arduino/Arduino#11347]
Hi, if possible I would like my IoTWebconf library version to be added to the library manager.
This library is reworked to fit most ESP boards together with Arduino IDE as well as Visuino. It is used to set the WiFi credentials and other properties after the sketch has been uploaded. This will show up as it's own access point and a setup portal for the user.
It can also have custom web pages with your own text fields for other features like MQTT and similar settings. There is no problem to have both mine and the original installed at the same time.

Here's the library:
https://github.com/BadASszZ/IoTWebConf_for_Visuino_modified_by_IoT_Jedi

// Tobbe a.k.a. IoT Jedi

**Comment by cmaglie** [comment]
Done.
