### ISSUE TITLE
[Library Manager] Please add my library BOARD

### ISSUE THREAD

**Issue by PhotonTechnologyCodeSpace** [arduino/Arduino#11343]
Please add my library.

Link: https : https://github.com/PhotonTechnologyCodeSpace/Alpha-Board

**Comment by per1234** [comment]
Hi @PhotonTechnologyCodeSpace. I see these are sketches, not a library. Only libraries can be added to the Arduino Library Manager.

More information:
- https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
- https://arduino.github.io/arduino-cli/latest/library-specification/
