### ISSUE TITLE
[Library Manager] Please add GSM_Generic Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#11340]
Please add [**GSM_Generic library**](https://github.com/khoih-prog/GSM_Generic) to Library Manager.

Thanks and Regards.

---

### Features

This library is based on, modified, bug-fixed and improved from:

1. [`MKRGSM`](https://github.com/arduino-libraries/MKRGSM)

to add support to many boards besides `Arduino MKR GSM 1400`.

This [GSM_Generic library](https://github.com/khoih-prog/GSM_Generic) will finally provide these following features (certainly ony if supported by the GSM/GPRS modules)

1. **TCP Client and Server** (HTTP, **HTTPS**, MQTT, Blynk, WebSockets, ...)
2. **UDP** data connections
4. **USSD** (Sending USSD requests and decoding 7,8,16-bit responses)
5. **SMS** (Sending and Receiving)
6. **Voice Call** (Making and Receiving)
7. **Location**

### Supported modems

- [X] u-blox 2G, 3G, 4G, and LTE Cat1 Cellular Modems (many modules including LEON-G100, LISA-U2xx, SARA-G3xx, SARA-U2xx, TOBY-L2xx, LARA-R2xx, MPCI-L2xx)
- [X] u-blox LTE-M/NB-IoT Modems (SARA-R4xx, SARA-N4xx, _but NOT SARA-N2xx_). Not fully tested yet.

### To be Supported modems

- [ ] SIMCom SIM800 series (SIM800A, SIM800C, SIM800L, SIM800H, SIM808, SIM868)
- [ ] SIMCom SIM900 series (SIM900A, SIM900D, SIM908, SIM968)
- [ ] SIMCom WCDMA/HSPA/HSPA+ Modules (SIM5360, SIM5320, SIM5300E, SIM5300E/A)
- [ ] SIMCom LTE Modules (SIM7100E, SIM7500E, SIM7500A, SIM7600C, SIM7600E)
- [ ] SIMCom SIM7000E/A/G CAT-M1/NB-IoT Module
- [ ] AI-Thinker A6, A6C, A7, A20
- [ ] ESP8266 (AT commands interface, similar to GSM modems)
- [ ] Digi XBee WiFi and Cellular (using XBee command mode)
- [ ] Neoway M590, M590E
- [ ] Sequans Monarch LTE Cat M1/NB1 (VZM20Q)
- [ ] Quectel BG96
- [ ] Quectel M95
- [ ] Quectel MC60 ***(alpha)***

More modems may be supported later:

- [ ] Quectel M10, UG95
- [ ] SIMCom SIM7020, SIM7020E
- [ ] Telit GL865
- [ ] ZTE MG2639
- [ ] Hi-Link HLK-RM04
- [ ] WIS800C, compatible to SIM900A, SIM800L, SIM800C

### Currently Supported Boards

This [**GSM_Generic** library](https://github.com/khoih-prog/GSM_Generic) currently supports these following boards:

 1. **nRF52 boards**, such as **AdaFruit Feather nRF52832, nRF52840 Express, BlueFruit Sense, Itsy-Bitsy nRF52840 Express, Metro nRF52840 Express, NINA_B302_ublox, NINA_B112_ublox, etc.**
 
 2. **SAM DUE**
 
 3. **SAMD21**
  - Arduino MKR GSM 1400
  - Arduino SAMD21: ZERO, MKRs, NANO_33_IOT, etc.
  - Adafruit SAMD21 (M0): ItsyBitsy M0, Feather M0, Feather M0 Express, Metro M0 Express, Circuit Playground Express, Trinket M0, PIRkey, Hallowing M0, Crickit M0, etc.
  - Seeeduino:  LoRaWAN, Zero, Femto M0, XIAO M0, Wio GPS Board, etc.
  
 4. **SAMD51**
 
  - Adafruit SAMD51 (M4): Metro M4, Grand Central M4, ItsyBitsy M4, Feather M4 Express, Trellis M4, Metro M4 AirLift Lite, MONSTER M4SK Express, Hallowing M4, etc.
  - Seeeduino: Wio Terminal, Grove UI Wireless
  
 5. **Teensy (4.1, 4.0, 3.6, 3.5, 3,2, 3.1, 3.0, LC)**
 
 6. **ESP32 including ESP32-S2 (ESP32-S2 Saola, AI-Thinker ESP-12K, etc.)**
 
 7. **ESP8266**
  
 8. **STM32F/L/H/G/WB/MP1 boards (with 32+K Flash)**

  - Nucleo-144 (F429ZI, F767ZI, etc.)
  - Nucleo-64
  - Discovery
  - Generic STM32F0, STM32F1, STM32F2, STM32F3, STM32F4, STM32F7 (with 64+K Flash): x8 and up
  - STM32L0, STM32L1, STM32L4
  - STM32G0, STM32G4
  - STM32H7
  - STM32WB
  - STM32MP1
  - LoRa boards
  - 3-D printer boards
  - Generic Flight Controllers
  - Midatronics boards
---
---

### Release v1.2.4

1. Initial public release to add support to many boards / modules besides MKRGSM 1400 / SARA U201

**Comment by cmaglie** [comment]
Done.
