### ISSUE TITLE
Forcing a reset of com port on compile even if error!

### ISSUE THREAD

**Issue by lensman11** [arduino/Arduino#11358]
Is it possible to withhold the com port reset stage until an error free compile is completed?

It is so annoying to have a com port reset when an error occurs - is it possible to only force the reset when the compile is completed.

Regards Colin

**Comment by per1234** [comment]
Hi @lensman11. Thanks for taking the time to submit an issue.

We already have a prior issue report about this at https://github.com/arduino/Arduino/issues/8146.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
If you end up with additional information to share, feel free to comment in the other thread.

I would recommend doing a test with the nightly build of Arduino IDE 2.0.0-beta to see whether the issue also occurs when using that IDE. You can download it here:
https://www.arduino.cc/en/software#nightly-builds
If you do that, please let us know what your findings are.
