### ISSUE TITLE
[library manager] Please add the SparkFun QwiicNES library

### ISSUE THREAD

**Issue by NPoole** [arduino/Arduino#11351]
v1.0.0 was just released! 
https://github.com/sparkfun/SparkFun_QwiicNES_Arduino_Library

Thank you!

**Comment by per1234** [comment]
Hi @NPoole. I get a 404 error from that URL. Is the repository visibility maybe set to "Private"?

**Comment by NPoole** [comment]
Ah, of course, it was. Sorry.

**Comment by dsyleixa** [comment]
the link in your repo is also not valid (404), so hard to see for which hardware this is actually for?
`https://www.sparkfun.com/products/18038`

**Comment by NPoole** [comment]
The hardware hasn't been released yet, that link is to the product page that will go live in a few weeks.

**Comment by dsyleixa** [comment]
thank you, I'm looking forward to the realease and what it's for. I was just curious about the invalid link.

**Comment by cmaglie** [comment]
Done.
