### ISSUE TITLE
[Library Manager] Please add PlayingWithfusion  drivers to library

### ISSUE THREAD

**Issue by CodingWithFusion** [arduino/Arduino#11360]
Please add the following sensor derivers to the Arduino library
- [x] https://github.com/PlayingWithFusion/PWFusion_Mcp960x
- [x] https://github.com/PlayingWithFusion/PWFusion_MAX31865
- [x] https://github.com/PlayingWithFusion/PWFusion_VL53L3C
- [x] https://github.com/PlayingWithFusion/PWFusion_TCA9548A

Thanks,
Jared

**Comment by cmaglie** [comment]
Done.
