### ISSUE TITLE
Arduino-IDE interface/fonts broken

### ISSUE THREAD

**Issue by thetechnician274** [arduino/Arduino#11389]
Recently I have been trying to install arduino-ide on linux Alpine 3.13.3. 
I managed to launch the IDE, but all of the text from the interface seems to be broken.
 It happens with Aduino IDE version 1.0.5 and 1.5.8 (version 1.8.13 won't even launch). 
My question is if there is any way to repair the interface. 
![Screenshot at 2021-03-29 13-33-44](https://user-images.githubusercontent.com/81565776/112831618-82dccc80-9094-11eb-92b9-ac2c69220ee6.png)
Thanks for all answers.

**Comment by per1234** [comment]
Hi @thetechnician274. Thanks for taking the time to submit a bug report.

We don't support old versions of the Arduino IDE so this would only be considered valid if it occurs when using the latest hourly build of the Arduino IDE downloaded from the "Software" page of Arduino's website:
https://www.arduino.cc/en/software#hourly-builds

If you try that out and find that the issue still occurs, please comment here and I'll be happy to reopen the issue.

Of course, that's not of much comfort to you if you can't start the Arduino IDE. If you post about your issues on the Arduino Forum, I'll try to help you out to get it working:
https://forum.arduino.cc/
