### ISSUE TITLE
The problem with -fpermissive

### ISSUE THREAD

**Issue by MarcSchoendorf** [arduino/Arduino#11402]
Today a user from the German Arduino Facebook Group ran into a problem with switch/case producing invalid code. After some hours of searching, it turns out the culprit is the -fpermissive flag in Arduino.
This code should never ever compile, but it does thanks to the flag:
```
switch(...)
{
    case 0:
    int val = 42; // This should throw an error. You're not allowed to declare variables in a case label without using additional brackets! Results in crashing assembly
    // ...
    break;

  // ...
}
```
This is serious business, because the compiler produces an invalid assembly that skips instructions randomly, and the compiler doesn't even give an error.
I know why -fpermissive was introduced and also read the discussion here: https://github.com/arduino/Arduino/pull/5021#issuecomment-225803775
and here: https://github.com/arduino/ArduinoCore-avr/issues/268

But accepting invalid and crashing code just because Arduino wants to support bad written libs and likes to suppress all warning is just non sense.

What are the plans for the flag?

**Comment by per1234** [comment]
Hi @MarcSchoendorf. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/Arduino/issues/10154.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
