### ISSUE TITLE
Array with index [0] always returns 2

### ISSUE THREAD

**Issue by Wilko01** [arduino/Arduino#11400]
When placing a value in an array at index number and then retrieving it will always result in 2.
Other indexes are fine.
I'm using Arduino IDE 1.8.13

My simpliefied code
```c++
int keypadPosition = 0; //keypad position
char keyInput[] = {8, 4, 5, 6, 7}; // create an array of 5 characters
//char keyInput[5]; // create an array of 5 characters
int code; //The code that was punched in
int checkKey =2; //verander deze waarde om te checken

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  
  /*
  keyInput[0] = 3; //always results in 2
  keyInput[1] = 4;
  keyInput[2] = 6;
  keyInput[3] = 8;
  keyInput[4] = '3';
 */
  code = 0;
  keyInput[keypadPosition] = checkKey;
}

void loop() {
  // put your main code here, to run repeatedly:
   Serial.println("in loop ");
  code = int(keyInput[0]);
  Serial.print("code =  ");
  Serial.println(code);
  delay(1000);
}
```

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
