### ISSUE TITLE
[Library Manager] Request to add new library: **Blues Wireless Notecard Pseudo Sensor**

### ISSUE THREAD

**Issue by zfields** [arduino/Arduino#11418]
Please add this library to Library Manager:

Library: https://github.com/blues/notecard-pseudo-sensor
Library release: https://github.com/blues/notecard-pseudo-sensor/releases/tag/v1.0.0

Thank you,
Zachary J. Fields
Blues Wireless

**Comment by cmaglie** [comment]
Done.
