### ISSUE TITLE
[Library Manager] Please add SmallProjects Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#11417]
Please add [**SmallProjects library**](https://github.com/khoih-prog/SmallProjects) to Library Manager.

Thanks and Regards.

---

### Features

[**SmallProjects** library](https://github.com/khoih-prog/SmallProjects) collects complicated projects to demonstrate the usage of [Khoi Hoang's libraries](https://github.com/khoih-prog/SmallProjects), such as ISR-based timers for ESP8266, ESP32 and Arduino Mega, Nano, etc. These projects are much more complicated than the ordinary libraries' examples. Some can even be used directly in real-life.

#### ISR-based Fire Smoke Alarm demonstrate how to use ESP8266TimerInterrupt, ESP32TimerInterrupt and TimerInterrupt Library

These are examples how to use, design and convert the code from normal `software timer` to `ISR-based timer`.

---
---

#### Release v1.0.2

1. Add [STM32_LAN8720 examples](https://github.com/khoih-prog/SmallProjects/tree/master/STM32_LAN8720)

#### Release v1.0.1

1. [MasterController](https://github.com/khoih-prog/SmallProjects/tree/master//MasterController)
2. [SmartFarm_DeepSleep](https://github.com/khoih-prog/SmallProjects/tree/master//SmartFarm_DeepSleep)
3. [AutoReConnect](https://github.com/khoih-prog/SmallProjects/tree/master//AutoReConnectp) 

#### Initial Release v1.0.0

Initial v1.0.0 release of sample codes to demonstrate the usage of ISR-based timers, designed for Arduino (Mega, Nano, UNO, etc.), ESP8266 and ESP32-based boards, by using these Hardware Timers libraries:

1. [**TimerInterrupt**](https://github.com/khoih-prog/TimerInterrupt) for Arduino (Mega, UNO, Nano, etc. ) boards
2. [**ESP8266TimerInterrupt**](https://github.com/khoih-prog/ESP8266TimerInterrupt) for ESP8266 boards
3. [**ESP32TimerInterrupt**](https://github.com/khoih-prog/ESP32TimerInterrupt) for ESP32 boards

Sample codes:

1. [FireSmokeAlarm](https://github.com/khoih-prog/SmallProjects/tree/master//FireSmokeAlarm) 
2. [FireSmokeAlarm_Arduino](https://github.com/khoih-prog/SmallProjects/tree/master//FireSmokeAlarm_Arduino)
3. [ISR_FireSmokeAlarm](https://github.com/khoih-prog/SmallProjects/tree/master//ISR_FireSmokeAlarm)
4. [ISR_FireSmokeAlarm_Arduino](https://github.com/khoih-prog/SmallProjects/tree/master//ISR_FireSmokeAlarm_Arduino) 
5. [ISR_Timer_4_Switches](https://github.com/khoih-prog/SmallProjects/tree/master//ISR_Timer_4_Switches)

The corresponding codes using Software Timers are also included to help understand the steps taken in order to convert those codes to be ISR-based.

**Comment by cmaglie** [comment]
Done.
