### ISSUE TITLE
[Library Manager] Request to add EasyLed library

### ISSUE THREAD

**Issue by lnlp** [arduino/Arduino#11411]
Can you please add the [EasyLed](https://github.com/lnlp/EasyLed) library to the Library Manager?

https://github.com/lnlp/EasyLed 

> ### EasyLed
> 
> Arduino library for controlling standard LEDs in an easy way.
> 
> EasyLed provides simple logical methods like led.on(), led.toggle(), led.flash(), led.isOff() and more. This library will help to write cleaner code that is easy to read and understand.

Thanks

**Comment by cmaglie** [comment]
Done.
