### ISSUE TITLE
Difference betweeen IDEs calling of g++/gcc on windows versus linux

### ISSUE THREAD

**Issue by jdn-aau** [arduino/Arduino#1142]
Hi
Compiling Sketches acts different on linux versus windows

Both environments uses g++ -g -c -Wall -ffunction-sections etc for system/lib files

But when it comes to your own code then
 - linux uses the same compiler and settings
- windows uses gcc with other settings.

This gives problems when dealing with ISR, naked code etc etc

Wasted a whole day debugging with avr-objdump etc...

PLEASE let all environments produce same code bit for bit

and furthermore

Please open for #pragma options on equal level on all platforms.

Benefits: for users ovbvious
for arduino - only one version to maintain.

**Comment by ffissore** [comment]
I don't understand. My guess is that you were using two different versions of the IDE. Every version of the IDE uses the very same gcc params, no exception AFAIK
