### ISSUE TITLE
[Feature request] definition of controller architecture

### ISSUE THREAD

**Issue by Jan-NiklasB** [arduino/Arduino#11424]
It would be awesome, if there where a definition holding the controller architecture, like AVR or SAMD for determining the type of the controller at compile time.
This way one doesn't have to test for each CPU like `__AVR_ATmega2650__` and so on if one only needs the architecture present on the board.

If there is already such a feature, it would be great if you can give me a hint, since I fond nothing about it.

If this is the wrong repo for this request, then sorry but I also didn't found it useful to open the same issue on every core repo for the architectures.

**Comment by per1234** [comment]
In the Arduino world, there is a standard convention to define an `ARDUINO_ARCH_<architecture name>` macro. That is followed by all official Arduino boards platforms, as well as all the 3rd party platforms I've checked.

It is mentioned here:
https://arduino.github.io/arduino-cli/latest/library-specification/#working-with-multiple-architectures

It isn't formally documented in the [Arduino Platform Specification](https://arduino.github.io/arduino-cli/latest/platform-specification/) where you might expect to find it. The reason for that is that there is nothing in the Arduino platform system that enforces this convention. It is simply implemented by each platform author.

We do have a proposal to also document these sorts of conventions that platform authors are expected to implement:
https://github.com/arduino/arduino-cli/issues/985
So I'll go ahead and close this as already having an existing request for better documenting this convention.

You'll also find that some such macros may be defined by the toolchains. For example, [`AVR` and `__AVR` when compiling for the AVR architecture](https://www.nongnu.org/avr-libc/user-manual/using_tools.html).
