### ISSUE TITLE
> **Maclain Makanda**

### ISSUE THREAD

**Issue by Maclain27** [arduino/Arduino#11435]
> **Maclain Makanda**
> HI! I' am in this repo!

_Originally posted by @Maclain27 in https://github.com/arduino/Arduino/issues/11433#issuecomment-821607254_

**Comment by per1234** [comment]
@Maclain27. You are being extremely disrespectful to the open source community with this behavior:

- https://github.com/arduino/ArduinoCore-avr/issues/408
- https://github.com/arduino/Arduino/pull/11279
- https://github.com/arduino/Arduino/issues/11434
- https://github.com/Azure/azure-quickstart-templates/issues/8760
- https://github.com/Azure/azure-quickstart-templates/issues/8761

If you persist in spamming our repository, we will be forced to block you and report your behavior to GitHub.
