### ISSUE TITLE
the API documentations of all Java files

### ISSUE THREAD

**Issue by FlyStory** [arduino/Arduino#11430]
I am a student. And I want to de somen research,I need to find the API documentations of all Java files,because the API documentations can teel me the function of all Java files. I hava looked for the web, but I can`t find. Can you help me

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
