### ISSUE TITLE
Request for Bonjour/zeroconf on WiFi Shield

### ISSUE THREAD

**Issue by akauffm** [arduino/Arduino#1143]
I have used Georg Kaindl's excellent [Arduino Ethernet library](http://gkaindl.com/software/arduino-ethernet/bonjour) in the past to give Ethernet shield projects constant addresses (a la "arduino.local") on networks where I couldn't control assigned IP addresses and would very much like to have the same ability using the WiFi shield, along with some of the other bonuses of zeroconf. Because DHCP and DNS are handled in firmware on the WiFi shield, this feels like an issue that can't just be solved with a library like Georg's.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#18
