### ISSUE TITLE
[Library Manager] Please add new library: Geekble_Oscillator

### ISSUE THREAD

**Issue by SooDragon** [arduino/Arduino#11445]
Would you mind add this library to library manager?
https://github.com/geekbleofficial/Geekble_Oscillator

This Library will help users to generate High frequency Pulse from 31.25KHz to 8MHz with fixed 50% duty ratio.
Thank you!

**Comment by cmaglie** [comment]
Done.

**Comment by geekbleofficial** [comment]
Thank you!
