### ISSUE TITLE
[Library Manager] Please add new library: ACAN_ESP32

### ISSUE THREAD

**Issue by pierremolinaro** [arduino/Arduino#11446]
Hello,

Please, can you include my ACAN_ESP32 library (CAN driver for ESP32 CAN Controller):
https://github.com/pierremolinaro/acan-esp32

Best regards,

Pierre Molinaro

**Comment by cmaglie** [comment]
Done.

**Comment by pierremolinaro** [comment]
Thank you very much.

Best regards,

Pierre Molinaro
