### ISSUE TITLE
2 nema 17 step motors

### ISSUE THREAD

**Issue by soo246** [arduino/Arduino#11450]
I want to use 2 Nema17 step motors.
Send signal from Arduino board to A4988 or TMC2208
next
Signal transmission from A4988 to Nema17 stepper motor (first motor)
I want to receive an input signal from the same A4988 to another Arduino Nano.
Then the Arduino Nano that received the signal
Signal to another A4988 or TMC2208. And I want to connect the motor and make the motor spin proportionally from the first motor turns.

For example, if the first motor turns 1 lap
Second motor turns 1 or 2 or 3 turns
 I want to rotate proportionally like this.
![image](https://user-images.githubusercontent.com/80942039/115536288-987c9500-a2d4-11eb-9d89-cbaa4890ee43.png)

like this
I would like to know about the schematic and firmware.

If you have anything to refer to
We would appreciate it if you could tell us the content.

It may be too difficult, but I would appreciate your help.

If there is anything you don't understand, please let me know.

**Comment by per1234** [comment]
Hi @soo246 Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
