### ISSUE TITLE
[Library Manager] Please add the SparkFun_SPI_SerialFlash_Arduino_Library

### ISSUE THREAD

**Issue by PaulZC** [arduino/Arduino#11451]
Hi @cmaglie  / @per1234 ,
Hope you're both doing OK.
Can you please add the SparkFun_SPI_SerialFlash_Arduino_Library to the Library Manager?
https://github.com/sparkfun/SparkFun_SPI_SerialFlash_Arduino_Library 
Sincere thanks - as always,
Paul

**Comment by cmaglie** [comment]
Done.
