### ISSUE TITLE
[Library Manager] Please add ER_OLEDM1_CH1115 library

### ISSUE THREAD

**Issue by gavinlyonsrepo** [arduino/Arduino#11467]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
Hello 

Please add ER_OLEDM1_CH1115 library to the library manager 

Source : https://github.com/gavinlyonsrepo/ER_OLEDM1_CH1115
Tag : https://github.com/gavinlyonsrepo/ER_OLEDM1_CH1115/releases/tag/1.0.0

Overview
--------------------
* Name : ER_OLEDM1_CH1115
* Title : Library to support the ER-OLEDM1.09-1 128X64 OLED Display Module driven by the CH1115 controller for the Arduino eco-system.
* Author: Gavin Lyons

There is no other library in manager that supports this currently.

Regards
Gavin

**Comment by cmaglie** [comment]
Done.
