### ISSUE TITLE
Please add my library SIKTEC-SdExplore to the library manager

### ISSUE THREAD

**Issue by siktec-lab** [arduino/Arduino#11466]
Please add my library [SIKTEC-SdExplore](https://github.com/siktec-lab/SIKTEC-SdExplore)
A companion lib to SdFat which handles scanning and searching files on an SD Card.

**Comment by per1234** [comment]
Hi @siktec-lab. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by siktec-lab** [comment]
Sorry for that -> Release pushed 1.0.2

**Comment by cmaglie** [comment]
Done.
