### ISSUE TITLE
Add my library to Library Manager: IoT_Modules-Buttons

### ISSUE THREAD

**Issue by gq97a6** [arduino/Arduino#11465]
Please add my library to Library Manager:
https://github.com/gq97a6/IoT-modules/tree/master/IoT_Modules-Buttons

Best regards, gq97a6.

**Comment by per1234** [comment]
Hi @gq97a6. Thanks for your interest in contributing to the Arduino Library Manager index.

One of the requirements for acceptance to the Arduino Library Manager is that the library must be in the root of the repository.  So your current repository, which appears to be intended to consist of a collection of multiple libraries in subfolders is not compliant.

If you would still like to add your library to Library Manager, you'll need to bring the repository into full compliance with all the requirements listed here;
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Once that's done, please comment here so we'll know we can proceed.
