### ISSUE TITLE
Add SparkFun Qwiic Haptic Driver Library to library manager

### ISSUE THREAD

**Issue by edspark** [arduino/Arduino#11468]
Good morning,

Could you please add the [SparkFun Qwiic Haptic Driver DA7280 Arduino Library](https://github.com/sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library) to the library manager at your earliest convenience?

Thank you!

**Comment by cmaglie** [comment]
Done.
