### ISSUE TITLE
[Library Manager] Please add new library: RhinoServo

### ISSUE THREAD

**Issue by shashank3199** [arduino/Arduino#11477]
Hi, Please consider adding this library to the Library Manager.
The link for the Library is : [shashank3199/RhinoServo](https://github.com/shashank3199/RhinoServo)
This library provides efficient and detailed control for **Nema-23: Rhino Encoder DC Servo Motor**, see Product [here](https://robokits.co.in/motors/high-torque-encoder-dc-servo-motor-10rpm-with-uart-i2c-ppm-drive?cPath=364_366_376&).

Regards,
Shashank

**Comment by cmaglie** [comment]
Done.
