### ISSUE TITLE
[Library Manager] Please add https://github.com/cesanta/elk

### ISSUE THREAD

**Issue by cpq** [arduino/Arduino#11471]
https://github.com/cesanta/elk is a tiny JavaScript engine for embedded systems

**Comment by per1234** [comment]
Hi @cpq. Thanks for your interest in contributing to the Arduino Library Manager index.

I see that you already added this library back in 2019: https://github.com/arduino/Arduino/issues/9310 Since no additional action is needed on our part, I'll go ahead and close this.
