### ISSUE TITLE
Incorrect SPI pins in Leonardo pinout.

### ISSUE THREAD

**Issue by oqibidipo** [arduino/Arduino#11470]
https://content.arduino.cc/assets/Pinout-Leonardo_latest.pdf 
pages 1 and 2

Pins 10 to 13 are marked as SPI pins when in reality SPI is only on the ISP header.

**Comment by FunzioneFabio** [comment]
Thank you @oqibidipo for poiting out this error, the pinout is now corrected and online!
https://content.arduino.cc/assets/Pinout-Leonardo_latest.pdf
https://store.arduino.cc/arduino-leonardo-with-headers

**Comment by gentilkiwi** [comment]
> Thank you @oqibidipo for poiting out this error, the pinout is now corrected and online! https://content.arduino.cc/assets/Pinout-Leonardo_latest.pdf https://store.arduino.cc/arduino-leonardo-with-headers

Can you also please the documentation, on https://docs.arduino.cc/language-reference/en/functions/communication/SPI/#description by example ?
