### ISSUE TITLE
[Library Manager] Please add new library: STM32duinoBLE

### ISSUE THREAD

**Issue by fpistm** [arduino/Arduino#11484]
Hi,
STM32duino is a fork of ArduinoBLE library to add the support of STM32WB, SPBTLE-RF, SPBTLE-1S, BLUENRG-M2SP and BLUENRG-M0 BLE modules.

https://github.com/stm32duino/STM32duinoBLE

Thank you

**Comment by cmaglie** [comment]
Done.
