### ISSUE TITLE
Add Tuya wifi mcu-sdk library

### ISSUE THREAD

**Issue by flyingcys** [arduino/Arduino#11486]
Hi :)
Could you please add this library to the library manager?
https://github.com/tuya/tuya-wifi-mcu-sdk-arduino-library

Thanks!

**Comment by per1234** [comment]
Hi @flyingcys. Thanks for your interest in contributing to the Arduino Library Manager index.

You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by flyingcys** [comment]
I have added the release version 0.0.1

Thanks!

**Comment by cmaglie** [comment]
Done.
