### ISSUE TITLE
const String index_html_string PROGMEM = R"rawliteral(  cause Ctrl-T feature to no longer work.

### ISSUE THREAD

**Issue by roblatour** [arduino/Arduino#11497]
I am using the latest nightly build 1.8.14 2021/05/07 12:33

Near the top of my code, I have a global const defined as follows:

`const String index_html_string PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html>
</html> 
)rawliteral";`

defined in that way, my sketch compiles and runs just fine.  However, in the IDE the Ctrl-T feature to autoindent my code no longer works.

I have found that if I put quotes around the literal as follows: 

`const String index_html_string PROGMEM = R"rawliteral("
<!DOCTYPE html>
<html>
</html> 
")rawliteral";`

the sketch compile fine, and the Ctrl-T feature works again, but the program does not run fine as the opening and closing quotes then become included as part of the string itself.

**Comment by per1234** [comment]
Hi @roblatour. Thanks for taking the time to submit an issue.

I see we already have a prior issue report about this at https://github.com/arduino/Arduino/issues/10946.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
