### ISSUE TITLE
[Add Library to Library Manager] for TridentTD_Linenotify V3.0.2  (fix library.properties )

### ISSUE THREAD

**Issue by TridentTD** [arduino/Arduino#11503]
Hi,

Could you please update TridentTD_Linenotify V3.0.1 to the latest V3.0.2 version in library manager?
( Already fixed version in library.properties )

https://github.com/TridentTD/TridentTD_LineNotify/releases/tag/3.0.2

Thank you very much.

**Comment by per1234** [comment]
Hi @TridentTD. Still the same problem as before:
https://github.com/TridentTD/TridentTD_LineNotify/blob/3.0.2/library.properties#L2

You need to update the version, **THEN** make the tag.

Once you've created a compliant tag, everything will be done automagically by the indexer system and the release will be available for installation via Library Manager within the next day, so there is no need to open an issue here for each release.
