### ISSUE TITLE
[Library manager] Please add my Library: Portenta Pro Community Examples

### ISSUE THREAD

**Issue by hpssjellis** [arduino/Arduino#11537]
Please add my Library: Portenta Pro Community Solutions

[https://github.com/hpssjellis/portenta-pro-community-solutions](https://github.com/hpssjellis/portenta-pro-community-solutions)

A growing set of examples that run on the new Arduino PortentaH7 board, Vision Shields and Breakout board.

**Comment by cmaglie** [comment]
Done, sorry for the long delay!
