### ISSUE TITLE
[Library Manager] Please add TridentTD_LineNotify v3.0.3

### ISSUE THREAD

**Issue by TridentTD** [arduino/Arduino#11540]
Please add  TridentTD_LineNotify v3.0.3 to Library Manager.

https://github.com/TridentTD/TridentTD_LineNotify/releases/tag/3.0.3

Thanks and Regards.

**Comment by per1234** [comment]
@TridentTD please don't open an issue here for every release of your library.

Any release that meets all the requirements, as documented [here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) is automatically added to Library Manager within a few hours. After the initial submission of the library to the index, everything is handled in a 100% automated manner.

We have already explained this to you multiple times over the last few years:
- https://github.com/arduino/Arduino/issues/7800
- https://github.com/arduino/Arduino/issues/8378
- https://github.com/arduino/Arduino/issues/11503
