### ISSUE TITLE
[Library Manager] Request to add to Library Manager

### ISSUE THREAD

**Issue by GyverLibs** [arduino/Arduino#11557]
Hello! I'am known russian developer and Arduino popularizer, and I have a bunch of libraries. It would be great to add them to Library Manager.

Display:
- [x] https://github.com/GyverLibs/SevenSegmentsDisp
- [x] https://github.com/GyverLibs/GyverTM1637
- [x] https://github.com/GyverLibs/GyverOLED
- [x] https://github.com/GyverLibs/GyverMAX7219

Sensors:
- [x] https://github.com/GyverLibs/microDS18B20
- [x] https://github.com/GyverLibs/microDS3231
- [x] https://github.com/GyverLibs/Psychrometer
- [x] https://github.com/GyverLibs/Tachometer
- [x] https://github.com/GyverLibs/GyverNTC
- [x] https://github.com/GyverLibs/GyverHX711
- [x] https://github.com/GyverLibs/GyverBME280

Hardware input:
- [x] https://github.com/GyverLibs/EncButton
- [x] https://github.com/GyverLibs/NecDecoder
- [x] https://github.com/GyverLibs/AnalogKey
- [x] https://github.com/GyverLibs/GyverButton
- [x] https://github.com/GyverLibs/GyverEncoder

Hardware output:
- [x] https://github.com/GyverLibs/GRGB
- [x] https://github.com/GyverLibs/microLED
- [x] https://github.com/GyverLibs/ServoSmooth
- [x] https://github.com/GyverLibs/SoftServo
- [x] https://github.com/GyverLibs/GyverRelay
- [x] https://github.com/GyverLibs/PWMrelay
- [x] https://github.com/GyverLibs/GyverStepper
- [x] https://github.com/GyverLibs/GyverMotor
- [x] https://github.com/GyverLibs/GyverDimmer
- [x] https://github.com/GyverLibs/AccelMotor

AVR periphery:
- [x] https://github.com/GyverLibs/GyverWDT
- [x] https://github.com/GyverLibs/microWire
- [x] https://github.com/GyverLibs/GyverTimers
- [x] https://github.com/GyverLibs/directTimers
- [x] https://github.com/GyverLibs/directADC

Algorithms:
- [x] https://github.com/GyverLibs/GyverFilters
- [x] https://github.com/GyverLibs/GyverPID
- [x] https://github.com/GyverLibs/mString
- [x] https://github.com/GyverLibs/VolAnalyzer
- [x] https://github.com/GyverLibs/Random16
- [x] https://github.com/GyverLibs/Hamming
- [x] https://github.com/GyverLibs/TimeRandom
- [x] https://github.com/GyverLibs/UnixTime
- [x] https://github.com/GyverLibs/GyverGFX
- [x] https://github.com/GyverLibs/GyverFIFO
- [x] https://github.com/GyverLibs/Forecaster
- [x] https://github.com/GyverLibs/fixed
- [x] https://github.com/GyverLibs/FFT_C
- [x] https://github.com/GyverLibs/BitPack
- [x] https://github.com/GyverLibs/Clap
- [x] https://github.com/GyverLibs/CRT

Communication:
- [x] https://github.com/GyverLibs/FastBot
- [x] https://github.com/GyverLibs/Gyver433
- [x] https://github.com/GyverLibs/GyverBus
- [x] https://github.com/GyverLibs/GParser
- [x] https://github.com/GyverLibs/AsyncStream

System:
- [x] https://github.com/GyverLibs/GyverPWM
- [x] https://github.com/GyverLibs/GyverTimer
- [x] https://github.com/GyverLibs/GyverUART
- [x] https://github.com/GyverLibs/TimerMs
- [x] https://github.com/GyverLibs/GyverPower
- [x] https://github.com/GyverLibs/GyverOS
- [x] https://github.com/GyverLibs/buildTime

**Comment by cmaglie** [comment]
Done, whew!

**Comment by GyverLibs** [comment]
Many thanks!
