### ISSUE TITLE
Library Manager] Request to add to Library Manager: MS5x

### ISSUE THREAD

**Issue by abishur** [arduino/Arduino#11555]
Please add my library to the library manager for the MS5xx, MS6xx, MS7xx, and MS8xx line of pressure sensors

https://github.com/abishur/ms5x

**Comment by per1234** [comment]
Hi @abishur. Thanks for your interest in contributing to the Arduino Library Manager index.

Before we can add your library to Library Manager, you need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by abishur** [comment]
I h ave added the release that matches the tag in my library.properties file, thanks!

**Comment by cmaglie** [comment]
Done.
