### ISSUE TITLE
Library Manager index is not updated

### ISSUE THREAD

**Issue by jandrassy** [arduino/Arduino#11552]
I made a release of <del>EthernetENC</del> UIPEthernet 2.0.10 yesterday and it is still not in Library Manager.
on https://www.arduinolibraries.info/ last addition is 20 hours ago

**Comment by per1234** [comment]
Hi @jandrassy is it this one?:
https://github.com/jandrassy/EthernetENC/tags

The latest tag is 2.0.1 and that one is in the Library Manager index:
![Clipboard01](https://user-images.githubusercontent.com/8572152/119221999-03bdb080-baa7-11eb-92e5-74d2c6be5db2.png)

**Comment by jandrassy** [comment]
Per, tag is 2.0.10

**Comment by per1234** [comment]
OK, thanks for the update. The Library Manager indexer is currently undergoing maintenance so no new releases are being picked up. I'll post an update here once it is back in action.

**Comment by jandrassy** [comment]
it works now
