### ISSUE TITLE
New Library for MAX7219 7 Segment Dispays - supports AVR and ESP

### ISSUE THREAD

**Issue by ArduinoShop** [arduino/Arduino#11575]
I am submitting a new Library for consideration of adding to the Library List.

It has many functions and supports ESP32, ESP8266, AVR, ATmega2560 with easy to use defaults for the novice user, using the IDE board selection...

It is available at https://github.com/ArduinoShop/Seg7

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

You can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/duinoShop/Seg7/
