### ISSUE TITLE
new library generic-Arduino

### ISSUE THREAD

**Issue by noah1510** [arduino/Arduino#11579]
Please add https://github.com/noah1510/generic-Arduino to the Arduino library manager.

This is a compatibility layer that makes developing libraries a lot easier.

Regards
Noa Sakurajin

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/noah1510/generic-Arduino/
