### ISSUE TITLE
[Library manager] Please add NETSGPClient library

### ISSUE THREAD

**Issue by enwi** [arduino/Arduino#11578]
Please add the NETSGPClient library found at [https://github.com/atc1441/NETSGPClient](https://github.com/atc1441/NETSGPClient) to the library manager.

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/atc1441/NETSGPClient/
