### ISSUE TITLE
[Library manager] Please add PNGdec

### ISSUE THREAD

**Issue by bitbank2** [arduino/Arduino#11581]
Please add PNGdec library to the Arduino library manager

url:
https://github.com/bitbank2/PNGdec

Thank you

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/bitbank2/PNGdec/
