### ISSUE TITLE
[Library manager] Request to add libraries

### ISSUE THREAD

**Issue by dimag0g** [arduino/Arduino#11587]
Hello,

Please, can you add my PPM Reader library
https://github.com/dimag0g/PPM-reader

Best regards,
dimag0g

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/dimag0g/PPM-reader/
