### ISSUE TITLE
[Library Manager] Please add new library: RP2040_PIO_Charlieplexing

### ISSUE THREAD

**Issue by pierremolinaro** [arduino/Arduino#11585]
Hello,

Please, can you add my RP2040_PIO_Charlieplexing library (Charlieplexing using RP2040's PIO):
https://github.com/pierremolinaro/rp2040-charlieplexing

Best regards,

Pierre Molinaro

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/pierremolinaro/rp2040-charlieplexing/
