### ISSUE TITLE
Add SparkFun Qwiic 6DoF Arduino Library to library manager

### ISSUE THREAD

**Issue by edspark** [arduino/Arduino#11582]
Good afternoon,

Could you please add the [SparkFun Qwiic 6DoF LSM6DSO Arduino Library](https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library) to the library manager at your earliest convenience?

Thank you!

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library/
