### ISSUE TITLE
[Library manager] Request to add libraries 

### ISSUE THREAD

**Issue by RCmags** [arduino/Arduino#11584]
Hi! Please add these libraries to the manager:

https://github.com/RCmags/vector_datatype
https://github.com/RCmags/ADNS3080
https://github.com/RCmags/basicMPU6050
https://github.com/RCmags/imuFilter

Thanks!

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/RCmags/vector_datatype/
http://downloads.arduino.cc/libraries/logs/github.com/RCmags/ADNS3080/
http://downloads.arduino.cc/libraries/logs/github.com/RCmags/basicMPU6050/
http://downloads.arduino.cc/libraries/logs/github.com/RCmags/imuFilter/
