### ISSUE TITLE
[Library Manager] Please add new library: ERO

### ISSUE THREAD

**Issue by syed93uthman** [arduino/Arduino#11586]
Hello,

Please, can you add my ERO library
https://github.com/Mysues/ERO

Best regards,
Syed Uthman

**Comment by per1234** [comment]
Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.

The library(s) will be available for installation via Library Manager within a day's time.

After that, you can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/Mysues/ERO/
