### ISSUE TITLE
avrdude: ser_open(): can't open device "/dev/ttyACM0": Input/output error

### ISSUE THREAD

**Issue by cao-huahua** [arduino/Arduino#11593]
Hello, my arduino board is uno with ATMEGA 328P. I`m using Arduino IDLE on my ubuntu desktop, apperanttly, something is going wrong. I just can`t connect to arduino and I try to fix it by searching on the internet, discussions, comunnities but all the methods didnt worked for me. Is anyone of u had that kind of experience?

Oh, the last thing I`d say is the last time I`d used the arduino it was fine and I don`t remember anytime it was running on the ACM0 ports, generally, it was USB0.
  
I would been very grateful for the answers.

**Comment by per1234** [comment]
Hi @cao-huahua. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/c/using-arduino/avrdude-stk500-bootloader-issues/81
