### ISSUE TITLE
Arduino Ethernet Shield R3, SD Card crashes arduino when library included.

### ISSUE THREAD

**Issue by kylemaes** [arduino/Arduino#1159]
Any time I use the Ethernet shield and include the SD library my Ethernet doesn't function and the Arduino reboots randomly and does weird things. The SD card can be written to and I have not yet tested reading with the Ethernet on, but the Ethernet once again refuses to function properly (when #include <SD.h> is in the code)...

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#13
