### ISSUE TITLE
Short circuit in schematic

### ISSUE THREAD

**Issue by antonilol** [arduino/Arduino#11596]
Just found a short circuit in one of the schematics [here](https://www.arduino.cc/en/Tutorial/BuiltInExamples/KeyboardAndMouseControl). Other schematics on the page are correct.

The wrong one:
![hot](https://user-images.githubusercontent.com/49868160/121812812-a06c0c00-cc69-11eb-9a4e-8a380e74568c.png)

This one is correct:
![ok](https://user-images.githubusercontent.com/49868160/121812917-2425f880-cc6a-11eb-9f19-e302f40fae6b.png)

**Comment by kengdahl** [comment]
@per1234 I have reported this to Content for a fix.

**Comment by per1234** [comment]
Thanks so much for reporting this error @antonilol. I see it has been corrected.
