### ISSUE TITLE
`library.properties` "Developer" field information is rendering both old and new variants in Library Manager.

### ISSUE THREAD

**Issue by zfields** [arduino/Arduino#11618]
When I first created the **Blues Wireless Notecard Pseudo Sensor** library, I accidentally used my name in the "Developer" field, as opposed to my company's name, Blues Wireless. To fix it, I updated the `library.properties` file, and revved the version to 1.0.1.

When you first search for "Blues Wireless" in the library manager, the library entry says "by: Blues Wireless", reflecting the latest update. However, when you hover over or highlight the library search result, the name returns to the original, "by: Zachary J. Fields".

I'm not sure where to file this bug, but I would like the name to be the company name, so folks know it's an officially supported library.

**Comment by per1234** [comment]
This should be resolved in Arduino IDE 2.0.0. Please give it a try. The download links are listed here:

https://www.arduino.cc/en/software/

If the problem still occurs, you can submit a report with the updated details here:

https://github.com/arduino/arduino-ide/issues/new/choose
