### ISSUE TITLE
Add wifi kit 8 to boards (ESP8266)

### ISSUE THREAD

**Issue by gneiss15** [arduino/Arduino#11622]
I use a "Wifi Kit 8" from Heltec. This board is not included in the current tool chain for the ESP8266.
I modified boards.txt.py and added the variant, so his kit is selectable using the normal "board selection".
There is a separate tool chain that supports this board (by installing a library from Aron Lee), but this uses a far outdated version of the ESP8266 tool chain. By adding this board to the official too chain it can be used without installing an extra (outdated) tool chain.
I attach a zip archive that contains the modified boards.txt.py as well as the folder "wifi_kit_8" with the file "pins_arduino.h" that  has to be put inside the "variants" folder.
I hope that was the correct way to supply such a change.

[WifiKit8.zip](https://github.com/arduino/Arduino/files/6745121/WifiKit8.zip)
.

**Comment by per1234** [comment]
Hi @gneiss15. Thanks for your interest in this open source project. This repository and issue tracker is for the Arduino IDE's code base. The ESP8266 boards platform is a 3rd party project not maintained by Arduino, so proposals for changes to that platform are off topic here.

>I hope that was the correct way to supply such a change.

In addition to being in the wrong repository, this is not the correct way to supply such a change even in the correct repository. The mechanism for doing this is called a "pull request". You can learn about it here:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests
If you would like additional assistance, feel free to post on the Arduino Forum:
https://forum.arduino.cc/

We'll be happy to help you out over there:
