### ISSUE TITLE
Flatpak package update

### ISSUE THREAD

**Issue by MartinIIOT** [arduino/Arduino#11633]
Hello,
is it possible to update Flatpak package (https://flathub.org/apps/details/cc.arduino.arduinoide) and distribute every latest version to this repository?

Thank you

**Comment by per1234** [comment]
Hi @MartinIIOT. Thanks for your interest in this open source project.

The Flatpak package is a 3rd party project that Arduino has no direct involvement with, so inquiries about it are off-topic here. It looks like the appropriate place to report issues or make feature requests is here:
https://github.com/flathub/cc.arduino.arduinoide

If you want the latest official version of the Arduino IDE, it is always available from the "Software" page on arduino.cc:
https://www.arduino.cc/en/software

**Comment by MartinIIOT** [comment]
Thank you
