### ISSUE TITLE
Elevator with 3 floors

### ISSUE THREAD

**Issue by salmanStronger** [arduino/Arduino#11657]
first we looked for how to plan and the parts that we require and after that we begin work we brought the wood and shaped a base so that the portion is devoted to the elevator and the other for cutting as shown in Figure 1 and after that We have installed the buttons for the primary, second ,third ,the a pointer up, a pointer down, emergency and after that the green and red lights And finally 7 segment in a wooden board as appeared in Figure 2, and after that we associated the wires and welded them and associated them with the Arduino and at last we tried them one by one and we writing the code in Arduino ide within the language of C ++, Then introducing pulley and rope At the top the wooden box and interfacing it to the elevator, and after that we linked him to the Motor driver , and then connecting it to the Arduino and we tested the motor, finally we connected the batteries And then we opened three openings between the part designated for the elevator and the pieces in order to put the sensors in it and each sensor has one floor in order to know the location of the elevator we tested them ,then we installed the wooden board, Arduino and motor in the wooden box ,then we wrote the code to run it

**Comment by per1234** [comment]
Hi @salmanStronger. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This is neither, so I'll go ahead and close it invalid.

You can use the Arduino Project Hub to share your projects:
https://create.arduino.cc/projecthub
