### ISSUE TITLE
Add a "Reload" option in the File menu to refresh a file that was modified by an external editor.

### ISSUE THREAD

**Issue by gitmeister** [arduino/Arduino#11667]
Is your feature request related to a problem? Please describe.
I often use Notepad++ to better visualize code and because the IDE is often fairly slow to load (even on my high-end W10 system with a SSD) I often leave it running with the project loaded.

Describe the solution you'd like
The addition of a "Reload" option in the File menu.

Describe alternatives you've considered
The only solution I know of is to File->New, Close the Project, and File->Open Recent....etc

Additional context

**Comment by per1234** [comment]
Hi @gitmeister. I see you already submitted the same request 5 years ago at https://github.com/arduino/Arduino/issues/5345.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

You'll be glad to learn that [the beta phase Arduino IDE 2.x](https://www.arduino.cc/en/software#experimental-software) automatically loads external changes (as requested in https://github.com/arduino/Arduino/issues/4551). There was also some work done to add the same capability to the classic Arduino IDE in https://github.com/arduino/Arduino/pull/6074 but it was never finished.
