### ISSUE TITLE
Preprocessor files / temporary compile files not saved

### ISSUE THREAD

**Issue by madworm** [arduino/Arduino#1166]
I started with a clean 1.0.2 installation, wiped the preferences.txt file as well. Enabled "preproc.save_build_files=true", but all that remains in /tmp/buildXXXXX is the .cpp and .cpp.d file. I would like to see the code after it has gone through the preprocessor with all text replacements done to debug compilation errors.

I think "-save-temps" would be nice to have.

**Comment by ffissore** [comment]
The `/tmp/buildXXXXX.cpp` file is the result of the preprocessing done by the IDE.
Related to preprocessing, you may want to give a spin to this version of the IDE bundled with a new preprocessor
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/4X2T3rCxXWM/nQEnH-9wmhMJ

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by ffissore** [comment]
New preprocessor available in nightly builds. Temporary files are preserved when using CLI and specifying `--preserve-temp-files`. See https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
