### ISSUE TITLE
Unable to upload the example file sensortest.ino

### ISSUE THREAD

**Issue by jimmoroz** [arduino/Arduino#11665]
I have successfully downloaded the library files and compiled with no errors.

I set to port 5 since Tools/Port indicated that 5 was connected to the Ardrino.

I selected upload and got this error.  

avrdude: Version 6.3-20190619
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\jgmor\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17/etc/avrdude.conf"

         Using Port                    : COM5
         Using Programmer              : arduino
         Overriding Baud Rate          : 115200
avrdude: ser_open(): can't open device "\\.\COM5": Access is denied.

avrdude done.  Thank you.

Upload error: Error: 2 UNKNOWN: uploading error: uploading error: exit status 1

Searched the web and the Audrino sites but no luck.  I have successfully downloaded and the example program "code_for_dht11.ino" successfully but this program fails to upload. 

Amy Ideas?
Jim

**Comment by per1234** [comment]
Hi @jimmoroz. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
