### ISSUE TITLE
Cannot Open Arduino

### ISSUE THREAD

**Issue by RockZombie123** [arduino/Arduino#11675]
This is a reopening of: Cannot Open Arduino

`/home/pi/Downloads/arduino-nightly/arduino: line 35: /home/pi/Downloads/arduino-nightly/java/bin/java: cannot execute binary file: Exec format error
`

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/11673

@RockZombie123 you already have an issue for this subject. Please just use the one. If we determine that there is a valid bug report, that other issue will be reopened.
