### ISSUE TITLE
How can I contribute to translate the Arduino Sensor Kit webpage into German language

### ISSUE THREAD

**Issue by Bodobolero** [arduino/Arduino#11671]
I am professional software developer, native German speaker and Arduino fan.

I would like to help create the German translation for the sensor kit lessons

https://sensorkit.arduino.cc

Currently it has English, Spanish, and a few other languages but not German.
Is German already work in progress or can I help?
I did not find a GitHub repo for this documentation.

**Comment by Bodobolero** [comment]
@kengdahl interested?

**Comment by g-castronovo** [comment]
@Bodobolero Guten Morgen! I am Gaia and I am the localisation specialist at Arduino. Currently, Sensorkit content isn't open to the community for translations. The localisation in German isn't planned for 2021. However, I'll forward the request and see if there is interest for it. Nontheless, I'd like to thank you for your support!

**Comment by kengdahl** [comment]
I will close this Issue since @Bodobolero has his answer.
