### ISSUE TITLE
incorrect menu positions, menus only open while mouse click 

### ISSUE THREAD

**Issue by ShantySuffisance** [arduino/Arduino#11680]
in antiX-19.4, using Arduio IDE 1.8.16, the menus are very hard to use, they are often at wrong positions and are only open, while the mouse holds a click. 

![bug](https://user-images.githubusercontent.com/63818756/136422911-766de8db-c6ce-4469-8c54-65592bc582b7.jpg)

please let me know, if i'd better report to antiX instead… thank you for that wonderful pieco of software!

**Comment by per1234** [comment]
Hi @ShantySuffisance. Thanks for your report.

Only maintainers can transfer issues between repositories, which I have now done. I appreciate your care for the issue being in the correct place.

**Comment by per1234** [comment]
This should be resolved in Arduino IDE 2.0.0. Please give it a try. The download links are listed here:

https://www.arduino.cc/en/software/

If the problem still occurs, you can submit a report with the updated details here:

https://github.com/arduino/arduino-ide/issues/new/choose
