### ISSUE TITLE
UI problem in Preferences window (macOS, Rosetta 2 on Apple Silicon)

### ISSUE THREAD

**Issue by seaxwi** [arduino/Arduino#11684]
<img width="800" alt="Preferences" src="https://user-images.githubusercontent.com/71350948/137105651-29e5be1b-28b2-4608-9e34-362f5b4a8cb9.png">

Using 1.8.16

Does _not_ occur running on Intel mac.

**Comment by per1234** [comment]
Thanks @seaxwi. This should be resolved in Arduino IDE 2.0.0.
