### ISSUE TITLE
Ubuntu fresh load of Arduino 0018 then upgrade to 1.0.2 gives GLIBC_2.8 error

### ISSUE THREAD

**Issue by eelmot** [arduino/Arduino#1169]
Arduino 0018 gave other errors when "uploading"( I don't have a board yet,
But when I upgraded, and run with the 1.0.2 version, it gives this error:   I can't find the download or .deb file for it.
/home/eelmot/jdk/arduino-1.0.2/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/cc1plus: /lib/tls/i686/cmov/libc.so.6: version `GLIBC_2.8' not found (required by /home/eelmot/jdk/arduino-1.0.2/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/cc1plus)

I have previously added the line
deb http://ftp.us.debian.org/debian squeeze main 
to
 /etc/apt/sources.list
and that seems to have gotten everthing for the 0018 version

**Comment by ffissore** [comment]
Unable to reproduce
