### ISSUE TITLE
Arduino DUE schematic PinOut SPI pins Wrong

### ISSUE THREAD

**Issue by tistructor** [arduino/Arduino#11691]
By checking where the Arduino DUE SPI pins are located on the pinout scheme I found these errors or presumed to be such for me:

It is indicated on the double Digital pins D50-D53 as SPI but this does not appear in the wiring diagram.

The labels on the SPI pins on the SPI connector are also wrong and precisely all three are reversed.

the correct sequence is this:
1: MISO (CIPO) PA25         SPI0_MISO PA25 
2: VCC
3: SCK PA27                       SPI0_SPCK PA27
4: MOSI (COPI) PA26         SPI0_MOSI PA26 
5: RESET
6:GND

Datasheet Microchip Pg. 679 https://www.microchip.com/content/dam/mchp/documents/OTH/ProductDocuments/DataSheets/Atmel-11057-32-bit-Cortex-M3-Microcontroller-SAM3X-SAM3A_Datasheet.pdf

Table 32-2. I/O Lines Instance Signal I/O Line Peripheral
SPI0 SPI0_MISO PA25 
SPI0 SPI0_MOSI PA26 
SPI0 SPI0_SPCK PA27

**Comment by per1234** [comment]
Thanks @tistructor!

The pinout in question is the "full pinout" available for download here:
https://store.arduino.cc/products/arduino-due#docs
and here:
https://docs.arduino.cc/hardware/due#resources

Maybe @FunzioneFabio can help us out with this one.

**Comment by FunzioneFabio** [comment]
@per1234 Sure, thank you for pointing out this, I will fix this asap.

**Comment by FunzioneFabio** [comment]
The pinout has been updated!

**Comment by per1234** [comment]
Thank you @FunzioneFabio

**Comment by tistructor** [comment]
Thanks also from me. @FunzioneFabio

**Comment by FunzioneFabio** [comment]
@tistructor Yeah sorry I forgot, thank you so much for spotting the error, this have improved our documentation!
