### ISSUE TITLE
feature request: String member readStringUntil()  

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#11707]
feature request: String member readStringUntil()
just like available in SD/File class and stream.

**Comment by per1234** [comment]
Hi @dsyleixa. I see you made another report about this at https://github.com/arduino/ArduinoCore-API/issues/152.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
