### ISSUE TITLE
How to make a load cell liquid filling machine?

### ISSUE THREAD

**Issue by Oceanlig** [arduino/Arduino#11719]

**Comment by per1234** [comment]
Hi @Oceanlig. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. It is NOT a place to ask for help with your project. The appropriate place for that is the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/

**Comment by Oceanlig** [comment]
Thanks for guidance
