### ISSUE TITLE
Unofficial-list-of-3rd-party-boards-support-urls please add link

### ISSUE THREAD

**Issue by jpnielsen** [arduino/Arduino#11732]
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

please add:

Raspberry Pi Pico Arduino core, for all RP2040 boards
https://github.com/earlephilhower/arduino-pico/

https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

**Comment by per1234** [comment]
Thanks @jpnielsen. I have added it:
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls/_compare/fcb3865b319111fe82da82c250b3301ea15603f8...4eb7cf856c9b36fcbb1d77a55a6cafee9e7848ac

I have also restored the public editing permissions to the wiki so everyone will once again be able to contribute to it. There was some malicious activity in the wiki and so I temporarily disabled editing.
