### ISSUE TITLE
MKR WAN 1300 Getting Started errata

### ISSUE THREAD

**Issue by TheOldBrick** [arduino/Arduino#11731]
On the page [https://www.arduino.cc/en/Guide/MKRWAN1300](https://www.arduino.cc/en/Guide/MKRWAN1300)

- "For more details on the Arduino MKR WAN 1300 , see the product page."

The link is broken.

It points to https://store.arduino.cc/arduino-mkrwan1300?_gl=1*pi8tqc*_ga*MTg4MDEyOTgyMC4xNjM3NDY2NDcz*_ga_NEXN8H46L5*MTY0MDQ4MjYzNS44LjEuMTY0MDQ4NTg0MC4w

It should probably point to https://docs.arduino.cc/hardware/mkr-wan-1300

- "Here a list of tutorials that will help you in making very cool things!"

The list is poorly formatted; rather than a list, it's just one line of wrapping text that contains three items

**Comment by kengdahl** [comment]
@TheOldBrick The page: https://www.arduino.cc/en/Guide/MKRWAN1300 is now redirected to https://docs.arduino.cc/hardware/mkr-wan-1300

I'm closing this issue.
