### ISSUE TITLE
Truncated text when compiling

### ISSUE THREAD

**Issue by rtek1000** [arduino/Arduino#11745]
**Describe the bug**

This occurs when compiling the examples for the ESP32 board.
Please see screenshot.
I started to notice this problem after updating the IDE to the latest version, version 1.8.13 didn't have it.

**To Reproduce**

**Expected behavior**

**Screenshots**
![arduino_ide_debug](https://user-images.githubusercontent.com/8660811/150463520-b991ab7f-5b95-4c96-b12e-6e4774569ddc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 2.0.0]

**Additional context**

**Comment by per1234** [comment]
Thanks @rtek1000. This should be resolved in Arduino IDE 2.0.0. Please give it a try. The download links are listed here:

https://www.arduino.cc/en/software/

If the problem still occurs, you can submit a report with the updated details here:

https://github.com/arduino/arduino-ide/issues/new/choose
