### ISSUE TITLE
Program was not compiled

### ISSUE THREAD

**Issue by 19-6105zilleali** [arduino/Arduino#11740]
**avrdude: ser_open(): can't set com-state for "\\.\COM4"** 
                        This error was showing when am compile the code .

**Comment by per1234** [comment]
Hi @19-6105zilleali. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
