### ISSUE TITLE
discovery does not send 'hello' as first command

### ISSUE THREAD

**Issue by ben-qnimble** [arduino/Arduino#11743]
Per the specification for pluggable discovery (https://arduino.github.io/arduino-cli/0.20/pluggable-discovery-specification/):
```
HELLO must be the first command sent to the discovery
```
but the 1.x Arduino IDE does not send the hello command. On starting a discovery, the first command it sends is START_SYNC which fails for [serial-discovery](https://github.com/arduino/serial-discovery) and discoveries based on it because they catch and error when the first command is not hello:

```
$ /packages/builtin/tools/serial-discovery/1.3.1/serial-discovery.exe
START_SYNC
{
  "eventType": "command_error",
  "message": "First command must be HELLO, but got 'START_SYNC'",
  "error": true
}
```
The arduino-cli does send the HELLO command first so this is not a problem in Arduino IDE 2.x, and I believe Arduino IDE 1.x should match this behavior.

**Comment by per1234** [comment]
Thanks for your report @ben-qnimble. This is considered resolved by the Arduino IDE 2.0.0 stable release.
