### ISSUE TITLE
Arduino IDE crashed when window lock or laptop sleep

### ISSUE THREAD

**Issue by rjrahul25** [arduino/Arduino#11757]
Arduino IDE crashes when windows lock screen or computer is in sleep mode. the faced issue in windows 11 only.

**Comment by per1234** [comment]
Hi @rjrahul25. Thanks so much for reporting this.

Which version of the Arduino IDE are you using?

When you say "crashed", do you mean that the IDE just exits unexpectedly?

Are there any error or warning messages associated with the problem? If so, please post the full and exact text of them here.

**Comment by per1234** [comment]
Closing due to lack of response.

@rjrahul25 if you will provide the requested information by commenting here, I'll be happy to re-open this issue.
