### ISSUE TITLE
Arduino IDE does not display correctly on Windows at 3840 × 2400 resolution

### ISSUE THREAD

**Issue by ixfd64** [arduino/Arduino#11764]
The Arduino IDE does not display correctly on Windows systems set to 3840 × 2400 resolution.

**To Reproduce**
1. Install the Arduino IDE on a Windows system that supports up to 3840 × 2400 resolution
2. Launch the application.

**Expected behavior**
The Arduino IDE should scale to fit the screen's resolution.

**Actual behavior and screenshot**
On higher resolutions, the splash screen is very small and the layout is messed up.

![Arduino_highres](https://user-images.githubusercontent.com/1526759/154206925-d7026c0f-cdef-46c1-a739-0015137dd5e1.png)

**Desktop:**
 - OS: Windows 10
 - Version: 2H11

**Additional context**
The splash screen appears normal if I enable high DPI scaling override. However, the application window will not appear unless I reduce the system resolution and change it back again.

**Comment by per1234** [comment]
Thanks @ixfd64. This should be resolved in Arduino IDE 2.0.0. Please give it a try. The download links are listed here:

https://www.arduino.cc/en/software/

If the problem still occurs, you can submit a report with the updated details here:

https://github.com/arduino/arduino-ide/issues/new/choose
