### ISSUE TITLE
Changing Application Icon - where ?

### ISSUE THREAD

**Issue by StefanL38** [arduino/Arduino#11760]
Hi everybody,

I want to know where the application-icon that is shown in the taskbar 
![grafik](https://user-images.githubusercontent.com/8948220/153938160-233d2e7c-eebe-4ec0-8325-feb826ef2244.png)

and in the app-overview shown after pressing Alt-TAB 
![grafik](https://user-images.githubusercontent.com/8948220/153938103-89921446-d83a-47e8-b134-6965ef885093.png)

is located. 
I want to change that Icon to a different color.

best regards Stefan

**Comment by per1234** [comment]
Hi @StefanL38. Here you can see an example of how to change the application icons:

https://github.com/arduino/Arduino/pull/9834/files
