### ISSUE TITLE
MacOS Monterey 12.3 - no more python 2 - Arduino cannot compile any sketch

### ISSUE THREAD

**Issue by homonto** [arduino/Arduino#11771]
Since the newest MacOS upgrade to 12.3 there in no python in MacOS
Installing python3 by any ways does not solve the problem and Arduino cannot find the python script to compile the sketch:

after installing python3 using brew, my .zprofile looks like this:

```
    PATH="/opt/homebrew/bin:${PATH}"
    export PATH
```

and command "echo $PATH" shows:

```
% echo $PATH
/opt/homebrew/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
```

and after linking python3 to python by command:
`ln -s `which python3` /opt/homebrew/bin/python`

```
~ % which python
/opt/homebrew/bin/python
```

but Arduino still cannot execute command: 

   ` python /Users/me/Library/Arduino15/packages/esp32/hardware/esp32/2.0.2/tools/gen_esp32part.py `

saying:

    `exec: "python": executable file not found in $PATH`

**Comment by per1234** [comment]
Hi @homonto. Thanks for your interest in this open source project.

The Arduino IDE does not use Python in any way, so the lack of Python is no problem at all for this project.

The Arduino IDE build system allows the authors of the Arduino boards platforms to use any arbitrary tools for compiling for and uploading to the boards. The 3rd party ESP32 boards platform happens to expect macOS users to have Python pre-installed and available via the command `python`. That fact is not relevant to the development of the Arduino IDE or the code that is hosted in this repository, so I will close this as off topic.

If you would like help with using the ESP32 boards platform, please make a post on the Arduino forum. I'm sure we'll be able to help you out over there:

https://forum.arduino.cc/
