### ISSUE TITLE
[Ubuntu 21.10] UTF-8 symbols not displayed properly in IDE

### ISSUE THREAD

**Issue by Batwam** [arduino/Arduino#11783]
I am using code which includes UTF-8 symbols (for export to a web page). These symbols are displayed fine on the Windows version of the IDE but when I open the file in Ubuntu, most of them are not being displayed (there is no specific error generated in the terminal).

For examples UTF-8 symbols like these are not showing: 🌞 🌑 🌔 🌜🌙
As I long as I don't touch the file, the characters are still exported with the code compilation as they still appear on the web page but the IDE is not displaying them.

Is this a known issue with the IDE? I am the IDE using 1.8.15

Content of my update-locale
```
LANG="en_AU.UTF-8"
LANGUAGE="en_AU:en"
```

# Screenshots
Windows version:
![Capture](https://user-images.githubusercontent.com/56710655/163330022-c8323572-2d03-4710-9ce5-7b71ff2da0c5.PNG)

Ubuntu 21.10 version:
![Screenshot from 2022-04-14 14-39-20](https://user-images.githubusercontent.com/56710655/163330214-89f5c435-5845-485e-82bc-72a36acad8ca.png)

**Comment by per1234** [comment]
Thanks for your report @Batwam. I am able to reproduce the bug with Arduino IDE 1.8.19, but not with Arduino IDE 2.0.0, so I will close this as resolved.

**Comment by Batwam** [comment]
confirmed, I just tried the 2.0.0 version in Flatpaj and this issue is fixed.
