### ISSUE TITLE
Read a keyboard with Arduino Mega

### ISSUE THREAD

**Issue by Nico4589** [arduino/Arduino#11791]
hi, I have a Arduino mega with which I wanted to read an unconventional keyboard.  But I have no idea how to do it.  The keyboard has a USB type B port. My goal would be to detect only the reading that any key is pressed (without really knowing which key it is).  how can I do?  thank you

**Comment by per1234** [comment]
Hi @Nico4589. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
