### ISSUE TITLE
Arduino IDE latest version 1.8.19 cannot use pico 2040 borad 

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/Arduino#11792]
Hi 
My Arduino IDE version was 1.8.15, and my pico 2040 board can work on this version.
but after I'm updated to the latest version which is 1.8.19, my board cannot upload the program anymore. could you help solve this problem, please?  

![image](https://user-images.githubusercontent.com/47217650/172552860-51cdf189-4095-4fbc-8056-374610ee1bbe.png)

best regards

**Comment by facchinm** [comment]
Answered here https://github.com/arduino/ArduinoCore-mbed/issues/496
