### ISSUE TITLE
Can anyone give code for a project of " Arduino Uno+gps module neo 6m+gsm module sim800l v2.0+ lcd display".
Please help me with working circuit diagram and code.

### ISSUE THREAD

**Issue by qwe12R** [arduino/Arduino#11809]

**Comment by per1234** [comment]
Hi @qwe12R. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
