### ISSUE TITLE
versions 1.8.14 and later (including 1.8.19) broke the expansion of property references in the version property in platform.txt

### ISSUE THREAD

**Issue by ObviousInRetrospect** [arduino/Arduino#11813]
Arduino 1.8.13 supported a version like:

(platform.txt, from https://github.com/SpenceKonde/megaTinyCore/blob/edd683dc9074a0e9844adb825cfb388f5fa74d04/megaavr/platform.txt)
```text
name=megaTinyCore
versionnum.major=2
versionnum.minor=6
versionnum.patch=0
versionnum.postfix=
versionnum.released=0

version={versionnum.major}.{versionnum.minor}.{versionnum.patch}{versionnum.postfix}
```

in 1.8.14 this stopped working. This is causing the author of a few fairly well used cores @SpenceKonde (megaTinyCore, DxCore, ATTinyCore) to recommend the continued use of 1.8.13 as the most recent working build. Unfortunately that build has a vulnerable version of Log4J and lacks a lot of the other good work done since.

This was reported for 2.0 by @per1234 in https://github.com/arduino/arduino-cli/issues/1823 and fixed by @cmaglie in  https://github.com/arduino/arduino-cli/pull/1830

Is there any chance of getting this fix back ported to a 1.8.x release since the behavior used to work in 1.8.13? 

If not, can the documentation be updated to say this is not a supported feature and won't be fixed?

Thanks and sorry it wasn't reported sooner after it broke. Because it only applies to manual installation it took a while to figure out the root cause and was considered nondeterministic for a long time.

**Comment by per1234** [comment]
The Arduino IDE 1.x project is now in maintenance mode so the backport will not be possible.
