### ISSUE TITLE
IDE filters out useful avrdude messages.

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#11823]
We get a fair number of queries on the forums, from people who are trying to upload a bootloader, and get the error message: "avrdude: Expected signature for ATmega328P is 1E 95 0F"
But to take the first steps to diagnose this, we need to know what signature avrdude has actually seen, to distinguish between wiring/clocking problems and ... actual wrong chips (atmega328 vs atmega328p, for example.)  This adds time and complexity to the troubleshooting process.

AVRDUDE itself actually reports both:
```
Reading | ################################################## | 100% 0.05s

avrdude: Device signature = 0x1e9406 (probably m168)
avrdude: Expected signature for ATmega328P is 1E 95 0F
         Double check chip, or use -F to override this check.
```
But the IDE has filtered out the first message containing the "seen" signature, which is ... not at all helpful.  Can it be changed to show both messages, even when "verbose" mode is not selected?

Example:
https://forum.arduino.cc/t/when-i-try-to-burn-bootloader-i-getting-error/1035364

**Comment by per1234** [comment]
Thanks for your report @WestfW. I'm happy to tell you that Arduino CLI and Arduino IDE 2.x don't do any upload output filtering or interpretation such as the Arduino IDE 1.x behavior you report here:

https://github.com/arduino/Arduino/blob/43b0818f7fa8073301db1b80ac832b7b7596b828/arduino-core/src/cc/arduino/packages/Uploader.java#L182-L185

The device signature will be shown in the output when using modern versions of the Arduino development tools.

>Can it be changed to show both messages, even when "verbose" mode is not selected?

I'm not sure about that. Going forward, I think it is best to take a generalized approach in the design of the tools. This sort of tool or architecture-specific code might have made sense back in 2009 when all Arduino boards were AVR, but in this era of an unlimited and quickly increasing number of targets, most of which are maintained by 3rd parties, it really isn't feasible to give them special treatment individually.

The new approach is to always print whatever output comes from the tool. The verbosity setting is used to adjust the upload command "pattern". So each platform author has control over what is shown in verbose and non-verbose modes when uploading to their "boards".
