### ISSUE TITLE
Arduino Nano 33 IoT schematic pin labels on the uBlox module should be updated to match datasheet

### ISSUE THREAD

**Issue by davepruitt** [arduino/Arduino#11830]
The Arduino Nano 33 IoT schematic available online has confusing pin labeling for the uBlox NINA W-102 module.

Web page that links to the schematic: https://store-usa.arduino.cc/products/arduino-nano-33-iot

Direct link to schematic: https://content.arduino.cc/assets/NANO33IoTV2.0_sch.pdf?_gl=1*je5aej*_ga*MTQ3MDIyMjExLjE2NDk4NjQzNzY.*_ga_NEXN8H46L5*MTY2NTQzNzkzOC43MC4xLjE2NjU0Mzc5NzEuMC4wLjA.

Here is the link to the NINA's datasheet: https://www.mouser.com/datasheet/2/1025/NINA_W10_DataSheet__UBX_17065507_-1915911.pdf

In the NINA datasheet, the pin *numbers* and the pin *labels* match (for example pin 2 is "ADC2/GPIO2"). In the Arduino schematic, for some reason pin 2 on the NINA-W102 is labeled "GPIO34". At first I thought I was mistaken, and that pin 2 on the Arduino schematic really is GPIO34 on the NINA, but that is not the case. Pin 2 on the Arduino schematic is really GPIO2 on the NINA, therefore it should not be labeled GPIO34. 

This is confirmed by the fact that the pin _numbering_ on the Arduino schematic matches the pin _numbering_ on the datasheet. In fact, even the label names partially match but the GPIO numbering is totally incorrect. This is true for virtually all the pins. The only correctly labeled pins are "RESET_N" (pin 19) and "ANT" (pin 13).

Please update the schematic so that the labels match their actual names on the datasheet. It is super confusing as it currently is.

Edit:

I've gone ahead and made a Google Sheets spreadsheet that documents the differences. Here is the link: https://docs.google.com/spreadsheets/d/1fg0GdIZRoR-zcgIXvTjGLXLb2gZsSUwlyFW9-ti1eKA/edit?usp=sharing

**Comment by facchinm** [comment]
Hi @davepruitt ,
if you look at datasheet (Section 3.4 Pinout) you'll notice that the symbol in the schematics is showing [ **NINA_pin_functionality** / **ESP-32 GPIO name** ] while the label in front of the pin is the **Nina_pin_name**.
This is done to help developers, since you'll immediately know that if you want to assign the pins for the UART you'll need to use GPIO1 and GPIO3 (of the ESP32).
