### ISSUE TITLE
Platform dependency for packages?

### ISSUE THREAD

**Issue by dmadison** [arduino/Arduino#11839]
Hello,

I'm trying to put together a package index for some 3rd party contributed boards platforms. The first of these packages contains an entire set of core files, while the second just contains some board definitions which make use of that core (with the `build.core` option in `boards.txt`). This works swimmingly, but it requires that the user know that they must manually install the first package.

Is there a way to mark the first package as a dependency for the second?

I saw that [the package index specification](https://arduino.github.io/arduino-cli/0.19/package_index_json-specification/) has options for `toolsDependencies` and `discoveryDependencies`, but not for platforms. My assumption at the moment is that this is a relatively niche case, and the package index specification does not currently support it.

**Comment by per1234** [comment]
Hi @dmadison. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/arduino-cli/issues/954.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
