### ISSUE TITLE
Help with new ATMega4809 registers

### ISSUE THREAD

**Issue by frog6205** [arduino/Arduino#11836]
My Arduino project uses the TLC5955 LED driver to control multiple LEDs, the datasheet is a bit confusing as to what the actual addresses are for each output (my project only needs to turn on and off individual LEDs, nothing fancy). So I thought that I could use some pre-existing code to try and understand what's going off.

[This](https://forum.arduino.cc/t/tlc5955-48-channel-led-driver-not-working-with-my-arduino-code/329823) code works with the Arduino Mega ADK (ATmega2560) but I'm using the Arduino nano every (ATMega4809), it just throws up [these](https://imgur.com/a/mPecVo5) errors. From what I can tell, the register names have changed and I'm struggling to find the new names for 'TCCR1A', 'TCCR1B' and 'OCR1A'.

I would really appreciate any advice.

**Comment by per1234** [comment]
Hi @frog6205. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/programming-questions/20
