### ISSUE TITLE
Can't disable `-Werror`

### ISSUE THREAD

**Issue by dragoncoder047** [arduino/Arduino#11848]
I am trying to add [Janet](https://janet-lang.org/capi/writing-c-functions.html) to my Arduino sketch, which (via using malloc and realloc) does a lot of implicit casts from `void*` to other pointer types.

Unfortunately when I try to compile, the compiler spits out `error: invalid conversion from 'void*' to 'Janet*' [-fpermissive]` (or another random pointer type that is not `void*`) hundreds of times and then aborts because "some warnings are being treated as errors." I know this code is not broken because Janet works :)

I don't have the time to go through and add `(Janet*)` casts to each and every one of these, so I'd rather just set the compiler to leave it a warning and not abort on warnings... but there doesn't seem to be a setting in the arduino settings to enable that. All the "Compiler warnings" dropdown setting does is change how many of these warnings come up. How do I actually disable this behavior?

I am using 1.8.13 on a Raspberry Pi and compiling for an ESP32.

**Comment by per1234** [comment]
Hi @dragoncoder047. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
