### ISSUE TITLE
Problem with Arduino talking to Processing

### ISSUE THREAD

**Issue by outlawracer555** [arduino/Arduino#1185]
Just started with Arduino.  The last example in the book tells you how to build a netowrk lamp with Arduino and Processing. The Processing sketch says "Can not find a class or type named "URL". "
It says this while highlighting a line of code as follows:

URL url = new URL(feed);  // An object to represent the URL

Found many errors in syntax (my mistake) and others in the books example (obviously theirs thad i had to learn to fix).  Not getting this one.  Note that i have no idea how to post a problem on Processing.org's page as is entirely unintuitive and of no help what-so-ever.  

I have a Arduino UNO, running windows Vista and the most recent updates of Processing and Arduino software.  Thanks.

**Comment by ffissore** [comment]
Your issue is about processing, not arduino
