### ISSUE TITLE
The background of Arduino IDE has changed to blue.

### ISSUE THREAD

**Issue by SF433** [arduino/Arduino#11869]
The screen suddenly turned blue during the test for downloading from Board Manager after entering .json into an additional Board Manager. Is it possible to solve it?
![제목 없음](https://user-images.githubusercontent.com/104555715/223965727-fd766c1f-93de-42d9-a95b-2d2b434a03af.png)

**Comment by per1234** [comment]
Hi @SF433. You can fix it by following these instructions:

1. Select **File > Preferences** from the Arduino IDE menus.
   The "**Preferences**" dialog will open.
1. Uncheck the box next to "**Use External Editor**" in the "**Preferences**" dialog.
1. Click the "**OK**" button in the "**Preferences**" dialog.

You will now find Arduino IDE is restored to the editable state.

If you have any other problems or questions, please post on the Arduino Forum:

https://forum.arduino.cc/

I'm sure we'll be able to help you out over there.
