### ISSUE TITLE
Robot

### ISSUE THREAD

**Issue by rubaalsulami** [arduino/Arduino#11861]
I programmed a robot using Arduino uno

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This issue tracker is only to be used for formal bug reports or feature requests. The type of issues you are creating are not appropriate here and have a harmful effect on the important development work done in this repository.

If you would like to share your project, the Arduino Project Hub will be an excellent place to do that:

https://projecthub.arduino.cc/

If you would like assistance with your project, you can post on the Arduino Forum:

https://forum.arduino.cc/
