### ISSUE TITLE
Led Blink

### ISSUE THREAD

**Issue by rubaalsulami** [arduino/Arduino#11862]
I just created a led blink appreciation that works when my analog input exceeds 5 
Using this code 😀 
int input = A0 ;
int LED = 13 ;
int sensorvalue = 0;
Void setup()
{
pinMode(LED,OUTPUT);
}
void loop() {
sensorvalue = analogRead(input);
if (input<= 518) {
    digitalWrite (LED,HIGH);
}
else{
    digitalWrite (LED,LOW);
}
     }

**Comment by per1234** [comment]
Closing as not appropriate for this issue tracker.

@rubaalsulami please see my reply on your other issue to understand the appropriate use of this issue tracker and the alternative places for you to share and discuss your Arduino projects: https://github.com/arduino/Arduino/issues/11861#issuecomment-1425188253
