### ISSUE TITLE
Provide builds for riscv64 host CPU architecture

### ISSUE THREAD

**Issue by N0rbert** [arduino/Arduino#11873]
Currently RISC-V became more and more popular, for example VisionFive 1 and VisionFive 2 SBC platforms are widely available.

Please provide Arduino IDE 1.x for this platform.

**Comment by per1234** [comment]
Hi @N0rbert. Thanks for your interest in this open source project.

Arduino IDE 1.x has been replaced by Arduino IDE 2.x so no further development work will be done on this project. We already have your request for providing RISC-V builds of Arduino IDE 2.x: https://github.com/arduino/arduino-ide/issues/1936
