### ISSUE TITLE
Arduino Based Proximity Feature [Help Wanted] [Question]

### ISSUE THREAD

**Issue by Miba786** [arduino/Arduino#11874]
I am trying to do a proximity feature using Arduino. 

What I am trying to do is develop a system (Consisting of two devices, let's call them Node A and Node B). Node B would ideally be a small device which would be carried by the user while the Node A would be a device mounted on a table. So when the user moves away from the table (Let's say a few meters away) the Node A on the table will trigger an Alarm.

So what I am trying to do is something similar to the car key proximity feature, where while the vehicle is running, if the driver walks away with the key, the vehicle won't be able to move.

Any suggestions on how I can achieve this?

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. It is not a place to request assistance with your Arduino project.

This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
