### ISSUE TITLE
How to disable COM port on Arduino Due only on native port?

### ISSUE THREAD

**Issue by zxcvqwerasdf** [arduino/Arduino#11889]
Is it even possible? I want programming port with COM port enabled and native port only as USB HID device, without COM port.

**Comment by per1234** [comment]
Hi @zxcvqwerasdf. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
