### ISSUE TITLE
Some options in tools available in one IDE and is not available in other

### ISSUE THREAD

**Issue by meakashrao** [arduino/Arduino#11893]
I downloaded Arduino IDE from the Windows store on 29th June 2023 (Arduino 1.8.19 -> Windows Store 1.8.57.0), which doesn't have the some options in the Tools menu options from the same version downloaded via the Windows Store some time ago

Image 1: Arduino IDE downloaded today:
![image](https://github.com/arduino/Arduino/assets/120377875/b6625a65-9324-4c1d-a201-e270868d92de)

Image 2: Arduino IDE downloaded sometime ago
![image](https://github.com/arduino/Arduino/assets/120377875/0056effc-879b-4ba4-bdda-10baea3139e8)

Also, previously downloaded Arduino IDE as mentioned above just required the preferences (https://dl.espressif.com/dl/package_esp32_index.json) and didn't require Boards manager Package to be downloaded while the newly downloaded IDE requires the Boards Manager and doesn't gives these two options

**Comment by per1234** [comment]
Hi @meakashrao 
> the preferences (https://dl.espressif.com/dl/package_esp32_index.json)

This is the reason for the difference. Espressif changed the URL you use in your "**Additional Boards Manager URLs**" preference to get updates of the platform. They stopped maintaining the old URL so you don't get any updates past 1.0.6 when using that URL. The "Arduino Runs On" and "Events Run On" menu items were added in a version of the ESP32 boards platform that came after the 1.0.6 version available from the outdated URL.

In case you would like to update to the modern version of the ESP32 boards platform, I'll provide instructions:

1. Open the web page containing Espressif's official installation instructions for the ESP32 boards platform:
   <https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#installing-using-arduino-ide>
1. Copy the URL shown under the "**Stable release link**" section of that page.
1. Select **File > Preferences...** from the Arduino IDE menus.
   The "**Preferences**" dialog will open.
1. If there is already a URL for the ESP32 boards platform in the "**Additional Boards Manager URLs**" field in the "**Preferences**" dialog, delete it.
1. Add the URL you copied from the ESP32 boards platform installation instructions to the "**Additional Boards Manager URLs**" field.
   **ⓘ** If there are other URLs in the field, separate them with commas (`,`).
1. Click the **<kbd>OK</kbd>** button in the "**Preferences**" dialog.
1. Select **Tools > Board > Boards Manager** from the Arduino IDE menus.
   A "**Boards Manager**" dialog will appear.
1. Wait for the updates to finish, as shown by the messages printed at the bottom of the "**Boards Manager**" dialog.
1. Scroll down through the list of boards platforms until you see the "**esp32 by Espressif Systems**" entry.
1. Click the <kbd>**Update**</kbd> button at the bottom of the entry.
1. Wait for the update to finish.
1. Click the <kbd>**Close**</kbd> button in the "**Boards Manager**" dialog.

If you have any questions or need additional assistance, please post on Arduino Forum. We'll be happy to help you out over there:

https://forum.arduino.cc/
