### ISSUE TITLE
OTA fails through TP-Link TL-WR802N(US) Ver: 4.8

### ISSUE THREAD

**Issue by OldSurferDude** [arduino/Arduino#11905]
When I use my Asus Router or softAP running on an ESP-12F , the OTA is successful.

- The TP-Link is configured as follows
1.  reset the TP-Link to factory defaults
2. connect to the WiFi TP-Link_xxxx using the default passphrase for that particular TP-Link 
3. I use my browser to connect to the TP-Link (my local router has the same IP address so I disconnect the cable)
4. The default first page is the "Quick Setup" [Next]
5. I do not change the password [Next]
6. I click the radio button O Access Point [Next]
7. I do not change the Network Settings [Next]
8. Lan Type [Static IP], IP Address [192.168.5.1] and leave DHCP server enabled [Next]
9. I wait until the update is complete (reconnecting my network cable) and reconnect to the Access Point as in 2.  My computer now has the IP address of 192.168.5.100

- My device is an ESP-12F (ESP8266). 
- For initial download I use a [test frame](https://www.aliexpress.us/item/3256802482050604.html).  (Depending on which USB I plug it into) it appears as COM8
- In the Arduino IDE I set the board to Generic ESP Module 
- Also, I set the port to COM8
- I load the Examples-->ArduinoOTA-->BasicOTA
- I modify the Basic OTA sketch to have the same SSID and Passphrase
- compile and upload
- once uploaded, I open a PuTTY terminal COM8 115200 BAUD.  This restarts the program that is now on the ESP-12F and indicates that device has an IP address of 192.168.5.101
- In the IDE, I now set the port to 192.168.5.101 for OTA upload
- compile and upload, a password id required [admin]<enter>
- The IDE reports the error:   
```
11:12:32 [ERROR]: No response from device
Failed uploading: uploading error: exit status 1
```
- The output on the PuTTY monitor port is:
```
▒Booting
Ready
IP address: 192.168.5.101
Start updating sketch
Error[2]: Connect Failed
Error[4]: End Failed
```

**Comment by per1234** [comment]
Hi @OldSurferDude. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
