### ISSUE TITLE
[QUESTION]. Is the arduino nano every compatible with liquidcrystal I2C

### ISSUE THREAD

**Issue by IoakeimSogiakas** [arduino/Arduino#11904]
Hi I know that this has been somewhat addressed before but I just need to be sure before I make a purchase. I am making a project game and I have made the code for it. However I found out that the sram on the arduino nano is not enough so I was thinking of getting am arduino man every. However after compiling i get a warning that the library is meant for avr boards and it might not work with other things. Is this true will it not work or should I ignore it?

**Comment by per1234** [comment]
Hi @IoakeimSogiakas. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. It is not a place to ask for support with your project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
