### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by dw1rm** [arduino/Arduino#11916]
A Place to share experiences

**Comment by dw1rm** [comment]
![97a1bb28_DigisparkSchematic.pdf](https://github.com/arduino/Arduino/files/12928278/97a1bb28_DigisparkSchematic.pdf)

**Comment by dw1rm** [comment]
![Screenshot_2023-10-17-18-53-06-512-edit_com.google.android.apps.docs.jpg](https://github.com/arduino/Arduino/assets/104103123/da9c6d8a-1846-4fe6-a33d-cdb425736de5)

**Comment by dw1rm** [comment]
![Screenshot_2023-10-17-18-55-29-511-edit_com.google.android.apps.docs.jpg](https://github.com/arduino/Arduino/assets/104103123/bef77787-b248-4bb9-8fb6-2bc6ddce8672)

The Digispark Attiny 85 design (schematic, layout, concept) is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License: http://creativecommons.org/licenses/by-sa/3.0/
The Digispark and Digistump names and logos (or derivatives thereof) may not be used as part of the name of a product, company, or domain name without express written permission.
Digispark name. logo and Digistump name, logo Copyright 2013 Digistump LLC All Rights Reserved
For full details and license information please see http://digistump.com/wiki/digispark/policy

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This is not a "place to share experiences".

If you would like to discuss Arduino-related subjects, please use the Arduino Forum:

https://forum.arduino.cc/
