### ISSUE TITLE
I have a problem saving the audio

### ISSUE THREAD

**Issue by zaid-alrowaili** [arduino/Arduino#11912]
Can you help me. 
![image](https://github.com/arduino/Arduino/assets/145748103/8b68ae84-6fe6-4cb3-84f6-d532ef644743)

All voice records in recognizer: 0
Valid voice records in recognizer: 0
VR is not in group mode.
VR Index Record Comment
0 Unloaded NONE
1 Unloaded NONE
2 Unloaded NONE
3 Unloaded NONE
4 Unloaded NONE
5 Unloaded NONE
6 Unloaded NONE

**Comment by per1234** [comment]
Hi @zaid-alrowaili. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. It is **NOT** a place to ask for help with your project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
