### ISSUE TITLE
Absolute path `/home/megabug/Code/arduino-1.8.19.tar.xz` in release SHA512 file

### ISSUE THREAD

**Issue by devenblake** [arduino/Arduino#11911]
The SHA612 file for the latest release includes the absolute file location for the tarball rather than a relative location. This doesn't seem critical or anything but the person assembling the tarball may want to avoid leaking their directory layout just out of principle, or it might be keen to have a build script generate the file rather than doing so manually.

**Comment by cmaglie** [comment]
Could you tell us the URL of the file?
I checked the one here https://downloads.arduino.cc/arduino-1.8.19.sha512sum.txt and it looks fine.

**Comment by devenblake** [comment]
Just wanted to give a heads up.
