### ISSUE TITLE
Add INT2 case to detachInterrupt()

### ISSUE THREAD

**Issue by leres** [arduino/Arduino#1191]
detachInterrupt() is missing the INT2 case, needed for chips such as the atmega644p.

Here's a patch that adds the necessary code when INT2 is defined:

> [extrapatch-hardware-arduino-cores-arduino-WInterrupts.c](https://gist.github.com/4400788)

**Comment by vicatcu** [comment]
I just submitted pull request #3221 to address this

**Comment by cmaglie** [comment]
Fixed with #3221, thanks!
