### ISSUE TITLE
pls add support for opencm9.04

### ISSUE THREAD

**Issue by NICOLASPEREZHOLCIM** [arduino/Arduino#11920]
Arduino IDE 2.2.1, I tried to paste this link:
https://raw.githubusercontent.com/ROBOTISGIT/OpenCM9.04/master/arduino/opencm_release/package_opencm9.04_index.json
but it didn't found the board. it only works for the openCR

**Comment by per1234** [comment]
Hi @NICOLASPEREZHOLCIM. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
