### ISSUE TITLE
ESP8266 sketch compiled binary is faulty on a specific windows computer

### ISSUE THREAD

**Issue by Petri2** [arduino/Arduino#11923]
I have this strange issue. I have 2 win 10 machines. Both 64 bit. Another core i5 and another core i7.
Installed just recently arduino ide on the i7 machine. 
The i5 I have been using for years.

The i7 seems to work fine but getting faulty binaries as result of compilation.
My sketch compiles and uploads fine with the i5 machine. 

If I replace the binary compiled in the i7 machine with the binary compiled in i5 the code uploads fine using the i7 .
Done it actually running the command that is outputted by compiler verbose on command line.
So it is clear that the only difference is the binary itself and the upload is working fine on both machines.

I attached the binaries here for inspection. They are quite similar if viewed using editor. The other that does not work is a bit longer. 
After removing the installation from i7 several times and also deleting left over folders and reinstalling no difference.
 The issue is somehow partially related to the size or contents of the sketch because when I tried a very simple sketch it worked.
There are no error in compilation. Only couple warnings about using right formatting in sprintf (I even solved those but still the issue remains).

[compilerissue.zip](https://github.com/arduino/Arduino/files/13254960/compilerissue.zip)

**Comment by per1234** [comment]
Hi @Petri2. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
