### ISSUE TITLE
 CLang -mno-skip-bug

### ISSUE THREAD

**Issue by risknu** [arduino/Arduino#11933]
```bash
clang: error: unknown argument: '-mno-skip-bug'

exit status 1

Compilation error: exit status 1
```
MacOS 12.6.1 Monterey
Error on building project

**Comment by per1234** [comment]
Hi @per1234. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the Arduino IDE 1.x codebase. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
