### ISSUE TITLE
Autosuggestion

### ISSUE THREAD

**Issue by Master811129** [arduino/Arduino#11944]
I know that this feature is available in modern Arduino IDE but I still prefer the Java version. the only thing that this IDE is missing for me is a proper autosuggestion feature.
Please implement it.

Regards.

**Comment by per1234** [comment]
Hi @Master811129. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino/Arduino/issues/849.

It is best to have only a single issue per subjec, so I'll go ahead and close this in favor of the other.
