### ISSUE TITLE
Nucleo64 G491RE board not showing up in editor

### ISSUE THREAD

**Issue by mercurial-moon** [arduino/Arduino#11948]
Hi,
My board selection list shows up like this
![image](https://github.com/arduino/Arduino/assets/117296073/e5ca7d71-0832-47bb-92e8-52429f1c4770)

There is no entry for G491RE board.
Tried with Generic G4 series board but couldn't get "blink" program to work the led remains off.
Editor version  1.8.15
STM32 boards version  2.7.1

**Comment by per1234** [comment]
Hi @mercurial-moon. The developers of the ["**STM32 MCU based boards**" platform](https://github.com/stm32duino/Arduino_Core_STM32) (AKA "STM32duino") simply haven't created an entry for that board. This is not the result of any defect in Arduino IDE so I will close this as off topic.

The "**STM32 MCU based boards**" platform developers are already tracking the task of adding the option here:

https://github.com/stm32duino/Arduino_Core_STM32/issues/722

You can subscribe to that issue to get notifications about any progress towards completing the task.

> Tried with Generic G4 series board but couldn't get "blink" program to work the led remains off.

You can post over on the stm32duino forum to get help with using that board definition with your Nucleo:

https://www.stm32duino.com/
