### ISSUE TITLE
SoftwareSerial Bug

### ISSUE THREAD

**Issue by 4dsystems** [arduino/Arduino#1195]
Hello,

Issue raised on the forum: http://arduino.cc/forum/index.php/topic,140227.0.html

We are having problems with the SoftwareSerial library found in the Arduino 1.02 Release.

When the SoftwareSerial is initialised, it sets the tx port to output and then sets it to HIGH. This causes a momentary low spike that is being interpreted as a start bit on some controllers.

The code currently is:-
void SoftwareSerial::setTX(uint8_t tx)
{
  pinMode(tx, OUTPUT);
  digitalWrite(tx, HIGH);
  _transmitBitMask = digitalPinToBitMask(tx);
  uint8_t port = digitalPinToPort(tx);
  _transmitPortRegister = portOutputRegister(port);
}

The 'fixed' code is:-
void SoftwareSerial::setTX(uint8_t tx)
{
  digitalWrite(tx, HIGH);
  pinMode(tx, OUTPUT);
  _transmitBitMask = digitalPinToBitMask(tx);
  uint8_t port = digitalPinToPort(tx);
  _transmitPortRegister = portOutputRegister(port);
}

This solves the issue.

Please advise

Regards
4D Systems

**Comment by hbisby** [comment]
closed by 90ca3934f25c992ebab0dfffc5715e949ee4081e 

@4dsystems Please use the latest version of the IDE.

**Comment by 4dsystems** [comment]
Thank you. What release was this fixed on, just out of interest. Was this fixed a while ago and just updated now, or was it just updated recently? 1.02 was the latest release at the time of reporting the issue... Thanks.

**Comment by matthijskooijman** [comment]
@4dsystems, if you click the commit link, you can see that this commit was first present in the 1.6.1 release (just below the commit message).
