### ISSUE TITLE
An error occurs when an arduino uses the IRremote library

### ISSUE THREAD

**Issue by Field-of-Dream** [arduino/Arduino#11952]
When using the IRremote library, the error message "C:UsersAdministratorAppDataLocalTempcckaRwmf.ltrans0.ltrans.o: In function 'loop':
C:UsersAdministratorDownloadsdong_li_xiao_chae/dong_li_xiao_chae.ino:38: undefined reference to `IRrecv::decode(decode_results*)'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1”

**Comment by Field-of-Dream** [comment]
An issue was found when the arduino imported the library file was .hpp, but the IRremote library required the .h file. Hopefully this can be fixed in the future

**Comment by per1234** [comment]
Hi @Field-of-Dream. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
