### ISSUE TITLE
issue while uploading in Arduino

### ISSUE THREAD

**Issue by MBH26** [arduino/Arduino#11998]
![Image](https://github.com/user-attachments/assets/0989ea68-a328-4fc7-a599-fe4930179363)

**Comment by per1234** [comment]
Hi @MBH26. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/avrdude-stk500-bootloader-issues/81
