### ISSUE TITLE
New idea, trying to figure out if it's possible..

### ISSUE THREAD

**Issue by Amitttttttttttt** [arduino/Arduino#12001]
I'm wondering if it's possible to somehow use sonar sensors or some sensors with arduino or other microchip in order to transfer my non-self flying Dji mavic mini 2 se drone into a self flying machine and use code and commends in order to make the app think it's a new drone with sensors and then use them to fly by its own or something like that... I have no clue or knowledge so I'm asking here the public and searching for answers from the people who know more then I do...
Thanks🙏🏽

**Comment by PaulStoffregen** [comment]
Might be possible, but what's not possible is asking for project guidance here.  That sort of questions is for the Arduino forum.  This place is only for reporting software defects and development.
