### ISSUE TITLE
How can we connect to vc-02?

### ISSUE THREAD

**Issue by navidhariri** [arduino/Arduino#12009]
How can we connect to vc-02?

**Comment by per1234** [comment]
Hi @navidhariri. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This is _**NOT**_ an appropriate place to request assistance with your project. The appropriate place to request assistance is on Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
