### ISSUE TITLE
unable to run program in arduino uno  on ubuntu , tried running sudo usermod -a -G dialout asus but it doesnt workout

### ISSUE THREAD

**Issue by tempraturepressure** [arduino/Arduino#12013]
unable to run program in arduino on ubuntu , tried running sudo usermod -a -G dialout asus but it doesnt workout

**Comment by per1234** [comment]
Hi @tempraturepressure. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
