### ISSUE TITLE
avrdude: ser_open(): can't open device "\\.\COM4": Access is denied.

### ISSUE THREAD

**Issue by amnaanonymous** [arduino/Arduino#12011]
avrdude: ser_open(): can't open device "\\.\COM4": Access is denied.

**Comment by per1234** [comment]
Hi @amnaanonymous. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/avrdude-stk500-bootloader-issues/81
