### ISSUE TITLE
Check out "Software update: update apps"

### ISSUE THREAD

**Issue by studding** [arduino/Arduino#12024]
https://play.google.com/store/apps/details?id=com.updateapps.updatesoftware.upgradephone.uptodate

**Comment by per1234** [comment]
@studding please stop submitting these pointless issues to our issue tracker.

If you want to mess around with GitHub, you are welcome to create a repository under your own account and do as you like, but it is not appropriate to do this in our repository.

Your behavior is harming a free open source software project.
