### ISSUE TITLE
IDE buries warnings where users can easily miss them

### ISSUE THREAD

**Issue by dave2** [arduino/Arduino#1215]
The IDE buries warnings even in verbose mode in a way that makes it non-obvious to new users they have issues they may want to consider.

For example, the code
```
int *ref(int len) { 
  int buf[len]; 
  return buf; 
}
```
will generate a g++ warning (since it is returning a reference to a stack variable which goes out of scope, something not obvious as wrong to a new user), but without verbose enabled and without trawling back through the output, there is no indication to the user anything is wrong. The compilation finishes looking like it's perfectly fine.

If g++ or other compile components generate warnings, these should be presented to the user explicitly, even with verbose off. For example, it should say "Done Compiling (with warnings)", and output just the warnings themselves in the output window at the end.

**Comment by ffissore** [comment]
Fixed with b42c6667e1c6ca748b3a24bdd87c5716332a9c39
