### ISSUE TITLE
IDE : Dead keys from keyboard does not get letter

### ISSUE THREAD

**Issue by Rpnpif** [arduino/Arduino#1217]
Typing a dead key as trema or circumflex key on an AZERTY keyboard following with a letter does nothing in Arduino IDE.

Cut and paste of these letters from another window works fine.

This is used in comments.

Example : type ^ then e does not get ê. " then o does not get ö but nothing.

Releases of the IDE : 1.0.1 from Debian Linux, 1.0.3 from arduino.cc. LANG=fr_FR@UTF8.
None of the others softwares in this machine have this issue.

Processing 1.5.1 works fine without this issue.

**Comment by ffissore** [comment]
Is this still true with current hourly build? We changed underlying editor, so things might get better

**Comment by ffissore** [comment]
Hourly builds are available at http://www.arduino.cc/en/Main/Software#hourly

**Comment by Rpnpif** [comment]
Yes, this bug is fixed in nightly build. Thanks.
But a minor other issue with dead keys appears or is still here.

When I typed the Ê, the top of circumflex was hidden and the letter could be mistaken for Ë. Then , if I selected this letter Ê, all was displayed fine.

**Comment by ffissore** [comment]
Does using a bigger font mitigate the issue? Can you attach a screenshot? (I can't reproduce the problem)

**Comment by ffissore** [comment]
Here is what I see and it looks as expected
![schermata del 2015-06-17 11 05 03](https://cloud.githubusercontent.com/assets/510465/8203258/c53755fe-14e0-11e5-9183-d3ffc047d4b5.png)
