### ISSUE TITLE
Serial Monitor doesn't recognize Carriage Return

### ISSUE THREAD

**Issue by gse76** [arduino/Arduino#1223]
With Arduino 1.0.3 the instruction "Serial.print('\r')" isn't displayed in the Serial Monitor. This instruction should return the carriage at the beginning of the current line in the terminal. 
Using another terminal instead, such as Putty, this instruction works as expected.

I use it in order to display a single line updating (i.e.: to show a continuos changing sensor state)

**Comment by ffissore** [comment]
@gse76, as @cmaglie said, this is a know limitation of Serial Monitor, unlikely to be fixed. Serial Monitor is not a terminal and it's unable to properly handle a handful of control codes. Please use tools like putty or cutecom instead
@AlanTJohnstone please open a specific issue with your request, if your enquiry is still valid

**Comment by akilawickey** [comment]
It's also cannot recognized on Linux screen serial monitor

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/346
