### ISSUE TITLE
IDE Does not correctly accept Dvorak keyboard commands

### ISSUE THREAD

**Issue by Pykk** [arduino/Arduino#1226]
I use the "Dvorak – Qwerty ⌘" keyboard layout and the commands do not work correctly in the Arduino IDE. I realize I might be the only person using Arduino that uses this layout, but it's technically still a bug which just cost me weeks of work so I figured it would be worth submitting on the off chance it might save someone else's time and frustration. It's also possible that other keyboard layouts have a similar problems.

(I had been pressing Command + S from muscle memory but it turns out that this was not saving.)

**Comment by ffissore** [comment]
Is this still true with current [hourly build](http://www.arduino.cc/en/Main/Software#hourly)? We changed underlying editor, so things might get better
