### ISSUE TITLE
IDE Download getting large; need to develop an incremental download plan

### ISSUE THREAD

**Issue by tigoe** [arduino/Arduino#1227]
The Arduino IDE download is getting large as we add more toolchains, libraries and examples. While these components are helpful, it makes the initial download huge. We should develop a scheme to reduce this, perhaps by using incremental downloads. 

Starting with an initial download that has only the AVR toolchain, then allowing you to incrementally add the Due toolchain dynamically would help. 

A library manager (already in discussion on the dev list) will help reduce the size of the initial download, and allow users to pick and choose which libraries they include.  Similarly, perhaps an example manager would help as well.
 
What other elements could be made modules and implemented as an incremental download?

**Comment by ffissore** [comment]
Fixed since 1.6.2
