### ISSUE TITLE
'lineheight' parameter in theme.txt not responding in IDE

### ISSUE THREAD

**Issue by jeffThompson** [arduino/Arduino#1228]
A nit-picky suggestion/tiny bug:
When modifying the `theme` folder's `theme.txt` file, the `linehighlight` parameter does not do anything!  I have it set to `true` and the color changed.

Perhaps I'm misunderstanding what this parameter does - I assume it highlights the current line where the cursor is?

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
