### ISSUE TITLE
Arduino Micro USB upload issue

### ISSUE THREAD

**Issue by harshasunder** [arduino/Arduino#1231]
Im finding that sometimes the Arduino Micro doesnt upload and sometimes it does. I traced both cases with USBlyzer and have attached the files below... can anyone look at the files and explain why this is happening? 
The files are csv files so just rename them from jpg to csv to see them

![arduino blink upload failure](https://f.cloud.github.com/assets/3286080/73618/e9dc498c-6051-11e2-85d7-561c7b430f9d.jpg)
![arduino blink upload success](https://f.cloud.github.com/assets/3286080/73620/ea8af586-6051-11e2-8487-20a587ce5390.jpg)

**Comment by agdl** [comment]
Reopen it if needed
