### ISSUE TITLE
Show file name in window title

### ISSUE THREAD

**Issue by caschoff** [arduino/Arduino#1239]
[Enhancement/feature request]

If one has a lot of files in a project there are a lot of tabs. If you have more tabs than space on the screen, you can navigate with the arrow looking down, selecting the file. With more tabs, you have to use "next tab", "previous tab". But then, sometimes you get confused about the tab, respectively file, that you see. 

It would be a great help if one could see the file name in the title of the Arduino window. It is now showing [Project name] | Arduino 1.0.3. Better would be something like [Project name] | [File name] | Arduino 1.0.3

**Comment by jasoncoon** [comment]
I agree, this would be really nice.

**Comment by ffissore** [comment]
Fixed in 2339049c0fd0cd7d215adc659f044a999a9dfeca. Fix is available in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
