### ISSUE TITLE
[Due] (I2C) Wire.endTransmission always returns non-zero.

### ISSUE THREAD

**Issue by chriskner** [arduino/Arduino#1251]
1.5.1r2

It looks like endTransmission returns the number of bytes sent from the transmit buffer, not an indication of success, as http://arduino.cc/en/Reference/WireEndTransmission suggests.

from \arduino-1.5.1r2\hardware\arduino\sam\system\libsam\source\twi.c :
```
uint8_t TwoWire::endTransmission(uint8_t sendStop) {
	...
	while (sent < txBufferLength) {
		...
	}
	...
	return sent;
}
```

**Comment by sandeepmistry** [comment]
The return code has been addressed by @bluesign2k's commit https://github.com/arduino/Arduino/commit/e079baa18daaa21ded7c3ea49fc82bd6f5a0fc5b and is already in master.
