### ISSUE TITLE
Failed uploads due to external tool failure (e.g., bossac, avrdude) do not get trapped as errors

### ISSUE THREAD

**Issue by MartyMacGyver** [arduino/Arduino#1273]
[Seen in 1.5.2, but I believe this has always been an issue.]

This issue occurs in BasicUploader's uploadUsingPreferences() method, but really seems to stem from Uploader's executeUploadCommand() method.

If a call is made to an external programmer in Windows, and that programmer fails, the return code is either not getting correctly conditioned when read or it's not being set in the first place. However, even if that's the case common errors should be able to be trapped via their output text.

The two examples I've encountered tonight (as I swap between Mega and Due programming) are the following:

*avrdude: stk500_getsync(): not in sync: resp=0x98
*No device found on COM11

If I learn more about the issue or possible solutions I'll follow up here.

**Comment by facchinm** [comment]
Fixed long time ago, tools must be compliant with return conventions (return `0` if upload succeeded, `-ERRNO` if failed)
