### ISSUE TITLE
bug on CS line using SPI library

### ISSUE THREAD

**Issue by schwingkopf** [arduino/Arduino#1280]
when using the SPI library with the predefined SPI-CS0 and SPI-CS1 pins (digital pins 10 and 4), the voltage during SPI communication on these lines doesn't drop to 0V (only to 1.6V), when defining the digital pins for SPI-CS0 and SPI-CS1 prior as pinMode OUTPUT.
with the SPI-CS2 on digital pin 52 it worked fine for me.

for details please see http://arduino.cc/forum/index.php/topic,148463.0.html

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#18
