### ISSUE TITLE
Multi-file sketches always marked as "Not saved" on OSX

### ISSUE THREAD

**Issue by realrolfje** [arduino/Arduino#1284]
In a Sketch with multiple files, when changing to a tab, it is always marked as "Changed" (it shows the paragraph sign next to the filename). (Detected on OSX 10.8.2, Arduino IDE 1.0.3)

Also, the Arduino IDE is missing a "Save All" feature, which really would come in handy in a multiple file project.

**Comment by ffissore** [comment]
Fixed with #2666
