### ISSUE TITLE
Failed to load arduino on Windows 7

### ISSUE THREAD

**Issue by humroben** [arduino/Arduino#1294]
I've tried both with the 1.0.3 and 1.5.2 arduino software distros, and I cannot get the program to load. The loading view with the arduino symbol and the hearts shows up, but once it disappears, the program terminates, without any inclination that it even tried to start.

Am I doing something wrong, am I forgetting something, or is there something wrong with my OS, I could really do with some feedback.

Using Windows 7, SP1.

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen it if needed.
