### ISSUE TITLE
Add the possibility to use a non-composite CDC-ACM serial port on native USB ports (Due or Leonardo)

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1300]
Older MacOSX (<=10.6) and Windows (<=XP SP2) doesn't handle correctly USB composite devices. 

A menu to choose the USB configuration may give a simple workardound for this issue.

Some more info:
http://arduino.cc/forum/index.php/topic,137032.msg1031089.html#msg1031089

**Comment by facchinm** [comment]
As a side effect, #3304 solves this too :sunglasses:

**Comment by facchinm** [comment]
Solved by PluggableUSB
