### ISSUE TITLE
W7 64 IDE not loading - just splash screen

### ISSUE THREAD

**Issue by JonnySchmidt** [arduino/Arduino#1302]
I have tried several versions of the Arduino software and with all of them are only the splash screen is loading up, then nothing. I have updated Java, checked the exe and made sure it is allowed to open without sandbox mode, and looked at other issues people have been having similar to mine but they seem to also be getting some kind of error box... I not getting that. I am only getting the splash screen for a few seconds.. can some help me please. I have a SainSmart Mega2560 Arduino board.

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen it if needed.

**Comment by hairypaulsack** [comment]
Anybody suggest a sudo chop?? AKA: Guys have you tried running as administrator? That fixed it instantly for me lol.. I feel like a noobtastic idiot for trying so many things and forgetting the easiest number 1 go to fix; Run as administrator. Now i believe arduino normally doesn't need it, but give it a try. Hopefully we can throw up a solved here
