### ISSUE TITLE
wrong placement of arduino.h

### ISSUE THREAD

**Issue by holgerlembke** [arduino/Arduino#1310]
My code begins with something like that
```
#if defined(__AVR_ATtiny85__) 
  const int Pin0 = 0;
#else
  const int Pin0 = 4;
#endif 

byte something;
```
Compiling it for any none __AVR_ATtiny85__ leads to an error due to wrong arduino.h placement into the if-else part.

Adding a dummy declaration at the start (in front of #if) omits the error... but a real fix would be better.

**Comment by ffissore** [comment]
Please give a try to the IDEs linked at the bottom of this email on the dev list
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/4X2T3rCxXWM/YNJl6PZuDucJ
We're testing a new preprocessor and it compiles your sketch just fine.

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by holgerlembke** [comment]
I'm too late for the test? The refered IDE links don't work anymore.

**Comment by ffissore** [comment]
Not too late: take a look at the bottom of this page #2729
