### ISSUE TITLE
source code and patches for avr-gcc

### ISSUE THREAD

**Issue by alejandro-anv** [arduino/Arduino#1316]
I am trying to build binaries for Mageia Linux. I can compile binaries of arduino without problems but it needs avr-gcc 4.3.2

I downloaded the official sources of avr-gcc 4.3.2 but it does not recognize the atmega32 of Arduino Leonardo. Then I think the binaries distributed with arduino must be patched. 

Where can I find this patches?

**Comment by ffissore** [comment]
Fixed with the introduction of https://github.com/arduino/toolchain-avr
