### ISSUE TITLE
SeekableStream

### ISSUE THREAD

**Issue by stg** [arduino/Arduino#1330]
I would like to see a SeekableStream class going between the File class (SD library) and the Stream class (or by adding the seek, position, size functions to the Stream object directly).

This would allow access to arbitrary (SD or other media) seekable streams without the user including the (large) SD library for projects that do not have an SD card reader, while still maintaining full compatibility with the SD card library.

For example, the HypotheticMusicPlayer class could play music from the SD card in a larger project, or from flash-rom in a smaller project via a class that subclasses SeekableStream and accesses PROGMEM data - without needing to include the SD library, which may not even fit on a smaller device.

This would also make it easier to provide standardised file access to other media, where including the SD card library makes no sense.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#10
