### ISSUE TITLE
#line directive interferes with disassembly.

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#1337]
Sometime recently (https://github.com/arduino/Arduino/commit/77ed2f4d62d51ca9d79f3353936e9d359d886ccb ) "#line" directives were added to the pre-processed code to make error messages better reflect the actual source code, instead of the pre-processed source code.
However, since the "#line" directives refer to the original file ("#line 1 Blink.ino"), which is not actually present in the build directory, dissassembly using "avr-objdump -S" cannot find the source to do a proper mixed source/assembly listing.
There are a couple of possible solutions:
1) copy the .ino files into the build directory.
2) use full paths to the original files in the "#line" directives.
3) insist that the user use -I in the avr-objdump (change or add documentation.)

**Comment by ffissore** [comment]
@WestfW as #3303 and #3435 are merged, now object files from core and libraries are split into separate subfolders of the build folder. Plus, sketch source code is in its own folder, together with some of its source files (everything but .ino). Can you update your issue with the latest hourly build? I would like to have this fixed for 1.6.6

**Comment by ffissore** [comment]
@WestfW with latest hourly we added the full path to the original source file in #line directives. Can you give it a spin a see if this issue is solved?

**Comment by ffissore** [comment]
Also see #3746

**Comment by WestfW** [comment]
I can confirm that 1.6.6 seems to be working correctly.
