### ISSUE TITLE
Add FTDI BitBang programmer [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#134]
This is [Issue 134](http://code.google.com/p/arduino/issues/detail?id=134) moved from a Google Code project.
Added by 2009-10-24T07:57:33.000Z by [Buda2...@gmail.com](http://code.google.com/u/108101329029609143890/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

I'd like to see BitBang added to the choices of programmers in the GUI

because it has the capabilitys of being done with out having to buy a 
seperate programmer (just 2 plugs and same wire)

Would this cause any incompatibilities with previous versions? 
no

**Comment by ffissore** [comment]
Assigning back to @cmaglie as configuring a programmer is beyond my expertise

**Comment by sandeepmistry** [comment]
I'm closing this and marking as won't fix for now as there is not much further interest in the feature..
