### ISSUE TITLE
Serial Monitor keeps the Serial Port blocked if usb cable is unplugged while it is open

### ISSUE THREAD

**Issue by Profman** [arduino/Arduino#1340]
Hi!

I am using:
Windows 7
IDE 1.0.4
Arduino Uno R3
External 12V power supply
2 COM-ports are assigned, COM13 for Bluetoth and at driver installation COM14 for Arduino 

Problem:
I am monitoring with the serial monitor.  When I remove the USB cabel, the serial monitor stops and will not continue when I reconnect the cable again.  The COM14 port in IDE is not there anymore.   It is still there in the Windows device manager.  I have to manipulate with resetting the board, dis/reconnecting the USB-cabel,  restarting the IDE. Sooner or later the COM14 is back again, but I don´t know how.  I looks like every time I restat the serial monitor the board is reset.

For debugging purposes I want to have the possibility to connect to the USB and monitor the program execution without interfering with or resetting the  execution.  If this can´t be done with the serial monitor in IDE, tell me how to do it.  Can I use something else, like Putty for instance.

Regards
Profman

**Comment by ffissore** [comment]
When unplugging a board while having serial monitor open, serial device will still be in use and OS will not delete it. Thus, plugging in the board once again, a new serial device will be created.
You have three options: 
1) close serial monitor before unplugging the device
2) close serial monitor after having unplugged the device, select its new port and reopen serial monitor
3) use putty
