### ISSUE TITLE
arduino in MAC

### ISSUE THREAD

**Issue by marcorigamonti** [arduino/Arduino#1355]
I tried to download different versions of arduino on mac platform IOS 10.8.3
The first time it opened but today I can't open it anymore or better When I click on the icon it opens but it doesn't appear anything on the screen, only the name arduino on the top left corner of the screen. If I click there I can open the preference panel where you can set the language and different other things but nothing more.
How can I solve it?
Thanks!
Marco Rigamonti

**Comment by ffissore** [comment]
User solved the issue http://forum.arduino.cc/index.php?topic=159506.0
