### ISSUE TITLE
Crash Ethernet with W5100

### ISSUE THREAD

**Issue by JanosAudron** [arduino/Arduino#1360]
Hardware:
Arduino UNO + Ethernet Shield

Software:
IDE 1.0.4 and 1.5.2

After some test I think the problem of the crash of W5100 chip that make it unresponsive is when you use an SD card, too.
If you don't force pin 4 to HIGH, disabling the SD card, if these's a card insered the W5100 may become unresponsive. Maybe the bug is in SD library and not in Ethrnet library.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#12
