### ISSUE TITLE
Windows *.ino file association

### ISSUE THREAD

**Issue by Yoshimasta** [arduino/Arduino#1379]
When updating to any version of the arduino IDE from v1.0, I am unable to get windows to open *.ino files with the new version. It always defaults to v1.0, even if i delete the v1.0 directory and try to "open with" v1.04 (or any other version), in which case it won't do anything at all. I can open the files by opening the v1.04 IDE and opening the file from there, but this is often a pain in the ***.  We have tried everything - my whole company has this issue. We are running Windows 7 64-bit.

Thanks in advance!

**Comment by ffissore** [comment]
With f6546aea4527bb0723fac6472c1e10328ebe9473 we turned off associating files when using the plain windows zip file. Only windows installer will set the registry keys for associating .ino files to installed IDE
