### ISSUE TITLE
Leonardo keyboard API only allows ASCII input

### ISSUE THREAD

**Issue by weizenspreu** [arduino/Arduino#1386]
The Arduino Leonardo keyboard API only allows ASCII input and then converts it to the actual key codes sent to the computer via USB. This is a huge problem because it fails for non-QWERTY systems (e.g. in Germany, France) and even for non-Windows systems (e.g. when it comes to special characters on a Mac).

Take this code as a small example. On a German computer this will actually output "qwerty".

    void setup() {
      Keyboard.begin();
    
      pinMode(2, INPUT);
      digitalWrite(2, HIGH);
    }
    
    void loop() {
      while (digitalRead(2) == HIGH) {
        delay(500);
      }
      delay(1000);
      
      Keyboard.print("qwertz");
    }

It would be great to have something like Keyboard.pressKeycode() and Keyboard.releaseKeycode() and actually do the conversions ourselves. That way we could ask the user what keyboard layout he/she has and do everything appropriately.

**Comment by sandeepmistry** [comment]
Closing, looking at [Keyboard.h](https://github.com/arduino-libraries/Keyboard/blob/master/src/Keyboard.h) the following API's are present:

```c
  size_t press(uint8_t k);
  size_t release(uint8_t k);
  void releaseAll(void);
```

**Comment by trahloff** [comment]
How would you modify these APIs in Keyboard.h to achieve a conversion?

**Comment by sandeepmistry** [comment]
Re-opening this, on closer inspection raw key codes are still not supported currently.

**Comment by nospam2000** [comment]
look at [pull request 1391 ](https://github.com/arduino/Arduino/pull/1391) it contains the code for the raw key codes

**Comment by NicoHood** [comment]
We decided that the arduino IDE keeps the library simple while my HID Project will add all those new features. That was made with 1.6.6 or 1.6.7 (?) when the new usb core came out.
https://github.com/NicoHood/HID

I think you can close this issue as "wont fix"

**Comment by PaulStoffregen** [comment]
@NicoHood - I see you've used my international keyboard layouts code in your project.  Please be aware the license for that code includes a requirement to have Teensy installed in the Tools > Boards menu.  It may be used on non-Teensy boards, but only when full Teensy support is available to the user in the menu.

**Comment by NicoHood** [comment]
which international keyboard layouts code? `TeensyKeyboardAPI.h` etc? That is not working. And well if you say we cannot use it like that i will remove the code in the next release :/

**Comment by limpkin** [comment]
oh that brings back lots of memories for the mooltipass project... we had to make a python script to generate Look Up  Tables between ascii codes and keyboard layouts... good times.

**Comment by weizenspreu** [comment]
IMHO it's still badly solved in the Core.

**Comment by NicoHood** [comment]
@weizenspreu feel free to buils something on top of HID-Project to use different layouts. It should be possible.

**Comment by weizenspreu** [comment]
The Arduino/Genuino Leonardo is EOL already, so I won't bother any longer.

**Comment by NicoHood** [comment]
Who said that? Those avrs are still widely used. Especially those with a 328 and a 32u4.
