### ISSUE TITLE
Leonardo doesn't appearing as CDC-ACM device

### ISSUE THREAD

**Issue by jotabr** [arduino/Arduino#1389]
After plugging Leonardo to USB port, /dev/ttyACM0 is created normally by bootloader:

```
$ ls /dev/ttyACM*
/dev/ttyACM0

$ lsusb | grep Ard
Bus 003 Device 113: ID 2341:0036 Arduino SA
```

After bootloader has finished execution, there is no CDC ACM device available and it is not possible to upload any sketch:

```
$ ls /dev/ttyACM*
ls: cannot access /dev/ttyACM*: No such file or directory

$ lsusb | grep Ard
Bus 003 Device 110: ID 2341:8036 Arduino SA Leonardo (CDC ACM, HID)
```

If I reset Leonardo I have ACM back and some seconds for uploading a sketch.

Maybe it is related to this issue? -> https://groups.google.com/forum/?fromgroups=#!topic/lufa-support/kKuFY8HGgWc

I'm currently running RHEL 6.4 - Linux 2.6.32-358.2.1.el6.x86_64

Regards

Jota

**Comment by facchinm** [comment]
Solved by newer kernel versions
