### ISSUE TITLE
Half-steps in stepper library for 4-wire motors [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#139]
This is [Issue 139](http://code.google.com/p/arduino/issues/detail?id=139) moved from a Google Code project.
Added by 2009-11-05T07:28:01.000Z by [john.zan...@gmail.com](http://code.google.com/u/113661901661592867205/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

Using a half-step-library would double the precision of the stepper. 

Attached you'll find my proposal for the changed Stepper library. I kept 
the changes to a minimum.
It contains a new (added) constructor, a private boolean which indicates 
whether or not to use the half-step system. The Stepper::step function was 
changed to allow 2, 4, or 8 steps and the Stepper::stepMotor was changed 
to send the 8 different signals to the 4 wires.

Users who created sketches using the previous lib can change to this new 
library without compatibility problems.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Stepper#2
