### ISSUE TITLE
IDE prints blank pages when printer asleep

### ISSUE THREAD

**Issue by alextrey** [arduino/Arduino#1392]
If the printer goes asleep, when awoken by a print job from the IDE (both 1.03 & 1.04) the printer will print the correct number of blank pages.  To work around, wake the printer manually and then quit and re-enter the IDE.  Then IDE will print properly.

**Comment by skuffle** [comment]
I can confirm/reproduce this bug on a completely different platform. Windows 8 64bit, with a Samsung CLP-365W colour laser printer.

If the printer is sleeping, the first time you press print in the Arduino IDE, it prints exactly the right number of *blank* pages.

After this print, the printer is 'awake', and the printing from the Arduino IDE again prints the code as it should.

This is a truly bizarre bug - the printer works fine with every other application under Windows. There must be something in the Arduino IDE code that does things differently.

I'm using Arduino IDE v1.6.0.

**Comment by alextrey** [comment]
Thanks for the info.  I have not tried 1.6.0 yet.


cheers
- Alex

"Start every day off with a smile  and get it over with."  --  W.C. Fields

**Comment by DrewOJensen** [comment]
I also am having this issue on OS X 10.10.3 with Arduino IDE 1.6.3. It's not exactly the same but when I do a print preview it's the right number of pages, but they're completely blank. I was able to print last night, but not this morning. It doesn't appear to be a printer hardware issue but rather output issue with the IDE.

**Comment by ffissore** [comment]
Please give a try to latest hourly build. A recent fix may have improved the behaviour http://www.arduino.cc/en/Main/Software#hourly

**Comment by agdl** [comment]
I tired with the latest build and it prints without problems. @alextrey let us know!
