### ISSUE TITLE
IDE Freezes on Focus Change

### ISSUE THREAD

**Issue by LightningStalker** [arduino/Arduino#1393]
Hello.  I'm using Arduino IDE 1.0.4 with JRE7u21 on Knoppix 7.0.5.  The problem is that the cursor freezes and I can't type if I change focus to another window and change back.

**Comment by agdl** [comment]
@LightningStalker any news about this issue in the latest arduino IDE?

**Comment by LightningStalker** [comment]
Just compiled from the latest git using jdk1.8.0_45, and I am not encountering the issue
Also, over a gigabyte is a HELL of a lot to to download for a chip burner.

**Comment by ffissore** [comment]
Good to know, thanks for the feedback :)
