### ISSUE TITLE
Optimized digitalWrite() function. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#140]
This is [Issue 140](http://code.google.com/p/arduino/issues/detail?id=140) moved from a Google Code project.
Added by 2009-11-11T21:17:35.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core, Milestone-Post-1.0
### Original description

From Paul Stoffregen:
# define digitalPinToPort(P) \

```
  (((P) >= 0 && (P) <= 7) ? &PORTD : (((P) >= 8 && (P) <= 13) ? &PORTB : &PORTC))
```
# define digitalPinToBit(P) \

```
  (((P) >= 0 && (P) <= 7) ? (P) : (((P) >= 8 && (P) <= 13) ? (P) - 8 : (P) - 14))
```
# define digitalWrite(P, V) \

```
  ((__builtin_constant_p(P) && __builtin_constant_p(V)) \
  ? bitWrite(*((volatile unsigned char *) digitalPinToPort(P)), digitalPinToBit(P), (V)) \
  : _digitalWrite((P), (V)))
```

static inline void digitalWrite(uint8_t, uint8_t) **attribute**((always_inline, unused));
static inline void digitalWrite(uint8_t P, uint8_t V)
{
      (__builtin_constant_p(P) && __builtin_constant_p(V))
      ? bitWrite(*((volatile unsigned char *) digitalPinToPort(P)), digitalPinToBit(P), V)
      : _digitalWrite(P, V);
}

**Comment by Avamander** [comment]
What's the status of this?

**Comment by PaulStoffregen** [comment]
Last I heard, this code was published as a library named digitalWriteFast.

Many years ago, David Mellis decided keeping 2 copies of the pins-to-register mapping would be involve too much maintenance and add too much work for porting the core library to other chips, so these optimizations were abandoned.  Since then, many other architectures have been added, all using the same pinout table approach.

This old issue can probably be closed.

**Comment by facchinm** [comment]
Totally agree with Paul, closing this one as wontfix (since it can be implemented at library level if needed)

**Comment by matthijskooijman** [comment]
This is still on my list of things to look at at some point, hoping to be able to fix this without duplicate information (it would require changes in the variant files, though). But if I ever get around to that, I can always reopen or create a PR right away.

> (since it can be implemented at library level if needed)

This is not entirely true: any such library will have to duplicate the pin mapping for each supported board in the library itself, so it can never support all boards properly. A proper solution in the Arduino core and variant could be applicable to all boards (that have made the necessary changes to their variant file). All under the assumption that such an implementation is in fact possible, of course.

**Comment by PaulStoffregen** [comment]
Such a change at this point would be highly disruptive to the many boards which depend on the Arduino cores.

**Comment by matthijskooijman** [comment]
I think this might be possible in a backward-compatible manner (unmodified boards would not benefit from the optimization), but I'd have to dive in again to actually try it some time.
