### ISSUE TITLE
problem with the Arduino Due programming port (no device found on COM18)

### ISSUE THREAD

**Issue by michaelk99** [arduino/Arduino#1409]
Hi,
If i try to upload a sketch to my due via the programming port, the IDE writes "no device found on COM18". But it has already worked. I use windows and I have installed the driver for the board. However when I try to upload a sketch via the native usb port it works. I have also tried it with another pc but there was no difference. How can I fix this problem.

**Comment by ffissore** [comment]
@michaelk99 sorry for the delay. did you resolve this issue during these 2 years?
