### ISSUE TITLE
DHCP only allows 6-character host names

### ISSUE THREAD

**Issue by mji83** [arduino/Arduino#1416]
There's a hardcoded assumption in the following code in dhcp.cpp:
<PRE>
    printByte((char*)&(buffer[24]), _dhcpMacAddr[3]);
    printByte((char*)&(buffer[26]), _dhcpMacAddr[4]);
    printByte((char*)&(buffer[28]), _dhcpMacAddr[5]);
</PRE>

This causes various failures with the DHCP server if you define HOST_NAME to be a string that isn't exactly 6-characters long that will at best cause the DHCP server to not issue you an IP, and at worst cause a memory leak in the code. I fixed this portion of the code as follows:

<PRE>
 int hostNameLen = strlen(HOST_NAME); 
 buffer[17] = hostNameLen + 6; // length of hostname + last 3 bytes of mac address
 strcpy((char*)&(buffer[18]), HOST_NAME);
 printByte((char*)&(buffer[hostNameLen+18]), _dhcpMacAddr[3]);
 printByte((char*)&(buffer[hostNameLen+20]), _dhcpMacAddr[4]);
 printByte((char*)&(buffer[hostNameLen+22]), _dhcpMacAddr[5]);
</PRE>

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#11
