### ISSUE TITLE
How to change file for compiled files

### ISSUE THREAD

**Issue by Biribu** [arduino/Arduino#1420]
I want to keep my compiled files always in arduino folder. I found that in Base.java is where a random temp folder is created to keep compiled files.

I want to modify it to save compiled files in a folder inside arduino folder. Is it possible? I tried to modify createTempFile funcion inside createTempFolder by a createFile... but it fails...

What do I have to do?

**Comment by ffissore** [comment]
You can set `build.path` property in `preferences.txt`
