### ISSUE TITLE
Update to Stepper library [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#144]
This is [Issue 144](http://code.google.com/p/arduino/issues/detail?id=144) moved from a Google Code project.
Added by 2009-11-19T00:38:14.000Z by [Matttron...@gmail.com](http://code.google.com/u/108297967188019548100/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

If the stepper doesn't complete a full resolution or goes for long periods of 
time between steps or steps over a long period of time, it gets really hot 
due to a bug in the stepper code. It leaves coils enegized. I have added a 
motorOff() function that shuts off all power so that it will not become too 
hot. Future development could be to insert a timer since we know the speed 
and step degree and shut it off that way.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Stepper#1
