### ISSUE TITLE
3rd Party Hardware Spec: Exception Thrown if Assembly Compile Recipe is Missing

### ISSUE THREAD

**Issue by thisdroneeatspeople** [arduino/Arduino#1457]
This is with the 1.5.x nightly build for OSX downloaded on June 7th, but also happens with 1.5.2 release.

I created a 3rd party hardware spec by copying the arduino specification, and modified the relevant files (including the platform.txt file). 

However, using the default platform.txt (having changed the name in it), any attempt to compile throws the following runtime exception:

```
processing.app.debug.RunnerException
at processing.app.debug.Compiler.getCommandCompilerS(Compiler.java:516)
at processing.app.debug.Compiler.compileFiles(Compiler.java:219)
at processing.app.debug.Compiler.compileCore(Compiler.java:656)
at processing.app.debug.Compiler.compile(Compiler.java:106)
at processing.app.Sketch.build(Sketch.java:1568)
at processing.app.Sketch.build(Sketch.java:1547)
at processing.app.Editor$DefaultRunHandler.run(Editor.java:1942)
at java.lang.Thread.run(Thread.java:680)
```

This exception can be eliminated by adding the following line to the platforms.txt:

```
## Compile assembly files (na)
recipe.S.o.pattern=""
```

It is unknown why this only happens with my hardware spec, and not with the standard arduino specs, but if it is required for 3rd party specs, it should be included in the arduino platform.txt so that we may start from a good copy.

**Comment by janjongboom** [comment]
For someone stumbling onto this in the future, this error popped up for me when building a project using the Arduino CLI and shows up when there's `.s` files in your source tree.

**Comment by facchinm** [comment]
@cmaglie based on https://github.com/arduino/Arduino/issues/1457#issuecomment-602044064 , does the cli currently compile `.S/.s` files?
