### ISSUE TITLE
Servo Library page: request on disabled pins

### ISSUE THREAD

**Issue by fvacca** [arduino/Arduino#1460]
Original by Andrew Paterson:

The page on the Servo Library contains  the following:
The Servo library supports up to 12 motors on most Arduino boards and
48 on the Arduino Mega. On boards other than the Mega, use of the
library disables analogWrite() (PWM) functionality on pins 9 and 10,
whether or not there is a Servo on those pins. On the Mega, up to 12
servos can be used without interfering with PWM functionality; use of
12 to 23 motors will disable PWM on pins 11 and 12.
however, in looking at the code on github, it (thankfully) does not
appear to be the case any longer that PWM on pins 9 and 10 is
disabled.  Can you confirm this and, if true, update the web page.

**Comment by q2dg** [comment]
Is the sentence " On boards other than the Mega use of the library disables...on pins 9 and 10"  still valid? I'm thinking of modern boards like Atmega32U4-based and, especially, of ARM-based.
