### ISSUE TITLE
Arduino DUE - TwoWire issue using Wire1

### ISSUE THREAD

**Issue by timnh24** [arduino/Arduino#1469]
Looks like these 2 signals do not have the required pullup resistors attached on the Arduino DUE board like SDA and SCL. Should have these resistors in place for test today or tomorrow. I'll update this post with the results.

Are there any known issues using SDA1 and SCL1 on the Arduino DUE platform?

Our application requires both Wire and Wire1 peripherals. Wire (SDA,SCL) works fine but Wire1 (SDA1, SCL1) is not working. Putting a scope on these signals it clear that the initialization phase is failing. Since Wire1.begin() does return status and since we can not single step the code, I figured I would ask for help prior to diving into Wire.cpp.

Thanks
Timothy Kimball

/* *****************************************************************************
 * @brief Initializes the communication peripheral.
 * @param device  - Specifies the Wire or Wire1 I2C peripheral.
 * @return - None.
*******************************************************************************/
void I2C_Init(uint8_t side)
{
   // Assume IIC is working.
   ad5934[side].iicStatus = true;

   // Use the Arduino Wire Class to initialize I2C.
   // Note: I2C will run at 100Khz by default.
   if (side == eSideA)
   {
      Wire.begin();
   }
   else
   {
      Wire1.begin();
   }
}

**Comment by sandeepmistry** [comment]
@timnh24 I'm not seeing any issues with ``Wire1``.

What i2c slave device are you using? Are you reading or writing to the device?

I connected ``SCL0`` to ``SCL1`` and ``SDA0`` to ``SDA1``, then ran the following sketch:

```arduino
#include <Wire.h>

void setup() {
  Serial.begin(9600);

  // setup the master on Wire1
  Wire1.begin();

  // setup the slave on Wire
  Wire.begin(42);
  Wire.onReceive(receiveEvent);
  Wire.onRequest(requestEvent);

  // write data to slave
  Wire1.beginTransmission(42);
  Wire1.write("hi\n");
  Wire1.endTransmission(true);

  // read data from slave
  Wire1.requestFrom(42, 6, false);
  
  while (Wire1.available()) {
      char c = Wire1.read();

      Serial.print(c);
  }
}

void loop() {
  delay(1000);
}

void receiveEvent(int howMany) {
  Serial.print("howMany: ");
  Serial.println(howMany);

  while(Wire.available()) {
    char c = Wire.read();
    Serial.print(c);
  }
}

void requestEvent() {
  Wire.write("hello\n");
}
```

Expected output is:
```
howMany: 3
hi
hello
```

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen it if needed.
