### ISSUE TITLE
BUG: [FIRMWARE] 16U2 on Arduino Mega2560 r.3

### ISSUE THREAD

**Issue by cbernardo** [arduino/Arduino#1470]
I'm using a mega2560 in a datalogger with a computer periodically interrogating the Arduino via the usb-serial link.  The data throughput is very low (about 100 characters per 10 seconds) and the bitrate is set at 38400.  The 16U2 hangs erratically - sometimes in a few minutes and sometimes after 3 or 4 days - and I have verified that the problem is with the 16U2 by connecting another usb-serial adapter to TX0 + RX0 to confirm that I can still communicate with the atmega2560 and that it was functioning as expected.

Sometimes, before the 16U2 hangs it erroneously retransmits old data as if the circular buffer within the 16U2 was poorly implemented and the software didn't know the head from the tail. However, this is not always the case so I can't rule out other possible causes such as stack corruption.

**Comment by CorvusCoraxDK** [comment]
Any news regarding this bug ?

I have been strugling with it for a long time, and the only solution I have found was to use a external serial-usb adapter.

-Mads

**Comment by cbernardo** [comment]
No such luck. I didn't seem to encounter the problem on some devices shipped later, so perhaps the bug was fixed in later firmware revisions. Otherwise, for about half the boards I had, I put in an external serial-usb adapter. I can't remember exactly how I wired it though; some care must be taken since there are potentially several pins trying to drive the Tx line.
- Cirilo

**Comment by CorvusCoraxDK** [comment]
OK, thanks for the fast answer in an rater old thread. I hope that the new Mega2560 behaves, otherwise I will use an external serial-USB adapter. And thank you for the warning about several pins trying to drive the Tx line.
-Mads

**Comment by agdl** [comment]
@cbernardo since you don't have the same issue on new boards I'm closing this. Reopen it if needed
