### ISSUE TITLE
I2C/Wire library: Allow multiple Wire.write in Slave onRequest handler.

### ISSUE THREAD

**Issue by ghost** [arduino/Arduino#1475]
If an Arduino is set as an I2C Slave, the onRequest handler can write data (being slave-transmitter) in the buffer. However only one Wire.write() can be used.

With Arduino version 1.0.5

The update would be easy, as shown by user veeman, http://forum.arduino.cc/index.php?topic=171474.0

**Comment by dronus** [comment]
As for now Wire implements a Stream interface, this behaviour is akward, as it affects print, println too. As print is often used repeated to output values of different type, this is easily triggered and leads to unexpected behaviour of print and println.

**Comment by sandeepmistry** [comment]
This has been corrected by #5014 from @kellerkindt.
