### ISSUE TITLE
menu bug

### ISSUE THREAD

**Issue by tecan** [arduino/Arduino#1484]
when the monitor is rotated to vertical view the menu's are not displayed in proper spots. effect can be enhanced with a larger window

**Comment by agdl** [comment]
Waiting for feedback from too long reopen it if needed.

**Comment by tecan** [comment]
sorry for the late reply the bug seems to be fixed in all versions of arduino IDE, in mate desktop 1.8.1. thanks for looking.

**Comment by agdl** [comment]
@tecan perfect! Thank you!
