### ISSUE TITLE
Wifi WEP connection fails

### ISSUE THREAD

**Issue by chris711** [arduino/Arduino#1486]
I'm using an Arduino Mega 2560 with the WIFI shield and the ConnectWithWep example. The device fails to connect to my network and the error led lights up on the WIFI shield.

My router shows up if I run the scan network example.

My network is running the Shared Key Authentication mode for WEP.

If I switch to WPA everything works fine.

**Comment by chris711** [comment]
I switched my network to wpa and that worked.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#16
