### ISSUE TITLE
error: invalid digit "8" in octal constant.

### ISSUE THREAD

**Issue by sjoch** [arduino/Arduino#1490]
Hi.

I came across a strange errormessage and it might be a bug in the 1.0.5 version of the arduino software.

The part of the code that gets the error looks like this:
"        if (i == 01) catchd01 = t;
        if (i == 02) catchd02 = t;
        if (i == 03) catchd03 = t;
        if (i == 04) catchd04 = t;
        if (i == 05) catchd05 = t;
        if (i == 06) catchd06 = t;
        if (i == 07) catchd07 = t;
        if (i == 08) catchd08 = t;
        if (i == 09) catchd09 = t;
"

And the compiler only complains on the last 2 lines.

error: invalid digit "8" in octal constant
error: invalid digit "9" in octal constant

So, whats wrong? it compiles good if all zeros are removed from the i == part.
But shouldnt it complain on all 9 lines if its the zero that is the problem.. why just 8 and 9?

**Comment by srknthcse** [comment]
Error solved but i need clear explanation can anybody explain .thank you

**Comment by shaishu03** [comment]
> Error resuelto, pero necesito una explicación clara, ¿alguien puede explicarme? Gracias.

como lo solucionaste?
