### ISSUE TITLE
arduino commandline only full path accepted

### ISSUE THREAD

**Issue by haobug** [arduino/Arduino#1493]
the .ino full path must be given.

either of following two will not work
$arduino some_proj.ino 
$arduino ./some_proj.ino
it works only in this way.
$arduino  `pwd`/some_proj.ino

my environment.
arduino version: downloaded from here http://downloads.arduino.cc/arduino-1.5.2-linux64.tgz
java version "1.7.0_21"
OpenJDK Runtime Environment (IcedTea 2.3.9) (7u21-2.3.9-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

**Comment by ffissore** [comment]
I've googled around once more and I can't find a working way of knowing current directory when using the `Arduino` binary from macosx. Tagging as "wontfix" and leaving open until working non hacks show up

**Comment by wayoda** [comment]
> I've googled around once more and I can't find a working way of knowing current directory when using the Arduino binary from macosx. 

I wrote this little test application [GetSystemPath.java](https://gist.github.com/wayoda/3d83ded3642e9531f731) for the commandline that reports the users current working dir, and the filesystem location of the jar file from which the little app is run. 

Here is a link to a jar-file with that class 
[gsp.jar](https://drive.google.com/file/d/0B77BN-f58jE6ZWc5RGdFb1h1TEU/view?usp=sharing)

Run this jar from anywhere on your filessystem
```'
wayoda@shredder:~/dev/java/arduino-user-dir$ java -jar ~/bin/gsp.jar 
          Current user dir is : '/home/wayoda/dev/java/arduino-user-dir'
         Here is the jar-file : '/home/wayoda/bin/gsp.jar'
The directory of the jar-file : '/home/wayoda/bin'
```
If anybody could please try this on a Mac? Does it really fail on OSX???

> Tagging as "wontfix" and leaving open until working non hacks show up

```
File jarDir=new File(GetSystemPath.class
                                    .getProtectionDomain()
                                    .getCodeSource()
                                    .getLocation()
                                    .toURI().getPath());
```
This is not a hack AFAIK.

**Comment by matthijskooijman** [comment]
@wayoda, it seems your example assumes running java directly, but on OSX Arduino uses an application launcher thingy AFAIK, that changes the current directory on startup (so I'd expect that your GetSystemPath thingy will then return the changed directory, not the original). I might be wrong, I've never actually used a Mac...

**Comment by wayoda** [comment]
> OSX Arduino uses an application launcher thingy 
So does windows (launch4j), but it is easy to fix this.

**Comment by matthijskooijman** [comment]
> So does windows (launch4j), but it is easy to fix this.

What do you mean by "fix"? Stop using the launcher, or configure the launcher to not change the working dir? It seems that on OSX, the latter isn't possible (at least I couldn't find a way, looking at documentation only, last time I tried).

**Comment by wayoda** [comment]
There is an config file for the launch4j utillity that creates the windows exe in
`build/windows/launcher/config.xml`

The key `<chdir>.</chdir>` tells the application to set the `user.dir` the directrory where the exe lives.

From [launch4j-config](http://launch4j.sourceforge.net/docs.html)

> `<chdir>`
> Optional. Change current directory to an arbitrary path relative to the executable. If you omit this
> property or leave it blank it will have no effect. Setting it to . will change the current dir to the same > > directory as the executable. 
> `..` will change it to the parent directory, and so on.

**Comment by matthijskooijman** [comment]
Yeah, I can see how that would work on Windows. However, AFAIK (last time I checked, anyway) we don't use launch4j on OSX, but some Apple-provided launcher thing. Or did this change recently?

**Comment by wayoda** [comment]
The important function for all of this is  `processing.app.BaseNoGui.getContentFile(String name)`that is used for looking up all the application resouces like the hardware path etc. For Linux and windows the function uses the artficially changed `user.dir` property and for the Mac it already uses .....

```
 static public File getContentFile(String name) {
    File path = new File(System.getProperty("user.dir"));

    if (OSUtils.isMacOS()) {
      if (System.getProperty("WORK_DIR") != null) {
        path = new File(System.getProperty("WORK_DIR"));
      } else {
        try {
          path = new File(BaseNoGui.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParentFile();
        } catch (URISyntaxException e) {
          throw new RuntimeException(e);
        }
      }
    }
```
... the method I was proposing for the other platforms too.

So to me the only question is:
> When I call the `arduino-launcher-thingy` on a **Mac** from the commandline is the `user.dir` property properly set to the users current directory?

**Comment by ffissore** [comment]
The answer is "no": it's always set to user's HOME, despite the location of the app, despite your current directory when you launch it from a terminal

**Comment by wayoda** [comment]
> The answer is "no": it's always set to user's HOME, despite the location of the app, despite your current directory when you launch it from a terminal

Thanks for testing, too bad!

Looks like OSX is simply **broken** in respect to the Java Documentation on `user.dir`: http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperties()

**Comment by ffissore** [comment]
Indeed :(

**Comment by ffissore** [comment]
FYI, I've opened an issue at https://bitbucket.org/infinitekind/appbundler/issue/14/missing-a-way-for-having-current-working

**Comment by ffissore** [comment]
Please give a spin to #3421 as soon as bot has published it

**Comment by wayoda** [comment]
Linux version with #3421 pulled in compiles and runs fine.

**Comment by ffissore** [comment]
I'm glad to say: fixes. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
