### ISSUE TITLE
MIDI tutorial needs specific addition for Leonardo

### ISSUE THREAD

**Issue by pmarbaix** [arduino/Arduino#1500]
The MIDI communication tutorial http://arduino.cc/en/Tutorial/Midi and the associated example should note that on the Leonardo, using the Serial class will fail - Serial1 must be used instead (as documented on the Leonardo page, but Tutorials are for beginners - so it is better to guide them, this is not trivial)

**Comment by agdl** [comment]
@pmarbaix as @lestofante says the tutorial shows an UNO and no other boards as many arduino tutorials. So this isn't a proper issue. If you want to use many Arduino tutorials with a board different from the indicated one you have to search and adapt it.

**Comment by pmarbaix** [comment]
Dear Arturo,

I do not see a reference to the UNO on that page. The shown board itself doesn’t seems to differentiate between UNO and other boards (especially Leonardo because it looks very similar). Hence I think that it would be better to mention that the provided tutorial is UNO based. At present I see no way through which a beginner could understand that this tutorial relates only to a UNO. Adding a caveat that the tutorial is only for the UNO and that other boards may need adaptation would be a bare minimum, unless I missed something (I do not see why it would make harm to remember that some boards should use Serial1).

Best wishes for 2015.

Philippe.

Le 9 janv. 2015 à 15:33, Arturo Guadalupi <notifications@github.com<mailto:notifications@github.com>> a écrit :


@pmarbaix<https://github.com/pmarbaix> as @lestofante<https://github.com/lestofante> says the tutorial shows an UNO and no other boards as many arduino tutorials. So this isn't a proper issue. If you want to use many Arduino tutorials with a board different from the indicated one you have to search and adapt it.

**Comment by agdl** [comment]
@pmarbaix I added this sentence to the page
Attention

Since Serial object is used to use this tutorial with 32u4 based boards like Leonardo, replace Serial with Serial1

**Comment by pmarbaix** [comment]
thank you

Philippe.
Le 9 janv. 2015 à 17:17, Arturo Guadalupi <notifications@github.com<mailto:notifications@github.com>> a écrit :


@pmarbaix<https://github.com/pmarbaix> I added this sentence to the page
Attention

Since Serial object is used to use this tutorial with 32u4 based boards like Leonardo, replace Serial with Serial1
