### ISSUE TITLE
Expand / Collapse Functions in IDE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#151]
This is [Issue 151](http://code.google.com/p/arduino/issues/detail?id=151) moved from a Google Code project.
Added by 2009-12-05T23:14:43.000Z by [rick.bro...@gmail.com](http://code.google.com/u/106333784486395813202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
To the left of each function name, there should be a method to expand or 
collapse the entire function.

**Why?**
Increased usability

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
Do not believe so

**Comment by ffissore** [comment]
Fixed with #3019 and available with latest hourly build http://www.arduino.cc/en/Main/Software#hourly
