### ISSUE TITLE
Coverity Scan Opportunity

### ISSUE THREAD

**Issue by noloader** [arduino/Arduino#1512]
Coverity offers free scanning services for free and open source projects at http://scan.coverity.com. The Arduino signal-filtering-library is part of the scanning service, but I don't believe other Arduino projects are, such as the Arduino Editor and Arduino Serial Monitor.

The service will help identify bugs, which could increase quality and improve stability.

**Comment by ffissore** [comment]
We are doing that on our internal CI server
