### ISSUE TITLE
Factory-Fresh Atmegas not correctly initialized when using "Upload using Programmer"

### ISSUE THREAD

**Issue by deltaphi** [arduino/Arduino#1514]
To reproduce:
- Get a non-arduino-preloaded Atmega168
- Flash any sketch using programmer (e.g., Blink)
- Sketch does not work (for Blink: LED just stays on all the time)

For comparison:
- Flash the Ardunino NG w/ 168 bootloader
- Upload any sketch using programmer
- Sketch works

For reference: I'm using an Arduino as ISP for programming. I made a similar observation on Atmega8, this may affect other Atmegas as well.

Tested using Arduino 1.0.5 on OSX, although I believe I have seen this since at least Arduino 1.0.3 on both OSX and Windows.

So clearly, uploading a bootloader has a different effect on the Atmega than simply uploading a sketch. I have not seen this behavior documented, so it quickly leads to thinking that you ordered a broken batch of Atmegas.

My personal suspicion, purely from observation without much of an idea of the underlying process: Some Fuse settings are wrong for Arduino on Atmegass fresh from the factory. These settings are not corrected when a sketch is uploaded using the programmer.

The behavior of the Arduino IDE should be changed to correctly initialize the Atmegas. At the very least, this behavior should be documented, e.g., on http://arduino.cc/en/Hacking/Programmer

**Comment by matthijskooijman** [comment]
@agdl, what was the reason for closing this? I don't think this is resolved yet - at the very least it needs improved documentation.

**Comment by Testato** [comment]
+1
It's time for write a "Burn Fuse" option, that pick the correct one from the board.txt

And the burn bootloader+the upload using programmer, will check the fuse before it job, if not equal to the board.txt appear a message that invite to use "Burn Fuse" option

**Comment by agdl** [comment]
@matthijskooijman sorry, I don't even remember that I closed this issue, maybe a wrong click. However I changed the documentation at https://www.arduino.cc/en/Guide.Environment to state that Burn Bootloader sets the fuses while Upload Using a Programmer doesn't.

**Comment by deltaphi** [comment]
Thank you very much, @agdl! At least there is now some documentation on this issue. However, when searching for "Programmer" on the Arduino website, the first hit that comes up is https://www.arduino.cc/en/Hacking/Programmer. While that page has been greatly reduced in size since I filed this bug 2 years ago, it still tells you how to upload a Sketch without a bootloader, but does not mention that a factory-fresh Atmega has to be bootloaded anyway. So I maintain that having a hint on handling Factory-fresh Atmegas on that page would be very helpful.

**Comment by agdl** [comment]
@deltaphi I added this statement
*However you must have in mind that the ''Upload Using Programmer'' procedure doesn't burn fuses so, if you have a fresh factory micro-controller you have to burn the boot-loader first in order to have a properly working device.*
in the page you linked. If it is ok for you please close the issue otherwise I will modify it in vase of your requests! Thank you!

**Comment by Testato** [comment]
I only suggest to add to the page that upload using programming do not work on Mega.

**Comment by deltaphi** [comment]
@agdl Awesome, thank you! I'm closing this issue.

@Testato That would be a different point - I suggest you open a new issue for that point.
