### ISSUE TITLE
WiFi Shield - Static IP addresses - WiFi.config(ip) and wrong endianness

### ISSUE THREAD

**Issue by ankitdaf** [arduino/Arduino#1520]
I just checked, there is an issue with the WiFi shield, a simple issue that is causing a lot of pain.

The endian-ness of the parameter is somehow wrong.

For example, I gave it an ip-address of 192.168.0.104. 
Its equivalent uint32 value is 3232235624 since
2^24 × 192 + 2^16 × 168 + 2^8 × 0 + 120 = 3232235640

However, when I call WiFi.begin, the wifi status output is as below : 
IP Address: 120.0.168.192

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#15
