### ISSUE TITLE
WiFi Shield - Static IP addresses - WiFi.config(ip) acting erratically

### ISSUE THREAD

**Issue by ankitdaf** [arduino/Arduino#1521]
Using the following lines of code to set my static IP address : 
IPAddress myip = (192,168,0,105); 
returns my IP address as  105.0.0.0
and similarly 
IPAddress myip = (105,0,168,192); 
returns my IP address as 192.0.0.0

It simply discards the first three bytes.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#14
