### ISSUE TITLE
Using pins 6-9 causes the Due to crash when using the Ethernet R3 shield and WebServer example

### ISSUE THREAD

**Issue by SeanDS** [arduino/Arduino#1539]
I'm using the Arduino Ethernet R3 shield with a Due board. The Ethernet shield uses the ICSP connector to communicate with the Due via the SPI socket on the Due, so it frees up pins 11, 12 and 13 for general I/O. Pin 10 is still used for chip select / slave select.

When I use the Ethernet and SPI libraries to set up a simple web server (basically the WebServer example but with an added function to set pins 2-13, excluding 10, to high, when a specific GET command is issued), setting any of pins 6-9 to high (via analogWrite(4095)) causes the web server to become unresponsive.

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#30
