### ISSUE TITLE
pin for shift registers tutorial

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#1544]
Original by Sam Fredericks:

I am abit confused by an error in this tutorial.
http://www.arduino.cc/en/Tutorial/ShiftIn

In the second Example (Daisy Chain)
the setup step 2 has the following:

2. Connect the 2 registers.
Two of these connections simply extend the same clock and latch signal from the Arduino to the second shift register (yellow and green wires). The blue wire is going from the serial out pin (pin 9) of the first shift register to the serial data input (pin 14) of the second register.

The Serial out pin should be Pin 3 and Serial in on Pin 11.
Pin 9 & 14 is from the ShiftOut Tutorial for the 595 .

This error may confuse those starting out with shift registers.

**Comment by agdl** [comment]
@tamul it was uptaded amd sould be correct. Thank you
