### ISSUE TITLE
proposed new faq

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#1545]
Original by Stephen Kangas.
If all informations are exact, this paragraph can be added to http://arduino.cc/en/Guide/Troubleshooting

Here’s something that I noticed on another group forum (one unrelated to Arduino but where a conversation has started about Arduino applications), and that is the same problem that I ran into after receiving my first Arduino board.  I suggest you add this to your FAQ page on your website to save mucho time for new users of Arduino boards trying to find an answer (ie, without having to comb through another support forum/site)…
 
Q: What type of power supply should I use with my Arduino board?
A:  Typically, the Arduino board can operate satisfactorily on power that is available on the USB port of the computer that it is connected to, depending upon the number and type of optional Shield modules used with the Arduino board and the rated USB power current available from the computer (varies according to computer manufacturer and model).  If you find that additional power is required from your Arduino board to operate it properly, OR if you need to operate the Arduino board disconnected from a USB port or when using it with one that does not provide power, then you need to acquire a power supply that provides 9V (Volts) of DC (Direct Current) power with enough current capacity for your needs.  The AC adapters commonly available in retail stores (eg, Radio Shack, Best Buy, Fry’s, etc, or on eBay) for use with consumer products are often suitable, but make sure that it has the proper connector for plugging into the power socket on your Arduino board: 5.5mm diameter cylindrical plug with 2.1mm pin hole, and that provides Positive voltage on the inside pin hole and Negative (or common/ground) voltage on the outside cylindrical sleeve of the connector plug.  For most applications, 1A (Amp) of current supply capacity is sufficient, but you may find that you’ll need more if you have a specific Shield module that needs it, or a stack of several Shield modules that along with the Arduino board draws a higher total current.  You should add (sum) the rated Input power current requirement for each Shield you are using along with your Arduino board to get the total needed, and acquire a power adapter/supply that provides a minimum of that total (higher current power supply current capacity has no ill effects).

**Comment by agdl** [comment]
I think now it is more clear. I'm closing this. Reopen if needed!

**Comment by jantje** [comment]
Can you explain what is more clear?

**Comment by agdl** [comment]
i posted the Q and the A in the trouble shooting rephrasing it

**Comment by jantje** [comment]
I see. I must have missed it. It looks like the formatting is a bit off when using firefox.

**Comment by agdl** [comment]
Which firefox version do u use? I don't have this problem with the 37.0

**Comment by jantje** [comment]
I'm using firefox 31.5.0
I see the same behaviour in chrome version 39.0.2171.95 (64-bit)
And if I look at the source of the page I see a <pre> tag with 1 very long line.  
<pre> Typically, the Arduino board can operate satisfactorily on power that is available on the USB port of the computer that it is connected to, depending upon the number and type of optional Shield modules used with the Arduino board and the rated USB power current available from the computer (varies according to computer manufacturer and model). If you find that additional power is required from your Arduino board to operate it properly, or if you need to operate the Arduino board disconnected from a USB port or when using it with one that does not provide power, then you need to acquire a power supply that provides from 7 to 12V (Volts) of DC (Direct Current) power with enough current capacity for your needs. The AC adapters commonly available in retail stores for use with consumer products are often suitable, but make sure that it has the proper connector for plugging into the power socket on your Arduino board: 5.5mm diameter cylindrical plug with 2.1mm pin hole, and that provides Positive voltage on the inside pin hole and Negative (or common/ground) voltage on the outside cylindrical sleeve of the connector plug. For most applications, 1A (Amp) of current supply capacity is sufficient, but you may find that you’ll need more if you have a specific Shield module that needs it, or a stack of several Shield modules that along with the Arduino board draws a higher total current. You should sum the rated Input power current requirement for each Shield you are using along with your Arduino board to get the total needed, and acquire a power adapter/supply that provides a minimum of that total (higher current power supply current capacity has no ill effects).
</pre>

**Comment by agdl** [comment]
try now please

**Comment by jantje** [comment]
much better
