### ISSUE TITLE
Due / SerialUSB losing bytes (high write rate/small buffer size)

### ISSUE THREAD

**Issue by pottedplant** [arduino/Arduino#1551]
dd if=foo of=/dev/ttyACM1 bs=64 # works fine
dd if=foo of=/dev/ttyACM1 bs=1 # ~13% byte loss
dd if=foo of=/dev/ttyACM1 bs=2 # ~5% byte loss
dd if=foo of=/dev/ttyACM1 bs=3 # seems to work fine

-- edit: test sketch:
void setup() {
 Serial.begin(115200);
 SerialUSB.begin(115200);
}

void loop() {
   char buffer[512];
   int l = SerialUSB.readBytes(buffer,512);
   if(l) Serial.println(l);
}

-- edit: stty settings: disabled everything except: cs8 cread clocal 115200

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#29
