### ISSUE TITLE
malloc() and free() are not interrupt safe

### ISSUE THREAD

**Issue by xxxajk** [arduino/Arduino#1554]
Simply put, if an interrupt routine uses malloc() or free() or new() or delete() the malloc arena and/or free list pointers can be corrupted.

I know nobody will like this, but both malloc() and free() need to be surrounded by cli() and sti() in order for it to be safe. This is a simple fix.

**Comment by xxxajk** [comment]
FWIW I'm providing a patch for this within the library that needs it.
https://github.com/felis/UHS30/tree/master/libraries/UHS_host

Thankfully such useful and simple things can be done by overriding the defunct cruft. 
Well, defunct in my opinion anyway. 
Don't take it as a sarcastic comment, for most things, stuff works. I just have higher requirements.

**Comment by cmaglie** [comment]
Hi @xxxajk,

I'm closing this because I don't want to change some base functions like `malloc` unless there is a really compelling reason to do so, the last thing I want is to add another maintenance burden to avr-libc.

But, really, why don't you try to push this upstream?
I'm wondering, don't you have the same problem for ARM, or other MCU architectures, too?

**Comment by xxxajk** [comment]
Yes, and UHS 3.0 contains fixes for AVR and any mcu using newlib (ARM and
mips).

**Comment by Chris--A** [comment]
I would personally overload global and class based operator new, but it looks like you have a lot of `C` code.

Either way it seems like it would be better to leave the standard as 'standard' and have your own custom allocation functions which incorporate interrupt handling, then you can also avoid confusion/misinformation with people browsing the code ( `thread_safe_alloc()`, `thread_safe_free()` ).

**Comment by xxxajk** [comment]
You cannot pragmatically do that and expect unknown code to obey the same
rules, therefore I supply direct replacements. The replacements are used
instead of the library, because LD does not have to look for it... Nothing
to override because it is C.
