### ISSUE TITLE
windows 7 creates undeletable files when using Arduino 1.0.5-windows

### ISSUE THREAD

**Issue by ayedee2** [arduino/Arduino#1571]
The reason they can't be deleted is that they too long pathnames. This is probably a windows 7 problem but can anyone help with this? Until I can resolve this issue I will have to go back to using 0022 on windows XP.

**Comment by ffissore** [comment]
Is this issue still valid?

**Comment by ffissore** [comment]
This issue should be fixed by  587590968356aeafb7b587ff16f6efad26e95bec, 3ecaf665ae4b3ce6c33f20d3eaf93e8193de60f3 and bede6967d5f0eaaeb927f43ac1168912e5dc1c98
