### ISSUE TITLE
EthernetClient flush() is pre-1.0 input discard

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#1576]
EthernetClient.cpp in 1.5.x has old pre-1.0 flush() function that discards input.  Arduino 1.0 changed flush() to complete transmission.

https://github.com/arduino/Arduino/blob/ide-1.5.x/libraries/Ethernet/src/EthernetClient.cpp#L122

void EthernetClient::flush() {
  while (available())
    read();
}

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#27
