### ISSUE TITLE
Handle multiple SPI devices

### ISSUE THREAD

**Issue by mikaelpatel** [arduino/Arduino#1581]
The current SPI implementation is very basic and it is difficult to handle multiple SPI devices that do not have the same bus settings (bit order, clock frequency, phase and polarity). There is also a lack of support for chip select and interrupt handling both master and slave mode.

Users have great problems with using several SPI device libraries in their sketches. 

Cheers, Mikael

**Comment by q2dg** [comment]
I think this issue should be closed (see https://github.com/arduino/Arduino/issues/3406)

**Comment by PaulStoffregen** [comment]
Yes, this is an old issue.  SPI transactions address the multiple device issues.  Chip select handling is done with digitalWrite, and there's a Due-specific API now for hardware support.
