### ISSUE TITLE
Arduino IDE 1.5 BETA and Arduno WiFi Shield and Arduino Due

### ISSUE THREAD

**Issue by davidcittadini** [arduino/Arduino#1589]
There is a recorded bug that when you install the Arduino WiFi Shield you can ping to the device but it does not work as a WiFi Server *Bug #1466.  Exactly the same problem exists if you use the Arduino Due board and the 1.5 BETA software.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#13
