### ISSUE TITLE
New interface design (with pictures!)

### ISSUE THREAD

**Issue by cannikin** [arduino/Arduino#1590]
Hey guys,

I've been working with the IDE now since version 0009 I believe. I finally sat down and sketched out what I think would be a beautiful overhaul to the UI for our favorite IDE.

![arduino_ide](https://f.cloud.github.com/assets/300/1213285/a5d8c9ae-2626-11e3-853d-05b692f3839d.png)

The biggest change would be to the **editor** itself. Right now I always use an external editor and it's really only to get some pretty basic functionality which would now be included right in the Arduino IDE itself:

* Line numbers (with an option to show/hide)
* Code folding
* Typeface update to antialiased Menlo (on the Mac) or Consolas (on Windows)
* Change your code coloring theme (screenshot uses Twilight) including swapping the white/black background

There's the addition of a **drawer** on the left that contains all of your Sketchbook files as well as examples and library code (all of which are expandable/collapsable). The drawer can be resized or hidden completely.

A **search bar** at the upper-right. By default it would search the file you're currently editing but would have a little dropdown of options for searching all open tabs or all files in the Sketchbook (or examples or libraries).

The **terminal** is now aliased Monaco (Mac) or Courier New (Windows). The terminal can be resized or hidden completely (running a Verify or Upload always opens it again).

Board and port are persisted in the footer.

I haven't sketched up what the serial monitor could look like yet. Assuming this ticket doesn't immediately get closed with a "you suck" message, I can add one soon. :)

Granted this design is 100% Mac focused. I'd be happy to do one that fits with the Windows Metro theme and a Gnome/KDE version as well.

I love the Arduino and the existing IDE is one of the things that makes it such a pleasure to work with. I'd just like to refresh the frame a little bit while keeping that wonderful core functionality alive and well!

**Comment by tschertel** [comment]
Any news on interface improvements??
IDE really needs it.

**Comment by Nandox7** [comment]
Hey, will this ever happen? 
The current IDE is dreadful, specially when working on a project with multiple files and on a small screen like of a laptop.

**Comment by ffissore** [comment]
Thank @cannikin for the proposal. The Java IDE has been screen shot  so many times that we just can't change its UI without disrupting existing tutorials/articles/books
Still, this issue brought @ryanthejuggler propose RSyntaxTextArea, which is available with the hourly builds http://www.arduino.cc/en/Main/Software#hourly

**Comment by tschertel** [comment]
@ffissore, I understand that sometime UI will change, right?
@cannikin proposed really good improvements. Everyone in community would be thankful for this changes.

**Comment by ffissore** [comment]
No, UI will not change as proposed. Only tiny little parts of it, to accommodate new features

**Comment by cannikin** [comment]
How "hard" would it be for someone to create their own IDE from scratch? (I realize asking how hard something is is a bit of a loaded question!) For example, is any of this exceedingly difficult to create from scratch: http://www.arduino.cc/en/Hacking/BuildProcess So difficult that it just wouldn't be worth it?

**Comment by ffissore** [comment]
AFAIK it's indeed difficult. However, many attempts have been made. You can find at least ten different IDEs that are based or use the Arduino IDE command line but offer a different editor. Some of them are open, most of them are closed source

**Comment by tschertel** [comment]
@cannikin I know [1] Gnoduino and [2] Arduide. Python/GTK and QT based, respectively.
Both are not being developed recently. But are a good start to fork and improve.

[1] - gnome.eu.org/index.php/Gnoduino
[2] - http://mupuf.org/project/arduide.html
