### ISSUE TITLE
No answer for pull requests on wifishield repo ?

### ISSUE THREAD

**Issue by sdrdis** [arduino/Arduino#1591]
Hi,

Just a message to say that there are a bunch or pull requests that have never received an answer since many months.

https://github.com/arduino/wifishield/pulls

Mine is insignificant, but the one from Detmud is interesting. I am just writing this message in case there is a problem in your notifications...

Anyway; thanks for this amazing project :).

**Comment by ffissore** [comment]
Answers to PRs get into PRs
