### ISSUE TITLE
Saving window position and size

### ISSUE THREAD

**Issue by willie68** [arduino/Arduino#1592]
I'm working on an 1920x1080 screen and if i start the IDE the window is so small...
I would like to see, that the window position and the size is saved on leaving the IDE and restored on starting. 
![arduinoide](https://f.cloud.github.com/assets/5518382/1224357/f34bf964-2747-11e3-8455-e21c93a2f2f4.png)

**Comment by willie68** [comment]
Using 1.6.3, the same. 
Ctrl-Q, File Close now working, but F4 or closing with the x doesn't work.

**Comment by ffissore** [comment]
This should be fixed or at least mitigated by cc4af81ac54313da03b0733cc754eb1f3d040374 available in latest hourly build

**Comment by willie68** [comment]
Just don't get any mail on this. f*** github
I give another try in 1.6.5_r2, not working. Closing with the x, no position, size saving, no autoopen last project. Has anyone something done? It's very annoying, this issue is 1,5 years old, you're discussing about new hardware and library structures over month and just don't get the easiest things right.

**Comment by ffissore** [comment]
Closing with X won't save position nor reopen opened sketches. Use CTRL+Q or File > Quit. Then every sketch will reopen each with its previous windows size

**Comment by willie68** [comment]
And that is the bug. I and many other windows users always close application with x or [ALT]+[F4] and that is normal. A hotkey like CTRL+Q is unusual in windows enviroment. Because hotkeys will change from application to application...
In previous comments i suggested a solution.

**Comment by ffissore** [comment]
This bug (saving window size and reopening last sketches) has been solved. Your additional request of making ALT+F4 behave like File > Quit is perfectly reasonable and should go into a new issue

**Comment by PaulStoffregen** [comment]
FWIW, this is a patch I've been applying to Arduino for years.

>So i have put the storeSketchs() before the editors.remove() and that worked too.

People really like it, and it seems to have no adverse issues.  But if it doesn't belong in the official IDE, that's fine.  I'm happy to keep patching.

**Comment by PaulStoffregen** [comment]
Or if there is some technical reason why that's a bad practice, I'd very much like someone to set me straight.  I've adapted this patch to every non-beta version of Arduino since the 0017 days.

**Comment by willie68** [comment]
>This bug (saving window size and reopening last sketches) has been solved. Your additional request of >making ALT+F4 behave like File > Quit is perfectly reasonable and should go into a new issue

But that's, what this issue is about. File > Quit or STRG+Q has worked always (with a short break).
