### ISSUE TITLE
Leonardo pinmode OUTPUT before INPUT (1.0.5)

### ISSUE THREAD

**Issue by jfgass83** [arduino/Arduino#1593]
On the Leonardo if you want to use A3, A4, A5 as outputs and Digital pins 0,1,2 as inputs you must declare the outputs before declaring the inputs.  If inputs are declared before outputs the output declarations (A3,A4,A5) overwrites the input declarations on 0,1,2.  I placed a while (1) in the setup to nail down where the problem was.  It occurred after second output declaration (A4);

ex:
//this does not work
pinMode(0, INPUT); 
pinMode(1, INPUT); 
pinMode(2, INPUT); 

pinMode(A5, OUTPUT);
pinMode(A4, OUTPUT);
pinMode(A3, OUTPUT);

//works
pinMode(A5, OUTPUT);
pinMode(A4, OUTPUT);
pinMode(A3, OUTPUT);

pinMode(0, INPUT); 
pinMode(1, INPUT); 
pinMode(2, INPUT);

**Comment by matthijskooijman** [comment]
Seems this bug was not reproducible. If it still persists, please reply to the previous comment and we can reopen this issue.
