### ISSUE TITLE
Shiftout13 indicates the wrong pin numbers in the sketch.

### ISSUE THREAD

**Issue by matelot** [arduino/Arduino#1641]
If I go to shiftout13 in the tutorials I notice the pin outs in the sketch are assigned to pins 2,3 and 4 in the instructions within the sketch but assigned to pins 8, 12 and 11 further down the sketch.
Is there a sketch anywhere that outputs the contents of an array to the 74HC595?

**Comment by agdl** [comment]
I'm closing this. It is correct now
