### ISSUE TITLE
WiFiUdp write() does not work when repeatedly writing single bytes

### ISSUE THREAD

**Issue by fpoto** [arduino/Arduino#1642]
Writing a buffer with a single call to WiFiUdp.write() works, while writing that same buffer one byte at a time does not.

The gist at https://gist.github.com/fpoto/7163904 demonstrates the problem.

Expected output with ```allTogether``` set to ```true```:
```
Attempting to connect to SSID: xxxxxxxx connected
UTC time: 1382745247
UTC time: 1382745249
UTC time: 1382745251
UTC time: 1382745254
UTC time: 1382745257
```

Expected output with ```allTogether``` set to ```false```:
```
Attempting to connect to SSID: xxxxxxxx connected
endPacket successful
request failed
```

You may notice that when it fails it also stops looping.  I did not investigate why.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#10

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#11
