### ISSUE TITLE
WiFiUdp begin() ignores its argument and always uses port 4097

### ISSUE THREAD

**Issue by fpoto** [arduino/Arduino#1643]
I checked this using my example program at https://gist.github.com/fpoto/7163904 and sniffing the NTP packet at the server. I observe that the local port is 4097 whichever the argument of WiFiUdp.begin().

**Comment by josephlm** [comment]
I am also observing this behavior.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#9
