### ISSUE TITLE
WiFiUdp read() fails when repeatedly called with two arguments

### ISSUE THREAD

**Issue by fpoto** [arduino/Arduino#1644]
I use repeated ```WiFiUdp.read()``` calls to read data from a single received packet.

In this scenario, ```read()``` without arguments works as expected, but fails when called with two arguments (buffer and length).

The gist at https://gist.github.com/fpoto/7171230 demonstrates the bug: when the ```bufl``` is set to 0 five NTP requests are sent and the response received. This is the expected serial output:
```
Attempting to connect to SSID: xxxxxxxx connected
UTC time: 1382804072
UTC time: 1382804074
UTC time: 1382804076
UTC time: 1382804078
UTC time: 1382804080
```

When ```bufl``` is set to a different number ```read()``` does not work. Everything should work with values of ```bufl``` set to 1, 2, 4, 8, 16 or 32. This is the observed output with any of those values:
```
Attempting to connect to SSID: xxxxxxxx connected
wrong time
UTC time: 2085978495
wrong time
UTC time: 2085978495
wrong time
UTC time: 2085978495
wrong time
UTC time: 2085978495
wrong time
UTC time: 2085978495
```

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#8
