### ISSUE TITLE
SPIClass::transfer function always return 0xEE(238) after some data exchange while using WiFi shield and Arduino Due board

### ISSUE THREAD

**Issue by PradeepMW** [arduino/Arduino#1654]
Use case: Arduino Due and WiFi shield is used to send and receive data to/from host PC(desktop) through a router. 
Application is running every 10ms and WiFiClient.read() is called in this application loop.

SPIClass::transfer function always return 0xEE(238) after some data exchange while using WiFi shield and Arduino Due board.
START_CMD(0xE0) is never read in SPI_RDR register even though data is sent from host(PC) side. Once this occurs, SPI communication on Arduino Due never reads any data sent from WiFi shield.

In file \arduino-1.5.4\libraries\WiFi\arch\sam\utility\spi_drv.cpp, if the "DELAY_TRANSFER() DELAY_SPI(10)" is changed to "DELAY_TRANSFER() DELAY_SPI(200)", this behavior is not observed.

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#27
