### ISSUE TITLE
OSX crashes recurrently

### ISSUE THREAD

**Issue by dpharris** [arduino/Arduino#1656]
OSX crashes after several uploads.  See: http://forum.arduino.cc//index.php?PHPSESSID=4eh4vteg9hlkuivgs6n66iq932&topic=123901.0

**Comment by jsmithcarlsbad** [comment]
No This has been a problem from day 1 with Arduino Zero target and ArduinoIDE (now 1.6.9) and OS X (now running V 10.11.15). I have had multiple updates to the toolchain, IDE, and OS X - Uploading to Arduino Zero crashes OS X on a regular basis (at least 4 times tonight).... WFT? Can we get a stable version of OS X?
