### ISSUE TITLE
Incorporate Encoder library from Wiring. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#166]
This is [Issue 166](http://code.google.com/p/arduino/issues/detail?id=166) moved from a Google Code project.
Added by 2010-01-02T17:02:55.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

The addition of the Encoder library from Wiring.  It uses one interrupt pin and one other pin (so you 
can have two encoders on the ATmega328).

**Comment by cmaglie** [comment]
The library is now available through LIbrary Manager.

**Comment by PaulStoffregen** [comment]
does the name conflict with my Encoder library?  (which is much more commonly used with Arduino)

**Comment by cmaglie** [comment]
Hi Paul,
I meant that your library is in the library manager.

I was convinced that your library is a fork of Encoder from Wiring: if yes, then the issue is fixed, otherwise is a "wontfix".

**Comment by PaulStoffregen** [comment]
Oh, mine's definitely not a fork of Wiring's library!
