### ISSUE TITLE
Mac OS X 10.9 Java 1.7 only

### ISSUE THREAD

**Issue by dbsqp** [arduino/Arduino#1665]
Current Mac version of the IDE only work with Java 6 runtime from Apple. On a clean install with only Oracle 1.7 SDK installed IDE does not run and prompts to install Java 6 from Apple.

I think the issue does not relate to the core but to the way the application is bundled for Mac OS as Arduino.app. This uses the documented procedure from Apple and is only applicable to their install of Java 1.6.

See here for more info: http://stackoverflow.com/questions/14806709/application-is-using-java-6-from-apple-instead-of-java-7-from-oracle-on-mac-os-x

**Comment by chenyi1976** [comment]
I am using Yosemite with Java 7 (1.7.0_72), the Arduino IDEs (Java 6 & Java 7) are not working for me.

**If you have Minecraft.app installed like me, just copy contents/MacOS/JavaApplicationStub from Minecraft.app to Arduino.app contents/MacOS/ folder ( overwrite the existing one) . **

Cheers

**Comment by ffissore** [comment]
Yesterday we pushed a fix for mac. Can you give a spin to the latest
nightly build?
Il giorno 04/mar/2015 07.44, "chenyi1976" <notifications@github.com> ha
scritto:

**Comment by ffissore** [comment]
This is the URL http://arduino.cc/en/Main/Software#nightly

**Comment by ffissore** [comment]
@ddm fixed with "7+". sorry for having missed your advice
