### ISSUE TITLE
ArduinoToBreadboard

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#1672]
Original by Drew Langston:

At the top of http://arduino.cc/en/Tutorial/ArduinoToBreadboard, it states that only the Duemilanove can be used as an ISP and that the Uno cannot. I believe that this is incorrect. Switching the words "Uno" and "Duemilanove" in the bolded sentence should fix the issue. I could be wrong, however I just used my Uno as an ISP and the diagrams on that page even show an Uno being used.

**Comment by agdl** [comment]
I removed the sentence because actually it isn't correct
