### ISSUE TITLE
tone does not work below 31 Hz or at 0 Hz

### ISSUE THREAD

**Issue by Timmmm** [arduino/Arduino#1676]
See this bug: https://code.google.com/p/arduino/issues/detail?id=558

tone() has a lower limit of around 31 Hz. Anything less than that INCLUDING ZERO results in a 31 Hz tone.

IF THIS IS NOT FIXED THE DOCUMENTATION SHOULD BE!

By the way, why the hell is the documentation not a wiki? There are so many stupid errors and clarifications that it needs but is never going to get because only a few people can actually edit it...

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/558.
>Anything less than that INCLUDING ZERO results in a 31 Hz tone.

Actually I think this statement is not correct. It results in a higher frequency that 31 Hz.
