### ISSUE TITLE
File dialog looks ugly in Mac OS X

### ISSUE THREAD

**Issue by Lauszus** [arduino/Arduino#1681]
This commit: https://github.com/arduino/Arduino/commit/8bcf02ac3b5adaa503574246572923b0bc7de9e1 caused the file dialog in Mac OS X to look "ugly".

It looks like it uses a custom one instead of the native file dialog in Mac OS X.

I tried to reverse the commit and then it looked normal again.
See the two screenshots provided below:

This is the old file dialog:
![arduino_old](https://f.cloud.github.com/assets/1098847/1535920/a502195e-4caa-11e3-8883-f78659f1526e.png)

And this is the new one:
![arduino_new](https://f.cloud.github.com/assets/1098847/1535921/a505388c-4caa-11e3-8e55-fdab389cfdbe.png)

**Comment by ffissore** [comment]
Fixed with e327bb091afb7859b6aa26f1050181d8f7979bc3. Available since next nightly and in 1.6.1
