### ISSUE TITLE
I2C not standard (with SHT11 sensor)

### ISSUE THREAD

**Issue by Izanami** [arduino/Arduino#1703]
Hello,

In my project, i use SHT11 (not standard I2C) and orther I2C.

For SHT11, it connect to pins 20 and 21 (Arduino Mega 2560). It's work perfectly, but not when i use Wire.begin(). And i not use orther pins...

But it is impossible to temporarily disable Wire, when I get value of SHT.

Best regards

Code:

```C++
#include <Wire.h>
#include <SHT1x.h>

// Specify data and clock connections and instantiate SHT1x object
#define dataPin  12
#define clockPin 13
SHT1x sht1x(dataPin, clockPin);

void setup()
{
   Serial.begin(38400); // Open serial connection to report values to host
   Serial.println("Starting up");
}

void loop()
{
  Wire.begin();
  float temp_c;
  float temp_f;
  float humidity;

  // Read values from the sensor
  temp_c = sht1x.readTemperatureC();
  temp_f = sht1x.readTemperatureF();
  humidity = sht1x.readHumidity();

  // Print the values to the serial port
  Serial.print("Temperature: ");
  Serial.print(temp_c, DEC);
  Serial.print("C / ");
  Serial.print(temp_f, DEC);
  Serial.print("F. Humidity: ");
  Serial.print(humidity);
  Serial.println("%");

  delay(2000);
}
```

**Comment by sandeepmistry** [comment]
There is a new ```Wire.end()``` API introduced for AVR in(See #613 to track progress for all cores).

**Comment by sandeepmistry** [comment]
There is a new ```Wire.end()``` API introduced for AVR in #3724, that can be used to disable Wire. (See #613 to track progress for all cores).
