### ISSUE TITLE
IDE 1.0.5 does not allow users to update libraries from developers

### ISSUE THREAD

**Issue by drmpf** [arduino/Arduino#1704]
Once a library is installed the IDE V1.0.5 does not allow it to be installed again.
Request removing this check

It has been suggested a dialog be opened to alert user the library exists, but I am not sure what this achieves.  With no concept of library version nos what is the user expected to do other then alway say overwrite.

Also If touching this function, request that the link between zip name and library name be overridable.

For example if the zip has just a top level directory (or directories) then these should be installed as the libraries.  This allows the zip name to include a version number so users can tell which version of the library they are installing.

It also allows multiple libraries to be installed from one zip file.
.eg. 
pfodParserLib_V2.zip
contains just 
 -> pfodParser     (dir)
then install pfodParser  (dir) under libraries dir

pfodParserLib_V2.zip
contains just 
 -> pfodParser     (dir)
 -> pfodCmdParser     (dir)
then install pfodParser  (dir) and pfodCmdParser (dir) under libraries dir.
i.e. installs two libraries.

For backward compatability, if the top level of the zip file has any non-directory entries then use existing install process which uses the name of the zip as the library name.

**Comment by ffissore** [comment]
While I can't redesign nor change the mindset that brought us here, a couple of things happened in the meanwhile. 

@PaulStoffregen coded #2850 which notified users about a possible conflict. He also added smarter choice of the library (which basically says: if 2 libs have foo.h and one lib is called "foo", then pick foo.h from "foo")

We added lib manager, which allows you to quickly switch between library versions.

I think we can close this as "partially fixed"
