### ISSUE TITLE
Upload problems for medium_sized programs with the Arduino IDE 1.5.5 version ?

### ISSUE THREAD

**Issue by chrisbur99** [arduino/Arduino#1707]
Hello World, 

For months I used to check routinely all my Mega2560 R3 boards (and graphic boards, too) with the "UTFT 320x240 demo" from Henning Karlsen (binary  : about 39 Ko)

Under Windows 7 or Windows Vista, this "graphic test" program works fine with the 1.0.5 version of Arduino software, BUT under the 1.5.5 version if compilation is OK then  the upload don't works.

I tried smaller graphics test programs (binaries : about 10Ko) : upload is working well (only when my Windows machines found the USB port, but it's another problem).

Chrisbur99

**Comment by sandeepmistry** [comment]
Closing this for now, it's been a few years and more information has not been provided.
