### ISSUE TITLE
German reference page for shiftIn() and shiftOut() misleading

### ISSUE THREAD

**Issue by hase-berlin** [arduino/Arduino#1708]
The text on the reference page is misleading: the Beschreibung part describes a bitwise shift (basically the << or >> operator), not a software-SPI.

I suggest the following text to replace the page:
shiftIn()
Beschreibung
Liest seriell ein Byte (8 bit) ein, ähnlich einem SPI.
Verwendet werden 2 Pins: einer für die Daten. einer für den Takt.
Die Funktion legt für jedes Bit den Takt (clock) Pin auf High, liest den am Eingang liegenden Wert ein und legt den Takt-Pin wieder auf Low.
Der Parameter bitOrder legt dabei fest, in welcher Reihenfolge die Bits eingelesen werden: MSBFIRST bewirkt, dass das zuerst eingelesene Bit als höchstwertiges Bit verwendet wird. Bei LSBFIRST wird das zuerst eingelesene Bit zum niederwertigsten Bit des eingelesenen Byte.
Beachte: Dies ist eine Softwareimplementation; Arduino stellt außerdem eine SPI Bibliothek bereit, welche eine Hardwareimplementation bereitstellt, die schneller ist, aber nur auf bestimmten Pins funktioniert. 

shiftOut()
Beschreibung
Sendet seriell ein Byte (8 bit), ähnlich einem SPI.
Verwendet werden 2 Pins: einer für die Daten (dataPin). einer für den Takt (clockPin).
Die Funktion legt für jedes Bit den Takt (clock) Pin auf High, sendet ein Bit und legt den Takt-Pin wieder auf Low.
Der Parameter bitOrder legt dabei fest, in welcher Reihenfolge die Bits ausgegeben werden: MSBFIRST bewirkt, dass das zuerst das höchstwertiges Bit ausgesendet wird. Bei LSBFIRST wird das niederwertigsten Bit zuerst gesendet.
Beachte: Dies ist eine Softwareimplementation; Arduino stellt außerdem eine SPI Bibliothek bereit, welche eine Hardwareimplementation bereitstellt, die schneller ist, aber nur auf bestimmten Pins funktioniert.

**Comment by agdl** [comment]
I'm closing this. The only supported language is EN so please refer to the English documentation

**Comment by matthijskooijman** [comment]
Does that mean the non-english documentation should be removed, or at least get a warning? Where does this documentation live anyway? Couldn't find any language links on arduino.cc just now.

**Comment by agdl** [comment]
@matthijskooijman yes we are working on a warning in those pages. Also for the ES on

**Comment by hase-berlin** [comment]
Excellent solution, exemplary execution of Arduino Style!
Awe-inspiring.
Not only did it take over a year to have a look at the ticket, the "solution" ist to simply disregard whatever effort a member of the community makes to improve the system.
That is *exactly* how we know the Arduino maintainers to have executed the project in the past.
And I sse that is the way forward as well.

If you had had a simple look at the ticket, you would have seen that the immediate fix is IN THERE: a perfectly good documentation of shiftin() and shiftout() in precise, concise, short and to the point in perfect grammar and spelling.
Written by a native speaker of the german tongue.

Instead of brushing me off with a "use the english documentation" or "go stick your head in a pig" you might have simply accepted the solution given.

Thank you.
Lesson learned here, very well learned, indeed.

**Comment by hase-berlin** [comment]
Close accepted by ticket creator: perfect solution.
