### ISSUE TITLE
#define syntax highlichting in editor (low priority)

### ISSUE THREAD

**Issue by gizmocuz** [arduino/Arduino#1710]
Would be great is there was syntax highlighting for lines with:

"#define"
"#include"

While i'm here i would like to propose:

- Editor loads last open file
- Keeps the size of the editor the same as when you closed it

- option for single editor, (or maybe using tabs)

Thanks for this great editor!

Rob

**Comment by ffissore** [comment]
- Editor loads last open file
- Keeps the size of the editor the same as when you closed it
available in latest hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by gizmocuz** [comment]
Thanks!
