### ISSUE TITLE
Stream.parseInt() doc bug

### ISSUE THREAD

**Issue by fpoto** [arduino/Arduino#1713]
At http://arduino.cc/en/Reference/StreamParseInt I read:

Parameters

stream : an instance of a class that inherits from Stream.
list : the stream to check for ints (char) 

The correct description for list should be:

skipChar: this is an optional string containing format characters (typically commas) in values to be ignored

**Comment by matthijskooijman** [comment]
I've collected all parseInt issues in #2867, so I'm closing this one.
