### ISSUE TITLE
WiFi server uses only one socket

### ISSUE THREAD

**Issue by SurferTim** [arduino/Arduino#1715]
The wifi shield library apparently uses only one socket, and that one poorly. The function below displays the state of each of the 4 sockets, and the port number if a server.

The first number is the status of that socket. 
-1 = available
0 to 3 = used

The second is the port.

When I start the server and call this function, I get this
0  80
-1  0
-1  0
-1  0

After the first request from a client, I get this
-1  80
-1  0
-1  0
-1  0

That is indicating to me the server is not starting a second socket listening when a client connects on the first as does the ethernet shield.

Also note that socket 0 is now available after the first request. That seems like a bug to me.

I would expect this after the first client request
-1  0
1  80
-1  0
-1  0

I am getting wrong image downloads and corrupted images using the server library. I think this may be related to the use of only one socket.

Or am I seeing this incorrectly?

```
void ShowSockStatus() {
  for(int x = 0; x < MAX_SOCK_NUM; x++) {
    Serial.print(WiFi._state[x]);    
    Serial.print("  ");
    Serial.println(WiFi._server_port[x]);    
  }
}
```

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#6
