### ISSUE TITLE
Add support to UDP

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#1716]
nuff said :)

And report back to the forum at
 - http://forum.arduino.cc/index.php?topic=194562.0
 - http://forum.arduino.cc/index.php?topic=239166.0

**Comment by cmaglie** [comment]
Fixed in 71de447, it needs the python counterpart https://github.com/arduino/YunBridge/commit/d2f4d999fff154597d76354aca64ad738d5794e9
