### ISSUE TITLE
Library selection logic for #include <....>

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1725]
originally reported by @jantje:

*Arduino finds libraries based on .h names. It also prefers user installed libraries to arduino delivered libraries. So if you include the SPI library arduino will add the line #include if you create a folder called x containing a empty file SPI.h in your libraries folder the sketch will not compile.
This because arduino will find x/SPI.h and add x to the build and include path and not the SPI folder*

**Comment by ffissore** [comment]
How's the situation now? Various improvements have been implemented in library automagic selection
