### ISSUE TITLE
Arduino NANO v3.0 Hardware BUG

### ISSUE THREAD

**Issue by michalzahor** [arduino/Arduino#1729]
There is error in HW design. On FTDI chip, pin 26 [ TEST ] has to be connected to GND. Else on LINUX it will not be detected properly if arduino is connected via USB to host system before powering UP. One have to unplug and replug arduino to USB system.

**Comment by per1234** [comment]
I can see from the Nano v3.3 schematic available on its product page that the TEST pin is now connected to ground:
https://store.arduino.cc/arduino-nano
![Clipboard01](https://user-images.githubusercontent.com/8572152/96245908-bdc2cc00-0f5c-11eb-90d5-490385e7663f.png)
