### ISSUE TITLE
WiFi library getSocket function incorrect

### ISSUE THREAD

**Issue by SurferTim** [arduino/Arduino#1732]
The way the getSocket() function allocates sockets is incorrect. It uses the wrong array to determine availability. This will cause errors if using a client connection with any of the listening protocols (udp and tcp server). This is in WiFi.cpp.
IDE v1.0.5 and v1.5.5.
```
uint8_t WiFiClass::getSocket()
{
    for (uint8_t i = 0; i < MAX_SOCK_NUM; ++i)
    {
        if (WiFiClass::_server_port[i] == 0)
        {
             return i;
        }
    }
    return NO_SOCKET_AVAIL;
}
```

This is the function I currently use, and it works good. It uses the state array instead. This is the same variable array that the client socket allocation uses.
```
uint8_t WiFiClass::getSocket()
{
    for (uint8_t i = 0; i < MAX_SOCK_NUM; ++i)
    {
        if (WiFiClass::_state[i] == 0)
        {
             return i;
        }
    }
    return NO_SOCKET_AVAIL;
}
```

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#4
