### ISSUE TITLE
#define c bug in compilation

### ISSUE THREAD

**Issue by polettix** [arduino/Arduino#1735]
This simple program fails to compile in the 1.0.5 IDE:

    #define c 42
    void setup () {}
    void loop () {}

I saw that the problem is with the `c`, nothing wrong happens using another token like `d` or `life`. Additionally, compilation is fine if there is a statement before the define, like in the following:

    int a = 0;
    #define c 42
    void setup () {}
    void loop () {}

I got the error while trying to compile the first sketch in http://www.arduino.cc/en/Tutorial/PlayMelody

**Comment by ffissore** [comment]
Please checkout this thread [1] on devs mailing list and try one of the linked IDEs. It should fix the problems reported in this issue
[1] https://groups.google.com/a/arduino.cc/forum/#!topic/developers/4X2T3rCxXWM

**Comment by polettix** [comment]
I'll take a look and provide some feedback. Thanks for caring!

2015-01-21 11:04 GMT+01:00 Federico Fissore <notifications@github.com>:

**Comment by agdl** [comment]
@polettix are there any news about this?
