### ISSUE TITLE
IDE 1.0.5 Brace Matching in Comments

### ISSUE THREAD

**Issue by SolarDuck** [arduino/Arduino#1737]
The IDE brace matching feature also pays attention to braces in single line comments that begin with //.

My problem line was  something like:

  //    if   (......)  {

The compiler itself and the  "  Tools > Auto Format (Ctrl-T) " all work OK, it is just the
"brace highlighting" feature that finds the other half of a pair of braces when you
put the cursor after an opening brace { or after a  closing }.

**Comment by ffissore** [comment]
Fixed since 1.6.5 thank to a new editor
