### ISSUE TITLE
USBAPI issue

### ISSUE THREAD

**Issue by jelimoore** [arduino/Arduino#1743]
There is some weird issue when I compile some code using Software Serial and keyboard.h, and while I compile my code using a board as a Leonardo (which I have), I get a few issues, just to be on the bright side.

Arduino: 1.5.5 (Mac OS X), Board: "Arduino Leonardo"

Using library SoftwareSerial in folder: /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/libraries/SoftwareSerial (pre-1.5)

/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=155 -DARDUINO_AVR_LEONARDO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8036 -DUSB_MANUFACTURER= -DUSB_PRODUCT="Arduino Leonardo" -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/variants/leonardo -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/libraries/SoftwareSerial /var/folders/f7/2tmyxt0j57gbdqw5qvfvcr6h0000gn/T/build5868658158046891644.tmp/Project45.cpp -o /var/folders/f7/2tmyxt0j57gbdqw5qvfvcr6h0000gn/T/build5868658158046891644.tmp/Project45.cpp.o 
In file included from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.h:118,
                 from /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/Arduino.h:197,
                 from Project45.pde:11:
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/USBAPI.h:179: error: expected ',' or '...' before numeric constant

**Comment by Dorrel** [comment]
Several of the Boards (Micro and Leonardo for example) use the USBAPI.h file in the compiling process.  The USBAPI.h file fails when a constant is used in the sketch that is being compiled.  Change all of the constants (#define) in your sketch to a regular variables and the sketch should then compile.

**Comment by cmaglie** [comment]
@jelimoore 
this issue is really old so I'm closing it.
If your problem persist, feel free to reopen and provide more details.
