### ISSUE TITLE
Find operations should work across multiple tabs [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#175]
This is [Issue 175](http://code.google.com/p/arduino/issues/detail?id=175) moved from a Google Code project.
Added by 2010-01-08T03:52:14.000Z by [rick.bro...@gmail.com](http://code.google.com/u/106333784486395813202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open a files in the IDE in separate tabs
2. Edit-> Find a string

**What is the expected output? What do you see instead?**
Expect to see ALL instances of the string across tabs.  Only see instances 
in the current tab.

What version of the Arduino software are you using? 0017
On what operating system?  Windows XP
Which Arduino board are you using? many

**Please provide any additional information below.**
Would be nice to include an option to search current tab OR all tabs
This functionality should extend to find & replace as well

**Comment by ffissore** [comment]
Fixed with #2652

**Comment by ffissore** [comment]
Fix available with latest hourly build http://www.arduino.cc/en/Main/Software#hourly
