### ISSUE TITLE
Update files when we use an external editor

### ISSUE THREAD

**Issue by ParksProjets** [arduino/Arduino#1778]
The Arduino IDE have an option to be use with an external editor but files are not updated: to debug, we are obliged to close and re-open files.

**Comment by BrentWilkins** [comment]
I agree that it works.  If you make a change, the new version will be compiled.  As @ZENN0N said, it would be nice if it auto-refreshed, but I wouldn't necessarily call it an issue.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
