### ISSUE TITLE
Dropped bytes at serial inputs for up to 6.6ms after reading bytes via native USB

### ISSUE THREAD

**Issue by EmbedHA** [arduino/Arduino#1784]
On the Arduino DUE, using IDE 1.5.4, following issue was found.
For a time of up to ca. 6.6ms after a SerialUSB.readBytes statement, the reception of serial bytes is corrupted by randomly dropped bytes - mostly one byte, sometimes two. This was tested tested from 115200baud down to 28800baud for the serial input and for serial1 and serial2. 

An extensive description of a setup  to check the issue, sample code to demonstrate the problem, test logs etc. can be found in the Arduino forum: http://forum.arduino.cc/index.php?topic=207299.0

**Comment by odbol** [comment]
@EmbedHA do you have a link to that post? I am having the exact same problem: my Due sketch freezes if you unplug the USB. Didn't used to happen on 1.5.5.

**Comment by EmbedHA** [comment]
Hello,

I gave up on Arduino and use Atmel Studio now directly with ASF. By checking if there is a USB connection at all, and also the free size of the USB transmit buffer before writing into it, this can be avoided. Such functions are available under ASF. The problem occurs if you perform a write over USB but your data does not fit any more into the transmit buffer of the USB driver. Obviously, the USB driver waits then until some transmit over the interface has taken place, but if that does not occur it hangs.

Best Regards
Christian

Am 06.11.2015 um 00:14 schrieb Tyler Freeman <notifications@github.com>:

**Comment by odbol** [comment]
@EmbedHA that's exactly what I'm looking for. What functions are you using to checkout the USB connection? Do you have any ASF code you can point me to?

**Comment by EmbedHA** [comment]
To check for the connection, you need to have callback function. With ASF, this is specified in the conf_usb.h. I do not know if it is possible by some trick under Arduino to have this be considered during compilation. The function is called upon established connection. There is a corresponding callback for disconnection. This alone does not help, you have to check also the transmit buffer. The ASF function is udi_cdc_get_free_tx_buffer. There is good online documentation from Atmel for the ASF framework.

Am 06.11.2015 um 08:31 schrieb Tyler Freeman <notifications@github.com>:

**Comment by morganchristiansson** [comment]
I started using the Arduino compatible Teensy board which doesn't have this problem and has excellent USB performance for this project. https://www.pjrc.com/teensy/td_serial.html

Teensy also has better I/O and performance and memory.

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#25
