### ISSUE TITLE
Arduino crashes on verify / compile, leaving avr-ar running. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#179]
This is [Issue 179](http://code.google.com/p/arduino/issues/detail?id=179) moved from a Google Code project.
Added by 2010-01-09T23:04:46.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, OpSys-Windows, Component-IDE

### Original description

From http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1262131379 "The program opens, will 
open the example sketches, will save, but will not verify or compile a sketch.  When these options 
are tried the program closes and I get multiple instances of avr-ar processes running in my task 
manager.  There are no error codes anywhere that I can see.  Windows XP SP3, Java 6 u.17 freshly 
installed, Java folder in Arduino files renamed.

**Comment by ffissore** [comment]
This is just too old to be reproduces or verified
