### ISSUE TITLE
Upload using usbasp programmer looks for a valid serial port

### ISSUE THREAD

**Issue by Lauszus** [arduino/Arduino#1791]
When trying to upload using a usbasp programmer directly you need to select a valid serial port as well, but this should not be needed as `-Pusb` is passed to avrdude.

For instance I get the following error message:

```
Board at /dev/tty.usbserial-AH00S1Pl is not available
```

A workaround is just to plug in some serial device - like a FT232 adapter and then select that serial port. After that I am able to upload using the usbasp.

It only seems like the "Upload Using Programmer" option is affected, since I am able to upload the bootloader without this workaround.

**Comment by cjdg** [comment]
Is not working on latest arduino

**Comment by sixtyfive** [comment]
Just downloaded the nightly and I'm still getting

```
An error occurred while uploading the sketch
avrdude: ser_open(): can't open device "COM1": No such file or directory
```

despite there being no way of changing the port setting. What am I doing wrong?

**Comment by sixtyfive** [comment]
Oh, nevermind, figured it out. For all you other unlucky googlers: you need to do `Ctrl-Shift-U` instead of `Ctrl-U` when using an USBASP.

**Comment by bcarteruk** [comment]
Thanks sixtyfive - spent a while goggling this problem before running across your post - works for me just using Cmd-Shift-U on a Mac.
