### ISSUE TITLE
String.toFloat() returns 0.00 if not a number

### ISSUE THREAD

**Issue by hobbex** [arduino/Arduino#1796]
.toFloat() returns 0.00 if not a Number.

For example
String str = "-------";
str.toFloat()  -> gives "0.000"

it should return something else, like "not valid", "NAN" or similiar.

**Comment by ScruffR** [comment]
No reason was given for the closure but alternative solutions may be worth considering.

e.g.
However if breaking existing code has to be avoided at all cost, how about adding an optional bool* success or even double* retValOrNAN?

**Comment by cousteaulecommandant** [comment]
A reason I could see for this being closed is that NAN is hard to document for inexperienced programmers; it's easier to just say *"on error, it returns 0"* than *"on error, it returns Not A Number (NAN), which is a special float value in C/C++ that blah blah blah..."*.  But I don't think it's a good enough reason; personally I think it would make more sense to return NAN as proposed, then at least there would be a way to properly check for errors (using the `isnan()` function).

**Comment by kubark42** [comment]
I'll strongly echo that `.toFloat()` should return something other than `0` on failure. I think the argument has been made pretty well above, so there's not much to add. I think that the 2014 comments probably captured the prevailing misunderstanding back then, but there are several good suggestions since then. 

Could the project owners maybe re-open this bug?

**Comment by keithlowc** [comment]
Hey I am also having this error somehow when I utilize this .toFloat() option is returning either 0 or nothing. A bit of background is that I am making a get to an api and returning a string value (a number as string) and i want to convert it back to float. But, everything breaks once I use the toFloat() func.. any ideas?
