### ISSUE TITLE
different behaviour between the toolbar and the menu when creating new file

### ISSUE THREAD

**Issue by dcuartielles** [arduino/Arduino#1805]
create a new file, add some text to it and then:

1) hit the "new file" button on the toolbar, it will prompt you whether you want to save the file, because the command will erase the contents

2) click cancel on the dialog-window and then

3) go to the File -> New menu

As you will see the behaviour is different, when using the menus, "new" is creating a new window without asking anything and doesn't erase the current editor's content

**Comment by ffissore** [comment]
Fixed with #2723
