### ISSUE TITLE
Assembly files not working with newer gcc, -assembler-with-cpp option does not exist?

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#1807]

**Comment by b-rohit** [comment]
I compiled a arduino mavlink sketch from [https://github.com/alaney/arduino-mavlink](url) in 1.8.1 and 1.8.2. and i got the same error. 

Arduino: 1.8.2 (Windows 10), Board: "Arduino/Genuino Uno"

In file included from E:\Dw\arduino-mavlink-master\ArduinoMAVLink\ArduinoMAVLink.ino:2:0:

C:\Users\Rohit\Downloads\arduino-PR-5863-BUILD-637-windows\arduino-PR-5863-BUILD-637\libraries\FastSerial/FastSerial.h:47:3: error: #error Must include FastSerial.h before the Arduino serial driver is defined.

 # error Must include FastSerial.h before the Arduino serial driver is defined.
   ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by matthijskooijman** [comment]
@b-rohit, huh? This does not seem to be related to this particular issue either. Are you having trouble creating a new issue, or?
