### ISSUE TITLE
ArduinoISP can not work "as is" with Leonardo

### ISSUE THREAD

**Issue by koocotte** [arduino/Arduino#1815]
The ArduinoISP use SS, MOSI, MISO and CLK to work; but on Arduino Leonardo, thoses pins are not at the same place than on the Arduino Uno.

- The ArduinoISP sketch does not say anything about that, it should be corrected (by saying that it can not work with Leonardo, or by explaining how to do).

- Page on http://arduino.cc/en/Tutorial/ArduinoISP does not say anything neither about Leonardo.

ArduinoISP does work if you define RESET as 10 instead of SS and connect MOSI, MISO and CLK on the right pins on the ICSP connector.

**Comment by agdl** [comment]
I modified the page in order to talk about boards like leonardo
