### ISSUE TITLE
Modify the font police to make difference between O and 0

### ISSUE THREAD

**Issue by bertrand59** [arduino/Arduino#1817]
can you change the font in the IDE to be able to distinguish the "O" (letter O) for 0 (null) ?

**Comment by ffissore** [comment]
@bertrand59 the font used by the IDE is what your Windows/Mac/Linux has associated with "Monospace" font. You can change the actual font using your OS font manager. If your OS doesn't provide one, you can tweak the actual font face editing your `preferences.txt` file, located in `%APPDATA%\Arduino15` or `~/Library/Arduino15` or `~/.arduino15`

**Comment by Chris--A** [comment]
This is handy to know. I might try a few different ones now. I thought I'd have to edit the preferences for each IDE version I'm using & testing.
