### ISSUE TITLE
listComPorts.exe - Type mismatch 80020005

### ISSUE THREAD

**Issue by pfruh** [arduino/Arduino#1818]
I'm having strange COM port disappearing / serial problems with the Arduino 1.5.5-R2 IDE,
while searching for the issue, I manually ran listComPorts.exe and got this error.
#1573 should have already fixed this, but it still seems broken.

It _seems_ to be caused by

``` C
dhGetValue(L"%s", &name,  objDevice, L".Name");
```

![2014-01-22 16_58_32-](https://f.cloud.github.com/assets/809734/1975520/11fe9fc8-837e-11e3-87e5-3b0bd6d067ed.png)

**Comment by dotKokott** [comment]
Just in case this helps anybody else:
I ran into the same problem & created a C# executable of listComPorts + some info on how to get this information without an extra executable: https://github.com/dotKokott/listComPorts-csharp
