### ISSUE TITLE
Arduino forum website inconsistent

### ISSUE THREAD

**Issue by syntotic** [arduino/Arduino#1830]
Cannot reach any page after being logged in, a blank page downloads; any other webiste address returns with a session cookie and stalls in a blank page. After finding the logout option, Login and sign up confused. The profile is simultaneously open and not recognized, reaching the forum page gives a refused connection. Has been like this since the last three months? Since I got this stuff and it kind of stopped workin' within three days of using it because... can it be totally erased and filled up or does it accumulate sketches til full or...?

**Comment by agdl** [comment]
Fixed!

**Comment by syntotic** [comment]
Allora era dal bug? Avevo dimenticato, ho acquisto appena il nano e
non ho visto il sito da quando ho trovato il  bug. Sicuri non era
cualcun **agente** facendo la cosa sua?

On 1/12/15, Arturo Guadalupi <notifications@github.com> wrote:
> Fixed!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/arduino/Arduino/issues/1830#issuecomment-69596459


-- 
Danilo J Bonsignore
