### ISSUE TITLE
bridge.cpp should not use string.

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#1831]
Currently the bridge library relies on the String class for put command. I think that including String only for put is a bit expensive. The author probably agrees with this as the code has following comment
> // TODO: do it in a more efficient way

I think extending transfer to another data set and this (untested) code would be far better

void BridgeClass::put(const char *key, const char *value) {
  transfer("D",1,key,strlen(key),"\xFE",1,value,strlen(value));
}
Best regards
Jantje

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Bridge#11
