### ISSUE TITLE
runShellCommandAsynchronously and runAsynchronously will not run properly when caled one after another

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#1832]
The idea of a asynchronous call may make the library user think he can do 2 calls at the same time with the same instance of process.
In fact before you can call runAsynchronously you need to call begin and runShellCommandAsynchronously calls begin itself.
Begin calls close which sends a w to linino with the handle. I assume this terminates the running process.

In other words you can not run 2 processes at linino at the same time with the same Process instance. 
This can be seen as a "desired" or a "bug"
If this behaviour is desired please document this behaviour at http://arduino.cc/en/Reference/YunProcessRunAsynchronously and http://arduino.cc/en/Reference/YunProcessRunShellCommandAsynchronously

If it is a bug: Please consider to remove handle from the class and in stead return the handle from the Asynchronous methods. The close and running methods will need a handle as parameter.

Best regards
Jantje

**Comment by agdl** [comment]
@jan-r I added this statement:

*Please note that since 'Process.begin(). calls close'' which sends a w to the linux processor, the running process is terminated. This is the reason why you can not run 2 processes the same time with the same Process instance.*

If it is ok for you close this issue please. Let me know.

**Comment by jantje** [comment]
fine for me

**Comment by cmaglie** [comment]
The sentence "which sends a w to the linux processor" is really an implementation detail and must be kept out of the documentation.

**Comment by jantje** [comment]
so is "'Process.begin(). calls close''"
Which leaves you with 
You can not run 2 processes the same time.

**Comment by agdl** [comment]
take a look now

**Comment by jantje** [comment]
fine for me
