### ISSUE TITLE
WifiShield R3 doesn't work with IDE 1.0.5, 1.0.3

### ISSUE THREAD

**Issue by ldgarcia** [arduino/Arduino#1840]
Currently using an Arduino UNO R3 with a WiFi Shield R3. 
Tried all the tutorial code regarding the WiFi shield, and nothing worked.
Finally, I found a "fix" in the Arduino forums: use IDE 1.0.2

> OK, is your Arduino IDE version 1.0.5? If it is, I recommend you download 1.0.2 to give it a try. 1.0.5 has library only working well with the "latest" firmware. Your R3 wifi shield has an unknown version firmware (unfortunately I have not found the version of firmware for an original R3. This version is the most stable from my own arduino server tests. Please don't upgrade firmware and try arduino ide 1.0.2

Source: http://forum.arduino.cc/index.php/topic,167794.0.html

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#26
