### ISSUE TITLE
Arduino projects book: Wood sheet confusion on page 13

### ISSUE THREAD

**Issue by Brawle** [arduino/Arduino#1845]
On page 13, step 3, an obvious visual mistake was made and has resulted in my own mistake of breaking some wood legs.

Step 3 requires you place the wood legs into the corners of the wood platform. It does not state whether or not it is the backside or the front. On that note, no where does it signify WHICH SIDE is the front or back. All we have to work by is assuming that the side with the markings is the front.

This is the next tricky part. In step 3, the visual model shown, the holes on the wood sheet should be mirrored to signify that the sheet has been "turned over." The designs were left out, which was the first indication that the legs went on the side with NO designs. However, because the punched holes were still identical to all other figures, it led me to believe that the designer of the project book maybe had just skipped adding the designs and used the punched hole orientation to signify which side to use.

This problem could of been easily remedied by mirroring the punched holes on the wood sheet in step 3 while also not showing the designs that the top side was supposed to reveal.

**Comment by GustavoGhelfi** [comment]
I have detected 3 other mistakes in the manual.

1) The language of the book must be the country language, as the UE consumer laws says. Ex.: If you want to sell a product in Spain, the manual must be printed in spanish, not english or italian.

2) The Arduino board has 4 holes to fix it to the wood base, so you'll need 4 screws not 3 as book indicates. This screws are NOT included in the kit.

3) The image that indicates how to mount de Breadboard does not indicate the orientation of the text printed on the board, so you could mount it in an incorrect way.

**Comment by GustavoGhelfi** [comment]
I have just discovered why the screws are no in the kit.

The holes in the Arduino board are 3mm diameter, but the holes in the wood base are bigger (4mm diameter), so you can't never fix it in the way the manual shows.

Also, the board has 4 holes, but the wood base only 3.

The worst of the topic "italian style".

**Comment by agdl** [comment]
@Brawle The screws are included in the component package if in your there aren't there was an error and you can write to support@arduino.cc to report this and also to ask for a replacement wood base.

The image is actually wrong and it will be updated in a new release of the book thank you for the hint.

@GustavoGhelfi  the same as stated above for the screws. 

The boards have 4 holes right, but only 3 of them are usable because of the improvement in the Arduino footprint adding the two extra pins SCL & SDA and the wood base is designed according to this.

**Comment by agdl** [comment]
However this isn't a properly issue because git is intended for software related issue so i'm closing this. Please if you have others hint & suggestion or problems please refer to our support
