### ISSUE TITLE
Ethernet Web Client Repeating example improvement

### ISSUE THREAD

**Issue by ZakkDiaz** [arduino/Arduino#1848]
It's not much but I found that for a project I'm working on, I need to send packets as soon as I can in unpredictable time intervals. The current example found at http://arduino.cc/en/Tutorial/WebClientRepeating waits one minute between intervals. An unnoticed side effect of this is that the client drops the connection before the next packet is able to be sent so you don't notice any interruption. However, if you want to decrease the time interval to 5 seconds, you notice that there is a long delay before it attempts to send a new packet because the client still has a hold of the connection for a period of time.

My solution is a little hacky but works pretty well. It's simply a global boolean flag that gets toggled at the end of a while loop that receives the client response. In the main loop, when that boolean flag is toggled, call client.stop(); and this will free up the connection for the next packet. This has been pretty reliable for me I've been testing it for a few hours without any missed pickets or data.

Is there something I'm missing as to why I wouldn't do it this way?

```

//This example was copied almost directly from the link above.
//I have modified some areas and added small functionality for my own use. 
#include <SPI.h>
#include <Ethernet.h>

byte mac[] = { 
  0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED};

boolean received = false;
EthernetClient client;

char server[] = "*SERVER*"; 
unsigned long lastConnectionTime = 0;
boolean lastConnected = false;
const unsigned long postingInterval = 5000;  // delay between updates, in milliseconds

void setup() {
  randomSeed(analogRead(0));
  Serial.begin(9600);
  delay(1000);
  Ethernet.begin(mac);
}

void loop() {
  while (client.available()) {
    char c = client.read();
    Serial.print(c);
    received = true;
  }
 if(received)
 {
        client.stop();
        received = false;
 }

  if (!client.connected() && lastConnected) {
    Serial.println();
    Serial.println("disconnecting.");
    client.stop();
  }

  if(!client.connected() && (millis() - lastConnectionTime > postingInterval)) {
    int i = random(10000);
    String reading = "1:" + String(i);
    httpRequest(reading);
  }
  lastConnected = client.connected();
}

void httpRequest(String val) {
  if (client.connect(server, 80)) {
    Serial.println("connecting...");
    Serial.println("Sending " + val);
    client.println("GET /*URL*?dataStream=" + (val) + " HTTP/1.1");
    client.println("Host: *HOST*");
    client.println("Connection: keep-open");
    client.println();
    lastConnectionTime = millis();
  } 
  else {
    Serial.println("connection failed");
    Serial.println("disconnecting.");
    client.stop();
  }
}
```

**Comment by agdl** [comment]
@ZakkDiaz You can make post a PR for this if you want because is the better way to give visibility to an improvement and generate a discussion about pro and cons. So I'm closing this issue (that has been buried for so long) and you can make a PR if you wish
