### ISSUE TITLE
Arduino Robot: Board files are missing

### ISSUE THREAD

**Issue by dischoen** [arduino/Arduino#1852]
in http://arduino.cc/en/uploads/Main/arduino-robot-reference-design_3b1.zip, there are only .sch files, no board layouts.

**Comment by agdl** [comment]
@dischoen updated thank you! We don't provide the BOM but you can easily generate it

**Comment by dischoen** [comment]
hi,

do you refer only to the BOM issue for closing this issue?
on the web page there still is the 3b1 zip file without layout files.

**Comment by agdl** [comment]
@dischoen i updated the whole archive try again i see the correct one

**Comment by dischoen** [comment]
now i see it too. the old version probably was still in a cache on the way.
thank you!
