### ISSUE TITLE
Error in IDE when Two Finger Scrolling

### ISSUE THREAD

**Issue by dalgibbard** [arduino/Arduino#1854]
Hello!
I've noticed in the Arduino IDE (1.5.5 beta is what i'm current using), on Ubuntu 13.10 64bit, on my Lenovo Ideapad Y410p, that when two finger scrolling through code it works fine until you reach the start/end, and then prints:

```
MEvent. CASE!
```

This appears both on the terminal session in which I launched the IDE, and also the built-in IDE console.

In addition to this, when reaching the top/bottom of the page and attempting to scroll further, the "Two-Finger-Double-Tap" menu flickers on/off the screen- as though the scrolling action is being read as multiple very quick presses rather than a dragging action. Bringing this menu up normally (with just a double two-finger tap) works fine, and doesn't generate the error.

Please let me know if you need any further details.

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen it if needed!
