### ISSUE TITLE
Wire library generates warning using pragma

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#1864]
Hi
I have a sketch that gives weird problems. Basically sometimes the processor doesn't even get to setup(). That means something is going wrong in the constructors or init.
When investigating I found these warnings

> Description   Resource   Path   Location   Type
> # warning Timer 2 not finished (may not be present on this CPU)   wiring.c   /batterijlader/arduino/core   line 265   C/C++ Problem
> # warning Timer 2 not finished (may not be present on this CPU)   wiring.c   /batterijlader/arduino/core   line 274   C/C++ Problem

Looking at the code that gives

> void init()
> {
> .....
> // set timer 2 prescale factor to 64
> # if defined(TCCR2) && defined(CS22)
> 
> ```
> sbi(TCCR2, CS22);
> ```
> # elif defined(TCCR2B) && defined(CS22)
> 
> ```
> sbi(TCCR2B, CS22);
> ```
> # else
> 
> ```
> #warning Timer 2 not finished (may not be present on this CPU)
> ```
> # endif
> 
>   // configure timer 2 for phase correct pwm (8-bit)
> # if defined(TCCR2) && defined(WGM20)
> 
> ```
> sbi(TCCR2, WGM20);
> ```
> # elif defined(TCCR2A) && defined(WGM20)
> 
> ```
> sbi(TCCR2A, WGM20);
> ```
> # else
> 
> ```
> #warning Timer 2 not finished (may not be present on this CPU)
> ```
> # endif
> 
> ....
> }

Is this a potential problem of just a "cosmetic" issue

Best regards
Jantje

**Comment by kautzz** [comment]
just ran across the same problem and you are right that something is missing... 
there is no timer/counter 2 on the 32u4 (yun, leonardo)

only timer 0, 1, 3 and 4 
(http://www.atmel.com/images/atmel-7766-8-bit-avr-atmega16u4-32u4_summary.pdf)

IMAO the warning sounds a bit drastic but as long as you don't use any libs that use timer 2, your code should run fine

**Comment by per1234** [comment]
These warnings were commented out in https://github.com/arduino/ArduinoCore-avr/commit/5ab6edb114eb8b0fb51939669aae2980309602fd.
