### ISSUE TITLE
USB related warnings on SAM / Due

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#1874]
I'm preparing a pullrequest to fix various warnings in both the AVR and SAM cores. However, there are few warnings in SAM that I'm not sure how to fix, since I'm not very familiar with that code. In case anyone has suggestions, here's the warnings:

	sam/cores/arduino/USB/HID.cpp:148: warning: unused parameter 'i'
	sam/cores/arduino/USB/USBCore.cpp:72: warning: "USB_MANUFACTURER" redefined
	<command-line>:0: note: this is the location of the previous definition
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::idProduct'
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::deviceVersion'
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::iManufacturer'
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::iProduct'
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::iSerialNumber'
	sam/cores/arduino/USB/USBCore.cpp:94: warning: missing initializer for member 'DeviceDescriptor::bNumConfigurations'
	sam/cores/arduino/USB/USBCore.cpp:122: warning: unused parameter 'ep'
	sam/cores/arduino/USB/USBCore.cpp:221: warning: unused parameter 'flags'

Possibly some of these are actual bugs, so I don't want to apply some kludge workaround without actually understanding the code.

**Comment by sandeepmistry** [comment]
I just tried build a sketch for the Due, and am no longer seeing these warnings.
