### ISSUE TITLE
Arduino Yun - No possibility to detect if power is supplied via micro USB port

### ISSUE THREAD

**Issue by CaMeLCaseError** [arduino/Arduino#1875]
This is more a feature request for battery powered operation (battery powered is something that should be considered useful in a "wireless" device like the arduino yun in my opinion)

Here's my problem: In battery powered devices it is often necessary to detect where power is coming from, for example to turn charging on / off while being connected to a pc or a charger and disabling the charger when no external power is present.

- It is (at leat theoretically) _possible_ to detect a connected usb-cable to a computer, utilizing the usb data lines, watching traffic (kind of a ugly hack but could work).
- It is _impossible_ to detect a simple 5V charger over the usb port. In the current design of the yun the 5V from a computer's usb port is running through a diode first, then directly connected to the 5V net of the entire arduino board. I would propose a change in the board design that has an additional line coming from the micro usb jack's 5V line to a microcontroller pin or at least a signalling mechanism for "power" on the usb port.

~~The same also applies for all other arduino boards~~ Other Arduino boards like the Leonardo or the Uno Rev. 3 have the 5V supply from USB directly connected to the VUSB Pin on the atmega32u4 or the atmega16u4.

Why is it impotant to know?
- if a dc converter is used to power the device it can be shut down while power over usb is present - saves battery.
- if a charging mechanism is used the arduino's 5V net can be used for charging when there is external power (like in any cellphone)

my current workaround is to have a separate micro usb jack for charging (but without usb connectivity) or alternatively a flex cable that has some additional electronics on it for voltage detection, forwarding the usb data lines to the micro usb port of the yun... but that's expensive and ugly too...

**Comment by sandeepmistry** [comment]
Closing as there is a forum post to continue the discussion.
