### ISSUE TITLE
IDE Background and print color options needed

### ISSUE THREAD

**Issue by martib** [arduino/Arduino#1878]
I have failing eyesight and when loading my code I can read White on Black Background OK, but have no idea what is written on error/debug screen in Red on Black Background.
Can I change some code to add an option, and how do I do it?
Thanks

**Comment by nxg** [comment]
+1 to making this a lot easier to find – I can't find any documentation on this other than this issue.

1. Note that the `theme.txt` is _not_ alongside the `preferences.txt` file, which is where I first looked for it, but alongside/beneath the Arduino jar files (thus on OS X, for example, in `.../Arduino-1.6.3.app/Contents/Java/lib/theme/theme.txt`).  It might be useful to make these theme files specifiable in the same location as the preferences file.

2. Dark orange on black is (if I may be blunt) a _terrible_ default colour scheme for error messages.  Nothing wrong with selecting it if that's what you like, but please not as a default.

**Comment by greenonline** [comment]
I can only presume that the person who selected the dark orange on a black background is either blind or thinks that tartan trousers are fashionable.

**Comment by seagift** [comment]
Wow Excellent. Thank you all. Easy to find the file to edit. Not so easy to save the file . Access denied. I got there. Now I can read the Errors I am making in my code. Cant thank you enough.

**Comment by ffissore** [comment]
Closing. Theme editor won't be included

**Comment by mweissen** [comment]
Or please add a second theme.txt file with better colors! Red on black is dreadful!
