### ISSUE TITLE
Wrong/misleading interface

### ISSUE THREAD

**Issue by ssakar** [arduino/Arduino#1881]
In Stream.h of the Arduino core library Stream::find(char *target) is declared as:

bool find(char *target);   // reads data from the stream until the target string is found

But if you look at the definition it only compares the first character of the string:

bool Stream::find(char *target)
{
  return findUntil(target, NULL);
}

That is very misleading and I have even seen wrong usage in the Arduino Cookbook (client.find("\r\n")). Either the interface should only expect a single character or the definition should use strlen instead of NULL.

**Comment by Chris--A** [comment]
FIxed with: https://github.com/arduino/Arduino/commit/f43a7a698ee04900772b116d896462b46cdb7926
