### ISSUE TITLE
mac osx 10.5.8 doesnt recognize enviroment

### ISSUE THREAD

**Issue by yesitshamilton** [arduino/Arduino#1897]
ive downloaded different builds, 1.05 and 1.03 and neither work, also tried using different unzip programs because i read on a board that it solved the issue for some people, and it still doesnt work, im not a computer programmer, im new to arduino and this is proving to be frustrating, can anybody help??

**Comment by ffissore** [comment]
Can you try "macosx-new" version from https://github.com/arduino/Arduino/pull/2590#issuecomment-72337128 ?

**Comment by ffissore** [comment]
Closing for lack of feedback. Please reopen if you are still having problems running the IDE
