### ISSUE TITLE
Duplicate IRremote

### ISSUE THREAD

**Issue by mpflaga** [arduino/Arduino#1909]
The way in which \libraries\RobotIRremote\src\IRremote was added, causes this library to take precedence, in conflict with those who have been using the alternate forks in their .\Arduino\libraries\IRremote\. folders. 

This locking in of this library seams contrary to the goals of allowing customizable libraries. I understand the goal of using it within the Robot Project to ensure support, but this inadvertently over rides all of the other forks of IRremote.

For example I see the SD library is an older instance of SdFatLib, but was implemented in the stock library with a unique Name and such, as not to conflict with more current and or other forks of SdFatLib. 

Is there a way to politely select the users libraries as the preferred when present, other than deleting the src directory (not altering the IDE's stock environment). Or should some additional effort be used to ensure functional co-existence. As not to jack the library and others ability to use their prior versions of the library on stock IDE.

There will be a lot of newbies who won't understand why this long lasting proven library stopped working.

**Comment by ffissore** [comment]
This has been fixed by #2681
