### ISSUE TITLE
RX and TX Buffers for HardwareSerial are hard coded in size and equal length

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#1929]
Hi
I have many arduino sketches that send out lots of data and hardly receives any data.
I really would like to increase the TX buffer but not the RX buffer. Therefore I would like to modify the HardwareSerial class where it states:

```
#if (RAMEND < 1000)
  #define SERIAL_BUFFER_SIZE 16
#else
#if ARDUINO_AVR_MEGA2560
#define SERIAL_BUFFER_SIZE 64
#else
  #define SERIAL_BUFFER_SIZE 64
#endif
#endif
```

to 

```
#if !(defined(SERIAL_TX_BUFFER_SIZE)&&defined(SERIAL_RX_BUFFER_SIZE))
#if (RAMEND < 1000)
#define SERIAL_TX_BUFFER_SIZE 16 
#define SERIAL_RX_BUFFER_SIZE 16 
#else
#if ARDUINO_AVR_MEGA2560
#define SERIAL_TX_BUFFER_SIZE 64 
#define SERIAL_RX_BUFFER_SIZE 64 
#else
#define SERIAL_TX_BUFFER_SIZE 64 
#define SERIAL_RX_BUFFER_SIZE 64 
#endif
#endif
```

this allows to change the size by using a define and allows for different sizes for RX and TX buffer.
and make all subsequent changes.
Would a change like this be accepted?
jantje

**Comment by mrts** [comment]
@jantje But how do you actually use it with Arduino IDE? Would 
```c++
#define SERIAL_TX_BUFFER_SIZE 32
#include <Arduino.h>
```

at the top of a `.ino` file work (I doubt as AFAIK `Arduino.h` is implicitly included)?

**Comment by matthijskooijman** [comment]
@mrts, that won't work, since those defines will not be in effect when HardwareSerial0.cpp, which defines the actual buffers, is compiled. I think the way to do this right now, is to modify HardwareSerial.h.

**Comment by mrts** [comment]
@jantje, right, that's what I expected. Thanks for clarifying!

**Comment by jantje** [comment]
you can also modify platform.txt or boards.txt
It may be a good idea to make a "big buffer" board.

**Comment by mrts** [comment]
Thanks for the tip!

**Comment by PaulStoffregen** [comment]
You can also create a menu using boards.txt, with each option in the menu passing different -Dxyz flags to the compiler.

**Comment by shine0212** [comment]
How i can change buffer of arduino due?
