### ISSUE TITLE
Bug: splitting define causes java regex error and arduino won't compile

### ISSUE THREAD

**Issue by nothinman** [arduino/Arduino#1935]
This doesn't compile:

#define SERIAL_BANNER "\
1) Scan for sensors\n\
2) Change sensor I2C address\n\
3) Show readings for all sensors\n\
"

It causes this:
Exception in thread "Thread-6" java.lang.StackOverflowError
	at java.util.regex.Pattern$Branch.match(Pattern.java:4114)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4168)
[..]

Changing it to:
#define SERIAL_BANNER "1) Scan for sensors\n2) Change sensor I2C address\n3) Show readings for all sensors\n"

makes it work...

Marcin

**Comment by agdl** [comment]
Waiting for feedback from too long. Reopen it if needed!

**Comment by peabo7** [comment]
Although this is a pre-pre-processor problem, it is also deprecated C++ syntax.  The recommended way to write this is:

#define SERIAL_BANNER \
    "1) Scan for sensors\n" \
    "2) Change sensor I2C address\n" \
    "3) Show readings for all sensors\n"

This takes advantage of the fact that in modern C/C++ compilers, successive string literals are concatenated as if they had been written as a single literal.

Peter Olson

**Comment by ffissore** [comment]
Please give a try to the IDEs linked at the bottom of this email on the dev list
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/4X2T3rCxXWM/YNJl6PZuDucJ
We're testing a new preprocessor and it compiles your sketch just fine.

**Comment by peabo7** [comment]
(I'm not the original poster.)

Tested this fix, it works.

Peter Olson

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by Chris--A** [comment]
Using the source for 1.6.5, this does not cause an error.

**Comment by cmaglie** [comment]
I confirm that this has been fixed on the latest release. Please reopen if needed.
