### ISSUE TITLE
Pro Mini board page lists only 168, is missing 328 variants

### ISSUE THREAD

**Issue by gsreeves** [arduino/Arduino#1939]
The page http://arduino.cc/en/Main/ArduinoBoardProMini only lists the 168-based Pro Mini, skipping the 328-based variants.
Sparkfun still offers a 3.3V 8MHz Pro Mini here: https://www.sparkfun.com/products/11114
and a 5V 16MHz version here: https://www.sparkfun.com/products/11113

**Comment by agdl** [comment]
updated according to new release
