### ISSUE TITLE
ServerBegin example error

### ISSUE THREAD

**Issue by mixage** [arduino/Arduino#1943]
http://arduino.cc/en/Reference/ServerBegin

Ethernet.begin(mac, ip, gateway, subnet);
should be
Ethernet.begin(mac, ip, DNS, gateway, subnet);

**Comment by agdl** [comment]
@mixage as you can see here 
https://github.com/arduino/Arduino/blob/master/libraries/Ethernet/src/Ethernet.cpp
line 50. The used initialization works too vene without DNS

**Comment by mixage** [comment]
You're right, thanks :-)
