### ISSUE TITLE
WiFiUdpSendReceiveString password variable missing from connection.

### ISSUE THREAD

**Issue by sebthepleb** [arduino/Arduino#1946]
There is an issue with the WiFiUdpSendReceiveString example code. 

All the example WiFi codes I have looked at use the following line to connect:

// Connect to WPA/WPA2 network. Change this line if using open or WEP network:
status = WiFi.begin(ssid, pass);

Now, with the WiFiUdpSendReceiveString example code, it seems the intention was similar, but the password variable has been missed.

// Connect to WPA/WPA2 network. Change this line if using open or WEP network:
status = WiFi.begin(ssid);

I believe that this code needs to be changed to include the password variable, or the comment needs to be changed to explain that the connection is for an open network.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#25
