### ISSUE TITLE
Save Dialog Text Field: Select All, Copy, Paste, Undo not working

### ISSUE THREAD

**Issue by NateD4** [arduino/Arduino#1949]
When in the save dialog text entry box (for file name) the typical behavior is to allow either right click access to select all, copy, paste, undo or to allow key commands: CTRL/Apple + A, CTRL/Apple + C, CTRL/Apple + V, CTRL/Apple + Z. This also applies to the Apple key on OS X. When using these currently they act on the open Arduino code file. So when using CTRL/Apple + V to paste text in the file name it ends up on the code rather than the Save dialog window.

**Comment by ffissore** [comment]
Is this issue still valid with IDE 1.6.4 or latest hourly? http://www.arduino.cc/en/Main/Software#hourly
