### ISSUE TITLE
Ctrl-Tab to switch between files [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#195]
This is [Issue 195](http://code.google.com/p/arduino/issues/detail?id=195) moved from a Google Code project.
Added by 2010-01-30T13:46:10.000Z by [qist...@gmail.com](http://code.google.com/u/106370313292761730621/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Pressing Ctrl-Tab advances to the next tab.
Pressing Ctrl-Shift-Tab switches to the previous tab.

**Why?**
The Ctrl-Tab behavior is so often implemented in applications that I, and
possibly many other developers, are very used to this.
Some applications allow you to just navigate through the tabs in a defined
order (like Firefox, Chrome and Internet Explorer).
Some even remember the order of tabs you've accessed and allow you to
switch between them in the accesses order (like Visual Studio, TextPad,
UltraEdit). Like Alt-Tab does in Windows, and probably on other OSes too.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
The only 'incompatibility' I can come up with is that people will not be
able to insert tabs while pressing Ctrl anymore. Though I think it's
unlikely anyone would do that.

An example of method 1:
- 3 tabs: "MainSketch", "Library.cpp", "Library.h"
- Currently in MainSketch
- Press (and release) Ctrl-Tab and switch to Library.cpp
- Press (and release) Ctrl-Tab again and switch to Library.h
- Press (and release) Ctrl-Tab again and switch to MainSketch

An exmaple of method 2:
- 3 tabs: "MainSketch", "Library.cpp", "Library.h"
- Currently in MainSketch
- Press (and release) Ctrl-Tab and switch to Library.cpp
- Press (and release) Ctrl-Tab again and switch to MainSketch
- Press (and release) Ctrl-Tab again and switch to Library.cpp
- Press (and hold) Ctrl, then Tab twice, and release both to switch to
Library.h

**Comment by cmaglie** [comment]
CTRL-TAB is working with the latest build, but not CTRL-SHIFT-TAB to go back on the previous tab.

**Comment by Scalpel78** [comment]
It would be useful if CTRL-TAB switched between the files you last used, and not EVERY file. I want to be able to quickly jump between two files, not step through all files in the project.

**Comment by lmihalkovic** [comment]
I missed some of the details of this proposal: 
* switching only on RELEASE while repainting the tabs to or something else to show which is the tentative target)
* finding a way to have a *sub-group* targetting only a subset of all the files (anyone knowing a app modeling this for inspiration?)

**Comment by matthijskooijman** [comment]
@lmihalkovic, I think those are two separate feature requeste, perhaps you should file them as such?

**Comment by lmihalkovic** [comment]
@matthijskooijman yes, they are distinct features. The first one was part of the original posting (AFAIK it is still not fully implemented), and the second seems to have been added @Scalpel78 more recently (added new entry for it #4350). My intention I was just to direct attention to the fact that the main entry is closed but these smaller details seemed to have fallen through the cracks. 

IMHO the first one is a great UX improvement for which you might want to consider reopening this item and finish including it in your recent rework (doing it in my fork).

**Comment by lmihalkovic** [comment]
think about it further.. it might even be nice for users to support
* case 1(already in scope of original posting)
Ctrl-TAB [show visually which fill file will become active next] 
Ctrl-TAB [show visually which fill file will become active next] 
RELEASE  --> switch
* case 2 (extension of previous case)
Ctrl-TAB [show visually which fill file will become active next] 
Ctrl-TAB [show visually which fill file will become active next] 
ESC  --> cancel switching and remain on the current tab

**Comment by matthijskooijman** [comment]
@lmihalkovic thanks for opening the new issue. Regarding the "switch on release" thing, I suspect you mean that you will switch when "ctrl" is released, instead of when tab is released? I do not think that the currently used java keybindings mechanism easily supports something like that, so we'd have to switch to processing key events directly. Also, I'm not sure what the advantages of adding this are. If you just switch the tab bar, or perhaps show a tab list popup, why not just switch tabs right away?

Anyway, if you feel that this is an important feature, could you also create a new report for it. Even if it was originally part of this request (which I'm not so sure), it will keep discussion cleaner if there is a separate issue for it.

**Comment by lmihalkovic** [comment]
```
Press (and release) Ctrl-Tab again and switch to Library.cpp
Press (and hold) Ctrl, then Tab twice, and release both to switch to Library.h
```
My reading of the second line is that as long as the keys are held, no switching is done. which is very convenient if someone has a sketch with a handful of tabs. This is also the way the app switching works on OSX (don't remember how it is on windoze). Just tested: Xcode jumps immadiately between tabs before releasing keys (sluggish feel when you jump 2 tabs away from the current). Safari also jumps immediately but at least it is not sluggish... will still try to the app-switcher way (jump only on release and press ESC to cancel switching away from current tab).


btw: as for the sub-grouping, Xcode has a fixed size list of "recently edited" files in a submenu, and no visible (so far) shortcut to cycle through only them.

**Comment by lmihalkovic** [comment]
```
public class KeyStroke extends AWTKeyStroke {
    public static KeyStroke getKeyStroke(int keyCode, int modifiers,  boolean onKeyRelease) {

```
the first piece seems to be there... will check the rest later

**Comment by lmihalkovic** [comment]
turns out it displaying a summary of the file (like the ALT-Tab app switcher) and only jumping when the right file is selected works fine and is somehow convenient: it means one can cycle through the list of files quickly to find the desired file without being delayed by the inertia of actually switching tab. you may want to look into it more closely.

**Comment by lmihalkovic** [comment]
example design for switching only when releasing ATL, and showing target file name in the meantime

<img width="400" alt="arduino-2016-01-07 at 9 27 35 am" src="https://cloud.githubusercontent.com/assets/1318077/12166250/e277c6c8-b524-11e5-89d4-1220b1fab120.png">
<img width="400" alt="arduino-2016-01-07 at 9 40 50 am" src="https://cloud.githubusercontent.com/assets/1318077/12166251/e2798a12-b524-11e5-9eb5-57a3d0f57071.png">
