### ISSUE TITLE
Downloader hangs...

### ISSUE THREAD

**Issue by three-jeeps** [arduino/Arduino#1959]
It seems this issue follow me around, no matter what board I use (uno, mega) or what OS (xp, w7, linux).  Attempting to download even the simplest program results in a wedging of the download...at about 80-90% complete...just hangs....then the USB port it subsequently reported to be in use.  I have used IDE v 1.0.1, 1.0.5, and earlier versions such as 0.22....Same intermittent problem....Seems like a real issue that has never been solved....just look at all the posts on the web....What a piece of crap.

Oh, and btw, use the correct terms....it is called DOWNLOADING...not 'uploading'....you are trying to change a well established NORM that has a definite meaning in the computer industry for the last 40 years....  just like trying to change the well established word 'program' to 'sketch'...artists do sketches, engineers and computer scientists write PROGRAMS....sheesh

**Comment by ffissore** [comment]
@three-jeeps have you tried the latest 1.6.4? Does it work?

**Comment by three-jeeps** [comment]
I moved on to a different platform and haven't used Arduino in over a
year.  Last time I used it, it was still flakey on dnlding...would hang.
J

**Comment by ffissore** [comment]
Closing as worksforme
