### ISSUE TITLE
Arduino 1.0.5 r2 version does not have driver for arduino micro

### ISSUE THREAD

**Issue by coreySheerer** [arduino/Arduino#1963]
![screenshot 32](https://cloud.githubusercontent.com/assets/7074175/2529974/61910592-b521-11e3-94bd-62437dd8fc43.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/7074175/2529975/6192b25c-b521-11e3-9624-63777c8428a5.png)

Arduino micro driver is not included in the driver folder downloaded with the 1.0.5 r2 version of arduino.  This is a huge problem as there is no previous ide builds available and I cant use the Arduino Micro I have.  Please see error message attached when driver is attempted to be installed.  Furthermore, please include at least the previous build for the ide on the download page

**Comment by ffissore** [comment]
Arduino Micro drivers are shipped and installed with latest 1.6.5
