### ISSUE TITLE
Dropdowns don't show text without hover

### ISSUE THREAD

**Issue by MrVoltz** [arduino/Arduino#1965]
When I activate dropdown, the active entry is empty. When I hover the entry, the text shows.

Linux Mint 16
java version "1.7.0_51"
OpenJDK Runtime Environment (IcedTea 2.4.4) (7u51-2.4.4-0ubuntu0.13.10.1)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)

![without text](https://cloud.githubusercontent.com/assets/5212649/2531029/efe08f9c-b52c-11e3-9dda-c555d7a473ec.png)

![with text](https://cloud.githubusercontent.com/assets/5212649/2531030/efe13ae6-b52c-11e3-8c73-309e64b0ebf2.png)

**Comment by ffissore** [comment]
This should have been fixed by f183966296458bc9e157b3d05cadb54aaac090aa, part of IDE 1.6.2
