### ISSUE TITLE
I2C on Arduino Nano

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#1966]
Original by Martin Rongen:

On http://arduino.cc/en/Main/ArduinoBoardNano it should state that I2C
is located at A4 and A5 (it currently states 4 and 5, which you usually
use as notation for the digital pins).

**Comment by UserXH726** [comment]
The error is still present.

**Comment by xl0** [comment]
The error cost us a 20-board batch.

**Comment by agdl** [comment]
fixed sorry about this

**Comment by xl0** [comment]
Thanks!
