### ISSUE TITLE
transformation .ino to .cpp fails with multi-line macro definition

### ISSUE THREAD

**Issue by peabo7** [arduino/Arduino#1971]
This code is not properly transformed from .ino to .cpp; the line containing "0" is erroneously emitted right after the #include "Arduino.h" statement resulting in a diagnostic such as:

  buggy.ino:5: error: expected unqualified-id before numeric constant

Rewriting the macro "abc" so it fits on one line avoids the problem.  Note also that the line number referenced in the error message is not the line number of the macro definition or the expansion, making it difficult to find what is wrong in a large program.

```C++
 #define abc \
 0
 
 void
 setup()
 {
   abc;
 }
 
 void
 loop()
 {
 }
```

I saw this using1.5.6-r2 BETA, but have not tested it on previous versions.

Peter Olson

**Comment by ffissore** [comment]
Please give a try to the IDEs linked at the bottom of this email on the dev list
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/4X2T3rCxXWM/YNJl6PZuDucJ
We're testing a new preprocessor. Your sketch needs a small change to work: you need to avoid using newlines between function return type and function names. Code `void setup` instead of
```
void
setup
```

**Comment by peabo7** [comment]
Tested using the Linux 64 bit version.  Works fine, thanks!

Will the issue with newlines be fixed?  I have been writing all my function
definitions that way for years and would keep to keep doing that.

Peter Olson

**Comment by ffissore** [comment]
Problem is with ctags: it reports where the function name is, not where its declaration (return type) starts. I guess this is as far as we can get for now. Code is available at https://github.com/ffissore/ctags if you want to tinker with it

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available
