### ISSUE TITLE
Arduino don't save my sketch !!!

### ISSUE THREAD

**Issue by gasemen2** [arduino/Arduino#1978]
I'm working about 3 hours. Then I turn off my computer. Arduino IDE don't ask me to save my sketch !!! All my job was lost. Fuck up. Pidarasu! Arduino 1.0.5-r2.

**Comment by agdl** [comment]
@gasemen2 the autosave function isn't implemented on the IDE. You have to do it by hand. However an autosave function on upload or verify will be soon implemented

**Comment by cmaglie** [comment]
Actually is implemented in nightly build and for the next 1.6.0 release.

**Comment by PnsUfuk** [comment]
banane ibne


2015-01-08 17:16 GMT+02:00 Cristian Maglie <notifications@github.com>:
