### ISSUE TITLE
Environmental conditions Arduino Micro

### ISSUE THREAD

**Issue by SilvanoZener** [arduino/Arduino#1979]
Hi. We need to integrate in some our specifications of a product based on Arduino micro, which we'll use in our company, the following informations:
Environmental conditions:
Operating temperature, min-max
Storage temperature, min-max
Operating humidity, min-max
Storage humidity, min-max.

We tried to look for them in the official Arduino website, but unfortunately without success. 
Is it possible, please, for you to integrate them in your below link or us them to send?

Thank you in advance.
--------------------------------------------------

(http://arduino.cc/en/Main/arduinoBoardMicro)
Summary
Microcontroller: ATmega32u4
Operating Voltage: 5V
Input Voltage (recommended): 7-12V
Input Voltage (limits): 6-20V
Digital I/O Pins: 20
PWM Channels: 7
Analog Input Channels: 12
DC Current per I/O Pin: 40 mA
DC Current for 3.3V Pin: 50 mA
Flash Memory: 32 KB (ATmega32u4) of which 4 KB used by bootloader
SRAM: 2.5 KB (ATmega32u4)
EEPROM:	1 KB (ATmega32u4)
Clock Speed: 16 MHz

**Comment by agdl** [comment]
@SilvanoZener unfortunately these parameters are not tested in production phase. They are tested @ Tamb because they are inted for domestic usage. We cannot give support to your request. If you really need these informations you can make tests by your own. Thank you
