### ISSUE TITLE
Arduino 1.5.6-r2 The directive " #if " not works properly

### ISSUE THREAD

**Issue by K5CZ** [arduino/Arduino#1983]
Arduino 1.5.6-r2 IDE and Nightly build

Conditional #include is also processed although the condition is evaluated as FALSE

Source code example:
#if defined(something_undefined)
Serial.print( "something_undefined is defined" ); //may not be printed and yes - is not printed
#include //may not be included but yes - IS included!
#else
Serial.print( "something_undefined is not defined" ); //may be printed and yes - is printed
#endif

**Comment by ffissore** [comment]
Fixed by #3779
