### ISSUE TITLE
NFC module won't work after a Ethernet.begin(mac,ip)

### ISSUE THREAD

**Issue by Sornii** [arduino/Arduino#1987]
Hello,

I'm using im my project a NFC module created by elecfreaks, and it use a PN532 which can comunicate over SPI, I2C or UART.

Currenctly I had problems using this in I2C, and switched to SPI, it works when nothing but the module is used in Arduino, but when I initialize the Ethernet it won't work.

Is everything okay in the Ethernet library or is the library that I'm using to control the NFC module?

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#26
