### ISSUE TITLE
Attiny + Software Serial + Mac OSX error

### ISSUE THREAD

**Issue by codemonkeybr** [arduino/Arduino#1988]
I got some problems related to the subject, i found out that it only occours on mac osx, a change in the file "/Contents/Resources/Java/hardware/tools/avr/avr/bin/ld" makes it work fine.

the error: /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr25/crttn85.o:(.init9+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `exit' defined in .fini9 section in /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/avr25/libgcc.a(_exit.o)

A discussion about it: http://forum.arduino.cc/index.php?topic=230862.new;topicseen#new

**Comment by ffissore** [comment]
Have you tried latest 1.5 as Coding Badly suggested on the forum?

**Comment by agdl** [comment]
reopen this if needed
