### ISSUE TITLE
Support for pre-compiled libraries. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#199]
This is [Issue 199](http://code.google.com/p/arduino/issues/detail?id=199) moved from a Google Code project.
Added by 2010-02-07T16:15:01.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE, OpSys-All

### Original description

**What change would like to see?**

Support for pre-compiled libraries, e.g. linking in of .o files.  There may need to be some way to 
provide multiple versions of the same object files, for different boards.  

**Why?**

Some libraries may not be open-source.  Others may require custom compilation parameters that 
aren't supported by the Arduino environment.

**Comment by ffissore** [comment]
Motivation for linking against binaries is that libraries may not be open source. Arduino core license is GPL, so anything that statically links to it must be (at least) GPL as well

**Comment by lmihalkovic** [comment]
```
Motivation for linking against binaries is that libraries may not be open source. Arduino core license is GPL, so anything that statically links to it must be (at least) GPL as well
``
In this formulation, this is not a true statement. Anyone can privately use GPLed code, compile it with non-GPL code, and not have the roof of their office fall on their head (i.e. I do not have to hang my code out on my balcony to have the right to use it with GPLed code). What cannot be done distribute a derivative work of a GPLed piece of work which does not itself comply with the GPL terms.

**Comment by matthijskooijman** [comment]
@lmihalkovic, agreed, that's also my understanding of the GPL.
