### ISSUE TITLE
Arduino project book project 05 wrong scheme

### ISSUE THREAD

**Issue by mjanmart** [arduino/Arduino#1997]
I am a real beginner in electronics so I might be wrong but in the servo scheme of the project 05 "Mood cue", the wires aren't displayed in the correct order:

the scheme display 3 wires where the servo has actually a plug. the wires are represented in order black red blank and the ones from the servo are in black blank red.

in addition, I can't fit the potentiometer and all the other components on line 16-18 on one side of the board.

Again I am very new to the world of electronics so I might be completely wrong...

Regards,

**Comment by agdl** [comment]
@mjanmart yes you are right because the servo used by Fritzing (the appl. used to make the images) is different from the one used by Arduino. However you can use it wiring GND to the black wire, PWM to the white one and 5V to the red one inserting all the wires in the connector without problems
