### ISSUE TITLE
Arduino Nano power output

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#2001]
Original by Alari Maricq:

Hello, I noticed that on the Arduino Nano overview page on arduino.cc says "As a result, when running on external (non-USB) power, the 3.3V output (which is supplied by the FTDI chip) is not available..." 
This statement can be found on this page: http://arduino.cc/en/Main/arduinoBoardNano
in the Power: section, the second sentence of the second paragraph.
I have personally verified that the Arduino Nano v3.0 does provide power through the 3.3V pin when powered by a 9volt battery that is connected to VIN and GND.
I hope this is helpful to you.

**Comment by agdl** [comment]
Fixed. In the schematic infact can be seen that the sentence is wrong. If a VIN is inserted the 5V chip that supply the FTDI chip works so the 3.3V output is available
