### ISSUE TITLE
Infinite recursive library import

### ISSUE THREAD

**Issue by austinstkong** [arduino/Arduino#2005]
Using the IDE's 'Add Library...' function, if the following directory is selected for import, then it will start to include itself infinitely. I have not tested other potentially recursive directory options. I had to kill the program from task manager.

    D:\user\My Documents\Arduino\libraries

![Screenshot](https://cloud.githubusercontent.com/assets/7272064/2687099/9ceb4a6a-c234-11e3-8425-04264b9053af.png)

**Comment by ffissore** [comment]
Fixed since 3ecaf665ae4b3ce6c33f20d3eaf93e8193de60f3. See #2795
