### ISSUE TITLE
Burn bootloader blocks IDE until it is completed

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#2009]
Tested using the ide-1.5.x branch from git.

This is probably because the bootloader process does not happen in a separate thread. There is [an attempt to do this](https://github.com/arduino/Arduino/blob/ide-1.5.x/app/src/processing/app/Editor.java#L2565) by using `SwingUtilities.invokeLater`, but that doesn't spawn a new thread, it just runs the given function later [in the event dispatching thread](http://docs.oracle.com/javase/6/docs/api/javax/swing/SwingUtilities.html#invokeLater%28java.lang.Runnable%29), which still locks up the GUI thread for as long as the function runs.

The proper fix this is to use an actual thread, but this should probably be combined by integrating the burn bootloader process into the verify/upload process (which should be simplified a lot - there's a lot of (unneeded) processing abstractions in there).

**Comment by per1234** [comment]
I can reproduce this with Arduino IDE 1.5.6-r2 (the latest IDE version at the time of the report) on Windows but it does not occur for me with Arduino IDE 1.8.3 so I'm going to close this.

If the issue still occurs for anyone with the latest IDE version please comment and I'll reopen.
