### ISSUE TITLE
Arduino Ide 1.5.3 for Intel Galileo won't start

### ISSUE THREAD

**Issue by shetter** [arduino/Arduino#2020]
Hi,

I'm quite new when it comes to microcontrollers and Arduino, however I have been working a bit with the Arduino Duemlianove. I'm also new on this forum so if i have posted in the wrong place or should have done it any other way please feel free to comment on it and I will keep that in mind for future posts.

Now I have bought an Intel Galileo board and I am trying to get the IDE for the Galileo board to run (1.5.3), which i downloaded from: https://communities.intel.com/docs/DOC-22226. I have been following the "Getting started guide" which can be downloaded from the same webpage above.

I have gotten to the point where I have installed the drivers for the Galileo on my windows 7 x64 system and I am now trying to start the IDE in order to update the firmware and uploading my first sketch. The problem is, when I start the arduino IDE the welcome screen appears but then it suddenly disappaears and nothing more happens. After the welcome screen is done i guess the main window should appear where you can write and upload code to the arduino, but it doesn't.

I have googled on this and found some other threads where people have had the same type of problem, for instance: 
http://forum.arduino.cc/index.php/topic,186529.0.html and 
https://github.com/arduino/Arduino/issues/1525. I have tried opening the arduino IDE through the command prompt as someone suggested, and also tried installing and opening the nightly build, however without any result. 

Do anybody know how to solve this? Experienced the same type of problem?
Help is greatly appreciated!

**Comment by ffissore** [comment]
This problem should have been fixed in recent IDEs. Can you try 1.6.4? Intel cores are available in Tools > Boards > Boards Manager

**Comment by shetter** [comment]
Hi ffissore, 

I have recently reinstalled the computer I had the problem with and also put the Galileo on a bookshelf for the time being, so I am sorry to say that I have no way of testing the IDE with the previous set up.

Thanks for taking time on the issue!

**Comment by ffissore** [comment]
I see, too bad. If you got a change to download IDE 1.6.4 and try uploading a blink on the galileo, it would be great. I'll leave this open for a while
