### ISSUE TITLE
OSX IDE Improvement -  option not to set defaults

### ISSUE THREAD

**Issue by HarperBen** [arduino/Arduino#2030]
OSX often reopens closed programs on restart - If you use a external drive / version control / encrypted image or what ever - the Arduino IDE can open before the volume is mounted or otherwise accesible, when it does so it resets the sketch directory path back to defaults - an option to cancel this would save us from remapping it every time

![image](https://cloud.githubusercontent.com/assets/1393814/2786236/dc29c230-cb6f-11e3-9f5e-590c17c0815e.png)

**Comment by ffissore** [comment]
What should happen once you click "cancel" if your encrypted/external/whatever drive is still unavailable?
