### ISSUE TITLE
Operator as a keyword

### ISSUE THREAD

**Issue by rynmcd** [arduino/Arduino#2033]
Creating a variable with the name "operator" creates problems because it is a keyword that can be used for operator overloading.  There is no way to tell that "operator" is a keyword using the Arduino IDE.

**Comment by Chris--A** [comment]
This is fixed!

https://github.com/arduino/Arduino/blob/master/build/shared/lib/keywords.txt#L49

**Comment by ffissore** [comment]
:+1:
