### ISSUE TITLE
Move --relax from Compiler.java to some boards.txt param

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#2039]
This piece of code should be removed and become part of a generic board specific flags configuration in boards.txt
https://github.com/arduino/Arduino/blob/ide-1.5.x/app/src/processing/app/debug/Compiler.java#L733-L739

**Comment by jantje** [comment]
This issue just got reported on the arduino eclipse plugin as well https://github.com/jantje/arduino-eclipse-plugin/issues/270
I was not aware of this.
The code frederico points to https://github.com/arduino/Arduino/blob/ide-1.5.x/app/src/processing/app/debug/Compiler.java#L733-L739 gives a page not found.
So what other things are in there?

I'm wondering:
In my eclipse plugin the boards.txt settings can overwrite the platform.txt settings by simply declaring the same name again.
If the Arduino IDE does it this way too, one could easily solve this as follows:
platform.txt
compiler.c.default.elf.flags=-w -Os -Wl,--gc-sections
compiler.c.elf.flags={compiler.c.default.elf.flags}

boards.txt
mega.compiler.c.elf.flags={compiler.c.default.elf.flags},--relax
..(something similar for other mega based boards)

**Comment by ffissore** [comment]
While we already have a handful of `extra_flags` options both in boards.txt and platform.local.txt, none of them is useful for `--relax`. AFAICS fixing this, whatever way we choose, will break backwards compatibility with older and especially custom cores. @cmaglie ?

**Comment by cmaglie** [comment]
As said by @xxxajk and @matthijskooijman we can just add it permanently to the command line for all AVR boards. Does anyone know a reason to not do so?

Previous versions of the IDE will continue to add the parameter to the command line and eventually ends to `-Wl,--gc-sections,--relax,--relax` that it seems to be tolerated by gcc, so this solution should be fully-compatible.

Just for the record, the relevant piece of code is now here https://github.com/arduino/Arduino/blob/740a14e638f2c386f84b05499e0a65ba3f7fdc61/arduino-core/src/processing/app/debug/Compiler.java#L1118
The current linker command is: `compiler.c.elf.flags=-w -Os -Wl,--gc-sections`
with the relax options becomes: `compiler.c.elf.flags=-w -Os -Wl,--gc-sections,--relax`
so `,--relax` should be added specifically to the parameter `-Wl,...` (just appending to the whole command line as it now may not work if the command line is reordered).

**Comment by per1234** [comment]
Looks like the code is now here:

1. https://github.com/arduino/arduino-builder/blob/5fd49b6d4c14abc31ae9e1a9f18d4c1e7ba8b355/phases/linker.go#L74
2. https://github.com/arduino/arduino-builder/blob/5fd49b6d4c14abc31ae9e1a9f18d4c1e7ba8b355/phases/linker.go#L94-L99

**Comment by matthijskooijman** [comment]
This issue is essentially duplicated by https://github.com/arduino/arduino-cli/issues/639 (which I reported last month, totally forgetting that this issue already existed). Regardless, that is now the location where the relevant code lives (nothing left to fix in this repo), so I'm going to close this issue in favor of that one.
