### ISSUE TITLE
Add new programmer class - for remote upload

### ISSUE THREAD

**Issue by tchilton** [arduino/Arduino#2047]
As its easier and faster to develop on a desktop PC, yet many embedded systems end up in hard to access places, it would be really helpful if there was a two-staged programming option for example :

1. Develop on PC - full size screen, plenty of CPU, plenty of RAM
2. Compile - as above
3. "Upload Using Programmer" by sending .hex files to intermediate small form factor raspberry Pi / equivalent over SCP. Remote machine just needs to be reachable on the network  wireless, wired, etc.
4. Initiate a script on the remote system (over SSH ?) that includes execution of AVRDUDE on raspberry PI to program Arduino
5. Report results back to IDE, so everything is Integrated, like it should be.

I note that the Yun has a SSH / SCP capability. Could this be expanded to make it more general ?

This would also allow for increased flexibility such as SPI programming of remote systems. Conversely, remote serial port redirection to support upload is far harder to do in such situations.

Alternately, could the programmers.txt file be enhanced to allow for a call-out to an OS script file that could do whatever the programmer requires to upload - Just pass it the argument of the .hex file and similar.

**Comment by tchilton** [comment]
Hi Lauszus 

I have finally found some time to write up the scripts and make them available for others. You can obtain them on Github as the farduino project. Here's the link.https://github.com/tchilton/farduino

**Comment by Lauszus** [comment]
Thanks @tchilton, I will take a look :)

**Comment by sandeepmistry** [comment]
I believe #4107 resolves this, but let me know if it doesn't we can re-open.
