### ISSUE TITLE
Arduino Leonardo Keyboard custom values

### ISSUE THREAD

**Issue by PeetvanStaden** [arduino/Arduino#2049]
All new Keyboards have custom buttons, like the button "Play/Pause" has a value of 0xB3, but the 0xB3 value is assigned to an extra "TAB" button. How can I send the value 0xB3 without using the Keyboard.write() function?

**Comment by LuisDiazUgena** [comment]
I'm trying to make a audio controller with arduino leonardo and I haven't being able to send this kind of keystrokes. I've used the teensy keyboard and library and it's so useful and easy to use. 

It would be possible to integrate this library into arduino leonardo? Maybe it's easier to make this than build it from scratch.

**Comment by facchinm** [comment]
Hi @LuisDiazUgena and @PeetvanStaden , 
using latest 1.6.6 hourly build and @NicoHood's HID project library the Teensy keyboard is already supported!

**Comment by LuisDiazUgena** [comment]
Hi @facchinm! Thanks for your response. 

I've downloaded NicoHood's library (dev branch) and I'm not been able to run it, i've already open a [issue under HID project](https://github.com/NicoHood/HID/issues/60), but maybe you can tell me what I'm doing wrong.

Thanks!

**Comment by NicoHood** [comment]
Teensy keyboard will be back soon.
Look at the examples, its so easy. Docs/wiki will follow. Sorry for the incompletion.
