### ISSUE TITLE
Save/View Circuit Diagrams/Images in Sketchbook IDE

### ISSUE THREAD

**Issue by craig1971** [arduino/Arduino#2085]
So, the projects our sketchbooks contain code that is supposed to work with a specific circuit, right?
Why doesn't the IDE have a way for me to upload, or even draw, a circuit diagram?

Yes, i know i can put it directly into the folder on my own, and then navigate there to view it later... but it would be much better if my diagram(s) were displayed as tab(s) in the IDE when I open my project.

**Comment by ffissore** [comment]
Wontfix. Arduino Create will provide a similar feature
