### ISSUE TITLE
Missiing File (1.5.6-r2) SerialEvent.html

### ISSUE THREAD

**Issue by K-I-S-S** [arduino/Arduino#2087]
Arduino/arduino-1.5.6-r2/reference/SerialEvent.html.

from the serialEvent() link on this page: Arduino/arduino-1.5.6-r2/reference/Serial.html

Should serialEvent be SerialEvent()?

Also reported here: http://forum.arduino.cc/index.php?topic=242092.0

**Comment by ffissore** [comment]
Bundled reference updated. Fix available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
