### ISSUE TITLE
Missing file (1.5.6-r2) arm-none-eabi-gcc++

### ISSUE THREAD

**Issue by K-I-S-S** [arduino/Arduino#2088]
$ pwd
[redacted]/Arduino/arduino-1.5.6-r2/hardware/tools/g++_arm_none_eabi
ubuntu@ubuntu:[redacted]/Arduino/arduino-1.5.6-r2/hardware/tools/g++_arm_none_eabi$

$ ls
arm-none-eabi  bin  getting-started-2010q1.pdf  lib  libexec README
	
===	

Got error running the Sketch application:

Cannot run Program "Arduinio/....../hardware/tools/g++_arm_none_eabi/bin/arm/arm-none-eabi-g++:Java.io.IOException: Error 2 No such file or directory

Sure enough.  the file arm/arm-none-eabi-g++  is MISSING!

When you copy the error message, sketch doesn't include the error.  The error is also obscured by the "Copy Error Messages" button.

Copy Error message says:

Arduino: 1.5.6-r2 (Linux), Board: "Arduino Due (Programming Port)"

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

I THOUGHT the download is supposed to include a compiler?

Arduino Due, Ububtu, 12.04 LTS, 64 bit.

"arm-none-eabi-gcc++"  is  supposed to be here?

This probably should be two posts.  Copy error messages probably only refers to the compiler and it should include errors reported on the bottom bar on Sketch_may23a

**Comment by cmaglie** [comment]
This has been fixed with c2e5f67ea62f127c1ad8ca5861d4c6afa4043c03.
