### ISSUE TITLE
Menu nearly impossible to read Arduino 1.5.6-r2

### ISSUE THREAD

**Issue by K-I-S-S** [arduino/Arduino#2093]
I can barely see the menu on my Toshiba A665-s6050 Laptop running Ubuntu 12.04 LTS 64 bit.

The white text in the lower orange and black bands of the application are fine, but the menu is nearly invisible.  Is this intentional?

Not sure how to attach screenshots if necessary.

**Comment by ffissore** [comment]
Is this issue still valid? Can you please attach a screenshot?
