### ISSUE TITLE
Can't start IDE on Mac 10.9.3

### ISSUE THREAD

**Issue by ivukotic** [arduino/Arduino#2099]
I have:
~ >/usr/libexec/java_home -V                                                          
Matching Java Virtual Machines (1):
    1.7.0_09, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk1.7.0_09.jdk/Contents/Home
~ >/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

Whatever version of the Arduino I downloaded it does not start:

5/25/14 11:36:31.408 PM com.apple.launchd.peruser.501[190]: ([0x0-0x91091].cc.arduino.Arduino[1210]) Exited with code: 1

I found tens of descriptions of the same problem and there is no good solution anywhere.

Please fix.

**Comment by ffissore** [comment]
@ivukotic can you try "macosx-new" version from https://github.com/arduino/Arduino/pull/2590#issuecomment-72337128 ?

**Comment by ffissore** [comment]
Fixed with IDE 1.6.0 release. If you still have problems, please open a new issue
