### ISSUE TITLE
Please Trap Permission Denied Errors

### ISSUE THREAD

**Issue by K-I-S-S** [arduino/Arduino#2100]
Since JSSC 2.5.0 
Added new exception TYPE_PERMISSION_DENIED. It can be very useful for _nix based system if user have no permissions for using serial device

Corollary:  A web page when you search for "Permission Denied" telling the user what they need to do to fix it.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
