### ISSUE TITLE
Find and replace utility functions incorrectly.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#2106]
A small bug has been identified in the find & replace utility within the IDE.
http://forum.arduino.cc/index.php?topic=243579.msg1746052

Entering text into the 'Replace with:' text box and hitting Replace will insert the text directly into the document. No text has to be entered into the 'Find' text box.

A simple fix may be to disable the replace button until something is found. The 'Replace All' button does not have the same error.

This has been tested in Arduino IDE versions 1.5.6-r2

**Comment by ffissore** [comment]
This has been fixed with cd75cc24a2774a98dc11d7fc501c55b8bf2a6a1e but issue was not closed
