### ISSUE TITLE
TFT library not working with Arduino 1.0.5 

### ISSUE THREAD

**Issue by Filip-** [arduino/Arduino#2108]
I use the Arduino TFT LCD Screen. From its reference page  I got to the TFT library reference page [1] where it is  written :

Quote: ".. The TFT library is included with Arduino IDE 1.0.5 and later.... "

 but for me it is only working with Arduino 1.5.5 BETA downloaded from 2. 
( I only tested 1.0.5 and then 1.5.5 BETA on Uno and Mega ) 

I think that the quoted statement above is confusing, since you get the impression that the library in 1.0.5 is also working for the Arduino TFT LCD Screen .

[1] http://arduino.cc/en/Reference/TFTLibrary
[2] http://arduino.cc/en/Main/OldSoftwareReleases

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/TFT#7
