### ISSUE TITLE
Robot Play Melody

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#2115]
From http://forum.arduino.cc/index.php?topic=240270.0

I think that the description on the page http://arduino.cc/en/Reference/RobotPlayMelody of the modifier '.' is incorrect. Where it describes note durations, it says ". : Make the previous note 3/4 its length". Comparing this to the source at https://github.com/arduino/Arduino/blob/master/libraries/Robot_Control/Melody.cpp, this should be 2/3, not 3/4.

**Comment by agdl** [comment]
Hi to all according to musical notation a . after the note it states that the note last its duration + 1/2 its duration. So i modified the documentation according to this
