### ISSUE TITLE
1.0.5 IDE not launching on Mac OS X 10.7.4

### ISSUE THREAD

**Issue by oscillator** [arduino/Arduino#2121]
Steps to Repro:

1) From Arduino.cc, download Mac OS X version 1.0.5 .zip 

2) Unzip & drag Arduino.app to /Applications (note: no Library folder, I expect this is created automatically when app is first launched?)

3) From Mac OS X Terminal: (cd /Applications): open Arduino.app

Actual Result:
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Arduino.app.

Expected Result: 
Arduino.app launches normally

Troubleshooting step taken - no joy:

1) From Apple site, Install missing JVM 1.6: java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

2) Run Disk Utils, found (1) W perms on Java Group - fixed 

3) From Arduino.app/Contents/Info.plist, change:
<key>JVMVersion</key>
      <string>1.5*</string>
to
<key>JVMVersion</key>
      <string>1.6*</string>

Notes: 

• Dbl-click on desktop icon, very brief indiscernible flash to display, then nothing
• No issues with previous version of the IDE going back several years 11,12, mostly 23 on 10.4.11 on MacBook Pro
• Current install is on Mac Mini Mid 2011

**Comment by ffissore** [comment]
Java issues with recent macosxs should be solved by the "macosx-new" version of the IDE from https://github.com/arduino/Arduino/pull/2590#issuecomment-72337128 Can you give it a try?

**Comment by ffissore** [comment]
Fixed with IDE 1.6.0 release. If you still have problems, please open a new issue
