### ISSUE TITLE
Update PROGMEM reference page to mention that variables must be either defined Globally or with the static keyword in order to work w/PROGMEM

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [arduino/Arduino#2122]
The Arduino PROGMEM reference page (http://arduino.cc/en/Reference/PROGMEM) should have the following important lines added: 

-----------------------------------------------------------------------------

Variables must be either globally defined, OR defined with the "static" keyword, in order to work with PROGMEM.

ex: 
The following code will NOT work when inside a function:

PROGMEM char long_str[] = "Hi, I would like to tell you a bit about myself.\n"

...though this line WILL work, even if locally defined within a function:

PROGMEM static char long_str[] = "Hi, I would like to tell you a bit about myself.\n"

-----------------------------------------------------------------------------

For more discussion, and detailed code, see here: http://forum.arduino.cc/index.php?topic=245480

**Comment by agdl** [comment]
@ElectricRCAircraftGuy I added the statement as you suggested. If it is ok for you please close this issue

**Comment by ElectricRCAircraftGuy** [comment]
@agdl, I'm looking at the arduino page (http://www.arduino.cc/en/Reference/PROGMEM) but don't see your added statements. Where can I see the documentation where you added them? Has it not been released to the Arduino.cc pages yet?

**Comment by agdl** [comment]
@ElectricRCAircraftGuy it is there before tue see also in a paragraph "Note" written in bold

**Comment by ElectricRCAircraftGuy** [comment]
@agdl, I see the change now. I think it didn't show up in my browser before because I checked it only a couple minutes after you made the change, and it needed a few minutes to take effect. 

Sorry, one more error in my recommended edit. Please add the keyword "const" in front of both lines of code now. I wrote them before const was required by the version of GCC that Arduino IDE uses, but now it won't compile without const being in front. The code lines should look like this now:

```
const PROGMEM char long_str[] = "Hi, I would like to tell you a bit about myself.\n"
```
and
```
const PROGMEM static char long_str[] = "Hi, I would like to tell you a bit about myself.\n"
```

**Comment by Chris--A** [comment]
It seems a more accepted way to use PROGMEM, is before the assignment. It is more concurrent with the actual behavior as it is not a type modifier, but a data attribute.

```Arduino
const static char long_str[] PROGMEM  = "Hi, I would like to tell you a bit about myself.\n";
```

**Comment by ElectricRCAircraftGuy** [comment]
@Chris--A, sounds fine with me. @agdl , if you're good with it, let's go with this then:


Please note that variables must be either globally defined, OR defined with the "static" keyword, in order to work with PROGMEM.

The following code will NOT work when inside a function:
```
const char long_str[] PROGMEM = "Hi, I would like to tell you a bit about myself.\n"
```
The following code WILL work, even if locally defined within a function:
```
const static char long_str[] PROGMEM = "Hi, I would like to tell you a bit about myself.\n"
```

**Comment by agdl** [comment]
@ElectricRCAircraftGuy @Chris--A done!

**Comment by ElectricRCAircraftGuy** [comment]
thanks!
