### ISSUE TITLE
Where's the beef...(Arduino Starter Kit PDF Guide)...? 

### ISSUE THREAD

**Issue by PeteRudenko** [arduino/Arduino#2127]
Hello Arduino
Where are the PDF files for your excellent starter kit...?
I am finding it cumbersome reading paper back manual and work with circuits at same time.
Its like having one hand tied behind your back (holding manual) while finding parts, using a magnifing glass to read circuit pictures and assembling the physical circuit.  Fortunatly I was able to find a variety of OUT-OF-DATE working  PDF and JPG files on the WEB at  http://www.oomlout.com/a/ -and- http://ardx.org/src/guide/4/DATA/.  Kindly review the Adafruit WEB site for their superb learning leasons and downloadable PDF's, example https://learn.adafruit.com/adafruit-arduino-lesson-15-dc-motor-reversing?view=all.

**Comment by agdl** [comment]
@PeteRudenko sorry but we don't provide pdf files for the starterkit. In any case for feature questions like this please contact support@arduino.cc. GitHub is intended for software related issues. Thank you!
