### ISSUE TITLE
Cursor is badly positioned after mouse click on the text area.

### ISSUE THREAD

**Issue by earl2586** [arduino/Arduino#2128]
I have been using Parallax for all my control products. Their a little pricey. So I decided to try UNO.

programming software sucks.. 

The curser will not go were I need it to be. Its just tearable.

Why would they sell a product that it is so hard to program?

I took me hours because the curser on the screen would just go were ever it wanted, and there was always a square box close to it.

I spent all day tiring to get it to work. 

I loaded 1.0.3

I loaded 1.0.4

And the latest version..

They all do the same after a few min. of programming.

Tell me what I’m doing wrong please or I’m going back to Parallax..

Their program software is so much better than theirs. 

You think you would try to compete with the same or a better program.

The Parallax support is so much better to  

Earl...........

**Comment by ffissore** [comment]
You may want to try the latest hourly build http://www.arduino.cc/en/Main/Software#hourly
We changed editor and input from any language is now fully supported. We also changed how the IDE starts on Windows, fixing some strange graphical glitches
