### ISSUE TITLE
Arduino Due I2C connection problem

### ISSUE THREAD

**Issue by Hammad32** [arduino/Arduino#2129]
I am trying to use MS5611A2 barometer with Arduino due but there is some problem with the I2C connection of the Due board. I also connected MPL3115A2 with Due and it also does not work. But when i connect both of these baros with Arduino Uno, they work fine. Please i need help urgently. If someone has experience with using Due with I2C, i would really appreciate your help. Thank you.

**Comment by sxpert** [comment]
you can use a PCA9511AD to do the proper conversions

**Comment by VaclavSal** [comment]
Due has two I2C "ports" and only ONE of them has build-in pull-ups. Since the ports are "open collector" type pull-ups are not optional and should be adjusted so the I2C bus works properly.

**Comment by agdl** [comment]
@Hammad32 is this problem solved? If so please close the issue!

**Comment by VaclavSal** [comment]
Since the original postee did not show further interest it should be closed to keep things uncluttered.
So whose job it is ?
