### ISSUE TITLE
Licensing problem with dataflash library on the Playground.

### ISSUE THREAD

**Issue by xl0** [arduino/Arduino#2135]
Hello.

It seems that the "dataflash" library from the playground might have a non-open-source license:

```cpp
//      COPYRIGHT (c) ATMEL Norway, 1996-2001
//
//      The copyright to the document(s) herein is the property of
//      ATMEL Norway, Norway.
//
//      The document(s) may be used  and/or copied only with the written
//      permission from ATMEL Norway or in accordance with the terms and
//      conditions stipulated in the agreement/contract under which the
//      document(s) have been supplied.
```

IANAL, but this seems to create two problems: Arduino distributing some code without having a license, and the users creating commercial products based on Arduino and this library would also distribute the code illegally.

**Comment by agdl** [comment]
I'm clarifying the situation here

https://github.com/agdl/Arduino/tree/libraryLicenses

 in order to make a big PR when everything will be ok if someone can check this the help will be very appreciate!

**Comment by per1234** [comment]
The library has since been moved from the playground to the forum. I have commented on the thread regarding the licensing issue:
http://forum.arduino.cc/index.php?topic=298022.msg3324540#msg3324540
I'll see if the forum moderators chime in with an opinion on this and update this issue if there is any progress.

**Comment by per1234** [comment]
I have removed the forum topic that contained the material in violation of Microchip's copyright.
