### ISSUE TITLE
Minimal Circuit Breadboard clock

### ISSUE THREAD

**Issue by Guilhermemf89** [arduino/Arduino#2141]
It's necessary correct the file "Breadboard.zip" in this link: http://arduino.cc/en/Tutorial/ArduinoToBreadboard
For that we need change the line:
atmega328bb.build.f_cpu=8000000L
The correct is:
atmega328bb.build.f_cpu=1000000L
Because the Atmega chip divide the clock by 8, without that the delay function doesn't work properly.

**Comment by agdl** [comment]
@Guilhermemf89 if you look at low fuse configuration in the boards.txt you can see that the fuse CKDIV8 (low fuse pag 284 of http://www.atmel.com/images/Atmel-8271-8-bit-AVR-Microcontroller-ATmega48A-48PA-88A-88PA-168A-168PA-328-328P_datasheet_Complete.pdf) is uprogrammed so the division by 8 is disabled and so the atmega328bb.build.f_cpu=8000000L is correct

**Comment by agdl** [comment]
I'm closing this. reopen it if needed
