### ISSUE TITLE
Serial Monitor Improvements

### ISSUE THREAD

**Issue by andreujuanc** [arduino/Arduino#2149]
Hello, I'd like to leave a few things i think would be nice to have. I wish I had time to implement it myself, but I cant at the moment.

- Option to open Serial monitor right after build & deployment on board.
- Option maintain monitor's window state (size, location) after being closed and open again. (works better with improvement #1).

Best regards

**Comment by cmaglie** [comment]
Closing as duplicate #1891 and #1631
