### ISSUE TITLE
clarify parseInt() return type

### ISSUE THREAD

**Issue by nixmd** [arduino/Arduino#2154]
In the refrence and documents, it is not clear which type will be returned by parseInt(). Somewhere it says long int and somewhere else it says int. I think it should be clarified as it may confuse those who want to parse long integers and they may think that this function only parses int and not long int.

http://arduino.cc/en/Serial/ParseInt
https://github.com/arduino/Arduino/blob/master/hardware/arduino/cores/arduino/Stream.h#L70

**Comment by matthijskooijman** [comment]
I've collected all parseInt issues in #2867, so I'm closing this one.
