### ISSUE TITLE
multiple called TFT library occur error

### ISSUE THREAD

**Issue by yonta** [arduino/Arduino#2165]
`loadImage`, `read16`, `read32`, and `loadImage` in the `Adafruite_GFX.h` have defined function bodies in `.h` files.
So, it occur errors in case of multiple calling `TFT.h`.
I have gotten this errors some time in making my libraries.

Please, fix it by updated the newest `Adafruite_GFX` library.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/TFT#6
