### ISSUE TITLE
Arduino 1.0.5 doesn't open on OSX 10.9.4

### ISSUE THREAD

**Issue by andreasciamanna** [arduino/Arduino#2176]
In order to get rid of all the mess with the different jvm version (that blocked me from installing Eclipse on my machine) I had in my machine, I brutally got rid of the Java folder, then installed it from scratch.

```
Now I can't run Arduino anymore:
open Arduino.app/
2014-07-11 17:33:41.719 open[20763:507] JLRequestRuntimeInstall: CFMessagePortSendRequest: error -1
LSOpenURLsWithRole() failed with error -10658 for the file /Users/andrea/Downloads/Arduino.app.
```

```
java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
```

As far as I understand this issue is caused by the 64bit version of Java, but I though that this issue got fixed (https://github.com/arduino/Arduino/issues/1496) long ago.

Anyway, any hint on how I can fix it?

**Comment by gibiansky** [comment]
How can I get around this?

 I have Arduino 1.6 and Java 1.8. What's going on? 

The error is
```
[JavaAppLauncher] Requested [1.6*], launching in [1.8] instead.
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bundle/Libraries/libserver.dylib
JavaVM: Failed to load JVM: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bundle/Libraries/libserver.dylib
JavaVM FATAL: Failed to load the jvm library.
[JavaAppLauncher Error] JNI_CreateJavaVM() failed, error: -1
```

Do I really have to install Java 6?

**Comment by ffissore** [comment]
@gibiansky try the macosx experimental version http://arduino.cc/en/Guide/IDEonRecentMacOSX

**Comment by gibiansky** [comment]
@ffissore Thank you! Works perfectly. (Or at least opens, haven't tried connecting it to Arduino)
