### ISSUE TITLE
IDE Error Check For == vs. = in logic compare statements [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#218]
This is [Issue 218](http://code.google.com/p/arduino/issues/detail?id=218) moved from a Google Code project.
Added by 2010-03-10T14:48:01.000Z by [itstheme...@gmail.com](http://code.google.com/u/109613247880466878689/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

The IDE does not notice the difference between:

if (x=1) 

and the correct

if (x==1)

Just an enhancement.

Thanks.

**Comment by ffissore** [comment]
See http://code.google.com/p/arduino/issues/detail?id=218 comments
