### ISSUE TITLE
RX on Leonardo

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#2181]
Original by Eugene Frizza:

I have discovered a mistake on the Software Serial reference page ( http://arduino.cc/en/Reference/SoftwareSerial ). It states that the Leonardo can only use the software serial RX function on certain pins, but it actually works for all digital pins, as stated on the main Leonardo board page ( http://arduino.cc/en/Main/arduinoBoardLeonardo ). I have verified that the latter is the correct one.

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen it if needed.
