### ISSUE TITLE
Incorrect first responder behavior in save panel

### ISSUE THREAD

**Issue by dgatwood** [arduino/Arduino#2185]
In the Arduino app, you're doing something screwy with the first responder, because when the save panel (window) is open, the window behind it is still getting some messages, and shouldn't be.  For example:

1.  Press Command-Shift-S to open a save panel.
2.  Put your cursor in the name bar.
3.  Press Command-A to select the entire filename.
4.  Observe that instead of highlighting the filename, it highlights the entire contents of the file in the window behind the save panel.

Besides breaking the normal usage patterns of users, assuming that other keystrokes also get passed through to the window behind it, the bug could potentially be dangerous, as users could potentially do damage to the contents of their files without knowing it.

**Comment by ffissore** [comment]
@dgatwood is this still valid with latest 1.6.5 or hourly? This issue looks JVM related rather the Arduino IDE related, and we switched to java 8: maybe it autosolved?
