### ISSUE TITLE
File naming requirements should go away

### ISSUE THREAD

**Issue by dgatwood** [arduino/Arduino#2186]
For some baffling reason, Arduino insists on renaming my projects so that they don't include spaces.  It's a very un-Mac-like user experience, and there's no possible valid reason to do so.

Such workarounds almost invariably indicate that some part of your code isn't quoting filenames correctly.  In my experience, in 99.9% of code where I've encountered code like this, that code has turned out to be inadequate, so odds are quite good that the failure to fix the actual quoting bugs is a potential security hole.  And even if it isn't a hole, it causes new users to be concerned about the quality of code.  Please fix whatever code necessitated this hack, then stop changing the filenames.

**Comment by ffissore** [comment]
Wontfix. It's not just about osx. Your sketch path is used in platform.txt files written by arduino hackers worldwide. By avoiding spaces we make life easier to everyone

**Comment by dgatwood** [comment]
That's ridiculous.  You aren't avoiding spaces.  You're preventing us from using spaces.  There's a difference.  And who cares where those paths end up?  Why does that matter even slightly?
