### ISSUE TITLE
Arrow UP 'OPen' issue with libraries list

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#2189]
Another issue i have on Windows Vista is:
When i click on the arrow 'UP' open sketch on the IDE, i don't see the libraries list ...

(I have added manually some new libraries)

**Comment by z3t0** [comment]
Can you give us more information regarding to what version of the IDE you use, and also a screenshot if possible. I don't get this error so I recommend trying the latest IDE

**Comment by ffissore** [comment]
Closing as invalid. Not enough info were provided
