### ISSUE TITLE
Arduino 1.5.7 IDE & Windows 7

### ISSUE THREAD

**Issue by quillby** [arduino/Arduino#2197]
I installed arduino IDE v1.5.7 It starts the program and it's possible to open the Blink example. When doing the verification/compilation, is doesn't work.
The error message shows forward slashes in the first command, while the rest have backslashes:

Arduino: 1.5.7 (Windows 7), Board: "Arduino Yún"

M:\Programma\arduino-1.5.7/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=157 -DARDUINO_AVR_YUN -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8041 -DUSB_MANUFACTURER= -DUSB_PRODUCT="Arduino Yun" -IM:\Programma\arduino-1.5.7\hardware\arduino\avr\cores\arduino -IM:\Programma\arduino-1.5.7\hardware\arduino\avr\variants\yun C:\Users\Bert\AppData\Local\Temp\build6474042086913624782.tmp\Blink.cpp -o C:\Users\Bert\AppData\Local\Temp\build6474042086913624782.tmp\Blink.cpp.o

When using the same configuration, but arduino 1.5.5 there are no errors.
Is this a bug in the compiling program of arduino 1.5.7?
How can it be solved?

Thanks, Bert.

**Comment by cmaglie** [comment]
Closing for lack of feedback. Feel free to reopen and provide more information.
