### ISSUE TITLE
Due bug: Cannot use pin as digital after analogRead

### ISSUE THREAD

**Issue by trickedj** [arduino/Arduino#2198]
Once a pin has been used by analogRead it cannot be returned to digital use with pinMode(xxxx, OUTPUT) because analogRead only frees up the pin when another channel is read. pinMode needs to check if the pin is currently selected for the ADC and if so free it up.

A work around is to free up the pin by selecting a spare with analogRead

I discovered this while porting (from a Uno to Due) a TFT+touchpanel screen which shares digital TFT functions with raw touchpanel resistors.

**Comment by facchinm** [comment]
I've added some thoughts and code on https://groups.google.com/a/arduino.cc/forum/#!topic/developers/IdhTIT0V5GY ,
I'd be very glad to have some discussion before committing any fix :wink:

**Comment by facchinm** [comment]
Solved by #3524
