### ISSUE TITLE
Increase/decrease indent doesn't work on OS X with swedish keyboard layout. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#220]
This is [Issue 220](http://code.google.com/p/arduino/issues/detail?id=220) moved from a Google Code project.
Added by 2010-03-15T19:40:59.000Z by [krook.jo...@gmail.com](http://code.google.com/u/107155206166980269532/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Press Command
2. Press Alt
3. Press 8/9

**What is the expected output? What do you see instead?**

The row or all selected text should change indentation. Instead, nothing happens.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Arduino 0018 on OS X with swedish keyboard.

**Please provide any additional information below.**

Seems like the problem is with shortcuts which need Alt to be pressed. The shortcut for 
comment/uncomment works fine. That is: 
1. Command 
2. Shift 
3. 7. 
A possible solution could be to change shortcuts to Command-( and Command-). 

The issue is similar to http://code.google.com/p/arduino/issues/detail?id=76

**Comment by ffissore** [comment]
Fixed with #3229
