### ISSUE TITLE
IDE: remove trailing spaces

### ISSUE THREAD

**Issue by MrScarabus** [arduino/Arduino#2202]
Can you make an option to remove trailing spaces in editor, sometimes it's very annoying.

**Comment by ffissore** [comment]
AStyle is the way to go. You can have your own [formatter.conf](https://github.com/arduino/Arduino/blob/master/build/shared/lib/formatter.conf) file: put it in the same folder as preferences.txt and restart the ide

**Comment by pedzed** [comment]
I'm not sure why this is closed. Why do some settings need a third-party program while others don't? This is an important setting to have built-in...
