### ISSUE TITLE
Add Entry to All Program for Arduino IDE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#221]
This is [Issue 221](http://code.google.com/p/arduino/issues/detail?id=221) moved from a Google Code project.
Added by 2010-03-23T04:43:27.000Z by [cappy2...@gmail.com](http://code.google.com/u/105159837660030726516/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I would like the Arduino installer to make the proper entry for the Arduino
IDE under All Programs. Currently, you need to make a shortcut and stick it
on the desktop. Most programs put an Entry so you can launch it from "All
Programs"

**Why?**

It makes the IDE easier to launch, and makes it more compliant to how
Windows programs and installers currently are configured.

**Comment by ffissore** [comment]
Fixed a long time ago with a windows installer
