### ISSUE TITLE
Arduino 1.5.7 IDE on OS X Mavericks: Find function doesn't show find UI.

### ISSUE THREAD

**Issue by huertanix** [arduino/Arduino#2211]
Edit > Find... brings up an empty window (below) instead of a find dialog. Window cannot be resized or maximized and only displays title bar buttons.
![arduino_find_command](https://cloud.githubusercontent.com/assets/72914/3715530/b26ecd56-15e7-11e4-9f89-b60199cee291.jpg).

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by huertanix** [comment]
@ffissore Excellent, thank you!
