### ISSUE TITLE
cygwin1.dll missing from avr-gcc 4.8.1 directory

### ISSUE THREAD

**Issue by mpflaga** [arduino/Arduino#2216]
Yes, it works from within the IDE. However if from Windows one calls the avr-gcc manually, such as "C:\Users\mflaga\desktop>"C:\projects\Arduino\arduino-1.5.7\hardware\tools\avr\bin\avr-gcc.exe" -v", it fails with the following:

```
---------------------------
avr-gcc.exe - Entry Point Not Found
---------------------------
The procedure entry point __ctype_ptr__ could not be located in the dynamic link library cygwin1.dll. 
---------------------------
OK   
---------------------------
```
Placing C:\projects\Arduino\arduino-1.5.7\cygwin1.dll into the C:\projects\Arduino\arduino-1.5.7\hardware\tools\avr\bin\ directory along with avr-gcc, as with 1.5.6r2 and before, allows the proper dll to be called.

While this is not a direct problem with the stock IDE, it will cause problems for other IDE's such as SubLim's STINO and other IDE's that point their build/compile commands to the IDE's avr-gcc.

**Comment by hamsafar** [comment]
Hi
I want to use atmel studio for arduino but it have an error like other!
i cannot solve "error: spawn: No such file or directory" please help me to solve it.
tanx

**Comment by ffissore** [comment]
@hamsafar your issue is off topic. Please submit it to the [avrfreaks forum](http://www.avrfreaks.net/)

Closing as we are tackling this issue in #2422
