### ISSUE TITLE
[Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError] when using long char array [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#222]
This is [Issue 222](http://code.google.com/p/arduino/issues/detail?id=222) moved from a Google Code project.
Added by 2010-03-26T20:02:34.000Z by [kreychek](http://code.google.com/u/kreychek/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Compile the code located at:
http://www.ladyada.net/make/eshield/LEDcolorpicker.pde using Arduino-0018

This compiles without error on Arduino-0010, but outputs the following in
Arduino-0018:

Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at com.oroinc.text.regex.Perl5Matcher._pushState(Perl5Matcher.java)
	at com.oroinc.text.regex.Perl5Matcher._match(Perl5Matcher.java)

with the last line repeating *many* times.

This occurs on Windows XP and possibly other OSes based on anecdotal reports.
ex: http://forums.adafruit.com/viewtopic.php?f=31&t=6558&p=32002

From the admin (adafruit) at the above post:
"...the javascript string appears to be too long..."

**Comment by ffissore** [comment]
Answer posted on the original issue

**Comment by ffissore** [comment]
Fixed by #3779
