### ISSUE TITLE
Add way to clear and/or hide output panel?

### ISSUE THREAD

**Issue by Annonomus-Penguin** [arduino/Arduino#2221]
I've always thought the output window, when an error occurs, is quite distracting when you're fixing the code. Ideally, I would write better code, but that's not always possible. :sleeping:

I was thinking maybe double click to clear any messages? I know you can scroll up/down to hide the error message so it doesn't catch your eye, but there's still a giant orange bar at the bottom. Even better would be that the bar disappears when it's cleared so it doesn't waste valuable screen real estate.

If not all users would want this, you might want to have a setting.

**Comment by ffissore** [comment]
Also see #423 about hiding/closing console: it's a wontfix

**Comment by natevw** [comment]
@ffissore Is there a **reason** that "it's a wontifx"? My son is trying to use the Arduino IDE on PocketChip and he can pretty much only see/edit one line at a time. It'd be a nice little interface if we could hide the output.

On 1.6.4 at least on OS X, there's a little button to collapse it. And on https://bbs.nextthing.co/t/is-the-arduino-ide-usable-on-the-pocketchip/5582/7 thread there's a screenshot of someone without it too. But that thread just ends with a bunch of people saying "how did you hide the output?"

**Comment by ffissore** [comment]
@natevw  sorry you missed the news. I no longer work for arduino. See https://groups.google.com/a/arduino.cc/forum/#!msg/developers/YJLX6AZHem4/kpsLef7XBAAJ
