### ISSUE TITLE
Missing documentation for some String methods

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#2235]
The [documentation for the String object](http://arduino.cc/en/Reference/StringObject) seems to be missing some of the methods and operators. In particular, I'm missing:
 - `remove()`
 - `toFloat()`
 - `c_str()`
 - `operator<`, `operator>`, `operator<=`, `operator>=`
 - `operator=`
 - `operator+=`
 - `operator!=`

See [WString.h](https://github.com/arduino/Arduino/blob/master/hardware/arduino/cores/arduino/WString.h) for the full list of methods available.

**Comment by agdl** [comment]
@matthijskooijman is it ok for you writing only this?

http://arduino.cc/en/Reference/CStr

If you have some improvement in mind you are very welcome!

**Comment by matthijskooijman** [comment]
You should probably add something like:

> Note that this gives direct access to the internal String buffer and should be used with care. In particular, you should never modify the string through the pointer returned. When you modify the String object, or when it is destroyed, any pointer previously returned by `c_str()` becomes invalid and should not be used any longer.

**Comment by agdl** [comment]
Done. It should be online in a minute. Can we finally close this? :)

**Comment by matthijskooijman** [comment]
Looks good to me, so yes :-)

**Comment by agdl** [comment]
Yeah
