### ISSUE TITLE
IDE 1.5.7 Crashes when boards.txt is incomplete/wrong

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2238]
Hi,
I had a lot of problems with crashing IDE when the bootloader.txt is incomplete.

To simply crash the ide add this to boards.txt
```
atmega32u4.name=Atmega 32u4 DFU
atmega32u4.upload.tool=avrdude
atmega32u4.upload.protocol=avr109
atmega32u4.upload.maximum_size=28672
atmega32u4.upload.maximum_data_size=2560
atmega32u4.upload.speed=57600
atmega32u4.upload.disable_flushing=true
atmega32u4.upload.use_1200bps_touch=true
atmega32u4.upload.wait_for_upload_port=true

atmega32u4.bootloader.tool=avrdude
atmega32u4.bootloader.low_fuses=0xFF
atmega32u4.bootloader.high_fuses=0xD9
atmega32u4.bootloader.extended_fuses=0xC3
atmega32u4.bootloader.file=dev/ATMega32U4-usbdevice_dfu-1_0_0.hex
atmega32u4.bootloader.unlock_bits=0x3F
atmega32u4.bootloader.lock_bits=0x2F
```
add the rest and it will work:
```
atmega32u4.build.mcu=atmega32u4
atmega32u4.build.f_cpu=16000000L
atmega32u4.build.vid=0x2341
atmega32u4.build.pid=0x8037
atmega32u4.build.usb_product="Atmega 32u4"
atmega32u4.build.board=AVR_32U4
atmega32u4.build.core=arduino
atmega32u4.build.variant=atmega32u4
atmega32u4.build.extra_flags={build.usb_flags}
```

I also had a total IDE brick with a wrong boards.txt in the sketchbook/hardware folder(bricks more than this one). I struggeled very hard to get the IDE working again. This bug is not in 1.0.5. I also recommend you to give the user a debug uninstall. This deletes any %temp% and all data in %appdata% related to arduino.

and by the way: it would be nice to have dfu uploading support with the ide. should i open a new issue for that or wont this ever happen anyways?

**Comment by Chris--A** [comment]
Using the current source for 1.6.5 this no longer causes any error. Nothing is added to the boards list however, but no crash happens.

**Comment by NicoHood** [comment]
Closing this as outdated. Not tested anymore, but well everything works as intended if you do it correct ;)
