### ISSUE TITLE
Ability to include (and link to) HTML docs with a sketch. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#224]
This is [Issue 224](http://code.google.com/p/arduino/issues/detail?id=224) moved from a Google Code project.
Added by 2010-04-01T18:23:35.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-Post-1.0, Component-IDE, OpSys-All

### Original description

A sketch should be able to include HTML documentation (e.g. in a docs/ sub-folder).  The IDE 
would then display a link / button to open the documentation in a browser.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
