### ISSUE TITLE
GSM Library  compilation issues

### ISSUE THREAD

**Issue by nenadalm** [arduino/Arduino#2242]
Arduino: nightly (Linux), Board: "Arduino Leonardo"

Build options changed, rebuilding all
Using library GSM in folder: /home/nenadalm/Downloads/arduino-nightly/libraries/GSM 

/home/nenadalm/Downloads/arduino-nightly/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=157 -DARDUINO_AVR_LEONARDO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8036 -DUSB_MANUFACTURER= -DUSB_PRODUCT="Arduino Leonardo" -I/home/nenadalm/Downloads/arduino-nightly/hardware/arduino/avr/cores/arduino -I/home/nenadalm/Downloads/arduino-nightly/hardware/arduino/avr/variants/leonardo -I/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src /tmp/build7185471309775697337.tmp/sketch_aug16b.cpp -o /tmp/build7185471309775697337.tmp/sketch_aug16b.cpp.o 
/home/nenadalm/Downloads/arduino-nightly/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=157 -DARDUINO_AVR_LEONARDO -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8036 -DUSB_MANUFACTURER= -DUSB_PRODUCT="Arduino Leonardo" -I/home/nenadalm/Downloads/arduino-nightly/hardware/arduino/avr/cores/arduino -I/home/nenadalm/Downloads/arduino-nightly/hardware/arduino/avr/variants/leonardo -I/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src /home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp -o /tmp/build7185471309775697337.tmp/GSM/GSM3MobileMockupProvider.cpp.o 
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::begin(char*)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:49:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::begin()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'virtual int GSM3MobileMockupProvider::ready()':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:55:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::ready()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::beginSMS(const char*)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:61:2: error: 'Serial' was not declared in this scope
  Serial.println("SM3MobileMockupProvider::beginSMS()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'void GSM3MobileMockupProvider::writeSMS(char)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:67:2: error: 'Serial' was not declared in this scope
  Serial.print(c);
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::endSMS()':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:72:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::endSMS()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::availableSMS()':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:77:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::availableSMS()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'void GSM3MobileMockupProvider::flushSMS()':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:96:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::flushSMS()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::connectTCPClient(const char*, int, int)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:115:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::connectTCPClient()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'void GSM3MobileMockupProvider::writeSocket(const uint8_t*, size_t, int)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:123:3: error: 'Serial' was not declared in this scope
   Serial.print(buf[i]);
   ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::disconnectTCP(int)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:174:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::disconnectTCP()");
  ^
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp: In member function 'int GSM3MobileMockupProvider::connectTCPServer(int, char*, int*)':
/home/nenadalm/Downloads/arduino-nightly/libraries/GSM/src/GSM3MobileMockupProvider.cpp:180:2: error: 'Serial' was not declared in this scope
  Serial.println("GSM3MobileMockupProvider::connectTCPServer()");
  ^

**Comment by cmaglie** [comment]
@nenadalm 
may you try with the latest nightly build and see if this problem is fixed?
http://arduino.cc/en/Main/Software#nightly

**Comment by nenadalm** [comment]
@cmaglie - I can try on friday (but you can close if you think this is resolved and I can reopen in case it isn't)

**Comment by nenadalm** [comment]
now it compiles correctly. thanks. (can't verify it's functionality because I don't have the gsm module right now)
