### ISSUE TITLE
Add INPUT_PULLUP to firmata library setPinMode function?

### ISSUE THREAD

**Issue by vytronics** [arduino/Arduino#2246]
Is there a reason INPUT_PULLUP is not a defined mode in firmata library? When all input pins are set for INPUT mode and not connected to anything there is a tremendous amount of Tx noise for inputs changing every several milliseconds.

**Comment by soundanalogous** [comment]
I've moved this issue over to the Firmata repo: https://github.com/firmata/arduino/issues/197.
