### ISSUE TITLE
Tutorial/ArduinoSoftwareRS232, wiring and coding errors

### ISSUE THREAD

**Issue by charlesglorioso** [arduino/Arduino#2247]
Tutorial/ArduinoSoftwareRS232 has both wiring error and coding errors.

1) wiring instructions for Capacitors.  
Says connect capacitor between pins 1 and 3. Correct.
then says between pin 1 and ground.  Incorrect.   That should be between pin 2 and ground.

2) Code error.
#define bit9600Delay 84.    This is not enough delay on my Arduino Uno,  
Oscilloscope says bit9600Delay 100 produces correct baud rate.
Also halfBit9600Delay 50 is correct.

3) Code Error
in Setup()
digitalWrite(tx, HIGH);  requires
delay(2);   ( or similar) to allow at least one character time after setting output high for receiving PC to prepare for following output characters of "hi"

**Comment by agdl** [comment]
@charlesglorioso modified! Thank you!
