### ISSUE TITLE
WiFiClient read method does not return readed length

### ISSUE THREAD

**Issue by bondarchook** [arduino/Arduino#2251]
In WiFiClient class read method implementation call getDataBuf and pass pointer to to _size variable
getDataBuf will return readed length in to it. But this length will not propagate out of WiFiClient::read method because size parameter is not a pointer and and also this   uint16_t _size = size;

```c++
int WiFiClient::read(uint8_t* buf, size_t size) {
  // sizeof(size_t) is architecture dependent
  // but we need a 16 bit data type here
  uint16_t _size = size;
  if (!ServerDrv::getDataBuf(_sock, buf, &_size))
      return -1;
  return 0;
}
```
i think WiFiClient::read should get pointer to uint16_t and path it directly to getDataBuf
so after call size actualy has nember of readed bytes

```c++
int WiFiClient::read(uint8_t* buf, uint16_t* size) {
  if (!ServerDrv::getDataBuf(_sock, buf, size))
      return -1;
  return 0;
}
```

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#2
