### ISSUE TITLE
issues with Arduino REV 2,3

### ISSUE THREAD

**Issue by Dietrick** [arduino/Arduino#2262]
i ust picked up a Arduino uno REV3 to replace my REV2. and when I upload a program I made for my rev 2 to the rev 3 it wont work the same way as the rev 2 would. for example when I made my obatical avoiding robot with a ping ultrasonic sensor, it wouldn't use the same program that worked on my rev 2. is my REV 3 dysfunctional or is the rev 2 and 3 suppose to be programed differently or is my programing language out of date because I am using arduino 1.0.5

**Comment by agdl** [comment]
@Dietrick can you better explain what you mean with different behaviour?

**Comment by agdl** [comment]
reopen if needed
