### ISSUE TITLE
Arduino Leonardo/Micro - Add support for USB keyboard LED reports 

### ISSUE THREAD

**Issue by Mr-Click** [arduino/Arduino#2275]
Dear Arduino Developers,

I recently bought an Aruino Mirco and I'm struggling to retrive LED reports from host machine.
On Arduino forum I found a patch (not tested) that should solve the issue (see http://forum.arduino.cc/index.php?topic=173583.0 )

Why not patching the HID implemetation on arduino IDE to include LED reports?

regards,
Valerio

**Comment by facchinm** [comment]
Closing with #1803, please use @NicoHood Pluggable HID library ( https://github.com/NicoHood/HID/tree/dev_2_4) to get Keyboard leds working with the standard core
