### ISSUE TITLE
Orientation of the chip not shown .../ArduinoToBreadboard

### ISSUE THREAD

**Issue by grahamatgithub** [arduino/Arduino#2285]
http://arduino.cc/en/Tutorial/ArduinoToBreadboard does not show the orientation of the chip on the breadboard.

Need to identify PIN1 in the images

**Comment by lmihalkovic** [comment]
markdown would make for nice lib documentation

<img width="400" alt="arduino-2015-12-01 at 1 39 00 am" src="https://cloud.githubusercontent.com/assets/1318077/11489152/0aa8d8a0-97cd-11e5-905f-8faf7b2bd1ad.png">
