### ISSUE TITLE
Serial monitor window writes huge error-log to disk after unplugging board   [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#229]
This is [Issue 229](http://code.google.com/p/arduino/issues/detail?id=229) moved from a Google Code project.
Added by 2010-04-19T09:45:08.000Z by [e.fa...@wayoda.org](http://code.google.com/u/112428979976680495685/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Start up the IDE on windows
1.Open to serial monitor and connect to a board that send a stream of data
2.Unplug the board and leave the serial monitor window open

The output panel of the IDE prints an endless stream of IOExceptions until
the serial monitor is closed. The same messages are written to a file on
the harddisk  
\Users\<NameOfUser>\AppData\Local\Temp\console<SomeRandomNumber>.tmp
The size of the file increases very fast (User reports 10GB written in one
night). 

What version of the Arduino software are you using? 
Found this error on 0017 and 0018
On what operating system?
XP and Vista 32 bit (at least)
Which Arduino board are you using?
Any board

**Please provide any additional information below.**
Solution : 
Close the Serial Port when an IOException is thrown in method
processing.app.Serial.serialEvent(SerialPortEvent)

Original report is here
http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1271286720

**Comment by ffissore** [comment]
Fixed since the removal of RXTX and the introduction of JSSC. Tested with latest hourly.
