### ISSUE TITLE
Error in Arduino Yun product documentation

### ISSUE THREAD

**Issue by hansvi** [arduino/Arduino#2290]
On the page http://arduino.cc/en/Main/ArduinoBoardYun , section "Communication", it says:

 A SoftwareSerial library allows for serial communication on any of the Yún's digital pins except for pins 0 and 1.

This is not true: Tx works on any IO pin (analog pins also), Rx only works on certain pins (identical to Leonardo).

That one sentence led me on a wild goose hunt that lasted 5 hours.

**Comment by per1234** [comment]
This issue is still present on the page. Was the change never pushed to the website or did it get reverted at some point? I have reported it again as part of an overall review of the page at: https://github.com/arduino/Arduino/issues/6509
