### ISSUE TITLE
ArduinoToBreadboard minimal doesn't work without initial ext clock

### ISSUE THREAD

**Issue by grahamatgithub** [arduino/Arduino#2297]
http://arduino.cc/en/Tutorial/ArduinoToBreadboard

Section "Minimal Circuit (Eliminating the External Clock)" describes a procedure to burn the bootloader without an external oscillator.

This does not work if you have a standard bootloader which set the UNO up to use the ext clock.

In order to do this you would have to burn the internal clock bootloader already, which defeats the point :)

**Comment by agdl** [comment]
@grahamatgithub The example states:

If you have a new ATmega328 (or ATmega168), you'll need to burn the bootloader onto it. 

After an example using the 16MHz quartz is provided otherwise without it so it is correct. I'm closing this reopen it if you have new doubts

**Comment by grahamatgithub** [comment]
My point was not if you have a blank ATmega chip, it is if you have a standard Arduino UNO chip (with a bootloader already installed). This is the thing which does not work for the "Minimal Circuit" section.

I tried this with a Arduino UNO chip (bootloader preinstalled) from RS. It failed as the standard bootloader uses the external clock and so does not run.

You need to reflash the bootloader FIRST (using an Arduino as an ISP) to install one which does not rely on the external clock before you can continue, i.e. treat it as a blank ATmega chip even though it is not.
