### ISSUE TITLE
Arduino IDE preprocessor causes unknown type references from prototype creation

### ISSUE THREAD

**Issue by JeffBobbo** [arduino/Arduino#2304]
Functions using/returned an object, structs or using typedefs cause bad code to be fed to the compiler:

Source code:
http://0bin.net/paste/Xz5MZdbmuafYUQ2Q#567rrlhZy8-xCaiI7geiRXEZ+DFo92e4dpZ/cAJvJ3j

Arduino preprocessed code (fed to avr-g++):
http://0bin.net/paste/JgtLxMb23ZOaGJMu#RYZv9sCkcSXeapn0XXRCKphshFH38YLSHmGmn2Iy4EL

**Comment by ffissore** [comment]
We've just posted a new preprocessor version at https://groups.google.com/a/arduino.cc/d/msg/developers/4X2T3rCxXWM/WbQ2_dGzuhsJ
While it does not solve your issue, at least it allows you to work around it by specifying the prototype your self. Try adding a `Foo makeFoo();` at line 21: the sketch will compile fine.

**Comment by ffissore** [comment]
Fixed by #3779
