### ISSUE TITLE
Arduino mega having pins not assigned to be usable on IDE

### ISSUE THREAD

**Issue by markusdnd** [arduino/Arduino#2307]
Just lately I bumped on running out of pins on arduino mega. The problem is that there are extra pins but they have no place on board nor are they accessible from the IDE. 

I will be working on libraries myself to get Port J working for soft serial and simple I/O but someone who knows more about arduino internals might want to make changes to the libraries so that those pins are able to be used for more than just fastening cpu to board. 
http://forum.arduino.cc/index.php?topic=267316.0 is the post I made about it on the forum. 

From my point of view never ever should any processor have any part un-used just because headers for those pins did not look nice on the composition of the board. That is just plain wrong just bring out the pads. Mega has more than enough room for that. 

These are my two cents that I thought that might help arduino onward a bit. 

On the professional level, Arduino is very good dev platform for idea testing and software preliminary development, but from time to time this kind of thing becomes a huge inconvenience that takes more time off of users than it should.

**Comment by agdl** [comment]
@matthijskooijman can you close this?
