### ISSUE TITLE
[OS X] Retina display support (NSHighResolutionCapable and image@2x)

### ISSUE THREAD

**Issue by jacobseptember** [arduino/Arduino#2309]
Crossposting here and at the Google Groups page; it's not clear which one is more active.

There are two issues regarding Retina support: Text/buttons/UI in general, and high-quality images.

The "simple" text/buttons/etc issue can be addressed by adding the following to Info.plist:
`<key>NSHighResolutionCapable</key>  <true/>`
This was apparently done with [this commit](https://github.com/arduino/Arduino/commit/409da1d9c790e03aac9b078ac791bfb0502edf41) in August 2012, but the version of 1.5.7 that I downloaded in August 2014 did not have this key in its Info.plist.

The images issue is a bit more complicated. I'm used to working with iOS, in which the OS will generally accept either `image.png` or `image@2x.png` (the high-resolution version). This is apparently not the case with OS X; when I try to use an image I created for the little down-triangle in the top right of the IDE, it doesn't show up at all if the filename includes the "@2x" and shows up twice as large as should be if the filename doesn't include the "@2x".
The fix here is more involved, but shouldn't be too difficult (I think). First, high-def images need to be created for the eleven images in `Arduino.app/Contents/Java/lib/theme`. Then, the source code needs to be modified to look for the "@2x" images as well as the regular ones, and take the correct one. I don't know exactly how this is done, and I suspect it will be more involved in Java than Obj-C. Sorry.

SEE ALSO: Google Code [issue 982](https://code.google.com/p/arduino/issues/detail?id=982), Github [issue 982](https://github.com/arduino/Arduino/issues/982), Github [issue 2204](https://github.com/arduino/Arduino/issues/2204), Google Code [issue 1140](https://code.google.com/p/arduino/issues/detail?id=1140)

![tab-unsel-menu](https://cloud.githubusercontent.com/assets/8811726/4310483/cf3a75e2-3ea6-11e4-8f2e-395eaacbfda1.gif)
![tab-unsel-menu@2x](https://cloud.githubusercontent.com/assets/8811726/4310484/cf55c630-3ea6-11e4-97bf-5e464bcc616e.gif)

**Comment by maximkrusina** [comment]
To refresh cache, no need to reboot Mac OS, just use in terminal:
`sudo touch /Applications/Appname.app`
