### ISSUE TITLE
ArduinoISP example sketch does not work with Mega or Due

### ISSUE THREAD

**Issue by championswimmer** [arduino/Arduino#2314]
The ArduinoISP included example works fine with Uno or Leonardo

But it fails to work for Mega (this works good for Mega https://raw.githubusercontent.com/rsbohn/ArduinoISP/master/ArduinoISP/ArduinoISP.ino)

 and it cannot compile at all for Due as arm doesn't support spi_* functions like avr gcc (this works good for Due https://raw.githubusercontent.com/PeterVH/ArduinoISP/due/ArduinoISP/ArduinoISP.ino)

**Comment by facchinm** [comment]
Solved by #3500
