### ISSUE TITLE
Numeric Keypad Arrow Keys

### ISSUE THREAD

**Issue by george-gallant** [arduino/Arduino#2317]
I am using 1.5.7 on a dual boot Centos 6.5 And Windows 7 laptop. With Centos, the 4 arrow keys on the numeric pad do nothing when pressed in the IDE Editor. Same machine with Windows they work fine. The Page UP/DOWN and HOME/END work. Same keys work inside the Serial Monitor. Tried with builtin keypad as well as external usb keyboard. Same behavior on 2 Centos desktop machines.

Down graded to 1.0.5 and same results. This is the only application I use that exibits this behavior.

**Comment by ffissore** [comment]
Can you give a try to latest hourly? http://www.arduino.cc/en/Main/Software#hourly We changed editor and your issue could have been autofixed

**Comment by george-gallant** [comment]
Does not seem to be fixed. I played with the system keycode table and 
have it working (until next
system purge/update). Have one non-fixed system to test your implementation.

George

**Comment by ffissore** [comment]
Fixed in 054a901b992e52e101a42996fcf22e16b1b39bcd. Fix will be available in next hourly build. Please remind that due to unknown glitches, only plain arrows work: no shift/ctrl/etc combination
