### ISSUE TITLE
Editor Font Selection Capability [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#232]
This is [Issue 232](http://code.google.com/p/arduino/issues/detail?id=232) moved from a Google Code project.
Added by 2010-04-22T13:39:41.000Z by [jkob...@gmail.com](http://code.google.com/u/108587518660752956155/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I would like to be able to set the font for the editor on arduino ubuntu
linux. i've tried changing theme.txt and preferences.txt and nothing works.
how about a simple couple of drop down menus in the preference dialog for
font and size. added plus would be anti-aliasing of fonts but not a show
stopper.

Why? because i consider it unusable the way it is now. i can barely read it.

Would this cause any incompatibilities with previous versions?  should not
cause any incompatibility issues.

Thanks
Jeff O'Brien

**Comment by ffissore** [comment]
Font size change is available at File > Preferences, font face can be changed tweaking `preferences.txt`. Antialiasing has been turned on by default since 1f12aa9a45e4683e966afa4c75a7d34bf8571331
