### ISSUE TITLE
If you close the IDE the clipboard is lost (Ubuntu)

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#2332]
Steps to reproduce:

* In the IDE copy some text to the clipboard.
* Close the IDE (you do this because maybe you need to install a library)
* Re-open the IDE.
* Try to paste.
* Get message: "Clipboard does not contain a string"

IDE 1.0.5.
Ubuntu 14.04 LTS

This can be pretty annoying if you are working on a small demo sketch (eg. for the forum) and have chosen not to save it (ever), so you just copy it to the clipboard so you can install a library that the sketch need to compile. The clipboard should not vanish just because the app that you copied from the text from closed.

I notice that some other apps (eg. Libre Office) seem to do the same thing, however gedit does not. You can  copy something in gedit to the clipboard, close it, re-open it, and paste it back. There must be some "save the clipboard" function that should be called on app close down.

Or alternatively gedit might "more powerfully" (for want of a better term) put text that has been copied onto the Clipboard.

**Comment by ffissore** [comment]
Closing as wontfix. We can't fix it, it's a linux only issue and no java app on linux works correcly
