### ISSUE TITLE
Ardino IDE 1.5.7 cpp segmentation fault

### ISSUE THREAD

**Issue by ziotibia81** [arduino/Arduino#2336]
-Add "compiler.cpp.extra_flags=-fpermissive" to platform.local.txr
-Install this DCF77 library: http://blog.blinkenlight.net/experiments/dcf77/dcf77-library/
-Compile the example "Simple Clock"

gpp has a segmentation fault. Tested in windows e linux.

**Comment by agdl** [comment]
@matthijskooijman what about this issue?

**Comment by agdl** [comment]
@matthijskooijman up

**Comment by cmaglie** [comment]
This is a gcc bug, I guess we should close this issue and wait for a fix on upstream gcc.
