### ISSUE TITLE
Command line options not working at all [OS X - Java 7 Bundle]

### ISSUE THREAD

**Issue by aknoerig** [arduino/Arduino#2342]
I'm trying to get the CLI to work as described here:
[https://github.com/arduino/Arduino/blob/ide-1.5.x/build/shared/manpage.adoc](https://github.com/arduino/Arduino/blob/ide-1.5.x/build/shared/manpage.adoc)

I'm using 1.5.8 with Java 7 on OS X, and am aware that I have to use the full path to `Arduino.app/Contents/MacOS/JavaAppLauncher` (which btw needs to be updated in the manpage). However, any command line arguments are always ignored, and Arduino is always launching with the GUI and an empty sketch.

Thanks for any pointers.

**Comment by ffissore** [comment]
Fixed since 1.6.2

**Comment by ajfisher** [comment]
I don't believe this is fixed. I'm trying to run from command line using 1.6.4 at the moment and any instruction passed to /Applications/Arduino.app/Contents/MacOS/Arduino are simply ignored and the IDE starts with a blank new sketch - usually with the error of "can't open sketch ..."

Could this be a regression?

**Comment by facchinm** [comment]
Hi @ajfisher , could you test with the latest nightly? Every problem with CLI on Mac should have been solved with #1493

**Comment by ajfisher** [comment]
Confirmed it's working in nightly. How long until this hits release? I'm worried about NodeBots day coming up next weekend and us not having a reliable CLI tool for OSX for that.
