### ISSUE TITLE
When making a new tab in the IDE, the focus does not always change to it

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#2349]
Steps to reproduce:

* Make a new sketch
* Add a new tab: foo.h
* Note that the focus switches to the new, empty tab: foo.h
* Type something into foo.h
* Add a new tab: foo.cpp
* Note that the focus **does not switch** to the new tab: foo.cpp

This is confusing. Why should the focus switch some times but not others? I suspect it is because of the alphabetical order of the tabs, but even so. Normally when you make a new file (or new tab) you expect that new file / new tab to be given the focus.

Tested in IDE 1.0.6 and also 1.5.8.

**Comment by ffissore** [comment]
Fixed a long time ago
