### ISSUE TITLE
When deleting a tab, there is a confusing confirmation message

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#2350]
Steps to reproduce:

* Make a new sketch
* Make a new tab: foo.h
* Make another new tab: foo.cpp
* Delete the tab: foo.h
* Note that the error message is: Are you sure you want to delete "foo"?

I have **two** "foo" tabs (foo.h and foo.cpp). This message does not confirm which of those I am about to delete. Can it not echo the actual tab name? (foo.h / foo.cpp)

Tested in IDE 1.0.6 and also 1.5.8.

**Comment by q2dg** [comment]
Also: there's no option to close tab without deleting its content from disk!!!??
In fact, File-> Close and File->Quit do the same: close the IDE.
So...there's no way to only close a tab and nothing else.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
