### ISSUE TITLE
Bridge usage will hang 32u4 sketch upon ar9331 reboot

### ISSUE THREAD

**Issue by arve0** [arduino/Arduino#2351]
BridgeClass::transfer blindly accepts receive length (Bridge.cpp line 179) and keeps reading instead of discarding even if above receive buffer (line 192). This makes sketch on 32u4 hang if it runs a bridge command when ar9331 restarts (process, console, etc).

This also affects #2028.

Forum threads possibly affected:
http://forum.arduino.cc/index.php?topic=222941.0
http://forum.arduino.cc/index.php?topic=271090.0
http://forum.arduino.cc/index.php?topic=204077.0
http://forum.arduino.cc/index.php?topic=222476.5

**Comment by facchinm** [comment]
Closing with #2781 
Please comment on #2353 if you want to improve the "ping" functionality
