### ISSUE TITLE
Componet layout Drawing for Due

### ISSUE THREAD

**Issue by jimdooris** [arduino/Arduino#2361]
It would be helpful if a component placement drawing was available for the Due. It would help locate thing like JR1 which I cannot locate

**Comment by agdl** [comment]
@jimdooris you can access it downloading the eagle files and showig only the layer you needs. In any case if you have both the schematic and the layout file opened if you click on the component you need on the schematic it will lights up in the layout so you can locate it. A very fast method to find a component however is to click on move in the layout editor and write the name of the component you need on the command line. Doing this the component will move to you current mouse position an so looking at te tracks you can locate it.
