### ISSUE TITLE
enabling Tone for Due

### ISSUE THREAD

**Issue by HanaJin** [arduino/Arduino#2362]
Hi Arduino Team, 

Is there a plan or timeline in mind to enable Tone for Due board in future releases?

**Comment by q2dg** [comment]
Well, a solution seems to be here (http://forum.arduino.cc/index.php?topic=136500.0) .
Could you add it to official tone() function code, plis??

...And, on the other hand, what about tone() implementation in Zero??? API must be consistent between boards!!!

**Comment by aethaniel** [comment]
@q2dg, tone() is implemented on Zero: https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/Tone.cpp

**Comment by q2dg** [comment]
@aethaniel Ah, oook, thanks! (and sorry!). 
Anyway, clarificating the documentation to specify the diferent API's functionality scope among the diferent boards (if there is any) is fundamental. But that's for another issue.

**Comment by q2dg** [comment]
Well, I only wanted to point that problem with tone() and Due still remains...

**Comment by VogonJeltz** [comment]
I don't see how it now should work for the Due - can you provide a example source code please?

**Comment by VogonJeltz** [comment]
OMG, the TOP dated from October 2014  !!
why hadn't it been fixed yet ?!?

**Comment by aethaniel** [comment]
I have a question to answer yours as you seem to be very demanding on various projects:
Why don't you provide any patch to help on missing features, Helmutt?

On 6 December 2015 12:22:45 CET, VogonJeltz <notifications@github.com> wrote:
>OMG, the TOP dated from October 2014  !!
>why hadn't it been fixed yet ?!?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arduino/Arduino/issues/2362#issuecomment-162304569

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by VogonJeltz** [comment]
I am a user, not a constructer.
Buying a Arduino I seemply expect it to work, like I expect buying a washing machine or a TV.
Or do you buy either one and then having no water pump or no tone on TV, 
and when complaining those issues at your seller getting to hear
"I have a question to answer yours as you seem to be very demanding on various projects: Why don't you provide any patch to help on missing features,aethaniel " ?!?

**Comment by aethaniel** [comment]
Hi,

Like many people, I personally think there is a delta between finished manufactured products and DIY Community boards, even very well branded.

Cheers,

T.


On 7 December 2015 15:07:00 CET, VogonJeltz <notifications@github.com> wrote:
>I am a user, not a constructer.
>Buying a Arduino I seemply expect it to work, like I expect buying a
>washing machine or a TV.
>Or do you buy either one and then having no water pump or no tone on
>TV, 
>and when complaining those issues at your seller getting to hear
>"I have a question to answer yours as you seem to be very demanding on
>various projects: Why don't you provide any patch to help on missing
>features,aethaniel " ?!?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/arduino/Arduino/issues/2362#issuecomment-162533061

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by VogonJeltz** [comment]
you may personally thin what you wish, but to me a Arduino Due is a finished manufactured product which is expected to work!

**Comment by NicoHood** [comment]
He is partly right.

Not everyone is able to patch those things (especially timer related stuff) hisself without reading up on this for hours. Even I do not know where to start, not even on avr. So he is probably right. And tone() is a basic API feature that should be added.

DYI is always incomplete and not perfect. Arduino is the best example, even though it tries to make stuff simple. But time passes, version changes, new boards come and not enough people are working on this. And the Arduino community which just uses the boards will never attempt to fix this. This is hard core.

So yeah, I'd vote for @VogonJeltz that someone fixes this, as its a basic feature like digitalWrite() etc. However I think @VogonJeltz should try to post a bit less aggressive here. Things wont change if you force them to do.

**Comment by VogonJeltz** [comment]
I agree, perhaps my posts appear  sort of harsh - if one didn't know te story before.

I am always  used to ask freindly and politely the first time, but if repetively there comes no answer or soething like "help yourself, don't expect others to do your homework" and the topic immediately gets closed  then the limit of my politeness has been quickly reached.

Finally tis tone issue is pending since the Due has been released, and even in this repository this issue has been successfully ignored since more than one year, nothing just silence in the forest. When would it be time then to slowly getting impatient?

**Comment by VogonJeltz** [comment]
BTW, if it's really time-related stuff:
why note set it up to DueTImer by attaching a free interrupt?

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#24
