### ISSUE TITLE
Nano 3.1 freezes after calling Wire.endTransmission

### ISSUE THREAD

**Issue by HanaJin** [arduino/Arduino#2363]
The Arduino Nano 3.1 board freezed when running the code below in 1.5.8 IDE.

![image](https://cloud.githubusercontent.com/assets/9121904/4634512/ffd52da2-53d0-11e4-80f5-a735e100576f.png)

The output seen is 

![image](https://cloud.githubusercontent.com/assets/9121904/4634457/79c43b54-53d0-11e4-985a-c0240ce2cdf2.png)

If comment out the endTransmission line, it no longer hangs.

The output seen with Wire.endTransmission commented out is 

![image](https://cloud.githubusercontent.com/assets/9121904/4634487/bba15fc0-53d0-11e4-9c27-5395c67cd3e0.png)

Is Wire library supported on Nano 3.1? If so, is this issue known?

**Comment by matthijskooijman** [comment]
This has been open for a long time, and I suspect there might be an error in the original poster's setup that caused this (that, or the fact that he starts a transmission without actually transmitting any data).

In any case, I'm closing this issue, feel free to reopen if needed.
