### ISSUE TITLE
Add support to Bus Pirate ISP programmer

### ISSUE THREAD

**Issue by ziotibia81** [arduino/Arduino#2383]
Sice version 5.8 AVRDude support Dangerous Prototypes Bus Pirate as ISP device.
Could be nice to have this programmer on Arduino IDE.

Here details about this programmer: http://dangerousprototypes.com/docs/Bus_Pirate_AVR_Programming

**Comment by cmaglie** [comment]
#2385 has already been merged, the programmer is supported.

**Comment by mbrodicky** [comment]
Dear, may I please ask to make buspirate available in the linux IDE? (I am using original ubuntu Software center)

**Comment by NicoHood** [comment]
This IDE is outdated and ubuntu wont update the software. Just download a recent version from arduino.cc

**Comment by mbrodicky** [comment]
Thanks NicoHood! I did download, but this version has also no bus pirate included,

**Comment by NicoHood** [comment]
It does. IDE 1.6.6 from arduino.cc

**Comment by mbrodicky** [comment]
Many thanks!
