### ISSUE TITLE
#include "tool tip" to identify the library / menu path 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2399]
This may be  a super long shot, but it seems that few people have an unnecessary challenge trying to make sure that the "library" they think they are using is for real. 
Would it be possible to add a "tool tip" ( to library Menu )  to identify the path of the library?

**Comment by ffissore** [comment]
Library manager implemented, library path confusion mitigated by b5367bcdbe236c5b771e0019b0170f42fbe89081 available since 1.6.3
