### ISSUE TITLE
Make sketch preprocessing optional

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#2406]
Right now, the IDE applies some preprocessing to sketches. In particular, it:

 1. Merges all .ino files
 2. Inserts `#include <Arduino.h>`
 3. Inserts forward declarations for functions

This preprocessing (especially point 3.) is messy and causes problems (#2304, #472, #386, #992, #455, #1735, #2289). We should work towards disabling it by default. The first step would be to make it optional (and allow a sketch author to opt-out of the preprocessing).

#1112 also suggested the same, using a  `#pragma` line in the source file to do the opt-out. I don't really like using a `#pragma`, since it's scary looking (and I'd really like to encourage novice users to disable this as well, perhaps disable it by default on new sketches at some point).

I was thinking it would be a good idea to introduce some sketch metadata, e.g. add a sketch.properties (similar to library.properties) file to a sketch that can define some metadata, this flag and in the future perhaps also library options, compiler flags, etc. This file could then be edited through a GUI in the IDE.

#2324 already has some code to disable preprocessing based on a global preference (but that PR still needs some more cleanup).

**Comment by ffissore** [comment]
Could the new preprocessor solve the issue? It's based on ctags, which understands c++, and coan, than cleans undefined sections of code.

If you wish to give it a try, the urls are:
http://arduino.cc/download.php?f=/arduino-preproc-linux32.tar.xz
http://arduino.cc/download.php?f=/arduino-preproc-linux64.tar.xz
http://arduino.cc/download.php?f=/arduino-preproc-windows.zip
http://arduino.cc/download.php?f=/arduino-preproc-macosx.zip
http://arduino.cc/download.php?f=/arduino-preproc-macosx-java-latest.zip

Code is available at https://github.com/ffissore/Arduino/tree/coanctags

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by ffissore** [comment]
New preprocessor available in nightly builds.
