### ISSUE TITLE
avr-gcc 4.8.1 bug: "unable to find a register to spill in class 'POINTER_REGS'"

### ISSUE THREAD

**Issue by xxxajk** [arduino/Arduino#2413]
Toolchain known bug in 4.8.1 and I hit it tonight.

error: unable to find a register to spill in class 'POINTER_REGS'
error: this is the insn:
(insn 212 211 213 33 (set (reg:HI 26 r26)
(reg/f:HI 194))
{*movhi}
     (nil))

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58545
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60040

Both 4.7.2 and 4.8.1 are known to have this problem.

**Comment by ffissore** [comment]
This one will be solved once https://github.com/arduino/toolchain-avr/issues/26 is closed. Stay tuned

**Comment by per1234** [comment]
It looks like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60040 was in fact not fixed by https://github.com/arduino/toolchain-avr/issues/26 and https://github.com/arduino/Arduino/issues/3972 goes into much more detail so I'm closing this as duplicate.
