### ISSUE TITLE
1.5.8. Nightly build Windows Nov 4 Serial does not name a type in multiple .ino 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2414]
First the error report : Serial does not name a type in multiple .ino 
Have three ino files and the second and third just prints etc.

Here is one test file text:

```
#pragma message("rebuilding for DUE using 1.5.8 ")
#pragma message( "Compiling " __FILE__ )
#pragma message( "Last modified on " __TIMESTAMP__ )

Serial.print("Hello");
```

Arduino: nightly (Windows XP), Board: "Arduino Due (Programming Port)"

C:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly/hardware/tools/gcc-arm-none-eabi-4.8.3-2014q1/bin/arm-none-eabi-g++ -c -g -Os -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/libsam -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/CMSIS/CMSIS/Include/ -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/CMSIS/Device/ATMEL/ -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\cores\arduino -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\variants\arduino_due_x C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build7912510807317996349.tmp\sketch_nov04a.cpp -o C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build7912510807317996349.tmp\sketch_nov04a.cpp.o 

sketch_nov04a.ino:8:2: error: #error STOP
sketch_nov04a.ino:3:50: note: #pragma message: rebuilding for DUE using 1.5.8 
sketch_nov04a.ino:4:40: note: #pragma message: Compiling sketch_nov04a.ino
sketch_nov04a.ino:5:52: note: #pragma message: Last modified on Tue Nov 04 23:14:28 2014
Test.ino:1:50: note: #pragma message: rebuilding for DUE using 1.5.8 
Test.ino:2:40: note: #pragma message: Compiling Test.ino
Test.ino:3:52: note: #pragma message: Last modified on Tue Nov 04 23:14:28 2014
Test.ino:6:1: error: 'Serial' does not name a type
hello.ino:1:50: note: #pragma message: rebuilding for DUE using 1.5.8 
hello.ino:2:40: note: #pragma message: Compiling hello.ino
hello.ino:3:52: note: #pragma message: Last modified on Tue Nov 04 23:14:28 2014
hello.ino:5:1: error: 'Serial' does not name a type
Error compiling.

Second report - but it compiles nicely and fast ( thanks for all the work) EXECEPT on first pass / access 

Build options changed, rebuilding all

It just sits on this line until it is all done - than it prints progress and errors (because I have not added printf yet).  

Using library Wire in folder: C:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\libraries\Wire 
Using library LiquidCrystal in folder: C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal (legacy)

C:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly/hardware/tools/gcc-arm-none-eabi-4.8.3-2014q1/bin/arm-none-eabi-g++ -c -g -Os -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/libsam -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/CMSIS/CMSIS/Include/ -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\system/CMSIS/Device/ATMEL/ -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\cores\arduino -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\variants\arduino_due_x -IC:\Documents and Settings\Vaclav\My Documents\Downloads\arduino-nightly-windows\arduino-nightly\hardware\arduino\sam\libraries\Wire -IC:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build7912510807317996349.tmp\Audio_DUE_25.cpp -o C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build7912510807317996349.tmp\Audio_DUE_25.cpp.o 
Audio_DUE_25.ino:48:50: note: #pragma message: rebuilding for DUE using 1.5.8 
Audio_DUE_25.ino:49:40: note: #pragma message: Compiling Audio_DUE_25.ino

......

**Comment by cmaglie** [comment]
Closing as invalid for now, feel free to reopen if you can provide more information.
