### ISSUE TITLE
FYI  #error and #warning on Nightly build 1.5.8

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2415]
Just minor stuff
The #error does not stops compiler - it should , right? It works on "regular " 1.5.8 stopping the compiler
#warning gets not reaction from compiler - on both Nightly ( Nov 4) and regular 1.5.8. It should just print the message attached.

**Comment by ffissore** [comment]
#error does indeed stop the compiler (at least with 1.6.3)
I've added a new preference "show all compiler warnings" that turns warnings on
Available as nightly builds in the next few hours

**Comment by VaclavSal** [comment]
Thanks for your work.

I am not sure why a semi-serious developer AKA coding more that "blink LED" would NOT want all helpful stuff from compiler. 
But that is why we have "defaults" , right?

Thanks again.
