### ISSUE TITLE
Endless selfreference library path and can't delete folder

### ISSUE THREAD

**Issue by BillWenChaoJiang** [arduino/Arduino#2423]
if you accidently try to add the library folder as a new library(even though you are suppose to add some folder inside the library folder). Then it creates the another library folder within the existing one, and another.... i endup have endless nested folder with file name too long and can't delete

**Comment by F8VPE** [comment]
I've runned into the same problem, you cannot delete the folder because the list is too long all the way to the end.
Rename all the folders into 1 letter names and the list wiil be shorter so you may be able to delete the range. (Will cost some time)

**Comment by ffissore** [comment]
Same as #2861. Fixed in 587590968356aeafb7b587ff16f6efad26e95bec. Fix available with 1.6.5 http://arduino.cc/en/Main/Software
