### ISSUE TITLE
Rename file dialog gets stuck  during compile time (1.5.8 Nov4) 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2426]
During compiler "pregnant pause", before it starts verbose output , ( about 1/4 of compile time)  I can "Rename" UNUSED file but the modal dialog gets stuck thus covering the compiler progress bar. 
It stays that way after the compiler is finished and any attempt to rename another file is blocked by it. No response. Perhaps I am pushing the IDE too far? 

![dialog](https://cloud.githubusercontent.com/assets/6053260/4964219/73c1790c-6716-11e4-8c41-6e054e527d3d.JPG)

**Comment by ffissore** [comment]
Same problem reported in #666. Fixed. Fix is already available with the hourly build http://www.arduino.cc/en/Main/Software#hourly
