### ISSUE TITLE
Intrinsic bug in getCaretLocation of CompositionTextPainter class

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#2429]
To get the screen Y offset, the following equation is used.

loc.y = lineIndex * fm.getHeight() + offsetY; 

But the linIndex is not the screen Y line number, it is the source line number. To get the screen Y offset, the actual source line number of the first screen line should be subtracted from the current source line number. So it should be changed to the following:

loc.y = (lineIndex - textArea.getFirstLine()) * fm.getHeight()  + offsetY;

**Comment by facchinm** [comment]
Hi @Myriads, does this also occurs using latest nightly (http://arduino.cc/download.php?f=/arduino-nightly-windows.zip) ? The new editor solved a lot of similar problems (and maybe also yours :wink: )

**Comment by ffissore** [comment]
#3223 reports a working editor, despite having a misplaced caret
