### ISSUE TITLE
New program won't overwrite older one

### ISSUE THREAD

**Issue by jorridius** [arduino/Arduino#2432]
I just bought an Arduino Robot and when I connected it for the first time it worked perfectly, but when I tried to upload a new script, the arduino sketch said it couln't connect/upload to the selected board (I made sure it was the right board and tried again, but nothing changed). So I downloaded Ubuntu, and yes, it worked. But now there's another problem, the new program won't overwrite the older one. I tried resetting the Robot, but it had the same result.

Any suggestions?

**Comment by matthijskooijman** [comment]
@jorridius, is this still happening for you? If so, please provide the verbose output. If not, please close this issue.
