### ISSUE TITLE
Question - Is it "normal" to run 100% CPU on Windoze when compiling Due ?

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2438]
For over a minute  1.5.8.  takes over the PC (100 % CPU - all javaw ) practically stopping anything "multitasking", it almost looks as it stops / compete with itself - got several  same  "cannot delete ..tmp.."  file  in few seconds apart while nothing else in running.
100% CPU does not mean most efficient, it may be sign of trouble. .

**Comment by ffissore** [comment]
Yes, gcc will use your CPU at its maximum, until it will finish compiling
