### ISSUE TITLE
SD Library not working with FAT16

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#2443]
Initializing the volume and running the CardInfo example works fine, but reading files does not work. Instead of the actual file contents, I get some random garble (mostly spaces) of the correct length. I tried this using the DumpFile example.

I suspect that the block lookup for FAT16 might be wrong. Looking at [this piece of code](https://github.com/arduino/Arduino/blob/ide-1.5.x/libraries/SD/src/utility/SdFile.cpp#L682-L684), I can't imagine that being correct.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#8
