### ISSUE TITLE
 FYI Could not replace file...1.5.8 Nov 3 on XP 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2445]
Here is a partial output I started getting after adding another local ( my class) header file.
It may be nothing , but may be of interest to someone.
It generally goes away after I make some changes and verify / upload. 
The app runs normal, no problems.
 
I have deleted some parts which behave "normal". 
I am trying to find why it takes so long for the compiler to start printing the verbose messages and so far after having five active local headers it pauses right after the pragma message ( to only one ) before I get "using previously compiled file...." 

Arduino: nightly (Windows XP), Board: "Arduino Due (Programming Port)"

java.io.IOException: Could not replace C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\C_Image.h

	at processing.app.Base.saveFile(Base.java:2901)

	at processing.app.Sketch.preprocess(Sketch.java:1407)

	at processing.app.Sketch.preprocess(Sketch.java:1306)

	at processing.app.Sketch.build(Sketch.java:1584)

	at processing.app.Sketch.exportApplet(Sketch.java:1610)

	at processing.app.Sketch.exportApplet(Sketch.java:1596)

	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2392)

	at java.lang.Thread.run(Unknown Source)

processing.app.debug.RunnerException: Problem moving C_Image.h to the build folder

	at processing.app.Sketch.preprocess(Sketch.java:1410)

	at processing.app.Sketch.preprocess(Sketch.java:1306)

	at processing.app.Sketch.build(Sketch.java:1584)

	at processing.app.Sketch.exportApplet(Sketch.java:1610)

	at processing.app.Sketch.exportApplet(Sketch.java:1596)

	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2392)

	at java.lang.Thread.run(Unknown Source)

Problem moving C_Image.h to the build folder

Using library Wire in folder: C:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\libraries\Wire 

Using library LiquidCrystal in folder: C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal (legacy)

Using library USBHost in folder: C:\Program Files\Arduino_All\arduino-nightly_Nov4\libraries\USBHost 

C:\Program Files\Arduino_All\arduino-nightly_Nov4/hardware/tools/gcc-arm-none-eabi-4.8.3-2014q1/bin/arm-none-eabi-g++ -c -g -Os -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/libsam -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/CMSIS/CMSIS/Include/ -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/CMSIS/Device/ATMEL/ -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\cores\arduino -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\variants\arduino_due_x -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\libraries\Wire -IC:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\libraries\USBHost\src C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\A_Project_3.cpp -o C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\A_Project_3.cpp.o 

A_Project_3.ino:3:29: note: #pragma message: Empty INO

THIS IS WHERE THE COMPILER PAUSES 

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\Wire\Wire.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\FastIO.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\I2CIO.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LCD.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LiquidCrystal.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LiquidCrystal_I2C.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LiquidCrystal_SR.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LiquidCrystal_SR2W.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\LiquidCrystal\LiquidCrystal_SR3W.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\USBHost\adk.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\USBHost\hid2.cpp.o

Using previously compiled file: C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build4216374743901224023.tmp\USBHost\hidboot.cpp.o

Using previously compile.....

**Comment by ffissore** [comment]
This could also be due to a file name clash. If so, latest hourly should fix it: core, libs and sketch are compiled in their own folders.
