### ISSUE TITLE
YAII - yet another include issue - just annoying so far  

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2454]
It is probable this has been brought-up before, so if this is dupe , my apology.
Importing improperly formatted ( IDE does not like it for whatever reason)  library from windows directory where it was downloaded results in 

BLANK LINES added to INO file - no #includes etc. 

The "system"  , either IDE or compiler is "doing something" and it must be convinced it is useful. 
AKA A. Cooper's "dancing bear" . 

Could someone volunteer to do something about this "bear" ?  No hurry.

**Comment by ffissore** [comment]
Fixed with b2f8b9b6c16d9ab3eeca25ba8082128a08b47ef7 available in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
