### ISSUE TITLE
Inconsistent behaviors of analogWrite and pinMode on Due and Uno

### ISSUE THREAD

**Issue by HanaJin** [arduino/Arduino#2455]
I connected an RC circuit between D3 and A1 pins. Basically, D3 is connected to a 100K resistor, then to a 1uF capacitor. The voltage drop on the capacitor is measured on pin A1. 

With the code below, I get reasonable readings on Uno R3. 
![image](https://cloud.githubusercontent.com/assets/9121904/5076367/7370cb2a-6e68-11e4-90dc-8797d86ff842.png)

However, using a Due and the same code, after changing the pinMode to INPUT and then OUTPUT manually, analogWrite stopped working as shown below. You can rule out the malfunctioning of analogRead as I had confirmed that using a DMM.

![image](https://cloud.githubusercontent.com/assets/9121904/5076436/dd49ba70-6e68-11e4-97e3-f803502efec4.png)

Is this behavior expected on Due? Which mode should I set it to for PWM on the Due to make it work?

**Comment by facchinm** [comment]
Hi @HanaJin , sorry for the late response.
Switching analog/digital functions on the same pin on a Due is not straightforward as with a UNO because, at platform level, we need some hacks to achieve maximum performances (as you can see in issue #3064 ). Issue #2198 is also probably related.

Anyway, from your sketch I can't see any `pinMode(OUTPUT)` in the real code, so how is it supposed to work?

**Comment by hanabanana** [comment]
Hi @facchinm, thanks for your response. Sorry that I took the screenshot of the wrong sketch. There was a line between line 17 and 18 that is 'pinMode(3, OUTPUT);' for both sketches. 
I agree that this is probably related to issue #2198 and #3064. But one thing still odd to me is that, if the analogWrite indeed locks up the resource even after pinMode is called, shouldn't the following analogWrite calls remain functioning properly? As you can see, I am only checking for analog functionality in the sketch before and after the pinMode calls.
It seems to me that the subsequent calls of pinMode actually does something that breaks the analogWrite functionality of the pin.

**Comment by shimizutko** [comment]
/*
 Date: July.16,'15

 Arduino Sketch bug check: The first PWM ON duty is unstable bug TEST.
 This is for "Arduino ATMega328 16MHz" as Arduino Pro mini., UNO and others
 
 How To Test:
 1) Compile & upload code to Arduino board.
 2) Use oscilloscope at D3 port. Y:2V/div, X:1mS/div, +trigger. 

 Tool chain:  Arduino softwares
 Command Line:   None
 Release 0.1
 */
//-------------------------------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
const int INL_C_PWM = 3; // PWM pin D3
const int LED = 13;
//-----------------------------------------------------------------------------
// Global VARIABLES
//-----------------------------------------------------------------------------
void setup()
{
  pinMode(INL_C_PWM, OUTPUT);
  digitalWrite(INL_C_PWM, 0); // init OFF

  pinMode(LED, OUTPUT);
}
//-----------------------------------------------------------------------------
// MAIN Routine
//-----------------------------------------------------------------------------
void loop()
{
  digitalWrite(LED, 0);
  analogWrite(INL_C_PWM, 0); // analogWrite values from 0 to 255
  // digitalWrite(INL_C_PWM, 0); // port OFF
  delay (100); // any delay time for retrigger
  digitalWrite(LED, 1);
  // The first PWM ON duty is unstable Sketch bug is here
  analogWrite(INL_C_PWM, 1); // analogWrite values from 0 to 255
  delay (6); // any delay time 
  analogWrite(INL_C_PWM, 200); // analogWrite values from 0 to 255
  delay (3); // any delay time 
}
// End Of File

**Comment by facchinm** [comment]
Solved by #3524
