### ISSUE TITLE
Ms Surface Pro 3 Upload Failure

### ISSUE THREAD

**Issue by jimbluesa** [arduino/Arduino#2463]
I just got a Surface Pro 3. Everything Arduino seems fine (compiling, the monitor), but when I try to upload the program, I get a write error. THis doesn't happen on my laptop, just the Surface. I checked the driver and com port and can't find anything out of order. THe monitor works fine communication with the arduino. It just won't upload.
After compiling, upload fails immediately with :
"avrdude: ser_send(): write error: sorry no info avail"

Only with Surface. Works fine with Dell laptop and desktop.

**Comment by ffissore** [comment]
Can't reproduce
