### ISSUE TITLE
OT - is this normal? Compiler error printout starts at #error directive 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2468]
I am posting this here because it may have something to do with #error not stopping compiler as reported earlier ( 1.5.8 Nov 4 release ) .

My ino file includes A_Main.h header and that includes other headers - it WORKS the way I want it, no issue there.
I have a bug somewhere and I have put #error STOP and the entry of the A_Main.
It gets displayed as a FIRST entry in the output and than followed by  #pragma messages
and finally by a real error which stops the compiler.

I would expect the #pragma messages FIRST - they all come from headers included BEFORE the A_Main header and that as last the #error STOP. No so. Sure makes debugging a challenge since the printout is not in expected sequence / order. 
Or am I all wet and it is in correct printout  sequence?  

Build options changed, rebuilding all
Using library USB_LIBRARY in folder: C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY (legacy)
Using library Wire in folder: C:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\libraries\Wire 
Using library LiquidCrystal in folder: C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal (legacy)
Using library USBHost in folder: C:\Program Files\Arduino_All\arduino-nightly_Nov4\libraries\USBHost 

C:\Program Files\Arduino_All\arduino-nightly_Nov4/hardware/tools/gcc-arm-none-eabi-4.8.3-2014q1/bin/arm-none-eabi-g++ -c -g -Os -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/libsam -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/CMSIS/CMSIS/Include/ -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\system/CMSIS/Device/ATMEL/ -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\cores\arduino -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\variants\arduino_due_x -IC:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\hardware\arduino\sam\libraries\Wire -IC:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\LiquidCrystal -IC:\Program Files\Arduino_All\arduino-nightly_Nov4\libraries\USBHost\src C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build3012088613117182121.tmp\a_Project_24.cpp -o C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build3012088613117182121.tmp\a_Project_24.cpp.o 
In file included from a_Project_24.ino:243:0:
C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build3012088613117182121.tmp\A_MAin.h:5:2: error: #error STOP
 #error STOP 
  ^
In file included from a_Project_24.ino:64:0:
C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/board.h:52:47: note: #pragma message: Standard board header file.
 #pragma message ("Standard board header file.")
                                               ^
C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/board.h:53:76: note: #pragma message: #define BOARD ARDUINO_DUE_X  definition here in board.h 
 #pragma message ("#define BOARD ARDUINO_DUE_X  definition here in board.h ") 
                                                                            ^
In file included from C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/board.h:68:0,
                 from a_Project_24.ino:64:
C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/compiler.h:49:74: note: #pragma message: Commonly used includes, types and macros.   compiler.h
 #pragma message ("Commonly used includes, types and macros.   compiler.h")
                                                                          ^
In file included from C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/compiler.h:230:0,
                 from C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/board.h:68,
                 from a_Project_24.ino:64:
C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/interrupt.h:50:39: note: #pragma message: Interrups disabled 
 #pragma message ("Interrups disabled ") 
                                       ^
In file included from a_Project_24.ino:64:0:
C:\Documents and Settings\Vaclav\My Documents\Arduino\libraries\USB_LIBRARY/board.h:237:51: note: #pragma message: Arduino board defined as board 
 #pragma message ("Arduino board defined as board ") 
                                                   ^
In file included from a_Project_24.ino:243:0:
C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build3012088613117182121.tmp\A_MAin.h: In function 'boolean TRACE_Test()':
C:\DOCUME~1\Vaclav\LOCALS~1\Temp\build3012088613117182121.tmp\A_MAin.h:85:3: error: 'lcm1602' was not declared in this scope
   lcm1602.init();
   ^
Error compiling.

**Comment by ffissore** [comment]
Closing as gcc related, not IDE
