### ISSUE TITLE
Arduino Nano v3.0 Will not connect to computer via USB port

### ISSUE THREAD

**Issue by hjking0** [arduino/Arduino#2480]
After having 2 different  nano  boards connect one time to the computer with no problem. in subsequent times plugging in it computer says it cant find drivers. Tried reloading drivers from multiple places..no luck. Emailed FTDI and asked for their help. after running a troubleshooting program they said that the FTDI chip was counterfiet.. This chip is on a Genuine Arduino board.. Tried boards on multiple computers no luck.  I see many posts in forums so I am obviously not the only person having this problem.

Any help would be appreciated

**Comment by jogo-** [comment]
Is your Nano using the FTDI FT232RL or the CH340G "clone" ?

**Comment by leongeyer** [comment]
For the nanoclone on OS10.10, installing FTDIs drivers (which I didnt need for the UNO) didn't work, this worked for me:  

download the driver http://www.wch.cn/download/CH341SER_MAC_ZIP.html
sudo nvram boot-args="kext-dev-mode=1"
then reboot, not before

for more data and explanation here my sources:
http://arduino.stackexchange.com/questions/5119/arduino-nano-no-serial-port-for-macbook-air-2013
and http://kiguino.moos.io/2014/12/31/how-to-use-arduino-nano-mini-pro-with-CH340G-on-mac-osx-yosemite.html

**Comment by sandeepmistry** [comment]
Closing as this is not related to an Arduino product.
