### ISSUE TITLE
Arduino on Ultra HD display is very small

### ISSUE THREAD

**Issue by digifriend** [arduino/Arduino#2483]
I have downloaded Arduino 1.0.6. and 1.5.8 to my new Windows 8.1 Notebook.
But the editor content does not scale to the Ultra HD display.
How can I manage to write a program without using a magnifying glass.

**Comment by cmaglie** [comment]
@digifriend 
Please look #2776 for a possible solution and, if you can, try it and report back there if it works for you.

Closing ad duplicate of #2776
