### ISSUE TITLE
1.6.0 error verbose output - a tiny small bug. 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2484]
The 1.6.0.Nov 29 has a tiny, small problem when LARGE amount of errors are generated - the "normal - white "  "error header" is missing, So the printout starts with first reported error.
 
Here is sample copied using "copy error messages"  which shows the missing header line OK.

Arduino: 1.6.0 (Windows XP), Board: "Arduino Due (Programming Port)"

#error STOP 

.... I have deleted all of the errors here  - about 200 + lines 

Error compiling.

If someone  will work on this , how about AUTOMATICALLY scroll to the first error line? 
Seems logical  IMHO, but I am a lousy / lazy coder. 

BTW thanks for speeding up the verbose  output, nice job!

**Comment by ffissore** [comment]
Fixed with 4c9e5fc56416386a5db90fa567d872ac2907ee26, available since 1.6.4
