### ISSUE TITLE
Selection in board sub-menus (e.g. "processor") doesn't update status bar text.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2494]
For example, if you select "LilyPad Arduino" from the Tools > Board menu, "LilyPad Arduino, ATmega328" appears in the editor status bar. If you then select "ATmega168" from the Tools > Processor menu, the text doesn't change. The IDE appears to use the right processor when compiling, but shows the wrong text in the status bar.

**Comment by ffissore** [comment]
Fixed with #2675 since 1.6.3

**Comment by m-ri** [comment]
Ciao amico!

Ho letto molto sull’argomento di cui abbiamo  discusso nella nostra ultima conversazione e  ho trovato  un  sacco  di momenti interessanti, leggine di  più qui <http://vanni.whatthewonton.com/dhvq>

Più tardi, marco ribero

**Comment by m-ri** [comment]
Ei!

So che stavi cercando quella roba da molto,  quindi  credo di averla trovata, dai  un'occhiata qui <http://orazio.liseljane.com/cnxo>

Saluti,marco ribero
