### ISSUE TITLE
Bitwise AND online documentation page error?

### ISSUE THREAD

**Issue by Deweywsu** [arduino/Arduino#2496]
Sorry if I'm posting this in the wrong place.  On the online documentation page for the bitwise AND operator at http://arduino.cc/en/Reference/BitwiseAnd, in the second paragraph under "Example Program", the text says:

"So if we write PORTD = B00110001; we have made pins 2,3 & 7 HIGH."

Isn't that backwards?  (The author counted the pins from left to right, not right to left).  Shouldn't it read "we have made pins 0,4 & 5 HIGH."?

**Comment by agdl** [comment]
@PaulStoffregen you are right. I added that the example is referred to an Arduino UNO
