### ISSUE TITLE
analogReference(EXTERNAL) doesn't work on Arduino(ATMega328)

### ISSUE THREAD

**Issue by jbarfod** [arduino/Arduino#2502]
on ATMEGA328 default analog reference (5V) and INTERNAL analog reference (1.1V) do Work as expected but an external analog refrence on AREF (ATMEGA328 pin21) does not Work an generates AD outputs of 1023, no matte. the input (appears as if internal analog reference is zero volts).

Board is UNO rev 3 and  the IDE is 1.0.6 for Windows.
2 UNO boards were tested - same result.

Can anybody help?

Jesper Barfod

**Comment by agdl** [comment]
I tried it and it works. I'm closing this. Try on the latest Arduino IDE
