### ISSUE TITLE
ArduinoToBreadboard:Breadboard.zip file not working

### ISSUE THREAD

**Issue by Clemtaur** [arduino/Arduino#2505]
Unziping the file gives you only a text (.txt) file, not a Folder as described in the instruction page..

I tried placing this text file in a Folder named 'hardware' in my sketch directory, then into the library sub directory, Restarting each time.   Did not have the 'ATMEGA on a breadboard' show up in the 'Tools > Board' menu at any time..

 Not sure which version of the IDE I'm using;  window header has 'Arduino 1:1.0.5+dfsg2-2'
running under Ubuntu 14.04

**Comment by agdl** [comment]
@Clemtaur please take a look here
http://arduino.cc/en/Tutorial/ArduinoToBreadboard

**Comment by ReDetection** [comment]
@agdl try to investigate issue before posting just a link.
@Clemtaur you'd better post a link where you found this. but thanks to @agdl, he found and posted.
If you try to check other subfolders in hardware folder in the Arduino installation path, you find that boards.txt is placed into avr subfolder. So the path to the txt file should look like hardware/anynamefolder/avr/boards.txt. After restart you will find new board in the menu.
And it could work if you're lucky to have fuse bits programmed to respect your board configuration (clock source and speed I mean). But if it's not — you need to program them, to do this in arduino you need to burn bootloader, right before bootloader arduino will correct the fuses.

**Comment by Clemtaur** [comment]
@ReDetection >"post a link where you found this."  Ta.  will do so next time  (neub mistake on my part.)    
The boards.txt file for the linux version seems to be in > ./usr/share/arduino/hardware/arduino  I apended the downloaded boards.txt to it using sudo, as it's read only  (overwriting seemed a bad idea to me as, if i'm reading this right, that would leave me with just the one option that I'm trying to install) and that seemed to work.  i.e. the apperance of the new board in Tools> Board menu.  The files referanced in the board.txt addition all exist in their various folders so I'm hopeful this will work now.  I won't get to testing it until sunday, so..   :D

**Comment by agdl** [comment]
It is ok now for both the arduino 1.0.x & 1.5.x
