### ISSUE TITLE
Bug in   Stream::findUntil    when stream contains NUL (0x00) characters

### ISSUE THREAD

**Issue by trickedj** [arduino/Arduino#2507]
findUntil, used also by 'find' in 'Stream' and 'Serial', has a bug if the received data being searched contains NUL (0x00) characters.

Line 105 in stream.cpp is currently 
          while( (c = timedRead()) > 0){
The intention is that the while loop is executed as long as characters are being received but exits on timeout. However as it is currently written, a received zero character will be interpreted as a timeout.
The fix is to make the compare >= IE
          while( (c = timedRead()) >= 0){

This affects all versions of the IDE up to 1.5.8 in both the AVR and SAM core

**Comment by Chris--A** [comment]
Resolved: https://github.com/arduino/Arduino/commit/f43a7a698ee04900772b116d896462b46cdb7926
