### ISSUE TITLE
Update Servo library for more standard default pulse widths

### ISSUE THREAD

**Issue by bhuang10000** [arduino/Arduino#2509]
The Servo library uses a default pulse width of 544 uS to 2400 uS -- with a zero/neutral position at 1472 uS? 

This does not coincide with any standard servos that I've seen. Most servos (like HiTech or other generic ones) operate on a rage from 900 uS to 2100 uS with a neutral position (90 deg) at 1500 uS. The "default pulse width" is set to 1500, but this is not the same as 90 degrees on the servo.

Suggest changing the default settings to align with 900 uS and 2100 uS --

#define MIN_PULSE_WIDTH       900     // the shortest pulse sent to a servo  
#define MAX_PULSE_WIDTH      2100     // the longest pulse sent to a servo 
#define DEFAULT_PULSE_WIDTH  1500     // default pulse width when servo is attached

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Servo#3
