### ISSUE TITLE
Error while downloading Arduino IDE 1.0.6

### ISSUE THREAD

**Issue by prajeshv** [arduino/Arduino#2514]
Hi,
I've been trying to download Arduino IDE 1.0.6 for the last one week, to program my Arduino board provided by Electrono Solutions Pvt. Ltd. Even though I've used multiple browsers, and tried it various different times, I'm not able to download the software completely. My last attempt using IE 8.0 resulted in the error shown in the attached image.
![untitled](https://cloud.githubusercontent.com/assets/10305230/5557887/30a0a534-8d37-11e4-9158-c106ac426e2a.PNG)

Appreciate if you could please help me at the earliest.

**Comment by Ramoonus** [comment]
your download seems corrupt

**Comment by prajeshv** [comment]
Yeah, but the file on Arduino's site seems to be corrupted; I've tried to
download this multiple times. Doesn't work!

**Comment by ffissore** [comment]
1.0.6 is out since 7th of November and this is the first report we see. It's likely a problem on your side: may be a network quality issue, full disk..

**Comment by PaulStoffregen** [comment]
I just downloaded arduino-1.0.6-windows.exe and ran the installer on a fresh XP virtual machine.  It works fine.

![sc](https://cloud.githubusercontent.com/assets/965463/5595628/fe78bb5a-922c-11e4-97bd-8fc6567dee46.png)

The file size for arduino-1.0.6-windows.exe is 55139088 bytes.

The MD5 sum is 4c152fdac58cf7b0923117e2471eed58
The SAH1 sum is a3aef05b94633b306431104f114c79347101604a

**Comment by AbstractBeliefs** [comment]
Multiple users today reporting the same problem for Mac 1.0.6.
Personally I have seen the following:
* zip truncated at 30MB
* HTTP 503
* HTTP 500

All of these were available on Win7 Enterprise with Chrome 39.0.2171.95 m.
Casual testing with Firefox and Safari on Mac also show errors.

**Comment by Ramoonus** [comment]
this seem to be webserver issues, not related to the source code

Gareth Pulham schreef op 7 jan '15: 

> Multiple users today reporting the same problem for Mac 1.0.6.
> Personally I have seen the following: 
> 
> * zip truncated at 30MB
> * HTTP 503
> * HTTP 500
> 
> All of these were available on Win7 Enterprise with Chrome 39.0.2171.95 m.
> Casual testing with Firefox and Safari on Mac also show errors. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/arduino/Arduino/issues/2514#issuecomment-69032778

**Comment by AbstractBeliefs** [comment]
@Ramoonus Agreed, I don't think this is the right place for this, but there's not anywhere I know of for issues specific to infra, and this is already a discussion on the matter that has engaged a member of the Arduino core team ( @ffissore ).

**Comment by ffissore** [comment]
Our storage provider finally replied: they confirmed and solved a problem with their systems.
