### ISSUE TITLE
Two errors on the Arduino GSM Shield guide

### ISSUE THREAD

**Issue by michaelshiloh** [arduino/Arduino#2515]
On page arduino.cc/en/Guide/ArduinoGSMShield

1) The link to the modem documentation in "Making voice calls" seems to be broken: http://www.auroramobile.ru/content/files/pdf/queltec/m10_hd_v1.01.pdf

2) At the very bottom, the reader is referred to "See the hardware page for more information about the shield itself." However this is in fact the hardware page for the shield and so it currently points at itself. Before deleting this sentence, I wanted to find out whether this was intended to refer to something else

**Comment by agdl** [comment]
@michaelshiloh are there any news?

**Comment by michaelshiloh** [comment]
haven't had time yet. busy setting up for TEI15.

**Comment by agdl** [comment]
up
