### ISSUE TITLE
"Bootloader Development" contains a link to itself; in fact the page is woefully out of date

### ISSUE THREAD

**Issue by michaelshiloh** [arduino/Arduino#2517]
At the top of "Bootloader Development" (arduino.cc/en/Hacking/Bootloader) it says "See this page for an explanation of what a bootloader is and why we're using one. " but the link under "this page" is redirected to this same page. Either fix the link to point at the correct document or, if it no longer exists, remove the sentence.

While you're at it, the page seems to have been last updated for the ATmega168. At least the 328 should be added, and ideally the the 32U4 as well.

**Comment by agdl** [comment]
@michaelshiloh please do it and tell me when I can close this issue.

**Comment by agdl** [comment]
i modified the sentence just to make a long story short
