### ISSUE TITLE
Arduino does not respond after uploading.

### ISSUE THREAD

**Issue by Nick-Zhang1996** [arduino/Arduino#2520]
Bug appears both on 1.5.X and 1.0.6. After uploading my program, arduino does not work as expected. Instead, the led blinks at about 1Hz. The program includes UTFT library and a number of pictures converted to .c array.

Platform OSX 10.9
Arduino verion 1.5.x 1.0.6
board: Mega 2560

**Comment by ffissore** [comment]
Please be more specific. What do you expect your arduino to do and what error messages or misbehaviours do you see? Please provide a like to your whole sketchbook (as you're using a library).

Be aware that github issues are intended for reporting bugs on the Arduino software. You should probably ask your question on the [arduino forum](http://forum.arduino.cc/).

**Comment by sandeepmistry** [comment]
This is quite old and requested information has not been provided in over a year. I'm closing for now, please re-open with requested information if you are still interested.
