### ISSUE TITLE
Library 1.5 Specification should be more clear about Keywords

### ISSUE THREAD

**Issue by jbdatko** [arduino/Arduino#2521]
The Library [specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification) for 1.5 is not very clear concerning "keywords" and simply says the following without any link:

>The list of highlighted keywords must be placed in a file called keywords.txt. The format of this file is the same as the 1.0 libraries

I did not realize this meant keywords for ***syntax highlighting*** until I found this blog [post](http://acsweb.ucsd.edu/~sbliven/2012/01/arduino-ide-keywords/). 

I recommend adding a statement about syntax highlighting and/or linking to the 1.0 keyword semantics.

**Comment by NicoHood** [comment]
Is this not clear for you? If so, why not edit it? It is a free wiki and it seems you are allowed to edit.

Keywords

The list of highlighted keywords must be placed in a file called keywords.txt. The format of this file is the same as the 1.0 libraries

Servo/keywords.txt

**Comment by jbdatko** [comment]
I have no problems editing the wiki and I probably just should. However, I wasn't sure of the workflow. I figured it'd be nice to have an issue to reference the "why" behind the change.

I'll edit the wiki, link the editing text back here and then close the issue.

**Comment by agdl** [comment]
Hi to all! Arduino has a new theme so all the keywords should be updated according to this
https://github.com/arduino/Arduino/blob/master/build/shared/lib/theme/theme.txt
