### ISSUE TITLE
Incorrect comment in Arduino.h

### ISSUE THREAD

**Issue by michaelshiloh** [arduino/Arduino#2524]
Arduino.h line 159 says: 

"... // This comes from the pins_*.c file ..."

In fact I believe they come from pins_*.h, for example pins_arduino.h

This can be assigned to me

Michael

**Comment by agdl** [comment]
@michaelshiloh will you make a PR?

**Comment by michaelshiloh** [comment]
Sure! What's a PR?

**Comment by agdl** [comment]
It is a pull request. In this way your changes can be merged in the origin repository

**Comment by michaelshiloh** [comment]
Oh! Of course.
