### ISSUE TITLE
make an arduino due-ethernet

### ISSUE THREAD

**Issue by sxpert** [arduino/Arduino#2535]
Considering the chip has an embedded ethernet device, how about moving the reset button somewhere else, and add the necessary components to have a native ethernet, which would give much better performance than the ethernet shield...

**Comment by ckglobalroaming** [comment]
that sounds very good, endorsed.

**Comment by PaulStoffregen** [comment]
Who's going to write the Ethernet library for Due's MAC?

**Comment by ckglobalroaming** [comment]
As far as I am aware you Paul are the expert on this subject given your excellent Teensy products.

**Comment by cmaglie** [comment]
Thanks for the suggestion, but the software layer is going to be very complex.
IIRC some Due-derivative boards with the Ethernet on board was made but didn't had much follow up.
