### ISSUE TITLE
faults in arduino uno schematic

### ISSUE THREAD

**Issue by nmt89** [arduino/Arduino#2553]
Hello,

I don't want to sound like a know it all and to be honest I have never really reported a bug. However I want to support this project in any way I can, so here are the errors I found:

1) fuse F1 - wrong symbol
2) wire drawn to long
3) +5V is labeled twice

...marked them in red.

![arduino_uno_rev3-schematic_errors](https://cloud.githubusercontent.com/assets/10571729/5788410/36714b5e-9e34-11e4-9313-253fbb3a21db.png)

**Comment by bobc** [comment]
I wouldn't say those are errors, just cosmetic changes. It's clear what the design intent is.

**Comment by nmt89** [comment]
yeah, that's true. But still, I thought it would be worth reporting...

**Comment by cmaglie** [comment]
Thanks for the report, but we are not going to change the schematics (everyone has their own taste...).
