### ISSUE TITLE
#include finds (cached?) versions of files not on include path.

### ISSUE THREAD

**Issue by KimSJ** [arduino/Arduino#2559]
To demonstrate this bug:

1. Create two BareMinimum projects, e.g. "With" and "Without"

2. In the "With" directory, touch test.h

3. Add "#include test.h" to both projects.

4. Attempt to verify the "Without" project. This will give an error

5. Verify the "With" project (which should succeed) then verify "Without" again. This time the verify will succeed.

**Comment by facchinm** [comment]
As of 1.6.5 (master), the faulty behaviour is no longer present, and the "Without" project refuses to build for the lack of the header, no matter if the "With" project has been compiled before.
Thanks for reporting!
