### ISSUE TITLE
Ver 1.0.4 SD library, Available function return value is integer, should be long int

### ISSUE THREAD

**Issue by Stanley-K** [arduino/Arduino#2561]
I don't know if this has been reported but I thought I would. When using the available function in SD.lib, version 1.0.4, the return variable is int. This accounts for only 32768 bytes when files could be much longer. I would suggest changing the variable to long int. This will report much larger file sizes.

Stan K'

**Comment by facchinm** [comment]
The `available()` function is not a replacement of `size()` (which indeed returns a 32bit variable).

While not too pretty, the `available()` code uses internally a 32 bit variable but returns a 15bit one, so if anything exceeds 0x7FFF bytes it returns 0x7FFF, which only tells something like 
> "You still have a lot of bytes to read"

I agree it is not very clear but, given that `size()` exists, I'd mark it as wontfix
