### ISSUE TITLE
Ethernet.begin(mac) hangs

### ISSUE THREAD

**Issue by nmklotas** [arduino/Arduino#2565]
Hello,

I use Arduino uno rev3 board on windows 8.1 x64 with Arduino 1.58 beta, and after uploading the sketch, code line: 
<code>
Ethernet.begin(mac);
</code>
hangs and does not return! Been waiting for like 5 - 10 mins.

Also setting pin 4 as an output and writting HIGH to it didn't help.
(I found this instruction here http://arduino.cc/en/Main/ArduinoEthernetShield)

Not working example would be in Arduino IDE > File > Examples > DhcpAddressPrinter

Thank you

**Comment by Julius2342** [comment]
Hi @nmklotas, how did you solve this issue?

Best

Julius

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#31
