### ISSUE TITLE
OPC Server

### ISSUE THREAD

**Issue by yaswanthrajk** [arduino/Arduino#2569]
I installed Arduino OPC server and configured. in Info its showing "Waiting for OPC clients to connect....". Even i browse for Opc server in Matricon Explorer or dOPC Explorer or Wonderware Scada DA server, this Aurdino Opc server is not browsing there. What may be the problem. Please suggest me.

**Comment by ffissore** [comment]
I think you submitted your issue on the wrong issue tracker. Please submit your issue here: http://www.st4makers.com/forum/index
