### ISSUE TITLE
Unplugging Uno with IDE open causes kernel panic (OSX Yosimite) 

### ISSUE THREAD

**Issue by hestonkent** [arduino/Arduino#2575]
Unfortunately I can't find the error codes to provide on this within the console, and no shutdown dialog box appears upon reboot with an error report. However there's documentation all over the web with this occurrence, that can be found here: http://tinyurl.com/ooq8oj9
 

This occurs with sketches that even have no serial communication once uploaded whatsoever. Extremely frustrating, and discouraging as someone who is trying to learn Arduino.

**Comment by bobc** [comment]
Duplicate of #350? Try version 1.5.6 or later.

Otherwise, seems to be a bug in OSX, needs Apple to fix it.

**Comment by ffissore** [comment]
@hestonkent what version of the IDE are yo uusing?

**Comment by hestonkent** [comment]
Ah! I was using the 1.0.5, which appeared to be the 'non-beta' release. After upgrading to the 1.5.8, I cannot replicate the problem. Whoop whoop!
