### ISSUE TITLE
Wrong link to avrdude config on Raspberry Pi (debian) 1.6 rc2

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2587]
See this post for more information:
http://www.raspberrypi.org/forums/viewtopic.php?p=677255#p677255

I dont know if this also applies to other Linux distributions. It would also be nice to provide a raspberry pi version of 1.6 when its out without manual recompiling.

**Comment by ffissore** [comment]
It looks like the issue is not related to the IDE but to how it has been packaged for raspian. Closing as invalid.
