### ISSUE TITLE
Can't get into arduino forum. 

### ISSUE THREAD

**Issue by stryzbiak** [arduino/Arduino#2589]
I can't get into arduino forum. Here is what comes up, it just stalls on this blank screen. I am logged into the Arduino website. 

https://id.arduino.cc/auth/login/?go=1

Thanks,

Sid

**Comment by mastrolinux** [comment]
Hello,

Please send us your browser version at support@arduino.cc

**Comment by stryzbiak** [comment]
[cid:image001.png@01D03BB2.2C9FEC00]

**Comment by stryzbiak** [comment]
[cid:image001.png@01D03BB2.5DD3BF40]

**Comment by ffissore** [comment]
@stryzbiak can you confirm you've written to support@arduino.cc?

**Comment by stryzbiak** [comment]
Hi,

Not sure what happened but I can get in now.

Thanks a lot.

Sid
