### ISSUE TITLE
1.6.0 missing on Arduino site ?

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2592]
I realize this is wrong place for this. But Arduino.inc is a lost cause to ask, so here I am.

1.Anybody has a clue why 1.6.0 or its nightly builds are NOT on Arduino site to download? 
2. Is there a list of 1.6.0. rc2  DIFFERENCES from 1.6.0 ? 
    I have been using 1.6.0 (nov4)  and if the rc2 has minor improvements I see no point to "upgrade".  
    Just asking. 

PS Sure would like to find more cooperative ( nobody wants to talk about USB)  and friendlier group to ask questions than on ARduino site.

**Comment by ffissore** [comment]
1.6.0 builds, changelog and feedback are done on the [dev list](https://groups.google.com/a/arduino.cc/forum/#!forum/developers).
