### ISSUE TITLE
UNO R3 stopped working and shows a mismatch error

### ISSUE THREAD

**Issue by knildon** [arduino/Arduino#2593]
My UNO R3 stopped working and gives me the error message:
"avrdude: verification error, first mismatch at byte 0x0000
0x0c != 0x62
avrdude: verification error; content mismatch"
This happened immediately after I uploaded the sketch for the DigitalHourglass from the Arduino Starter Kit Instruction Book.
I have searched the internet to find a cure for this problem but to no avail.  I have returned the UNO and will purchase another when I receive my refund.
I did not stop searching for a cure to this problem and today found something about the internal clock fuses.  It appears they may need to be reset or reprogrammed to fix this error.  Since the Hourglass sketch was the first time I used the "unsigned long currentTime = millis()" and "long interval = 600000" in a sketch, could this possibly have something to do with the error message?
Some food for thought!!  If there is a relation, how does someone reset or reprogram the internal fuses?
Don

**Comment by facchinm** [comment]
Hi @knildon, in no way a simple upload via UNO bootloader could change the fuses bytes. You need an external programmer or another Arduino running the ISP sketch to achieve this. 

Probably your board had a faulty flash; I hope you received a non faulty one in the meantime!
Cheers
