### ISSUE TITLE
I have a problem, arduino due doesn't load more sketches

### ISSUE THREAD

**Issue by narflug** [arduino/Arduino#2595]
Hello!
I have a problem, I loaded a led example sketch and arduino due run OK. The led start and stop with a interval of one second. After I load the same sketch but with 5 seconds, the sketch didn't load, then, I press reset button, and nothing, after I pressed erase button and load again,.... nothing. 0_o

What happend? I erased the first sketch and I can't load more sketches!!!! 

Can anyone help me?
Thanks!

**Comment by agdl** [comment]
@narflug please post something like this doubt on forum.arduino.cc. There is a dedicated section for the DUE.
