### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by rammohanselvaraj** [arduino/Arduino#2599]
i am using arduino 1.0.5 driver version  for connecting 3d printer.

i am getting vulnerability error from my network, when i am trying use  version 1.0.5.
 i am not getting any error if i try to connect with arduino version 1.0.0.

pls suggest the possible solution for the above said issue.

warm regards
Ram

our network security system generating vulnerability error when i am using arduino version 1.0.5

**Comment by ffissore** [comment]
Please detail what this vulnerability error is

**Comment by agdl** [comment]
@ffissore  & @rammohanselvaraj I'm closing this. Reopen in case of necessity.
