### ISSUE TITLE
IDE doesn't start after having double clicked a lonely sketch [$50]

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#2604]
As reported on the developers mailing list

Nevada Smith ha scritto il 06/02/2015 alle 15:48:> Found a bug (windows tested):
> Create a sketch and move it out of the normal folder. Double click it. 
> The IDE will ask to create a folder for this sketch. It does, but it 
> doesnt move the sketch into it and the IDE wont start afterwards. Also 
> appeared in 1.6 rc2, dont know any earlier release.

**Comment by NicoHood** [comment]
Make sure to test it under other OS as well (had no chance to do). Good Luck ;)

**Comment by moshi04** [comment]
Please check the check-sum or integrity error of windows installer file. Its not starting after download showing integrity error. 
![arduino](https://cloud.githubusercontent.com/assets/3740530/6141931/6786345a-b1d7-11e4-8793-bb8ceff1efcc.jpg)

**Comment by NicoHood** [comment]
Isnt this a totally different bug?
I am using the zip version anyways.

**Comment by ffissore** [comment]
@moshi04 please retry downloading and paste the url you're downloading from
Il giorno 11/feb/2015 05.19, "moshi04" <notifications@github.com> ha
scritto:

**Comment by moshi04** [comment]
@ffissore Thank you very much. Now its work.

**Comment by NicoHood** [comment]
Any fix for the actual problem?

**Comment by ffissore** [comment]
There is an open bounty on this issue. First one that solves it opening a valid pull request wins 50$

**Comment by PaulStoffregen** [comment]
Who's paying the bounty, if it gets fixed?

**Comment by ffissore** [comment]
That's about how Bountysource works. Basically, Arduino has already paid the bounty. The winner will see the 50$ coming to her bountysource account, and she'll then decide to use them or cash them out
https://github.com/bountysource/frontend/wiki/Frequently-Asked-Questions#does-100-of-the-bounty-go-to-the-developer

**Comment by gerito1** [comment]
This pull request should fix that.
https://github.com/arduino/Arduino/pull/2700

**Comment by NicoHood** [comment]
haha if that fixes it, great job.
Did I miss something about the bounty? Do you do this for other issues as well?

**Comment by PaulStoffregen** [comment]
Yup, that's the right fix!

**Comment by ffissore** [comment]
Indeed it is. Thank you very much!
