### ISSUE TITLE
Port desciptions are twisted at arduino site

### ISSUE THREAD

**Issue by Krzysaker** [arduino/Arduino#2609]
Hi,

I think there is a small error at http://arduino.cc/en/Tutorial/MasterReader in Circuit paragraph.

It is written
> Connect pin 4 **(the clock, or SCL, pin)** and pin 5 **(the data, or SDA, pin)** on the master Arduino...

and there should be

> Connect pin 4 **(the data, or SDA, pin)** and pin 5 **(the clock, or SCL, pin)** on the master Arduino...

**Comment by NicoHood** [comment]
Can confirm this.
http://arduino.cc/en/uploads/Main/Arduino_Uno_Rev3-schematic.pdf

**Comment by agdl** [comment]
@Krzysaker corrected thank you!
