### ISSUE TITLE
Tinkerkit DMX Receiver - No documentation - Arduino Library

### ISSUE THREAD

**Issue by maxxist** [arduino/Arduino#2610]
I purchased a Tinkerkit DMX Receiver - Relay and I can not find documentation or
the DMX library needed to run on an Arduino uno board.
Thanks
maxxist

**Comment by sxpert** [comment]
the tinkerkit.com website appears dead...

**Comment by q2dg** [comment]
Maybe this could help? https://github.com/TinkerKit/DmxMaster

**Comment by maxxist** [comment]
Thanks
MP

**Comment by q2dg** [comment]
Well, I would like to insist in this issue.

There's no bit of information about what happened to Tinkerkit. In the forum reigns the silence (http://forum.arduino.cc/index.php?topic=261238.0). In Arduino Store there's no advice neither. Last updates in its Github come from 2013 (except an strange commit from two month ago)...

If official boards like Esplora and official shiedls like Motor and USBHost carry these kind of connectors, as a affected part Arduino should move on. This is not acceptable situation at all.

**Comment by mbanzi** [comment]
HI the TinkerKit Products are NOT Arduino.cc products. We used to sell them and used to add tinkerkit connectors to some products because they were generic enough 3pin connectors. You should contact the manufcturer indicated on the box
