### ISSUE TITLE
Feature request: Option to overwrite library examples

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2619]
Library examples are protected. Since I am developing them it would be nice to set add a checkbox to the settings which allows to edit the files. Or maybe a special "dev/advanced" section for that stuff in settings would be nice. Then we could also add other stuff people suggested but not bother beginners too much.

**Comment by ffissore** [comment]
Closing as duplicate of #3512. Despite this being older, #3512 raised more attention

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly. See #3512 for how to make it work
