### ISSUE TITLE
Missing cmd-line support for Arduino IDE for Java 7 on Mac OS X  

### ISSUE THREAD

**Issue by der-onkel** [arduino/Arduino#2638]
Hi there,

i've tried to use the CMD-line tool as described on https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-from-command-line
But it doesn't work on my installation. :-/

kind regards 
Juergen

**Comment by ffissore** [comment]
Confirm. cmd line doesn't work on mac :(
Schedule for 1.6.1 is already tight: it will be fixed with 1.6.2

**Comment by PaulStoffregen** [comment]
What is the schedule for 1.6.1 ?!

**Comment by carlosperate** [comment]
Does the cmd line interface work in 1.5.8 in mac OS X?  What would be the expected schedule for 1.6.2?

**Comment by carlosperate** [comment]
Does the command line support at least work on the 1.6 release for Java 6?

**Comment by ffissore** [comment]
Yes

**Comment by ffissore** [comment]
Fixed with aca6c223ded5c6f718fd4ea14b9b29bc03935549. Available since next nightly and in 1.6.1

**Comment by carlosperate** [comment]
Great to hear, thanks Federico!
