### ISSUE TITLE
Add log() and other avr-libc math functions to reference and keywords.txt. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#264]
This is [Issue 264](http://code.google.com/p/arduino/issues/detail?id=264) moved from a Google Code project.
Added by 2010-05-25T20:40:09.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Docs, Component-Build
### Original description

Since they are available and people want to use them.

**Comment by per1234** [comment]
Documentation aspect of this issue moved to https://github.com/arduino/reference-en/issues/522
