### ISSUE TITLE
Error in web site:reference:&bitwiseand:

### ISSUE THREAD

**Issue by cgendron** [arduino/Arduino#2645]
In the example program, it is stated that "so if we write PORTD = B00110001; we have made pins 2,3 & 7 HIGH. "  this is incorrect. Pins 0, 4 and 5 will be HIGH, not 2, 3 and 7.
A+

**Comment by agdl** [comment]
@cgendron done thank you

**Comment by cgendron** [comment]
Another issue #2496 seems to me as the same issue...sorry I saw it too late.
