### ISSUE TITLE
Bugs in ArduinoISP [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#265]
This is [Issue 265](http://code.google.com/p/arduino/issues/detail?id=265) moved from a Google Code project.
Added by 2010-05-26T06:01:17.000Z by [xacc....@gmail.com](http://code.google.com/u/101645689127408636600/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-ArduinoISP

### Original description

I have picked up a couple of obvious bugs in ArduinoISP. While they may not
be an issue now (I dont have anything bigger than a 328 to test), this
could be a problem on bigger chips like the 644 and 1280.

Code:

typedef struct param {
  uint8_t devicecode;
  uint8_t revision;
  uint8_t progtype;
  uint8_t parmode;
  uint8_t polling;
  uint8_t selftimed;
  uint8_t lockbytes;
  uint8_t fusebytes;
  int flashpoll;
  int eeprompoll;
  int pagesize;
  int eepromsize;
  int flashsize;
}  

* flashpoll could and should be uint8_t
* eeprompoll should be uint16_t (i assume time cant be negative)
* pagesize and eepromsize should be uint16_t (i assume size cant be less
than 0)
* flashsize should be uint32_t given it expects 4 bytes, again cant be less
than zero

The biggest potential problem is with flashsize, as currently it limits it
to 32kb.

**Comment by Chris--A** [comment]
The proposal in #3500 fixes these data types.

**Comment by per1234** [comment]
@cmaglie now that #3500 is merged with all the changes suggested above this issue can be closed.

**Comment by facchinm** [comment]
Should be ok now, closing, thank you @per1234
