### ISSUE TITLE
Weird Tools->Board order for extern hardware folder names

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2650]
Create a custom sketchbook/hardware/name/avr folder.
Insert a boards.txt with a boards and a platform.txt which is empty (only add the name).

Now rename the name of that folder and the board will appear at the top, at the bottom, between other custom boards or not. I cant find any logic here, not by alphabet, not by length, no idea. But its too bad that some libs appear right above the Arduino stuff and some not.

**Comment by NicoHood** [comment]
To 1.6.1 the order changed again. Why and how?

**Comment by ffissore** [comment]
Order is now under control, and has changed once more
