### ISSUE TITLE
1.6.0 IDE sets "file modified" flag whenever a tab is clicked for viewing, instead of when the content is actually changed

### ISSUE THREAD

**Issue by plocher** [arduino/Arduino#2653]
Context:
* MacOS
* Arduino IDE 1.6.0

To reproduce:
* Start with a multi-tab sketch
* Save it (ensures all "file modified" state/markings are cleared for this example...)
* Click on another tab but do not modify its content
* Notice the tab now shows the "file modified" squiggle even though nothing was done to modify the content of the tab

IMO, the "modified" state should track the changelog/undo buffer, such that "undo"ing all edits clears the modified flag and the modified state only is set after a true content modification.  The current implementation seems to be much less nuanced :-)

**Comment by ffissore** [comment]
Can reproduce this on linux. @cmaglie may you test this with your mac?

**Comment by cmaglie** [comment]
Happens also on linux, I can reproduce it with the following sequence:

* Open a sketch
* *Modify the sketch and save* (add some empty lines for example)
* Create a new tab, for example "test.h"
* Save
* Click on the first tab
* Now the first tab is marked as modified

**Comment by ffissore** [comment]
A fix will be available at #2666 in the next couple of hours

**Comment by ffissore** [comment]
@plocher can you give a spin to https://github.com/arduino/Arduino/pull/2666#issuecomment-75529858 and report if it fixes your issue?

**Comment by plocher** [comment]
Will try to find time in midst of business travel tonight 🌃
