### ISSUE TITLE
"Save as" should default to parent of current sketch folder.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2655]
On Mac at least, when you select "Save as..." from the File menu, the dialog box has the sketch's folder selected by default. That means if you simply type a new name and press enter, you'll get an error about trying to save a copy of the sketch inside itself ("How very Borges of you").

It would probably make more sense for the dialog box to default to the parent of the current sketch folder instead, i.e. default to saving the copy next to the original instead of inside it.

This is with 1.6 (the recommended version) on Mac OS X 10.10.2.

**Comment by ivovdgrift** [comment]
It seems to only do this on mac, not on windows. I'll try to create a fix for macs

**Comment by ivovdgrift** [comment]
Offered a solution [here](https://github.com/arduino/Arduino/pull/2716)

**Comment by ffissore** [comment]
Fixed with #2716
