### ISSUE TITLE
TFTRect Documention Code is wrong

### ISSUE THREAD

**Issue by koraybasegmez** [arduino/Arduino#2660]
Hi,
http://arduino.cc/en/Reference/TFTRect
in this document this line
screen.line(screen.width()/2-5, screen.height()/2-5, 10, 10);
should replace with this line
screen.rect(screen.width()/2-5, screen.height()/2-5, 10, 10);
:)

**Comment by agdl** [comment]
@koraybasegmez  done thank you!
