### ISSUE TITLE
Wrong link in Development Tools

### ISSUE THREAD

**Issue by MordodeMaru** [arduino/Arduino#2661]
Under the biicode title here:

http://playground.arduino.cc/Main/DevelopmentTools

there's a wrong link.

*Installation and set up* should point to:

http://docs.biicode.com/arduino/arduino-installation.html

**Comment by agdl** [comment]
@MordodeMaru  playground is a wiki and every one can edit it so you can close this issue by yourself :)

**Comment by MordodeMaru** [comment]
How stupid. Thanks @agdl

**Comment by MordodeMaru** [comment]
BTW @agdl you seem to be a C and C++ dev, you might like then https://www.biicode.com ;-]
