### ISSUE TITLE
Schematic is incorrectly drawn in LCD Hello World! tutorial

### ISSUE THREAD

**Issue by camerontbelt** [arduino/Arduino#2664]
The schematic should have connections on LCD pin 15 to Vin and pin 16 to GND
http://arduino.cc/en/Tutorial/LiquidCrystal

**Comment by agdl** [comment]
@camerontbelt the LCD indicated in the tutorial hasn't the back light so these connections are useless. However I will update it using a newer image that uses the LCD provided by the Arduino starterkit. Thank you

**Comment by agdl** [comment]
Done
