### ISSUE TITLE
Grammar mistake?

### ISSUE THREAD

**Issue by Moredread** [arduino/Arduino#2667]
I think in Arduino/libraries/Bridge/examples/Bridge/Bridge.ino on line 30

"the webserver on the Yún will forward there all the HTTP requests for us."

the position of 'there' is grammatically not correct, but I'm not a native speaker.

**Comment by ffissore** [comment]
It's correct. However, we rephrased it for better clarity https://github.com/arduino/Arduino/commit/0b6e274b5dacd7da4b6acb3f68e8ef939dca44d7
