### ISSUE TITLE
Status bar doesn't update when custom menu selections change

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#2668]
The status bar, on the bottom right corner of the IDE window, shows the currently selected board, the port, and any custom menu selections.  It updates when the board or port selections are changed, but not when any custom menus are changed.

For example, set Tools > Boards to "Arduino Pro or Pro Mini".  The status bar will update.  Then change Tools > Processor to any of other other options.  The status bar will continue to show the old setting, even though the custom menu and build settings used for compiling have changed.

**Comment by ffissore** [comment]
Fixed by #2675
