### ISSUE TITLE
[ENHANCEMENT] joystick api

### ISSUE THREAD

**Issue by nieknooijens** [arduino/Arduino#2674]
Hi there

wouldn't it be a great idea to include the joystick api from here:
www.imaginaryindustries.com/arduino/leoJoy/USBAPI.h
www.imaginaryindustries.com/arduino/leoJoy/HID.cpp
http://www.imaginaryindustries.com/blog/?p=80
in the default distribution so the leonardo and the DUE can interact like true joysticks?

**Comment by ffissore** [comment]
What about proposing some code in the form a pull request? That will make life easier for those that want to try the api and for those that want to test it and decide to include it or not

**Comment by facchinm** [comment]
Close with #1803
