### ISSUE TITLE
WiFi shield library usage does not preserve analogReference?

### ISSUE THREAD

**Issue by mfkrzeminski** [arduino/Arduino#2679]
A genuine Uno with WiFi shield, both MCU and WIFI chips updated to latest firmware
1.6.0 IDE with default associated libraries

A program that is pulling an aeronautical meteo observation (METAR) via HTTP GET and
then displays it on the 4x20 LCD screen along with local baro and temp readings.
Code makes use of WiFi, SPI and LiquidCrystal unmodified libs.

Apparently, after first pass of the HTTP GET request the read analog values all change (to unreliable, much-too-high ones).

I have noticed this can be cured only by reapplying the DEFAULT (my sensors are 5V) analogReference after the httpRequest routine is exited (this one actually comes wholly from the examples included with the IDE so not worth quoting it).

By trial and error it seems that the value gets changed to INTERNAL.

A real bug or i am doing something wrong here? Quite funny as i did not expect the WiFi library
to interact with the analog ports by itself.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#23
