### ISSUE TITLE
Obsolete instructions to building Arduino from source

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2708]
https://github.com/arduino/Arduino/blob/master/build/howto.txt
points to 
http://code.google.com/p/arduino/wiki/BuildingArduino
whose last update was from 2010.
Maybe a wiki article could be worthy.

**Comment by ffissore** [comment]
Thanks for the heads up. Issue is being tracked at #2621
Il giorno 27/feb/2015 00.39, "Osqui LittleRiver" <notifications@github.com>
ha scritto:
