### ISSUE TITLE
compiler fails if  another editor window is closed during compilation [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#271]
This is [Issue 271](http://code.google.com/p/arduino/issues/detail?id=271) moved from a Google Code project.
Added by 2010-06-03T18:16:29.000Z by [massimo....@gmail.com](http://code.google.com/u/109669526874165950228/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1.Open two editor windows
2.Press the compile button on one
3.Close the other window
4. compila

**What is the expected output? What do you see instead?**

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 18, tested on Windows 7 and Ubuntu Linux

**Please provide any additional information below.**
Submitted by forum user "calamaro"

**Comment by ffissore** [comment]
I guess this was fixed a long time ago, I can't reproduce it
