### ISSUE TITLE
Can't install Experimental Arduino version on MacBook Pro - Yosemite + Java 8: <Code>AccessDenied</Code> 

### ISSUE THREAD

**Issue by tr2000** [arduino/Arduino#2717]
Tried to install experimental Arduino SDK for Java 7 or later and on the page: 

http://downloads.arduino.cc/arduino-1.6.0-macosx-java-latest.zip 

Received the message in the browser:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
    <Code>AccessDenied</Code>
    </Error>

What now?

**Comment by mastrolinux** [comment]
Hello,

That was due some old DNS cache on your system. Please try again now so I can close this bug report.

**Comment by tr2000** [comment]
Fixed, thank you!

-----Original Message-----

**Comment by mastrolinux** [comment]
You are welcome, closing issue.
