### ISSUE TITLE
Tutorial TFTPong

### ISSUE THREAD

**Issue by ArnauldDev** [arduino/Arduino#2721]
http://arduino.cc/en/Tutorial/TFTPong

I tested the sample code "**Examples> TFT> Arduino> TFTPong**" and I have to modify parameters in the following lines :
  // map the paddle's location to the position of the potentiometers
  paddleX = map(analogRead(A0), 512, -512, 0, myWidth) - 20 / 2;
  paddleY = map(analogRead(A1), 512, -512, 0, myHeight) - 5 / 2;
in
  paddleX = map(analogRead(A0), 0, 1023, 0, myWidth) - 20 / 2;
  paddleY = map(analogRead(A1), 0, 1023, 0, myHeight) - 5 / 2;
for example working properly ;-)

Thank you to correct on the site and in the IDE.

**Comment by agdl** [comment]
Done thank you!
