### ISSUE TITLE
ATtiny85 problem with newest version of Arduino software

### ISSUE THREAD

**Issue by MishaBravo** [arduino/Arduino#2730]
Details in the discussion on Reddit:
http://www.reddit.com/r/arduino/comments/2xv530/attiny85_problem_with_newest_version_of_arduino/

**Comment by ffissore** [comment]
Last comment on reddit links to the right place for receiving support on tiny https://code.google.com/p/arduino-tiny/

**Comment by cmaglie** [comment]
For the record, the link to the arduino-tiny cores from reddit is
http://code.google.com/p/arduino-tiny/downloads/detail?name=arduino-tiny-0150-0020.zip
A quick check on the zip file shows that this should be a 1.6 compatible version: I didn't tried it BTW.

You can also try the cores from @damellis: https://github.com/damellis/attiny/
In the readme there is a link to the 1.6 version: https://github.com/damellis/attiny/tree/ide-1.6.x
