### ISSUE TITLE
Request for Hooks in the Build process

### ISSUE THREAD

**Issue by Wackerbarth** [arduino/Arduino#2732]
It would be very useful to be able to add a recipe to the platform specification that is executed at the start of the build process. (pre-build)

In particular, my use case is to generate version strings which will be incorporated in the Rom image based on information extracted from a SCM repository. However, the concept is generic and I am sure that there are other uses.

Similarly, a (post-build) hook should be provided to allow platform-specific actions at the end

**Comment by ffissore** [comment]
That's a very nice enhancement. We are currently working on a redesign of the build process (while keeping platform.txt unchanged): I hope we'll find time for this implementation in the coming months. Any code contribution is well accepted
