### ISSUE TITLE
Help files out of date "http://arduino.cc/en/Hacking/Programmer?from=Main.Programmer"

### ISSUE THREAD

**Issue by vwpeter** [arduino/Arduino#2736]
http://arduino.cc/en/Hacking/Programmer?from=Main.Programmer

Obvoiusly this is the old state, before the menu item "File --> Upload using Programmer" was added.
Took me a while to find this easy solution, trying to hack preferences.txt etc...

**Comment by agdl** [comment]
@vwpeter I updated it. Thank you
