### ISSUE TITLE
Compiler errors don't highlight corresponding line of code.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2737]
In past Arduino versions, when compiling a sketch the line of code corresponding to the first error would be highlighted. This was a big help in assisting users in locating (and fixing) the error, without necessarily needing to read through the (often-confusing) error message in detail. At some point, this behavior seems to have stopped. For example, I don't see it in the latest master branch (1.6.1) on Mac OS X (10.10.2). It would be great to bring back this functionality.

**Comment by ffissore** [comment]
Report back here once fixed http://forum.arduino.cc/index.php?topic=307531.0

**Comment by ffissore** [comment]
Fixed nightly available in the next few hours

**Comment by damellis** [comment]
Great!
