### ISSUE TITLE
compiling error for ultrasonic sensorhc-sr04

### ISSUE THREAD

**Issue by hannanrazvi** [arduino/Arduino#2739]
hey guys i have a udoo board and i am having a problem in comiling the code for the ultrasonic sensor hc-sr04 the error i am getting is -

/home/ubuntu/Arduino/libraries/NewPing/NewPing.cpp: In constructor 'NewPing::NewPing(uint8_t, uint8_t, unsigned int)':
/home/ubuntu/Arduino/libraries/NewPing/NewPing.cpp:21:17: error: cannot convert 'RwReg* {aka volatile long unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
  _triggerOutput = portOutputRegister(digitalPinToPort(trigger_pin)); // Get the output port register for the trigger pin.
                 ^
/home/ubuntu/Arduino/libraries/NewPing/NewPing.cpp:22:13: error: cannot convert 'RoReg* {aka volatile long unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in assignment
  _echoInput = portInputRegister(digitalPinToPort(echo_pin));         // Get the input port register for the echo pin.
             ^
/home/ubuntu/Arduino/libraries/NewPing/NewPing.cpp:24:75: error: 'portModeRegister' was not declared in this scope
  _triggerMode = (uint8_t *) portModeRegister(digitalPinToPort(trigger_pin)); // Get the port mode register for the trigger pin.
                                                                           ^
Error compiling.

please help me as this is my college project and im really running low on time

**Comment by cmaglie** [comment]
This issue tracker is not intended for help on personal project, please ask on the forum:

http://forum.arduino.cc

or even better on the UDOO forum:

http://www.udoo.org/forum/
