### ISSUE TITLE
Support for assembly files in IDE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#274]
This is [Issue 274](http://code.google.com/p/arduino/issues/detail?id=274) moved from a Google Code project.
Added by 2010-06-11T10:54:38.000Z by [qist...@gmail.com](http://code.google.com/u/106370313292761730621/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Duplicate).

Original labels: Type-Enhancement, Priority-Medium, Component-IDE
### Original description

**What change would like to see?**
As described in http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1276151354 the Arduino IDE doesn't support .S (assembly) files.
Whenever someone wants to use these, they have to be put in a library, which makes editing them from the IDE impossible.

**Why?**
Even though it's probably for some advanced users only, since it only requires very small changes, I think we should add it.

The compile scripts already support .S files, they're just not opened in the IDE or copied to the 'work folder'.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
I don't foresee any real incompatibilities. If someone already has .S files in their project directory these will suddenly appear in the IDE and be copied to the 'work folder'.

The changes required are both in app\src\processing\app\Sketch.java (rev. 964).
Line 1345 should be changed to
if (sc.isExtension("c") || sc.isExtension("cpp") || sc.isExtension("h") || sc.isExtension("s")) {

Line 1800 should be changed to
return new String[] { "pde", "c", "cpp", "h", "s" };

**Comment by lmihalkovic** [comment]
<img width="400" alt="arduino-2015-12-03 at 12 55 32 pm" src="https://cloud.githubusercontent.com/assets/1318077/11995012/9ab4fb16-aa49-11e5-8a05-b707638e96a2.png">

This is a version for GAS & AVR instruction set. Improvements are needed for ARM

**Comment by NicoHood** [comment]
I'd like to use your Arduino IDE. Not bad how fast (and from the user point of view good looking) you always get things patched.

**Comment by lmihalkovic** [comment]
@NicoHood  thx for the feedback. For now I'm still working on some of the core features from my [master list](https://github.com/lmihalkovic/Arduino/issues/1) (grew a lot and right now it looks more like a 2.0 than a 1.7.xx). I shared with @mbanzi and his team how it would be easy to make a lot of improvements fast, provided that a deep initial cleanup would be done. I guess the issue is not so much how difficult it is to write things, but more whether or not it is obvious that they can be.
