### ISSUE TITLE
Wifi Shield Firmware Update

### ISSUE THREAD

**Issue by golfguy777** [arduino/Arduino#2740]
I have been trying to update the firmware on my wifi shield for the past two weeks. However, the link that contains the firmware code on github gives me a 404 error. Would someone be able to help me with this? I've had no luck with this issue.

**Comment by CaptCoonoor** [comment]
Can you give us link, so that we can help you?

**Comment by golfguy777** [comment]
Hello,

Apologies for the late reply. The link with the incorrect instructions to
install the new firmware is here:
http://arduino.cc/en/Hacking/WiFiShieldFirmwareUpgrading,
and the github link for the code to install is here:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/firmwares

The URL with the correct firmware code is:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/firmwares/wifishield

Regards,
Jeff

**Comment by agdl** [comment]
like in #2896
