### ISSUE TITLE
some librairies should be in platform dependent directories

### ISSUE THREAD

**Issue by piif** [arduino/Arduino#2741]
Libraries like Audio and Scheduler are specific to Due platform, but are located in /libraries directory instead of /hardware/arduino/sam/libraries

**Comment by ffissore** [comment]
We are trying to pull out libraries from cores and instead use their
metadata to filter/select them.
See the architectures key in file library.properties of library format 1.5
Il giorno 09/mar/2015 16.50, "piif" <notifications@github.com> ha scritto:

**Comment by piif** [comment]
Thank you for this information
I try to compile Arduino code from outside of Arduino IDE, but I didn't know this convention.
I'll try to use it to auto discover libraries.
