### ISSUE TITLE
hardware/arduino/avr/firmwares/arduinoISP/readme.txt has bad link

### ISSUE THREAD

**Issue by bperrybap** [arduino/Arduino#2748]
Not sure what this was supposed to be but the readme here:
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/firmwares/arduinoISP
says you can download ArduinoISP firmware source from here:
https://github.com/arduino/ArduinoISP
which doesn't exist

**Comment by ffissore** [comment]
Repo is now public. Sorry for the inconveniences
