### ISSUE TITLE
Hello, what's up with the new version 1.6.1 ARDUINO

### ISSUE THREAD

**Issue by lindoduende** [arduino/Arduino#2750]
Hello, what's up with the new version 1.6.1 ARDUINO that does not accept programs built with the previous version and that they were right and why not let access the menu to change the port to use with the Arduino?

**Comment by ffissore** [comment]
Can you please detail what error is the IDE printing and the whole sketch
you're trying to compile?
Il giorno 11/mar/2015 13.50, "lindoduende" <notifications@github.com> ha
scritto:

**Comment by agdl** [comment]
Please reopen this if needed
