### ISSUE TITLE
Windows 1.6.1 ZIP & installer files differ

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#2751]
It seems an updated JDK version 7 was used to build the Windows ZIP file, but the code in the Windows installer looks like it was built with a very old JDK version 6.

**Comment by ffissore** [comment]
Caught in the act. We made the two released on different boxes. 1.6.2 will be made by one box only in a fully automated way. Is this difference giving you troubles?

**Comment by PaulStoffregen** [comment]
It's only a minor inconvenience.  I opened this issue only in case you weren't aware the Windows downloads contain different files.

**Comment by ffissore** [comment]
Thank you for the heads up: I'll leave this open until we have properly set up the windows box

**Comment by PaulStoffregen** [comment]
fixed in 1.6.2
