### ISSUE TITLE
GUI glitch

### ISSUE THREAD

**Issue by Nerijuslt4** [arduino/Arduino#2761]
My arduino GUI is glitching. It works, but it is really anoying when text is disappearing. I dont know how to explain. So the pictures should give more info: 
In first pic we see almost normal GUI, but these white dots doesnt seem right...
![1](https://cloud.githubusercontent.com/assets/11447842/6628328/322e8b20-c90d-11e4-8101-575455084efc.PNG)
Then the fun begins, I sweep my mouse over text (i mean "file, edit, sketch...") and its gone. Well, almost gone... Few symbols stays sometimes.
![2](https://cloud.githubusercontent.com/assets/11447842/6628350/5772ab50-c90d-11e4-8112-53aa380d3106.PNG)
Then even i'm getting even more fun: i press "File" in the corner and move my mouse around options, and they are disappearing too:
![3](https://cloud.githubusercontent.com/assets/11447842/6628329/356e08f6-c90d-11e4-8648-d29453065952.png)

So please, help me. I can't work like this... Everything else works fine i gues. I  mean code writing, compiling, uploading etc. But when I need to open something from sketchbook, I'm almost guesing what I'm gonna open, cause file names are becoming invisible whan I move my mouse over them (and they are not comming back until i press something else).
It goes the same way with all other options (edit, sketch, etc.).

All started after i updated my arduino to 1.6.1 yesterday

What I have tried: reinstalling arduino, downloading zip file, updating java (idk if that has anything to do with arduino...), restarting computer. 
Any suggestions?

**Comment by jcarlosgarciauah** [comment]
I have got the same problem, but in my case I have noticed the following:
* The IDE versión 1.6.1 Works fine within 'Windows 8.1'
* But the IDE-1.6.1 fails (in the way you show here) within 'Windows 7'

Is this the case with you? Are you running Windows-7?

Nevertheless, previous versions of IDE Works fine with Windows 7. I think this is a bug in IDE-1.6.1, let us hope that versión 1.6.2 (coming son) will address this bug!

**Comment by Nerijuslt4** [comment]
Yes, I'm using win-7. And yes, previous versions worked fine.

**Comment by ffissore** [comment]
Can you please give a try to this build and tell if it fixes your issue? https://github.com/arduino/Arduino/pull/2783#issuecomment-82223032

**Comment by kloper** [comment]
Same issue here. Win7 64 bit.

**Comment by Nerijuslt4** [comment]
Had only few free minutes and tried
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2783-BUILD-224-windows.zip
Those issues seems like to be gone at first look. Ill test it more later.
