### ISSUE TITLE
Compilation error: missing terminating " character

### ISSUE THREAD

**Issue by qbahn21** [arduino/Arduino#2762]
Code sample:
![sample](https://cloud.githubusercontent.com/assets/11447977/6628719/1f4225f8-c908-11e4-9683-abc23e7bb48e.png)

Regards,
Qbahn21

**Comment by qbahn21** [comment]
applies to Arduino 1.6.1

**Comment by ffissore** [comment]
That's because of the preprocessor and there already is a fix for that: please give a spin to this version of the IDE #2729 (bottom of the page)

**Comment by qbahn21** [comment]
Thanks, but I don't know what a spin is... :(

2015-03-13 8:28 GMT+01:00 Federico Fissore <notifications@github.com>:

**Comment by ffissore** [comment]
Sorry, I meant: can you please download a build of the IDE suitable for your operating system from #2729 (bottom of the page) and try using it to compile the sketch you posted? That build should contain a fix to your issue

**Comment by qbahn21** [comment]
Done already. That build works fine with that sample. But whole sketch doesn't compile. Hangs up during "coan source -m -E -P -kb -DF_CPU=16000000L -DARDUINO=10602 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR..." without any additional output :(

**Comment by ffissore** [comment]
Can you share the whole sketch?
