### ISSUE TITLE
Arduino & Processing

### ISSUE THREAD

**Issue by Eslih** [arduino/Arduino#2766]
Hi,

At the fhe following page is mentioned on how to add the Arduino lib to processing:
http://playground.arduino.cc/interfacing/processing

Download a zip, extract it and so on. There is a way that is much easier and faster: 
Processing -> Sketch -> Import Library -> search for Arduino & install = done

**Comment by ffissore** [comment]
Playground is a user generated wiki. You're free to edit every single page
