### ISSUE TITLE
SVN keywords being used yet SVN keyword expansion not happening [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#277]
This is [Issue 277](http://code.google.com/p/arduino/issues/detail?id=277) moved from a Google Code project.
Added by 2010-06-21T18:34:01.000Z by [bperry...@gmail.com](http://code.google.com/u/107476669756743351267/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

There are places in the tree where SVN keywords are being used in files yet the SVN keyword expansion, which is controlled by the file properties, does not appear to have keyword expansion enabled.
For a specific example of file look at this file:
http://code.google.com/p/arduino/source/browse/trunk/hardware/arduino/cores/arduino/wiring_digital.c

See line 22:

Here is some additional discussion on the topic:
http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1277081988

Without the properties enabled, no keyword expansion will happen
and users get stale (wrong) information
in the SVN keywords - which is not good.

This is not isolated to the single file above.

**Comment by ffissore** [comment]
Mitigated
