### ISSUE TITLE
No space on the left side of the code

### ISSUE THREAD

**Issue by chq76** [arduino/Arduino#2774]
Hello,

since years there is a small problem with arduino on mac. Sometimes, after wrting a lot of code, there is suddenly no space between the code and the left border.

Here you can see a small movie, showing this problem:

https://www.sendspace.com/file/r0enjb

Normally there is a little bit space between the code and the left border (i colored it yellow):

http://fs2.directupload.net/images/150315/453j3if5.gif

Months ago i wrote this issue in the arduino forum, but nothing happened.

The bug is still present (in 1.6.1 too).

Greetz Chris

**Comment by ffissore** [comment]
Does enabling line numbers works around the issue?

**Comment by chq76** [comment]
When i close arduino and open it again, everything is fine again. I don't want to use line numbers.

Greetz Chris

**Comment by ffissore** [comment]
I wasn't suggesting to keep line numbers on. I was asking if, with line numbers enabled, the issue disappears or is still there. This could help us understanding the root cause of the issue

**Comment by chq76** [comment]
Don't know, because i don't use enabled line numbers.

Greetz Chris

**Comment by ffissore** [comment]
Chris, please strictly follow these steps: 1) enable line numbers, 2) verify if the space issue is still present, 3) disable line numbers

**Comment by chq76** [comment]
Please consult your betatesters.

Greetz Chris

**Comment by chq76** [comment]
Why closed? Is there a solution?

**Comment by ffissore** [comment]
No, but I wasn't able to reproduce the issue, nor to convince you trying if enabling line number worked around it
