### ISSUE TITLE
Arduino 1.6.1 installation has broken my code!

### ISSUE THREAD

**Issue by benw33** [arduino/Arduino#2777]
Hi, after installing Arduino 1.6.1, my sketch which uses the SD.h library that worked fine before the update no longer compiles. I'm getting an error message which says:

C:\Program Files (x86)\Arduino\libraries\SD\src\utility\Sd2Card.cpp:26:17: fatal error: SPI.h: No such file or directory
 #include SPI.h
                 ^
compilation terminated.

Any ideas on how to fix this?

**Comment by ffissore** [comment]
Add `#include <SPI.h>` on top of your sketch
