### ISSUE TITLE
Arduino MEGA 2560

### ISSUE THREAD

**Issue by nonamesmallkid** [arduino/Arduino#2778]
I have developed a 7x7x7 LED cube with this board. I uploaded a sketch file with 67,216bytes size, the cube is working nicely. However, I increase the pattern and the file size reach 67,576bytes, the cube is totally not working. I am using PROGMEM to store the pattern.

**Comment by ffissore** [comment]
Please post your issue on the arduino forum or specify the bug you've found
and detail how to reproduce it.
 Il giorno 16/mar/2015 14.13, "nonamesmallkid" <notifications@github.com>
ha scritto:
