### ISSUE TITLE
Arduino WiFi Shield Firmware/Library do not pass up sender's info.

### ISSUE THREAD

**Issue by josephlm** [arduino/Arduino#2780]
I am not familiar with how much detail I should add here, so I am giving a description of the issue and a proposed solution.

When using the Firmware already installed on my Arduino Wifi Shield (V1.0.0) or the firmware (V1.1.0) in the latest release version of Arduino (Arduino 1.6.1), it does not pass up the sender's information to the library for each packet in my shield's buffer (ie. IP Address & Port). There is an API provided which can get the last packet in my buffer and retrieve it's sender, but this sender information can be overwritten before my application can retrieve what is at the beginning of the buffer when a new packet goes in at the end of my buffer. Therefore, all packets will appear to be belong to the last packet's sender. This can cause weird operation in the enduser's application as receiving packets from different network users simultaneously will appear to only belong to the last packet's sender.

There is no disassociation between the last sender's packet and the sender before that packet as the sender's information is simply overwritten by the last sender's information via "setRemoteClient()". I would propose fixing this via:

A. changing the interface between the firmware and wifi library to pass up IP Address & Port information with every recv() command.
B. add a new send/recv construct and API in the Wifi Library (so as not to break existing users of this library) with fixes from proposal A.
C. Update the interface between the firmware and wifi library and change the public APIs of the Wifi Library to pass up IP Address & Port information with every recv() command.

I have tested proposal C above locally and I am able to provide my solution to developer's within the Arduino community to implement how they see fit as a reference only, if needed. Please contact me for a copy of my updated source.

**Comment by josephlm** [comment]
I would like to note that I had mis-typed the version information in the report above. There is no new firmware version. I had pre-emptively bumped the version number in my local 'hacked' version of the firmware and thus reported it being differently in Arduino 1.6.1 mistakenly. I apologize. However, V1.0.0 of the Arduino Wifi Shield firmware still has this fault in which the last packet in the shield's buffer becomes "owner" to all packets in the buffer (even if they are NOT the actual owner of the individual packets).

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/WiFi#22
