### ISSUE TITLE
small typo @ main page

### ISSUE THREAD

**Issue by robertocr** [arduino/Arduino#2786]
on http://arduino.cc/en/Main/ArduinoBoardYun?from=Products.ArduinoYUN
there is http://arduino.cc/en/uploads/Main/BridgeInShort.png
that could have its "enviroment" fixed, like this http://i.imgur.com/krrUR3d.png

(why isn't the page itself open?)

sorry for using this media if it's not the best, it's just that this was the easiest way for this info to be shown :)

**Comment by agdl** [comment]
@robertocr thank you very much. Updated!
