### ISSUE TITLE
Tools-Menu is not appeared.

### ISSUE THREAD

**Issue by sunaokumura** [arduino/Arduino#2787]
Arduino IDE Ver.1.6.1 by Java8 on Windows7 64bit.
Tools-Menu is not appeared.
Text Area is small.

I tried following:
http://arduino.cc/download.php?f=/javaide/pull_requests/arduino-PR-2783-BUILD-224-windows.zip
but This Arduino IDE has same issue as Ver.1.6.1.

![arduinoide](https://cloud.githubusercontent.com/assets/11499550/6704598/2e5e8dd0-cd8e-11e4-84cc-f314ba304fd7.jpg)

**Comment by sunaokumura** [comment]
and Arduino IDE Ver.1.0.6 has no problem as below.

![ard106](https://cloud.githubusercontent.com/assets/11499550/6704823/6f1d4e12-cd91-11e4-9643-5dd52e527abb.jpg)

**Comment by ffissore** [comment]
Is there any customization you made to windows that could help reproduce your issue? I too have a windows7 64bit and the build from #2783 shows fine :(

**Comment by sunaokumura** [comment]
There is no customization.
I tried #2783 again.
Thank you!

**Comment by ffissore** [comment]
Fixed/Improved by #2783
