### ISSUE TITLE
Critical bug found while manually importing library

### ISSUE THREAD

**Issue by micahnightwolf** [arduino/Arduino#2795]
If you attempt to import a library and the folder you select is your Arduino/libraries folder or a parent of it, the program will enter an infinite loop and recursively add the libraries folder as a library as well as everything inside it, creating infinite copies of your Arduino/libraries folder within itself. After that, the file path is too long for Windows to process, so these infinite folders cannot be deleted easily.

To see for yourself, click Sketch > Import Library > Add Library, select your Arduino folder or a parent of it, and click Open. Be quick to close the Arduino IDE though.

**Comment by ffissore** [comment]
Thank you very much for your issue. It has been fixed and it will be available with the next hourly build http://www.arduino.cc/en/Main/Software#hourly
