### ISSUE TITLE
DateTime library redefines boolean

### ISSUE THREAD

**Issue by OMRobin** [arduino/Arduino#2797]
On subject bool vs Boolean.    The Arduino.h file found many layers down clearly states
typedef bool  Boolean.   In the DateTime.h file the author ( Mike Margolis ) redefines it as follows
typedef uint8_t  Boolean.    The compiler cant handle two definitions.   Suggest DateTime gets a fix.

**Comment by facchinm** [comment]
Hi @OMRobin , just a ping. Did you contact the DateTime author for a fix? 
In the meantime I'm closing this as wontfix (from our side), reopen if needed
