### ISSUE TITLE
Sketch will not compile on a Mac with 1.6.x

### ISSUE THREAD

**Issue by roontoon** [arduino/Arduino#2799]
Details on this post along with sketch.

http://forum.arduino.cc/index.php?topic=309360.0

**Comment by facchinm** [comment]
Hi @roontoon ,
the issue should be solved with 22bd9f6 and latest nightly does contain the fix (http://arduino.cc/download.php?f=/arduino-nightly-macosx.zip for java6 / http://arduino.cc/download.php?f=/arduino-nightly-macosx-java-latest.zip for java7+)
Thanks for reporting!
