### ISSUE TITLE
Add pretty printer

### ISSUE THREAD

**Issue by PaulMurrayCbr** [arduino/Arduino#2801]
On the forum, I see the occasional programming error because people haven't lined up their braces. It would be great if the IDE had a frob to reformat your code.

**Comment by PaulStoffregen** [comment]
Like Tools > Auto Format ?

**Comment by Chris--A** [comment]
@PaulStoffregen 

It appears this is the correct solution, and has solved this issue: http://forum.arduino.cc/index.php?topic=310385.0

**Comment by PaulMurrayCbr** [comment]
Agreed. Should have made a note here as well as on the forums.
