### ISSUE TITLE
Add Board Reset Option to serial monitor

### ISSUE THREAD

**Issue by holgerlembke** [arduino/Arduino#2803]
Motivation: I have some Arduinos under my roof to program some data collectors. I mostly do that remote from my warm developer desk via remote desktop on the dev. pc under the cold roof.

For debugging it is very convenient to be able to reset them. In the very old times it was easy (due to a "bug" in the serial monitor): close monitor, open it, reset! 

This error has been fixed. So I switched to the Arduino ERW (Erwin Ried), he added a RESET-Button to the monitor and I love it... But I have to stay with the old 1.0.x IDE.

So.

Could you please bring some more features to the serial monitor? As far as I see, all the code is there at Erwin Rieds Github-repostory.

Java & .Net updated code: https://github.com/eried/Arduino/
Commit History (features+source files): https://github.com/eried/Arduino/commits/master
And the IDE: http://forum.arduino.cc/index.php?topic=118440.0

Thank you!

**Comment by q2dg** [comment]
+1

**Comment by testato** [comment]
+1

**Comment by holgerlembke** [comment]
I did implement it myself, See https://github.com/arduino/Arduino/pull/2809
