### ISSUE TITLE
Esplora Library: Incorrect Pin Specification For Accelerometer Y Input

### ISSUE THREAD

**Issue by SpiderMatt3825U** [arduino/Arduino#2805]
Refer to line 54 of the Esplora.cpp file where it has the following:

const byte ACCEL_Y_PIN = A11;

This is present in both versions that I currently have which are 1.6.1 and 1.1.0.5 (Ubuntu 14.04 current).

I changed it to the following because based on the comments just above it, the current value would seem wrong as the comments state that A11 is related to the Green LED.

const byte ACCEL_Y_PIN = A7;

Here are the comments just above this definition:

// non-multiplexer Esplora pins: 
// Accelerometer: x-A5, y-A7, z-A6
// External outputs: D3, D11
// Buzzer: A8
// RGB Led: red-D5, green-D10/A11, blue-D9/A10
// Led 13: D13

I'm not sure what is right here. My world is crashing down and this contradiction killed the Unicorn!

**Comment by SpiderMatt3825U** [comment]
I have corrected this problem and submitted a pull request.

**Comment by facchinm** [comment]
Fixed with ae8549c
