### ISSUE TITLE
[DOC] What happened/will happen to Arduino BT?

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2811]
It seems out of sale but there is no explanation about the reasons. It doesn't appear as deprecated, so it is confusing because there's no information about if it will be available anytime soon or no...Thanks

**Comment by ffissore** [comment]
Please mail store@arduino.cc

**Comment by ffissore** [comment]
Sorry shop@arduino.cc

**Comment by q2dg** [comment]
Well, there's someone who is ahead... 
http://makerstudio.cc/index.php?main_page=product_info&cPath=6&products_id=353
Missed oportunity
