### ISSUE TITLE
ld returned 5 exit status

### ISSUE THREAD

**Issue by laisan86** [arduino/Arduino#2813]
When I compile my sketch by 1.6.1, the message always showed up! No matter compile only or upload mode.
![ld returned](https://cloud.githubusercontent.com/assets/10933267/6798912/a5cc7158-d24c-11e4-96ee-a7f1f1953ec9.JPG)

I don't know what's 'ld', so suppose you can tell me how to solve this problem. Thanks!

**Comment by laisan86** [comment]
However, when the code has been modified, just make linkPin and pvVol become integer declarations, problem solved! Anyone tell me is this a compiler's bug or not?
![normal](https://cloud.githubusercontent.com/assets/10933267/6799023/6f787830-d24d-11e4-91ff-b15eae0f4fa7.JPG)

**Comment by matthijskooijman** [comment]
Is there any error _before_ the ld error? Could you try again with verbose compilation enabled, and post the full output (from the bottom window) and your full sketch code?

**Comment by laisan86** [comment]
No! No compilation errors, I checked many times.

**Comment by ffissore** [comment]
Can you share the whole sketch?

**Comment by agdl** [comment]
https://github.com/arduino/Arduino/issues/1469

**Comment by HiTechHiTouch** [comment]
Please see [Issue 2989](https://github.com/arduino/Arduino/issues/2989#issuecomment-245832814).  There are full dumps and source all zipped up, including the Windbg analysis.  There should be more than enough information for someone with the LD.exe source to trace the problem.
![windbg anaylsis](https://cloud.githubusercontent.com/assets/11083774/18379361/2f7690f8-7640-11e6-97cf-ce611b578cb1.png)
