### ISSUE TITLE
Software Serial missing

### ISSUE THREAD

**Issue by Danyc0** [arduino/Arduino#2818]
Software Serial seems to have been removed from the new versions of the IDE, i heard it was meant to be replaced by a newSoftSerial library but that doesn't seem to exist either?

**Comment by hashashin** [comment]
Hi @Danyc0, for me the library is still there, which IDE version you've?
https://github.com/arduino/Arduino/tree/1.6.1/hardware/arduino/avr/libraries/SoftwareSerial
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/libraries/SoftwareSerial

**Comment by PaulStoffregen** [comment]
Maybe you have the wrong board selected?

The new IDE doesn't show libraries for AVR when you have a Due selected, for example.  Or if you've installed a non-Arduino board (and selected it in Tools > Boards), maybe Arduino is not picking up that it supports SoftwareSerial.

**Comment by Danyc0** [comment]
Yea, that was me being stupid, thanks guys!
