### ISSUE TITLE
Arduino Micro Interrupt 6 (pin 7)

### ISSUE THREAD

**Issue by dpuyosa** [arduino/Arduino#2819]
In the Arduino Micro main page it doesnt list this Interrupt, that is avaible for the ATmega32u4 (http://arduino.cc/en/Main/arduinoBoardMicro). Since on the micro interrupts 0 to 3 are "not avaible" unless you lose USB Serial connection (pins 0, 1) or I2C/TWI (pins 2, 3) I think it should be listed to avoid trouble for newcomers.

**Comment by agdl** [comment]
added thank you
