### ISSUE TITLE
Mac build fails with "MacOSX requires MACOSX_BUNDLED_JVM property set"

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#2835]
Does Arduino now require extra setup to build on Macintosh?

**Comment by PaulStoffregen** [comment]
BUILD FAILED
    /Users/paul/1.6.2/build/build.xml:58: The following error occurred while executing this line:
    /Users/paul/1.6.2/build/build.xml:258: MacOSX requires MACOSX_BUNDLED_JVM property set

**Comment by Wackerbarth** [comment]
I ran into the same problem. Commit b48e07c switched to using the branch that was created to upgrade to a newer version of java. However, although I have the latest JDK and JRE installed, I cannot figure out where I should have this environment variable point. Does anyone know what we need?

**Comment by PaulStoffregen** [comment]
It's fixed  https://github.com/arduino/Arduino/commit/319f1c3b632bb52a5814337df9d984618f068db4
