### ISSUE TITLE
http://arduino.cc/en/Reference/EEPROM isn't updated with changes introduced in 1.6.2

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2840]
That's all

**Comment by sej7278** [comment]
Nor has the entirely new library/hardware directory structure been documented.

The 1.5.x - 1.6.1 structure is documented here for comparison:

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5---3rd-party-Hardware-specification
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by facchinm** [comment]
Fixed updating docs
