### ISSUE TITLE
[DOC] Why aren't Serial.readString() and Serial.readStringUntil() documented in web Reference?

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2842]
Serial.readBytes() and Serial.readBytesUntil() are, for instance. Is there any reason for this? Thanks

**Comment by agdl** [comment]
Done they are online here
http://arduino.cc/en/Reference/Serial

http://arduino.cc/en/Serial/ReadString

http://arduino.cc/en/Serial/ReadStringUntil

**Comment by q2dg** [comment]
Ok. Thanks!!
