### ISSUE TITLE
1.6.2 IDE - support for additional boards - RedbearLab boards ?

### ISSUE THREAD

**Issue by henrysinn** [arduino/Arduino#2845]
Hi.
I've just upgraded to the latest IDE and like / love the idea of a 'boards manager' 
I've followed instructions from http://blog.arduino.cc/2015/03/28/arduino-ide-1-6-2-released/
but unfortunately I'm not seeing the boards I need / have

ie. Some from redbearlab.com

How do I install 3rd party boards in the interim?

**Comment by ffissore** [comment]
The usual instructions (sketchbook "hardware" folder etc) will work as usual. We are working on some new cores and libs

**Comment by henrysinn** [comment]
Thanks for the note Federico.
Unfortunately it's not. Something isn't working / connecting.. 
Henry

**Comment by ffissore** [comment]
It may be because of a bug we introduced in 1.6.2 and that we're fixing.

**Comment by ffissore** [comment]
Hold on until we fix it

**Comment by henrysinn** [comment]
OK / Thanks for the update

**Comment by henrysinn** [comment]
Hi Federico / all.

Any update/s?

Henry

**Comment by agdl** [comment]
@henrysinn the 1.6.3 fix the problem. Please try it and close this issue if it works :)

**Comment by henrysinn** [comment]
Hi agdl.
Sorry for slow response

Have tried without success...


Pretty easy to try yourself even if  you don't have a board:
1. Get "RedBearLab Blend Add-On version 20140701" from http://redbearlab.com/getting-started-blendmicro
2.  "Follow the yellow brick road" - steps 5, 6, 7, and 8 in particular - the rest doesn't matter 

Henry

**Comment by sakulstra** [comment]
Same problem here :+1: 

Regards,
Lukas

**Comment by cmaglie** [comment]
Looking at the "source code" link it seems that RedBearLab has released an 1.6.x update:

https://github.com/RedBearLab/Blend/

Please try the archive download from github, here the link: https://github.com/RedBearLab/Blend/archive/master.zip

**Comment by henrysinn** [comment]
Hi cmaglie,

This works.

Henry
