### ISSUE TITLE
SoftwareSerial returns impossible values

### ISSUE THREAD

**Issue by Goz3rr** [arduino/Arduino#2858]
I have the following code (Arduino 1.6.1):

    if(_bt.available() > 0) {
    	int data = _bt.peek();
    	bool found = true;

    	if(data == 'a') {
    		// do something
    	} else if(data == 'b') {
    		// do something else
    	} else {
    		found = false;
    	}

    	if(found) _bt.read();
    }

(It's set up like this because it's a library, and if unknown messages are found they should be passed to the code handling other commands, if that makes sense)

At random points the Arduino would stop reacting to any received messages, and after adding some debug code I found out that while `_bt.available()` would keep incrementing with each message received, `_bt.peek()` returns some a nonsense negative value but `_bt.read()` will return something completely different, these are some i've encountered so far:

-1 == 255
-76 == 180
-1 == 255
-36 == 220
-1 == 255
-5 == 251
-72 == 184
-36 == 220
-18 == 238

I'm not sure where these values originate from because I'm never sending them to the HC-05 attached to this SerialPort. Worth noting is that once this happens even if i disconnect the HC-05 the SoftwareSerial will keep returning the last values, so I assume some buffering is done internally.

**Comment by matthijskooijman** [comment]
What board are you using? Could you see if you could reproduce this problem using a minimal sketch, preferably without any external hardware attached?

Are you sure you're using the official SoftwareSerial library, and not some other library inside your sketchbook? Perhaps you should post the full verbose compilation output, which should show this.

**Comment by Goz3rr** [comment]
These are school supplied Arduino Uno's and HC05 Bluetooth modules, I'm not sure if they're genuine Arduinos but I have managed to reproduce it with multiple Arduinos and HC05's and a minimal sketch, I haven't been able to recreate it without external hardware because it doesn't seem to happen while no data is being sent, however it does seem to happen more often when messages are sent more often, baud rate is 9600 so that shouldn't be too high. I'm currently on a bus but I'll post compilation output in a moment.

**Comment by matthijskooijman** [comment]
Cool, thanks!

If you can reproduce it by using output from another Arduino (connect its TX pin to the softwareserial RX pin), that would also help a lot. I don't think genuine or clone Arduino would make much of a difference here, btw.

**Comment by Goz3rr** [comment]
So far I haven't been able to reproduce this between two Arduinos, it only seems to happen with this specific bluetooth module

**Comment by sbrynen** [comment]
You're looking at the same thing; just the difference between signed and unsigned numbers.
byte signed: -1 = byte unsigned 255

If you look carefully at all the numbers you supplied, you'll notice that the difference between the two numbers is always 256.

**Comment by sandeepmistry** [comment]
There is a subtle difference between ```SoftwareSerial::read()``` and ```SoftwareSerial::peek()```, ```read``` converts the buffered byte to a ```uint8_t``` before returning, ```peek``` does not.

I'll prepare a pull request to correct this.

**Comment by Goz3rr** [comment]
Cool to see someone bothered to look at old issues, and in retrospect that makes a lot of sense

**Comment by sandeepmistry** [comment]
I've submitted #4669 to resolve this.
