### ISSUE TITLE
Library Installer can install items that are not libraries

### ISSUE THREAD

**Issue by tboicey** [arduino/Arduino#2861]
While using OS-X version 1.6.2, I was installing several libraries from ZIPs that were in my Downloads folder using the "Include Library / Add .ZIP library" menu items.

I *SUSPECT* that one time instead of opening the Downloads folder, I actually highlighted and chose the Downloads folder to install. There was a pause, then the IDE resumed and I assumed nothing had happened.

However I noticed today that the app had actually made an entire copy of my Downloads folder in the Arduino library folder (several gigs of random files, dmgs, etc).

Could some safety code be added here that did some simple validation that what is being worked on is indeed a library file?

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
