### ISSUE TITLE
Character modifying key combinations do not work

### ISSUE THREAD

**Issue by stolendata** [arduino/Arduino#2864]
Character modifying key combinations such as tilde (alt-gr + ~), umlaut (¨) and other accents do not work in the IDE. The modifying keystroke is accepted, but the following keystroke never outputs a character.

The problem is in both 1.5.8 and 1.6.1, and I have only tested this on Linux Mint 16 and 17.1 32-bit.

**Comment by stolendata** [comment]
Fix: https://github.com/arduino-org/Arduino/commit/5d429fa62f7e2907bfc568a3abc06a2ffad14a12

**Comment by ffissore** [comment]
Closing as duplicate of #2620. A fix is on its way

**Comment by ffissore** [comment]
Issue is being fixed with a brand new editor. See #3019

**Comment by ffissore** [comment]
#3019 merged. Next hourly build and IDE 1.6.5 will contain the fix
