### ISSUE TITLE
Fix for deprecated features.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#2866]
In the new compiler (4.8.1 - AVR) the prog_* variants (`prog_char`) are deprecated and removed. Standard types should be used instead (`char`).

These could be re-activated by adding a compiler option `-D` for `PROG_TYPES_COMPAT`.

It appears many people are using libraries/examples which declare these types causing *type undeclared* errors. It would avoid a lot of headache by simply keeping them in (if the PROGMEM added to the prog_* defines doesn't cause problems).

**Comment by facchinm** [comment]
Hi @Chris--A ,
we are trying to get rid of all the legacy and deprecated definitions "the hard way" ™ so defining `__PROG_TYPES_COMPAT__` could only slow down the adoption of the new ones.

Also, the definition does not automatically solve the compile failure but simply tells to add the keyword `const`, leaving the deprecation problem opened. Instead, if the library author fixed it "the right way" ™ it would be fixed forever.

However you are right, the error without the `#define` is cryptic and we should do something more to tell the user a possible solution. 

An entry about this topic exists ( https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions#errors-related-to-avr-progmem-changes) but it's not easily reachable, so we'll integrate it in the Reference soon.

Cheers!
