### ISSUE TITLE
parseInt documentation issues

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#2867]
There are a number of problems with parseInt documentation:
 - There are three places where it is documented. One is about Stream::parseInt and two about Serial::parseInt. All three of them are different, even thought the refer to the same function
     - http://arduino.cc/en/Reference/ParseInt
     - http://arduino.cc/en/Reference/StreamParseInt
     - http://arduino.cc/en/Serial/ParseInt
 - There is a single optional parameter, called `skipChar`, which specifies a non-digit character that is skipped inside the number. This can be used for e.g. a thousands separator.
 - The return type should be `long`, not `int`. Previously, #870 was closed stating that `parseInt` really returns `int`, but the code disagrees: https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Stream.cpp#L114
 - The documentation should clearly specify how `parseInt` works. In particular, it should state that:
    - Initial characters that are not digits or a minus sign, are skipped
    - Parsing stops when no characters have been read for a configurable timeout value, or a non-digit is read
    - If no valid digits were read when the timeout occurs, 0 is returned
   Currently, none of the three documentation pages have _all_ of the above info.

This issue is partly based on, and replaces #2154, #1713 and #870

**Comment by agdl** [comment]
@matthijskooijman i modified

http://arduino.cc/en/Reference/ParseInt

If you think is ok i will modify the others according to this

**Comment by matthijskooijman** [comment]
The skipChar parameter is not documented, and there should probably be a link to how to the timeout can be set (I don't know off-hand).

**Comment by agdl** [comment]
do you mean as done here? (timeout)

http://arduino.cc/en/Serial/ReadBytesUntil

**Comment by matthijskooijman** [comment]
Yup, though you should probably check if that `setTimeout` is actually used for `parseInt` as well. If so, `setTimeout` documentation should list `parseInt` as well.

One more thing: It seems the font in the `parseInt` page for the list you probably copied from my post, is different from the rest of the page.

**Comment by agdl** [comment]
The font is different because I used a list style format to empathise the key points :)

**Comment by agdl** [comment]
Should be good now. If you agree with me I'll indicate the same things in the other references

**Comment by matthijskooijman** [comment]
It doesn't indicate that skipChar is optional yet...

**Comment by agdl** [comment]
I stated in the syntax that it can be written in two ways

**Comment by matthijskooijman** [comment]
Oh indeed, missed that. Looks acceptable to me now (though the font issue still seems to be there?)

**Comment by agdl** [comment]
Actually is not an issue. In the used language that font is related to the list usage

**Comment by matthijskooijman** [comment]
Ah, right. No more comments from me, then :-)

**Comment by agdl** [comment]
Updated the other pages
