### ISSUE TITLE
New StereoSID library to add to Library Manager

### ISSUE THREAD

**Issue by daitangio** [arduino/Arduino#2870]
Hi, I'd like to add my library to Arduino Library Manager (I have read the FAQ at https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ).
The library is StereoSID, a SID emulator with stereo capability.
It is in developement, and works well.
You can find it at https://github.com/daitangio/sid-arduino-lib
Current stable release:
https://github.com/daitangio/sid-arduino-lib/releases/tag/StereoSID-2.0.2

**Comment by ffissore** [comment]
library.properties misses 'url' field

**Comment by daitangio** [comment]
Sorry, I have just fixed it and tested with IDE 1.6.x.
Do I need to add other file/fields?

**Comment by ffissore** [comment]
I think not. Once tagged, if successful, in at most an hour you'll see your lib listed

**Comment by daitangio** [comment]
Hi, I just retagged it with a new label and the correct library.properties
https://github.com/daitangio/sid-arduino-lib/tree/StereoSID-2.0.3
Is it right or must I do something else?
Thank you :)

**Comment by ffissore** [comment]
It's already in the list of repo. It should come up in the IDE in at most an hour

**Comment by ffissore** [comment]
And thank you! :)
