### ISSUE TITLE
Request to add new library: aREST

### ISSUE THREAD

**Issue by marcoschwartz** [arduino/Arduino#2872]
Hello,

I am the maintainer of the aREST (http://arest.io/) library that implements a RESTful API for Arduino. It works on most Arduino boards, and can be used via HTTP (Ethernet or WiFi), Serial, or Bluetooth LE.

It's used by several hundreds of people for their projects, I have about 200 views/day on the library page and I have a lot of interaction with users. The link:

https://github.com/marcoschwartz/aREST

I just updated the library with a library.json & library.properties files. Could you add it to the Arduino library manager? If you need more details let me know. Thanks!

Cheers,
Marco Schwartz

**Comment by ffissore** [comment]
There are no tags on lib repo. Please review https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by marcoschwartz** [comment]
I just added a release today with a tag. Let me know if this is ok now, thanks.

**Comment by ffissore** [comment]
Added. Thanks!

**Comment by marcoschwartz** [comment]
Thank you!
