### ISSUE TITLE
Arduino 1.6.3 (Mac) warns about unconfirmed developer identity.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#2877]
I get the attached dialog when trying to open the software. (It's possible to work around this by right-clicking the file and selecting open from the pop-up menu, but this shouldn't be necessary.)

![screen shot 2015-04-02 at 9 11 34 am](https://cloud.githubusercontent.com/assets/405058/6964568/7b45b0c0-d918-11e4-8572-ae669f835d19.png)

**Comment by ffissore** [comment]
Argh... @cmaglie is re-packing it. It's a matter of minutes

**Comment by damellis** [comment]
Great. Just wanted to let you know...

**Comment by cmaglie** [comment]
The file has been replaced, can you try to download again?
