### ISSUE TITLE
Serial monitor in 1.6.3 (Linux, 64 bits) doesn't work

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2882]
When I try to open it, this error message  appears in the IDE console: "Board at /dev/ttyACM0 is not available" . But if I use another serial terminal (like picocom), it just works.
This issue doesn't happen in 1.6.1

**Comment by PaulStoffregen** [comment]
I've been seeing something similar too, but for me it manifests as not being able to open the serial monitor for a few seconds after uploading.  Not sure if that's related or completely different, but I intend to dig into it.

**Comment by facchinm** [comment]
Probably related to #2892, fix already merged and available in nightly
