### ISSUE TITLE
Library and Board managers haven't close button (X) in Fedora 21 (64 bits)/Gnome 3.14

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2884]
...So I can't close its modal windows unless I right-click over it to show system contextual menu and select "Close" from it. It's a nuisance

**Comment by ffissore** [comment]
This is new to me: can you attach a screenshot?

**Comment by q2dg** [comment]
Yes!
Here they are
![boardmanager](https://cloud.githubusercontent.com/assets/7274874/6970230/5c53e75c-d974-11e4-9839-4e21933879d6.png)
![librarymanager](https://cloud.githubusercontent.com/assets/7274874/6970229/5c532060-d974-11e4-882f-406c237141c3.png)

**Comment by ffissore** [comment]
Ok. Wow. No buttons. Uhm.. Anyway, if you press ESC once or twice, the modal will close

**Comment by ffissore** [comment]
It's a workaround. I'll see where I can put a close button

**Comment by q2dg** [comment]
Ok. Thanks!

**Comment by sej7278** [comment]
Same on Debian Jessie 64-Bit with Gnome 3.14, escape works, but there's no icon

**Comment by ffissore** [comment]
Fixed. Fix will be available with the next hourly build http://www.arduino.cc/en/Main/Software#hourly
