### ISSUE TITLE
Open file by double-clicking it not working

### ISSUE THREAD

**Issue by 00alis** [arduino/Arduino#2888]
When I open a .ino file by double clicking it in the file system, the IDE is correctly launched but opens a new file instead of the one I selected.

here a video to demonstrate this behavior
https://www.dropbox.com/s/shakdis0av182sl/not%20opening%20file.mov?dl=0

@ffissore

**Comment by stitchineer** [comment]
I'm having this same problem. I'm using Mac OS X 10.10.2

**Comment by ffissore** [comment]
Fixed in latest hourly http://www.arduino.cc/en/Main/Software#hourly
