### ISSUE TITLE
Check for newer library versions after compile errors

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#2889]
After any compile error, Arduino should check if the core library or any of the libraries the sketch uses have newer versions.  If so, a helpful message should be printed to advise the user newer versions are available, which might solve their problem.

Perhaps the fetching of the latest library list only need to occur if the current copy is older than a few days, so every compile error from every user doesn't generate needless internet communication.

**Comment by ffissore** [comment]
Mitigated by update notification introduced with #3625
