### ISSUE TITLE
Add USB Host Shield Library 2.0 to the library manager

### ISSUE THREAD

**Issue by Lauszus** [arduino/Arduino#2893]
Please see: https://github.com/felis/USB_Host_Shield_2.0.

**Comment by ffissore** [comment]
The lib misses at least a tag. Please review https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Lauszus** [comment]
Sorry I had to merge something before I wanted to tag it. It is tagged now :)

**Comment by ffissore** [comment]
Added. Thanks!
