### ISSUE TITLE
links from Arduino site not working - wifi shield

### ISSUE THREAD

**Issue by alexmac131** [arduino/Arduino#2896]
https://github.com/arduino/Arduino/tree/master/hardware/arduino/firmwares

Does not work http://arduino.cc/en/Hacking/WiFiShieldFirmwareUpgrading

**Comment by alexmac131** [comment]
The issue also relates to the removal of the firmware tools in the current master branch.  One possible fix I am going to do is go back to a revision that has the bits used by the firmware hardware/tools/  sub dir and give it a go.

**Comment by alexmac131** [comment]
So here is the rather odd little fix...

Check out the base Arduino code  for  ide-1.0.x,  copy in the missing the tools into your current release. I am use 1.6.2 for the hardware, you have to change the mac fix script and you need to copy in the wifi firmware as well

**Comment by agdl** [comment]
The correct link is https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/firmwares I updated the on-line page!

**Comment by solarfly73** [comment]
:+1:
