### ISSUE TITLE
Add 'mqtt' lib to library manager.

### ISSUE THREAD

**Issue by 256dpi** [arduino/Arduino#2897]
Would be cool, if you could add this library to the manager:
https://github.com/256dpi/arduino-mqtt

**Comment by ffissore** [comment]
Library it's ok, but its tag 1.3.0 is not. To comply with semver syntax, 1.3 is automatically converted to 1.3.0. As next tag is 1.3.0, our job skips that version because it's already listed. Please bump version 1.3.0 to something like 1.3.1

**Comment by ffissore** [comment]
1.3.0 is in the list. you're free to tag 1.3.1 (or whatever version you'll choose)
