### ISSUE TITLE
1.6 upgrade concern on OSX

### ISSUE THREAD

**Issue by vikfors** [arduino/Arduino#2899]
![skarmavbild 2015-04-03 kl 23 05 51](https://cloud.githubusercontent.com/assets/11790601/6989045/4d4b9cbc-da57-11e4-9de8-bd3da7e9066e.png)
Compiling the same code on 1.0.5 and 1.6.3 gives the results shown
What is wrong?
Leif

**Comment by PaulStoffregen** [comment]
You have to add "const" to the variable.  The old avr-gcc toolchain didn't require this.  The new one does.

**Comment by ffissore** [comment]
@vikfors see https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions#errors-related-to-avr-progmem-changes

**Comment by vikfors** [comment]
OK,
Thanks for the info.
In my case changing the variable from static to const did solve the problem.
Tested and that works fine.
I also had a problem with a project that was using SD.h
This was calling SPI.h
That was resolved by including SPI.h in the project directly.
A bit weird that it no longer works when called indirectly and it took me a while to find the solution.
