### ISSUE TITLE
1.6.2+ Use of Windows Appdata folder appears to breach Microsoft usage guidelines

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [arduino/Arduino#2902]
See https://msdn.microsoft.com/en-us/library/windows/apps/hh465094.aspx

The Windows AppData folder is not intended to be used to store binaries or other large files

(From the page linked to)

"Use roaming for user preferences and customizations, links, and small data files. For example, use roaming to preserve a user's background color preference across all devices."

"Don't roam large sets of app data. There's a limit to the amount of app data an app may roam; use RoamingStorageQuota property to get this maximum. If an app hits this limit, no data can roam until the size of the app data store no longer exceeds the limit. When you design your app, consider how to put a bound on larger data so as to not exceed the limit. For example, if saving a game state requires 10KB each, the app might only allow the user store up to 10 games."

Also. The folder will sync via Microsoft's cloud syncing service for some users, which may be a bandwidth issue to some users.

**Comment by sej7278** [comment]
the same goes for linux, binaries and compilers should never be stored in user's home directories.

its not good security practice, impossible to package, not good for backups, not good for multi-user systems.....
