### ISSUE TITLE
Patch to set baudrate in Bridge.h (Arduino Yún, Yún shield)

### ISSUE THREAD

**Issue by mschlenker** [arduino/Arduino#2904]
The Arduino Yún currently uses an optimistic baud rate setting of 250000 that is hardcoded to busybox' inittab and the bridge library. While this works on the combination of 32u4 and AR9331 under medium loads, it fails on interrupt storms and will probably fail in the future when using the upcoming Yún shield on some 328P variants. On Uno knock offs with slightly out of range oscillators 57600 seems good, on 328P with the internal 8MHz oscillator, 19200 is reliable.

Thus I suggest starting with a small patch to allow the user to set the baud rate:

https://gist.github.com/mschlenker/03b242de9627c5e38ddc

In the mid term, the Yún shield (or anything compatible) should announce the suitable baudrate via Avahi (along with the detected MCU).

Update: Alternatively you might want to import Paul Stoffregens slightly modified version of the bridge that also allows using software serial:

https://github.com/PaulStoffregen/Bridge

**Comment by ffissore** [comment]
Patch applied. Bridge library 1.0.4 will be available through library manager in the next hour
