### ISSUE TITLE
Version number too low, please raise to 2.0.0

### ISSUE THREAD

**Issue by mschlenker** [arduino/Arduino#2912]
"The other guys and gals™" just released 1.7.0, judging features based on "This side©" 1.5.x or 1.6.0. Thus I suggest racing, ahemmm, raising the version number accordingly.

**Comment by PaulStoffregen** [comment]
In the long run, copying older versions of Arduino and falsely labeling them with a higher versions is only going to destroy their credibility with the few people who can overlook all the other shady stuff they've done.

**Comment by mschlenker** [comment]
What makes matters worse is that their github repos README.md points here for issues.

**Comment by sej7278** [comment]
Please don't mess with versions just to beat the "other side".

**Comment by cmaglie** [comment]
We are not going to change version because a fork of the Arduino IDE has been re-released with an upper version number.

Closing as wontfix.

**Comment by matthijskooijman** [comment]
@cmaglie, FWIW, it might be sane to consider to skip the 1.7.x version later on, to prevent confusion. But that's something to consider when the a new minor version number is needed, and the dust has settled wrt the .org situation.
