### ISSUE TITLE
Add Adafruit GFX library to master library list.

### ISSUE THREAD

**Issue by tdicola** [arduino/Arduino#2913]
This issue is just to add the Adafruit GFX library to the master library list so it can be pulled into Arduino's new library manager system.  

The URL for the repository is: https://github.com/adafruit/Adafruit-GFX-Library.git  

Right now the library should be tagged and setup with a library.properties file as required by the library system specs.  Let me know if there are any issues or concerns adding this library, thanks!

**Comment by ffissore** [comment]
Added. Thanks!
