### ISSUE TITLE
Comments for RX TX pins are reversed on image under "Overview"

### ISSUE THREAD

**Issue by Sharokd** [arduino/Arduino#2915]
Comments for RX TX pins are reversed on image under "Overview"

http://arduino.cc/en/Main/ArduinoGSMShield
![gsmpinuse_2 bad](https://cloud.githubusercontent.com/assets/10146967/6996409/e46a398e-db54-11e4-9077-0230e91dc093.jpg)

**Comment by agdl** [comment]
@Sharokd corrected tahnk you
