### ISSUE TITLE
missing component: Due USB host library not in 1.6.3 bundle

### ISSUE THREAD

**Issue by bgodard** [arduino/Arduino#2916]
The USB host library for the Arduino Due USB host port is not in the 1.6.3 bundles. But the docs are in.
I had to get it from the github repository.

Documentation:
http://arduino.cc/en/Reference/USBHost
and the sources:
https://github.com/arduino/Arduino/tree/master/libraries/USBHost

**Comment by ffissore** [comment]
@bgodard DUE support is no more bundled with the IDE and must be installed with Boards Manager (tools > board > boards manager). DUE libs like USBHost, Audio and Scheduler can be installed with Library Manager (Sketch > Include library > Manager Libraries)
