### ISSUE TITLE
Due Core files do not show up in hardware (still show up in Boards menu)

### ISSUE THREAD

**Issue by Asaurus1** [arduino/Arduino#2918]
I need to edit the variant.cpp file for the Due. In previous versions this was located in the hardware subdirectory. In 1.6.3 it seems that the Due core files are not even installed in the arduino-1.6.3 directory. The fact that these files are "missing" is a problem, even though I can still compile to the Due like before.

**Comment by ffissore** [comment]
@Asaurus1 The IDE does no longer bundle SAM files. They need to be installed using boards manager. I've added an entry to Boards Manager FAQ: https://github.com/arduino/Arduino/wiki/Boards-Manager-FAQ#where-are-installed-cores-located

**Comment by Asaurus1** [comment]
You might consider adding a "open core folder" link to the board manager entries.

**Comment by ffissore** [comment]
Right, and you're not alone with this feature request #2874
