### ISSUE TITLE
tone command does not work correctly on ATmega8 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#292]
This is [Issue 292](http://code.google.com/p/arduino/issues/detail?id=292) moved from a Google Code project.
Added by 2010-07-15T07:34:09.000Z by [p.reckte...@gmail.com](http://code.google.com/u/100614490999857774768/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. load and run a tone example script, f.e. toneMelody.pde

**What is the expected output? What do you see instead?**

You can hear the melody correctly on a Arduino Duemilanove with ATmega328.
On a board with ATmega8 you can only hear one tone (NOTE_B3 I think??). 

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Arduino018 on Windows 7. myAVR USB MKII board with ATmega8 3.6864MHz Quarz.

**Please provide any additional information below.**
Only the following frequencies give a correct signal: 61Hz, 244Hz, 976Hz, 3.9KHz. Any other frequency gives no signal (PWM output signal measured with oscilloscope)

**Comment by jan-r** [comment]
A fix for this issue has been proposed, see pull request #2961.

**Comment by facchinm** [comment]
PR #2961 merged
