### ISSUE TITLE
[DOC] Mention in http://arduino.cc/en/Serial/SetTimeout (description section) of parseInt()/parseFloat() methods

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2920]
Thanks.

Aah...and another thing..Maybe it's worth adding the "in particular" section showed in parseInt() page to parseFloat() page . For consistency.

**Comment by agdl** [comment]
Done thank you! I linked to the Serial and Stream page where all the methods are listed!

**Comment by q2dg** [comment]
But now you have removed mention to Serial.readString() and Serial.readStringUntil() !!??

And I insist: Maybe it's worth adding the "in particular" section showed in parseInt() page to parseFloat() page . For consistency.
