### ISSUE TITLE
Add EEPROMex library to the library manager

### ISSUE THREAD

**Issue by rric** [arduino/Arduino#2921]
Download: http://thijs.elenbaas.net/downloads/?did=6
Docs: http://playground.arduino.cc/Code/EEPROMex, http://thijs.elenbaas.net/2012/07/extended-eeprom-library-for-arduino/

**Comment by q2dg** [comment]
Have you see the changes in new official EEPROM library? (http://arduino.cc/en/Reference/EEPROM)

**Comment by ffissore** [comment]
Please provide a git repo to fetch library code from. Also see https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
