### ISSUE TITLE
Precision of the reading in the temperature web panel

### ISSUE THREAD

**Issue by DPicard15** [arduino/Arduino#2922]
The ADC to milivolt conversion is not working properly in the code for the example of the temperature web panel.  In the division I had to add a decimal to the value because the result was truncating it and I was losing precision.

Before :
      float voltage = (5000 / 1023) * sensorValue;  =4

After :
      float voltage = (5000.00 / 1023.00) * sensorValue; =4.88

**Comment by agdl** [comment]
@DPicard15 I added the cast thank you!
