### ISSUE TITLE
Tone.cpp stops compile when TCCR0A/TCCR0B defined and WGM01 not defined

### ISSUE THREAD

**Issue by jipp** [arduino/Arduino#2923]
In case using an own pins_arduino.h for the ATtiny861 the compile stops in Tone.cpp.

This can be avoided adding an additional "#if defined" statement which catches the case of undefined WGM01:

Tone.cpp line 154: 
#if defined(TCCR0A) && defined(TCCR0B) 
-> 
#if defined(TCCR0A) && defined(TCCR0B) && defined(WGM01)

**Comment by q2dg** [comment]
Is there any support to this microcontroller??
https://code.google.com/p/arduino-tiny/issues/detail?id=64

**Comment by jipp** [comment]
adding the above mentioned would allow to compile the sketch for the attiny861/461/261 using arduino ide 1.6.x:

https://github.com/damellis/attiny/pull/18

**Comment by facchinm** [comment]
Closed by merging #2972
