### ISSUE TITLE
SD library broken by 0e898d5e03eac5f0a42e658a35a57e758bf7e36a

### ISSUE THREAD

**Issue by McNeight** [arduino/Arduino#2924]
My code that had worked with previous versions of the Arduino IDE suddenly failed to work with 1.6.3 (didn't adequately test with 1.6.2). The SD card on an Arduino Ethernet was no longer readable. The SD card itself tested OK, but testing with the SD example sketch "listfiles" produced the same failure.

Adding the line `digitalWrite(10, HIGH);` after `pinMode(10, OUTPUT);` to the "listfiles" sketch caused it to function normally. No other changes were made to the sketch.

Commit 0e898d5e03eac5f0a42e658a35a57e758bf7e36a modified how SPI influences the state of the SS pin. I believe that a corresponding change needs to be made in the SD library in order for everything to work properly.

-Neil

**Comment by matthijskooijman** [comment]
This appears to be an issue with the example sketches, that has been exposed by that recent SPI change. This is already being tracked in #2868, so I'm closing this issue as a duplicate.
