### ISSUE TITLE
Max78630 energyboard library add request

### ISSUE THREAD

**Issue by akkoyun** [arduino/Arduino#2944]
hi all,
we developed a pollyphase measurement board an library 
https://github.com/x2bus/EnergyBoard
we want ta add library to arduino library manager  thanks

**Comment by ffissore** [comment]
Hi. Your library is in Library folder. Our job currently does not support fetching subfolders. That may change in the future but for now it's a blocking issue: we cannot add your library to lib manager.

**Comment by akkoyun** [comment]
i change the folder structure

**Comment by ffissore** [comment]
Great! Now you just need to make a "release" of your library (add a tag) and it will become available in lib manager

**Comment by akkoyun** [comment]
thats ok. (i think :) )

**Comment by ffissore** [comment]
Still no tags: https://github.com/x2bus/EnergyBoard/tags

**Comment by akkoyun** [comment]
thats ok now :)

**Comment by ffissore** [comment]
Done. Thanks :)

**Comment by akkoyun** [comment]
New version 1.1.0 relased what can i do ? 
is it included automaticly

**Comment by cmaglie** [comment]
You must change the version in `library.properties` (it's the version in this file that counts not the tag)

**Comment by ffissore** [comment]
Indeed. I've just made FAQ clearer https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by akkoyun** [comment]
so ? i made some thing wrong ?

**Comment by ffissore** [comment]
In your master, `library.properties` version is 1.1.0
In your tag 1.1.0, `library.properties` version is 1.0.2
In your tag 1.0.2, `library.properties` version is 1.0.1
In your tag 1.0.1, `library.properties` version is 1.0.1
Hence, we are able to publish version **1.0.1** from tag 1.0.1 and version **1.0.2** from tag 1.1.0 but I don't think that's what you really wanted.
To keep things simple, even if it's not needed, please use the same tag name as the version in your library.properties

**Comment by akkoyun** [comment]
oke i fix tag 1.1.0 thanks i understand system thank u

**Comment by ffissore** [comment]
Please make another tag, something like 1.2.0 with version 1.2.0 in library.properties

**Comment by akkoyun** [comment]
done

**Comment by ffissore** [comment]
Thanks

**Comment by akkoyun** [comment]
Hi,
our library name is changed from (max78630 - V1.2.0) to (EnergyBoard - from V2.0.0) 
but old library still at libmanager
can u delete old library (max78630)

thanks

**Comment by akkoyun** [comment]
Hi,
our GitHub Repo removed to
https://github.com/LVXElektronik/EnergyBoard
link. can i do something for arduino library ?
