### ISSUE TITLE
Library Manager (mandatory window on Arduino IDE v1.6.4)

### ISSUE THREAD

**Issue by misteralex** [arduino/Arduino#2945]
Hi,

currently I am working under Linux/GNOME context with Arduino IDE (Debianinux). 

So, I updated the IDE to the new version 1.6.4 and there is an issue when I open the new "Library Manager" section. It opens a separated mandatory window to manage the list of all available libraries but I cannot close this window.

Currently I have to kill Arduino IDE to restart to work properly.

Thanks

Alex

**Comment by ffissore** [comment]
Some linuxes windows theme don't show close/minimize/maximaze buttons on top of windows. We don't have a fix yet, but you can hit the ESC key or CTRL+W and the modal will close
Duplicate of #2884
