### ISSUE TITLE
Avrdude on Linux64 is compiled whitout libusb

### ISSUE THREAD

**Issue by eni23** [arduino/Arduino#2952]
arduino: 1.6.3 release from arduino-website
os: debian wheezy amd64

the avrdude-binary is not compiled with libusb, which means no usb-serial adapters are supported.   since most arduino-boards depend on usb-communication this is a quite big impact. 
workaround: compile avrdude 6.0.1 on your own and replace broken binary's

**Comment by mschlenker** [comment]
USB serial adapters usually are supported by the linux kernels drivers, not userland drivers. Those userland drivers are usually just needed for more exotic programmers. 

Could you please post the USB IDs of the USB serial adapter (lsusb output) and the kernel version you are using (uname -a). Then after plugging in the usb serial adapter take a look at the last lines in the out put of dmesg.

**Comment by matthijskooijman** [comment]
Agreed that libusb isn't needed for usb-serial adapaters, but not having libusb is still a problem for non-serial programmers like the JTAGICE3 and some others.

**Comment by ffissore** [comment]
I've checked the logs, and indeed since we switched to static compiling, avrdude is not linking to libusb anymore. Problem is without static, gcc fails with a missing LTO plugin.

**Comment by ffissore** [comment]
This issue was moved to arduino/toolchain-avr#23

**Comment by ffissore** [comment]
1.6.4 core and tools (with libusb fix) available through boards manager
