### ISSUE TITLE
Boards manager package_index.json checksum only works if lower case

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [arduino/Arduino#2953]
It appears that the checksum calculator used by the Boards Manager, only works if the checksum in package_index.json is lower case

e.g. this works

 "checksum": "SHA-256:2909a4c6dd6d7497e7e1b5fcaa2f66a100271417510f3a68593b65af8ff78c1c",

However this does not work

 "checksum": "SHA-256:2909A4C6DD6D7497E7E1B5FCAA2F66A100271417510F3A68593B65AF8FF78C1C",

I suspect your internal CRC generator code generates a lower case string, and you are doing case sensitive compare.

It would be best if it was case insensitive, as often CRC generator programs create upper case checksums

**Comment by ffissore** [comment]
Fixed. Nightly build will be ready in the next few hours
