### ISSUE TITLE
Add to Library Manager: Pushetta 

### ISSUE THREAD

**Issue by guglielmino** [arduino/Arduino#2954]
Url to repo
https://github.com/guglielmino/arduino-pushetta-lib

**Comment by ffissore** [comment]
You library is in a subfolder of the repo. We currently don't support this layout: libs have to be in the root. See also https://github.com/arduino/Arduino/issues/2944#issuecomment-91156647

**Comment by ffissore** [comment]
Just added this: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#is-my-git-repo-ok

**Comment by ffissore** [comment]
Closing for lack of feedback. Reopen when lib is ready for lib manager

**Comment by guglielmino** [comment]
sorry, I was quite busy and I have lost the feedback. Now library layout is right, how can I reopen the request. Thanks

**Comment by ffissore** [comment]
Thanks. However you still need to tag it.

**Comment by guglielmino** [comment]
I did it. I made a mistake in version, it's 1.0.0 in library.properties and 1.0 in tag, I hope this isn't a problem, eventually I make a new tag.

**Comment by ffissore** [comment]
Lib added. Thanks
