### ISSUE TITLE
Board manager: cores should support post install scripts

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#2956]
So we may install/updated windows drivers once a board support has been added

**Comment by damellis** [comment]
It seems like there are some potential security issues here. Maybe we should only do this for official cores?

**Comment by ffissore** [comment]
Indeed, that's what stopped me from implementing. Running it for trusted cores only looks good

**Comment by ffissore** [comment]
Fixed in 987cad2633b8f818ba1149ca434f086436555c2a
