### ISSUE TITLE
Arduino Forum Registration

### ISSUE THREAD

**Issue by biebergagabcbs** [arduino/Arduino#2958]
hello,

I am trying to register on the Arduino forums. the registration link I received is not working. is it possible to resend me the registration link. thanks a lot.

username: biebergaga. 

email: biebergaganbcnn@yahoo.com

https://id.arduino.cc/auth/activate/biebergaga/f807e746ee79913bc1111a77fccc84cf

**Comment by ffissore** [comment]
This issue was moved to arduino/forum-issues#189
