### ISSUE TITLE
Adding boards to Boards Manager

### ISSUE THREAD

**Issue by Isaac96** [arduino/Arduino#2967]
Hi
I was wondering if this is possible, maybe by editing arduino.l4j.ini ?
I want to add @rogerclarkmelbourne's STM32_Arduino (https://github.com/rogerclarkmelbourne/Arduino_STM32)
to it.Thanks!
-Isaac

**Comment by ffissore** [comment]
This is being tracked by #2949
We are looking for a automated solution. Old way of unzipping core into hardware still works of course
