### ISSUE TITLE
[DOC] Missing references to boards capables of using Keyboard & Mouse libraries

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#2968]
In http://arduino.cc/en/Reference/HomePage appears both libraries can be used only in Leonardo and Due but Micro and Esplora aren't mentioned.
Also, in http://arduino.cc/en/Reference/MouseKeyboard, Esplora is missing again.

**Comment by agdl** [comment]
In order to also include the Yùn and other future Leonardo based boards i corrected the statement in
Leonardo based boards

**Comment by q2dg** [comment]
Ok, but then...there is any place where is clearly shown which boards are Leonardo-based?

**Comment by q2dg** [comment]
@agdl ...

**Comment by q2dg** [comment]
@ffissore Thanks

**Comment by agdl** [comment]
@q2dg a leonardo based board is a board that uses a 32u4 micro-controller and i think is well known. Where dou you wanna see this statement?

**Comment by q2dg** [comment]
Well, I think "32u4 based boards" is better, so if an user doesn't know if a particular board is 32u4 based or not, he/she could look at its "product" page.
I will close the issue
Thanks
PD: For consistency, I would do the change in http://arduino.cc/en/Reference/MouseKeyboard , too.

**Comment by agdl** [comment]
modified thank you!
