### ISSUE TITLE
Link on ParallelProgrammer Page Not working.

### ISSUE THREAD

**Issue by aguerrero810** [arduino/Arduino#2976]
http://arduino.cc/en/Hacking/ParallelProgrammer

The Link to giveio is broken.

**Comment by testato** [comment]
it work in this moment

**Comment by mschlenker** [comment]
http://www.nongnu.org/uisp/docs.html might be the correct link for the source download - no binaries. Are there computers with parports still around? So this page might only be kept for µC archeological reasons.

**Comment by aguerrero810** [comment]
I don't have one, but It would be nice if the page was fixed for those who do.

**Comment by mschlenker** [comment]
Gosh. I like the wayback machine: https://web.archive.org/web/20150329233303/http://arduino.cc/en/Hacking/ParallelProgrammer Here the link still works.

**Comment by agdl** [comment]
changed thank you
