### ISSUE TITLE
Arduino Due not detecting on 1.6.3

### ISSUE THREAD

**Issue by shreyshan** [arduino/Arduino#2979]
The sam folder in hardware was missing. I added it in both of the mentioned paths
C:\Program Files (x86)\Arduino\hardware\arduino\
C:\Users\<Username>\AppData\Roaming\Arduino15\packages\arduino\hardware\

But it still doesn't show DUE in the boards list.
If i try doing it via board manager.
It says no internet connection. I even tried running IDE as administrator. Still can't connect to internet.

Kindly help me out

**Comment by ffissore** [comment]
Are you behind a proxy? If so, in File > Preferences you set up proxy
parameters

**Comment by ffissore** [comment]
Lack of feedback. Closing
