### ISSUE TITLE
The kalmanfilter library is 2 times available in the library manager

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#2983]
Following Library is 2 times available in the library manager in Arduino IDE 1.6.3 

https://github.com/TKJElectronics/KalmanFilter

**Comment by ffissore** [comment]
Reported upstream

**Comment by ffissore** [comment]
Thanks for the heads up!

**Comment by Lauszus** [comment]
@ffissore I believe this happened as I changed all words in the name with capital letters: https://github.com/TKJElectronics/KalmanFilter/commit/f214b76246e996e5a579b5cb4b17fbcc3ae53028.

**Comment by ffissore** [comment]
The duplicate needs to be manually removed

**Comment by ffissore** [comment]
Done

**Comment by Lauszus** [comment]
@ffissore it seems like there still is a duplicate? The one name "Kalman filter library" (version 1.0.0) should be removed.

**Comment by ffissore** [comment]
First you need to remove tag 1.0.0

**Comment by Lauszus** [comment]
Done.

**Comment by ffissore** [comment]
Done

**Comment by Lauszus** [comment]
@ffissore this problem is still present.

**Comment by ffissore** [comment]
@Lauszus did you remove the tags with the wrong names? I'm setting up a weekly job that will regenerate the list completely, but if the offending tag is still there, the problem will keep on showing up

**Comment by ffissore** [comment]
FYI I've added an entry in the FAQ https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#sorry-i-did-something-wrong-how-can-i-change-or-unpublish-an-already-published-library

**Comment by Lauszus** [comment]
@ffissore yes there is only one tag: https://github.com/TKJElectronics/KalmanFilter/tags.

That might also solve the problem that the [USB Host Shield library](https://github.com/felis/USB_Host_Shield_2.0) is still at 1.0.0 despite the fact that I released 1.1.0 a while ago: https://github.com/felis/USB_Host_Shield_2.0/tags.

**Comment by ffissore** [comment]
List re-re-generated. Close issue if ok

**Comment by Lauszus** [comment]
Thanks that fixed the issue. Note that I can't close the issue, as it was opened by @jantje.

**Comment by jantje** [comment]
I can :-)
