### ISSUE TITLE
Problem after upgrading Yun to 1.5.3

### ISSUE THREAD

**Issue by ptestoni** [arduino/Arduino#2984]
After upgrading Yun OpenWRT to 1.5.3 my board cannot be connected to internet more than 2 hours. After rebooting it works but only for an instant.  
I already upgrade the OpenWRT again, following all instructions, but the issue remains...

Any help is welcome!

**Comment by ffissore** [comment]
Hi @ptestoni, please use the yun forum as this repository and its issues are dedicated the to development of the Arduino IDE only
http://forum.arduino.cc/index.php?board=93.0

Thank you for your understanding
