### ISSUE TITLE
Arduino 1.6.3 Hang on saving

### ISSUE THREAD

**Issue by thegrazingcow** [arduino/Arduino#2994]
Using with an arduino uno. When saving any sketches, the IDE will hang for around 5-10 seconds before resuming.

**Comment by facchinm** [comment]
Hi @thegrazingcow , can you give some more information about your PC (CPU / RAM) and environment (operating system etc) ?

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen if needed.
