### ISSUE TITLE
Permanent "Ignoring Bad library name" error

### ISSUE THREAD

**Issue by Artistblock307** [arduino/Arduino#2995]
for the time being please disregard this post

**Comment by facchinm** [comment]
Finding all references to `WProgram.h` and changing them to `Arduino.h` should solve the issue. 

However, if you are using legacy libraries you could encounter other problems; here (https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions)  you can find a list of the most common troubles and how to solve them

**Comment by matthijskooijman** [comment]
Seems the issue description was removed in an edit to say "for the time being please disregard this post". I'll go ahead and close this issue then.
