### ISSUE TITLE
Not reloading keywords.txt for new boards

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#2996]
If a new board definition via sketchbook/hardware/myboard has intern libraries with keywords.txt they are not loaded after a board switch.

Example:
Select Arduino Leonardo. Type Gamepad. It will not mark orange. Thats fine.
Now switch to the HID Project Leonardo Board (which has a library with Gamepad as keyword).
You see its still not highlighted.
Close the IDE and restart it. Since the setting is now the HID Project at startup it will load its keywords.

Example file:
https://github.com/NicoHood/HID/tree/master/avr/libraries/HIDBridge

tested with 1.6.3 under Windows

**Comment by cmaglie** [comment]
Fixed with #3847
