### ISSUE TITLE
UniCode and Diacritical Characters in Arduino 1.6.2/1.6.3

### ISSUE THREAD

**Issue by j-s-com** [arduino/Arduino#3000]
With Arduino Software 1.6.2/1.6.3 for Mac it is not possible, to enter a UniCode or diacritical Character in the IDE. You cannot make comments with them and you cannot use them in Strings. Up to Version 1.6.1 everything was OK. I urgently need them for comments and for Strings to display on a terminal screen. Copy and paste works as a workaround but is no solution.

**Comment by ffissore** [comment]
Confirm. It's a bug and a solution is on its way. Closing as duplicate of #2620

**Comment by ffissore** [comment]
Issue is being fixed with a brand new editor. See #3019
