### ISSUE TITLE
arduino software should use original driver instead of apple one

### ISSUE THREAD

**Issue by LunarLanding** [arduino/Arduino#3001]
If this software is expected to work out of the box, the procedure described here:
http://forum.arduino.cc/index.php?topic=198539.30
should be applied automatically for osx 10.9+

**Comment by ffissore** [comment]
I can't find the procedure you mentioned. Can you be more specific? Also, we don't bundle drivers for macosx. And our getting started guide links to ftdi website http://www.arduino.cc/en/Guide/MacOSX#toc3

**Comment by LunarLanding** [comment]
My bad, I linked to somepage of the thread instead of the OP:
http://forum.arduino.cc/index.php?topic=198539.0
But since the guide links to the ftdi drivers, I guess it's a moot point
... but OSX does have a driver that partially works with Arduino, which is a source of confusion, guide or no guide.
