### ISSUE TITLE
Four libraries (Freetronics-developed) for library manager

### ISSUE THREAD

**Issue by projectgus** [arduino/Arduino#3005]
Hi folks,

I'd like to get some of our Freetronics libraries added to the Arduino Library Manager, please. Our libraries are designed for our products, but our products are all OSHW and a lot of the components are common. Where applicable I've mentioned the underlying component in the library description.

The libraries are all in the joint v1.0.x/v1.5 compatible format for now. We're hoping to migrate towards v1.5-only format as soon as most of our users have upgraded.

Repo github web page URLs:
```
https://github.com/freetronics/FTOLED
https://github.com/freetronics/FTRGBLED
https://github.com/freetronics/DMD2
https://github.com/freetronics/BaroSensor
```

Direct git repo (ssh-based?) URLs:
```
git@github.com:freetronics/FTOLED.git
git@github.com:freetronics/FTRGBLED.git
git@github.com:freetronics/DMD2.git
git@github.com:freetronics/BaroSensor.git
```

Thanks very much for your hard work on Arduino.

Angus

**Comment by ffissore** [comment]
Added. thanks
