### ISSUE TITLE
Provide sources for drivers

### ISSUE THREAD

**Issue by bromagosa** [arduino/Arduino#3006]
I couldn't find the source code for these drivers:

https://github.com/arduino/Arduino/tree/06d95d42257c606a1c8c2e8f76074c60db9974c6/build/windows/dist/drivers

Are those proprietary?

Thanks! :)

**Comment by facchinm** [comment]
Hi @bromagosa ,

that driver leverage on the standard Windows USB-CDC driver. 
The `.inf` file _is_ the driver itself as it tells the OS that certain VID/PID combinations can use the CDC standard driver. 

If you have a more specific question (like the signing procedure) feel free to reopen the issue :wink: 

Cheers

**Comment by bromagosa** [comment]
Oh, I see! That goes to show I know nothing about Windows...

Are those drivers under the GPL too? Can we redistribute them?

**Comment by PaulStoffregen** [comment]
The actual driver code is in USBSER.SYS, which comes with Windows.  If you want the source code for that, you'll have to contact Microsoft!

**Comment by bromagosa** [comment]
I understand that, yes. But can we redistribute the files under https://github.com/arduino/Arduino/tree/06d95d42257c606a1c8c2e8f76074c60db9974c6/build/windows/dist/drivers ? What is the license for those?

**Comment by cmaglie** [comment]
@bromagosa 
the license on the `arduino.inf` drivers has been set.

**Comment by bromagosa** [comment]
Cool, thanks! :)
