### ISSUE TITLE
Change error copy in Library/Board Managers

### ISSUE THREAD

**Issue by 00alis** [arduino/Arduino#3007]
Copy should be "Unable to reach Arduino.cc due to possible network issues"

instead of
"No internet connection available...." as in this screenshot
![screen shot 2015-04-10 at 7 19 31 pm](https://cloud.githubusercontent.com/assets/6151328/7227728/3bb67bda-e753-11e4-958e-1123c6ae4901.png)

@ffissore

**Comment by ffissore** [comment]
Should the whole phrase read "Unable to reach Arduino.cc due to possible network issues. The list of available boards is not complete. You will be able to manage only the boards you've already installed." or just "Unable to reach Arduino.cc due to possible network issues" ?

**Comment by 00alis** [comment]
@ffissore please refer to this conversation on Basecamp, this is what has been decided. Thanks!
https://basecamp.com/2546761/projects/5094615/messages/40584564
