### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by gvuyk** [arduino/Arduino#3009]
Windows 7 64
Arduino IDE 1.6.3
Process: "listComPorts.exe" 
It's even more noticeable when having multiple instances running as each one spawns its own listComPorts.exe

**Comment by feveran** [comment]
I got same issue with WMI Provider Host when running arduino ide 1.6.0 and newer versions in high performance or balanced mode (on aptop) but not in power saver mode.

**Comment by asantaga** [comment]
ditto.. makes compiling incredibly slow

**Comment by ffissore** [comment]
Last week, on our windows box, the IDE began to take lots of time to start: it stay stuck to "loading configuration..." for much longer than usual. Guess what? It's the antivirus, Avira. Once turned it off, everything started being waayyy faster

**Comment by phme** [comment]
I'm still having the issue, antivirus disabled. WMI Provider Host (WmiPrvSE.exe) at stable 25% CPU as soon as the IDE is launched. Something about the way USB port is being polled?
Windows 8.1
Arduino IDE 1.6.6 Hourly 2015/10/01 10:54

**Comment by tangshuran** [comment]
i got the same problem

**Comment by tangshuran** [comment]
any solution?

**Comment by phme** [comment]
Well, this issue is still marked as closed, so I suspect the problem is not that interesting.
On my machine, it's still manageable, as it maxes out one core out of four. So I just have to put up with annoying fan noise, but otherwise it works.
I guess the long-term solution would be to use Visual Studio or Atmel Studio, if you're on PC.

**Comment by tangshuran** [comment]
thanks a lot. It just makes me confused that what kind of service cost 20% ability of my i7 core. And the machine really get hot.
My crude solution is shutting down the arduino IDE immediately after  copying examples and compiling.

**Comment by ckpinguin** [comment]
Well after all, why has Arduino to use WMI Host fully when idle? It heatens up my notebook making it sound like a starting airplane

**Comment by ffissore** [comment]
indeed it doesn't, not intentionally. it's also not a widespread issue: looks like only some windows are affected

**Comment by HopWorks** [comment]
I just chased this to Arduino 1.6.5 also. Having the same issue with WMI Provider Host on a Windows 10 machine.

**Comment by facchinm** [comment]
Hi @HopWorks ,
can you test if WMI Provider Host cpu occupation stays high with the hourly build? 
It should have been solved by #4211

**Comment by HopWorks** [comment]
I will test with the new build, but FYI... the link on the page you sent me is broken.
[http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-4211-BUILD-475-windows.zip](url)

**Comment by facchinm** [comment]
Yep, the builds get canceled when they are merged so it is expected.
If you could test it using the nightly build it would be great!
