### ISSUE TITLE
Connecting YUN to a Wireless with less than 8char password

### ISSUE THREAD

**Issue by NicolaClab** [arduino/Arduino#3016]
Using the config panel of my Arduino YUN, i cannot connect my company wifi because there is a numeric password length 6char and Arduino tell..password must have 8 or more char.

**Comment by ffissore** [comment]
Any chance you can use a 8+ char password? 6 chars is really weak

**Comment by NicolaClab** [comment]
Yes, i know, but it's the Company Password, i cannot modify Company policy. How can i workaround?

**Comment by ffissore** [comment]
ATM you can switch to the advanced configuration panel and configure wifi from there

**Comment by NicolaClab** [comment]
What section to config you to attach it to my wifi?

![arduinoyunset](https://cloud.githubusercontent.com/assets/11921209/7269662/2b97da76-e8d6-11e4-9e63-81541d46ebe6.png)

**Comment by ffissore** [comment]
Please check out this video: https://www.youtube.com/watch?v=yAwnWU5VWD8
Closing as this is turning into a support ticket rather than a bug report.
For further assistance in using the yun, please refer to the dedicated Arduino Forum http://forum.arduino.cc/index.php?board=93.0

**Comment by matthijskooijman** [comment]
FWIW, I think that < 8 character passwords aren't really allowed by the wifi/WPA specification. This minimum isn't very strictly defined it seems, but a lot of software and devices adhere to it. See also http://serverfault.com/a/165102
