### ISSUE TITLE
Firewall issue

### ISSUE THREAD

**Issue by PacksGamingHD** [arduino/Arduino#3021]
When I try to run a nightly build this error message keeps popping up. Kind of annoying.
![screen shot 2015-04-22 at 1 39 06 pm](https://cloud.githubusercontent.com/assets/7285557/7284840/25c8fea8-e8f5-11e4-9787-f4faf026c34a.png)

Any ideas?

**Comment by ffissore** [comment]
It's standard OSX behaviour for unsigned apps. Since you're building, you should enable sort of "developer mode", disabling these annoying popups at least for the Arduino binary
