### ISSUE TITLE
Feature Request: PWM read function

### ISSUE THREAD

**Issue by thijsvb** [arduino/Arduino#3025]
It would be very usefull to have a function that can read a pwm signal from for example another arduino. Using the pulseIn function just isn't very practical, especially when trying to continuesly read a pin.

**Comment by agdl** [comment]
What do you want to say exactly? Read the PWM and convert it back to a number from 0 to 255?

**Comment by thijsvb** [comment]
Yes, exactly!

**Comment by mikevanis** [comment]
I think this feature request wouldn't exist if the `pulseIn()` function was non-blocking. Just a thought!

**Comment by facchinm** [comment]
You could check if #2409 solves your problems, as it contains an implementation of pulseIn based on micros() beside the normal implementation rewritten in ASM.
The pulseInLong() works correctly in interrupt context as it is interrupt based :smile:

**Comment by agdl** [comment]
you can do it in a very simple way connecting a PWM output to an analog input by means of an RC filter (it exctract the average value of the PWM waveform)

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen if needed
