### ISSUE TITLE
Display entire error message from avrdude upon failure [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#303]
This is [Issue 303](http://code.google.com/p/arduino/issues/detail?id=303) moved from a Google Code project.
Added by 2010-07-22T22:15:17.000Z by [drmn...@gmail.com](http://code.google.com/u/107379186338214693261/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Display the complete error message from avrdude upon failure (see also Issue#301). For example, in the case of the following error:

avrdude: Device signature = 0x1e9406
avrdude: Expected signature for ATMEGA644P is 1E 96 0A
         Double check chip, or use -F to override this check.

avrdude done.  Thank you.

only the "Expected" value is shown, but not the signature actually read.

**Why?**

In the above case, knowing the signature actually read could help in diagnosing the cause of failure, e.g. shorted/grounded MISO pin (signature always read
000000 or FFFFFF), wrong chip ("close", consistent but wrong
signature), or floating MISO pin (misconnected or maybe target chip
not receiving a clock -> signature random/different every time).

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

None that I know of

**Comment by ffissore** [comment]
Fixed a long time ago
