### ISSUE TITLE
Arduino.exe start, write initializing packages and closed.

### ISSUE THREAD

**Issue by VladimirKrd** [arduino/Arduino#3031]
Do not work, Win8 x64. Java SE DK 8 Update 45

**Comment by mschlenker** [comment]
Could you please check if #3015 applies to your problem?

**Comment by VladimirKrd** [comment]
No, deleting a file does not work

**Comment by VladimirKrd** [comment]
The program does not show any error messages, it just closes.

**Comment by mschlenker** [comment]
Would you start it from the command line to check whether Java spills out some errors?

**Comment by VladimirKrd** [comment]
Of course I can, you need to write in command line?

**Comment by ffissore** [comment]
Use command prompt and `cd` into the Arduino IDE folder, then run `arduino_debug.exe`. It will print *stuff*: please paste it here

**Comment by VladimirKrd** [comment]
![n1](https://cloud.githubusercontent.com/assets/12102583/7328430/4b9a5fe2-eade-11e4-9178-f94733fd5c7e.jpg)

**Comment by mschlenker** [comment]
The missing `bootloaders/platform.txt` looks a bit like a broken install. Would you mind uninstalling and re-installing again?

**Comment by VladimirKrd** [comment]
Ok. I downloaded the .exe, set does not work. Download *.zip, copied all, does not work. Now reinstall  *.exe, and all run! Fiction. Thank you so much for your help, God forbid you well.

**Comment by mschlenker** [comment]
You might have a corrupted file system or bad hard drive. So you'd better run CHKDSK on your hard drives now. Have fun. And have a nice weekend!

**Comment by usef-96** [comment]
![1](https://cloud.githubusercontent.com/assets/12232614/7452068/0db546e4-f248-11e4-9aa4-e17a18112c0f.PNG)
![2](https://cloud.githubusercontent.com/assets/12232614/7452069/0dbb6cfe-f248-11e4-8851-60823257a595.PNG)
Hi,
I have the same problem but look in my case please can you help me .

**Comment by ffissore** [comment]
Please delete file `library_index.json` from your `%APPDATA%\Arduino15\` folder. Then reopen the IDE

**Comment by usef-96** [comment]
Thank you very very much mister I appreciate your help, have a good day.

**Comment by Steltek** [comment]
Had the same problem because I installed over an old version. Fix was to delete the 'hardware' directory and re-extract it from the original ZIP archive.
