### ISSUE TITLE
Download flop

### ISSUE THREAD

**Issue by enlitened1** [arduino/Arduino#3038]
I'm new to Arduino, not new to computers (not only those big clunky things I'm writing on).
I bought a couple of different PCBs, one being a Romeo V3 and an Arduino Uno. 
I'm trying to down load the drivers from this website (http://www.arduino.cc/en/Main/Software). 
I'm on WIn 7 32 bit with six core processor  and 4GB.
When I down load the 1.6.3 Zip for windows I get an error message about end of files missing(?)
When i download the 1.6.3 installer, it says it is not a Win 32 bit file.
How do I get these drivers so I can use the boards?
I plugged in my Romeo board w with USB. I thought I wold get some response to the comuter that it was there. Nothing. I guess it needs drivers to understand "duh".

**Comment by ffissore** [comment]
It sounds like a network problem. Please retry. Closing as invalid: issues are for bug and feature requests of the Arduino IDE. Other enquiries should go to either support at arduino cc or the arduino forum
