### ISSUE TITLE
Add SparkFun Graphic LCD Library to master library list

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3044]
Request to add the SparkFun Graphic LCD Library to the master list. 

[Repository](https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library). 

Most up-to-date release is [V_1.0.1]
(https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library/releases/tag/V_1.0.1).

Library is tagged and has library.properties file per 1.5 library specs. Thanks so much!

**Comment by ffissore** [comment]
Added. Thanks
