### ISSUE TITLE
Add SparkFun ColorLCD Shield Library to master library list

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3045]
Request to add the SparkFun Color LCD Shield Library to the master library list.

Repository lives [here](https://github.com/sparkfun/SparkFun_Color_LCD_Shield_Arduino_Library). 

Most recent release is [V_1.0.1](https://github.com/sparkfun/SparkFun_Color_LCD_Shield_Arduino_Library/releases/tag/V_1.0.1).

Library includes the library.properties file per the 1.5 library manager spec. Thanks!

**Comment by ffissore** [comment]
Added. Thanks
