### ISSUE TITLE
SD CardInfo Example Fails on 1.6.3

### ISSUE THREAD

**Issue by robbob009** [arduino/Arduino#3049]
The SD CardInfo Example cannot detect the SD Card when uploaded from 1.6.3.  The CardInfo example from 1.0.6 uploads and works as expected.  Using the same computer (Win 7), Arduino Uno R3, Ethernet Shield Model R3, 8 GB Micro SD.

**Comment by facchinm** [comment]
Hi @robbob009 ,
try updating the SD library using the Library Manager.
Latest version is 1.0.4 and contains the fix #2974

**Comment by agdl** [comment]
Waiting for feedback for too long. Reopen if needed.
