### ISSUE TITLE
Add SparkFun micro OLED library to master library list

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3051]
Request to add SparkFun micro OLED library to master library list.

Repo is [here](https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library). 
Most recent release is [V_1.1.1](https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/tree/V_1.1.1).

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
