### ISSUE TITLE
Add SparkFun Microview library to master library list

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3052]
Request to add SparkFun Microview Library to master library list.

Repo is [here](https://github.com/sparkfun/SparkFun_MicroView_Arduino_Library).
Most recent release is [V_1.0.1](https://github.com/sparkfun/SparkFun_MicroView_Arduino_Library/tree/V_1.0.1). 

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
