### ISSUE TITLE
Add SparkFun VKey library to master library list

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3065]
Request to add SparkFun VKey Library to master library list in lib manager. 

Repo is [here](https://github.com/sparkfun/SparkFun_VKey_Voltage_Keypad_Arduino_Library).

Most recent tag is [V_1.0.1](https://github.com/sparkfun/SparkFun_VKey_Voltage_Keypad_Arduino_Library/tree/V_1.0.1)

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
