### ISSUE TITLE
Add SparkFun MPL3115A2 library

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3066]
Request to add SparkFun MPL3115A2 library to master list in library manager.

Repo is [here](https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library).
Most recent tag is [V_1.2.0](https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library/tree/V_1.2.0).

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
