### ISSUE TITLE
Holding down Shift key while uploading will cause the upload to fail.

### ISSUE THREAD

**Issue by juj** [arduino/Arduino#3068]
Developing here on Windows 8.1 on an Arduino Uno board. I am trying to get the disassembled output of a built sketch, and stumbled to http://forum.arduino.cc/index.php?topic=50169.0 where it is stated that holding down the Shift key while uploading or compiling should show a verbose log so that one is able to extract the commands/code files for dumping out.

However, if I hold down the Shift key while pressing the Upload button (on an otherwise successfully building Sketch, I get the following build result with an error:

	Sketch uses 9,284 bytes (28%) of program storage space. Maximum is 32,256 bytes.
	Global variables use 182 bytes (8%) of dynamic memory, leaving 1,866 bytes for local variables. Maximum is 2,048 bytes.
	avrdude: usbdev_open(): did not find any USB device "usb"

If I hold down the Shift key while pressing Compile, the Compile is successful and no errors are printed,  but the print output does not differ in any way from not holding down the Shift key. Should it have?

Finally, is there a way to get the disassembly of an Arduino program?

**Comment by ffissore** [comment]
Pressing shift + upload changes label from "upload" to "upload using programmer". Verbose compilation can be turned on from file > preferences

**Comment by juj** [comment]
Thanks!
