### ISSUE TITLE
Add library to Library Manager

### ISSUE THREAD

**Issue by thijse** [arduino/Arduino#3078]
Hi,

Could you please add the TimeZone library to the manager:

https://github.com/ivankravets/Timezone

If there are any issues, please let me know or the library maintainer Ivan Kravets

**Comment by ffissore** [comment]
The most recent tag https://github.com/ivankravets/Timezone/tree/v1.0 misses a library.properties file

**Comment by thijse** [comment]
Thanks! Ivan Kravets accepted my pull request for library.properties, but
did not create a release. I will ask him to do so

**Comment by ffissore** [comment]
Closing. Please reopen once the target library is ready
