### ISSUE TITLE
UI Improvement: Reopen Serial Window after uploading

### ISSUE THREAD

**Issue by carpii** [arduino/Arduino#3079]
I'd love to see an option to keep the serial window open when uploading via Arduino (or maybe just an option to keep it open permanently, even if its not connected during that time).

I'm doing a lot of debugging lately and its driving me a bit crazy having to keep reopening it on every update. 

Seems like it would be a fairly simple addition, but very useful.

**Comment by ffissore** [comment]
Fixed by #2742

**Comment by carpii** [comment]
Excellent, thankyou :+1:
