### ISSUE TITLE
Unclear how to add more than one additional boards manager URL.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3092]
Having a single text box for multiple URLs seems awkward. In particular, it's not clear how to add multiple URLs, i.e. what to use to separate them.

**Comment by probonopd** [comment]
+1

**Comment by BrentWilkins** [comment]
A comma is the way to go AFAIK, but a note next to the field wouldn't hurt.

**Comment by ffissore** [comment]
Fixed in hourly build (available in the next few hours). Added a tooltip to both label and text field. Hourly also features a button that will open (yet-another) tiny modal where urls can be written one per line
