### ISSUE TITLE
[WEB/DOC] Arduino Gemma doesn't appear in "Products" page

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3095]
If it's an official board like the others...it should appear there and it should have a product page, right?
Thanks

**Comment by agdl** [comment]
@q2dg you are right it will be online very soon

**Comment by agdl** [comment]
@q2dg it is online now

**Comment by q2dg** [comment]
Well, you know... http://www.arduino.cc/en/Main/Products looks out of position now :-|

**Comment by agdl** [comment]
@q2dg what do you mean?

**Comment by q2dg** [comment]
This
![screenshot](https://cloud.githubusercontent.com/assets/7274874/7566039/fad6d4a4-f7f4-11e4-8677-80778dc0c2ad.png)

**Comment by akash73** [comment]
Fixed.
thank you.
