### ISSUE TITLE
Arduino 1.6.4 Warning about unconfirmed developer

### ISSUE THREAD

**Issue by Pixelworlds** [arduino/Arduino#3097]
MacBook Pro running OSX 10.10.4

![image](https://cloud.githubusercontent.com/assets/701846/7517407/d2a7acf6-f4a2-11e4-8af8-f2873c8cf9c9.png)

I've already made sure that "Allow Apps Downloaded from Anywhere" is selected in the security preferences - that doesn't seem to fix the issue. 

Any suggestions would be greatly appreciated!

**Comment by ffissore** [comment]
What version have you downloaded?

**Comment by Pixelworlds** [comment]
1.6.4 - but it seems that it was a permissions issue. I ran

sudo chown root:admin Arduino.app

which resolved the issue
