### ISSUE TITLE
Improve new editor keyboard shortcuts, especially on mac

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#3098]
Starting from @damellis suggestions: https://github.com/arduino/Arduino/pull/3019#issuecomment-95699278

**Comment by damellis** [comment]
Three in particular that would be nice to fix:
Alt-Backspace should delete the word preceding the cursor. (This works in 1.6.4).
Command-E should use the current selection for find. (This works in 1.6.4.) Also, Command-F should not use the current selection for find; it should use the previous find text. (This is wrong in 1.6.4, too.)
Command-Up should go to the start of the file; Command-Down to the bottom. (This doesn't work in 1.6.4 either.)

**Comment by ffissore** [comment]
Alt-Backspace restored. Available in next hourly build

**Comment by damellis** [comment]
Thanks!

**Comment by damellis** [comment]
Whoops, maybe I spoke too soon... it looks like this is deleting the word in front of the cursor, instead of behind it.

**Comment by ffissore** [comment]
Whoops sorry. I coded that on purpose because I read your comment... Ehm...
Backwards
Il giorno 13/mag/2015 18.47, "David A. Mellis" <notifications@github.com>
ha scritto:

**Comment by damellis** [comment]
I probably wasn't clear. Sorry about that!

**Comment by ffissore** [comment]
Fixes pushed. From [your comment](https://github.com/arduino/Arduino/pull/3019#issuecomment-95699278) I miss only CMD+J: what does it do?

**Comment by damellis** [comment]
Thanks again!

One minor nitpick: Cmd+E shouldn't open the Find dialog; it just sets the Find text (e.g. for use by subsequent Cmd+G commands).

In the current build, Cmd+J concatenates the next line onto the end of the current line. I find the equivalent behavior (J-key) useful in Vi, but here it seems out of place. Also probably a minor nitpick.

**Comment by ffissore** [comment]
Uhm I guess we may leave CMD+E as it is (although it will look a little awkward, it will still implement the feature) and remove CMD+J on macosx (thus avoiding errors).
Closing, as the new editor should now behave as expected
