### ISSUE TITLE
Alt-Up and Alt-Down shouldn't move the current line of text.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3101]
Personally, I find this behavior disconcerting and I worry that might create problems with beginners moving code accidentally. I know this behavior exists in some other programming editors, but AFAIK it's not in standard text editors on any platform. (At least, it's not on the Mac.) Given that we're trying to appeal to more than just existing programmers, it seems better to follow the behavior of more standard editors. These shortcuts seem especially problematic on Mac, where they already have another standard meaning: moving the cursor to the next or previous paragraph. But I personally think it would be best to get rid of them on all platforms.

**Comment by ffissore** [comment]
Fixed and available in next hourly build
