### ISSUE TITLE
Don't highlight current tokens w/ gray background.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3102]
It's distracting and confusing that the current tokens (i.e. those equal to the one containing the text cursor) get highlighted in gray a second or so after you move the cursor into it. I think this is likely to confuse beginners who already have a lot to understand without text "randomly" changing color on them. Also, I find it visually distracting. I know it's intended to provide value by highlight other instances of the same token, but I don't think it's worth it.

**Comment by ffissore** [comment]
Fixed and available in next hourly build
