### ISSUE TITLE
Command-K doesn't work as shortcut for "Open Sketch Folder".

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3103]
In the latest version on GitHub (on Mac), Command-K doesn't open the folder containing the open sketch. It does highlight the Sketch menu as you'd expect on Mac, but the folder doesn't actually open. If you select "Show Sketch Folder" from the Sketch menu, the folder opens correctly. This seems to be true of both built-in examples and sketches in the sketchbook.

**Comment by ffissore** [comment]
Fixed and available in hourly build

**Comment by m-ri** [comment]
Caro,

Wow, ti  prego di dare un'occhiata a queste  belle cose che ho appena trovato, sono incredibili! Dai un'occhiata <http://giuseppa.mobiado.tw/estr>

Sinceramente tuo,marco ribero

**Comment by m-ri** [comment]
Caro,

Ho delle  buone notizie per te, qualcosa che potrebbe piacerti molto, ti prego di  dare  un'occhiata <http://valter.mobiado.tw/fukc>


Cari saluti, marco ribero
