### ISSUE TITLE
Board and port names are cut off in the Tools menu.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3104]
The name of the selected items that now appear in the Tools menu are often cut off. For example, I see 'Board: "Arduino Duemilan..."'. I assume this is an attempt to keep the menu from getting too big, but it seems like we should at least make the maximum length long enough for the names we use. I think the longest one is "Arduino Duemilanove or Diecimila". 

The problem is perhaps worse for serial ports, at least on Mac, because the serial number of some ports is cut off, making it hard to distinguish between two different boards. For example, I see only "/dev/cu.usbmodem..." and not the 14511 suffix that tells me which Arduino it is.

**Comment by mschlenker** [comment]
Kinda sucks - only a little bit :-) - when hovering and the submenu is shown and you get the information you need. IMHO the current state is quite an improvement (tinkering with Pro Minis of various voltage) over the previous state where you had to open the submenus always. So, good work @ffissore but still a little work left.
