### ISSUE TITLE
Serial ports title in Port menu looks like a menu entry

### ISSUE THREAD

**Issue by carlosefr** [arduino/Arduino#3113]
The "Serial ports" entry in the **Tools/Port** menu looks like an active menu entry, when in fact it does nothing. I think it should be gray like, for example, the "Arduino AVR Boards" entry in the **Tools/Board** menu.

**Comment by matthijskooijman** [comment]
Confirmed, the code probably forgot to mark it as disabled (or whatever the right term was again). Should be simple to fix, though.

**Comment by ffissore** [comment]
Indeed. Thank you for the heads up. Fix will be available with the next hourly build
