### ISSUE TITLE
Cannot compile Example sketches. 1.6.4

### ISSUE THREAD

**Issue by jl-p** [arduino/Arduino#3115]
Hi,

I upgraded to 1.6.4. and i was able to compile fastled library examples.
sometimes it hungs but most of the time it worked. 
but after a day i cannot upload any of the examples anymore.
I downloaded the zip version of 1.6.3. and the same codes with the same installed librarys works perfectly.

compile the code with 1.6.3. and save it again. open it in 1.6.4 and it get stuck again

output of the compiler

Bibliotheek FastLED in map: C:\Users\My Account\Documents\Arduino\libraries\FastLED (legacy) wordt gebruikt

C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++ -c -g -Os -Wall -Wextra -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10604 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino -IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard -IC:\Users\My Account\Documents\Arduino\libraries\FastLED C:\Users\MYACCO~1\AppData\Local\Temp\build7734498561037075679.tmp\sketch_may10a.cpp -o C:\Users\MYACCO~1\AppData\Local\Temp\build7734498561037075679.tmp\sketch_may10a.cpp.o

**Comment by jl-p** [comment]
I noticed my issue is also only when choosing something else then default as compiler warning settings

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build. Thanks for the heads up!

**Comment by z3t0** [comment]
Just to confirm, this fix is in 1.6.5?

**Comment by ffissore** [comment]
Yes

**Comment by z3t0** [comment]
Thanks
