### ISSUE TITLE
Command E

### ISSUE THREAD

**Issue by freddybloggs** [arduino/Arduino#3116]
Command E to enter the cuurently selected text in to the "find" clipboard has been removed from
OSX IDE making it unusable, also you cannot select the 1st character in a line off text, it has always been hard to do but now with 1.6.5 it is impossible.

**Comment by ffissore** [comment]
Closing as duplicate of #3098. Please remind that 1.6.5 (at the time of writing) is an hourly build, not a release. If you wish to see that feature working, please use 1.6.4 (latest release). Otherwise, thanks for the heads up!
