### ISSUE TITLE
IDE 2:1.0.5 on Linux Always Opens a New Sketch

### ISSUE THREAD

**Issue by Wintermute3** [arduino/Arduino#3117]
Whenever I launch the IDE I am greeted by a new, blank sketch (for instance sketch_may10a).  I then have to open the sketch I really want to work on, which opens a new window, then close the new unwanted one.  This gets old fast.  How can I get the IDE to re-open the sketch I most recently worked on, and/or not open a new one each time it starts?  As an added bonus, it would be nice for it to remember my window size and position as well.

I did try searching the issue list, but found no matching problems, which is puzzling.  Is this working as designed, and everyone accepts it, or is my system working abnormally?

This is on Kubuntu 15.04 if that is relevant.  I installed the IDE from the built-in 'Muon' package manager for Kubuntu.  Perhaps this version is so old that the problem was fixed so long ago that no one deals with it any more?

*** I just downloaded and installed 1.6.4 on Windows 7 and observe the same behavior.

**Comment by wayoda** [comment]
Its a feature, not a bug.

A little trick:
- Opening a sketch from the file menu or `Crtl+O`opens a new Window
- Opening a sketch with the load button replaces the sketch in the current window

Inconsistent, but at least a workaround
