### ISSUE TITLE
RowColumnScanning tutorial mistake

### ISSUE THREAD

**Issue by Semphora** [arduino/Arduino#3118]
if I'm correct in thinking, that the cathode is the negative end of an led then the text in http://www.arduino.cc/en/Tutorial/RowColumnScanning
should read:

These can be very useful displays. To control a matrix, you connect both its rows and columns to your microcontroller. The columns are connected to the LEDs cathodes (see Figure 1), so a column needs to be **low** for any of the LEDs in that column to turn on. The rows are connected to the LEDs anodes, so the row needs to be **high** for an individual LED to turn on. If the row and the column are both high or both low, no voltage flows through the LED and it doesn’t turn on.

To control an individual LED, you set its column **low** and its row **high**. To control multiple LEDs in a row, you set the **row** high, then set the **columns low or high as appropriate; a low **column will turn the corresponding LED on, and a high **column** will turn it off. 

**Tip: Pins set to OUTPUT by use of the PinMode command are set to LOW if not otherwise stated**

**Comment by agdl** [comment]
@Semphora I modified it. If it is ok for you now please close the issue.
