### ISSUE TITLE
Add Additional Boards Manager URLs in Boards Manager

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3119]
It seems more logical to enter 3rd party Boards Manager URLs in Boards Manager instead of File > Preferences.

**Comment by ffissore** [comment]
Boards Manager is intended to be explained to (advanced) students. We though adding additional urls text field in that window would have scared. So we isolated the feature in preferences

**Comment by per1234** [comment]
Thanks for the fast response! I just thought I'd mention it in case it hadn't ocurred to you. I understand the reasoning for doing it the way it is and am glad to hear it was considered.
