### ISSUE TITLE
Arduino : VMI Provider Host

### ISSUE THREAD

**Issue by Hellboy94** [arduino/Arduino#3128]
Hi,
When i launch Arduino IDE 1.6.3, i have a "VMI Provider Host" program that is also execute (on WIndows 8.1).It uses 70% of my processor (I7 - 3630Q 2.4GHz), that is not normal. 
Is there a solution ?
Thanks
![2015-05-13 13 55 17](https://cloud.githubusercontent.com/assets/12428389/7609920/8365d462-f978-11e4-9b27-d3bef3dc0fc5.jpg)

**Comment by ffissore** [comment]
It looks like a [windows issue](http://answers.microsoft.com/en-us/windows/forum/windows_8-performance/wmi-provider-host-constantly-disrupting/8e1ead34-d25f-4ee5-8eb1-7a6afe3c0696). Also [this](https://www.google.it/search?client=ubuntu&channel=fs&q=VMI+Provider+Host&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=S0BTVcHnJ6mO8Qfk0YGAAg#safe=off&channel=fs&q=%22WMI+Provider+Host%22)
