### ISSUE TITLE
1.6.4 IDE libraries

### ISSUE THREAD

**Issue by jfhenderson** [arduino/Arduino#3131]
Robot Motor is persistent under Contibuted Libraries. Both Mac and Windows.

**Comment by ffissore** [comment]
Confirmed. It was due to an incorrect push on its [repo](https://github.com/arduino-libraries/Robot_Motor). Fixed. Fix will be available in next hourly build and the next time you'll open library manager

**Comment by jfhenderson** [comment]
Thanks for this, Frederico. Quick work! Regards, John.
