### ISSUE TITLE
New download link on donate page doesn't work correctly.

### ISSUE THREAD

**Issue by AbstractBeliefs** [arduino/Arduino#3138]
After visiting the Download page, and selecting "Linux 64 bits" (sic), I'm redirected to the Donate page.

Clicking the "No thanks, just download" button will then try to give me Windows releases (inconsistent even between what type of release).

Following is a screenshot of the state after pressing the download button 3 times after selecting the Linux 64 bits download link on the Download main page.

This issue was reported by another user in #arduino on freenode, and is reproducible on several individuals PCs.
![image](https://cloud.githubusercontent.com/assets/1375203/7635174/55e3ff70-fa57-11e4-844b-336210ce7464.png)

**Comment by mastrolinux** [comment]
Hello @AbstractBeliefs 

Sorry about that. Turned out there was a misconfiguration. Please try again now. It should be solved. Any feedback is appreciated.
