### ISSUE TITLE
Per-sketch libraries (e.g. code/ folder) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#314]
This is [Issue 314](http://code.google.com/p/arduino/issues/detail?id=314) moved from a Google Code project.
Added by 2010-08-02T19:40:01.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE, OpSys-All

### Original description

**What change would like to see?**

The ability to include libraries on a per-sketch basis.  This should probably be in the code/ folder to mirror Processing, or a libraries/ folder (to mirror other library locations).  In the long run, this should support pre-compiled libraries too (issue #199), but source libraries would be a good start.

**Why?**

So people can include all the dependencies for a sketch in one place.  This would also be a nice place to put assembly files for a sketch (since you can't edit them in the IDE) - issue #274.

**Comment by ffissore** [comment]
The very same result can be obtained by having multiple sketchbooks, each with its own set of libraries. That also allows to have a hardware definition specific to a sketch

**Comment by lmihalkovic** [comment]
Rational for supporting it is that it makes it easy to test some changes to a library on a single sketch while still using the official version everywhere else, or start a new library by extracting code directly inside a large sketch project.

**Comment by SuperTango** [comment]
Sketchbook is global to the IDE.  What I (and I'm assuming others) are looking for is the ability to have per-sketch libraries that aren't tied to a global for the IDE.  I work on many arduino projects, most with differing library sets and it's really a pain to have to change the sketchbook when moving from project to project (or other hacks like have multiple instances of the IDE running, or different versions of the IDE, etc).
