### ISSUE TITLE
Preferences window opens too small to use

### ISSUE THREAD

**Issue by richrad** [arduino/Arduino#3140]
Like so:
![screen_shot_2015-05-14_at_10_58_15_am](https://cloud.githubusercontent.com/assets/1631126/7635726/36bf3ba2-fa28-11e4-862c-fc0225fe5cd3.png)
I can fix it by trashing my `~/Library/Arduino/preferences.txt` file but I didn't figure out which line in particular is causing the problem. Here's a gist with the contents: [https://gist.github.com/richrad/47f2684cd1fd4f1f1aca](https://gist.github.com/richrad/47f2684cd1fd4f1f1aca)

I do have three or four versions of the IDE installed so I wouldn't be surprised if another version caused the problem.

**Comment by ffissore** [comment]
We started coding a new preferences window, which should be corretly
displayed. More info later tomorrow

**Comment by ffissore** [comment]
Fix will be available in next hourly build
