### ISSUE TITLE
No copyright header. License confusion.

### ISSUE THREAD

**Issue by mtomczew** [arduino/Arduino#3145]
What is the license for file https://github.com/arduino/Arduino/blob/master/hardware/arduino/sam/cores/arduino/avr/pgmspace.h
?

It does not have any copyright header.
Is the licence LGPL like dtostrf.c file in the same directory?

It would be great if you could add appropriate header to decrease confusion how this file can be used in other software.

Additionally, writing "in general" in license.txt is not very clear. If part of code is licensed under GPL and the other under LGPL, specifying precise folders licensed differently is a good idea.

**Comment by cmaglie** [comment]
This is something I added months ago, just after the Arduino Due was released.
I know that @PaulStoffregen has something very similar for the Teensy: I've looked before writing this one.

I'm going to add an LGPL license as for the rest of the core.
@PaulStoffregen is it ok for you?

**Comment by PaulStoffregen** [comment]
Oh, looks like my copy of pgmspace.h ( https://github.com/PaulStoffregen/cores/blob/master/teensy3/avr/pgmspace.h ) lacks a license header too.

I use MIT license.  If the code came from me, please put the MIT license header on it.

**Comment by cmaglie** [comment]
I really don't remember, it may be a mix of forum posts and your implementation. BTW I've added the MIT license, so no problem.

**Comment by mtomczew** [comment]
Thanks for help. License is appropriate for my usage.
