### ISSUE TITLE
Cmd+E shouldn't open Find dialog (Mac OS X)

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3147]
On Mac, the Cmd+E keyboard shortcut should set the Find text (to the currently selected text) without opening the Find dialog. That way, for example, you can then use the Cmd+G shortcut to find additional instances of the selected text. This is a detail, it's true, but it's also standard behavior across Mac applications.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build
