### ISSUE TITLE
Request to add SparkFun ATSHA204 library to library manager.

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3149]
Request to add SparkFun ATSHA204 library to library manager. 

Repo: https://github.com/sparkfun/SparkFun_ATSHA204_Arduino_Library
Most recent tag: https://github.com/sparkfun/SparkFun_ATSHA204_Arduino_Library/tree/V_1.0.0

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
