### ISSUE TITLE
Request to add SparkFun Quadstepper Motor Driver lib to library package manager.

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3150]
Request to add SparkFun Quadstepper Motor Driver lib to library package manager.

Repo: https://github.com/sparkfun/SparkFun_Quadstepper_Motor_Driver_Arduino_Library
Most recent tag: https://github.com/sparkfun/SparkFun_Quadstepper_Motor_Driver_Arduino_Library/tree/V_1.0.1

**Comment by ffissore** [comment]
Added. Thanks!
