### ISSUE TITLE
Request to add SparkFun MG2639 Cellular library to library package manager. 

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3151]
Request to add SparkFun MG2639 Cellular library to library package manager. 

Repo: https://github.com/sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library
Most recent tag: https://github.com/sparkfun/SparkFun_MG2639_Cellular_Shield_Arduino_Library/tree/V_1.0.0

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
