### ISSUE TITLE
Request to add SparkFun Graphic LCD Backpack library to library package manager. 

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3152]
Repo is here: https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_Graphic_LCD_Serial_Backpack_Arduino_Library/tree/V_1.0.1

Thank you!

**Comment by ffissore** [comment]
Duplicate of #3044. Lib already listed
