### ISSUE TITLE
Request to add SparkFun Bar Graph Library to library package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3153]
Repo : https://github.com/sparkfun/SparkFun_Bar_Graph_Breakout_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_Bar_Graph_Breakout_Arduino_Library/tree/V_1.2.0

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
