### ISSUE TITLE
Request to add SparkFun APDS-9960 library to lib package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3155]
Repo: https://github.com/sparkfun/SparkFun_AD5330_Breakout_Arduino_Library/tree/V_1.2.3

Most recent tag: https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library/tree/V_1.4.1

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
