### ISSUE TITLE
Request to add SparkFun MS5803-14BA sensor library to lib. package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3157]
Repo: 
https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library/tree/V_1.1.0

Thank you!

**Comment by ffissore** [comment]
Added. Thanks!
