### ISSUE TITLE
Request to add SparkFun HTU21D lib to library package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3159]
Repository: https://github.com/sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_HTU21D_Breakout_Arduino_Library/tree/V_1.1.0

Edit: thank you!

**Comment by ffissore** [comment]
Added. Thanks!
