### ISSUE TITLE
Request: add SparkFun T5403 sensor lib to library package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3162]
Main repo: https://github.com/sparkfun/SparkFun_T5403_Barometric_Sensor_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_T5403_Barometric_Sensor_Arduino_Library/tree/V_1.0.1

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
