### ISSUE TITLE
Request: add SparkFun VL6180 library to lib package manager

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#3163]
Main repo: https://github.com/sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library

Most recent tag: https://github.com/sparkfun/SparkFun_ToF_Range_Finder-VL6180_Arduino_Library/tree/V_1.1.0

Thank you!

**Comment by ffissore** [comment]
Added. Thanks!
