### ISSUE TITLE
Add more support for 3rd party boards and other mcu families [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#317]
This is [Issue 317](http://code.google.com/p/arduino/issues/detail?id=317) moved from a Google Code project.
Added by 2010-08-05T20:48:11.000Z by [GorillaCoder](http://code.google.com/u/GorillaCoder/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

It would be easier to create third party boards with a bit more help from the IDE, if it were to provide a #define for the board and mcu_family. Further, the xmega fuse bits are much different than other AVR's. Would be nice to use those fuse bits if they are defined in boards.txt.

See attachments to be provided soon.

**Comment by ffissore** [comment]
Solved with 1.6.2
