### ISSUE TITLE
SPI library not found

### ISSUE THREAD

**Issue by Varbin** [arduino/Arduino#3170]
I wanted to use a SD-Card with my Arduino Uno + Ethernet Shield (code from http://www.arduino.cc/en/Tutorial/DumpFile) but I got following error:

```
/home/simon/builds/arduino-1.6.4/libraries/SD/src/utility/Sd2Card.cpp:26:17: fatal error: SPI.h: No such file or directory
 #include <SPI.h>
                 ^
compilation terminated.
Fehler beim Kompilieren.
```

But this works:
```
#include <SPI.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by Chris--A** [comment]
It needs to be included in the sketch also (this will hopefully be fixed soon, part a feature of the IDE preprocessing).

Include SPI.h and SD.h into your sketch.

**Comment by agdl** [comment]
@Varbin @Chris--A I linked the example to dump the code from Git. Now it is correct.
