### ISSUE TITLE
wrong "word" color...

### ISSUE THREAD

**Issue by andres26263** [arduino/Arduino#3175]
I've just installed IDE 1.6.4 and recompiled some old sketches...
I've noticed that "word" variable identifier is showed in GREEN... Should it not be in BLUE ?
I think this is something like "char" issue... :)

**Comment by Chris--A** [comment]
Good find, the word appears twice in the keywords file.

The second version looks like a mistake.

**Comment by andres26263** [comment]
:+1:   :)
