### ISSUE TITLE
Inconsistency between image in schematic for Calibration

### ISSUE THREAD

**Issue by slit27** [arduino/Arduino#3181]
Someone correct me if I'm wrong since I'm new to Arduino and circuits in general, but it seems as though the schematic for http://www.arduino.cc/en/Tutorial/Calibration is not consistent with the image. The 220 ohm resistor and LED are swapped.

**Comment by agdl** [comment]
@slit27 you are right.. Actually the swap is not relevant because they are in series, but I will correct it in order to avoid confusion. Thank you!
