### ISSUE TITLE
Port selection unavalible

### ISSUE THREAD

**Issue by PacksGamingHD** [arduino/Arduino#3183]
If you want to make me go through the extra steps of choosing my board the least you could do is make the Port option selectable! 
![screen shot 2015-05-18 at 10 51 56 am](https://cloud.githubusercontent.com/assets/7285557/7686618/ec1c7728-fd4b-11e4-91c3-3251000fedf4.png)
It was bad enough that I had to go to File > Open > and choose the file instead of double clicking before!

Mac OS X 10.9.5

**Comment by ffissore** [comment]
Please don't cry and tell us which version of the IDE are you running

**Comment by PacksGamingHD** [comment]
1.6.4

**Comment by Chris--A** [comment]
If there is no Arduino connected to the PC via USB, or the PC does not recognize it, the port menu will be disabled.

- Try re-connecting (cheap/old cables do not help).
- Check your device is discovered by the PC (on windows there is a device manager, there would be something similar on a mac)
- If nothing, install/re-install the drivers (ARDUINO_PATH\drivers).

**Comment by PacksGamingHD** [comment]
I'm on a mac and apparently I think it's because I don't actually have wifi (PCIE card broke or something) and now I use an adaptor.

**Comment by ffissore** [comment]
Which boards exactly have you attached to your computer?

Why do you think your wifi adapter is the problem? Are you using a Yun? If
so, does attaching it via usb cable make it work?
Il giorno 19/mag/2015 02.38, "PacksGamingHD" <notifications@github.com> ha
scritto:

**Comment by PacksGamingHD** [comment]
No I'm using an Arduino Pro 3.3 v atmega 328 (TinyDuino)

The only two things connected were the USB cable for the Arduino and
the 802.11n WLAN Adapter

On Mon, May 18, 2015 at 11:27 PM, Federico Fissore <notifications@github.com

**Comment by ffissore** [comment]
Can you say it's an issue with your tinyduino coupled with that wlan
adapter then?

**Comment by PacksGamingHD** [comment]
I have no idea. The only port at the minute that works is usbmodem1411 which is for the Arduino Unos

**Comment by Chris--A** [comment]
Try your other USB ports.

On my old PC, only the main ports on the back of the tower worked with the Arduino.
Using the secondary extension at the front (add on panel in case) does not work.

**Comment by ffissore** [comment]
This starts looking like a problem on your computer, not with the IDE (proof is the UNO is showing up)

**Comment by PacksGamingHD** [comment]
Just connected to Ethernet and all the ports are working

**Comment by PacksGamingHD** [comment]
I have two USB ports. My WLAN adaptor only works in one and the other is for the Arduino
