### ISSUE TITLE
tty.* ports are incorrectly filtered on MacOSX

### ISSUE THREAD

**Issue by zminjie** [arduino/Arduino#3189]
Just got 1.6.4 today and realized that all my /dev/tty.* ports are gone from the port selection menu. Only /dev/cu.* ports remain. Checked my /dev/ manually and see that all the tty ports are actually there, so the Arduino IDE must be filtering them out.

Looking at the change logs: I see this

    ARDUINO 1.6.1 - 2015.03.10
    
    [ide]
    */dev/cu.* serial ports are now filtered from the port list on MacOSX

But it seems that the actual change that went in filtered out all the ports except /dev/cu.* ones.

Did a little digging and saw this commit: cf3e9480a507d7afd158061d1b68fd257ad4a927

The code looks correct since it's returning every port that doesn't start with /dev/cu.*, but for some reason only cu ports are showing up.

**Comment by ffissore** [comment]
That's expected. We changed behaviour after having received negative feedback on it, and switch filtering out ttys. See https://github.com/arduino/Arduino/commit/a8b29d48a51fd633a9c1407581a8eb772141ac70
We failed to update the revision log however. Fixed: https://github.com/arduino/Arduino/blob/master/build/shared/revisions.txt#L66
