### ISSUE TITLE
ArduinoISP sketch should use the SPI library. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#319]
This is [Issue 319](http://code.google.com/p/arduino/issues/detail?id=319) moved from a Google Code project.
Added by 2010-08-06T01:58:28.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-ArduinoISP

### Original description

**What change would like to see?**

The ArduinoISP sketch should use the SPI library rather than including low-level SPI code directly in it.

**Why?**

It should make the code more readable and portable.

**Comment by Chris--A** [comment]
The proposal in #3500 changes the code to use SPI.h for hardware, and also introduces a software alternative.

**Comment by per1234** [comment]
@cmaglie now that #3500 is merged this issue can be closed.

**Comment by facchinm** [comment]
Correct, closing! Thanks @per1234
