### ISSUE TITLE
Selected Board preview doesn't match the board selected in the dropdown

### ISSUE THREAD

**Issue by BrentWilkins** [arduino/Arduino#3198]
I was working on one project on a Pro Mini, but opened a new window with the example Blink sketch.  I uploaded that to another board & closed that window.  The parent window is now in a bad state.
![screen shot 2015-05-20 at 3 43 29 pm](https://cloud.githubusercontent.com/assets/218822/7737469/a65bab8c-ff08-11e4-9831-d36ad3b11320.png)

**Comment by ffissore** [comment]
I'm unable to reproduce it. Here are the steps I followed:
1) Opened IDE
2) Selected Arduino UNO
3) New sketch window
4) Selected Arduino Leonardo
5) Compiled empty sketch
6) Closed window
7) Now first window correctly displays Arduino Leonardo

Are these the steps you've taken?

**Comment by ffissore** [comment]
Also tested on mac and still unable to reproduce it.

**Comment by BrentWilkins** [comment]
I'm also having trouble reproducing it.  Glad I took a screenshot.  I'll report back later if I see it again.  It's apparently non-trivial to get it to that state.
