### ISSUE TITLE
I want to change Arduino Editor Font (Courrier to Consolas)

### ISSUE THREAD

**Issue by turkcanfidan** [arduino/Arduino#3201]
I want to change Arduino Editor Font (Courrier to Consolas)
possible ? or new version :)

**Comment by ffissore** [comment]
Click on the preferences file (bottom of the window opened by clicking on File > Preferences), close the IDE, open file preferences.txt and properly change a line that looks like [this one](https://github.com/arduino/Arduino/blob/master/build/shared/lib/preferences.txt#L93)
