### ISSUE TITLE
auto starting serial monitor on sketch startup

### ISSUE THREAD

**Issue by dominator99** [arduino/Arduino#3204]
My Mega 2560 54MB sketch starts automatically every morning at 06:30.
I would like the serial monitor to begin monitoring this sketch at the same time.
Would it be possible to add this feature?

**Comment by ffissore** [comment]
I think this is out of scope for the IDE and much specific to your particular use case. You'd better add a scheduled task or a cron job that automatically opens putty (or some other serial terminal) at the specified hour
