### ISSUE TITLE
IDE/Editor Short Cut Keys for Windows Users [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#321]
This is [Issue 321](http://code.google.com/p/arduino/issues/detail?id=321) moved from a Google Code project.
Added by 2010-08-07T23:10:07.000Z by [arduinov...@gmail.com](http://code.google.com/u/109943230291489072187/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

Support for ctrl+ins and shft+ins for copy/paste
Ctrl+end/up/down etc to highlight text

**Why?**

I know many windows users who can't use the arduino ide because these shortcuts are missing. This is what we are used to using. Thanks

**Comment by ffissore** [comment]
Fixed since #3019, available in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
