### ISSUE TITLE
Sugestion: unused variables notification

### ISSUE THREAD

**Issue by anjoze** [arduino/Arduino#3213]
When compiling, some IDEs warn about variables not used.
Its a nice feature especially for sketches with tons of variables.
Thanks

**Comment by per1234** [comment]
In IDE 1.6.4+ If you set **File > Preferences > Compiler warnings** to **More** or **All** then you will get warnings about unused local variables. Unfortunately no warnings about unused global variables.

**Comment by cmaglie** [comment]
The global variable is not detected because it may be used from another compilation unit. If you declare the global variable as `static`, it can not be used anywhere else and it's correctly detected as unused, in fact the following sketch:

```C++
int a;
static int b;
void setup() {
  int c;
}
void loop() { }
```

produces:

```
sketch_may25a.ino: In function 'void setup()':
sketch_may25a.ino:5:7: warning: unused variable 'c' [-Wunused-variable]
sketch_may25a.ino: At global scope:
sketch_may25a.ino:2:12: warning: 'b' defined but not used [-Wunused-variable]
```

**Comment by per1234** [comment]
Thanks for the information cmaglie!
