### ISSUE TITLE
Wrong menu items position in Ubuntu

### ISSUE THREAD

**Issue by richardbalaz** [arduino/Arduino#3214]
OS: Ubuntu 15.04 64-bit
IDE: v1.6.5

In Ubuntu is menu items positioning wrong and ugly. Instead of being floated with window buttons, are under them.
![arduino-1 6 5](https://cloud.githubusercontent.com/assets/10794877/7784793/a4573b96-0172-11e5-85cd-b986424b9110.png)

**Comment by ffissore** [comment]
See #3024, #3057, #3046, #3081. Jayatana has been disabled in 25b03b39543a8f2f19f361d39fdf3dfd14420148. You're welcome to dig into the issue and provide an alternative solution

**Comment by RootMale** [comment]
really bad solution, suggest reopen with minor and trying brainstorm on solution
