### ISSUE TITLE
Suggestion: improve default sketch name

### ISSUE THREAD

**Issue by arduinium** [arduino/Arduino#3218]
I think it would be much better if the sketch was named properly with the full date it was started, so instead of "sketch_may25a", "sketch_may25b", we would see names like "sketch_2012-05-25_15.24.52", "sketch_2015-05-25_00.36.12". So we know exactly when this sketch was made, that is much easier in my opinion to find an old sketch, also in the sketch list they will be sorted from the oldest to the newest.

What do you think? Thanks :)

**Comment by ffissore** [comment]
Thank you for your suggestion. Many books, tutorial and articles report such default sketch name. Moreover, you are unlikely to save a sketch with its default name, but rather with a meaningful name you can understand. For these reasons, we won't change the default sketch name
