### ISSUE TITLE
Error -600

### ISSUE THREAD

**Issue by PacksGamingHD** [arduino/Arduino#3219]
I can't open my Arduino application. It says the application can't be opened then it says -600

Mac OS X 10.6.8

**Comment by ffissore** [comment]
Macosx 10.6 is no longer supported. [Download page](http://www.arduino.cc/en/Main/Software) states 10.7 or newer. If you need to run the IDE on older macs, you need to use an [older version](http://www.arduino.cc/en/Main/OldSoftwareReleases#1.5.x) (1.6.1 or older)

**Comment by PacksGamingHD** [comment]
I meant 10.8.5

**Comment by ffissore** [comment]
Does this help? https://discussions.apple.com/thread/4719930

**Comment by ffissore** [comment]
Looks like lots of osx weirdness. Can you try rebooting and retry?

**Comment by PacksGamingHD** [comment]
The problem fixed itself
