### ISSUE TITLE
IDE Editor: Search/find in the files of a project. Easier code navigation [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#322]
This is [Issue 322](http://code.google.com/p/arduino/issues/detail?id=322) moved from a Google Code project.
Added by 2010-08-07T23:13:11.000Z by [arduinov...@gmail.com](http://code.google.com/u/109943230291489072187/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

Find in files (project). Allow a search for code within all files of the current sketch project. Show search results in the same way as compiler output window displays compile errors. Allow double click to the relevent code in the same way as can be done with compiler errors

**Why?**

It would make the ide much less cumbersome to use and allow code to be navigated much more easily. It is a standard feature of many other ide software products and it's absence must "put off" a lot of potential arduino fans

**Comment by ffissore** [comment]
Find dialog looks for text across multiple tabs since #2652, available with latest hourly build http://www.arduino.cc/en/Main/Software#hourly
