### ISSUE TITLE
This erroneous random function

### ISSUE THREAD

**Issue by aonoxh** [arduino/Arduino#3222]
I was doing a very simple code:

void setup () {
   Serial.begin (9600);
}

void loop () {
   int number = random (15);
   Serial.println (number);
   if (number> = 10) {
     Serial.println ("You won");
   }
   delay (1000);
}

and I realize that always comes:

7
4
8
8
10

this is not random

**Comment by Chris--A** [comment]
It always starts from the same seed value.

If you provide a different seed to `randonSeed()` it will produce pseudo random sets.

Try `randomSeed( analodRead( A0 ) );`. And if A0 is unconnected it will sample some static and seed the randomizer.

When I built a game, I used the time it took for the user to select the next screen as a seed value. This provided a very stable random engine as people do not have millisecond accuracy.
