### ISSUE TITLE
[Library Manager] Add more Libraries

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3230]
https://github.com/NicoHood/Nintendo
https://github.com/NicoHood/MSGEQ7

**Comment by NicoHood** [comment]
*push*

**Comment by cmaglie** [comment]
Added but the Nintendo library miss a library.properties. Once you add it (and re-tag the correct revision) the library should appear automatically within an hour.

**Comment by NicoHood** [comment]
Oh I see. Its in my current local dev version. It will take some time till I push this to the master.
Does this matter in any way if I wait too long? Otherwise I'd try to find a solution sooner.

**Comment by cmaglie** [comment]
No problem, no need to hurry.
