### ISSUE TITLE
Little question about (A>B)?A:B;

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3231]
I try to play with an lcd I2C and try the example that follow!
```
      switch(StringToPrint)
      {
        case 0:lcd.print(F("Aux.:"));readAuxTypeLCD();break;
        case 1:lcd.print(F("Sync.:"));lcd.print((synchroIsActive == true)?"On  ":"Off ");break;
        case 2:lcd.print(F("T:"));lcd.print(GetTemp());lcd.print("\x06");lcd.print("C");break;
#ifdef EXTERNALVBATT
//        case 3:lcd.print(F("V:"));lcd.print((externalVBatt == true)?GetExternalVoltage():0.0);lcd.print("V  ");break;
        case 3:lcd.print(F("V:"));lcd.print(GetExternalVoltage());lcd.print("V  ");break;
#endif
      }
```

The case 3 commented don't run but the last run:
The code that read the external voltage is:
```
float GetExternalVoltage()
{
  externalVBatt = true;

  static float coeff_division = 4.0;
  /* Mesure de la tension brute */
  uint16_t raw_bat = analogRead(BROCHE_BATTEXT); //attention a I2C qui utilise les pins A4 et A5  
  /* Calcul de la tension reel */
  float real_bat = ((raw_bat * (5.0 / 1024)) * coeff_division);
//  /* Affichage */
//  Serial << real_bat << endl;
  return (real_bat);
}
```
Thanks for your explain !!!

**Comment by ffissore** [comment]
I've edited your message so that code is properly rendered

**Comment by pierrotm777** [comment]
Cool , thanks

**Comment by cmaglie** [comment]
It seems that part of your message has been lost somewhere, so I don't understand exactly where's your issue.

BTW looks like an error in your sketch not in the LCD library, so you should probably open a discussion in the Arduino Forum http://forum.arduino.cc/ because this site is for tracking and fixing problems in the Arduino software.

**Comment by agdl** [comment]
@pierrotm777 Waiting for feedback for too long. Reopen it if needed
