### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by tarunhv** [arduino/Arduino#3235]
I'm getting this error in each and every program i compile in arduino.
Arduino: 1.6.4 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, 115200, 512K (64K SPIFFS)"

In file included from Blink.ino:18:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/Arduino.h:27:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

DO any one have any solution??

**Comment by ffissore** [comment]
This repository is for bugs and proposals to the Arduino IDE. You're using ESP8266 core, which is a community generated core. Contact the author or post your enquiry on http://forum.arduino.cc
