### ISSUE TITLE
CMD+SHIFT+ARROW should select text on Mac OS X

### ISSUE THREAD

**Issue by Lauszus** [arduino/Arduino#3238]
I believe that the keyboard shortcut for selecting text is wrong on Mac OS X after the introduction of RSyntaxTextArea.

Currently the shortcut is FN+SHIFT+ARROW, but in Arduino 1.6.4 and below it was CMD+SHIFT+ARROW.

**Comment by ffissore** [comment]
You mean current shortcut is ALT+SHIFT+ARROW right?

**Comment by Lauszus** [comment]
No. ALT+SHIFT+ARROW should only select the next word and works as expected. CMD+SHIFT+ARROW should select the entire line.

**Comment by Lauszus** [comment]
I just tried FN+SHIFT+ARROW and it seems like the standard is that it selects all text on the line and any text that follows. Let say I press FN+SHIFT+LEFT, then it selects the text to the left and all text above it.

**Comment by Lauszus** [comment]
I just found this Wiki article which backs up my claim: http://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing.

**Comment by ffissore** [comment]
Please give a spin to #3239 as soon as @ArduinoBot has published a build
