### ISSUE TITLE
[Library Manager] Add more Libraries

### ISSUE THREAD

**Issue by karlbackstrom** [arduino/Arduino#3247]
https://github.com/akafugu/FourLetterWord
https://github.com/akafugu/TWIDisplayLibrary
https://github.com/akafugu/TWIKeyboardLibrary
https://github.com/akafugu/TWILiquidCrystalLibrary
https://github.com/akafugu/WireRtcLibrary

**Comment by ffissore** [comment]
Added. Thanks!
