### ISSUE TITLE
"Board at /dev/ttyACM0 is not available" error when opening Serial monitor/plotter (1.6.5)

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3249]
But when I upload the sketch it's fine.
I'm using Fedora 22 64 bits

**Comment by ffissore** [comment]
When you open a sketch, you don't open serial ports. When you open the serial monitor, the selected serial port must be available. If your issue is specific to the proposed plotter, please close this issue and comment at #2177

**Comment by q2dg** [comment]
Ok, thanks a lot!  (how fast!, so glad)
Now it works perfectly
