### ISSUE TITLE
[DOC] Arduino Gemma page incorrectly states Li-Ion Battery charging is built-in

### ISSUE THREAD

**Issue by tapanther** [arduino/Arduino#3258]
The Arduino Gemma page, http://www.arduino.cc/en/Main/ArduinoGemma, incorrectly states that the Gemma board is capable of charging a Li-Ion Battery pack:

>The board contains a MIC5225 Li-Ion battery charging chip. If the board is connected to both USB 
> and a battery, the USB power will charge the battery. This is true regardless of the position of the
> switch. The LED above the word "CHG" lights up while the battery is being charged. The charging 
> will stop automatically when the battery is fully charged.

The online image shows no such chip or CHG LED. I received a Gemma board today, and I can confirm that no LED lights up when both USB and a Li-Ion battery are connected with the board off. MIC5225 is not a Li-Ion charging chip, it is an LDO regulator.

This issue was raised with Adafruit (from whom the inspiration for Gemma came from), and they confirm the Gemma board has no such Li-Ion charging capabilities: https://forums.adafruit.com/viewtopic.php?f=8&t=74482&p=377579&hilit=gemma#p377626

**Comment by agdl** [comment]
@tapanther I removed the incorrect statement thank you!
