### ISSUE TITLE
Arduino should ask before silently creating the folder "sketchbook" in the home directory

### ISSUE THREAD

**Issue by mghansen256** [arduino/Arduino#3259]
When starting the Arduino UI (version 2:1.0.5+dfsg2-4) for the first time on Linux, a folder "sketchbook" is created in the home directory. IMHO the program should first ask the user whether it may create the folder there or elsewhere, in order not to clutter a user's home directory with unknown folders.

**Comment by tytower** [comment]
One thing is for sure . If its unknown to you now it won't be for long if you use Arduino

**Comment by sspence65** [comment]
Where else would you have it create sketchbook? It's not an unknown folder, it's where all your sketches and 3rd party libraries are held.

**Comment by ffissore** [comment]
Wontfix. All available documentation uses the *default sketchbook location*
