### ISSUE TITLE
Missing documentation for String() constructors

### ISSUE THREAD

**Issue by dwwolfe** [arduino/Arduino#3264]
Issue #1297 added support for constructing a String object with a float/double.  The documentation for string constructors does not reflect the ability to do this:

http://www.arduino.cc/en/Reference/StringConstructor
http://www.arduino.cc/en/Tutorial/StringConstructors

I've wasted a lot of time trying to get around this issue using dtostrf() and writing custom functions so it would have been much nicer to immediately find it on the reference pages!  Thanks

**Comment by agdl** [comment]
@dwwolfe it is online now. If it is good for you please close this issue

**Comment by dwwolfe** [comment]
The reference page looks good, thanks.  I'm not sure whether it is worth updating the tutorial page as well?  I will let that up to you but a google search for arduino string constructors turns up both pages that I cited so a user could still land on a page without any mention of float/double support.  If those tutorial pages are not typically updated then I can just close the issue

**Comment by agdl** [comment]
They will be updated automatically because they dump the code from github
so now that the PR is merged they will go online as well
Il 01/Giu/2015 15:44, "dwwolfe" <notifications@github.com> ha scritto:

**Comment by dwwolfe** [comment]
Very good, thanks again
