### ISSUE TITLE
YunClient's connected() returns false with unread bytes

### ISSUE THREAD

**Issue by RobAtticus** [arduino/Arduino#3274]
According to its documentation, YunClient should return true with unread bytes:
http://www.arduino.cc/en/Reference/YunClientConnected

However, if the connection is closed at a TCP level, it will return false even with bytes left unread.

**Comment by RobAtticus** [comment]
I'm not sure this is a documentation problem as other clients, e.g., WifiClient, have the same documentation. I believe the YunClient does not conform to other Clients.

**Comment by RobAtticus** [comment]
I have submitted a PR to address this and another issue I found:
https://github.com/arduino/Arduino/pull/3288

**Comment by cmaglie** [comment]
Fixed by #3288
