### ISSUE TITLE
[1.6.4.] [OSX] Invalid port names

### ISSUE THREAD

**Issue by KenjutsuGH** [arduino/Arduino#3275]
Port names are displayed as (for example) "/dev/**cu**.usbserial-A943NTHT" but it should be the **tty** equivalent, in other words, "/dev/**tty**.usbserial-A943NTHT"

**Comment by ffissore** [comment]
It's a feature: see #2626 and a8b29d48a51fd633a9c1407581a8eb772141ac70. You can re-enable them closing the IDE, editing file `preferences.txt`, changing value `serial.ports.showall` from `false` to `true` and restarting the IDE
