### ISSUE TITLE
[Ethernet 2 Library] DHCP Response Latency of IP Address

### ISSUE THREAD

**Issue by elsa0919** [arduino/Arduino#3278]
I got an Arduino Ethernet Shield 2 from this distributor: 
https://www.switch-science.com/catalog/2270/

Follow by the instructions I downloaded the Arduino IDE 1.7.2 and have tried the build-in example DhcpAddressPrinter with Ethernet 2 Library.

It works, it does have return the ip address of my Ethernet 2 shield.

But somehow it is not a very quick response to get this ip address...
I almost wait for 30 seconds then get the response.

I got information from the Arduino.cc forum that were saying users can get a DHCP response within the fraction of second..
http://forum.arduino.cc/index.php?topic=326802.15

*My Testing Environment (the link has specified where I got it)*
- [Arduino UNO SMD Rev 3 (A000073)](http://akizukidenshi.com/catalog/g/gM-07383/)
- [Arduino Ethernet Shield 2 (A000024)](https://www.switch-science.com/catalog/2270/)
- [Arduino IDE 1.7.2](http://www.arduino.org/downloads/previous-releases)

Do you have any idea of this phenomena?
Any help is appreciated..

**Comment by Chris--A** [comment]
Your Ethernet shield is not part of the official Arduino products from http://arduino.cc (http://www.arduino.cc/en/Main/Products).

This issue tracker is for the Arduino IDE managed by the people who run the Arduino.cc site. Your products and IDE came from a mob that called themselves arduino.org.

You can post an issue on their tracker here: https://github.com/arduino-org/Arduino

As far as helping, I can only advise to try a long delay at the beginning to allow the Ethernet chip to finish resetting properly, this helped get a quick DHCP response with my real Arduino Ethernet shield.
