### ISSUE TITLE
EducationShield

### ISSUE THREAD

**Issue by Alejandro1982** [arduino/Arduino#3286]
Library used for the completion of the projects of Creative Techonlogies in the Class (CTC)

**Comment by ffissore** [comment]
I guess you want it included in the library manager: can you provide the repo url?

**Comment by Alejandro1982** [comment]
yes, that is the idea. I just opened the issue in the Arduino Github as
EducationShield and the repo url is:

https://github.com/arduinoverkstad/EducationShield.git
ᐧ



Alejandro Vazquez Bofill
Hardware/Firmware Developer
+46 (0) 760248825
Arduino Verkstad Malmö <http://verkstad.cc/>

**Comment by ffissore** [comment]
Added. Thanks!

**Comment by Alejandro1982** [comment]
Thank you!!!

**Comment by q2dg** [comment]
Would it be possible to add this shield to Arduino official shields (and therefore, to sell it in Arduino store)? It's done by Cuartielles and co...
