### ISSUE TITLE
Bridge problem with YUN

### ISSUE THREAD

**Issue by IvanKunjasic** [arduino/Arduino#3298]
I try to upload simple Bridge sketch to my Arduino YUN, but i didn't get any Serial Monitor output. 
http://www.arduino.cc/en/Tutorial/Bridge

Also, on two separate Arduino Yuns on two separate laptops, I can't get JsonParserExample(aJSON) to Run. I just get no output in the Serial Monitor. And if I change the lines
```arduino
if (!root.success()) {
Serial.println("parseObject() failed");
return;
}
```
to
```arduino 
if (!root.success()) {
Serial.println("parseObject() failed");
return;
} else {
Serial.println("Success!");
}
```
I still get nothing from the Serial Monitor.

I've checked the Baud Rates. I've run Examples>04.Communication>SerialCallResponse and the Serial Monitor works fine there.

Any clue?

**Comment by per1234** [comment]
Transferred to https://github.com/arduino-libraries/Bridge/issues/29
