### ISSUE TITLE
Renaming don't consider case change as a change

### ISSUE THREAD

**Issue by simonjamain** [arduino/Arduino#3305]
I forgot to uppercase the first letter of my class file name, so I go rename via the menu at the right of the tabs. After putting it uppercase I validate but it doesn't do anything. I manage to do it by first rename the file by changing letters and then putting the good file name.

Sorry if bad english.

Simon

**Comment by ffissore** [comment]
I think this is a windows issue: windows filesystem is case insensitive so changing a file name from "this" to "This" is not a change. You'd better change "this" to "that" and back to "This"

**Comment by simonjamain** [comment]
Thank you for your answer.

But I would like to mention that this "bug" occured on **OSX yosemite** and not on windows, sorry about forgetting to mention that.

**Comment by ffissore** [comment]
Ah, that changes. I'll look into it. Thanks

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by simonjamain** [comment]
Many thanks, have a good day.
