### ISSUE TITLE
Missing line break between compiler warning and multiple libraries notification

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3308]
Using Arduino IDE 1.6.5 Hourly Build 2015/06/08 03:34 under Windows 7 64 bit
Very minor issue but I thought I'd mention:
- Include library that has multiple copies installed.
- Add code to sketch that causes a compiler warning.
- Compile sketch - there is no line break between the last warning and the multiple libraries notification.
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/8053292/08c05d78-0e44-11e5-9f66-7ef9ade898d2.gif)
If I paste the text here I do get the line break in the proper place.

**Comment by per1234** [comment]
This issue is not limited to the multiple libraries notification. For example when 
compiling the Ethernet library AdvancedChatServer example with Compiler warnings: All:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/8368532/5e753ab2-1b60-11e5-9c9a-a128102d854b.gif)
There is a missing line break between two warnings.

**Comment by ffissore** [comment]
I've started working on a fix by reimplementing the EditorConsole. Some initial work is available at https://github.com/ffissore/Arduino/tree/new-console but it's still not mature enouhg

**Comment by ffissore** [comment]
Give a try to #3433 it's ready to be merged, it needs just some positive feedback

**Comment by per1234** [comment]
Works fine for me. Thanks!
