### ISSUE TITLE
IDE - ERROR COMPILING font Color - color blindness for RED

### ISSUE THREAD

**Issue by Wayne-Web** [arduino/Arduino#3314]
Hi

Any chance the font color can be changed (red on black and my color blindness kicks in big time) - user selectable or at least contrasting colours (black/white etc)

Thanks in advance

**Comment by ffissore** [comment]
Close the IDE, locate file IDEFOLDER/lib/theme/theme.txt: you'll find a variety of #RRGGBB colors. Look for `console.error.color = #E34C00` and change it accordingly. Restart the IDE
