### ISSUE TITLE
Switch to Java 8

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#3315]
With #3312 merged, every IDE for every OS bundles the JVM. We can now switch to java 8 without forcing installation of an updated JVM.

**Comment by jverne** [comment]
Part of the move to Java 8 might consider a bulk edit to get rid of the warnings about bare "_" identifiers.

**Comment by ffissore** [comment]
Indeed

**Comment by ffissore** [comment]
Fixed by 1e82def56e7e9bd1f0f416667539c26dc8a1b098. `_` identifiers tracked at #3344
