### ISSUE TITLE
RAMBo motherboard missing

### ISSUE THREAD

**Issue by a4jp-com** [arduino/Arduino#3318]
I moved the files for the RAMBo motherboard into the hardware folder but the RAMBo motherboard option doesn't come up.

Without this my Printer can't load the LCD driver.

Please help.

Windows 7 64-bit

**Comment by ffissore** [comment]
Please ask your question to RAMBo support/issue tracker/forum

**Comment by a4jp-com** [comment]
Please add RAMBo boards to Arduino.

**Comment by a4jp-com** [comment]
From version 1.0.5 to 1.6.4 what changed to make the RAMBo board not load? I guess the change was programming here.

**Comment by ffissore** [comment]
Indeed hardware folder structure changed. See this guide https://github.com/arduino/Arduino/wiki/Arduino-Hardware-Cores-migration-guide-from-1.0-to-1.6 Please forward it to RAMBo developers
