### ISSUE TITLE
Add three new libraries to library manager

### ISSUE THREAD

**Issue by tdicola** [arduino/Arduino#3320]
This is a small issue to add the following three new libraries to the Arduino library manager:
- Adafruit_MQTT, general purpose MQTT library: https://github.com/adafruit/Adafruit_MQTT_Library
- Adafruit_SleepyDog, watchdog and sleep library: https://github.com/adafruit/Adafruit_SleepyDog
- Adafruit_IO_Arduino, REST API client for Adafruit's IO service: https://github.com/adafruit/Adafruit_IO_Arduino

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
