### ISSUE TITLE
build error - 1.6.5

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#3322]
During build time, the following error message is displayed and build failed. 'Apache Ant(TM) version 1.9.4 compiled on April 29 2014' is used on Cygwin.

error message
============
```
untar-unzip-checksum:
     [echo] Testing checksum of "Firmata-2.4.3.zip"

unzip:
   [rename] DEPRECATED - The rename task is deprecated.  Use move instead.

BUILD FAILED
```

**Comment by Chris--A** [comment]
I have confirmed this and added a PR.

**Comment by ffissore** [comment]
Thanks for the heads up!
