### ISSUE TITLE
Add a clickable link for the Unofficial boards list page

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3327]
A good idea would be to add a clickable link for your page :
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

If possible, on the label 'Additional Boards Manager URLs' into the preferences window ???

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
