### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by f7soft** [arduino/Arduino#3328]
Please, could you sync translations with transifex project? I use Russian language in IDE and current translation is not very good. There are fixed strings on transifex.
Also I ask you to add new strings for translation to transifex and update it more frequently. It will be easier to work with Arduino for the people who don't speak English. Thanks!

**Comment by ffissore** [comment]
Translations updated with 80fa3451be1a07a2d009a1588ac113ba1d95a850 and transifex synchronized. Updated translations will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
