### ISSUE TITLE
Library manager submenus cosmetic issue - observed on Due. 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#3332]
Current 1.6.4. release Library Manager lists / display submenu items ("Arduino/SAM libraries") ( after separator ) grayed out. This menu item can be selected ( full blue color) but it does nothing. 
If intended to be used as a title of the following submenus it should be standard (full) text color with ellipsis followed with real submenu list.

**Comment by ffissore** [comment]
Can you attach a screenshot of an app that behaves the way you describe?

**Comment by VaclavSal** [comment]
A menu item NOT selected 
B menu item SELECTED

![ide1 6 4_a](https://cloud.githubusercontent.com/assets/6053260/8146178/12957c1a-11f1-11e5-8f92-386575260728.JPG) 
![ide1 6 4_b](https://cloud.githubusercontent.com/assets/6053260/8146179/1688208e-11f1-11e5-9a39-bd13aeaaf4a4.JPG)

**Comment by Chris--A** [comment]
But can you actually select it, or does it do nothing.

On Windows 8.1 it looks like this, and it is not clickable:
![menus](https://cloud.githubusercontent.com/assets/6584350/8147499/09910ae2-12b1-11e5-845d-ace86fcf9a71.png)

**Comment by VaclavSal** [comment]
Yes it does nothing and that is why I brought it up as a "cosmetic" issue.
It is an unusual usage of "Menu Control" independent ( or should be) of OS or  software used to build it.
Ideally the "Include Library" menu should look this way

Manage Libraries...    (or "Manage Libraries > "  to be consistent with the parent menu title ) 
Separator
Add Zip Library..
Separator
Arduino Libraries ( Or Adruino /SAM libraries..)  - opens submenu 
Separator 
and so on

That would be consistent usage of menu control, however , an average " push button and light up LED" user probably does not care - hence "cosmetic issue".
.

**Comment by Chris--A** [comment]
I agree, that it would be handier to use sub menus rather than a huge list of boards from every core.

**Comment by ffissore** [comment]
Submenus VS. disabled menu entry have been debated in the past but are a Processing inheritance we prefer to stick to. Closing as wontfix
