### ISSUE TITLE
Wrap Around for Higher (>10) Serial Port Number in Windows 7

### ISSUE THREAD

**Issue by xsk8rat** [arduino/Arduino#3333]
When the serial port for the Yun is larger than "Com10", (shown as COM20 in the example image):
![image1](https://cloud.githubusercontent.com/assets/9683767/8145743/b77dd6a4-11d9-11e5-9ad6-f290abd9005b.jpg)
The Tools menu of the Arduino App reports that both the N and Int[N/10] ports are occupied by the Yun:
![image2](https://cloud.githubusercontent.com/assets/9683767/8145744/e7b2d20c-11d9-11e5-8d3b-8caf88c93a24.jpg)
Of course, only one is really there.

**Comment by ffissore** [comment]
Next time it happens, can you open a command prompt, `cd` to `IDE_FOLDER\hardware\tools\`, run program `listComPorts.exe` and paste the output? That will help understand where the problem is

**Comment by xsk8rat** [comment]
Thanks! Here is the output you requested. Please note that i manually changed the port to the higher COM12 using the Device Manager.

    COM1 - (Standard port types) - ACPI\PNP0501\1
    COM2 - (Standard port types) - ACPI\PNP0501\2
    COM12 - Arduino LLC (www.arduino.cc) - USB\VID_2341&PID_8041&MI_00\8&AB76839&0&0000
    COM3 - FTDI - FTDIBUS\VID_0403+PID_6015+DA00WSEWA\0000

**Comment by ffissore** [comment]
Ah, weird. I'll test it. Does COM1 stays labelled as "yun" even after some minutes?

**Comment by ffissore** [comment]
That was indeed a bug in the parser. Thank you very much. Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by xsk8rat** [comment]
Cool! Thank you!
