### ISSUE TITLE
Arduio Zero documentation

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3341]
This pages says the Zero has a 16u2.
http://www.arduino.cc/en/Guide/ArduinoZero

This page says it is EDBG
http://www.arduino.cc/en/Main/ArduinoBoardZero

I think 16u2 is wrong and should be fixed.

And what about atmel studio integration?
What about usb HID functions?

**Comment by Fede85** [comment]
thank you for spotting this typo. EDBG is the correct one, any reference to the 16u2 on the Getting Started page was a mistake. Now the description of the Programming Port on the Getting Started page is correct.

At the moment the HID functions implemented are mouse and keyboard.
The Arduino Zero is already supported by Atmel Studio. At the moment we don't have any documentation that describes how to use the Zero with Atmel Studio. However, any update about this will be communicated via the Arduino blog.
