### ISSUE TITLE
Colors issue 1.6.5

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3346]
The variable type boolean has no color for the words 'true' or 'false' !

**Comment by Chris--A** [comment]
These are explicitly in the keywords.txt, I just guessed this was the colour they intended to use: 
https://github.com/arduino/Arduino/blob/master/build/shared/lib/keywords.txt#L57
https://github.com/arduino/Arduino/blob/master/build/shared/lib/keywords.txt#L73

**Comment by ffissore** [comment]
I forgot it. Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by pierrotm777** [comment]
Colrs are specified but stay always black

**Comment by ffissore** [comment]
Please re-download the hourly: you may have downloaded a yet-not-fixed version

**Comment by pierrotm777** [comment]
It's ok now on 1.6.6 . What file i must to copy into the 1.6.5 IDE for solve this issue ?

**Comment by ffissore** [comment]
`lib/theme/theme.txt` and pde.jar. Since we just started 1.6.6, it's safe for you to keep on using it: it's *almost* equal to 1.6.5

**Comment by pierrotm777** [comment]
It's ok for me, thanks

**Comment by otojunior** [comment]
I having this same problem. The property 'editor.fgcolor' in lib/theme/theme.txt doesn't working. The text it's always black
Where can I dowload version 1.6.6 ? Is the master branch? Have I to build it ?

**Comment by Chris--A** [comment]
You can download it here:
http://www.arduino.cc/en/Main/Software

Scroll below the main download links and there is a section labelled 'Hourly Builds'
