### ISSUE TITLE
Additionnals board manager screen issue

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3348]
The internal list don't follow the change screen size !

May be , the link that stop the change size ?

**Comment by ffissore** [comment]
I didn't catch that. A screenshot maybe?

**Comment by pierrotm777** [comment]
![arduino](https://cloud.githubusercontent.com/assets/8189970/8202387/ba07fc76-14d9-11e5-98fc-bdb41ecb4239.jpg)

**Comment by ffissore** [comment]
wow, ok

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
