### ISSUE TITLE
Error highlighting wonky 

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#3349]
![Screenshot](http://i.imgur.com/lkM776z.png)

I am using Ubuntu 15.04 and Arduino IDE release 2015/06/16 04:19.

This happens when IDE finds an syntax error and then takes the cursor there, when the cursor is moved with a mouse click a black bar (visible from screenshot) appears. This can be reproduced.

**Comment by ffissore** [comment]
I can't reproduce it. The highlight bar is pinky from start to end

**Comment by Chris--A** [comment]
No error on windows either.

**Comment by pfeerick** [comment]
Not repeatable here. I unpacked a squeaky clean version of Arduino IDE v1.6.5 x32 onto Ubuntu 15.04 (from the package provided on the arduino site) and 'broke' the Blink sketch to get a similar error. I also get the pink highlight across the full line. 

![capture](https://cloud.githubusercontent.com/assets/5500713/8271316/d1b6e602-1853-11e5-985e-813464b95f3e.PNG)

**Comment by Avamander** [comment]
Most likely some weird hardware+software and planetary state combination that causes this for me.
