### ISSUE TITLE
User-unfriendly error message that could be made simpler

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#3350]
Arduino: 1.6.6 Hourly Build 2015/06/16 04:29 (Linux), Board: "Arduino Nano, ATmega328"

>avrdude: ser_open(): can't open device "/dev/ttyUSB2": No such file or directory
>ioctl("TIOCMGET"): Inappropriate ioctl for device

Could be just replaced with "Failed to find device at "/dev/ttyUSB2" ". Also, avrdude error message does not begin with a new line, it is printed on top of previous message ![bytes.avrdude](http://i.imgur.com/7pFRXXq.png).

**Comment by ffissore** [comment]
Actually, that error message may mean lots of different things and we can't change it so easily. As for the missing new line, it's caused by a buggy handling of the output we hope to fix for 1.6.6. Also see #2680 and #2798
