### ISSUE TITLE
Image missing in IDE Help

### ISSUE THREAD

**Issue by akash73** [arduino/Arduino#3354]
In Troubleshooting guide inside the IDE , under " What if my board doesn't turn on (the green power LED doesn't light up)?" , the image "jumper.jpg" is missing.
IDE 1.6.5 , MacOSX

![screenshot 2015-06-17 12 29 55](https://cloud.githubusercontent.com/assets/921616/8205163/6d845614-14ee-11e5-96be-c28b4239cefd.png)

**Comment by ffissore** [comment]
Bundled reference updated. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
