### ISSUE TITLE
[Library Bug] Only takes the main tree

### ISSUE THREAD

**Issue by juanscelyg** [arduino/Arduino#3357]
When I choose a library to work, but it had so many trees, the software takes only de main tree and the others files arent importan for the compilation. The solution is put the files into the main directory. Any questions? Sorry but i dont have time to read full issues! Greatings from Colombia! I forget that . . . this problem has been on Ubuntu 14.04 with Arduino Version 1.0.5. Bye

**Comment by ffissore** [comment]
I didn't catch that. Closing as invalid. Reopen when you have time for a detailed explanation. Also, 1.0.5 is quite old. Download 1.6.5 from http://www.arduino.cc/en/Main/Software
