### ISSUE TITLE
Windows: if username contains non ASCII char, IDE won't create correct Arduino15 folder

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#3360]
Because the output of `req query` is encoded someway
```

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders
    AppData    REG_SZ    C:\Users\Ren\AppData\Roaming
```

**Comment by bjorn-wiberg** [comment]
Same problem on a Swedish (CP850) Windows 8 installation (#3376).

**Comment by ffissore** [comment]
Reopen since I'm not sure and need to test it

**Comment by ffissore** [comment]
@bjorn-wiberg can you try downloading the hourly build? http://www.arduino.cc/en/Main/Software#hourly The problem should be fixed. Please start the IDE from command prompt using `arduino_debug.exe` so that any error message gets printed and you can paste them here

**Comment by ffissore** [comment]
Positive feedback received from http://forum.arduino.cc/index.php?topic=329989.msg2288421#msg2288421. Closing
