### ISSUE TITLE
Compile with -fvtable-gc  for smaller binaries

### ISSUE THREAD

**Issue by yyyc514** [arduino/Arduino#3363]
Ref: http://stackoverflow.com/questions/17433791/eliminate-unused-virtual-functions

Should this be a default?  I know a lot of graphics libraries subclass Print and then have to define write... but then you get dependency chains like `write -> drawChar (-> drawRect for zoom), fontTable`, etc... and now you're linking in 2kb of stuff that a graphics (sprites, etc) only program will never use.  And the compiler happily links it all because `write` happens to be in your subclasses vtable and the compiler isn't trying hard enough to figure out if it's actually used or not.

Thoughts?

We'll probably end up using separate subclasses to solve this problem... one that supports printing and one that doesn't, but it seems that wouldn't be necessary with this switch.

**Comment by Chris--A** [comment]
From the latest build:

> avr-g++: warning: switch '-fvtable-gc' is no longer supported

**Comment by yyyc514** [comment]
Oh:

http://stackoverflow.com/questions/17445907/replacement-for-fvtable-gc-in-gcc

Ok then, I guess that solves that.
