### ISSUE TITLE
Theme colors issue ?

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3367]
I try to change the color of the comment type 2 but without succes:
# TEXT - COMMENTS
#editor.comment1.style = #434F54,plain
editor.comment1.style = #416913,plain
#editor.comment2.style = #95a5a6,plain
editor.comment2.style = #416913,plain

**Comment by ffissore** [comment]
have you restarted the IDE?

**Comment by ffissore** [comment]
btw, `comment2` is not used anymore, only `comment1` is

**Comment by pierrotm777** [comment]
Yes !

**Comment by pierrotm777** [comment]
How to change the type comment like /*...*/  ?

**Comment by ffissore** [comment]
Thank you @pierrotm777, indeed multiline comments weren't handled by theme. Now they are, using `comment2` (re-enabled). Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by pierrotm777** [comment]
Cooool, thanks
