### ISSUE TITLE
The 'editor.fgcolor' property in theme config file doesn't work

### ISSUE THREAD

**Issue by otojunior** [arduino/Arduino#3372]
I'm trying to configure a dark theme in IDE and the property 'editor.fgcolor' located in lib/theme/theme.txt doesn't change the editor text color. The text color is always black, no matter the property value.

**Comment by pfeerick** [comment]
Nice! Didn't realise you could change the theming of the editor that easily! 

editor.bgcolor changes the background properly, but as otojunior has commented, editor.fgcolor does not appear to be changing the text colour. Arduino IDE v1.6.5, Windows 7 x64.

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly. Thanks!
