### ISSUE TITLE
Second serial monitor window opens after "Board at COMx is not available" error

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3379]
Using Windows 7 64 bit with Arduino IDE 1.6.6 Hourly Build 2015/06/19 06:42

Steps to reproduce:
- Plug in board to USB
- Open serial monitor
- Unplug board from USB
- Upload - it fails with `Board at COMx is not available` error
- Plug in board to USB
- Open serial monitor - there are now two serial monitor windows open, one working the other not working.

**Comment by pfeerick** [comment]
Repeatable here with Arduino IDE v1.6.5 on Windows 7 x64.

**Comment by ffissore** [comment]
Thanks! I'll look into it asap

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
