### ISSUE TITLE
Auto closure of scope.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#3390]
I know that inserting brackets for users '{}' is handy when you're a beginner, which is why I've decided to try and like it. However when creating objects (class,struct,union) it does not add the required semicolon after the closing brace, and is probably going to cause more headaches than the advantages it provides. People new to the language will most likely accept that the IDE knows what it is doing.

Is this fixable here, or is this an issue for the RSyntaxTextArea repo?

**Comment by ffissore** [comment]
Not something we may easily fix. However, I was just checking with my IDE (intellij) and it too leaves the closing brace alone, no matter what is behind the opening one: if it's a method, fine, otherwise it underlines the closing brace with a red line.
