### ISSUE TITLE
Hyperlinks with ampersand in comments are truncated

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3392]
Windows 7 64 bit Arduino IDE 1.6.6 Hourly Build 2015/06/19 06:42
- add the text `// https://forums.adafruit.com/viewtopic.php?f=25&t=12170` to a sketch
- click on the URL
- the browser opens https://forums.adafruit.com/viewtopic.php?f=25 instead of https://forums.adafruit.com/viewtopic.php?f=25&t=12170

**Comment by ffissore** [comment]
Doesn't happen on linux, so I think it's because there are no double quotes around the url [here](https://github.com/ffissore/Arduino/blob/master/arduino-core/src/processing/app/windows/Platform.java#L137-137). I'll check it as soon as I can get my hand a windows box

**Comment by Chris--A** [comment]
I'll check it now.

**Comment by Chris--A** [comment]
Its quite strange this one. I couldn't get it working with quotes. It just opened up a console named with the URL.

Directly using the console is no better.
This only searches for *cheese*:
`start https://google.com?q=cheese&q=bread`

This opens up a console:
`start "https://google.com?q=cheese&q=bread"`

To get it working, an empty set of quotes is required before the quoted URL.
Now a browser opens and searches for *bread*:
`start "" "https://google.com?q=cheese&q=bread`

Here is the commit I ended up with: https://github.com/Chris--A/Arduino/commit/cac568f44c3dd007d29d24c9aedd6cc86804fffc

**Comment by ffissore** [comment]
Thanks @Chris--A , I'll test it on my windows box later tomorrow. According to this, your empty double quotes is assigned to the `title` param, while the url to the `filename`: maybe `start` opens the url specified with title if not filename is given, but `&` are forbidden in titles and get removed

**Comment by ffissore** [comment]
"this" was this https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/start.mspx?mfr=true

**Comment by ffissore** [comment]
@Chris--A looks good. Mind making a plain PR? So we keep on dancing the usual dance

**Comment by Chris--A** [comment]
No worries, will push it through
