### ISSUE TITLE
Add a new tab with the IDE

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3397]
It's possible to a have the possibility to add a new tab with by example CTRL + T ?

**Comment by per1234** [comment]
CTRL + T is used for Auto Format. I think it would be great to have a keyboard shortcuts manager that allows the user to choose any shortcut for any function of the IDE. All my favorite software has this feature.

**Comment by pierrotm777** [comment]
As you prefer :-)

**Comment by ffissore** [comment]
There already is CTRL+SHIFT+N

**Comment by pierrotm777** [comment]
It's ok for me !
