### ISSUE TITLE
Arduino 1.6.5-r2 installer Java errors

### ISSUE THREAD

**Issue by brv64b** [arduino/Arduino#3398]
Hi
What's with all the Java errors (>10) during install ?
You can ignore them (by hand) and the Arduino IDE will run - but what's wrong ..?

My pc is running Win7/64

Regards
bs

**Comment by ffissore** [comment]
What are those errors? Haven't seen them yet

**Comment by brv64b** [comment]
[image: Billede indsat i tekst 1]

[image: Billede indsat i tekst 2]

[image: Billede indsat i tekst 3]

And so on for 10 more screens - all that I Ignored ..
However the IDE works so I ques that it's something local problem with my
pc/setup ..?


2015-06-22 16:43 GMT+02:00 Federico Fissore <notifications@github.com>:

> What are those errors? Haven't seen them yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/3398#issuecomment-114137122>.
>



-- 

bs

**Comment by ffissore** [comment]
Sorry, github does not support attachment. Please attach those files using your browser

**Comment by brv64b** [comment]
I hope this works ..
![arduino 1 6 5 - installation folder](https://cloud.githubusercontent.com/assets/10738165/8287995/af3185b8-1913-11e5-87ac-53c770207de6.png)
![arduino 1 6 5 - setup 1](https://cloud.githubusercontent.com/assets/10738165/8287998/b1dfd9d6-1913-11e5-882a-4f4ce927d237.png)
![arduino 1 6 5 - setup 2](https://cloud.githubusercontent.com/assets/10738165/8288001/b42278de-1913-11e5-8627-861147ef4e9c.png)

**Comment by PaulStoffregen** [comment]
Perhaps you have anti-virus or security software which is interfering with the installation?

**Comment by ffissore** [comment]
Or perhaps you need to run it as administrator?

**Comment by brv64b** [comment]
Nope - that didn't help either ..  :-(
Well - let's leave it there. The IDE works (never the less).
Strange that I should be 'the only one' ..  ;-)

2015-06-23 8:44 GMT+02:00 Federico Fissore <notifications@github.com>:

> Or perhaps you need to run it as administrator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/3398#issuecomment-114378202>.
>



-- 

bs
