### ISSUE TITLE
[Library Manager] New SWAP library

### ISSUE THREAD

**Issue by dberenguer** [arduino/Arduino#3405]
Please add the this repository to the list of available libraries:
https://github.com/panStamp/swap

SWAP stands for Simple Wireless Abstract Protocol:
https://github.com/panStamp/panstamp/wiki/Simple%20Wireless%20Abstract%20Protocol

Thanks in advance.

**Comment by ffissore** [comment]
Your sram lib from #3416 share the same name with this lib. Both libs removed.

**Comment by dberenguer** [comment]
Libraries renamed. Sorry for the confusion.
