### ISSUE TITLE
Support for faster baud rates in the serial monitor and Serial class. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#341]
This is [Issue 341](http://code.google.com/p/arduino/issues/detail?id=341) moved from a Google Code project.
Added by 2010-08-29T19:11:10.000Z by [narmada.prabakaran](http://code.google.com/u/narmada.prabakaran/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

I would like to have more baud rates in the SerialMonitor.java file (230400, 460800, 921600bps etc.,)

**Why?**

It is supported by FTDI chip so we can use for faster data transfer

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

no

**Comment by ffissore** [comment]
Added 230400 and 250000 baud rates. Available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
