### ISSUE TITLE
[Library Manager] Some more libraries by panStamp

### ISSUE THREAD

**Issue by dberenguer** [arduino/Arduino#3416]
Could you please add these libraries to the Library Manager?
https://github.com/panStamp/sram
https://github.com/panStamp/thermistor
https://github.com/panStamp/mma8652

Thanks in advance.

**Comment by ffissore** [comment]
See https://github.com/arduino/Arduino/issues/3405#issuecomment-115152534

**Comment by dberenguer** [comment]
Libraries renamed. Sorry for the confusion.

**Comment by ffissore** [comment]
Please open a new issue dedicated to added those 2 libs
