### ISSUE TITLE
No error when non-existent board given to --board on the commandline

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#3417]
Running this:

    arduino --board arduino:avr:foo --verify Sketch.ino 

Happily verifies the sketch using the previously configured board. This implies that the code sees that the board doesn't exist and then ignores it, instead of showing an error message.

When the format is incorrect (e.g. `--board foo`), the package does not exist (e.g.  `--board foo:bar:baz`) or the architecture does not exist (e.g. `--board arduino:foo:bar`), an error is shown as expected.

**Comment by ffissore** [comment]
Fixed. Thanks!
