### ISSUE TITLE
Why not update official Arduino SD library with newest Geiman's one?

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3428]
Some parts of official Arduino SD library (https://github.com/arduino/Arduino/tree/master/libraries/SD/src) are based in an old version of Greiman's one (https://github.com/greiman/SdFat). The newest versions of the latter has some interesting improvements, as support to long file names, use of multiple cards, etc. I think it could be worthy to valorate if these changes could be merged.
Thanks.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#6
