### ISSUE TITLE
Add two libraries to library manager system

### ISSUE THREAD

**Issue by tdicola** [arduino/Arduino#3429]
Here are a couple libraries to add to the library manager:
- Adafruit_BluefruitLE_nRF51: https://github.com/adafruit/Adafruit_BluefruitLE_nRF51
- Adafruit_UNTZtrument: https://github.com/adafruit/Adafruit_UNTZtrument

They should be all ready to go with a tagged release and library.properties file.  Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
