### ISSUE TITLE
Support of ISO8859_8  [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#343]
This is [Issue 343](http://code.google.com/p/arduino/issues/detail?id=343) moved from a Google Code project.
Added by 2010-09-03T16:15:57.000Z by [danpeleg1](http://code.google.com/u/danpeleg1/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

**What change would like to see?**

I whould like to have a support of ISO8859_8 encoding, so the compiler will suppot hebrew charecters.

**Why?**

Lots of companys in israel works with the arduino and alot of them whould like to have a support with hebrew on Serial.println(); and with LCD display and more :)

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

I dont know ;)

**Comment by facchinm** [comment]
Should be solved now since both the serial terminal and the editor are UTF8 compliant.
