### ISSUE TITLE
Just FYI - User feedback is not wanted on Arduino.cc forums. 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#3443]
Since few of my recent comments on 1.6.6 behavior never got posted on Arduino.cc forum I presume the administrators  do not care nor want users feedback. 
Great, I can use my time elsewhere.

**Comment by Chris--A** [comment]
You are a user who has provided feedback.
What are you requesting with regards to the Arduino.cc forum?
This is the issue tracker for the IDE, posting in the forums may allow issues to go unnoticed and disappear from view.
