### ISSUE TITLE
Software allows a file to be created with the same name as the sketch it's in

### ISSUE THREAD

**Issue by praxiq** [arduino/Arduino#3452]
My environment: Arduino 1.6.5 on Mac OS 10.10.3 with an HFS+ drive, which is (by default) case-preserving but NOT case-sensitive.

Steps: 
1. Create a sketch called "Foo".
2. Try to create a tab called "Foo.cpp". Arduino complains that this isn't allowed. 
3. Create a tab called "foo.cpp" (notice the different capitalization). Expected behavior: Arduino complains again. Actual behavior: Arduino creates the file.
4. Hit "Verify." Arduino complains about "undefined reference to `setup'" and so on.

The error message has nothing to do with the actual problem, and if you google that error message you don't find anything relevant, so this could be frustrating for Arduino newbies who don't know how to troubleshoot it.

**Comment by per1234** [comment]
This seems to no longer be an issue. I can reproduce the issue with Arduino IDE 1.6.5-r5 (didn't try other versions) but with 1.8.3 (on Windows 7 64 bit) the IDE allows me to create Foo.cpp and the sketch compiles.

I'm closing as solved. If anyone can still reproduce the issue with the latest IDE version please comment and I'll reopen the issue.
