### ISSUE TITLE
Tie together the port, board and sketch.

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#3459]
Hello,
I wish that in a sketch be able to specify
##Board = "Arduino Uno"
##Port = "COM13"
or in any other way tie together the port, board and sketch.
/Sincerely BG

**Comment by matthijskooijman** [comment]
Thanks for the suggestion. However, this was already reported in #3228, so I'm closing this issue as a duplicate.

**Comment by per1234** [comment]
Duplicate of #1481
