### ISSUE TITLE
Adding support for AVR assembly

### ISSUE THREAD

**Issue by PopeLevi** [arduino/Arduino#3464]
Not an urgent issue, but I would quite like a feature in the IDE which allows the editing and compiling/uploading of AVR assembly files. Right now, the IDE seems somewhat restrictive as it only supports C++. Thanks :)

**Comment by matthijskooijman** [comment]
This is already supported, just add a new .S file to your project, which will be compiled as expected.

I'll close this issue, feel free to reopen if it isn't working for you.

**Comment by PopeLevi** [comment]
Oh wow. Sorry, I just realised I am running version 1.0.5. Oops :/
