### ISSUE TITLE
Change the colour of PREPROCESSOR words (Suggestion)

### ISSUE THREAD

**Issue by ReeceM** [arduino/Arduino#3480]
I was wondering if it would be okay to change the colour of preprocessors to the way C++ or othe IDEs colour them eg.
```C++
#define xyz
#include <xyz.h>
```

I thought this would be better as it makes them more distinguishable from other things as the straight black colour to them just seems ugly and it looks like other code when it is mixed up around other variables(although you wouldn't have stuff clumped together):

![2015-07-08 14_07_13-sketch_jul08a _ arduino 1 6 6 hourly build 2015_07_07 09_41](https://cloud.githubusercontent.com/assets/2767904/8569721/a7f45f82-257a-11e5-8104-80d8a12b4861.png)

Compared to this:
![2015-07-08 14_04_11-sketch_jul08a _ arduino 1 6 6 hourly build 2015_07_07 09_41](https://cloud.githubusercontent.com/assets/2767904/8569738/cfda4066-257a-11e5-9044-5a75aa9b157b.png)

I edited the `theme.xml` `PREPROCESSOR` style token and put a new value in for fg, very simple though.

```xml
<style token="PREPROCESSOR" fg="9a4e00" bold="false"/>
```

A link to the [color charts.](http://www.color-hex.com/color/9a4e00)

**Comment by 00alis** [comment]
Good catch @ReeceM!

#define and #include should be green because they are part of the Structure category, as you can see in the Language Reference page https://www.arduino.cc/en/Reference/HomePage

We can make this change for the next release! Thanks for your feedback!

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by ReeceM** [comment]
Cool, I'm glad it was of use to point it out and help, its bothered me since I noticed it. 

I did it brown as I liked the look N++ gives for C++ code style.

**Comment by 00alis** [comment]
Thank you both!! :)
