### ISSUE TITLE
Earlier sketch opens at start of new IDE

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#3482]
(1) I start the IDE by double clicking on the EXE file
(2) Then I open a previously saved sketch. [File] - [Open]
then save the file with the [File] - [Save]
If I start a new IDE opens the sketch that was saved in the IDE (2) not the standard empty.

I run on W7 pro 64-bit. sp1, Arduino-1.6.6-nightly-windows_2015-07-07

**Comment by ffissore** [comment]
Every time the IDE opens a sketch, it saves it into a list of "open sketches". If you open another instance of the IDE, it will read that list and open those sketches. It behaves as you added a 3rd step "close the IDE with File > Quit"
