### ISSUE TITLE
Incorrect cleaning of servo_allocated_mask in Servo.c::Teensy 3.x implementation

### ISSUE THREAD

**Issue by pramilo** [arduino/Arduino#3486]
Hi

I'm not entirely sure this code comes from Arduino or Paul Stoffregen. If it's not on your plate, please close it and let me know in order to forward it.

Using Arduino 1.0.6 with Teensyduino:
The Servo.c file includes specific code (isolated by an #ifdef) for performing the PWM emulation in Teensy 3.x using a PDB.

- The "servo_allocated_mask" bit is flipped on the constructor function.
- Yet it is cleared on the "detach()" procedure which can lead to a state where the class is actively being used but it is not registered in the "allocated" mask.

Reproducing the problem:
1) create an instance of the class,
2) attach() a servo
(by now servo_allocated_mask is set correctly)
3) detach() the servo (at this time servo_allocated_mask is cleared)

4) attach() a new servo reusing the same class instance (for example on a different pin)
By now, servo_allocated_mask is in a wrong state; it is not set for this class instance because it was cleared on detach() yet it hasn't been restored when I attach'ed() the new pin.

Proposed:
Either set and clear the servo_allocated_mask on class construction/destructor
OR set and clear the servo_allocated_mask on attach() and detach() 
for proper symmetric behavior

Thank you

**Comment by PaulStoffregen** [comment]
Opps, that's my bug, not Arduino's!

I've set up a repository here: https://github.com/PaulStoffregen/Servo

Please post this bug there.
