### ISSUE TITLE
RS232 Tutorial defines halfBit9600Delay incorrectly

### ISSUE THREAD

**Issue by jondea** [arduino/Arduino#3487]
On line 7 and 8 of the example code for RS232 connector, we have

> #define bit9600Delay 100  
> #define halfBit9600Delay 500

I may be misunderstanding, but shouldn't halfBit9600Delay be 50 if bit9600Delay is 100. Also, using 50 works in my project, and using 500 produces unexpected outputs.

**Comment by facchinm** [comment]
Hi @jondea ,

where did you find that piece of code? It doesn't seem to be shipped with the IDE

**Comment by jondea** [comment]
I may have posted this in the wrong place, I apologise if so, but it's on the website

https://www.arduino.cc/en/Tutorial/ArduinoSoftwareRS232

**Comment by agdl** [comment]
@jondea done thank you!
