### ISSUE TITLE
Add search in the IDE right click context menu?

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#3489]
Hey,
 Can one imagine adding search in the IDE right click context menu?
 / Sincerely BG

**Comment by ffissore** [comment]
Search for what and where?

**Comment by bgma** [comment]
Same as Ctrl-F

**Comment by ffissore** [comment]
Ah ok. Then no, we are not going to add it. It's not a common UI pattern and adds yet-another-entry in the already crowded context menu

**Comment by bgma** [comment]
it was sad
