### ISSUE TITLE
Learning/Examples/Fade typo

### ISSUE THREAD

**Issue by tvilberg** [arduino/Arduino#3491]
"If brightness is at either extreme of its value (either 0 or 255), then fadeAmount is changed to its negative. In other words, if fadeAmount is 5, then it is set to -5. If it's 55, then it's set to 5. The next time through the loop, this change causes brightness to change direction as well."

I think it should change to -55, not 5.

**Comment by ffissore** [comment]
This is the page https://www.arduino.cc/en/tutorial/fade

**Comment by agdl** [comment]
@tvilberg actually the 55 should be a -5 however the new revision will be online soon. Thank you!

**Comment by agdl** [comment]
It will be online next week because other changes are needed. In any case I'm closing this!
