### ISSUE TITLE
Request to add SparkFun ZX Distance and Gesture Sensor Arduino Library to library package manager

### ISSUE THREAD

**Issue by ShawnHymel** [arduino/Arduino#3494]
Repo is here: https://github.com/sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library

Most recent tag is here: https://github.com/sparkfun/SparkFun_ZX_Distance_and_Gesture_Sensor_Arduino_Library/tree/V_1.0.2

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
