### ISSUE TITLE
[Library Manager] New additions.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#3497]
Please add two of my libraries to the manager list:
https://github.com/Chris--A/BitBool
https://github.com/Chris--A/SmallSetup

**Comment by Chris--A** [comment]
Also, a quick question.

If I have a library in testing, will version tags like `0.0.5` be valid?

**Comment by ffissore** [comment]
Added. Thanks!
Tags can be freely named, it's version in library.properties that matter. Yes, 0.0.5 is a valid version according to http://semver.org/
