### ISSUE TITLE
[Website] Arduino Playground sidebar edits

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3506]
Some suggested edits for the Playground sidebar. I don't think there is any way for me to make these edits so I am posting them here:

1. Change **Arduino on other Atmel Chips** to **Arduino on other Chips**
1. Change **Suggestions & Bugs** link from the [Google Code issue tracker](http://code.google.com/p/arduino/issues/list) to the [GitHub issue tracker](https://github.com/arduino/Arduino/issues)
1. **PARTICIPATE** section:
  1. Change ~~**PARTICIPATE**~~ **Partecipate** to **Participate**
  1. ~~Remove **Suggestions** - this already has a sidebar item(**Suggestions & Bugs**)~~
  1. ~~Remove **Cookbook (addons)**~~
  1. ~~Remove **Drone with Arduino** - I will add this link to the **Exhibition** section once it is removed from the sidebar.~~
  1. ~~Remove **Thermostat with Arduino** - I will add this link to the **Exhibition** section once it is removed from the sidebar.~~

I believe the page that needs to be edited is http://playground.arduino.cc/Site/SideBar but it has a different password from the standard one.

EDIT: I have struck out all the items that are completed.

**Comment by q2dg** [comment]
I know it's an utopia, but if someone had the time to erase (very) deprecated and/or incorrect content, it would be perfect.

**Comment by per1234** [comment]
@q2dg if you see anything that needs updating or correction feel free to do so. If a page is completely obsolete then you can delete it. The playground is a community project, it's as good as we make it. As of yesterday you don't need to email the webmaster for a password to edit anymore.

**Comment by q2dg** [comment]
@perf1234 Ooh, I didn't know now it's possible to edit directly without asking. Thanks. Sorry for not be able to answer your question.

**Comment by q2dg** [comment]
Ei!!! Original issue hasn't been resolved! 
Don't close it without any explanation, please!

**Comment by per1234** [comment]
@mastrolinux why did you close this issue?

**Comment by mastrolinux** [comment]
Because everyone can do that and Playground is not part of the Arduino IDE. It is best to put this info and discussion in the forum in the "website and forum" section. Thanks.

**Comment by per1234** [comment]
As I say in the issue, that page has a different password so no everyone can't edit the sidebar. I'm guessing only an admin can do this specific edit. Because of this it seemed more appropriate to put it here in the issue tracker as admins probably don't read every post in the "website and forum" section of the forum.

**Comment by per1234** [comment]
It's been 2 weeks since I posted this issue on the forum and no response. @mastrolinux would you please take another look at this issue. I understand that the content of the Playground is the responsibility of the community, but it seems like it's reasonable to expect the Arduino website team to consider making obvious corrections of the Playground infrastructure that can't be edited by the community.

**Comment by per1234** [comment]
@ffissore can I ask you a big favor to look at this issue and consider either reopening it, suggesting an appropriate place for me to submit it if this is not the right place for it, or telling me how I can make these changes myself if that's indeed possible. I believe some of these suggestions are obvious and simple improvements on a very important part of the Playground.

**Comment by mastrolinux** [comment]
Fixed, closing issue. Thanks a lot.

**Comment by per1234** [comment]
@mastrolinux thanks so much for working on this. A couple things though:
>- Change Arduino on other Atmel Chips to Arduino on other Chips

This change wasn't made.
>- Change Suggestions & Bugs link from the Google Code issue tracker to the GitHub issue tracker

This change wasn't made(the link should be changed to https://github.com/arduino/Arduino/issues).
>- Change PARTICIPATE to Participate

There's a typo, you wrote "Partecipate".

**Comment by per1234** [comment]
@mastrolinux please read my last comment.

**Comment by per1234** [comment]
@mastrolinux please... This is a 2 minute job that has been dragged out over 2.5 months.

**Comment by per1234** [comment]
@agdl would you mind taking a look at this issue and consider reopening it? Thanks

**Comment by matthijskooijman** [comment]
@mastrolinux, could fix the last few issues reported by @per1234? Or perhaps @agdl can?

**Comment by mastrolinux** [comment]
Ok I think I fixed all of those. Can you please check and reopen if necessary?

Thank you

**Comment by per1234** [comment]
Looks good. Thanks!

**Comment by alextaujenis** [comment]
Thanks!
