### ISSUE TITLE
[Library manager] Add Keypad library, please

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3507]
It's hosted in http://playground.arduino.cc/Code/Keypad , but unfortunately author is missing (and library hasn't been updated to follow manager guidelines).

**Comment by facchinm** [comment]
Hi @q2dg , I don't believe we will add this to the libraries maintained by Arduino, however being the code GPL you can always fork it, fix the library manager compatibility issues, submit a request for inclusion by yourself and we'll be glad to include it :wink:

**Comment by Chris--A** [comment]
I have one here we can use. https://github.com/Chris--A/Keypad

I'm just going to update it for the new 1.5 specification first. Older IDE's can use the playground link.

**Comment by facchinm** [comment]
:+1:

**Comment by Chris--A** [comment]
Ok, it looks good to go!

**Comment by q2dg** [comment]
Yeah, thanks!!

**Comment by matthijskooijman** [comment]
@Chris--A, perhaps you should add a notice to the playground page, pointing people to your github and the library manager (probably best after it is added to the library manager, of course)?

**Comment by Chris--A** [comment]
Yes, once everything is rolling.

**Comment by cmaglie** [comment]
@Chris--A 
the library is still missing tags: https://github.com/Chris--A/Keypad/releases
please add one so I can publish into the lib manager

**Comment by Chris--A** [comment]
Its added now, sorry.

**Comment by cmaglie** [comment]
No problem, it should be online now!
