### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Wackerbarth** [arduino/Arduino#3508]
I would like to see the Arduino IDE adhere to the versioning expectations that violate "backward compatibility".

In particular, I have some "platform.local.txt" entries which worked well on IDE 1.6.3. (and .4 and .5)
However, when I upgraded to the current (hourly) IDE, they failed because the path to the source files has changed ( .../sketch/ .. was added to the file path)

IMHO, this should have caused a jump to IDE 1.7.x since the previous 1.6.x configurations no longer work.

**Comment by facchinm** [comment]
Hi @Wackerbarth , sorry for the inconvenience, I don't believe it was intentional. However we'll keep track of this issue in #3510 and fix it as soon as @ffissore is back.
