### ISSUE TITLE
Comment/Uncomment broken

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#3513]
Steps to reproduce:
* Open a new sketch,  it has a `// put your setup code here, to run once:`line
* Put the cursor into that line
* Select "Comment/Uncomment" from the menu

Expected result:
`put your setup code here, to run once:`
Actual result:
`//  // put your setup code here, to run once:`

Also it would be nice if Comment/Uncomment and Auto Format would work nicely together. Right now, using Comment/Uncomment, then Auto Format, and then Comment/Uncomment again breaks it.

I am using <img width="206" alt="bildschirmfoto 2015-07-12 um 12 52 37" src="https://cloud.githubusercontent.com/assets/2480569/8637521/eb5693f4-2894-11e5-9ef0-cac353682a3b.png"> on OS X 10.9.

**Comment by per1234** [comment]
It only happens with indented comments.

**Comment by probonopd** [comment]
Correct. It also happens that Auto Format indents comments.

**Comment by ffissore** [comment]
Fixed. Autoformat keeps on formatting comments. This can be easily disabled editing file formatter.conf and saving a copy into your own Arduino15 folder
