### ISSUE TITLE
Spelling in the menus

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#3514]
It would be nice if spelling in the menus could be more consistent. We have "Comment/Uncomment" with no spaces around the "/" but "Verify / Compile". Please remove the extra spaces. This is also the case in other languages, e.g., German. The Apple standard for "/" in the menus is without spaces.

I am using <img width="206" alt="bildschirmfoto 2015-07-12 um 12 52 37" src="https://cloud.githubusercontent.com/assets/2480569/8637521/eb5693f4-2894-11e5-9ef0-cac353682a3b.png"> on OS X 10.9.

**Comment by facchinm** [comment]
@00alis

**Comment by 00alis** [comment]
let's do it, consistency it is always better :)

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by probonopd** [comment]
Thank you!
