### ISSUE TITLE
Add Library - Quirkbot

### ISSUE THREAD

**Issue by paulobarcelos** [arduino/Arduino#3516]
Please add the Quirkbot library to the public index. It conforms to the 1.5 format.
https://github.com/Quirkbot/QuirkbotArduinoLibrary

**Comment by facchinm** [comment]
Hi @paulobarcelos, @ffissore is in charge for library manager so expect some delays in integration. Don't worry though, it will be added as soon as he is back!

**Comment by paulobarcelos** [comment]
Great! Looking forward to it.

Are there any plans on making this process automated? I can imagine that manually going through these libraries submissions is very time consuming...

**Comment by facchinm** [comment]
Testing the conformity of a library with the specifications can be almost fully automated, however there are still corner cases which would need human intervention, so it's unlikely to see a fully automated process in a short time :wink:

**Comment by cmaglie** [comment]
The library has been added! Thanks!
