### ISSUE TITLE
Add Library - Dallas Temperature

### ISSUE THREAD

**Issue by PaoloP74** [arduino/Arduino#3517]
Please add the Dallas Temperature library to the public index.
https://github.com/milesburton/Arduino-Temperature-Control-Library

**Comment by facchinm** [comment]
Hi @PaoloP74 , @ffissore is in charge for library manager so expect some delays in integration. Don't worry though, it will be added as soon as he is back!

**Comment by PaoloP74** [comment]
Ok.

**Comment by cmaglie** [comment]
@PaoloP74 you must tag a release on the repository to get it published:

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

also a `library.properties` file is missing.

**Comment by cmaglie** [comment]
The library has been added.
Thanks!

**Comment by PaoloP74** [comment]
Latest release is 3.7.5, but Library Manager install version 3.7.2. Bug?

**Comment by ffissore** [comment]
I see 3.7.5 listed in http://downloads.arduino.cc/libraries/library_index.json

**Comment by ffissore** [comment]
Please open a new issue if you experience a bug. Comments to closed issues may get lost (too many emails)
