### ISSUE TITLE
IDE removes the TAB!

### ISSUE THREAD

**Issue by bgma** [arduino/Arduino#3520]
Hey,

I try to put in 2 TAB and } one after the other in a line.
2 TAB is going well but when I press } it removes 1 TAB away.

I know it is missing 1 { but I will in any case be able to format my code without the IDE is doing something on it's own.
In the run on W7 Pro 64-bit. sp1, Arduino-1.6.6-nightly-windows_2015-07-10 12:34

/Best regards BG

**Comment by facchinm** [comment]
Hi @bgma , the new Editor contains some "automation" which has been considered helpful for a lot of users (like parenthesis matching). However, as soon as @ffissore is back, he'll be able to give you a proper answer :wink:

**Comment by ffissore** [comment]
@bgma that happens because the editor is aligning the closing curly brace to the one you opened above. Either open the second curly brace or first type the closing one, then indent it.

**Comment by bgma** [comment]
is it possible to turn off this BUG? or must i use notepad to get rid of it?

**Comment by ffissore** [comment]
I'm sorry, it's not possible
