### ISSUE TITLE
ArduinoToBreadboard tutorial hardware configuration archive is not compatible with 1.6.5

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3521]
The hardware configuration archive [Breadboard1-5-x.zip](https://www.arduino.cc/en/uploads/Tutorial/Breadboard1-5-x.zip) linked in the **Minimal Circuit** section of www.arduino.cc/en/Tutorial/ArduinoToBreadboard doesn't work with Arduino IDE 1.6.5r2 etc.

The following changes need to be made to the archive:
- Add `atmega328bb.bootloader.tool=arduino:avrdude` to **boards.txt**
- Add `atmega328bb.upload.tool=arduino:avrdude`
- Change `atmega328bb.upload.protocol=stk500` to `atmega328bb.upload.protocol=arduino`
- Remove `atmega328bb.bootloader.path=arduino:atmega`
- It doesn't include a bootloader file so either:
  - https://github.com/arduino/Arduino/issues/2656 needs to be fixed so it can use the arduino core bootloader file and update the bootloader.file line to: `atmega328bb.bootloader.file=arduino:atmega/ATmegaBOOT_168_atmega328_pro_8MHz.hex`
  - **or** add the bootloader file **ATmegaBOOT_168_atmega328_pro_8MHz.hex** to the bootloaders subfolder of the archive.

**Comment by agdl** [comment]
@per1234 there is a new archive now that works with 1.6.5. I included the bootloader file in the archive. If it is good for you please close this issue!

**Comment by per1234** [comment]
@agdl the url for breadboard-1.6-x.zip (https://www.arduino.cc/en/6-x/Zip?action=edit) on the tutorial page doesn't work

**Comment by agdl** [comment]
i just noticed it. Try in a minute. updated it

**Comment by per1234** [comment]
Still doesn't work: https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard?action=upload&upname=breadboard-1.6-x.zip

**Comment by agdl** [comment]
try to refresh the page cleaning the cache please

**Comment by agdl** [comment]
ok it works for sre now. It is online sorry about this

**Comment by per1234** [comment]
Works great, thank you!
