### ISSUE TITLE
Add Library - iobeam

### ISSUE THREAD

**Issue by RobAtticus** [arduino/Arduino#3522]
Please add the iobeam library:

https://github.com/iobeam/iobeam-client-embedded

Thanks

**Comment by facchinm** [comment]
Thanks @RobAtticus , your library will be integrated as soon as @ffissore is back!

**Comment by cmaglie** [comment]
@RobAtticus 

the revision tagged as 0.1.0 doesn't have a `library.properties` (but instead it has a `library.properties.notyet`): https://github.com/iobeam/iobeam-client-embedded/tree/v0.1.0

Please re-tag the correct git revision.

**Comment by RobAtticus** [comment]
Sorry about that, fixed.

**Comment by cmaglie** [comment]
Done.

**Comment by RobAtticus** [comment]
Thanks!
