### ISSUE TITLE
[Library Manager] Please Add U8glib_Arduino

### ISSUE THREAD

**Issue by olikraus** [arduino/Arduino#3525]
Please add U8glib_Arduino to the Library Manager:

https://github.com/olikraus/U8glib_Arduino

U8glib is a graphics library for monochrome graphics LCDs and OLEDs.
U8glib is dicussed here: http://forum.arduino.cc/index.php?topic=91395.0

Thanks, Oliver

**Comment by facchinm** [comment]
Hi Oliver, your library will be integrated as soon as @ffissore is back, so expect some delay but don't worry!

**Comment by olikraus** [comment]
No problem. Thanks for the feedback.

**Comment by cmaglie** [comment]
@olikraus the library has been added. Thanks!
