### ISSUE TITLE
Library Manager not updating library

### ISSUE THREAD

**Issue by fenichelar** [arduino/Arduino#3529]
I have pushed 2 releases that have not been picked up by the library manager. The first one was over 36 hours ago. Is there a problem with the library manager or my repository? Thanks.

https://github.com/fenichelar/Pin/releases

**Comment by facchinm** [comment]
Hi @fenichelar , your latest releases contain a broken symlink (`extra/documentation/Documentation.html`), thus they are not passing the compliance test. Please remove that file, tag again the library and everything will solve automagically :smile:

**Comment by fenichelar** [comment]
Thank you.
