### ISSUE TITLE
Add INPUT_PULLDOWN to keywords.txt

### ISSUE THREAD

**Issue by MarkusLange** [arduino/Arduino#3534]
INPUT_PULLDOWN LITERAL2 Constants RESERVED_WORD_2

is missing INPUT_PULLDOWN has no color

**Comment by facchinm** [comment]
Hi @MarkusLange  , indeed `INPUT_PULLDOWN` is not a valid keyword as it's not declared anywhere in the IDE :smile: 
Where did you find it?

**Comment by Chris--A** [comment]
A custom library maybe?

**Comment by facchinm** [comment]
I also thought it was in a custom library, but if the code is declared inside a custom core you can't specify a custom keyboard.txt (issue #755). Leaving open for reference

**Comment by MarkusLange** [comment]
Hi Chris, hi facchinm,

I found in ...\samd\cores\arduino\wiring_digital.c from the new ZERO Board, the ZERO has of pull-up and pull-down resistors on the pins.

**Comment by facchinm** [comment]
Well, this is a bit awkward :grin: I didn't grep inside Zero core actually. 
We can't add the keyword platform-wide (if we don't provide an alias of `INPUT` as `INPUT_PULLDOWN` of course) but I'll push to solve #755 and then we'll add the keyword only to Zero core.
Thank you very much Markus!

**Comment by MarkusLange** [comment]
Not for that. I tripped over it because of a similar issue (https://forum.pjrc.com/threads/29140-Bug-in-teensy-installer-for-arduino-1-6-5-r2) and my messing around on the Onewire lib to get the Zero on duty, works so far, (http://forum.arduino.cc/index.php?topic=331220.msg2297555#msg2297555) but I don't get the basic operations, direct register access working.

**Comment by PaulStoffregen** [comment]
I have long wanted this #755 feature for Teensy.  Of course, not enough to dig into the IDE source to implement it....

Until recently, there's been relatively little activity in the global keywords.txt file, so I've just installed a patched copy.  Obviously that's not so good.

Ideally, the keywords.txt from core libraries could apply in addition to the global one, much like how the keyboard.txt from libraries do.  All that's needed is more hours in the day for someone to actually implement this in the IDE.....
