### ISSUE TITLE
Serial Monitor view moves on full buffer

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3538]
I am analyzing music, so I print a lot of vertical bars to the Serial monitor.

After a while of listening the Serial buffer of the IDE gets full and discards old data, which is fine.
The problem is, if you pause (disable autoscroll) the serial monitor, it will also move the view every x seconds. Which is totally distracting me. I have to completely restart my program in oder to empty the buffer.

It would be better to move the view, with the discarded bytes as well, so you have no visible difference.

**Comment by per1234** [comment]
Now tracked at https://github.com/arduino/arduino-ide/issues/1250
