### ISSUE TITLE
Multiple sketches don't show in taskbar (Ubuntu - Karmic Koala) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#354]
This is [Issue 354](http://code.google.com/p/arduino/issues/detail?id=354) moved from a Google Code project.
Added by 2010-09-21T11:23:18.000Z by [damonz1...@gmail.com](http://code.google.com/u/114736351980271174276/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE, OpSys-Linux

### Original description

**What steps will reproduce the problem?**
1.Open more than two sketches
2.Have to use alt-tab to switch windows to find IDE
**3.**

**What is the expected output? What do you see instead?**

Sometimes the IDE doesn't show at all so you have to alt-tab when switching between sketches.  This can become pain full when copying and pasting between sketches

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Ubuntu - Karmic Koala, Arduino 0019, Mega

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Closing as invalid for lack of feedback on the original issue
