### ISSUE TITLE
Hourly Build version information at download page

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3540]
I wanted to download the new hourly build, because a PR got merged.

But where do I see how old the build is?
https://www.arduino.cc/en/Main/Software

A Timestamp and the number of the last commit should be added as information?

**Comment by ffissore** [comment]
The hourly box displays
```
LAST UPDATE
21 July 2015 17:15:16 GMT
```

**Comment by NicoHood** [comment]
I did not see it because I had scripts blocked. If there is a way to do it without a script that'd be nice. Or just a not "activate scripts to see last update time"
