### ISSUE TITLE
unable to recognize the port

### ISSUE THREAD

**Issue by Manisha-Manimaran** [arduino/Arduino#3545]
after making a connection with Intel galileo2 board ..my lap is not showing port information....can i know what will be the reason???
![port](https://cloud.githubusercontent.com/assets/12667908/8761637/ae2665fc-2d78-11e5-8c56-79942bbd8a9b.png)

**Comment by Avamander** [comment]
Have you tried the latest hourly build?

**Comment by Manisha-Manimaran** [comment]
.I have tried but,I'm not getting the port on the tools bar.is there any other possiblities ??

**Comment by Avamander** [comment]
Have you installed all the software the installation manual told you?

**Comment by Manisha-Manimaran** [comment]
yes

**Comment by facchinm** [comment]
Have you tried installing the specific Galileo drivers? You can find them [here] (https://downloadcenter.intel.com/downloads/eula/24748/Intel-Galileo-Firmware-and-Drivers-1-0-4?httpDown=http%3A%2F%2Fdownloadmirror.intel.com%2F24748%2Feng%2FIntelGalileoWindowsSerialDrivers.zip)

**Comment by ffissore** [comment]
@Manisha-Manimaran any news?
