### ISSUE TITLE
linux 32bit avrdude should be static

### ISSUE THREAD

**Issue by xxxajk** [arduino/Arduino#3548]
/opt/Arduino/hardware/tools/avr/bin/avrdude: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

avrdude should really be compiled static in order to avoid this sort of nonsense.

**Comment by facchinm** [comment]
Hi @xxxajk, did you update `libncurses` recently? However you are right, the bundled 32bit package only contains `libusb` library binaries. Would you mind moving the issue from here to https://github.com/arduino/toolchain-avr/issues

**Comment by xxxajk** [comment]
A symlink to my current library works. Point is that you should not have to do this. 
If you link statically, you ensure that the program will work whether-or-not someone has any particular library installed, at the cost of a slightly less larger distributed binary.

**Comment by xxxajk** [comment]
Oh yeah, and I do not mind moving the issue.
