### ISSUE TITLE
Went to down load new arduino 1.6.5 it uninstalled old arduino, will not reload on computer

### ISSUE THREAD

**Issue by jaws180** [arduino/Arduino#3552]
i went to install new arduino 1.6.5 on computer, win 7. i cant get it to reload  or even get it to work once i do get it to down load, can you help? when it opens it gives me nothing an closes.

**Comment by Chris--A** [comment]
There is another app in the Arduino folder called *arduino_debug.exe*.

If you can run it using the command line, it'll load the IDE and spit out debugging information you can paste here.
