### ISSUE TITLE
Window menu is missing on the Mac

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#3557]
On the Mac, (almost) every application has a "Window" menu, where you can see and switch between all open windows of that application.

![mac-osx-window-zoom](https://cloud.githubusercontent.com/assets/2480569/8781783/6cf330e8-2f11-11e5-8c8a-2d2dacc53723.jpg)

It would be nice if Arduino cold have this menu, too.

**Comment by ffissore** [comment]
Duplicate of #234

**Comment by lmihalkovic** [comment]
simple first step

<img width="418" alt="screen shot 2015-11-26 at 10 35 43 am" src="https://cloud.githubusercontent.com/assets/1318077/11419866/8ba8a9c2-942a-11e5-8876-2bcb5bc69f75.png">

**Comment by probonopd** [comment]
Great @lmihalkovic - did you send a pull request?
