### ISSUE TITLE
BitwiseCompoundAnd incorrect bit formatting (missing a 1)

### ISSUE THREAD

**Issue by thantik** [arduino/Arduino#3558]
At the URL https://www.arduino.cc/en/Reference/BitwiseCompoundAnd

The code at the bottom of the page, just above the "See Also" is

    myByte =  10101010;
    
    myByte &= B1111100 == B10101000;

But the B1111100 is missing a 1 on the left side of the value. It should be:

    myByte =  10101010;
    
    myByte &= B11111100 == B10101000;

**Comment by mikaelpatel** [comment]
BW "myByte =  10101010;" should be "myByte =  B10101010;" if you are correcting things. Cheers!

**Comment by agdl** [comment]
corrected both thanks!
