### ISSUE TITLE
Remove The Not Working Library 

### ISSUE THREAD

**Issue by KrrishnaShah** [arduino/Arduino#3559]
I've got a not working library installed. It shows up every time I open the Arduino App. It has made my Arduino program to work slow and annoying that it always keeps pop-up window showing :

"    The library "SparkFun_APDS9960_RGB_&_Gesture_Sensor" cannot be used.
Library names must contain only basic letters and numbers.
(ASCII only and no spaces, and it cannot start with a number)     "

**Comment by ToniCorinne** [comment]
We fixed the library name on the SparkFun repo, so once the Arduino library manager scans for updates, that should be fixed (I hope).

**Comment by KrrishnaShah** [comment]
thankyou ..
