### ISSUE TITLE
Linux install package should contain script to create Dash item.

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#3566]
It would be much nicer if the Linux package also contained script to add Arduino IDE to the Dash menu.

**Comment by mschlenker** [comment]
I admit this. Upon first start a file `$HOME/.local/share/applications/arduino-1.6.5.desktop` might be created as a simple softlink to the not yet existing `arduino-1.6.5/arduino.desktop`. When updating the IDE and deleting old versions orphaned softlinks to old IDEs do not point to valid desktop files anymore and thus are ignored.

Should I change the startup script accordingly and add a desktop file?

**Comment by Avamander** [comment]
Maybe an additional script for those who do have the privileges, everything will continue to work the same way, but those who wish can get a shortcut to dash. (Also, why isn't Arduino package updated in the Ubuntu repos?)

**Comment by Avamander** [comment]
@ffissore I guess you aren't working on this :) ?

**Comment by NicoHood** [comment]
Isnt this fixed now?

**Comment by ffissore** [comment]
Indeed I'm not. See
https://groups.google.com/a/arduino.cc/forum/#!msg/developers/YJLX6AZHem4/kpsLef7XBAAJ

Avamander ha scritto il 13/03/2016 alle 20:00:
