### ISSUE TITLE
Arduino GSM 

### ISSUE THREAD

**Issue by Vijana** [arduino/Arduino#3571]
Hi I'm newer to arduino programming and working with arduino gsm module which is Aptinex LEON G100. I want to get AT command response to if conditions (ex. if(response == "OK") //do something,if(response == "ERROR") // do something)

**Comment by agdl** [comment]
@Vijana GitHub is inted for tracking issues. For questions like this please use the Arduino forum. Close this issue and move it to the forum!

**Comment by Vijana** [comment]
Thank you!
