### ISSUE TITLE
Library Manager inclusion request

### ISSUE THREAD

**Issue by ReefPOM** [arduino/Arduino#3575]
I have created a library, and believe it is formatted v1.5 appropriately for the Library Manager.   bitbucket.org/ReefPOM/ospom

**Comment by cmaglie** [comment]
@ReefPOM I'm sorry be we do not support bitbucket now, because the library manager use the Github's CDN to serve the .zip archives of the libraries.

I'm sorry to say that you must move your repo to github (or maybe just copy it if you want to keep it on bitbucket).

**Comment by ReefPOM** [comment]
Thank you,  I have moved it to GitHub:    https://github.com/ReefPOM/OSPOM

Once included, if I push version tag updates, they will be automatically updated on arduino.com (with a delay)?

**Comment by Chris--A** [comment]
The libraries are scanned once a day I'm pretty sure, so at the most 24 hours.

**Comment by cmaglie** [comment]
Done, thank you!

> The libraries are scanned once a day I'm pretty sure, so at the most 24 hours.

the libraries scan is done every hour so, even better, you'll get updates published within an hour.

**Comment by ReefPOM** [comment]
When should I expect to see it on 'playground.arduino.cc/Main/LibraryList'?  I don't mind waiting, I'm just new at this, and am thinking maybe I didn't do something correctly.

**Comment by facchinm** [comment]
Hi @ReefPOM , your library has been listed in the library manager (inside the IDE), not on the website; that page is in Playground so you can update it manually including your lib if you wish :smile: 

![2015-07-31-094945_805x458_scrot](https://cloud.githubusercontent.com/assets/8843437/9002998/50cbbef6-376a-11e5-8f4d-9fa1e94b437f.png)

**Comment by ReefPOM** [comment]
So Cool!  Thank you :-)
