### ISSUE TITLE
Library Manager inclusion request: elapsedMillis

### ISSUE THREAD

**Issue by pfeerick** [arduino/Arduino#3577]
Hi guys,

I believe my 'lil library is also 1.5 spec compliant, so here is my request for it's inclusion in the library manager list and exposure to the big bad world generally...

Please feel to yell and scream if I stuffed up somewhere...

https://github.com/pfeerick/elapsedMillis

Cheers,
Pete

**Comment by Testato** [comment]
+1

**Comment by cmaglie** [comment]
Done!
