### ISSUE TITLE
pin details

### ISSUE THREAD

**Issue by Manisha-Manimaran** [arduino/Arduino#3579]
in Intel Galileo gen2 ,which pin represents the following
1.XTAC1
2.ICP1
3.OC1A
4.AC0
5.INT
6.XCK

**Comment by facchinm** [comment]
Hi, I'm pretty sure that those pins are not exported to the Arduino headers. You'd better ask [Intel's support for makers] (http://www.intel.com/support/mailform/maker/emailsupport.htm) if you are looking for specific chip features.
Thanks
