### ISSUE TITLE
integer overflow during variable declaration

### ISSUE THREAD

**Issue by martincollett** [arduino/Arduino#3590]
I'm seeing any calculation in a variable declaration fail if the result is over 32000 (probably 32768?).

long a = (1000 * 32 );      //compiles OK
long b = (1000 * 33 );      //compiler warning: integer overflow in expression [-Woverflow]
long c = (1000.0 * 33 );  //compiles OK

Arduino 1.6.4

Regards, Martin Collett

**Comment by mikaelpatel** [comment]
@martincollett 
long b = (1000L * 33 );
Please check the C/C++ standard for expression calculation.

**Comment by martincollett** [comment]
Thanks Mikael, much appreciated - my error.

**Comment by matthijskooijman** [comment]
Yeah, this is sort of by design in the C/C++ language. Agreed that it's not terribly convenient, but it's not something Arduino can change.
