### ISSUE TITLE
Wrong Eagle file for Arduino Uno- R3 SMD

### ISSUE THREAD

**Issue by varnonga** [arduino/Arduino#3592]
I downloaded the Eagle file for the Arduino Uno- R3 SMD and that file was actually for the Arduino Uno - R3.

**Comment by mesqui** [comment]
very good tenkiu

**Comment by agdl** [comment]
@varnonga actually we are not supporting the UNO smd at the moment like you can easily understand from the new web page. However if you want the right files, please open a ticket using our customer care platform!
