### ISSUE TITLE
An Error Has Occurred

### ISSUE THREAD

**Issue by hamsafar** [arduino/Arduino#3595]
Hi
Excuse me why my account banned?!
Sorry hamsafar_a85, you are banned from using this forum!
This ban is not set to expire.

I did not know where I have said this issue....

**Comment by Chris--A** [comment]
I have left a message on your behalf here: http://forum.arduino.cc/index.php?topic=302710.msg2333911#msg2333911

You can close this issue, as this tracker is not for forum problems.
