### ISSUE TITLE
1.6.3: can't add library by manager, no internet connection (???), cant find USBhost class to include

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#3612]
I can't add  either  library by the manager (IDE 1.6.3) , 
says no internet connection (??? rubbish !!! ), 

can't find USBhost  class to include, 

nothing to find on https://www.arduino.cc/en/Reference/USBHost

can't compile
~~~
//   source: https://www.arduino.cc/en/Reference/KeyboardControllerConstructor   //


#include <KeyboardController.h>

// Initialize USB Controller
USBHost usb;

// Attach Keyboard controller to USB
KeyboardController keyboard(usb);

void setup(){
  Serial.begin(9600);
}

void loop(){
  usb.Task();
}

void keyPressed() {
  Serial.print("Pressed:  ");
  Serial.print(keyboard.getKey());
  Serial.println();
}
~~~

"
USB_keyb001.ino:7:32: fatal error: KeyboardController.h: No such file or directory
compilation terminated.
"

**Comment by ffissore** [comment]
It seems this is going to be solved by manually updating the lib. See #3622.

**Comment by VogonJeltz** [comment]
HELL, CAN'T YOU READ ???
I CAN'T UPDATE MANUALLY BECAAUSE THE LIBS CAN'T BE FOUND ANYWHERE!!!!!

WHERE THE FU** ARE  Scheduler.h and USBhost.h to be found to be installed manually ?????

PLEASE LEARN TO READ AND TO UNDERSTAND BEFORE YOU'RE CLOSING ISSUES !!!

**Comment by JASON33** [comment]
Same on mine says com is busy.raspberry. pi. New. Ima gonna loaded
perfect.ardiuno quality is down hilllllllll😞
