### ISSUE TITLE
Error in layout drawing for "Button" project

### ISSUE THREAD

**Issue by warry-williams** [arduino/Arduino#3616]
arduino-1.6.5-r2-windows\arduino-1.6.5-r2\examples\02.Digital\Button
This path links to some documentation for the beginner's project "Button".
The "layout picture shows the input as pin 2. The schematic and sketch language assign this to pin 12. Not a big deal, but it could throw a newbie for a loop.

**Comment by agdl** [comment]
@warry-williams i think you refer to these images https://www.arduino.cc/en/Tutorial/Button
In the page both the images and the sketch are consistent and use pin 2 so can you please link the wrong place?

**Comment by warry-williams** [comment]
Thank you for taking the time to help. I have been in electronics many years but never used bread boards before- I expect I had something plugged incorrectly.  


     On Tuesday, September 1, 2015 7:33 AM, Arturo Guadalupi <notifications@github.com> wrote:
   

 @warry-williams i think you refer to these images https://www.arduino.cc/en/Tutorial/Button
In the page both the images and the sketch are consistent and use pin 2 so can you please link the wrong place?—

**Comment by agdl** [comment]
@warry-williams it all is ok in the documentation, can you please close the issue?

**Comment by agdl** [comment]
@warry-williams I'm closing this. Reopen it if needed please.
