### ISSUE TITLE
How arduino IDE on mac understand where the arduino uno is connected

### ISSUE THREAD

**Issue by mitko9000** [arduino/Arduino#3618]
Hello all !

Can someone explain me how under MAC OS the Arduino IDE understand that the /dev/tty that is assigned to it it's actually a Arduino Uno board ?

Can someone show me that in the code where is it because I am unable to find it.

**Comment by ffissore** [comment]
Code is https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/macosx/SystemProfilerParser.java
Unit test is https://github.com/arduino/Arduino/blob/master/app/test/processing/app/macosx/SystemProfilerParserTest.java
