### ISSUE TITLE
UTFT_SdRaw library submitted for inclusion in library manager.

### ISSUE THREAD

**Issue by ghlawrence2000** [arduino/Arduino#3619]
Submitted for inclusion in library manager.

https://github.com/ghlawrence2000/UTFT_SdRaw/tree/V1.2.0

**Comment by ffissore** [comment]
Repo added but lib didn't go into the list because you did not make a release. Please double read the FAQ https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by ffissore** [comment]
Once properly tagged, the lib will be available within the hour

**Comment by ghlawrence2000** [comment]
Hello, I made a new realease V1.2.2 on git of the same library and 15 hours later it has still not appeared in library manager, is there anything else I need to do?
The new git release is here :- https://github.com/ghlawrence2000/UTFT_SdRaw/releases/tag/v1.2.2

Thanks,

Graham
