### ISSUE TITLE
where to find all the Arduino system  libs at 1 place (e.g., Scheduler, USB host)?

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#3622]
as online lib updating by the lib manager does not work on my cPCs:
how to update libraries offline by downloading a complete lib zip file and then c+p the desired libs manually to the libraries system folder ?
where can one find all the desired libs?
e.g., Scheduler, USBhost,...
there should be 1 place to find them all!

**Comment by ffissore** [comment]
This is the URL the IDE uses: http://downloads.arduino.cc/libraries/library_index.json
Look for the libs you need and their related zip files

**Comment by ffissore** [comment]
The FAQ contains the above link. You should give it a quick read: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
