### ISSUE TITLE
A bit of refactoring of the WiFi code

### ISSUE THREAD

**Issue by mladenb** [arduino/Arduino#3629]
Hi,

At this page: https://www.arduino.cc/en/Guide/ArduinoWiFiShield
there is a code example in the section named "Scan for available networks", which could be improved by a simple refactoring.
If we move the line "delay(10000);" to the bottom of the loop() method, we could get rid of the last three lines in the setup() method (because they are redundant now).

Hope this helps :)

Cheers!

**Comment by cmaglie** [comment]
I've fixed the example in the repository.

@agdl it should be automatically fixed in the tutorial page? I still see the old example.

**Comment by agdl** [comment]
@cmaglie the page was linked to a wrong place. It is ok now. Every mod will be automatically tracked.
