### ISSUE TITLE
Arduino Robot can't read example pictures and melodies from the SD-card

### ISSUE THREAD

**Issue by Zibedy** [arduino/Arduino#3642]
Hi guys! Have a problem with my robot. It's display do not draw BMP and play melodies with the code from Arduino Robot examples. With the help of TFT example from IDE I have tested display and discovered that it can read bmp-files from my card and draw images . So as we can see the card and display are not broken but Robot libraries don't work. What is the problem?

**Comment by Zibedy** [comment]
Guys please help!

**Comment by agdl** [comment]
@Zibedy the examples work, so it's a problem of your robot. Please send a ticket to support@arduino.cc to highlight this and search for something similar on forum.arduino.cc .
