### ISSUE TITLE
[DOC] Zero capabilities don't appear in https://www.arduino.cc/en/Reference/AttachInterrupt

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3643]
Thanks

**Comment by q2dg** [comment]
...and where it says "Leonardo", it should say "32u4 based (Yun, Micro, etc)", shouldn't?

**Comment by agdl** [comment]
@q2dg take a look now please!

**Comment by q2dg** [comment]
It looks great!
Maybe I'd replace *"Most Arduino boards have two external interrupts: numbers 0 (on digital pin 2) and 1 (on digital pin 3)."* by *"Arduino UNO board, for instance, has two external interrupts: numbers 0 (on digital pin 2) and 1 (on digital pin 3)."* or something similar, but all the rest is good!
I'll close the issue, ok?

**Comment by agdl** [comment]
@q2dg done thank you!
