### ISSUE TITLE
[DOC] Can Zero board use Audio library (https://www.arduino.cc/en/Reference/Audio)?

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3644]
I ask because it has a DAC too. If so, this page should be update accordingly

**Comment by q2dg** [comment]
Well, according to https://www.arduino.cc/en/Tutorial/SimpleAudioPlayerZero , the answer is yes. But reference page should clarify this

**Comment by agdl** [comment]
@q2dg as you can see from the bottom of the page, the zero has a dedicated audio library that actually is simpler compared with the due one. Can we close this issue?

**Comment by q2dg** [comment]
So...where is AudioZero in https://www.arduino.cc/en/Reference/Libraries?

**Comment by agdl** [comment]
@q2dg added

**Comment by q2dg** [comment]
Yeah! Thanks a lot again!
