### ISSUE TITLE
I18N & L10N for Library and Board Managers.

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#3646]
Main IDE is well I18Nized and L10Nized. 
But Library Manager and Board Manager are some lacked of I18N and L10N: title, menu items and  descriptions are not supported with local languages.

**Comment by ffissore** [comment]
Translations have been recently updated. Try the hourly build http://www.arduino.cc/en/Main/Software#hourly. Koren is almost complete https://www.transifex.com/mbanzi/arduino-ide-15/ but an additional review is always welcome

**Comment by Myriads** [comment]
![arduino_lm01](https://cloud.githubusercontent.com/assets/9634845/9167739/67f04a6a-3f90-11e5-9cbe-50c7f84f96a0.png)
![arduino_lm02](https://cloud.githubusercontent.com/assets/9634845/9167743/69efbe68-3f90-11e5-9e76-22ff4650f783.png)

I attached 2 pictures of Library Manager. 
Type and subject are almost English. And more bad things are that all items are described in English.

**Comment by ffissore** [comment]
Ah I see. Thanks

**Comment by ffissore** [comment]
Those labels are now translatable. Please join our community of translator at https://www.transifex.com/mbanzi/arduino-ide-15/ide-15/
