### ISSUE TITLE
library manager hourly job not running?

### ISSUE THREAD

**Issue by soundanalogous** [arduino/Arduino#3652]
I updated Firmata from v2.4.3 to v2.4.4 earlier in the day. However, the new version is not appearing in http://downloads.arduino.cc/libraries/library_index.json. I'm wondering if the hourly job is not running or perhaps it has been changed to run less frequently (it has been about 11 hours since I added the v2.4.4 tag).

**Comment by ffissore** [comment]
Jobs still fetches from our fork https://github.com/arduino-libraries/Firmata. I've just updated it and libs will be published asap. /ccing @cmaglie (which is having his summer break atm)
