### ISSUE TITLE
Serial monitor does not honor some characters

### ISSUE THREAD

**Issue by xxxajk** [arduino/Arduino#3654]
I'm not sure if these have been requested to be acted upon properly in the past or not, but I'm pretty sure somebody should have complained at some point in the past.

Notably, \r and \b are ignored.
```\r``` should simply return to the beginning of the line.
```\b``` should do a backspace, without a rubout.
These two are fairly important to make progress displays. I'm not asking for full cursor controls, but these two would be very helpful to have and shouldn't be a huge leap to implement, considering ```\t``` does work.

**Comment by ffissore** [comment]
IDE Serial monitor is not aware of control chars other than \n. If you wish to use them, you need to use a terminal app like putty

**Comment by xxxajk** [comment]
I use cu or screen, but that's not really the point.

**Comment by VogonJeltz** [comment]
I double this TOP!
It's not a good practise by you, ffissore , to always ignore wishes about useful improvements in a stubborn manner and always forthwith setting them to "Wontfix"! 
Please note desires of the Arduino users with the proper respect, benevolence, and openness!

**Comment by ffissore** [comment]
I do. Don't hesitate to provide a pull request

**Comment by VogonJeltz** [comment]
I don't know and don't understand what a pull request is - Google translate does not help ;)

**Comment by PaulStoffregen** [comment]
A pull request means you do all the coding work to implement the feature, then after you have carefully tested your code, you send your change using git's "pull request" feature.  Obviously you need to learn at least the basics of using the git software, as well as doing the actual work on the source code!

https://help.github.com/articles/using-pull-requests/

**Comment by VogonJeltz** [comment]
sorry, I'm just a stupid low-end user with just 1 year Sketch coding experience in some spare time.
If I knew how to do it I already had long since made without losing a word about it.
But I daresay I know what stupid low-end users need for coding Sketches in some spare time.

**Comment by PaulStoffregen** [comment]
Well, at least you now know what "provide a pull request" means!

**Comment by VogonJeltz** [comment]
yes, and hopefully someone will pull this thing in future!

**Comment by xxxajk** [comment]
At some point I may do this. I am currently busy in a contract job. It is
good to know that it is wanted.

yes, and hopefully someone will pull this thing in future!

—
Reply to this email directly or view it on GitHub
<https://github.com/arduino/Arduino/issues/3654#issuecomment-135804250>.

**Comment by VogonJeltz** [comment]
+1:

**Comment by VogonJeltz** [comment]
+1:

**Comment by PaulStoffregen** [comment]
If you do, please test CPU usage carefully with a Teensy 3.1 and Arduino Due sending continuous data without delay.  About a year ago, I put a tremendous amount of work into making Arduino not lock up and not run out of RAM under those conditions.  Let's not revert back to the bad-old-days of issue #2233 just to parse terminal control characters!

**Comment by xxxajk** [comment]
Of course I would.

On Fri, Aug 28, 2015 at 2:20 PM, Paul Stoffregen <notifications@github.com>
wrote:

> If you do, please test CPU usage carefully with a Teensy 3.1 and Arduino
> Due sending continuous data without delay. About a year ago, I put a
> tremendous amount of work into making Arduino not lock up and not run out
> of RAM under those conditions. Let's not revert back to the bad-old-days of
> issue #2233 <https://github.com/arduino/Arduino/issues/2233> just to
> parse terminal control characters!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/3654#issuecomment-135852443>.
>



-- 
Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by VogonJeltz** [comment]
xxxajk, remember, actually PaulStoffregen is number one motivator for innovations to the Arduino IDE.

**Comment by xxxajk** [comment]
I know Paul well enough to know this ;-)

**Comment by per1234** [comment]
Partial duplicate (\r) of https://github.com/arduino/Arduino/issues/346.
