### ISSUE TITLE
Port access taking twice as long on Mega 2560 with 1.6x builds

### ISSUE THREAD

**Issue by drp0** [arduino/Arduino#3658]
I have written a program to utilise the 1.2MHz ADc TLV571.
This is a parallel ADC.
With build 1-5.6-R2, I can read the TLV571 at a top rate of 1.142 Mhz
This is consistent with the stated speed of the ADC chip.
With  a 1.6x build the maximum rate is 549.5 Khz.

I use direct port access to initiate the capture, then poll a parallel port line for a completion. 
The max rate is achieved using void nodelay()
Slower rates are obtained using void usedelay() and variable delayer

variable econ = 8
the ADC signals end of conversion by taking (PINC & econ) high

With build 1.6.5:
1) Data appears to record correctly at 1263 Khz, however the inputted waveform period is approximately halved.
2) I have tried without disabling the interrupts in void nodelay()
Data records correctly, however at a capture rate of 549.5Khz

This suggests that the issue is with the V1.6 method used to directly access the port.
Possibly in conjunction with interrupt disabling.

```arduino
void nodelay(){
cli();
  while(triggered==false){
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    while ((PINC & econ) == 0 ); // wait for econ to go high
  newval=PINA;
  trip = newval-oldval;
    if(!trigplus) trip = -trip;
    if (trip > trigger) triggered=true; else oldval=newval;
  }
// sei(); // include for build 1.6x - much slower but timings ok
starttime=micros();
  for (i=0;i<BUF_SIZE;i++){
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    // wait for econ to go high
    while ((PINC & econ) == 0 );
  bufa[i]=PINA;
  }
endtime=micros();
sei();
}

void usedelay(){
cli();
  while(triggered==false){
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    while ((PINC & econ) == 0 ); // wait for econ to go high
  newval=PINA;
  trip = newval-oldval;
    if(!trigplus) trip = -trip;
    if (trip > trigger) triggered=true; else oldval=newval;
  }
starttime=micros();

  for (i=0;i<BUF_SIZE;i++){
   cli();
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    while ((PINC & econ) == 0 ); // wait for econ to go high
  bufa[i]=PINA;
  sei();
  delayMicroseconds(delayer);
  }
endtime=micros();
}
```
Data from V1.5.6R2 build with a pwm 3921.16Hz wave on port 3
![v1 56r2](https://cloud.githubusercontent.com/assets/13746202/9257753/34be73a4-41ef-11e5-8e05-b5283b11a8a7.jpg)
Data from 1.65 build. Identical pwm source
![v1 65](https://cloud.githubusercontent.com/assets/13746202/9257897/4275ee68-41f0-11e5-895f-5d26bb91bc7f.jpg)
Data from 1.65 build with delayer=1, using void usedelay() 
The wave representation and frequency is correct

![v1 65b](https://cloud.githubusercontent.com/assets/13746202/9258042/137af710-41f1-11e5-949b-93a86a31b6d4.jpg)

Note that similar issues are produced if an externally generated square wave is used.

**Comment by ffissore** [comment]
(edited for better code formatting)

**Comment by drp0** [comment]
After much experimentation!
The issue lies with the global declaration of the unsigned int i.
If this variable is replaced with a local unsigned int, void nodelay() works perfectly, with data capture exactly as expected:
This begs the question, what has changed between build 1.5 and 1.6, in the implementation of global variables?
On a positive note, the local variable processing time improves the sample rate by 43KHz.

void nodelay(){
unsigned int il;
cli();
  while(triggered==false){
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    while ((PINC & econ) == 0 ); // wait for econ to go high
  newval=PINA;
  trip = newval-oldval;
    if(!trigplus) trip = -trip;
    if (trip > trigger) triggered=true; else oldval=newval;
  }
starttime=micros();
  for (il = 0; il < BUF_SIZE; il ++){
  PORTC = B00000010; // RD low, WR high, CS low
  PORTC = B00000110; // RD high, WR high, CS low
    // wait for econ to go high
    while ((PINC & econ) == 0 );
  bufa[il]=PINA;
  }
endtime=micros();
sei();
}

**Comment by matthijskooijman** [comment]
> The issue lies with the global declaration of the unsigned int i.

I suspect that with a global variable for i, its value is forced into memory, while a local variable can be put in a register instead. Perhaps the older compiler optimized more aggressively by keeping the variable in a register during the loop and only writing it near the end, but the newer compiler is more conservative? Dunno really, but good that you've found a fix!
