### ISSUE TITLE
serial monitor open, when unplugging the board forces a reset of iMac [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#366]
This is [Issue 366](http://code.google.com/p/arduino/issues/detail?id=366) moved from a Google Code project.
Added by 2010-10-02T21:31:55.000Z by [dcuartie...@gmail.com](http://code.google.com/u/117755853950663432173/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Arduino Duemilanove
2. IDE 0020 open with Serial Monitor open
3. forces iMac reset when unplugging the board in the middle of the operation

**What is the expected output? What do you see instead?**
The computer should not reset

What version of the Arduino software are you using? On what operating
system?  Which Arduino board are you using?
iMac, Arduino 0020, Arduino Duemilanove, OSX 10.6.4

Please provide any additional information below.
This same situation doesn't happen with 0019
ask: mike-mc at live DOT co DoT uk for further questions

**Comment by ffissore** [comment]
Fixed since the removal of RXTX and the introduction of JSSC. Tested with latest hourly.
