### ISSUE TITLE
Need to close and open Aduino on Linux Ubuntu 15.04

### ISSUE THREAD

**Issue by 34626** [arduino/Arduino#3660]
Im visually impaired and have to edit my arduino code in gedit. When i wanna run it in Arduino im forced to exit the current Arduino window and open a new (CTRL + O) and select the .ino file and then i can upload it to the arduino.. It would be nice with a "reload page" shortcut.. or if you replace the file on its directory you dont need to close arduino but simple can reload page.. (Last thing is just another benefit)

**Comment by BrentWilkins** [comment]
Under preferences chose 'Use external Editor'.  Your changes will be read on compile.

**Comment by 34626** [comment]
Very nice, but a key shortcut would be nice to it :-)

2015-08-11 20:49 GMT+02:00 Brent Wilkins <notifications@github.com>:

> Under preferences chose 'Use external Editor'. Your changes will be read
> on compile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/3660#issuecomment-130014763>.
>



-- 
Best regards /
Med venlig hilsen
Kenneth Rasmussen

**Comment by matthijskooijman** [comment]
I don't think there is a shortcut, but you only have to enable this once and it will be remembered. After that, you can use the regular ctrl-r to verify and ctrl-u to upload.

Let us know if this answers your needs sufficiently.

**Comment by ffissore** [comment]
It looks like that solved @34626 issue
