### ISSUE TITLE
Add new JTAG library

### ISSUE THREAD

**Issue by mrjimenez** [arduino/Arduino#3661]
Please add this JTAG/XSVF player library.

https://github.com/mrjimenez/JTAG

**Comment by ffissore** [comment]
Output is
```
2015/08/12 11:38:18 ... ... tag 1.0.0
2015/08/12 11:38:18 'sentence' and 'url' fields must be defined
```
Please give a second read to https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by ffissore** [comment]
Once fixed, please make another tag/release. The job will publish it in at most an hour

**Comment by mrjimenez** [comment]
I'll do the other release. Thanks.

Just one curiosity, "sentence" __was__ defined in library.properties, "url" was not, indeed. I worry that it will fail again, since "sentence" had no apparent trouble. Does the sentence has to end with a stop punctuation?

**Comment by ffissore** [comment]
No. Indeed setting url was enough and your lib is now listed. Thanks!
