### ISSUE TITLE
Add aREST UI Library

### ISSUE THREAD

**Issue by marcoschwartz** [arduino/Arduino#3662]
Hello,

I would like the aREST UI library to be added to the Arduino library manager. The base library, aREST, is already part of the library manager. This library extends aREST by allowing the user to easily create graphical interfaces to control their Arduino boards, via WiFi or Ethernet.

The GitHub repository for aREST UI is:

https://github.com/marcoschwartz/aREST_UI

Thanks!
Marco

**Comment by ffissore** [comment]
Added. Thanks!
