### ISSUE TITLE
[Library Manager] Please add Blynk

### ISSUE THREAD

**Issue by vshymanskyy** [arduino/Arduino#3670]
Please, add the Blynk library to the library manager. It is a library that enables easiest IoT integration for different hardware platforms.

https://github.com/blynkkk/blynk-library

**Comment by ffissore** [comment]
Your lib contains .exe files and therefore it's invalid. Please give a second read to https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ. Closing as wontfix. Reopen when ready

**Comment by vshymanskyy** [comment]
Thanks for pointing this out!
