### ISSUE TITLE
[DOC] https://www.arduino.cc/en/Reference/EEPROM doesn't mention Zero and Due haven't EEPROM memory

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3671]
First line is bleeding : "The microcontroller on the Arduino board has EEPROM" . Maybe it should replaced by "The AVR microcontrollers on Arduino boards have EEPROM (ARM-based, as Zero or Due, haven't so this library isn't useful for them)..." or similar.
Thanks

**Comment by agdl** [comment]
@q2dg please check the way I stated it and if it is ok for you close the issue please. About the Zero that has an emulated EEPROM library some words should be spent, but maybe it is clearer to open a different issue. Let me know!

**Comment by q2dg** [comment]
For me it's ok. Thanks a lot!
