### ISSUE TITLE
Able to accidentially overwrite Arduino examples

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3678]
1. Open blink
2. Change led number
3. Save, ignore warning, use a different path
4. reopen blink and it will have the content of your new programm

IDE 1.6.6 from yesterday linux

**Comment by ffissore** [comment]
Confirm. Good catch and a nasty bug

**Comment by ffissore** [comment]
Thank you twice. This bug has been around since 1.6.0
