### ISSUE TITLE
[DOC] SPI.transfer(void *buf, size_t count) and SPI.transfer16(unsigned int data) aren't documented in web

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3685]
But they exist at https://github.com/arduino/Arduino/blob/bd8f7932e64fb3a41e3d934437d5eabd8707dcc9/hardware/arduino/avr/libraries/SPI/SPI.h

**Comment by q2dg** [comment]
Well, I see in https://github.com/arduino/Arduino/blob/master/hardware/arduino/sam/libraries/SPI/SPI.h and in https://github.com/arduino/ArduinoCore-samd/blob/master/libraries/SPI/SPI.h that Due and Zero (respectively) only has SPI.transfer(void *buf, size_t count) implemented, but they hasn't SPI.transfer16(unsigned int data). Is it intentional?

Anyway, at least the transfer() variant should be advertised, don't you think? 
Thanks.

**Comment by agdl** [comment]
@q2dg actually with the introduction of the transactions, the transfer function is deprecated and hold only for retro-compatibility reasons. So maybe it's better to not add documentation about this.

**Comment by q2dg** [comment]
What? The transfer function is the only way to transfer bytes inside a SPI communication, either inside a transaction or not!!!!!!.  Are you saying these two alternatives (SPI.transfer(void *buf, size_t count) and SPI.transfer16(unsigned int data) are deprecated? Because SPI.transfer(byte data) isn't!!!!

**Comment by PaulStoffregen** [comment]
The deprecated functions are SPI.setClockDivider(), SPI.setBitOrder() and SPI.setDataMode().

SPI.transfer() is not deprecated.

**Comment by agdl** [comment]
@q2dg @PaulStoffregen I know, you are right, I made a mistake. I will add these functions.

**Comment by agdl** [comment]
What do you think about documenting them in the transfer page and delete (in the transfer page) the informations about the extended methods for due?

**Comment by agdl** [comment]
cc @cmaglie

**Comment by cmaglie** [comment]
For me it's fine to remove "Extended SPI" methods on the `transfer` page.

Probably the Extended API is obsoleted by transactions, I've made a more in-depth analysis in #3682. Let's move the discussion there and close this one if you're done.

**Comment by agdl** [comment]
as suggested by @cmaglie i removed the reference to extended methods and closing this!
