### ISSUE TITLE
MQ Sensors for Arduino.

### ISSUE THREAD

**Issue by Sanpasqual123** [arduino/Arduino#3686]
AQ-3 is not reactive to alcohols or hydrocarbons, being selective for hydrogen.  See manufacturer data sheet: http://www.arihav.com/Datasheet/SP-AQ3.pdf

**Comment by matthijskooijman** [comment]
I'm sorry, but what do you want to achieve with this issue exactly? If you want a library to be included in the library manager, you'll have to be more explicit. If you want someone to write a library to talk to a specific sensor, this is not the right place to ask (the arduino forums on arduino.cc would be more appropriate).

**Comment by Sanpasqual123** [comment]
I was pointing to an error on the extant listing.

**Comment by matthijskooijman** [comment]
And with extant you mean existent? :-)

A listing of a library? Which library? If the error is in the description for a library, you should probably report the error to the library maintainer, since Arduino just displays whatever description is stored inside the library.

**Comment by ffissore** [comment]
Closing as invalid
