### ISSUE TITLE
DIY Gamer Kit libraries for library manager

### ISSUE THREAD

**Issue by mikevanis** [arduino/Arduino#3695]
Hi! 

We'd like to include the [DIY Gamer Kit](https://www.techwillsaveus.com/shop/diy-kits/diy-gamer-kit-arduino/) library in the library manager. 

Here is a link to the release: https://github.com/techwillsaveus/Gamer/releases/tag/v2.0

Additionally, Gamer has another library for interfacing with multiplayer (IR serial) functions. 

Here is a link to that release: https://github.com/techwillsaveus/GamerIR/releases/tag/v1.0

Many thanks! Looking forward to our library appearing gloriously in the brand new (awesome) library manager!!

TWSU

**Comment by ffissore** [comment]
Added. Thanks!

**Comment by mikevanis** [comment]
Hi @ffissore, thanks for adding our libraries! GamerIR works perfectly. However, Gamer throws an error when we try to install it with the library manager. This is the error we get: 

`CRC doesn't match. File is corrupted`

**Comment by ffissore** [comment]
Did you force pushed a new tag?

**Comment by mikevanis** [comment]
I don't think we did. The latest commit is tagged as v2.0, and was created with GitHub's release feature. Any suggestions / wisdom?

**Comment by ffissore** [comment]
Probably some change from github. I'll regenerate the hash

**Comment by mikevanis** [comment]
Great! Feel free to give me a ping if it starts working. We're trying from our end too!

**Comment by ffissore** [comment]
It's working now. You'll have to manually delete previously downloaded .zip file (.arduino15/staging/libraries)

**Comment by mikevanis** [comment]
Perfect, thanks Federico! Thumbs up :+1:
