### ISSUE TITLE
Add character testing and conversion routines from Wiring. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#370]
This is [Issue 370](http://code.google.com/p/arduino/issues/detail?id=370) moved from a Google Code project.
Added by 2010-10-05T13:14:08.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core
### Original description

That is, things like isAlpha(), isDigit(), and toLowerCase(), toUpperCase(), etc.

**Comment by per1234** [comment]
These functions are already part of the core:
https://github.com/arduino/Arduino/blob/1.8.3/hardware/arduino/avr/cores/arduino/WCharacter.h
