### ISSUE TITLE
Add ArduinoJson library

### ISSUE THREAD

**Issue by bblanchon** [arduino/Arduino#3703]
Hi,

Can you please add ArduinoJson to the Arduino Library Manager:
https://github.com/bblanchon/ArduinoJson

Thanks you very much!

**Comment by matthijskooijman** [comment]
@bblanchon, Woah, impressive use of C++ creating that library, looks like it employs maximum compiletime abstraction to get an API that is easy *and* efficient. I wonder if some the stuff done in this library could be used in core Arduino APIs as well :-)

**Comment by ffissore** [comment]
Added. Thanks!
