### ISSUE TITLE
board manager

### ISSUE THREAD

**Issue by piobel** [arduino/Arduino#3706]
on ARDUINO 1.6.6 version shows error in board manager with this json link:

 https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json

**Comment by per1234** [comment]
This issue was also submitted here: https://github.com/damellis/attiny/issues/78 where I am looking into it.

**Comment by matthijskooijman** [comment]
Ok, then I'll close this issue. If it turns out to be an IDE bug, please leave a comment here with more details and we will reopen.

**Comment by piobel** [comment]
this is the problem ..

best



Il giorno 21/ago/2015, alle ore 07:59, Matthijs Kooijman <notifications@github.com> ha scritto:

Ok, then I'll close this issue. If it turns out to be an IDE bug, please leave a comment here with more details and we will reopen.
