### ISSUE TITLE
Request to add library to Arduino Library Manager

### ISSUE THREAD

**Issue by rpurser47** [arduino/Arduino#3707]
Hi,

We'd like to request that you add our new ThingSpeak library to the Arduino Library Manager.  Our code is in the https://github.com/mathworks/thingspeak-arduino repository.

Thanks,
Rob Purser
rob.purser@mathworks.com

**Comment by ffissore** [comment]
Added. Thanks!

**Comment by rpurser47** [comment]
Thanks so much!

All the best,
-Rob Purser
