### ISSUE TITLE
Suppress splash when using Command line options

### ISSUE THREAD

**Issue by mvandere** [arduino/Arduino#3708]
The use of certain command line options says "if any of the following command line options is given, no graphical interface will be shown". This is not strictly correct as the splash screen is still shown.

Could this be fixed, or at least an (other) option to suppress the splash be added?

Thanks,

Mark

**Comment by mvandere** [comment]
Duh, now I see the note about 'arduino_debug'.

**Comment by matthijskooijman** [comment]
:-)
