### ISSUE TITLE
pcduino externel interrupts

### ISSUE THREAD

**Issue by sriranjanr** [arduino/Arduino#3716]
Hello,

I am working with pcduino3. I set the pcduino to externel interrupts and gave it a signal at 11Mhz but the duino is not catching it at the same frequency. Per second I get a 1000 hits in the ISR (as I am incrementing a variable ever time the ISR runs and printing it in the main loop). What is wrong with this board and how do I set it to catch a 11mhz interrupt with 44khz OR 8khz OR 2khz ISR.

**Comment by PaulStoffregen** [comment]
Do you realize pcduino is a 3rd party board?  It's not made or supported by the Arduino Team?  While it may use the Arduino software, the actual device-level code it uses is written & published by LinkSprite, not Arduino.

You really need to ask this question of LinkSprite.

If it's running your sketch as a Linux-based user program, as Intel Galileo does, it simply may not be up to the task of responding to so many real-time events.  If it's Linux-based, you'd probably have to get into Linux kernel-level programming.  Probably?  Maybe?  Really, I'm just guessing here.  I do not know.

But I do know you've asked in the wrong place.
