### ISSUE TITLE
Renaming deleted tab renames main tab and folder

### ISSUE THREAD

**Issue by AlexLardschneider** [arduino/Arduino#3720]
Renaming a deleted tab (clicking rename so the input field shows at the bottom, and then deleting the tab) renames the main file/tab and the folder the files sit in. Also the rename input field doesn't disappear when deleting the tab.

**Comment by ffissore** [comment]
Thank you. Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
