### ISSUE TITLE
Add Example Group title

### ISSUE THREAD

**Issue by 00alis** [arduino/Arduino#3725]
We are redesigning the Tutorial pages on arduino.cc and it would be super helpful if we could add a title to each Example group in the menu (as we did for Boards, attachment)
![screenshot 2015-08-25 16 17 47](https://cloud.githubusercontent.com/assets/6151328/9470831/fb10540c-4b4d-11e5-9e03-cac3c8ca7f3b.png)

Specifically the titles would be:
- Built-in Examples
- Examples from Libraries
- Examples from Custom Libraries

If this copy is too long we can consider removing the word Examples everywhere.
Thanks @ffissore !

**Comment by matthijskooijman** [comment]
I implemented pretty much this in #1986, see https://github.com/arduino/Arduino/pull/1986#issuecomment-41328050 for a screenshot. That PR is probably severely outdated (and this is not the main goal of the PR), but it can still probably useful. If the rest of the PR is also considered useful, I could have a go at updating it.

**Comment by NicoHood** [comment]
Since we now have the categories I agree with @matthijskooijman to add category folders as well as the 3 main categories as described above. My library list is very long even though I have not installed that ultra much libraries. Especially the builtin number of libs is very long.
