### ISSUE TITLE
Request to Add Library to Library Manager

### ISSUE THREAD

**Issue by cwjpalmer** [arduino/Arduino#3731]
I am very excited to request that the following library be added to the list of libraries available through the Library Manager. Please don't hesitate to get in touch with me at chris@awesomeshield.com

# Repo URL

https://github.com/awesomeshield/Awesome-Shield-Library.git

# Release

v0.1.0

# Hash

f4462f298930d8f47ec67756174ab07669600916

**Comment by ffissore** [comment]
Added. Thanks!

**Comment by cwjpalmer** [comment]
@ffissore Thank you so much!! :smile:
