### ISSUE TITLE
Library Manager should group unknown categories into "Uncategorized" in Topic list

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#3732]
The library spec defines 9 legal values for the category field.

Currently 5 libraries are using undefined names.  The library manager is trusting these names, rather than checking them against the list of legal categories.  For example, the Topics list currently shows "Cloud", which lists just 1 library.  If left unchecked, over time more library authors will use improper category names, causing the Topics list to grow to mostly useless categories that show only 1 or 2 libraries.

When building the Topics list, the Library Manager really should check the category names against the list of legal strings.  Any names not on the list should be treated as "Uncategorized".

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
