### ISSUE TITLE
[DOC] Serial readStringUntil has incorrect Syntax in documentation.

### ISSUE THREAD

**Issue by mathmauney** [arduino/Arduino#3734]
Page in question: https://www.arduino.cc/en/Serial/ReadStringUntil

Using the syntax provided of Serial.readString(terminator) results in an error: candidate expects 0 arguments, 1 providedno matching function for call to 'HardwareSerial::readString(char)'

This can be fixed using the correct syntax of Serial.readStringUntil(terminator).

**Comment by agdl** [comment]
@mathmauney corrected with the right syntax. If it is ok for you, close the issue please!

**Comment by agdl** [comment]
@mathmauney I'm closing this. Reopen it if needed please!
