### ISSUE TITLE
Implement full screen mode on Mac OS X

### ISSUE THREAD

**Issue by cunidev** [arduino/Arduino#3749]

**Comment by carlosperate** [comment]
This feature was tested, but ultimately dropped: https://github.com/arduino/Arduino/pull/3243

**Comment by cunidev** [comment]
Dropped definitely, or just waitiing for developers? #3256

**Comment by ffissore** [comment]
Closing as duplicate of #3256. Indeed that code needs some mac expert. Feel free to fetch, use and adapt that code
