### ISSUE TITLE
SPI Library not found

### ISSUE THREAD

**Issue by deisterhold** [arduino/Arduino#3751]
When I attempt to compile I get "fatal error: SPI.h: No such file or directory". I'm not sure whether this library is just not being found or if there isn't a library available yet for the Tre.

The IDE I am using is the web IDE on the Arduino Tre. I believe I have the latest version of the app which is version 0.0.12. Any help is appreciated.

**Comment by per1234** [comment]
There has been a huge amount of work done on the Arduino Web editor since this issue was reported and I just verified that indeed it is possible to include SPI.h (though the Arduino Tre is no longer with us). So I'm going to go ahead and close this issue.
