### ISSUE TITLE
missing Arduino code examples and documentation: serial communication lib for 2-way half duplex communication by 48-128 bytes string length / array size

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#3765]
hello,
I just started with implementing a serial communication lib between 2 Arduino Megas (Serial2) for 2-way half duplex communication by 48-128byte bandwidth (sending and receiving data packages of bytes or strings up to arrays[128] ) . 
Baud rate which I tested was from 9600...64000...115200... 256000 up to 460800. 
I started by byte arrays[8], enlarging the array size step by step.
But unfortunately I encountered many transmission errors, data corruption, and data loss and the connection is lowsy slow (< one time per second sending an array there and back).

In the Arduino examples there is no code example to find about quick and fail-safe data transmission.
Please provide such a code!

**Comment by PaulStoffregen** [comment]
This github issue tracker is for reporting bugs in Arduino.

You really need to post this question (and most of the stuff you post here) on the Arduino Forum:

https://forum.arduino.cc/index.php?board=3.0

**Comment by VogonJeltz** [comment]
ok,
the issue is: I can't find it, 

and so if it really doesn't,
then my request is to pull this for an improvement!

**Comment by PaulStoffregen** [comment]
Post your question on the forum.

**Comment by VogonJeltz** [comment]
no.

**Comment by VogonJeltz** [comment]
I searched all forums, the playground and all existing code examples in the IDE  but no code examples found!

Please provide code examples  about quick and fail-safe 2-way data transmission of long strings .or byte arrays (length > 48 bytes, possibly up to 128 bytes each.)
