### ISSUE TITLE
sensor library working for arduino v1.0 but not for v1.6.5

### ISSUE THREAD

**Issue by samarth003** [arduino/Arduino#3773]
Hi,
I am trying to integrate SHT-75 (Temp and RH) sensor with Arduino Uno. 
I am using this library: https://github.com/practicalarduino/SHT1x 
This works perfectly fine with Arduino v1.0 but when i try to use Arduino v1.6.5, the readings comes out weird. Example of the faulty readings is as follows:

Temperature: 22.2899971008C / -433.2279968261F. Humidity: -1775.94%
Temperature: -258.4599914550C / -433.2279968261F. Humidity: -1775.90%
Temperature: -258.4599914550C / -433.2279968261F. Humidity: -1775.94%
Temperature: 23.3599967956C / -433.2279968261F. Humidity: -1775.94%
Temperature: -258.4599914550C / -433.2279968261F. Humidity: -1775.94%
Temperature: -258.4599914550C / -433.2279968261F. Humidity: -1775.94%
Temperature: -258.4599914550C / -433.2279968261F. Humidity: -2265.65%

Is this a known issue? Could you please guide me on how to resolve this issue.
Your help is much appreciated! 
Thanks!!

**Comment by ffissore** [comment]
I see you've already [asked this question](https://github.com/practicalarduino/SHT1x/issues/12) to library maintainers. That's what I was going to suggest, as your issue is with the library, not the IDE. Please let us know if the Arduino IDE or one of its tools is misbehaving
