### ISSUE TITLE
RCTime tutorial on website is corrupted--needs fixing

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [arduino/Arduino#3782]
Something happened to it. The tutorial code is scrambled and malformatted. 

https://www.arduino.cc/en/Tutorial/RCtime

partial screenshot:

![image](https://cloud.githubusercontent.com/assets/6842199/9827964/bddc0ca0-58b5-11e5-8909-ffafe2d249fb.png)

**Comment by carise** [comment]
Poking around on the Chrome Dev Tools, it seems that if I uncheck the "white-space: normal" css property on the pre tag, the formatting goes back.

<img width="1467" alt="screen shot 2015-09-12 at 12 13 36 am" src="https://cloud.githubusercontent.com/assets/14340/9830449/617f32ce-58e3-11e5-9e8e-ab163292c1c5.png">

**Comment by agdl** [comment]
@ElectricRCAircraftGuy done it is ok now. I'm closing this!
