### ISSUE TITLE
Compiler warnings when compiling EEPROM.h

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#3783]
Under 1.6.4 of the IDE (and reportedly under nightly builds as well) compiling an EEPROM example gives this warning:

```
In file included from eeprom_get.ino:18:0:
/home/nick/Development/arduino-1.6.4/hardware/arduino/avr/libraries/EEPROM/EEPROM.h:43:30: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     operator const uint8_t() const       { return **this; }
                              ^
/home/nick/Development/arduino-1.6.4/hardware/arduino/avr/libraries/EEPROM/EEPROM.h:92:26: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
     operator const int() const          { return index; }
                          ^
```

To fix, remove the **first** const from both of those lines.

**Comment by Chris--A** [comment]
Cheers, in the update proposal I have in the works, all the warnings are fixed.

Once all the changes are pushed, I'll link here and add a post the dev mailing list. :+1:

**Comment by maxmclau** [comment]
Any update on this?

**Comment by Chris--A** [comment]
Yeah, I have the updated files ready, I'll do up a PR after work tomorrow.

**Comment by glansberry** [comment]
Bump - problem is still there in 1.8.0

**Comment by Chris--A** [comment]
This has been fixed and added to the next proposal (https://github.com/Chris--A/Arduino/commit/acbd8bccdc13b14098adff0330403dbf010ed430) [here](https://github.com/arduino/Arduino/compare/master...Chris--A:EEPROM_2.1?expand=1)

**Comment by per1234** [comment]
@Chris--A I can't seem to find the pull request.

**Comment by gtozzi** [comment]
It looks like this is still present in 1.8.5

**Comment by szotsaki** [comment]
Any news on removing the two `const` qualifiers?

**Comment by d-a-v** [comment]
Do you think making a PR would help with this 2½ years old trivial fix ?

**Comment by nickgammon** [comment]
It can't make things any slower. :)

**Comment by matthijskooijman** [comment]
I'm closing this in favor of https://github.com/arduino/ArduinoCore-avr/issues/36 which describes the same issue, but is in the (by now) right repository (and has a PR with a fix).
