### ISSUE TITLE
Calling Arduino.exe over the Command Line (issues)

### ISSUE THREAD

**Issue by obiwanjacobi** [arduino/Arduino#3789]
I have a couple of issues with using the command line with Arduino.exe
I have a whole lot of example .ino files and check/verify/compile them as part of the build/release cycle of my library.

1) There should be a silent mode that reports over the stdout/errout streams.
All compiler output (verbose or not) should be visible then.

2) Exit code reports 0 on compile error.
Which makes the --verify option pretty useless.

**Comment by carlosperate** [comment]
In windows you should be using `arduino_debug.exe` to get those features.

**Comment by ffissore** [comment]
Indeed. On Windows, use `arduino_debug`
