### ISSUE TITLE
Entry for newly added URL doesn't appear the first time Boards Manager is opened

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3795]
Using Arduino IDE 1.6.6 2015/09/14 05:43 with Windows 7 64 bit
- Add a URL for a package that has never been installed to File>Preferences>Additional Boards Manager URLs
- Tools>Board>Boards Manager...
- Wait for all downloads to complete
- The entry for the newly added URL does not appear in Boards Manager
- Close Boards Manager
- Tools>Board>Boards Manager...
- Wait for all downloads to complete
- The entry for the newly added URL appears in Boards Manager

This happens consistently. The issue does not occur with 1.6.5r5

**Comment by NicoHood** [comment]
I remember to have the same problem.

**Comment by SpenceKonde** [comment]
This is really confusing to new users. I've just had to amend the installation instructions for the cores I maintain to reflect this bug.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by hatam1975** [comment]
hhhhh
