### ISSUE TITLE
Hourly build seem to have removed  -mmcu={build.mcu} argument to compiler

### ISSUE THREAD

**Issue by fallberg** [arduino/Arduino#3796]
This causes a lot of problems for low level functionality. For example, sleep.h gets a preprocessor error because of missing precompiler defines obtained from the -mmcu compiler argument.

**Comment by ffissore** [comment]
Thanks for the heads up! Fixing it right now

**Comment by ffissore** [comment]
uhm, can you provide the command line you're using? I've just tried compiling a Blink for a Nano with 
```
./arduino --verify --board arduino:avr:nano:cpu=atmega328 --verbose ./examples/01.Basics/Blink/Blink.ino 
```
and it works as expected

**Comment by fallberg** [comment]
I use the GUI to test. Blink compiles, since it does not include AVR specific stuf (at least not sleep.h). Just try to add #include <avr\sleep.h> and it will fail (at least for an Arduino Nano which is the board I tested with).

**Comment by ffissore** [comment]
Confirm. Thanks

**Comment by ffissore** [comment]
Fixed in latest hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by fallberg** [comment]
Thanks!
