### ISSUE TITLE
IDE Ctl+A / Ctl+E missing

### ISSUE THREAD

**Issue by conorpeterson** [arduino/Arduino#3800]
UI regression. Mac version of Arduino 1.6.5.

Expected: Ctl-a should jump cursor to start of line. Ctl-e should jump to end of line.
Result: Nothing happens. Keyboard shortcuts evidently removed?

Standard Macintosh text edit boxes respond to these commands.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
