### ISSUE TITLE
[DOC] A better data types explanation is needed

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3801]
* In https://www.arduino.cc/en/Reference/Word should be added a note saying that only in AVR boards it is a 2-byte data type : in Due (**and Zero???**) it is a 4-byte data type (as it is already explained in https://www.arduino.cc/en/Reference/UnsignedInt) 

* Maybe should be added a table somewhere simply showing three columns for each data type (row): the bytes stored in both architectures (AVR & ARM) if it's signed or not and their resepective numerical boundaries. This would help to see, for instance, that in Due (**and Zero???**) the *word* type and the *unsigned long* type are the same and also the *int* type and the *long* type, whereas in AVR the *short* type is equal to *int* type. 

* @VogonJeltz points in #3797 that the *char* type in Due (**and Zero???**) is unsigned. I haven't a Due and I can't test it, but if it is true, it should be documented too!!

Former points show some mess in data types definitions depending on the architecture of the board (and besides, these definitions are different from ANSI C, as @VogonJeltz points again in #3797). I suppose it's very out of scope of this issue, but maybe a general review of how data types are defined in Arduino platform as a whole should be done. 

Thanks

**Comment by agdl** [comment]
@q2dg As you have seen this argument is a little bit hard in the Arduino eco-system :( Since you referenced this issue in the newer one, I'm closing this (they are almost the same) and leaving the other one opened because it is newer so upper in the issue history
