### ISSUE TITLE
Arduino lmic problem to run sample code.

### ISSUE THREAD

**Issue by po4life** [arduino/Arduino#3803]
I have downloaded the arduino lmic master so I can test my arduino uno boards with the libellium sx1272. But i get a failure when I run the code and listen on the serial port.
 // some sanity checks, e.g., read version number
    u1_t v = readReg(RegVersion);
#ifdef CFG_sx1276_radio
    ASSERT(v == 0x12 );
#elif CFG_sx1272_radio
    ASSERT(v == 0x22);
#else

The code gives a failure at runtime in the assert(v == 0x22). But when I check wat the variable v is, it is not the same as 0x22.

Someone knows what's going on here??

Greets

**Comment by matthijskooijman** [comment]
@po4life, this is an issue with the arduino-lmic library, so you should report it there: https://github.com/matthijskooijman/arduino-lmic/issues I'm closing this issue.

Incidentally, I'm also the maintainer of that library, so I'll respond a bit here anyway. If the value of v is 0x12, you seem to have the sx1276 chip instead. If it has another value, perhaps the SPI connection isn't set up properly? If you want to respond to this, please open up an issue in the right repository, thanks.
