### ISSUE TITLE
IDE should not steal focus for "Update available for some of your libraries"

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#3809]
Something that seems to be annoying: When the "Update available for some of your libraries" popup shows, the IDE window is focused (though not always, it seems). I'm not sure how this was designed to be, but ideally this popup would just stay within the IDE and should certainly not bring the entire IDE to the top.

Only tried on Linux, not sure how other platforms behave.

**Comment by ffissore** [comment]
Sorry, I've tried but I was unable to avoid it from gaining focus. All OSs are affected. Help wanted

**Comment by NicoHood** [comment]
Is there a way to disable auto update and manually search for new updates? That'd be at least an idea. Especially for dev versions when you get a new avr core, that you dont want to use.

**Comment by i-make-robots** [comment]
Also the about dialog on startup refuses to stay down.
- start arduino
- see about image
- select any other window
- about image resurfaces
I can replicate this multiple times before app finishes loading.

**Comment by sandeepmistry** [comment]
See https://github.com/arduino/Arduino/issues/4546#issuecomment-205312163, this should be resolved now.
