### ISSUE TITLE
Error in wiring diagram in Liquid Crystal 'Hello World' tutorial

### ISSUE THREAD

**Issue by ArtcoInc** [arduino/Arduino#3810]
In the Liquid Crystal tutorial:

https://www.arduino.cc/en/Tutorial/HelloWorld?from=Tutorial.LiquidCrystal

There is an error in the Fritzing image:

https://www.arduino.cc/en/uploads/Tutorial/LCD_Base_bb_Fritz.png

There is a black wire leading up from pin 5 of the Liquid Crystal module, terminating in the Power buss. This should terminate in the Ground buss.

**Comment by agdl** [comment]
@ArtcoInc updated thank you!
