### ISSUE TITLE
OSX Arduino IDE 1.6.5 no indication when file is not saved

### ISSUE THREAD

**Issue by iseldonz** [arduino/Arduino#3816]
Altering a file should put a black "bullet" in the red circle in the window's header. This does not happen, so ther is no way to tell whether an altered file has been saved.

**Comment by ffissore** [comment]
This is when the sketch is saved
![saved](https://cloud.githubusercontent.com/assets/510465/9953623/adfb744c-5de2-11e5-8527-a65635c143ae.png)
This is when is NOT saved
![unsaved](https://cloud.githubusercontent.com/assets/510465/9953631/bcfa4612-5de2-11e5-8b4a-04a4b6f58186.png)
Where have you red about this black bulled in a red circle?

**Comment by Chris--A** [comment]
I think @iseldonz is mentioning this:

![osx](https://developer.apple.com/library/mac/technotes/tn2007/images/tn2196_modified.png)

Whether or not this is a common behavior, I do not know (do not use OSX)

**Comment by Chris--A** [comment]
It is also mentioned in the apple developer guides.
https://developer.apple.com/library/mac/documentation/Java/Conceptual/Java14Development/07-NativePlatformIntegration/NativePlatformIntegration.html (search for *Window-Modified Indicator*).
So I guess it is a standard way of doing things.

**Comment by ffissore** [comment]
Yes I was just reading it. Thank you, seems feasible

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
