### ISSUE TITLE
OSX Arduino IDE 1.6.5 end-of-line markers do not show up

### ISSUE THREAD

**Issue by iseldonz** [arduino/Arduino#3817]
The "little pooties at the end of lines that show where they finish" (to quote the Style.txt file) are not visible. Attempts to make them visible by changing the color values in the file were not successful.

**Comment by ffissore** [comment]
There is no style.txt file. Can you clarify what are you talking about?

**Comment by ffissore** [comment]
You meant theme.txt. I confirm with the introduction of the new editor we lost EOL markers. Fixed now. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
Thank you!
