### ISSUE TITLE
Arduino does not support sketchbook on iCloud Drive?

### ISSUE THREAD

**Issue by M6KWH** [arduino/Arduino#3832]
I would like to keep all my Arduino stuff - libraries, sketches etc, on iiCloud Drive folder.

But when browsing to set the sketchbook folder, iCould is not offered as a destination.

Or am I missing something?

**Comment by ffissore** [comment]
Is your iCloud a real folder?

**Comment by M6KWH** [comment]
Well it is the official Apple iCloud Drive folder visible in the Finder

On 21 Sep 2015, at 10:26, Federico Fissore <notifications@github.com> wrote:

Is your iCloud a real folder?

**Comment by ffissore** [comment]
I guess it's not a real folder then. I don't use any of these cloud stuff, but my colleague has his sketchbook synched with Dropbox

**Comment by ffissore** [comment]
This stackoverflow may help you http://superuser.com/questions/827827/access-icloud-drive-via-terminal
Closing as invalid as this issue has nothing to do with the IDE, but it's a mac issue
