### ISSUE TITLE
[library] Please add PJON to manager

### ISSUE THREAD

**Issue by PaoloP74** [arduino/Arduino#3837]
PJON (Padded Jittering Operative Network) is a single wire, multi-master communication bus system. It is designed as an alternative to i2c, 1-Wire, Serial and other Arduino compatible protocols.

https://github.com/gioblu/PJON

**Comment by ffissore** [comment]
Added. Thanks! However, there are no tags, so it didn't go into library manager. Contact the author and forward him/her this https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
