### ISSUE TITLE
Pluggable USB does not check maximum endpoint number

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3842]
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/USBCore.cpp#L321-L323

The u2 series only can add 1 (not 3) more additional endpoint (Serial + HID for example). It still works, but you could remove this stuff there.

Wasnt there a definition with maximum interfaces? We should make this definition more flexible.
but before patching this I suggest to first get an answer here:
https://github.com/arduino/Arduino/pull/3840

**Comment by NicoHood** [comment]
https://github.com/arduino/Arduino/pull/3896 fixes this. Even tough its not finished yet, I want to mention it

**Comment by facchinm** [comment]
Fixed by merging #3896
