### ISSUE TITLE
OPC Library for Arduino for the IDE library manager

### ISSUE THREAD

**Issue by ildemartinez** [arduino/Arduino#3843]
Hello

I am proud to release the OPC library for Arduino. It is widly used but I would like to be available using the Arduino IDE library manager.

Here is the url of the released 1.0 

https://github.com/SoftwareTools4Makers/OPC/releases/tag/1.0

The main project page is at: http://www.st4makers.com/

I think the procedure for publising it is ok, otherwise please let me know.

All the best
ilde

**Comment by ffissore** [comment]
Added. Thanks!
