### ISSUE TITLE
Removing buggy versions of lib from library manager.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#3846]
Hi, I have removed old tags from one of my libraries that had bugs in those releases. However they still appear in the library manager and are visible in the json file.

Is there a way to remove these so people do not get curious and install them.

**Comment by matthijskooijman** [comment]
@Chris--A IIRC they will be removed during a weekly cleanup run on Sunday.

**Comment by ffissore** [comment]
Correct. Just wait until Sunday

**Comment by Chris--A** [comment]
Thank you for the explanation.
