### ISSUE TITLE
Problems with version 1.6.5 under Mac Os

### ISSUE THREAD

**Issue by jackbell16** [arduino/Arduino#3849]
Arduino:1.6.5 (Mac OS X), Scheda:"Arduino/Genuino Uno"

Cannot run program "{runtime.tools.avr-gcc.path}/bin/avr-g++" (in directory "."): error=2, No such file or directory

**Comment by ffissore** [comment]
It looks like your installation is a bit screwed up. Try deleting/renaming folder ~/Library/Arduino15 and restarting the IDE

**Comment by jackbell16** [comment]
You're right. The problem was that ! Thank you for your support !
