### ISSUE TITLE
[DOC] Serial.availableForWrite() is not documented on web

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3866]
See https://github.com/arduino/Arduino/commit/e5c7cb9de174778521ff4be164c616caebc48801

(and https://groups.google.com/a/arduino.cc/forum/#!topic/developers/uvdvnbhW3go)

**Comment by agdl** [comment]
@q2dg https://www.arduino.cc/en/Serial/AvailableForWrite let me know if it is good for you!

**Comment by q2dg** [comment]
For me it's ok, thanks! I don't know if @cmaglie has something to say, though (I'm not an expert)

**Comment by cmaglie** [comment]
:+1:
