### ISSUE TITLE
Add PJON to library manager

### ISSUE THREAD

**Issue by gioblu** [arduino/Arduino#3870]
I wrote an opensource one wire communications bus system for Arduino named PJON in 3 and a half years of development and tests and now it is finally in v1.0 stable version, full of examples and a detailed readme: https://github.com/gioblu/PJON

Would be a great pleasure if the community will start to use it and test it so I would see it added in the Library Manager :)

**Comment by matthijskooijman** [comment]
Your library was already added, see #3837. At that time it did not have any tags yet, so it might need some time for the tag you added to be found. I'm closing this issue, please reopen it if your library is not available in the Library Manager by the end of monday.
