### ISSUE TITLE
[DOC] Missing https://www.arduino.cc/en/Reference/HID page

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3880]
When HID library is selected in Library Manager, its "See more" link points to this address, which doesn't exist.  If this library is not intended to be used directly by sketch developer (as it seems it's a base for other "front-ender" libraries like Keyboard or Mouse, but I'm not sure about this) at least the missing page could mention this.

On the other hand, including Keyboard and/or Mouse library in a sketch but forgetting including HID library doesn't throw any compilation error (28 sept, hourly build). Is it normal??

*@facchinm Is it based on https://github.com/NicoHood/HID/tree/dev_2_4?? Or is it something different??*

**Comment by NicoHood** [comment]
I tried to upgrade the HID library with some additional features. If its partly integrated (at least the pluggable HID key features) is under discussion.

An HID documentation would be nice, a link to my library would be cool.

**Comment by facchinm** [comment]
Hi @q2dg , the HID library is a porting of existing code which lived inside the core, Nico's one is a (very good) rewrite/expansion of the original code.
A sketch compiles without the inclusion of `HID.h` thanks to @ffissore 's work on recursive library detection, which is still in beta so the documentation has not been updated.
We will stabilize the documentation once the library APIs will be stable (quite soon I hope) :wink:

**Comment by q2dg** [comment]
Ok, thanks a lot for your explanation. I'll close this issue, then, because I infer you are already working on it and you don't need this thread to be open.

I have a last question, though: is HID library intended to be used by a sketch developer or it's like a "hidden" library designed to support Keyboard/Mouse/... ones? I ask this because HID library appears as another regular library inside the list of standard libraries shown by the IDE, so I don't know if this fact could be a little confusing. But maybe I'm completely wrong.

**Comment by facchinm** [comment]
Well, you could use it directly in a sketch but without defining a proper descriptor (and thus implementing a real device) it is pretty useless.
I'm reopening the issue as a reminder, will close it when the docs are ok!
