### ISSUE TITLE
1.6.5 doesn't seem to work with SD card readers

### ISSUE THREAD

**Issue by steowens** [arduino/Arduino#3886]
I have tried several card reader shields now with Arduino 1.6.5 and none seem to work.  Downgrading to older Arduino

**Comment by PaulStoffregen** [comment]
What sort of an answer could you possibly expect?

You didn't even mention which Arduino you're using, not to mention specifics on the "several card reader shields".  Even if somebody wanted to dig into this, they'd have to start by guessing which hardware you used!
