### ISSUE TITLE
[DOC] Example shown in https://www.arduino.cc/en/Tutorial/SimpleAudioPlayer uses old SPI API

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3890]
The same example is shown in Audio's begin(), prepare() and write() method's pages.

**Comment by q2dg** [comment]
Well, https://www.arduino.cc/en/Tutorial/SimpleAudioPlayerZero has the same problem

**Comment by agdl** [comment]
Well, in any case the default setting is 4, so maybe it can be removed, without breaking anything

**Comment by agdl** [comment]
@q2dg I'm closing this thank you!
