### ISSUE TITLE
Expand buildsystem with a few additions

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3895]
* A command to just run the ide without recompiling would be cool. "run" should be kept as it is, maybe use something like "start"?
* A command to copy the modified hardware folder. This is very annoying for testing. I currently need to copy my changes from linux/work into the real hardware folder (for a new commit). Also if I switch the branch and recompile the IDE all progress is lost. If i could simply edit the real (intended to edit) files and just copy them to my work directory (without hitting recompile) that'd be very nice.

**Comment by ffissore** [comment]
@cmaglie we've talked about first @NicoHood request a few days ago. What's your opinion?
As for your second request, doesn't putting your hardware under `sketchbook/hardware" solve?

**Comment by NicoHood** [comment]
Well but I still cannot switch branches via git fast enough. And I still need to copy them back for a commit. So there is no real improvement except the avoided data loss on rebuilding the ide.

**Comment by ffissore** [comment]
What I usually do is to commit on some branch, switch to another, do some work, and switch back to previous branch. If previous branch needs the work done on the other, I rebase and git reset HEAD~1

**Comment by ffissore** [comment]
ok, try now with `ant start`

**Comment by matthijskooijman** [comment]
> A command to copy the modified hardware folder. This is very annoying for testing. I currently need to copy my changes from linux/work into the real hardware folder (for a new commit). Also if I switch the branch and recompile the IDE all progress is lost. If i could simply edit the real (intended to edit) files and just copy them to my work directory (without hitting recompile) that'd be very nice.

I have a symlink from `sketchbook/hardware/arduino/avr` to `arduino_git_checkout/hardware/arduino/avr`, which pretty much solves this problem for me. This version overrides the version from `linux/work`, so you can edit in the git-controlled files directly, ignoring `linux/work` completely.

**Comment by NicoHood** [comment]
Had no time to test this yet, but I guess it works as expected. Thanks for the addition :)
And thanks @matthijskooijman for the tip. will try that as well today.

**Comment by NicoHood** [comment]
Works pretty well. Just added here:
https://github.com/arduino/Arduino/wiki/Building-Arduino

**Comment by ffissore** [comment]
Thanks!
