### ISSUE TITLE
21 crashes with Java 1.6.0_22 on Mac OS 10.6.4 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#390]
This is [Issue 390](http://code.google.com/p/arduino/issues/detail?id=390) moved from a Google Code project.
Added by 2010-11-03T03:31:49.000Z by [slaws...@gmail.com](http://code.google.com/u/115566339125259193955/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Install Java update
2. Start IDE
3. IDE Crashes

Java 1.6.0_22 on Mac OS 10.6.4

Crash report below.
----------------------

Process:         JavaApplicationStub [266]
Path:            /Applications/Arduino.app/Contents/MacOS/JavaApplicationStub
Identifier:      cc.arduino.Arduino
Version:         0021 (0021)
Code Type:       X86 (Native)
Parent Process:  launchd [191]

Date/Time:       2010-10-25 17:06:29.205 -0700
OS Version:      Mac OS X 10.6.4 (10F569)
Report Version:  6

Interval Since Last Report:          656861 sec
Crashes Since Last Report:           4
Per-App Interval Since Last Report:  41718 sec
Per-App Crashes Since Last Report:   4
Anonymous UUID:                      FC7B714E-7180-42B7-80AC-EFD743FE864F

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x000000000000000c
Crashed Thread:  3

Thread 0:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib                  0x9246a0fa mach_msg_trap + 10
1   libSystem.B.dylib                  0x9246a867 mach_msg + 68
2   com.apple.CoreFoundation            0x9785dfaf __CFRunLoopRun + 2079
3   com.apple.CoreFoundation            0x9785d094 CFRunLoopRunSpecific + 452
4   com.apple.CoreFoundation            0x9785cec1 CFRunLoopRunInMode + 97
5   ...ple.JavaApplicationLauncher      0x000066f1 startupJava(LauncherArgsStruct*) + 342
6   ...ple.JavaApplicationLauncher      0x00008908 launchJavaApplicationWithJVMInfo + 1402
7   ...ple.JavaApplicationLauncher      0x00005cc3 launchJavaApplication + 39
8   cc.arduino.Arduino                  0x00001e8a 0x1000 + 3722
9   cc.arduino.Arduino                  0x00001cec 0x1000 + 3308
10  cc.arduino.Arduino                  0x00001c19 0x1000 + 3097

Thread 1:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib                  0x92490942 kevent + 10
1   libSystem.B.dylib                  0x9249105c _dispatch_mgr_invoke + 215
2   libSystem.B.dylib                  0x92490519 _dispatch_queue_invoke + 163
3   libSystem.B.dylib                  0x924902be _dispatch_worker_thread2 + 240
4   libSystem.B.dylib                  0x9248fd41 _pthread_wqthread + 390
5   libSystem.B.dylib                  0x9248fb86 start_wqthread + 30

Thread 2:
0   libSystem.B.dylib                  0x9248f9d2 __workq_kernreturn + 10
1   libSystem.B.dylib                  0x9248ff68 _pthread_wqthread + 941
2   libSystem.B.dylib                  0x9248fb86 start_wqthread + 30

Thread 3 Crashed:
0   libjvmlinkage.dylib                0x000a0d52 JVM_GetInterfaceVersion + 18
1   libjava.jnilib                      0x000af06d JNI_OnLoad + 33
2   libjvm.dylib                        0x028148e9 0x2800000 + 84201
3   libjvm.dylib                        0x02814377 0x2800000 + 82807
4   libjvm.dylib                        0x02814345 0x2800000 + 82757
5   libjvm.dylib                        0x0280e54b 0x2800000 + 58699
6   libjvm.dylib                        0x028018a3 0x2800000 + 6307
7   libjvm.dylib                        0x029f7309 JNI_CreateJavaVM_Impl + 185
8   ...ple.JavaApplicationLauncher      0x000075be startJavaApplication + 3595
9   ...ple.JavaApplicationLauncher      0x000067b1 runJava(LauncherArgsStruct*) + 78
10  ...ple.JavaApplicationLauncher      0x0000675b java_main_stub(void*) + 22
11  libSystem.B.dylib                  0x9249781d _pthread_start + 345
12  libSystem.B.dylib                  0x924976a2 thread_start + 34

Thread 4:
0   libSystem.B.dylib                  0x9246a0fa mach_msg_trap + 10
1   libSystem.B.dylib                  0x9246a867 mach_msg + 68
2   libSystem.B.dylib                  0x924d5e18 mach_msg_server + 520
3   libjvm.dylib                        0x0280ed25 0x2800000 + 60709
4   libjvm.dylib                        0x0280eae5 0x2800000 + 60133
5   libjvm.dylib                        0x02ac6091 JVM_RaiseSignal + 442177
6   libSystem.B.dylib                  0x9255faf2 _pthread_body + 27

Thread 3 crashed with X86 Thread State (32-bit):
 eax: 0x00000000  ebx: 0x028146fb  ecx: 0x00500d80  edx: 0xb0903750
 edi: 0xb0903750  esi: 0x000af05c  ebp: 0xb0903658  esp: 0xb0903650
  ss: 0x0000001f  efl: 0x00010286  eip: 0x000a0d52   cs: 0x00000017
  ds: 0x0000001f   es: 0x0000001f   fs: 0x0000001f   gs: 0x00000037
 cr2: 0x0000000c

Binary Images:
   0x1000 -     0x1fff +cc.arduino.Arduino 0021 (0021) <5E54AC31-1068-E190-4963-CAF51A6A915A> /Applications/Arduino.app/Contents/MacOS/JavaApplicationStub
   0x5000 -     0xfff7  com.apple.JavaApplicationLauncher 13.3.0 (13.3.0) <869D5EC4-730B-B902-6CD3-C6946815DE37> /System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Versions/A/J
avaApplicationLauncher
  0x17000 -    0x1fff7  com.apple.JavaVM 13.3.0 (13.3.0) <305C2162-CCF2-1D2A-EE2B-B7D666DEA849> /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM
  0x82000 -    0x8aff7  libverify.dylib 1.0 (1.0) <5E6D4960-086E-AC8B-5428-8271E5757EB4> /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Libraries/libverify.d
ylib
  0x8f000 -    0x97ff7  JavaNativeFoundation ??? (???) <2969E61F-2A16-2A87-1B39-777B86F8230A> /System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks/JavaNativeFoun
dation.framework/Versions/A/JavaNativeFoundation
  0xa0000 -    0xa7ff3  libjvmlinkage.dylib ??? (???) <5EC4F027-FDF1-C828-6419-F51B9BE15B03> /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvmlink
age.dylib
  0xae000 -    0xcbff7  libjava.jnilib ??? (???) <153634A3-2CC3-8ED3-7DD8-6A9A7499B7C5> /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Libraries/libjava.jni
lib
0x2800000 -  0x2b51fe3  libjvm.dylib ??? (???) <D1F32456-468F-9588-47FF-8A31D0E206FE> /System/Library/Frameworks/JavaVM.framework/Versions/1.5.0 copy/Home/bundle/Libraries/libjvm.dylib
0x8fe00000 - 0x8fe4162b  dyld 132.1 (???) <A4F6ADCC-6448-37B4-ED6C-ABB2CD06F448> /usr/lib/dyld
0x90003000 - 0x9000cff7  com.apple.DiskArbitration 2.3 (2.3) <E9C40767-DA6A-6CCB-8B00-2D5706753000> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x90210000 - 0x90210ff7  com.apple.CoreServices 44 (44) <AC35D112-5FB9-9C8C-6189-5F5945072375> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x90218000 - 0x90219ff7  com.apple.audio.units.AudioUnit 1.6.3 (1.6.3) <959DFFAE-A06B-7FF6-B713-B2076893EBBD> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
0x9021a000 - 0x9023cfef  com.apple.DirectoryService.Framework 3.6 (621.3) <05FFDBDB-F16B-8AC0-DB42-986965FCBD95> /System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryServic
e
0x90268000 - 0x9028cff7  libJPEG.dylib ??? (???) <5CE96981-6B2A-D15B-4A17-E7BD329095B6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/I
mageIO.framework/Versions/A/Resources/libJPEG.dylib
0x9030f000 - 0x9043dfe7  com.apple.CoreData 102.1 (251) <E6A457F0-A0A3-32CD-6C69-6286E7C0F063> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
0x9043e000 - 0x90442ff7  IOSurface ??? (???) <66E11D8E-CF4B-EFD0-37F9-20177C647021> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
0x90443000 - 0x9047bff7  libcups.2.dylib 2.8.0 (compatibility 2.0.0) <76C02F5C-98FD-BD64-B5FB-C698FB76EA25> /usr/lib/libcups.2.dylib
0x9065c000 - 0x9070aff3  com.apple.ink.framework 1.3.3 (107) <57B54F6F-CE35-D546-C7EC-DBC5FDC79938> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/
Versions/A/Ink
0x9076b000 - 0x9076bff7  com.apple.vecLib 3.6 (vecLib 3.6) <7362077A-890F-3AEF-A8AB-22247B10E106> /System/Library/Frameworks/vecLib.framework/Versions/A/vecLib
0x9076c000 - 0x90815ff7  com.apple.CFNetwork 454.9.8 (454.9.8) <DB2A5C33-E833-1B3A-4DE0-5FF172B2048B> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwor
k.framework/Versions/A/CFNetwork
0x90834000 - 0x90865ff7  libGLImage.dylib ??? (???) <9340012D-595A-6243-9C97-7D30D76D9D9E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dyli
b
0x90899000 - 0x9094fffb  libFontParser.dylib ??? (???) <067DC1A2-764B-41EA-B07E-4205472749B7> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/A
TS.framework/Versions/A/Resources/libFontParser.dylib
0x90950000 - 0x90a00ff3  com.apple.ColorSync 4.6.3 (4.6.3) <AA1076EA-7665-3005-A837-B661260DBE54> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/C
olorSync.framework/Versions/A/ColorSync
0x90a09000 - 0x90a1dfe7  libbsm.0.dylib ??? (???) <14CB053A-7C47-96DA-E415-0906BA1B78C9> /usr/lib/libbsm.0.dylib
0x90a1e000 - 0x90a62fe7  com.apple.Metadata 10.6.3 (507.10) <630494FA-3BB3-EDD3-E10B-8DAAF4831E26> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata
.framework/Versions/A/Metadata
0x90bba000 - 0x90c3cffb  SecurityFoundation ??? (???) <3670AE8B-06DA-C447-EB14-79423DB9C474> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFound
ation
0x90c51000 - 0x90d7dfff  com.apple.audio.toolbox.AudioToolbox 1.6.3 (1.6.3) <F0D7256E-0914-8E77-E37B-9720430422AB> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
0x90daf000 - 0x90e68fe7  libsqlite3.dylib 9.6.0 (compatibility 9.0.0) <16CEF8E8-8C9A-94CD-EF5D-05477844C005> /usr/lib/libsqlite3.dylib
0x90e7c000 - 0x90e86ffb  com.apple.speech.recognition.framework 3.11.1 (3.11.1) <EC0E69C8-A121-70E8-43CF-E6FC4C7779EC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognit
ion.framework/Versions/A/SpeechRecognition
0x90e87000 - 0x90e87ff7  com.apple.ApplicationServices 38 (38) <8012B504-3D83-BFBB-DA65-065E061CFE03> /System/Library/Frameworks/ApplicationServices.f

**Comment by ffissore** [comment]
Fixed with https://github.com/arduino/Arduino/commit/21203cbe1b1194e0ae99018ffc4de3de8878da5a#diff-10
