### ISSUE TITLE
Srduino Mega USB 3.0 Problem

### ISSUE THREAD

**Issue by Carlitos1991Segura** [arduino/Arduino#3902]
Hello, i´m new in this world, i buy a ultrabook asus zenbook with only 3 ports USB 3.0 Arduino Mega   can´t upload scketch to the arduino megaboard, my pc say that arduino is old, tat in USB 3.0 port no function well. help me please

**Comment by ffissore** [comment]
Please consult the [Arduino forum](http://forum.arduino.cc/). Github issues are for bugs with the software, not for support requests.
