### ISSUE TITLE
Manager Board issue when a server is off

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3906]
This morning, i wanted to use the Boards Manager but the web page https://www.mattairtech.com/ was off , so the ide returned me an error and after this error the ide don't continue to read other .json files . Is it possible to have a pop up error if a .json file isn't found or anything other error is found, and than the ide continue to read other .json file !
Sorry for my english !!!

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
