### ISSUE TITLE
Gemma does not define LED_BUILTIN

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#3907]
But AFAIU, it does have a built in led.

**Comment by pwillard** [comment]
Locate your IDE program installation folder, and under `\hardware\arduino\avr\variants\gemma` edit "pins_arduino.h".  In the file, under your pin constants for A0 - A3, add the following line:

   #define LED_BUILTIN 1

   Save the file and start the IDE.

And yes... Adafruit *should* have done this...   for shame.

**Comment by agdl** [comment]
Done thank you!

**Comment by pwillard** [comment]
FYI: Adafruit Trinket needs the same love...
