### ISSUE TITLE
Houly build 2-10-2015 4h41 read also .ino files into  folder

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3909]
With this new version, the ide read old files saved into folders that exist into my sketch project 
![bugg](https://cloud.githubusercontent.com/assets/8189970/10250869/b5ebd470-692d-11e5-858c-28a57ed81064.jpg)
IDE read also .ino or .pde files found into the folder 'INO en cours' or 'InOut & Doc' .

That was not the case with the older IDE version !
It's a new feature or an issue ?

**Comment by ffissore** [comment]
If this folder is a library, this was fixed since arduino-builder beta22. Please download a fresh hourly http://www.arduino.cc/en/Main/Software#hourly

**Comment by per1234** [comment]
@ffissore I believe what pierrotm777 is referring to is demonstrated by this example(using Arduino IDE 1.6.6 2015/10/07 06:43):

folder structure:
```
Blink
|-- Blink.ino
|-- backup
|   |-- Blink1.ino
```
If you compile Blink.ino you get:
```
E:\Stuff\misc\electronics\arduino\temp\Blink\backup\Blink1.ino: In function 'void setup()':

E:\Stuff\misc\electronics\arduino\temp\Blink\backup\Blink1.ino:1:6: error: redefinition of 'void setup()'

 void setup() {

      ^

Blink:1: error: 'void setup()' previously defined here

 void setup() {

      ^

E:\Stuff\misc\electronics\arduino\temp\Blink\backup\Blink1.ino: In function 'void loop()':

E:\Stuff\misc\electronics\arduino\temp\Blink\backup\Blink1.ino:6:6: error: redefinition of 'void loop()'

 void loop() {

      ^

Blink:6: error: 'void loop()' previously defined here

 void loop() {

      ^

exit status 1
'void setup()' previously defined here
```
I'm not sure whether this is a bug or a new feature but if it's a feature then Blink1.ino should be shown as a tab in the IDE.

**Comment by ffissore** [comment]
Confirm. Thank you!

**Comment by ffissore** [comment]
This issue was moved to arduino/arduino-builder#31
