### ISSUE TITLE
Submit FastLED into the library manager

### ISSUE THREAD

**Issue by focalintent** [arduino/Arduino#3917]
Library: FastLED
Version: 3.1.0
Github URL: https://github.com/FastLED/
Release Tag: https://github.com/FastLED/FastLED/tree/v3.1.0

and there's a library.properties file in place.

(I was unable to find a list of accepted architectures, and since fastled supports avr and multiple arm platforms (atmel's sam3x8e & samd21, freescale's k20 and kl26, nordic's nrf51822, etc...) I went with * for architecture for now).

**Comment by ffissore** [comment]
Added. Thanks!
