### ISSUE TITLE
New libraries request

### ISSUE THREAD

**Issue by stevemarple** [arduino/Arduino#3930]
Please add the following libraries:

https://github.com/stevemarple/SoftWire
https://github.com/stevemarple/RTCx
https://github.com/stevemarple/MCP342x
https://github.com/stevemarple/MicroNMEA
https://github.com/stevemarple/HIH61xx
https://github.com/stevemarple/MLX90614
https://github.com/stevemarple/AS3935

Thanks.

**Comment by ffissore** [comment]
Added. Thanks!
