### ISSUE TITLE
tone() for Due

### ISSUE THREAD

**Issue by chrisrichards01** [arduino/Arduino#3937]
Please add to documentation that tone() does not currently work with the Due.

**Comment by VogonJeltz** [comment]
... and then please add a lib that would work with the Due...

**Comment by q2dg** [comment]
...and what about Zero? I'm in Europe and I can't try it.

**Comment by aethaniel** [comment]
@q2dg tone has been implemented for the Zero a while ago ;-)
https://github.com/arduino/ArduinoCore-samd/commits/master/cores/arduino/Tone.cpp

**Comment by VogonJeltz** [comment]
but not for the Due (which is far longer on the market) ?

**Comment by cmaglie** [comment]
Duplicate of #2362

**Comment by VogonJeltz** [comment]
I don't see how it now should work for the Due - can you provide a example source code please?

**Comment by cmaglie** [comment]
The tone function is not implemented on the Due, and the code posted by @aethaniel is for the Zero board and cannot be used for the Due. That's why #2362 is still open.

**Comment by VogonJeltz** [comment]
ok, thank you, I didn't understand this.
is there a timeline about when it will be available?

**Comment by VogonJeltz** [comment]
https://github.com/arduino/Arduino/issues/2362

why hadn't this been fixed yet?!?
