### ISSUE TITLE
Arduino Boards Manager registration

### ISSUE THREAD

**Issue by akkoyun** [arduino/Arduino#3943]
Hi,
We develope a board named LVX M1 and we want to register boards manager. How can we do this ? can you help us ?

**Comment by q2dg** [comment]
Well, I think these documents will help you:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x---package_index.json-format-specification
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls
