### ISSUE TITLE
AM/PM handling with 12-hour RTC setting?

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#3944]
If you put the RTC library in 12-hour mode, how does it handle AM and PM? Is there any way to specify whether or not an hour is AM or PM? Or tell, when you get the time, whether it's AM or PM? If not, should we just eliminate 12-hour mode?

**Comment by VogonJeltz** [comment]
maybe poll the time in 24 hour intermediately?
char * hourfmt= (hour24 != hour12 ? "PM" : "AM") ;

**Comment by agdl** [comment]
@damellis you are right, at the moment, we have no method to understand the time representation, however it ca be simply implemented pollig the control bit RTC_MODE2_CTRL_CLKREPin RTC->MODE2.CTRL.reg (that you set with the rtc.begin(bool timeRep). I also wnt to add methods that returns to you a string for time and date. What do you think about these improvements?

**Comment by damellis** [comment]
I think you could start by just dropping 12 hour support, and letting the
user's sketch do the translation from 24 hour to 12 hour time if they want
to print it that way. If we do add date formatting code, it would be good
to include 12 hour options there, but that also feels like an extension
that isn't necessarily a solution to this particular issue.

On Mon, Oct 19, 2015 at 12:38 AM, Arturo Guadalupi <notifications@github.com

**Comment by agdl** [comment]
@damellis @VogonJeltz I removed the 12 hour support as you suggested. It can be implemented in the sketch with no so may effort

https://github.com/arduino-libraries/RTCZero/commit/c7d65d21feb6bb60c69a277e73076f023f1b7ac7

**Comment by agdl** [comment]
I'm closing this. Reopen it if there are further requests please

**Comment by agdl** [comment]
We have this PR. What do you think about it?

**Comment by agdl** [comment]
Adding @cmaglie and @facchinm to the loop

**Comment by damellis** [comment]
Personally, I don't really see the value of 12 hour time. It just seems
more complicated to call one function to get the hours and another function
to get AM vs. PM, when you could just get one number from 0 to 23. Are
there people that are asking for 12 hour functions? What's the use case?

**Comment by agdl** [comment]
@damellis ok i asked also to Gabriel his opinion, and he agreed to remove it. So I'm closing this again!

**Comment by ShoneVj** [comment]
i think its better to setDS1307 in 24 hr mode and later convert it to 12 hr .Bcoz if we config it in 12 hr mode it is not possible to read whether it is am or pm.. i not pretty sure about this any way.
