### ISSUE TITLE
Add library to Library Manager

### ISSUE THREAD

**Issue by Mokolea** [arduino/Arduino#3952]
Hi, please add my library to the Library Manager: https://github.com/Mokolea/InputDebounce
Thanks

**Comment by cmaglie** [comment]
Done, thanks!

**Comment by NicoHood** [comment]
Working sundays, not bad. You must love your job, dont you? Respect!

**Comment by cmaglie** [comment]
Of course I do... like every one else contributing here ;-)

**Comment by Mokolea** [comment]
:)
