### ISSUE TITLE
Find button only has focus the first time the Find dialog is opened

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3959]
Using Arduino IDE 1.6.6 2015/10/09 12:42 with Windows 7 64 bit
- Open IDE
- Edit>Find - the Find button has focus
- Close the Find dialog
- Edit>Find - the Find button doesn't have focus

**Comment by ffissore** [comment]
Can't replicate on linux. Need to wait until I get access to a windows box

**Comment by ffissore** [comment]
Confirm. Working on it

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
