### ISSUE TITLE
Arduino Zero & Due lack SPI.transfer16()

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#3961]
The transfer16() function was added to the SPI library quite some time ago.  It's been documented on the website.

https://www.arduino.cc/en/Reference/SPITransfer

It works on AVR boards, but Arduino Zero & Due don't have transfer16() in their SPI libraries yet.

**Comment by cmaglie** [comment]
Fixed with #4081 and arduino/ArduinoCore-samd#59
