### ISSUE TITLE
Enum cannot contain true/false 

### ISSUE THREAD

**Issue by cb88** [arduino/Arduino#3965]
But the following in a fresh sketch to break it.
```
enum ternary {
  unknown,
  true,
  false
};
```

**Comment by NicoHood** [comment]
Those names are reserved. Thats all. Thats c/c++ i'd say.
You could use TRUE and FALSE

**Comment by cb88** [comment]
Hmm... reserved to mean 0 and 1 or some other value? Which would mean you couldn't do true = someValue in an enum.

I mean having true and false in an enum makes sense... unless there is just some arbitrary limitation to not be able to do so. The wiki indicates this as doable here: http://playground.arduino.cc/Code/Enum

**Comment by NicoHood** [comment]
true = true????
This makes no sense. however its a c++ question, so you might ask on stackoverflow for help. This is not an Arduino issue.

**Comment by NicoHood** [comment]
Oh, the wiki aka playground is not official. Its.. yeah a wiki... with a crapy article. Someone should remove it.

**Comment by cmaglie** [comment]
`true` and `false` are reserved keywords in C/C++, like `for`, `if`, `while`. This is a complete list:
http://it.cppreference.com/w/cpp/keyword

Simply you cannot use them for user-defined types.

And yes, the article on the playground should be fixed/removed...
