### ISSUE TITLE
Copy as HTML removes line breaks from multi-line comments

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3970]
Using Arduino IDE 1.6.6 2015/10/12 05:42 with Windows 7 64 bit
Issue reported in http://forum.arduino.cc/index.php?topic=352672.0
- write multi-line comment:
```
/*
 * multi
 * line
 * comment
 */
```
- select multi-line comment
- Edit>Copy as HTML:
```
<pre>
<font color="#95a5a6">/*</font><font color="#95a5a6"> * multi</font><font color="#95a5a6"> * line</font><font color="#95a5a6"> * comment</font><font color="#95a5a6"> */</font>

</pre>
```
Which produces the output:
```
/* * multi * line * comment */
```

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
