### ISSUE TITLE
Update PUSB docs

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#3976]
https://github.com/arduino/Arduino/wiki/PluggableUSB-and-PluggableHID-howto

**Comment by facchinm** [comment]
Looks better now? :wink:

**Comment by NicoHood** [comment]
Yep.

But please fix this:
https://github.com/arduino-libraries/MIDIUSB/blob/pusb_newApi/src/MIDIUSB.cpp#L158-L165


````cpp
	if (r > 0){
		return r;
	}
	return 0;
```

Not sure if size_t can be negative though, but the style looks not okay, I needed to mention this.
