### ISSUE TITLE
IDE 1.6.5 Windows 8.1

### ISSUE THREAD

**Issue by Aliwalio** [arduino/Arduino#3987]
Having upgraded from 1.0.5 to 1.6.5 I have had to revert to old IDE  as new version seems unusable. Have tried 1.6.0 with same results.

With both these new versions the WMI Provider Host process hogs 30% of CPU and the IDE stalls. Seems also to have something to do with plugging in the USB cable to board. Also, intermittently, port number is not recognised or lost.

Some unkind comments re this problem also here : https://www.reddit.com/r/arduino/comments/2vbcm7/arduino_ide_16_is_released_download_it_now/

Having reverted to 1.0.6 everything works fine.

**Comment by ffissore** [comment]
It looks like a windows problem. Try checking this http://answers.microsoft.com/en-us/windows/forum/windows_8-performance/wmi-provider-host-constantly-disrupting/8e1ead34-d25f-4ee5-8eb1-7a6afe3c0696?auth=1
Disabling your antivirus is also an option, although not really feasible for windows users

**Comment by Aliwalio** [comment]
Mille grazie Federico. Very kind of you to respond so quickly.

I will try the workarounds suggested when I get a moment and who knows the Windows 10 upgrade (eventually) might fix anyway…..

I see also that you have earmarked this issue for 1.6.6 so good luck with it.

Regards

Alistair
