### ISSUE TITLE
Auto Format moves error highlight to the first line

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#3988]
Using Arduino IDE 1.6.6 2015/10/14 10:42 with Windows 7 64 bit
- Add the following code:
```
void setup() {}
 void loop() {}
x
```
- Verify - line 3 is highlighted as error.
- Edit > Auto Format - line 1 is now highlighted as error

**Comment by ffissore** [comment]
Highlight removed when autoformatting. This is not ideal but highlighying in rsyntaxtarea has some issues. See https://github.com/bobbylight/RSyntaxTextArea/issues/150
