### ISSUE TITLE
Please provide an option to disable the animation for matching braces

### ISSUE THREAD

**Issue by nickgammon** [arduino/Arduino#3991]
See: http://forum.arduino.cc/index.php?topic=353730.0

Apparently in IDE 1.6.5 an animation was added for matching brackets/braces when you click on the or merely move the keyboard cursor over them.

As reported in the above thread, some users find this distracting and annoying.

Please make the animation optional. It drags the eye away from what you are doing when a different part of the page "flickers" as the corresponding bracket/brace jumps into life with an animated box around it.

**Comment by ffissore** [comment]
Disabled by default. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
