### ISSUE TITLE
Ethernet example code doesn't work

### ISSUE THREAD

**Issue by richw42** [arduino/Arduino#3992]
At the URL
file:///C:/Program%20Files%20(x86)/Arduino/reference/arduino.cc/en/Reference/ServerAvailable.html

I see the following code:

```
if (client == true) {
    // read bytes from the incoming client and write them back
    // to any clients connected to the server:
    server.write(client.read());
  }
```

In my tests, the (client == true) test is never true.
Changing the test to (client) fixed the problem for me.
This same code is found in other places in the documentation.
Downloaded install file is arduino-1.6.5-r5-windows.exe
Using Arduino Ethernet board.
Windows 7-64

**Comment by richw42** [comment]
Hmmm, maybe it makes a difference:
Downloaded install file is arduino-1.6.5-r5-windows.exe
Using Arduino Ethernet board.
Windows 7-64

**Comment by agdl** [comment]
@richw42 unlucky the documentation provided with the downloaded IDE has some update problem. Please always refer to the online documentation that is always updated and maintained.

**Comment by agdl** [comment]
I'm closing this
