### ISSUE TITLE
Library Manager, update CRC

### ISSUE THREAD

**Issue by plinioseniore** [arduino/Arduino#3996]
Hi,

I've messed-up a bit and used --force for a tag, so now it has a different CRC and the Library Manager doesn't complete the installation of the library.

Could you please reset the CRC for 

```
    {
      "name": "souliss",
      "version": "7.1.0",
      "author": "Souliss Team",
      "maintainer": "Souliss Team",
      "sentence": "SmartHome Networking Framework",
      "paragraph": "Build a network of multiple nodes over Ethernet, Wireless and RS485 for your smart home",
      "website": "http://souliss.github.io",
      "architectures": [
        "avr",
        "esp8266"
      ],
      "types": [
        "Contributed"
      ],
      "url": "https://github.com/souliss/souliss/archive/v7.1-friariello.0.zip",
      "archiveFileName": "souliss-7.1.0-github.zip",
      "size": 621126,
      "checksum": "SHA-256:b7a44bcffb1ae1fb6cc855e5a43d6e446dffcfc1d9be47b89172432fba5e3bf2"
    },
```

Thanks

**Comment by matthijskooijman** [comment]
I suspect this happens automatically during the weekly cleanup run on sunday evening, so could you please check again tomorrow and report if the problem still exists then?

**Comment by plinioseniore** [comment]
@matthijskooijman just had a try, the JSON has been updated but the checksum is still the old one. At which time is supposed to run this clean-up?

**Comment by matthijskooijman** [comment]
Not sure, on sunday evening (CEST, probably) I believe. Should have ran now, I think.

**Comment by plinioseniore** [comment]
Unfortunately I still get a CRC error, I've checked that the JSON file has been updated by the IDE.

**Comment by cmaglie** [comment]
It seems that you pushed the release right after the weekly cron job. I've triggered it manually and now the CRC seems fixed.

**Comment by plinioseniore** [comment]
Thanks
