### ISSUE TITLE
GSM libraries incompatible with Intel Edison board

### ISSUE THREAD

**Issue by prudencer** [arduino/Arduino#4001]
Is there a solution to the issue of incompatible architectures of the Intel Edison board and the gsm libraries? Because it does not allow me to import gsm.h at all because of that issue.
Please help.

**Comment by agdl** [comment]
@prudencer I know there was an similar issue with the Galileo, however fort example in this tutorial http://www.instructables.com/id/GSM-Controlled-Star-Light/ there is a link to a GSM library that works with the Galileo. Can you give a try and post a feedback please?

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Reopen it if needed please
