### ISSUE TITLE
Defective eagle files for arduino Due

### ISSUE THREAD

**Issue by QRikard** [arduino/Arduino#4011]
Eagle files downloaded from https://www.arduino.cc/en/Main/ArduinoBoardDue a few days (?) ago

This is the error message:
"Board and schematic not consistent!
...
Use ERC for detailed report"

When running the ERC tool you get 4 consistency errors: 
"NET Class 2 has different Clearence, Drill, Name and Width"

Solution: Open the eagle schematic go to edit tab and Net Classes... 
Under #2 fill in gnd, 8mil, 16mil, 8mil in corresponding order (look at same menu in the board view) and run the ERC and save. Then schematic and board should become consistent again. 

If possible please try to minimize the amount of ERC and DRC errors in the design when possible. 

Please do this and update the files on the site so others wont need to debug it. 

Best regards // Rikard

**Comment by agdl** [comment]
@QRikard  done thank you!
