### ISSUE TITLE
New BME280 library and examples from SparkFun

### ISSUE THREAD

**Issue by marshalltaylorSFE** [arduino/Arduino#4013]
Hello,

I've got a new library to add to the manager.  Please include it and let me know if there is anything else I need to do.

It's master of https://github.com/sparkfun/SparkFun_BME280_Arduino_Library

Thank you,
MTaylor

**Comment by NicoHood** [comment]
The link is broken.

**Comment by marshalltaylorSFE** [comment]
Sorry about that, I forgot it was still private.  Repo is now public and the link should work!

Thanks,

**Comment by cmaglie** [comment]
Added, thanks!
