### ISSUE TITLE
can't upload atmega8 bootloader

### ISSUE THREAD

**Issue by coccobello27** [arduino/Arduino#4024]
"efuse" memory type not defined for part "ATmega8"
Error while burning bootloader.

**Comment by rigelinorion** [comment]
Try this
https://github.com/arduino/Arduino/issues/2541#issuecomment-136123188

**Comment by sandeepmistry** [comment]
Closing, based on https://github.com/arduino/Arduino/issues/2541 this is fixed and released already.
