### ISSUE TITLE
http://playground.arduino.cc/Learning/AtmegaStandalone   broken link

### ISSUE THREAD

**Issue by thegman52** [arduino/Arduino#4028]
There is a broken link on this page: http://playground.arduino.cc/Learning/AtmegaStandalone

**Comment by q2dg** [comment]
Well,this is the Playground...so you can edit it simply clicking in "Edit" link (predefined password is ok) and solving the issue by yourself

**Comment by ffissore** [comment]
Indeed. Playground is user generated, not maintained by arduino
