### ISSUE TITLE
problem with installing LIFA for Arduino UNO R3

### ISSUE THREAD

**Issue by amkamyab** [arduino/Arduino#4036]
hello
when i try to install  LIFA ( labview interface for Arduino), a message appear and my labview cant connect to Arduino.
1 - i installed LIFA on labview over VIPM
this is message:
```
Arduino: 1.6.6 Hourly Build 2015/10/27 05:42 (Windows 8.1), Board: "Arduino/Genuino Uno"

C:\Program Files (x86)\Arduino\LIFA_Base\LIFA_Base.ino:26:67: fatal error: OneWire.h: No such file or directory

 #include <OneWire.h>                //For use with OneWire devices

                                                                   ^

compilation terminated.

exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
```

**Comment by facchinm** [comment]
Hi @amkamyab ,
you simply need to install OneWire library by Paul Stroffegen; since you are using 1.6.6 you can download it via Library Manager :smile:

**Comment by amkamyab** [comment]
thanks for your reply. i will do it and let you warn about it.

**Comment by facchinm** [comment]
Hi @amkamyab , any news? Did installing the library solve the issue?

**Comment by amkamyab** [comment]
hello
i used arduino version 1.0.5 and it solved problem. it is look like that new version i downloaded didn't match with my arduino.
any way thanks for your help.
