### ISSUE TITLE
IDE 1.6.5 with ELCapitian OSX 10.11.1 

### ISSUE THREAD

**Issue by Randcook** [arduino/Arduino#4038]
1. No Longer see any TTY ports?
2. Very Very slow to open Sketches 

I am very disappointed and frustrated with IDE 1.6.5 on OSX 10.11.1.

I guess a severe LACK of TESTING for such obivious  Errors

**Comment by ffissore** [comment]
Autoclosed issue! Thanks! Did you realized El Capitan has been released 3 months and a half AFTER 1.6.5?

**Comment by PaulStoffregen** [comment]
I personally tested 1.6.5 with El Capitan, just last week.  It worked very well.  I was able to access serial devices and everything ran quickly.

**Comment by Randcook** [comment]
Not sure what you are saying?
Cheers
Peter

On Wednesday, 28 October 2015, Federico Fissore <notifications@github.com>
wrote:

> Autoclosed issue! Thanks! Did you realized El Capitan has been released 3
> months and a half AFTER 1.6.5?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4038#issuecomment-151893261>.
>


-- 
Cheers
Peter
