### ISSUE TITLE
User names with accents not correctly supported in Arduino IDE on Windows

### ISSUE THREAD

**Issue by noeldev** [arduino/Arduino#4041]
The "Sketchbook location" and preferences.txt file paths are invalid in the Arduino IDE, File > Preferences properties if the user name contains accents or dieresis; such characters are replaced by other signs for example a Per Mille sign (‰). This also lead to the creation of folders with the wrong names on the disk.

**Comment by ffissore** [comment]
Which os are you using? Can you tell the actual location of your sketchbook so we may reproduce your issue?

**Comment by ffissore** [comment]
This should be fixed in the current hourly build http://www.arduino.cc/en/Main/Software#hourly. Can you please give it a try?

**Comment by noeldev** [comment]
The OS is Windows 10 Pro, x64. The default location of the Sketchbook was "C:\Users\Noël\Documents" which appeared as "C:\Users\No‰l\Documents" in the IDE and a "C:\Users\No‰l" folder was created which includes sub-folders: AppData\Roaming\Arduino15 with 4 files including preferences.txt. I will give the hourly build a try, I will uninstall the current version 1.6.5 and delete the invalid folders first. Thanks.

**Comment by ffissore** [comment]
Yeah, it looks a lot like #3360 which was fixed

**Comment by noeldev** [comment]
Indeed, this issue is fixed in the latest hourly build: the paths look ok in the IDE and the correct folders are used on the disk, no more No‰l folders. Thanks.
