### ISSUE TITLE
Arduino leonardo windows 8.1 install problem.

### ISSUE THREAD

**Issue by hamitk** [arduino/Arduino#4044]
How can i install Arduino leonardo?

windows can not install Leonardo...

Thanks

**Comment by NicoHood** [comment]
You need to install the drivers inside the drivers folder of the ide.

**Comment by ffissore** [comment]
Please consult the [arduino forum](http://forum.arduino.cc/). This issue repository is for bugs and feature requests for the IDE, not for generic support

**Comment by hamitk** [comment]
i am trying installing from drivers folder, windows say " no driver "
