### ISSUE TITLE
Failed to install driver Arduino on Win 10 64bit

### ISSUE THREAD

**Issue by hungthuanmk** [arduino/Arduino#4046]
I try installing driver for Arduino Leonardo on my Win 10 64bit but it's seems failed. I try with Uno and I realize that my windows can't  receive any board (same issue).
![image](https://cloud.githubusercontent.com/assets/12544161/10824933/2f762d78-7e95-11e5-8e95-9ecd45abaf5f.png) 
Whileas other computers are totally normal (I tested with Win 7 and Win 8.1 64bit)
Please help me, thanks!

**Comment by ffissore** [comment]
Please consult the [arduino forum](http://forum.arduino.cc/). This issue repository is for bugs and feature requests for the IDE, not for generic support
