### ISSUE TITLE
K12 environment and Windows Group Policy

### ISSUE THREAD

**Issue by pamccall** [arduino/Arduino#4052]
We are using this in Career Tech in our high schools and we use Windows Group Policy to prevent student users from unintentionally or intentionally deleting files from PCs that would prevent the PC from working.  After install this software recently and making sure the C:\Program Files (x86)\Arduino path was open to be accessed by students the program still will not launch.  When you double click the icon the screen flashes but the program doesn't open.  It seems like the software may be going somewhere else other than this path when launched that may be blocked but I can't tell where in the OS that is happening?  Anyone have any insight into this that can help?

**Comment by NicoHood** [comment]
%appdata%/Arduino15 or something like that.
In the home folder is also a sketchbook folder named Arduino where you can place libraries and save sketches. This also should be unlocked.

**Comment by ffissore** [comment]
Indeed.
That path is used to store preferences, boards support installed through boards manager, and libraries installed through library manager.
If you want the IDE to use its installation path, you need to create a `portable` folder inside it.

However, the IDE needs a folder where to store its sketchbook, which by default on Windows is the `Arduino` in `My Documents` folder.
This be changed via File > Preferences

**Comment by NicoHood** [comment]
I heard about the portable folder never before. Is this somewhere documented? Maybe you should add this to the .zip files by default or as Setting? Thats sounds like a cool feature on school PCs which are mostly windows and blocked.

**Comment by pamccall** [comment]
I have tried adding to Security Settings in Group Policies the following:
 %AllUsersProfile%\Arduino 15
%SystemDrive%\Users\Default\AppData\Roaming\Arduino15
%ProgramFiles%(x86)\Arduino 
None of these helped.  In addition we opened the Program and went to File and Preferences and changed the Sketchbook path to a mapped drive for the students where they can save.  Students can not save to My Documents on the local machine.  We force them to save to a network drive so that we can backup their work.  When we try to open the program we still only get a brief flash and then the program never opens.  I am at a loss as to what else we should try.  Any ideas?

**Comment by ffissore** [comment]
Have you created a `portable` folder, as I mentioned in https://github.com/arduino/Arduino/issues/4052#issuecomment-152519782 ?

**Comment by pamccall** [comment]
Yes, I have created that folder but still same result

**Comment by pamccall** [comment]
Yes, I have created that folder.  Still same result.

On Fri, Oct 30, 2015 at 2:18 PM, Federico Fissore <notifications@github.com>
wrote:

> Have you created a portable folder, as I mentioned in #4052 (comment)
> <https://github.com/arduino/Arduino/issues/4052#issuecomment-152519782> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4052#issuecomment-152607436>.
>



-- 
Pam McCall
IT Systems Administrator
HCPS Technology

-- 


All e-mail correspondence to and from this address is subject to the North 
Carolina Public Records Law, which may result in monitoring and disclosure 
to third parties, including law enforcement.

**Comment by ffissore** [comment]
Try running the IDE from the command line with `arduino_debug.exe`. It will print an error message. Paste it here

**Comment by pamccall** [comment]
Students do not have access to command lines - restricted.  Program opens
file as an administrator so I am not sure running the debug from
there would be helpful.  Any other ideas?

On Fri, Oct 30, 2015 at 3:54 PM, Federico Fissore <notifications@github.com>
wrote:

> Try running the IDE from the command line with arduino_debug.exe. It will
> print an error message. Paste it here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4052#issuecomment-152635990>.
>



-- 
Pam McCall
IT Systems Administrator
HCPS Technology

-- 


All e-mail correspondence to and from this address is subject to the North 
Carolina Public Records Law, which may result in monitoring and disclosure 
to third parties, including law enforcement.

**Comment by ffissore** [comment]
Create a shortcut to `arduino_debug.exe` and prepend `C:\Windows\System32\cmd.exe /k ` (final space) to `Target`

**Comment by ffissore** [comment]
Then use that shortcut to start the IDE. An error message will be printed. Please paste it here

**Comment by pamccall** [comment]
Thanks!  We tried another route.  Another laptop has this software but the
previous version 16.1 and it works as a student on this version.  I just
downloaded and install this version after uninstalling the newest and
verified the older version works.  That tells me something in the source
code changed and for us that meant anyone who was a non-admin local use on
the PC could not use the new software.


On Mon, Nov 2, 2015 at 9:33 AM, Federico Fissore <notifications@github.com>
wrote:

> Then use that shortcut to start the IDE. An error message will be printed.
> Please paste it here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4052#issuecomment-153032398>.
>



-- 
Pam McCall
IT Systems Administrator
HCPS Technology

-- 


All e-mail correspondence to and from this address is subject to the North 
Carolina Public Records Law, which may result in monitoring and disclosure 
to third parties, including law enforcement.

**Comment by ffissore** [comment]
Good for you, although that doesn't help us finding the problem, which is likely to remain unresolved, unless someone else comes with more details

**Comment by pamccall** [comment]
I will try again later today to install on a different laptop and still get
the debugging info to you.


On Mon, Nov 2, 2015 at 10:48 AM, Federico Fissore <notifications@github.com>
wrote:

> Good for you, although that doesn't help us finding the problem, which is
> likely to remain unresolved, unless someone else comes with more details
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4052#issuecomment-153058785>.
>



-- 
Pam McCall
IT Systems Administrator
HCPS Technology

-- 


All e-mail correspondence to and from this address is subject to the North 
Carolina Public Records Law, which may result in monitoring and disclosure 
to third parties, including law enforcement.

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen this if needed
