### ISSUE TITLE
double-click to open sketch does not

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#4057]
windows 8.
double click sketch/sketch.ino
"sketch folder missing.  will create new default sketch folder if required, then stop talking about oneself in the third person."
click ok.
app quits.
....
try again, same results
....
click arduino icon.
app gives error message again.
click ok.
app opens two copies of sketch/sketch.ino

**Comment by ffissore** [comment]
Which version of the IDE are you using?

**Comment by i-make-robots** [comment]
OSX 10.10.1
Arduino 1.6.4

On Mon, Nov 2, 2015 at 1:31 AM, Federico Fissore <notifications@github.com>
wrote:

> Which version of the IDE are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arduino/Arduino/issues/4057#issuecomment-152969312>.
>



-- 
Dan Royer :: Marginally Clever <http://www.marginallyclevergroup.com/> ::
Raising Robot Literacy :: +1.604.916.2281

**Comment by Jed-SWSDT** [comment]
I can't duplicate that exact issue with Arduino 1.6.6 on OSX 10.10.5. But I do see a similar issue. If Arduino isn't running and I double-click a sketch it opens Arduino, but loads the last sketch I was working on, not that one I double-clicked on. 

Was able to get it to move it to a new folder. Double-click on sketch outside of a folder, opens Arduino to the WRONG sketch. Double-click on the sketch outside of the folder again and a different dialog box pops up for me:

"The file "xxx.ino" needs to be inside a sketch folder named "xxx". Create this folder, move the file, and continue?"

Was able to do it, at least on the desktop.

**Comment by ffissore** [comment]
Working on it

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
