### ISSUE TITLE
Place partner libraries immediately after Arduino libraries?

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#4060]
This is a detail, but it seems confusing to me to have "partner" libraries so near the bottom of the list in the library manager. Are these supposed to libraries created in an official partnership with Arduino? If so, wouldn't it make sense to place them after the "Arduino" category and before the "Recommended" category? To me, a library from an official partner seems more "official" than a library from a random third-party that we just happen to recommend.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
