### ISSUE TITLE
"Update available" pop-up notification not repositioned on window resize.

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#4068]
The little pop up window that displays "update available for some of your boards" (or libraries) isn't repositioned when the associated editor window is resized (just when that window is moved). So you get things like the attached screenshot.

<img width="763" alt="screen shot 2015-11-02 at 2 23 53 pm" src="https://cloud.githubusercontent.com/assets/405058/10896251/933d32c2-816d-11e5-961c-37a622f3ccd0.png">

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
