### ISSUE TITLE
io.h is not working on Arduion DUE in 1.6.5-r5

### ISSUE THREAD

**Issue by NiZi93** [arduino/Arduino#4070]
I was trying to connect MPU-6050 and getting gyro readings but compilation terminated by saying "fatal error: avr/io.h: No such file or directory"
what should i do?

**Comment by cmaglie** [comment]
`avr/io.h` is specific for AVR, the Due uses a SAM3X cpu, it's very likely that your sketch uses some AVR-specific feature that are, of course, not available on SAM.

You can try to remove `#include <avr/io.h>`, recompile to see which part of your sketch access directly the AVR registers and see if exists an architecture-independent way for doing the same thing.
