### ISSUE TITLE
Arduino resizing interface glitch

### ISSUE THREAD

**Issue by THPOONS** [arduino/Arduino#4073]
The Arduino 1.6.6 IDE update came with improvements. But whenever I use the bottom right corner to resize the interface, it seems to reset the top left corner to it's original position when the window opened. I am currently running on the newest OSX of Mac. Nothing major. Keep on coding :)

**Comment by ffissore** [comment]
Never seen this before. Are you saying the top left corner moves? Can you record a screencast?
