### ISSUE TITLE
1.6.6 rude popups

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#4080]
Arduino 1.6.6 in OSX 10.10.1 loading about dialog insists on being top-most, even when other applications are brought to the foreground.  The same behavior is repeated with "there are updates to your libraries".  These both feel about as polite as a website spam popup.  Please stop that.

**Comment by per1234** [comment]
See https://github.com/arduino/Arduino/issues/3809

**Comment by i-make-robots** [comment]
Agreed, #4080 is a duplicate.
