### ISSUE TITLE
Support for editing library code

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4085]
Libraries are a great way to enhance the platform popularity. There is not good technical reason why the IDE cannot be altered to support editing them.

feature should cove
* initial creation
* source code editing
* community submission

Proposed reference design
<img width="1008" alt="arduino-2015-11-02 at 1 26 08 pm" src="https://cloud.githubusercontent.com/assets/1318077/10965148/57551ffa-83ab-11e5-8d1a-7683bbdfba1b.png">

(ps: this is actually a limited but working implementation)

**Comment by matthijskooijman** [comment]
Cool! I might have missed it, but did you have a PR open with this code? Or do you perhaps just have it pushed to github somewhere so I can take a peek?

**Comment by lmihalkovic** [comment]
As I wrote somewhere else, I was having some technical challenges (read: I was twisting myself in the ropes) with altering arduino-builder to support that feature and the customizable link priority scheme I also described, so I had to back-track and implement my own compiler. The redeeming factor is that I made it a config param to switch between all 3 compilers.

**Comment by matthijskooijman** [comment]
What changes do you need in arduino-builder for this? To allow modified-but-not-saved library files to be included in the build?

**Comment by lmihalkovic** [comment]
At the moment the IDE uses CTL-L to go to a given line of code. In eclipse the default is to use CTRL-G (goto). In the library editor I was thinking about (read: am currently) using CTRL-L for opening the library's folder in the OS navigator (Finder/Explorer/... on Linux).

<img width="1133" alt="arduino-2015-11-05 at 11 05 52 am" src="https://cloud.githubusercontent.com/assets/1318077/10965451/4d0ca2d2-83ad-11e5-9b79-ce98f64bc3e5.png">

Does anyone have a better suggestion for OpenLib, or might it be possible to switch CTRL-L to CTRL-G instead?!

**Comment by lmihalkovic** [comment]
Done
