### ISSUE TITLE
Hourly build "is damaged and can't be opened" on OS X

### ISSUE THREAD

**Issue by beargun** [arduino/Arduino#4096]
If I try to open the hourly build for Mac OS X, you get the error message "Arduino.app is damaged and can't be opened". I'm running OS X Mountain Lion v10.8.5.

Running `xattr -rc /Applications/Arduino.app` did fix it for me, though I have no idea why.

**Comment by ffissore** [comment]
Maybe you just downloaded it while it was uploaded? Have you tried downloading it once more?

**Comment by beargun** [comment]
Yes. That fixed it. 

Thank you.
