### ISSUE TITLE
Point Release note blog post to HID master

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#4100]
I merged the changes now to the master branch. A library manager release will follow.
Please relink to this link:
https://github.com/NicoHood/HID

Talking about this blog post:
https://blog.arduino.cc/2015/11/03/arduino-ide-1-6-6-released-and-available-for-download/

Thx for all the cooperation with the USB Core, it turns out to be very useful and simple for a (normally) complex funktion like an USB Core. I am really happy about the progress we did.

**Please also add my library to the library manager.** A new release is now tagged.

**Comment by facchinm** [comment]
Hi Nico, blog post updated, assigning to @ffissore for Library Manager inclusion!

**Comment by cmaglie** [comment]
I've added the library, but the tag contains a `.development` file, you should remove the file and re-tag the release. Once done the library should be published within an hour.

**Comment by NicoHood** [comment]
whoops. I will release a new version then, does this work too? I dont want to mess with the git again.

**Comment by cmaglie** [comment]
yup that works too
