### ISSUE TITLE
Add IRremote to Library Manager

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4108]
Please add the IRremote library to Library Manager:
https://github.com/z3t0/Arduino-IRremote
As requested in https://github.com/z3t0/Arduino-IRremote/issues/229

**Comment by pcoughlin** [comment]
Let us know if there are any other pre-admission criteria that we need to complete to get the Library included in the official releases.

Thanks!

**Comment by ffissore** [comment]
Added. Thanks!
