### ISSUE TITLE
possible preprocessor issue when checking for included files in Arduino 1.6.6

### ISSUE THREAD

**Issue by soundanalogous** [arduino/Arduino#4109]
In Arduino 1.6.5, this worked (and still works fine):

```
#if !defined ethernet_h && !defined _YUN_CLIENT_H_
#error "you must uncomment the includes for your board configuration. See OPTIONS A and B in the NETWORK CONFIGURATION SECTION"
#endif
```

[Full file for greater context](https://github.com/firmata/arduino/blob/master/examples/StandardFirmataEthernet/StandardFirmataEthernet.ino#L124-L126).

However since updating to Arduino 1.6.6 the error is always thrown. It seems to be that `ethernet_h` is no longer found by the preprocessor even though Ethernet.h is included. The Ethernet library is still included and works as expected. Maybe it's loaded later even though it is included above this code. It could also just be sloppy coding on my part that is picked up by stricter checking in the updated arduino-builder.

**Comment by matthijskooijman** [comment]
I think this is essentially the same issue as https://github.com/arduino/arduino-builder/issues/33 (though that talks about a specific `USBCON` define, but the issue is really more generic). I'll add a comment to that issue soon to highlight the generic issue.

**Comment by ffissore** [comment]
Also https://github.com/arduino/arduino-builder/issues/51 is related. These are already fixed or getting fixed. Please keep an eye on https://github.com/arduino/arduino-builder/issues/33
