### ISSUE TITLE
String Library Memory Test Assignment Failure [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#411]
This is [Issue 411](http://code.google.com/p/arduino/issues/detail?id=411) moved from a Google Code project.
Added by 2010-11-22T22:39:23.000Z by [rick.rickanderson](http://code.google.com/u/rick.rickanderson/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

String Library Memory Test Assignment Failure

**What steps will reproduce the problem?**

The two attached tests show that there is a memory leak or memory corruption with the String Library.

**What is the expected output? What do you see instead?**
The idea is that you have an original string initialized to longest value in the String Library examples. Assign new values to the string. Then assign the original string value back. You should see no memory loss after assigning the values to the variables.

However, the attached two tests fail.

 Save the the Sketch make sure ArduinoTestStuite is in the libraries folder. Then upload the sketch to the Arduino connect to it's serial port and the test results will be reported to the console.

**Comment by per1234** [comment]
The included tests pass with Arduino IDE 1.8.3, which makes me suspect this issue has been resolved.

The ArduinoTestSuite library required for the tests is available here:
https://github.com/arduino/Tests

**Comment by per1234** [comment]
I'm going to close this as solved. If anyone can still reproduce the issue then please comment here with details and I'll reopen.
