### ISSUE TITLE
1.6.7 hourly build directories issue

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#4111]
If a directory exist into the same folder as the main .ino file, all files .ino found into the directory are read by the compiler and return an error .
This issue existed into the 1.6.6 hourly build and solved with the 1.6.6 final version .

**Comment by per1234** [comment]
@pierrotm777 are you referring to issue https://github.com/arduino/Arduino/issues/3909?

**Comment by pierrotm777** [comment]
Yes , this is the same issue !

**Comment by ffissore** [comment]
This issue was moved to arduino/arduino-builder#65
