### ISSUE TITLE
Arduino Projects Book: Windows Installation needs update

### ISSUE THREAD

**Issue by davidcornell123** [arduino/Arduino#4115]
Page 16 of the projects book provides information for Windows Installation.  Since the printing date is 2013, it cannot include facts for Windows 10, but should be updated for a newer printing..

This advises users that Arduino software installation completed with no problems under Windows 10.  When the Arduino Uno board was plugged into the USB port, the driver installed automatically, assigning COM 4 to the device.  Communication following pp. 18-19 worked perfectly.  So installation under Windows 10 is simpler and more automatic than with earlier versions of the Microsoft OS.

**Comment by SalvorinFex** [comment]
This GitHub repository is for the IDE not the book, your best bet would be to contact the publisher.

**Comment by davidcornell123** [comment]
Thanks Kurt,  I've closed the publishing issue on GitHub.
Dave Cornell

On 11/9/2015 5:54 PM, Kurt Roesener wrote:
>
> This GitHub repository is for the IDE not the book, your best bet 
> would be to contact the publisher.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/arduino/Arduino/issues/4115#issuecomment-155257901>.
>

-- 
David A. Cornell
18624 Blue Ridge Drive
Lynnwood, WA 98037
425-771-4745

**Comment by SalvorinFex** [comment]
You're welcome and BTW, your reply shows your address and number number.
Just an FYI

**Comment by davidcornell123** [comment]
Yes, I customarily send out signature block with that info.  Do you 
think I should be more guarded about personal contact info?

Dave

**Comment by SalvorinFex** [comment]
I am but that's up to you, especially the phone number.  
I have our phones on the "do not call lists" and we still get robocalls and other junk calls.
