### ISSUE TITLE
MPU-6050 code conflict with Due

### ISSUE THREAD

**Issue by ibmua** [arduino/Arduino#4116]
On
http://playground.arduino.cc/Main/MPU-6050
the "Short example sketch" and probably some other codes too have to be modified with 

const int MPU=0x68;  // I2C address of the MPU-6050
being changed to something like
const int MPU_addr=0x68;  // I2C address of the MPU-6050

and the consequential changes, due to a conflict with some Due code. Because it doesn't compile on the Due otherwise.

**Comment by cmaglie** [comment]
playground content is provided and editable by users, you can edit the page and fix the code autonomously! :-)
