### ISSUE TITLE
Ethernet shield product page need update compatibility Arduino boards

### ISSUE THREAD

**Issue by aeternaict** [arduino/Arduino#4117]
From http://forum.arduino.cc/index.php?topic=134560.0, it is described that ethernet shield is compatible with Arduino DUE.

From https://www.arduino.cc/en/Main/ArduinoEthernetShield, it is described that ethernet shield is compatible with only Arduino UNO and MEGA boards

Please add Arduino DUE in the ethernet shield compatibility board list if correct.

**Comment by agdl** [comment]
@aeternaict updated thank you!

**Comment by aeternaict** [comment]
Thank you.
