### ISSUE TITLE
Add installation instructions for Asus eeePC to wiki [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#412]
This is [Issue 412](http://code.google.com/p/arduino/issues/detail?id=412) moved from a Google Code project.
Added by 2010-11-24T09:16:00.000Z by [rob.till...@gmail.com](http://code.google.com/u/113198963792305667520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

Addition to the installation page how to install Arduino drivers on an Asus eeePC.

**Why?**

in http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1290461251#6
it is discussed how to install the drivers on an ASus eeepc. It differs from a normal windows PS.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

No, just a small addition on the main wiki

**Comment by ffissore** [comment]
I don't think we'll put any effort in documenting such an old pc. It wasn't old back in 2010, but we failed to add documentation when it was needed
