### ISSUE TITLE
Library manager tries to replace a core library

### ISSUE THREAD

**Issue by facchinm** [arduino/Arduino#4136]
If a core contains a library with the same name and metadata of one listed in Library Manager, when trying to install the later the IDE will prompt for removal of the bundled one.
Confirming this action won't remove the bundled library but neither installs the external one.

**Comment by ffissore** [comment]
I can't reproduce it with latest hourly. Maybe it was a side effect of (fixed) #3795?

**Comment by facchinm** [comment]
Update is now straightforward, the core libs being updatable is tracked in issue #4064, thus closing as duplicate
