### ISSUE TITLE
Include issue in last hourly build (13 November 2015 15:37:55 GMT)

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#4144]
I use the excellent LCD menu library https://github.com/Jomelo/LCDMenuLib/releases .
With this new hourly version , the compiler don't understand this type of write!
```
				//LCD includes
#				include <Wire.h>
#				include <LiquidCrystal_I2C.h>

but only
				//LCD includes
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
```
I don't know if this is an issue ?

**Comment by ffissore** [comment]
This issue was moved to arduino/arduino-builder#64
