### ISSUE TITLE
Intel i686 Boards: CRC not corresponding. File is damaged

### ISSUE THREAD

**Issue by BeatArnet** [arduino/Arduino#4149]
After installing the latest versions 1.6.6 and 1.6.7 I can no more select the Intel Edison Board. I wanted to reinstall the I686 Board but I get the message (CRC stimmt nicht überein. Date ist beschädigt - CRC not corresponding. File is damaged).

**Comment by ffissore** [comment]
I've just tried and it works as expected. Can you please delete the files you can find in `%LOCALAPPDATA%\Arduino15\staging and retry?
