### ISSUE TITLE
Use External Editor doesn't apply to all open sketches. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#415]
This is [Issue 415](http://code.google.com/p/arduino/issues/detail?id=415) moved from a Google Code project.
Added by 2010-11-29T02:23:26.000Z by [pl...@bigpond.com](http://code.google.com/u/100437644944823497850/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open sketch and select 'use external editor' - workspace is then locked and on build, it will update the files in that sketch as normal.
2. Open a second sketch for testing small snippets of code, say for example the blink sketch. In order to edit this sketch deselect 'use external editor'. The workspace in this window is unlocked and editing can occur. This works as normal for this sketch.
3. Going back to the origional sketch opened and locked, the workspace is still locked and the tickbox stating 'use external editor' is unselected.

**What is the expected output? What do you see instead?**
The main problem is that when attempting to upload the sketch, the files are not updated before upload. The workspace looks like it is still set to use the external editor but it does not function as so. The expected outcome would be that each workspace should be able to be independently set to using external editors, or that deactivating the external editor in one workspace flows onto other workspaces.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Version 0021 on Windows 7
Boards: Mega, Duo and Pro

**Please provide any additional information below.**
Origional post at:
http://www.arduino.cc/cgi-bin/yabb2/YaBB.pl?num=1290433792

**Comment by ffissore** [comment]
Fixed a long time ago. Tested with latest hourly.
