### ISSUE TITLE
Modernize the look of the UI to track Arduino Create

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4151]
Create looks really nice, and it would make sense to align the two UI where it makes sense. This is a first cut where only the buttons are still hard-coded (the rest is has been cleaned up and the images can be deleted).

<img width="966" alt="arduino-2015-11-15 at 2 11 35 am" src="https://cloud.githubusercontent.com/assets/1318077/11166652/8966e90c-8b3e-11e5-90c1-e1cb1de95e30.png">

TODO: 
* ~~fix the remaining spacing issues~~  fixed with #4158 
* ~~restore the local popup menu~~  fixed with #4158

**Comment by ffissore** [comment]
Thank you once more @lmihalkovic However, very few features of Create will be ported to the IDE

**Comment by lmihalkovic** [comment]
It is quite unfortunate considering how little work is involved in modernizing the UI that nobody has ever taken one hour to do it. But I understand that as a company, it is preferable to do the bare minimum to just *maintain* an old product while all efforts are focussed on the next generation.

**Comment by matthijskooijman** [comment]
> nobody has ever taken one hour to do it.

That seems like a pretty severe (and incorrect) assumption. Looking at improved syntax highlighting, error highlighting, a new library manager, etc. added in the last year or so, things *are* improving. It's just that all of these "one hours" can only be spent once, so choices must be made.

**Comment by lmihalkovic** [comment]
I never questioned that the team is doing an awesome job, and I think we can all agree that it is unfortunate that there will never be any time for this. Arduino Create did all the design (really great job, btw!!). Implementation was just a matter of altering EHeader.paintComp(), adding 10 line to Themes (to avoid duplications between the themes, the base theme.txt is always applied, and an optional variation is applied after if the config says so), adding a couple lines to EToolbar, and creating a couple of new classes to draw the dot-logo and the new title box. I still have to replace the green buttons with java code, to make it work with any background color.  

But again i understand the decision to spend more efforts on the new product. Some companies still consider a unique visual identity an asset though.

**Comment by lmihalkovic** [comment]
[LMDONE]

**Comment by q2dg** [comment]
@lmihalkovic Could you do a pull request, please?
