### ISSUE TITLE
When external editor is set, hitting upload scrolls back to the top of file.

### ISSUE THREAD

**Issue by BlitzKraft** [arduino/Arduino#4155]
I often compare files and have some example files open for reference. I lose my position in the file if I hit upload or verify. It would be better if the IDE doesn't scroll to the top and I can edit/compare the same line without having to scroll back down.

This happens exclusively when the external editor is set. When it is not set, it has the expected behavior of not scrolling, when I hit upload.

**Comment by matthijskooijman** [comment]
I suspect this is because the content of the textarea is cleared and reloaded, resetting the scroll position. The fix would probably to save the current scroll position before reloading the file and restoring it afterwards.

If you're able to code this, a pullrequest would be helpful.

**Comment by BlitzKraft** [comment]
I haven't worked with the IDE before. But I will look into that.

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
