### ISSUE TITLE
Support theme variants

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4158]
The upcoming Arduino Create looks awesome, and seems to support different color variants. This is about adding the same feature to Arduino IDE.

<img width="1000" alt="screen shot 2015-11-15 at 7 32 04 pm" src="https://cloud.githubusercontent.com/assets/1318077/11170568/a1bd7f80-8bd8-11e5-9abe-b432e5802ff6.png">

<img width="1000" alt="screen shot 2015-11-15 at 8 34 04 pm" src="https://cloud.githubusercontent.com/assets/1318077/11170569/ac99fed8-8bd8-11e5-998e-620d8c12eb5b.png">

Note: at the moment the code is still using buttons.gif for the toolbar. It would be nice to replace them with either a simple color mask with the same content, or just code (like for the drop-down and the tabs)

**Comment by lmihalkovic** [comment]
Credit for the look is entirely going to the [Arduino Create](https://blog.arduino.cc/2015/05/05/sneak-peak-arduino-create/) designers

**Comment by ffissore** [comment]
Thank you @lmihalkovic. We won't add support for multiple themes. It's a feature you'll find in Create, not in the IDE

**Comment by lmihalkovic** [comment]
No problem. It took a few minutes to do it, and i like it as it is.

**Comment by lmihalkovic** [comment]
In case you change your mind, this is my theme-dark.txt

```
# GUI - TABS
header.bgcolor = #2c353a
header.text.selected.color = #abbdc1
header.text.unselected.color = #a2b5bb
header.tab.unselected.bgcolor= #384247
header.tab.selected.bgcolor= #171e20

# EDITOR - DETAILS

# foreground and background colors
#editor.fgcolor = #000000
editor.fgcolor = #707778
editor.bgcolor = #171e20


# GUI - BUTTONS
# LJPM delete when replaced with code
header.toolbar.buttons= buttons3.gif
```

**Comment by lmihalkovic** [comment]
Done
