### ISSUE TITLE
Duplicate "Invalid library found in" messages when Library Manager is opened/closed

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4163]
Using Arduino IDE 1.6.7 2015/11/13 05:42 with Windows 7 64 bit
- Install invalid library. For example, by putting **src** and **utility** folders in the library root folder.
- **Sketch > Include library > Manage libraries...** - the `Invalid library found in`... message appears 4 times.
- **Close** - the `Invalid library found in`... message appears 2 times.

**Comment by ffissore** [comment]
73e857fda934704c5fb894b34fb1d943d1c72484 fixes this
