### ISSUE TITLE
Please don't reset the sketches folder path on "not found" error

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#4165]
_From @MikeyMoMo on November 11, 2015 0:48_

Do NOT reset the setting item for the sketches folder if it is not immediately found.
Put out a message, yes, as is done now but don't reset the entry.  The user has to find
out why the folder is inaccessible and then reset the settings entry to what it already was
before you "fixed" it.  Just remove the path reset code, please. It is a waste of time.  My sketches folder is on a shared drive and Windows is slow finding it.  So I have to encourage it.  If I happened to open the IDE before it was time, you message me then reset the path.  Then I have to go get the share online and go reset the path.  Double work for nothing.

_Copied from original issue: arduino/arduino-builder#53_

**Comment by per1234** [comment]
Even though this one came first, there is a little bit more discussion on the subject in the duplicate https://github.com/arduino/Arduino/issues/7863 so I'll close this in favor of the other.
