### ISSUE TITLE
Arduino due is not recognized by Raspberry pi through i2c

### ISSUE THREAD

**Issue by polito1980** [arduino/Arduino#4178]
Hi guys, I am tring to conect my arduino due board with raspberry pi through i2c writing in the raspberry terminal the instruction: sudo i2cdetect -y 1 and it didnt work, I do it with my arduino uno and it works properly, anyone can tell me how can I fix it?  Thx.

**Comment by ffissore** [comment]
github issues are for bugs and feature requests for the Arduino IDE, not for generic support. Please consult the [arduino.cc forum](http://forum.arduino.cc/)
