### ISSUE TITLE
Manager libraries install a libarry into two ways !

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#4179]
I wanted to install the library 'PulsePosition' .
I see two curious things:
1- The library is installed into my folders:
C:\Users\pierre\AppData\Local\Arduino15\staging\libraries\PulsePosition-1.0.0-github.zip
and
C:\tmp\Arduino_Compilateur\arduino-1.6.6\MyArduinoSketch\MesProgrammes\libraries\PulsePosition

2-I can't uninstall a library installed by the manager !

Don't know if this is two issues ?

**Comment by ffissore** [comment]
The first path is the downloaded zip of the library, the second path is the actual, unpacked, library that the IDE will use to compile your sketches (and your sketchbook folder is `C:\tmp\Arduino_Compilateur\arduino-1.6.6\MyArduinoSketch\MesProgrammes`)

Your second point is a known limitation, mentioned both at #2878 and in https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-delete-a-library
