### ISSUE TITLE
Multiplot examples

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#4188]
Where can i find a multiplot example ?
Is it possible to have different colors for each plot ?

**Comment by agdl** [comment]
You have to simply write in the code something like
`arduino
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
}

void loop() {
  // put your main code here, to run repeatedly:
  for (int i = 0; i < 100; i++)
  {
    Serial.print(i);
    Serial.print("\t");
    Serial.println(2 * i)
  }
}
`

colours are automatically assigned

**Comment by ffissore** [comment]
indeed. or print sin and cos with a final `println`
