### ISSUE TITLE
Where is _asciimap in the new arduino?

### ISSUE THREAD

**Issue by crushedice2000** [arduino/Arduino#4191]
Hi! I can't find the `const uint8_t _asciimap[128]` array on this repository. Why is happening this? Where is now this file? In my computer is on `/usr/share/arduino/`**`hardware/arduino/cores/arduino/HID.cpp`**

**Comment by sandeepmistry** [comment]
@crushedice2000 it has been moved to the new [Keyboard library](https://github.com/arduino-libraries/Keyboard) as part of the Pluggable USB and HID feature introduced in the 1.6.6 release.

https://github.com/arduino-libraries/Keyboard/blob/master/src/Keyboard.cpp#L86

**Comment by crushedice2000** [comment]
Ok, thank you very much!
