### ISSUE TITLE
Library Manager: display Arduino Libraries at the beginning of the list

### ISSUE THREAD

**Issue by 00alis** [arduino/Arduino#4195]
@ffissore When I open the Library Manager the Type dropdown filter is correctly set on All, we should just display Arduino Libraries at the beginning of the list, and all the others afterwards in alphabetical order.

@mbanzi

**Comment by lmihalkovic** [comment]
If you might consider that some sort of quick search could make sense, then a possible way to use it could be to display that same information. Could all be done via keyboard by typing "CTRL+3", "libs" ('l' is enough). More differentiation in the display could include color, font, .... just a thought.

![qa-libs1](https://cloud.githubusercontent.com/assets/1318077/11313077/9c501386-8fda-11e5-9f04-1c4f9dd83403.jpeg)

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly
