### ISSUE TITLE
Add 'support' for additional file types in a sketch

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4197]
I noticed that Arduino Create will support storing some sort of a README as well as a one or more images describing the sketch. I would be nice for the IDE to provide the same level of support for them.

In my case this extends to allowing some of these in libraries as well.

**Comment by lmihalkovic** [comment]
Adding support for layout details if they are present in a sketch (i.e. any images in lib or sketch can be displayed inside the editor)

<img width="450" alt="arduino-2015-11-22 at 11 12 50 am" src="https://cloud.githubusercontent.com/assets/1318077/11323128/64a9ffd8-910a-11e5-98ac-f090c001fed0.png">

**Comment by ffissore** [comment]
This has been internally discussed and there are no plans to add such features to the Arduino IDE
