### ISSUE TITLE
Add support for markdown files

### ISSUE THREAD

**Issue by lmihalkovic** [arduino/Arduino#4198]
Follow-up to #4197, it would be nice to allow READMEs written in markdown to display with all enhancements

**Comment by ffissore** [comment]
See https://github.com/arduino/Arduino/issues/4197#issuecomment-158875296

**Comment by lmihalkovic** [comment]
I know, *Arduino Create will do it*. It is quite unfortunate that the desktop IDE is headed to become the ugly girlfriend.,, the code is not pretty (you know it better than me), but it is still salvageable.

<img width="400" alt="arduino-2015-12-01 at 1 39 00 am" src="https://cloud.githubusercontent.com/assets/1318077/11489176/2c68db02-97cd-11e5-8277-0f166c0c1773.png">
