### ISSUE TITLE
Sketch name conflicts

### ISSUE THREAD

**Issue by aweatherguy** [arduino/Arduino#4199]
Here's a situation that took me a while to fix and it would be something that perhaps the Arduino build process could detect and warn folks about. This can be reproduced in Win7 with the Arduino IDE 1.7.7

I have a sketch file named (for example) runthehdwr.ino

I also have a C++ class named "RunTheHdwr" in the sketch directory defined in these two files:
    RunTheHdwr.h
    RunTheHdwr.cpp

The problem is that when I try to build the sketch it does not compile runthehdwr.ino and I wind up with unresolved symbols for setup() and main().

Hard to find and easy to fix (rename the sketch or the class). I don't think there's anything wrong with saying this is not a supported thing to do. However, it seems to me that the IDE could detect this easily and tell the user what's wrong so they don't spend too much time trying to figure out why the sketch isn't being compiled.

**Comment by ffissore** [comment]
There is no version 1.7.7. The latest stable version of the IDE is 1.6.6, available from the [download page](https://www.arduino.cc/en/Main/Software). You may have been fooled by a fork of the IDE which has been created months ago and never updated. You can find more info [here](https://github.com/arduino-org/Arduino/issues/2) and [here](http://makezine.com/2015/03/19/massimo-banzi-fighting-for-arduino/).

Can you please try the latest IDE and report if the issue persists? https://www.arduino.cc/en/Main/Software
