### ISSUE TITLE
WARNING: Spurious .git folder in library

### ISSUE THREAD

**Issue by hryamzik** [arduino/Arduino#4204]
Due to #3237 there shouldn't be such a warning but I do get in in Arduino IDE v1.6.6.

**Comment by ffissore** [comment]
This issue was moved to arduino/arduino-builder#70

**Comment by hryamzik** [comment]
@ffissore thanks!

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
