### ISSUE TITLE
MIDI output circuit violates the MIDI specification

### ISSUE THREAD

**Issue by cladisch** [arduino/Arduino#4217]
On the MIDI Note Player tutorial example page (https://www.arduino.cc/en/Tutorial/Midi), the circuit uses a single 220 Ω resistor. However, the MIDI specification (http://www.midi.org/techspecs/electrispec.php) requires two resistors in order to limit the current to approximately 5 mA.

The description and the code comment should be changed to "MIDI jack pin 2 connected to ground through 220-ohm resistor", and the circuit and schematic modified appropriately.

**Comment by agdl** [comment]
@cladisch fixed thank you!
