### ISSUE TITLE
100% cpu load

### ISSUE THREAD

**Issue by dial-up** [arduino/Arduino#4229]
100 percent of the load on the core immediately after startup.
![image](https://cloud.githubusercontent.com/assets/15235015/11456390/c3135d82-968f-11e5-888c-f3174dc98b2d.png)
1.0.x:
![image](https://cloud.githubusercontent.com/assets/15235015/11456465/80900714-9692-11e5-8910-74f9644f999c.png)

**Comment by ffissore** [comment]
I read 31.2%, not 100%. I think it's kind of normal for an app to use some cpu, especially when starting up. Have you tried with your antivirus temporary disabled? Our windows box becomes 10 times faster

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Reopen it if needed please
