### ISSUE TITLE
atan2: wrong function reference in https://www.arduino.cc/en/Reference/MathHeader

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#4237]
atan2: 
wrong function reference in https://www.arduino.cc/en/Reference/MathHeader

it says
~~~
double 	atan2 (double __y, // arc tangent of y/x
~~~

but atan2 has 2 arguments:
~~~
double atan2 ( double Yaxis, double Xaxis);
~~~

**Comment by VogonJeltz** [comment]
this should be added, too:

https://cloud.githubusercontent.com/assets/423515/11477995/d0cf487c-978a-11e5-96b3-e2148e6af70e.png

**Comment by agdl** [comment]
fixed thank you!
