### ISSUE TITLE
atan2 implementation / calculation bug?  atan2(y,x)  for x=0 ?

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#4238]
I encountered a calculation bug for : atan2 for x=0 (CMIIW):

as 
atan2(y,x) = atan (y/x)  ,  x≠0
I would expect a NAN for 
atan2(2, 0), 
but instead I get 
1.5707

...or did I miss something?

**Comment by cmaglie** [comment]
From: https://en.wikipedia.org/wiki/Atan2

![atan2](https://cloud.githubusercontent.com/assets/423515/11477995/d0cf487c-978a-11e5-96b3-e2148e6af70e.png)

The result is undefined if x **and** y are 0.
In your case the point x==0, y==2 is on the Y axis, so 1.5707 (== rad(90) or PI/2) is the correct result.

**Comment by VogonJeltz** [comment]
thanks, I stand corrected!
