### ISSUE TITLE
String concat reference page is incorrect

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4244]
https://www.arduino.cc/en/Reference/StringConcat
The Description, Syntax, Parameters, and Returns sections are all completely wrong. I suggest changing it to something like:

Description
Appends the parameter to the String.

Syntax
string.concat(parameter)

Parameters
parameter: Allowed types are String, string, char, byte, int, unsigned int, long, unsigned long, float, double, __FlashStringHelper(F() macro).

Returns
true: success
false: failure (in which case the string is left unchanged).

Originally reported at: http://forum.arduino.cc/index.php?topic=363080.0

**Comment by agdl** [comment]
@per1234 changed as you suggested thank you!

**Comment by per1234** [comment]
@agdl I think the line:
>true: success false: failure (in which case the string is left unchanged). 

should be written in two lines like:
>true: success
false: failure (in which case the string is left unchanged).

This is consistent with the way that it is done on other reference pages such as: https://www.arduino.cc/en/Reference/StringStartsWith

**Comment by per1234** [comment]
@agdl the formatting error I reported in my last comment still has not been fixed.

**Comment by Lauszus** [comment]
B

**Comment by per1234** [comment]
@agdl https://github.com/arduino/Arduino/issues/4244#issuecomment-161943110 still not fixed,  if you don't have time to fix it now please reopen this issue so it doesn't get lost.

**Comment by matthijskooijman** [comment]
@per1234, done, thanks for persisting :-)

**Comment by agdl** [comment]
Sorry, actually I didn't noticed this mail :( I did it. Please take a look and close the issue
