### ISSUE TITLE
please enable tone() for the DUE !

### ISSUE THREAD

**Issue by VogonJeltz** [arduino/Arduino#4256]
please enable tone() for the DUE !
This issue is well-known since lot of years and still unresolved (at least workarounds - if any - are not well-documented)!

**Comment by NicoHood** [comment]
Duplicate:
https://github.com/arduino/Arduino/issues/2362

**Comment by matthijskooijman** [comment]
This is indeed a duplicate, so I'm closing this issue in favor of the other one.

**Comment by VogonJeltz** [comment]
OMG, the other thread is dated from October 2014  !!
why hadn't it been fixed yet ?!?
