### ISSUE TITLE
[DOC] Upload Using Programmer wrong menu

### ISSUE THREAD

**Issue by likuilin** [arduino/Arduino#4263]
Sorry if I'm doing anything incorrectly, this is the first time I'm doing anything with Github. 

So on this page: https://www.arduino.cc/en/Hacking/Programmer it says to use the menu item "File->Upload Using a Programmer"

The Upload Using a Programmer menu item is actually located under Sketch, not File. This small issue has costed me much patience since Google doesn't provide an answer anywhere for where that menu item actually is.

**Comment by agdl** [comment]
@likuilin fixed thank you very much!
