### ISSUE TITLE
Digispark

### ISSUE THREAD

**Issue by KahnSoft** [arduino/Arduino#4268]
Hello,

we use massivly Digispark extensions, all works fine under newest Version.

But in this Version we take some Messages they are un like

Invalid library found in C:\Users\Schulz\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.5\libraries\Digispark_Examples: C:\Users\Schulz\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.5\libraries\Digispark_Examples

All processes works good,  Can u stop this nerved Waring -Messages ?

Thanks
 Karsten

**Comment by ffissore** [comment]
Please report this issue to digistump developers https://github.com/digistump/DigistumpArduino
