### ISSUE TITLE
Version 1.6.6: Bad permissions on Arduino.app/Contents/Java/reference/Edison_help_files, Arduino.app/Contents/Java/reference/Galileo_help_files

### ISSUE THREAD

**Issue by jhowe-sgs** [arduino/Arduino#4273]
serveradmin@wenchang:/Applications/Arduino.app/Contents/Java/reference
$ ls -al
drwx------ 32 serveradmin staff 1088 Mar 25  2015 Edison_help_files
drwx------ 40 serveradmin staff 1360 Mar 25  2015 Galileo_help_files

Top level help dirs are mode 0700, should be 0755.

Thanks

**Comment by jps3** [comment]
(Bump)

**Comment by NicoHood** [comment]
Another user reported the same error for (arch)linux. It applies to all files in the listed folders above too.

**Comment by NicoHood** [comment]
Those files are downloaded here and the zip file already contains this data:
https://github.com/arduino/Arduino/blob/master/build/build.xml#L188

We have two options to fix this issue:
* Change the zip file (and its shasum)
* Merge this PR: #5306
