### ISSUE TITLE
Windows7 AMD64 USB Port not installing have additional comm port card ports 3&4

### ISSUE THREAD

**Issue by RichW8VKinSidneyOhio** [arduino/Arduino#4274]
Arduino windows 7 installer won't install any USB Port and I have a comm port card in HP computer I'm not changing. Puts comm 3 & 4 as usb port in Arduino software program but tries to install port 22 or in device manager. What is the fix so I can use these (2) new Arduino 2560s? Need Help by email ASAP Please!

RichW8VKinSidneyOhio

**Comment by per1234** [comment]
Closing due to insufficient information.
