### ISSUE TITLE
Libraries folder location setting

### ISSUE THREAD

**Issue by dpeukert** [arduino/Arduino#4287]
It would be great to have an setting similar to the sketchbook location for the `libraries` folder.

**Comment by ffissore** [comment]
Can't you just change sketchbook folder?

**Comment by dpeukert** [comment]
Libraries installed using the Library Manager are still being installed to the libraries subfolder in the default sketchbook location.

**Comment by ffissore** [comment]
No, they are installed in the `libraries` subfolder of the current sketchbook folder. You may have hit one of #4139 #3904 #3795: they are all fixed in latest hourly http://www.arduino.cc/en/Main/Software#hourly

**Comment by dpeukert** [comment]
You're right, everything is working correctly in the latest hourly.

**Comment by ffissore** [comment]
:+1:
