### ISSUE TITLE
IDE should not try to compile common "support" filenames...

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#4289]
In particular, it should ignore "dot files" like the emacs recovery history (?) for a source file:

stat /Applications/arduino/Arduino-1.6.6.app/Contents/Java/hardware/arduino/avr/cores/arduino/.#Arduino.h: no such file or directory

On unix/macos, I'm pretty sure that anything beginning with a "." should not be treated as source code.

**Comment by ffissore** [comment]
This issue was moved to arduino/arduino-builder#82
