### ISSUE TITLE
"Archive Sketch" command won't add a proper extension automatically  [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#429]
This is [Issue 429](http://code.google.com/p/arduino/issues/detail?id=429) moved from a Google Code project.
Added by 2010-12-09T08:53:40.000Z by [kotob...@gmail.com](http://code.google.com/u/114024383179456627909/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. open a sketch
2. choose Archive Sketch in Tools menu
3. a save dialog appears

**What is the expected output? What do you see instead?**
Expected a file name with proper extension such as "sketchname_1208-101209a.zip" but got "sketchname_1208-101209a". So I had to add an extension manually.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 0021 on Mac OS X 10.6

**Please provide any additional information below.**
Confirmed that the same issue occurs in Processing 1.2.1

**Comment by ffissore** [comment]
Works fine with current hourly build
