### ISSUE TITLE
New HDC1000 library

### ISSUE THREAD

**Issue by hotchpotch** [arduino/Arduino#4299]
Please add my library to the Arduino Library Manager.

- https://github.com/hotchpotch/Arduino-HDC1000

thanks.

**Comment by ffissore** [comment]
Added. However you did not released your library and hence it was not included in Lib Manager. Please give a second read to https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ. Once you'll be done, our job will automatically push your released library into the list

**Comment by hotchpotch** [comment]
@ffissore 

Thank you.
I pushed with releases tag!
