### ISSUE TITLE
1.6.6 Library Manager - CRC errors occurred during updating libraries

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#4303]
During updating libraries, CRC errors are occurred:
- FreqCount,  MsTimer2, Time and TimeOne
- FreqCount and MsTimer2 updated manually after CRC errors occurred.

![librarymanager_01](https://cloud.githubusercontent.com/assets/9634845/11783648/a83a8340-a2bb-11e5-98f2-ce346bc0a88e.png)

**Comment by ffissore** [comment]
Please delete files from `%LOCALAPPDATA%\Arduino15\staging\libraries` and retry

**Comment by Myriads** [comment]
Even if %LOCALAPPDATA%\Arduino15\staging\libraries were deleted, CRC errors still come out

**Comment by Myriads** [comment]
In DownloadableContributionsDownloader.java, FileHash.hash function generates a quite different hash value with the checksum value of the Time library:

checksum : SHA-256:1b658b9d71cddd4c24a63ec5c0c1cf345a44b32d46e0a207c7e129f8bc6e6492
hash value : SHA-256:3ae1f8839a6d48aeb3c0c4489e0ddeb32b245df700b8fb01b03f784a47aee18e

Tested with Time library.

**Comment by bukrat** [comment]
I have the same problem here. Any help?

**Comment by Myriads** [comment]
Please try with the newest IDE version.
2016. 4. 28. 오후 4:27에 "Bukrat" <notifications@github.com>님이 작성:

**Comment by Myriads** [comment]
Please try with the newest IDE version.
2016. 4. 28. 오후 4:27에 "Bukrat" <notifications@github.com>님이 작성:

I have the same problem here. Any help?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/arduino/Arduino/issues/4303#issuecomment-215334184>

**Comment by cmaglie** [comment]
This issue has been fixed with #5453.
The fixed version is available in the hourly build, or the next IDE release 1.6.13.
