### ISSUE TITLE
RAMBo board missing from board options

### ISSUE THREAD

**Issue by a4jp-com** [arduino/Arduino#4306]
The RAMBo board missing from board options.
I think the Arduino/Genuino Mega 2560 is the base for the board but it has extra pins for the LCD and SD card.

**Comment by ffissore** [comment]
Ask RAMBo devs, not Arduino

**Comment by a4jp-com** [comment]
Sorry, I thought the RAMBo board was a Arduino board but just with extra pins for the LCD and SD card reader.
