### ISSUE TITLE
NEW I-Bot library

### ISSUE THREAD

**Issue by somsinchai** [arduino/Arduino#4308]
Please add my I-Bot library to the Arduino Library Manager.

https://github.com/somsinchai/IBot

thanks.

**Comment by VogonJ** [comment]
could you provide a website with a project description, please?

**Comment by somsinchai** [comment]
https://www.facebook.com/ibotcamp/?fref=ts
it about camp for hight school student to pratcit robotic skill our robot is a sample line follower robot and some servo using arduino UNO

**Comment by cmaglie** [comment]
@somsinchai 
to publish the library you must create a "tag" or a github's "release", please have a closer look here:

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

**Comment by somsinchai** [comment]
ok, now i've released my library.
thank.

**Comment by cmaglie** [comment]
@somsinchai 
your library is named I-Bot but in the property file you wrote "WebServer", but maybe this is not what you want?
I'd say that you should write the correct name in library.properties, do another release and remove the previous wrong release.

**Comment by somsinchai** [comment]
oh, my wrong
i missing edit library.properties form default file.
now i 've edit it and delete previous release.
thank

**Comment by cmaglie** [comment]
Thanks, the library is now published!
