### ISSUE TITLE
Font issue with hourly build 15 December 2015 12:46:26 GMT

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#4309]
The font used has now a very bad quality !!!!

**Comment by facchinm** [comment]
Hi @pierrotm777 , the problematic commit is this one 6c5e58445402597f0472fbf4da9e518ff38b399b, probably it has side effects on Windows because both Linux and OSX behave exactly as before. Investigating and eventually reverting soon

**Comment by facchinm** [comment]
Closed by reverting the patch since fonts where rendered badly also on OSX.
Thanks for pointing this out!
