### ISSUE TITLE
Ctrl+/ deletes the selection, not comments/uncomments [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#431]
This is [Issue 431](http://code.google.com/p/arduino/issues/detail?id=431) moved from a Google Code project.
Added by 2010-12-17T15:47:17.000Z by [nizamov....@gmail.com](http://code.google.com/u/100459741806008157090/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

1. Select a piece of text
2. Press Ctrl+/

Instead of commenting the block, it would be replaced by slash. Pressing Ctrl+Z this may be reversed. Also it makes clear that Ctrl+/ actually comments the block, but then immediately replaces it with /. It looks like pressing Ctrl+/ and then /.  Selecting the corresponding menu item works OK.

Arduiono ide 0021, Linux (Ubuntu 10.10 / 64bit )

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build. Non US keyboard layout can use the `/` key on the keypad

**Comment by ffissore** [comment]
Next hourly build will be available at http://www.arduino.cc/en/Main/Software#hourly
