### ISSUE TITLE
New BLE Serial Library

### ISSUE THREAD

**Issue by shrikantpatnaik** [arduino/Arduino#4315]
Hi, please add my BLE Serial Library

* https://github.com/5pIO/BLESerial
* https://github.com/5pIO/BLESerial/releases

Thanks

**Comment by cmaglie** [comment]
Hi @shrikantpatnaik 

I see that the 1.1 release tag has a library.properties containing version = 1.0:
https://github.com/5pIO/BLESerial/blob/1.1/library.properties

IMHO that it's not what you intended, could you fix the library.properties and update the release 1.1 (by removing/redoing it)?

**Comment by shrikantpatnaik** [comment]
Oops, thats my bad, fixed it now :smile:

**Comment by cmaglie** [comment]
Added, thanks!
