### ISSUE TITLE
Add MiniPirate library, a command line for Arduino

### ISSUE THREAD

**Issue by chatelao** [arduino/Arduino#4322]
Pleas add the "MiniPirate" library. It contains a serial command line tool for Arduino running on any OS with a serial monitor:

- https://github.com/chatelao/MiniPirate

For more informations see these articles of the older, non-library edition:
- Hackaday: https://github.com/chatelao/MiniPirate
- Instructable: http://www.instructables.com/id/Arduino-comand-line-tool-MiniPirate/

**Comment by cmaglie** [comment]
Done, thanks!

**Comment by chatelao** [comment]
Thanks, cannot wait next Sunday night

**Comment by cmaglie** [comment]
You don't need to wait, it's already there :-)
(the Sunday job is for clean-up, i.e. removing old versions or fixing errors on already published libraries)

**Comment by chatelao** [comment]
Help: I tried to search it after restarting the IDE, but it didn't show up. Any idea how I could debug the process?

**Comment by cmaglie** [comment]
Just writing the first letters "Minip".. in the search box should do:

![minp](https://cloud.githubusercontent.com/assets/423515/11934753/4d9f0c00-a804-11e5-969d-fbf62e8d0a34.png)

Maybe your IDE is not able to update the `library_index.json` file for some reason?

**Comment by chatelao** [comment]
Thanks for your nice answer, I will try it again. Now I know the name of the file to search for :-)
