### ISSUE TITLE
SerialEvent documentation: list of incompatible boards incomplete

### ISSUE THREAD

**Issue by extrapixel** [arduino/Arduino#4328]
https://www.arduino.cc/en/Reference/SerialEvent

Yun, Zero, etc are not compatible with SerialEvent. Please update list of incompatible boards.

**Comment by NicoHood** [comment]
We should better discuss to remove the API fully. I dont have the link to this commit anymore where we started the discussion.
@PaulStoffregen @cmaglie @matthijskooijman

**Comment by extrapixel** [comment]
:+1:

**Comment by per1234** [comment]
Fixed by https://github.com/arduino/reference-en/pull/506 and https://github.com/arduino/reference-en/pull/518
