### ISSUE TITLE
timer1_detachInterrupt();

### ISSUE THREAD

**Issue by sasa999** [arduino/Arduino#4346]
After timer1_detachInterrupt(); timer/counter not call handler function at all. I cant enable it with timer1_attachInterrupt(handler);
For test I  added 1 line in code - timer1_detachInterrupt();. It stopped all. :(
```
  timer1_isr_init();
  timer1_enable(0, 0, 1);
  timer1_write(120000);
  timer1_detachInterrupt();
  timer1_attachInterrupt(handler);```

Any solutions?

**Comment by matthijskooijman** [comment]
@sasa999, this issue tracker is meant for bugs in and suggestions for the Arduino IDE. For help with debugging your own sketches, you can better post on the Arduino forums instead. Also, from your code I suspect your using the ESP2866 core, which isn't maintained by the Arduino team, so some other forum or mailing list specific to the ESP2866 might be more appropriate (I don't really know, you'll have to look yourself).

I'm closing this issue. If you think this is wrong, feel free to leave a comment and we can re-open if needed.
