### ISSUE TITLE
installing arduino libraries

### ISSUE THREAD

**Issue by ruggb** [arduino/Arduino#4348]
in this document near the bottom is
Restart the Arduino application. Make sure the new library appears in the Sketch->Import Library menu item of the software. That's it! You've installed a library! 

I believe that should be
Restart the Arduino application. Make sure the new library appears in the Sketch->INCLUDE Library menu item of the software. That's it! You've installed a library!

**Comment by matthijskooijman** [comment]
What document exactly? Could you provide a link?

**Comment by ruggb** [comment]
Sorry, I thought the title would be sufficient

https://www.arduino.cc/en/Guide/Libraries#toc5
it is p/o manual installation, 5 lines from the bottom

**Comment by lmihalkovic** [comment]
IMHO the only thing missing is the app not forcing an exit/restart cycle. I will try yo address that in my fork, ithink you might want to do the same.

**Comment by per1234** [comment]
Thanks @ruggb! The obsolete menu path in the documentation reported here has since been fixed. Unfortunately some typos were introduced but that's a topic for a fresh issue.
