### ISSUE TITLE
Add BME280 Library to Arduino library manager.

### ISSUE THREAD

**Issue by finitespace** [arduino/Arduino#4370]
Hello All,

I created a library for my greenhouse to read data from the new Bosch BME 280 environmental sensor.
I thought I would share it for other people to use. The link is below. 

https://github.com/finitespace/BME280.git

Provides an Arduino library for reading and interpreting Bosch BME280 data.

Reads temperature, humidity, and pressure. Calculates altitude and dew point. Provides functions for english and metric. Also reads pressure in Pa, hPa, inHg, atm, bar, torr, N/m^2 and psi.

Cheers! And happy holidays!

**Comment by cmaglie** [comment]
Done, thanks!

**Comment by finitespace** [comment]
Thanks!
