### ISSUE TITLE
Add Oregon Library to Arduino library manager

### ISSUE THREAD

**Issue by Mickaelh51** [arduino/Arduino#4371]
Hi,
I created a new library to decode Oregon Sensors.
Can you add this new library in your Arduino development ?

Features:
- Oregon sensor's battery level
- Oregon sensor's id
- Oregon sensor's type
- Oregon sensor's channel
- Oregon sensor's temperature
- Oregon sensor's humidity

```
Arduino UNO <-- (PIN 2) --> 433Mhz receiver <=============> Oregon sensors
```

https://github.com/Mickaelh51/Arduino-Oregon-Library.git

thanks in advance

**Comment by cmaglie** [comment]
Done, thanks!
