### ISSUE TITLE
Ethernet Server available() documentation issue

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#4373]
On the Server class available() documentation:

https://www.arduino.cc/en/Reference/ServerAvailable

The words "available() inherits from the Stream utility class" are incorrect.  Stream's available() function returns an integer, indicating how many bytes may be read.  Server's available() returns a Client object, not an integer.  The returned Client object inherits from Stream.  The Server object does not.

**Comment by agdl** [comment]
Fixed thank you!
