### ISSUE TITLE
Typing error in learning reference

### ISSUE THREAD

**Issue by BertUpm** [arduino/Arduino#4374]
Hello, there is a typing error on the Bitwise AND (&), Bitwise OR (|), Bitwise XOR (^) reference page:

![unbenannt](https://cloud.githubusercontent.com/assets/12617636/12072366/8c79202a-b0db-11e5-910b-76d93b4cfa6d.JPG)

**Comment by facchinm** [comment]
Fixed, thank you for reporting!
