### ISSUE TITLE
Add mfrc522 library

### ISSUE THREAD

**Issue by Rotzbua** [arduino/Arduino#4382]
Please add RFID library:
https://github.com/miguelbalboa/rfid

**Comment by cmaglie** [comment]
@Rotzbua 
the release tagged 1.1.2 has a library.properties with version set to 2015.9.4:

https://github.com/miguelbalboa/rfid/blob/v1.1.2/library.properties

if I add the library as is the release 1.1.2 will be published on top of the other as the latest version "2015.9.4" that is probably not what you want. To solve this you can remove the tag "1.1.2" or add another commit to fix the release number (basically branching from 7e9a17d and moving the tag 1.1.2 from 7e9a17d to the new commit).

**Comment by Rotzbua** [comment]
@cmaglie 
I reported to the repo owner and now it seems fixed :)
Is there any tool to check a library/tags?

**Comment by cmaglie** [comment]
great, thanks!

> Is there any tool to check a library/tags?

Not yet, this should be still done manually, we are working on some web service to do so, but not soon.
