### ISSUE TITLE
Request to add in Library Manager

### ISSUE THREAD

**Issue by psychogenic** [arduino/Arduino#4386]
Greetings,

I'd like to request having a library added to the library manager.

Chronos is a C++ library that makes manipulating date-times easy in order to perform scheduling, setup calendars and find points in time that are of interest.  It is designed to work with time sources (like the Time library) and add a great deal of functionality with very little memory usage, allowing it to be useful on even the tiniest Arduino.

It is comprised of three major components: 
* DateTimes and Spans: object-oriented date-time objects that can be manipulated in many ways

* Time marks: sets of timeline points like "every Sunday at 15h00" or "every first of the month"

* Calendar Events: actual events with fixed or repeating datetimes of specific duration, and the  functions needed to find past, current and future event occurrences.

and has complete examples included.

Github URL:
https://github.com/psychogenic/Chronos

**Comment by cmaglie** [comment]
Done, thanks!
