### ISSUE TITLE
'readonly' does not name a type

### ISSUE THREAD

**Issue by vit46** [arduino/Arduino#4401]
Hi, I think this should work like it works in C ++
class MyClass {
public:
readonly int x; // x can not modify out of this class

}

But the result is error: 'readonly' does not name a type

**Comment by matthijskooijman** [comment]
I think you're confusing C++ with  C#: C++ does not have a `readonly` modifier, but C# has. See also http://www.cplusplus.com/forum/articles/36872/ or http://stackoverflow.com/questions/6020506/what-is-the-c-equivalent-of-cs-readonly-field-modifier

I'm closing this issue, as it works as expected AFAICS.

**Comment by vit46** [comment]
Yes, you're right :)
