### ISSUE TITLE
Can't verify/upload with directory junctions in the Arduino libraries folder

### ISSUE THREAD

**Issue by thewknd** [arduino/Arduino#4402]
With Arduino 1.6.7 on Windows 7 I've been unable to verify/upload when the folder for the custom libraries (*Documents\Arduino\libraries*) contains a directory junction. (I use directory junctions to switch between different library versions)

Error message:

    C:\arduino167\arduino-builder -dump-prefs -logger=machine -hardware "C:\arduino167\hardware" -tools "C:\arduino167\tools-builder" -tools "C:\arduino167\hardware\tools\avr" -built-in-libraries "C:\arduino167\libraries" -libraries "C:\Users\thewknd\Documents\Arduino\libraries" -fqbn=arduino:avr:uno -ide-version=10607 -build-path "C:\Users\thewknd\AppData\Local\Temp\buildf861fa3b4440ac4767ab26e18e654c6c.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "C:\Users\thewknd\AppData\Local\Temp\untitled175997220.tmp\sketch_jan08a\sketch_jan08a.ino"
    readlink C:\Users\thewknd\Documents\Arduino\libraries\test: The system cannot find the file specified.

    Error compiling.

test is the directory junction, created with

    MKLINK /J "C:\Users\thewknd\Documents\Arduino\libraries\test" "C:\Users\thewknd\Documents\test"
 
With Arduino 1.6.5r5 everything was fine (didn't use 1.6.6)

**Comment by facchinm** [comment]
Moved to https://github.com/arduino/arduino-builder/issues/90
