### ISSUE TITLE
Remember window positions

### ISSUE THREAD

**Issue by PickyBiker** [arduino/Arduino#4404]
When Arduino starts, it alway opens in a small window rather than remembering the window positions that were last used.  Please add a feature to remember the last window positions. 

Here's an example with the arduino window stretched to take up 3/4ths of the screen starting at the left side of the screen and then the Serial Monitor on the right 1/4 of the screen.  
![capture](https://cloud.githubusercontent.com/assets/16281039/12203246/9119e03e-b5f3-11e5-8651-13fee413787c.JPG)

**Comment by lmihalkovic** [comment]
I was considering docking the monitoring window inside the editor, pretty much where you have it in your setup, and insuring that the data shows up in the proper editor (for scenarios where someone would let things run for a bit while working on some other source in a different editor window). Anyone thinks it might have some possible usefullness?
