### ISSUE TITLE
Ship appdata.xml with Linux builds

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#4406]
Please ship [arduino.appdata.xml](https://github.com/arduino/Arduino/blob/master/build/linux/dist/appdata.xml) with the Linux builds provided on https://www.arduino.cc/en/Main/Software. As of today, the file is present in git but absent from the binary builds.

**Comment by cmaglie** [comment]
where this file is expected to be? in the root folder of the zip file (together with the `arduino` executable)?

**Comment by probonopd** [comment]
According to the [spec](http://people.freedesktop.org/~hughsient/appdata/), it would normally go to `/usr/share/appdata/arduino.appdata.xml` but since Arduino zip files are not packages that are installed into the system by a package manager I think it's not really specified; close to `desktop.template` would probably make sense. The user or some script acting on behalf of the user will then be able to copy it from there and install it in the system.
