### ISSUE TITLE
DAC MCP4822 Firmware Library for inclusion.

### ISSUE THREAD

**Issue by feilipu** [arduino/Arduino#4416]
https://github.com/feilipu/Goldilocks_Analogue_DAC_Library

This library implements firmware for the MCP4822 12-bit, dual channel, SPI interface, DAC integrated into the Goldilocks Analogue, a ATmega1284p MCU classic Arduino board.

IIR filtering functions with (high, band, and low) pass configuration options are are available and can be used prior to audio output.

**Comment by cmaglie** [comment]
Done thanks!

**Comment by feilipu** [comment]
Closed without a tag for 1.6.8 inclusion.
Oversight?

**Comment by matthijskooijman** [comment]
Libraries are included directly, in an online index, and not released as part of a specific IDE version. They should be available in all versions of the IDE by now.
