### ISSUE TITLE
Opening the Serial Monitor while uploading is not a good idea

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#4420]
This should be blocked or it should be opened grayed out and then starts to listen.

**Comment by matthijskooijman** [comment]
This is related to #3771, a rewrite to fix that one should probably also pick up this issue.

**Comment by facchinm** [comment]
Solve by #4482 (commit 3f07b8a)

**Comment by facchinm** [comment]
Fixed by merging 6d5597b070c7bedce15047c7c560249965cc0bfc
