### ISSUE TITLE
Compiles fail after auto conversion from .pde to .ino

### ISSUE THREAD

**Issue by KeithV** [arduino/Arduino#4426]
If you set in Preferences the "Update sketch files to new extension on save" and open a sketch that is a .pde and just do a "save" and then build. You will get an error that the .pde can't be found. I believe that is because the file was a .pde when opened, but when the save occurred the IDE did not switch the build from a .pde extension to a .ino extension and still attempts to compiler the .pde instead of the renamed .ino. Restarting the IDE solves the problem.

**Comment by lmihalkovic** [comment]
It has been my experience that the ide does not like renames in general. the first day i tried using it, i changed a file's extension and it took me a while to figure that there were 2 files as the original was still in the build folder 1.6.5 at the time). Thx for the info.

**Comment by matthijskooijman** [comment]
@KeithV, could you see if this still occurs with the version shown there: https://github.com/arduino/Arduino/pull/4363#issuecomment-170562023 That pull request contains a lot of cleanups and small improvements, among which some improvements to the renaming code.

**Comment by facchinm** [comment]
Fixed by #4363
