### ISSUE TITLE
Page should reveal that SD.read() can read multiple bytes, just like SD.write() can write them.

### ISSUE THREAD

**Issue by CosmickGold** [arduino/Arduino#4427]
The page for SD.write()
https://www.arduino.cc/en/Reference/FileWrite
correctly points out that SD.write() can write any number of bytes at once, and gives the syntax as:
file.write(data) 
file.write(buf, len)

However the page for SD.read()
https://www.arduino.cc/en/Reference/FileRead
only states that SD.read() can read one byte at a time, and gives the syntax as:
file.read()

I proved with a sketch in Arduino 1.0.6 that SD.read() can also read any number of bytes, so it's page should explain this and show the syntax:
file.read(data) 
file.read(buf, len)

**Comment by agdl** [comment]
Done thank you!
