### ISSUE TITLE
Arduino 1.6.6 crashes sometimes at Windows XP

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#4429]
Sometimes Arduino crashes suddenly, than I start again and often I can continue without any crashes further. In older Arduino versions this happens never. 

This is the logfile:
A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x78ab0aa3, pid=56556, tid=51720

 JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
 Java VM: Java HotSpot(TM) Client VM (25.66-b17 mixed mode windows-x86 )
 Problematic frame:
 C  [msvcr100.dll+0x10aa3]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

---------------  T H R E A D  ---------------
Current thread (0x03910400):  JavaThread "cc.arduino.packages.discoverers.network.NetworkChecker" [_thread_in_native, id=51720, stack(0x03f90000,0x03fe0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x052b3000

Registers:
EAX=0x00000000, EBX=0x00000000, ECX=0x00000078, EDX=0x00000001
ESP=0x03fdf620, EBP=0x03fdf62c, ESI=0x052b3000, EDI=0x052d61d0
EIP=0x78ab0aa3, EFLAGS=0x00010202

etc etc..................

**Comment by per1234** [comment]
Since Arduino IDE [is no longer compatible with Windows XP](https://github.com/arduino/Arduino/issues/10018), I'm closing this.
