### ISSUE TITLE
Better code for Tone() tutorial [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#443]
This is [Issue 443](http://code.google.com/p/arduino/issues/detail?id=443) moved from a Google Code project.
Added by 2011-01-01T08:42:15.000Z by [fvdma...@gmail.com](http://code.google.com/u/111993498251185928304/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Examples
### Original description

Addition of rest notes in melody[] by specifying a note with value 0.
Better name for noteDurations[], they are divisions, not durations.
Real melody as example.
Automatic counting of melody size with sizeof().
See attached [file](http://storage.googleapis.com/google-code-attachments/arduino/issue-443/comment-0/toneMelody2.pde).

**Comment by per1234** [comment]
Moved to https://github.com/arduino/arduino-examples/issues/6
