### ISSUE TITLE
ArduinoToBreadboard needs to be updated for Arduino Studio

### ISSUE THREAD

**Issue by quizzicus** [arduino/Arduino#4435]
The instructions at https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard (unsurprisingly) don't work in ArduinoStudio. I'm assuming the attached hardware definitions (zip files) need to be updated and/or ArduinoStudio doesn't yet have the ability to load new definitions.

**Comment by per1234** [comment]
Arduino Studio is a different company's software so you would need to contact them with any support requests.
