### ISSUE TITLE
Version string in about box unreadable in hourly builds

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#4437]
White text on light grey background doesn't make for great readability:

![screenshot_2016-01-16_15-54-28](https://cloud.githubusercontent.com/assets/2480569/12372963/7482df8a-bc69-11e5-90ed-0b148d0687e9.png)

**Comment by ivanebernal** [comment]
I can fix this. I'm currently trying to contribute to a big open source project.

**Comment by cmaglie** [comment]
Fixed by #4745
