### ISSUE TITLE
Update library notification window overlays everything on screen

### ISSUE THREAD

**Issue by probonopd** [arduino/Arduino#4441]
On Xubuntu 15.10, the Update library notification window overlays everything on screen, including other applications such as the web browser or a text editor:

![screenshot_2016-01-16_22-04-22](https://cloud.githubusercontent.com/assets/2480569/12374539/8f2e902e-bc9e-11e5-9149-58cd2022e162.png)

The update window should not overlay non-Arduino windows.

Tested with the latest hourly build.

**Comment by per1234** [comment]
See https://github.com/arduino/Arduino/issues/3809

**Comment by probonopd** [comment]
Agree, looks like a duplicate, so closing this.
