### ISSUE TITLE
New Ring Buffer Library

### ISSUE THREAD

**Issue by wizard97** [arduino/Arduino#4443]
Hi,
I wrote a Ring Buffer library implementation that I would like to share. I have followed the Arduino IDE 1.5 specification.

Here is a link to my repo:
https://github.com/wizard97/ArduinoRingBuffer

Thanks,
Aaron

**Comment by agdl** [comment]
@wizard97 if you want to add your library to the library manager please make sure to follow this procedure
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by wizard97** [comment]
I followed that procedure. 

I conformed to the 1.5 format, and I included a library.properties file. What am I missing?

Thanks in advance,
Aaron

**Comment by matthijskooijman** [comment]
The repo and tags look good to me. @agdl, was there anything you were missing in particular?

**Comment by cmaglie** [comment]
I added the library, so it's now published on the library manager.

BTW there is a spurious release "v1.2" that points to a `library.properties` containing `1.1`:
https://github.com/wizard97/ArduinoRingBuffer/blob/v1.2/library.properties

as it is, is not a problem for the library manager, but you may want to delete this tag for cleanness and keep only "1.2" and "1.1".

**Comment by wizard97** [comment]
Thanks for pointing that out, that was an error on my part.

I deleted the "v1.2" tag. Thanks!
