### ISSUE TITLE
Pushbutton Library

### ISSUE THREAD

**Issue by Gemelon** [arduino/Arduino#4449]
I have wrote a library to debounce a pushbutton and interpret the pushbutton state on an Arudino Digital Input. I like to share it on the library manager.

Here is the link:
https://github.com/Gemelon/Pushbutton

**Comment by cmaglie** [comment]
there are no tag/releases on your repository https://github.com/Gemelon/Pushbutton/releases

you must create one to publish the library in the library manager.
See:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen it if necessary
