### ISSUE TITLE
Arduino IDE misbehaves with links (junctions) on Windows

### ISSUE THREAD

**Issue by faxik** [arduino/Arduino#4454]
I develop a large project that is split into libraries. I used to make links (junctions) from development directories to the Arduino Libraries directory. That allows for quick edit-and-test cycles, as the changes are in effect immediately. This worked good in 1.x; this semi-worked in 1.6.5 and seems to be completely broken in 1.6.6 (maybe, somehow related to Java 8 or new library discovery): IDE just doesn't "see" the linked libraries.

Furthermore, uninstaller deletes not the links, but traverses and deletes all the files which can be very disasterous.

**Comment by facchinm** [comment]
Leaving here for the discussion about the uninstaller.
Moving to https://github.com/arduino/arduino-builder for junctions not traversed bug

**Comment by matthijskooijman** [comment]
@facchinm, Note that this is a duplicate of https://github.com/arduino/arduino-builder/issues/90

**Comment by facchinm** [comment]
Right, closing arduino/arduino-builder#98 as duplicate :smile:

**Comment by facchinm** [comment]
Completely moved to arduino/arduino-builder#90, closing this one
