### ISSUE TITLE
variant.h or variant.cpp file for DUE to assign PC20

### ISSUE THREAD

**Issue by castfxman** [arduino/Arduino#4455]
I have an Arduino DUE based board and need to have PC20 on the SAM3X8E chip go to one of my motors.  This was done by DigiX for a board based on the DUE and I am trying to do the same thing but just with one pin.  I don't know if I should be rewriting the variant.h file or variant.cpp file in the Hardware\arduino\sam\variants\arduino_due_x section.  Any help would be appreciated so I don't have to just print the board differently.  Thank you in advance!

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#11
