### ISSUE TITLE
Not able to install New IDE on Ubuntu64 14.04.3

### ISSUE THREAD

**Issue by VMikeM** [arduino/Arduino#4464]
Newbie, need step by step example.

**Comment by matthijskooijman** [comment]
This issue tracker is intended for bugs and feature requests related to the Arduino IDE, not for general support. I recommend you ask on the Arduino forums instead. I also recommend you include more details with your question: What have you tried so far? Did you run into problems? Any error messages? etc.

**Comment by VMikeM** [comment]
Thanks
