### ISSUE TITLE
Library: Simple, Stable and Fast DHT Library

### ISSUE THREAD

**Issue by winlinvip** [arduino/Arduino#4469]
I have wrote a simple and fast library for DHT sensor. I like to share it on the library manager.

1. Simple: Simple C++ code with lots of comments.
1. Stable: Follow the DHT11 protocol strictly.
1. Fast: Support 0.5HZ or 1HZ sampling rate.

Here is the link:
https://github.com/winlinvip/SimpleDHT

**Comment by winlinvip** [comment]
The release: https://github.com/winlinvip/simple-dht/releases
I have check the https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

Thanks~

**Comment by agdl** [comment]
Done!

**Comment by winlinvip** [comment]
Great, thanks~
I will contribute more HDT sensor in future.
