### ISSUE TITLE
Library: statsd client for Arduino

### ISSUE THREAD

**Issue by jasiek** [arduino/Arduino#4477]
Hey,

I wrote a library that implements a statsd client and should work with Ethernet and WiFi. If possible, I'd like this to be added to the Library Manager.

https://github.com/jasiek/arduino-statsdclient

Cheers,
Jan

**Comment by agdl** [comment]
Hi, your tag has a 'v' in front of the version number. This is not valid. Please follow this guide:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jasiek** [comment]
Fixed.

**Comment by agdl** [comment]
Done! You will see it soon in the library manager!
