### ISSUE TITLE
Attiny24 ISP Arduino 

### ISSUE THREAD

**Issue by Mike-Menci** [arduino/Arduino#4478]
Arduino: 1.6.5 (Windows 7), Board: "ATtiny24 (internal 8 MHz clock)"

Error while burning bootloader: missing 'bootloader.tool' configuration parameter

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by matthijskooijman** [comment]
What attiny core are you using? You should probably report this with the maintainer of the core, unless you think this is a bug in the Arduino IDE itself?

**Comment by sandeepmistry** [comment]
Closing this due to lack of feedback, please re-open with requested information.
