### ISSUE TITLE
Request to add Ubidots_FONA library to lib package manager

### ISSUE THREAD

**Issue by Metavix** [arduino/Arduino#4480]
Repoo: https://github.com/ubidots/Ubidots-FONA/tree/1.0.0

Most recent tag: https://github.com/ubidots/Ubidots-FONA/tree/1.0.0

Thanks!

**Comment by agdl** [comment]
Hi, in your version number in the library.properties a .0 is missing. Now you have 1.0. The tag instead is correct. So you have to remove the tag and make a new one with the right librray.properties

**Comment by Metavix** [comment]
Hello! I changed library.properties to match with our tag number. Thanks you

**Comment by agdl** [comment]
Added!
