### ISSUE TITLE
Request to add Plotter to library manager

### ISSUE THREAD

**Issue by devinconley** [arduino/Arduino#4481]
https://github.com/devinconley/ArduinoPlotter-for-Library-Manager

Thanks,
Devin

**Comment by agdl** [comment]
Hi, your tag has a 'v' in front on the version. This isn't supported. Please try to follow this guide:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by devinconley** [comment]
Thanks, I have changed the tag from v1.0.0 to 1.0.0

**Comment by agdl** [comment]
I'm adding it, but please remove the tag with the v
