### ISSUE TITLE
request to add Rtc library

### ISSUE THREAD

**Issue by Makuna** [arduino/Arduino#4485]
https://github.com/Makuna/Rtc

**Comment by agdl** [comment]
like for #4484 this library is without a tag

**Comment by cmaglie** [comment]
You should also give it a less generic name by adding a prefix, like MakunaRtc.

**Comment by Makuna** [comment]
Do you mean change the class name and folder names to be MakunaRtc?  Or just the name in the properties file?

**Comment by cmaglie** [comment]
I mean the library name in properties file, because people may search for "Rtc" and find your library, thinking about a generic Rtc library, but confused afterwards by the fact that is a library specific for some models of RTC.

**Comment by Makuna** [comment]
Tag added.  "v1.0"
I updated the library title to MakunaRtc as suggested.

**Comment by agdl** [comment]
@Makuna please delete the tag v1.0 (a .x is missing) and rename the tag v1.0.0 into 1.0.0 (without the v)  in order to be compliant with the other libraries

**Comment by Makuna** [comment]
mmm, you can't require all tags to be just used for your system.  I could have the tag v1.0 for other purposes (other library managers) that you need to ignore/filter.  How do you plan to support this?

**Comment by agdl** [comment]
I added it. You should see it in the library manger in an hour. 

For what concern the tags actually you can write whatever you want but for compliance with all the other library I requested you to follow the "standard". What you actually see in the library manager is what is written in the library.properties associated to the tag that for the sake of simplicity is equal to the name of the tag with only numbers like in all the other libraries. I'm telling you this for what you asked in #4484

**Comment by Makuna** [comment]
It is showing up with the wrong name.  What are you seeing?

I see MakunaRtc, but the properties files lists "Rtc by Makuna".

**Comment by agdl** [comment]
![screenshot from 2016-01-29 11 35 12](https://cloud.githubusercontent.com/assets/2743774/12673380/b46e496e-c67c-11e5-9d42-4b13e5373165.png)

**Comment by Makuna** [comment]
I rebooted my computer the problem went away.  Some sort of caching?  The name I was seeing was what I changed it too before I submitted the fix.  I switched to the name you see just before submitting.  Even restarting the IDE didn't help.  Oh well, problems gone.
