### ISSUE TITLE
Request to add Cytron G15 Shield library

### ISSUE THREAD

**Issue by IdrisCytron** [arduino/Arduino#4486]
The library can be found at the following GitHub link.
https://github.com/CytronTechnologies/Cytron-G15Shield

Thank you.

**Comment by agdl** [comment]
Hi you library does not define any tag, so it can't be added at the moment. Please follow this guide:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by IdrisCytron** [comment]
Hi, I already create a release for this library. Thanks.

**Comment by agdl** [comment]
Done! you will see it soon in the library manager!

**Comment by IdrisCytron** [comment]
Hi, when this library will available on Arduino Library Manager? Thanks.

**Comment by agdl** [comment]
It is already available!

**Comment by IdrisCytron** [comment]
I have search "Cytron G15 Shield" on Arduino Library Manager, but nothing found. Please advice.

**Comment by agdl** [comment]
![screenshot from 2016-01-28 09 58 34](https://cloud.githubusercontent.com/assets/2743774/12639678/ed2e70a8-c5a5-11e5-968b-1f6b86357c50.png)

**Comment by IdrisCytron** [comment]
My Arduino IDE still can't search for this library. Nevermind, I try to install the latest IDE. Anyway, thanks for your help. :)
