### ISSUE TITLE
AC Phase Control Documentation

### ISSUE THREAD

**Issue by stefanmeili** [arduino/Arduino#4493]
In the circuit shown in:
http://playground.arduino.cc/Main/ACPhaseControl

I suspect that R3 and R4 should be exchanged.

**Comment by matthijskooijman** [comment]
@stefanmeili, the playground area of the site is a wiki, so you can just create an account and edit the page yourself! I had a quick look at the circuit myself, but I can't tell if you're correct without looking more closely. If you want more feedback on your observation, the best approach is probably to ask on the Arduino forums and then edit the page once you are satisfied it is indeed incorrect.

I'm closing this issue, as this is not really a bug or feature request for the Arduino IDE.
