### ISSUE TITLE
error in http://playground.arduino.cc/Main/FindText

### ISSUE THREAD

**Issue by edfraenkel** [arduino/Arduino#4494]
The described function doesn't do what it is supposed to. If the word is at the end of the 'haystack' then it will not be matched with 'needle' because the comparison in the for statement: "<" should be "<=".

**Comment by matthijskooijman** [comment]
@edfraenkel, the playground area of the site is a wiki, meaning you can edit it yourself if you register for an account. As for the change you propose: agreed, it should indeed be `<=`. I'm closing this issue, feel free to correct the playground yourself.
