### ISSUE TITLE
Arduino Uno Pack

### ISSUE THREAD

**Issue by THMAcidGuNZz** [arduino/Arduino#4507]
Hi i bought the Arduino pack and it says it came with 2 tact push switch but it did not come with any Thank You my email is Itzgiovannidiaz@gmail.com

**Comment by agdl** [comment]
@THMAcidGuNZz Arduino pack is not a product sold by arduino.cc and furthermore GitHub is intended for SW related issue this is the reason why I'm closing this. I suggest you to contact the reseller that sold you this and ask him for assistance.
