### ISSUE TITLE
EEPROM function definitions 

### ISSUE THREAD

**Issue by cvmanjoo** [arduino/Arduino#4520]
Where can i find function definitions for EEPROM Libraries.
I'm able to find EEPROM.h file but not the .c file. Can one help.?

Thanks,
Sorry If i posted this question is wrong place.

**Comment by agdl** [comment]
https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/libraries/EEPROM

Here. I'm closing this

**Comment by Chris--A** [comment]
There is no .c or .cpp file, it is entirely implemented in the header!

**Comment by cvmanjoo** [comment]
@Chris--A  Ya got it thanks.

**Comment by q2dg** [comment]
I don't understand the meaning of https://github.com/arduino-libraries, then... EEPROM library isn't there although other seems to be...

**Comment by Chris--A** [comment]
That is for exclusively owned Arduino LLC libraries. You'll notice all the repos have *"Copyright (c) Arduino LLC. All right reserved."*.

Whereas that claim cannot be placed on this library at it has been written by myself and attributed to the fact in the licence. The library is just being used by the Arduino AVR core.

**Comment by q2dg** [comment]
Oh, I see. 
Thanks a lot for the clarification!
