### ISSUE TITLE
Another entry for Linux in "Why I can't upload my programs to the Arduino board?" (Arduino Troubleshooting)

### ISSUE THREAD

**Issue by dilope** [arduino/Arduino#4524]
In https://www.arduino.cc/en/Guide/Troubleshooting#toc1 there should be added:
Run
```
sudo usermod -a -G tty yourUserName
sudo usermod -a -G dialout yourUserName
```
Log off and log on again for the changes to take effect!
And/or a link to http://playground.arduino.cc/Linux/Debian

**Comment by agdl** [comment]
@dilope done if it is ok for you close the issue please!

**Comment by q2dg** [comment]
Is first command really necessary?

**Comment by agdl** [comment]
@q2dg actually it isn't but nothing bad happens if you use it :) I'm closing this issue since 14 days are elapsed!
