### ISSUE TITLE
Can't create/use a project with ANY name

### ISSUE THREAD

**Issue by Gargo** [arduino/Arduino#4540]
It doesn't allow to use .ino file until it will be in the folder with the same name. BUT WHY?

**Comment by agdl** [comment]
@Gargo because this is the arduino standard: you must have a folder that is named as the main .ino file. In the same folder you can also have other .ino files but also .h, .cpp .s etc.
The file with the same name as the folder is the main file. Actually this isn't an issue so I'm closing this!

**Comment by Gargo** [comment]
You have closed it too early.
Okay, I want to copy a folder which contains my project into the same folder. It becomes a hell if this folder contains a lot of files. Could you suggest an appropriate solution?

**Comment by PaulStoffregen** [comment]
> becomes a hell if this folder contains a lot of files. Could you suggest an appropriate solution?

Maybe use Ctrl-A (or Cmd-A on a Macintosh) to select all the files.  Then press and hold your mouse button on any of the file, and use a movement of the mouse to drag the entire lot to the new location.  Is that so hard?

**Comment by Gargo** [comment]
The same trouble - the parent folder will have the different name and I would have a possibility to place ino files into the same folder with other. Or do you suggest to have 2 folders inherited into each other? Maybe but there is no other ide which is so "user friendly"

**Comment by matthijskooijman** [comment]
I'm not exactly sure I understand the question exactly, but you can open up a sketch and use "save as" to copy it to a different name, or use "rename" in the tab menu (the arrow to the right of the tab bar) to rename the sketch.

**Comment by Gargo** [comment]
yes. And after these actions try to open it

**Comment by matthijskooijman** [comment]
I'm pretty sure I did that recently, without any problems. Is save as / rename not working for you in the IDE?

**Comment by Gargo** [comment]
The problem is I can't open the project file except of the situation when it is in a folder with the same name
