### ISSUE TITLE
Contributing to "IDE examples" ?

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#4543]
What if any is a accepted process to submit contributions to IDE code examples?

**Comment by facchinm** [comment]
You can simply open a pull request which modifies/adds examples in this folder https://github.com/arduino/Arduino/tree/master/build/shared/examples

**Comment by VaclavSal** [comment]
Thanks
OT question 
Why am I getting your notifications e-mails twice?
No big deal , I just read  one( duh) but just curious. 
I used to have similar issue on Arduino site - it would pull two quotes instead of only one.
