### ISSUE TITLE
CMSIS-DSP included with Arduino Due is not up to date

### ISSUE THREAD

**Issue by mochr** [arduino/Arduino#4544]
The CMSIS-DSP library included with the Arduino Due board installation is dated 25 July 2011 (CMSIS version 2.10), while the latest version of CMSIS-DSP is dated 20 October 2015 (CMSIS version 4.5.0). 

The CMSIS package seem to contain lots of useful functions, and it would be great to have it included in the Arduino IDE. Also the included CMSIS library did not work "out of the box", but required "{build.variant.path}/libarm_cortexM3l_math.a" to be added to platforms.txt, and the .a file to be copied to "..AppData\Local\arduino15\packages\arduino\hardware\sam\1.6.6\variants\arduino_due_x".

Is there a specific reason to why the library has not been updated, or should it be possible to exchange the old library with the new without too much work?

**Comment by pamribeirox** [comment]
I share the same opinion, for now, I think I'll be doing some hammering to use some DSP functions ...
regards.

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#10
