### ISSUE TITLE
Stabilize the pre-processing of sketches (e.g. prototype generation and #include insertion). [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#455]
This is [Issue 455](http://code.google.com/p/arduino/issues/detail?id=455) moved from a Google Code project.
Added by 2011-01-08T19:10:32.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-PreProcessor

### Original description

We need to be sure that the way we generate function prototypes and the #include for the Arduino core is one that we want to stick with.  The ordering of the WProgram.h include versus other includes in the user sketch has been a constant source of breakage and it's important to find a strategy to stick with.

**Comment by ffissore** [comment]
Posted answer on googlecode

**Comment by ffissore** [comment]
Fixed by #3779
