### ISSUE TITLE
[GSM library] Problem with letter "w"

### ISSUE THREAD

**Issue by antoinedewailly** [arduino/Arduino#4553]
Hello, 
I think I have a problem with this library.
I perfectly manage to send & receive messages into arduino with this librairy (and with AT command) but when i send messages from arduino via ethernet shield and webservice it's work with all the letters except "w" which deletes the rest of the message. exemple: i send "hello world" i receive "hello w"

Do you have an idea ?
Cordialy,
Antoine.

**Comment by antoinedewailly** [comment]
With the GSM librairy *

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/GSM#2
