### ISSUE TITLE
Suggest reinstating end() method in the SD library

### ISSUE THREAD

**Issue by dookaloosy** [arduino/Arduino#4559]
The old beta library (https://github.com/adafruit/SD) used to have an SDClass::end() method that could be used to close an SDClass session. Without it, removing and reinserting a storage card would trigger an failure upon calling SDClass::begin(), as the previous session hadn't been closed.

Suggest adding to SD.h:
//call this when a card is removed. It will allow you to inster and initialise a new card.
void end(); 

and to SD.cpp:
//call this when a card is removed. It will allow you to inster and initialise a new card.
void SDClass::end()
{
  root.close();
}

**Comment by per1234** [comment]
Transferred to https://github.com/arduino-libraries/SD/issues/90
