### ISSUE TITLE
Ethernet and GSM interfaces could keep track of total traffic (like netstat)

### ISSUE THREAD

**Issue by rhbroberg** [arduino/Arduino#4560]
Being able to capture the amount of traffic being used on an interface would be very useful, especially in a situation where the interface is on a network which incurs cost (like GSM).  A simple counter for bytes in/out, reported by the interface, much like 'netstat' shows, would be suitable.    Presumably the count could be made in GSM3SoftSerial::finalWrite()?

This would allow an application using GSM data to keep track of the data it is using, and perhaps make adjustments.  (Just like a mobile phone has a report showing you how much data you are using).

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#5
