### ISSUE TITLE
Does not contain a Windows JVM

### ISSUE THREAD

**Issue by iHateInventNames** [arduino/Arduino#4561]
Trying build on Gentoo Linux:
BUILD FAILED
/home/name/sources/oo/Arduino/build/build.xml:110: The following error occurred while executing this line:
/home/name/sources/oo/Arduino/build/build.xml:87: The following error occurred while executing this line:
/home/name/sources/oo/Arduino/build/build.xml:924: It looks like /usr/lib64/icedtea8/jre does not contain a Windows JVM

**Comment by facchinm** [comment]
Hi,
do you need to compile the IDE to run locally or to package it?
In the first case, once setting up JAVA_HOME env variable to point to Java8 (Oracle or openjdk), you can simply execute
```bash
cd build
ant build run
```
In the second case, you need to pass a couple of defines. For example, when packaging for Linux64, you should execute
```
ant dist -Djava.net.preferIPv4Stack=true -Dplatform=linux64 -DLINUX64_BUNDLED_JVM=/opt/jvm/linux64_jre1.8.0/
```

**Comment by iHateInventNames** [comment]
Thank you much

**Comment by sandeepmistry** [comment]
This looks resolved, closing.

**Comment by iHateInventNames** [comment]
I want to make a fresh ebuild for Gentoo
09.03.2016 19:23 пользователь "Sandeep Mistry" <notifications@github.com>
написал:
