### ISSUE TITLE
Add CoAP Simple Library to in Library Manager

### ISSUE THREAD

**Issue by hirotakaster** [arduino/Arduino#4565]
Hi, 
This CoAP library for Arduino is very simple and useful implementation about the CoAP.
https://github.com/hirotakaster/CoAP-simple-library
Thanks!

**Comment by agdl** [comment]
Hi, you library is tagged ad V1.0 by in the library.properties related to that tag I can see a 1.3.5 It is better if you fix it please

**Comment by hirotakaster** [comment]
Hi, I update v1.0 -> V1.3.5 on github.

**Comment by agdl** [comment]
Please remove the v1.0 tag and leave only the release 1.3.5

**Comment by agdl** [comment]
Done thank you!
