### ISSUE TITLE
Remove or update the arduino and arduino-core packages on Ubuntu's repository

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#4575]
It would be really nice if people could automatically update their Arduino IDE with their package manager but currently the IDE package available from Ubuntu's repository is version 1.0.5 would it be possible to start updating it again? Offering different channels like stable/unstable would be even nicer.

**Comment by per1234** [comment]
I believe what is preventing the recent versions from being available is https://github.com/arduino/Arduino/pull/2703

**Comment by cousteaulecommandant** [comment]
Ubuntu inherits most of its packages from Debian, and Debian's Arduino is 1.0.5.  However the `experimental` branch of Debian has 1.5.6.2 (wow, so much new).  Probably the way to solve this is to convince Debian first to update Arduino, and then insist Ubuntu to "inherit" it ASAP.  (This is, if there are no license issues.)

Alternatively, Areuino could provide a PPA if it doesn't already.

**Comment by Avamander** [comment]
Not Debian needs to be convinced, someone dealing with the Arduino project
needs to.

**Comment by matthijskooijman** [comment]
I'm closing this issue, at is indeed something to report upstream. AFAIK the update in Debian is indeed awaiting license clarification, but that is the subject of #2703, so there is no point in keeping this open separately as well.
