### ISSUE TITLE
Add MS5837-30BA pressure sensor library

### ISSUE THREAD

**Issue by rjehangir** [arduino/Arduino#4577]
Hello,

This library supports the new MS5837-30BA pressure sensor. 

https://github.com/bluerobotics/BlueRobotics_MS5837_Library

Please let me know if there are any issues.

-Rusty

**Comment by agdl** [comment]
Adeed to library manager! Thank you!

**Comment by rjehangir** [comment]
Thanks!

**Comment by jaxxzer** [comment]
@per1234 wonderful response, thank you.
