### ISSUE TITLE
Request to add the BLE SmartEverything Library in the Library Manager

### ISSUE THREAD

**Issue by searobin** [arduino/Arduino#4578]
Please add the following library:

Request for SmartEverything TDK SESUB-PAN-T2541 BLE module based on Texas Instruments CC2541 component.
repo = https://github.com/ameltech/sme-cc2541-library/
tag = https://github.com/ameltech/sme-cc2541-library/tree/v1.0.1

**Comment by agdl** [comment]
Done thank you!

**Comment by searobin** [comment]
Thanks  a lot.
