### ISSUE TITLE
Problems with the Linux install script

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#4581]
The first thing is that the desktop shortcut created is not marked executable (impossible to open by double click). Second thing is that the execution path should escape spaces in the path, it will result in an error without doing so. 

To test it put the Arduino installation in a folder that has space in the name and execute the install script. The desktop entry is invalid, possibly other entries too.

OS: Ubuntu 15.10 64bit

**Comment by herrold** [comment]
The problem also exists with the XFCE window manager

**Comment by facchinm** [comment]
FIxed by merging #6558
