### ISSUE TITLE
Request to add Pololu Raspberry Pi slave library for Arduino

### ISSUE THREAD

**Issue by pdg137** [arduino/Arduino#4583]
Hello,

This library sets up an Arduino as an I2C slave device for use with the Raspberry Pi.  We will be publishing a related tutorial soon, and it would be easier if people could install the library from the library manager.

https://github.com/pololu/pololu-rpi-slave-arduino-library

Please let me know if you see any problems with it.

Sincerely,
Paul Grayson

**Comment by agdl** [comment]
Done thank you!
