### ISSUE TITLE
Add Arduino_I2C_ESC Library to library manager

### ISSUE THREAD

**Issue by rjehangir** [arduino/Arduino#4590]
We would like to have the Arduino_I2C_ESC library included in the library manager. This library allows control of BlueRobotics ESCs, such as the BlueESC, through I2C control. It can also be used with other SimonK-firmware ESCs.

https://github.com/bluerobotics/Arduino_I2C_ESC

Please let me know if there are any issues.

Best regards,

Rusty

**Comment by agdl** [comment]
Done thank you!
