### ISSUE TITLE
Update Wifi101 from 0.6.0 to 0.8.0

### ISSUE THREAD

**Issue by chatelao** [arduino/Arduino#4592]
Hi, this would help a lot with the MKR1000

**Comment by agdl** [comment]
It is related to https://github.com/arduino/Arduino/issues/4496
It is already solved in the nightly build. In the stable it will be solved when the IDE will be released (very soon)

So please try the last nightly

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen it if needed
