### ISSUE TITLE
[Library Manager] Please add these libraries

### ISSUE THREAD

**Issue by leomil72** [arduino/Arduino#4601]
Please add these libraries to Library Manager:

- [swRTC](https://github.com/leomil72/swRTC) software implementation of a Real-Time Clock for Arduino boards and Atmel microcontrollers
- [leOS](https://github.com/leomil72/leOS) simple scheduler to execute little tasks in background using ISRs
- [leOS2](https://github.com/leomil72/leOS2) simple scheduler to execute little tasks in background using interrupts generated by the watchdog
- [looper](https://github.com/leomil72/looper) simple software scheduler to execute little jobs at specific intervals using a mechanism of time counting based on millis()
- [pRNG](https://github.com/leomil72/pRNG) pseudo-random number generator with good unpredictability
- [secTimer](https://github.com/leomil72/secTimer) a simple seconds counter
- [analogComp](https://github.com/leomil72/analogComp) library to use the internal analog comparator

**Comment by agdl** [comment]
Done thank you!
