### ISSUE TITLE
Add CMPS10 library to arduino library manager

### ISSUE THREAD

**Issue by neildhar** [arduino/Arduino#4607]
https://github.com/neildhar/Arduino_CMPS10

**Comment by agdl** [comment]
@neildhar please have a look at how Arduino libraries are structured
https://github.com/arduino-libraries/

and provide some example. When you will do it I will add this to the library manager!

**Comment by agdl** [comment]
Done thank you!

**Comment by agdl** [comment]
sorry wrong browser tab

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen it if when changes will be made
