### ISSUE TITLE
Add "Serial0" to keywords.txt in Adruino IDE

### ISSUE THREAD

**Issue by EmbeddedMan** [arduino/Arduino#4610]
Just like Serial1, Serial2, etc. some boards (like FubarinoSD, DP32, and chipKIT Pi) sometimes use a serial object called Serial0. Including this in keywords.txt would make the use of Serial0 less confusing to users.

**Comment by matthijskooijman** [comment]
I wonder if a platform has its own keyword.txt (or keywords.txt?), perhaps it would be better to put in there for those platforms, if this is possible?

**Comment by PaulStoffregen** [comment]
Yes, 1.6.7 supports a custom keywords.txt for each platform.  It goes in the same location as boards.txt and platform.txt.

**Comment by EmbeddedMan** [comment]
Woah! No way. That's simply awesome. A far better solution than changing
hard-coded values in the IDE. Thanks guys!
