### ISSUE TITLE
[Library Manager] Please add ArduinoFacil

### ISSUE THREAD

**Issue by kwendenarmo** [arduino/Arduino#4615]
https://github.com/SindormirNet/ArduinoFacil

Thanks!

**Comment by agdl** [comment]
A tag is missing in you library. Please follow this guide
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by kwendenarmo** [comment]
@agdl Done, thanks again!

**Comment by agdl** [comment]
Done thank you!
