### ISSUE TITLE
Ignore .git folders in /libraries

### ISSUE THREAD

**Issue by mcauser** [arduino/Arduino#4628]
If I git clone a library into the /libraries folder, I see warnings like this:
`WARNING: Spurious .git folder in 'DHT sensor library' library`

The library manger is great, but sometimes I want to use git.

Could the Arduino IDE ignore `/libraries/**/*/.git`?

I'm using Arduino IDE 1.6.6 on OSX 10.10.5

**Comment by per1234** [comment]
That's been done since 1.6.7. In the future please test the [hourly build](http://www.arduino.cc/en/Main/Software#hourly) before reporting an issue to make sure it hasn't already been fixed.

**Comment by mcauser** [comment]
@per1234 My bad :)
