### ISSUE TITLE
IDE: allow to hide tabs for better handling projects with many .h and .cpp files [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#463]
This is [Issue 463](http://code.google.com/p/arduino/issues/detail?id=463) moved from a Google Code project.
Added by 2011-01-18T03:15:30.000Z by [pablo...@gmail.com](http://code.google.com/u/110533151206976731339/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I like to see that Arduino IDE resembles a normal C++ IDE, that displays only the files you want to edit and not the entire project all the time.

Because tabs are really uncomfortable when working with large projects with several files, such as in Arduino Mega, for example.

No, I do not think that this will cause any incompatibilities

**Comment by ffissore** [comment]
Wontfix. IDE has a tab menu located upper right corner. Opening the files you want to edit only implies having a file manager side panel, which we won't have, at least for now
