### ISSUE TITLE
AVR Boards platform.txt was modified and released without changing version

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4633]
`recipe.preproc.macros` in Arduino AVR Boards platform.txt was modified in https://github.com/arduino/Arduino/commit/802c7456909f7b06780ffaa1f5acb379a9e337e4 but the version number was never changed before the Arduino IDE 1.6.7 release. This means the Arduino AVR Boards 1.6.9 [included with Arduino IDE 1.6.6](https://github.com/arduino/Arduino/blob/1.6.6/hardware/arduino/avr/platform.txt#L89) and installed via Boards Manager is different from the one [included with Arduino IDE 1.6.7](https://github.com/arduino/Arduino/blob/1.6.7/hardware/arduino/avr/platform.txt#L89). I understand that nothing can be done about this now but I'm hoping you might consider implementing a system/policy to be sure this doesn't happen again.

**Comment by cmaglie** [comment]
thanks @per1234 

I've placed a check in the build script, now running the `dist` target with:

`ant -Drevision.check=enforce dist`

will produce an error for mismatching cores:

```
revision-check:
     [echo] AVR Arduino core version in platform.txt is: 1.6.10
     [echo]                     latest in index.json is: 1.6.9

BUILD FAILED
/home/megabug/Code/arduino/build/build.xml:271: Mismatching versions for bundled AVR core and package_index.json.
      Please check your platform.txt and package_index.json.

Total time: 2 seconds
```

This should enforce the correct release, if I'm not missing something else...
