### ISSUE TITLE
My request to add NeoPixelBus Library has yet to show up

### ISSUE THREAD

**Issue by Makuna** [arduino/Arduino#4643]
I could not reopen the original https://github.com/arduino/Arduino/issues/4484, so I created a new issue. 

My library located at https://github.com/Makuna/NeoPixelBus has not yet shown up in the list after four days.  My other libraries showed up over night so I am concerned there is an issue.

**Comment by sandeepmistry** [comment]
I can see it in the Library Manager on my Mac with IDE v1.6.7:

<img width="802" alt="screen shot 2016-03-03 at 2 33 43 pm" src="https://cloud.githubusercontent.com/assets/1163840/13506653/225c16a0-e14d-11e5-8191-914d2c32f1cc.png">

What IDE version and OS are you using?

**Comment by Makuna** [comment]
v1.6.7 on Win10.  Your search above gives no results, I search for NeoPixel and below is what I get.

![image](https://cloud.githubusercontent.com/assets/7972357/13507199/7ee0d102-e136-11e5-8e9f-20c147a94585.png)

Search for Makuna, and this is all I get
![image](https://cloud.githubusercontent.com/assets/7972357/13507277/cc570a64-e136-11e5-82fb-199a470884c9.png)

**Comment by sandeepmistry** [comment]
Ok, you're hitting this issue: https://github.com/arduino/Arduino/issues/4139#issuecomment-156857120

This issue has be resolved, however we have not released a new IDE version with the fix (https://github.com/arduino/Arduino/pull/4361).

Suggested workarounds for now:
 * Delete ```%LOCALAPPDATA%\Arduino15\library_index.json.tmp.gz``` and then restart the IDE.
 * Or try an hourly IDE build.

**Comment by Makuna** [comment]
Ok, that works.

Is there an estimate as to when the next IDE will get published?  I have had a few users who raised this issue to me.

**Comment by sandeepmistry** [comment]
IDE 1.6.8 is out now.
