### ISSUE TITLE
Library can't use both 'src' and 'utility' folders.

### ISSUE THREAD

**Issue by harryboo** [arduino/Arduino#4653]
Hi,

with latest nightly build i get this error:

Library can't use both 'src' and 'utility' folders. Double check C:\Documents and Settings\Test\Desktop\arduino-1.6.8\hardware\arduino\avr\libraries\Wire

The latest nightly build that was tested and was working 19.02.2016.

Thanx

**Comment by sandeepmistry** [comment]
@harryboo I've submitted a fix for this in PR #4655.

**Comment by harryboo** [comment]
Hi,

this fixes the problem.....

Thanx Jens

**Comment by domonetic** [comment]
not solved

**Comment by harryboo** [comment]
This Problem is solved. Tested with latest nightly build also.
