### ISSUE TITLE
Arduino AVR Boards don't appear in hourly build

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4656]
Arduino IDE 1.6.8 2016/03/04 03:33 Windows 7 64 bit

https://github.com/arduino/Arduino/commit/576ac3ca30a3248cd4f42a55e747c5edb86a904e changed the version of the Arduino AVR Boards included with the hourly build to 1.6.10. Apparently if the version doesn't occur in the JSON file then the boards are not shown in Tools > Board.

**Comment by PaoloP74** [comment]
:+1:

**Comment by sandeepmistry** [comment]
AVR core 1.6.10 is released now (along with IDE 1.6.8). I am not seeing this issue with the latest hourly build on my Mac.
