### ISSUE TITLE
shiftIn misses input 8 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#467]
This is [Issue 467](http://code.google.com/p/arduino/issues/detail?id=467) moved from a Google Code project.
Added by 2011-01-25T01:55:53.000Z by [nic...@gmail.com](http://code.google.com/u/100134637457763543993/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

**What steps will reproduce the problem?**
1. Use the circuit on the shiftin tutorial page
2. Use the new shiftIn function included since 0021
3. Notice the lack of input of the 8th button

After switching the code from the previous shift in method to the newly included version I noticed that it wasn't picking up my 8th button.

I looked at the code in wiring_shift.c and noticed that it was pulling the clock high then low, whereas the previous function (used in the tutorial) pulled it low then high...

While I have yet to read the datasheet of various 4021's I can only assume there is an error in the code and not in the 4021...

If others operate inversely I would add a parameter to switch things around.

Patch attached.

**Comment by Chris--A** [comment]
Should be closed?

See: #1635, #1541

**Comment by cmaglie** [comment]
Yes, the workaround has been documented on the reference page.
