### ISSUE TITLE
Add Button to the Arduino library mananger

### ISSUE THREAD

**Issue by madleech** [arduino/Arduino#4677]
Hi there,

I've written a fairly simple, quite high level library for debouncing buttons. I think it is quite a bit simpler than the existing debouncing libraries in the Library Manager, and lets you write really quite simple code that does exactly what you think it should. I think it'll be a real bonus for people trying to Do Stuff who aren't too sure about how to handle debouncing and state tracking.

To quote my README.md:

> Sometimes you really wish you could ignore all the mechanics of debouncing, reading inputs, monitoring state, and just say... `if (button.pressed())` and know that it'll only run once each time you press a button.
> 
> Or how about `if (button.released())`, or `button.toggled()`. It is such a simple concept, but in practice you need to set up timers, monitor input puts, set pullups, etc etc. On anything more than the most simple example, that can become quite a headache.
> 
> So fed up with all that I figured there had to be a better way. This library is the result.

The repository is here: https://github.com/madleech/Button

It would be great if this could be added to the Library Manager.

**Comment by agdl** [comment]
Done thank you!
