### ISSUE TITLE
Core lib - Stream class: getTimeout property

### ISSUE THREAD

**Issue by mattb5906** [arduino/Arduino#4680]
Modify the Stream class to allow reading of the protected _timeout value.

`unsigned long getTimeout(void) { return _timeout; }`

[Arduino/hardware/arduino/avr/cores/arduino/Stream.h](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Stream.h)
[ Arduino/hardware/arduino/sam/cores/arduino/Stream.h](https://github.com/arduino/Arduino/blob/master/hardware/arduino/sam/cores/arduino/Stream.h)

**Comment by sandeepmistry** [comment]
Closed via #4718.
