### ISSUE TITLE
auto complete 

### ISSUE THREAD

**Issue by Alessandrofdp** [arduino/Arduino#4687]
olá gostaria que fosse adicionado na nova versão o recurso de auto complete ..

como si ve em ides profissionais como Atmel Studio e visual Studio  

hello like it to be added in the new version the auto complete feature ..

as you ve in professional ides as Atmel Studio and Visual Studio

**Comment by sandeepmistry** [comment]
Hi @Alessandrofdp, https://github.com/arduino/Arduino/issues/849 is already open to track this feature request.

I am closing this and marking it as a duplicate.
