### ISSUE TITLE
Ugly upscaled icon in Windows 7 and incorrect context menu [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#469]
This is [Issue 469](http://code.google.com/p/arduino/issues/detail?id=469) moved from a Google Code project.
Added by 2011-02-04T13:18:15.000Z by [erwinr...@gmail.com](http://code.google.com/u/115110071359087212016/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE, OpSys-Windows

### Original description

**What steps will reproduce the problem?**
1. Open Arduino IDE
2. Right click the taskbar icon for Arduino IDE

What is the expected output? 
A nice/not resized icon and a context menu referencing Arduino.exe or just showing "Close" as the unique available option

What do you see instead?
You see a fuzzy icon (for 0022 and a java icon for previous releases) and an incorrect context menu (it references to javaw.exe, so if you pin the exe to the Windows 7 taskbar you will get an invalid reference)
http://content.screencast.com/users/eried/folders/Jing/media/aa2a12cd-09ec-417d-a6c3-1a081747da22/2011-02-03_1525.png

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Any version (for wrong context menu and wrong java icon), but the 0022 shows a upscaled icon, not the javaw.exe one. Windows 7 x86 or x64

**Please provide any additional information below.**
I have made a temporal workaround: http://servicios.ried.cl/arduino/temp/windows7_arduino-0022_fix.rar

**Comment by ffissore** [comment]
Closing in favour of #3473 which, being more recent, has more chances to get traction and contributions
