### ISSUE TITLE
Arduino Projects Book

### ISSUE THREAD

**Issue by sith77** [arduino/Arduino#4698]
Page 64 Project 5 Mood Cue

The servo that comes with the kit has different wiring pin out than that of the projects learning look. The White control line and Red power line need to have the Ardiuno connections reversed from proper usage. 

Page 86 Project 8 Digital Hourglass 

The switch shown in the photo for parts needed is incorrect and shows an analog push button switch NOT a tilt switch.

**Comment by facchinm** [comment]
@00alis ,could you check that?

**Comment by 00alis** [comment]
Hi @sith77, thanks for your feedback. Could you tell us the version of your Starterkit? In the book please go to the orange page before the Index, please tell us what the last sentence says.

For the Project 8 Digital Hourglass, it has already been corrected in a later version, as you can see
![screenshot 2016-07-19 18 07 27](https://cloud.githubusercontent.com/assets/6151328/16957202/c03ad988-4ddb-11e6-9223-a7a4d76c02f3.png)

@agdl is going to doble check the servo wiring, do you have the white wire in the middle in your servo?

**Comment by agdl** [comment]
Wiring is correct. All ours servo have the white in the middle

**Comment by 00alis** [comment]
@agdl in the illustration the white wire is not in the middle, is the illustration correct or not?
![screenshot 2016-07-20 10 09 02](https://cloud.githubusercontent.com/assets/6151328/16979578/1de7feea-4e62-11e6-8311-56ab18fa7e14.png)

**Comment by 00alis** [comment]
We will update the illustration, thanks everybody!

**Comment by agdl** [comment]
In the illustration effectively seems that white is not in the middle. However the colors are right:
- GND is black
- +5V is red
- PWM input is white

**Comment by 00alis** [comment]
Illustration updated in the new edition
