### ISSUE TITLE
Arduino 101 Broken Drivers

### ISSUE THREAD

**Issue by bobdabiulder** [arduino/Arduino#4699]
On my Windows 10 OEM Asus machine with an AMD CPU, the board is not recognized correctly by Windows.  It shows the proper name, but I cannot upload/communicate with it.

**Comment by facchinm** [comment]
Hi @bobdabiulder ,
have you tried to follow the guides on the [forum](http://forum.arduino.cc/index.php?board=103.0)? 
I'm sorry but I have to close this as this repo only tracks IDE related issues (not board specific)
