### ISSUE TITLE
Blurry Serial Monitor icon when switching applications

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#4701]
Arduino IDE 1.6.9 2016/03/15 03:33 with Windows 7 64 bit
- Open Serial Monitor
- Press Alt+Tab
The Arduino IDE application icon is sharp but the Serial Monitor icon is blurry:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/13811851/9130c1ce-eb35-11e5-8822-4376e8d2695c.gif)

Using Arduino IDE 1.6.6 both icons are blurry:
![clipboard02](https://cloud.githubusercontent.com/assets/8572152/13812044/e326542a-eb36-11e5-8453-f87ed33624e8.gif)

I suspect that the fix for https://github.com/arduino/Arduino/issues/3473 was responsible for the IDE icon becoming sharp after 1.6.6 so maybe a similar fix could be applied to the serial monitor?

**Comment by facchinm** [comment]
Should be solved by https://github.com/facchinm/Arduino/commit/2c564e68b91b71871fb22e35278579eccb8f79dc (only tested on Linux, though).
Could you test the latest build produced by ArduinoBot in this page? https://github.com/arduino/Arduino/pull/4482

**Comment by per1234** [comment]
Looks good on Windows 7:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/14055482/a96a30ce-f29f-11e5-84df-0ee6c8763990.gif)
Thanks facchinm!
