### ISSUE TITLE
1.6.8 compiler doesn't ignore unchanged files

### ISSUE THREAD

**Issue by steronydh** [arduino/Arduino#4703]
I'm running 1.6.8 on 64-bit Windows 7. If I compile the code and upload it, then click on upload again, the code is recompiled instead of being reused as-is. The IDE used to ignore unchanged files. It's causing really slow development as I'm working on a large project for a Mega2560.

**Comment by sandeepmistry** [comment]
This is currently being tracked in https://github.com/arduino/arduino-builder/issues/127.

Closing this as a duplicate.
