### ISSUE TITLE
Please add MahonyAHRS library

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#4705]
https://github.com/PaulStoffregen/MahonyAHRS

**Comment by agdl** [comment]
@PaulStoffregen I added it, but please in next release put some example, in this way it is easier for user to have a starting point in using it!

**Comment by PaulStoffregen** [comment]
Will do.

**Comment by PaulStoffregen** [comment]
Should I also contribute the examples to arduino-libraries/MadgwickAHRS?  These 2 libs do the same thing, same API, with different algorithms.

I already sent one pull to improve that MadgwickAHRS's performance....
