### ISSUE TITLE
Please add AnalogMultiButton library

### ISSUE THREAD

**Issue by dxinteractive** [arduino/Arduino#4707]
I've made a library for easily reading presses from multiple buttons through a single analog input using a voltage ladder. It does debouncing, and provides a set of functions to detect when buttons are being held, pressed, released, pressed for a duration, released before or after a specific duration has elapsed, and also allows a button being held to repeatedly report a "press" on a timed interval for use with cursors or scrolling. Could I please get this added to the list of libraries? Hopefully it'll be nice and easy for most people to use given the examples:

[https://github.com/dxinteractive/AnalogMultiButton](https://github.com/dxinteractive/AnalogMultiButton)

Please let me know if you need anything fixed up first.

**Comment by agdl** [comment]
@dxinteractive your library cannot be added. library.properties is missing, tag and examples too. Please follow this guide
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

and take a look on how Arduino libraries are structired

https://github.com/arduino-libraries/RTCZero

**Comment by dxinteractive** [comment]
OK thanks, I looked around for a guide on how to structure it but didn't come up with anything, I'll resubmit once it's ready. Thanks again

**Comment by agdl** [comment]
I linked you a library to see how they are structured

**Comment by dxinteractive** [comment]
Hi agdl, I've followed the standards you've provided and think I have it ready. Changes have been pushed, could you please review?

**Comment by agdl** [comment]
Sorry about the delay. However it can't be added yet since a tag is missing

**Comment by dxinteractive** [comment]
Ok done, thanks

**Comment by agdl** [comment]
Done thank you!
