### ISSUE TITLE
Improve command line : add --help

### ISSUE THREAD

**Issue by itziksi** [arduino/Arduino#4709]
Improve command line user friendliness - 
I added "--help" action and when no valid action/option used, tell user he can use --help

Patch is attached.
This my first submit to this project, I hope I did it ok.

[patch.txt](https://github.com/arduino/Arduino/files/177853/patch.txt)

**Comment by CarlosMiguelCuevas** [comment]
I haven't check the patch, but I think you should make a Pull Request with the solution, that way your patch can be checked easier and merge quicker to the project. In the wiki you can find the way to download and build the project : https://github.com/arduino/Arduino/wiki/Building-Arduino.

**Comment by facchinm** [comment]
Closing this one and keeping track in PR#4765
