### ISSUE TITLE
Request to add Cytron ESPWiFi Shield Library to Arduino Library Manager

### ISSUE THREAD

**Issue by bengchet** [arduino/Arduino#4711]
Repo is here:
https://github.com/CytronTechnologies/CytronWiFiShield

Most recent tag is here:
https://github.com/CytronTechnologies/CytronWiFiShield/releases/tag/v1.0.0

Thank you!

**Comment by bengchet** [comment]
Hi,

May I know is this library already added to Arduino Library Manager? Thanks.

**Comment by agdl** [comment]
Sorry, I lost this issue. It is there now
