### ISSUE TITLE
Sketch always rebuilded

### ISSUE THREAD

**Issue by Testato** [arduino/Arduino#4713]
on IDE 1.6.8, win7_64, at every Verification in the consolle appear:

- Build options changed, rebuilding

This made the verification rpocess very slow

**Comment by Testato** [comment]
seems that the rpoblem is present only when switch from an architecture to another. Example if you try blink on AVR, it do not rebuild, but if you try Blink on ESP and after you return to AVR, it start to rebuild every verification, also if you remain always on AVR

**Comment by Testato** [comment]
Test the bug in this way:

- Open Arduino IDE, it will open on empty sketch whit setup() and loop()
- add a simply space in the loop function
- press Verify

the "Build options changed, rebuilding" will writed in the consolle and the verification process is slow.
If you try to verify a second time, the Build options changed, rebuilding always return

**Comment by PaoloP74** [comment]
:+1:

**Comment by facchinm** [comment]
should be solved by arduino/arduino-builder#129 , please test the nightly to check if the fix behaves correctly

**Comment by Testato** [comment]
it seems to work
