### ISSUE TITLE
NTP Client library for ESP8266 platform

### ISSUE THREAD

**Issue by gmag11** [arduino/Arduino#4719]
Hi,
I've developed a library to allow easy NTP sync on ESP8266 projects with Arduino environment. Next step is making it compatible with AVR Arduino based boards and ethernet module. Sorry I do not have a WiFi module for arduino so I cannot test this scenario.
You can download if from GitHub in https://github.com/gmag11/NtpClient.git
Please include include it in repository if you think it is useful.
Regards,
Germán

**Comment by agdl** [comment]
Done thank you!
