### ISSUE TITLE
Compilation error using "template <class T>" (prototypes generated incorrectly) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#472]
This is [Issue 472](http://code.google.com/p/arduino/issues/detail?id=472) moved from a Google Code project.
Added by 2011-02-06T15:31:57.000Z by [leomi...@gmail.com](http://code.google.com/u/111471411294508506079/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE, Component-PreProcessor

### Original description

I found an error using the last revision of Arduino IDE (0022).
This code doesn't compile correctly:

```c++
template <class T> int SRAM_writeAnything(int ee, const T& value)
{
    const byte* p = (const byte*)(const void*)&value;
    int i;
    for (i = 0; i < sizeof(value); i++)
	  EEPROM.write(ee++, *p++);
    return i;
}


template <class T> int SRAM_readAnything(int ee, T& value)
{
    byte* p = (byte*)(void*)&value;
    int i;
    for (i = 0; i < sizeof(value); i++)
	  *p++ = EEPROM.read(ee++);
    return i;
}
```

The IDE returns this error:
error: expected ',' or '...' before '&' token
error: ISO C++ forbids declaration of 'T' with no type
error: 'T' has not been declared

Using version 0021 it works fine.

**Comment by ffissore** [comment]
Please checkout this thread [1] on devs mailing list and try one of the linked IDEs. It should fix almost all the problems reported in this issue. Typedefs are still incorrectly handled so @nickgammon example still won't work
[1] https://groups.google.com/a/arduino.cc/forum/#!topic/developers/4X2T3rCxXWM

**Comment by ffissore** [comment]
With this latest build https://groups.google.com/a/arduino.cc/d/msg/developers/4X2T3rCxXWM/WbQ2_dGzuhsJ even typedefs will work fine

**Comment by ffissore** [comment]
Fixed by #3779

**Comment by danlsk** [comment]
I am using 1.6.8. I got this error: 'T' does not name a type.

**Comment by Chris--A** [comment]
@danlsk 
You'll have to provide the code you are using (a small complete example). Gammon's code does not cause errors in 1.6.12/13.

Compiles fine:
```C++
// generic minimum
template <typename T> T minimum (T a, T b) 
  {
  if (a < b)
    return a;
  return b;
  }  // end of minimum

void setup () 
  { 
  int foo = minimum (6, 7);
  }
void loop () { }
```

**Comment by danlsk** [comment]
`template <class T> 
T sum (T a, T b){
  T result;
  result = a + b;
  return result;
}

void setup() {
  Serial.begin(9600);
  int i=5, j=6, k;
  double f=2.0; g=0.5; h;
  
  k = sum<int>(i,j);
  h = sum<double>(f,g);  
  
  Serial.println (k);
  Serial.println (h);
  
}

void loop() {
  // put your main code here, to run repeatedly:

}`

**Comment by danlsk** [comment]
Alright, I just figured out that it cannot break into 2 lines and must be on a single line.
`template <class T> T sum (T a, T b)`

**Comment by Chris--A** [comment]
Yeah, the class function works on multiple lines as the IDE does not generate a prototype for it. Only file scoped functions are generated.

IMO the multi line error should be fixed as templates can become very involved and a single line detracts from readability dramatically. Especially now that C++11 has been enabled, templates are a staple diet of the language and are more prevalent that ever (standard template lib for one).

At least there is a workaround for now.

**Comment by facchinm** [comment]
This https://github.com/arduino/arduino-builder/pull/182 PR should solve the multiline problem once for all , but the code is horribly convoluted and needs a big cleanup before merging. Anyway, if you could test it and report any bug you may encounter, it would be great!

**Comment by Chris--A** [comment]
Will do, I can spend a little time trying to break it for you :)

**Comment by facchinm** [comment]
@Chris--A ,
I rebased and refactored the code, it should be much better now :smile: 
@ArduinoBot should produce a build really soon so I'd really like you (and anyone interested) to test it!

**Comment by Chris--A** [comment]
just got home from work, will give it a spin shortly.

**Comment by Chris--A** [comment]
Unfortunately there was no luck with the new code, test results here: https://github.com/arduino/arduino-builder/pull/182#issuecomment-264142984
