### ISSUE TITLE
ESP8266 Udp send waits for a receive before sending

### ISSUE THREAD

**Issue by jgrina** [arduino/Arduino#4720]
Why does udp sendPacket wait for a received packet before sending? It is only the first send command that waits. If I force a transmit from host, a burst of "sent" packets appears and everything works great from there. Sends and receives go. I'm using Arduino IDE version 1.6.8 on a Win 7 machine for this listing, but the same happened with version 1.6.5 on my Win 10 machine. The ESP is an Adafruit Huzzah breakout board, but I also tried the ESP feather 8266 and the NodeMCU boards with the same result

The arduino side file shows the ESP messages which have the sends, but no response until the host sends "!Start" message. The host side shows no messages until after the !Start message, then a burst of messages with responses to each message.

I'v tried several WiFi.modes, plus udp.flush(), udp.stop(), commands, but nothing changes.

[zipfiles.zip](https://github.com/arduino/Arduino/files/180973/zipfiles.zip)

**Comment by facchinm** [comment]
Hi @jgrina ,
I believe that your problem should be reported to ESP8266 devs https://github.com/esp8266/Arduino since it doesn't seem to be an IDE bug.
