### ISSUE TITLE
[Boards/Lib Manager] doesn't work on Ubuntu 15.10 

### ISSUE THREAD

**Issue by agdl** [arduino/Arduino#4727]
Every time I open the boards/lib manager on ubuntu 15.10 the IDE stops working and I must kill it

**Comment by cmaglie** [comment]
OpenJDK has an issue with the latest libatk and related java bindings:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798131
https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1510009

I guess you're trying to run the IDE from source? In the meantime please use the JVM from Oracle that works without problems.

**Comment by agdl** [comment]
Yes I compile it from source. Using nightly build it works

**Comment by sandeepmistry** [comment]
Closing, this was dev environment related.
