### ISSUE TITLE
Board manager won't work on my macbook pro, but it will work on iMac with the exact same operating system. I was trying to add ATtiny 44 to the hardware list. like I say, it worked on the iMac but refuses to work on the macbook pro.

### ISSUE THREAD

**Issue by Stevensea** [arduino/Arduino#4728]

**Comment by cmaglie** [comment]
Can you please add some more details?

- MacOSX version
- Arduino IDE version
- URL of the external core you're trying to install
- What do you mean with "won't work"? what do you expect and what is happening instead?
- There are some errors displayed that you can copy and paste here?

thanks.

**Comment by Stevensea** [comment]
I solved the problem:-) My initial download must have been corrupted somehow. It took me some time to workout how to fully uninstall it from my OS X system. But when I did that and reinstalled it, the problem was gone. 

Regards Steven.

**Comment by Breidenbach** [comment]
@Stevensea

Can you document the steps needed to uninstall completely?  I’d like to do that also, I am hopeful that it would solve my problems also.

Thank you,

Hal

**Comment by sandeepmistry** [comment]
Closing this for now, until we have steps to reproduce.
