### ISSUE TITLE
Adding library for Signals and Slots

### ISSUE THREAD

**Issue by tomstewart89** [arduino/Arduino#4732]
I've written a short library to implement Signals and Slots which works similar to Boost::Signals. It might be a little esoteric but I've found it to be handy for writing event-driven programs, so I'm hoping someone else might too.

I've been through the library manager faq so hopefully the file structure and the library.properties file are ok. You can find it all here:

https://github.com/tomstewart89/Callback

If there's anything that needs changing, let me know. Thanks!

**Comment by agdl** [comment]
Done thank you!
