### ISSUE TITLE
Request to add ArduMideaWrapper to Arduino Library Manager

### ISSUE THREAD

**Issue by AndressAndrade** [arduino/Arduino#4734]
URL Repo:
https://github.com/WiserUFBA/ArduMideaWrapper

ArduMideaWrapper is a library to control remotely Midea AC.

Thanks!

**Comment by agdl** [comment]
Hi, I'm sorry but your library can't be added since a tag is missing. Please follow this guide
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by AndressAndrade** [comment]
Done!

**Comment by agdl** [comment]
Done thank you!
