### ISSUE TITLE
have a link to install library on the IDE

### ISSUE THREAD

**Issue by lorenzoromagnoli** [arduino/Arduino#4736]
This is just a useful feature request!
When writing a tutorial is often required to have the user to install a specific library. 
It would be great if we could just embed a link in the tutorial that would automatically install the library in the user IDE.

Similarly to when you click on to a magnet link and it opens up transmission

**Comment by facchinm** [comment]
Something like this? 8326236426018c6082dbd72d696d5f17bbd9986f
@00alis

**Comment by 00alis** [comment]
top!

**Comment by facchinm** [comment]
Merged! :smile:
