### ISSUE TITLE
Console preference ignored [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#474]
This is [Issue 474](http://code.google.com/p/arduino/issues/detail?id=474) moved from a Google Code project.
Added by 2011-02-08T00:50:20.000Z by [CyberSta...@gmail.com](http://code.google.com/u/116460546586517435669/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Edit preferences.txt to show console.lines=0

**What is the expected output? What do you see instead?**
I expect to see no blank lines in the console before output, Verify adds a blank space regardless of preferences.txt, while Upload adheres to preferences.txt

What version of the Arduino software are you using? 22 On what operating
system? Win7 64  Which Arduino board are you using? Uno

**Please provide any additional information below.**
Upload will invoke Verify, so long as the code has changed.

**Comment by ffissore** [comment]
`console.lines` is used to size console, not to skip blank lines
