### ISSUE TITLE
1.6.8 won't install due to missing Java 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#4744]
It would be nice gesture to warn public that IDE 1.6.8 NEED Java version  upgrade which will not install in XP. ( Warned by Windows Installer )
Hence to upgrade Arduino IDE users have to upgrade Windows OS.

**Comment by facchinm** [comment]
Hi Vaclav, this is not true at all. 1.6.9 can be installed and used in XP without any issue (tested with a real old school XP pc :smile: ).
