### ISSUE TITLE
Blank in file name causes IDE exception [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#475]
This is [Issue 475](http://code.google.com/p/arduino/issues/detail?id=475) moved from a Google Code project.
Added by 2011-02-09T18:10:53.000Z by [cdrg...@gmail.com](http://code.google.com/u/107138719073423978030/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. A blank in the file name/folder name for a sketch results in
   an exception in the IDE.

Removing the blank(s) allows the sketch to load.

**What is the expected output? What do you see instead?**

Blanks should be allowed in file names.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

This happened on arduino_22 with an Arduino Uno connected.

**Comment by ffissore** [comment]
Fixed a long time ago. Invalid names are reported when the IDE starts up
