### ISSUE TITLE
Can't access buttons on Preferences window on screens with vertical resolution of 600 px

### ISSUE THREAD

**Issue by yvescordier** [arduino/Arduino#4753]
Arduino IDE 1.6.8
The preference window has no vertical scrollbar. So it is impossible to access the OK button on the bottom of the window on a PC (old recycle for courses) with lower resolution (1024x600 or 800x600).

Would it be possible to reorganize the items of this window to be able to access then on 10'' old notebook? There is this huge useless empty gap between the end of the last preference and the buttons. There is a lot of room unused between lines and another way could be to put the OK and Cancel buttons on the top of the box.
![preferences](https://cloud.githubusercontent.com/assets/18050289/14016794/b0e44142-f1c2-11e5-9f86-9f2c43158d91.jpg)

**Comment by lmihalkovic** [comment]
@yvescordier this was my own thinking on the preferences: #4421, #4417, [#4102/comment](https://github.com/arduino/Arduino/pull/4102#issuecomment-171289157): the single page has been split into more logical smaller pages accessible via the left hand-side list. I think the arduino team's original argument that 'users are so non-tech that they can't be overwhelmed with too many choices' has over the years turned into an efficient justification for doing the bare minimum, especially considering how the IDE (not the libraries) could be construed as having entered _de-facto sunset mode_.

**Comment by yvescordier** [comment]
Sorry but english is not my mother language. My problem is not to split the informations and checkboxes in two or three pages but the problem is to be able to access all informations of the preference window on a screen with low resolution (1024*600). On such screen, it is not possible to acces the OK button to validate the choices. It is why I propose to have a slimerst box of about 500 point heigh (this could be done by elimating usless zones).

regards
yves cordier

**Comment by lmihalkovic** [comment]
```
this could be done by elimating usless zones
```
... or by avoiding to cram together things that have nothing in common, but result in a window too big for everything to be visible on a smaller resolution monitor. But the arduino designers likely has a plan for what they want to do.
Cheers.

Reminds me of this architect friend who used to say nobody could pay him enough to make him design a toilet in the center of a living room, without a very serious reason...

**Comment by facchinm** [comment]
Fixed by #6459

**Comment by yvescordier** [comment]
sorry to have been late to try the modification but i Had'nt my computer avilable. 

due to function bar of  XP on the bottom of the screen, it sill be difficult to press the buttons

only 10 pixels of the button are visible

50 pixels less should be apeciate

is it possible to remove 2 or 3 trailing lines more at the bottom of the preference windows

 

Thank's for all

regards

yves cordier

 

 

 

> Message du 01/08/17 11:48
> De : "Martino Facchin" 
> A : "arduino/Arduino" 
> Copie à : "yvescordier" , "Mention" 
> Objet : Re: [arduino/Arduino] Can't access buttons on Preferences window on screens with vertical resolution of 600 px (#4753)
> 
>
> Closed #4753.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/arduino/Arduino","title":"arduino/Arduino","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/arduino/Arduino"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4753."}],"action":{"name":"View Issue","url":"https://github.com/arduino/Arduino/issues/4753#event-1187310480"}}}

**Comment by facchinm** [comment]
Due to the padding of all the other elements it's truly difficult to get back other 50 pixels (there is always the "dual tab" chance, as I mentioned in #6459).
The main problem I think it's gone is that it was simply impossible to press the buttons. Now it's difficult but feasible (temporarily hiding the taskbar should help in the "desperate" cases of 1024x576 screens).

**Comment by rin67630** [comment]
Temporarily hiding the taskbar does not help enought to get the button on screen.
It would have been so easy to put the 7 tick options side by side on two columns...

**Comment by cjdg** [comment]
Its happening again on 1.8.9
