### ISSUE TITLE
CurieIMU documentation syntax uses wrong case

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#4754]
The many CurieIMU documentation pages have Syntax sections with "CurieImu".  It should be "CurieIMU".

For example:

http://www.arduino.cc/en/Reference/CurieIMUgetAccelerometerRate

```
Syntax

CurieImu.getAccelerometerRate() 
```

**Comment by SimonePDA** [comment]
Ok,  noted.  Leftovers from the former version.  I'll fix the reference asap.

**Comment by SimonePDA** [comment]
All the occurrences have been fixed. Now the syntax is "CurieIMU.function()"

**Comment by per1234** [comment]
@SimonePDA @agdl  almost every reference page for the CurieIMU library still has this problem.
https://www.arduino.cc/en/Reference/CurieIMU

The only ones that **DON'T** have the problem are:
- https://www.arduino.cc/en/Reference/CurieIMUdetachInterrupt
- https://www.arduino.cc/en/Reference/CurieIMUattachInterrupt
- https://www.arduino.cc/en/Reference/CurieIMUshockDetected
- https://www.arduino.cc/en/Reference/CurieIMUreadTemperature

Also, two of the links at https://www.arduino.cc/en/Reference/CurieIMU have typos:

https://www.arduino.cc/en/Reference/CurieIMUsgetDetectionThreshold
should be changed to:
https://www.arduino.cc/en/Reference/CurieIMUgetDetectionThreshold

https://www.arduino.cc/en/Reference/CurieIMUsgetStepDetectionMode
should be changed to:
https://www.arduino.cc/en/Reference/CurieIMUgetStepDetectionMode

**Comment by akash73** [comment]
fixed thanks

**Comment by per1234** [comment]
Thanks @akash73! There are still three pages with the "CurieImu" problem:

- https://www.arduino.cc/en/Reference/CurieIMUnoGyroOffset
- https://www.arduino.cc/en/Reference/CurieIMUgetGyroOffset
- https://www.arduino.cc/en/Tutorial/Genuino101CurieIMUOrientationVisualiser

**Comment by SimonePDA** [comment]
Two pages weren't pushed properly, done. THe tutorial had an occurrence of CurieImu in Hardwared Required and was fixed as well.

**Comment by SimonePDA** [comment]
I keep pushing, but it doesn't update. Investigating

**Comment by SimonePDA** [comment]
After three attempts each, the pages finally got updated
