### ISSUE TITLE
[Library Manager] Please add keyboardButton library

### ISSUE THREAD

**Issue by klenov** [arduino/Arduino#4767]
Please, add keyboardButton library to the library manager.
https://github.com/klenov/keyboardButton

**Comment by agdl** [comment]
I'm sorry but your library cannot be added since it has a wrong structure. Please see how an Arduino library is structured
https://github.com/arduino-libraries/RTCZero

**Comment by klenov** [comment]
I think I've fixed it

**Comment by agdl** [comment]
Done thank you!
