### ISSUE TITLE
[LibraryManager] Please add Wiegand library

### ISSUE THREAD

**Issue by paulo-raca** [arduino/Arduino#4771]
https://github.com/paulo-raca/YetAnotherArduinoWiegandLibrary

**Comment by paulo-raca** [comment]
Thanks!

**Comment by agdl** [comment]
I'm sorry but your library cannot be added since a tag is missing. Please follow this guide 
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by paulo-raca** [comment]
I'm sorry, I forgot that step.
It's tagged now.

Thanks!

**Comment by agdl** [comment]
Done thank you!
