### ISSUE TITLE
when I am using the compile guide, there are some errors as follows.

### ISSUE THREAD

**Issue by oneway3124** [arduino/Arduino#4772]
The guide is from the site :https://github.com/arduino/Arduino/wiki/Building-Arduino
The erros is as below:
![image](https://cloud.githubusercontent.com/assets/3787176/14078904/23aeb970-f52c-11e5-8130-ebad70f579b6.png)
The linux environment is ubuntu 
![image](https://cloud.githubusercontent.com/assets/3787176/14078951/783fc0c4-f52c-11e5-88cd-e5c9100e1cdf.png)

![Uploading image.png…]()

**Comment by cmaglie** [comment]
The `JAVA_HOME` environment variable should point to a JDK but it seems that you set it to a JRE.

**Comment by oneway3124** [comment]
![image](https://cloud.githubusercontent.com/assets/3787176/14145877/1523a3b4-f6c8-11e5-804a-5556b4fb7325.png)
can you tell me which linux version did you use? I am using ubuntu 14

**Comment by cousteaulecommandant** [comment]
openjdk-8 is not available in the Ubuntu 14.04 ("LTS") repositories, only in 14.10 or newer (this has always been an issue in Ubuntu apparently).  You will need to install it separately, for example adding a PPA.  http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/ contains instructions on how to do this.
