### ISSUE TITLE
[LibraryManager] Mispelled category Communiction

### ISSUE THREAD

**Issue by rlogiacco** [arduino/Arduino#4776]
There is a typo for library `Lewis` which is published under a mispelled category `Communiction`.

Please fix and merge into category `Communication`.

**Comment by per1234** [comment]
I have submitted a pull request to fix this issue: https://github.com/DefProc/lewis/pull/1

**Comment by DefProc** [comment]
I've pulled that, and bumped the version number, so 0.1.1 should quiet that message

**Comment by rlogiacco** [comment]
So that makes my suggestion for a different elaboration of the aggregated JSON even more relevant... at least in my mind :smile:

**Comment by cmaglie** [comment]
In this particular case removing the 0.1.0 would solve this issue, but let's follow #4802 for a final solution.
