### ISSUE TITLE
JGit library

### ISSUE THREAD

**Issue by CarlosMiguelCuevas** [arduino/Arduino#4782]
I'm trying to use JGit API to provide the Arduino IDE with Git functions, in order to help with the issue #4387. Could someone add this repo https://github.com/eclipse/jgit to the Library Manager ? 
I also downloaded the Raw API library, but I couldn't make it run, I don't know where to put it, maybe someone knows better where to put the .jar file.

**Comment by agdl** [comment]
Hi, I'm sorry but this library can't be added to the library manager. It is intended to collect Arduino libraries. This means that only libraries that extend the Arduino boards basic functionalities providing examples are included in the library manager.
