### ISSUE TITLE
[LibraryManager] Please add Yet Another PcInt library

### ISSUE THREAD

**Issue by paulo-raca** [arduino/Arduino#4783]
https://github.com/paulo-raca/YetAnotherArduinoPcIntLibrary

Thanks

**Comment by agdl** [comment]
Done thank you!

**Comment by NicoHood** [comment]
"Doesn't support user data on or pin state on callbacks"

I think there is an "on" too much.

I am not sure what this feature that is missing should be, but you might want something like this?
https://github.com/NicoHood/PinChangeInterrupt#get-trigger-on-mode-change

You made a very great comparison though. I know my code is messy, but I've no idea how to optimize it like this (low and high level API) with less definitions.

**Comment by paulo-raca** [comment]
Yes, that is the feature I meant. I've already fixed the comparisson table.

Your code is "messy" because you've made different trade-offs:
- Your code is very efficient and configurable, but it  comes with extra complexity.
- Mine is simpler, but wastes more RAM and CPU cycles with pins that are not used

Thanks for taking a look :D

**Comment by NicoHood** [comment]
Sure. Thats all great. Good to see some variations :)
