### ISSUE TITLE
Request to add ESP8266 Microgear Library to Arduino Library Manager

### ISSUE THREAD

**Issue by chavee** [arduino/Arduino#4786]
Repo is here:
https://github.com/netpieio/microgear-esp8266-arduino

Most recent tag is here:
https://github.com/netpieio/microgear-esp8266-arduino/releases/tag/v1.1.2

Thank you!

**Comment by agdl** [comment]
I'm sorry but your library cannot be added since the library.properties is missing. If you can please also use the 1.5 library format is good.

**Comment by chavee** [comment]
Sorry about that. I've added the file already. 

Repo is here:
https://github.com/netpieio/microgear-esp8266-arduino

Most recent tag is here:
https://github.com/netpieio/microgear-esp8266-arduino/releases/tag/v1.1.3

**Comment by agdl** [comment]
Done thank you!
