### ISSUE TITLE
Arduino ZERO schematic error.  Page 3 has R303 missing and 2 R302's

### ISSUE THREAD

**Issue by ram713** [arduino/Arduino#4788]
Arduino ZERO schematic, page 3 states in upper right corner: Mounting R303 permanently enables the power.  One can review the LED/RESISTOR combinations below the statement.  There are 2, R302's and no R303.

**Comment by agdl** [comment]
R303 is there on the right of Q300T2 and on the left of Q300T1 with value DNP
