### ISSUE TITLE
Arduino IDE build.xml needs a debug target [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#479]
This is [Issue 479](http://code.google.com/p/arduino/issues/detail?id=479) moved from a Google Code project.
Added by 2011-02-15T03:55:01.000Z by [rick.rickanderson](http://code.google.com/u/rick.rickanderson/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
build.xml could use a debug target that is similar to the "run" target but does two things:
1. Console is still open when the software is running, so that system.out.println statements are visible.
2. If logging is available then enable the logging feature in debugging mode.

**Why?**
Convenient feedback for debugging.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
This would cause no incompatibilities.

**Comment by ffissore** [comment]
Fixed a long time ago
