### ISSUE TITLE
[Library Manager] Please add this library.

### ISSUE THREAD

**Issue by NAzT** [arduino/Arduino#4799]
http://github.com/cmmakerclub/CMMCEasy

thanks!

**Comment by per1234** [comment]
April fools joke? Then not a very funny one.

**Comment by NAzT** [comment]
@per1234  Oh sorry, some commits are missing!

I've pushed them up. and here's the build status:

[![Build Status](https://travis-ci.org/cmmakerclub/CMMCEasy.svg?branch=master)](https://travis-ci.org/cmmakerclub/CMMCEasy)

Thank you!

**Comment by per1234** [comment]
Ok, sorry, I thought you got me there(April 1st is a traditional day for pranks). I noticed there was no category specified in library.properties so started to submit a pull request to add one but kept running into more and more bugs, then I realized the date of the issue report!

**Comment by agdl** [comment]
@NAzT Your tag says 0.0.0 but library.properties says 0.0.1 fix this please

**Comment by NAzT** [comment]
@agdl  done Thanks! <3

**Comment by agdl** [comment]
Done thank you!
