### ISSUE TITLE
Inconsistent documentation on ArduinoBoard101

### ISSUE THREAD

**Issue by foxtrotfire** [arduino/Arduino#4803]
Under 'Technical specs':
"DC Current per I/O Pin	20 mA"

Under 'Input and Output':
"Each pin can source or sink a maximum of 4 mA."

Which one is correct?

Also under 'Input and Output': 
"Analog Inputs. Six of the 20 general purpose I/O pins on the Zero provide analog input." 

Should be:
"Analog Inputs. Six of the 20 general purpose I/O pins on the 101 provide analog input."

**Comment by agdl** [comment]
@foxtrotfire thank you for pinting this out. The correct one is 4 mA. Updated thank you!
