### ISSUE TITLE
Arduino Mega maximum voltage is 16V, not 20V

### ISSUE THREAD

**Issue by JohnETanner** [arduino/Arduino#4806]
According to this schematic (https://www.arduino.cc/en/uploads/Main/arduino-mega2560-schematic.pdf) the Mega board uses a pair of voltage regulators in parallel, both MC33269xx, which are specified to withstand 20V input voltage. I bought some Arduino Mega boards from Amazon that were claimed to be genuine, and when they blow out, I found that the manufacturer substituted a AMS1117 regulator that is has a maximum input rating of 15V. I propose that someone update the schematic and especially change the Mega board maximum input voltage spec here (https://www.arduino.cc/en/Main/ArduinoBoardMega2560) to be 15V instead of 20V.

**Comment by agdl** [comment]
Hi, Github is intended to track software related issues (Arduino IDE) so I'm closing this.

However please send an email to support@arduino.cc with front and back picture of the board and the receipt. 

Thank you for collaborating
