### ISSUE TITLE
liquidcrystal createchar after setCursor issue

### ISSUE THREAD

**Issue by tablatronix** [arduino/Arduino#4809]
createChar does not work after calling setCursor
at least for me, was driving me nuts until I made sure to always do it before moving the cursor.

```
  // would not print my character
  lcd.setCursor(numCols-1, 0);
  lcd.createChar(1,custombyte);
  lcd.write((char)1);
```

**Comment by agdl** [comment]
Hi, I think you should move this issue here
https://github.com/arduino-libraries/LiquidCrystal/issues

I'm closing this and openig a new one there
