### ISSUE TITLE
Dead Link on Arduino Playground Website

### ISSUE THREAD

**Issue by ChaitanyaBaweja** [arduino/Arduino#4823]
http://playground.arduino.cc/Code/SLCD
Unable to access the SCLd library..
Error displayed : Http/1.1 Service Unavailable

**Comment by per1234** [comment]
The Arduino Playground content is the responsibility of the community, not the Arduino developers. It looks like you have made a post on the Arduino Forum regarding this issue: http://forum.arduino.cc/index.php?topic=391663. Since it is off topic here I think it would be best if you close this issue and we will continue discussion of how to fix this on the forum.

**Comment by ChaitanyaBaweja** [comment]
Ohh. Actually it wasn't me who started that thread in the forum and I
understand your point regarding the off topic issue.. Sorry I thought all
bugs should be reported there, but yes I will surely delete the thread..
On Apr 6, 2016 3:55 AM, "per1234" <notifications@github.com> wrote:

The Arduino Playground content is the responsibility of the community, not
the Arduino developers. It looks like you have made a post on the Arduino
Forum regarding this issue: http://forum.arduino.cc/index.php?topic=391663.
Since it is off topic here I think it would be best if you close this issue
and we will continue discussion of how to fix this on the forum.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/arduino/Arduino/issues/4823#issuecomment-206009560>

**Comment by per1234** [comment]
>Actually it wasn't me who started that thread in the forum

That's funny, I just assumed it to be you. I guess there is some interest in this library. I'd appreciate your input on the solutions I have proposed in my comment on the forum thread: http://forum.arduino.cc/index.php?topic=391663.msg2697798#msg2697798  I have posted a link to where you can find the SLCD library in that comment. Per

**Comment by facchinm** [comment]
Moving the conversation to the forum, thakns :wink:
