### ISSUE TITLE
Compilation feedback directs to the end of fileset disregarding actual error location.

### ISSUE THREAD

**Issue by Alignak** [arduino/Arduino#4827]
OS: Linux Ubuntu 15.10
IDE: Arduino 1.6.8
Compiling for Mega 3560

**Comment by facchinm** [comment]
If I understand correctly the issue, this should be solved in nightly (next 1.6.9). Please test it and, if not working, expand the bugreport.

**Comment by sandeepmistry** [comment]
I'm closing this due to lack of feedback, IDE 1.6.9. has been released please try it out and let us know if you are still experiencing this issue and provide more details.
