### ISSUE TITLE
Link not available 

### ISSUE THREAD

**Issue by MrwanBaghdad** [arduino/Arduino#4836]
Highlighted link isn't available 
webpage: http://playground.arduino.cc/Learning/AtmegaStandalone 
![image](https://cloud.githubusercontent.com/assets/13662516/14383182/abba7e8e-fd93-11e5-9709-ca7d7ef837ca.png)

**Comment by MrwanBaghdad** [comment]
It seems that all links associated with https://itp.nyu.edu/ aren't working

**Comment by facchinm** [comment]
Playgroud is completely editable by registered users, probably https://itp.nyu.edu/ changed some redirect, but if you are able to recover the broken links you can fix it by yourself (and receive a very big thank, btw :wink: )

**Comment by MrwanBaghdad** [comment]
Cool Thanks :smile:
