### ISSUE TITLE
1.6.8 IIC 1602 error can display all codes

### ISSUE THREAD

**Issue by wwwusr** [arduino/Arduino#4838]
hello guys,
Sth wrong with me,need help!
Use Arduino 1.6.8 in win7 64,when I run the code from Lib LiquidCrystal_I2C-HelloWorld,I can only get a "H" at the first of the 1602,lose other words.
But when run the code in Arduino 1.0.5 in win7 64,I can get the right result.......
I feel confuse about that .

**Comment by wwwusr** [comment]
Version 1.5.8 is OK,tested

**Comment by facchinm** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/4302, simply update the LiquidCrystal_I2C library and it should work correctly again!

**Comment by wwwusr** [comment]
Thanks!I'll try like that
