### ISSUE TITLE
Arduino 1.6.8 always reset boards

### ISSUE THREAD

**Issue by wwwusr** [arduino/Arduino#4839]
Hello guys,
Use Arduino1.6.8 in Win7 64,I plug 4 Arduino boards:2 Pro mini(through PL2303),1 Nano,1 Uno(all uses  CH340G),when I open the 1.6.8 IDE,all board's 13 LED will flash,means that the boards are all reset time an time again,and sometimes can upload codes,but sometimes can't do that.
And,1.0.5 IDE version is OK, after run 1.0.5,all boards  run stable,even run some codes throuth serial port.

**Comment by wwwusr** [comment]
Version 1.5.8 is OK,tested

**Comment by PaulStoffregen** [comment]
Any chance you could test with a genuine Arduino Uno, which uses the 16u2 chip (not ch340).

**Comment by facchinm** [comment]
Closed by merging https://github.com/arduino/Arduino/pull/4792, try the latest nightly build and the problem should disappear

**Comment by wwwusr** [comment]
Thanks!I'll try like that
