### ISSUE TITLE
[Library Manager] Please add 6-digit-7-Segment-Arduino

### ISSUE THREAD

**Issue by SohnyBohny** [arduino/Arduino#4841]
Repo is here:
https://github.com/SohnyBohny/6-digit-7-Segment-Arduino

Most recent tag is here:
https://github.com/SohnyBohny/6-digit-7-Segment-Arduino/releases/tag/v1.0

Thank you!

**Comment by agdl** [comment]
Done thank you!

**Comment by SohnyBohny** [comment]
Installing throws an error 

The library "6-digit-7-Segment" cannot be used.
Library names must contain only basic letters and numbers

I've renamed to "six-digit-seven-segment" in my library.properties

**Comment by SohnyBohny** [comment]
@agdl please help! - what should I do?

**Comment by agdl** [comment]
@SohnyBohny you have to tag the library again. Make a new release!

**Comment by SohnyBohny** [comment]
done - thank you!

**Comment by SohnyBohny** [comment]
done - thank you @agdl for your great help!

**Comment by agdl** [comment]
You are welcome. In within one hour you should see it in the library manager

**Comment by SohnyBohny** [comment]
@agdl would the old one be deleted if I point it as a Pre-release?

**Comment by agdl** [comment]
No you have to manually remove the tag from git and then the library manager will remove it as well!

**Comment by SohnyBohny** [comment]
Ok - and what's about the colors

**Comment by agdl** [comment]
What do you mean with the colors?

**Comment by SohnyBohny** [comment]
I've added a `keywords.txt` file for highlighted in 

>  see:
[If you tried the new sketch, you probably noticed that nothing from our library was recognized by the environment and highlighted in color. Unfortunately, the Arduino software can't automatically figure out what you've define in your library (though it would be a nice feature to have), so you have to give it a little help. To do this, create a file called keywords.txt in the Morse directory. It should look like this:](https://www.arduino.cc/en/Hacking/LibraryTutorial)

What did I wrong?

**Comment by agdl** [comment]
Try putting one tab \t between the word you want to highlight and the KEYWORDx keyword
