### ISSUE TITLE
on OSX el capitan arduino ide doesn't recognize usb ports

### ISSUE THREAD

**Issue by wtheesfeld** [arduino/Arduino#4842]
On el capitan, arduino IDE does not "see" any usb ports, only /dev/cu not /dev/tty
tried with 1.6.8 and the latest hourly build

cannot program any boards :(

**Comment by PaulStoffregen** [comment]
/dev/cu and /dev/tty are the same, as far as Arduino is concerned.

**Comment by facchinm** [comment]
Indeed, cu and tty are the "same" thing, the problem seems to be El Capitan. Closing as duplicate of https://github.com/arduino/Arduino/issues/3928 (the issue is closed but we are keeping all the conversation/workarounds there )
