### ISSUE TITLE
Library manager scraper did not include the latest tag of our library

### ISSUE THREAD

**Issue by iSsO** [arduino/Arduino#4846]
It has been more than 14 hours since we tagged the latest version of our library and it hasn't been included in the library manager yet.

![Still the old version](https://cloud.githubusercontent.com/assets/4904293/14421036/a5604530-ffcf-11e5-961c-983dfaa1d03f.png)

Here is the link of the tag: https://github.com/Integreight/1Sheeld-Arduino-Library/releases/tag/v1.9.0

It is mentioned in the [FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) that new tags should be available within 1 hour. Should I be worried?

Is there a way we can track the status of the library manager scraper? (i.e. a [status page](http://statuspage.io) for instance)

**Comment by facchinm** [comment]
Hi @iSsO , we are experiencing some problems on our Jenkins machine, the libraries will be updated as soon as possible

**Comment by iSsO** [comment]
@facchinm Thanks, it has been updated.

I suggest you add a status page as I mentioned to avoid this kind of posts. :)
