### ISSUE TITLE
Arduino Nano Incorrect wiring of FT232RL

### ISSUE THREAD

**Issue by torepaulsson** [arduino/Arduino#4848]
In the schematic the Test pin of FT232RL is left floating, should be connected to ground.
https://www.arduino.cc/en/uploads/Main/ArduinoNano30Schematic.pdf

http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf page 8

BR
Tore

**Comment by agdl** [comment]
@torepaulsson thank you for pointing out this. However we don't produce it any more, but it is there as legacy so I'm closing this. Thank you!
