### ISSUE TITLE
Arduino fastIO.h library missed

### ISSUE THREAD

**Issue by aaassasdf** [arduino/Arduino#4849]
I just updated the Arduino software and I found that the fastIO.h missed.

Before that, it was wire.h library...

I just want a COMPLETE library set.

btw, my Arduino's current version is 1.6.8

**Comment by aaassasdf** [comment]
Please anyone can help?

**Comment by facchinm** [comment]
If you could paste here the sketch (or an excerpt triggering the issue) plus the verbose output and your configuration (IDE version, operating system) maybe someone can understand the problem :smile:

**Comment by sandeepmistry** [comment]
I'm closing this due to lack of feedback, please re-open with the requested information.
