### ISSUE TITLE
Request do add KONNEKTING library to lib-manager

### ISSUE THREAD

**Issue by tuxedo0801** [arduino/Arduino#4852]
This library enables you to create an arduino/esp8266 powered KNX device

Repo: https://github.com/KONNEKTING/KonnektingDeviceLibrary
Latest tag: https://github.com/KONNEKTING/KonnektingDeviceLibrary/releases/tag/1.0.0-BETA3

Thanks for adding.

**Comment by agdl** [comment]
Done thank you!
