### ISSUE TITLE
Library conflict-GSM-Keypad, still needs to be fixed!

### ISSUE THREAD

**Issue by DouglasBair** [arduino/Arduino#4858]
Take a blank Arduino sketch, include <GSM.h> and <Keypad.h>. try to compile.  I receive this error:
"C:\Program Files (x86)\Arduino\libraries\GSM\src/GSM3MobileAccessProvider.h:37:36: note: previous declaration 'GSM3_NetworkStatus_t IDLE'
 enum GSM3_NetworkStatus_t { ERROR, IDLE, CONNECTING, GSM_READY, GPRS_READY, TRANSPARENT_CONNECTED, OFF};"

Researching this, I see many years of users asking that this be fixed, and not expecting to be told 
fix it yourself by editing a library.  What then for the next release, fix it again? 
I've already check the forum and the issues.  Many 'smart alecs' say its fixed, where?
This happens in v1.6.5, 1.6.6, and in (.org's) 1.7.9.

When will Arduino.cc fix this?  
And, yes, I'm a newbie. So if I'm expecting too much or have entered the lib names incorrectly,
let me know.
Doug

**Comment by Chris--A** [comment]
I have written a solution to the problem here (not Arduino specific): https://github.com/Chris--A/Keypad/issues/4#issuecomment-213909336

I will update the Arduino.cc playground with a link to the repo wiki documentation for others (once I have created it).

This issue can be closed.

**Comment by DouglasBair** [comment]
Thank you.
Doug

  _____

**Comment by agdl** [comment]
@Chris--A I'm closing this. Thank you

**Comment by DouglasBair** [comment]
How has this been fixed?
 
Is there a new GSM library that doesn't conflict with the Arduino Keypad
lib?
 
Douglas Bair
 
  _____
