### ISSUE TITLE
Ability to pause the serial plotter?

### ISSUE THREAD

**Issue by damellis** [arduino/Arduino#4860]
It might be nice to be able to pause the serial plotter to inspect the graphs in more detail. Especially nice could be a combination of this and #4859 that would allow you to mouse over (or click) at various points in the paused plot to see the numeric values of each data series at that point in time.

**Comment by mobluse** [comment]
Workaround: One way to pause it is to change the baudrate because then it can't communicate. If e.g. 115200 baud is normally selected you can pause by pressing arrow up, and play with arrow down.

**Comment by per1234** [comment]
Implemented in the Arduino IDE 2.x Serial Plotter (**STOP**/**RUN** button).
