### ISSUE TITLE
[Library Manager] Please add PM2005Lib libary

### ISSUE THREAD

**Issue by jwagnerhki** [arduino/Arduino#4866]
Please add PM2005Lib to the library manager:
https://github.com/jwagnerhki/arduino_pm2005lib

Thank you!

**Comment by per1234** [comment]
The `version` value in your library.properties is [1.0.0](https://github.com/jwagnerhki/arduino_pm2005lib/blob/1.0.1/library.properties#L2) but the release/tag is [1.0.1](https://github.com/jwagnerhki/arduino_pm2005lib/releases/tag/1.0.1), they should match.

**Comment by jwagnerhki** [comment]
Thanks, didn't realize the mistake. Renaming tags seems quite involved. Now I simply updated library.properties to 1.0.2 and made release/tag 1.0.2. Could you add it? Thanks!

**Comment by agdl** [comment]
Done thank you!
