### ISSUE TITLE
4 legs rgb led library for arduino

### ISSUE THREAD

**Issue by arsalmaner** [arduino/Arduino#4869]
This library works for rgb led with 4 legs. You can manage colour rgb codes and work duration of the led light. 

[https://github.com/arsalmaner/Arduino-Libraries/tree/master/RGB_LED](https://github.com/arsalmaner/Arduino-Libraries/tree/master/RGB_LED)

**Comment by agdl** [comment]
Hi, your library cannot be added since a library.properties is missing. Please see how arduino library are structured and  follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by arsalmaner** [comment]
Thanks, I updated it with this guide. Can you check it out again?

**Comment by agdl** [comment]
A tag is still missing

**Comment by arsalmaner** [comment]
Sorry I am new. Is it ok now @agdl  ?

**Comment by agdl** [comment]
Done thank you!

**Comment by per1234** [comment]
@arsalmaner your library was never added to Library Manager. The issue is the folder structure of your repository. From https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ:
>Your repo is ok if its root folder contains file library.properties and the rest of the library source code. If your library is stored into a subfolder, your repo it's not ok and we can't include your library in the list.

So you need to have a repository specifically for the library, rather than having the RGB_LED library be a subfolder of the Arduino-Libraries repository as it is currently.

**Comment by arsalmaner** [comment]
I got it. Thanks @per1234 . I arranged it again. What should I do to request to add this now ?

**Comment by agdl** [comment]
Argh.. @arsalmaner delete old tag and push it again. It will be added automatically!

**Comment by arsalmaner** [comment]
ok @agdl I did it.

**Comment by agdl** [comment]
Ok due to the way the manager works you will see changes on monday
