### ISSUE TITLE
Library suggestion: BTLE

### ISSUE THREAD

**Issue by floe** [arduino/Arduino#4885]
Available at https://github.com/floe/BTLE, just created a suitable release, all other preconditions should be met. Library is for supporting a subset of Bluetooth Low Energy with the super-cheap nRF24L01+ radio modules.

**Comment by per1234** [comment]
Your release is [0.1](https://github.com/floe/BTLE/releases/tag/v0.1) but your version value in library.properties is [1.0](https://github.com/floe/BTLE/blob/v0.1/library.properties#L2). They should match.

**Comment by floe** [comment]
Oops, sorry, my bad. Fixed in https://github.com/floe/BTLE/releases/tag/v0.1.1 and https://github.com/floe/BTLE/blob/v0.1.1/library.properties

**Comment by agdl** [comment]
Done thank you!
