### ISSUE TITLE
much faster Print.cpp on ethernet

### ISSUE THREAD

**Issue by pidloop** [arduino/Arduino#4899]
Hello. I greatly improved the speed of my W5100 ethernet shield by adding some buffering to the method in Print.cpp for FLASH memory strings. This wiki won't let me attach it here but you can get it from my web site at http://www.clearskyinstitute.com/ham/AST or contact me at ecdowney at clearskyinstitute.com. Cheers.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#30
