### ISSUE TITLE
Problem with code to Arduino

### ISSUE THREAD

**Issue by Blob157** [arduino/Arduino#4915]
whenever i start my arduino and start the arduino software it starts doing "Blink" endlessly, even if i change the code it still just does blink with pin 13 and the rest doesnt do anything.

i have an arduino uno.

**Comment by facchinm** [comment]
Hi,
it looks like a problem with you board/setup, did you try asking the [forum](http://forum.arduino.cc) or the [support](mailto:support@arduino.cc)? This repo is for IDE related bugs so I'm closing the issue, sorry.
