### ISSUE TITLE
EMoRo 2560 Librbary

### ISSUE THREAD

**Issue by inovatic-ict** [arduino/Arduino#4920]
Hello,

company Inovatic ICT is Arduino's partner and we would like that user can download libraries for EMoRo 2560 via Arduino Manager.

Link to json: 

https://raw.githubusercontent.com/inovatic-ict/inovatic-repoz/master/package_Inovatic-EMoRo_index.json

Thanks!

Dino

**Comment by agdl** [comment]
Done thank you!

P.S next time link to the repo please :)

**Comment by inovatic-ict** [comment]
OK! Thanks!

When will these libraries be able to download via Library Manager?

**Comment by agdl** [comment]
It should be already available. After the adding in about one hour it should be there

**Comment by inovatic-ict** [comment]
So why I can't see it?

Sketch->Include Library-> Manage Libraries -> typing Emoro and nothing shows up.

And is it possible to download our Emoro2560 Bord files via the Bord Manager without using the json file, ? We want that our users do not need to put json URL in the „Preferences“, than just types „Emoro2560“ in the „Bord Manager“ and install Board files and libreries.

Json URL: https://raw.githubusercontent.com/inovatic-ict/inovatic-repoz/master/package_Inovatic-EMoRo_index.json

Thank you!
