### ISSUE TITLE
Unable to auto-prototype multiline defined functions

### ISSUE THREAD

**Issue by TheFax** [arduino/Arduino#4921]
From IDE 1.6.7 I had problems to compile programs containing functions with multi-line definition.

For example, this program is compiled successfully:
```
void setup() {}

void loop() {
  int z = sum(1, 2, 3);
}

int sum (int x, int y, int z) {
  return (x+y+z);
}
```

...and this one return an error:
```
void setup() {}

void loop() {
  int z = sum(1, 2, 3);
}

int sum (int x,
         int y,
         int z   ) {
  return (x+y+z);
}
```

I think it is a problem in auto-prototyping because if I move the function above the loop(), the software is compiled successfully

This issue for me start from version 1.6.7 and is also present in version 1.6.8.
I'm pretty shure that version 1.6.6 has not this problem.

**Comment by facchinm** [comment]
The issue was solved in arduino-builder just after 1.6.8 release so it is fixed in nighlty (and will be in 1.6.9)
