### ISSUE TITLE
.hex export option [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#493]
This is [Issue 493](http://code.google.com/p/arduino/issues/detail?id=493) moved from a Google Code project.
Added by 2011-03-04T16:05:22.000Z by [skywodd](http://code.google.com/u/skywodd/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-Post-1.0

### Original description

**What change would like to see?**
The possibility to export compiled .hex from temp directory directly from gui.

**Why?**
For programming no bootloaded chip or put into an emulator.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

**Comment by facchinm** [comment]
Fixed by 78936541
