### ISSUE TITLE
New Library - DueFlashStorage by Sebnil

### ISSUE THREAD

**Issue by rmcolbert** [arduino/Arduino#4930]
Please add https://github.com/sebnil/DueFlashStorage

**Comment by agdl** [comment]
Hi, I'm sorry but your library can't be added please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

In particular a tag is missing

**Comment by rmcolbert** [comment]
Repository tagged w/ v1.0 release.

**Comment by Chris--A** [comment]
@rmcolbert 

Is `FLASH_DEBUG` meant to be enabled by default?
Might cause problems if Serial isn't used (once buffer is filled)..

**Comment by agdl** [comment]
Done thank you!

**Comment by PnsUfuk** [comment]
ananın amına korum gavur it


2016-05-26 12:53 GMT+03:00 Arturo Guadalupi <notifications@github.com>:
