### ISSUE TITLE
New Library - ESP8266RestClient by fabianofranca

### ISSUE THREAD

**Issue by fabianofranca** [arduino/Arduino#4932]
Please add https://github.com/fabianofranca/ESP8266RestClient

**Comment by agdl** [comment]
Hi, I'm sorry but your library can't be added please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

In particular a tag is missing

**Comment by fabianofranca** [comment]
Tag v1.0.0 added. Thanks

**Comment by agdl** [comment]
Done thank you!
