### ISSUE TITLE
New Library - OpenDevice by ricardojlrufino

### ISSUE THREAD

**Issue by ricardojlrufino** [arduino/Arduino#4934]
Please add https://github.com/OpenDevice/OpenDeviceArduino

**Comment by per1234** [comment]
That link is a 404. Did you mean https://github.com/OpenDevice/opendevice-lib-arduino?

**Comment by ricardojlrufino** [comment]
that is, sorry. I do not know why I put this url. Thank you

**Comment by per1234** [comment]
@ricardojlrufino did you close this issue accidentally?

**Comment by cmaglie** [comment]
anyway, the library has been added
