### ISSUE TITLE
Library manager -- Please add EMoRo2560 lib to library manager

### ISSUE THREAD

**Issue by inovatic-ict** [arduino/Arduino#4935]
Please add EMoro 2560 to Library manager.

https://github.com/inovatic-ict/emoro-2560-library

Thank you!

**Comment by agdl** [comment]
Hi, your library.properties and the tag do not match in the version number. Update this please

**Comment by inovatic-ict** [comment]
Updated!  (v. 2.4)

**Comment by agdl** [comment]
Done thank you!
