### ISSUE TITLE
Auto dfu factory reset for onboard ATmega8U2 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#494]
This is [Issue 494](http://code.google.com/p/arduino/issues/detail?id=494) moved from a Google Code project.
Added by 2011-03-04T16:09:58.000Z by [skywodd](http://code.google.com/u/skywodd/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Possibility to add a DFU "burn factory bootloader" option for ATmega8U2 ? (like flip for window or dfu-programmer for linux) 

**Why?**
Because some time people aren't perfect and would like restart with the factory firware or simply recovery standard usage.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

**Comment by NicoHood** [comment]
I think this can be closed. Since if someone uploads a new firmware to the 8u2 (which is now a 16u2) he knows how to do it. So he can switch back to the usb-serial firmware again.

Also nowadays there are better options like my HoodLoader2 to upload code, instead of with dfu.

**Comment by sandeepmistry** [comment]
Closing as per @NicoHood's comment.
