### ISSUE TITLE
Persistent Board Setting

### ISSUE THREAD

**Issue by BADnetwork** [arduino/Arduino#4950]
A great feature to add would be for each sketch to remember the board it was compiled for, if a write a sketch for a uno, it would add a file to the sketch folder with '328p, 16MHz, Bootloader' etc So when I open it next time, It auto chooses the correct 'tools' setting.

**Comment by jsotola** [comment]
maybe it would be better if the settings were in the sketch itself in a form of a comment on first line,
or a #pragma line
that way the settings would be applied to a sketch that was copied from the internet

**Comment by per1234** [comment]
Duplicate of #1481
