### ISSUE TITLE
New Library - CoDrone

### ISSUE THREAD

**Issue by RobolinkInc** [arduino/Arduino#4951]
Hi, 

We'd like to include our CoDrone library to the Arduino Library Manager.  The library manages functions and examples for our CoDrone product users.
The library can be found here: https://github.com/RobolinkInc/CoDrone.git

Thanks,
http://robolink.com/

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing

**Comment by RobolinkInc** [comment]
I've created a new release 1.1 and merged the pull request.  
Please let me know me know if you need me to do anything else.
Thanks

**Comment by agdl** [comment]
Done thank you!
