### ISSUE TITLE
Arduino 101 - McAffee reports trojan in arduino101load.exe

### ISSUE THREAD

**Issue by VisualMicro** [arduino/Arduino#4952]
Running windows and 1.6.9. 

I just installed the 1.0.5 Intel core. The previous 1.0.4 was ok. 

McAffee report attached.

![arduino101loadertrojan](https://cloud.githubusercontent.com/assets/1071555/15271110/a98856c6-1a31-11e6-8841-d5cf6330d791.png)

**Comment by facchinm** [comment]
Hi @VisualMicro ,
thanks for reporting, I'm moving this issue to the proper repo for faster solution

**Comment by facchinm** [comment]
Reported here https://github.com/01org/corelibs-arduino101/issues/184

**Comment by VisualMicro** [comment]
Had a quick response to this. Sounds like a false positive so will be reported to McAffee.

Great support thanks!
