### ISSUE TITLE
New library: TLC5615

### ISSUE THREAD

**Issue by xcvista** [arduino/Arduino#4953]
TLC5615 DAC driver.

https://github.com/ArduinoMax/TLC5615

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing

**Comment by xcvista** [comment]
@agdl What is a tag? How to add it?

**Comment by agdl** [comment]
Hi, here what you need
https://help.github.com/articles/creating-releases/

**Comment by xcvista** [comment]
@agdl Added a tag (and a README, and a reference to a license. I am going permissive with 3-BSDL and hope it can work with you guys.)

**Comment by agdl** [comment]
Done thank you!
