### ISSUE TITLE
New library: LircRemote101 for Arduino101/Genuino101

### ISSUE THREAD

**Issue by dantler** [arduino/Arduino#4956]
Driver for turning any GPIO pin into an infrared remote transmitter.  Only supports Arduino101/Genuino101.

https://github.com/dantler/LircRemote101

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing

**Comment by dantler** [comment]
Updated.  Did I fix the issues?

**Comment by agdl** [comment]
I can't see any tag I'm sorry. please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by agdl** [comment]
Done thank you!

**Comment by dantler** [comment]
Thank you for the link.  Please reopen this.  The tag is now pushed.
