### ISSUE TITLE
arduino yun

### ISSUE THREAD

**Issue by SKYLARA** [arduino/Arduino#4966]
i try to upload my code but i have this error !!!
avrdude: no programmer has been specified on the command line or the config file
         Specify a programmer using the -c option and try again

**Comment by facchinm** [comment]
Hi @SKYLARA ,
can you post the verbose output (you can enable it from Preferences menu, select both "compilation" and "upload")?

**Comment by CubeFromSpace** [comment]
Im sorry yo, but the Arduino Yun is outdated

**Comment by CubeFromSpace** [comment]
You may need to talk to the arduino tech experts

**Comment by agdl** [comment]
I'm closing this for lack of feedback
