### ISSUE TITLE
Upload problem after upgrading Arduino AVR Boards to 1.6.10

### ISSUE THREAD

**Issue by hamid914** [arduino/Arduino#4974]
I used Board Manager to upgrade Arduino AVR Boards  to version 1.6.10. After that, uploading any program to my MEGA board finished with no errors and it displays `Upload Done` but it is not functional on the board. Even Blink example does not work after upgrade.
I tried upgrade to 1.6.11 but the problem did not solved.
I tried downgrade to 1.6.9, after that all upload process finish with success and all programs are functional.
I reproduced this scenario on Windows and Mac with Arduino 1.6.9.

Why this problem happens?

**Comment by facchinm** [comment]
Hi @hamid914 ,
could you paste here the sketch and the verbose output (also with compiler warnings set to "all")? Thanks

**Comment by hamid914** [comment]
@facchinm Unfortunately I haven't access to the MEGA board for months I think. I will include more details later if the problem persists.

**Comment by sandeepmistry** [comment]
I'm closing this for now, please re-open when you have more details.
