### ISSUE TITLE
Documentation String replace

### ISSUE THREAD

**Issue by DrDooom** [arduino/Arduino#4980]
I am using String.replace to cut some text. The documentation tells us:

[String Replace Reference](https://www.arduino.cc/en/Reference/StringReplace)
> Returns
> another String containing the new string with replaced characters. 

So my Line looks like:
`text = text.replace("\0"," ");`
and the compiler crashes with message "no known conversion for argument 1 from 'void' to 'const char*'".

So the Line
`text.replace("\0"," ");`
works well.

Please correct the Info about the Return Value.

**Comment by agdl** [comment]
Done thank you!
