### ISSUE TITLE
Cannot get to board manager from with editor 1.6.9

### ISSUE THREAD

**Issue by foxed-in** [arduino/Arduino#4985]
Per release notes of 1.6.9: 
"* Make http://librarymanager and http://boardmanager links clickable from the editor window"

It works for library manager but not with board manager, which opens a browser that of course is not resolvable by dns

**Comment by facchinm** [comment]
Hi @foxed-in ,
sorry for the inconvenience, the correct "link" for Board manager is `http://boardsmanager`, I'm updating the changelog right now.
Thanks for pointing it out.

**Comment by facchinm** [comment]
Fixed by f0e5c90d4324de1d6389e85a5c7efbbce70c40dd
