### ISSUE TITLE
7805 reverse bias

### ISSUE THREAD

**Issue by fulda1** [arduino/Arduino#4986]
Hello all,

I have little problem with Arduino reference schematics. For example for Arduino Nano. Here is good D1 "+5V auto selector", but it is only one half. As it is stated in 78x05x datasheet, this chip is not "reverse bias tolerant". It is strongly recommended to use any of reverse bias protection circuit. For example this one in attachment. 

Jindra

![7805_reverse_bias](https://cloud.githubusercontent.com/assets/12329667/15533986/24924f7e-2267-11e6-8902-277774fef2cd.png)

**Comment by facchinm** [comment]
Hi @fulda1 , the board is currently retired and the documentation will not be kept up-to-date.
Anyway, thanks for the insight, if anyone should search for a problem with a new design it will find this useful information.
