### ISSUE TITLE
Watchdog.h does not exist for avr

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#4994]
I'm currently trying to make a sketch compatible between mega and due as I want to move my project from the mega to the due.
I used avr_wdt.h but I see that due knows watchdog.h.
Is there any reason (except of -not yet done-) avr does not have this class?

**Comment by vbextreme** [comment]
Arduino Due does not use an MCU Avr consequently methods for working with the watchdog are different.
I think that your question should be placed in the Arduino forum.
