### ISSUE TITLE
Inability to start IDE due to dialogue from #2719 for reasons unclear.

### ISSUE THREAD

**Issue by Ghostbird** [arduino/Arduino#4995]
Today I updated my Arduino IDE to `ARDUINO 1.6.9 2016.05.10`

I tried to start it, but got the dialogue created to solve #2719: 

> Your copy of the IDE is installed in a subfolder of your sketchbook. Please move the IDE to another folder.

I was rather annoyed that it did not provide me with additional info that clarified why it was suddenly going wrong. I would have liked to see:
- The path to the IDE
- The sketchbook path

After as short search, I found that the sketchbook location was defined in .arduino/preferences.txt
I checked, and I concluded that my sketchbook folder was: `/home/gijsbert/sketchbook`.
My IDE is installed in `/home/gijsbert/Arduino`
I checked both paths and noticed that the sketchbook folder did not exist. It could be that it therefore defaulted to the part of the path that did exist, though that would be a bug in its own right.
I created the folder `/home/gijsbert/sketchbook`, and tried to restart Arduino IDE, but I still got the same error.
I ran:

``` bash
ls -laR /home/gijsbert/Arduino | grep sketchbook
```

To verify that no links in the filesystem existed that would somehow link the IDE folder and the sketchbook folder together. (Doing this check the other way around wasn't necessary, because I just created the empty sketchbook folder.)

I also deleted my `preferences.txt` to ensure that it wasn't caused by misconfiguration on my part. However this did not solve the issue.

At this point I just decided that it was probably a report worthy bug. I'm sorry if I just overlooked something trivial, but if this happens to other people too, it should probably be looked into.

EDIT: I found out that [this information](https://www.arduino.cc/en/Hacking/Preferences) is incorrect, and the preferences are located in the folder `/home/gijsbert/.arduino15`. The sketchbook folder was misdefined there.
At this point I'm not sure whether this is still a bug, so I'll leave this open for comments. Personally I'm curious:
- Why use the folder `.arduino15` instead of `.arduino` or the even more standard `.config/arduino`?

The _fix_ in my opinion would be to change the dialogue such that it shows these values:
- The Arduino IDE path
- The sketchbook path
- The location of the config file that determined the sketchbook path.

Furthermore I think that the suggestion of moving the IDE is the wrong one. The correct solution should be to check the sketchbook path in the config file and then decide whether to change that, or to move the IDE.
_Ideally_ the dialogue should allow the user to change the sketchbook path configuration directly without having to look for the config file, since this would be nicest to the user. However, if this issue is fairly rare, it may not be worth the effort.

**Comment by Ghostbird** [comment]
Even more silly. If the Arduino IDE is installed in `/home/username/Arduino` (which, as it turns out, is the default sketchbook location), you can start it `once`, since the fix for #2719 does not check whether the IDE location conflicts with the default value if no preferences.txt exists. However once you close it, and try to re-open it, the fix for #2719 kicks in, and you can no longer open the IDE.
It seemed logical to me to install the Arduino IDE into `/home/gijsbert/Arduino` and the sketchbook in `/home/gijsbert/sketchbook`. But apparently my logic triggered this whole issue.

It turns out the suggestion to move the IDE in the dialogue was indeed the logical solution when you thought about it from the point of view of the Arduino IDE writer.

**Comment by per1234** [comment]
> this information is incorrect, and the preferences are located in the folder /home/gijsbert/.arduino15.

Thanks for pointing that out @Ghostbird! That documentation has since been updated.

Since the dialog mentioned here doesn't even work/exist anymore and we have a new issue where that situation as well as your excellent suggestion of making the dialog offer to change the sketchbook location is being discussed (https://github.com/arduino/Arduino/issues/10511), I'm going to go ahead and close this. I welcome your input over on https://github.com/arduino/Arduino/issues/10511 @Ghostbird.
