### ISSUE TITLE
Serial.end() returns before the transmit pin is available for other uses. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#500]
This is [Issue 500](http://code.google.com/p/arduino/issues/detail?id=500) moved from a Google Code project.
Added by 2011-03-08T03:06:46.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

**What steps will reproduce the problem?**
1.Serial.print() followed by a Serial.end()
2.Then toggle another pin.
3.Look at the TX pin and the other pin on a scope.

**What is the expected output? What do you see instead?**

The other pin gets toggled before the transmission is done.  We probably need to use the transmit complete interrupt to check for the end of the transmission (i.e. the byte has been shifted out of the shift register).

**Please use labels and text to provide additional information.**

**Comment by sandeepmistry** [comment]
This should be resolved by https://github.com/arduino/Arduino/commit/9b7b23f045968ff14252e74c355279d9f17ef3f5.
