### ISSUE TITLE
"string" is highlighted as variable type

### ISSUE THREAD

**Issue by Gorkde** [arduino/Arduino#5001]
Tried to use string as variable type which did throw an error.
Couldn't find the reason since the word "string" (lowercase) is recognized by the IDE as variable type and highlighted cyan.

**Comment by facchinm** [comment]
Hi @Gorkde ,
thanks for pointing it out, the`string` literal was probably added to highlight c++ strings but can be misleading for novices, so I removed it with 61323525b7fe49a0638f478cbd2a9e909dd18e17

Thanks!
