### ISSUE TITLE
The reference design and schematics for the motor shield V3 are wrong.

### ISSUE THREAD

**Issue by gorlando1234567890** [arduino/Arduino#5009]
Hi,
on this web page https://www.arduino.cc/en/Main/ArduinoMotorShieldR3 there are the wrong files.
Could you upload the correct files, please?
Thanks
Giovanni

**Comment by q2dg** [comment]
Maybe it's time to a V4 or at least, a "Genuino" version, but...

**Comment by frrederik** [comment]
Closing this issue. Files are rev 3.
