### ISSUE TITLE
Dynamically add menu items? 

### ISSUE THREAD

**Issue by lpercifield** [arduino/Arduino#5019]
I'm working on an OTA interface for a bluetooth board and I would like the ability to dynamically add a list of discovered boards. Similar to the way the Yun IPs show in the ports menu. So far, I can manually add each of the board UUIDs in a static menu, but I would love to be able to run a scan as part of the menu creation, or some port rescan function...

Any thoughts on how this might work with existing builds?

As always, keep up the good work!

**Comment by sandeepmistry** [comment]
There's now support for pluggable discovery: https://github.com/arduino/Arduino/pull/8038
