### ISSUE TITLE
Ethernet interface should use const parameters for pointers to constant data [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#502]
This is [Issue 502](http://code.google.com/p/arduino/issues/detail?id=502) moved from a Google Code project.
Added by 2011-03-10T02:23:23.000Z by [pe...@stairways.com.au](http://code.google.com/u/113171804669272702099/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

**What change would like to see?**

Currently the Ethernet (and subsystems) use parameters like uint8_t *mac, being pointers to MAC or IP addresses, as well as data packets.  These parameters do not and should not modify these bytes, and this should be explicitly declared in the interfaces.

**Why?**

Otherwise the user is left wondering whether the function might modify the MAC or IP address bytes, and whether they are safe to be resized for successive calls.

Would this cause any incompatibilities with previous versions?  If so, how can these be mitigated?

This should not cause any incompatibilities, but subsystems will need to ensure they properly use const pointer parameters or the higher level functions with const parameters will not be able to pass their data in.

Attached is a diff affecting Ethernet.{cpp,h} Udp.{cpp,h} socket.{cpp,h} w5100.{cpp,h}

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#29
