### ISSUE TITLE
EthernetServer begin returns void

### ISSUE THREAD

**Issue by vprheli** [arduino/Arduino#5023]
Hi, Why the function EthernetServer.begin(port|null) returns void? It calls function socket() which return uint8_t as result, same as EtherentUdp.If sock counter > MAX_SOCK_NUM it fails also.Or add some function like isListening() to know if it socket is in listening state.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#4

**Comment by agdl** [comment]
I moved this issue in the proper repository
