### ISSUE TITLE
New Library:rBASE64

### ISSUE THREAD

**Issue by boseji** [arduino/Arduino#5027]
I have made a new base64 encoding / decoding library for Arduino UNO and ESP8266. This library works with String operations and has better memory management. This library would help people in quickly implementing Base64 encoding without much lines of code. Please look at the examples it would be helpful.
Thus I request you to add this library to the list of Arduino library so that every one benefits.
This library has been released under CC-BY-SA and hence is open source contribution to Arduino ecosystem.

https://github.com/boseji/rBASE64

This is the Git location for the library, First release version v1.0.0

**Comment by agdl** [comment]
Done thank you!
