### ISSUE TITLE
New Library: xxtea-iot-crypt

### ISSUE THREAD

**Issue by boseji** [arduino/Arduino#5028]
Hello, 
I have created a XXTEA encryption and decryption library.
This library is memory efficient and works for both Arduino UNO and ESP8266.
Also native interfaces are available for advance users to hook on network streams to help them in continuous encryption implementation. This library also work for MQTT messaging and is small enough to run locally in the Arduino UNO. There are examples provided to explain the operation of encryption and decryption both using the Arduino Style API and native API.
I would like to request you to add this library to Arduino's list of library so that everyone benefits.
This library has been released under CC-BY-SA and hence is open source contribution to Arduino ecosystem.

https://github.com/boseji/xxtea-iot-crypt

This is the Git location for the library, First release version v1.0.0

**Comment by agdl** [comment]
Done thank you!
