### ISSUE TITLE
New Library: FXAS21002C Arduino

### ISSUE THREAD

**Issue by sabas1080** [arduino/Arduino#5034]
Arduino library for the FXAS21002C 3-Axis Digital Angular Rate Gyroscope

https://github.com/sabas1080/FXAS21002C_Arduino_Library

Thanks

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing
Please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by sabas1080** [comment]
Sorry, done

**Comment by agdl** [comment]
I added it, but please next time tag must be compliant with what is written in the library.properties
