### ISSUE TITLE
Arduino Uno Rev3, not being recognized by Windows 10

### ISSUE THREAD

**Issue by GlauberBazotti** [arduino/Arduino#5041]
Hello, my Arduino Uno Rev3, not being recognized by Windows 10, since I disabled the driver signing, more still is not being recognized by the OS when having to update the driver, the one Kontakt saying that the update was not performed because the win already installed the best driver for your device!

What do I do?

**Comment by agdl** [comment]
@GlauberBazotti I'm closing this. Please contact the Arduino support at support@arduino.cc GitHub is intended for software related issue. Please have a look also at forum.arduino.cc
