### ISSUE TITLE
Arduino IDE selects wrong board package toolchain

### ISSUE THREAD

**Issue by vshymanskyy** [arduino/Arduino#5042]
The Arduino IDE (or arduino-builder), selects the wrong toolchain when some additional platforms are installed through Boards Manager.

For example, if I install both Digistump Oak and ESP8266 community packages, it selects
```.arduino15/packages/digistump/tools/xtensa-lx106-elf-gcc``` instead of
```.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc``` when compiling for regular ESP8266.

It causes more problems like this:
I'm trying to build "Blink" example for MKR100 (after installing RedBear Duo support package):
It fails, because IDE selects ```~/.arduino15/packages/RedBear/tools/arm-none-eabi-gcc/4.9-2015-q3``` toolchain, and it's not compiling correctly.

Same for some other boards combinations.

**Comment by vshymanskyy** [comment]
https://github.com/arduino/Arduino/issues/4593 - might be relevant.

**Comment by cmaglie** [comment]
May you post a link to the boards managers packages and the IDE version you're using?

**Comment by vshymanskyy** [comment]
How to reproduce:

1. Install Arduino IDE v1.6.9
2. Install MKR1000 board support from the Boards Manager
3. Check that "Basics->Blink" example compiles fine for MKR1000 board.
4. Configure additional Boards Manager source: https://redbearlab.github.io/arduino/package_redbear_index.json
5. Install RedBead Duo package the Boards Manager
6. "Basics->Blink" example compilation **fails for target MKR1000 board**.

**Comment by facchinm** [comment]
This is probably solved by https://github.com/arduino/Arduino/pull/4795, would you mind giving the @ArduinoBot build a try?
