### ISSUE TITLE
USART interface for Tiny AVRs

### ISSUE THREAD

**Issue by syddo** [arduino/Arduino#5046]
Hello!

I was wondering if there is any plan to make some code for USART support on Tiny AVRs?
They are especially a bit more challenging to do debug on since there is no OCD. I was thinking the USART could be used to send data via a Virtual COM Port so we can have some debugging capability?

**Comment by agdl** [comment]
@syddo actually apart from Arduno Gemma there no products based on Tiny AVRs. What I suggest you is to look at cores like this https://github.com/SpenceKonde/ATTinyCore

**Comment by syddo** [comment]
@agdl thanks for sharing that link!
