### ISSUE TITLE
Library register request: Thing+

### ISSUE THREAD

**Issue by yhjo8478** [arduino/Arduino#5048]
Hello. I made Arduino library.
This library helps connecting your Arduino board to Thing+ cloud easly and fast.
Please add my library to Library manager.

This is github url : https://github.com/daliworks/arduino_library

Thanks advance.

**Comment by agdl** [comment]
Hi, I'm sorry but you library can't be added since the release is not compliant with standard arduino library

https://github.com/daliworks/arduino_library/tree/v1.0.0

Please fix it and consider to rename the repository in thingplus instead of arduino_library

**Comment by yhjo8478** [comment]
Thank you for fast reply.
I changed library name from arduino_library to Thingplus and i re-release it.
Please check my changes from https://github.com/daliworks/arduino_library

**Comment by agdl** [comment]
Done thank you! (Please delete unused release)
