### ISSUE TITLE
New library request: CalculatorLibrary

### ISSUE THREAD

**Issue by danaack** [arduino/Arduino#5057]
https://github.com/danaack/CalculatorLibrary/releases/tag/1.0.0

**Comment by matthijskooijman** [comment]
I don't think the libraries added to the manager are typically screened or limited, but in this case I wonder: what's the point of this library?

**Comment by agdl** [comment]
I'm agree with @matthijskooijman . I find more difficult to understand how to use your library instead of actually do the operation

**Comment by danaack** [comment]
@matthijskooijman @agdl Sorry for the confusion, I was simply testing the process of adding a library to the Arduino library manager. This library will be deleted later this week.

**Comment by agdl** [comment]
@danaack ok so I'm closing this issue thank you!
