### ISSUE TITLE
Close tab

### ISSUE THREAD

**Issue by fivitti** [arduino/Arduino#5067]
Hello!
I cannot close any tab without delete them. I don't have 'x' button on tab. Shortcut Ctrl+W close the ArduinoIDE window.
Version 1.6.9.

**Comment by matthijskooijman** [comment]
This is intentional, all files in the sketch are always shown in tabs.

**Comment by q2dg** [comment]
Well, weĺl have no luck, @fivitti ...see https://github.com/arduino/Arduino/issues/2883

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/2883
