### ISSUE TITLE
Updated library: ROKduino

### ISSUE THREAD

**Issue by morozovsky** [arduino/Arduino#5070]
Updated library: ROKduino

Allows control of Rokenbok Education ROKduino robotics system and provides functions for light, bump, angle, and proximity sensor blocks, light and motor modules, ROK-star IR communication (transmit and receive), built-in LEDs and speaker, and battery voltage measurement.

Library can be found here: https://github.com/EscaVic/ROKduino
Release tag 2.0.1

**Comment by agdl** [comment]
Done thank you!
