### ISSUE TITLE
[Library Manager] Adding ArduinoSpritzCipher library request

### ISSUE THREAD

**Issue by abderraouf-adjal** [arduino/Arduino#5072]
*ArduinoSpritzCipher*, It is a C implementation of *Spritz cipher* library for Arduino, CSPRNG, cryptographic hash and MAC functions, symmetric-key data encryption, and general-purpose functions.

The library GitHub repo: https://github.com/abderraouf-adjal/ArduinoSpritzCipher
The library releases are signed with a the developer (me) PGP signature.

https://github.com/abderraouf-adjal/ArduinoSpritzCipher/releases

**Comment by agdl** [comment]
Done thank you!
