### ISSUE TITLE
Error compiling on rename file (Multiple definitions) when using external editor

### ISSUE THREAD

**Issue by rkost** [arduino/Arduino#5075]
When using an external editor for refactoring a file (move it to a sub directory etc) with "use external editor"-setting set, compiling will fail with error message "multiple definition" of all functions the files contain. 

Setup: 
Local project with relative includes and sub directorys.

Using version 1.6.9 on plain arch linux (up to date), compiling for Atmega2560

**Comment by rkost** [comment]
Wooops. Think #5055 covered this one already..

**Comment by matthijskooijman** [comment]
Yup, so I'm closing this as a duplicate. Thanks for taking the time to report, though :-)
