### ISSUE TITLE
[Library Manager] Please add U8g2: Graphics Library for Monochrome OLEDs and LCDs

### ISSUE THREAD

**Issue by olikraus** [arduino/Arduino#5076]
Hi

U8g2 is  the successor of U8glib, a graphics library for monochrome OLEDs and LCDs
Github Repo of the Arduino Library: 
https://github.com/olikraus/U8g2_Arduino

Official project page: https://github.com/olikraus/u8g2

Thanks,
Oliver

**Comment by agdl** [comment]
Done thank you!
