### ISSUE TITLE
[Library Manager]: Please Add Adafruit_WINC1500 to the Library Manager

### ISSUE THREAD

**Issue by toddtreece** [arduino/Arduino#5083]
https://github.com/adafruit/Adafruit_WINC1500

Thanks!

**Comment by per1234** [comment]
@toddtreece it looks like this request slipped through the cracks but I see that the library readme now says it was [deprecated](https://github.com/adafruit/Adafruit_WINC1500/commit/88d7ff9d2ae4b0af17aee99e5603d3add6d8878b). Am I correct to think that you no longer want this library added to Library Manager?
