### ISSUE TITLE
Minor Typo in sketch naming error message.

### ISSUE THREAD

**Issue by ZoogerZager** [arduino/Arduino#5086]
![screenshot from 2016-06-29 10 17 55](https://cloud.githubusercontent.com/assets/11649609/16455613/fccbc88e-3de2-11e6-880b-e7a6a315a246.png)

The message should read:

The sketch name had to be modified. Sketch names can only consist
of ASCII characters and numbers (but cannot start with a number).
They should also be less than 64 characters long.

**Comment by per1234** [comment]
You should check the hourly build to make sure the issue hasn't already been fixed. I don't see that typo on the hourly build or 1.6.9.

**Comment by sandeepmistry** [comment]
@per1234, thanks for checking this in the hourly build!

@ZoogerZager based on your screenshot, you using version 1.0.5 of the IDE which is really old. I would suggest you upgrade to 1.6.9.
