### ISSUE TITLE
USB Flash disk with Arduino ?

### ISSUE THREAD

**Issue by MehmetKALA** [arduino/Arduino#5090]
for months i am researching to use USB HardDisk with Arduino. I bought 2 usb module but i can't do it. My purpose is creating a txt file and writing some data with arduino and then to view on computer. Can you suggest a shield or help these modules? http://www.dx.com/p/ch376-usb-communication-module-reader-adapter-217605#.V3i21mh97IU and http://www.dx.com/p/usb-host-shield-expansion-board-google-android-compatible-for-arduino-blue-156155#.V3i3PWh97IU

**Comment by sandeepmistry** [comment]
Hi @MehmetKALA,

This issue tracker is for reporting issues with the IDE or AVR and SAM Arduino cores.

I would suggest you raise your question on the Arduino forum: http://forum.arduino.cc
