### ISSUE TITLE
Wrong symlink causes compiling failure

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#5093]
```
stat /home/arch/hackallthethings/sketchbook/hardware/arduino3/avr: no such file or directory
```

The path above does no longer exist. avr points to an inaccessible folder (cause I swtiched my OS). But this error caused the whole ide to not work. This is not a normal case, but should not cause the whole IDE to not function.

**Comment by matthijskooijman** [comment]
"caused the whole ide to not work" <-- that's a bit of a lousy error description, you really should know better than that. Does it not start? Does it print anything on stderr? Is there an error popup? ALso, is this `sketchbook` folder configured as your sketchbook?

**Comment by NicoHood** [comment]
Yes it is configured as sketchbook and sorry, the uploading did not work anymore.

**Comment by facchinm** [comment]
Should be fixed by https://github.com/arduino/arduino-builder/pull/166

**Comment by NicoHood** [comment]
I have not tested this again but I'll close it of you say so.
