### ISSUE TITLE
Install Button does not work for SuSE 13.2

### ISSUE THREAD

**Issue by pischky** [arduino/Arduino#5104]
On http://playground.arduino.cc/Linux/OpenSUSE the install Button does not work for Version 13.2.

Message is:
The install link or file you opened does not contain instructions for openSUSE 13.2.

**Comment by pischky** [comment]
just have edit arduino.ymp and changed 13.1 to 13.2 two times. Installation now works, but what you get is version 1.0.6. Hmm...

**Comment by facchinm** [comment]
The package looks quite unmaintained indeed... I'm closing this since Playground is a fully modifiable wiki, so feel free to fix the link or add the instructions on how to fix it if you wish :wink:
