### ISSUE TITLE
Check local system before installing anything.

### ISSUE THREAD

**Issue by xcvista** [arduino/Arduino#5110]
Currently the IDE installs the JRE and all board dependencies blindly. Is it possible to perform a bit of system checking before installing anything?

Things to check for:

1. System JRE. If the installer detected an installed JRE in the system, prefer that over the bundled JRE. The bundled JRE is usually an older 32-bit one but the user may already have a newer, 64-bit one already installed.

    On my Linux-based development system I deleted the built-in JRE and symlinked the copy installed by my system's package manager in.

2.  Embedded Toolchains. If the required toolchains are already installed for a platform, do not install the tools packaged in the board definition and prefer the system-provided one. This enables Arduino IDE to share toolchain with other development tools like AVR Studio, MPLAB or Keil, reducing the footprint of the IDE.

**Comment by facchinm** [comment]
Hi @xcvista , to do so we would need a modular install system and/or a bunch of different packages.
We love to keep things simple, so a new user doesn't need to know what a toolchain or Java is when he starts using the IDE.
If you want to use your own tools, simply dig into core's `platform.txt` and replace {runtime.*} variables with actual paths.
