### ISSUE TITLE
New ProcessScheduler Library

### ISSUE THREAD

**Issue by wizard97** [arduino/Arduino#5111]
Hi,

I made a new cooperative [ProcessScheduler](https://github.com/wizard97/ArduinoProcessScheduler) Library I would like to get added to the Library Manager. It conforms to the 1.5 Library format. 

If you are interested, here are a few features:
- Processes are objects, not callback functions
- Concurrency protection by using a scheduler job queue
- Process priority Levels
- Process time statistics (get the % CPU time for processes)
- Exception handling (using `setjmp()` and `longjmp()`)
- Auto scheduler interruption of stuck processes (using ISR and `longjmp()`)

**Comment by agdl** [comment]
Done thank you!
