### ISSUE TITLE
[Library manager]: Please add mysensors library to library manager

### ISSUE THREAD

**Issue by tbowmo** [arduino/Arduino#5112]
https://github.com/mysensors/MySensors/tree/master

Thanks

**Comment by agdl** [comment]
Done thank you!

**Comment by tbowmo** [comment]
It seems that the crawler is stopped, as the library_index.json file haven't been updated since Thu, 07 Jul 2016 20:37:08 GMT, according to the headers received from download.arduino.cc. (Other libraries which should have been added the last couple of days, is not in the file as well, so it seems that it's a generic problem)

Could you please check this @agdl ?

Thanks..
