### ISSUE TITLE
Please allow multi-word font names

### ISSUE THREAD

**Issue by noyannus** [arduino/Arduino#5114]
Please allow multi-word font names in the next version. I'd love to use Roboto Mono or Source Code Pro. 

I tried editing the line "editor.font=Monaco, ..." in ~/Library/Arduino15/preferences.txt, using the font name within " " or ' ', or changing spaces to underscores (e.g., "Roboto_Mono") but in all cases the font was not recognized.

Thank you!

Arduino 1.7.10
Mac OX 10.11.3

**Comment by agdl** [comment]
Hi, Arduino 1.7.10 doesn't refer to this repository I'm sorry. So I'm closing this issue
