### ISSUE TITLE
library manager crawler seems to be defunct

### ISSUE THREAD

**Issue by tbowmo** [arduino/Arduino#5119]
It seems that the crawler for the library manager doesn't run, as the last modified time for the library_index.json file (located here : http://downloads.arduino.cc/libraries/library_index.json) is Thu, 07 Jul 2016 20:37:08 GMT, according to the HTTP headers received.

New libraries should have been added in #5111 and #5112, a couple of days ago.. But they are not showing up..

@agdl could you look into this? (Seems that you're the library manager wizard :) )

**Comment by facchinm** [comment]
Hi Thomas,
the Jenkins cron job went on vacation for a few days, just restarted :wink: 
Thanks for reporting! The libraries should be added in a matter of an hour
