### ISSUE TITLE
Add Library Release: Syncano Arduino Library

### ISSUE THREAD

**Issue by StudentDawid** [arduino/Arduino#5120]
New release:
[https://github.com/Syncano/syncano-arduino/releases/tag/0.2.0](https://github.com/Syncano/syncano-arduino/releases/tag/0.2.0)
for:
[https://github.com/Syncano/syncano-arduino](https://github.com/Syncano/syncano-arduino)

**Comment by agdl** [comment]
@StudentDawid please fix version number in the library.properties

**Comment by StudentDawid** [comment]
Now it`s version 0.2.0.

**Comment by agdl** [comment]
Done thank you!
