### ISSUE TITLE
Add XLR8Pong library to library manager

### ISSUE THREAD

**Issue by tedholler** [arduino/Arduino#5123]
https://github.com/AloriumTechnology/XLR8Pong

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing. Please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by tedholler** [comment]
Sorry about that.
I tagged the library  (1.0.0)

**Comment by agdl** [comment]
Done thank you!

**Comment by tedholler** [comment]
Thanks!  Have a fun day!!!
