### ISSUE TITLE
Add XLR8BuildTemplate library to Library Manager

### ISSUE THREAD

**Issue by MattWeberDesign** [arduino/Arduino#5126]
https://github.com/AloriumTechnology/XLR8BuildTemplate

**Comment by agdl** [comment]
Done thank you!

**Comment by MattWeberDesign** [comment]
Thank you.
Is there a reason why the name was changed from XLR8BuildTemplate to XLR8_Build? Similarly, my XLR8Core library appears to have been changed to XLR8_Core. I'm concerned it will be confusing for people to see one name in github and then a different name in their libraries folder.
Thanks,
Matt

**Comment by agdl** [comment]
Fixed

**Comment by MattWeberDesign** [comment]
Thank you!
