### ISSUE TITLE
http://playground.arduino.cc/Code/ACPhaseControl circuit diagram image broken

### ISSUE THREAD

**Issue by mikemwalsh** [arduino/Arduino#5129]
Circuit diagram appears to be missing from page.  Broken img reference.

Network request:
GET http://img27.imageshack.us/img27/6200/acphasecontrol.png 404 (Not Found)

**Comment by facchinm** [comment]
Playground is a wiki, so any logged user can modify it. 
We didn't create the contents there and we are unable to fix the broken link, sorry.

**Comment by facchinm** [comment]
The last user who modified that page is [pert](http://forum.arduino.cc/index.php?action=profile;u=224903), maybe he knows where to find that image

**Comment by mikemwalsh** [comment]
Woops!  Sorry about that, I got mixed up about what section I was in!
