### ISSUE TITLE
Serial.available() not working

### ISSUE THREAD

**Issue by clovervineetdodd** [arduino/Arduino#5133]
My code currently reads to check Serial.available(), but it always goes to zero. I have tried adding delays, and I have even tried sending commands through the terminal. That being said, I am not sure what is going wrong. I also cannot send messages to the Arduino.

**Comment by agdl** [comment]
Hi, which board are you using? IDE version?

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Please reopen it if needed
