### ISSUE TITLE
[Library Manager]: Please Add LoRa Serialization to the Library Manager

### ISSUE THREAD

**Issue by joscha** [arduino/Arduino#5134]
https://github.com/thesolarnomad/lora-serialization

Thanks!

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing

**Comment by joscha** [comment]
@agdl I am sorry, I don't understand - are you talking about a version tag on the master branch or some tag in the library.properties?

**Comment by joscha** [comment]
In the first case, I added `v2.1.0`.

**Comment by agdl** [comment]
Done thank you!

**Comment by joscha** [comment]
Great, thanks @agdl!
