### ISSUE TITLE
Library Manager - Please add Eventually to the list of libraries

### ISSUE THREAD

**Issue by johnnyb** [arduino/Arduino#5139]
Please add my new event-based library, Eventually, to the list of libraries:

https://github.com/johnnyb/Eventually

Tag: release-0-1-0 

Note - I didn't know if there was some way I was supposed to tag the release.  If it needs a different tag, let me know.

**Comment by Chris--A** [comment]
Yes you'll need to release it with a tag format of #.#.# So you'd need `0.1.0` without the word release. The numbers can be double digit, as in 1.0.10 as well.

**Comment by johnnyb** [comment]
Completed - thank you!

**Comment by agdl** [comment]
Done thank you!
