### ISSUE TITLE
Library Manager - Please add Shifty to the List of Libraries

### ISSUE THREAD

**Issue by johnnyb** [arduino/Arduino#5140]
Here is Shifty, a new Shift-register library that should eventually handle input/output using standard output shift registers:

https://github.com/johnnyb/Shifty

Tag: release-0-1-0

**Comment by Chris--A** [comment]
Like your other lib, you'll have to change the tag: https://github.com/arduino/Arduino/issues/5139#issuecomment-233246720

The description for the version and tag is here: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by johnnyb** [comment]
Completed.

**Comment by agdl** [comment]
Done thank you!
