### ISSUE TITLE
Board Manager - allow relative url in JSON

### ISSUE THREAD

**Issue by sleemanj** [arduino/Arduino#5141]
Presently the url to a board manager package zip in a json file has to be absolute.  

This is a PITA for lots of reasons, for example when testing the package file locally (that is I use a file:// board manager URL) I have to edit the package file to hard-code urls in that package file to also be file:// absolute urls.  Meaning the package json I test, and the package file I upload somewhere are not identical.

Similarly it means that if for example your board development and it's json is here on github, if anybody forks your development they then have to go and manually edit that json so that the URLs point to files in their repo, instead of yours, because they all have to be hard coded absolute.

It would be highly preferable for the urls in the json file to be able to be specified relative to the json file.

For example if the JSON file at `http://example.com/foo.json` contains `"url": "packages/bar.zip"` then that is resolved to `"url": "http://example.com/packages/bar.zip"`

**Comment by cmaglie** [comment]
To accomplish this we should save somewhere (outside the json?) the origin of the .json for an already downloaded `package_index.json`. Also this is a backward-incompatible change.

IMHO the advantages are very thin to justify such a big change, so I'm closing as won't-fix.
