### ISSUE TITLE
Add bitclock parameter for programmers to 'AvrdudeUploader.java' / programmers.txt [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#515]
This is [Issue 515](http://code.google.com/p/arduino/issues/detail?id=515) moved from a Google Code project.
Added by 2011-03-28T18:57:38.000Z by [madworm_...@spitzenpfeil.org](http://code.google.com/u/111909123140588471448/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

What:

Add bitclock parameter for programmers to 'AvrdudeUploader.java' / programmers.txt

Why: 

Significantly improve uploading speed / bootloader burning time with programmers that support setting the bitclock to low values like "-B 1" (e.g. usbtinyisp).

Possible conflicts:

With this patch "-B ..." is only set if it is defined in programmers.txt. If it is not defined, nothing changes.

---
```diff
--- a/app/src/processing/app/debug/AvrdudeUploader.java
+++ b/app/src/processing/app/debug/AvrdudeUploader.java
@@ -104,6 +104,10 @@ public class AvrdudeUploader extends Uploader  {
     Map<String, String> programmerPreferences = target.getProgrammers().get(programmer);
     List params = new ArrayList();
     params.add("-c" + programmerPreferences.get("protocol"));
+
-    if (programmerPreferences.get("bitclock") != null) {
-      params.add("-B" + Integer.parseInt(programmerPreferences.get("bitclock")));
-    }
  
   if ("usb".equals(programmerPreferences.get("communication"))) {
     params.add("-Pusb");
```
---

**Comment by per1234** [comment]
As was stated here: https://github.com/arduino/Arduino/pull/25#issuecomment-100881516, this can be accomplished by merely adding the desired parameters to `program.extra_params` in programmers.txt. So I think the patch provided is not useful but the suggestion to add the bitclock setting to may still be valid.
