### ISSUE TITLE
Quick questions regarding library specification & compatability.

### ISSUE THREAD

**Issue by Chris--A** [arduino/Arduino#5152]
Is the new library specification (rev 2.1) backwards compatible.
As in the 'includes' property isn't going to cause issues?

Also, when testing with 1.5.3, I get this error on many libraries:
> Missing 'core-dependencies' from library

From what I'm understanding in the Wiki, this shouldn't be happening:
> This is the specification for 3rd party library format to be used with Arduino IDE 1.5.x onwards.
  rev.1 has been implemented starting with version 1.5.3 (now superseded by rev.2)

**Comment by cmaglie** [comment]
> Is the new library specification (rev 2.1) backwards compatible.

yes the `includes` property is optional.

> Also, when testing with 1.5.3, I get this error on many libraries:
> > Missing 'core-dependencies' from library

IIRC this enforcing was present in 1.5.3 and removed afterward. Maybe the specification is not fully precise in this matter. Have you tried with later releases like 1.5.4 or 1.5.5?

**Comment by cmaglie** [comment]
I'm closing this one, feel free to reopen if you have further questions.
