### ISSUE TITLE
[Library Manager] New library BowlerCom for communication and robotics

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#5157]
Hello,

I have ported over my robotics communication and control framework to an Arduino 1.5 compliant stack. 

It can be found at:

https://github.com/CommonWealthRobotics/BowlerCom

Thank you!

**Comment by agdl** [comment]
@madhephaestus please fix library.properties. Look here
https://github.com/CommonWealthRobotics/BowlerCom/blob/3.12.1/library.properties

**Comment by madhephaestus** [comment]
I'm sorry, I don't understand what's wrong. Did a log file kick back any information about whats wrong?

**Comment by madhephaestus** [comment]
Hows this, i made a new release: https://github.com/CommonWealthRobotics/BowlerCom/blob/0cf0d1f9829ab5dc96f90e83cfe5a4665e3b4068/library.properties

**Comment by madhephaestus** [comment]
Ah, yes, i had a mismatch between the release number in the file and the Git release, that is resolved now in 3.12.2

**Comment by madhephaestus** [comment]
@agdl I believe it should be fixed now.

**Comment by agdl** [comment]
Done thank you!
