### ISSUE TITLE
Library register request: WizFi250 library

### ISSUE THREAD

**Issue by kaizen8501** [arduino/Arduino#5158]
Hi. I made Arduino library for Wi-Fi.
WizFi250 is Wi-Fi shield and I think this library helps using your Arduino board with Wi-Fi easily and fast.
Please add my library to Library manager.

This is gitbug url : https://github.com/Wiznet/WizFi250_arduino_library

Thank you.

**Comment by agdl** [comment]
Hi, please follow specification about repository structure

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by kaizen8501** [comment]
Thank you for fast reply. I modified directory structure.
Please check my repository again ^^
Thank you

**Comment by agdl** [comment]
Structure is good, but a tag is missing. Please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by agdl** [comment]
Another note. About the readme:
is Arduino not Arudino

**Comment by kaizen8501** [comment]
Hi. I modified wrong word and made tag to V1.0.
Please check again ^^

**Comment by agdl** [comment]
Done thank you!
