### ISSUE TITLE
arduino IDE problem text height retina

### ISSUE THREAD

**Issue by mcanet** [arduino/Arduino#5162]
Text in arduino IDE is rendering with wrong text line height and it is unreadable. I have last version 1.6.9 Arduino IDE. 
<img width="1440" alt="screen shot 2016-07-26 at 14 28 53" src="https://cloud.githubusercontent.com/assets/308759/17136309/3cfcd26c-533d-11e6-963c-2d707fa04ff6.png">

**Comment by gvarisco** [comment]
This issue should be gone away for good. I can't reproduce it on macOS High Sierra or Mojave. I'm going ahead and mark this as 'closed'. Feel free to re-open it if the problem persists on newer OS/Arduino IDE versions.
