### ISSUE TITLE
[WEB] Please, remove Yun shield from Arduino/Genuino Products page

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#5171]
There's no link to buy it. I asked to support@arduino.cc about that question and they told me that this product isn't available and there is not ETA. I think it's very confusing and frustrating to see a "ghost" product which can't be bought anywhere, so I suggest this action while this situation isn't resolved. Thanks

**Comment by jantje** [comment]
And what for the people who have one?

**Comment by q2dg** [comment]
Well, if it is a retired product, its page should be go to https://www.arduino.cc/en/Main/Products#retired
If it is a product is expected to be on sale in a future, its rectangle should be painted as "Coming next" instead of yellowish-orange. It's easy.

**Comment by jantje** [comment]
O I missed the web part. Sorry

**Comment by akash73** [comment]
Back on product line
https://www.arduino.cc/en/Main/Products
