### ISSUE TITLE
Arduino 1.6.10 subfolder error

### ISSUE THREAD

**Issue by MagoKimbra** [arduino/Arduino#5176]
I have module in subfolder, until the 1.6.9 version it could easily include files in subfolder
example #include "module / macros.h"
Now with the new 1.6.10 version of error that can not find the file.
Why?
And 'anything changed in the inclusions?

**Comment by per1234** [comment]
You now need to move it to the `src` subfolder of your sketch folder and change the code to:
```arduino
#include "src/module/macros.h"
```
This is the source of the change: https://github.com/arduino/arduino-builder/pull/148

**Comment by matthijskooijman** [comment]
Exactly, so I'm closing this commit. @cmaglie, this should be made more prominent in the changelog, I think.

**Comment by MagoKimbra** [comment]
Ok.. I change name subfolder "module" in "src" and now function!!! Thank's
