### ISSUE TITLE
LcdProgressBar lib

### ISSUE THREAD

**Issue by wloche** [arduino/Arduino#5177]
Hello,

Just pushed a lib: **LcdProgressBar**.
_LcdProgressBar_ is an Arduino library for displaying a progress bar in LCD display.

GitHub repos: <https://github.com/wloche/LcdProgressBar.git>

Hope it will be useful for somebody else.

Best Regards,
Wilfried

**Comment by agdl** [comment]
Done thank you!

**Comment by wloche** [comment]
Thx a lot! Just requested a second one :smile:
