### ISSUE TITLE
[Library Manager] Request to add CheapStepper library to library manager

### ISSUE THREAD

**Issue by tyhenry** [arduino/Arduino#5181]
I've created a library specifically for the 28BYJ-48 stepper motor with ULN2003 driver board.  It's a cheap and readily available stepper, and this library allows you to perform very fine-grained moves, with 4096 steps per rotation.  The library supports blocking and non-blocking moves, direct micro-step control, and comes with 3 example sketches:

[https://github.com/tyhenry/CheapStepper](https://github.com/tyhenry/CheapStepper)

Thanks!

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by tyhenry** [comment]
Hi - thanks for the note.
I've now tagged the repo with release v0.2

**Comment by agdl** [comment]
Done thank you!
