### ISSUE TITLE
[website]Troubleshooting page gives wrong instructions for verbose output during upload

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5194]
From https://www.arduino.cc/en/guide/troubleshooting#upload:
> The messages displayed when you try to upload with verbose output enabled. To do this, hold down the shift key while clicking on the upload button in the toolbar. 

That causes **Upload Using Programmer**, not verbose output. It should be changed to:
> The messages displayed when you try to upload with verbose output enabled. To enable verbose output check the box next to **File > Preferences > Show verbose output during: > upload**. Use code tags(</> button on the toolbar) to post the output to the forum so that it will be correctly formatted.

Originally reported at: http://forum.arduino.cc/index.php?topic=415993.msg2864938#msg2864938

EDIT: another case of a user being confused by this: http://forum.arduino.cc/index.php?topic=418304.msg2880624#msg2880624

**Comment by akash73** [comment]
Fixed and updated page: https://www.arduino.cc/en/guide/troubleshooting#upload:

thanks @per1234 for pointing out.
