### ISSUE TITLE
LcdProgressBarDouble lib

### ISSUE THREAD

**Issue by wloche** [arduino/Arduino#5196]
Hello,

Just pushed a lib: **LcdProgressBarDouble**.
_LcdProgressBar_ is an Arduino library for displaying a 2 progress bars in a single row in LCD display.

GitHub repos: https://github.com/wloche/LcdProgressBarDouble.git

Hope it will be useful for somebody else.

Best Regards,
Wilfried

**Comment by agdl** [comment]
Done thank you!
