### ISSUE TITLE
Arduino101 schematic is a cartoon?

### ISSUE THREAD

**Issue by mmolter** [arduino/Arduino#5198]
This [schematic](https://www.arduino.cc/en/uploads/Main/Arduino101-REV4Schematic.pdf) is what the [Arduino101 Page](https://www.arduino.cc/en/Main/ArduinoBoard101) links to. It isn't actually a schematic? Is this a placeholder that got forgotten?

**Comment by mmolter** [comment]
I guess I didn't see the subsequent pages, but the first page still seems like placeholder.

**Comment by facchinm** [comment]
Hi @mmolter ,
you are right, it looks like a placeholder but the next pages are indeed the correct schematic.
