### ISSUE TITLE
www.arduino.cc/en/Reference/Int add: Arduino Zero

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#5200]
Change:
On the Arduino Due, an int stores a 32-bit (4-byte) value
to
On the Arduino Due and Zero, an int stores a 32-bit (4-byte) value

**Comment by q2dg** [comment]
Well...I remember this https://github.com/arduino/Arduino/issues/4525 (and this https://github.com/arduino/Arduino/issues/3801)

**Comment by cousteaulecommandant** [comment]
...And while we're at it, fix the signed overflow thing (#4511) (either remove that part from the documentation or make Arduino actually do what the documentation says)

**Comment by cmaglie** [comment]
Actually the page says:

> On the Arduino Due and SAMD based boards (like MKR1000 and Zero),

I don't know if there the page has been edited in the meantime.

**Comment by avandalen** [comment]
Dear Cristian

I will help you but I don’t know which article you refer?

Albert
