### ISSUE TITLE
sorry - this program has been built without plugin support 1.6.10

### ISSUE THREAD

**Issue by iplayfast** [arduino/Arduino#5207]
Compiling Blink on 1.6.9 gives library warnings below (included for completeness) but otherwise works. Uploads and runs.

On Arduino 1.6.10 I get the sorry error. 

Arduino: 1.6.10 (Linux), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

WARNING: Category '' in library EEPROM is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library SoftwareSerial is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library TimedServo is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library Wire is not valid. Setting to 'Uncategorized'
sorry - this program has been built without plugin support
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
verbose shows more warnings but otherwise the same.

**Comment by facchinm** [comment]
Solved by of #5199 , the updated IDE will be available really soon. Sorry for the inconvenience
