### ISSUE TITLE
[WEB] Link to AtmelStudio is dead

### ISSUE THREAD

**Issue by mjbohn** [arduino/Arduino#5220]
The link to Atmel Studion under [http://playground.arduino.cc/Main/DevelopmentTools](http://playground.arduino.cc/Main/DevelopmentTools) is dead.

New link to Atmel Studio 7 is 
[http://www.atmel.com/tools/ATMELSTUDIO.aspx](http://www.atmel.com/tools/ATMELSTUDIO.aspx)

**Comment by per1234** [comment]
The Arduino Playground is a publicly editable wiki. The community is responsible for maintaining the content, not the Arduino developers. I have updated the dead link on that page.

**Comment by matthijskooijman** [comment]
Thanks!
