### ISSUE TITLE
[DOC] https://www.arduino.cc/en/Reference/CurieIMUreadTemperature Wrong formula

### ISSUE THREAD

**Issue by GregorioW** [arduino/Arduino#5225]
In the [CurieIMU.readTemperature() reference](https://www.arduino.cc/en/Reference/CurieIMUreadTemperature) the conversion example is wrong.
Instead of
Celsius=(raw/32767.0)+23
it should be
`tempCelsius = rawTemperature / 512.0 + 23.0;`
(see [BMI60.cpp:2272](https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieIMU/src/BMI160.cpp#L2272))

**Comment by agdl** [comment]
Hi, I'm sorry but this issue should be open here 

https://github.com/TheThingsNetwork/arduino-library.git

Please do it :)

**Comment by agdl** [comment]
Sorry there was a wrong link! My fault :)

**Comment by GregorioW** [comment]
Thanks for redirecting. I’ve already opened it over there :)

**Comment by agdl** [comment]
Nice! Thank you!
