### ISSUE TITLE
New library: Arduino-TCM2

### ISSUE THREAD

**Issue by oxullo** [arduino/Arduino#5238]
A library for the E-Ink timing controller MPico TCM2 and 4.41" Pervasive Displays panels

https://github.com/oxullo/Arduino-TCM2

**Comment by cmaglie** [comment]
I've added the library, BTW the tag 1.0.1 is pointing to an old library.properties (with `version=1.0.0` in it).

https://github.com/oxullo/Arduino-TCM2/blob/1.0.1/library.properties

to fix this:

- remove the current tag 1.0.1
- tag again the master branch with 1.0.1

once done the version 1.0.1 will appear automatically in about 1 hour

**Comment by oxullo** [comment]
@cmaglie thanks, it's done.
