### ISSUE TITLE
Problem with hostnames that contain underscores when Using ArduinoOTA

### ISSUE THREAD

**Issue by mhmayyan** [arduino/Arduino#5240]
Hello all,

I noticed a small problem that took me a night and day to figure out.

When I use '_' in the setHostname like below
       ArduinoOTA.setHostname(XXX_YYY);
Then Arduino IDE doesn't show the device in the " Tools > Port " drop down list.

When I change it to 
       ArduinoOTA.setHostname(XXX-YYY);
Then it works.

I think this problem is related to the Arduino IDE because when I use "XXX-YYY" as a host name of ESP8266 then I can see the host name in the "Tools > Port" drop down list. After that if I change the host name to something with Underscore "_" like "XXX_YYY" then after uploading the new sketch and if I did not restart the Arduino IDE I still can upload sketches using the old host name which is "XXX-YYY". However, the new host name has changed but has the same IP address. Once I restart the Arduino IDE then I cannot see the new host name in the "Tools > Port" drop down list. 

When I change the host name again to something without Underscore and upload the sketch using USB-Serial port and then I can see the new host name in the Port list.

Thanks,

**Comment by per1234** [comment]
Are you referring to the [esp8266 core](https://github.com/esp8266/Arduino)'s ArduinoOTA library(https://github.com/esp8266/Arduino/tree/master/libraries/ArduinoOTA)?

**Comment by mhmayyan** [comment]
@per1234 Yes I am referring to the esp8266 core's ArduinoOTA library(https://github.com/esp8266/Arduino/tree/master/libraries/ArduinoOTA).

**Comment by sandeepmistry** [comment]
Closing as it's not related to this repo. I would suggest opening it here: https://github.com/esp8266/Arduino/issues

**Comment by mhmayyan** [comment]
Ir is NOT a library problem. It is Arduino IDE problem.

**Comment by sandeepmistry** [comment]
This might be related to https://github.com/jmdns/jmdns/issues/78.

**Comment by oqibidipo** [comment]
An underscore is not a valid character in a host name.

[Wikipedia: Hostname §Restrictions on valid host names](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names)
