### ISSUE TITLE
Kernel Panic while uploading via native usb into M0

### ISSUE THREAD

**Issue by jleed** [arduino/Arduino#5242]
If I uploading after double press restart its going well, but while I using native usb to upload sketch I getting kernel panic every time.

[kp.txt](https://github.com/arduino/Arduino/files/416481/kp.txt)

**Comment by q2dg** [comment]
Sorry but M0 is a product from "the other guys" (http://www.arduino.org). You should ask for support there.

**Comment by sandeepmistry** [comment]
Closing, as mentioned by @q2dg above the M0 is not an arduino.cc product.
