### ISSUE TITLE
Wrong text and/or wrong baud rate in IDE serial monitor

### ISSUE THREAD

**Issue by MagnusKo** [arduino/Arduino#5246]
Linux,  Arduino IDE 1.6.10:

In the Serial monitor where you choose baud rates it says 74480 baud but should be 76800 (38400*2) ?
Is it just a typo or is it wrong baud rate to?

**Comment by JamesNewton** [comment]
https://github.com/arduino/Arduino/pull/3389

**Comment by cmaglie** [comment]
74480 it's the correct value, it's a "weird" baudrate used to debug ESP8266 bootloader.
