### ISSUE TITLE
Website links appear to bypass Create ToS

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#5255]
Some of the links on this page appear to allow accessing create.arduino.cc, even when I have not clicked "AGREE" to the Terms & Conditions.

https://blog.arduino.cc/2016/05/20/arduino-create-is-a-one-stop-shop-for-makers/

**Comment by 00alis** [comment]
Hi! thanks for your report. Yes this is correct, you don't need to accept the Terms and Conditions to use Project Hub, Cloud or look at public code (e.g. https://create.arduino.cc/editor/00alis/99661645-5645-41fe-9c8d-c25e4827fc87/preview).

You need to accept the Terms and Conditions just to use the actual Arduino Web Editor app.
What links are you referring to exactly?
