### ISSUE TITLE
Arduino IDE won't boot

### ISSUE THREAD

**Issue by dimitris7s** [arduino/Arduino#5257]
When I try opening the arduino.exe, it doesn't open. On the other hand the arduino_debug.exe seems to work fine. I have windows 7/64 and I tried arduino 1.6.7, 1.6.10 and 1.6.12 . I am new using the arduino so it would be nice if you could help me. thank you in advance

**Comment by mattpackwood** [comment]
Same issue here, both Mac and PC....

**Comment by per1234** [comment]
I'm going to close this under the assumption the issue was likely fixed in the last 5 years. If not, please comment here with any additional information that could enable an investigation and I'll reopen.
