### ISSUE TITLE
UsbMemory tutorial link broken

### ISSUE THREAD

**Issue by beaubeautastic** [arduino/Arduino#5263]
This is on http://playground.arduino.cc/Main/UsbMemory
The link to the commands is broken and I see one of those annoying ad domains when I click on it. I'm not sure if you guys monitor playground.arduino.cc but if it is, heres what I found.

**Comment by per1234** [comment]
The Arduino Playground is a wiki, anyone can edit it. Its maintenance is the responsibility of the Arduino community, not the developers. I have fixed all the broken links on that page.

**Comment by sandeepmistry** [comment]
@per1234 thank you for fixing the broken links!
