### ISSUE TITLE
[Library Manager]: Update CoAP Simple Library to in Library Manager

### ISSUE THREAD

**Issue by hirotakaster** [arduino/Arduino#5265]
Hi, 
This CoAP library for Arduino update 1.3.5 to 1.3.6(just bug fiexed).
https://github.com/hirotakaster/CoAP-simple-library
Thanks!

**Comment by per1234** [comment]
Check Library Manager. 1.3.6 of your library is already in there. New releases/tags should always be automatically added within an hour.

**Comment by hirotakaster** [comment]
oh, thank you!!
