### ISSUE TITLE
[Library Manager] Twitter client library

### ISSUE THREAD

**Issue by NeoCat** [arduino/Arduino#5270]
Please add my Twitter client library to send tweets via Ethernet:
    https://github.com/NeoCat/Arduno-Twitter-library

**Comment by per1234** [comment]
You need to make a 1.2.0 release or tag so that Library Manager will pick up your library once it's added. For more information see https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by NeoCat** [comment]
Added the tag '1.3.0' to the repository (correct version was 1.3.0 -- now it is fixed both in tag and library.properties).
Thanks!

**Comment by agdl** [comment]
Done thank you!
