### ISSUE TITLE
[DOC] https://www.arduino.cc/en/Reference/SPI

### ISSUE THREAD

**Issue by olikraus** [arduino/Arduino#5273]
The table about the SPI Modes is wrong for modes 2 and 3. Additionally i suggest to add a column on the clock edge for the data capture (takeover) of the client device. 

Existing (wrong) table:

| Mode	| Clock Polarity (CPOL)	| Clock Phase (CPHA)	| Output Edge  | 
|---|---|---|---|---|
| SPI_MODE0	| 0	| 0	| Falling |
| SPI_MODE1	| 0	| 1	| Rising |
| SPI_MODE2	| 1	| 0	| Falling |
| SPI_MODE3	| 1	| 1	| Rising |

I suggest to replace the table by this (modified cell content in bold):

| Mode	| Clock Polarity (CPOL)	| Clock Phase (CPHA)	| Output Edge  | Data Capture | 
|---|---|---|---|---|
| SPI_MODE0	| 0	| 0	| Falling |  Rising | 
| SPI_MODE1	| 0	| 1	| Rising |  Falling | 
| SPI_MODE2	| 1	| 0	| **Rising** | Falling  | 
| SPI_MODE3	| 1	| 1	| **Falling** | Rising | 

References:
Forum discussion:
http://forum.arduino.cc/index.php?topic=419660.0

Existing issues related to this topic:
olikraus/u8g2#52
esp8266/Arduino#2416

**Comment by agdl** [comment]
Done thank you!

**Comment by olikraus** [comment]
Thanks
Unfortunately there is a small spelling mistake on the web page (marked in bold below)

| Mode	| Clock Polarity (CPOL)	| Clock Phase (CPHA)	| Output Edge  | Data Capture | 
|---|---|---|---|---|
| SPI_MODE0	| 0	| 0	| Falling |  Rising | 
| SPI_MODE1	| 0	| 1	| Rising |  Falling | 
| SPI_MODE2	| 1	| 0	| Rising | **Flling**  | 
| SPI_MODE3	| 1	| 1	| Falling | Rising |

**Comment by agdl** [comment]
Fixed sorry for that
