### ISSUE TITLE
how to store pir sensor output data into database without Ethernet shield?

### ISSUE THREAD

**Issue by shanthan25** [arduino/Arduino#5274]
how to store pir sensor output into database without ethernet shield? my task is count no of passengers inside a bus.and display output in a web page.i got output from pir sensor.but i am unable to store data into database while serial connection arduino with laptop.
![dsc_0006](https://cloud.githubusercontent.com/assets/20897352/17838491/84466d54-67ec-11e6-917c-b32236e3565a.JPG)

**Comment by q2dg** [comment]
You should ask in users forum (http://forum.arduino.cc). Here isn't the right place, sorry
