### ISSUE TITLE
boolean invert bug

### ISSUE THREAD

**Issue by joahend** [arduino/Arduino#5279]
boolean blink=false;

void loop() {
    blink=!blink;
    delay(200);
    Serial.println(blink); //allways only false 
}

i cant say what part of rest of code affect this routine

work fine until version 1.6.9
doesn't work on versions 1.6.10 and 1.6.11

tested with nano

**Comment by matthijskooijman** [comment]
> i cant say what part of rest of code affect this routine

Please try reducing the code further, removing all other code, and see if it still breaks. If so, please post the *full* sketch that shows the behaviour. Also, please be more specific about what the resulting behaviour is (your comment says "always only false", but that line should, AFAICS, always print 0/1, not true/false anyway...).

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity.
