### ISSUE TITLE
logical expression bug !

### ISSUE THREAD

**Issue by KORBANK-T** [arduino/Arduino#5288]
The logical expressions do not work correctly. 

Tested at arduino one, mini and duemilanove. 

This is a simple code. The results is 12, what can not happend.

```
#define DL_KOL 10
void setup(){

  
  delay(10000);
  Serial.begin(115200);

}

void loop(){
  
byte a=1;  
byte zaj_kol_nad[DL_KOL];  
byte b=1;
   
int i, gdzie=DL_KOL;

for(i=0;i<DL_KOL;i++) zaj_kol_nad[i]=1;

i=0;
while((zaj_kol_nad[i]!=0) && (i<DL_KOL)) i++;
  
  Serial.print(" i="); 
  Serial.print(i);
  delay(10000);
     
}
```

**Comment by facchinm** [comment]
Hi @KORBANK-T ,
your code contains a subtle error; the condition `while((zaj_kol_nad[i]!=0) && (i<DL_KOL))` is evaluated in left-to-right order. So when `i==10`  zaj_kol_nad[10] is accessed (every board/compiler combination holds something different in that position, so your sketch runs correctly on some boards and reports strange results on others).
Reversing the condition makes it work as expected.
