### ISSUE TITLE
[Library Manager] Please add these libraries

### ISSUE THREAD

**Issue by ryantm** [arduino/Arduino#5298]
Hi.

We are still working on getting all of our libraries into the library manager! Can you please add the following libraries to the library manager?

https://github.com/pololu/drv8835-motor-shield
https://github.com/pololu/dual-mc33926-motor-shield
https://github.com/pololu/usb-pause-arduino
https://github.com/pololu/pushbutton-arduino

Thanks,
Ryan

**Comment by agdl** [comment]
Done thank you!
