### ISSUE TITLE
[Library Manager] Please add these libraries

### ISSUE THREAD

**Issue by MPParsley** [arduino/Arduino#5304]
https://github.com/LowPowerLab/LowPower
https://github.com/LowPowerLab/RFM69
https://github.com/LowPowerLab/SPIFlash

**Comment by per1234** [comment]
Please see https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ. You still need to do some things to your libraries before they can be added to Library Manager

**Comment by agdl** [comment]
I'm closing this for lack of feedback. Reopen it if needed

**Comment by Chris--A** [comment]
There is another library already using the name SPIFlash as well.
