### ISSUE TITLE
Arduino IDE Crash

### ISSUE THREAD

**Issue by HMStith** [arduino/Arduino#5307]
When I replace the Arduino IDE Example Files with my own Arduino will not start. Is there any way to get around this?

**Comment by facchinm** [comment]
Hi @HMStith , 
could you please expand? We need to know 
1 - what you did exactly
2 - your setup (operative system, IDE version, boards connected)

Thanks

**Comment by HMStith** [comment]
I was changing the Arduino Example Files in attempt to be my own but the IDE would not start afterwards.

**Comment by facchinm** [comment]
Sorry but I can't understand what you are doing. Which operating system are you using? Which IDE version? Can you send the output of "arduino-debug.exe" (if you are on Windows) ? Otherwise I must close the issue as invalid...

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of feedback.
