### ISSUE TITLE
Forum code window incorrect after quick edit

### ISSUE THREAD

**Issue by Grumpy-Mike** [arduino/Arduino#5314]
When a code window has insufficient lines to generate a scroll bar the window is made smaller to fit the text. However after a "quick edit" all windows default to the standard size as if it had a scroll bar and have lots of blank white space at the bottom. The work around is to just open the modify post window, and then save it again. But this behavior is very annoying.

**Comment by per1234** [comment]
Moved to https://github.com/arduino/forum-issues/issues/249
