### ISSUE TITLE
https://www.arduino.cc/en/Tutorial/LibraryExamples doesn't show all tutorial pages

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#5317]
Specifically, I was looking for the Curie's BLE tutorials which are only listed at bottom of https://www.arduino.cc/en/Reference/CurieBLE . I think these tutorials should be placed (also) in LibraryExamples page as a central entry point, as well as CurieIMU, CurieTimer etc examples.

**Comment by agdl** [comment]
@00alis

**Comment by q2dg** [comment]
Tutorials listed in https://www.arduino.cc/en/Guide/ArduinoZero#toc6 aren't in LibraryExamples neither.

**Comment by 00alis** [comment]
Adding @SimonePDA and @akash73 who are taking care of the documentation pages.
@q2dg thank you so much for reporting the issue!

**Comment by q2dg** [comment]
Well, still waiting.
Meanwhile,  https://www.arduino.cc/en/Guide/ArduinoZero#toc6 has become  https://www.arduino.cc/en/Guide/ArduinoZero#toc7

**Comment by akash73** [comment]
hello @q2dg ,
thanks for bring up again.
we decided to keep the two types of example in different areas: the BLE IMU and others come with the core and is not a separate library.
in https://www.arduino.cc/en/Tutorial/LibraryExamples we list all the examples that you'll find by downloading the library.
Other examples fall in proper reference page like : 

https://www.arduino.cc/en/Reference/CurieIMU
https://www.arduino.cc/en/Reference/CurieBLE 
https://www.arduino.cc/en/Reference/CurieTimerOne

**Comment by per1234** [comment]
It sounds like this issue is a wontfix and @q2dg gave a thumbs up so I'm going to close it. Feel free to re-open (or request a re-open) if I'm wrong about this.
