### ISSUE TITLE
[Library manager] Buffered Streams library

### ISSUE THREAD

**Issue by paulo-raca** [arduino/Arduino#5320]
Hello, please add this library to the library manager:
https://github.com/paulo-raca/ArduinoBufferedStreams

It provides implementations of Arduino's Stream to emulate a pair of connected Streams or a Loopback Stream.

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by paulo-raca** [comment]
My apologies!
The tag has been created now

**Comment by agdl** [comment]
Done thank you!
