### ISSUE TITLE
[Library Manager] Please add this IR Position library

### ISSUE THREAD

**Issue by jimaobian** [arduino/Arduino#5321]
Hi,
Could you please add this library:
[https://github.com/DFRobot/DFRobotIRPosition](https://github.com/DFRobot/DFRobotIRPosition)

Thank you for your efforts!

Regards,
Angelo

**Comment by agdl** [comment]
Hi, look @ this
https://github.com/DFRobot/DFRobotIRPosition/blob/1.0.1/library.properties

You have 1.0.1 tag but properties says 1.0

Fix this please!

**Comment by jimaobian** [comment]
Updated! Sorry for the late.

Thank you for your time

**Comment by agdl** [comment]
Done thank you!
