### ISSUE TITLE
Client Avaiable ethernet shield

### ISSUE THREAD

**Issue by birotx** [arduino/Arduino#5331]
https://www.arduino.cc/en/Reference/ClientAvailable

I think this phrase is ambiguous/wrong: 

> that is, the amount of data that has been written to the client by the server it is connected to

I suppose the client is the browser and the server is the arduino web server. This function basically selects the parameters after domain (www.domain.com/THINGS, in this case THINGS). That means the client is sending data to the server not the other way around.

So I think the proper definition is:

>  that is, the amount of data that has been written by the client to the server it is connected to

**Comment by agdl** [comment]
Done thank you!
