### ISSUE TITLE
[Library Manager]: Please add BRZO I2C library

### ISSUE THREAD

**Issue by squix78** [arduino/Arduino#5333]
Hi 

Can you please add this library to the library manager?
https://github.com/pasko-zh/brzo_i2c/blob/master/library.properties

Thank you
Daniel

**Comment by agdl** [comment]
@squix78 can you please change the name in the library.properties in something shorter? i.e Brzo I2C

**Comment by pasko-zh** [comment]
I have merged the pull request from @squix78. 
@agdl is now everything fine, or do we need to change more?

**Comment by agdl** [comment]
Done thank you!
