### ISSUE TITLE
[Library Manager]: Please add controleForno

### ISSUE THREAD

**Issue by Atzingen** [arduino/Arduino#5337]
hello, 

Can you please add this library to the library manager?

https://github.com/Atzingen/controleForno

Thankyou

**Comment by agdl** [comment]
Look at this:
https://github.com/Atzingen/controleForno/blob/v2.0.0/library.properties

You have a library.properties with a version different from the tag

**Comment by Atzingen** [comment]
Sorry about that, now it should be ok

**Comment by agdl** [comment]
Done thank you!

**Comment by Atzingen** [comment]
Hello again, 
The library was supposed to be in http://downloads.arduino.cc/libraries/library_index.json ?
I'm not able to find it.
Thanks in advance
