### ISSUE TITLE
Toolbar does not go full width on 4K

### ISSUE THREAD

**Issue by moxy-bc** [arduino/Arduino#5341]
The Arduino toolbar does not display full width when maximized on a 4k screen.    See this screen-shot.

![arduino_4k_toolbar](https://cloud.githubusercontent.com/assets/1828944/18228236/6c32086a-71f9-11e6-8d9d-29418778a1ce.png)

**Comment by facchinm** [comment]
_@TheBetaFruit commented:_

> When using a 21:9 Ultra-Wide Monitor (e.g. the popular LG 34UM95, resolution = 3440x1440px), the upper turquise menu bar of the Arduino IDE is too short in full-screen mode and therefore centered with two ugly grey areas besides it.
> 
> It would be nice to fix this by making sure the menu bar stays left-aligned while expanding the turquise area to the right, fitting any screen width.
>

**Comment by cmaglie** [comment]
Fix will be available on the next release 1.8.4
