### ISSUE TITLE
Website Joke

### ISSUE THREAD

**Issue by GlennKessler** [arduino/Arduino#5343]
Every time I try to sign in I get so much crap from your system I n ever get in. Even I have another user name no emails ever come to activate or change passwords. Really sick of it.

**Comment by matthijskooijman** [comment]
Can you be more specific about what you're trying, what you expect to happen and what happens? Your report is too vague to be useful now, I think.

**Comment by connornishijima** [comment]
This joke doesn't have a punchline. I've opened an issue so you can add one.

**Comment by per1234** [comment]
Closing due to lack of a response to the request for more information.
