### ISSUE TITLE
ArduinoIDE and ESP8266

### ISSUE THREAD

**Issue by iliemv** [arduino/Arduino#5347]
Mihalcea Elijah returns with a problem related to the Arduino IDE.
Any version of the Arduino IDE does not recognize plaques type ESP8266 install even if I set my preferences " http://arduino.esp8266.com/st.../package_esp8266com_index.json " . How can rezovza ? use W10

**Comment by facchinm** [comment]
The correct link to add to "Preferences" field is http://esp8266.github.io/Arduino/versions/2.3.0/

Thanks
