### ISSUE TITLE
Library manager descriptions unreadable

### ISSUE THREAD

**Issue by FabianInostroza** [arduino/Arduino#5353]
When using the library manager and a dark desktop theme the descriptions of the libraries are unreadable. It seems like somebody forgot to set the font color.

See screenshot
![screenshot](https://i.imgsafe.org/0770f126d1.png)

PD: I'm using numix gtk theme

**Comment by q2dg** [comment]
"Liberías" instead of "Librerías"?? I see a typo there, too.

**Comment by FabianInostroza** [comment]
@q2dg You are right!, I didn't notice that typo.

**Comment by per1234** [comment]
> "Liberías" instead of "Librerías"?? I see a typo there, too.

Looks like there are two instances of that:
https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/i18n/Resources_es.po
and
https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/i18n/Resources_es.po

**Comment by sdale28** [comment]
Hi there. I fixed the spelling issues in this pull request: https://github.com/arduino/Arduino/pull/5357
Though I'm not sure how to do the color scheme issue. Cheers!

**Comment by cousteaulecommandant** [comment]
...plus I'd rather call them "bibliotecas" (although "librerías" seems to be accepted too).

**Comment by sdale28** [comment]
I agree it seems like "bibliotecas" is more correct, but I'm not a native speaker.

**Comment by FabianInostroza** [comment]
I'm a native spanish speaker (chilean) and I think that "librerías" is more used (at least in Chile).

**Comment by q2dg** [comment]
Well, I agree...I'm spanish speaker (from Spain) and although "bibliotecas" would be the "correct" translation, "librerías" is much more used instead.

**Comment by FabianInostroza** [comment]
The same problem exists in the board manager
