### ISSUE TITLE
missing terminating " character

### ISSUE THREAD

**Issue by EagleSmith** [arduino/Arduino#5354]
my code:
`const char HTTP_String [] PROGMEM ="<html>
<title></title>
<html>";
`

sketch_sep08c:13: error: expected ',' or ';' at end of input

exit status 1
missing terminating " character

**Comment by facchinm** [comment]
Hi @EagleSmith , that line is ok if you copy/paste it into your sketch, but it contains stray characters (like \n or \r).
Gmail shows it like this 
![2016-09-08-095247_1366x768_scrot](https://cloud.githubusercontent.com/assets/8843437/18341418/30ad0380-75aa-11e6-9e25-a7f3ddf90299.png)
which is obviously wrong (a multiline separator `\` is needed). Rewrite it by hand in a single line and you'll be ok :smile:
