### ISSUE TITLE
[Library Manager] Please add this library, Exode.  

### ISSUE THREAD

**Issue by sne3ks** [arduino/Arduino#5365]
Exode is a Python library for communication between Arduino microcontroller boards and a connected computer. Once Arduino board connected to a device (computer, Rasberry Pi, smartphone ..) using a serial IO (usb/bluetooth), it's possible to have interraction between the computer and the board.  

https://github.com/sne3ks/ExodeCore

**Comment by agdl** [comment]
Done thank you!
