### ISSUE TITLE
[Library Manager] Update TheThingsNetwork library repo

### ISSUE THREAD

**Issue by FokkeZB** [arduino/Arduino#5367]
We've renamed the repo for the TheThingsNetwork library added in #5266, to align it with libraries we have for other platforms. Please update the listing to use the new repo name:

* Old: https://github.com/thethingsnetwork/arduino-library
* New: https://github.com/TheThingsNetwork/arduino-device-lib

**Comment by agdl** [comment]
Done thank you!
