### ISSUE TITLE
Only upper case S files are selected by Arduino IDE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#540]
This is [Issue 540](http://code.google.com/p/arduino/issues/detail?id=540) moved from a Google Code project.
Added by 2011-05-11T04:39:53.000Z by [rick.rickanderson](http://code.google.com/u/rick.rickanderson/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Only upper case S files are selected by Arduino IDE

$grep -n '\"S\"' Compiler.java

108:               findFilesInPath(buildPath, "S", false),
123:               findFilesInFolder(libraryFolder, "S", false),
131:               findFilesInFolder(utilityFolder, "S", false),
146:              findFilesInPath(corePath, "S", true),

Comparison operation:
  if (file.getName().endsWith("." + extension))
       files.add(file);

**Comment by ffissore** [comment]
Indeed and it's right
