### ISSUE TITLE
http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino6-i686-mingw32.zip is missing

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5400]
Updating to Arduino AVR Boards 1.6.14 with Windows fails:
```
Error downloading http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino6-i686-mingw32.zip
```
http://downloads.arduino.cc/tools/avrdude-6.3.0-arduino6-i686-mingw32.zip gives a 404 not found error.

The other OS versions of avrdude 6.3.0-arduino6 can all be downloaded.

EDIT: originally reported at http://forum.arduino.cc/index.php?topic=425310

**Comment by facchinm** [comment]
Fixed, thank you VERY much for reporting
