### ISSUE TITLE
https://www.arduino.cc/en/Reference/Libraries USBHost seems to be in the wrong spot

### ISSUE THREAD

**Issue by Manfet** [arduino/Arduino#5403]
https://github.com/arduino-libraries/USBHost/commit/a0f9e00adbe7adbc8d6d70ff137a6dca701f4f53
USBHost git says it is DUE only
Component: Documentation

**Comment by Manfet** [comment]
Seems like I cannot label this...

**Comment by sandeepmistry** [comment]
Hi @Manfet,

The Zero/MKR1000 version of the USBHost library is bundled with the SAMD core: https://github.com/arduino/ArduinoCore-samd/tree/master/libraries/USBHost
