### ISSUE TITLE
How to change speed in motors?

### ISSUE THREAD

**Issue by davidhaw** [arduino/Arduino#5406]
How can you change the speed with motors hooked up. I got it to work on full speed, but how do I change that because my motors are really fast.

**Comment by Alienwaren** [comment]
Use PWM, so `analogWrite(pin, value)`. Make sure that you are using a H-Bridge IC like L293D or so.

**Comment by davidhaw** [comment]
I'm using a Adafruit motor driver

**Comment by davidhaw** [comment]
it has worked for me. Thanks!
