### ISSUE TITLE
Document limits to Serial.print() asynchronicity and transmit buffer

### ISSUE THREAD

**Issue by beikeland** [arduino/Arduino#5408]
https://www.arduino.cc/reference/en/language/functions/communication/serial/print/ says "As of version 1.0, serial transmission is asynchronous; Serial.print() will return before any characters are transmitted."

I think it could be beneficial to update this to include that it is only non-blocking until you exceed the transmit buffer, and the current size of the buffer, or a link to where the buffer size is defined to avoid potentially stale information both on the docs, and users finding stale information when turning to google to search for the answers.

**Comment by q2dg** [comment]
I agree but maybe a little short explanation about what a buffer is should be grateful for newbies.

**Comment by aknrdureegaesr** [comment]
Where is the source code for https://www.arduino.cc/en/Serial/Print , so one can make a pull request to fix this?

**Comment by matthijskooijman** [comment]
@aknrdureegaesr 
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/HardwareSerial.h
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Print.h
(and corresponding cpp files)

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/reference-en/pull/520
