### ISSUE TITLE
New Library EasyWebServer

### ISSUE THREAD

**Issue by llelundberg** [arduino/Arduino#5409]
Please add 
https://github.com/llelundberg/EasyWebServer/releases/tag/1.0

**Comment by agdl** [comment]
Check your tag please https://github.com/llelundberg/EasyWebServer/tree/1.0

**Comment by llelundberg** [comment]
Sorry for that, still learning Gihub. I have a new proper release:
https://github.com/llelundberg/EasyWebServer/tree/v1.1

**Comment by agdl** [comment]
Done thank you!
