### ISSUE TITLE
Can not save sketches on non admin Windows user account

### ISSUE THREAD

**Issue by j54n1n** [arduino/Arduino#5423]
Hello,

With the latest version of the Arduino IDE v1.6.12 I get the following message when I try to save (Ctrl+Shift+S) a sketch with its default name. The error message says something like that the sketch can not be saved in the current sketchbook since it already exists, but that is not the case. Afterwards if I try to save the sketch again I get redirected in the Save As window to the TEMP folder of the current user.
In particular in my case I installed the Arduino IDE from the ZIP file (non admin install) within the current non admin user folder.
The same issue does not happen if I use the Arduino IDE v1.6.11 ZIP file.

**Comment by sandeepmistry** [comment]
This also impacts OS X. If I create a new sketch and save, the following is shown:

![screen shot 2016-09-28 at 8 58 44 am](https://cloud.githubusercontent.com/assets/1163840/18914168/e8efbbe0-8559-11e6-81a3-e42fb261d817.png)

The sketch is not saved in my sketch book folder, but rather in `/var/folders/m9/y22yzb0d49x_kws_6jtwdphw0000gn/T/untitled617461295.tmp/sketch_sep28b/sketch_sep28b.ino`.

**Comment by cmaglie** [comment]
Thank you for the bug report!

the fix will be available on IDE 1.6.13 or next hourly build

**Comment by matthijskooijman** [comment]
@cmaglie, thanks for fixing my oopsies :-)

Fix looks good to me.
