### ISSUE TITLE
New Library - FT857d

### ISSUE THREAD

**Issue by pavelmc** [arduino/Arduino#5425]
New library contribution.

FT857d is a library to give any ham radio related Arduino project [CAT](https://www.socialhams.net/m/tutorials/view/Computer-Aided-Transceiver-for-Ham-Radio) capabilities, then you can control your project via PC like if it was a Yesu FT-857d Radio, it's simple and yet powerful.

Github address: https://github.com/pavelmc/FT857d/

An use case of this is my Arduino ARCS project here https://github.com/pavelmc/arduino-arcs/

Please add to Library manager

**Comment by cmaglie** [comment]
Done!

**Comment by pavelmc** [comment]
Thanks!
