### ISSUE TITLE
New Library: ESPectro

### ISSUE THREAD

**Issue by andriyadi** [arduino/Arduino#5426]
I made a library for users to get up fast for using ESPectro Core board with Arduino IDE. ESPectro is an ESP8266 development board as the culmination of our 1+ year experience in exploring and developing products with ESP8266 MCU.

Github address: https://github.com/andriyadi/EspX
ESPectro product detail: https://shop.makestro.com/product/espectro-core/

Please add to Library manager. Thanks!

**Comment by cmaglie** [comment]
Done!

**Comment by andriyadi** [comment]
Awesome, confirmed it's there! Thanks!
