### ISSUE TITLE
pwmWrite / analogWrite returns nothing

### ISSUE THREAD

**Issue by itzmejawad** [arduino/Arduino#5429]
HI,
I'm trying to generate PWM output on arduino UNO/NANO PWM pins. But I've tried several methods like pwmWrite or analogWrite. But it's not working for multiple pins.

Means...
{pwmWrite(9,13)} sets PWM on 9

But

If I do like the below....
{
pwmWrite(9,13);
pwmWrite(10,13);
pwmWrite(11,13);
}
This only writes PWM on 9th pin but not on 10th and 11th... 
Help me overcome this issue

**Comment by facchinm** [comment]
Hi @itzmejawad ,
on the UNO, only pins marked with the tilde `~` are PWM capable, so you can call `analogWrite` on 3,5,6,9,10,11 (see the reference [here](https://www.arduino.cc/en/Reference/AnalogWrite) ).  `pwmWrite` is not a core function and probably comes from a library.
Load the `Fade` example and check each pin functionality, then try assembling them in the way you prefer :smile:
