### ISSUE TITLE
1.6.12 Path+Sketch length error / Could not create sketch / Failed to open sketch / Only showing include files

### ISSUE THREAD

**Issue by degerrit** [arduino/Arduino#5431]
Not sure why this issue appeared (maybe I moved the Arduino sketch folder - I hadn't used my Arduino in a few months), but my Arduino IDE on Windows is now having issues with Sketches that have long path+filenames.  I created these in Arduino IDE, so previously I had no issues with this.

Other programs, i.e. Wordpad, can open the .ino files without any problems, so it's not an OS limitation.

Examples:
D:\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1.ino
105 chars - result: **opens OK**

D:\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1_Dist12_13_8s_s\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1_Dist12_13_8s_s.ino
135 chars - result: **Not OK, "Could not create sketch"**

Interestingly, the first sketch I opened after upgrading to 1.6.12 had some include files with short filenames (x10rf.h, x10rf.cpp) - the result here is NO ERROR MESSAGE, but the IDE opening only the include files, and not the .ino file.

A full downgrade back to 1.6.9 (uninstall/reinstall) fixes the issue.
---
Default path - looks OK:
-----
![arduino_ide_bugreport_longpath_05_default_path_ok](https://cloud.githubusercontent.com/assets/22508603/18995871/80275902-872e-11e6-8094-a1dfdae0bd1f.png)

Wordpad - no issue:
-----
![arduino_ide_bugreport_longpath_03_wordpad_no_issue](https://cloud.githubusercontent.com/assets/22508603/18995869/80259edc-872e-11e6-80ca-dafc3193f652.png)

The long path
-----
![arduino_ide_bugreport_longpath_01](https://cloud.githubusercontent.com/assets/22508603/18995870/802691f2-872e-11e6-97c4-6cf550e80f18.png)

Long (>128 character?) .INO sketch file that contains include files - IDE only shows the short include files, NO ERROR message is given
-----
![arduino_ide_bugreport_longpath_02_includes_load_but_not_ino_file](https://cloud.githubusercontent.com/assets/22508603/18995873/8029522a-872e-11e6-8afe-bed766617b56.png)

Short test sketch with no includes, but long path - ERROR
-----
![arduino_ide_bugreport_longpath_06_used_blink_no_includes_results_in_errormsg](https://cloud.githubusercontent.com/assets/22508603/18995874/8040eeb2-872e-11e6-8f97-ab0fa4dacb13.png)

-----
![arduino_ide_bugreport_longpath_06b_used_blink_no_includes_results_in_errormsg](https://cloud.githubusercontent.com/assets/22508603/18995875/8044b902-872e-11e6-9523-63ea48a3c243.png)

-----
![arduino_ide_bugreport_longpath_06c_used_blink_no_includes_results_in_errormsg_moved_also](https://cloud.githubusercontent.com/assets/22508603/18995868/80239326-872e-11e6-9e4f-0b30e9b756e5.png)

Same sketch, renamed / shortened path and Sketch name - opens OK
-----
![arduino_ide_bugreport_longpath_07_shortened_name_ok](https://cloud.githubusercontent.com/assets/22508603/18995872/80282bac-872e-11e6-9a57-420988e7e961.png)

**Comment by degerrit** [comment]
Updated my original bug, a downgrade to 1.6.9 via full uninstall/reinstall **resolves** the problem. 
Previously my downgrade to 1.6.9 that didn't resolve the problem involved swapping the Arduino folder for a backed-up folder, not a full uninstall/reinstall. Very strange!

**Comment by degerrit** [comment]
OK, 1.6.11 also does not have this problem. Maybe it's the editor code refactoring in 1.6.12

**Comment by cmaglie** [comment]
Thanks for the bug report.

In this case is not the full path length the problem, but only the **sketch name** length.

The sketch name is limited to 63 chars and this limit has always been there but, before 1.6.12, the check was made only on the sketch name **without the .ino extension**. After 1.6.12 this check has been changed to test the full file name (with .ino extension). So a sketch that previously fitted exactly the 63 chars limit after 1.6.12 it will suddenly became invalid because the .ino extension will made it of 64+4 -> 67.

Now I've fixed it by making the check again on the sketch name. Of course this bug affects only sketch with very long names (nearing 63 chars).

**Comment by Lizews2006** [comment]
> Not sure why this issue appeared (maybe I moved the Arduino sketch folder - I hadn't used my Arduino in a few months), but my Arduino IDE on Windows is now having issues with Sketches that have long path+filenames. I created these in Arduino IDE, so previously I had no issues with this.
> 
> Other programs, i.e. Wordpad, can open the .ino files without any problems, so it's not an OS limitation.
> 
> Examples:
> D:\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1.ino
> 105 chars - result: **opens OK**
> 
> D:\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1_Dist12_13_8s_s\Blink_undDet-D8_Water-A0_Temp-D2_X10RF-D4_LDR-A1_Dist12_13_8s_s.ino
> 135 chars - result: **Not OK, "Could not create sketch"**
> 
> Interestingly, the first sketch I opened after upgrading to 1.6.12 had some include files with short filenames (x10rf.h, x10rf.cpp) - the result here is NO ERROR MESSAGE, but the IDE opening only the include files, and not the .ino file.
> 
> ## A full downgrade back to 1.6.9 (uninstall/reinstall) fixes the issue.
> ## Default path - looks OK:
> ![arduino_ide_bugreport_longpath_05_default_path_ok](https://cloud.githubusercontent.com/assets/22508603/18995871/80275902-872e-11e6-8094-a1dfdae0bd1f.png)
> 
> ## Wordpad - no issue:
> ![arduino_ide_bugreport_longpath_03_wordpad_no_issue](https://cloud.githubusercontent.com/assets/22508603/18995869/80259edc-872e-11e6-80ca-dafc3193f652.png)
> 
> ## The long path
> ![arduino_ide_bugreport_longpath_01](https://cloud.githubusercontent.com/assets/22508603/18995870/802691f2-872e-11e6-97c4-6cf550e80f18.png)
> 
> ## Long (>128 character?) .INO sketch file that contains include files - IDE only shows the short include files, NO ERROR message is given
> ![arduino_ide_bugreport_longpath_02_includes_load_but_not_ino_file](https://cloud.githubusercontent.com/assets/22508603/18995873/8029522a-872e-11e6-8afe-bed766617b56.png)
> 
> ## Short test sketch with no includes, but long path - ERROR
> ![arduino_ide_bugreport_longpath_06_used_blink_no_includes_results_in_errormsg](https://cloud.githubusercontent.com/assets/22508603/18995874/8040eeb2-872e-11e6-8f97-ab0fa4dacb13.png)
> 
> ![arduino_ide_bugreport_longpath_06b_used_blink_no_includes_results_in_errormsg](https://cloud.githubusercontent.com/assets/22508603/18995875/8044b902-872e-11e6-9523-63ea48a3c243.png)
> 
> ![arduino_ide_bugreport_longpath_06c_used_blink_no_includes_results_in_errormsg_moved_also](https://cloud.githubusercontent.com/assets/22508603/18995868/80239326-872e-11e6-9e4f-0b30e9b756e5.png)
> 
> ## Same sketch, renamed / shortened path and Sketch name - opens OK
> ![arduino_ide_bugreport_longpath_07_shortened_name_ok](https://cloud.githubusercontent.com/assets/22508603/18995872/80282bac-872e-11e6-9a57-420988e7e961.png)

Same here. If anyone found a way, pls email me: lizews2006@gmail.com
You see, I'm actually a student and I need to finish the code but I cannot open it. The competition is in one week time, so pls help me... Thanks!

**Comment by cmaglie** [comment]
@Lizews2006 thanks for the bug report but this issue should be solved with **IDE 1.8.10**, if not please open another issue and do not comment on already closed issues.

Anyway, if you're in a hurry, you may consider renaming the `.ino` file **and the containing folder** to a shorter name for a quick workaround.
