### ISSUE TITLE
[Boards Manager] Please add official STM Nucleo boards support 

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [arduino/Arduino#5434]
Hi
STMicroelectronics have produced a Boards manager package (and cores etc) to support some of their Nucleo range of boards

The JSON package is located at

https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/master/STM32/package_stm_index.json

Currently this only supports the Nucleo STM32F103RB and Nucleo STM32L476, however more Nucleo boards will be added in the coming weeks and months.

The Stm32duino community is also working to add some none STM branded boards to this core, but these are a work in progress and have not been added to the boards manager package yet.

**Comment by facchinm** [comment]
Hi Roger,
great to hear that! Right now we can only add the link to https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls but in the future, in case we should officially support an STM32 based board, we'll surely add this core to the supported (and "bundled") ones.
Thanks again!
