### ISSUE TITLE
New Library: LIDARLite

### ISSUE THREAD

**Issue by nseverson** [arduino/Arduino#5440]
Please add the library for LIDAR-Lite v3 to the library manager: [https://github.com/garmin/LIDARLite_v3_Arduino_Library](https://github.com/garmin/LIDARLite_v3_Arduino_Library)

**Comment by agdl** [comment]
Hi, please update library.properties according to the tag

https://github.com/garmin/LIDARLite_v3_Arduino_Library/blob/v1.0.1/library.properties

**Comment by nseverson** [comment]
Updated, thanks.

**Comment by agdl** [comment]
Done thank you!
