### ISSUE TITLE
.hh and .hpp files in libraries can only be included after a .h file from that library

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5441]
Using Arduino IDE 1.6.13 Hourly Build 2016/10/03 06:51 with Windows 7 64 bit

https://github.com/arduino/Arduino/pull/3186 added support for including .hpp and .hh files from libraries.

If I have a library installed with the folder structure:

foo
|_foo.h
|_foo.hh
|_foo.hpp

With Arduino IDE 1.6.6 or newer, doing:
```arduino
#include <foo.hh>
```
or
```arduino
#include <foo.hpp>
```
causes compilation to fail:
```
fatal error: bar.hh: No such file or directory
 #include <foo.hh>
```
It will only compile if I do:
```arduino
#include <foo.h>
#include <foo.hh>
```
Using Arduino IDE 1.6.5-r5 I don't need to include the .h file.

**Comment by facchinm** [comment]
@per1234 , could you move it to `arduino-builder` repo? Thx

**Comment by per1234** [comment]
OK, I've merged with https://github.com/arduino/Arduino/issues/5442 and moved to the arduino-builder repo: https://github.com/arduino/arduino-builder/issues/181. Sorry about that, I should have realized the include stuff was arduino-builder.
