### ISSUE TITLE
Can't include .hh sketch tab

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5442]
Using Arduino IDE 1.6.13 Hourly Build 2016/10/03 06:51 with Windows 7 64 bit

@Chris--A added support for .hh and .hpp sketch files in https://github.com/arduino/Arduino/pull/3485 however if I create a sketch tab with a .hh extension and then try to include that file from the sketch:
```arduino
#include "hhtab.hh"
```
compilation fails:
```
fatal error: hhtab.hh: No such file or directory
 #include "hhtab.hh"
```
This problem doesn't occur with sketch tabs with the .hpp extension.

EDIT: originally reported at http://forum.arduino.cc/index.php?topic=427309

**Comment by facchinm** [comment]
To be merged with #5441
