### ISSUE TITLE
Recently used  file  feature does not , but  loads multiple files.  IDE 1.6.11. 

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#5447]
This very useful feature loads multiple recently used files - generally one full size window and the next one in standard window size on top of this base window. 
Loading / opening another file requires deleting at least one of these windows because the new file does not load as "top window", but is hidden bellow the full size window. 
This is aggravated by not be able to permanently remove the files from this list. 
I have seen five files in the list and closing them using "close" dos not remove them from the list .
On next IDE start they  are still on the list. 

The feature should load / display only one true recently used file ( singular) or cascade multiple files loaded so user can select the one of interest - move  as top full size window. 

Opening new file could be done similar way - put the new one in cascade as top window would work nice.

**Comment by VaclavSal** [comment]
I like to close this apparently "non issue ".
May I?

**Comment by facchinm** [comment]
Sure :smile:
No one else complained about the existing behaviour, so I believe it is ok as it is.
Reopen if needed
