### ISSUE TITLE
[website] MKR1000 product page has incorrect URL for pinout diagram

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5457]
On the MKR1000 product page https://www.arduino.cc/en/Main/ArduinoMKR1000 the "Download the pinout in PNG format" link http://edit.arduino.cc/en/uploads/Main/MKR1000_pinout.png requires authentication:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/19142661/eb207558-8b53-11e6-8ded-3d50acd7750a.png)

EDIT: it looks like the link just needs to be changed to http://arduino.cc/en/uploads/Main/MKR1000_pinout.png

**Comment by agdl** [comment]
Done thank you!
