### ISSUE TITLE
https://www.arduino.cc/en/Tutorial/WiFiRTC missing timezone handling code

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5458]
The example code at https://www.arduino.cc/en/Tutorial/WiFiRTC has the following line:
```arduino
const int GMT = 1; //change this to adapt it to your time zone
```
but `GMT` is never used in the rest of the sketch so that line has no purpose.

Originally reported at http://forum.arduino.cc/index.php?topic=417338

**Comment by agdl** [comment]
Done thank you!

**Comment by per1234** [comment]
Thanks! I didn't know about the [tutorials repository](https://github.com/arduino/tutorials). That's really nice to have! I'll make any future issues/pull requests to that repository.

**Comment by agdl** [comment]
@per1234 you are welcome :)
