### ISSUE TITLE
IDE tab as symbolic link is overwritten wit real file on "Save"

### ISSUE THREAD

**Issue by Copmic** [arduino/Arduino#5478]
setup is:
/project1/project1.ino
/project1/localinclude1.h
/project1/include2.h
/include2.h

where /project1/include2.h is a symbolic link to /include2 and
/project1/localinclude1.h is a "real" file.

project1.ino includes both .h via 
# include "localinclude1.h"
# include "include2.h"

system is Linux Debian Jessie 64bit; arduino ide 1.6.11; file system is ext4
###### 

If I open /project1/project1.ino in arduino ide then all three files (project1.ino, localinclude1.h, include2.h) are shown in ide in tabs (= correctly).
I can edit and save all three files independently. If I save project1.ino or localinclude1.h from the ide all is fine and /project1/include2.h is still a symbolic link.

But if I save include2.h from the ide the symbolic link is replaces by a copy of /include2.h.
Thus, I then still have 
/project1/project1.ino
/project1/localinclude1.h
/project1/include2.h
/include2.h

but now /project1/include2.h is a "real" file (not a link any more) and is a copy of /include2.h.

This bug is really hard to recognize, as at first everything seems to be ok and continues to work.
Only if later you change something in /include2.h it won't show up in /project1/include2.h an v.v.

**Comment by facchinm** [comment]
Hi @Copmic , I agree that soft links should be saved by following the link and saving the actual file. However, this scenario is quite uncommon and platform-dependant, so the solution may be less than obvious. I changed the title into something more explicit

**Comment by Madouc** [comment]
this issue is also occurring within Windows 10 in Arduino 1.6.11.
Created files (both hard and sym link)
`mklink global.h ..\libraries\mcp2515\global.h`
or 
`mklink /h global.h ..\libraries\mcp2515\global.h`

**Comment by Madouc** [comment]
Arduino 1.8.1 on windows 10 still exhibits this behavior.

symlinks created:
'mklink global.h ..\libraries\mcp2515\global.h

but overwritten on save.

**Comment by 45gfg9** [comment]
Problem consists to this day.
See #8535
