### ISSUE TITLE
arLCD touch screen upload issues

### ISSUE THREAD

**Issue by Taytay001** [arduino/Arduino#5479]
Just recently bought the arLCD touch screen. I've uploaded many of the example sketches and they've worked fine. I've managed to make a sketch and upload it to the board. It didn't come out like i wanted it to, so I tried to improve the sketch and test it but it now wont let me upload the new sketch or any of the example sketches that came with it. The only error message it gives me is "An error occurred while uploading the sketch." Anyway i can clear the memory so i can be able to use this again so i don't look at messed up images anymore?
Also, I've noticed that I cant do anything over the internet while the board is plugged into my usb

**Comment by dlabun** [comment]
This is the wrong place to ask for support, you should contact the touch screen manufacturer for help.
