### ISSUE TITLE
i2c freeze arduino in case of no answer instead of passing and try to restart comm

### ISSUE THREAD

**Issue by neoaurion** [arduino/Arduino#5481]
i2c freeze arduino in case of no answer instead of passing and try to restart comm. It's an important issue in case of 24/24 running applications like in my case nfc door lock. The issue is described here https://rheingoldheavy.com/changing-the-i2c-library/ . I solved it by modding the lib, see files attached.
[utility_twi_patched_IIC.zip](https://github.com/arduino/Arduino/files/528863/utility_twi_patched_IIC.zip)

**Comment by facchinm** [comment]
Hi @neoaurion,
the issue has been reported in the past (https://github.com/arduino/Arduino/pull/2489) and will likely be fixed in the near future. Please comment on that PR or open a new proper one, mergeable :slightly_smiling_face:
