### ISSUE TITLE
MKR1000 Issue

### ISSUE THREAD

**Issue by Amorasamy** [arduino/Arduino#5483]
I have an MKR1000 board and i want to extend its range by adding an external antenna and asking about the possibility of this , or another method to do this issue
Thanks

**Comment by agdl** [comment]
@Amorasamy unlikely there is no UFL connector on the board for an external antenna, so the only thing you can do increase your AP TX range (I hope is not another MKR1000)

**Comment by Amorasamy** [comment]
Thanks for your response 
unfortunately , there are mobiles :D , and i think i can't extend their range
