### ISSUE TITLE
Remove https://github.com/adafruit/Adafruit_LSM303 from Library Manager

### ISSUE THREAD

**Issue by microbuilder** [arduino/Arduino#5485]
Is it possible to remove this repo from the library manager: https://github.com/adafruit/Adafruit_LSM303

It's been replaced with a more modern version, and having both in there leads to some confusion as to which version to install.

Thanks!
Kevin (Adafruit)

**Comment by sandeepmistry** [comment]
Hi @microbuilder,

I've removed it from the list, so it should be removed automatically on Sunday. If it's still there on Monday, just re-open this issue.

**Comment by microbuilder** [comment]
Thanks Sandeep, I'll have a couple others shortly since I'm merging some duplicate libraries into single repos.
