### ISSUE TITLE
Add new library - Logger

### ISSUE THREAD

**Issue by bakercp** [arduino/Arduino#5494]
https://github.com/bakercp/Logger

**Comment by cmaglie** [comment]
The `library.properties` in the release tag `1.0.2` doesn't have the correct version:
https://github.com/bakercp/Logger/blob/1.0.2/library.properties

please fix that with the following steps:

- remove tag 1.0.2
- update library.properties, setting 1.0.2, commit and push
- tag 1.0.2 again

**Comment by bakercp** [comment]
I think it's fixed now.  Thanks @cmaglie

**Comment by cmaglie** [comment]
Done, all (4) libraries are now published.

**Comment by bakercp** [comment]
Thanks!!
