### ISSUE TITLE
Selecting "Windows 10 Iot Core" gives null pointer exception

### ISSUE THREAD

**Issue by bfjelds** [arduino/Arduino#5502]
Seems that the Win10 boards.txt lacks a "buld.core" property and this code throws a null pointer exception:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
              at processing.app.BaseNoGui.getBoardPreferences(BaseNoGui.java:188)

Seems to be in this code ... assume Win10 plugin needs to be fixed, perhaps this should as well:

```
// Add all tools dependencies from the (possibily) referenced core
String core = prefs.get("build.core");
if (core.contains(":")) {
```

**Comment by facchinm** [comment]
@cmaglie need to add a check for NPE (and inform who is in charge for Win10 IoT board to fix the problem).
@bfjelds , thanks for reporting!

**Comment by bfjelds** [comment]
No problem!  I'm a part of the Win10 IoT team, we have a new version 1.1.1 that contains a fix.
