### ISSUE TITLE
[Library Manager] Checksum (CRC) doesn't match. File corrupted.

### ISSUE THREAD

**Issue by HackerInside0** [arduino/Arduino#5503]
Last friday i have noticed that if i try to download my own libraries from the library manager, the download fails and the error that i have reported in the title appears.

Before open this issue, i've waited for the library manager refresh on sunday, but it doesn't had any effect.

I'm talking about the L293 library:
https://github.com/HackerInside0/Arduino_L293.git

and the SharpIR library:
https://github.com/Hackerinside0/Arduino_SharpIR.git

![schermata del 2016-10-17 20 02 54](https://cloud.githubusercontent.com/assets/20952171/19449177/c67e61e2-94a4-11e6-917d-b308f3685390.png)

**Comment by cmaglie** [comment]
It's working for me...

![l293](https://cloud.githubusercontent.com/assets/423515/19483224/ea210474-9553-11e6-96e3-8049909e4703.png)

maybe you already downloaded some files that do not match crc?
You can try one of the following:

- remove the folder `$HOME/.arduino15/staging/libraries/`

or

- try the hourly build of the Arduino IDE that should do this automatically (this is a recent fix that will be released with IDE 1.6.13)

**Comment by HackerInside0** [comment]
Resolved, thanks.
