### ISSUE TITLE
Arduino IDE add iot_x86.a lib

### ISSUE THREAD

**Issue by 327** [arduino/Arduino#5508]
hi ,I have an lib ,name is iot_x86.a  ,and have three header files for this lib .Header files name is fd_engine.h ,ff_inc.h, ff_syshdr.h

iot_x86.a  contain fd_engino.o ff_inc.o ff_syshdr.o

How could I and add the iot_x86.a lib to  my Arduino sketch ?

**Comment by facchinm** [comment]
Adding a custom `.a` is not supported on Arduino out of the box. You need to hack the `platform.txt` file for the platform you are targeting and add the library to the linker commandline (like shown here for example https://github.com/esp8266/Arduino/blob/master/platform.txt#L37).
Note that a basic knowledge of C linking is required to get things done without getting mad :slightly_smiling_face:
