### ISSUE TITLE
AD9850 dds lib 

### ISSUE THREAD

**Issue by bandarei** [arduino/Arduino#5509]
Could anybody please add AD9850 DDS to the lib manager Thanks in advance 
https://github.com/bandarei/AD9850-DDS

**Comment by agdl** [comment]
Hi, you have no version number and no tag
https://github.com/bandarei/AD9850-DDS/blob/master/library.properties
Hi, I'm sorry but your library can't be added please follow [this guide](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

**Comment by bandarei** [comment]
version number and tag fixed :)

**Comment by cmaglie** [comment]
> version number and tag fixed :)

There are still no tags: https://github.com/bandarei/AD9850-DDS/tags
have you pushed them?

**Comment by bandarei** [comment]
tag is ready

**Comment by agdl** [comment]
Done thank you!
