### ISSUE TITLE
Add Library ArduinoLearningBoard-lib

### ISSUE THREAD

**Issue by JeffShapiro** [arduino/Arduino#5512]
https://github.com/JeffShapiro/ArduinoLearningBoard-Lib

Hi!  I've created an Arduino Learning Board project that combines a developer board (hardware) and a library that contains everything necessary (including samples) to create all of the sample projects.  I was previously hosting everything on CodeBender.cc but they just annonced they're shutting down so I'm moving everything to the Arduino IDE.

Thanks!
Jeff

**Comment by agdl** [comment]
Done thank you!
