### ISSUE TITLE
REACH & ROHS compliance Genuino MEGA 2560 Rev 3

### ISSUE THREAD

**Issue by C1MORIN** [arduino/Arduino#5519]
Hello,
Could you tell me please if the Genuino MEGA 2560 Rev 3 is compliant with RoHS 2 et REACh ?
Do you have a material declaration for this product ?

Thank you.
Caroline

**Comment by akash73** [comment]
@C1MORIN 
yes, MEGA 2560 is compliant with RoHS 2011/65/CE .
if you need assistance and documents please contact us here . https://store.arduino.cc/index.php?main_page=contact_us&language=en

thanks!
