### ISSUE TITLE
String.toCharArray() and String.getBtytes are not const [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#552]
This is [Issue 552](http://code.google.com/p/arduino/issues/detail?id=552) moved from a Google Code project.
Added by 2011-06-03T21:54:18.000Z by [matthew....@gmail.com](http://code.google.com/u/112744358256949035477/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
**1.**
**2.**
**3.**

**What is the expected output? What do you see instead?**

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

**Please provide any additional information below.**

**Comment by Chris--A** [comment]
Fixed!
These functions are marked const.

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/WString.h#L160
