### ISSUE TITLE
Library: Remove Adafruit_DHT_Unified

### ISSUE THREAD

**Issue by microbuilder** [arduino/Arduino#5527]
Can you please remove the following library from the library manager: https://github.com/adafruit/Adafruit_DHT_Unified

We've merged both of our DHT libraries into a single repo to avoid confusion, thanks.

**Comment by Timon2** [comment]
In file included from C:\Users\Laborator\Desktop\New_sketch_cu_do_while\New_sketch_cu_do_while.ino:2:0:

C:\Users\Laborator\Documents\Arduino\libraries\DHT_sensor_library/DHT_U.h:25:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

exit status 1


This error apears after library update

PLS HELP

**Comment by microbuilder** [comment]
This is the wrong place to post support issues for Adafruit libraries, but you are missing the Adafruit_Sensor library.

**Comment by Timon2** [comment]
thx, i instaled Adafruit_sensor-master library but now i have 3 errors.
Strange. Before update had no errors in compilation

**Comment by Timon2** [comment]
all is ok, thx microbuilder

**Comment by microbuilder** [comment]
Please file this as an issue on Adafruit's forums. It's inappropriate here to hijack an unrelated issue, thanks.

**Comment by cmaglie** [comment]
Done, the library will disappear at the next weekly cleanup round.
