### ISSUE TITLE
New Library: ArduinoSerialToTCPBridgeClient

### ISSUE THREAD

**Issue by RoanBrand** [arduino/Arduino#5533]
URL: https://github.com/RoanBrand/ArduinoSerialToTCPBridgeClient

More on the protocol and use see [Serial to TCP Bridge Protocol](https://github.com/RoanBrand/SerialToTCPBridgeProtocol)

**Comment by RoanBrand** [comment]
Anything I did wrong / still need to do?

**Comment by cmaglie** [comment]
the library has been added. Thanks!
