### ISSUE TITLE
[Library manager]  New leOS2 v. 2.3.2

### ISSUE THREAD

**Issue by leomil72** [arduino/Arduino#5548]
Please add leOS2 to v. 2.3.2 into Library Manager, thank you:
https://github.com/leomil72/leOS2
Direct link to zip file:
https://github.com/leomil72/leOS2/releases/download/2.3.2/leOS2_2.3.2.zip

**Comment by cmaglie** [comment]
The library is already added in the library manager and is checked regularly by our servers (each hour) for new releases.

Just push the new tag, and the library will be published within an hour, no need to ask!
