### ISSUE TITLE
Arduino Mega: sprintf (multiple args) substitute for floats as well

### ISSUE THREAD

**Issue by tofrnr** [arduino/Arduino#5551]
hello,
for my Arduino Mega a sprintf substitute  ( by multiple args+ multiple var types) is needed for floats as well. 
Unfortunately, an extended "genuine" sprintf lib for floats is not available for AVRs.

So perhaps an additional substitute then, e.g, something like an additional **_sprintfEx()_** .
It should work then like sprintf()  normally by stdio.h.

**_note:
I don't want to extend the Serial class, I just want to copy multiple float vars and different other vars to a buffer string_**

```
char strbuffer[100];
float f=2.12, g=-33.12345, h=1234.56789;
int i=23;

sprintfEx(strbuffer, "i=%-4d  f=%-8.4f  g=%8.4f  h=%-11.4f",  i, f,g,h);
```

it will be used e.g. for multiple  following chart table outputs on a TFT LCD, **_not_** bei Serial.print.

how is that possible?
if not, can it be added as a future feature please?

**Comment by per1234** [comment]
See: https://github.com/arduino/Arduino/issues/5033#issuecomment-234778198
