### ISSUE TITLE
Burn bootloader fail in 1.6.12

### ISSUE THREAD

**Issue by syvic** [arduino/Arduino#5552]
Burn bootloader option does work under Linux but not under MacOS or Windows in this version. No problems with 1.6.11...
Thanks!

**Comment by cmaglie** [comment]
Can you please provide more details?

**Comment by syvic** [comment]
Hi Cristian,

I'm afraid I cannot reproduce the error. It was detected during a course
where the students were using MacOS and Windows 10. I only use Linux and
it works correcly.

Regards
