### ISSUE TITLE
Addition of MIDI library

### ISSUE THREAD

**Issue by Franky47** [arduino/Arduino#5555]
Hello,

I recently refactored my [MIDI Library](https://github.com/FortySevenEffects/arduino_midi_library) for 1.5 rev2.1 format compatibility, and I've just released its version 4.3, available here:
https://github.com/FortySevenEffects/arduino_midi_library/releases/latest

If you could add it to the registry for the Arduino Library Manager, that would be nice.

Thanks !

**Comment by shiftleftplusone** [comment]
hello,
is this MIDI lib also compatibel to Arduino ZERO, M0,  and DUE boards?

**Comment by Franky47** [comment]
Yes. All boards/platforms that expose a Serial interface (HardwareSerial or SoftwareSerial) are compatible.

**Comment by facchinm** [comment]
Hi @Franky47 ,
we can't actually import the library since the version number in `library.properties` is still 4.2 while the tag is 4.3. Can you fix it? Thx :slightly_smiling_face:

**Comment by Franky47** [comment]
Ah, I must have missed that bugger, I'll fix that rightaway.

**Comment by Franky47** [comment]
It should be all good now:
https://github.com/FortySevenEffects/arduino_midi_library/tree/4.3.1

**Comment by facchinm** [comment]
Added, thank you!
