### ISSUE TITLE
Please add the following 3 new Library

### ISSUE THREAD

**Issue by smkkHw** [arduino/Arduino#5559]
This is the Library for LoRa communication based on Microchip rn2483  Rel =  V1.0.0
https://github.com/axelelettronica/sme-rn2483-library

This is a library for the LSM6DS3 3D accelerometer, 3D gyroscope Rel = V1.0.0
https://github.com/axelelettronica/sme-lsm6ds3-library

This is the library for a new shield with  some ST and NXP components
https://github.com/axelelettronica/sme-nxp-st-library REL = V1.0.0

**Comment by facchinm** [comment]
Added, thank you!

**Comment by smkkHw** [comment]
Thank U for the prompt answer
