### ISSUE TITLE
Please add lib AutoAnalogAudio

### ISSUE THREAD

**Issue by TMRh20** [arduino/Arduino#5565]
https://github.com/TMRh20/AutoAnalogAudio

**Comment by facchinm** [comment]
Hi @TMRh20 ,
you need to properly tag your library to get it listed in library manager. Please tag it using the same values of `version=` in `library.properties`. Thanks!

**Comment by TMRh20** [comment]
Ahhh, ok I think I have that all straightened out now.

**Comment by cmaglie** [comment]
Done!
