### ISSUE TITLE
Wrong code in example page

### ISSUE THREAD

**Issue by ckwiek** [arduino/Arduino#5566]
Hi, there is a syntax error in the official page of example the link below.

https://www.arduino.cc/en/Reference/BooleanVariables

It is missing one ; (Semicolon) in the last line of code,

digitalWrite (ledPin, running) // Indicate via LED)

I pointed out this link for a beginner, and then realized the error.

Regards.

Carlos Kwiek

**Comment by akash73** [comment]
thanks Carlos!
we have corrected the page.

**Comment by ckwiek** [comment]
You're welcome akash,
tank you for correcting.
