### ISSUE TITLE
AVR C Runtime Library - power_usart3_* functions no more

### ISSUE THREAD

**Issue by J-M-L** [arduino/Arduino#5568]
a fix for this has been submitted here [http://savannah.nongnu.org/bugs/index.php?48898](url)

Can this be included in the next build so that the Low-Power library for example works with a Mega?

thx

**Comment by facchinm** [comment]
Hi @J-M-L ,
we should keep track of this issue in one place only (#5286), so I'm closing this one as duplicate.
You can read my response there :slightly_smiling_face: 
Thanks!
