### ISSUE TITLE
MySensors library missing in library manager

### ISSUE THREAD

**Issue by tbowmo** [arduino/Arduino#5569]
Somehow Mysensors library have disappeared in the Arduino library manger,

we originally asked for inclusion with issue #5112

link to repository is https://github.com/mysensors/MySensors/tree/master

**Comment by agdl** [comment]
It should be fixed in wihin an hour. If so close this please

**Comment by mfalkvidd** [comment]
@agdl What happened? What can we do to prevent this from happening in the future?

**Comment by agdl** [comment]
There was a temporary server errors by our side sorry about this
