### ISSUE TITLE
Attempts to reopen a sketch fails [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#557]
This is [Issue 557](http://code.google.com/p/arduino/issues/detail?id=557) moved from a Google Code project.
Added by 2011-06-08T20:13:46.000Z by [matthew....@gmail.com](http://code.google.com/u/112744358256949035477/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open an existing sketch via the File|Examples or File|Sketchbook menu
2. Close the sketch
3. Attempt to reopen the sketch via as in 1.

**What is the expected output? What do you see instead?**
Expected: The sketch opens correctly
Actual: The sketch fails to open and an error message is presented: 'Sketch Does Not Exist'

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
arduino-1.0-beta1 on Windows

**Please provide any additional information below.**
This seems to be a side effect of *.pde sketch files being automatically renamed to *.ino

**Comment by ffissore** [comment]
This issue made sense 4 years ago, when the transition from pde to ino was in place. We failed to fix it and fixing it now is not worth anymore
