### ISSUE TITLE
Update Library Request

### ISSUE THREAD

**Issue by closedcube** [arduino/Arduino#5570]
Ciao,

Please add a new version for the following libraries:
https://github.com/closedcube/ClosedCube_OPT3001_Arduino
https://github.com/closedcube/ClosedCube_OPT3002_Arduino

Many thanks

**Comment by cmaglie** [comment]
About OPT3001, you already have: https://github.com/closedcube/ClosedCube_OPT3001_Library.git
shall we remove that one before adding the new one?

**Comment by cmaglie** [comment]
About OPT3002, the new release is already published: once the library is added to the library manager you can autonomously publish a new release by adding a new tag, our crawler checks every hour for a new release, no need to request again here.

**Comment by closedcube** [comment]
Yes, please "old" version of OPT3001 - https://github.com/closedcube/ClosedCube_OPT3001_Library.git

re: OPT3002 - thanks for the details

**Comment by cmaglie** [comment]
Done!
