### ISSUE TITLE
overview, list, and remove/uninstall libs once added (e.g., as zip )

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5572]
hello,
in the IDE (1.6.12) there are no library managing features provided about 
- an overview to find about  additionally libs once added manually e.g., as a zip file, and 
-  to remove/uninstall them when they are not needed any longer.

**Comment by per1234** [comment]
>an overview to find about additionally libs once added manually e.g., as a zip file, and

This is already possible: **Sketch > Include library > Manage Libraries > Type > Installed**.

>to remove/uninstall them when they are not needed any longer.

Duplicate of https://github.com/arduino/Arduino/issues/2878
