### ISSUE TITLE
Add library NeoGPS v3.1.2

### ISSUE THREAD

**Issue by SlashDevin** [arduino/Arduino#5575]
https://github.com/SlashDevin/NeoGPS

Thanks!

**Comment by SlashDevin** [comment]
Hello?  Is there a problem with the NeoGPS library format?  I moved the config and doc directories under extras, just in case they were not allowed in the library root.  The new tag is [v3.1.2](https://github.com/SlashDevin/NeoGPS/releases/tag/v3.1.2).

**Comment by cmaglie** [comment]
Done, sorry for the delay!
