### ISSUE TITLE
Source Code Help

### ISSUE THREAD

**Issue by Caizhenyu** [arduino/Arduino#5580]
Hello,everyone.
I am a yong developer.I want to know about the Arduino IDE.
But the source code’s line numbers are huge to me ,can you give me some guide and some Documents about?Especially on Windows platform.
Waiting for your feedback.Thank you.

**Comment by mikaelpatel** [comment]
@Caizhenyu This sounds like something for the forum (or stackexchange). You should report errors, suggest new functionality, pull requests, here. There are excellent tools for learning about a large source code base. You could start with generating statistics with for instance SourceMonitor and then use Doxygen to generate hyperlinked source code web-page. Cheers!
