### ISSUE TITLE
Please include SparkFun L55231 library in manager 

### ISSUE THREAD

**Issue by ToniCorinne** [arduino/Arduino#5583]
Link is here: https://github.com/sparkfun/SparkFun_LP55231_Arduino_Library/tree/V_1.0.0

Thanks!

**Comment by cmaglie** [comment]
I've added the library, but the line break in the `paragraph` field is not allowed:

https://github.com/sparkfun/SparkFun_LP55231_Arduino_Library/blob/V_1.0.0/library.properties#L7

please fix that field (put everything on a single line) and redo the tag. Once done the library will be published automatically within an hour.

**Comment by ToniCorinne** [comment]
Thanks for letting me know about that. It should be fixed and retagged now.
