### ISSUE TITLE
[website] "Authentication Required" on product pages

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5586]
The following product pages linked from the main chart on https://www.arduino.cc/en/Main/Products cause an "Authentication Required" dialog to appear:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/20177250/abfc4e06-a700-11e6-8b91-7fe589b6bef4.png)
https://www.arduino.cc/en/Main/ArduinoBoardMini
https://www.arduino.cc/en/Main/Robot
https://www.arduino.cc/en/Main/GTFT
https://www.arduino.cc/en/Main/ArduinoWiFiShield
https://www.arduino.cc/en/Main/ArduinoWirelessProtoShield

**Comment by akash73** [comment]
@per1234 thanks for noticing.
pages updated, now they don't show anymore the auth dialog box.

**Comment by oqibidipo** [comment]
But wait, there's more... 

There are still links to edit.arduino.cc at least on the following pages: 

https://www.arduino.cc/en/Main/ArduinoBoardEsplora
https://www.arduino.cc/en/Main/ArduinoBoardEthernet
https://www.arduino.cc/en/Main/ArduinoBoardLeonardo
https://www.arduino.cc/en/Main/ArduinoBoardMegaADK
https://www.arduino.cc/en/Main/ArduinoEthernetShieldV2
https://www.arduino.cc/en/Main/ArduinoMotorShieldR3
https://www.arduino.cc/en/Main/ArduinoUSBHostShield
https://www.arduino.cc/en/Main/ArduinoWirelessShield
https://www.arduino.cc/en/Main/MiniUSB
https://www.arduino.cc/en/Main/USBSerial

Details (grep output): 
[edit_arduino_cc.txt](https://github.com/arduino/Arduino/files/586565/edit_arduino_cc.txt)

**Comment by akash73** [comment]
Thanks also to @oqibidipo ! we have fixed the broken / uncorrect links.
I'll leave this issue open til some days, if you notice some other glitches.

**Comment by per1234** [comment]
I haven't found any more links to edit.arduino.cc since and all the pages listed above are fixed so I'm going to close this issue. Thanks akash73!
