### ISSUE TITLE
Problem changing name to library

### ISSUE THREAD

**Issue by alejandrorosas** [arduino/Arduino#5587]
![image](https://cloud.githubusercontent.com/assets/4923867/20186168/303b7214-a76f-11e6-8330-e45f57be1210.png)

There's an issue on the first version name, and on the last version I've changed "Driver" to "Drive" and now when I install the new version at the library manager there are two libraries.

Could you remove the first version? Or is there anything I can do?

Thanks!!

**Comment by agdl** [comment]
Can you please specify the github link?

**Comment by alejandrorosas** [comment]
Yes! Here: https://github.com/IngeniaMC/Ingenia-Serial-Servo-Drive-Library

**Comment by alejandrorosas** [comment]
@agdl Is there anything I can do to help or fix the issue?

**Comment by cmaglie** [comment]
It would have automatically disappeared this weekend, during the weekly clean-up, BTW I forced a manual clean up to speed up things, and now it's ok!
