### ISSUE TITLE
Arduino IDE: Use native file selection dialogs from KDE/Gnome [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#559]
This is [Issue 559](http://code.google.com/p/arduino/issues/detail?id=559) moved from a Google Code project.
Added by 2011-06-12T18:57:18.000Z by [Atalantt...@gmail.com](http://code.google.com/u/102057389459367553073/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

Hi

The Arduino IDE has a small usability problem on (K)ubuntu.
The Arduino IDE (v0022) uses its own open/save dialog box, which is quite rudimentary compared to the file selection dialogs from KDE (KDialog) or Gnome (Zenity).

For the future it would be nice when the Arduino IDE on Linux uses the native file selection dialogs like on Windows.

See cross-post at URL:
http://arduino.cc/forum/index.php/topic,62960.msg456797.html

Best Regards,
Atalanttore

**Comment by ffissore** [comment]
Fixed with e327bb091afb7859b6aa26f1050181d8f7979bc3 and since IDE 1.6.4

**Comment by Atalanttore** [comment]
Thanks!
