### ISSUE TITLE
Add Gamebuino to Libraries Manager

### ISSUE THREAD

**Issue by Rodot** [arduino/Arduino#5595]
Hello, could you please add the Gamebuino Library ? Thank you !
https://github.com/Rodot/Gamebuino

**Comment by agdl** [comment]
Hi, in your latest tag a library.properties is missing. Fix this please
https://github.com/Rodot/Gamebuino/tree/v0.3/library.properties

**Comment by Rodot** [comment]
The latest tag is 0.4 not 0.3, to which I added the library.properties:
https://github.com/Rodot/Gamebuino/releases/tag/0.4
Is it ok ? Thanks for your help.

**Comment by agdl** [comment]
Sorry, you are right. Done Thank you!
