### ISSUE TITLE
Add FanController to Library Manager

### ISSUE THREAD

**Issue by GiorgioAresu** [arduino/Arduino#5596]
Hi, could you please add my library to the library manager?

Here's the repo: [https://github.com/GiorgioAresu/FanController](https://github.com/GiorgioAresu/FanController)

**Comment by agdl** [comment]
Hi, I'm sorry but your library can't be added since the tag is not compliant with the version indicated in the library.properties https://github.com/GiorgioAresu/FanController/blob/v0.1.3/library.properties
Fix this please

**Comment by GiorgioAresu** [comment]
Sorry, forgot to update it. Fixed with v0.1.4.

Thanks

**Comment by cmaglie** [comment]
Done!
