### ISSUE TITLE
 PCA9536 RGB LED DRIVER: New Library Contribution

### ISSUE THREAD

**Issue by nadavmatalon** [arduino/Arduino#5600]
Hi, 

I wrote (and tested with hardware) a new library which enables the user to drive an RGB-LED
(Common-Anode or Common-Cathode) over an I2C bus. The bridge between the I2C master (Arduino) and the RGB Led is formed by the PCA9536.

The library comes complete with testing & usage sketch examples and functional documentation.

The current version of the library is: v1.2.0 (for which a 'Github Release' has been created)

The Github repo of the library can be found at: https://github.com/nadavmatalon/PCA9536_RGB

Could this new library please be added to the list of contributed libraries on the 'Interfacing with Hardware' of the Arduino Playground.

Thanks,
Nadav

**Comment by agdl** [comment]
Done thank you!
