### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by juan8taco** [arduino/Arduino#5606]
Hi, Can you add the following files to the core directory.
I'm working on a project with Arduino and Ikea Dioder and user used the files from
https://github.com/mysensors/MySensors
these files seem to be missing.
MyTransportNRF24.h 
MySensor.h

**Comment by facchinm** [comment]
Hi @juan8taco ,
that files are part of `mySensors` library, which you can download from the Library Manager. 
As a future reference, if you want a simple link which opens the Lib Manager when needed, add a comment containing `http://librarymanager/all#mysensors` to your sketch; clicking on it will prompt for the correct library to be installed.
