### ISSUE TITLE
Error something

### ISSUE THREAD

**Issue by zackhaikal** [arduino/Arduino#5608]
I've been working some project and using arduino mega 2560
The code written is verified and passed
When clicking upload to the board, the software froze for a few minutes and gave the following error:
avrdude: stk500_2_ReceiveMessage(): timeout

**Comment by cmaglie** [comment]
This seems more like an error in your setup than a bug in the Arduino IDE.
Please post your question in the forum http://forum.arduino.cc/.
I'd suggest to put more details if you want to receive an answer.
