### ISSUE TITLE
Issues Regarding Arduino Uno

### ISSUE THREAD

**Issue by Jee77** [arduino/Arduino#5616]
c:\users\jeeso\downloads\arduino-1.6.12-windows\arduino-1.6.12\hardware\tools\avr\bin\../lib/gcc/avr/4.9.2/../../../../avr/bin/ar.exe: unable to rename 'core\core.a'; reason: Permission denied

every time I try to up load the code onto Arduino uno I keep getting this error message and I don't know whats wrong! can someone help me out?

**Comment by facchinm** [comment]
Hi @Jee77 ,
could you post the whole verbose output of the compilation?

**Comment by andresquintero2017** [comment]
Arduino:1.8.1 (Windows 10), Tarjeta:"Arduino/Genuino Uno"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\usuario\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10801 -build-path C:\Users\usuario\AppData\Local\Temp\arduino_build_859997 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\usuario\Documents\Arduino\led8_var_int\led8_var_int.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\usuario\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10801 -build-path C:\Users\usuario\AppData\Local\Temp\arduino_build_859997 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\usuario\Documents\Arduino\led8_var_int\led8_var_int.ino
Using board 'uno' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10801 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\sketch\led8_var_int.ino.cpp" -o "nul"
Generating function prototypes...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10801 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\sketch\led8_var_int.ino.cpp" -o "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\preproc\ctags_target_for_gcc_minus_e.cpp"
Compilando programa...
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10801 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\sketch\led8_var_int.ino.cpp" -o "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\sketch\led8_var_int.ino.cpp.o"
Compiling libraries...
Compiling core...
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_pulse.S.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\WInterrupts.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\hooks.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_analog.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_digital.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_pulse.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_shift.c.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\CDC.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\HardwareSerial.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\HardwareSerial0.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\HardwareSerial1.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\HardwareSerial2.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\HardwareSerial3.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\IPAddress.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\PluggableUSB.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\Print.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\Stream.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\Tone.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\USBCore.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\WMath.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\WString.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\abi.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\main.cpp.o
Utilizando archivo previamente compilado: C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\new.cpp.o
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_pulse.S.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\WInterrupts.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\hooks.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_analog.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_digital.c.o"
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc-ar" rcs  "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a" "C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\wiring_pulse.c.o"
c:\program files (x86)\arduino\hardware\tools\avr\bin\../lib/gcc/avr/4.9.2/../../../../avr/bin/ar.exe: unable to rename 'C:\Users\usuario\AppData\Local\Temp\arduino_build_859997\core\core.a'; reason: Permission denied

exit status 1
Error compilación en tarjeta Arduino/Genuino Uno.

**Comment by facchinm** [comment]
Would be nice to know how @MaxPowe solved this issue. Running as administrator is a way but it shouldn't be necessary. Which AntiVirus are you running?

**Comment by andresquintero2017** [comment]
avg antivirus @facchinm

**Comment by facchinm** [comment]
Try pausing it when you compile the sketch; if the compilation succeeds, he's the culprit

**Comment by andresquintero2017** [comment]
ESO ERA MUCHAS GRACIAS

2017-02-14 10:21 GMT-05:00 Martino Facchin <notifications@github.com>:

**Comment by sandeepmistry** [comment]
Closing as resolved, the problem was antivirus related.

**Comment by jomardyan** [comment]
Disabling Antivirus not help.

**Comment by Mayoogh** [comment]
Temporary fix 
- Create a new blank  sketch 
```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```
- Verify/Compile 
- Close new sketch and try compiling project sketch

**Comment by mirfozil99** [comment]
hi Guys ,Mayoogh`s way works thanks
