### ISSUE TITLE
missing feature: adjust default  message window (debug window) size at startup

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5627]
I am missing a feature (for 1.6.12): 
I cannot adjust default the  message window size at startup.
It is always about 3 lines high but 8 lines are needed as a default.
Where can one adjust it accordingly?

If not possible, this should be a feature requst then.

**Comment by per1234** [comment]
I'm assuming by "message window" you mean the console.

This can be done by:
1. Close the Arduino IDE
2. Open preferences.txt in a text editor. For the location of preferences.txt see https://www.arduino.cc/en/Hacking/Preferences
3. Chang the value of `console.lines`
4. Save preferences.txt

Currently it seems that 4 is the minimum value. It's possible this will be changed by https://github.com/arduino/Arduino/issues/6130, I haven't tested it.
