### ISSUE TITLE
missing a feature: compilation error => double click on error msg in debug window => jump to related code line in editor  window

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5628]
I am missing a feature (for 1.6.12): 
when there is a compilation error 
=> it should be possible to double click on error msg in debug window 
=> and then the cursor jump to related code line in code editor window

 this is a feature request.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/3383
I agree this would be super useful. I really liked that feature when I tried Visual Micro/Atmel Studio.

**Comment by shiftleftplusone** [comment]
yes, thx for your approval! 
this feature is also provided by the Geany IDE (Raspbian) and also very helpful here
