### ISSUE TITLE
Library inclusion request: Simple automated Daylight Saving Time adjust library for esp8266

### ISSUE THREAD

**Issue by neptune2** [arduino/Arduino#5631]
Here is the GitHub :
https://github.com/neptune2/simpleDSTadjust

**Comment by cmaglie** [comment]
Done!

**Comment by neptune2** [comment]
Thank-you for adding to the library.

Unfortunately I had the wrong name in the library.properties file.
I have now released a new 1.1.0 version that now has the correct name "simpleDSTadjust".

Is it possible to change the "name" in the library_index.json file and associated download.arduino.cc/libraries/neptune2/* files?

**Comment by cmaglie** [comment]
Done the rename
