### ISSUE TITLE
#define _CRT_SECURE_NO_WARNINGS #include <iostream> #include <vector> #include <stdio.h> #include <algorithm> #include <memory.h> #include <string> #include <string.h> #include <map> 

### ISSUE THREAD

**Issue by leen94** [arduino/Arduino#5637]

**Comment by matthijskooijman** [comment]
There is no description in this issue and the title makes no sense. Please use this issue tracker only for well-described bugs and feature request. I'm closing this one, feel free to reopen if you edit in a proper description and title.
