### ISSUE TITLE
"!!!" thing

### ISSUE THREAD

**Issue by zackhaikal** [arduino/Arduino#5640]
is it normal that Arduino Mega 2560 can't tolerate with "!!!" thing?
btw, it worked properly when using Arduino Uno

**Comment by PaulStoffregen** [comment]
This was fixed years ago.

Maybe you have a *very* old board?  Or a clone that's still using the old bootloader from before this was fixed?

**Comment by zackhaikal** [comment]
it seems that i have a very old board, sorry for my ignorance.

**Comment by matthijskooijman** [comment]
Yup, this is covered in #392. To fix this, you'll have to update the bootloader on the mega (the Arduino IDE can do that, but you'll need an ISP programmer, or possibly another Arduino with the ArduinoISP sketch).
