### ISSUE TITLE
Please add tinySPI

### ISSUE THREAD

**Issue by philipp-frey** [arduino/Arduino#5643]
As title says, please add the tinySPI library:
[https://github.com/JChristensen/tinySPI](url)

**Comment by oqibidipo** [comment]
Weird... that link actually points to `https://github.com/arduino/Arduino/issues/url`

testing... (looks ok in preview)
https://github.com/JChristensen/tinySPI

**Comment by cmaglie** [comment]
The library is missing a `library.properties` file and a tag release.

Please get in touch with the author and ask to prepare the library for inclusion in the library.manager.
