### ISSUE TITLE
Arduino TFT/SD Shield drives SPI MISO permanently

### ISSUE THREAD

**Issue by cawena** [arduino/Arduino#5644]
The Arduino LCD Screen/SD Card Shield circuit has IC3, which buffers MISO, permanently enabled so that the line is always driven. This prevents the shield being used with any other SPI devices on that bus.

[Arduino JCD/SD Shield](https://www.arduino.cc/en/Main/GTFT)

**Comment by per1234** [comment]
Closing because the product has been retired.
