### ISSUE TITLE
Issue #4803 'Inconsistent documentation ArduinoBoard101' not fixed correctly

### ISSUE THREAD

**Issue by foxtrotfire** [arduino/Arduino#5650]
In the issue I created [here](https://github.com/arduino/Arduino/issues/4803) it was said 4mA was the correct value for the I/O sink/source current. But now the documentation is quite adamant about it being 20mA. 

Was this changed correctly or are people being disappointed about the true current capabilities of this board?

Regards

**Comment by facchinm** [comment]
The correct one is 20mA (measured, not datasheet data). The 4 mA misunderstanding was due to an early datasheet which did not take into account the drive strength of the level translators. Thanks
