### ISSUE TITLE
Add Industrial Shields library

### ISSUE THREAD

**Issue by albertprieto** [arduino/Arduino#5652]
Hello, 
I'm Albert Prieto from industrial Shields. Our company is developing @Arduino based PLCs using original Arduino boards inside. And we have done a library for those PLCs. 
I would like if our GitHub Library can be added on the Arduino library.
https://github.com/IndustrialShields/arduino-IndustrialShields

Many Thanks.
Albert

**Comment by cmaglie** [comment]
I've added the library to the indexer, but the repository is still missing a release/tag. Please add a release and the library will be publised within an hour.
