### ISSUE TITLE
[MAC] IDE crashes on any keypress [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#566]
This is [Issue 566](http://code.google.com/p/arduino/issues/detail?id=566) moved from a Google Code project.
Added by 2011-06-28T15:23:21.000Z by [robbinsk...@gmail.com](http://code.google.com/u/116561609626502820566/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Install and open IDE
2. Place cursor in code field
3. Press any key

**What is the expected output? What do you see instead?**
Obviously I expect to see the key I pressed appear in the code field. Instead, the app crashes (report down below)

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino v0022
Arduino Uno
Max OS X 10.7 (Lion)
Apple Mac Mini (late 2009), 2.53GHz version

**Please provide any additional information below.**
Crash Report: http://pastebin.com/zSfCKduu

Robin Kanters

**Comment by ffissore** [comment]
Question posted on the original issue
