### ISSUE TITLE
Allow referencing a library in Library Manager

### ISSUE THREAD

**Issue by vshymanskyy** [arduino/Arduino#5666]
IDE code editor has a feature to open Library Manager using a link: http://librarymanager
It would help a lot, if developers could reference also to a concrete library using this method.

For example, this link:
http://librarymanager/Adafruit%20NeoPixel
would open Library Manager and automatically put "Adafruit NeoPixel" in Filter field.

Thanks!

**Comment by facchinm** [comment]
Indeed, you already can do it :smile: 
The syntax is http://librarymanager/category#searchFields 
For uncommon names, use the `all` category (eg. http://librarymanager/all#Adafruit&NeoPixel).

**Comment by vshymanskyy** [comment]
Cool, thank you!
