### ISSUE TITLE
turn off overwriting preferences.txt in portable folder

### ISSUE THREAD

**Issue by hanabanana** [arduino/Arduino#5668]
Using the portable folder inside IDE folder, it is nice that we are able to to make all IDE files self-contained in one location instead of having files scattered around many places. To share the same IDE across multiple machines(same OS), we need to put the IDE folder on a network drive, which only have read permission for normal users. Now, the IDE can no longer open because it tries to overwrite the preferences.txt in the portable folder and fails with a permission issue. We are forced to go back to the scattered IDE option, which makes it harder to share across multiple machines.

Is there a way to make IDE not overwriting the preferences.txt in portable folder by either turning it off or setting it to write the txt somewhere else?

**Comment by cmaglie** [comment]
@hanabanana 
is the `--preference-file` an option for you?

```
  --preferences-file filename
    Read and store preferences from the specified filename instead of the default one.
```

using this option you can make the IDE write the file in any arbitraty path.
