### ISSUE TITLE
Run the Arduino compiler from terminal

### ISSUE THREAD

**Issue by mgameiro** [arduino/Arduino#5670]
It could help sometimes to have the chance of just typing a command to compile the code for Arduino.

**Comment by Chris--A** [comment]
You can:

> arduino --upload /path/to/sketch/sketch.ino

I have just tested this:

> arduino -v --verify /path/to/sketch/sketch.ino --pref buld.path=/path/to/build/folder

https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc

**Comment by facchinm** [comment]
Thanks @Chris--A ! Closing as solved
