### ISSUE TITLE
Uploading process stuck on Due if sketch is larger then 256KB and 'Verify code after upload' is set

### ISSUE THREAD

**Issue by prasimix** [arduino/Arduino#5672]
An attempt to upload sketch on Due that is larger then 256KB cannot be completed if `Verify code after upload` option is selected:

![Due stuck](https://cloud.githubusercontent.com/assets/22171393/20843292/c8b67802-b888-11e6-92fe-2eb7a4325839.png)

To reproduce this step, make sketch that is more then 256KB long or try this [eez_psu_sketch](https://github.com/eez-open/psu-firmware) where we noticed this bug, go to **File... Preferences** and select `Verify code after upload` option and start upload (Ctrl+U).

I tested that with Arduino IDE 1.6.9 and 1.6.13 on Windows and Ubuntu with installed _Arduino SAM boards (32-bits ARM cortex-M3) by Arduino_ package 1.6.9. Board is obviously Arduino Due.

**Comment by facchinm** [comment]
Hi @prasimix ,
thanks for reporting. I tested the sketch (both with and without verify) and it behaves correctly (on Linux). I'm attaching the (super) verbose output in case you are interested or can spot any relevant difference (like the OS in use :slightly_smiling_face: ).
[verbose_out.txt](https://github.com/arduino/Arduino/files/631807/verbose_out.txt)

If you enable the verbose output you should see the `bossac` version; mine is `1.6.1`

**Comment by prasimix** [comment]
Thanks for quick response. How can I generate such verbose output file? I tried uploading (not just compiling) once again with selected both *Show verbose output during: upload* and *Verify code after upload* options and got the same problem.

**Comment by mvladic** [comment]
I tried with `Arduino IDE 1.6.9` on Windows 10 and upload fails during verify as @prasimix reported. Here is the verbose output:

[verbose_out.zip](https://github.com/arduino/Arduino/files/636711/verbose_out.zip)

You can see that `bossac` is version `1.6.1`.

**Comment by facchinm** [comment]
@mvladic @prasimix I may have an idea; how long is it taking the upload process? We recently added a check on the IDE to avoid stuck programmers instances which block the serial port (https://github.com/arduino/Arduino/blob/ec2e9a642a085b32701cf81297ee7c1570177195/arduino-core/src/cc/arduino/packages/Uploader.java#L136)
If your upload takes more than 2 minutes it gets killed forcibly... On my PC it takes far less, but it could be OS dependant

**Comment by mvladic** [comment]
Yes, it takes more than 2 minutes. I tried again and upload blocked after exactly 2 minutes and 30 seconds.

**Comment by facchinm** [comment]
Ok, so we reached a corner case which I never thought it was possible to encounter, my bad. 
@cmaglie @PaulStoffregen for your experience, what could be a safe value for MAXIMUM successful upload duration? 3 minutes? 5 minutes?

**Comment by prasimix** [comment]
If 2 minutes is enough for 256KB, 4 minutes should be enough for 512KB :) 
Maybe you can link that limit to selected board.
