### ISSUE TITLE
DigitalPotentiometer tutorial circuit exceeds rated specs on the AD5171

### ISSUE THREAD

**Issue by EddieEdwards** [arduino/Arduino#5680]
https://www.arduino.cc/en/Tutorial/DigitalPotentiometer

The circuit applies 5V across the A and B terminals of the AD5171, and then attaches a 220 Ohm resistor and an LED to the W terminal.  When set to max. brightness, the AD5171 has approximately 60 Ohms of resistance in series with the 220 Ohms.  Assuming a 1.8V drop across the LED this leads to a current of about 11.5mA through the LED, series resistor, and AW terminals of the AD5171.

Unfortunately, digital pots are not rated for this kind of current.  The maximum continuous current allowed through the AD5171's potentiometer (AW or BW) is 5mA.  The tutorial circuit exceeds this by a factor of two.

Please specify a 680 Ohm resistor in place of the 220 Ohm resistor.  This will limit the current to under 5mA in all cases.  It would be helpful to mention the current limit as the reason for this high resistance, especially as the manufacturers like to hide these limits deep in the datasheet.  The limit here is under "Absolute Maximum Ratings" on page 6: http://www.analog.com/media/en/technical-documentation/data-sheets/AD5171.pdf

It's also worth noting that this tutorial is somewhat obsolete, as the AD5171 cannot be obtained in DIP package any more.  According to parametric search at Digikey, the only remaining I2C DIP parts are the Maxim DS18030 series.

**Comment by agdl** [comment]
Done thank you!
