### ISSUE TITLE
WatchDog - New Library Contribution

### ISSUE THREAD

**Issue by nadavmatalon** [arduino/Arduino#5683]
Hi,

I've written a library containing a set of functions that utilizes the WatchDog timer found in many AVRs as an ordinary interrupt-based timer. This library has several advantages over AVR's wdt library, including: the ability to set a custom period (provided it's divisible by 16mS); no limit on the  interrupt period length; setup for user-defined, customizable  ISR; and, what I hope is a  much clearer code-base for users to follow and modify if desired.

The Github repo contains the relevant documentation for installing and running the library, as well as usage examples, and so far I've tested it on the Arduino Uno, Attiny84, and ATtiny841.

The current version of the library is: v1.2.0 (for which a 'Github Release' has been created).

The Github repo of the library is located at: https://github.com/nadavmatalon/WatchDog

I've added the library to the Arduino Playground's 'Interfacing with Hardware' list, and wanted to ask if you could please also add it to the library manager?

Many thanks,
Nadav

**Comment by cmaglie** [comment]
Done! Sorry for the delay!
