### ISSUE TITLE
Arduino IDE Library Manager - libraries information

### ISSUE THREAD

**Issue by ControllinoAdmin** [arduino/Arduino#5687]
Hello,
I have a question about the source of information for Library Manager's libraries.
On your webistes ([https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)) it is explained, what each key in the .properties file means. We successfully created the file and you added the Controllino Library.

The problem is a little weird. When I changed the author and the maintainer from SG-Tronic to Controllino, the information in Library Manager changed. But, when I open the Library Manager, filter for Controllino and then click aywhere on the bottom part of the found library, without selecting any old version, the author changes (see attached image). I also noticed, that version 1.0.3 in the listbox is missing.

The question is. Where does Arduino IDE take the information from, if the .properties file value is different than the one displayed? You can check the .properties file and its hitory here: [https://github.com/Controllino/ControllinoLibrary/blob/master/library.properties](https://github.com/Controllino/ControllinoLibrary/blob/master/library.properties).
If you need any more information for solving the problem, I will be glad to tell you.

Thank you
![error](https://cloud.githubusercontent.com/assets/14331493/20971418/aa020540-bc91-11e6-9d08-08f23959edf8.jpg)

**Comment by facchinm** [comment]
Version 1.0.3 is missing from the dropdown since it's already installed; about the author name, there could be a bug regarding cached information and the json evaluation order; I can see "CONTROLLINO" as author since I don't have the lib installed. The caching issue is already being tracked at https://github.com/arduino/Arduino/issues/5517
