### ISSUE TITLE
DHCP client doesn't handle multiple DNS server addresses in DHCP response [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#569]
This is [Issue 569](http://code.google.com/p/arduino/issues/detail?id=569) moved from a Google Code project.
Added by 2011-07-07T20:57:41.000Z by [adrian.m...@gmail.com](http://code.google.com/u/108388509099941515037/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

With the new Arduino 1.0 Ethernet library with the DHCP client included, if your DHCP server returns more than one DNS server address for use it fails to parse the remainder of the DHCP response correctly.

This often results in the Ethernet chip not being configured correctly (which can sometimes be spotted if the netmask and/or gateway IP address are set to 0.0.0.0) and the Arduino won't be able to communicate over Ethernet

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#24
