### ISSUE TITLE
avr-g++ file

### ISSUE THREAD

**Issue by arun1944** [arduino/Arduino#5691]
I am trying to compile a simple "BLINK" sketch for Arduino UNO board, using Arduino IDE v1.6.13 on my Win 8.1 OS.
But while compiling, the output window shows an error message 
C:\\Users\\Admin\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.9.2-atmel3.5.3-arduino2/bin/avr-g++": file does not exist
Error compiling for board Arduino/Genuino Uno.

How do I resolve this issue, any suggestions please ?
-arun karkare

**Comment by dlabun** [comment]
Sounds like your installation is corrupt... You may want to try removing and reinstalling Arduino

**Comment by facchinm** [comment]
Before starting the uninstall/reinstall dance, try opening the Board Manager and uninstall the AVR core. If everything goes well the label should become "BUILTIN" and the IDE should start using the builtin core again (with its related tools)

**Comment by arun1944** [comment]
Thank you

**Comment by arun1944** [comment]
Thank you

**Comment by facchinm** [comment]
@arun1944 did it solve your issue? :smile:

**Comment by arun1944** [comment]
I had to delete the "C\Users\...Arduino15" file, uninstall the Arduino IDE
program, and then re-install 1.6.13 version.
Now it is working fine.
Anyway Thanks for ur concern
-Arun

**Comment by Nibbels** [comment]
xec: "C:\\Users\\USERNAME\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.9.2-atmel3.5.4-arduino2/bin/avr-g++": file does not exist
Fehler beim Kompilieren für das Board Arduino/Genuino Mega or Mega 2560.

This happens when running a suggested "Board update" while compiling something. Then the update doesnt work and the board is unusable.

**Comment by facchinm** [comment]
@Nibbels probably on the first round the extraction failed but the folder structure (and relevant files) where in the correct place, so every other installation would pick theme as the correct core. Uninstalling und reinstalling the core from board manager does the trick as you discovered :wink:

**Comment by binmulyadin** [comment]
My problem solved as suggested by Nibbels, thank you

**Comment by Steve92169** [comment]
I had the same error message on a Mega 2560 R3 using IDE 1.8.5 and AVR Boards 1.6.20. I installed AVR Boards 1.6.19, and that solved the problem.  Re-installing 1.6.20 failed, so I went back to 1.6.19. It seems to work fine.

**Comment by davidm-public** [comment]
@facchinm  worked for me!
thanks

**Comment by adumont** [comment]
@Steve92169 solution above worked for me.

**Comment by Gurubasavaraj003** [comment]
same problem but this time also facing the same issue any solution plz

**Comment by irfanctn** [comment]
you change arduino's home directory to the root directory, long folder names causes this error

**Comment by Aaron-Roar** [comment]
I am using arduino-cli on Alpine Linux and I received this error. After some investigation I noticed it was dynamically linked when running
`Sat Jan  9 06:03:49 UTC 2021> file ~/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++`
with output
`/root/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=a96cf70b452ab1acb76a923f4aba04eeade2a926, stripped`

I was missing dependencies to handle this, specifically /lib64/ld-linux-x86-64.so.2
This dependency can be acquired from the alpine repository https://pkgs.alpinelinux.org/contents?file=ld-linux-x86-64.so.2
`apk add gcompat`

after acquiring such package I am able to compile

`Sat Jan  9 06:09:24 UTC 2021> ~/arduino-cli compile -b arduino:avr:uno`
with output
`Sketch uses 924 bytes (2%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.
`

**Comment by Mayoogh** [comment]
Downgrading Arduino AVR Boards from `1.8.3` to `1.8.1` from the board manager fixed the issue for me

**Comment by giulionyakunga** [comment]
This issue occurred to after updating Arduino AVR Boards from older version to version 1.8.4, to fix this I had to downgrade  Arduino AVR Boards to version 1.8.3, so I recommend you to install Arduino AVR Boards version 1.8.3 through this simple steps, go to Tools -> Boards -> Board Manager -> Install "Arduino AVR Boards (1.8.3)"
Good luck...

**Comment by rovesoul** [comment]
> This issue occurred to after updating Arduino AVR Boards from older version to version 1.8.4, to fix this I had to downgrade Arduino AVR Boards to version 1.8.3, so I recommend you to install Arduino AVR Boards version 1.8.3 through this simple steps, go to Tools -> Boards -> Board Manager -> Install "Arduino AVR Boards (1.8.3)" Good luck...

thanks,your answer solve my problem.
