### ISSUE TITLE
Add "IoTtweet" library to Library manager Arduino IDE

### ISSUE THREAD

**Issue by Isaranu** [arduino/Arduino#5704]
We are developer team from http://www.iottweet.com which provided an IoT user designable dashboard. It's compatible use with ESP8266 Wifi module, NodeMCU, WeMos, Nano32 and several IoT model.

github url : https://github.com/Isaranu/IoTtweet

Thank you very much.
IoTtweet team.

**Comment by cmaglie** [comment]
Done!
