### ISSUE TITLE
[Library Manager] Please add to library: Pablo

### ISSUE THREAD

**Issue by edeleflie** [arduino/Arduino#5705]
https://github.com/polygondoor/Pablo

**Comment by edeleflie** [comment]
Hi there,

I've just done a quick survey of all requests to be added to the Arduino Library Manager. None of those requests have yet been included in the library manager (since about 10 days).

I realise that whoever is managing that is probably very busy. But I was just wondering if there is some kind of ETA possible? We have a workshop running at a local school next week, and having our library included will greatly lower the Arduino barrier-to-entry for our students.

regards,
Etienne

**Comment by cmaglie** [comment]
Done!
