### ISSUE TITLE
[Library Manager] Please add the library BridgeHttpClient

### ISSUE THREAD

**Issue by imrehorvath** [arduino/Arduino#5706]
A practical and easy to use generic HTTP client library for the Yun.

Features:
GET/POST/PUT/DELETE
Both sync and async requests
You can access the HTTP response code and headers, not just the body
Basic authorization
Multiple extra request headers
Extraction of a particular response header value
Designed for efficiency and easy usage
Built on top of the Bridge library
Uses cURL on the Linux side

https://github.com/imrehorvath/BridgeHttpClient

**Comment by cmaglie** [comment]
Done!
