### ISSUE TITLE
"Copy as html" copies for forum...

### ISSUE THREAD

**Issue by joeybab3** [arduino/Arduino#5708]
When using the "copy as html" it simply surrounds your code with a [code] tag instead of copying as html like in older versions.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/5401.
Until the bug is fixed you will need to use **Edit > Copy for Forum** instead of **Edit > Copy as HTML**.

**Comment by joeybab3** [comment]
ah, my bad didn't see that one...
