### ISSUE TITLE
Programmer "Arduino Gemma" does not work on Gemma v2

### ISSUE THREAD

**Issue by mwhuss** [arduino/Arduino#5710]
As outlined in most documentation it's recommended to use the "Arduino Gemma" under Tools Programmer. This results in the error "avrdude: Error: Could not find USBtiny device". Switching to the "USBtinyISP" programmer resolves the issue.

**Comment by mwhuss** [comment]
If it makes a difference this was for the "Adafruit GEMMA v2" board.

**Comment by mwhuss** [comment]
Doing more research, it does look like the Adafruit Gemma and the Arduino Gemma are different. I'm currently using `v1.6.13` which is supposed to have the Adafruit boards available in the board manager according to [this article](https://learn.adafruit.com/adding-custom-boards-to-the-arduino-v1-6-board-manager).

Alternatively I was able to get them to show up by adding this as an "Additional Boards Manager URL".

https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

**Comment by sandeepmistry** [comment]
The article you linked to: https://learn.adafruit.com/adding-custom-boards-to-the-arduino-v1-6-board-manager has a warning:
> This guide is no longer accurate with the release of version 1.6.4 of the Arduino IDE. Custom third party board support has been officially added in v1.6.4+.

So adding the board manager URL is the way to go. I'm closing this as resolved.
