### ISSUE TITLE
Typo in Examples From Libraries

### ISSUE THREAD

**Issue by Alexvthooft** [arduino/Arduino#5713]
There is a small typo in Examples From Libraries on page https://www.arduino.cc/en/Tutorial/HomePage 

In the second sentence the word "your" is used where it should be "you"

<img width="921" alt="screen shot 2016-12-13 at 09 21 23" src="https://cloud.githubusercontent.com/assets/24541185/21132858/6e2758e8-c116-11e6-8acb-18111e23ad7a.png">

**Comment by agdl** [comment]
Fixed thank you!
