### ISSUE TITLE
bitWrite macro incorrectly expands ternary operator

### ISSUE THREAD

**Issue by svatoun** [arduino/Arduino#5714]
let's have a bitWrite(data, bitIndex, computedValue == 5 ? 1: 0);

bitWrite macro definition lacks parenthesis around the `bitvalue' parameter, so it expands as follows

(computedValue == 5 ? 1 : 0 ? bitSet(value, bit) : bitClear(value, bit)) 

and the `0 ? bitSet...' is then compiled as the false branch of the ternary operator in the passed expression.
Please correct the definition as follows:

#define bitWrite(value, bit, bitvalue) ((bitvalue) ? bitSet(value, bit) : bitClear(value, bit))

(parenthesis added)

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#14
