### ISSUE TITLE
https://github.com/MadTooler/Gobbit_Line_Commander/releases

### ISSUE THREAD

**Issue by MadTooler** [arduino/Arduino#5715]
https://github.com/MadTooler/Gobbit_Line_Commander

https://github.com/MadTooler/Gobbit_Line_Commander/releases

Beta library for Gobbit and similar robots running line following.

**Comment by MadTooler** [comment]
Is there something else I need to do to have this added to the library manager?

Thanks

**Comment by matthijskooijman** [comment]
Nope, just have some patience. Libraries are manually added, usually a few of them together every now and then.

**Comment by MadTooler** [comment]
Cool.  I can do patience.  This was my first repository on github and attempt to have a library added to the list, and I was not sure I had made all the steps in full or entirely correct.

Thanks again.

**Comment by cmaglie** [comment]
Library added, thanks!
