### ISSUE TITLE
Add DatavisionLCD library

### ISSUE THREAD

**Issue by CsCrazy85** [arduino/Arduino#5719]
https://github.com/CsCrazy85/DatavisionLCD
DatavisionLCD library 1.0.0

**Comment by per1234** [comment]
Are you requesting your library to be added to Library Manager. If so you should review https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ:
>Your repo is ok if its root folder contains file library.properties and the rest of the library source code. If your library is stored into a subfolder, your repo it's not ok and we can't include your library in the list.

**Comment by facchinm** [comment]
Hi @CsCrazy85 ,
as @per1234 pointed out, your repo is not in the right form to be included in library manager. You need to move all the files from DatavisionLCD folder to the root of the repo.
No need to open another issue if you fix these things, so I closed #5720

**Comment by facchinm** [comment]
Library added, you need to modify https://github.com/CsCrazy85/DatavisionLCD/blob/master/library.properties#L2 to match the tag to make it appear in library manager (modify that line to 1.0.2 and tag 1.0.2 to do so).
Thanks!

**Comment by CsCrazy85** [comment]
Okay! I will do so! Thank you!
