### ISSUE TITLE
Simple Nokia5110 LCD library to print strings on screen

### ISSUE THREAD

**Issue by nitins11** [arduino/Arduino#5724]
Hi,

Submitting a simple Nokia5110 LCD library to print strings easily on the screen. None of the current LCD libraries or example codes on internet provide an easy solution to do so for Nokia5110 LCD. Below is the repository link:

https://github.com/nitins11/Nokia5110LCD

Happy to answer if any questions.

Thanks
Nitin

**Comment by cmaglie** [comment]
I've added the library to the indexer, BTW the tag 0.1 has a top library folder:

https://github.com/nitins11/Nokia5110LCD/tree/v0.1

instead your `master` branch has the correct layout (all files on the root of the git repo).
To fix this I suggest you to delete the tag `0.1` and redo it on master branch. Once done the library will be automatically published within an hour.

**Comment by nitins11** [comment]
Thanks Christian! I have re-created the tag v0.1 on the master now.

Let me know if there is any pending action on my side.

Thanks
Nitin
