### ISSUE TITLE
Revert Subtract one from USB_EP_SIZE in USB_SendSpace 

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#5732]
https://github.com/arduino/Arduino/pull/4864 introduced a bug that rawhid and the gamepad is not working anymore. This was reported by a lot of users now and should be reverted. There are lots of others suggestions to fix this bug, please go another way. This is definitely not the correct way and breaks multiple USB modules. The core should not try to fix CDC module bugs.

More details in the pr above and here: https://github.com/NicoHood/HID/issues/91

**Comment by NicoHood** [comment]
@facchinm @cmaglie People constantly contact me about this issue and I need to tell them to download the very old IDE 1.6.8 or 1.6.9 to fix this issue. Please revert the commit and then think of another fix.

**Comment by mnhpias** [comment]
I'm unable to work RawHID.write ,
I changed \libraries\HID\src\SingleReport\RawHID.h in line 50 from #define RAWHID_TX_SIZE RAWHID_SIZE to #define RAWHID_TX_SIZE 63 , then I sent 50 bytes long uint8_t throgh RawHID.write , but pc didn't receive anything . pls help me to make RawHID.write working .
