### ISSUE TITLE
rollingAverage function in Average.h library does not work

### ISSUE THREAD

**Issue by marciukasb** [arduino/Arduino#5733]
I have imported the Average library but none of the functions seem to work and even the examples in the package do not compile.

**Comment by Chris--A** [comment]
>I have imported the Average library

From the  library manager?
If so you should find the GitHub repo for that library and post the issue there.

**Comment by facchinm** [comment]
The Average library does not seem to be included in library manager. The closest one I could find is https://github.com/MajenkoLibraries/Average, which I tested and works well. If you could provide a link to the library we can try to understand if it's a core-related problem.

**Comment by marciukasb** [comment]
I have tryed two different versions of arduino and still none of the methods work. The description in http://playground.arduino.cc/Main/Average says that the library https://github.com/MajenkoLibraries/Average has a method RollingAverage that adds values to the array shifting all the values down one place and returns the average. I cannot find or use this method.

**Comment by per1234** [comment]
The new function for a rolling average in that [Average library](https://github.com/MajenkoLibraries/Average) is called [`rolling()`](https://github.com/MajenkoLibraries/Average/blob/master/Average.h#L113-L116), as was confirmed by the author here: https://github.com/MajenkoLibraries/Average/issues/8.

I have removed the obsolete documentation from http://playground.arduino.cc/Main/Average.
