### ISSUE TITLE
[website] Broken datasheet links on product pages

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5734]
The datasheet links on all the following product pages are broken:

- https://www.arduino.cc/en/Main/ArduinoBoardUno
- https://www.arduino.cc/en/Main/Robot
- https://www.arduino.cc/en/Main/ArduinoBoardMegaADK
- https://www.arduino.cc/en/Main/ArduinoBoardPro
- https://www.arduino.cc/en/Main/ArduinoBoardEthernet
- https://www.arduino.cc/en/Main/ArduinoBoardLilyPad
- https://www.arduino.cc/en/Main/ArduinoBoardYun - The link is missing but the "ATmega32u4 (datasheet)" in the text indicates that one was intended.

Originally reported at http://forum.arduino.cc/index.php?topic=442344

**Comment by akash73** [comment]
@per1234  thanks for notice.
we are managing it, I'll write once done.

thanks

**Comment by akash73** [comment]
Hi, pages are now corrected.
thanks
