### ISSUE TITLE
Another protype mis-insertion issue

### ISSUE THREAD

**Issue by alto777** [arduino/Arduino#5737]
The attached sketch will not compile with IDE 1.6.13.

If two blank lines are removed from apUNI8a.ino as stated in the comment preceding them, the sketch will compile.

The matter is discussed and concluded in

http://forum.arduino.cc/index.php?topic=442502.15

[apUNI8a.zip](https://github.com/arduino/Arduino/files/659704/apUNI8a.zip)

**Comment by bperrybap** [comment]
Here is some additional useful information:
If you insert a dummy line of C code at the bottom of apUNI8a.ino it will insert the prototypes correctly again.

**Comment by facchinm** [comment]
Moved to https://github.com/arduino/arduino-builder/issues/199
