### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by najkulime** [arduino/Arduino#5742]
Unable to contact the code compilation service. 

Please try again later or contact us if the problem persists.

I have tryed again later but this still appears. Any suggersions? It refers to this project:

https://circuits.io/circuits/3557330-the-unnamed-circuit

**Comment by matthijskooijman** [comment]
What is this about exactly? If it's about circuits.io, that's not related to Arduino at all. Or is this about the online Arduino IDE? Can you be more specific? Perhaps a screenshot of the error?

**Comment by najkulime** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/24657134/21360700/460b6680-c6e1-11e6-97a9-75c978d937e2.png)

**Comment by facchinm** [comment]
Hi @najkulime ,
indeed you should contact circuits.io guys (maybe via their support). we are not the right people to solve your problem :smile:
