### ISSUE TITLE
randomSeed should have unsigned long as parameter [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#575]
This is [Issue 575](http://code.google.com/p/arduino/issues/detail?id=575) moved from a Google Code project.
Added by 2011-08-05T07:31:16.000Z by [rob.till...@gmail.com](http://code.google.com/u/113198963792305667520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

OBSERVATION
------------
Wmath.cpp / Wprogram.h have defined randomSeed as

void randomSeed(unsigned int seed)
{
  if (seed != 0) {
    srandom(seed);
  }
}

while the avrlib defines - void srandom (unsigned long __seed);

This means loss of 2^32 -2^16 possible seeds to randomize.

PROPOSAL
--------

If you accept 0 as a valid seed you can rewrite it to: 

#define randomSeed(s) srandom(s)

otherwise

void randomSeed(unsigned long seed)
{
  if (seed != 0) srandom(seed);
}

See - http://arduino.cc/forum/index.php/topic,66206.msg505310.html#msg505310

// using windows 7/64 IDE 22

**Comment by facchinm** [comment]
Fixed by #3202
