### ISSUE TITLE
menu font looks like broken in ide-1.8.0

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#5750]
menu font looks like broken in ide-1.8.0:
[ide-1.8.0]
![ide_font_01](https://cloud.githubusercontent.com/assets/9634845/21454460/27493632-c95c-11e6-9c10-3aff6d96765e.png)

In the menu some Korean characters are not displayed completely and displayed like broken. Please compare with the below picture of IDE 1.6.13.  

[ide-1.6.3]
![ide_font_02](https://cloud.githubusercontent.com/assets/9634845/21444980/f101d54e-c8f6-11e6-9d2c-4fff3a22623c.png)

**Comment by facchinm** [comment]
Hi @Myriads ,
can you expand your bug report? Are you referring to Korean vs English for board names and programmers or something more subtle?

**Comment by Myriads** [comment]
![image](https://cloud.githubusercontent.com/assets/9634845/21454508/82546c86-c95c-11e6-81de-9830a9a28721.png)

![image](https://cloud.githubusercontent.com/assets/9634845/21454523/9b0d5d50-c95c-11e6-9bfd-a27d651d986f.png)

**Comment by SurfingDude** [comment]
Same problem in the English Language IDE. Going from 1.6.12 to 1.8.0 gives thinner letters in a font that is more difficult to read. The preferences dialog shows this quite clearly.

**Comment by cmaglie** [comment]
Which version of windows are you running?

**Comment by SurfingDude** [comment]
I am running Windows 10 Pro.

      ...glen

**Comment by cmaglie** [comment]
For some reason the antialias is gone.
Investigating...

**Comment by cmaglie** [comment]
It seems caused by this commit cf54cce that is part of #5578.
I'm looking for a solution.

**Comment by DougieLawson** [comment]
@cmaglie Do you need any additional docs, screenshots or stuff from a Windows 10 user?

Do you need anyone to alpha or beta test any fix you develop for this? Give me a download link and I'm quite happy to give things a try out (although not on Xmas day).

**Comment by cmaglie** [comment]
I managed to reproduce it on my pc so I'm ok for now, thanks!
A test build to try will be produced by @ArduinoBot once I have a fix.

**Comment by FernandoGarcia** [comment]
Hi @cmaglie !

This PR solve the problem to me.

Thanks.

Best regards.

**Comment by ameliaamelia** [comment]
I am using Arduino IDE 1.8.0 and Visual Studio 14 on Windows 10.
The font for both is "Input"; with IDE 1.6.13 all OK but with IDE 1.8.0 the fixed length is not taken in account:
SHORT  a;
BYTEu  b; (note the 'b' is slightly left shifted, like in this non fixed font post)
The font is correctly displayed.

amelia

**Comment by ameliaamelia** [comment]
Addendum:
If I use the font "Monospac821 BT" all is OK.

amelia

**Comment by DBenS** [comment]
Hi,
I'm using Windows 8.1 and Arduino IDE for Windows.
The editor has its font OK, but the message window is really very bad. I tried to change the font settings onto "preferences.txt" without any effect.

See below:
![image](https://cloud.githubusercontent.com/assets/13090884/21578875/269eade8-cf79-11e6-9629-5c7dea410c7e.png)

**Comment by PaulStoffregen** [comment]
@DBenS - This problem was fixed 3 days ago.  Download the latest nightly build version to get the fix.
