### ISSUE TITLE
Arduino Library (LBT) for LinkIt One not working

### ISSUE THREAD

**Issue by sjc2810** [arduino/Arduino#5751]
Hello,
I am working on a project for which I need Bluetooth connectivity. I am using the Bluetooth module present in the groove kit of linkit one. For the operation of this module the Bluetooth library LBT is needed which is provided with the linkit one sdk. This library is not working (It does not change its colour when declared and also does not give the required results). Its folder is already present in the Libraries yet it is not working.
Please help me asap as I'm not able to continue my work ahead.
Thanks in advance

**Comment by facchinm** [comment]
Hi @sjc2810 ,
we can't help you unless your problem is IDE-related. For anything else (including projects not working) you should refer to the right forum or support center (in this case Seeed Studio / Mediatek). Thanks
