### ISSUE TITLE
Incorrect mention of Pins in 74HC595 "one by one" tutorial"

### ISSUE THREAD

**Issue by BraveTea** [arduino/Arduino#5752]
https://www.arduino.cc/en/Tutorial/ShftOut12

I might be wrong  (for I haven't been doing this long), but I believe there is a mistake on the page above.

It states

Hardware:
 _* 74HC595 shift register attached to pins 2, 3, and 4 of the Arduino,
 as detailed below._

but also

_//Pin connected to latch pin (ST_CP) of 74HC595
const int latchPin = 8;
//Pin connected to clock pin (SH_CP) of 74HC595
const int clockPin = 12;
////Pin connected to Data in (DS) of 74HC595
const int dataPin = 11;_

the tutorial from where this linked also calls for a usage of board pins 8, 11, and 12. 

So I reckon the first mention in Hardware should be changed from 2,3,4 to 8,11,12

<img width="657" alt="screen shot 2016-12-23 at 11 10 14" src="https://cloud.githubusercontent.com/assets/24541185/21451596/814fc594-c900-11e6-82d8-f16bea40c5c7.png">

**Comment by akash73** [comment]
@BraveTea thanks for notice.
we have fixed the description.
