### ISSUE TITLE
I18N for compilation message - IDE1.8.0

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#5757]
The previous version IDE provides the L10N for compilation message but IDE1.8.0 doesn't:

> Sketch  uses 2660 bytes (8%) of program storage space. Maximum is 32256 bytes.
Global variables use 208 bytes (10%) of dynamic memory, leaving 1840 bytes for local variables. Maximum is 2048 bytes.

**Comment by facchinm** [comment]
Hi  @Myriads, that shouldn't happen since we preserved the wording when moving the sketch size calculation from the IDE to `arduino-builder`.
If I set the IDE language in Korean I get
```
스케치는 프로그램 저장 공간 9056 바이트(3%)를 사용. 최대 262144 바이트.
```
Is it correct? How can I replicate your configuration?

**Comment by Myriads** [comment]
Hi @facchinm. The message you got is correct. But in my case, evenif I set the IDE language to Korean, I always get the English messages.

**Comment by Myriads** [comment]
I replicated this. Please build resource files with update.sh and rebuild IDE, then messages are displayed in English.

**Comment by facchinm** [comment]
You are totally right; indeed 1a97ec448182c57bc8fc0278075f429f3877b2a2 removed the Java strings but the actual resources in 1.8.0 are correct (still don't know why). Anyway, I'm pushing the strings back and recreating the resources. Thanks for helping!
