### ISSUE TITLE
Multiple Arduino.cc Subdomains SSL Certificates expired

### ISSUE THREAD

**Issue by dlabun** [arduino/Arduino#5758]
I think that pretty much sums up the issue, the SSL cert expired today.

**Comment by NicoHood** [comment]
It seems that this only applies to downloads.arduino.cc. However I cannot build arduino packages anymore and I will not download them via http as no GPG signatures #5619 are available.

Test URL:
https://downloads.arduino.cc/cores

**Comment by dlabun** [comment]
You're right, I blew right through the homepage and didn't even realize it was a HTTPS connection. Somebody must have forgotten to update all of the subdomains with the new cert.

**Comment by Chris--A** [comment]
I'm getting the issue on forum.arduino.cc. It seems now it is forced over a https connection. Can't receive any data via http.

**Comment by PaoloP74** [comment]
Dear Santa Claus, please bring a new certificate to the Arduino Team.

**Comment by PaulStoffregen** [comment]
The forum also seem to be affected.

**Comment by Isaac100** [comment]
Yep, it definitely expired.
![image](https://cloud.githubusercontent.com/assets/24738852/21468686/15bbb510-c9ee-11e6-9c30-3de8fd0b1734.png)

**Comment by Isaac100** [comment]
I've figured out a temporary fix, set your computer's clock to before the expiration date(Dec 24).  On Firefox it should go automatically to the website and on Chrome the same error will come up, just click on advanced and click continue to website.

**Comment by matteosuppo** [comment]
Santa arrived with a brand new certificate

**Comment by mastrolinux** [comment]
Solved, thanks for the report
