### ISSUE TITLE
delayMicroseconds(0) delays far longer than expected. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#576]
This is [Issue 576](http://code.google.com/p/arduino/issues/detail?id=576) moved from a Google Code project.
Added by 2011-08-05T07:49:00.000Z by [rob.till...@gmail.com](http://code.google.com/u/113198963792305667520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
----------------------------------------

See - http://arduino.cc/forum/index.php/topic,68383.0.html

Due to predecrement of the param us, the function does not work as expected when the param is 0.

snippet of the code:

void delayMicroseconds(unsigned int us)
{
   if (--us == 0)
      return;
...
 

**What is the expected output? What do you see instead?**
------------------------------------------------------
Expected an immediate return;
See, long busy wait

**Please provide any additional information below.**
-------------------------------------------------

Fix proposed - http://arduino.cc/forum/index.php/topic,68383.msg504892.html#msg504892

replace
   if (--us == 0)
      return;

with (16 Mhz)
   if (us < 2) 
      return;
   us--;

Fix not tested.

**Comment by agdl** [comment]
See https://github.com/arduino/Arduino/issues/1121
