### ISSUE TITLE
[reference] WiFi.subnetMask() example code doesn't print the subnet mask

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5760]
Example code from https://www.arduino.cc/en/Reference/WiFiSubnetMask"
```arduino
    subnet = WiFi.subnetMask();
    Serial.print("NETMASK: ");
    Serial.println();
```
should be changed to:
```arduino
    subnet = WiFi.subnetMask();
    Serial.print("NETMASK: ");
    Serial.println(subnet);
```
Originally reported at http://forum.arduino.cc/index.php?topic=444008

**Comment by akash73** [comment]
@per1234 thanks for notice.
we have updated the example.
