### ISSUE TITLE
Arduino 1.8.0 can't compile sketch for the Maple Mini board

### ISSUE THREAD

**Issue by vicmic54** [arduino/Arduino#5763]
I'm using Arduino 1.8.0 IDE on Linux Mint 18. It works with original Arduino board, of course.

I installed Arduino_STM32-master to work with Maple boards. But when I try to upload sketch compiler says:

> fork/exec /bin/arm-none-eabi-g++: no such file or directory
> Ошибка компиляции для платы Maple Mini board.

    It means: _Compilation error for Maple Mini ._

What else I need to install for this board?

**Comment by cmaglie** [comment]
@vicmic54 
I'm sorry but we are not the maintainers of the STM32 port for Arduino.

I'd suggest to look for support on the repository/website where you downloaded the file (search for an issue tracker or better a forum).
