### ISSUE TITLE
[Improvement suggestion] Internal updater for the IDE

### ISSUE THREAD

**Issue by HackerInside0** [arduino/Arduino#5765]
It would be nice to add an internal updater for the IDE, as already happens with the library manager for libraries.
Because it's a hassle to care about manual updates when Ubuntu's repos are stuck to Arduino 1.0.5

**Comment by NicoHood** [comment]
Complain at Ubuntu and not here. It does not make sense to code workarounds (at least for linux) if proper OS integration via packages can be achieved. ArchLinux provides arduino packages :P
