### ISSUE TITLE
Can't download from IDE

### ISSUE THREAD

**Issue by ormet** [arduino/Arduino#5769]
Good morning, 
I can't download any boards from IDE.
It starts to download but after any seconds it stop and make an error.

**Comment by PaulStoffregen** [comment]
Maybe copying and pasting the error here, or taking a screenshot to share if the text can't be copied, might be a good idea?  Also consider how little anyone knows about what you're doing.  We can't see what you did, which things you clicked, how to installed.  In fact, nobody can tell which version of Arduino you're really using, or even which operating system you have.

Can you understand how this lack of information makes investigating and solving your problem pretty much impossible?
