### ISSUE TITLE
IDE/Serial Monitor freezes on single live overrun [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#578]
This is [Issue 578](http://code.google.com/p/arduino/issues/detail?id=578) moved from a Google Code project.
Added by 2011-08-05T16:13:43.000Z by [mausb...@gmail.com](http://code.google.com/u/105956539693444794743/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. create a sketch that output data at 115200 using Serial.write(), and sends random values from 0x00 to 0xFF at max rate (as in unformatted values from a digital accelerometer)
2. Download sketch and run, open serial monitor as soon as RX/TX LEDs go dark after download.
3. Watch serial data spew onto the top line of the serial monitor window (make sure autoscroll is checked) and wait for a few seconds. Data will stop, the system will freeze, Java will go zombie, etc.

**What is the expected output? What do you see instead?**
Expected output is a constant stream of serial characters, without crashing.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 22 on Win7Pro SP1 on an Intel Corei7 laptop.
Arduino is a Sparkfun Mini Pro 328/8MHz/3.3 via a Sparkfun 3.3V FTDI Basic Breakout.

**Please provide any additional information below.**
This issue is easily and regularly repeatable on my system. If I insert the CRLF characters at the end of each line like the autoscroll system expects, it works correctly. Fat fingering 0x0D 0x0B (vertical tab) instead causes the crash as well as no line termination characters.

**Comment by ffissore** [comment]
Fixed with #2491

**Comment by dejanmeznarc** [comment]
I'm having same problem with 1.8.9
