### ISSUE TITLE
https://www.arduino.cc/en/Serial/ReadBytesUntil Documentation Formatting

### ISSUE THREAD

**Issue by HydrOptix** [arduino/Arduino#5784]
Documentation of Serial.readBytesUntil parameters currently reads:
> character : the character to search for (char)
buffer: the buffer to store the bytes in (char[] or byte[]) length : the number of bytes to read (int)

the documentation should read to prevent confusion:
> character : the character to search for (char)
buffer: the buffer to store the bytes in (char[] or byte[])
length : the number of bytes to read (int)"

**Comment by akash73** [comment]
@HydrOptix thanks for notice.
we have updated the documentation
