### ISSUE TITLE
[reference] Incorrect Ethernet controller chip names in Ethernet library reference

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5785]
From https://www.arduino.cc/en/Reference/Ethernet:
>Ethernet library (Ethernet.h) manages the WINC5100 chip, while Ethernet2 library (Ethernet2.h) manages the WINC5500 chip

The correct names are W5100 and W5500. The WIZnet website and datasheets for these parts make no mention of WINC5100 or WINC5500 and a search for either of these terms returns only the Ethernet library reference page as relevant results.

**Comment by facchinm** [comment]
Fixed, thanks!
