### ISSUE TITLE
access time of reference menu

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#5787]
Even though reference contents ara located at the local high speed SSD, the reference menu of the Arduino IDE takes much longer and sometimes irregular(erratic) than accessing the reference menu of Arduino Home page through Internet. 

Chrome browser used.

**Comment by Chris--A** [comment]
Might be best to find the reference in the Arduino install folder. Then open directly in the browser.
As I have html files set to open by default in Notepad++ the link does not even work for me.

**Comment by per1234** [comment]
This should no longer occur now that the local reference content has been removed (https://github.com/arduino/Arduino/pull/11495). The menu items now simply open the relevant page from arduino.cc directly.
