### ISSUE TITLE
New Libraries: MD_Parola and MD_MAX72xx

### ISSUE THREAD

**Issue by MajicDesigns** [arduino/Arduino#5788]
Please add these libraries to the IDE supported list.

These libraries (together) enable scrolling text with text effects on LED matrix modules. Parola is dependent on MAX72xx.

https://github.com/MajicDesigns/MD_Parola
https://github.com/MajicDesigns/MD_MAX72XX

**Comment by cmaglie** [comment]
The libraries have been added to the index but the repositories don't have tags.

https://github.com/MajicDesigns/MD_Parola/tags
https://github.com/MajicDesigns/MD_MAX72XX/tags

Please create a tag and name it with the version number (for example "2.6" or "v2.6"). Once done the libraries will be automatically published within an hour.
