### ISSUE TITLE
Add ArduinoMqtt to the library manager

### ISSUE THREAD

**Issue by monstrenyatko** [arduino/Arduino#5791]
Please add the ArduinoMqtt to the library manager.

https://github.com/monstrenyatko/ArduinoMqtt

Thank you.

**Comment by cmaglie** [comment]
The library has been added to the index but the repository doesn't have tags.

https://github.com/monstrenyatko/ArduinoMqtt/tags

Please create a tag and name it with the version number (for example "1.0.0" or "v1.0.0"). Once done the library will be automatically published within an hour.

**Comment by monstrenyatko** [comment]
I'll do tag(release) soon. Thank you very much.
