### ISSUE TITLE
Got wrong when try multiplication different data type

### ISSUE THREAD

**Issue by Lexander24** [arduino/Arduino#5793]
Hello, 
I'm doing multiplication float and storage using long. Because i want to do modulo operation.

The bug is when i multiplied 9.9997 or 8.9997 with 10000 and storage to long.

Anyone know to solved this issue? Because i didn't know how many other value will error

**Comment by matthijskooijman** [comment]
I suspect you're either running into the automatic type conversion rules of the C++ language, or the inexactness of floating point numbers (which can sometimes round things in unexpected ways). In any case, this github tracker is for bugs and improvements in the Arduino environment, not for help with problems in your own code. I recommend you ask this question on the forums, and be sure to include the code you used, as well as the (unexpected) outcome you get.
