### ISSUE TITLE
https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard unclear which programmer to use and how to replace bootloader for crystal.

### ISSUE THREAD

**Issue by codytheking** [arduino/Arduino#5806]
It is not clear that when burning the bootloader that you choose the programmer under tools as "Arduino as ISP." This should be it's own bullet point before the last step of choosing "Burn Bootloader" under "Tools."

It is also never stated that if the ATmega328 already has a bootloader that requires a crystal, you cannot burn a bootloader to use the internal oscillator without an extra crystal (at least not using the instructions given on the page) because the chip will not run without a crystal in the first place.

**Comment by facchinm** [comment]
The tutorial looks pretty good to me (if you read it entirely). 
+1 for the programmer choice to be highlighted with its own bullet point
-1 for the second observation: it works on a brand-new ATMEGA328, since factory fuses are configured to use the internal 1Mhz oscillator

**Comment by akash73** [comment]
Added the own bullet point to the doc. https://www.arduino.cc/en/Tutorial.ArduinoToBreadboard
thanks for notice it.
