### ISSUE TITLE
Please add new library to download manager

### ISSUE THREAD

**Issue by lperez31** [arduino/Arduino#5812]
v1.0.0 of library to connect to YouMadeIt! service is here:
[https://github.com/lperez31/youmadeit-arduino/tree/1.0.0](https://github.com/lperez31/youmadeit-arduino/tree/1.0.0)

Thanks.

**Comment by Chris--A** [comment]
You have copied the ArduinoJson library into your library.

This library is already in the library manager: https://github.com/arduino/Arduino/issues/3703

**Comment by lperez31** [comment]
Sorry, I don't find in the documentation how I can specify ArduinoJson as a requirement. How can I achieve this?

Thanks.

**Comment by lperez31** [comment]
I removed ArduinoJson code from my library. Can you please add it to the library manager?

https://github.com/lperez31/youmadeit-arduino/releases/tag/1.0.1

Thanks again.

**Comment by Chris--A** [comment]
I was just pointing it out.
You do not have to remove it, but there could be issues if someone is using the ArduinoJson lib and yours.
You could simply add it as a requirement to your documentation.

**Comment by lperez31** [comment]
OK, thanks for pointing it out. I added the requirement in the documentation.

**Comment by cmaglie** [comment]
Done!
