### ISSUE TITLE
It would be nice to be possible to hava some tabs of the project closed while coding.

### ISSUE THREAD

**Issue by mgameiro** [arduino/Arduino#5818]
For bigger projects the tabs can be confusing if they are all opened at the same time.

**Comment by facchinm** [comment]
Hi @mgameiro ,
I understand your point, but the open tabs *are* the project itself. Right now, if you close a tab its backing file will be deleted (and thus not compiled).
Adding an extra layer of UI (closed tabs) will make it difficult to understand what is being compiled.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/2883
