### ISSUE TITLE
Blank line inserted without error on "Sketch -> Import Library"

### ISSUE THREAD

**Issue by JulienPalard** [arduino/Arduino#5822]
I'm trying to compile with http://playground.arduino.cc/Main/LedControl, so:

- I downloaded the LedControl-1.0.6.zip archive from github
- Added it using "Sketch -> Import Library -> Add Library"
- Restarted Arduino because nobody knows
- Clicked on "Sketch -> Import Library -> LedControl" (happily present in the list)
- Got a new blank line without an error instead of an import statement (obviously won't compile).

I'm using arduino from Debian package:
```
$ apt-cache policy arduino
arduino:
  Installed: 2:1.0.5+dfsg2-4.1
```

**Comment by per1234** [comment]
>`  Installed: 2:1.0.5+dfsg2-4.1`

That's a very outdated and non-standard version of the Arduino IDE. Please try using the latest official version downloaded from http://www.arduino.cc/en/Main/Software
