### ISSUE TITLE
Add DFW Library to Library Manager

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#5828]
https://github.com/WPIRoboticsEngineering/DFW

This is a library to support autonomous/tele-op change over code for competition robots. This library is used by WPI RBE program to teach robotics engineering to college students.

**Comment by madhephaestus** [comment]
In addition to this library we will have a large collection of robotics libraries, would it be appropriate to post an issue with a list of libraries to add, or should I stick to the one-issue-one-library convention?

**Comment by cmaglie** [comment]
One issue for all libraries is OK!

**Comment by cmaglie** [comment]
The library has been added.
