### ISSUE TITLE
Pin Monitor

### ISSUE THREAD

**Issue by mgameiro** [arduino/Arduino#5834]
It would be nice to add a new monitor to Arduino IDE, the Pin Monitor. This Monitor would allow people to see in realtime the logic state of the Pins from Arduino.

**Comment by matthijskooijman** [comment]
Interesting idea, though I do not think it is feasible. Adding something like that would require software running on the Arduino itself, communicating with the IDE through serial, which is hard to combine with a user-written sketch.

If you need something like this, there are third-party solutions available, such as Firmata. I recommend you look into those for your own needs, but integrating something like this in the IDE is probably out of scope for the IDE.

I'll go ahead and close this issue. If you have further comments, feel free to post them here regardless.
