### ISSUE TITLE
Why does user need to manually pick library version to update to? And why no "update all" button?

### ISSUE THREAD

**Issue by electronicsguy** [arduino/Arduino#5839]
Arduino IDE shows a popup saying some libraries need to be updated. When I goto the library manager, I must manually select the version to update to. This seems unnecessary. The GUI should select the latest version by default for all updatable packages. If someone wants a different version, they could just pick that. 
![arduino-update](https://cloud.githubusercontent.com/assets/5799357/21879298/b3727ebe-d8bd-11e6-86bb-86bf15409145.JPG)

Secondly, I don't see any "update all" button. Am I missing that?

**Comment by facchinm** [comment]
Hi @electronicsguy ,
the "Update" button will automatically update to the latest version available if you don't click the dropdown. And the "Update all" button is not there for safety reasons (you could have modified a library and accidentally click that button, losing all your changes)

**Comment by electronicsguy** [comment]
Thanks. So if we infact have modified a library, does the update manager do a 3-way merge?

**Comment by facchinm** [comment]
Nope, it completely overwrites the modified library, replacing it with the new one. Very dumb but effective :slightly_smiling_face:
