### ISSUE TITLE
New CONTROLLINO-PLC library

### ISSUE THREAD

**Issue by CONTROLLINO-Support** [arduino/Arduino#5841]
Hello,
we prepared a new Arduino library for Arduino compatible device-CONTROLLINO.
We would like to add it to the Arduino IDE Library Manager. Would it be possible to check if the GitHub repository is in correct format and add it to the Library Manager please?

Our GitHub repository: https://github.com/CONTROLLINO-PLC/CONTROLLINO_Library

Thank you,
CONTROLLINO team

**Comment by cmaglie** [comment]
Done!
