### ISSUE TITLE
Add FingerLib to library manager

### ISSUE THREAD

**Issue by OllyMcBride** [arduino/Arduino#5842]
https://github.com/Open-Bionics/FingerLib

This library allows for servo-like functionality for finger control. For Atmega 2560 (Almond PCB) and Arduino Zero (Chestnut) boards.

FingerLib.h has been designed to closely resemble the Servo.h library, to allow ease of implementation for hobbyists and researchers. 

Thanks

**Comment by cmaglie** [comment]
Done!
