### ISSUE TITLE
Web Editor Error 403 Forbidden

### ISSUE THREAD

**Issue by poiu2463** [arduino/Arduino#5846]
When I try and access the web editor it gives me this error code. I am trying to access on a Chromebook C720 (Which may be my problem anyways). The error shows up specifically when I try to download the plugin. When I click the download plugin button it redirects me to the 403 error page (Screenshot below)
![screenshot 2017-01-13 at 9 58 20 am](https://cloud.githubusercontent.com/assets/25104333/21934345/111c792a-d977-11e6-8f0b-0925e8fff256.png)

**Comment by facchinm** [comment]
Hi @poiu2463 ,
what is the url in the titlebar when you get the 403? It's missing in the screenshot... :slightly_frowning_face:

**Comment by poiu2463** [comment]
http://downloads.arduino.cc/CreateBridgeStable/

**Comment by poiu2463** [comment]
Hi, Sorry for the delay. The url is: http://downloads.arduino.cc/CreateBridgeStable/ 
@facchinm

**Comment by poiu2463** [comment]
![screenshot 2017-01-17 at 11 52 46 am](https://cloud.githubusercontent.com/assets/25104333/22030396/7f0e2e06-dcab-11e6-9af0-cd6a62121ecb.png)

**Comment by poiu2463** [comment]
![screenshot 2017-01-17 at 11 54 16 am](https://cloud.githubusercontent.com/assets/25104333/22030472/b3c55598-dcab-11e6-8823-f19b1f964584.png)

**Comment by poiu2463** [comment]
![screenshot 2017-01-17 at 11 54 45 am](https://cloud.githubusercontent.com/assets/25104333/22030492/c2fd7ef0-dcab-11e6-9e83-8046cecd3eba.png)

**Comment by mastrolinux** [comment]
Hi @poiu2463 We currently do not support Chromebooks and that's why you get that error. We have a working prototype to support Chromebooks but it is not yet released.
I am closing this issue for now but I can assure you we are working on it on the Arduino Create Web Editor project.

**Comment by mastrolinux** [comment]
We released a Chromebook app now available on the official store. You can directly go to the Create Editor and try again.
