### ISSUE TITLE
Add "Clear" button to Serial Monitor UI.

### ISSUE THREAD

**Issue by rlaferla** [arduino/Arduino#5849]
Many times, your Arduino is spitting out a ton of data and you want to manually clear the monitor.  The only way currently (AFAIK) is to restart the app.  I'd like to see a "Clear" button on the GUI that when pressed clears the monitor.

I looked at the code and this could be easily added to SerialMonitor and AbstractTextMonitor with some code similar to below:

```
protected JButton clearButton;

protected void onCreateWindow(Container mainPane) {
  // after adding send button
  clearButton = new JButton(tr("Clear"));
  upperPane.add(clearButton);
}

  public void onClearCommand(ActionListener listener) {
    clearButton.addActionListener(listener);
  }

protected void onEnableWindow(boolean enable) {
  // other code
    clearButton.setEnabled(enable);
}

// and in Serial Monitor.java

    onClearCommand(new ActionListener() {
          public void actionPerformed(ActionEvent e) {
              textArea.setText("");
          }
    });

```

**Comment by lpasqualis** [comment]
+1

**Comment by agdl** [comment]
@rlaferla you are right there is no button, anyway if you click again on the baud rate the Serial monitor is cleared (faster than close/open again the monitor). Anyway on boards like the UNO this means a board reset

**Comment by cmaglie** [comment]
Fixed by https://github.com/arduino/Arduino/commit/99006fc5c68115a55b01b796a50d6a904c9b716c

Thank you!
