### ISSUE TITLE
Arduino101: Serial.print() rounding error

### ISSUE THREAD

**Issue by jverive** [arduino/Arduino#5851]
Serial.print() gives 0.00 instead of 1.00 for values in () from 0.995 thru 0.999 when run on Arduino101. The rounding errors are not occurring with the Arduino Mega 2560, Arduino Uno, and Uno clones I have tested. 

I'm using Arduino IDE 1.8.1 with Intel Curie Arduino101 boards file 1.0.7. - I have not tried other boards files or IDE versions.

**Comment by oqibidipo** [comment]
01org/corelibs-arduino101#339

**Comment by facchinm** [comment]
Indeed, it's solve in mainline and the patch will be published soon with core 2.0.0.
Closing the issue here and keeping track on corelibs-arduino101 repo
