### ISSUE TITLE
Please add these libraries to the Library Manager Index

### ISSUE THREAD

**Issue by bhagman** [arduino/Arduino#5853]
Hiya!

I've got a few libraries to add to the Arduino Library Manager index.

https://github.com/bhagman/ControlledServo
https://github.com/bhagman/LitSwitch
https://github.com/bhagman/MillisTimer
https://github.com/RogueRobotics/RogueMP3
https://github.com/RogueRobotics/RogueSD
https://github.com/RogueRobotics/SmartDial
https://github.com/bhagman/SoftPWM
https://github.com/bhagman/Tone
https://github.com/bhagman/WireData

Thank you!

**Comment by cmaglie** [comment]
Done!
