### ISSUE TITLE
Document Wire.setSpeed() in Reference page

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5865]
CMIIW, but I think  there is a documentation missing about 
set i2c speed on ARM (Due) to 400kHz 
(FAST-i2c, i2c master, perhaps even a setting for slaves?)

**Comment by shiftleftplusone** [comment]
so as this website
http://playground.arduino.cc/Main/WireLibraryDetailedReference
refers only to ATMega and perhaps dofferent AVRs - is everything what's written here also true for the ARM MCUs or not? 
or which is true, and which not?

**Comment by facchinm** [comment]
Playground is user-generated content, so you shouldn't take it as reference; the actual Wire documentation is https://www.arduino.cc/en/Reference/Wire, which applies to both AVR and ARM. The I2C speed can be changed using `Wire.setClock()` which unfortunately is not documented on that page. I'll change the issue title to underline that we need to fix the Reference.

**Comment by akash73** [comment]
@shiftleftplusone thanks for notice.
Reference page added 
https://www.arduino.cc/en/Reference.WireSetClock

**Comment by shiftleftplusone** [comment]
thank you for adding the reference page,
Nonertheless, the site
https://www.arduino.cc/en/Reference/Wire
does not load

**Comment by shiftleftplusone** [comment]
thank you, now the reference ist listed!
