### ISSUE TITLE
Unnecessarily slow Ethernet interfaces due to none ideal SPI clock

### ISSUE THREAD

**Issue by DieterBurandt** [arduino/Arduino#5870]
(Arduino 1.6.18.1)

On default the W5500 is running with a 8MHz SPI clock with up to 359.712kb/s transfer rate to a PC.

Using an Arduino Due board the W5500 can run with a 28MHz SPI clock with up to 505.500kb/s transfer rate to a PC.

The SPI clock rate depends on the CPU (board), the W5500, and the layout of the board. Experience user should have a chance to choose his own SPI clock settings.

Please implement a simple method that users can set the SPI speed (e.g. like implemented in SD.cpp already).

**Comment by facchinm** [comment]
Hi @DieterBurandt ,
are you using Adafruit's Ethernet2 library? https://github.com/adafruit/Ethernet2 In this case you'd better open an issue to their repo about exposing a function to allow overriding
```
SPISettings wiznet_SPI_settings(8000000, MSBFIRST, SPI_MODE0);
```
