### ISSUE TITLE
Trouble with static buffer sizes within the I2C libray.

### ISSUE THREAD

**Issue by DieterBurandt** [arduino/Arduino#5871]
(Arduino 1.6.18.1)

- I2C communication:

The I2C buffer has a fixed size of 32byte in the Arduino library. If you like to use an EEPROM with a page size of e.g. 128 byte, then you must patch the buffer size in the Arduino library.

Please implement a simple method, that the user can set the size of the buffer from within the project (AVR, SAM, and SAMD(?)).

(SAM: "Wire.h" => "#define BUFFER_LENGTH 32")

**Comment by agdl** [comment]
This issue was moved to arduino/ArduinoCore-sam#19
