### ISSUE TITLE
BUG: EEPtr++ is incorrectly equivalent to ++EEPtr

### ISSUE THREAD

**Issue by eric-wieser** [arduino/Arduino#5874]
See [these lines](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/EEPROM/src/EEPROM.h#L100-L101).

Post-increment is supposed to return the value before the increment occured.

However, the `,` operator is a sequence point, so despite attempts to the contrary, the result here is that the value after the increment is returned.

Pinging @Chris--A

**Comment by Chris--A** [comment]
@eric-wieser Good find. I'll definitely patch this to my changes (https://github.com/arduino/Arduino/compare/master...Chris--A:EEPROM_2.1)

**Comment by eric-wieser** [comment]
Actually I'm wrong, and this is all fine

**Comment by Chris--A** [comment]
nice. I had not even started to test it. But yeah, I too mixed up the overloads on first glance.
