### ISSUE TITLE
Add the <typetraits> header

### ISSUE THREAD

**Issue by eric-wieser** [arduino/Arduino#5876]
Since all of this part of the STL runs at compile-time, arduino being an embedded platform is not a good reason to exclude it.

In particular, things like `std::remove_reference` are needed to implement #5875

**Comment by cmaglie** [comment]
Why you say it's excluded? AFAIK the build of the toolchain did not exclude anything, maybe those are not implemented yet for AVR?

**Comment by eric-wieser** [comment]
You're right, this is really a complaint against avr, not against arduino.

It might be nice if arduino could provide it to make up for its absense from avr though

**Comment by cmaglie** [comment]
Ok the question is then, where we can find a good implementation of them? I think that Arduino doesn't have enough resources to maintain his own implementation of the standard C++ lib.

**Comment by matthijskooijman** [comment]
uclibc++ has a decent implementation (also available in a few Arduino libraries), though it is incomplete (especially most of C++11 is missing). Not sure if `type_traits` is among it.

**Comment by cmaglie** [comment]
Closing this as wontfix.
