### ISSUE TITLE
example code update needed: File / Examples / LiquidCrystal / CustomCharacter

### ISSUE THREAD

**Issue by birozso** [arduino/Arduino#5895]
The purpose of the post is in the SUBJECT line.

It is the update of the example file of arduino IDE.  It does not show the I<3 Arduino sentence of the first row of the LCD. Missing setting position of the LCD writting. So i added this. 

In red you can see my added lines, which correct the original code and make it work.

path of original code, should change:
File / Examples / LiquidCrystal / CustomCharacter
(CustomCharacter.ino)

i hope it is clear . 
[CustomCharacter.zip](https://github.com/arduino/Arduino/files/721077/CustomCharacter.zip)
![customchar_added](https://cloud.githubusercontent.com/assets/25263987/22173935/0802f250-dfd1-11e6-895b-952798cda2c6.png)

regards

**Comment by per1234** [comment]
See https://github.com/arduino-libraries/LiquidCrystal/pull/13

**Comment by facchinm** [comment]
Closing as duplicate
