### ISSUE TITLE
Add SimplyAtomic to library manager

### ISSUE THREAD

**Issue by wizard97** [arduino/Arduino#5901]
Created the [SimplyAtomic](https://github.com/wizard97/SimplyAtomic) library to create a portable version of the useful `ATOMIC_BLOCK(ATOMIC_RESTORESTATE) ` that only works on AVR. My version works on AVR, ARM, and the ESP8266.

https://github.com/wizard97/SimplyAtomic

**Comment by agdl** [comment]
Done thank you!
