### ISSUE TITLE
Suggestion - IDE - Libraries

### ISSUE THREAD

**Issue by rogwabbit** [arduino/Arduino#5904]
Could we add an external Library folder option, This allows upgrading of IDE to not delete existing separate user made or downloaded libraries.

**Comment by per1234** [comment]
This feature already exists. It's called the sketchbook. The sketchbook location is set at **File > Preferences > Sketchbook location**. You should always install libraries to {sketchbook folder}/libraries. Don't ever install anything except the IDE to the Arduino IDE installation folder.

**Comment by facchinm** [comment]
:+1:  for @per1234 explanation. The sketchbook does not get erased when you update the IDE and the libraries in there shadow the bundled ones. So if you need to modify a bundled library, simply copy its folder in the sketchbook, modify it and it will never be touched by the IDE
