### ISSUE TITLE
Add new library (Shield driver): PC Joystick Shield

### ISSUE THREAD

**Issue by jelson** [arduino/Arduino#5906]
https://github.com/lectrobox/PCJoy

**Comment by shiftleftplusone** [comment]
helle,
a great idea!
Just out of interest, as it is absolutely inevitible:

is this shield 3.3V Arduino-ARM compatible ? (DUE, ZERO, M0 ) ?

**Comment by agdl** [comment]
Done thank you!

**Comment by jelson** [comment]
@shiftleftplusone Thank you! It should be, but I just bought one to test and make sure.
