### ISSUE TITLE
MKRZero freezes when using Scheduler

### ISSUE THREAD

**Issue by simplecast** [arduino/Arduino#5916]
I have 2 new Arduino mkr 2 i was  looking for a way to do multi-tasking  i used this in my my code and tried it twice to confirm now both mkrzeros wont upload, won,t been seen by Arduino IDE but the computer sees it, i can't upload a empty sketch nothing everything i tried has failed

**Comment by shiftleftplusone** [comment]
which Scheduler lib? there are at least 3 different ones, all named "Scheduler"

**Comment by cmaglie** [comment]
> won't been seen by Arduino IDE but the computer sees it

Try this: push **quickly** the reset button two times, this should put the board into "bootloader" mode and allow you to upload again.

**Comment by per1234** [comment]
@simplecast did you try the instructions that cmaglie provide? If so, did they solve the issue for you?

**Comment by per1234** [comment]
Closing due to lack of response from @simplecast.
