### ISSUE TITLE
2 repos for the same library

### ISSUE THREAD

**Issue by Rotzbua** [arduino/Arduino#5925]
There 2 repos from arduino for the same library.

For example the Ethernet library:
 - https://github.com/arduino-libraries/Ethernet
 - https://github.com/arduino/Arduino/tree/master/libraries/Ethernet

Some issues were moved from the main repo to the other repo by moderator. But they maintain both? Or how I have to understand this construction?

The source code is doubled without synchronisation. So the question: where should the PR/issues be?

**Comment by njh** [comment]
See also #5908

**Comment by Rotzbua** [comment]
@njh That's not the answer. I updated my description.

**Comment by njh** [comment]
Sorry, I was not attempting to answer your question, I was simply trying to gather some of the issues together.

Both the Ethernet and Ethernet 2 shields have not been getting a lot of love recently - there are a lot of outstanding issues. While there are people willing to help solve problems and make improvements, there needs to be some leadership around what the plan is.

You issue highlights some fundamental problems around what the authoritative source of code is and where issues should be reported.

**Comment by cmaglie** [comment]
Please send new PR/issues to https://github.com/arduino-libraries/Ethernet.

We have not removed yet the copy of the library in this repository to preserve existing pull requests, but we'll do soon, I'm in the process of evaluating various alternatives to move forward this library (including, but not all: #2325, @PaulStoffregen's [fork](https://github.com/PaulStoffregen/Ethernet), [Ethernet2](https://github.com/adafruit/Ethernet2) and a bunch of other patches people sent me).

**Comment by njh** [comment]
Good news, thanks @cmaglie 😃
