### ISSUE TITLE
WireWrapper library

### ISSUE THREAD

**Issue by SMFSW** [arduino/Arduino#5931]
WireWrapper library (derived from cI2C library):
https://github.com/SMFSW/WireWrapper

**Comment by shiftleftplusone** [comment]
I filed  an issue about
misleading: 400 kHz is Fast speed, not Low Speed !

could you additionally please work out a little more about the pros and cons to Wire.h ?

**Comment by SMFSW** [comment]
Hello,

thanks for the feedback, I'll update speed in the day (for both WireWrapper & cI2C libs).

I'll try to explain some more about Pros & Cons to Wire.h on both WireWrapper & cI2C libraries.
About WireWrapper, it basically automates calls to Wire lib functions to perform read/write transactions in one call.

**Comment by shiftleftplusone** [comment]
now I see, thank you very much for considering the changes!
kind regards!

**Comment by SMFSW** [comment]
changes done!

**Comment by cmaglie** [comment]
Library added, thanks
