### ISSUE TITLE
Publish command line option help

### ISSUE THREAD

**Issue by chrisspen** [arduino/Arduino#5933]
This is a feature request. Could you please add a standard command line `--help` parameter to publish the [man page documentation](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) via the command line? It's confusing that there's now an official command line interface, but you can only find documentation of that interface by digging through the code on Github.

**Comment by facchinm** [comment]
PR https://github.com/arduino/Arduino/pull/4765 applies perfectly, please continue the discussion there :slightly_smiling_face:
