### ISSUE TITLE
Web Editor plugin not working: cannot upload to MKR 1000

### ISSUE THREAD

**Issue by oliver-gilmour-twi** [arduino/Arduino#5939]
Hi,

I'm using Windows7, 64 bit. The computer is a company one, so all internet traffic goes through HTTP proxy.
I'm also using Firefox 47.0.2. 

I've installed the plugin, and that seems to be working (I see the green and black Arduino icon on the system tray), and I go to the Arduino Web Editor, but I keep getting the message "No Plugin Connection. Uploading is disabled until you reconnect".

I've installed the driver (because I've also installed desktop IDE - there's another bug there because of proxy implementation, but that's another story) and the system does recognise the Genuino MKR 1000 board. I just can't program it.

**Comment by facchinm** [comment]
Hi @oliver-gilmour-twi ,
I'm moving the issue to the correct repository (https://github.com/arduino/arduino-create-agent) . The plugin is currently unaware of proxies so any failure is expected. We'll update it soon with all the needed stuff. Thanks for your patience
