### ISSUE TITLE
missing documentation: how to include new 3rd-party libs manually?

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/Arduino#5949]
hello,
I can't find a documentation about  how to include completely new libs manually, accordingly.
About libaries there is just 1 topic to be found, but that's about writing own libraries.

http://playground.arduino.cc/Code/Library

e.g., there are many Scheduler Libs, but in the Arduino IDE no single one of them is listes beyond 
Sketch/include library/,
neither in the section "Arduino" , nor in "recommended", nor in "contributed"
and also it's not listed by 
Sketch/manage library/

I also don't want to add a zip lib automatically because it's too vague, too obscured what's happenning then and too uncertain where it's stored and how it may be removed, re-edited, replaced, back-up'ed or restored in case of unintentional deletion.

So in which folder have the libs to be copied accordingly?
Although
c:\programs(x86)\Arduino\libraries\
is commonly known for the original Arduino libs folder - which alternatives do exist, e.g. especially for IDE-update-safety purposes? Eventually this subfolder vanishes in case of uninstallations.

So how to create a proprietary folder which contains all proprietary libs which one once  has picked up and gathered together and which are designed to work also for all Arduino IDE updates in the future, even after complete IDE uninstall and new install with the Windows installer or the non-admin zip container from the scratch?

Where  is the final guide in the references which explains all that?
Nothing to be found by the search in the Playground or in the References.

**Comment by per1234** [comment]
See the "Manual Installation" section of https://www.arduino.cc/en/Guide/Libraries.

However, I must say those instructions are just terrible:
- They don't account for the fact that the user might not be using the default sketchbook location.
- They don't account for the 1.5 library format. In fact just today I helped someone on the forum who was trying to apply those instructions to a manual installation of a library in 1.5 format and they were very confused that the official documentation was completely wrong.

**Comment by shiftleftplusone** [comment]
I do not even see something about 1.5 library format or either other one or what's the difference anyway!

**Comment by cmaglie** [comment]
The place to add your own libraries is `SKETCHBOOK/libraries/YourLibrary/...`.

FWIW when you install a library with the library manager or "from zip", it will be unzipped the path above.

**Comment by cmaglie** [comment]
@akash73 the section "Manual Installation" of https://www.arduino.cc/en/Guide/Libraries should be revised with @per1234 suggestions, also the procedure described is a bit confusing.

**Comment by shiftleftplusone** [comment]
I have no Sketchbook folder, I am using 3 different USB drives with 3 different paths  randomly.
So a dedicated user-defined path on c:\ or d:\ is needed!

**Comment by cmaglie** [comment]
> So a dedicated user-defined path on c:\ or d:\ is needed!

Set your sketchbook folder to that path from preferences

**Comment by shiftleftplusone** [comment]
aha!  
So if the path is
d:\libs
will I have to set
d:\libs\
or
d:\libs\libraries\
:?:

**Comment by cmaglie** [comment]
if you set `D:\mylibs` you should put the libraries into `D:\mylibs\libraries\...`.
Basically you're using `D:\mylibs` as sketchbook, a bit weird but it should work.

**Comment by shiftleftplusone** [comment]
I see,  that was the missing information!
Thank you very much!

**Comment by akash73** [comment]
hi all,
page reworked and published.
thanks for notice.

**Comment by shiftleftplusone** [comment]
thank you very much, very comprhensible indeed.

> Arduino libraries are managed in three different places: inside the IDE installation folder, inside the core folder and in the libraries folder inside your sketchbook. The location of your sketchbook defaults to “..\<you>\DOCUMENTS\Arduino” on Windows machines. The path is clearly shown in the Preferences panel. If you want to see where the sketchbook defaults open Preferences under File. 

> 

Just 1 question:
where is the core folder?
