### ISSUE TITLE
SD library reference doesn't document File::name()

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#5952]
https://www.arduino.cc/en/Reference/SD doesn't have an entry for `name()` under the **File class** section but the library does contain this function:
https://github.com/arduino-libraries/SD/blob/1.1.1/src/File.cpp#L47

Originally reported at http://forum.arduino.cc/index.php?topic=453341

**Comment by Ivan-Perez** [comment]
Note that it should return a `const char*` instead of `char*`.

**Comment by agdl** [comment]
Done thank you! about the const we can PR this @sandeepmistry
