### ISSUE TITLE
Add Phpoc to Library Manager

### ISSUE THREAD

**Issue by phpoc** [arduino/Arduino#5958]
This library is to use [PHPoC (Wi-Fi) Shield](http://www.phpoc.com/phpoc_shield_for_arduino.php).

https://github.com/phpoc/arduino

Thank you.

**Comment by agdl** [comment]
I'm sorry, but your library can't be added since a tag is missing with the library.properties file inside the tag

**Comment by phpoc** [comment]
I am sorry but I couldn't quite catch what you mean.
Our library has [the tag information](https://github.com/phpoc/arduino/tags).
I am not familiar with a "Library Manager" system.
Would you please explain in full detail.

**Comment by phpoc** [comment]
I changed the tag information of our repository.
Would you please check it?

**Comment by agdl** [comment]
Is not right yet. https://github.com/phpoc/arduino/blob/v1.2.0/library.properties

version=0.8.0 
tag 1.2.0

Fix this please!

**Comment by phpoc** [comment]
Finally, I got it.
I fixed the issue related to revision. And I also changed the revision to v1.0.0.
Would you please check it again?
https://github.com/phpoc/arduino/blob/v1.0.0/library.properties

**Comment by agdl** [comment]
Done thank you!

**Comment by phpoc** [comment]
Thank you so much. ^^
