### ISSUE TITLE
[Library manager] Please add UIPEthernet library

### ISSUE THREAD

**Issue by cassy73** [arduino/Arduino#5959]
Please add new UIPEthernet library to the library manager:
https://github.com/UIPEthernet/UIPEthernet

Thanks!

**Comment by agdl** [comment]
Done thank you!

**Comment by cmaglie** [comment]
@cassy73 
the `library.properties` must have the `maintainer` field set, please add it and redo the tag so it points to the updated file. Once done the library should be published automatically within an hour.
