### ISSUE TITLE
Some way to free or reduce the size of a String. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#596]
This is [Issue 596](http://code.google.com/p/arduino/issues/detail?id=596) moved from a Google Code project.
Added by 2011-08-24T18:49:26.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core
### Original description

Some ability to shorten a string (i.e. realloc() with a smaller capacity).  Maybe even renaming reserve() to resize() and allowing it to either grow or shrink the string?

**Comment by sandeepmistry** [comment]
I'm marking this as won't fix, it's been a few years and no one else has requested this.
