### ISSUE TITLE
Due basic sketch SPIF not defined by SPI.h Arduino 1.8.1

### ISSUE THREAD

**Issue by adrien59cadri** [arduino/Arduino#5962]
Hello

I've read that the arduino library as a different SPI installation for Due since 1.6, but i'm running into this issue on arduino 1.8.1.

Any possible other explanation?

Thanks

![image](https://cloud.githubusercontent.com/assets/536398/22709917/7eff89f6-ed49-11e6-8e29-c3e1530dfa34.png)

**Comment by facchinm** [comment]
Hi @adrien59cadri ,
the `SPIF` macro is only defined by AVR core, but it's an internal signal and should not be used if you are writing cross-platform sketches. 
If you stick to use SPI library functions (as defined [here](https://www.arduino.cc/en/reference/SPI) ) all your sketches will run on both AVR and Due (and Zero etc etc)
