### ISSUE TITLE
Arduboy2 and ArduboyTones have disappeared from the library manager

### ISSUE THREAD

**Issue by MLXXXp** [arduino/Arduino#5963]
My [Arduboy2](https://github.com/MLXXXp/Arduboy2) and [ArduboyTones](https://github.com/MLXXXp/ArduboyTones) libraries are no longer present in the *library_index.json* file. (They were there a few days ago.)

The relevant issues I created to have these libraries included are: #5561 and #5562 

I would appreciate you looking into this.

Thank you,
Scott Allen

**Comment by cmaglie** [comment]
Hi @MLXXXp 
it was indeed a problem on our indexer.

The issue affected your libraries with another 5 libraries that were scanned almost at the same time.

For some reasons the clone of the git repo that is kept on our server has been left in an unclean state, I guess some network problem happened. We have now added an explicit status check to handle this case and the problem solved itself after running another round of the indexer, so I'm confident that it should never happen again.

Thank you, and sorry for the troubles.
