### ISSUE TITLE
On OSX, program should not quit when last window is closed until user clicks away.

### ISSUE THREAD

**Issue by Segmented** [arduino/Arduino#5972]
In order to keep the behaviour consistent with other programs on OSX, Arduino should not automatically close when the last window is closed, until the user clicks away. This allows the user the opportunity to open a new file, or change settings. Other programs such as QuickTime behave in this way.

**Comment by cmaglie** [comment]
Duplicate of #936

**Comment by Segmented** [comment]
I'll add a note about how QuickTime behaves to the other issue, thanks.
