### ISSUE TITLE
Add IRremoteESP8266 library

### ISSUE THREAD

**Issue by kaklik** [arduino/Arduino#5975]
Infrared remote library for ESP8266, it is commonly used in [ESPEasy](http://www.letscontrolit.com/wiki/index.php/ESPEasy) project, and it is the last one missing, to compile project source files directly in Arduino IDE.

Github URL: https://github.com/markszabo/IRremoteESP8266

**Comment by cmaglie** [comment]
You must add a git tag to your repository to mark a release:

https://github.com/markszabo/IRremoteESP8266/tags

**Comment by crankyoldgit** [comment]
I've created a release tag (labeled as a pre-release) in IRremoteESP8266. Does this allow it to work now?

**Comment by cmaglie** [comment]
Yes, thanks!
