### ISSUE TITLE
Add SparkFun SevSeg to Library Manager

### ISSUE THREAD

**Issue by BrentWilkins** [arduino/Arduino#5983]
https://github.com/sparkfun/SevSeg

Current release:

https://github.com/sparkfun/SevSeg/releases/tag/V_1.0.2

**Comment by cmaglie** [comment]
There is already a library named SevSeg, you must change the library name (for the record this is the second name clash)

**Comment by cmaglie** [comment]
Please reopen when ready. Thanks!
