### ISSUE TITLE
Use and display of COM1 as default serial port on Mac and Linux is confusing. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#600]
This is [Issue 600](http://code.google.com/p/arduino/issues/detail?id=600) moved from a Google Code project.
Added by 2011-08-27T16:05:24.000Z by [rick.rickanderson](http://code.google.com/u/rick.rickanderson/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

Arduino 1.0 feature: Selected board and port display the serial ports should display the current OS serial port name

Currently, COM1 is displayed on Mac OS x instead of /dev/tty.usb*

**Comment by matthijskooijman** [comment]
@ffissore Was this fixed? It still sounds like a relevant issue. Ideally, the default value for the port is empty/undefined, allowing the IDE to prompt the user, telling him to choose a port, when no port is defined yet?
