### ISSUE TITLE
Problem with arduino software

### ISSUE THREAD

**Issue by Soumil123** [arduino/Arduino#6001]
I have installed arduino software(1.8.2)...in examples i opened blink and and tried to upload it to my arduino r3 uno atmega 328P atmega 16u2 but didn't work...
I request u to help me with this Please...

**Comment by dlabun** [comment]
This is the wrong place to ask for getting started help... Please post this to the Arduino forum

**Comment by PaoloP74** [comment]
Latest version is 1.8.1 (https://www.arduino.cc/en/Main/Software)

**Comment by matthijskooijman** [comment]
As mentioned, this issue tracker is for bugs in the software, try the forums for help with writing and uploading sketches. I'm closing this issue.
