### ISSUE TITLE
Add "IoTtweetESP32" library to Library Manager Arduino IDE

### ISSUE THREAD

**Issue by Isaranu** [arduino/Arduino#6011]
We are developer team from https://www.iottweet.com which provided an IoT user designable dashboard. It's compatible use with ESP8266 Wifi module, NodeMCU, WeMos, Nano32 and several IoT model.

This library "**IoTtweetESP32**" is support esp32 wifi chip device.

github url : https://github.com/Isaranu/IoTtweetESP32

Thank you very much.
IoTtweet team.

**Comment by cmaglie** [comment]
Done!
