### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by dario-bandeira** [arduino/Arduino#6015]
I use Serial Monitor everytime. If I open it after seeing "Done uploading", there is no problems, but if I open Serial Monitor **after** tapping Ctrl+U (compile + send) and **before** seeing "Done uploading" i get a **timeout** message.

I'm using:
- Arduino Mega 2560;
- Ubuntu 16.04 64bits;
- Arduino IDE 1.8.1;

**Comment by facchinm** [comment]
Thanks for reporting the complete procedure, I would have missed the keyboard shortcut. Should be fixed by 	c0a99f9, which will land in nightly in a couple of hours.

Thanks again!
