### ISSUE TITLE
Session not persistent between subdomains

### ISSUE THREAD

**Issue by ezeffery** [arduino/Arduino#6026]
Use Case: 
As a user currently logged into the site of I can view my profile https://id.arduino.cc/

As this user I navigate to https://www.arduino.cc/en/Main/Software and click on https://create.arduino.cc/editor 

I am then redirected to https://id.arduino.cc/cas/login?service=https%3A%2F%2Fid.arduino.cc%2Fcas%2Foauth2.0%2FcallbackAuthorize

When attempting to login with my credentials I get a message: " Invalid Credentials" 
User Name: _zeffy_

Also when I log out and attempt to log back in I get an error: A form re-post or an unknown error has occurred.

**Comment by mastrolinux** [comment]
This has been fixed with the new SSO system
