### ISSUE TITLE
Curie IMU readAccelerometer

### ISSUE THREAD

**Issue by LightningAlchemist** [arduino/Arduino#6028]
The unit it says the raw data can me translated to is mg. If it is mg in the most common form it would be megagrams, if it is mg as a form of acceleration would me mega g's. Both are inordinate in scale, and the first one is not a unit of acceleration. I need the correct units soon.

**Comment by facchinm** [comment]
Hi @LightningAlchemist , you should report this issue at Intel's github repo (https://github.com/01org/corelibs-arduino101), thanks.
