### ISSUE TITLE
variable not assignment value

### ISSUE THREAD

**Issue by Baytron** [arduino/Arduino#6036]
problem in IDE 1.6.5, 1.6.13, 1.8.1. With two boards UNO R3 (clone), NANO (clone).
variable "i" not equal 0 in start of loop after "i = 0;" in else
variable "i" rise to max value
variable "a" rise to max value 

unsigned long currentMillis = 0;
unsigned long prevMillis = 0;
int a = 0;
int i = 0;

void setup() {
  Serial.begin (9600);
}

void loop() {
  // there variable "i" have previus value (before i = 0, in else)
  //Serial.print (i);  //sketch not work without Serial.print (i) or delay (5). variable "a" rise to max value 
  currentMillis = millis();
  if (prevMillis + 1000 >= currentMillis) {   //Cycles Count
    i = ++i;
    if (a < i) {
      a = i;
      Serial.println(a);
    }
  }
  else {
    i = 0; // there variable "i" = 0
    prevMillis = currentMillis;
  }
}

**Comment by Baytron** [comment]
problem in IDE 1.6.5, 1.6.13, 1.8.1. With two boards UNO R3 (clone), NANO (clone).

**Comment by facchinm** [comment]
Hi @Baytron , this is a question for the [forum](http://forum.arduino.cc/index.php) since your code needs a good refinement before calling a bug in the core :smile: If you post your problem there you'll get more guidance and advice than you can get here. Thanks!
