### ISSUE TITLE
Library register request 

### ISSUE THREAD

**Issue by JAICHANGPARK** [arduino/Arduino#6038]
Hi there
I made Arduino smart watch library for students
It would be great to add the following library to the Arduino Library Manager :)

this is github url : https://github.com/JAICHANGPARK/Arduino-Watch

thank you

**Comment by per1234** [comment]
You need to do a release or tag. See:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Please consider merging my pull request before doing so.

**Comment by JAICHANGPARK** [comment]
Thank you and I changed your Pull request

**Comment by cmaglie** [comment]
@JAICHANGPARK 
you must make a *tag*, this is needed by our indexer to find the release of your library:

https://github.com/JAICHANGPARK/Arduino-Watch/tags

**Comment by cmaglie** [comment]
Done, thanks!
