### ISSUE TITLE
parse error on boards.txt

### ISSUE THREAD

**Issue by trivalik** [arduino/Arduino#6042]
If we add a board and you want to add a comment after maximum_size entry an error occure.

Example for a line which will create an error:

esplora.upload.maximum_size=130048 #131072

The error is:

strconv.ParseInt: parsing "130048 #131072": invalid syntax

**Comment by facchinm** [comment]
Hi @trivalik ,
`boards.txt` parser doesn't allow inline comments. I'm moving the issue to arduino-builder repo because it can be a nice improvement to the core developer experience (although any core with inline comments won't be backwards compatible)

**Comment by facchinm** [comment]
Moved to https://github.com/arduino/arduino-builder/issues/218
