### ISSUE TITLE
[Library Manager] Add TheThingsNode library

### ISSUE THREAD

**Issue by johanstokking** [arduino/Arduino#6044]
We have created a specific Arduino library for The Things Node; a LPWAN device with sensors, based on Arduino, that communicates with LoRaWAN networks (including but not limited to The Things Network).

At first, this code was part of [TheThingsNetwork library](https://github.com/TheThingsNetwork/arduino-device-lib) which is already in the library manager. Because of dependencies on AVR, we moved code from that library to this new library.

https://github.com/TheThingsNetwork/arduino-node-lib

**Comment by cmaglie** [comment]
Done!
