### ISSUE TITLE
Feather M0 serial port decoding

### ISSUE THREAD

**Issue by tangtangdn** [arduino/Arduino#6045]
Hello,
I do not know it is my problem or a bug for the Feather M0. 
I found no matter what the baud rate  is set to in Serial.begin(**), I always collected data with the Tera Term when the baud rate is set to 9600 in Tera Term. However, after I connected a communication module with Feather M0 and collected data from the communication module, the number of data will be right.
Please help to check it, thank you.

Best ragards
Tang

**Comment by facchinm** [comment]
Hi Tang, you should ask for help on Adafruit's [forum](https://forums.adafruit.com/) or [github](https://github.com/adafruit/ArduinoCore-samd) for informations about the feather M0.
Thanks!
