### ISSUE TITLE
railway crossing using arduino 

### ISSUE THREAD

**Issue by kj1039** [arduino/Arduino#6046]
i have made a codefor the train comin from one side could someone help me with the other side with mdification in my code
int sensePin1 = 0;
int sensePin2 = 1;
int sensePin3 = 2;
int sensePin4 = 3;
int motorPin1 = 4;
int motorPin2 = 5;
int motorPin3 = 6;
int motorPin4 = 7;
void setup(){
  pinMode(0,INPUT);
  pinMode(1,INPUT);
  pinMode(2,INPUT);
  pinMode(3,INPUT);
  pinMode(4,OUTPUT);
  pinMode(5,OUTPUT);
  pinMode(6,OUTPUT);
  pinMode(7,OUTPUT);
}
void loop(){
  int s1,s2,s3,s4;
  s1= digitalRead(0);
  s2= digitalRead(1);
  s3= digitalRead(2);
  s4= digitalRead(3);
  if(s1&s2==1)
  {
    crossingclose();
    delay(3000);
    wait();
  }
    else 
    {
     wait();
    } 
      if(s3&s4==1){
      crossingopen();
      delay(3000);
      wait();
    }}
    void crossingclose()
    {
    digitalWrite(7,HIGH);
    digitalWrite(6,LOW);
    digitalWrite(5,HIGH);
    digitalWrite(4,LOW);
    }
    void crossingopen()
    {
      digitalWrite(7,LOW);
    digitalWrite(6,HIGH);
    digitalWrite(5,LOW);
    digitalWrite(4,HIGH);
    }
    void wait()
    {
      digitalWrite(7,LOW);
    digitalWrite(6,LOW);
    digitalWrite(5,LOW);
    digitalWrite(4,LOW);
    }

**Comment by cmaglie** [comment]
Please use the forum for assistance.
