### ISSUE TITLE
Correct way to install?

### ISSUE THREAD

**Issue by Henrietta1989** [arduino/Arduino#6056]
I have latest version of NOOBS Raspbian in Raspberry 3 and i try to update Arduino to 1.8.1.

I downloaded ARM version of Arduino from www.arduino.cc/en/Main/Software

cd ~/Downloads
tar xvf arduino-1.8.1-linuxarm.tar.xz
cd arduino-1.8.1
./install.sh

Now i have two Arduino IDEs in /usr/share/applications directory.

How i can uninstall older one?

What’s the right place to install apps in Raspbian? Now newer one in that directory points to /home/pi/Downloads/arduino-1.8.1 directory and that can’t be best location to keep this folder???

/opt directory has now minecraft-pi, pigpio, sonic-pi, vc and Wolfram. So here seems to be 3rd party apps??

What i should change so i have only one Arduino IDE installed and i have Arduino installed correctly to correct directory and can trash arduino-1.8.1 folder in Downloads?

Thanks

**Comment by facchinm** [comment]
Hi @Henrietta1989 ,
the Linux "installer" in fact only creates the shortcuts from where you extracted the IDE and doesn't copy itself in a standard location. You can safely move the `arduino-1.8.1` folder to `/opt` and rerun `install.sh` to obtain the correct links. To get rid of the old installation (the packaged one) simply run `sudo apt-get remove arduino` and you should be ok
