### ISSUE TITLE
Still issues with the hw serial library

### ISSUE THREAD

**Issue by mattskimi** [arduino/Arduino#6062]
There is still serious issue with the irq driven version. 
Had to revert back to 1.0.6 where no issues.
The code is simple, collecting data from the analog inputs in an irq routine and sending those to a display through serial with 115200 baud. There is strict handshaking and something is dropped or transferred twice. Speed makes no difference, it crashes sooner with high speed.
Version 1.0.6 is the one  that works. Application  has been up and running for days. 
With 1.5 or newer the system crashes within 1 minute.

**Comment by PaulStoffregen** [comment]
To have any chance to anyone ever looking into this, you must post a complete (hopefully compact) program which demonstrates the problem.  Of course, a likely response will be "don't do that from interrupts".  But without a program posted, nobody can do anything at all.

**Comment by mattskimi** [comment]
Hi Paul,
I understand, and when I have time, I will try to create an app that
simulates this. There are propably a lot of coders suspecting their own
code working on workarounds.
/kimi

**Comment by facchinm** [comment]
@mattskimi ,
a stripped sample code demonstrating the issue (plus an indication of the hardware/board you are using and the libraries version) is the minimum requirement to start analysing this, thanks :slightly_smiling_face:

**Comment by PaulStoffregen** [comment]
While recently working with the Wire library, I noticed the Wire library "slave_receiver" example calls Serial.print from its receiveEvent() function, which the Wire lib calls from interrupt context.  This probably isn't a similar case, but it is one of the oldest and most well established of the many Arduino libs that has always demonstrated to users calling Serial.print() from interrupt context.

**Comment by mattskimi** [comment]
Hi.
I only collect data from the adc  in the irq. Raw code and calculation. Not
a single library call.
/kimi

13.3.2017 12.15 "Paul Stoffregen" <notifications@github.com> kirjoitti:

**Comment by PaulStoffregen** [comment]
Well then, this only serves to show how we are spending our time with fruitless guesswork, because you haven't provided a program.

**Comment by mattskimi** [comment]
This serves the users to try the older version of hwserial if they have
issues with irq driven code. The old works like a Buick. I will try to
create a simple sketch when i have time.
/kimi

On 13 Mar 2017 22:05, "Paul Stoffregen" <notifications@github.com> wrote:

Well then, this only serves to show how we are spending our time with
fruitless guesswork, because you haven't provided a program.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arduino/Arduino/issues/6062#issuecomment-286226827>,
or mute
the thread

**Comment by per1234** [comment]
@mattskimi we're still waiting on that demonstration sketch from you...

**Comment by per1234** [comment]
Closing due to lack of response from @mattskimi.

**Comment by mattskimi** [comment]
Hi, will reopen when i have the test sketch that proofs the issue.
