### ISSUE TITLE
Arduino MKR1000 board in list of boards in Ubuntu. 

### ISSUE THREAD

**Issue by lotelx** [arduino/Arduino#6068]
With Arduino 1.8 After installing Arduino SAMD Boards 32 bits (ARM Cortex M0+) 1.6.12

MKR1000 is not visible in the boards list.

**Comment by facchinm** [comment]
Could you post a couple of screenshots, one for your "board" menu and one for the board manager after selecting "SAMD boards" ? Thanks

**Comment by per1234** [comment]
@lotelx we're still waiting for you to provide those screenshots. Please help us out so we can investigate this issue.

**Comment by per1234** [comment]
Closing due to lack of response from @lotelx.
