### ISSUE TITLE
[Library Manager] Please Add Thermal Printer Shield to the Library Manager

### ISSUE THREAD

**Issue by NADA-ELECTRONICS** [arduino/Arduino#6072]
Hi.  
Please add AS-289R2 Thermal Printer Shield to the library manager.  
GitHub : [https://github.com/NADA-ELECTRONICS/AS-289R2](https://github.com/NADA-ELECTRONICS/AS-289R2)  
  
Thnaks.

**Comment by NADA-ELECTRONICS** [comment]
Thank you very much.

**Comment by cmaglie** [comment]
Done!
