### ISSUE TITLE
Arduino playground edit history viewer

### ISSUE THREAD

**Issue by Jeinzi** [arduino/Arduino#6080]
Hello! I think the history viewer for Arduino playground entries could benefit from an upgrade. Maybe one could implement something similar to the diff viewer used on github? (eg. https://github.com/rtfpessoa/diff2html)

I guess it's not an urgent issue, but I find it quite difficult gleaning anything from the current view.

**Comment by per1234** [comment]
Closing as wontfix since Arduino decided to make the Arduino Playground readonly:
https://forum.arduino.cc/index.php?topic=580991.0
