### ISSUE TITLE
Add new library to the Arduino library manager

### ISSUE THREAD

**Issue by LoRaFi** [arduino/Arduino#6096]
Hello,
We would like to add our library for Arduino library manager. This library for our LoRaFi board. The board consists of LoRa RF transceiver, WiFi, and Arduino. 
The category of the library is communication. The link to the library on the GitHub below:
https://github.com/LoRaFi/LoRaFi/tree/v1.1

Thank you for the great Arduino team 

Khudhur Alfarhan 
the author and maintainer of the library

**Comment by cmaglie** [comment]
Done!

**Comment by LoRaFi** [comment]
Thank you so much :)
