### ISSUE TITLE
Want to change library name

### ISSUE THREAD

**Issue by kaizen8501** [arduino/Arduino#6104]
Hi. Thank you for adding our library.

But I have some mistake about library name. I want to change library name so I already changed name in library.properties. But It doesn't adjust in library manager.
If I want to change library name, How to do that?

**Comment by cmaglie** [comment]
Which library are you referring to?

**Comment by kaizen8501** [comment]
https://github.com/Wiznet/WizFi310_arduino_library

**Comment by cmaglie** [comment]
Ok it should be fixed now
