### ISSUE TITLE
Upgrade to newer avr toolchain: avr-gcc, avr-binutils, etc. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#611]
This is [Issue 611](http://code.google.com/p/arduino/issues/detail?id=611) moved from a Google Code project.
Added by 2011-08-29T15:09:22.000Z by [jc@wippler.nl](http://code.google.com/u/jc@wippler.nl/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Build

### Original description

**What change would like to see?**

The avr-gcc in the new 1.0 beta is still at 4.3.2 - while gcc now has had releases 4.5.3 and 4.6.1 for several months.

**Why?**

The upcoming 1.0 release already introduces lots of changes, this could be a rare opportunity to make a big step forward with avr-gcc as well. Improved optimizations can matter greatly on an embedded platform.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

I doubt there will be any incompatibilities, gcc is pretty mature by now.

**Comment by Chris--A** [comment]
> The avr-gcc in the new 1.0 beta is still at 4.3.2 - while gcc now has had releases 4.5.3 and 4.6.1 for several months.

Resolved, GCC is now at 4.8.1!

**Comment by ffissore** [comment]
:+1:
