### ISSUE TITLE
arduino ide

### ISSUE THREAD

**Issue by mmalm** [arduino/Arduino#6112]
hello ,

I am trying to connect my mbot to the Arduino ide but the code is not able to download to the mbot it is the board issue I am not sure which type to use I have tried the Leonardo and Genuine but still what I have found that some people use Uno only but I cannot see it in my board list

**Comment by facchinm** [comment]
Hi @mmalm ,
please post your questions on the [forum](http://forum.arduino.cc/). This issue tracker is intended for IDE bugs and enhancements. Thanks!
