### ISSUE TITLE
[Library Manager] Please Add AzureIoTHubMQTTClient to the Library Manager

### ISSUE THREAD

**Issue by andriyadi** [arduino/Arduino#6113]
Hi,

I've created an unofficial Azure IoT Hub client library for ESP8266, that's specifically built to leverage MQTT. 

It's  hosted at this Github repository: https://github.com/andriyadi/AzureIoTHubMQTTClient

Please kindly add it to Library Manager. Thanks!

**Comment by cmaglie** [comment]
Done!
