### ISSUE TITLE
SimulIDE_0.0.4 not running

### ISSUE THREAD

**Issue by thesauband** [arduino/Arduino#6119]
I have downloaded the  SimulIDE_0.0.4-Lin64-SR1  arduino simiulator  and i found  the icon SimulIDE_0.0.4 in the /home/bandula/SimulIDE_0.0.4-Lin64-SR1 folder but i cannot run SimulIDE_0.0.4 program when i click on it please let me know how can i run this

**Comment by facchinm** [comment]
We are not related in any way with SimulIDE, I'm sorry.
