### ISSUE TITLE
[Library Manager] Add Brasilino Library

### ISSUE THREAD

**Issue by OtacilioN** [arduino/Arduino#6127]
Brasilino Library is a Arduino Library that allows to use the portuguese from Brasil language to program in Arduino Language, also all the documentation is in portuguese from Brasil. We believe that by breaking the language barrier we can encourage people to use Arduino, which can later migrate to the Arduino Program Language. 

The Github URL is: https://github.com/OtacilioN/Brasilino
The current release is v1.0.0: https://github.com/OtacilioN/Brasilino/releases/tag/v1.0.0

Please add Brasilino to Llibrary Manager.

**Comment by cmaglie** [comment]
Done!

**Comment by OtacilioN** [comment]
Thanks a lot!
