### ISSUE TITLE
Wire library TwoWire.end() needed by Firmata [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#613]
This is [Issue 613](http://code.google.com/p/arduino/issues/detail?id=613) moved from a Google Code project.
Added by 2011-08-30T13:51:00.000Z by [paul.sto...@gmail.com](http://code.google.com/u/102276914943260257800/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

**What change would like to see?**

TwoWire.end() function that disables I2C and returns both pins to normal operation.

**Why?**

So the pins can be reused

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

should not cause any compatibility problems

**Comment by cmaglie** [comment]
Fixed with #3724

**Comment by sandeepmistry** [comment]
@cmaglie re-opening as the SAM core ``Wire.end()`` function hasn't been implemented yet.

**Comment by cmaglie** [comment]
closed by #3894
