### ISSUE TITLE
GSM3SoftSerial supports only 20, 16 and 8MHz processors

### ISSUE THREAD

**Issue by stnorthern** [arduino/Arduino#6131]
I get an error when I compile with GSM library with my board:

` #error This version of GSM3SoftSerial supports only 20, 16 and 8MHz processors

I have a 48 MHz board

**Comment by facchinm** [comment]
Which board are you using? GSM library is only compatible with AVR boards and none of them is clocked at 48MHz. If you are using an Arduino Zero or similar, please reopen this issue in the correct repo (https://github.com/mattairtech/ArduinoCore-samd). Thanks

**Comment by stnorthern** [comment]
I see. 
I am using SmartEverything board. It is Atmel ARM M0+ MCU. 
I am totally new with Arduino, and not even sure if this is AVR?

**Comment by facchinm** [comment]
Yes, it's a SAMD boatd (no AVR). The repository is https://github.com/ameltech/sme-arduino-core, please reopen the issue there, thanks!

**Comment by stnorthern** [comment]
Okay, I will. 
I have been looking at the requirements for the GSM modem, but I did not find anywhere that AVR was required, nor that only certain frequencies was supported.

**Comment by stnorthern** [comment]
The board you linked was for SmartEverything. I dont see why they have anything to do with the GSM modem code (I bought the modem separately). 
I guess I have to make a port for non-avr Arduinos or find another modem? Would it be difficult to make a non-avr port of the code?

**Comment by facchinm** [comment]
For this kind of questions you should write to the relevant repo (https://github.com/ameltech/sme-arduino-core) or in the [forum](forum.arduino.cc). This repo tracks problem with the IDE and the AVR core it contains, no other kind of problem.
Probably you will be luckier with [this GSM library](https://github.com/arduino-org/Arduino/tree/master/hardware/arduino/samd/libraries/GSM) but I can't help more than that, sorry.
