### ISSUE TITLE
Add SDS011 library to the Arduino library manager

### ISSUE THREAD

**Issue by ricki-z** [arduino/Arduino#6133]
Hello,
I would like to add my library for Arduino library manager. The library is for the SDS011, a dust sensor for PM10 and PM2.5. 
The category of the library is sensors The link to the library on the GitHub below:
https://github.com/ricki-z/SDS011

Thank you for the great Arduino team

Rajko Zschiegner

**Comment by cmaglie** [comment]
Done!
