### ISSUE TITLE
jm_CPPM - a new Arduino Library

### ISSUE THREAD

**Issue by jmparatte** [arduino/Arduino#6134]
https://github.com/jmparatte/jm_CPPM

jm_CPPM - CPPM Library for Arduino
Supported architecture: Arduino UNO and Leonardo

The library can read and decode a CPPM input signal generated by a R/C transmitter.
The library can also encode and write up to 3 CPPM ouput signals (Arduino Leonardo).

**Comment by cmaglie** [comment]
Done!
