### ISSUE TITLE
readStringUntil() reference page unclear about the return value

### ISSUE THREAD

**Issue by jzaruba** [arduino/Arduino#6137]
https://www.arduino.cc/en/Serial/ReadStringUntil
It is not clear whether the returned value contains the terminator or not. (I read elsewhere that it does not.) And what happens to the terminator? Is it returned in the next Serial.read or is it thrown away?

**Comment by inflector** [comment]
From testing the code, the answer to this question is:

1) It does NOT return the terminator.
2) It does NOT leave it in the buffer and return it the next time.

**Comment by per1234** [comment]
I'm merging this issue to https://github.com/arduino/reference-en/issues/446 since that is now the more appropriate place for it.

If anyone wants to submit a pull request to https://github.com/arduino/reference-en to clarify the documentation that would be welcome.
