### ISSUE TITLE
[DOCS] Code repo error

### ISSUE THREAD

**Issue by AlexMunoz905** [arduino/Arduino#6142]
Hello, I noticed last night that the code repo was done on Arduino.cc
> SORRY, There is an error at our code repository, please inform to web@arduino.cc
The link that had it is https://www.arduino.cc/en/tutorial/sweep
Thanks for any help! Also, please just don't send me the code for it, please fix it!

**Comment by per1234** [comment]
https://www.arduino.cc/en/tutorial/sweep now correctly shows the code for me so I'm closing this as solved. @AlexMunoz905, if the issue still occurs for you please comment and I'll reopen.
