### ISSUE TITLE
[Add Library] Neotimer

### ISSUE THREAD

**Issue by jrullan** [arduino/Arduino#6144]
https://github.com/jrullan/neotimer

**Comment by cmaglie** [comment]
@jrullan 
the fields 'sentence' and 'url' must be defined in the library.properties file.

To fix that:
1) remove the `v1.0` tag
2) add the missing fields in library.properties
3) commit and push
4) re-create the `v1.0` tag

once done the library should be automatically published within an hour.

**Comment by jrullan** [comment]
I couldn't remove the existing v1.0 tag and the sentence property was in the library.properties. 
So,... I added the url property and created a v1.1 tag and release.
Should this work?

**Comment by cmaglie** [comment]
yes
