### ISSUE TITLE
parseFloat() miscapitalized in Stream reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6145]
The list of functions at https://www.arduino.cc/en/Reference/Stream miscapitalizes `parseFloat()` as `parsefloat()`.
![parsefloat](https://cloud.githubusercontent.com/assets/8572152/24592123/cb96cf58-17c5-11e7-8a9a-3446b4f3e7f0.png)
Originally reported at http://forum.arduino.cc/index.php?topic=467455

**Comment by agdl** [comment]
Done thank you!
