### ISSUE TITLE
Adding library to arduino's library manager

### ISSUE THREAD

**Issue by xcoder123** [arduino/Arduino#6156]
Hello,

I was trying to get my library added to the arduino library manager. As far as I understood once I made in a specific structure with keywords.txt and library.properties files it should have been picked up automatically. But it hasn't for over 2 days, I tried also tagging.

Anyway here is the link to the library:
https://github.com/xcoder123/FlexiPlot_Arduino

Have I made mistakes in the structure?

**Comment by cmaglie** [comment]
The library should be registered in our library manager indexer to be published, so you must ask here to add it.

The library format is ok, and now I've added it!
