### ISSUE TITLE
Arduino uno upload error 

### ISSUE THREAD

**Issue by kareemsakkary** [arduino/Arduino#6162]
Hello Arduino, 
I bought arduino uno from ram electronics in Cairo .
When i test it  in my home ,it didn`t upload and gave me this error :
"Avrdude ser_open() can't open device . com1 the system cannot find the file specified."
i went to ram electronics to change board but they told me contact with arduino .
please help me ,
Thanks.
arduino uno serial nom: *U01864061* 
my name : Kareem sakkary 
my email address : kimoosakkary@gmail.com

**Comment by facchinm** [comment]
Hi @kareemsakkary , are you sure you selected the correct port from "Tools/Port" menu? If so,  the board could be defective, please mail support@arduino.cc for a replacement or further debugging of your problem
