### ISSUE TITLE
[Library Manager] Please add Arduboy-TinyFont

### ISSUE THREAD

**Issue by yinkou** [arduino/Arduino#6166]
Tinyfont is a 4x4 font small-asci with for Arduboy which subclasses Arduino Print.

https://github.com/yinkou/Arduboy-TinyFont

Thank you <3

**Comment by yinkou** [comment]
Updated everything for the  1.5 Library Format specification. thanks per1234 ✌️
Now you can add, thank you. :)

**Comment by cmaglie** [comment]
Done!
