### ISSUE TITLE
Bug in WiFi.status() reference page example sketch

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6172]
The example sketch found at https://www.arduino.cc/en/Reference/WiFiStatus has a missing closing parenthesis at line 40:
```arduino
Serial.println(WiFi.status();
```
Originally reported at http://forum.arduino.cc/index.php?topic=469130

**Comment by agdl** [comment]
Done thank you!

**Comment by per1234** [comment]
@agdl the incorrect code is still displayed at https://www.arduino.cc/en/Reference/WiFiStatus

**Comment by agdl** [comment]
@per1234 try to reload the page clearing the cache please

**Comment by per1234** [comment]
OK, fixed now, thanks!
