### ISSUE TITLE
Wire library slave examples won't compile with Arduino 101

### ISSUE THREAD

**Issue by Pachicito** [arduino/Arduino#6174]
Works great with the Uno, but not the 101.

error: 'class TwoWire' has no member named 'onReceive'

Same with 'onRequest'.

Same issue in both desktop IDE and Create.

**Comment by facchinm** [comment]
I believe it should be moved to https://github.com/01org/corelibs-arduino101 because the non-standard implementation is on 101's side. Would you mind reopening there? Thanks!
