### ISSUE TITLE
[Library Manager]: Inclusion of Settimino Libary

### ISSUE THREAD

**Issue by kristbaum** [arduino/Arduino#6186]
Would be nice if Settimino were available in the Arduino IDE Libary Manager.
https://sourceforge.net/projects/settimino/
I am not the owner of this project, but it is GPL, so I guess it would be okay..

**Comment by agdl** [comment]
Hi, to be added to the library manager the library must have a proper structured GitHub repository and the author has to ask for the inclusion I'm sorry.
