### ISSUE TITLE
[Library Manager]: Please add BlueDot BME280 Library

### ISSUE THREAD

**Issue by BlueDot-Arduino** [arduino/Arduino#6191]
https://github.com/BlueDot-Arduino/BlueDot_BME280

**Comment by per1234** [comment]
Please read https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and update your library to comply:

1. Add a [library.properties file](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#library-metadata).
2. Create a tag or release.

**Comment by BlueDot-Arduino** [comment]
Thanks for the information. I created a library.properties file as well as a new release. I believe it is now in 1.5 format.

**Comment by Rotzbua** [comment]
@BlueDot-Arduino There is no license information about your library, please add one :) .

**Comment by BlueDot-Arduino** [comment]
Ops! Thanks again for the information. 
I made a few changes and I guess now the library should be complete! :)

**Comment by agdl** [comment]
Done thank you!
