### ISSUE TITLE
[Library Manager]: Please consider adding SevenSeg to the Arduino Library Manager

### ISSUE THREAD

**Issue by sigvaldm** [arduino/Arduino#6194]
https://github.com/sigvaldm/SevenSeg

**Comment by per1234** [comment]
You need to create a release or tag to match the version value in your library.properties file. For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by sigvaldm** [comment]
Sorry, I forgot to push it. Please try again now :)

**Comment by agdl** [comment]
Done thank you!
