### ISSUE TITLE
[IDE] Lose unsaved content when check "use external editor"

### ISSUE THREAD

**Issue by truebucha** [arduino/Arduino#6196]
Lose unsaved content when check "use external editor" checkbox in settings.
it is very distractive. I can't remember any IDE that could lose changes without prompt.
IDE 1.8.1 mac os 10.12.4
Are we going back to early 2000?

**Comment by cmaglie** [comment]
Please post instruction to reproduce the bug.

**Comment by truebucha** [comment]
type some code into editor
press cmd+s
type more code and do nothing that make it autosave
go to settings and check the "use external editor" checkbox, press OK
What happened: editor reload file
What should happen: editor save changes before reload file

**Comment by cmaglie** [comment]
Thanks for the detailed bug report!

Weird that nobody ever reported this, maybe is not so common that someone starts writing a sketch and in the middle of it swaps to external editor.

Yet it's still very dangerous, so I've pushed a fix on #6223 for the next IDE release.

**Comment by PaulStoffregen** [comment]
I can confirm I've hit this several times, but it's never really bothered me.

**Comment by truebucha** [comment]
My fault was I implemented new GPRS class at least 500 lines before change the editor =). that time it bothered me a lot.
