### ISSUE TITLE
problem with energia c2000 f2807

### ISSUE THREAD

**Issue by josele000** [arduino/Arduino#6201]
i have a problem with the c2000. i press the button verify and my program its no compiling the message is the next:
**"C:\Users\JOSELE RENDON\AppData\Local\Temp\build1613906076524589072.tmp\sketch_apr19a.cpp", line 4: error #34: invalid line number
1 error detected in the compilation of "C:\Users\JOSELE RENDON\AppData\Local\Temp\build1613906076524589072.tmp\sketch_apr19a.cpp".

>> Compilation failure**
I already tried everything
helpme please my energia is the edition 0101E0017

**Comment by facchinm** [comment]
Hi @josele000 , you should reopen the issue in the Energia issue tracker (https://github.com/energia/Energia), thanks

**Comment by shakil1740** [comment]
> i have a problem with the c2000. i press the button verify and my program its no compiling the message is the next: **"C:\Users\JOSELE RENDON\AppData\Local\Temp\build1613906076524589072.tmp\sketch_apr19a.cpp", line 4: error #34: invalid line number 1 error detected in the compilation of "C:\Users\JOSELE RENDON\AppData\Local\Temp\build1613906076524589072.tmp\sketch_apr19a.cpp".
> 
> > > Compilation failure**
> > > I already tried everything
> > > help me please my energia is the edition 0101E0017

add 1 blank line at the beginning of your sketch.
