### ISSUE TITLE
Arduino IDE NOT updating USB comm ports !!

### ISSUE THREAD

**Issue by rbjassoc66** [arduino/Arduino#6209]
The IDE 1.8 is not updating comm ports when using USB ? I have tried it on 3x different computers but something has changed ??? Anyway I am unable to communicate with my Wemos 8266

**Comment by facchinm** [comment]
IDE 1.8 works as expected, I think your board has some problems (with drivers, maybe)? Anyway, we don't give assistance for 3rd party boards, so you'll need to reach the right people for any help.
