### ISSUE TITLE
ABS documentation wrong

### ISSUE THREAD

**Issue by warpster** [arduino/Arduino#6214]
The documentation says that ABS returns

x: if x is greater than or equal to 0. 
or
-x: if x is less than 0.   <-----this is wrong I believe, should be x: if x is less than 0.  (no minus)

That is unless ABS works different in Arduino than any other language.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/3338

**Comment by facchinm** [comment]
Closing as duplicate
