### ISSUE TITLE
[Library Manager] Please add AK9750 Sensor

### ISSUE THREAD

**Issue by nseidle** [arduino/Arduino#6215]
Hi,

We have a library over here for the AK9750 sensor:

https://github.com/sparkfun/SparkFun_AK9750_Arduino_Library

Please add when possible. Thanks!

**Comment by cmaglie** [comment]
You need to create a release or tag that matches the version value set in `library.properties`. See https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ for more info.

**Comment by nseidle** [comment]
Shoot! Sorry. Pushed with tags. Should be good to go now.

**Comment by cmaglie** [comment]
Done, thanks!
