### ISSUE TITLE
[Library Manager] Please add Logger

### ISSUE THREAD

**Issue by awickert** [arduino/Arduino#6220]
https://github.com/NorthernWidget/Logger
It's an Arduino-based data logger library.
Thanks!

**Comment by cmaglie** [comment]
Sorry, there is already a library named Logger, please choose another name...

**Comment by awickert** [comment]
Name changed to "ALog"; transition will take some testing, will ping when we are ready.

**Comment by per1234** [comment]
@awickert did you still want your library added to the Library Manager index?

**Comment by awickert** [comment]
@per1234 Thanks for the ping! I did rename the library to "ALog", and would love for this to be added:
https://github.com/NorthernWidget/ALog

**Comment by cmaglie** [comment]
Done!
sorry for delay... this one really went off my radar!

**Comment by awickert** [comment]
Thank you!
