### ISSUE TITLE
Error in install script

### ISSUE THREAD

**Issue by ertwoditwo** [arduino/Arduino#6226]
# Resource name to use (including vendor prefix)
RESOURCE_NAME=cc.arduino.arduinoide

should be

# Resource name to use (including vendor prefix)
RESOURCE_NAME=arduino-arduinoide

**Comment by facchinm** [comment]
Solved by https://github.com/arduino/Arduino/commit/bd4921910987bf9ec1c19ed2e9fd1c966180282d, the fix will be available in the next IDE version
