### ISSUE TITLE
Split avrdude and avrdude.conf out from massive tools .zip file. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#623]
This is [Issue 623](http://code.google.com/p/arduino/issues/detail?id=623) moved from a Google Code project.
Added by 2011-09-03T03:50:10.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Build

### Original description

Every time we update avrdude or avrdude.conf (which is somewhat often), we need to commit new versions of the huge Mac and Windows AVR tools zip files.  These two files should really be outside of the zip archive, so we can update them in a more light-weight fashion.  The rest of the AVR toolchain is updated much less frequently (typically with new versions of WinAVR, when we just grab a new .zip).

**Comment by ricklon** [comment]
This is a really good idea. Here's an example solution:

```

  <target name="update-avrdude-macosx" description="Update the avrdude configuration to latest version." depends="">
      <copy todir="macosx/work/mpide.app/Contents/Resources/Java/hardware/tools/avr/etc/">
        <fileset file="macosx/dist/avrdude.conf" />
    </copy>
  </target>

  <target name="update-avrdude-windows" description="Update the avrdude configuration to latest version." depends="">
      <copy todir="windows/work/hardware/tools/avr/etc/">
        <fileset file="windows/dist/avrdude.conf" />
    </copy>
  </target>
  <!-- not need linux does this already.
    <target name="update-avrdude-linux" description="Update the avrdude configuration to latest version." depends="">
      <copy todir="macosx/work/mpide.app/Contents/Resources/Java/hardware/tools/avr/etc/">
        <fileset file="linux/dist/tools/avrdude.conf" />
    </copy>
  </target>
```

**Comment by ffissore** [comment]
Thanks @ricklon for pulling this up. It's been a while since the avr toolchain became a zip file downloaded at IDE packing time. This is the repository that generates such zip files, for linux, windows and mac https://github.com/arduino/toolchain-avr
I'm therefore closing this
