### ISSUE TITLE
Error on CS811

### ISSUE THREAD

**Issue by mshaz** [arduino/Arduino#6230]
I got this error when running the code on WEMOS D1 Mini. Hope can help me

Soft WDT reset

ctx: cont 
sp: 3ffef3c0 end: 3ffef5a0 offset: 01b0

>>>stack>>>
3ffef570:  3fffdad0 00000000 3ffee548 4020237c  
3ffef580:  feefeffe 00000000 3ffee564 40202b0c  
3ffef590:  feefeffe feefeffe 3ffee580 40100114  
<<<stack<<<
?⸮⸮L)⸮D⸮ ⸮CCS811 Read Example
Hardware ID wrong: 0xFF
Problem with CCS811

CCS811 Air Quality Sensor Example Code
  By: Nathan Seidle
  SparkFun Electronics
  Date: February 7th, 2017
  License: This code is public domain but you buy me a beer if you use this and we meet someday (Beerware license).

  Works with SparkFun CCS811 board https://www.sparkfun.com/products/14181
  Or Combo board https://www.sparkfun.com/products/14241
  Enjoy this code? Buy a board and help support SparkFun! 

  Read the TVOC and CO2 values from the SparkFun CSS811 breakout board

  A new sensor requires at 48-burn in. Once burned in a sensor requires 
  20 minutes of run in before readings are considered good.

  Hardware Connections (Breakoutboard to Arduino):
  3.3V = 3.3V
  GND = GND
  SDA = A4
  SCL = A5

  Serial.print it out at 9600 baud to serial monitor.
*/

#include <Wire.h>

//These are the air quality values obtained from the sensor
unsigned int tVOC = 0;
unsigned int CO2 = 0;

void setup()
{
  Serial.begin(9600);
  Serial.println("CCS811 Read Example");

  Wire.begin();

  if (configureCCS811() == false)
  {
    Serial.println("Problem with CCS811");
    while(1);
  }
  else
  {
    Serial.println("CCS811 online");
  }
}

void loop()
{
  if (dataAvailable())
  {
    readAlgorithmResults(); //Calling this function updates the global tVOC and CO2 variables

    Serial.print("CO2[");
    Serial.print(CO2);
    Serial.print("] tVOC[");
    Serial.print(tVOC);
    Serial.print("] millis[");
    Serial.print(millis());
    Serial.print("]");
    Serial.println();
  }
  else if (checkForError())
  {
    printError();
  }

  delay(1000); //Wait for next reading
}

**Comment by cmaglie** [comment]
This issue tracker is not for assistance on personal projects, please use the [forum](https://forum.arduino.cc/) instead.

(also, I suggest you to be more descriptive in your request, because is not clear at all what your problem is)
