### ISSUE TITLE
[Library Manager] Please add SerialUI

### ISSUE THREAD

**Issue by psychogenic** [arduino/Arduino#6233]
Hi,

SerialUI is at:

https://github.com/psychogenic/SerialUI

and it allows you to create an interface available through the USB/Serial with menus, commands and input requests.

Cooler still, it works with _Device Druid_ to give an Arduino an automatic **GUI**:

https://www.youtube.com/watch?v=r6NEJgOIPK4

The reason I'd like to see it added to the library manager is that with this latest version, there's now a _builder_ app available that really lowers the barrier in terms of getting programs running with SerialUI:

https://www.youtube.com/watch?v=QuSCNdB23lw

So having the firmware-side library easy to install would be a boon to neophytes, and generally make the whole process more seamless.

If you'd like to find out more about how these apps work together, there's a dedicated project site:

https://devicedruid.com/

Please don't hesitate to let me know if you have questions or need anything else from me.

Thanks!

**Comment by cmaglie** [comment]
Done!
