### ISSUE TITLE
MKR1000: Crash of VNC/WiFI101 if another device connects to the WLAN

### ISSUE THREAD

**Issue by DieterBurandt** [arduino/Arduino#6237]
I use two Genuino MKR1000 (MR510PB), now Firmware 19.5.2, Arduino 1.8.2, samd: 1.6.14 and 1.6.15, WiFI101: 0.14.1, IDE: VS2017 + Visual Micro 1704.03, (also Atmel  Studio and Arduino IDE), DSL-Router: AVM Fritz!Box 7490 FW:06.83, Access point: AVM FRITZ!Powerline 546E FW: 06.50.

Two MKR1000 Boards:
1) One original bare one
2) One board with user hardware: RTC, SRAM, EEPROM, SD-card, a serial device. Web-pages using modified “Webduino“.

All attached devices are working well. I looked further on regarding my failing WLAN connections. The error occurs within a few Minutes and up to more then 4 hours. Then:

-  The loop is still executed. WiFi.status returns “WL_CONNECTED”.
-  Ping from the MKR1000 to my gateway returns forever “okay”.
-  Reading the internal Mac or reading the signal strength returns 0.
- The Led at Pin 6 is blinking in half second intervals that I  did not programmed.
-  The board is dead in respect to the WLAN. Trying to reconnect mostly fails. (But I don’t know how to reconnect correctly.)
-   After a failure, sometimes two power fail and reboots are required the get access to the WLAN again. The ATWINC1501 Model B firmware or the WiFi101 driver seems being crash completely.

I tested a lot to find any reproducible procedure to force the bug. I am sure there is more than one reason for the failure. I found one method to reproduce it:

If I connect one of our two laptops to the WLAN both of my MKR1000 fails exactly in the same moment. When you insert code in the loop that causes the LED to blink, you will see a short wait time of around a second when another device is connecting to the WLAN and then sometimes the connection of the MKR1000 fails and sometimes not. With my two laptops, the bug is well reproducible, but not with my mobile.  I also could see, that the second MKR1000 often crash when I connected the first one to the WLAN. (One of my MKR1000 is running my application, the other one is running the example code of “WiFiWebServer”.) On failure, after around a minute, the MKR1000 enters a low power mode even noLowPower is specified.

I tested with my two access points, I used  CCMP or TKIP, I changed a pin and did not use pin 7, I took power bank to supply the bare MKR1000 far away from electrical noise, nothing of that had any influence on the bug.

This failure may be specific to some access points/routers products. But keep in mind that the  AVM Fritz!Boxes have a market share of more than 50% in Germany and they sell their products in a lot of countries too. Other users also reported trouble with the MKR1000 loosing the WLAN connection already.

With this bug, all products using the ATWINC1501 and/or WiFi101 ares not usable for me. I spend a lot of time, but I must stop my project with this board. My project will clearly delayed by month.

At is worth looking at two points: 

1) The MKR1000 was extremely sensitive to electrical noise I think induced by my screen that was near by. If I did come near to the board with my hand (5 to 10 cm not touching) the MKR1000 mostly stopped working. After initializing all user pins properly the MKR1000 was stable. There will be a pin configured as input activated to handling interrupts.  (tested using FW: 19.4.4).  One should clarify which pins are used by the VNC and also if there are pins are not initialized properly . A user must know which of the pins can be used and which of them not. In contrast tp the documentation digital pin 7 seems not to be used by the VNC, but pin 6. But despite this pin 6 can be used by the user with restrictions.

2) If you try to connect to an access point (or a router) with an SSID and a key, WiFI101 uses CCMP or TKIP. In both cases „WiFi.encryptionType();“ returns ENC_TYPE_TKIP.  That is incorrect if CCMP is actually used. You can check this using „WifoInfoView“ from www.nirsoft.net on your Laptop and changing the mode of the access point. Other users got already confused and thought only TKIP is supported.

For security reason CCMP setting of the cipher mode must be supported without any fallback to TKIP.

(It would be very interesting to see if the above crash still exist, if you define the encryption method explicitly.)

**Comment by facchinm** [comment]
Moved to https://github.com/arduino-libraries/WiFi101/issues/161
