### ISSUE TITLE
[Library Manager] Please add Rosserial arduino lib

### ISSUE THREAD

**Issue by frankjoshua** [arduino/Arduino#6239]
https://github.com/frankjoshua/rosserial_arduino_lib

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value set in your library.properties file. For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by frankjoshua** [comment]
OK, I added 0.7.7 tag.

**Comment by cmaglie** [comment]
Done!
