### ISSUE TITLE
[Library Manager] Please add LM35

### ISSUE THREAD

**Issue by ggzucco** [arduino/Arduino#6240]
https://github.com/ggzucco/LM35

Thanks

**Comment by per1234** [comment]
You need to add a library.properties file to your repository:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Details on this the library.properties file here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by ggzucco** [comment]
I uploaded the library.properties

**Comment by cmaglie** [comment]
Tag 1.0 doesn't have the library.properties file, you probably created the file after making the release.

https://github.com/ggzucco/LM35/tree/1.0

a quick fix is to delete the tag 1.0.1 and make it again on master.

**Comment by ggzucco** [comment]
ok, I do it =)

https://github.com/ggzucco/LM35

**Comment by cmaglie** [comment]
Done!
