### ISSUE TITLE
Cannot Complile 

### ISSUE THREAD

**Issue by NKT007** [arduino/Arduino#6242]
Hey!!!
I am unable to compile programs in my Arduino software. The error message mentioned below pops up every-time I try to compile any code
ERROR MESSAGE:
Arduino: 1.8.0 (Windows 10), Board: "Arduino Duemilanove or Diecimila, ATmega328"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\NKT\Documents\Arduino\libraries -fqbn=arduino:avr:diecimila:cpu=atmega328 -ide-version=10800 -build-path C:\Users\NKT\AppData\Local\Temp\arduino_build_7236 -warnings=all -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Program Files (x86)\Arduino\examples\03.Analog\AnalogInput\AnalogInput.ino

Even though I tried using other boards to compile it was of no help.
Does anyone know the solution for  this problem.

**Comment by facchinm** [comment]
Hi @NKT007 ,
could you try updating to IDE 1.8.2? Also, the output is not useful at all since it doesn't report the actual error, only the commandline used :wink: 
Before posting here try asking the [forum](forum.arduino.cc) since this repo only tracks IDE bugs and improvements, thanks!
