### ISSUE TITLE
Serial.println(1.23456, 4) gives "1.2346"   6-5

### ISSUE THREAD

**Issue by abcyixyz** [arduino/Arduino#6246]
![arduino](https://cloud.githubusercontent.com/assets/15166358/25571785/f1613186-2e65-11e7-8db7-3410ef727424.PNG)
https://www.arduino.cc/en/Serial/Print

**Comment by mikaelpatel** [comment]
1.23456 printed with 4 decimals will give 1.2346 as it gets rounded up and not truncated.

**Comment by abcyixyz** [comment]
Thank you
