### ISSUE TITLE
J1850-PWM-Encoding-Library

### ISSUE THREAD

**Issue by VittorioEsposito** [arduino/Arduino#6249]
Arduino library which allow to communicate using j1850 pwm encode
https://github.com/VittorioEsposito/J1850-PWM-Encoding-Library

**Comment by cmaglie** [comment]
Tag 1.0.1 doesn't have the library.properties file, you probably created the file **after** making the release.

https://github.com/VittorioEsposito/J1850-PWM-Encoding-Library/tree/1.0.1

a quick fix is to delete the tag 1.0.1 and make it again on master.

**Comment by VittorioEsposito** [comment]
Fixed

**Comment by cmaglie** [comment]
Done!
