### ISSUE TITLE
Eror downloading ...package_esp8266com_index.json on MS Windows 7 & 10

### ISSUE THREAD

**Issue by crs94878** [arduino/Arduino#6258]
Hi
I try to download ESP8266 by ESP8266 Community Forum in Boards Manager.
Error appears:
Error downloading http://arduino.esp8266.com/package_esp8266com_index.json
Error downloading http://arduino.esp8266.com/staging/package_esp8266com_index.json
I tried downloading  on 2 computers.

Yesterday everything worked.

**Comment by per1234** [comment]
See https://github.com/esp8266/Arduino/issues/3198
This is caused by esp8266.com being down. It has nothing to do with the Arduino IDE.
