### ISSUE TITLE
Enabling serial port monitor during firmware upload breaks upload

### ISSUE THREAD

**Issue by mleko** [arduino/Arduino#6264]
Serial port monitor on init sends reset signal which breaks upload.
It might be good idea to disable Serial port monitor option for the time of firmware upload.

**Comment by facchinm** [comment]
Since c0a99f9ec9f1ed1d7d94b21068ec7f9bf7cb59ea this bug is fixed so IDE 1.8.2 is not affected. I'm closing the issue as solved, please reopen if you can reproduce it in 1.8.2, thanks :slightly_smiling_face:
