### ISSUE TITLE
Add print(int8_t) and println(int8_t) to format ASCII digits as with uint8_t. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#627]
This is [Issue 627](http://code.google.com/p/arduino/issues/detail?id=627) moved from a Google Code project.
Added by 2011-09-06T16:21:59.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

You can apparently distinguish three different single byte types: char, uint8_t, int8_t.  Calling print on the first outputs a single byte (e.g. 'A'); the second the digits as ASCII (e.g. '6' , '5').  We should add an overload for the third to behave the same as the second.

**Comment by NicoHood** [comment]
I  think this ca be achieved via print(int8_t, DEC). Not sure about the minus prefix though. Why not implement this?

**Comment by sandeepmistry** [comment]
This looks good now, here's a sample sketch and output:

```arduino
void setup() {
  Serial.begin(9600);
  Serial.println("begin");
}

void loop() {
  char a = 'c';
  uint8_t b = 'c';
  int8_t c = 'c';

  Serial.println(a);
  Serial.println(b);
  Serial.println(c); 
  Serial.println();
  
  delay(2500);
}
```

```
begin
c
99
99
```

Print out of ```uint8_t``` matches ```int8_t```.

**Comment by NicoHood** [comment]
Nah. You have to test it like this:
```
int8_t number = -23;
```

So this will be printed as some value > 128. So it is not properly implemented.

**Comment by sandeepmistry** [comment]
Hmm, still looks good to be:

```arduino
void setup() {
  int8_t number = -23;

  Serial.begin(9600);
  Serial.println(number);
}

void loop() {
}
```

prints out the following on the Uno:

```
-23
```

**Comment by NicoHood** [comment]
but why? Is this casted to int then? I have not tested this myself, so I do not know how it behaves. A generic int8_t function could give us less code size.

**Comment by sandeepmistry** [comment]
Yes, ```size_t Print::print(int n, int base)``` is called.

**Comment by NicoHood** [comment]
if we implement a special 1 byte version it would be smaller. You should consider this and reopen the issue.
