### ISSUE TITLE
Arduino Software version 1.8.2 Linux 64bit bug 

### ISSUE THREAD

**Issue by TamiSze** [arduino/Arduino#6274]
Hi,
The version for 64bit for Linux downloaded from https://www.arduino.cc/en/Main/Software can not be installed. Additionally the version in the Linux mint manager is way to old. 
I figured out that the version on this homepage: http://www.arduino.org/downloads 
is correct, so this problem is solved, I just wanted to report the other ones.

**Comment by facchinm** [comment]
The bug was solved by https://github.com/arduino/Arduino/commit/bd4921910987bf9ec1c19ed2e9fd1c966180282d and will be included in upcoming IDE release.
