### ISSUE TITLE
[Library Manager] Please add ArduinoFFT

### ISSUE THREAD

**Issue by kosme** [arduino/Arduino#6278]
https://github.com/kosme/arduinoFFT
Fast Fourier Transform library for Arduino for obtaining the main frequency out of a sampled signal.

**Comment by per1234** [comment]
Please read:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
and update your repository to meet the requirements for inclusion in the Library Manager index:
- Add library.properties file
- Create release or tag with version matching the `version` value set in library.properties.

**Comment by kosme** [comment]
Done

**Comment by agdl** [comment]
@kosme there is also a typo in the maintainer field. Please fix it!

**Comment by kosme** [comment]
Thanks! It is fixed now.

**Comment by cmaglie** [comment]
Done!
