### ISSUE TITLE
ERROR: dev-embedded/arduino-ide-1.8.1::alexxy failed (install phase):

### ISSUE THREAD

**Issue by artbody** [arduino/Arduino#6281]
generate-hourly-build-txt:

BUILD SUCCESSFUL
Total time: 43 seconds
>>> Source compiled.
>>> Test phase [not enabled]: dev-embedded/arduino-ide-1.8.1

>>> Install arduino-ide-1.8.1 into /var/tmp/portage/dev-embedded/arduino-ide-1.8.1/image/ category dev-embedded
/usr/bin/install: cannot stat 'dist': No such file or directory
!!! doins: dist does not exist
 * ERROR: dev-embedded/arduino-ide-1.8.1::alexxy failed (install phase):
 *   doins failed
 * 
 * If you need support, post the output of `emerge --info '=dev-embedded/arduino-ide-1.8.1::alexxy'`,
 * the complete build log and the output of `emerge -pqv '=dev-embedded/arduino-ide-1.8.1::alexxy'`.
 * The complete build log is located at '/var/tmp/portage/dev-embedded/arduino-ide-1.8.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-embedded/arduino-ide-1.8.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-embedded/arduino-ide-1.8.1/work/Arduino-1.8.1/build/linux/work'
 * S: '/var/tmp/portage/dev-embedded/arduino-ide-1.8.1/work/Arduino-1.8.1'
 * QA Notice: file does not exist:
 * 
 *      doins: dist does not exist
!!! When you file a bug report, please include the following information:
GENTOO_VM=oracle-jdk-bin-1.8  CLASSPATH="" JAVA_HOME="/opt/oracle-jdk-bin-1.8.0.131"
JAVACFLAGS="-source 1.8 -target 1.8" COMPILER="javac"
and of course, the output of emerge --info =arduino-ide-1.8.1

**Comment by facchinm** [comment]
Hi @artbody ,
you should notify Gentoo developers about this problem. From out side the `ant` script works correctly.
