### ISSUE TITLE
o que quer dizer isto redefinition of 'int pinButton'

### ISSUE THREAD

**Issue by Nazaedeco** [arduino/Arduino#6288]

**Comment by neu-rah** [comment]
quer dizer que a variável é definida mais que uma vez...
em caso de dúvida mostre o código.

**Comment by facchinm** [comment]
Hi @Nazaedeco , the question belongs to the [forum](https://forum.arduino.cc/index.php?board=32.0), in this issue tracker we only collect and solve problems directly related to the IDE, thanks.
