### ISSUE TITLE
Please change Sakura Communication Module library in Lib Manager

### ISSUE THREAD

**Issue by chibiegg** [arduino/Arduino#6296]
Hi.

Please change URL of our SakuraIO library in the library manager:
(We moved the repository to `sakuraio` organization.)

Current : https://github.com/sakura-internet/SakuraIOArduino
New : https://github.com/sakuraio/SakuraIOArduino

Thanks.

**Comment by cmaglie** [comment]
Done!

**Comment by chibiegg** [comment]
thanks a lot!
