### ISSUE TITLE
Stream parseInt() and parseFloat() functions should have an option to not search ahead. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#630]
This is [Issue 630](http://code.google.com/p/arduino/issues/detail?id=630) moved from a Google Code project.
Added by 2011-09-08T18:45:08.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

I'd like to add a parameter to these functions (or some other method) that tells them not to skip ahead in the stream data to find the next number.  Ideally, there should be three options: don't skip anything, only skip whitespace, and skip anything.  Maybe SKIP_NONE, SKIP_ALL, SKIP_NONE.

**Comment by Chris--A** [comment]
An implementation for this has been proposed in #3337

**Comment by sandeepmistry** [comment]
Resolved by #3337.
