### ISSUE TITLE
uMT - a preemptive, real-time multitasker for the ARDUINO AVR boards

### ISSUE THREAD

**Issue by GO01260** [arduino/Arduino#6300]
https://github.com/GO01260/uMT

uMT - a preemptive, real-time multitasker for the ARDUINO AVR boards

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem:

```
JOB 973 - 2017/05/18 22:18:34 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

Please add `sentence` and `url` field in your library.properties, commit and redo the tag.
Once done the library will be automatically published within an hour.
