### ISSUE TITLE
[Library Manager] Please add Sodaq_wdt

### ISSUE THREAD

**Issue by keestux** [arduino/Arduino#6301]
Can you please add this library?

    https://github.com/SodaqMoja/Sodaq_wdt

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem:

JOB 972 - 2017/05/18 22:18:32 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined

Please add sentence and url field in your library.properties, commit and redo the tag.
Once done the library will be automatically published within an hour.
