### ISSUE TITLE
[Library Manager] Please add EmSevenSegment

### ISSUE THREAD

**Issue by ssuhrid** [arduino/Arduino#6307]
https://github.com/ssuhrid/EmSevenSegment

## EmSevenSegment

This is a library to drive multiple-digit 7-segment LED displays using HEF4094B, CD4094B,  CD4094BMS, MC74HCT4094A and other 4094 shift registers. 

### Features
  - Concatenate upto 255 displays using just 3 pins of Arduino
  - Prints both numbers and alphabets
  - Supports both common anode and common cathode displays
  - Directly print multiple integer values
  - Print arrays of numbers/strings
  - Add/remove leading zeros for numbers
  - Choose between left/right alignment of text
  - Blink at specific location on display
  - Clear the display

**Comment by cmaglie** [comment]
Done!
