### ISSUE TITLE
[Library Manager] Please add ghaemShopSmSim Lib

### ISSUE THREAD

**Issue by ghaemshop** [arduino/Arduino#6308]
https://github.com/ghaemshop/ghaemShopSmSim

this library is very simple remote controler by SMS (Sim900A  from SimCom/ or other SIM-Module if it is compatible with)
over **ghaemShopSmSim protocol**

Sample  -> `*RLY=*pass*Motor*ON*3000#`

last release: v3.1.0

**Comment by cmaglie** [comment]
Done!
