### ISSUE TITLE
avrdude fails to upload sketches to Arduino Micro under linux

### ISSUE THREAD

**Issue by HackerInside0** [arduino/Arduino#6309]
Instead it works perfectly under windows 10 without installing the drivers manually.

Here are the avrdude logs:
Under windows: 
https://gist.github.com/HackerInside0/eb3336ecd1b3f03e315930998d5b2065

Under linux ( user mode ):
https://gist.github.com/HackerInside0/f52a96abd3b2ac79dab7669be46ef644

Under linux ( as root ):
https://gist.github.com/HackerInside0/eb456815f097e4c1f8d38f6e788985ce

In this last case, sometime it freezes on : "avrdude: butterfly_recv(): programmer is not responding"

**Comment by facchinm** [comment]
Hi @HackerInside0 ,
the problem is 99,999% related with `modemmanager`. Simply uninstall it from your Linux distribution (it is useless unless you use a 56k modem :slightly_smiling_face: ) and the problem should disappear.

**Comment by HackerInside0** [comment]
It works now.
Thanks
