### ISSUE TITLE
Merge PWMServo library (hardware servo control on pins 9 and 10) into Servo library. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#631]
This is [Issue 631](http://code.google.com/p/arduino/issues/detail?id=631) moved from a Google Code project.
Added by 2011-09-08T21:06:25.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Core

### Original description

It would be cool if the Servo library could use either of two strategies: hardware PWM control if the servos are on pins 9 or 10, and software if not.  This would basically be combining the old servo library with the new one.  See also PWMServo (http://arduiniana.org/libraries/pwmservo/) for an alternative version of the old (hardware-control) servo library.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Servo#5
