### ISSUE TITLE
[Library Manager] Please add KerbalSimPit library

### ISSUE THREAD

**Issue by phardy** [arduino/Arduino#6310]
Library URL is https://bitbucket.org/pjhardy/kerbalsimpit-arduino .

This library provides a serial interface for Arduino devices to communicate with [Kerbal Space Program](https://kerbalspaceprogram.com). It implements the protocol used by an accompanying plugin, at https://bitbucket.org/pjhardy/kerbalsimpit

Library version in `library.properties` is specified as "1.0.0". I wasn't sure precisely what format the tag should be, so have tagged it both `v1.0.0` and `1.0.0`. Would appreciate knowing the preferred format for future releases.

**Comment by cmaglie** [comment]
Done!

Actually the tag can be anything (even `asdjhasd` :-)), so both `v1.0.0` and `1.0.0` works, up to you.
