### ISSUE TITLE
not getting email

### ISSUE THREAD

**Issue by tmieske** [arduino/Arduino#6318]
Not getting an email when registering so I can download newest version of Arduino IDE.

**Comment by matthijskooijman** [comment]
Huh? No need to register when downloading the IDE: https://www.arduino.cc/en/Main/Software

**Comment by cousteaulecommandant** [comment]
To be fair the first link is the Arduino Web Editor (which requires a login), not the Download one, so I understand this may be confusing.  (Maybe the two should be swapped?)

**Comment by matthijskooijman** [comment]
Then perhaps this bug report is about the web IDE, not about downloading the offline one. In any case, I"m closing this issue for lack of a response. @tmieske, feel free to reopen this issue and add further clarification if the problem persists.
