### ISSUE TITLE
Arduino Nano Eagle file broken

### ISSUE THREAD

**Issue by KateElizabeth112** [arduino/Arduino#6321]
The Eagle file for the Arduino Nano schematic currently available is broken. I get the following error message "Error: line 140, column 25: Unexpected ''."

I believe there has been a fix from a previous thread, but the website has not been updated. Happy to apply the fix myself.

**Comment by michaellass** [comment]
More or less connected to #6039 which was reopened now. There seems to exist a fix for the files which hasn't made it to the websites yet.

**Comment by per1234** [comment]
Thanks for pointing that out michaellass! Closing as duplicate of https://github.com/arduino/Arduino/issues/6039 since the issue is already being tracked there and @KateElizabeth112 has already commented on that issue.
