### ISSUE TITLE
Setting it up Arduino Uno R3 not working with USB 3.0

### ISSUE THREAD

**Issue by harshit101** [arduino/Arduino#6323]
The USB 3.0 is not recognized when I am setting up in windows 8 64 bit OS

**Comment by facchinm** [comment]
Hi @harshit101 ,
do you have any USB2 port on the same PC to make sure that the drivers are installed and the board is not faulty? 
Original boards are known to work with any USB version so, if your board is original and it's not getting recognized you should contact the [support](support@arduino.cc) for replacement. 

If the board is a clone with the ch340 usb-to-serial converter you might need additional drivers to make it working and we can't give you further assistance.
Thanks!
