### ISSUE TITLE
Please add new library

### ISSUE THREAD

**Issue by tobeedelafuente** [arduino/Arduino#6330]
Hello!

I would like to kindly request to add this library: https://github.com/meeo/meeo-arduino to the Library Manager. Please let me know if you have any concerns with the library

**Comment by cmaglie** [comment]
@tobeedelafuente 
a git tag is required to publish the library, please add it to the repository:
https://github.com/meeo/meeo-arduino/tags

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

**Comment by tobeedelafuente** [comment]
Hello @cmaglie, I added the release tag. Let me know if you have any concerns. Thank you

**Comment by cmaglie** [comment]
Done!

**Comment by tobeedelafuente** [comment]
Thank you so much!
