### ISSUE TITLE
Please consider adding a new repository specifically for managing addition (and removal) of libraries in the Library manager

### ISSUE THREAD

**Issue by feikname** [arduino/Arduino#6332]
I feel like they're taking a substantial amount of the issues in this repository and getting out of hand for searching real issues related to the board manager. Or perhaps a `add-library-request` label could be added to them, so it'd be possible to blacklist it whilst doing searches.

**Comment by matthijskooijman** [comment]
Sounds like a good plan! In addition to cluttering the issue list, they also cause a lot of noise among the email notififcation of issues.

In fact, perhaps the board manager config file / library list (which I assume exists) can be managed in git, so people can even submit PRs themselves for adding libraries?

**Comment by feikname** [comment]
\*bump\*

**Comment by feikname** [comment]
Apologies for pinging you guys here, but there has been no official reply since I created this issue 3 months ago.

@cmaglie @mastrolinux @agdl @facchinm

**Comment by per1234** [comment]
All management of the Arduino Library Manager index is now to be done in a dedicated repository:
https://github.com/arduino/library-registry

I will be transferring and redirecting all incoming issues from this repository over there, getting this repo one step closer to being dedicated to the Arduino IDE.

I created a pinned issue to bring more awareness to the change: https://github.com/arduino/Arduino/issues/11588
