### ISSUE TITLE
List of libraries is re-downloaded everytime that the Library Manager is opened

### ISSUE THREAD

**Issue by feikname** [arduino/Arduino#6333]
Everytime that the Board Manager is opened, the library list is fetched and rebuilt again, even if there were no changes since the previous fetch. This behaviour makes opening the library manager a slow process for those with no so great internet speeds and wastes data unnecessarily, furthermore, rebuilding the library list takes a bit of time, which is annoying.

Perhaps a `Last-Modified` header could be a good solution to this?

**Comment by facchinm** [comment]
Fixed by #9023
