### ISSUE TITLE
There is no documentation regarding the custom auto-formatting options with AStyle

### ISSUE THREAD

**Issue by feikname** [arduino/Arduino#6334]
The only places I could see referencing the possibility of using an AStyle `formatter.conf` are #2960 and #5012 which aren't intuitive places to look after.

The creator of #2960 even said it:
> Thanks, I guess next (silly) question could be - why is this not VISIBLY published?

**Comment by per1234** [comment]
This is now documented here: https://github.com/arduino/Arduino/wiki/Arduino-IDE-Auto-Format-configuration
