### ISSUE TITLE
[Library Manager] A simple Sensor Wrapper

### ISSUE THREAD

**Issue by pachonk** [arduino/Arduino#6343]
Here's a link to the repository:
https://github.com/pachonk/Sensor

Thank you!

**Comment by cmaglie** [comment]
Done!

**Comment by pachonk** [comment]
Hmm, is this supposed to show up in this list?
https://www.arduino.cc/en/reference/libraries

**Comment by cmaglie** [comment]
No, it will show up in the library manager of the Arduino IDE.

https://www.arduino.cc/en/Guide/Libraries#toc2

**Comment by pachonk** [comment]
Sounds good. Saw it there already, just wanted to verify about the other one.
