### ISSUE TITLE
[Library Manager] Babelduino - A library that allows writing and highlighting code in local language

### ISSUE THREAD

**Issue by karolsarnacki** [arduino/Arduino#6346]
Hi,

Please add a new Library to the Manager: [Babelduino](https://github.com/elpassion/Babelduino)

Babelduino is a library that allows writing and highlighting code in the local language. Currently, most common Polish keywords are supported, but new languages and keywords can be easily added:

Link to the repo:
https://github.com/elpassion/Babelduino

Usage example:
```c
void loop() {
  auto distance = radar.ping_cm();
  
  if (distance < 15) {
    go_forward(250);
  } else {
    turn_right(250);
    go_forward(100);
  }
}
```
⬇ *(Translated into Polish)*
```c
procedura powtarzaj() {
  niech odleglosc = radar.ping_cm();
  
  jezeli (odleglosc < 15) {
    do_przodu(250);
  } w_przeciwnym_razie {
    obroc_w_prawo(250);
    do_przodu(100);
  }
}
```

**Comment by cmaglie** [comment]
Done!
