### ISSUE TITLE
Incorporate latest changes to the Ethernet library. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#635]
This is [Issue 635](http://code.google.com/p/arduino/issues/detail?id=635) moved from a Google Code project.
Added by 2011-09-09T03:38:36.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

Grab Adrian's latest.

**Comment by sandeepmistry** [comment]
Closing, this is really old, I see no reference to "Adrian's latest" patch in the [original issue](https://code.google.com/archive/p/arduino/issues/635).
