### ISSUE TITLE
arduino download new packages has error

### ISSUE THREAD

**Issue by bigelite** [arduino/Arduino#6355]
Hi. I have installed a fresh copy of the IDE but continue to get this error when opening the boards manager. I have followed instructions on the forum to rectify the problem but nothing works.
I am running Windows 10.
I can access this URL from my browser.
I am able to install some of the boards that are listed in the boards manager, but most give errors when trying to install.

![image](https://user-images.githubusercontent.com/21035685/26870596-bf404dbc-4b85-11e7-8d0b-30d04b4ad57e.png)

Error downloading http://downloads.arduino.cc/packages/package_index.json

I've deleted  staging/packages folder.
and i tried  this one :
Copy: setx _JAVA_OPTIONS -Djava.net.preferIPv4Stack=true

i anyone can help me?

**Comment by facchinm** [comment]
Hi @bigelite ,
if you click on the link (http://downloads.arduino.cc/packages/package_index.json) are you able to see the content? It appears to be a network problem of some sort (or an incomplete proxy configuration)

**Comment by bigelite** [comment]
yes i can see the JSON into that link.
![image](https://user-images.githubusercontent.com/21035685/27031200-85b0bb56-4f84-11e7-99ca-8f1dde955928.png)
here is windows proxy setting,

and 
![image](https://user-images.githubusercontent.com/21035685/27031264-dcc59ba0-4f84-11e7-958f-979d8dbe31f2.png)
this is arduino preferences network.
![image](https://user-images.githubusercontent.com/21035685/27031304-068b651e-4f85-11e7-859e-dbafe9dfd982.png)

but error is still exist!

**Comment by Squirrelwolf** [comment]
I suppose this is related, considering previous similar problems. I'm trying to install Intel Curie Board files, but I get "Error downloading https://downloadmirror.intel.com/25470/eng/arc-toolchain-osx-arcem-1.0.1.tar.bz2"

**Comment by feikname** [comment]
Perhaps the the problem is caused by a firewall or an antivirus?

**Comment by Squirrelwolf** [comment]
Regarding my problems: The server seems to be working again. (And no firewall or antivirus here.)

**Comment by bigelite** [comment]
does it occur using by kaspersky antivirus? how can i prevent antivirus? @feikname

**Comment by facchinm** [comment]
@bigelite your AV should have some sort of "[whitelist](https://support.kaspersky.com/12677#block2)", try adding the IDE to this list and please report if it worked, thanks!

**Comment by per1234** [comment]
@bigelite did you ever try whitelisting the Arduino IDE in your antivirus? If so, did it solve this issue for you?

**Comment by per1234** [comment]
Closing due to lack of response from @bigelite.
