### ISSUE TITLE
I made a LEGO WEDO2.0 ble library

### ISSUE THREAD

**Issue by lemio** [arduino/Arduino#6356]
Can this be added to the Arduino third party list of available libraries?
https://github.com/lemio/esp32_ble_wedo

**Comment by per1234** [comment]
Do you mean Library Manager? If so you need to make a release or tag matching the `version` value set in your library.properties. For more information please see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by lemio** [comment]
Like this:
https://github.com/lemio/esp32_ble_wedo/releases/tag/1.0

**Comment by cmaglie** [comment]
Done thanks!
