### ISSUE TITLE
IDE window: CTRL-MouseWheel for zoom

### ISSUE THREAD

**Issue by snobu** [arduino/Arduino#6359]
The inability to zoom in/out the code window is slightly annoying, i'm sure i'm not the only out there bothered by it. What's the development effort required to implement either `CTRL-MouseWheel` and/or `CTRL-+`, `CTRL-minus`? Do we have to move away from Java? :) Or just bind to some events?

I am aware a font size can be specified under Preferences, but that's `CTRL-comma - click-select - type - click`, not exactly the best UX.

**Comment by bengtmartensson** [comment]
Possibly Java 9, due next month, will bring something here?

**Comment by facchinm** [comment]
That's a good suggestion , thanks for posting! It should be fairly easy to trap the event inside the Editor view and apply the preference. Hot-reloading could be a bit more difficult but feasible indeed. If anyone wants to try coding a solution we'll be super happy to test it :smile:

**Comment by skishida** [comment]
Now, font size may become a negative value in #6551 change and at that time, the IDE will not start.
The temporary fixing approach is edit `editor.font` in `preferences.txt`.
