### ISSUE TITLE
include solution for Adafruit Trinket for Linux/Ubuntu

### ISSUE THREAD

**Issue by jerabaul29** [arduino/Arduino#6360]
Hi!

It is well known that the Adafruit Trinket (based on ATtiny85) has problems with the Arduino IDE on Linux/Ubuntu. For my part, trying to upload code from the Arduino IDE, I get:

```
An error occurred while uploading the sketch
avrdude: error: usbtiny_transmit: Input/output error
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.


avrdude: error: usbtiny_transmit: Input/output error
```

But applying the solution offered here solved the problem, and I am able to upload code successfully now:

https://andijcr.github.io/blog/2014/07/31/notes-on-trinket-on-ubuntu-14.04/

The solution is basically a change in some definitions for the ATtiny in the avrdude.conf:

https://gist.github.com/andijcr/f4a660fde4035fb0a3aa

Would it be possible to make the arduino IDE automatically apply those changes when dealing with the Trinket? If not, what is preventing you from doing this? I ask here but maybe I should see with the Adafruit library, just tell me and I will open an issue there in this case ;)

**Comment by facchinm** [comment]
Moved to https://github.com/arduino/avrdude-build-script/issues/7
