### ISSUE TITLE
Library for DPS310 Pressure Sensor

### ISSUE THREAD

**Issue by mhollfelder** [arduino/Arduino#6364]
Dear all,

could you please add the following library to the library manager?

https://github.com/Infineon/DPS310-Pressure-Sensor

We have added a new release V1.0.1 for the Arduino IDE.

Thank you very much in advance!

Best regards,

Manuel

**Comment by cmaglie** [comment]
Done!

**Comment by mhollfelder** [comment]
Great, thank you very much!

Best,

Manuel
