### ISSUE TITLE
[Library Manager] Please add RFD77402 Library

### ISSUE THREAD

**Issue by nseidle** [arduino/Arduino#6366]
Hi,

Please add RFD77402 time of flight sensor library:

https://github.com/sparkfun/SparkFun_RFD77402_Arduino_Library

Thanks!
-Nathan

**Comment by cmaglie** [comment]
hi @nseidle,

this library is named `SparkFun RFD77402 Distance Sensor - VCSEL Time of Flight`, but the dash `-` may create problems on some OS. May you rename the library and remove the `-`?
(also a shorter name may be better, but this up to you :-))

**Comment by cmaglie** [comment]
ops sorry, scratch that, I've confused the allowed chars... `-` is fine, I'm going to add the library!

**Comment by cmaglie** [comment]
Done!
