### ISSUE TITLE
A new library

### ISSUE THREAD

**Issue by Onno-Dirkzwager** [arduino/Arduino#6374]
Could you please add this library to the "Manager"

https://github.com/iotappstory/ESP8266-Library-V1.0

Any feedback or recommendations are welcome!

**Comment by per1234** [comment]
You need to create a tag or release with a version matching the value of the `version` property in library.properties:
https://github.com/iotappstory/ESP8266-Library-V1.0/blob/master/library.properties#L2

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Onno-Dirkzwager** [comment]
Thankyou for your feedback.
We just did: https://github.com/iotappstory/ESP8266-Library-V1.0/releases

**Comment by Onno-Dirkzwager** [comment]
Per1234, 
thanks for the feedback. We made the tag / release: 
https://github.com/iotappstory/ESP8266-Library/releases/tag/1.0.0

And removed -V1.0 from the lib name:
https://github.com/iotappstory/ESP8266-Library

**Comment by cmaglie** [comment]
Done!

**Comment by Onno-Dirkzwager** [comment]
Thank you sir!
