### ISSUE TITLE
Compile faster - only recompile files that have changed [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#638]
This is [Issue 638](http://code.google.com/p/arduino/issues/detail?id=638) moved from a Google Code project.
Added by 2011-09-11T15:25:43.000Z by [paul.sto...@gmail.com](http://code.google.com/u/102276914943260257800/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Enhancement, Priority-Medium, Milestone-1.0.1, Component-IDE
### Original description

**What change would like to see?**

Avoid recompiling when the sources have not changed.  Just reuse the compiled .o files from previous compilation.  Make, Ant and other build systems do this.  Arduino can too!

**Why?**

Faster Upload  :-)

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

Done properly, it should be fully compatible.  I originally submitted this as part of a patch on issue 393.  At the time, it was decided to only reorder the compile process so errors in the sketch would report faster.  A separate issue was suggested, and here it is!

I have recently improved this code and I will be releasing it as part of Teensyduino, to solicit feedback and bug reports.  This issue is meant as a placeholder for users to comment on how much (or how little) improvement this makes in Upload times, and to report any bugs or compatibility problems.

When/if there's enough confidence in the value and reliability to accept this feature into Arduino, I'll prepare a patch.

**Comment by per1234** [comment]
Implemented via:

- https://github.com/arduino/Arduino/commit/b0ae6e764d6d1a43eee567dd29869739a6687e26
- https://github.com/arduino/Arduino/commit/1a7fe19348404226c3a28b6fc77fa1ac6a246e2e
- https://github.com/arduino/Arduino/commit/24a0dfdf000ae22af058f4ea3894407582353722
