### ISSUE TITLE
Arduino Motor Shield Documentation

### ISSUE THREAD

**Issue by jackdewhurst** [arduino/Arduino#6382]
Is there any documentation for the motor shield? Specifically this product - https://www.arduino.cc/en/Main/ArduinoMotorShieldR3.

The 'Getting Started' section links to a general page where the shield isn't listed in the right column ~~and then later also refers to "examples on how to use the WiFi interface are available in the WiFi101 Library reference page."~~ which is surely irrelevant to this shield?

Am I missing something or are the only guides on how to use this shield on 3rd party sites like this - https://www.allaboutcircuits.com/projects/arduino-motor-shield-tutorial/

**Comment by per1234** [comment]
I see there is now a tutorial for the Arduino Motor Shield Rev3:

https://docs.arduino.cc/tutorials/motor-shield-rev3/msr3-controlling-dc-motor

Hopefully that will be sufficient to consider this resolved. If anyone has suggestions for specific additional information that should be provided, please open an issue in the new dedicated repository for the Arduino documentation content:

https://github.com/arduino/docs-content/issues
