### ISSUE TITLE
Doc error on  analog pins pullup resistors

### ISSUE THREAD

**Issue by fivage** [arduino/Arduino#6389]
Online doc error:

digitalWrite should be pinMode

https://www.arduino.cc/en/Tutorial/AnalogInputPins

> Pullup resistors
> 
> The analog pins also have pullup resistors, which work identically to pullup resistors on the digital pins. They are enabled by issuing a command such as 
> 
> **digitalWrite**(A0, INPUT_PULLUP);  // set pullup on analog pin 0 
>

**Comment by SimonePDA** [comment]
Fixed, thanks for pointing out.
