### ISSUE TITLE
can Arduino 101 access Wifi using Yun shield?

### ISSUE THREAD

**Issue by chanhyeoni** [arduino/Arduino#6403]
can Arduino 101 access Wifi using Yun shield?

Thank you

**Comment by facchinm** [comment]
Hi @chanhyeoni ,
this is a question for the [forum](https://forum.arduino.cc) :wink: Anyway, yes, it can provide WiFi connectivity but you'll be unable to perform an OTA upload since the 101 bootloader can't communicate via UART nor SPI.
