### ISSUE TITLE
IDE 1.8.3 installer

### ISSUE THREAD

**Issue by Camper-Guy** [arduino/Arduino#6406]
The installer for 1.8.3 thinks it is installing 1.6.3.  If you have 1.6.3 on your compute it will not install 1.8.3 until you unstall  1.6.3

**Comment by facchinm** [comment]
Hi @Camper-Guy ,
if you install the IDE with the exe installer it always tries to uninstall any other version already installed. You can have 2 (or more) coexisting versions by using the zip package (which doesn't register the file association, so double click on "ino" files will open the older IDE).
Thanks
