### ISSUE TITLE
DNS timeout hardcoded

### ISSUE THREAD

**Issue by corymayer** [arduino/Arduino#6414]
Line 141 in Dns.cpp has a hardcoded 5 second timeout for DNS lookups. It causes a hang intermittently in my code. Can this be a configurable value?

`ret = ProcessResponse(5000, aResult);`

**Comment by facchinm** [comment]
Hi @corymayer , which board + shield are you using? The issue should be moved to the relevant repo ([ESP8266](https://github.com/esp8266/Arduino) maybe) or library ([Ethernet](https://github.com/arduino-libraries/ethernet) maybe). Thanks!

**Comment by corymayer** [comment]
@facchinm It's an Arduino Ethernet (no shield)

**Comment by facchinm** [comment]
Move to https://github.com/arduino-libraries/Ethernet/issues/48, thanks!
