### ISSUE TITLE
Ethernet library transmit buffer free space [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#642]
This is [Issue 642](http://code.google.com/p/arduino/issues/detail?id=642) moved from a Google Code project.
Added by 2011-09-16T15:14:44.000Z by [t...@prolectron.com](http://code.google.com/u/100426908544959980659/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

While checking the code in the ethernet library and the w5100 datasheet, I discovered a utility function that should be included in the ethernet library.

The w5100 datasheet specifies before writing to the transmit buffer, you must check the transmit buffer free space register first to insure enough space is available for the next data send.

The function is already available in the w5100.cpp file. getTXFreeSize();

It should be included in the Arduino ethernet library, since it is now possible to send large amounts of data from the SD. This would not be too apparent on a localnet, but when the internet bogs down, or bandwidth restrictions take effect, this could cause a problem.

I added this in Client.cpp below the Client::available() function and it works well.

int Client::free() {
  if (_sock != MAX_SOCK_NUM)
    return W5100.getTXFreeSize(_sock);
  return 0;
}

I added this in Client.h below the declaration for available()

virtual int free();

To find the transmit buffer free space remaining in the w5100, it is about like the Client::available() function.

int freeSpace = client.free();

The variable freeSpace would contain the transmit buffer free space remaining in bytes. 

Writing to the transmit buffer when there is insufficient room will cause errors.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#23
