### ISSUE TITLE
Add column-mode editing to the IDE's text editor

### ISSUE THREAD

**Issue by TheBetaFruit** [arduino/Arduino#6425]
It would be awesome to have a column-mode for the editor. This makes it really easy to replace whole columns of content at once.

Like in Visual Studio or Notepad ++, it could be activated using the Alt+Shift+ArrowKey Combination.

**Comment by facchinm** [comment]
This should be first implemented by RSyntaxTextArea (issue here https://github.com/bobbylight/RSyntaxTextArea/issues/90), feel free to comment on that issue to gain traction and speedup the implementation :wink:

**Comment by per1234** [comment]
It should be noted that this feature was previously available in the Arduino IDE before the switch to RSyntaxTextArea in Arduino IDE 1.6.5 (see https://forum.arduino.cc/?topic=333659).

**Comment by CyberSwatTeam990000** [comment]
Is this ever coming? It's a pretty usual thing. I wanna comment out a whole method, I have to go line to line and double tap, what is this the 1970's lol

**Comment by per1234** [comment]
Great news everyone! This requested functionality is now available in [Arduino IDE 2.x](https://github.com/arduino/arduino-ide). By default, it uses the same standard keyboard shortcut as VS Code and Notepad++.

It's still in the beta development phase, but if you like, you're welcome to try it out:
https://www.arduino.cc/en/software#experimental-software
