### ISSUE TITLE
delay() and "void init( void )" can't be used  in the same sketch

### ISSUE THREAD

**Issue by MitchiLaser** [arduino/Arduino#6426]
Using the _delay()_  function and a self-written function called "_void init ( void )_" is not possible and causes the following error:

wiring.c.o (symbol from plugin): In function `__vector_16':
(.text+0x0): multiple definition of `init'
sketch/sketch_jun25a.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Fehler beim Kompilieren für das Board Arduino Nano.

Here is some example sketch that you can only compile when you remove the _delay(1000)_ in the loop function:

_void setup() {_
  _init();_
_}_
_void loop() {_
  _Serial.println("Hello World");_
  _delay(1000);_
_}_
_void init(void) {_
  _Serial.begin(9600)_
_}_

**Comment by PaoloP74** [comment]
Funcion init() is defined here: https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Arduino.h#L128

**Comment by MitchiLaser** [comment]
But there is still no possibility to use a function called _void init(void)_ inside an arduino Sketch

**Comment by facchinm** [comment]
Hi @MitchiLaser ,
`init()` function is reserved, just like `main()` . In your sketch you should use less generic names or wrap everything in a different namespace (or a class, as you prefer).
