### ISSUE TITLE
BUGS  IN NEW IDE

### ISSUE THREAD

**Issue by dalwinder1578singh** [arduino/Arduino#6427]
I have downloaded new IDE , just for testing purpose i uploaded slandered basic blink sketch.  it gives pinMode not declare in-scope. and don't compile. please give me feedback what is to be done. thanks

**Comment by per1234** [comment]
Also posted at http://forum.arduino.cc/index.php?topic=485832

**Comment by matthijskooijman** [comment]
The forum is a better place for this, so I'm closing this report. Also, it seems unlikely that something simple as pinMode is broken in the newest IDE version, so there is likely something in your setup that breaks this. Without more information (as pert requested on the forum), nobody can help you.
