### ISSUE TITLE
Only .pde file with same name as sketch is renamed to .ino on save-as. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#643]
This is [Issue 643](http://code.google.com/p/arduino/issues/detail?id=643) moved from a Google Code project.
Added by 2011-09-16T16:43:36.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Open a sketch with multiple .pde files.
2. Do a Save-As.

**What is the expected output? What do you see instead?**
All the .pde files should get a .ino extension, but only one does (the one with the same name as the sketch).

**Comment by ffissore** [comment]
Fixed a long time ago
