### ISSUE TITLE
Wrong schematic (and text) in ShiftOut Tutorial

### ISSUE THREAD

**Issue by Liam18** [arduino/Arduino#6433]
The issue is with this tutorial: https://www.arduino.cc/en/Tutorial/ShiftOut

The capacitor is shown in multiple schematics between `latchPin` (`ST_CP`, `STCP` or `RCLK`) and `GND`. However, it should be placed between `VCC` and `GND`.

The Texas Instruments datasheet for SN74HC595 shows the correct capacitor placement in `Figure 5` under `10.2 Typical Application`: http://www.ti.com/lit/ds/symlink/sn74hc595.pdf

This has been discussed on the Arduino StackExchange page as well as the Arduino forum:

- https://arduino.stackexchange.com/questions/39827/is-the-shiftout-tutorial-on-the-official-arduino-website-really-wrong-regarding
- https://forum.arduino.cc/index.php?topic=408135.0

I hope this is all the information you need. Please tell me, if there's something I could do or if I did something wrong. 😳 Thank you.

**Comment by Liam18** [comment]
Another source for the corrected capacitor placement: [SN74HC595 - Texas Instruments](http://www.ti.com/lit/ds/symlink/sn74hc595.pdf) (See Figure 5 under 10.2 Typical Application)

**Comment by wsshambaugh** [comment]
Adding another reference to where this was an issue: https://arduino.stackexchange.com/questions/44291/weird-output-from-chained-74hc595-shift-registers

The shiftOut function has an operating frequency that is fast enough to be very sensitive to a non-decoupled power supply, and so getting the capacitor right here is more than a technicality - it's essential for the solid operation of the circuit. 0.1uF was failing in the above link, and 10uF was working. Recommend changing the drawing cap value to 10uF. 

Also, as brought up in the above posts, there is an overcurrent potential on the chips for LEDs with the resistor values as listed at 220ohm. Bumping them up to 470ohm should resolve this.

**Comment by SimonePDA** [comment]
Fixed schematics with new 470 ohm resistors and 10uF capacitor wired to VCC and GND.

Thanks for pointing out these changes.
