### ISSUE TITLE
Arduino IDE   Save and Save As

### ISSUE THREAD

**Issue by Feroli13** [arduino/Arduino#6434]
Hello,
Please Help.
On My arduino IDE, The option (File- Save)  and (File - Save As) are not active, so I Can't save my Sketck.
How to solve?
Thanks.

Fernando
![image](https://user-images.githubusercontent.com/16353019/27634623-d4e76aac-5bfb-11e7-97e9-ed0e874e839d.png)

**Comment by Feroli13** [comment]
Hello,
Please Help.
On My arduino IDE, The option (File- Save) and (File - Save As) are not active, so I Can't save my Sketck.

![sem nome](https://user-images.githubusercontent.com/16353019/27634741-6bec05c0-5bfc-11e7-9561-a14416c15e1a.jpg)

How to solve?
Thanks.

Fernando

**Comment by cmaglie** [comment]
You've the "Use external editor" preference set (that means that your sketch is already saved).

**Comment by Feroli13** [comment]
OK.

Solved.

Thanks.

Fernando

2017-06-28 12:31 GMT+01:00 Cristian Maglie <notifications@github.com>:
