### ISSUE TITLE
[library manager] Please add AVRUtils library to library manager

### ISSUE THREAD

**Issue by SConaway** [arduino/Arduino#6436]
Please add the following repository to the library manager listing.

https://github.com/SConaway/AVRUtils

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file. For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by SConaway** [comment]
I have done so.

**Comment by SConaway** [comment]
Bump.

**Comment by cmaglie** [comment]
Done, sorry for the delay!

**Comment by SConaway** [comment]
Thank you!
