### ISSUE TITLE
[Library Manager] Remove 'BlueRobotics MS5837-30BA' duplicate

### ISSUE THREAD

**Issue by jaxxzer** [arduino/Arduino#6458]
We changed the name of the library some time ago, but the older one still appears in the manager. The one to be removed is the lower one with '30BA' in the title.

![screenshot 2017-07-04 11 58 21](https://user-images.githubusercontent.com/8315108/27837031-1dfd9eba-60b0-11e7-83e7-ff9b587c80f4.png)

**Comment by cmaglie** [comment]
Rename done, sorry for the delay!
