### ISSUE TITLE
Merge Pull Request #21 for Emacs Keybindings [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#646]
This is [Issue 646](http://code.google.com/p/arduino/issues/detail?id=646) moved from a Google Code project.
Added by 2011-09-17T15:55:19.000Z by [ulrich.moritz](http://code.google.com/u/ulrich.moritz/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

Take a look at the Github pull request #21 from ndrake (https://github.com/arduino/Arduino/pull/21) which adds Emacs Keybindings for forward/backward up/down, begin/end of line

**Why?**
Most editors on OS X and other systems support these as these keybindings (ctrl-f, ctrl-b, ctrl-p, ctrl-n, ...) are much more convenient than hitting the cursor keys.

It would also improve the user experience on OS X as the system supports these keybindings out of the box. These missing bindings make Arduino look like a non-osx application. 

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
As these keybindings aren't bound to anything, there would be no incompatibility.

The pull-request also merges nicely on the new-branch.

**Comment by ffissore** [comment]
#21 has been rejected

**Comment by thomasaw** [comment]
Disappointed that this was rejected. What is the acceptance process? Is there a forum where discussion occurs?

**Comment by ffissore** [comment]
There is no formal acceptance process. Most of the features gets proposed and implemented. A proposed feature gathers feedback: see #3243 for example. If feedback is positive and feature does not disrupt the IDE user experience, it gets merged.
