### ISSUE TITLE
[Library Manager] BlueDot BME280 Library - Update

### ISSUE THREAD

**Issue by BlueDot-Arduino** [arduino/Arduino#6467]
Please add

https://github.com/BlueDot-Arduino/BlueDot_BME280

to the library manager.

Thank you!

**Comment by per1234** [comment]
Your library was already added to the Library Manager: https://github.com/arduino/Arduino/issues/6191 and I confirm that version 1.0.0 can be successfully installed.

If you want to make a new version of the library available via Library Manager then you only need to create a tag or GitHub release that matches the `version` value in your library.properties and it will be automatically picked up by the indexer and added to Library Manager within an hour.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
