### ISSUE TITLE
Windows App "Get" badge is huge on the Chinese version of the Software page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6468]
From: https://www.arduino.cc/en/Main/Software?setlang=cn
![clipboard01](https://user-images.githubusercontent.com/8572152/27939965-c337a722-627c-11e7-8c71-ef2ec7adb4ee.png)

Firefox 54.0.1 (64-bit) and Version 59.0.3071.115 (Official Build) (64-bit) on Windows 7 64 bit.

Looking at the image info, the actual badge image dimensions are the same size on both pages but it's only scaled down on the English version.

**Comment by facchinm** [comment]
@00alis

**Comment by 00alis** [comment]
@smellai please have a look, thank you @per1234 for pointing this out

**Comment by smellai** [comment]
Fixed
