### ISSUE TITLE
Error burning bootloader 

### ISSUE THREAD

**Issue by wenhuizhang** [arduino/Arduino#6477]
```
avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: error: program enable: target doesn't answer. 1 
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

Error while burning bootloader.
```

I was trying to follow the instructions on  http://tutorial.cytron.com.my/2011/12/19/burning-arduino-bootloader-with-avr-usbasp/ .

**Comment by per1234** [comment]
This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post the **verbose** output, using code tags (`</> button on the toolbar).
3. Add a comment to this issue with the link to your thread to help anyone else who later has the same problem find the solution.
