### ISSUE TITLE
BLECharacteristic reference page documents non-existent  maxLen parameter

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6481]
https://www.arduino.cc/en/Reference/BLECharacteristicConstructor claims a `maxLen` parameter but a look at the source of the library ([BLETypedCharacteristics.h](https://github.com/01org/corelibs-arduino101/blob/master/libraries/CurieBLE/src/BLETypedCharacteristics.h)) shows it doesn't exist.

Originally reported at http://forum.arduino.cc/index.php?topic=489026

**Comment by kengdahl** [comment]
I have removed the `maxLen` parameter from https://www.arduino.cc/en/Reference/BLECharacteristicConstructor

You were right.
