### ISSUE TITLE
Incorrect wiring of breadboard power rails in https://www.arduino.cc/en/Tutorial/ArduinoISP

### ISSUE THREAD

**Issue by grayl** [arduino/Arduino#6483]
In the breadboard examples in https://www.arduino.cc/en/Tutorial/ArduinoISP, the power rails are not correctly labeled. They should be paired top/top, bottom/bottom, not top/bottom, bottom/top

**Comment by per1234** [comment]
Just to make the issue more clear, even though the polarity of the power rails on the tutorial page are not marked, in the real world every breadboard of this type I've seen had the polarity labeled in a way that contradicts the diagram in the tutorial. For example, https://www.adafruit.com/product/64:
![64-00](https://user-images.githubusercontent.com/8572152/28175251-8d2c7d52-67a8-11e7-8326-3c7bf6f07953.jpg)

**Comment by SimonePDA** [comment]
THe Arduino as ISP has been completely revamped and the issue is now obsolete.
