### ISSUE TITLE
Incorrect capitalization of String in reference pages

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6486]
The following pages incorrectly call Strings a string. The two are frequently confused with each other by beginners so it's important that the documentation always uses the correct capitalization:

- https://www.arduino.cc/en/Reference/StreamReadString
- https://www.arduino.cc/en/Reference/StreamReadStringUntil
- https://www.arduino.cc/en/Reference/StringBrackets
- https://www.arduino.cc/en/Reference/StringComparison
- https://www.arduino.cc/en/Reference/StringDF
- https://www.arduino.cc/en/Reference/StringEqualsIgnoreCase
- https://www.arduino.cc/en/Reference/StringGE
- https://www.arduino.cc/en/Reference/StringGT
- https://www.arduino.cc/en/Reference/StringGetBytes
- https://www.arduino.cc/en/Reference/StringLE
- https://www.arduino.cc/en/Reference/StringLT
- https://www.arduino.cc/en/Reference/StringRemove
- https://www.arduino.cc/en/Reference/StringReplace
- https://www.arduino.cc/en/Reference/StringReserve
- https://www.arduino.cc/en/Reference/StringToCharArray
- https://www.arduino.cc/en/Reference/StringToFloat
- https://www.arduino.cc/en/Reference/StringToInt
- https://www.arduino.cc/en/Reference/StringToLowerCase
- https://www.arduino.cc/en/Reference/StringToUpperCase
- https://www.arduino.cc/en/Reference/StringTrim
- https://www.arduino.cc/en/Serial/ReadString
- https://www.arduino.cc/en/Serial/ReadStringUntil
- https://www.arduino.cc/en/Tutorial/StringReplace

Possibly related: https://github.com/arduino/Arduino/issues/6137

**Comment by SimonePDA** [comment]
Capitalized all occurrences of "string" into "String" as discussed with CMaglie. Fixes #6486
