### ISSUE TITLE
Fixed ignoring of LIBRARY_INDEX_URL of system property

### ISSUE THREAD

**Issue by xardael** [arduino/Arduino#6495]
Please take at look at comment in this PR
https://github.com/arduino/Arduino/pull/6494

Could it be included in the next version?

Thanks!

**Comment by matthijskooijman** [comment]
No need to create an issue in addition to creating a PR, whenever a PR or issue is created or a comment is added, everyone watching this repo is already notified by e-mail (so no need to create more spam than needed).
