### ISSUE TITLE
Typos on Mouse.isPressed() reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6498]
https://www.arduino.cc/en/Reference/MouseIsPressed
Change:
>Returns
boolean : reports wether a button is pressed or not 

to:
>Returns
boolean : reports **whether** a button is pressed or not 

Change:
>  //if the switch attached to pin 2 is closed, press and hold the right mouse button and save the state ina  variable

to:
>  //if the switch attached to pin 2 is closed, press and hold the **left** mouse button and save the state **in a** variable

Change:
>//if the switch attached to pin 3 is closed, release the right mouse button and save the state in a variable

to:
>//if the switch attached to pin 3 is closed, release the **left** mouse button and save the state in a variable

**Comment by akash73** [comment]
fixed, thanks!
