### ISSUE TITLE
Typos on Mouse.press() reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6499]
https://www.arduino.cc/en/Reference/MousePress

Change:
>  //if the switch attached to pin 2 is closed, press and hold the right mouse button

to:
>  //if the switch attached to pin 2 is closed, press and hold the **left** mouse button

Change:
>  //if the switch attached to pin 3 is closed, release the right mouse button

to:
>  //if the switch attached to pin 3 is closed, release the **left** mouse button

**Comment by akash73** [comment]
fixed, thanks!
