### ISSUE TITLE
Typos on if (Serial) reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6502]
https://www.arduino.cc/en/Serial/IfSerial
Change:
>On 32u4 based boards (Leonardo, Yùn, ecc) , if (Serial) indicates wether or not the USB CDC serial connection is open.

to:
>On 32u4 based boards (Leonardo, Yùn, ecc) , if (Serial) indicates **whether** or not the USB CDC serial connection is open.

----
Change:
>For all other instances, including if (Serial1) on the Leonardo, this will always returns true. 

to:
>For all other instances, including if (Serial1) on the Leonardo, this will always return true. 

----
Change:
>boolean : returns true if the specified serial port is available.

to:
>**boolean: Returns** true if the specified serial port is available.

**Comment by akash73** [comment]
fixed thanks!
