### ISSUE TITLE
Typos on EEPROM.update() tutorial page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6504]
https://www.arduino.cc/en/Tutorial/EEPROMUpdate

Change:
>the EEPROM ha salso a limit

to:
>the EEPROM **has also** a limit

----
Change:
>limit of 100.000 write cycles per single location

to:
>limit of **100,000** write cycles per single location

OK, I know that one is debatable. The important thing is to be consistent throughout the documentation. A quick search found comma used for the digit grouping delimiter in the [int](https://www.arduino.cc/en/Reference/Int), [unsigned int](https://www.arduino.cc/en/Reference/UnsignedInt), [long](https://www.arduino.cc/en/Reference/Long), [unsigned long](https://www.arduino.cc/en/Reference/UnsignedLong), [short](https://www.arduino.cc/en/Reference/Short), and even the [EEPROM.update()](https://www.arduino.cc/en/Reference/EEPROMUpdate) reference pages and no other instances of periods. The period is also used throughout the reference pages as the decimal mark.

**Comment by akash73** [comment]
fixed thanks!
