### ISSUE TITLE
Incorrect return type in SoftwareSerial.listen() reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6507]
https://www.arduino.cc/en/Reference/SoftwareSerialListen says:
>Returns
None 

but actually it returns a bool:
https://github.com/arduino/Arduino/blob/1.8.3/hardware/arduino/avr/libraries/SoftwareSerial/src/SoftwareSerial.h#L95
```
bool listen();
```

**Comment by SimonePDA** [comment]
Updated and pushed the Reference page with 
"Returns
boolean: Returns true if it replaces another"
s
