### ISSUE TITLE
Typos in and suggestions for improvements of "Installing additional Arduino Cores" reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6508]
https://www.arduino.cc/en/Guide/Cores

Change:
>only AVR Arduino boards are installed by default.

to:

>only **Arduino AVR Boards** are installed by default.

----
Change:
>you need to install the SAM Core using the Boards Manager 

to:
>you need to install the **Arduino SAM Boards Core** using the Boards Manager 

----
Change:
>Click on Tools menu and then Boards > Boards Manager. 

to:
>Click on Tools menu and then Board > Boards Manager. 

----
At this point in the text I recommend adding something like:
>Wait for the download to finish.

The reason is that the index file is quite large now so it does take some time to download. This is increased if you have added additional Boards Manager URLs to your preferences. You can't click on the entries until it has finished downloading. The list also scrolls back to the top after the download finishes.

----
Change:
>The board manager will open and you will see a list of installed and available boards. 

to:
>**Boards Manager** will open and you will see a list of installed and available boards. 

----
Change:
>Select the SAM core

to:
>**Click on Arduino SAM Boards**

The reason for changing "select" to "click on" is to emphasize that you actually need to click on the Boards Manager entry before the version menu and the Install button appear. This astonishing UI behavior has caused confusion for users in the past.

----
Change:
>, choose the version in the drop-down menu and click on install. 

to:
>, choose the version in the drop-down menu and click on **Install**. 

----
Change:
>Now you can find the new board in the Board menu. 

to:
>Now you can find the new board in the **Tools >** Board menu. 

----
Capitalization of the word "core":
The word is capitalized in some places, not capitalized in other places. Pick one and be consistent. I prefer non-capitalized.

**Comment by SimonePDA** [comment]
Cleaned up and fixed
