### ISSUE TITLE
Typos in "Payment Methods" Arduino Store page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6515]
https://store.arduino.cc/usa/payment-methods

Change:
>Arduino Store is accepting payments via Credit / Debit Cards and PayPal

to:
>Arduino Store **accepts** payments via Credit / Debit Cards and PayPal

----
Change:
>Due to potential fraud and misuse, we may not to ship an order, or request additional verification information.

to:
>**In case of** potential fraud or misuse, we may **chose to not** ship an order, or request additional verification information.

**Comment by kengdahl** [comment]
Thank you @per1234 ! It is now fixed with your suggested fixes.

**Comment by per1234** [comment]
@kengdahl, the page is unchanged. Maybe your fixes weren't pushed to the public server?

**Comment by kengdahl** [comment]
Is it still iunchanged? @per1234

**Comment by per1234** [comment]
When I load https://store.arduino.cc/usa/payment-methods it's still unchanged. I'm using ctrl+F5 to do a "Reload (override cache)".

When I change my location to Europe/Africa and load https://store.arduino.cc/payment-methods I do see the changes. On that page I notice an issue:

>Arduino Store is accepts payments via Credit / Debit Cards and PayPal

should be:
>Arduino Store accepts payments via Credit / Debit Cards and PayPal

**Comment by kengdahl** [comment]
EU and US page are now fixed.

**Comment by per1234** [comment]
@kengdahl I accidentally introduced a typo with my suggestion:
Change:
>In case of potential fraud or misuse, we may chose to not ship an order, or request additional verification information.

to:
>In case of potential fraud or misuse, we may **choose** to not ship an order, or request additional verification information.

Sorry about that!

**Comment by kengdahl** [comment]
**Fixed**
