### ISSUE TITLE
Incorrect link in "Privacy Policy" Arduino Store page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6517]
https://store.arduino.cc/usa/privacy-policy-cookie-restriction-mode

The link "[please fill out this form](https://store.arduino.cc/usa/privacy-policy-cookie-restriction-mode)" in the  "Questions" section points to:
https://store.arduino.cc/usa/privacy-policy-cookie-restriction-mode
which is wrong. It should point to:
https://store.arduino.cc/store-support

**Comment by kengdahl** [comment]
Fixed
