### ISSUE TITLE
Typos on "Transparency" Arduino Store page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6518]
https://store.arduino.cc/usa/transparency
Change:
>you can check every details

to:
>you can check every **detail**

----
Change:
>Once you selected all the items you'd like to purchase

to:
>Once you **have** selected all the items you'd like to purchase

----
Change:
>the 'Checkout' button you can find on Cart popover

to:
>the 'Checkout' button you can find on the Cart popover

----
>reachable from the Cart icon in the header

The icon is actually a shopping bag, not a cart. This was the source of some confusion after it was first added (https://forum.arduino.cc/index.php?topic=473506.msg3238998#msg3238998):
>Anybody knows what the second icon in the blue bar at the top is for?
There is a magnifying glass (for search), a user icon (for profile, messages and sign out) and in between them is an icon that looks like a lock; what is the latter for?

----
Change:
>Please contact us at our Customer Care.

to:
>Please contact us at our [Store Support form](https://store.arduino.cc/store-support).

----
Change:
>Arduino Store is accepting payments via Credit / Debit Cards (American Express, Visa, Mastercard, Discover Network) and PayPal

to:
>Arduino Store **accepts** payments via Credit / Debit Cards (American Express, Visa, Mastercard, Discover Network) and PayPal

----
The "PAYMENTS" section seems to result in duplicate content with https://store.arduino.cc/usa/payment-methods. You might consider migrating unique content to that page and then just having a link to it from the Transparency page.

----
The "SHIPMENTS" section seems to result in duplicate content with https://store.arduino.cc/usa/shipping-policy. You might consider migrating unique content to that page and then just having a link to it from the Transparency  page.

----
Change:
>For any further information, please refer to our Condition of Use page.

to:
>For any further information, please refer to our **Conditions** of Use page.

**Comment by kengdahl** [comment]
**Only these two left: **
----
The "PAYMENTS" section seems to result in duplicate content with https://store.arduino.cc/usa/payment-methods. You might consider migrating unique content to that page and then just having a link to it from the Transparency page.

----
The "SHIPMENTS" section seems to result in duplicate content with https://store.arduino.cc/usa/shipping-policy. You might consider migrating unique content to that page and then just having a link to it from the Transparency  page.

----

**Comment by per1234** [comment]
@kengdahl I spotted a newly added typo.
Change:
>Please contact us thruu our Store support form.

to:
>Please contact us **through** our Store support form.

**Comment by kengdahl** [comment]
**Fixed**

Was only left on the US page. Must have forgot to fix it.
