### ISSUE TITLE
Typos on AtHeart page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6520]
https://www.arduino.cc/en/ArduinoAtHeart/Products

----
The "Shop AtHeart products on our Store." link points to:
~~https://store.arduino.cc/category/84~~
https://store.arduino.cc/atheart
but that just dumps me to the Arduino Store homepage.

The correct link (for USA region) is:
https://store.arduino.cc/usa/atheart

EDIT 2017-09-13: The link has been updated but the issue remains.

----
~~Change:~~
~~>Below the official AtHeart products.~~

~~to:~~
~~>Below are the official AtHeart products. ~~

----
~~Change:~~
~~>In the heart of MicroView there is an ATMEL’s ATmega328P~~

~~to:~~
~~>In the heart of MicroView there is an Atmel ATmega328P~~

----
~~www.microview.io gives a "Server not found" error~~

----
~~Change:~~
~~>- ATMega328 clocked at 8 or 16 MHz~~
~~>- ATMega1280 clocked at 16 MHz~~
~~>- ATMega2560 clocked at 16 MHz~~
~~>- ATMega32U4 at 8 or 16 MHz	~~
~~>- ATMega64M1 at 16 Mhz ~~

~~to:~~
~~>- ATmega328P clocked at 8 or 16 MHz~~
~~>- ATmega1280 clocked at 16 MHz~~
~~>- ATmega2560 clocked at 16 MHz~~
~~>- ATmega32U4 at 8 or 16 MHz	~~
~~>- ATmega64M1 at 16 Mhz ~~

~~Also: what about ATmega168 and ATtiny85 (or ATmega8 if you want to get really complete)?~~

----
For more information about the AtHeart program please contact at_heart [at] arduino.cc

The non-obfuscated email address is shown at the top of the page so I don't think this has any value for spam prevention.

----
EDIT 2017-09-13: The issue has been partially resolved and I have struck out those items. The non-struck out items remain unresolved.

**Comment by kengdahl** [comment]
Thank you @per1234 

Fixed.

**Comment by per1234** [comment]
@kengdahl, the link [Shop AtHeart products on our Store.](https://store.arduino.cc/atheart), although updated, still dumps me in the store home page. https://store.arduino.cc/usa/atheart does take me to the right store section. I would expect the store to be able to take the non-regional URL and convert it to the correct regional URL, as it does for product pages (e.g. https://store.arduino.cc/arduino-uno-rev3 redirects to https://store.arduino.cc/usa/arduino-uno-rev3) but apparently this doesn't work for store sections. Maybe that's a separate issue that should be reported and the link on the AtHeart page can be left as-is in the hopes that it will eventually work?

**Comment by kengdahl** [comment]
I'm reopening the issue. I'll look further into this with our main admin.

**Comment by kengdahl** [comment]
The link to the atheart products should work now. Better late than never, right :)
