### ISSUE TITLE
Typos in "About Us" page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6522]
https://www.arduino.cc/en/Main/AboutUs

----
Change:
>Hundreds of thousands designers

to:
>Hundreds of thousands **of** designers

----
Change:
>to create working prototype connecting

to:
>to create working **prototypes** connecting

----
Change:
>Since then it went to become

to:
>Since then it **has** become

----
Change:
>and was setup to build

to:
>and was set up to build

----
Change:
>that could help out spread the use of the tool

to:
>that could help spread the use of the tool

----
Change:
>supports other users on the forums 

to:
>**support** other users on the forums 

----
Change:
>Since Arduino project’s foundation 

to:
>Since **the** Arduino project’s foundation

**Comment by kengdahl** [comment]
Fixed.
