### ISSUE TITLE
Typos on "Upgrading the OpenWrt-Yun image on the Yún" page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6524]
https://www.arduino.cc/en/Tutorial/YunSysupgrade

----
Change:
>sysupgrade image is available for download [here](http://http//downloads.arduino.cc/openwrtyun/1.6.2/YunSysupgradeImage_v1.6.2.zip). 

to:
>sysupgrade image is available for download [**here**](http://downloads.arduino.cc/openwrtyun/1.6.2/YunSysupgradeImage_v1.6.2.zip). 

(fix link, the previous one is invalid)

----
Change:
>or put it in the root folder of a USB memory

to:
>or put it in the root folder of a USB **flash drive**

**Comment by kengdahl** [comment]
Fixed
