### ISSUE TITLE
Incorrect link for corrections/suggestions on all documentation pages

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6526]
At the bottom of all documentation pages (EDIT: seems to no longer be on all pages, but it remains on the library reference pages: [example](https://www.arduino.cc/en/Reference/MKRMotorCarrier)) is this line:
>Corrections, suggestions, and new documentation should be posted to the [Forum](http://arduino.cc/forum/index.php/board,23.0.html).

The link points to the "Other Software Development" section of the forum. The "[Suggestions for the Arduino Project](http://forum.arduino.cc/index.php?board=21.0)" section seems much more appropriate.

Example of this causing confusion and wasted time:
http://forum.arduino.cc/index.php?topic=494624

**Comment by kengdahl** [comment]
Are you refering to the documentation tabs in the store?

**Comment by per1234** [comment]
... and now after the forum update that link just takes you to an "Oops! That page doesn’t exist or is private." page.

**Comment by per1234** [comment]
It was fixed at some point but nobody bothered to close this.
