### ISSUE TITLE
Typos on "Analog Input Pins" page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6527]
https://www.arduino.cc/en/Tutorial/AnalogInputPins

----
Change:
>an Arduino chip (Atmega8, Atmega168, Atmega328, or Atmega1280). 

to:
>an Arduino chip (**ATmega8, ATmega168, ATmega328P, or ATmega1280, ATmega2560, ATmega32U4**). 

----
Change:
>The Atmega controllers used for the Arduino

to:
>The **ATmega** controllers used for the Arduino

----
Change:
>contain an onboard 6 channel analog-to-digital (A/D) converter.

to:
>contain an onboard 6 channel **(8 channels on the Mini and Nano, 16 on the Mega)** analog-to-digital (A/D) converter.

(as written at https://www.arduino.cc/en/Reference/AnalogRead)

----
Change all instances of "pullup" to "pull-up". Reference: Atmel datasheets.

----
Change:
>The Atmega datasheet also cautions

to:
>The ATmega datasheet also cautions

**Comment by SimonePDA** [comment]
Done
