### ISSUE TITLE
IDE 1.8.3 Gives compilation warnings for EEPROM.h

### ISSUE THREAD

**Issue by brownrb** [arduino/Arduino#6534]
There are warnings in the EEPROM.h file provided with Arduino release. Should not the code be cleaned up so as not to produce warnings?

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\EEPROM\src/EEPROM.h:43:30: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]

     operator const uint8_t() const       { return **this; }

                              ^

C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\EEPROM\src/EEPROM.h:92:26: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]

     operator const int() const          { return index; }

                          ^

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/3783

We welcome bug reports and feature requests but in the future please take the time to search for existing open and closed issues and pull requests before submitting an issue:
https://github.com/arduino/Arduino/issues?&q=
