### ISSUE TITLE
LCD library example code update

### ISSUE THREAD

**Issue by Isaac100** [arduino/Arduino#6538]
A while back I made a pull request on the Arduino Libraries Liquid Crystal repo. about updating the code for an example sketch(And it got merged).  I'm just wondering, when would those changes be made into a new release and then merged into this repo? (because the LCD library is included with the IDE)

**Comment by facchinm** [comment]
Hi @Isaac100 ,
we usually accumulate some patches before releasing a library update; however, I'm going to merge a couple of PRs and release the library later today :wink:
