### ISSUE TITLE
[Library Manger] Please add SparkFUn Si7021 Arduino Library 

### ISSUE THREAD

**Issue by JoelEB** [arduino/Arduino#6541]
https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library

Thanks!

**Comment by per1234** [comment]
@JoelEB the link gives a 404 error. Is the repository private?

**Comment by JoelEB** [comment]
Sorry, forgot to set to Public before opening the issue. Should be good to go now. Thanks!

**Comment by cmaglie** [comment]
Done!
