### ISSUE TITLE
Liquid Crystal Display Code

### ISSUE THREAD

**Issue by maddilemi** [arduino/Arduino#6550]
Code

You need to connect the board to your computer and use the Arduino Software (IDE) serial monitor to communicate with it.

SORRY, There is an error at our code repository, please inform to web@arduino.cc

https://www.arduino.cc/en/Tutorial/LiquidCrystalSerialDisplay

**Comment by facchinm** [comment]
Thanks for posting. I'm fixing the broken links right now.

**Comment by facchinm** [comment]
Should be ok now, please reopen the issue if there are still broken links somewhere
