### ISSUE TITLE
Nightly Serial is broken

### ISSUE THREAD

**Issue by openSoftMan** [arduino/Arduino#6552]
Using: arduino-nightly-windows_19 July 2017 5_34_36
Windows 7 x86

Serial throws a null pointer exception when opening the serial monitor.
I believe this [commit](https://github.com/arduino/Arduino/commit/125846f55d624951897d5a432e528e9cc7a5e06f) caused this.

Using the arduino-core.jar from the official release (arduino-1.8.3-windows) resolves this.

**Comment by cmaglie** [comment]
Your analysis is correct... I'm pushing a fix in a moment.

**Comment by cmaglie** [comment]
...and thanks for the detailed report! :-)
