### ISSUE TITLE
Need (or not) of pulling https://github.com/01org/corelibs-arduino101 into one own repository here after Arduino 101 sunset

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#6557]
I ask because I don't know if Arduino (.cc/.org) will do efforts to keep this board alive or not
(See: http://hackaday.com/2017/07/25/the-end-of-arduino-101-intel-leaves-maker-market/)
Thanks

**Comment by per1234** [comment]
As you foresaw, the "Intel Curie Boards" platform repository was indeed moved to the Arduino organization:
https://github.com/arduino/ArduinoCore-arc32
