### ISSUE TITLE
Error in "return" reference page example code

### ISSUE THREAD

**Issue by RicardoGlobal** [arduino/Arduino#6562]
In the webpage https://www.arduino.cc/en/Reference/Return, in the code example there is an error:
it says:
```arduino
int checkSensor(){       
    if (analogRead(0) > 400) {
        return 1;
    else{
        return 0;
    }
}
```
there is a `}` missing just before the `else`.
It is obvious for programmers but could turn out to be a nightmare for novices.

**Comment by per1234** [comment]
Closed by https://github.com/arduino/reference-en/pull/200
