### ISSUE TITLE
New library - IRsend

### ISSUE THREAD

**Issue by cristborges** [arduino/Arduino#6576]
Hello,

Please add a new library:

https://github.com/cristborges/IRsend

Many thanks

**Comment by NicoHood** [comment]
Hi,
This look interesting. Any chance to integrate this into:
https://github.com/NicoHood/IRLremote

I have a very fancy receiving code, but no sending code yet. Maybe we can combine our work?

**Comment by q2dg** [comment]
Ei, what's about the proposition??

**Comment by cristborges** [comment]
Yes @q2dg .. I changed the library to also cover the receipt of IR codes.
