### ISSUE TITLE
New library

### ISSUE THREAD

**Issue by evert-arias** [arduino/Arduino#6581]
Please, publish this new version of the library.

https://github.com/evert-arias/LedSync

Thank you

**Comment by per1234** [comment]
From https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list:
>How can I publish a new release once my library is in the list?

>Ensure you've changed version in your library.properties. Then tag your library once more and push the new tag (or create a release if your web hosting offers a way to do it, for example with GitHub "releases"). Our indexer checks for new releases every hour and will eventually fetch and publish your new release.

So there's no need to open a new issue every time you release a new version, it will automatically be added to Library Manager.
