### ISSUE TITLE
WiFi 101 Firmware Updater

### ISSUE THREAD

**Issue by 0x454447415244** [arduino/Arduino#6584]
The integrated Firmware Updater in Arduino IDE for the WiFi101 fails to add Root CA when the CN is an IP address and the CA is self-signed. I tried the standalone firmware updater and it worked.

**Comment by facchinm** [comment]
Hi @0x454447415244 (wow :smile: ) would you mind moving the issue here https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin ? Thanks!

**Comment by 0x454447415244** [comment]
Okay, I will post the issue there. Thanks!

**Comment by per1234** [comment]
Closing as moved to https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin/issues/10
