### ISSUE TITLE
New libraries have not been added to Arduino Web Editor's Library Manager since June 29

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6593]
It looks like no new Library Manager libraries have been added to the Arduino Web Editor since [EasyNTPClient](https://github.com/arduino/Arduino/issues/6441). Everything from [OctoSonar ](https://github.com/arduino/Arduino/issues/6445)and newer does not show up in the Arduino Web Editor Library Manager search.

The standard IDE's Library Manager index has been updated as expected.

Originally reported at https://github.com/arduino/Arduino/issues/6542#issuecomment-319737680

**Comment by cmaglie** [comment]
Hi @RobPo @per1234 

all the new libraries have been added, sorry for the delay...

The libraries import process until now has been a part of another bigger deploy process, that's the reason for the long delay this time.

Now we are fixing it for good so it can run independently and more often.
