### ISSUE TITLE
[Library Manager]: Please add PTW-Arduino-Assert

### ISSUE THREAD

**Issue by aj-ptw** [arduino/Arduino#6594]
Please add:
https://github.com/PushTheWorld/PTW-Arduino-Assert

Thanks!

PushTheWorld/PTW-Arduino-Assert

**Comment by per1234** [comment]
The `version` value in your library.properties file must match the release version. Currently the release version is 1.1.0 but the `version` value in library.properties is 1.0.1.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by aj-ptw** [comment]
Okay I fixed and bumped version!

**Comment by cmaglie** [comment]
Done!
