### ISSUE TITLE
[Library Manager] please add THiNXLib

### ISSUE THREAD

**Issue by suculent** [arduino/Arduino#6597]
Repository: https://github.com/suculent/thinx-lib-esp8266-arduinoc
Current version/tag: 2.0.0

**Comment by cmaglie** [comment]
Done!

**Comment by suculent** [comment]
Awesome, thanks a lot. 

Odesláno z iPhonu

14. 8. 2017 v 11:21, Cristian Maglie <notifications@github.com>:
