### ISSUE TITLE
i keep getting this error message .. im new here 

### ISSUE THREAD

**Issue by ahmed-rd** [arduino/Arduino#6599]
ketch uses 4682 bytes (16%) of program storage space. Maximum is 28672 bytes.
Global variables use 154 bytes (6%) of dynamic memory, leaving 2406 bytes for local variables. Maximum is 2560 bytes.

**Comment by per1234** [comment]
That's not an error message. It's just some helpful information to tell you the memory usage of your sketch. That indicates the compilation was successful.

This issue tracker is for reporting bugs or feature requests only. You can get help with any questions or problems you may have by posting on the Arduino forum:
http://forum.arduino.cc/
