### ISSUE TITLE
Please add Charge-n-Boost library to library manager

### ISSUE THREAD

**Issue by bernebeer** [arduino/Arduino#6602]
Hi,

Please add my library: Charge-n-Boost.

https://github.com/bernebeer/Charge-n-Boost

Thanks!

Gijs

**Comment by bernebeer** [comment]
Was not Semversioning compliant. Changed it to 1.1.0

Link to release: https://github.com/bernebeer/Charge-n-Boost/releases/tag/1.1.0

**Comment by cmaglie** [comment]
@bernebeer 
the library name `Charge 'n Boost` cannot be used due to the `'` on the name, may you remove the quote?
(remember to change the name in the `library.properties` and to commit and push **before** redoing the tag)

**Comment by bernebeer** [comment]
Hi cmaglie,

Thank you for getting back to me. I have updated the library to reflect the new name.: 

https://github.com/bernebeer/Charge-n-Boost/releases/tag/1.1.0

Regards,

Gijs

**Comment by cmaglie** [comment]
Library added, thanks!
