### ISSUE TITLE
[Library Manager] Request to add E131

### ISSUE THREAD

**Issue by forkineye** [arduino/Arduino#6604]
https://github.com/forkineye/E131
https://github.com/forkineye/ESPAsyncE131/releases/tag/v1.0.0

**Comment by cmaglie** [comment]
@forkineye is this the same as #6605?
May I close this as duplicate?

**Comment by forkineye** [comment]
It isn't, this is the original library I wrote which uses polling and supports traditional UNO Ethernet Shields, plus the ESP8266.  #6605 is asynchronous and supports the ESP8266 only. Thanks!

**Comment by cmaglie** [comment]
Ok, library added.
Thanks
