### ISSUE TITLE
Library documentation

### ISSUE THREAD

**Issue by z3t0** [arduino/Arduino#6607]
I would like to add information to the site [here](https://www.arduino.cc/en/Tutorial/LibraryExamples).

**Comment by per1234** [comment]
The best way to suggest changes to that page is to submit an issue report to this repository. It's helpful if you can specify the exact wording of the change you would like rather than just a vague description of the suggested improvement.

**Comment by z3t0** [comment]
I am currently the maintainer of the Arduino-Irremote library. Currently I am spending time updating documentation and writing tutorials for the library. I think it would be a great idea to add the tutorials to the site I mentioned above.

**Comment by per1234** [comment]
Sorry, that page is for official Arduino libraries only so that will not be possible. I would recommend you to instead use the GitHub wiki feature in your repository for this purpose.

**Comment by z3t0** [comment]
Ah sorry. I misunderstood. Thanks!

Thanks,
Rafi Khan
________________________________
