### ISSUE TITLE
Arduino 101 / Arduino 101 stuck after uploading code

### ISSUE THREAD

**Issue by tamirmha** [arduino/Arduino#6614]
Hello,

i have an arduino 101 and after i added to my project an EEPROM Get/Put its worked for 1 minute and after this the device stucked and didn't response anymore and the computer doesnt recognize it any more ( i disconnected from the usb, tried the master reset, tried to downgrade for older version the ide and the drivers).
i tried before to write the only to the eeprom and its worked fine
i have win7 64bit and the latest version of the ide and the intel curie drivers)
I attached the code.
Hope if anyone could help... #bug #arduino101

**Comment by facchinm** [comment]
Hi @tamirmha ,
you forgot to attach the sketch :slightly_smiling_face: 
I can help debugging your issue but it would be better to move the discussion to the proper repo (https://github.com/01org/corelibs-arduino101). Would you mind closing this issue and reopening there? Thanks!

**Comment by tamirmha** [comment]
Thanks, i posted a new one.

**Comment by per1234** [comment]
Just to link things together, here's the relevant issue in the other repository: https://github.com/01org/corelibs-arduino101/issues/565
