### ISSUE TITLE
[Library Manager] arduino library for TS4231 Light to Digital Converter

### ISSUE THREAD

**Issue by jseibel6900** [arduino/Arduino#6616]
Please add the TS4231 library to the library manager list.  I think I have met all of the 1.5 format requirements, but this is my first library so please let me know if I missed something.  Thanks.

https://github.com/TriadSemi/TS4231

**Comment by jseibel6900** [comment]
Hi per1234 - 
Do I need to do anything else to have the library added to the library manager list?  The library manager FAQ says the list is updated about every hour, but I don't know if the library has officially been accepted so that it can be added to the list.  I'm sure I'm missing something.  Please let me know how to proceed.
Thanks!

**Comment by per1234** [comment]
It looks like your library meets all the requirements for addition to Library Manager. The way it works is that cmaglie comes through every few days and adds all the libraries that have been submitted as long as they don't have any issues that prevent this. Once that is done, the libraries should be added to Library Manager via the hourly job. There [may be a longer delay](https://github.com/arduino/Arduino/issues/6593#issuecomment-321559057) before they are added to the Arduino Web Editor's Library Manager, I'm not sure whether that is still the case.

So there's nothing more you have to do, just wait for the notification that cmaglie has closed this issue and then check Library Manager in the standard IDE a couple hours later to be sure that your library was successfully added.

**Comment by jseibel6900** [comment]
Got it.  Thanks for the quick response!

**Comment by cmaglie** [comment]
Done!
