### ISSUE TITLE
[Library Manager] Please add BrushlessServo library

### ISSUE THREAD

**Issue by erdnaxe** [arduino/Arduino#6629]
Please add **BrushlessServo to the library manager**:
https://github.com/erdnaxe/Arduino_BrushlessServo

This library provides a way to use a Brushless motor directly from the Arduino (without an ESC) for precision projects (gimbals...). It differs from other libraries from the fact it's made for fast and accurate move. 

There is some code sample and a video here: https://erdnaxe.github.io/brushlessservo-library/

This is for my next year school project. If there is any issue, please help and I will do my best !

Regards,

Alexandre

**Comment by cmaglie** [comment]
Done!
