### ISSUE TITLE
[Library Manager] Please add fDigitsSegtPin library

### ISSUE THREAD

**Issue by KuangLei** [arduino/Arduino#6630]
Please add [fDigitsSegtPin](https://github.com/KuangLei/fDigitsSegtPin) library.  
https://github.com/KuangLei/fDigitsSegtPin  

* About [4Digit7Seg12Pin](https://github.com/KuangLei/4Digit7Seg12Pin) library, I'm sorry for making the mistake. Now I've [removed](https://github.com/KuangLei/4Digit7Seg12Pin/releases) all its GitHub Releases. If the whole [library](https://github.com/arduino/Arduino/issues/6627) can't be deleted automatically, please manually remove it.  

* I've [added](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification/_compare/b2d5eb1fb01708f04360caa773416f5539ed244f) the following line to [Arduino IDE 1.5: Library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification). If there are any pages cloned from this please update them too.  
> Library names must contain only basic letters and numbers. (ASCII only and no spaces, and it cannot start with a number)  

Thanks.

**Comment by cmaglie** [comment]
thanks, it should be fixed now!
