### ISSUE TITLE
MKR1000 port not showing on IDE, MacOS X

### ISSUE THREAD

**Issue by dackdel** [arduino/Arduino#6631]
I did the double reset that I read from the previous thread. But still have the same issue. The double reset made it work once but thats it.

**Comment by facchinm** [comment]
Hi @dackdel ,
where did you find the "double reset" info? just the link the important parts of the conversation.
In fact, the double click allows the board to be in bootloader mode forever, with no timeout. You should then upload a sketch (a blink, for example) to reacquire the complete functionality. 
Let me know if it work for you.

**Comment by dackdel** [comment]
https://github.com/arduino/Arduino/issues/5223 i found it here

**Comment by facchinm** [comment]
Thanks for the link! Are you able to upload a sketch after the double tap?

**Comment by dackdel** [comment]
no

**Comment by facchinm** [comment]
Can you paste here the "verbose" output of the upload? you can enable it under File/Preferences -> verbose output for compilation and upload

**Comment by dackdel** [comment]
ok it started working again i aggressively kept pressing reset. left the lab now. will post the verbose tomo?

**Comment by cmaglie** [comment]
If the board is working there is no more reason to post the verbose output.
I'm closing this as solved, please reopen if you have other questions.
