### ISSUE TITLE
Arduino Environment

### ISSUE THREAD

**Issue by CAKA86** [arduino/Arduino#6632]
All my codes can`t show on the screen in Monitoring mode.
I can not to see AT+ commands for ESP8266, for Sim modules for everything.
90% I saw only $%#$#@@$ another 10% just white screen.

I restart computer, reinstal Arduino software, try onlyne software, Reconnect my Arduino board to PC change COM port, change baud rate, but nothing.

I thing this is Arduino software bug.

**Comment by facchinm** [comment]
Hi @CAKA86 ,
this issue should probably be handled better by esp8266 community (https://github.com/esp8266/Arduino) Please reopen the issue there, thanks!
