### ISSUE TITLE
Can't install the grbl library

### ISSUE THREAD

**Issue by RamziBel** [arduino/Arduino#6645]
Arduino version 1.8.3 and 1.8.4 won't accept the grbl library, he write the following message : The specified folder does not contain a valid library

**Comment by per1234** [comment]
This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
