### ISSUE TITLE
please add to the Library Manager

### ISSUE THREAD

**Issue by h-c-c** [arduino/Arduino#6648]
Hi, I'd like to have my library added to the Arduino Library Manager and I'm opening this issue as advised by the Library Manager FAQ. 

URL is:
https://github.com/h-c-c/Seven_Segment_Pixel

Archive is here: 
https://github.com/h-c-c/Seven_Segment_Pixel/archive/v1.0.0.zip

General info:
http://blog.hartmanncomputer.com/7-segment-pixel-library-for-arduino/

Thank you!

**Comment by cmaglie** [comment]
Done!
