### ISSUE TITLE
Issue with the timer

### ISSUE THREAD

**Issue by arindamsetu** [arduino/Arduino#6651]
I am writing a code for counting 100Khz digital signal. I need to count the pulses for 1 micro second and then store the data to a array. Then after 1 mili second send the vector of data through the serial port. I am using **Timer/Counter 4** for 1 micro second software interrpt and **Timer/counter 3** for 1 mili second interrupt the initiation code is below-
///////////////////////////////////////////////////////////////////////////////////////////////
void timer4Initiate()
{
  TCCR4A = 0;
  TCCR4B = 0;
  TCNT4  = 0;
  OCR4A = 16;            //
  TCCR4B |= (1 << WGM42)|(1 << CS40);   // CTC mode
  TIMSK4 |= (1 << OCIE4A);  // enable timer compare interrupt 
}

void timer3Initiate()
{
  TCCR3A = 0;
  TCCR3B = 0;
  TCNT3  = 0;
  OCR3A = 250;            // 
  TCCR3B |= (1 << CS31)|(1 << CS30)|(1 << WGM32);//64 bit pre
  TIMSK3 |= (1 << OCIE3A);  // enable timer compare interrupt 
}
///////////////////////////////////////////////////////////////////////////////////////////////////
In the while loop I am using the below code to check the input-
//////////////////////////////////////////////////////////////////////////////////////////////////
  if(digitalRead(inputPin)==1)
{
  //while(digitalRead(inputPin)==1)
  //{}
  count++;
}
//////////////////////////////////////////////////////////////////////////////////////////////////////
but the problem is according to the code I should get 1000 count in counter 4 between, 1 counter 3 interrupt (Counter4 interrupt=1us and Counter 3 Interrupt=1 mili second) 
But when I am setting the OCR4A=16 (for 1 us interrupt) its giving me 325 interrupt in 1 mili second( 1interrupt in timer 3).

When setting OCR4A= 128 (for 8 us interrupt) it is giving me exact 125 interrupt in 1 mili (as it should by calculation).

What is the problem? could anybody help me regarding this.
The whole code is-

int inputPin=12;
int count=0;
int interuptCount=0;
int pulses[1000];

void setup()
{
  Serial.begin(9600);
  pinMode(inputPin,INPUT);
  noInterrupts();           // disable all interrupts
  timer4Initiate();
  timer3Initiate();
  interrupts();
}

void loop() {
  if(digitalRead(inputPin)==1)
{
  //while(digitalRead(inputPin)==1)
  //{}
  count++;
}
}

ISR(TIMER4_COMPA_vect)          // timer compare interrupt service routine
{
  pulses[interuptCount]=count;
  count=0;
  interuptCount++;
  //Serial.print(count);
  //Serial.print(" ");
  
}

ISR(TIMER3_COMPA_vect)
{
  
  closeTimer4();
  closeTimer3();
  noInterrupts();
  //Serial.print("Hey\n");// toggle LED pin
  Serial.println(interuptCount);
  for(int i=0; i<=interuptCount; i++)
  {
    Serial.print(pulses[i]);
    Serial.print(" ");
  } 
Serial.println("\nThe values of G are= ");
  int g[100];
  for(int j=0; j<63; j++)
  {
    g[j]=((pulses[j]*pulses[j+62])/(pulses[j]*pulses[j]));
    Serial.print(-g[j]);
    Serial.print(" ");
  }
  //Serial.println(0/0);
}

void timer4Initiate()
{
  TCCR4A = 0;
  TCCR4B = 0;
  TCNT4  = 0;
  OCR4A = 128;            // compare match register 16MHz/1/.001
  TCCR4B |= (1 << WGM42)|(1 << CS40);   // CTC mode
  TIMSK4 |= (1 << OCIE4A);  // enable timer compare interrupt 
}

void timer3Initiate()
{
  TCCR3A = 0;
  TCCR3B = 0;
  TCNT3  = 0;
  OCR3A = 250;            // compare match register 16MHz/256/2Hz
  TCCR3B |= (1 << CS31)|(1 << CS30)|(1 << WGM32);//64 bit pre
  TIMSK3 |= (1 << OCIE3A);  // enable timer compare interrupt 
}

void closeTimer4(){
  TCCR4B &=0b11110000;    // 8 prescaler 
  TIMSK4 |= (0 << OCIE4A); 
}

void closeTimer3(){
  TCCR3B |= (0 << WGM32);   // CTC mode
  TCCR3B &=0B11110000;    // 8 prescaler 
  TIMSK3 |= (0 << OCIE3A); 
}

**Comment by matthijskooijman** [comment]
This is really not the right place for this question, unless you believe this is something that should be fixed with changes in the Arduino IDE? See https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md for info on what belongs here and where to take other questions.
