### ISSUE TITLE
[Library Manager] Library for GSL1680 based touch screen

### ISSUE THREAD

**Issue by Skallwar** [arduino/Arduino#6654]
Hi, 
I want to add my library to the Library Manager :)
Here is the link : https://github.com/ESTBLC/GSL1680
Thanks. 

P.S: I don't have put my email address on the library.properties file. I hope it's not a problem.

**Comment by cmaglie** [comment]
Done!

**Comment by ESTBLC** [comment]
Hi,
I have removed some old unusable released and now my new releases don't seem to be fetched by the lib manager

What should I do ?

**Comment by Skallwar** [comment]
Hi,
The link as changed: https://github.com/Skallwar/GSL1680

**Comment by cmaglie** [comment]
done

**Comment by Skallwar** [comment]
Thanks
