### ISSUE TITLE
[Library Manager] Please add CarreraDigitalControlUnit library

### ISSUE THREAD

**Issue by tkem** [arduino/Arduino#6655]
This is a cross-platform library for Arduino and mbed OS for interfacing a microcontroller board with the Carrera® DIGITAL 124/132 slot car racing system.

https://github.com/tkem/CarreraDigitalControlUnit
https://github.com/tkem/CarreraDigitalControlUnit/releases/tag/0.1.0

**Comment by cmaglie** [comment]
Done!

**Comment by tkem** [comment]
Thanks!
