### ISSUE TITLE
Tab names are not allowed to start with a number

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6656]
https://github.com/arduino/Arduino/commit/4545283ae773b6351d089e37b6d4080905ea8fd5 made it so that sketch names starting with a number are now allowed but New Tab still doesn't allow a number to be entered as the first character of the tab name.

Originally reported at: http://forum.arduino.cc/index.php?topic=496959

**Comment by cmaglie** [comment]
Thanks, now is fixed.

BTW I'm not fully satisfied with the solution since JTextBox implements his own validation logic, this must be refactored to use the `BaseNoGui.sanitizedName()` method to validate the input.
