### ISSUE TITLE
Can not cancel make new tab after upload [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#666]
This is [Issue 666](http://code.google.com/p/arduino/issues/detail?id=666) moved from a Google Code project.
Added by 2011-10-03T15:52:30.000Z by [laus...@gmail.com](http://code.google.com/u/112642187820935890496/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open some kind of code
2. Press "New Tab"
3. Do not name the tab, instead upload the code
4. Now you can not cancel making the tab
5. You have to enter a name for the tab, which creates it, and then you can delete it

As one can see at attached picture, it look like it on top of the new progressbar - that might cause some king of problem.

I am using:
Arduino 1.0
Mac OSX Lion 10.7.1
Arduino Duemilanove

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
