### ISSUE TITLE
Servo won't turn while accepting commands from an Arduino 

### ISSUE THREAD

**Issue by Bradfo69** [arduino/Arduino#6662]
Hello everyone,

I'm asking for your advice -

I'm attempting to turn a servo with my Arduino when it gets orders from a serial contribution, for this situation, my console. I have officially done this with engines and it works fine however when I attempt with my servo it doesn't move by any means. (an example from - http://www.powerjackmotion.com/product-category/electric-motor/servo-motor-range/ ) So far I have this written -

#include <SoftwareServo.h>

SoftwareServo myservo;
int movemotor;
void setup() { 
Serial.begin(9600);
myservo.attach (10);
myservo.write(90);
}
void loop() {
movemotor = Serial.read();
if (movemotor = 111) {
for (int pos = 90; pos >=0; pos--) {
myservo.write(pos);
delay(15);
}
}
else if (movemotor = 99) {
for (int pos = 90; pos <= 180; pos++) {
myservo.write(pos);
delay(15);
}
}
}

I'm powering the servo remotely with a 9-volt battery and have made a point to associate its ground to that of the Arduino, however, can't see whatever else I fouled up.
Any help would be greatly appreciated.
Thanks

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/6661

@Bradfo69 you've already been told this is not the appropriate place to ask for help with your code. This issue tracker is to be used solely for reporting bugs and feature requests, as explained in the contributing guide:
https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md

This topic is more appropriate for the[ Arduino Forum](http://forum.arduino.cc). If you have not done so already, please post there after reading the [forum rules](http://forum.arduino.cc/index.php?topic=148850).  I'm sure we'll be able to help you with your problem over there.

Please inform the person that told you to ask for help here that is bad advise so they don't lead others astray.
