### ISSUE TITLE
Arduino IDE takes more time to startup each time

### ISSUE THREAD

**Issue by Richard-B** [arduino/Arduino#6664]
I am using Arduino IDE version 1.8.4 in my laptop , with **windows 10**. It will take **more time** to **startup** the Arduino IDE **each time.**
Plz give the solution for this type of issues.

**Comment by Richard-B** [comment]
I already have the title **Arduino** , it will take more time to startup for each time

**Comment by facchinm** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/6350
