### ISSUE TITLE
Non-ascii quotes in documentation

### ISSUE THREAD

**Issue by b0tting** [arduino/Arduino#6665]
The English example code on Serial / Write (https://www.arduino.cc/en/Serial/Write) contains some Word or otherwise non-ascii quote characters: 

> void loop(){
>   Serial.write(45);	// send a byte with the value 45
> 
>    int bytesSent = Serial.write(â€œhelloâ€); //send the string â€œhelloâ€ and return the length of the string.
> }

**Comment by kengdahl** [comment]
Replaced chars with ASCII-chars.
