### ISSUE TITLE
atwinc1500 AWS IOT Connectivity Issue

### ISSUE THREAD

**Issue by Anudeep09** [arduino/Arduino#6675]
Hi,  I am trying to connect my atwinc1500 to AWS IOT platform and am using samd21 as host controller, Please some one can help to how to connect to AWS IOT, For AWS we should pass CA certificate, Client certificate and Privatekey, I am using Arduino IDE.

**Comment by matthijskooijman** [comment]
Did you read the [contributing guidelines](https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md)? This issue tracker is not for asking help with your own project, so I'm closing it.
