### ISSUE TITLE
[Library Manager] Please add BlueRobotics_KellerLD_Library

### ISSUE THREAD

**Issue by rjehangir** [arduino/Arduino#6680]
Hello, this library supports the Keller LD series pressure sensors, which interface over I2C and measure water pressure. This library is very similar to our "BlueRobotics_MS5837_Library".

URL: https://github.com/bluerobotics/BlueRobotics_KellerLD_Library

**Comment by cmaglie** [comment]
Done!

**Comment by rjehangir** [comment]
Thanks! Appreciate it.
