### ISSUE TITLE
Incorrect formatting of Wire.onRequest(handler) reference page

### ISSUE THREAD

**Issue by DigantGoradia** [arduino/Arduino#6682]
https://www.arduino.cc/en/Reference/WireOnRequest page has a typo on the method name, which is not similar to other www.arduino.cc pages.

**Comment by per1234** [comment]
What's the typo?

**Comment by DigantGoradia** [comment]
There is a font Style mistake in name of the method according to other methods on the similar page(s).
i.e. the font color, style is mismatching.

**Comment by facchinm** [comment]
Fixed, thanks!
