### ISSUE TITLE
Using CLI options the loading screen opens on windows

### ISSUE THREAD

**Issue by Sorunome** [arduino/Arduino#6683]
On windows, when invoking command line options, the loading screen (that one that always appears when normally opening the IDE) appears. This is using Arduino 1.8.4

**Comment by cmaglie** [comment]
That is due to the way Launch4J works. To run the IDE as a pure command line on Windows you should use `arduino_debug.exe` (...I know the name is not the best... anyway...).

**Comment by Sorunome** [comment]
Works with that one, thanks! Should I close this issue?

**Comment by feikname** [comment]
@Sorunome You might be interested in the [Arduino(1) manual page](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) by the way.

**Comment by matthijskooijman** [comment]
Seems good to close this indeed :-)
