### ISSUE TITLE
Hardwareserial: Disable interrupts while setting TXC bit

### ISSUE THREAD

**Issue by NicoHood** [arduino/Arduino#6685]
As discussed [here](https://github.com/arduino/Arduino/commit/0be4e8cd3cbc6216ff01cd83282b1231639f9b60#commitcomment-23903797) the TXC bit setting should be atomic. Otherwise other (non usart) interrupts may corrupt the hardwareserial flush() function.

**Comment by NicoHood** [comment]
seems to be the same issue as #3745 with already opened pr by me long time ago #3865

**Comment by matthijskooijman** [comment]
I'm closing this as a duplicate, since though even though #3745 was opened for a different issue (double transmissions), its discussion has broadened to include this flush lockup issue too.
