### ISSUE TITLE
How can i reset the code from arduino

### ISSUE THREAD

**Issue by anantsingh4** [arduino/Arduino#6687]
hey arduino team, I have used the led blink code. But when i Start the arduino after some time, the code was still in the arduino. Can you please tell me a way to delete the code from it?

**Comment by per1234** [comment]
This issue tracker is only to be used for reporting bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
