### ISSUE TITLE
MySensors library missing in library manager

### ISSUE THREAD

**Issue by benji1304** [arduino/Arduino#6690]
Same as this previous issue the MySensors lib is no longer available from the Arduino library manager

https://github.com/arduino/Arduino/issues/5569

**Comment by per1234** [comment]
I can't reproduce this:
![clipboard01](https://user-images.githubusercontent.com/8572152/30005931-317a6820-90a2-11e7-9e58-d4d6a9e59404.png)

If the issue still occurs for you, please try this:

1. Click the link at the line following **File > Preferences > More preferences can be edited directly in the file**. This will open the Arduino15 (or similar) folder.
2. Delete all the files that start with library_index. Please be very careful when deleting files on your computer. When in doubt, back up!
3. Sketch > Include Library > Manage libraries... > Filter your search... > MySensors.

Hopefully it will now appear in the search results. Let me know if that solves the issue.

**Comment by benji1304** [comment]
@per1234 thanks for the assist. Didn't work, but then I noticed I was running an older version of the software. Uninstalled completely and reinstalled, worked fine.
