### ISSUE TITLE
New library: GUI for Arduino

### ISSUE THREAD

**Issue by MikhailNatalenko** [arduino/Arduino#6696]
Hello,

We have created the library for GUI: handling widgets, events, windows and etc. Would your manager support submodules? 

Repository: https://github.com/libEmGUI/emGUI-arduino

Thanks

**Comment by per1234** [comment]
I don't believe submodules are supported. See https://github.com/arduino/Arduino/issues/6385#issuecomment-310406324.

**Comment by romansavrulin** [comment]
Will Lib manager prefer binary github releases to just tags and git checkout?

**Comment by cmaglie** [comment]
> Will Lib manager prefer binary github releases to just tags and git checkout?

No, because it's more error prone than now.

Also archives generated on github are not guaranteed to be stable (i.e. they can change checksum, for example if "gzip" is updated on the github's servers... already happened in the past and also the reason why the archives are now hosted on arduino.cc servers).

**Comment by per1234** [comment]
I added a note to the Library Manager FAQ about submodules not being supported:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ/_compare/04d79210c86309b0bfa80e9faba001ce1d0896fd...46b8656d4fd038d1f2c0d8ce4f5a422d0bd5fa36

I'm guessing a subtree would work. https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree.

@MikhailNatalenko or @romansavrulin, please comment here once your repository is compliant so we know we can proceed with adding the library to the Library Manager index.

**Comment by MikhailNatalenko** [comment]
@per1234 We have switched to subtree. Please check if repo is ready for submit.

**Comment by per1234** [comment]
The final thing you need to do is to create a 1.0.0 release or tag. After you have done so, please comment here and we can then proceed to add your library to the Library Manager index.

More information: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by MikhailNatalenko** [comment]
@per1234  We have created the release and tag

**Comment by cmaglie** [comment]
Done!
