### ISSUE TITLE
[Library Manager]: Please add OpenBCI_32bit_SD

### ISSUE THREAD

**Issue by aj-ptw** [arduino/Arduino#6698]
**please note** the `master` branch in [OpenBCI_32bit_SD](https://github.com/OpenBCI/OpenBCI_32bit_SD) does not conform to standards please look at  [OpenBCI/OpenBCI_32bit_SD/pull/2](https://github.com/OpenBCI/OpenBCI_32bit_SD/pull/2) which conforms and will be merged in as soon as you guys merge so i can update docs.

**Comment by aj-ptw** [comment]
actually i just went a head and merged it

**Comment by cmaglie** [comment]
Done!
