### ISSUE TITLE
Problem in uploading a code to the board

### ISSUE THREAD

**Issue by madihanagar** [arduino/Arduino#6700]
I tried several times to upload a simple blink code to an arduino uno...but I keep receiving the following msg:
"Problem uploading to board"
I don't know whether it is a problem with the operating system or what....because i tried it before on a pc with windows 7 as an OS and it worked.
So is there a problem that I need to fix so as the code works on windows 10??
![code](https://user-images.githubusercontent.com/31690246/30104415-d12b2f76-92f5-11e7-9d3b-86bd0abd959c.png)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
