### ISSUE TITLE
[Library Manager] Please add Fuzzy-Tank library

### ISSUE THREAD

**Issue by georgychen** [arduino/Arduino#6711]
Link: https://github.com/FuzzyStudio/Fuzzy-Tank
Thank you.

**Comment by cmaglie** [comment]
Done!

**Comment by njh** [comment]
This repository seems to have been deleted?
Has it been moved to a new location?

**Comment by georgychen** [comment]
Sorry for the inconvenience. Then owner of this library (Fuzzy Inc.) has just decided to go private on this library, and made the repo private. Would you kindly remove this library from arduino library manager? Thank you.

**Comment by cmaglie** [comment]
Ok done.
