### ISSUE TITLE
Arduino IDE go creazy with variable B1 and B0

### ISSUE THREAD

**Issue by mashanz** [arduino/Arduino#6720]
I wrote code like this:

`void setup() {
}
void loop() {
}
void something(int A1){
}`
![1](https://user-images.githubusercontent.com/9214059/30329476-9294df12-97fc-11e7-8921-ca4a52daffd5.PNG)

Click verify and no errors. After a while I got bored with variable A1 and change it to B1. So the code become like this:

`void setup() {
}
void loop() {
}
void something(int B1){
}`

Click verify and got ERROR! -_-"

`exit status 1
expected ',' or '...' before numeric constant`
![2](https://user-images.githubusercontent.com/9214059/30329487-987f493a-97fc-11e7-9cb4-c136be68fac5.PNG)

tried this with another computer got same result.

whats going on?

**Comment by tofrnr** [comment]
I can confirm this bug - why has this issue been closed without any comment or explanation?

**Comment by per1234** [comment]
It's explained here: http://forum.arduino.cc/index.php?topic=499796
