### ISSUE TITLE
[Library Manager] New library ReactorProtocol a simulated industrial control protocol. 

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#6729]
https://github.com/WPIRoboticsEngineering/ReactorProtocol

WPI has developed a reactor communication protocol to train roboticists to build robots that can communicate with industrial infrastructure. This library is to provide both the server and client side of the simulated industrial control protocol. 

(Thank you for all your hard work making Arduino awesome!)

**Comment by cmaglie** [comment]
Done!
