### ISSUE TITLE
[Library Manager] AFArray: Array ADT

### ISSUE THREAD

**Issue by keyro90** [arduino/Arduino#6733]
https://github.com/keyro90/AFArray

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by keyro90** [comment]
@per1234 ok, I've done! Thank you!

**Comment by cmaglie** [comment]
Done!
