### ISSUE TITLE
Are there builds of kodi for arduino?

### ISSUE THREAD

**Issue by vomitous** [arduino/Arduino#6740]
Are there builds of kodi for arduino?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is not appropriate for this issue tracker. This sort of thing should be asked on the Arduino Forum.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to give enough details that you actually have a chance of getting an answer. **USE A DESCRIPTIVE TITLE!!!** Something like "coh dee" is not going to be conducive to you getting help.
