### ISSUE TITLE
Please add XLR8Quadrature library

### ISSUE THREAD

**Issue by crakerbr-superiontech** [arduino/Arduino#6743]
https://github.com/AloriumTechnology/XLR8Quadrature

**Comment by crakerbr-superiontech** [comment]
The library has not been added still, is something wrong?

**Comment by cmaglie** [comment]
Done!

**Comment by PaulStoffregen** [comment]
Tiny suggestion: perhaps add a link to the shield or needed hardware in your readme file.  Then when Arduino users discover your library in the library manager and they click the link for more info, they'll see the readme and perhaps click that link to be able to buy your hardware.  :)

**Comment by crakerbr-superiontech** [comment]
Thanks for adding, and thanks for the suggestion!
