### ISSUE TITLE
create.arduino not able to load or find bridge/ethernet

### ISSUE THREAD

**Issue by arduinovs** [arduino/Arduino#6746]
On create.arduino all bridge libraries cannot be found ( after include), so bridge, console httpclient etc 
It gives a compile error: nos uch file etc.
I also noticed that when loading examples, they cannot be downloaded(doownlaod errors). Looks like some lib files connot be found by create.arduino.
Other libs no problem

My board is Yun.
On the traditional IDE  (local)  it can be compiled without problem

**Comment by facchinm** [comment]
Already reported on http://forum.arduino.cc/index.php?topic=501316 and https://github.com/arduino/arduino-create-agent/issues/181, currently under investigation. Keeping track there, thanks!
