### ISSUE TITLE
consider adding my library shift7seg. driving 7 segment displays from 74hc595 shift registers

### ISSUE THREAD

**Issue by pseudoVella** [arduino/Arduino#6759]
url=    https://github.com/pseudoVella/shift7seg

for now it's just for a 4 digit display but i'm  considering  making it compatible with up to 64 digits. working on a proper schematic to post, but you should be able to figure out the hookup from comments in shift7seg.h file for now.

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by pseudoVella** [comment]
Oops sorry about that... Okay added a release, should be good to go now .

**Comment by cmaglie** [comment]
Done!
