### ISSUE TITLE
Don't recompile upon selection of an alternative serial port (for uploading). [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#676]
This is [Issue 676](http://code.google.com/p/arduino/issues/detail?id=676) moved from a Google Code project.
Added by 2011-10-10T16:27:20.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Have a serial port selected that doesn't exist.
2. Hit upload and wait for the dialog to appear for selecting another serial port.
3. Pick another serial port and hit okay.

**What is the expected output? What do you see instead?**
The sketch is recompiled.  It should only be reuploaded with the new serial port, not compiled again.

**Comment by ffissore** [comment]
Fixed a long time ago
