### ISSUE TITLE
Varable definition preset error

### ISSUE THREAD

**Issue by ameliaamelia** [arduino/Arduino#6762]
with:
uint8_t Var1 = 0; // (zero)

Var1 contains  1

with other vales all OK.

Arduino DUE IDE 1.8.4

**Comment by per1234** [comment]
Please provide a complete, minimal sketch that demonstrates the issue,

**Comment by ameliaamelia** [comment]
With a simple sketch all is OK, my application has more than 4000 rows of code; all worked fine but when I added some varables, the error rised; I solved putting all initalizations into the Start()

iPhone di Silvio

**Comment by per1234** [comment]
Without a minimal demonstration sketch it will be impossible for us to investigate this so I'm closing as invalid.

If you do find a way to produce one in the future that shows this to be a bug with the Arduino IDE then please update this issue and I'll re-open.
