### ISSUE TITLE
[LIB MANAGER] Add StepperControl Library

### ISSUE THREAD

**Issue by Erhan-MADE** [arduino/Arduino#6764]
lightweight library for stepper motor, with actions that specify sequential movements and options to trigger callbacks.  [StepperControl.](https://github.com/Erhan-MADE/StepperControl)

**Comment by per1234** [comment]
There are some things you need to do to make your repository eligible for inclusion in the Library Manager index:
1. Create a library.properties file following the Arduino Library Specification: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
1. Create a release or tag that matches the `version` value set in library.properties.

After you have done this, please comment here so we know we can proceed.

More information: https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Erhan-MADE** [comment]
Added files and created a release,

thanks

**Comment by per1234** [comment]
Actually you created a release and then added the library.properties file, which means your release does not contain a library.properties file:
https://github.com/Erhan-MADE/StepperControl/tree/2.0

Please either re-do your release or create a new one and then comment here so we know we can proceed with adding your library to the Library Manager index.

**Comment by Erhan-MADE** [comment]
You are right, still not used to using git properly.
Made a new release, bumped the version to 2.0b

sorry for the inconvenience :(

**Comment by per1234** [comment]
The `version` value must be semver compliant, which `2.0b` is not. From https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format:
>- version - version of the library. Version should be semver compliant. 1.2.0 is correct; 1.2 is accepted; r5, 003, 1.1c are invalid

More information: http://semver.org/

Once you have resolved this issue please comment here so we know we can proceed.

**Comment by Erhan-MADE** [comment]
this is getting embarrassing -.-
version 2.1 it is

**Comment by Erhan-MADE** [comment]
merged your fork, and made a new release

**Comment by cmaglie** [comment]
Done!
