### ISSUE TITLE
wire library not included in 1.8.4 macOS download on arduino.cc website.

### ISSUE THREAD

**Issue by sww1235** [arduino/Arduino#6765]
I just downloaded both the 1.8.4 zip file and the nightly zipfile and verified that neither has the wire library included under `Arduino.app/Contents/Java/libraries` which is where the rest of the standard libraries appear to be. This library is still listed as a standard library under <https://www.arduino.cc/en/Reference/Libraries> but does not appear to be listed under the https://github.com/arduino-libraries teams repos either. 

Has the wire library become deprecated and no longer distributed with the Arduino IDE or was its inclusion just overlooked in the 1.8.4 and beyond build process. 

Thank you

**Comment by per1234** [comment]
The Wire library is architecture specific and thus bundled with each hardware package. You'll find it in the libraries subfolder of the hardware package. This includes the Arduino AVR Boards hardware package included with the Arduino IDE at Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire.

**Comment by sww1235** [comment]
Thank you.
