### ISSUE TITLE
[LIB MANAGER] Add Overly Simplified File System (OSFS)

### ISSUE THREAD

**Issue by charlesbaynham** [arduino/Arduino#6768]
Hi there,

Please add https://github.com/charlesbaynham/OSFS to the library manager. 

Cheers!

**Comment by cmaglie** [comment]
@charlesbaynham 
there is a problem in your `library.properties` file:

```
JOB 1119 - 2017/09/29 10:56:26 Scraping https://github.com/charlesbaynham/OSFS.git
JOB 1119 - 2017/09/29 10:56:28 Checking out tag: 1.0
JOB 1119 - 2017/09/29 10:56:28 Error syncing library: Error generating library from repo: invalid INI syntax on line 7: an Arduino or other AVR microprocessor. Could be ported to other architectures very easily.
```

the `paragraph` field could not span over multiple lines, you must put everything in a single line.

https://github.com/charlesbaynham/OSFS/blob/master/library.properties#L5

to fix this:

- remove the release tag
- edit `library.properties` so the `paragraph` field is in a single line
- commit & push
- recreate the release tag

once done the library will be automatically published within an hour.
Please comment here if you need further assistance.
