### ISSUE TITLE
Add easy task to support both time-driven and event-driven programing.

### ISSUE THREAD

**Issue by erow** [arduino/Arduino#6770]
A lightweight but powerful implementation of linear single-tasking supporting. [EasyTask](https://github.com/erow/Task)

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by erow** [comment]
OK, it's done. Thank you for your help.

**Comment by cmaglie** [comment]
Done!
