### ISSUE TITLE
New library: Simple log macroses

### ISSUE THREAD

**Issue by ploys** [arduino/Arduino#6772]
Hi,
I have publish a tiny macros-set for logging which use in own projects, could you please add it to Library Manager.

Repository: https://github.com/ploys/arduino-logger

Thanks

**Comment by cmaglie** [comment]
There is already a library named `Logger`, you must choose another name for your library.
To fix this:

- delete the current release tag
- edit the `library.properties` file and change the `name` field
- I suggest to change also the name of the include to reflect the new name
- commit & push
- recreate a new release tag

thanks!

**Comment by ploys** [comment]
Hi, 
Is it ok if I rename it to Log?

**Comment by ploys** [comment]
Lib renamed, new release tag:
https://github.com/ploys/arduino-logger/releases/tag/v1.0.0

**Comment by ploys** [comment]
Hi,
I fix fatal error which invoke reboot of esp8266 board, updated release is here:
https://github.com/ploys/arduino-logger/releases/tag/v1.0.1

**Comment by matthijskooijman** [comment]
New versions should be automatically picked up by the IDE, but only if you increase the version number in the library.properties file, which you did not do for this tag. The version number in the tag is not used, though you must create a tag for the release to be picked up.

**Comment by ploys** [comment]
Thanks for advice, is it all ok now?
https://github.com/ploys/arduino-logger/releases/tag/1.0.1

**Comment by cmaglie** [comment]
Done!
