### ISSUE TITLE
Incorrect capitalization of Bluetooth AT commands

### ISSUE THREAD

**Issue by jpl-pfungst** [arduino/Arduino#6779]
Many post are indicating AT commands in upper case but all devices I tested up to now do not accecpt upper case.

All commands must be in lower case

How to solve this documentation problem.

**Comment by per1234** [comment]
This issue tracker is only for reporting problems with the official Arduino documentation. You must post links to the documentation page(s) in question with an explanation of the specific issues found on the page.

**Comment by per1234** [comment]
Closing due do lack of response from @jpl-pfungst. @jpl-pfungst if you can comment here with a link to an error in official documentation then I will re-open the issue.
