### ISSUE TITLE
Fatal error: DHT.h: No such file or directory

### ISSUE THREAD

**Issue by FlorentSms** [arduino/Arduino#6781]
Good evening,

Being a beginner in the arduino, I am currently experiencing a problem with my program. I try to read the data sent by a DHT11 type sensor.

I have correctly installed the library that you put online. I verified that it's in the Arduino libraries folder and I have checked that the Arduino IDE visualizes it well.

But when I try to upload the program, that's what he tells me:
https://puu.sh/xNwjj/e0bf912c99.png
https://puu.sh/xNwn6/1ad8fc18a3.png
https://puu.sh/xNwpB/23ace6dcb7.png

I think my library is well installed but I have the impression that it doesn't recognize it.
I hope you can help me.

Good night.

Florent

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. In addition, make sure to add the following information to your forum post:
    1. The full error output **AS TEXT**. Posting links to some strange website of screenshots of text is very unhelpful. In cases where images are helpful you should attach and embed them following [these instructions](http://forum.arduino.cc/index.php?topic=364156).
    1. A link to where you downloaded the library from or if you installed it via Library Manager state the full name of the library.
