### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by zzcrow** [arduino/Arduino#6782]
All Linux versions when having lots of examples or libraries to scroll to select, if they go off the screen there is no scrolling past to select them successfully!!! I have a lot of libraries and cannot use Linux versions due to this issue. Someone fix this. Windows and Mac versions work just fine. It may be a native Linux problem though. Thanks

**Comment by per1234** [comment]
Which version of the Arduino IDE are you using with Linux?

**Comment by zzcrow** [comment]
Running Linux MintArduino IDE version: 2:1.0.5+dfsg2-4 

    On Sunday, October 1, 2017 3:39 PM, per1234 <notifications@github.com> wrote:
 

 Which version of the Arduino IDE are you using with Linux?—

**Comment by per1234** [comment]
That's your problem. When you install the Arduino IDE via `apt get` you get a very outdated and possibly non-standard version of the Arduino IDE. You should always download the IDE from https://www.arduino.cc/en/Main/Software no matter which operating system you're using.
