### ISSUE TITLE
Not return actual value from calculating 64 bit int

### ISSUE THREAD

**Issue by Mizanurrahman2010** [arduino/Arduino#6785]
The return value should be **8**
But it return 7. Why???

=========================================
void setup() {
uint64_t num1 = PowerE(77,7);
uint64_t num2 = num1 - (num1/15) * 15);
uint32_t num3 = num2-num1;

Serial.begin(115200);
Serial.print(num3);

}

void loop() {
  // put your main code here, to run repeatedly:

}
long PowerE(long a, long b) {
  int64_t temp = 1;
  for (long i = 0; i < b; ++i) {
    temp = temp * a;
  }
  return temp;
}

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This is **NOT** an appropriate place to share your sketch or ask for help. You are welcome to post to the Arduino Forum.

Before doing so, please read http://forum.arduino.cc/index.php?topic=148850
Then create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).

**Comment by matthijskooijman** [comment]
As @facchinm says indeed. I was having a look at your problem anyway, but the code you pasted won't compile (unmatched parenthesis in the `num2` calculation) and AFAICS it should print `8 - num1`, not 8. Be sure to fix your question when asking on the forum.

**Comment by Mizanurrahman2010** [comment]
Solved;
void setup() {
uint64_t num1 = PowerE(77,7);
uint32_t num2 = num1 - ((num1/15) * 15);

Serial.begin(115200);
Serial.print(num2);

}

void loop() {
  // put your main code here, to run repeatedly:

}
uint64_t PowerE(long a, long b) {
  uint64_t temp = 1;
  for (long i = 0; i < b; ++i) {
    temp = temp * a;
  }
  return temp;
}

**Comment by Mizanurrahman2010** [comment]
Thanks
