### ISSUE TITLE
Arduino Leonardo ETH -> SCHEMATICS link loop

### ISSUE THREAD

**Issue by Serg-L** [arduino/Arduino#6790]
Page   **https://store.arduino.cc/usa/arduino-leonardo-eth**    link    <**SCHEMATICS**> 
is forwarding to page    
 **http://download.arduino.org/products/LEONARDOETH/Arduino_Leonardo_Eth_V1_sch.pdf**
Which is is forfarding back to:  **https://www.arduino.cc/**

Loop...

**Comment by per1234** [comment]
Thanks for reporting the broken link. It looks like it was not updated when that page was moved from arduino.org.

As a workaround, you can access that file here:
https://www.arduino.cc/en/uploads/Main/Arduino_Leonardo_Eth_V1_sch.pdf

Note that this schematic is for v1 of the board and apparently there are some differences in the v2 board (https://github.com/arduino/Arduino/issues/6741).

**Comment by per1234** [comment]
@frrederik the links still point to .org if you set your locale to "America, Asia, or Oceania".

**Comment by kengdahl** [comment]
The loop is fixed now. The schematics are now downloadable from the US page.
