### ISSUE TITLE
Looking for library 'user32'

### ISSUE THREAD

**Issue by PROGRAMINO** [arduino/Arduino#6793]
Hello,

i have a problem with the "command line" option at Version 1.8.2 and higher.
I have this problem with Win7 and Win10 and using "arduino_debug.exe"

After verify the following msg comes over the std-output:

> Looking for library 'user32'
> Adding paths from jna.library.path: null
> Trying user32.dll
> Found library 'user32' at user32.dll
> DPI detection failed, fallback to 96 dpi
> Looking for library 'shell32'
> Adding paths from jna.library.path: null
> Trying shell32.dll
> Found library 'shell32' at shell32.dll
> Looking for library 'Ole32'
> Adding paths from jna.library.path: null
> Trying Ole32.dll
> Found library 'Ole32' at Ole32.dll

What i try:

- delete all Arduino IDEs and all Arduino and Arduino15 folders in "Local and Rooming"
- clear temp folder
- install the IDE 1.8.3 new (only zip-file)

But the output msg is the same :-(

Please help me.

Ulli

**Comment by per1234** [comment]
Other than the new output messages, is the program working for you as expected?

**Comment by PROGRAMINO** [comment]
Yes is working, but only this msg is not great and confused many users.
Is there a way to suppress with the "arduino.exe" the splash screen and wait for end?

**Comment by cmaglie** [comment]
Try `arduino_debug.exe` instead of `arduino.exe`

**Comment by feikname** [comment]
@cmaglie he IS using `arduino_debug.exe` already.

**Comment by cmaglie** [comment]
Fixed by #7159
