### ISSUE TITLE
Append ssd1306 i2c oled library to Library Manager

### ISSUE THREAD

**Issue by lexus2k** [arduino/Arduino#6799]
Append ssd1306 i2c oled library to Library Manager

https://github.com/lexus2k/ssd1306

**Comment by per1234** [comment]
@lexus2k why did you close the issue? Do you no longer wish your library to be added to Library Manager?

**Comment by lexus2k** [comment]
@per1234 I'm sorry. I made it by mistake. I reopened the issue.

**Comment by cmaglie** [comment]
Done!
