### ISSUE TITLE
Linux - give a helpful error message if required packages missing [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#680]
This is [Issue 680](http://code.google.com/p/arduino/issues/detail?id=680) moved from a Google Code project.
Added by 2011-10-14T09:07:32.000Z by [paul.sto...@gmail.com](http://code.google.com/u/102276914943260257800/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

A user friendly, helpful error printed when someone tries Verify or Upload on a Linux system where one of the required packages (avr-gcc, avr-libc, binutils-avr) is missing.

**Why?**

The errors printed can be very confusing, especially in the case where avr-gcc is installed, but avr-libc is missing!

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

Should be fully compatible, only more user friendly.

**Comment by ffissore** [comment]
The IDE bundles all the needed tools
