### ISSUE TITLE
Please add UltraDistSensor library

### ISSUE THREAD

**Issue by shubhamtrivedi95** [arduino/Arduino#6805]
the library is available here https://github.com/shubhamtivedi95/UltraDistSensor

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by shubhamtivedi95** [comment]
yes i finishes the task you can check

**Comment by shubhamtivedi95** [comment]
yes i have finished task you can check

**Comment by shubhamtrivedi95** [comment]
![error](https://user-images.githubusercontent.com/24900137/31349721-fd276f8e-ad41-11e7-8f2b-8f6c1df69d50.png)  my library is not available on software can you please solve this issue.

**Comment by per1234** [comment]
Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through and clear all the outstanding Library Manager inclusion requests and closes the issues. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
Done!
