### ISSUE TITLE
Icon files for Arduino IDE

### ISSUE THREAD

**Issue by navy57** [arduino/Arduino#6814]
If you want to change the icon for Arduino files, here is the file:
Multi-sizes. 
[arduino_ico_ino_pde.zip](https://github.com/arduino/Arduino/files/1373849/arduino_ico_ino_pde.zip)

**Comment by navy57** [comment]
Add the icon file to the default installation folder Arduino:
"C:\Program Files (x86)\Arduino"
  and run the following reg file:
[Arduino reg_master.zip](https://github.com/arduino/Arduino/files/1373892/Arduino.reg_master.zip)

**Comment by per1234** [comment]
This issue tracker is only to be used for reporting bugs or feature requests. If I understand correctly, this is neither so I'm closing as invalid. In the future please post things like this to the [Arduino Forum](http://forum.arduino.cc/) or the [Arduino Playground](http://playground.arduino.cc/) wiki.
