### ISSUE TITLE
Library Manager: Change Name of DPS310 library

### ISSUE THREAD

**Issue by mhollfelder** [arduino/Arduino#6825]
Dear all,

we created a new release for the DPS310 library and changed the name from IFX_DPS310 to the more user-friendly name DPS310 in the library.properties.

https://github.com/Infineon/DPS310-Pressure-Sensor

However, the library manager indexer does not update the name from IFX_DPS310 to the new one.
What is the correct way to do this? Is there action needed by the Arduino staff?

Problem is, besides the name change, that the downloaded version pops up with the new name, but the IFX_DPS310 library can still be downloaded and installed. Therefore, the multiple names seem to confuse the library manager.

Thank you very much in advance and best regards,

Manuel

**Comment by cmaglie** [comment]
Done!
