### ISSUE TITLE
I2C- Communication mulfuctioning on EK-TM4C1294XL Launchpad 

### ISSUE THREAD

**Issue by KingZuluKing** [arduino/Arduino#6838]
dear all, 

The  EK-TM4C1294XL Launchpad shows dozens of devices when using i2C scanner. The same i2c scanner works fine, together with 4 slaves on the bus. The launchpad does not really spot devices on the bus via i2C scanner. Anyone has bumped into this issue so far? 

-slaves on Bus 
1. mcp 4351 potti
2. LM-75 temperature sensor
3. PCF 8575 I/O expander 
4.  PCF 8575 I/O expander

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This is **NOT** an appropriate place to share your sketch or ask for help. You are welcome to post to the Arduino Forum.

Before doing so, please read http://forum.arduino.cc/index.php?topic=148850
Then create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
