### ISSUE TITLE
Please add this library to the manager.

### ISSUE THREAD

**Issue by s00500** [arduino/Arduino#6841]
https://github.com/s00500/ESPUI

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by s00500** [comment]
done

**Comment by cmaglie** [comment]
Library added!
