### ISSUE TITLE
Arduino Nano code Download with Averdude 

### ISSUE THREAD

**Issue by AVRCrazyDude** [arduino/Arduino#6843]
Hello , i have a problem . I have UsbAVr programmer and i export hex form the Arduino software and burn it with averdude on a barebone atmega328 and it working perfect , i can download it back in to .hex and the arduiono software open it , no problem . The problem comes when i have a program arduino nano with Arduino Softwere  , averdude can download the hex file from the arduino nano, so far soo good . The funnny part is that i try to open it the Arduino Softwere say it can open only ,ino or .bsp. So How exported hex can be open and code that is burned on Nano that uses Arduino Software and USB to serial ic cant be open when it be downloaded ot hex :D > Help me  how to Open The Hex file from arduino nano that is downloaded from Averdude

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
