### ISSUE TITLE
Cannot satisfy the following dependencies for kmod-video-uvc

### ISSUE THREAD

**Issue by ephraimguo** [arduino/Arduino#6846]
I am currently working on Arduino yun FIR sensor and camera project, but I am not able to install "kmod-video-uvc" for my Arduino yun. I have also tried to reflash  the Arduino yun, but still cannot install "kmod-video-uvc". Our web panel shows linino webpage, it is not not Arduino page.May I know what is the problem?

**Comment by facchinm** [comment]
Hi @ephraimguo,
the package availability depends on which firmware image is installed. You can follow the update procedure [here](https://www.arduino.cc/en/Tutorial/YunSysupgrade) to install 1.6.2 which contains the needed kernel module. 
If you find any problem, please reopen the issue in the yun github repository (https://github.com/arduino/openwrt-yun-1505).
Thanks!
