### ISSUE TITLE
Incorrect text on pin mapping/pinout buttons on Micro product page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6857]
Documentation tab of https://store.arduino.cc/arduino-micro

The text on the buttons is just a generic placeholder:
![clipboard01](https://user-images.githubusercontent.com/8572152/32022921-a79d6120-b98c-11e7-8458-7da1d427268b.png)
Rather than the correct text as you would see on e.g. the Uno product page:
![clipboard02](https://user-images.githubusercontent.com/8572152/32022977-d157b7b8-b98c-11e7-912d-d27a8c9364d2.png)

**Comment by kengdahl** [comment]
On it.

**Comment by kengdahl** [comment]
Solved
