### ISSUE TITLE
Incorrect PWM pin on Micro schematic

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6858]
The schematic for the Arduino Micro:
https://www.arduino.cc/en/uploads/Main/arduino-micro-schematic.pdf
Which is linked from the product page:
https://store.arduino.cc/arduino-micro

Shows that Arduino pin 4 (PD4) has PWM. In fact that should be Arduino pin 3 (PD0).

![clipboard01](https://user-images.githubusercontent.com/8572152/32024293-cf22fc24-b990-11e7-87b2-a4022cacef60.png)

This information is documented correctly everywhere else I have checked, including the Leonardo documentation.

Originally reported at http://forum.arduino.cc/index.php?topic=507716

In a way, this was previously reported at https://github.com/arduino/Arduino/issues/1373 but that issue assumes the schematic was correct and thus recommended incorrect edits to the documentation.

**Comment by kengdahl** [comment]
The schematics should be fixed now.
