### ISSUE TITLE
onReceive in Wire?

### ISSUE THREAD

**Issue by cqin5** [arduino/Arduino#6861]
I noticed that in Wire.h there is no method similar to onReceive in the original Wire library, is it missing or is it not there by design? 

If it is not there by design, what would be the alternative to it?

Thank you in advance.

**Comment by per1234** [comment]
It's not clear which Wire library you're referring to but since this was the traditional place to report Arduino AVR Boards I'll assume that's the one. Here it is:
https://github.com/arduino/ArduinoCore-avr/blob/3f63f2975e7183c3254b6794bfcc8f19ca0301c9/libraries/Wire/src/Wire.h#L72
