### ISSUE TITLE
Feature request: Collapse/Expand functions

### ISSUE THREAD

**Issue by Kabcorp** [arduino/Arduino#6863]
Hello, I don't understand why this feature isn't here since the first version =)
This will be very usefull when a project start to be a bit big.

Thank you!

**Comment by PaulStoffregen** [comment]
File > Preferences : Enable Code Folding.

**Comment by Kabcorp** [comment]
Yes i wanted to delete it after i seen it... But, it should be great to have a "Collapse All" and "Expand All".
