### ISSUE TITLE
No rule to make target 

### ISSUE THREAD

**Issue by Nonth8031** [arduino/Arduino#6865]
Hello:

I have installed Sloeber v4.0 ([link](http://eclipse.baeyens.it/archived.php?ver=4.0)) today but It gives me an error when I compile.
Error:
12:45:38 **** Incremental Build of configuration Release for project Blink_LED13 ****
"C:\\sloeber\\arduinoPlugin\\tools\\make\\make" all 
'Building file: ..\.ino.cpp'
'Starting C++ compile'
"C:\sloeber\/arduinoPlugin/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10802 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   -I"C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.20\cores\arduino" -I"C:\sloeber\arduinoPlugin\packages\arduino\hardware\avr\1.6.20\variants\mega" -MMD -MP -MF".ino.cpp.d" -MT".ino.cpp.o" -D__IN_ECLIPSE__=1 -x c++ "..\.ino.cpp"  -o  ".ino.cpp.o"
'Finished building: ..\.ino.cpp'
' '
make: *** No rule to make target 'C:\Users\JM\My', needed by 'Blink_LED13.elf'.  Stop.

12:45:45 Build Finished (took 6s.922ms)

When I try Upload to my Arduino Mega 2560 R3 that's occurs.
I have installed Arduino IDE v 1.8.5 too

Thank you for your time 😄

**Comment by facchinm** [comment]
Hi @Nonth8031 ,
we don't use make in  our build system so the bug is 100% on the Sloeber side. You can report the issue [here](https://github.com/Sloeber/arduino-eclipse-plugin/issues)
