### ISSUE TITLE
Request to add FingerLib V2.0.7 to library manager

### ISSUE THREAD

**Issue by OllyMcBride** [arduino/Arduino#6866]
https://github.com/Open-Bionics/FingerLib

thank you :)

**Comment by cmaglie** [comment]
The library is already added, if you need to release another version just git-tag it, our indexer will pick it up automatically within an hour.

**Comment by OllyMcBride** [comment]
The indexer hasn't picked up the latest version (V2.0.7). The most recent version on the Arduino libraries manager is V2.0.5.

**Comment by cmaglie** [comment]
I can see it:

![image](https://user-images.githubusercontent.com/423515/32167448-27035552-bd69-11e7-9a9f-21b0738a60dc.png)
