### ISSUE TITLE
Does anyone know how I can fix this issue?

### ISSUE THREAD

**Issue by ArmandoHernandez14** [arduino/Arduino#6868]
Arduino: 1.8.5 (Windows 10), Board: "Arduino Due (Programming Port)"

Sketch uses 23536 bytes (4%) of program storage space. Maximum is 524288 bytes.
No device found on COM3
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by cmaglie** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
