### ISSUE TITLE
Does Arduino signal to its 'Tools' that it is closing.

### ISSUE THREAD

**Issue by TonyCallear** [arduino/Arduino#6869]
### Background:
I am not a java programmer – I am not much of a programmer at all.

I’m asking in relation to the tool – Ardublock at https://github.com/taweili/ardublock . The .jar is here https://github.com/taweili/ardublock/releases/download/beta-20171028/ardublock-all-master-beta-20171028.jar

I’ve got Ardublock to question attempts to close down with unsaved work -EXCEPT- when the main Arduino IDE is closed..  where Ardublock silently dies.

### The Question:
* I not sure if my problem is a general java thing but I think it’s specific to Arduino?

* Are there signals I can use that Arduino sends to its Tools when it’s closing? If not, could these be created?

* Can I prevent the Arduino IDE closing from a 'Tool'?

Hope you can help - please let me know where I'm not being .

**Comment by facchinm** [comment]
Hi @TonyCallear,
since ardublock is an external project I'd only leave the issue you opened there as the only reference for this bug. Thanks for reporting anyway!
