### ISSUE TITLE
Can't build Arduino on Windows using 64-bit JDK. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#687]
This is [Issue 687](http://code.google.com/p/arduino/issues/detail?id=687) moved from a Google Code project.
Added by 2011-10-22T03:27:37.000Z by [yincrash](http://code.google.com/u/yincrash/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Build, OpSys-Windows

### Original description

**What steps will reproduce the problem?**
1. clone git repo
2. ant
3. ant run

**What is the expected output? What do you see instead?**
Arduino IDE running. Instead, splash screen shows, then disappearsa

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
$ git log
commit b14a3c501ebd62afff251fb69169df6a6bcf9758
Author: David A. Mellis <d.mellis@arduino.cc>
Date:   Fri Oct 21 18:25:14 2011 -0400

**Please provide any additional information below.**
Windows 7 x64

**Comment by ffissore** [comment]
This was fixed with IDE 1.5.6 by removing RXTX. The other UnsatisfiedLinkError has been fixed as well with f6546aea4527bb0723fac6472c1e10328ebe9473
