### ISSUE TITLE
Error Bluetooth hc-06

### ISSUE THREAD

**Issue by tatansti** [arduino/Arduino#6873]
Hola, tengo un arduino mega 2560 y una placa bluetooth hc-06, necesito prender un led con una aplicacion, pero a la hora de conectar el rx y tx del bluetooth a mi arduino, siempre me da un error (avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
Ha ocurrido un error mientras se enviaba el sketch), Yo conecto el tx del bluetooth al rx0<-0 del arduino y el rx del bluetooth al tx0->1 del arduino. Al parecer el error solo ocurre cuando conecto algo al tx0 del arduino :( Necesito ayuda porfa!.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
