### ISSUE TITLE
XMEM interface of the ATmega2560

### ISSUE THREAD

**Issue by mamama1** [arduino/Arduino#6876]
Hi

does the Arduino Core support the XMEM interface provided by the ATmega2560 (and others)?
That would be hilarious, with that we'd be able to have an 8 Bit AVR with 64KB(!) of memory!

Thanks

**Comment by facchinm** [comment]
Hi @mamama1 ,
there is no helper in the core but probably avr-libc provides some useful functions (and probably also a library exist). I'm closing the issue since this kind of questions should be asked on the forum (primarily) or on the developers mailing list. Thanks!
