### ISSUE TITLE
https://playground.arduino.cc/Csharp/SerialCommsCSharp

### ISSUE THREAD

**Issue by Granta-DEV** [arduino/Arduino#6880]
"https://playground.arduino.cc/Csharp/SerialCommsCSharp"

Error in the C# Syntax within the documentation/tutorial listed above, 
Ln 29 :: portFound = false";
Ln 62 :: ComPort.name = returnMessage;

**Comment by per1234** [comment]
The Arduino Playground is a publicly editable wiki. The Arduino community is responsible for the content of the Playground so it is not appropriate to create issue reports for it in this repository.  You are welcome to edit the Playground as you see fit. When you go to edit you will encounter a password page but that's just to prevent spam, the password is pre-filled. If you are unsure of how to fix an issue you find on the Playground or just want to discuss planned work with the community feel free to post on the [Arduino Forum.](https://forum.arduino.cc/index.php?board=21.0).

>Ln 29 :: portFound = false";

I have fixed this error.
>Ln 62 :: ComPort.name = returnMessage;

I don't have enough (any) knowledge of C# to know how to fix this one, I hope you'll take the time to do so.
