### ISSUE TITLE
Please add my library to library manager.

### ISSUE THREAD

**Issue by Geabong** [arduino/Arduino#6881]
Please.

My library name is ModbusRTUSlaveArduino.
https://github.com/Geabong/ModbusRTUSlaveArduino

**Comment by per1234** [comment]
The `version` value in your library.properties file must match the release version. The only release that has a Library Manager compliant library structure is 1.01 but the `version` value in library.properties is[ 1.0.0](https://github.com/Geabong/ModbusRTUSlaveArduino/blob/1.01/library.properties#L2).

Please either redo your release or create a new one that has a matching `version` value.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
