### ISSUE TITLE
Please add my library to library manager.

### ISSUE THREAD

**Issue by Geabong** [arduino/Arduino#6882]
#6881 

Please.

My library name is ModbusRTUSlaveArduino.
https://github.com/Geabong/ModbusRTUSlaveArduino

I corrected the mistake and released it again.

**Comment by cmaglie** [comment]
Library added!
For the next time, you can post additional comments on the previous issue #6881, no need to open a new one.

**Comment by Geabong** [comment]
I used github for the first time. Thanks.

**Comment by njh** [comment]
@Geabong it looks like you have now deleted this library.
Do you have any feedback about why you deleted it?
(it is currently still in the Arduino Library Manager)
