### ISSUE TITLE
Please add this library to the library manager?

### ISSUE THREAD

**Issue by r-downing** [arduino/Arduino#6883]
https://github.com/r-downing/PersWiFiManager

It is a Persistent WiFi Manager, an alternative to tzapu's WiFiManager for ESP8266. It is non-blocking, and allows the program to proceed into the main loop with or without an internet connection (station mode or AP mode w/ captive DNS server), and also allows the user to change wifi settings at any time from either mode, while continuing to function as a web server, etc.

**Comment by cmaglie** [comment]
Done!
