### ISSUE TITLE
delay() function broken in IDE-1.0-rc1 w/ avr-binutils 2.21.1 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#689]
This is [Issue 689](http://code.google.com/p/arduino/issues/detail?id=689) moved from a Google Code project.
Added by 2011-10-23T12:54:13.000Z by [Vliegend...@gmail.com](http://code.google.com/u/106514463411566029577/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Use IDE 1.0 rc1
2. Upload Blink.ino to an Arduino UNO
3. See the led on pin 13 NOT blink

**What is the expected output? What do you see instead?**
Led should blink, but doesn't

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino UNO, optiboot version shipped with 1.0 rc1

**Please provide any additional information below.**
Problem comes from the delay() function.
I've been having similar issues in other projects and libraries, so I tested the blink.ino example to verify that it really is a basic issue with the delay() function.

This bug also persists on various other 328P based arduino hardware with optiboot.

**Comment by NicoHood** [comment]
I guess this can be closed?

**Comment by sandeepmistry** [comment]
Closing, no complaints about the Blink sketch or delay() not working recently.
