### ISSUE TITLE
[Lib Manager] Please add M10Examples to the Arduino Library Manager

### ISSUE THREAD

**Issue by PulseRainmaker** [arduino/Arduino#6890]
https://github.com/PulseRain/M10Examples

**Comment by per1234** [comment]
It looks like your library.properties file is copied from the M10ADC library. There is already a library of that name in the Library Manager index. Please update your library.properties file and then create a release that matches the `version` value in library.properties.

After doing so, please comment here so we know we can proceed.

**Comment by PulseRainmaker** [comment]
Sorry for the stupid mistake. I have updated the repository and created a new tag 1.1.0

**Comment by cmaglie** [comment]
Done!

**Comment by PulseRainmaker** [comment]
Thanks!
