### ISSUE TITLE
Arduino Primo library CoreSensors.h throws error: undefined reference to `Wire1'

### ISSUE THREAD

**Issue by Hobabu** [arduino/Arduino#6892]
The following error message is displayed with every example code that uses the library. Please fix the library.

"C:\Users\X\AppData\Local\Temp\arduino_build_823832/..\arduino_cache_81757\core\core_arduino_nrf52_primo_5bcc9bbe99028a4ca8901f30df64474e.a" -Wl,--end-group
C:\Users\marcus\AppData\Local\Temp\arduino_build_823832\libraries\CoreSensors\CoreSensors.cpp.o: **In function `CoreSensors::begin()'::**

C:\Users\X\AppData\Local\Arduino15\packages\arduino\hardware\nrf52\1.0.2\libraries\CoreSensors\src/CoreSensors.cpp:50: **undefined reference to `Wire1'**

collect2.exe: error: ld returned 1 exit status

**Comment by cmaglie** [comment]
Hi @Hobabu,

the library is made for the "Primo Core", so it will compile once you select the "Arduino Primo Core" board from the Tools->Board menu.
