### ISSUE TITLE
Add Library request: MFUthings

### ISSUE THREAD

**Issue by beetlikeyg087** [arduino/Arduino#6894]
Hello,

Please check and add this library to Library Manager

https://github.com/beetlikeyg087/MFUthings

best regards.

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by beetlikeyg087** [comment]
I have updated information,

can you please check again?

best regards.

**Comment by cmaglie** [comment]
Done!

**Comment by njh** [comment]
Hi @beetlikeyg087

It looks like your library has now been deleted?
https://github.com/beetlikeyg087/MFUthings

Any background as to why?

nick.
