### ISSUE TITLE
RTC_DS3231 does not name a file type

### ISSUE THREAD

**Issue by jsteele09** [arduino/Arduino#6898]
Previously working sketches are no longer compiling. Even the supplied example sketches no longer work giving the same error. This is on Arduino editor online and the local Arduino 1.8.3. See attached for example code I was referring to.
[DS3231_dateformat.txt](https://github.com/arduino/Arduino/files/1450792/DS3231_dateformat.txt)

EDIT 2017-11-07 by @per1234 to add the code from the above attachment:
```arduino
#include <Wire.h>
#include "RTClib.h"

/*-----( Declare Constants and Pin Numbers )-----*/
// Not needed: RTC Lib expects connections as above

/*-----( Declare objects )-----*/
RTC_DS3231 rtc;    // Create a RealTimeClock object

/*-----( Declare Variables )-----*/
// NONE because the library handles this...

void setup()   /****** SETUP: RUNS ONCE ******/
{
  Serial.begin(9600); // Set up for Serial Monitor to be able to see this work
  // Set this in the lower right of the Serial Monitor screen
  
  Serial.println("YourDuino.com DS1307 Real Time Clock - Set / Run Utility");

  /*----( These lines allow code to work also on Arduino DUE )----- */
#ifdef AVR
  Wire.begin();
#else
  Wire1.begin(); // Shield I2C pins connect to alt I2C bus on Arduino Due
#endif

  rtc.begin(); // Start the RTC library code

  /*----( SET the date and time.  Comment OUT these lines after setting )----*/
  // Put these "//" in front of the line you do NOT want to use
  // following line sets the RTC to the date & time this sketch was compiled
  rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));
  // This line sets the RTC with an explicit date & time, for example to set
  // May 21, 2015 at 6pm you would call: (use 24 hour time)
  //    rtc.adjust(DateTime(2015, 5, 21, 18, 0, 0));

}//--(end setup )---


void loop()   /****** LOOP: RUNS CONSTANTLY ******/
{
  DateTime now = rtc.now();  // Read data from the RTC Chip

  Serial.print(now.year(), DEC); //
  Serial.print('/');
  Serial.print(now.month(), DEC);
  Serial.print('/');
  Serial.print(now.day(), DEC);
  Serial.print(' ');
  Serial.print(now.hour(), DEC);
  Serial.print(':');
  Serial.print(now.minute(), DEC);
  Serial.print(':');
  Serial.print(now.second(), DEC);
  Serial.println();

  delay(3000);
}
```

**Comment by facchinm** [comment]
Hi @jsteele09 , which version of the IDE was compiling this sketch successfully? The error means that "RTClib.h" cannot be found by the builder; I'm closing the issue here, you should reopen it on https://github.com/arduino/Arduino-builder with the following information:
- IDE version in which this sketch was compiling
- **Verbose** output of the compilation (enable it on file/preferences)
- Check if it works with Beta IDE (https://www.arduino.cc/en/Main/Software#beta)

Thanks!

**Comment by jsteele09** [comment]
The original IDE version that I successfully compiled was 1.8.3. Using the web version on create.arduino.cc I was able to get my sketches to compile once more. All I had to do to accomplish this was change RTC_DS3231 rtc; to DS3231rtc; Everything works and it keeps time as it should. I am not sure if a library changed automatically online, but I don't see why mine quit on the desktop unless I may have updated that library myself without realizing it.

**Comment by facchinm** [comment]
Yep, probably the local library you have installed contains some modifications over the regular one (which is "shipped" by Create). You can try moving it outside your sketchbook and redownload it via Library Manager to check if they're different.

**Comment by Giovani-Delgado** [comment]
Please help me!
I have not been able to compile with the web editor for a week.
It bears the following message:
No matching function for call to'DS3231 (const uint8_t &, const uint8_t &)'
I already uninstalled the DS3231 library and reinstalled. Unsuccessfully.
The usage examples for the DS3231 also carry the same message...
In IDE 1.8.5 it compiles perfectly.
Thank you very much for your attention!

**Comment by per1234** [comment]
@Giovani-Delgado please post about this to the Create > Editor section of the Arduino Forum:
http://forum.arduino.cc/index.php?board=101.0

That is the best place for us to provide support for your problem. It is also the place to report bugs in the Arduino Web Editor in case we determine that is the problem.

Make sure to provide all the information we will need to reproduce the problem, including the complete error output. This will allow us to help you get your problem solved quickly.
