### ISSUE TITLE
Create some demo tool plugins (e.g. for copying the built .hex file to a known location). [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#690]
This is [Issue 690](http://code.google.com/p/arduino/issues/detail?id=690) moved from a Google Code project.
Added by 2011-10-23T16:13:21.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE

### Original description

We should make some examples of the Tools menu plugins.  For example, something that copies the .hex file to a known location after compilation to make it easier for custom upload processes.  Or a tool that disassembles the final binary for people to inspect.

**Comment by ffissore** [comment]
Saving hex implemented in #2458. We won't make a demo tool because, having missed synchronization with Processing, we had to maintain that API on our own, including documentation
