### ISSUE TITLE
Add library request: DS1624

### ISSUE THREAD

**Issue by bluemurder** [arduino/Arduino#6900]
Hello,
I recently created a library to interface with Maxim DS1624 temperature sensor.

Some code related to that sensor can be found over internet, but my aim is to extend that codes in order to cover all the IC functionalities (temperature sensing, thermostat, eeprom).

The url related to such library is https://github.com/bluemurder/DS1624

Best regards,
Alessio

**Comment by bluemurder** [comment]
I merged the requested changes and published a release including that code.

**Comment by cmaglie** [comment]
done!
