### ISSUE TITLE
Link to Mouse library reference page redirects to Keyboard reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6901]
The Keyboard and Mouse library links on https://www.arduino.cc/en/Reference/Libraries both point to https://www.arduino.cc/en/Reference/MouseKeyboard. Apparently before the new Language Reference pages system was put in place there was a common entry page for the documentation of those libraries. Now there is a separate page for each library but https://www.arduino.cc/en/Reference/MouseKeyboard redirects to the Keyboard page only (https://www.arduino.cc/reference/en/language/functions/usb-leonardo-and-due-only/keyboard/), causing the Mouse link on https://www.arduino.cc/en/Reference/Libraries to lead to the Keyboard reference page rather than the Mouse reference page.

The correct URL for the Mouse library reference page is https://www.arduino.cc/reference/en/language/functions/usb-leonardo-and-due-only/mouse/.

The same issue occurs at https://www.arduino.cc/en/Guide/ArduinoLeonardoMicro

I'm also confused why the Keyboard and Mouse library reference pages are even part of the Language Reference since other library reference pages are not. Maybe this is a relic from when the libraries were in the core?

**Comment by kengdahl** [comment]
Fixed
