### ISSUE TITLE
Library examples page implies the Wire library is not compatible with Due

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#6902]
From the Wire Library section of https://www.arduino.cc/en/Tutorial/LibraryExamples:
>For all Arduino boards, BUT Arduino DUE.

To me, that reads as saying the Wire library is not compatible with Due but I'm pretty sure that's wrong because Arduino SAM Boards does contain a Wire library, the example sketches are functionally identical to those in the examples page, and the Wire library reference page does mention the Due.

Originally reported at http://forum.arduino.cc/index.php?topic=510365

**Comment by SimonePDA** [comment]
As documented in the Wire Library page, it IS compatible with the Arduino DUE as well. Corrected the wrong statement in the Library Examples page.

Thanks

**Comment by per1234** [comment]
Re-opening because the erroneous statement remains:
![Clipboard01](https://user-images.githubusercontent.com/8572152/54976399-7b3f3600-4f57-11e9-9123-1ee99f4de361.png)

**Comment by SimonePDA** [comment]
For some reason the page was "recovered" from an earlier edit and the correcion got lost. Redone.
