### ISSUE TITLE
Rename existing library in Library manager

### ISSUE THREAD

**Issue by Marzogh** [arduino/Arduino#6904]
Hi guys, I’m looking at possibly renaming my SPIFlash library to something else as it appears to cause issues for users using @LowPowerLab ‘s SPIFlash library. (Felix's library has been around for a few years more than mine)

Would it be possible re-name my library and not break the upgrade path (through library manager) for current users?

Ref: [Issue 83 (SPIFlash)](https://github.com/Marzogh/SPIFlash/issues/83)

**Comment by cmaglie** [comment]
> Would it be possible re-name my library and not break the upgrade path (through library manager) for current users?

No, existing users will need to reinstall the library with the new name.

Moreover, you must ask here to change the name in the library manager, you can't do it autonomously.

**Comment by Marzogh** [comment]
Thanks for the information. I'll see/do what needs to be done. :)
