### ISSUE TITLE
Add Library Request: STEAMbot

### ISSUE THREAD

**Issue by aramperez-tst** [arduino/Arduino#6912]
Dear Arduino,

I'm kindly requesting that you add the STEAMbot library to the IDE. It's available at https://github.com/The-STEAM-Train/STEAMbot

Thank you,
Aram

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by aramperez-tst** [comment]
I've just tagged and released the library.

Thanks,
Aram

**Comment by cmaglie** [comment]
Done!
