### ISSUE TITLE
Mention processor ressources in reference documentation (like millis() command etc.)

### ISSUE THREAD

**Issue by dl1dmw** [arduino/Arduino#6914]
Neebies and hobyists like me like to know the internal processor ressources used by a command like millis() or other c commands. In case of millis() it should be mentioned the timer used in the reference doc. In other cammands it would be helpful to know the estimated amount of space.
Also in Arduino libs: They should mention used internal processor ressources to avoid conflicts.

**Comment by kengdahl** [comment]
Hey. Here is a article about timers you might find interesting: 
[https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM](https://www.arduino.cc/en/Tutorial/SecretsOfArduinoPWM)

**Comment by SimonePDA** [comment]
The documentation is made to be easy to read and understand; the more tech-heavy topics are dealt on our forum and on many dedicated pages around the net. You may find the details you are looking for just visiting our forum and by googling your specific topic.

Thanks for your request.
