### ISSUE TITLE
[Library Manager] Add ESP-DASH

### ISSUE THREAD

**Issue by ayushsharma82** [arduino/Arduino#6915]
ESP-DASH is a new Library to Add UI Dashboards to your ESP8266.
Please Add it.

https://github.com/ayushsharma82/ESP-DASH

Thanks!

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by cmaglie** [comment]
Done!
