### ISSUE TITLE
Some String examples broken [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#692]
This is [Issue 692](http://code.google.com/p/arduino/issues/detail?id=692) moved from a Google Code project.
Added by 2011-10-24T01:47:53.000Z by [maniac...@ymail.com](http://code.google.com/u/104304625040622075887/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

The changes to the String class API surface have broken some of the examples.  This patch fixes them.  (If it doesn't apply cleanly let me know, I'll regenerate one from a clean repo)

**Comment by per1234** [comment]
Closed by https://github.com/arduino/Arduino/commit/383ac95f3ec975bd466e265c945cdffb9828f205
