### ISSUE TITLE
Reference pages for Keyboard.write and Keyboard.print/Keyboard.println: incorrect return types 

### ISSUE THREAD

**Issue by sterretje** [arduino/Arduino#6920]
Referring https://github.com/arduino/Arduino/issues/6659

Same/similar issue (which was solved), but now for the Keyboard library (e.g. Leonardo). The functions in the title return size_t, not int.

**Comment by per1234** [comment]
Thanks! I'll submit a PR to fix this but there is currently an open pull request on those pages fixing another issue so I'll wait until it's merged to avoid a merge conflict.
