### ISSUE TITLE
Keyboard.println unexpected behaviour

### ISSUE THREAD

**Issue by sterretje** [arduino/Arduino#6922]
When using Keyboard.println, one expects the cursor to go to beginning of the next line in the active window. This does not happen,

The description in the reference section states the below and technically that is correct

> Sends a keystroke to a connected computer, followed by a newline and carriage return.

A note on the reference page would be useful. Workaround is to use Keyboard.print{"Hallo") followed by Keyboard.write(KEY_RETURN).

A bugfix would even be better ;-)

In case relevant:
Windows 8 64 bit, IDE 1.6.6 (so you can determine library version), tested with Notepad and Notepad++.

**Comment by facchinm** [comment]
Could you move the issue to https://github.com/arduino-libraries/keyboard? Thanks!
