### ISSUE TITLE
espcomm errors after updating to macOS 10.13.1 High Sierra

### ISSUE THREAD

**Issue by TS22082** [arduino/Arduino#6928]
I believe updating to High Sierra caused the problem because code that was working RIGHT before the update, do not upload anymore. I even tried uploading the sample blinky program for the Sparkfun esp8266 Thing Dev board and it wont upload to the board either. 

Sparkfun thing dev, Arduino 1.85, macOS 10.13.1 High Sierra (tried 2 different usb cables both work on different devices)

the errors Im getting: 
`An error occurred while uploading the sketch
Uploading 228336 bytes from /var/folders/vm/7zhkws111z575vj68kz3wzkw0000gn/T/arduino_build_776513/blickyESP8266.ino.bin to flash at 0x00000000
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
error: espcomm_upload_mem failed`

**Comment by per1234** [comment]
Since Arduino doesn't sell any ESP8266 based boards this is off topic for this repository.
