### ISSUE TITLE
Digital Read Serial typo

### ISSUE THREAD

**Issue by pleabargain** [arduino/Arduino#6934]
URL
https://www.arduino.cc/en/Tutorial/DigitalReadSerial

bord 
should be 
board

Once the bord has read the input, make it print this information back to the computer as a decimal value. You can do this with the command Serial.println() in our last line of code:
should be
Once the board has read the input, make it print this information back to the computer as a decimal value. You can do this with the command Serial.println() in our last line of code:

**Comment by kengdahl** [comment]
Fixed

**Comment by per1234** [comment]
Re-opening because the typo is still there:
![Clipboard01](https://user-images.githubusercontent.com/8572152/54975815-91e48d80-4f55-11e9-8231-186c50a4b5e0.png)
