### ISSUE TITLE
Incorrect hyperlink for noDisplay() on LiquidCrystalDisplay tutorial webpage 

### ISSUE THREAD

**Issue by bdr2** [arduino/Arduino#6941]
On the LiquidCrystalDisplay tutorial webpage (https://www.arduino.cc/en/Tutorial/LiquidCrystalDisplay), in the "See Also" section, the hyperlink for "noDisplay()" is incorrectly pointing to the page for "noCursor()". It should be set to the correct page: https://www.arduino.cc/en/Reference/LiquidCrystalNoDisplay

**Comment by kengdahl** [comment]
Fixed
