### ISSUE TITLE
Incorrect hyperlink for noBlink() on LiquidCrystalBlink tutorial webpage 

### ISSUE THREAD

**Issue by bdr2** [arduino/Arduino#6942]
On the LiquidCrystalBlink tutorial webpage (https://www.arduino.cc/en/Tutorial/LiquidCrystalBlink), in the "See Also" section, the hyperlink for "noBlink()" is incorrectly pointing to the page for "blink()". It should be set to the correct page: https://www.arduino.cc/en/Reference/LiquidCrystalNoBlink

**Comment by kengdahl** [comment]
Fixed :)
