### ISSUE TITLE
[Library Manager] Request to add Microchip_RN487x library

### ISSUE THREAD

**Issue by EmbeddedMan** [arduino/Arduino#6943]
It's located at https://github.com/chipKIT32-libraries/Microchip_RN487x

An updated library for the Microchip RN487x BLE modules, compatible with chipKIT and other Arduino platforms.

**Comment by cmaglie** [comment]
A library with the same name already exists, https://github.com/SodaqMoja/Microchip_RN487x.git, you must rename your library (changing the library.properties and re-tagging the releases).

Anyway, It seems that you already forked from the library above, it will be better if you try to push your changes upstream.

**Comment by EmbeddedMan** [comment]
Agreed - I will try to get my changes accepted upstream before creating a renamed library. Thanks!
