### ISSUE TITLE
Forces the computer to restart

### ISSUE THREAD

**Issue by iclojano15** [arduino/Arduino#6953]
This takes 5 seconds to make the computer to go crazy and says it has to force restart because of a problem 
I checked the holes and everything but it won't stop its crashing can someone help me?

**Comment by per1234** [comment]
Please provide more details:
- Is the 5 seconds relative to starting the Arduino IDE or plugging the USB cable on your Arduino board in to the computer?
- Which version of the Arduino IDE are you using?
- Which operating system are you using?

**Comment by per1234** [comment]
@iclojano15 we're still waiting for more details from you regarding this issue. Are you still having this problem?

**Comment by per1234** [comment]
Closing due to lack of response. @iclojano15 if you can provide the requested information I'll be happy to reopen this.
