### ISSUE TITLE
[Library Manager] Please add WioLTEforArduino library

### ISSUE THREAD

**Issue by matsujirushi** [arduino/Arduino#6957]
Hello.

https://github.com/SeeedJP/WioLTEforArduino

I created a library to manage my board named WioLTEforArduino. (Arduino library for [Wio LTE](https://www.seeedstudio.com/Wio-LTE-US-Version-4G%2C-Cat.1%2C-GNSS%2C-JavaScript(Espruino)-Compatible-p-2957.html).)
Could you add this to a list of libraries?

Thanks.

**Comment by cmaglie** [comment]
Done!
