### ISSUE TITLE
[Library Manager] Please add GameControllersSTM32 library

### ISSUE THREAD

**Issue by arpruss** [arduino/Arduino#6958]
Please add the GameControllersSTM32 library (support for Nunchuck, Gamecube controller and PC game port for STM32F1/libmaple): https://github.com/arpruss/GameControllersSTM32

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by arpruss** [comment]
Oops, forgot. Done.

**Comment by cmaglie** [comment]
Done!
