### ISSUE TITLE
[Library Manager] Please add DMXUSB

### ISSUE THREAD

**Issue by DaAwesomeP** [arduino/Arduino#6963]
https://github.com/DaAwesomeP/dmxusb

Emulates an ENTTEC USB DMX device on any serial port

**Comment by cmaglie** [comment]
done!

**Comment by DaAwesomeP** [comment]
Thanks!

**Comment by Hotkidd** [comment]
@DaAwesomeP, may i know can we emulate the Arduino native port(which is a serial port) to be like a generic USB port (like keyboard) with dmxusb?
