### ISSUE TITLE
Iremote

### ISSUE THREAD

**Issue by Ronto55** [arduino/Arduino#6966]
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

Build-Optionen wurden verändert, alles wird neu kompiliert
C:\Users\admin\Documents\Arduino\Fernbedinung\Fernbedinung.ino:2:22: fatal error: IRremote.h: No such file or directory

 #include <IRremote.h>

                      ^

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board Arduino/Genuino Uno.

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

Irgend etwas will nicht funktionieren.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. It is not for providing support. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
