### ISSUE TITLE
[Library Manager] Non interrupting lighting library for single LEDS 

### ISSUE THREAD

**Issue by SethSenpai** [arduino/Arduino#6968]
https://github.com/SethSenpai/singleLEDLibrary

Please add this library. A non interrupting library for single LED lighting behaviour.

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by SethSenpai** [comment]
Whoops my bad. 
[https://github.com/SethSenpai/singleLEDLibrary/releases/tag/v1.0](https://github.com/SethSenpai/singleLEDLibrary/releases/tag/v1.0)

**Comment by cmaglie** [comment]
Done!
