### ISSUE TITLE
Library Manager: please add ESP32 HTTP Update

### ISSUE THREAD

**Issue by suculent** [arduino/Arduino#6971]
https://github.com/suculent/esp32-http-update

Thanks.

**Comment by per1234** [comment]
The `version` value in your library.properties file must match the release/tag version but yours does not:
https://github.com/suculent/esp32-http-update/blob/2.1.144/library.properties#L2
Please update the `version` value and then either redo the release or create a new release.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by suculent** [comment]
Thanks, fixed.

**Comment by per1234** [comment]
You change the version after the release so the version value in the release is still wrong: 
https://github.com/suculent/esp32-http-update/blob/2.1.144/library.properties#L2
You need to either redo the release or update the version again and then create a new release that matches the version.

**Comment by cmaglie** [comment]
Done!
