### ISSUE TITLE
Dead link on lilypad simple page

### ISSUE THREAD

**Issue by sterretje** [arduino/Arduino#6978]
I hope this is the correct section.

On the "lilypad simple" product page https://store.arduino.cc/lilypad-arduino-simple is a link that refers to http://lilypadarduino.org/?p=149 (first link under "need help?") which is 'dead'.

**Comment by per1234** [comment]
Here's the lilypadarduino.org page on the Wayback Machine:
http://web.archive.org/web/20161018192320/http://lilypadarduino.org/?p=149
There is also an arduino.cc page for the LilyPad boards, including the LilyPad Simple: https://www.arduino.cc/en/Guide/ArduinoLilyPad
but it has different content than the lilypadarduino.org page.

**Comment by q2dg** [comment]
Nowadays best information source for Lilypads is Sparkfun: https://www.sparkfun.com/lilypad_sewable_electronics

**Comment by kengdahl** [comment]
I have removed the link until other content is made to replace it.
