### ISSUE TITLE
[Library Manager] TFT LCD library for SPFD5408 chip

### ISSUE THREAD

**Issue by sadika9** [arduino/Arduino#6986]
github repo: https://github.com/sadika9/TFTLCD-SPFD5408

This is based on changes made by JoaoLopesF (https://github.com/JoaoLopesF/SPFD5408) to make SPFD5408 based displays to work with Adafruit TFT libary. I have ported JoaoLopesF's changes to newer version of Adafruit's TFT libray.

**Comment by cmaglie** [comment]
Done!
