### ISSUE TITLE
Arduino Lucky Shield schematics

### ISSUE THREAD

**Issue by army113** [arduino/Arduino#6989]
https://www.arduino.cc/en/Main/ArduinoLuckyShield
The eagle and pdf schematics on the product page are linked to the old arduino.org page which redirects you back to the arduino.cc page.
Thus the schematics are not accessible.

**Comment by q2dg** [comment]
In fact, this product doesn't appear on https://www.arduino.cc/en/Main/Products
Arduino, please, clarify your current catalog of real officially maintained boards/shields and deprecated ones.

**Comment by SimonePDA** [comment]
We are uploading the schematics and eagle files, making them available again in the product page.
