### ISSUE TITLE
Request to add KniwwelinoLib to Library Manager

### ISSUE THREAD

**Issue by lazyzero** [arduino/Arduino#6992]
Hello,
can you please add the library for for our Kniwwelino Board to the Library Manager?
URL to access the lib: https://github.com/LIST-LUXEMBOURG/KniwwelinoLib
more information on the Kniwwelino Board:
http://www.kniwwelino.lu

Kind regards 
Christian

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by lazyzero** [comment]
Hi, we made a release now.

**Comment by haarism19** [comment]
lazyzero can you help me out . I'm a newbie so I don't much, what does "create a release " mean ??? Do I have to include a license.txt file in my repository or just change the version in librabry.properties file. Have a look if possible at my library if you have time : 
https://github.com/haarism19/test_for_slab

**Comment by lazyzero** [comment]
Hi @haarism19 you can make a release for your repository on https://github.com/haarism19/test_for_slab/releases

**Comment by cmaglie** [comment]
Done!
