### ISSUE TITLE
Issue while using this SPI library in ECLIPSE  with DEBUG option(using SLOEBER plugin)

### ISSUE THREAD

**Issue by Meghadoot** [arduino/Arduino#6993]
When I tried to use this library for debugging  Arduino MEGA 2560 board using SLOEBER plugin in eclipse, it is giving errors as undefined SPDR,SPCR and SPSR.

**Comment by per1234** [comment]
This is the repository for the Arduino IDE, not Sloeber. If you can confirm a bug using the latest hourly or beta version of the Arduino IDE from:
https://www.arduino.cc/en/Main/Software
then please comment here and I'll reopen this. Otherwise you will need to report the issue elsewhere.
