### ISSUE TITLE
Request to add Slab to Library Manager

### ISSUE THREAD

**Issue by haarism19** [arduino/Arduino#6994]
Hello,
Can you please add the library for our Slab-32 Board to the Library Manager?
URL to access the lib: https://github.com/haarism19/test_for_slab
more information on the Slab-32 Board:
http://startoonlabs.com/Innovation/
Also, this is our test code we will update the repository right when we get the access to the Library Manager

Kind regards
Haaris

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by haarism19** [comment]
Done, also I wanted to delete this whole repository after its being tested and create a proper library for Slab-32 board. Can you guys delete it from the server ?

**Comment by haarislabs** [comment]
Done.

**Comment by haarism19** [comment]
Done

**Comment by per1234** [comment]
>Done, also I wanted to delete this whole repository after its being tested and create a proper library for Slab-32 board. Can you guys delete it from the server ?

Let's just wait until you have your finished library. It's just a big waste of time for us to add a do-nothing library and then have to delete it. I suspect you are actually wanting to implement Boards Manager installation for your 3rd party board and that has nothing to do with Library Manager and will be handled without any need for action from the Arduino team. As I recommended in your other issue (https://github.com/arduino/Arduino/issues/6997), please start a thread on the Arduino Forum and I'll help you out over there.

**Comment by haarislabs** [comment]
Thanks a lot sorry for being a newbie. I'm a student so I'm new to this so I sound a bit ignorant but I will make sure that next time I don't waste your time
