### ISSUE TITLE
Arduino Store pages won't load with "too many redirects" error

### ISSUE THREAD

**Issue by aigore** [arduino/Arduino#6995]
Hello, I'm writing here just because the store section of the official website of arduino seems broken.
I'm trying to trace an order but, as soon as I try to go to the section "view your orders" every browser I use gives me back "too many redirects".
I tried also erasing cookies and history.
Also trying to write to the store support gives back that error
Maybe from here I can reach someone that can figure out how to fix the store section.
Thanks
My best

----

EDIT by @per1234:
Forum threads on this topic:
- http://forum.arduino.cc/index.php?topic=515828
- http://forum.arduino.cc/index.php?topic=514974
- http://forum.arduino.cc/index.php?topic=515405

**Comment by aigore** [comment]
Hi, I jest reopened the issue because I closed it by accident.
Anyway the store today is working and I was able to track an order.
I leave it open so who should have a look to it is been aware of potential issues on the website.

**Comment by per1234** [comment]
Closing because there was a cluster of reports around the same few days, then nothing since, which leads me to believe the problem was resolved.
