### ISSUE TITLE
Add Wire Update to library manager

### ISSUE THREAD

**Issue by agdl** [arduino/Arduino#6996]
Please add my library to library manager
https://github.com/agdl/WireUpdate

It allows to update a sketch on samd based boards using I2C bus

**Comment by cmaglie** [comment]
The library has been added but you miss `sentence` and `url` fields in `library.properties`:

```
JOB 1247 - 2017/12/14 01:07:46 Scraping https://github.com/agdl/WireUpdate.git
JOB 1247 - 2017/12/14 01:07:48 Checking out tag: 1.0.0
JOB 1247 - 2017/12/14 01:07:48 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

please define them and re-tag the release, the library will be automatically published once done.
