### ISSUE TITLE
How to make my board accessible ???

### ISSUE THREAD

**Issue by haarism19** [arduino/Arduino#6997]
I wanted work with my custom board but how do I upload it into the arduino server.

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification

I went through this tutorial but I couldn't understand after creating the Folder structure in the github repository  how do I make it accessible to others ???

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
