### ISSUE TITLE
Add arduino-sht to Library Manager

### ISSUE THREAD

**Issue by dhasenfratz** [arduino/Arduino#6999]
Dear maintainers,

can you please add the arduino-sht library to the Library Manager?
https://github.com/Sensirion/arduino-sht

We support with the library a large set of our temperature and humidity sensors (www.sensirion.com).

Thanks.

**Comment by dhasenfratz** [comment]
@per1234 Thanks for your fix of the keywords.txt file. I merged your PR and created and new release.

**Comment by cmaglie** [comment]
Done!
