### ISSUE TITLE
Please add Mutila v1.1.1 library to the library manager

### ISSUE THREAD

**Issue by matthewg42** [arduino/Arduino#7000]
Hi,

This is my first attempt to get a library published in the library manager, so I hope I did it right! Links:
* [Github repo](https://github.com/matthewg42/Mutila)
* [Release 1.1.1 download](https://github.com/matthewg42/Mutila/releases/tag/v1.1.1)

Thanks,
-- 
Mouse

**Comment by cmaglie** [comment]
Done!

**Comment by matthewg42** [comment]
Thank you very much - I'm thrilled to have Mutila in the library manager!  :grin:
