### ISSUE TITLE
Bug character on LCD

### ISSUE THREAD

**Issue by lucasmad03** [arduino/Arduino#7001]
Hello, my LCD V4.0 starter kit does not want to display characters, only the colors are displayed. cordially (It's google trad)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
