### ISSUE TITLE
Library Manager not seeing latest ThingSpeak library release

### ISSUE THREAD

**Issue by jasontwinters** [arduino/Arduino#7012]
There has been a new release (1.3.1) of the [ThingSpeak Communication Libraries](https://github.com/mathworks/thingspeak-arduino/releases).  It went out on Dec 7, but it is not getting picked up by the library manager script.

A 1.3.1 tag was created for the release and the [library.properties](https://github.com/mathworks/thingspeak-arduino/blob/master/library.properties) file looks correct.

Any ideas what the problem could be?

**Comment by per1234** [comment]
The problem is that the `version` value in library.properties was updated after the point in the commit history that was tagged 1.3.1:
https://github.com/mathworks/thingspeak-arduino/blob/1.3.1/library.properties#L2

You will need to either redo the tag or bump the version and do a new tag.
