### ISSUE TITLE
RFE: move theme.txt from application folder on Mac

### ISSUE THREAD

**Issue by IoTMike** [arduino/Arduino#7013]
On the MacOS version, the Arduino UI "theme" file is stored inside the application container, e.g. Arduino/Java/lib/theme/theme.txt.  Request that the contents of this file be moved outside of the application (so it withstands new application versions), say to the ~/Library/Arduino15/preferences.txt file or just move the theme.txt to ~/Library/Arduino15 folder.  Thanks!

**Comment by per1234** [comment]
Fixed by https://github.com/arduino/Arduino/pull/7115 (thanks Mumfrey!).
