### ISSUE TITLE
New library: DHT library for ESP32

### ISSUE THREAD

**Issue by beegee-tokyo** [arduino/Arduino#7015]
If you like, please add new DHT temperature and humidity sensor library to your list. The library is optimized for Espressif ESP32 modules.
URL: https://github.com/beegee-tokyo/DHTesp

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by beegee-tokyo** [comment]
Done

**Comment by cmaglie** [comment]
Library added!
