### ISSUE TITLE
https://github.com/aceOfModernElectronis/Ananke-Arduino-library

### ISSUE THREAD

**Issue by sudheeraMadusankha** [arduino/Arduino#7021]
I've wrote a library to connect arduino development boards, Node MCU etc. to connect our own IOT platform. 
https://github.com/aceOfModernElectronis/Ananke-Arduino-library

**Comment by per1234** [comment]
Are you requesting that your library be added to the Library Manager index?

If so, you need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
