### ISSUE TITLE
[Library manager] Request to add AGirs to the library manager.

### ISSUE THREAD

**Issue by bengtmartensson** [arduino/Arduino#7028]
This is a request to add [AGirs](https://github.com/bengtmartensson/AGirs)  to the library manager. This is an infrared server that can be used on its own, and in conjunction with IrScrutinizer and Lirc. Strictly speaking, it is more of an application (contained in the exampes/Girs directory) than a library, but I see no better way.

**Comment by cmaglie** [comment]
Done!
