### ISSUE TITLE
isWhitespace / isSpace

### ISSUE THREAD

**Issue by 171231** [arduino/Arduino#7039]
in https://www.arduino.cc/reference/en/language/functions/characters/isspace/
isSpace() true by ASCII 9 and 32 (DEC).
in https://www.arduino.cc/reference/en/language/functions/characters/iswhitespace/ 
isWhitespace() true then ASCII-Code 9, 10, 11, 12, 13 and 32 (DEC) 
```

void setup()
{
  Serial.begin(9600); // Serial Init
  while (!Serial); // Wartet auf seriellen Monitor
}

void loop() 
{
  for (int thisChar = 0; thisChar < 128; thisChar++)
  {
    Serial.print("Char: \'");
    Serial.write(thisChar);
    Serial.print("\'  ASCII: ");
    Serial.print(thisChar);
    Serial.print("  ");
    if (isSpace(thisChar))            { Serial.print(", isSpace()"); }
    if (isWhitespace(thisChar))       { Serial.print(", isWhitespace()"); }
    Serial.println(".");
  }
  while(1);
}
```
This Code maen: isSpace(thisChar); is true by 9, 10,11, 12 13 32 (DEC) and maen isWhitespace(thisChar) is true by 9 and 32 (DEC)

The great Problem is trim()! 
What is wrong here?

Thanks!

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
