### ISSUE TITLE
USB port isn't detected

### ISSUE THREAD

**Issue by PARoby** [arduino/Arduino#7042]
I can't download my code from my mac to the Arduino UNO card, because I can't choose the right usb port. All I see is a bluetooth incoming port.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
