### ISSUE TITLE
Broadcast Bonjour/Rendezvous more often

### ISSUE THREAD

**Issue by dirkx** [arduino/Arduino#7046]
On mac - it may be an idea to broadcast the Bonjour/Rendezvous solicitation more often.

Perhaps every time the 'Tools' menu is opened.

That way we can be sure that the `Port' sub menu is populated after a (re)program.

**Comment by facchinm** [comment]
Hi @dirkx ,
would you mind testing IDE 1.9.0 beta? We merged the updated jmdns which should be MUCH  more reliable at discovery (and removal notification)

**Comment by per1234** [comment]
@dirkx did you ever get a chance to try out the beta build of the Arduino IDE? You can download it here:
https://www.arduino.cc/en/Main/Software#beta

**Comment by sandeepmistry** [comment]
I'm closing this for now due to lack of feedback. Please re-open with requested info if needed.
