### ISSUE TITLE
Error Uploading Code To Arduino Nano

### ISSUE THREAD

**Issue by AyudhN** [arduino/Arduino#7047]
The Error message shown is as follows:

Arduino: 1.6.5 (Windows 8.1), Board: "Arduino Nano, ATmega328"

Sketch uses 1,030 bytes (3%) of program storage space. Maximum is 30,720 bytes.

Global variables use 9 bytes (0%) of dynamic memory, leaving 2,039 bytes for local variables. Maximum is 2,048 bytes.

avrdude: ser_open(): can't open device "\\.\COM3": The semaphore timeout period has expired.

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

WARNING: Spurious .github folder in 'Adafruit Motor Shield library' library

WARNING: Spurious .github folder in 'Adafruit Motor Shield library' library

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
