### ISSUE TITLE
Tutorials - ADXL3xx Accelerometer

### ISSUE THREAD

**Issue by razwww** [arduino/Arduino#7054]
https://www.arduino.cc/en/Tutorial/ADXL3xx
Contains a mistake, probably after some rephrasing:  "communicate the acceleration to the a personal computer".

![adxl mistake](https://user-images.githubusercontent.com/8641203/34343591-f939c902-e9dd-11e7-8ad5-1d4e7260b228.PNG)

**Comment by kengdahl** [comment]
Fixed?
