### ISSUE TITLE
[Library Manager] Please add log4arduino library to Library Manager

### ISSUE THREAD

**Issue by jandelgado** [arduino/Arduino#7058]
https://github.com/jandelgado/log4arduino

thanks
jan

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jandelgado** [comment]
release created

**Comment by cmaglie** [comment]
Done!
