### ISSUE TITLE
stk500v2 bootloader should be buildable without extra tools [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#706]
This is [Issue 706](http://code.google.com/p/arduino/issues/detail?id=706) moved from a Google Code project.
Added by 2011-11-09T08:47:29.000Z by [wes...@gmail.com](http://code.google.com/u/103342639718054305536/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low

### Original description

The STK500v2 bootloader should get makefile hacks similar to those done for optiboot, so that the bootloader can be compiled with the tools that come with the Arduino IDE.

**Comment by facchinm** [comment]
STK500v2 can be compiled using the provided makefile (just tested), closing as solved
