### ISSUE TITLE
Translation of tutorial pages?

### ISSUE THREAD

**Issue by sebuls** [arduino/Arduino#7062]
Hello.
I read
https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay
and I found that this article is very Good.
How can make a page, for example
https://www.arduino.cc/ko/Tutorial/BlinkWithoutDelay
and write a translation of
https://www.arduino.cc/en/Tutorial/BlinkWithoutDelay
into that URL ?

https://forum.arduino.cc/index.php?topic=517516.0

**Comment by SimonePDA** [comment]
We are working on a solution to allow the translation of our Tutorials into other languages. You will be informed when everything is ready.

Thanks for your support to the community
