### ISSUE TITLE
Unable to launch IDE on Mac Yosemite after trying IDEonRecentMacOSX prescription

### ISSUE THREAD

**Issue by dawajo48** [arduino/Arduino#7068]
Loaded Java 8 Update 151 (jre-8u151-macosx-x64.dmg) but still got "Unable to load Java Runtime Environment" error

**Comment by facchinm** [comment]
Any recent Arduino version should run on OSX Yosemite (10.10) without any problem. Java is being bundled with the IDE since 1.6.1 (at least). Which IDE version are you trying to run? Could you try 1.8.5 and report if it works?

**Comment by dawajo48** [comment]
Martino,

Thanks for getting back to me.  I just upgraded to Sierra OS 10.12.6 and
the problem disappeared....

Dave

**Comment by facchinm** [comment]
Ok, glad it worked for you. Closing the issue, please reopen if the problem appears again.
