### ISSUE TITLE
LTC2633 library for Arduino

### ISSUE THREAD

**Issue by TamojitSaha** [arduino/Arduino#7069]
[Here](https://github.com/TamojitSaha/LTC2633) is the repository link of library for LTC2633
[Here](https://github.com/TamojitSaha/LTC2633/releases/tag/0.1.0) goes the release of the library
Please add to Arduino Library Manager.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/7063

Create one issue per topic only please @TamojitSaha.
