### ISSUE TITLE
There is need of a terminal button in the Arduino IDE

### ISSUE THREAD

**Issue by Youngwolf1810** [arduino/Arduino#7080]
There is absolute need of a terminal button in the arduino IDE

EDIT by @per1234 2018-01-04:
Also posted at https://forum.arduino.cc/index.php?topic=519163

**Comment by PaulStoffregen** [comment]
![serialmon](https://user-images.githubusercontent.com/965463/34578439-ca031770-f139-11e7-8167-0aeaf3d04fb2.png)

**Comment by facchinm** [comment]
Closing as .... solved :wink: ?
