### ISSUE TITLE
Link to FLIP software needs to be updated

### ISSUE THREAD

**Issue by agamagtdM10102148** [arduino/Arduino#7081]
the link on https://www.arduino.cc/en/Hacking/DFUProgramming8U2: 
Download a DFU Programmer
This is the software that will update the code 
Windows: Download Atmel's flip programmer from here......

Where "here" should be navigated to the following (Because Atmel had been bought by Microchip):
http://www.microchip.com/developmenttools/productdetails.aspx?partno=flip

**Comment by krgoodwin** [comment]
I just went through the process of updating the MEGA8U2 on an Uno with Windows 7 and the version of FLIP hosted on microchips website does not include drivers for Arduino Uno DFU nor does it support AT90USB82 at all form what I can tell.

I ended up using dfu programmer 0.7.2 which included the correct drivers. I wouldn't bother updating the link to a program that doesn't work but instead update the page to a process that works.

(https://forum.arduino.cc/index.php?topic=522536.0)

https://sourceforge.net/projects/dfu-programmer/files/dfu-programmer/0.7.2/

**Comment by william-s-owen** [comment]
It appears that they have, for windows, version 2.4.6 only.

**Comment by krgoodwin** [comment]
There are multiple references (forums posts, videos) to Windows FLIP 3.4.x from a couple years ago. It looks like Microchip is hosting the old 2.4.6 version which doesn't include the necessary drivers.

**Comment by william-s-owen** [comment]
Looks like they put up 3.4.7 for windows on http://www.microchip.com/developmenttools/productdetails.aspx?partno=flip

**Comment by krgoodwin** [comment]
Wow, I was not expecting them to actually do anything helpful like that. Looks like my previous comments can be disregarded. Just need a link update on the original page now.

**Comment by kengdahl** [comment]
Fixed
