### ISSUE TITLE
Arduino zero guide improvements

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/Arduino#7085]
The page https://www.arduino.cc/en/Guide/ArduinoZero can be improved:
 - It now features a link to the https://create.arduino.cc/projecthub/monica/control-an-arduino-zero-using-node-js-84f877 project, along with a small animation showing an Arduino Zero connected to a LED *without a resistor*. This seems like a harmful example. I've also added a comment (and tried to add feedback) to that project, but until it is fixed, it should probably not be featured.
 - It has a "Differences from ATMEGA based boards" section which only talks about voltage. It would be good to also mention the I/O pin current limits there, since these are significantly lower than on an ATmega.

**Comment by matthijskooijman** [comment]
One more:
 - Under "Serial ports on the Zero" -> "Native" it shows an example: `while (!Serial) ;` I believe this should be `SerialUSB`, as the docs indicate `Serial` refers to the programming port, not the native port.

**Comment by kengdahl** [comment]
**Won't change (can't change):** The Zero outputs 3.3V and the drain on the board should fall within the acceptable range for a LED, however I agree that It is good practice to add a resistor. We can't do anything about the linked example, because it is  automatically retrieved from Project Hub.

**Changed:** "while (!Serial) ;" --> "while (!SerialUSB) ;"

**Added**: "If in doubt measure the IORef or the VCC pin, which supplies the voltage corresponding to the i/o of your board." Also added comparison to the Mega's 5V IORef.

**Comment by matthijskooijman** [comment]
> Won't change (can't change): The Zero outputs 3.3V and the drain on the board should fall within the acceptable range for a LED, however I agree that It is good practice to add a resistor. 

I'm not sure you understand the problem here. Perhaps the comment I added to that project can clarify:

 > The project movie and component list suggest using a LED without a resistor, which is bad for the LED and the Arduino. Either will likely break after some time.

> It is a myth that Arduino pins are "current limited": The current limits on the pins are maximums you cannot exceed without risk for pin damage. It is also a myth that "pin 13 already has a resistor", since that resistor is hidden behind an opamp and not in series with the pin 13 line, so it does not protect an external led.

> We can't do anything about the linked example, because it is automatically retrieved from Project Hub.

I guess you could *not* feature it on this page? Or does it automatically pick some arbitrary project based on the board name or something? That would be silly, for exactly this reason.

I also believe you have not addressed my concerns about I/O pin current limits, you only added more info on voltages?

**Comment by kengdahl** [comment]
@matthijskooijman Take a look now.

**Comment by matthijskooijman** [comment]
Yeah, looks good wrt the current limits, thanks! Some minor remarks:
 - You changed "Current out of a GND pin" (from the datasheet) to "Current into a GND pin". Was that intentional? It changes the meaning, since the current limit *into* a GND pin is probably 0 or something similar (and that should never happen anyway).
 - You typed "se" instead of "see" in "For more information se page 936 in this document."
 - I would also mention something about the connection between clusters and VDD/GND pins. Perhaps: "For more information about what pins belong to what cluster, and what VDD/GND pins they draw power from, see page 936 in this document."

**Comment by kengdahl** [comment]
Fixed.

**Comment by matthijskooijman** [comment]
I don't see any changes yet, I guess there's some caching. I'll try to remember to check again later.

**Comment by matthijskooijman** [comment]
Looks good, thanks!
