### ISSUE TITLE
IDE crashed before reaching the editor

### ISSUE THREAD

**Issue by Aventedor** [arduino/Arduino#7086]
My arduino ide is not opening,the start window just splashes and went off.I t neither shows any error nor any other issue.I have uninstalled and reinstalled various versions of it but it is of no use.Though in same pc(64 bit windows 8.1)it was running fine few months ago.can anyone help me with this problem?

**Comment by facchinm** [comment]
Hi @Aventedor ,
could you try running `arduino_debug.exe` (for the same folder where you installed the IDE) and report here all the output? Thanks

**Comment by per1234** [comment]
Closing due to lack of response. @Aventedor if you're still having the problem and can provide the requested information I'll be happy to reopen the issue.
