### ISSUE TITLE
Update release version of arm-none-eabi-gcc

### ISSUE THREAD

**Issue by xloem** [arduino/Arduino#7088]
Arduino currently provides arm-none-eabi-gcc tool version 4.8.3 .

This version is very old and is no longer distributed at arm.com .

If the compiler were upgraded to at least version 6, then modern c++ tools like boost::hana could be used.

**Comment by facchinm** [comment]
Hi @xloem ,
would you mind moving the issue to https://github.com/arduino/ArduinoCore-samd/issues ?
However, I agree, we should ship a newer toolchain but it's a big effort since it needs to be validated again
