### ISSUE TITLE
Upload issues: Mac OS X 10.4.11 with Arduino 0022 IDE and UNO board [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#709]
This is [Issue 709](http://code.google.com/p/arduino/issues/detail?id=709) moved from a Google Code project.
Added by 2011-11-10T04:06:37.000Z by [ga...@jacqcad.com](http://code.google.com/u/114738159194458171574/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Any attempt to upload a sketch fails with stk500_getsynch(0) not in synch: resp=0x86 followed by stk500_rcv(0): programmer is not responding
**2.**
**3.**

**What is the expected output? What do you see instead?**
Expected success, got failure

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
software 0022, Mac OS X 10.4.11 on G4 CPU, board UNO

**Please provide any additional information below.**
Following work-around appears to be reliable: hold down Reset button on UNO, start upload, keep holding Reset until first LED flash then release quickly.  Others have suggested waiting just until "binary sketch size" message appears, but that has not been reliable here. Continuing to hold until first flash (seems to be L LED, quickly followed by Rx/Tx LEDS) seems more reliable.
Major show-stopper for new users...

**Comment by ffissore** [comment]
Mac 10.4 is no longer supported
