### ISSUE TITLE
New Library for Arduino

### ISSUE THREAD

**Issue by stejsoftware** [arduino/Arduino#7091]
https://github.com/stejsoftware/ArduinoLibrary

**Comment by stejsoftware** [comment]
https://github.com/stejsoftware/ArduinoLibrary/releases/tag/v2.1.1

**Comment by cmaglie** [comment]
The name `ArduinoLibrary` is a bit too generic... also the description `A collection of objects and utilities for the Arduino` doesn't tell anything I guess that nobody is going to find your library among the other 1600+ libraries with a more meaningful description.

Please choose a name that uniquely identifies your toolkit, and don't use the word `Arduino` in it, it is superflous and looks like a library made by Arduino (the company).

**Comment by Rotzbua** [comment]
And a license is missing...
