### ISSUE TITLE
Timer lib function every is not an interrupt

### ISSUE THREAD

**Issue by JanvdZanden** [arduino/Arduino#7092]
In fact every() of the Timer lib is not an interrupt. It is a hook from the mainloop done by update.
I was very disappointed when I discovered this.

This implies that it is impossible to fire ISR-s at exactly the repeat time of the timer0, which the documentation suggests. It is only fired when the mainloop comes to update() and the time in ms. has gone. And if you want a repeated interrupt, it will never be faster than the mainloop.

So please correct the documentation!!!

I looked for an easy interrupt that is really connected with the 1 ms timer of millis(). So that my ISR really executes in interrupt mode. Is there a solution for that?

**Comment by per1234** [comment]
Lacking details, I'll have to assume you're talking about https://playground.arduino.cc/Code/Timer.

The Arduino Playground is a publicly editable wiki. The Arduino community is responsible for the content of the Playground so it is not appropriate to create issue reports about it in this repository.  You are welcome to edit the Playground as you see fit. When you go to edit you will encounter a password page but that's just to prevent spam, the password is pre-filled. If you are unsure of how to fix an issue you find on the Playground or just want to discuss planned work with the community feel free to post on the [Arduino Forum.](https://forum.arduino.cc/index.php?board=21.0).
