### ISSUE TITLE
[Library] GEM 💎 - Good Enough Menu

### ISSUE THREAD

**Issue by Spirik** [arduino/Arduino#7093]
Hi everyone!

I want to contribute just another library for creation of graphic multi-level menu. It's good enough for me, so might as well be useful to somebody else=) Features editable menu items and option selects. User-defined callback function can be specified to invoke when menu item is saved. Supports buttons that can invoke user-defined actions.

https://github.com/Spirik/GEM

All complete with the README, annotated examples and [wiki](https://github.com/Spirik/GEM/wiki).

![GEM structure](https://github.com/Spirik/GEM/wiki/images/party-hard-lcd_full-demo_p12_640x360_256c_mask.gif)

**Comment by cmaglie** [comment]
Done!
