### ISSUE TITLE
PCA9505/06 Library add to library manager

### ISSUE THREAD

**Issue by tofuman0** [arduino/Arduino#7112]
Library for PCA9505/06 40bit IO Expander

https://github.com/tofuman0/PCA9505_06

Thanks.

**Comment by tofuman0** [comment]
Sorry about that. Updated.

Thanks.

**Comment by per1234** [comment]
The `version` value in your library.properties file must match the release version, and also must be semver compliant.

Please comment when you have fixed this issue so we can proceed with adding your library to Library Manager.

**Comment by tofuman0** [comment]
Okay I've re-released with the tag v1.0.0 again.

**Comment by cmaglie** [comment]
Done!
