### ISSUE TITLE
Bluetooth Connection Issue

### ISSUE THREAD

**Issue by RianHeiges** [arduino/Arduino#7117]
I have looked at at least 15 YouTube videos/forums discussing Bluetooth errors but none have helped with my specific issue, the LED when connected to my android, flashes twice fast then stops for a bit then repeats over and over again. It will not receive or transmit anything from here, I have RX to TX and TX to RX. Does anyone know about how to fix this? Please help! This is my last resort.

PS: I have H-05 model Bluetooth and Arduino UNO. I wish I could upload video but its not supported :(

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
