### ISSUE TITLE
esp8266andarduinouno

### ISSUE THREAD

**Issue by hossamassad** [arduino/Arduino#7118]
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

Build options changed, rebuilding all
In file included from C:\Users\Hossam Assad\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiSTA.h:28:0,

                 from C:\Users\Hossam Assad\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:34,

                 from C:\Users\Hossam Assad\Documents\Arduino\sketch_jan13a\sketch_jan13a.ino:1:

C:\Users\Hossam Assad\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiGeneric.h:27:22: fatal error: functional: No such file or directory

 #include <functional>

                      ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
