### ISSUE TITLE
[Library Manager] Add Plaquette library to the library manager

### ISSUE THREAD

**Issue by sofian** [arduino/Arduino#7121]
Plaquette is a new Arduino library that turns your Arduino environment into an object-oriented environment.

First release now available tagged "v0.1"

https://github.com/SofaPirate/Plaquette

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by sofian** [comment]
I am sorry, I created the tag locally but did not push it properly.
Just pushed it as "v0.1" tag now: https://github.com/SofaPirate/Plaquette/tree/v0.1

**Comment by cmaglie** [comment]
Done!
