### ISSUE TITLE
[Library Manager] Add VirtualDelay library to the library manager

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#7123]
https://github.com/avandalen/VirtualDelay
The library is used many times and is stable.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by avandalen** [comment]
Thank for your help. I have added the release v.1.0.3

**Comment by cmaglie** [comment]
Done!
