### ISSUE TITLE
[Library Manager] Add OctoPrintAPI library to the library manager

### ISSUE THREAD

**Issue by chunkysteveo** [arduino/Arduino#7126]
Hello, please can we add OctoPrintAPI library to the Arduino Library Manager:

https://github.com/chunkysteveo/OctoPrintAPI

Thanks,

Steve

**Comment by per1234** [comment]
The `version` value in library.properties at the time of the release/tag must match the release version. The `version` value in your 1.0.2 release remains at 1.0.1.

**Comment by chunkysteveo** [comment]
Correction in the library.properties file to the latest patch, and keyword file updated to match the example format and style.

**Comment by cmaglie** [comment]
Done!
