### ISSUE TITLE
Resizing font to a very tiny value causes Java to crash the IDE

### ISSUE THREAD

**Issue by mohammedzero43** [arduino/Arduino#7128]
I was reducing my font size by (Scrolling down + CTRL) and suddenly a java error appeared in my "Console Box" when I reached to a very tiny size, then I closed the IDE, but it didn't show the GUI and crashed immediately when reopened it.

**Comment by facchinm** [comment]
Hi @mohammedzero43, the issue was solve with IDE 1.8.5 (see  #6689).
Closing as duplicate.
