### ISSUE TITLE
Please add Switch library to Library Manager

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#7131]
https://github.com/avandalen/Switch

This library is used for years now and is stable.
Supports also long press and double clicks.

**Comment by avandalen** [comment]
Dear Per
Thank you, but I can't find it at the lib manager. Maybe something get wrong?

**Comment by per1234** [comment]
Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
Done
