### ISSUE TITLE
Kindly add "AIS_NB_BC95" Library to Library manager Arduino IDE

### ISSUE THREAD

**Issue by AIS-DeviceInnovation** [arduino/Arduino#7134]
github url : https://github.com/AIS-DeviceInnovation/AIS_NB_BC95

We are AIS (Mobile Network Operator & Digital Life Service Provider in Thailand : http://www.ais.co.th/en/) which developed and sell NB-IoT Shield (Narrow Band Internet of Thing Shield: https://www.facebook.com/AISBusinessSolutions/photos/pcb.835014549993484/835098493318423/?type=3&theater). Then we also develop the "AIS_NB_BC95" Library for easy using with our NB-IoT Shield. 

Kindly help adding our library to Library manager Arduino IDE.

Thank you in advanced.
Device Innovation Team / AIS

**Comment by cmaglie** [comment]
Done!
