### ISSUE TITLE
[Library] Add stblassitude/Adafruit_SSD1306_Wemos_OLED

### ISSUE THREAD

**Issue by stblassitude** [arduino/Arduino#7140]
https://github.com/stblassitude/Adafruit_SSD1306_Wemos_OLED

This library is based on the original [Adafruit library](https://github.com/adafruit/Adafruit_SSD1306) and adds the support for the Wemos D1 Mini OLED shields' [64x48 OLED display by causer](https://github.com/mcauser/Adafruit_SSD1306). This is also the default setting for this library, so there are no changes necessary to the .h file.

The reason for this simple repackaging is to be able to simply select this library from the library manager without manual patching of the library code.

**Comment by cmaglie** [comment]
Done
