### ISSUE TITLE
Please add log4Esp logging library to Library Manager

### ISSUE THREAD

**Issue by hunsalz** [arduino/Arduino#7141]
Please add https://github.com/hunsalz/log4Esp to Library Manager. log4Esp is a light-wight logging library for ESP8266.

Thanks in advance.

**Comment by per1234** [comment]
The `version` value in library.properties should match the release version. The `version` value in the 1.0.1 release is still set to 1.0.0:
https://github.com/hunsalz/log4Esp/blob/v1.0.1/library.properties#L2

This means you must update the `version` value, commit and then create the release or tag at or after that commit.

**Comment by hunsalz** [comment]
Fixed version value in library.properties and re-created tag v1.0.1

**Comment by cmaglie** [comment]
Done
