### ISSUE TITLE
[Library Manager] Adafruit Libraries

### ISSUE THREAD

**Issue by deanm1278** [arduino/Arduino#7142]
hello! Some Adafruit libraries to add to the manager:
- https://github.com/adafruit/Adafruit_VEML6070
- https://github.com/adafruit/Adafruit_CompositeVideo
- https://github.com/adafruit/Adafruit_AMRadio
- https://github.com/adafruit/Adafruit_FreeTouch
- https://github.com/adafruit/Adafruit_NeoPixel_ZeroDMA
- https://github.com/adafruit/Adafruit_NeoMatrix_ZeroDMA
- https://github.com/adafruit/Adafruit_ZeroTimer
- https://github.com/adafruit/Adafruit_DAP
thanks!

**Comment by cmaglie** [comment]
Done

**Comment by ladyada** [comment]
thanx!
