### ISSUE TITLE
parseDHCPResponse dont exit on endOption [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#715]
This is [Issue 715](http://code.google.com/p/arduino/issues/detail?id=715) moved from a Google Code project.
Added by 2011-11-17T07:37:03.000Z by [marius.r...@gmail.com](http://code.google.com/u/115116159264406895000/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

parseDHCPResponse do not exit if it read the endOption. If there is more then one dhcp replay, it continue parsing the next one.

--- Dhcp.cpp.orig	2011-11-17 08:34:56.000000000 +0100
+++ Dhcp.cpp	2011-11-17 08:35:34.000000000 +0100
@@ -253,6 +253,8 @@
             switch (_dhcpUdpSocket.read()) 
             {
                 case endOption :
+                    _dhcpUdpSocket.flush();
+                    return type;
                     break;
                     
                 case padOption :

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#22
