### ISSUE TITLE
USING WINUSB Driver with Arduino AS USB 

### ISSUE THREAD

**Issue by newpie18** [arduino/Arduino#7153]
Project Goal: Create a custom USBDevice. 
Name of device : "CapiaZ"
Board USed: Arduino MICRO
summary:
I was able to create a unique boatloader for my CapiaZ board, it has a specific VID & PID for it. and when you plug it to the pc the ARDUINO IDE will show the port and the name "CAPIAZ".
Then I used WINUSB.sys and WINUSB.inf to generate the driver. Successfully, I am able to install the driver and Device manager shows it as follwoing -which is the goal so far-: 
+ CapiaZ Device 
      CapiaZ-S01

I was able to use Arduino macro to be recognized as A USB Device, with a new VID and PID and a unique class. Then I used WINUSB to communicate , read and write from the usb device using Endpoints bulik in and Builk out to read and write. I have successfully accomplished creating a new boat

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This doesn't appear to be either. If you want to share your projects you are welcome to do so on the Arduino Forum.
