### ISSUE TITLE
Arduino IDE problem on a Mac

### ISSUE THREAD

**Issue by WPRob** [arduino/Arduino#7155]
Hi, I use either a MacBook Pro or an iMac and bot exhibit the same problem. 
The problem is when downloading/installing the IDE on either computer it flags an error saying that the Custom Libraries AND the Standard Libraries contain names which contain either a space or do not start with a letter.
I have located the folders and files in question and changed the names to start with a letter and/or do not contain a space. But now the error says that they are unknown to Arduino and are not loaded.
I can download to a  Windows machine OK but not the Macs.
If I partition my Mac and instal a fusion program and windows will it work?
I've had a few problems getting the iMac to do what I want it to do but that is outside the scope of this forum.
I imagine I am not the only person wanting to use a Mac.
Any ideas would be appreciated.
Thanks in advance

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we end up determining there is a bug in the IDE after investigating this on the forum I can always reopen this issue.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post the full text of all error messages and state which version of the Arduino IDE you're using.
