### ISSUE TITLE
Changed Arduino library name. Please update.

### ISSUE THREAD

**Issue by jaean123** [arduino/Arduino#7162]
https://github.com/jaean123/ArduinoBlue-library
I decided the permanent name for the library will be ArduinoBlue. 
The previous link to the library was: https://github.com/jaean123/ArduinoBLE-library
The new link with the updated name is: https://github.com/jaean123/ArduinoBlue-library

Please make the update to the library manager.

Thank you.

**Comment by cmaglie** [comment]
I've changed the name, BTW the name in the library.propertiese on tag `1.0` is still `ArduinoCommander`

https://github.com/jaean123/ArduinoBlue-library/blob/1.0/library.properties

```
JOB 1312 - 2018/01/31 13:50:58 Scraping https://github.com/jaean123/ArduinoBlue-library.git
JOB 1312 - 2018/01/31 13:51:00 Checking out tag: 1.0
JOB 1312 - 2018/01/31 13:51:00 Release ArduinoCommander:1.0.0 has wrong library name, should be ArduinoBlue
```

you may probably want to remove the tag `1.0` and redo-it on master.
Once done the library will be automatically published by our indexer (that should happen within an hour), no need to comment further.
