### ISSUE TITLE
New BlueDot Library for Arduino - BME280+TSL2591

### ISSUE THREAD

**Issue by BlueDot-Arduino** [arduino/Arduino#7164]
Could you please add the BlueDot_BME280_TSL2591 library to the Library Manager?
https://github.com/BlueDot-Arduino/BlueDot_BME280_TSL2591

Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by BlueDot-Arduino** [comment]
Sorry, forgot to create the release. 
Just created the public release version.

**Comment by cmaglie** [comment]
The name `BlueDot BME280+TSL2591 Library` is not allowed because it contains the `+` character.

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

Please change the name written in the `library.properties` to `BlueDot BME280 TSL2591` (no need to add `Library` there, it's implicit), commit & push, and redo the release.

**Comment by BlueDot-Arduino** [comment]
I changed the library name, created a new release and updated the README file. I hope now is everything right...

**Comment by per1234** [comment]
You didn't update the `version` value in your library.properties file before creating the release. So the release version is V1.0.1 but the `version` value is set to 1.0.0:
https://github.com/BlueDot-Arduino/BlueDot_BME280_TSL2591/blob/V1.0.1/library.properties#L2

**Comment by BlueDot-Arduino** [comment]
Hi! okay, I created a new release version (V1.0.3) and now it matches the version value. Did I miss anything? :)

**Comment by cmaglie** [comment]
Done!
