### ISSUE TITLE
[Library Manager] ArduinoSensors library

### ISSUE THREAD

**Issue by YuriiSalimov** [arduino/Arduino#7168]
Could you please add the ArduinoSensors library to the Library Manager?
https://github.com/YuriiSalimov/ArduinoSensors

Thanks!

**Comment by cmaglie** [comment]
There is already another library called `ArduinoSensor`.

Please chose another name possibly without the using the word `Arduino` (since you're using the Arduino IDE it is implicit that the library is for Arduino) and the word `Sensor` alone (because it's too generic and broad).

**Comment by YuriiSalimov** [comment]
Ok, I will format my lib, divide it into smaller libraries. And in future will add new issue. Thanks.

**Comment by cmaglie** [comment]
Please consider adding a prefix to each library, so your toolkit can be easily identified, for example:
`YS Relay`
`YS Thermistor`
etc. etc.
