### ISSUE TITLE
A completely outdated Troubleshooting page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7170]
https://www.arduino.cc/en/Main/Troubleshooting

Every bit of information on this page is completely outdated so it should be deleted. This is the 3rd Google search result I get for a search of `arduino troubleshooting`. 

Note this is a different page from https://www.arduino.cc/en/Guide/Troubleshooting, with completely different content.

Maybe https://www.arduino.cc/en/Main/Troubleshooting could be made to redirect to https://www.arduino.cc/en/Guide/Troubleshooting or just replace the content of https://www.arduino.cc/en/Main/Troubleshooting with a link to https://www.arduino.cc/en/Guide/Troubleshooting if you don't want to remove that page altogether.

**Comment by kengdahl** [comment]
I replaced the content of: https://www.arduino.cc/en/Main/Troubleshooting
With the content of: https://www.arduino.cc/en/Guide/Troubleshooting

**Comment by per1234** [comment]
https://www.arduino.cc/en/Main/Troubleshooting still contains the same completely outdated content. I don't know whether the update never went through or if the change ended up being reverted later. It would be best if the page was redirected to https://www.arduino.cc/en/Guide/Troubleshooting.

**Comment by animeshsrivastava24** [comment]
@per1234  Is this issue assigned to someone? I'll be happy to document it and get reviewed.

**Comment by per1234** [comment]
@animeshsrivastava24 the removal of the obsolete page and redirect of that URL to the more modern troubleshooting page can only be done by someone with edit access to arduino.cc so there is no way you can assist with this issue.

**Comment by animeshsrivastava24** [comment]
@per1234 Thank you so much for the reply. Sure, I can understand.

**Comment by kengdahl** [comment]
@animeshsrivastava24 I updated the page again. It should be good now.
