### ISSUE TITLE
Add new Temperature_LM75_Derived library

### ISSUE THREAD

**Issue by jeremycole** [arduino/Arduino#7171]
Please add the following new library:

https://github.com/jeremycole/Temperature_LM75_Derived

**Comment by cmaglie** [comment]
Hi @jeremycole,

the name `I²C Temperature Sensors derived from the LM75` contains the UTF-8 char `²`, even if not explicitly denied it may cause some troubles, would you like to replace the `²` with a `2`?

**Comment by jeremycole** [comment]
Hi @cmaglie! Not a problem at all. Replaced I²C with I2C in the name and bumped the version.

**Comment by jeremycole** [comment]
FYI, we have now tagged version 1.0.0 of this library, after receiving, building breakout boards for, and testing it with 14 additional LM75-derived temperature sensors!

![LM75-derived sensors tested](https://i.imgur.com/NQUe5YO.jpg)

**Comment by cmaglie** [comment]
Done!
