### ISSUE TITLE
Typos on "Installing Additional Arduino Libraries" page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7172]
https://www.arduino.cc/en/Guide/Libraries

### Using the Library Manager section:

Change:
>Then the library manager will open and you will find a list of libraries

to:
>Then the **Library Manager** will open and you will find a list of libraries

----
Change:
>Scroll the list to find it, then select the version of the library you want to install.

to:
>Scroll the list to find it, **click on it,** then select the version of the library you want to install.

(Version menu and Install button don't appear until you click on the library entry)

----
Change:
>Finally click on install

to:
>Finally click on **Install**

----
Change:
>You can now find the new library available in the _Include Library_ menu

to:
>You can now find the new library available in the **_Sketch > Include Library_** menu

----
Change:
>If you want to add your own library open a new issue on github.

to:
>If you want to add your own library to Library Manager, **follow [these instructions](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)**.

(it is very common for Library Manager inclusion requests to not initially meet all the requirements so it's best for people to start from the FAQ, which then links to the issue tracker)

----
### Importing a .zip Library section

Change:
>In the Arduino IDE, navigate to _Sketch > Include Library_. At the top of the drop down list, select the option to "Add .ZIP Library''. 

to:
>In the Arduino IDE, navigate to **_Sketch > Include Library > Add .ZIP Library..._**

----
Change:
>Return to the _Sketch > Import Library_ menu.

to:
>Return to the _**Sketch > Include Library**_ menu.

----
Change:
>NB: the Library will be available to use in sketches, but examples for the library will not be exposed in the File > Examples until after the IDE has restarted.

to:
>NB: the Library will be available to use in sketches, but **with older IDE versions** examples for the library will not be exposed in the File > Examples until after the IDE has restarted.

(The Arduino IDE now updates the File > Examples menu when you do an **Add .ZIP Library**. I don't know exactly which version this started with and don't have access to my full array of IDE versions right now to check.)

----
### Manual installation section
Change:
>Arduino libraries are managed in three different places: inside the IDE installation folder, inside the core folder and in the libraries folder inside your sketchbook. The location of your sketchbook defaults to “..\<you>\DOCUMENTS\Arduino” on Windows machines. The path is clearly shown in the Preferences panel. If you want to see where the sketchbook defaults open Preferences under File. 

to:
>**You can find or change the location of your sketchbook folder at _File > Preferences > Sketchbook location_.**

(This is a lot of unnecessary information at the start of the instructions that will only cause confusion. The explanation of the various library folder locations is more appropriate in the library override discussion, which comes after the basic manual library installation instructions.)

----
Change:
>Start the Arduino Software (IDE), goto Sketch and the Include Library.

to:
>Start the Arduino Software (IDE), **go to** **_Sketch > Include Library_**.

----
Change:
>Verify that the library you just added is available in the list, after the core libs. 

to:
> Verify that the library you just added is available in the list.

(The term "core libs" is not clear. It's easiest for the user just to look for the installed library on the list. The menu section headings will provide any explanation needed.)

----
Change:
>Please note: the way libraries are chosen

to:
>Please note: **Arduino libraries are managed in three different places: inside the IDE installation folder, inside the core folder and in the libraries folder inside your sketchbook. T**he way libraries are chosen

----
Change:
>This is why we assume that your libraries are properly put in your sketchbook folder and therefore they are not deleted during the Arduino Software (IDE) update process. 

to:
>This is why we **recommend that you only install libraries to the sketchbook folder so they are not deleted during the Arduino IDE** update process.

**Comment by kengdahl** [comment]
Implemented you suggestions
