### ISSUE TITLE
new lib for hcsr04 sensor

### ISSUE THREAD

**Issue by gamgine** [arduino/Arduino#7174]
Please add the hcsr04sensor library to the library manager list. Thanks.
https://github.com/gamgine/Arduino-lib-HCSR04
https://github.com/gamgine/Arduino-lib-HCSR04/releases (version 1.0.0) next after test (1.1.0)
https://github.com/gamgine/Arduino-lib-HCSR04/blob/master/README.md

**Comment by cmaglie** [comment]
There is already another library called `HCSR04`, please choose another name.
Remeber to update the `library.properties` to reflect the new name and re-do the release tag **after** the update to `library.properties` is commited and pushed.

**Comment by gamgine** [comment]
I'm coming to find nothing of that name in the libraries manager.
but name "ultrasonic sensor" is available?

**Comment by cmaglie** [comment]
`HCSR04` is taken by https://github.com/Martinsos/arduino-lib-hc-sr04.git but for some reason is not being published, will look at this separately.

About your library, `Ultrasonic Sensor` is available, but I will use `HCSR04` in the name, maybe prefixed with something else like `gamgine_HCSR04`... anyway, up to you.

**Comment by gamgine** [comment]
hi sorry for long time
I chose to use `hcsr04 ultrasonic sensor` if is available for name

**Comment by cmaglie** [comment]
Ok, please:

- update name and version in your `library.properties`
- commit & push
- make a new release / git tag

**Comment by gamgine** [comment]
ok it's done
library.properties , release (1.0.0) and readme
https://github.com/gamgine/HCSR04-ultrasonic-sensor-lib

**Comment by cmaglie** [comment]
Done!

**Comment by gamgine** [comment]
thanks
