### ISSUE TITLE
mouse cursor in editor is not text cursor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#718]
This is [Issue 718](http://code.google.com/p/arduino/issues/detail?id=718) moved from a Google Code project.
Added by 2011-11-20T06:19:54.000Z by [frank.zhao.main@gmail.com](http://code.google.com/u/frank.zhao.main@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

Arduino 1.0 RC2 on Windows 7 Pro, 64-bit

When my mouse is over the editor window text area, the cursor does not turn into the "I" that I am used to, it remains a "pointer".

**Comment by ffissore** [comment]
Latest hourly works as expected
