### ISSUE TITLE
add AceButton Library to Library Manager

### ISSUE THREAD

**Issue by bxparks** [arduino/Arduino#7185]
Please add:
https://github.com/bxparks/AceButton
to the Library Manager. Thank you.

"An Adjustable Compact Event-driven (ACE) button library that handles debouncing and dispatches events to a user-defined event handler.
Supported events are Pressed, Released, Clicked, DoubleClicked, LongPressed, and RepeatPressed. Timing parameters, event activation, and event suppression can be configured at compile-time or run-time. Optimized for compact memory consumption. Unit tested using ArduinoUnit."

**Comment by cmaglie** [comment]
Done!
