### ISSUE TITLE
[Library Manager] frt library

### ISSUE THREAD

**Issue by Floessie** [arduino/Arduino#7186]
Hello,

Could you please add the `frt` library to the Library Manager?

https://github.com/Floessie/frt

> `frt` is an object-oriented wrapper around FreeRTOS tasks, mutexes, semaphores, and queues. It provides the basic tools for a clean multithreading approach based on the [Arduino_FreeRTOS_Library](https://github.com/feilipu/Arduino_FreeRTOS_Library) with focus on static allocation, so you know your SRAM demands at compile time.

Thanks,
Flössie

**Comment by cmaglie** [comment]
Done!

**Comment by Floessie** [comment]
Great! Thanks!
