### ISSUE TITLE
Arduino Mega 2460 and Arduino USB shield

### ISSUE THREAD

**Issue by klyles3** [arduino/Arduino#7187]
So I’m very new and need to be able to write to USB. I’m a M.E. Student and need it for senior project. I know it has a long history of not being able to do it. Is this correct?

**Comment by PaulStoffregen** [comment]
You're asking in the wrong place.  The forum is the proper place to ask for help.

https://forum.arduino.cc/

This place is only for reporting specific issues/bugs/defects with the software.

**Comment by klyles3** [comment]
Sorry and thank you.
