### ISSUE TITLE
cannot decrease indent on tab [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#719]
This is [Issue 719](http://code.google.com/p/arduino/issues/detail?id=719) moved from a Google Code project.
Added by 2011-11-20T06:22:59.000Z by [frank.zhao.main@gmail.com](http://code.google.com/u/frank.zhao.main@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Arduino 1.0 RC2 on Windows 7 Pro 64-bit

If I open a file with some lines that used tabs instead of spaces, I cannot highlight those lines and use the "decrease indent" feature on them.

**Comment by Chris--A** [comment]
This is fixed in 1.6.5 source.

On windows `Shift+Tab` decreases the indent of text containing actual tabs.

**Comment by ffissore** [comment]
Thanks @Chris--A
