### ISSUE TITLE
SD library 

### ISSUE THREAD

**Issue by pinemosquito** [arduino/Arduino#7191]
Hi Cristian: Novice to Arduino community so trying to educate myself. 

How come Arduino sketch make instantiation of class File 
eg File myFile 

but no one instantiate class SD...Should one instantiate SD mySD as well?

Secondly. In header file of SD.h I noticed that  card, volume and root are declared private, yet how come we can use outside of class in sketch? Why mix up private v. public declaration?

I love Arduino :-) but am puzzle

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
