### ISSUE TITLE
Modify USB profile to show serial port - Arduino MICO 

### ISSUE THREAD

**Issue by newpie18** [arduino/Arduino#7199]
I have two questions,
1 -I am using Arduino Micro (similar to Lenardo), i built my custom inf file, after installing the inf file the Serial comport disappear --> How can I make it not to disappear, like when using the Lenardo as a keyboard it show as HID and A serial port 

2- I know the Arduino Micrs Uses teh ATmega32U4 which have 6-7 endpoints 
but when I lconnect the arduino micro to tmy pc and usw usbview.exe it only show 3 endpoint 
0-> control
1-> bulkin
-> bulkout

how can i change the USBCORE.c  to show the rest of the endpoints

**Comment by per1234** [comment]
We've already been over this in your previous invalid issues (https://github.com/arduino/Arduino/issues/7153, https://github.com/arduino/Arduino/issues/7154). This is not the place to ask for help with your project. Appropriate places to ask for help have already been suggested. 

You will never get help from posting this sort of thing here so, in addition to being disrespectful, you're wasting your time. Please only submit issues here if you have discovered bug in the Arduino IDE that has not already been reported.
