### ISSUE TITLE
Re-word hotkeys for increase/decrease indentation [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#720]
This is [Issue 720](http://code.google.com/p/arduino/issues/detail?id=720) moved from a Google Code project.
Added by 2011-11-20T06:26:18.000Z by [frank.zhao.main@gmail.com](http://code.google.com/u/frank.zhao.main@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

Right now they are "Ctrl + Open Bracket" and "Ctrl + Close Bracket", it took me a few tries to figure out that you meant [ and ], why not just put [ and ] ?

Also why not just use tab and shift-tab like all other editors? tab works but shift-tab doesn't

**Comment by Chris--A** [comment]
Resolved (for Windows anyway)

Shift+Tab decreases the indent.

**Comment by ffissore** [comment]
:+1:
