### ISSUE TITLE
Error on nano board page - Tech Specs Tab

### ISSUE THREAD

**Issue by TkonekT** [arduino/Arduino#7201]
Error on "Tech Specs" Tab -> https://store.arduino.cc/arduino-nano

There is written : "Analog I/O pins" instead "Analog In Pins".
Sure, this pin can be DIGITAL I/O , there has never been a DAC ...

**Comment by kengdahl** [comment]
This is not an error. There is 8 I/O pins on the nano. I/O stands for *"in/out"*

**Comment by TkonekT** [comment]
I never see DAC on nano, as you want ...

**Comment by kengdahl** [comment]
You are correct. I'm sorry.

**Comment by kengdahl** [comment]
It's fixed now.

**Comment by per1234** [comment]
@kengdahl the problem is solved for the "Europe/Africa" version of the product page but it remains for the "America/Oceania/Asia" page.

**Comment by kengdahl** [comment]
@per1234 Should be fixed now :)
We have a sync between the pages but sometimes it just does not want to work.
