### ISSUE TITLE
Remove Library

### ISSUE THREAD

**Issue by uStepper** [arduino/Arduino#7204]
Hi!

We have split our egoShield library into two seperate parts, therefore we request to get the "old" library removed from the library manager. It is "egoShield" by ON Development IVS.
Thanks in advance!

![untitled](https://user-images.githubusercontent.com/16406355/36062353-146597ea-0e6b-11e8-9cb1-4fe544f3f22a.png)

Best regards,
Team uStepper

**Comment by cmaglie** [comment]
Done!
