### ISSUE TITLE
localization / Filipono translation

### ISSUE THREAD

**Issue by jcpuzs1** [arduino/Arduino#7209]
I would like to conrubute by means of localizing some or your file to Filipino.

**Comment by per1234** [comment]
Thanks for your interest in helping make Arduino accessible to more people!

Filipino localization work for the Arduino IDE is done here:
https://www.transifex.com/mbanzi/arduino-ide-15/language/fil/

A lot of work has been done on translating the [Arduino Language Reference](https://www.arduino.cc/reference/en/) pages lately but there is not currently a Filipino version. If that's something you'd be interested in participating in maybe someone from Arduino would be willing to consider providing that infrastructure.
