### ISSUE TITLE
cycle for after cycle for

### ISSUE THREAD

**Issue by DmitryAnton** [arduino/Arduino#7210]
IDE version 1.8.5. after compiling the code and loading it into any Board, the second cycle does not work. I tested cycle while, issue the same.
[Test-Holl.ino.zip](https://github.com/arduino/Arduino/files/1716214/Test-Holl.ino.zip)

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your error message, using code tags (`</>` button on the toolbar).
