### ISSUE TITLE
Library inclusion request: FlightSimSwitches

### ISSUE THREAD

**Issue by jbliesener** [arduino/Arduino#7212]
Please include the library at https://github.com/jbliesener/FlightSimSwitches with the library manager.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jbliesener** [comment]
Done.

**Comment by cmaglie** [comment]
Library added.

**Comment by jbliesener** [comment]
Hmmm, I've updated to version 1.0.5 on Github and tagged (released) it last night. Arduino library manager still shows 1.0.3 and does not update. I understand that the index is rebuilt every hour. Anything wrong with my setup?

**Comment by per1234** [comment]
@jbliesener I don't see anything wrong with your tag. There is another report of the same problem (https://github.com/arduino/Arduino/issues/7238) so I think the problem is with the indexer job. We'll track further progress on this topic in #7238.

**Comment by jbliesener** [comment]
Thank you!
