### ISSUE TITLE
Arduino IDE 1.8.5: unable to load java runtime environment

### ISSUE THREAD

**Issue by Loveboeing** [arduino/Arduino#7213]
<img width="453" alt="2018-02-13 11 12 20" src="https://user-images.githubusercontent.com/19518373/36144611-e239c9c6-10ae-11e8-840a-ace15428626d.png">

**Comment by facchinm** [comment]
@Loveboeing we need FAR more information to help debugging your issue. Which OSX version are you running? Do you have any particular Gatekeeper configuration?

**Comment by per1234** [comment]
@Loveboeing we're still waiting to hear back from you regarding facchinm's questions. Or if you have since resolved the problem please take a minute to leave a note here.

**Comment by per1234** [comment]
Closing due to lack of response.

@Loveboeing if you'll provide the requested information I'll be happy to re-open this issue.
