### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by pearlygurlee** [arduino/Arduino#7215]
Does anyone know if C is the only language that can be used to run Arduino? In college we were mainly thought in Java. We have been given a group project and the first part is to make an android app with 1Sheeld and Arduino. Any feedback would be appreciated!!!

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
