### ISSUE TITLE
Wire library documentation doesn't warn about buffer limit

### ISSUE THREAD

**Issue by technoblogy** [arduino/Arduino#7221]
I wasted a day trying to get the Arduino Wire library to work in an application, eventually discovering that because the implementation uses 32-byte buffers, attempting to send more than this in a single transmission fails silently.

It works now that I've broken my messages up into 32-byte chunks.

Please add a line to the documentation:

> Note that the Wire library imposes a maximum limit of 32 bytes for any transmission.

**Comment by SimonePDA** [comment]
Added the information about the 32 bytes limit into the documentation.

thank you :)
