### ISSUE TITLE
Not building Arduino IDE in Eclipse Java Oxygen

### ISSUE THREAD

**Issue by soloweyDev** [arduino/Arduino#7226]
Добрый день,
Скачал из Git версию Arduino IDE. Запускаю ее в Eclipse Java Oxygen. В консоле 3 ошибки. Две из них нехватка библиотек. Что делать?
![image](https://user-images.githubusercontent.com/23354576/36245082-5c8d5b48-123a-11e8-9593-a2e334353393.png)
Good afternoon,
I downloaded the version of Arduino IDE from Git. I run it in Eclipse Java Oxygen. There are 3 errors in console. Two of them lack of libraries. What to do?

**Comment by facchinm** [comment]
Hi @soloweyDev ,
the issue should be solved by https://github.com/arduino/Arduino/commit/fa2d18a1a55ecf6f22be6a88ca68b9075a2680d3 , which has been merged in ide-1.9.x-beta branch. Feel free to test it (by switching to beta or cherry-picking the patch) and report if it works

**Comment by soloweyDev** [comment]
Thanks, helped.
