### ISSUE TITLE
[Library Manager] Add new library request : Gamebuino Meta

### ISSUE THREAD

**Issue by Rodot** [arduino/Arduino#7231]
Please add https://github.com/Gamebuino/Gamebuino-Meta
Thanks ! 🎮 
Edit: changed repo owner from Rodot to Gamebuino

**Comment by cmaglie** [comment]
Looks like this library contains Windows executable files, this is not allowed by our policy

```
JOB 1339 - 2018/02/20 10:21:32 Scraping https://github.com/Gamebuino/Gamebuino-Meta.git
JOB 1339 - 2018/02/20 10:21:46 Checking out tag: 1.0.0
JOB 1339 - 2018/02/20 10:21:46 Error syncing library: *.exe files found, skipping
JOB 1339 - 2018/02/20 10:21:46 Checking out tag: 1.0.1
JOB 1339 - 2018/02/20 10:21:46 Error syncing library: *.exe files found, skipping
```

BTW the library has been added to the indexer, if you remove the .exe and publish a `1.0.2` version it will be published automatically by our crawler, within an hour.
I'm going ahead and close the issue, if you have more questions, please reopen and comment further.

**Comment by Rodot** [comment]
Thanks a lot ! 👍
