### ISSUE TITLE
The compilation time is too long. Temporary files of compilated core are not created.

### ISSUE THREAD

**Issue by Sterpa** [arduino/Arduino#7233]
Hardware:
Board:	M3Stack-Core-ESP32?
Core Installation/update date:	17.02.2018
IDE name:	Arduino IDE 1.8.6
Flash Frequency:	40Mhz
Upload Speed:	115200

Dear friends,
the compilation time is too long. Temporary files of the compiled core are not created.
Obviously, due to incorrect settings in the platform.txt, the compiled core archiving for ESP32 simply does not work!
The "Aggressive caching" option for the compiled core is enabled, but the archive folder is always empty!
Compiling any sketch takes more than 2 minutes - it's abnormal!

Typical compiletion, but folder C:\Users\mikha\AppData\Local\Temp\arduino_cache_559148\core is always empty! Never files in this folder... and 2 minutes every verify.

```
Archiving built core (caching) in: C:\Users\mikha\AppData\Local\Temp\arduino_cache_559148\core\core_espressif_esp32_m5stack-core-esp32_FlashMode_qio,FlashFreq_80,UploadSpeed_921600,DebugLevel_error_971a8c81649758eb73f9cbde4d14cb85.a
Sketch uses 693926 bytes (52%) of program storage space. Maximum is 1310720 bytes.
Global variables use 43364 bytes (14%) of dynamic memory, leaving 251548 bytes for local variables. Maximum is 294912 bytes.
```

What i do wrong?

----

EDIT @per1234 2018-02-16:
Also posted at https://forum.arduino.cc/index.php?topic=529677
EDIT by @per1234 2018-02-17:
Also posted at https://github.com/espressif/arduino-esp32/issues/1120

**Comment by facchinm** [comment]
This is a known "bug" with ESP32 `platform.txt`. The core archive needs to be called `core.a`, while ESP32 calls it `arduino.a` (see https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L73). The change has been requested more than a year ago but I can't find where :slightly_smiling_face: 
Just to be clear: the "aggressive core caching" feature only helps when you compile **for the first time** a sketch targeting a board you already have targeted. If every compilation (also the same file, with no modifications) takes more than 2 minutes, I'd take a closer look at your antivirus; some of them check every single file that gets created, so compiling anything becomes awfully slow.
Closing and keeping track on the ESP32 core tracker
