### ISSUE TITLE
[Library Manager] Indexer is not picking up new tags

### ISSUE THREAD

**Issue by henriksod** [arduino/Arduino#7238]
https://github.com/henriksod/Fabrik2DArduino

New tag 0.6.3

Thank you for your time

**Comment by per1234** [comment]
The Library Manager indexer job is supposed to run hourly and automatically pick up any new tag you create so there is no need to create an issue for every release. However, your tags have still not been picked up after 11 hours and I don't see anything wrong with the latest tag so I think something is wrong with the indexer. Further evidence of this is provided by https://github.com/arduino/Arduino/issues/7212#issuecomment-366524095

I'm sure @cmaglie will set it right soon.

**Comment by per1234** [comment]
Fabric2D 0.6.3 and FlightSimSwitches 1.0.5 are both now in the Library Manager index so it looks like this issue has been fixed.

**Comment by cmaglie** [comment]
It was a network problem on our side, thanks for your patience.
