### ISSUE TITLE
[Library Manager] New library: arduino-display-lcdkeypad

### ISSUE THREAD

**Issue by dniklaus** [arduino/Arduino#7244]
https://github.com/dniklaus/arduino-display-lcdkeypad

Generic Arduino LCD Keypad shield driver, supporting two HW types:

* 4 or 8 bit parallel data bus (LiquidCrystal driver)
* I2C bus and RGB color backlight (LiquidTWI2 driver)

**Comment by cmaglie** [comment]
done
