### ISSUE TITLE
Add uSevenSegmentLib to Library Manager

### ISSUE THREAD

**Issue by Naguissa** [arduino/Arduino#7248]
Hello,

Following Library Manager FAQ I open this issue to request adding uSevenSegmentLib library to Arduino repository.

Repository URL is: https://github.com/Naguissa/uSevenSegmentLib

This library depends on uTimerLib, which is still in inclusion process: https://github.com/arduino/Arduino/issues/7218

Thanks.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

**Comment by Naguissa** [comment]
Oh, my! What a basic mistake!

Fixed.

Thanks!

**Comment by cmaglie** [comment]
done

**Comment by Naguissa** [comment]
Thanks!
