### ISSUE TITLE
RSSI sometimes returns 0 when out of range

### ISSUE THREAD

**Issue by adamfowleruk** [arduino/Arduino#7250]
On the SparkFun ESP8266 Thing using the Arduino WiFi library. I've got code that checks for the presence of the two different WiFi networks around my home. It checks the RSSI value and connects to the best signal (highest, nearest 0, furthest from -100/-255).

One of the networks is on the other side of the house. Naturally, sometimes this isn't picked up. Sometimes it is but is given an RSSI of zero (for 'awesome connection') rather than something nearer -100/-255 for 'sucky connection'.

I'm presuming this is something in the WiFi code given that the standards instruct manufacturers to give poor connections a lower (larger negative) number for their RSSI.

I've had to workaround this by detecting an exactly 0 RSSI and replacing it in my code with -1000 so that my code doesn't try to connect to that network unless as a last resort.

You may want to check the WiFi library code to verify this is a code issue (likely) or an issue with the underlying hardware.

**Comment by per1234** [comment]
The library you're using with the ESP8266 is part of the [ESP8266 core for Arduino](https://github.com/esp8266/Arduino), which is a 3rd party project not part of the Arduino organization. There is an official Arduino library named WiFi but it is written for completely different hardware and is not in use for your ESP8266.
