### ISSUE TITLE
Cannot use KEYWORD3 color in keywords.txt file

### ISSUE THREAD

**Issue by jefersonla** [arduino/Arduino#7266]
I'm making a library and for some strange reason, in my keywords.txt if I want to use:

```
configura	KEYWORD3
algoritmo	KEYWORD3
```

Those words won't receive the same color of `setup` or `void` functions.
Any help on this?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
