### ISSUE TITLE
File.seek() in SD library--version 1.2.2 didn't work on M0 Pro using the IDE on macOS

### ISSUE THREAD

**Issue by egienvalue** [arduino/Arduino#7267]
Test platform: Arduino M0 Pro

I try to use the seek() function to move the write pointer to the head of a file, it didn't work. Then I change the version to 1.2.0, and it works with the same code.

**Comment by facchinm** [comment]
Hi @egienvalue ,
would you mind moving the issue to https://github.com/arduino-libraries/SD and closing this one? Thanks
