### ISSUE TITLE
misleading "analogWrite" for digital pins: better: pwmWrite, analogWrite only for DAC pins!

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#7268]
IMO the function name "analogWrite" is misleading for digital pins and leads to misconceptions.
it would be better to use the function name "pwmWrite" for that purpose and make analogWrite depricated to digital pins, 

analogWrite instead should be kept and reserved only for analog DAC pins!

**Comment by facchinm** [comment]
From an higher perspective and with the right filtering, `analogWrite` does exactly what it promises. On platforms with a DAC, the function invocation provides the correct analog voltage. Also, there is a huge mass of code using that function so a deprecation process is unfeasible anyway :wink:
