### ISSUE TITLE
feature request: AVR Dragon Support

### ISSUE THREAD

**Issue by sktrea** [arduino/Arduino#7269]
Hi,
is it possible to add the AVR Dragon to the programmer?

**Comment by facchinm** [comment]
Hi @sktrea,
would you mind moving the issue to https://github.com/arduino/ArduinoCore-avr and closing this one? Thanks!

**Comment by sktrea** [comment]
Moved to Arduino-Core 
#9 https://github.com/arduino/ArduinoCore-avr/issues/9
