### ISSUE TITLE
Simplify analog input pins-to-channels (and make more portable) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#727]
This is [Issue 727](http://code.google.com/p/arduino/issues/detail?id=727) moved from a Google Code project.
Added by 2011-11-23T05:35:24.000Z by [maniac...@ymail.com](http://code.google.com/u/104304625040622075887/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core
### Original description

The conversion from pins to channels currently has 3 #if/else clauses.  It can be made much simpler.  Also this would help support 1284P, and will be forward-compatible with other variants which come up in the future.

P/S Is the developer's list closed?  I tried to subscribe, but received no response.

**Comment by sandeepmistry** [comment]
I'm marking this as won't fix, it's unlikely an official 1284P will be made in.
