### ISSUE TITLE
Arduino ARM (32bit) is greyed out (Not available)

### ISSUE THREAD

**Issue by dennyjim** [arduino/Arduino#7270]
After I install the  "Arduino SAM boards (32 bits ARM Cortex-M3") 
the "Arduino ARM (32bits) Boards" shows in the boards list but it is greyed out and I can not choose it.
I had it all up and running but had to do a reinstall. Now I can't choose my board.
Anyone had this problem?

**Comment by per1234** [comment]
Please post a screenshot to demonstrate the problem.

**Comment by per1234** [comment]
Closing due to lack of response. Note that it's the expected behavior for the **Tools > Board** menu section headings to be greyed out since you would not want to select that text, but rather the board items under it.
