### ISSUE TITLE
ESP shows up as a WiFi access point

### ISSUE THREAD

**Issue by av4625** [arduino/Arduino#7274]
When I look at the Wifi sources on my phone/pc when I go to select a network to join, my esp8266’s show up.
I have 3 esp’s but only 2 show up, all running the same code. 
Are they meant to show up? Im I using the library wrong?

IN SETUP:

`
WiFi.persistent(false);
check_wifi();
`

IN LOOP:

`check_wifi();`

THE CHECK WIFI FUNCTION

`void check_wifi()
{
    // Check WiFi status
    if (WiFi.status() != WL_CONNECTED)
    {
        WiFi.disconnect();
        // Connect to the network
        WiFi.begin(ssid, wifi_password);
        Serial.println("Connecting to WiFi");
    }
    
    while (WiFi.status() != WL_CONNECTED)
    {
        delay(500);
        Serial.print(".");
    }
}`

Cant get the code to show right for the check wifi function

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
