### ISSUE TITLE
Library url changed

### ISSUE THREAD

**Issue by Onno-Dirkzwager** [arduino/Arduino#7277]
We changed our repository name as we will support all esp's and not only the esp8266. This also changed the url of our previously added library.

**Old location**
https://github.com/iotappstory/ESP8266-Library

**New location**
https://github.com/iotappstory/ESP-Library

Please update, thanks.

**Comment by cmaglie** [comment]
Done!

**Comment by Onno-Dirkzwager** [comment]
Thanks (Y)
