### ISSUE TITLE
Where is the content on arduino.cc tracked? Can we contribute?

### ISSUE THREAD

**Issue by TomasHubelbauer** [arduino/Arduino#7279]
I'd like to propose a change to the article at

https://www.arduino.cc/en/Guide/Troubleshooting#upload

There is only a single GitHub link on the page and it leads to the Arduino org. It would be amazing if there was a "Propose change" or "Fork me on GitHub" link like is usually the case with docs generated from a GitHub repository. Are these generated that way? Is the content tracked anywhere on GitHub so that I could offer my contribution to it?

I searched the Arduino GitHub org for *troubleshooting* using GitHub search, but I didn't find the sources for the docs that way.

**Comment by per1234** [comment]
Thanks for your interest in contributing to the Arduino project!

It is currently only possible to submit pull requests for the [Arduino Language Reference ](https://www.arduino.cc/reference/en/)content:
https://github.com/arduino?q=reference-
The Language Reference pages on arduino.cc do have edit links.

To suggest improvements or report problems with any of the other content you can simply submit an issue report here. Please first do a search for existing issue reports to avoid creating duplicate issues.

It is planned to eventually put the Library Reference content on GitHub and possibly some other parts of the arduino.cc content as well.
