### ISSUE TITLE
Add LM35 library

### ISSUE THREAD

**Issue by Manghao** [arduino/Arduino#7287]
https://github.com/Manghao/LM35

Following the instructions provided [here ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

Thank you in advance

**Comment by cmaglie** [comment]
There is already a library named LM35: https://github.com/ggzucco/LM35.git

Please choose another name and:

1) change the name in the `library.properties`
2) commit and push
3) remove and redo the tag/release

**Comment by cmaglie** [comment]
Closing for now. Please comment further when you're ready.

**Comment by Manghao** [comment]
Hello, sorry I completely forgot to make the requested change, it is currently online on my repository.
