### ISSUE TITLE
[Library Manager] Please add blinker-library

### ISSUE THREAD

**Issue by i3water** [arduino/Arduino#7299]
Hi,

I'd like to have my library added - https://github.com/i3water/blinker-library

Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by i3water** [comment]
Hi,

I had released the vervion.

Thanks!

**Comment by cmaglie** [comment]
Done!
