### ISSUE TITLE
New library ESP_EEPROM - improved EEPROM emulation library for ESP devices

### ISSUE THREAD

**Issue by jwrw** [arduino/Arduino#7308]
The standard EEPROM library for the ESP8266 uses flash memory to store the EEPROM data.  This is re-flashed every time the dates committed, which is slow, disruptive and will wear the flash prematurely. This library is substantially compatible with the standard library but avoids re-flashing as much as possible.

It may be found at
https://github.com/jwrw/ESP_EEPROM

**Comment by cmaglie** [comment]
Done!
