### ISSUE TITLE
[Library Manager] Please add MPU6050_tockn

### ISSUE THREAD

**Issue by Tockn** [arduino/Arduino#7309]
Hello.

I created a library to manage my board named MPU6050_tockn.
Could you add this to a list of libraries?

url: https://github.com/Tockn/MPU6050_tockn

**Comment by cmaglie** [comment]
I've added the library to the index but there is a problem:

```
JOB 1379 - 2018/03/16 21:43:19 Checking out tag: 1.2.0
JOB 1379 - 2018/03/16 21:43:19 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

To fix this:
- add `sentence` and `paragraph` fields to the `library.properties`
- commit and push
- remove and redo the release tag 1.2.0

Once done the indexer will automatically publish the library within an hour, no need to comment further here.
