### ISSUE TITLE
[LIbrary Manager] Please add M10SevenSeg 

### ISSUE THREAD

**Issue by PulseRainmaker** [arduino/Arduino#7310]
Please add the following to the library manager

https://github.com/PulseRain/M10SevenSeg

Thanks!

**Comment by PulseRainmaker** [comment]
keywords.txt has been changed, and spaces have been converted into single tab.

A new release 1.0.1 has also been created.

Thanks!

**Comment by PulseRainmaker** [comment]
pull request has been merged.

A new release 1.0.2 has also been created.

Thanks!

**Comment by cmaglie** [comment]
Done!

**Comment by PulseRainmaker** [comment]
Thanks!
