### ISSUE TITLE
Lack of pixels between edge and text at edge of window when a new window is opened. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#732]
This is [Issue 732](http://code.google.com/p/arduino/issues/detail?id=732) moved from a Google Code project.
Added by 2011-12-02T03:44:52.000Z by [jim.w.mu...@gmail.com](http://code.google.com/u/117209562169070676618/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open a new window in Arduino.

**What is the expected output? What do you see instead?**
I expect to see some pixels between the window edge and the text. Instead, text buts right up against the edge of the window.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

This is a problem in the Arduino IDE. It has occurred over several versions of the IDE, not just the latest version.

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Works fine with latest hourly
