### ISSUE TITLE
[Library Manager] Please Add Google-TTS-Library

### ISSUE THREAD

**Issue by horihiro** [arduino/Arduino#7323]
Please add the following library to the Library Manager.

https://github.com/horihiro/esp8266-google-tts

This is a library for generating a link to a speech mp3 from text.

Thanks!

**Comment by horihiro** [comment]
Fixed keyword.txt by @per1234.
https://github.com/horihiro/esp8266-google-tts/releases/tag/1.0.1

**Comment by cmaglie** [comment]
Done!

**Comment by horihiro** [comment]
Thanks! @cmaglie
