### ISSUE TITLE
[Library Manager] add 'AUnit' unit testing framework library

### ISSUE THREAD

**Issue by bxparks** [arduino/Arduino#7329]
Please add
https://github.com/bxparks/AUnit
to the library manager.

"A unit testing framework for Arduino platforms inspired by ArduinoUnit.
The unit tests run in the embedded controller, not in a simulator or emulator. It is almost a drop-in replacement of ArduinoUnit with 2 advantages. AUnit can reduce flash memory consumption by as much as 66% on the AVR platform. And it works with the ESP8266 platform, as well as the AVR and Teensy platforms."

**Comment by cmaglie** [comment]
done!
