### ISSUE TITLE
Please include Word100 library 

### ISSUE THREAD

**Issue by kd8bxp** [arduino/Arduino#7334]
https://github.com/kd8bxp/Word100

A simple library for The "100+ Word" Arduino Audio Shield! and LBT "Little Buddy Talker".  Speak Arduino, Speak! by Patrick Thomas Mitchell

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by kd8bxp** [comment]
Done - Thanks.

**Comment by cmaglie** [comment]
Done!
