### ISSUE TITLE
IPAddress missing definition of operator!= and may cause incorrect behaviour

### ISSUE THREAD

**Issue by ssilverman** [arduino/Arduino#7336]
Defining operator!= is needed to do comparisons like `a != b`. Otherwise, code comparing inequality of IPAddresses needs to do `!(a == b)`.

**Comment by ssilverman** [comment]
A request: would you mind adding the commit this was fixed in?

**Comment by matthijskooijman** [comment]
Did you look in the arduino core avr repo? It has a separate repository these days.

**Comment by facchinm** [comment]
Hi @ssilverman ,
sorry for the confusion, it was the automatic github issue closer in action :slightly_smiling_face: The commit is https://github.com/arduino/ArduinoCore-api/commit/d5ae3faba1d69500f920c57b2afac59021831278 (we are still preparing the official release)
