### ISSUE TITLE
WiFi Location library

### ISSUE THREAD

**Issue by gmag11** [arduino/Arduino#7338]
I've developed a library to get location using WiFi APs around with the help of Google maps Geolocation API. It is compatible with mkr1000, esp8266 and esp32.
You can check it on https://github.com/gmag11/WifiLocation
Presse, add it to official repository of you think it is useful.

**Comment by cmaglie** [comment]
Done!

**Comment by gmag11** [comment]
I guess script has selected the wrong branch, not master. I've deleted all extra branches. Tags are correctly defined up to last version 1.2.

**Comment by per1234** [comment]
The reason that only versions 0.0.1 and 1.2.0 are available from Library Manager is that it uses the `version` field in library.properties for versioning. The `version` value in library.properties for your [v1.0](https://github.com/gmag11/WifiLocation/blob/v1.0/library.properties#L2) and [1.1](https://github.com/gmag11/WifiLocation/blob/1.1/library.properties#L2) releases were both set to 0.0.1 so this caused the 1.1 release to be available as version 0.0.1 in Library Manager and the v1.0 release to not be available at all.

You just need to remember to always update the `version` value before you make a release.
