### ISSUE TITLE
Infinite loop in DhcpClass::parseDHCPResponse if more then 1 response packet arrives. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#734]
This is [Issue 734](http://code.google.com/p/arduino/issues/detail?id=734) moved from a Google Code project.
Added by 2011-12-02T15:31:08.000Z by [pe...@birchroad.net](http://code.google.com/u/109532119424734364017/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

I know you perhaps should not get a response from more than 1 machine on the same network but if you do, and it's more common than one might think of, the code will end up in a never ending loop.

I have downloaded Arduino-1.0 (the proposed release that were announced on the dev mailing list, later than rc2) and have some issues.
How I detected this was by trying to use the DhcpChatClient example.
In my network I will get (working on removing but still) 2 replies to a DHCP request.
I think this messes up the EthernetUDP / DHCP implementation.

This is somewhat related to issue #669 as well and it doesn't work even if I implement the proposed changes there.
This specific issue is about DHCP but I think it's an issue that might turn up elsewhere as well.

In the beginning of DhcpClass::parseDHCPResponse there is a _dhcpUdpSocekt.parsePacket() which updates the private EthernetUDP._remaining counter. So far everything is well and the packet starts to be parsed.

A while loop begins to parse the packet until .available() is 0 on the udp socket.
While parsing, another packet arrives to the buffer in the w5100.
This will add to the count that .available() returns which is correct but I will not be allowed to read them after the _remaining counter in EthernetUDP goes down to 0.
This will make the while(_dhcpUdpSocket.available()) run forever since there is correctly bytes available but I'm not allowed to read them, unless I would do another .parsePacket() on the UDP socket since all read methods look at the _remaining counter which is already 0.

You simply can not trust to .read() the socket until .available() turns 0 since you can not be sure that the _remaining counter and the buffer in w5100 match.

My HACKY workaround was to make EthernetUDP._remaining public instead of private and do 
while(_dhcpUdpSocket._remaining>0) 
instead of 
while(_dhcpUdpSocket.available())
and simply throw away the second response.
This is NOT the correct way to solve and I'm not good enough at c/c++ to do a correct solution but it shows the issue

Anything BUT ending up in a never ending loop would be fine, I could live with not getting an IP even though the first response would give me one. The best would be do deal with the situation in a proper way and use the first valid response (or perhaps only the first response, period) and ignore everything else.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#21
