### ISSUE TITLE
[add lib request] Please add U8g2_for_Adafruit_GFX library to the Arduino IDE

### ISSUE THREAD

**Issue by olikraus** [arduino/Arduino#7342]
This add-on library makes the U8g2 font rendering engine available for all Adafruit GFX based libraries. 
This will add Unicode/UTF-8 support and more than 1000 fonts to Adafruit GFX libs.

Library Link: https://github.com/olikraus/U8g2_for_Adafruit_GFX

Please add the library to the Arduino IDE Library Manager.

Thanks!

**Comment by cmaglie** [comment]
Done!

**Comment by olikraus** [comment]
Thanks!
