### ISSUE TITLE
add this library ubidots-mqtt-esp

### ISSUE THREAD

**Issue by pacav69** [arduino/Arduino#7345]
https://github.com/ubidots/ubidots-mqtt-esp

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by pacav69** [comment]
it has been tagged

**Comment by cmaglie** [comment]
Done
