### ISSUE TITLE
Optical Laser sensor

### ISSUE THREAD

**Issue by RedDragon99** [arduino/Arduino#7353]
Hello

I have 1 question 

I have and optical laser sensor which I would like to use using arduino UNO 
THe logic of it is if it gets the signal back there is no object between ...and if it doesnt get the signal back there is an object between.
It uses from 10-30VDC...I am powering it with 12V
I would just like to know how should I wire it and the code to use it ... just that the code tells me if there is an object between the sensor and reflecting glass.

The sensor with glass:
http://shrani.si/f/1y/Rg/Q5uKA25/294258361732158206827578.jpg

The wires:
http://shrani.si/f/W/Ic/3TaPwYR5/294333491732154103494655.jpg

The schematics of the wiring:
http://shrani.si/f/1I/ua/4iAEJK3s/294728761732154076827991.jpg

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
