### ISSUE TITLE
[Library Manager] Please add Motor Driver V1.0.0 to Library Manager

### ISSUE THREAD

**Issue by RupinC** [arduino/Arduino#7356]
URL of Repository https://github.com/CuriosityGym/MotorDriver
Tag 1.0.0. : https://github.com/CuriosityGym/MotorDriver/releases/tag/v1.0.0

Thank You

**Comment by per1234** [comment]
You should not quote the values in library.properties. Please resolve this and then create a new release or tag.

Reference: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by RupinC** [comment]
Updated:

URL of Repository https://github.com/CuriosityGym/MotorDriver
Tag 1.0.1. : https://github.com/CuriosityGym/MotorDriver/releases/tag/v1.0.1

Thank You

**Comment by cmaglie** [comment]
Done!
