### ISSUE TITLE
Back Slash at end of comment

### ISSUE THREAD

**Issue by falconphysics** [arduino/Arduino#7361]
If you put a backslash as the last character of a comment line the next line of code will be ignored by the compiler. Given the code below, the complier will tell me x is not declared:

```
// comment here\
int x = 10;
Serial.println(x);
```

**Comment by matthijskooijman** [comment]
That's a feature :-)

Putting a backslash at the end of a line is called a "line continuation", so this works as expected.

**Comment by falconphysics** [comment]
Oh, ok. Sorry about that.

Thanks.
