### ISSUE TITLE
Link to GitHub from Arduino Create

### ISSUE THREAD

**Issue by leemke** [arduino/Arduino#7369]
If you want people to report issues and suggestions using GitHub, then add a link to take you there
from Arduino Create.  Also add help information about this and what is necessary to create a GitHub
userid and some help on how to use it with Arduino.

**Comment by per1234** [comment]
In fact, as stated in https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the recommended place to report issues and suggestions on that topic is the Create section of the Arduino Forum, not GitHub.

I know that when something goes wrong during compilation in the Arduino Web Editor the error says:
>Compilation failed. Please report this issue on [our Forum](http://forum.arduino.cc/index.php?board=101.0).

I also see in the notifications area:
>Do you have any feedback or do you want to report a bug?
[Write us on the Forum!](http://forum.arduino.cc/index.php?board=101.0)

It could very well be there are other places where that information should also be provided ([including this repository](https://github.com/arduino/Arduino/pull/6357/commits/c6e84672c38f53b20c803053eba754ceeaf5ddc7)). So please create a post on the appropriate section of the Arduino Forum with specific suggestions of how the documentation of where/how to report issues/suggestions regarding Arduino Create could be improved.
