### ISSUE TITLE
Add "PointzNet" library to Library manager Arduino IDE

### ISSUE THREAD

**Issue by Isaranu** [arduino/Arduino#7370]
We are developer team from www.pointznet.com which provided an IoT user to send  a data of Air Quality Index (PM2.5, PM10) to display on designable map. It's compatible use with ESP8266 Wifi module, NodeMCU, WeMos, Nano32 and several IoT model.

github url : https://github.com/Isaranu/PointzNet

Thank you very much.
IoTtweet team.

**Comment by cmaglie** [comment]
Done!
