### ISSUE TITLE
[Library Manager]Please add Seeed Wio GPS Board v1.0.0 to Library Manager.

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7372]
This is the first time Seeed Studio pull library to the Library Manager, please give some tips to me if I was doing something wrong.

Github: https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board
Release: https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board/releases/tag/v1.0.0

Thanks a lot!

**Comment by cmaglie** [comment]
Done!
