### ISSUE TITLE
[Library Manager]Please add Seeed Wio GPS Board v1.0.2 to Library Manager.

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7375]
Thanks to some good guy a important bug has been fixed, please add v1.0.2 to Lib Manager.

Github: https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board
Release: https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board/releases/tag/v1.0.2

**Comment by per1234** [comment]
Now that your repository has been added to the index, the automated job will make new releases available for installation via Library Manager shortly after you create them. So there is no need to request that releases be added here. I just checked Library Manager and found that 1.0.2 has already been added to the index.
