### ISSUE TITLE
New library: FDC2214 

### ISSUE THREAD

**Issue by zharijs** [arduino/Arduino#7390]
https://github.com/zharijs/FDC2214

Ti noise-immune capacitative sensing series library
Supports FDC2112, FDC2114, FDC2212 and FDC2214.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by zharijs** [comment]
Made a release 1.0.

**Comment by cmaglie** [comment]
done
