### ISSUE TITLE
[Library Manager] ShiftRegister74HC595

### ISSUE THREAD

**Issue by Simsso** [arduino/Arduino#7396]
The [ShiftRegister74HC595](https://github.com/Simsso/ShiftRegister74HC595) library ([docs](https://shiftregister.simsso.de/)) has been around for quite a while and is now (with version [v1.1.0](https://github.com/Simsso/ShiftRegister74HC595/releases/tag/v1.1.0)) compliant with the Library Manager requirements.

This issue is kindly requesting to add the library publicly.

**Comment by Simsso** [comment]
Apparently the library was found by the crawler:
![image](https://user-images.githubusercontent.com/6556307/38177300-7c11de4c-35ff-11e8-8344-1851b85de340.png)
I assume this issue can be close then.

**Comment by per1234** [comment]
Library Manager lists libraries you already have installed on your computer as well as those available for installation from the Library Manager index.

Your repository must be added to the Library Manager index before it will be available for installation via Library Manager. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that.

**Comment by cmaglie** [comment]
Done
