### ISSUE TITLE
SD card support [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#740]
This is [Issue 740](http://code.google.com/p/arduino/issues/detail?id=740) moved from a Google Code project.
Added by 2011-12-05T23:57:52.000Z by [jur...@gmail.com](http://code.google.com/u/114151238874710475372/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

I had some problems with repeated initialization of SD cards with Arduino 1.0 (so I can remove them from the Arduino to retrieve the information on them). It would just stop writing to the card after a while. (before writing I initialized the SD card, but somehow this wouldn't work every time)

I got it working by using the latest version of SDFATlib, on which the current SD lib is based I think (a much older version).
The current SD lib works by providing a higher level interface for the old version of the SDFATlib.
With newer versions this is not needed anymore because a higher level interface is included in the SDFATlib itself.

Why don't you integrate this newer library, it also comes with good support for multiple SD cards and more features! :)

You can find the latest (Arduino 1.0 compatible) version on http://code.google.com/p/beta-lib/downloads/list

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/SD#18
