### ISSUE TITLE
Modify USB profile to remove serial port - With switch (Leonardo)

### ISSUE THREAD

**Issue by Shadow7369124** [arduino/Arduino#7405]
Hello,

I found a way here to disable the Serial port that appears in the Device manager for a simple HID exemple
https://github.com/arduino/Arduino/issues/6387

But I would like to had a switch on the leonardo that disables serial port when off and enables it when on.

If someone know how to edit the code to do it.

Thanks

**Comment by PaulStoffregen** [comment]
You're asking for help in the wrong place.  This area is only for reporting software defects.

Ask on the forum.
https://forum.arduino.cc/
