### ISSUE TITLE
[Library Manager] Please add library Digital Infrared Temperature Sensor MLX90615

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7406]
github: https://github.com/Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615
release: https://github.com/Seeed-Studio/Digital_Infrared_Temperature_Sensor_MLX90615/releases/tag/v1.0.0

thnaks!

**Comment by cmaglie** [comment]
Done
