### ISSUE TITLE
[Library Manager] Please add library for Grove_3_Axis_Compass_V2.0_BMM150

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7410]
github: https://github.com/Seeed-Studio/Grove_3_Axis_Compass_V2.0_BMM150
release: https://github.com/Seeed-Studio/Grove_3_Axis_Compass_V2.0_BMM150/releases/tag/v1.0.0

Thanks!

**Comment by cmaglie** [comment]
Done!
