### ISSUE TITLE
[Library Manager] Please add library painlessMesh

### ISSUE THREAD

**Issue by BlackEdder** [arduino/Arduino#7424]
https://gitlab.com/painlessMesh/painlessMesh

This library enables mesh functionality for both esp32 and esp8266 boards.

**Comment by BlackEdder** [comment]
Note that in the next version we'll most likely add ESPAsyncTCP and AsyncTCP to our dependencies, which I don't think are in the library manager yet?

**Comment by cmaglie** [comment]
Done. No `ESPAsyncTCP` nor `AsyncTCP` has been added in the library manager yet.
