### ISSUE TITLE
[Library Manager]Please add Grove Water Sensor v1.0.0 to Library Manager

### ISSUE THREAD

**Issue by linux-downey** [arduino/Arduino#7436]
Github:https://github.com/Seeed-Studio/Grove_Water_Sensor
Release:https://github.com/Seeed-Studio/Grove_Water_Sensor/releases

**Comment by per1234** [comment]
https://github.com/Seeed-Studio/Grove_Water_Sensor is a sketch, not a library. Library Manager is only for libraries.
