### ISSUE TITLE
[Library Manager] Please add library for Grove - Barometer Sensor (BMP280)

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7437]
github: https://github.com/Seeed-Studio/Grove_BMP280
release: https://github.com/Seeed-Studio/Grove_BMP280/releases/tag/1.0.0

Thanks!

**Comment by cmaglie** [comment]
parenthesis are not allowed on the name:

`Grove - Barometer Sensor (BMP280)`

could you remove them?
Remeber also to remove& redo the release tag after pushing the change to the repository.

**Comment by lanselambor** [comment]
@cmaglie Have fixed that, thank you!

**Comment by cmaglie** [comment]
done
