### ISSUE TITLE
[Library Manager] Please add library for Grove - I2C Color Sensor

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7446]
github: https://github.com/Seeed-Studio/Grove_I2C_Color_Sensor
release: https://github.com/Seeed-Studio/Grove_I2C_Color_Sensor/releases/tag/1.0.0

Thanks! 😄

**Comment by cmaglie** [comment]
I've added all the Grove libraries (except 2 that needs editing).

@lanselambor when you have a batch of libraries to add, just open one issue for all of them.
Just post the link to the github repo, there is no need to add the release/tag link that is picked automatically.

**Comment by lanselambor** [comment]
Ok got it.
