### ISSUE TITLE
[Library Manager] Please add these libraries.

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7450]
https://github.com/Seeed-Studio/Grove_I2C_Motor_Driver_v1_3
https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight
https://github.com/Seeed-Studio/Grove_LED_Bar
https://github.com/Seeed-Studio/Grove_LED_Matrix_Driver
https://github.com/Seeed-Studio/Grove_LoRa_433MHz_and_915MHz_RF
https://github.com/Seeed-Studio/Grove_Mini_Track_Ball
https://github.com/Seeed-Studio/Grove_Serial_MP3_Player_V2.0
https://github.com/Seeed-Studio/Grove_SHT31_Temp_Humi_Sensor
https://github.com/Seeed-Studio/Grove_Sunlight_Sensor
https://github.com/Seeed-Studio/Grove_Temper_Humidity_TH02
https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor
https://github.com/Seeed-Studio/Hercules_Motor_Driver
https://github.com/Seeed-Studio/IRSendRev

Thanks a lot.

**Comment by cmaglie** [comment]
All done
