### ISSUE TITLE
[Library Manager] Library addition request - Unified A/D multiplexer interface

### ISSUE THREAD

**Issue by stechio** [arduino/Arduino#7455]
Apparently, the Arduino library collection lacks a **unified interface for controlling analog/digital multiplexers**, so I decided to develop an elegant solution based on Nick Lamprianidis' MUX74HC4067 project (full credits included in the library). Relevant features:
* generic Mux + specialized implementations (4051 and 4067 ICs, at the moment)
* encapsulated R/W A/D operations
* multiple signal pin switching

Please consider adding this library to the Arduino library collection:

github: https://github.com/stechio/arduino-ad-mux-lib
release: https://github.com/stechio/arduino-ad-mux-lib/releases/tag/v1.0.0

Thank you

**Comment by per1234** [comment]
The `name` value in your library.properties contains the disallowed character `/`. Please do the following:
1. Change the name to meet the requirements of the [Arduino Library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format).
2. Create a release or tag (make sure it matches the value of the `version` field in your library.properties).
3. Comment here so we know we can proceed with adding your library to the Library Manager index.

**Comment by stechio** [comment]
1. Sorry for my oversight, now the name is fixed.
2. Sorry for my oversight, now the tag should be ok (see below).

github: https://github.com/stechio/arduino-ad-mux-lib
release: https://github.com/stechio/arduino-ad-mux-lib/releases/tag/1.0.0

Thanks

**Comment by cmaglie** [comment]
done
