### ISSUE TITLE
Add "IoTtweetNBIoT" library to Library manager Arduino IDE

### ISSUE THREAD

**Issue by Isaranu** [arduino/Arduino#7456]
We are developer team from www.iottweet.com which provided an IoT dashboard using for NB-IoT device send data to display. It's compatible use with NB-IoT device (provider : AIS)

github url : https://github.com/Isaranu/IoTtweetNBIoT

Thank you very much.
IoTtweet team.

**Comment by cmaglie** [comment]
done
