### ISSUE TITLE
Please add my library for multithreading to index

### ISSUE THREAD

**Issue by slavaza** [arduino/Arduino#7466]
https://github.com/slavaza/Thread

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by slavaza** [comment]
Ok. Thank you. I created a pre-release "Preliminary".

**Comment by slavaza** [comment]
Sorry, I'm still not very good at operating github. I hope now everything is correct.

**Comment by cmaglie** [comment]
done!

**Comment by slavaza** [comment]
@cmaglie  Thank you very much.
