### ISSUE TITLE
Sketch/Example/Library [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#747]
This is [Issue 747](http://code.google.com/p/arduino/issues/detail?id=747) moved from a Google Code project.
Added by 2011-12-11T20:39:22.000Z by [spycatch...@gmail.com](http://code.google.com/u/110483414950090752196/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I have a LOT of sketches and libraries, when I open the menu, the list goes off the screen - A Multi column splitting up the list would be very helpfull as currently I have to move my libraries and sketches out of there normal folders.

**Comment by ffissore** [comment]
Fixed some time ago
