### ISSUE TITLE
[Library Manager] MelodyWithoutDelay 

### ISSUE THREAD

**Issue by nathanRamaNoodles** [arduino/Arduino#7475]
https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary
This library is the next generation of tone().  Thanks to the help of bhagman(creator of the tone function), I've created an algorithm that can enable any Arduino to play Music without delay.  This library can make any arduino turn into an MP3 player with no extra hardware!

The examples are user-friendly and the documentation is clear and concise.

**Comment by cmaglie** [comment]
done!
