### ISSUE TITLE
Invalid Library error

### ISSUE THREAD

**Issue by sk8nfool** [arduino/Arduino#7476]
Following instructions here (https://github.com/arduino/Arduino/wiki/Building-Arduino) I just cloned and built (but not installed) the Arduino IDE on a 64 bit Ubuntu 16.04 system.
Immediately after the build I ran "ant run" to test the build and received the following errors

> ...
>
> start:
> 
> linux64-start:
>      [exec] Picked up JAVA_TOOL_OPTIONS: 
>      [exec] Invalid library found in /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6: /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6
>      [exec] Invalid library found in /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6: /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6
>      [exec] Invalid library found in /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6: /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6
>      [exec] Invalid library found in /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6: /home/braun/src/arduino/Arduino/build/linux/work/libraries/Firmata-2.5.6
> 
> ```

As it turns out the folder mentioned is empty so I don't know what library is invalid.

I also get the same error when I compile and download the Blink example to an Adafruit 5V Trinket Pro

**Comment by facchinm** [comment]
Hi @sk8nfool,
the "issues" are totally unrelated. The `Invalid library found ... ` is related to the way we unpack Firmata. It doesn't affect the actual functionality and does not appear when the IDE package is created with `and dist`.
For the second one, please open another issue with the **verbose** compilation turned on (first try posting it on the [forum](https://forum.arduino.cc), most compilation errors have known solutions)
