### ISSUE TITLE
Busy Flag in Liquid Crystal library not used [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#748]
This is [Issue 748](http://code.google.com/p/arduino/issues/detail?id=748) moved from a Google Code project.
Added by 2011-12-13T16:12:43.000Z by [mmoottu...@gmail.com](http://code.google.com/u/116628161091925147748/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
I noticed that the Liquid Crystal library is performing amazing delays of thousands microseconds instead of reading the busy flag. Why don't we use the busy flag, which was especially buit for this usage?

**Why?**
A lot of time is lost because of active waits.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
Not any incompatibility with previous versions.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/LiquidCrystal#9
