### ISSUE TITLE
[Library manager] Please add this HC-SR04 library

### ISSUE THREAD

**Issue by patou01** [arduino/Arduino#7509]
Yet another HC-SR04 library to add to the manager.

https://github.com/patou01/HC-SR04

Thanks!

**Comment by patou01** [comment]
I think I fixed the issues that have been reported, is there still something missing?

**Comment by per1234** [comment]
It looks to me as if your library meets all the requirements for inclusion in the Library Manager index. There's nothing you need to do other than wait for us to get around to adding your library to the index.

cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after.

**Comment by patou01** [comment]
Oh okay. Then I'll wait :). 

Thanks!

**Comment by cmaglie** [comment]
Hi @patou01, sorry for the delay.

I've added the library but there are some problems:

```
JOB 1546 - 2018/05/02 11:02:44 Checking out tag: 0.3
JOB 1546 - 2018/05/02 11:02:44 Error syncing library: .development file found, skipping
JOB 1546 - 2018/05/02 11:02:44 Checking out tag: V0.2
JOB 1546 - 2018/05/02 11:02:44 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

I see that you already defined on `sentence` and `url` fields on the latest release, so I guess that the only problem is the presence of the `.development` file. May you remove it and re-do the releae 0.3?

The library is now added to the index, once you fix the above it should be automatically published within an hour, no need to comment further.
