### ISSUE TITLE
[Library manager] Please add libraries

### ISSUE THREAD

**Issue by zoubworldArduino** [arduino/Arduino#7515]
Hello,

Could you please add these libraries to the repository? 
- https://github.com/zoubworldArduino/Zeeprom
  - drive EeProm AT24C01...1024
- https://github.com/zoubworldArduino/ZEncoder
  - drive motor encoder
- https://github.com/zoubworldArduino/ZSharpIR
  - drive sharp ir
- https://github.com/zoubworldArduino/Zmotor3
  - drive motor througth PCA9685 & MCP23017
- https://github.com/zoubworldArduino/ZMotor2
  - drive motor througth PCA9685 & MCP23017
- https://github.com/zoubworldArduino/ZMCP23017
  - drive MCP23017
- https://github.com/zoubworldArduino/ZPCA9685
  - drive PCA9685 
- https://github.com/zoubworldArduino/WireUtility
  - scan address on wire
- https://github.com/zoubworldArduino/PinExtender
  - give an abstraction of pin including on pin behing a MCP23017/PCA9685, to use it as arduino GPIO.
- https://github.com/zoubworldArduino/ZCmdMotor
  - control motor with PID.

Thank's for the support.
Pierre

**Comment by cmaglie** [comment]
Done
