### ISSUE TITLE
[Library manager] Add arduino-ess to Library Manager

### ISSUE THREAD

**Issue by winkj** [arduino/Arduino#7519]
Dear maintainers,

Could you add the arduino-ess library to the library manager?
  https://github.com/Sensirion/arduino-ess

I just tagged 0.5.0, which is a major release in terms of functionality. The ESS - Environmental Sensor Shield - is an Arduino shield which features humidity, temperature, TVOC and eCO2 sensors.

Thanks, Johannes

**Comment by cmaglie** [comment]
Done
