### ISSUE TITLE
Issues with "Variables" reference page

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7521]
https://www.arduino.cc/en/Reference/VariableDeclaration

Change:
```
int inputVariable1;
int inputVariable2 = 0;     // both are correct

```
To:
```
int inputVariable1;
int inputVariable2 = 0;     // both are correct
```
(Remove blank line from end of code block)

Change:
```
 int calibrationVal = 17;  // declare calibrationVal and set initial value

```
To:
```
int calibrationVal = 17;  // declare calibrationVal and set initial value
```
Notes:
- Remove one space indent.
- Remove blank line from end of code block

---
Change:
```
   int x;
   x = -32,768;
   x = x - 1;       // x now contains 32,767 - rolls over in neg. direction

   x = 32,767;
   x = x + 1;       // x now contains -32,768 - rolls over
```
To:
```
  byte x;
  x = 0;
  x = x - 1;       // x now contains 255 - rolls over in neg. direction

  x = 255;
  x = x + 1;       // x now contains 0 - rolls over
```

Notes:
- Use a type that will be a consistent size when using any official Arduino core (thanks Coding Badly).
- Signed integer overflow is undefined behavior so it's not a good thing to use in an example.
- Add missing semicolon.
- Don't use decimal separators.
- Standard 2 space indentation rather than weird 3 space indentation.

---
Change:
>Once variables have been declared, they are used by

to:
>Once variables have been declared, they **can be defined** by

---
Change:
```
 int lightSensVal;
   char currentLetter;
   unsigned long speedOfLight = 186000UL;
   char errorMessage = {"choose another option"}; // see string 
```
to:
```
  int lightSensVal = 1234;
  char currentLetter = 'a';
  unsigned long speedOfLight = 186000UL;
  char errorMessage[] = "choose another option"; // see string
```
Notes:
- Consistent, standard indentation.
- These are supposed to be examples of variable definition, not declaration. So define them.
- `errorMessage` is an array.
- Standard string initialization syntax.
- Trim trailing space

---
Change:
```
if (inputVariable2 < 100)
{
  inputVariable2 = 100;
}

delay(inputVariable2);
```
To:
```
  if (inputVariable2 < 100)
  {
    inputVariable2 = 100;
  }

  delay(inputVariable2);
```
(All previous code that would need to be inside a function was indented so either this should be indented for consistency or else other indentation should be removed)

---
Change:
>and it uses the value of the variable as an input parameter to the delay() function (` delay(inputVariable2)` )

To:
>and it uses the value of the variable as an input parameter to the delay() function ( `delay(inputVariable2)` )

(remove leading space from code tag)

---
"Some variable types" section:
Since a comment in the variable definition examples says "see string", add a link to https://www.arduino.cc/reference/en/language/variables/data-types/string/

---
What's the deal with this page? It appears to be a Language Reference page but it's not in the [Language Reference repository](https://github.com/arduino/reference-en).

**Comment by SimonePDA** [comment]
All the suggested corrections are implemented. Thanks
