### ISSUE TITLE
Switch to CMake to build sketches and rest of the components

### ISSUE THREAD

**Issue by Avamander** [arduino/Arduino#7528]
Would it be possible that Arduino IDE started creating and keeping up to date a CMake makefile for every new created sketch? This would allow way neater building of every component, better compatibility with build systems and even other development environments (vim, Kate, CLion and etc.).

**Comment by sandeepmistry** [comment]
Hi @Avamander,

Thank you for the suggestion, however we do not plan to support this feature. Please look at arduino-cli project: https://github.com/arduino/arduino-cli

**Comment by per1234** [comment]
Related:

- https://github.com/arduino/arduino-cli/issues/1973
- Discussion starting from https://github.com/arduino/arduino-builder/issues/17#issuecomment-231568403
