### ISSUE TITLE
Enable cpp0x options during compilation of .cpp files. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#754]
This is [Issue 754](http://code.google.com/p/arduino/issues/detail?id=754) moved from a Google Code project.
Added by 2011-12-21T22:06:16.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE

### Original description

**What change would like to see?**

Add the "-std=c++0x" flag during compilation of C++ files.

**Why?**

Enables optimizations for the string class (avoid creating temporary lvalues).

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

It shouldn't.

**Comment by Chris--A** [comment]
This has been resolved. See https://github.com/arduino/Arduino/commit/ddf4d878fdb39173b872f69149fb4cf1cd9fd017 & https://github.com/arduino/Arduino/commit/7fd62446213cc395f9cc3f886886107cbfb6ba5e
