### ISSUE TITLE
10.13.4 High Sierra Serial Port Problem

### ISSUE THREAD

**Issue by ddemsahin** [arduino/Arduino#7540]
Hello, 
A day ago my Arduino Uno detected the USB port and I was able to do projects. I updated my OS to Sierra 10.13.4 and now suddenly the USB serial option has disappeared. I tried to download the last packages to fix it which are CH34x V1.3 and CH34x V1.4. However, it is not working. I really need a quick help because we have an ongoing project. 
Looking forward to hearing from everybody! 
Thanks!

**Comment by facchinm** [comment]
Hi @ddemsahin, if the board needs CH34x drivers (because ti mounts a CH34x chip as serial to usb converter) it is not a genuine board; the official UNO needs no drivers on OSX.
