### ISSUE TITLE
The file "twi.c" uses "true" and "false", even though it's C and nothing defines true or false.

### ISSUE THREAD

**Issue by mortie** [arduino/Arduino#7546]
The file [hardware/arduino/avr/libraries/Wire/src/utility/twi.c](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/Wire/src/utility/twi.c) doesn't seem to compile, because `true` and `false` isn't defined.

**Comment by matthijskooijman** [comment]
Can you tell us a bit more about your setup? This file seems to compile fine for most users in the Arduino IDE, where AFAICT it is also compiled as C, not C++. Looking at the file itself, it includes "Arduino.h", which I think defines true/false (either directly, or perhaps by including stdbool.h).

**Comment by mortie** [comment]
You're right, Arduino.h includes `stdbool.h`. I was using the unofficial Arduino.h file for ATTiny cores, this issue should probably have been opened there, and not here. Sorry.
