### ISSUE TITLE
Add RFM69_LowPowerLab to the Library Manager index

### ISSUE THREAD

**Issue by LowPowerLab** [arduino/Arduino#7553]
Please update the library manager/index or add it if not already there.

https://github.com/LowPowerLab/RFM69

Thank you!

**Comment by cmaglie** [comment]
I've added the library but there is a problem:

```
JOB 1548 - 2018/05/10 19:34:29 Scraping https://github.com/LowPowerLab/RFM69.git
JOB 1548 - 2018/05/10 19:34:33 Checking out tag: 1.0
JOB 1548 - 2018/05/10 19:34:33 Error syncing library: *.exe files found, skipping
JOB 1548 - 2018/05/10 19:34:33 Checking out tag: 1.0.0
JOB 1548 - 2018/05/10 19:34:33 Error syncing library: *.exe files found, skipping
```

we do not allow to bundle executables in the library. To fix this:

1) remove all the executables from the library
2) commit & push
3) redo the release tag

Once done the library will be picked up automatically by our indexer within an hour, no need to comment further here.
