### ISSUE TITLE
[Library Manager] Please add SparkFun BH1749NUC Library

### ISSUE THREAD

**Issue by jimblom** [arduino/Arduino#7563]
Hi,

Please include the BH1749NUC color sensor library from here: https://github.com/sparkfun/SparkFun_BH1749NUC_Arduino_Library

Thank you!

**Comment by per1234** [comment]
@jimblom that URL returns a 404 error. Is the repository maybe set to private?

**Comment by jimblom** [comment]
@per1234 Yep -- sorry about that. Should be visible now.

**Comment by cmaglie** [comment]
Done
