### ISSUE TITLE
[Library Manager] Please add SparkFun PCA9536 Library

### ISSUE THREAD

**Issue by jimblom** [arduino/Arduino#7564]
Hello,

Please include the PCA9536 4-bit I/O expander library from: https://github.com/sparkfun/SparkFun_PCA9536_Arduino_Library

Thank you!

**Comment by per1234** [comment]
@jimblom that URL returns a 404 error. Is the repository maybe set to private?

**Comment by jimblom** [comment]
@per1234 Yep -- sorry about that. Should be visible now.

**Comment by cmaglie** [comment]
Done!
