### ISSUE TITLE
Library inclusion request: FlightSimOutputs

### ISSUE THREAD

**Issue by jbliesener** [arduino/Arduino#7572]
Please add the library at https://github.com/jbliesener/FlightSimOutputs to the Arduino library manager. 

This complements the already existing FlightSimSwitches library for cockpit builders and adds a universal output instance.

**Comment by jbliesener** [comment]
Keyword file fixed in v0.2.1

**Comment by jbliesener** [comment]
Can't find it in library index yet... Any other obstacle?

**Comment by cmaglie** [comment]
Done!

**Comment by jbliesener** [comment]
Thank you, Cristian!
