### ISSUE TITLE
class::enum types returned by functions can't be compiled [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#760]
This is [Issue 760](http://code.google.com/p/arduino/issues/detail?id=760) moved from a Google Code project.
Added by 2011-12-24T07:14:31.000Z by [gooc...@top.geek.nz](http://code.google.com/u/105104457273146163885/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

class myclass {
  enum mynum {
    E1, E2, E3 };
};

myclass::mynum dosomething() {
  return E2;
}

What is the expected output? 

I expect this to work as myclass:mynum is a legal type. It does work when compiling with avr-gcc 4.3.3 and avr-gcc 4.6.2.

What do you see instead?

The Arduino IDE utterly barfs itself to death on this, because it puts a big error into the sketch file massaged together internally, which contains

// Sketch summary info.
#include "Arduino.h"
mynum dosomething();

i.e. the "myclass::" has been stripped off.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Confirmed problem with 0023, 1.0, and probably every other Arduino IDE version.
On openSUSE 11.4 and with duemilanove, allthough I doubt this matters at all.

The only way around this for now is to dumb down my program. :-(

**Comment by sandeepmistry** [comment]
This looks good now, the following sketch builds and outputs ```1``` on an Uno:

```arduino
class myclass {
  public:
    enum mynum { E1, E2, E3 };

    myclass::mynum dosomething();
};

myclass::mynum myclass::dosomething() {
  return myclass::E2;
}

myclass c;

void setup() {
  Serial.begin(9600);
  Serial.println(c.dosomething());
}

void loop() {
}
```
