### ISSUE TITLE
[Library manager] Request to rename SPIFlash library to SPIMemory

### ISSUE THREAD

**Issue by Marzogh** [arduino/Arduino#7601]
Hi guys, I'm renaming my library from SPIFlash to SPIMemory (for reasons listed below in reference links). Could you please remove my SPIFlash library from the library manager and add the SPIMemory library instead?

Repo is here: https://github.com/Marzogh/SPIMemory
Most recent tag is here: https://github.com/Marzogh/SPIMemory/releases/tag/v3.2.0

For reference:
Original SPIFlash add request: https://github.com/arduino/Arduino/issues/3199
Reason for name change: https://github.com/Marzogh/SPIFlash/issues/83
Also re: https://github.com/arduino/Arduino/issues/6904

Thanks in advance! 😄

**Comment by cmaglie** [comment]
Done!
