### ISSUE TITLE
Add includes field to Library Manager index and search scope

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#7604]
Often when searching for a dependency of someone's code the only information we have is the `#include` directive for the missing file and so that filename is the logical term to use in a Library Manager search query. That filename is not necessarily found in the library.properties fields currently used by the Library Manager search.

Adding the library.properties `includes` field to the Library Manager search scope will increase the chances of finding a library by searching for the primary header filename.

This will require adding that field to the [Library Manager index JSON file](http://downloads.arduino.cc/libraries/library_index.json).

**Comment by cmaglie** [comment]
The field is now available on the library_index.json as `providesIncludes`. I've extended the search on the Library Manager too.
