### ISSUE TITLE
Code not verifying or uploading

### ISSUE THREAD

**Issue by Farhan1610001** [arduino/Arduino#7605]
I tried to upload an example code titled R02_line_follow. But it was not working and gave this error message :
Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\examples\explore\R02_Line_Follow\R02_Line_Follow.ino: In function 'void setup()':

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\examples\explore\R02_Line_Follow\R02_Line_Follow.ino:35:31: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   Robot.drawBMP("lf.bmp", 0, 0); // display background image

                               ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\examples\explore\R02_Line_Follow\R02_Line_Follow.ino:37:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

   Robot.playFile("chase.sqm");  // play a song from the SD card

                             ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp: In constructor 'RobotControl::RobotControl()':

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:26:42: error: 'LCD_CS' was not declared in this scope

 RobotControl::RobotControl():Arduino_LCD(LCD_CS,DC_LCD,RST_LCD){

                                          ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:26:49: error: 'DC_LCD' was not declared in this scope

 RobotControl::RobotControl():Arduino_LCD(LCD_CS,DC_LCD,RST_LCD){

                                                 ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:26:56: error: 'RST_LCD' was not declared in this scope

 RobotControl::RobotControl():Arduino_LCD(LCD_CS,DC_LCD,RST_LCD){

                                                        ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp: In member function 'void RobotControl::begin()':

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:36:21: error: 'MUXA' was not declared in this scope

  uint8_t MuxPins[]={MUXA,MUXB,MUXC,MUXD};

                     ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:36:26: error: 'MUXB' was not declared in this scope

  uint8_t MuxPins[]={MUXA,MUXB,MUXC,MUXD};

                          ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:36:31: error: 'MUXC' was not declared in this scope

  uint8_t MuxPins[]={MUXA,MUXB,MUXC,MUXD};

                               ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:36:36: error: 'MUXD' was not declared in this scope

  uint8_t MuxPins[]={MUXA,MUXB,MUXC,MUXD};

                                    ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:37:29: error: 'MUX_IN' was not declared in this scope

  Multiplexer::begin(MuxPins,MUX_IN,4);

                             ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:40:10: error: 'BUZZ' was not declared in this scope

  pinMode(BUZZ,OUTPUT);

          ^

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Robot_Control\src\ArduinoRobot.cpp:43:2: error: 'Serial1' was not declared in this scope

  Serial1.begin(9600);

  ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
That code is written for the Arduino Robot Control. You're compiling for the Arduino Uno, thus the errors.

This issue tracker is only to be used to report bugs or feature requests. In the future please only submit issue reports here if you have found a verified bug. Support requests such as this one should be made to the [Arduino Forum](forum.arduino.cc/).
