### ISSUE TITLE
Serial

### ISSUE THREAD

**Issue by MahmoudSB** [arduino/Arduino#7606]
Hello,
I am making a robot with Arduino UNO.
for adjusting the parameter of the robot I need to save some information during some practical tests.
to achieve this information, I made a 100-dimensional array and save my data inside and after the test, I tried to read the array through the serial monitor.
but I have figured out that when I run the serial monitor, all variable values are changed to zero and if I want to perform like that i should be connected to Arduino and the serial monitor window should be opened during the test, which is not possible in this case.
please let me know, how can I  derive the information, from the serial monitor without making them zero.

Best regards
Mahmoud Shirdast

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
