### ISSUE TITLE
Library contribution

### ISSUE THREAD

**Issue by kosme** [arduino/Arduino#7607]
I just uploaded an Arduino library to generate 32 bits timestamps compatible with UNIX format.
https://github.com/kosme/timestamp32bits

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by kosme** [comment]
Sorry about that. Now there is a release

**Comment by cmaglie** [comment]
Done
