### ISSUE TITLE
writePort() doesn't return a value [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#761]
This is [Issue 761](http://code.google.com/p/arduino/issues/detail?id=761) moved from a Google Code project.
Added by 2011-12-25T00:13:42.000Z by [gooc...@top.geek.nz](http://code.google.com/u/105104457273146163885/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

../src/Boards.h: In function 'unsigned char writePort(byte, byte, byte)':
../src/Boards.h:355: warning: no return statement in function returning non-void

The function appears to be unused by both core and standard libraries. It doesn't return any value, although it's declared to return uchar.
It's a bit unclear to me what the purpose of a return value might be - if it's ignored anyway, please return void and avoid useless code bloat. Problem exists regardless of whether ARDUINO_PINOUT_OPTIMIZE is defined.

Btw you find these problems easily by compiling with better warning options than just -Wall before release...

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Arduino 1.0. IDE if for Linux, but that's irrelevant here, as is the CPU type (other than that it's AVR8).

**Comment by sandeepmistry** [comment]
Closing, I no longer see a reference of sign of ```writePort``` in the current AVR core.
