### ISSUE TITLE
[Library Manager] Can my library be added?

### ISSUE THREAD

**Issue by Tvde1** [arduino/Arduino#7611]
I've made a library to dynamically add and remove saved wifi networks for the esp8266.
This is useful when you want to use an esp8266 with multiple networks, or if you know that you're not going to be able to upload a changed sketch when you switch routers.

I just don't like hardcoding stuff :)

Here's the link:  
https://github.com/Tvde1/WiFiPicker

It's compilant with all the rules at the FAQ.

**Comment by cmaglie** [comment]
Library added, sorry for the delay.
