### ISSUE TITLE
Analogs reading

### ISSUE THREAD

**Issue by r3d9u11** [arduino/Arduino#7618]
Hi. I have trouble with analog pins on my Adruino Uno: I have a physically connected  pin A0 and with some level (for example 2.2V) and some code:
```
...
analogRead(A0);
Serial.println(analogRead(A0));
delay(10);

analogRead(A1);
Serial.println(analogRead(A1));
delay(10);

analogRead(A2);
Serial.println(analogRead(A2));
delay(10);
...
```
this code must return something like a:
```
465
0
0
```
but pins A1 and A2 also have same level and will out something like a:
```
465
463
465
```
I can't looking a complete solution for this situation. What I'm doing wrong?
Is it possible to read different levels on different pins?

Thanks.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
