### ISSUE TITLE
Warnings with PROGMEM in extern declaration [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#762]
This is [Issue 762](http://code.google.com/p/arduino/issues/detail?id=762) moved from a Google Code project.
Added by 2011-12-25T05:33:06.000Z by [gooc...@top.geek.nz](http://code.google.com/u/105104457273146163885/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Arduino 1.0, file Arduino.h declares a number of variables like this

extern const uint8_t PROGMEM digital_pin_to_port_PGM[];

This produces warnings with -Wall from avr-gcc 4.6.2

/usr/local/pckg/arduino/arduino-1.0/hardware/arduino/cores/arduino/Arduino.h:130:30: warning: uninitialized variable 'digital_pin_to_port_PGM' put into program memory area [-Wuninitialized]

Comparing the output of avr-objdump shows that the PROGMEM can be removed from the extern declaration without change to the compiled code.

**What steps will reproduce the problem?**
1. Compile your favourite sketch using some Arduino pins with avr-gcc 4.6.2.

**What version of the Arduino software are you using? On what operating**
system?

Vanilla avr-gcc 4.6.2, avr-libc 1.7.1, Linux, 328P.

Patch attached.

**Comment by Chris--A** [comment]
These warnings do not show with the newer compiler.

**Comment by sandeepmistry** [comment]
Closing, as per @Chris--A's comment, these warnings no longer appear in the latest AVR core.
