### ISSUE TITLE
[Library manager] STEMI hexapod library 

### ISSUE THREAD

**Issue by epicfoox** [arduino/Arduino#7627]
Dear Arduino Community,

Please add our new library for controlling and programming STEMI hexapod v2 robot : 
https://github.com/stemi-education/stemi-hexapod

Thanks!
-Luka & STEMI dev team

**Comment by epicfoox** [comment]
STEMI hexapod v2 robot can be seen on [this link](http://stemi.education/).

**Comment by cmaglie** [comment]
Done!
