### ISSUE TITLE
Library update 

### ISSUE THREAD

**Issue by RobolinkInc** [arduino/Arduino#7634]
I already made tag for update but not update now can you let me know what's the problem is?

**Comment by per1234** [comment]
The repository in question:
https://github.com/RobolinkInc/CoDrone
For some reason you removed the `name` field from your library.properties after the 1.5.3 release:
https://github.com/RobolinkInc/CoDrone/commit/ce4a4c088307e13135e262bb3a7e88991f11d361#diff-ea32f5b85735296fd64b577e91a19607L1
This caused your library to become invalid and so the 1.5.4 and 1.5.5 releases were not added to the Library Manager index.

**Comment by RobolinkInc** [comment]
Thank you

**Comment by RobolinkInc** [comment]
thank you
