### ISSUE TITLE
arduino don't open

### ISSUE THREAD

**Issue by fafa2017** [arduino/Arduino#7646]
i can't open arduino-1:1.8.5-3 on fedora 28 
Show me this message:
java.awt.HeadlessException
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
	at processing.app.Base.<init>(Base.java:206)
	at processing.app.Base.main(Base.java:135)

What is solved?

**Comment by per1234** [comment]
Please install the official Arduino IDE from:
https://www.arduino.cc/en/Main/Software
The Arduino IDE you get from the package managers are unofficial modified versions and so you may encounter strange problems.
