### ISSUE TITLE
[Library Manager] New library - OpenTherm Arduino/ESP8266 Library

### ISSUE THREAD

**Issue by ihormelnyk** [arduino/Arduino#7652]
Hi,

I've created an OpenTherm Arduino/ESP8266 Library located on GitHub https://github.com/ihormelnyk/opentherm_library
I would like to publish it to Library Manager.

OpenTherm Library is based on OpenTherm protocol specification v2.2 and works with all OpenTherm compatible boilers.

Thanks,
Ihor Melnyk

**Comment by cmaglie** [comment]
A library named `OpenTherm` [already exists](https://github.com/jpraus/arduino-opentherm.git), please choose another name

**Comment by ihormelnyk** [comment]
Hi @cmaglie ,
I've changed library name to "OpenTherm Library"

Thanks,
Ihor Melnyk

**Comment by cmaglie** [comment]
done
