### ISSUE TITLE
Re: wrong jpeg header with OV5642 camera shield (Arducam-M-5MP) 

### ISSUE THREAD

**Issue by arduino123456** [arduino/Arduino#7653]
I am using an Arducam Mini module camera shield 5MP plus OV5642 with ESP8266 UNO board. I am trying to capture an image and write to SD card in JPEG mode.

Attached is the sketch that I am using. I added the "camera_debug" function to debug the issue. Here are the list of items I checked.

a.) SPI interface - ok. Using SPI_CS 16
b.) SD card SD_CS is 0. Checked that I can write and read a simple pattern to the SD card
c.) OV5642 module is getting detected based on the messages on the serial monitor. However, no image is written to the SD card. When I tried to print the JPEG header bytes on the serial monitor, they were 0xBFD8 instead of 0xFFD8. ``

I am using Arduino IDE 1.8.5. Any pointers greatly appreciated. Thanks.

//This demo can only work on ARDUCAM_SHIELD_V2  platform.
#if !(defined (ARDUCAM_SHIELD_V2)&&(defined (OV5640_CAM) ||defined (OV5642_CAM)||defined (OV2640_CAM)))
#error Please select the hardware platform and camera module in the ../libraries/ArduCAM/memorysaver.h file
#endif
#if defined(ESP8266)
 #define SD_CS 0 
 const int SPI_CS = 16;
#else 
 #define SD_CS 9 
 const int SPI_CS =10;
#endif
#if defined (OV2640_CAM)
  ArduCAM myCAM(OV2640, SPI_CS);
#elif defined (OV5640_CAM)
  ArduCAM myCAM(OV5640, SPI_CS);
#elif defined (OV5642_CAM)
  ArduCAM myCAM(OV5642, SPI_CS);
#endif
void myCAMSaveToSDFile(){
char str[8];
byte buf[256];
static int i = 0;
static int k = 0;
uint8_t temp = 0, temp_last = 0;
uint32_t length = 0;
bool is_header = false;
File outFile;
//Flush the FIFO
myCAM.flush_fifo();
//Clear the capture done flag
myCAM.clear_fifo_flag();
//Start capture
myCAM.start_capture();
Serial.println(F("Start Capture"));
while(!myCAM.get_bit(ARDUCHIP_TRIG , CAP_DONE_MASK));
Serial.println(F("Capture Done."));  
length = myCAM.read_fifo_length();
Serial.print(F("The fifo length is :"));
Serial.println(length, DEC);
if (length >= MAX_FIFO_SIZE) //8M
{
  Serial.println(F("Over size."));
  return ;
}
if (length == 0 ) //0 kb
{
  Serial.println(F("Size is 0."));
  return ;
}
//Construct a file name
k = k + 1;
itoa(k, str, 10);
strcat(str, ".jpg");
//Open the new file
outFile = SD.open(str, O_WRITE | O_CREAT | O_TRUNC);
if(! outFile){
  Serial.println(F("File open faild"));
  return;
}
i = 0;
myCAM.CS_LOW();
myCAM.set_fifo_burst();
while ( length-- )
{
  temp_last = temp;
  temp =  SPI.transfer(0x00);
  //Read JPEG data from FIFO
  if ( (temp == 0xD9) && (temp_last == 0xFF) ) //If find the end ,break while,
  {
    buf[i++] = temp;  //save the last  0XD9     
    //Write the remain bytes in the buffer
    myCAM.CS_HIGH();
    outFile.write(buf, i);    
    //Close the file
    outFile.close();
    Serial.println(F("Image save OK!"));
    is_header = false;
    i = 0;
  }  
  if (is_header == true)
  { 
    //Write image data to buffer if not full
    if (i < 256)
    buf[i++] = temp;
    else
    {
      //Write 256 bytes image data to file
      myCAM.CS_HIGH();
      outFile.write(buf, 256);
      i = 0;
      buf[i++] = temp;
      myCAM.CS_LOW();
      myCAM.set_fifo_burst();
    }        
  }
  else if ((temp == 0xD8) & (temp_last == 0xFF))
  {
    is_header = true;
    buf[i++] = temp_last;
    buf[i++] = temp;   
  } 
} 
}

// Example camera capture and write to SD for debug
void camera_debug() {
char str[16];
byte buf[256];
static int i = 0;
static int k = 0;
uint8_t temp = 0, temp_last = 0;
uint32_t length = 0;
bool is_header = false;
File outFile;
//Flush the FIFO
myCAM.flush_fifo();
//Clear the capture done flag
myCAM.clear_fifo_flag();
//Start capture
myCAM.start_capture();
Serial.println(F("Start Capture"));
while(!myCAM.get_bit(ARDUCHIP_TRIG , CAP_DONE_MASK));
Serial.println(F("Capture Done."));  
length = myCAM.read_fifo_length();
Serial.print(F("The fifo length is :"));
Serial.println(length, DEC);
if (length >= MAX_FIFO_SIZE) //8M
{
  Serial.println(F("Over size."));
  return ;
}
if (length == 0 ) //0 kb
{
  Serial.println(F("Size is 0."));
  return ;
}

// Simple debug to write a pattern to the SD card
const uint8_t pattern[4] = {0xa0, 0xbb, 0xcc, 0xdd};
const uint8_t pattern_i[4] = {1, 2, 3, 4};
Serial.print(F("Pattern is :"));
Serial.println(pattern[0], HEX);
Serial.println(pattern[1], HEX);
Serial.println(pattern[2], HEX);
Serial.println(pattern[3], HEX);
strcpy(str, "pattern.txt");
outFile = SD.open(str, FILE_WRITE);
if(! outFile){
  Serial.println(F("File open failed"));
  return;
}
outFile.println("Writing a test pattern");
outFile.println(pattern_i[0], HEX);
 
outFile.flush();
//Close the file
outFile.close();
Serial.println(F("Pattern written!"));

// read from the file until there's nothing else in it:
// re-open the file for reading:
outFile = SD.open("pattern.txt");
if (outFile) {
  while (outFile.available()) {
    Serial.write(outFile.read());
  }
  outFile.close();
} else {
  Serial.println("error opening txt");
}
//Construct a file name
k = k + 1;
itoa(k, str, 10);
strcpy(str, "cam1.jpg");
//strcat(str, ".jpg");
//Open the new file
outFile = SD.open(str, FILE_WRITE);
if(! outFile){
  Serial.println(F("File open faild"));
  return;
}
i = 0;
myCAM.CS_LOW();
myCAM.set_fifo_burst();
while ( length-- )
{
  temp_last = temp;
  temp =  SPI.transfer(0x00);
  Serial.print(F("camera temp data 2 is :"));
  Serial.println(temp, HEX);
  //Read JPEG data from FIFO
  if ( (temp == 0xD9) && (temp_last == 0xFF) ) //If find the end ,break while,
  {
    buf[i++] = temp;  //save the last  0XD9     
    //Write the remain bytes in the buffer
    Serial.print(F("camera temp data is :"));
    Serial.println(temp, HEX);
    myCAM.CS_HIGH();
    //outFile.write(buf, i);
    if (!outFile.write(buf,i))
    {
      Serial.println(F("Write to SD card failed!"));   
    } else {
      Serial.println(F("Write to SD card passed!"));
    }
    outFile.flush();
    //Close the file
    outFile.close();
    Serial.println(F("Image save OK!"));
    is_header = false;
    i = 0;
  }  
  if (is_header == true)
  { 
    //Write image data to buffer if not full
    if (i < 256)
    buf[i++] = temp;
    else
    {
      //Write 256 bytes image data to file
      //Serial.print(F("camera temp data 1 is :"));
      //Serial.println(temp, HEX);
      myCAM.CS_HIGH();
      outFile.write(buf, 256);
      outFile.flush();
      i = 0;
      buf[i++] = temp;
      myCAM.CS_LOW();
      myCAM.set_fifo_burst();
    }        
  }
  else if ((temp == 0xD8) & (temp_last == 0xFF))
  //else if ((temp == 0xD8) & (temp_last == 0xBF))
  {
    is_header = true;
    buf[i++] = temp_last;
    buf[i++] = temp;  
    //Serial.print(F("camera temp data 2 is :"));
    //Serial.println(temp, HEX);
  } 
} 
}
void setup(){
uint8_t vid, pid;
uint8_t temp;
Wire.begin();
Serial.begin(115200);
Serial.println(F("ArduCAM Start!"));
//set the CS as an output:
pinMode(SPI_CS,OUTPUT);
// initialize SPI:
SPI.begin();
while(1){
  //Check if the ArduCAM SPI bus is OK
  myCAM.write_reg(ARDUCHIP_TEST1, 0x55);
  temp = myCAM.read_reg(ARDUCHIP_TEST1);
  if (temp != 0x55){
    Serial.println(F("SPI interface Error!"));
    delay(1000);continue;
  }else{
    Serial.println(F("SPI interface OK!"));break;
  }
}
//Initialize SD Card
while(!SD.begin(SD_CS)){
  Serial.println(F("SD Card Error"));delay(1000);
}
Serial.println(F("SD Card detected."));
#if defined (OV2640_CAM)
while(1){
    //Check if the camera module type is OV2640
    myCAM.wrSensorReg8_8(0xff, 0x01);
    myCAM.rdSensorReg8_8(OV2640_CHIPID_HIGH, &vid);
    myCAM.rdSensorReg8_8(OV2640_CHIPID_LOW, &pid);
    if ((vid != 0x26 ) && (( pid != 0x41 ) || ( pid != 0x42 ))){
      Serial.println(F("Can't find OV2640 module!"));
      delay(1000);continue;
    }else{
      Serial.println(F("OV2640 detected."));break;
    }
  } 
#elif defined (OV5640_CAM)
while(1){
  //Check if the camera module type is OV5642
  myCAM.wrSensorReg16_8(0xff, 0x01);
  myCAM.rdSensorReg16_8(OV5640_CHIPID_HIGH, &vid);
  myCAM.rdSensorReg16_8(OV5640_CHIPID_LOW, &pid);
  if((vid != 0x56) || (pid != 0x40)){
    Serial.println(F("Can't find OV5640 module!"));
    delay(1000);continue;
  }else{
    Serial.println(F("OV5640 detected."));break;
  } 
  }
#elif defined (OV5642_CAM)
while(1){
  //Check if the camera module type is OV5642
  myCAM.wrSensorReg16_8(0xff, 0x01);
  myCAM.rdSensorReg16_8(OV5642_CHIPID_HIGH, &vid);
  myCAM.rdSensorReg16_8(OV5642_CHIPID_LOW, &pid);
  if((vid != 0x56) || (pid != 0x42)){
    Serial.println(F("Can't find OV5642 module!"));
    delay(1000);continue;
  } else{
   Serial.println(F("OV5642 detected.")); break;
  }
}
#endif
myCAM.set_format(JPEG);
myCAM.InitCAM();
delay(100);
#if defined (OV2640_CAM)
myCAM.OV2640_set_JPEG_size(OV2640_320x240);delay(1000);
#elif defined (OV5640_CAM)
myCAM.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
myCAM.OV5640_set_JPEG_size(OV5640_320x240);delay(1000);
#elif defined (OV5642_CAM)
//myCAM.write_reg(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);   //VSYNC is active HIGH
myCAM.set_bit(ARDUCHIP_TIM, VSYNC_LEVEL_MASK);
myCAM.clear_fifo_flag();
myCAM.write_reg(ARDUCHIP_FRAMES,0x00);
myCAM.OV5642_set_JPEG_size(OV5642_640x480);delay(1000);
#endif
delay(1000);
camera_debug();
delay(5000);
}

void loop(){
//  myCAMSaveToSDFile();
//  delay(5000);
}

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum, where I see you've already posted:
http://forum.arduino.cc/index.php?topic=550528
I'm sure we'll be able to help you with your problem over there.

**Comment by arduino123456** [comment]
ok. Thanks.
