### ISSUE TITLE
double compile [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#766]
This is [Issue 766](http://code.google.com/p/arduino/issues/detail?id=766) moved from a Google Code project.
Added by 2011-12-31T03:50:37.000Z by [practica...@gmail.com](http://code.google.com/u/109206834339219312240/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. double click on the 'compile and download button'
or
2. deselect window, then click on 'compile and download button'

What is the expected output?
the  IDE should NOT accept multiple clicks on the buttons(during a compile), since this causes problems when the code is downloaded

What do you see instead?
code failures when the bad code hits the board from the first compile, which is being recompiled, or sometimes  timeout errors.

Binary sketch size: 696 bytes (of a 258,048 byte maximum)
Binary sketch size: 696 bytes (of a 258,048 byte maximum)
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

What version of the Arduino software are you using? 

latest, but the display shows {$version}
On what operating system?  
osx
Which Arduino board are you using?
N/A

**Please provide any additional information below.**
none

**Comment by ffissore** [comment]
Merged into #3771
