### ISSUE TITLE
Arduino IDE 1.9 progress 

### ISSUE THREAD

**Issue by monouser7dig** [arduino/Arduino#7662]
- [x] Describe the issue based on the behaviour you were expecting
> work on Arduino continues 

blog announcement Oct 2017 https://blog.arduino.cc/2017/10/11/be-among-the-first-to-try-arduino-ide-1-9-beta/

https://github.com/arduino/Arduino/commits/ide-1.9.x-beta
last commit dates 28. Sept 2017
Arduino builder even older without activity in a full year.

Are both of this projects dead/ only developed internally?

would be really nice to see some progress on both ends. thanks

**Comment by facchinm** [comment]
Hi @monouser7dig ,
the commit history of the beta branch gets continuously rebased on master and the commits in there get reordered, so they do not reflect the actual development.
We are actively working on both the IDE and arduino-builder so don't worry :slightly_smiling_face:

**Comment by monouser7dig** [comment]
> We are actively working on both the IDE and arduino-builder so don't worry 🙂

thanks for the friendly response, I definitely did not look carefully enough, sorry.

A blog post one in a while/ year would not hurt IMO 👍 
Please just take my sign of disappointment as a representation of how I anticipate both tools.
thanks
