### ISSUE TITLE
if download boardmanger is goes to matlab folder why ..???

### ISSUE THREAD

**Issue by kesavanalangaramohan** [arduino/Arduino#7663]
C:\ProgramData\MATLAB\SupportPackages\R2018a\3P.instrset\arduinoide.instrset\idepkgs\staging\packages

i was used  matlab for my project.that that time my arduino link with matlab .after i uninstalled matlab and arduino ide also and i install new version arduino ide that that time i am download board manger for esp8266 .goes  show error In file included from c:\programdata\matlab\supportpackages\r2018a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:0,

                 from C:\ProgramData\MATLAB\SupportPackages\R2018a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Arduino.h:254,

                 from sketch\Wattmeter.ino.cpp:1:

c:\programdata\matlab\supportpackages\r2018a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\utility:68:28: fatal error: bits/c++config.h: No such file or directory

 #include <bits/c++config.h>
 like this how i fix help me please please ........

**Comment by per1234** [comment]
Maybe you're using a modified version of the Arduino IDE? Try installing the official Arduino IDE from https://www.arduino.cc/en/Main/Software.
