### ISSUE TITLE
arduino 

### ISSUE THREAD

**Issue by BNarasimhareddy** [arduino/Arduino#7665]
hello, friends i  got one doubt regarding the arduino, i.e what is the compiler of arduino.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to answer your question over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
