### ISSUE TITLE
Arduino IDE accesible

### ISSUE THREAD

**Issue by LuisFerduino** [arduino/Arduino#7667]
Hi, I am a blind person and I want to make stages on this platform, but my screen readers do not readme the Arduino IDE interfas, so i would like to have access at this software in order to continue making electronic projects.
My Arduino IDE versión is 1.8.5. I´ll be waiting for your answer. Thanks. Have a nice day.

**Comment by per1234** [comment]
I agree this is an important improvement for the Arduino IDE.

We already have a previous issue on this subject here:
https://github.com/arduino/Arduino/issues/5518
So I'm going to close this issue.

We welcome any specific input you might chose to add by commenting on that issue.
