### ISSUE TITLE
Please add my library for the multifunctional button into index

### ISSUE THREAD

**Issue by slavaza** [arduino/Arduino#7672]
I want propose simple of use detector of the button pressing.  Add this library into index please: https://github.com/slavaza/SuperButton  Thank you very much.

**Comment by per1234** [comment]
There is already a file named "Thread" in the Library Manager index (in fact, it's your library). I believe that may have been a copy/paste artifact in your library.properties. Please change the `name` value in your library.properties to a unique `name` value and then either create a new release/tag or redo the existing tag.

Once that's done, comment here to let us know we can proceed.

**Comment by slavaza** [comment]
Yes, it is my mistake. Excuse me, please. I hope that I fixed all.

**Comment by per1234** [comment]
That will work, but in the future you should remember to update the `version` field in library.properties before creating a release.

**Comment by cmaglie** [comment]
done

**Comment by slavaza** [comment]
Thank you very much.
