### ISSUE TITLE
I have a problem with an Arduino Mega 2560 R3 ( stk500_send(): failed to send command to serial port

### ISSUE THREAD

**Issue by FeliHD** [arduino/Arduino#7673]
I am new with the Arduino World.
I made an Led Cube with the Mega, today I 
wanted to start a new project but I cant upload it to the Arduino.

Arduino: 1.8.5 (Windows 8.1), Board: "Arduino Mega ADK"

In file included from C:\Users\User\Documents\Arduino\RfID\sketch_jun07b\sketch_jun07b.ino:3:0:

C:\Users\User\Documents\Arduino\libraries\MFRC522\src/MFRC522Extended.h: In constructor 'MFRC522Extended::MFRC522Extended(uint8_t)':

C:\Users\User\Documents\Arduino\libraries\MFRC522\src/MFRC522Extended.h:81:44: warning: 'MFRC522::MFRC522(byte)' is deprecated (declared at C:\Users\Felix\Documents\Arduino\libraries\MFRC522\src/MFRC522.h:337): use MFRC522(byte chipSelectPin, byte resetPowerDownPin) [-Wdeprecated-declarations]

  MFRC522Extended(uint8_t rst) : MFRC522(rst) {};

                                            ^
avrdude: ser_open(): can't open device "\\.\COM3": Das System kann die angegebene Datei nicht finden.

avrdude: ser_drain(): read error: Das Handle ist ungültig.

avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: ser_send(): write error: sorry no info avail
avrdude: stk500_send(): failed to send command to serial port
avrdude: ser_recv(): read error: Das Handle ist ungültig.

avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
