### ISSUE TITLE
Serial Plotter/Monitor permanently disabled if Plotter fails to open

### ISSUE THREAD

**Issue by thekakester** [arduino/Arduino#7683]
**Summary**:  If serial plotter fails to open due to a busy com port, the IDE "thinks" that it successfully opened even though it never opens up.  Serial Monitor can not be opened now because it thinks serial plotter is open, and serial plotter cant open because it thinks it is already opened.  Restart IDE to fix problem.

**Steps to reproduce:**

1. Try to open serial plotter on a busy com port
2. You will get this error (expected): "Error opening serial port 'COMX'. (Port busy)"
3. Now you can no longer open a serial plotter or monitor!
4. If you try to open serial monitor, it will give you this error: "Serial monitor not available while plotter is open"
5. If you try to open the serial plotter again, you will get no errors.

Restarting the arduino IDE fixes this problem.

**How to force a com port to be busy**
**Method 1**: Open another arduino IDE
The easiest way to do this without extra software is to open a second instance of arduino IDE.  This should result in two icons in your task bar.  If there's just one icon, all the windows will share the same port settings.  Open a serial monitor/plotter in the first instance of the arduino IDE.  Use the second instance of the arduino IDE for testing mentioned above.

**Method 2**: Serial terminal (software)
Download a serial terminal (like "Serial Port Monitor" by [Eltima Software](https://www.eltima.com/products/serial-port-monitor/)
Use this to open a com port.

**Comment by facchinm** [comment]
Fixed by  fa51a39, should land in hourly soon :slightly_smiling_face:
