### ISSUE TITLE
"--version" flag is not recognized

### ISSUE THREAD

**Issue by jmchiappa** [arduino/Arduino#7686]
In commandlineParser.java, ACTION.VERSION isn't parsed and treated.
Something like this should be added  :
```
public void parseArgumentsPhase1() {
...
if (a == ACTION.VERSION) {
// action to display version number in console
        }
}
```

**Comment by per1234** [comment]
Did you try the [hourly build](https://www.arduino.cc/en/Main/Software#hourly) of the Arduino IDE? Because that feature was added 3 weeks ago:
https://github.com/arduino/Arduino/pull/7549

**Comment by jmchiappa** [comment]
That's perfect ! :+1: 
Thank you for your quick reply !
Now I will wait for the 1.8.6 release. I hope that it will come soon :-)
