### ISSUE TITLE
Please add our OLED library

### ISSUE THREAD

**Issue by durydevelop** [arduino/Arduino#7692]
Please add our library:
https://github.com/durydevelop/arduino-lib-oled

Thanks.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by durydevelop** [comment]
ok now match, sorry

**Comment by per1234** [comment]
There are still no tags or releases:
https://github.com/durydevelop/arduino-lib-oled/tags

Did you maybe forget to push it to GitHub?

**Comment by durydevelop** [comment]
Sorry, I'm newbie on it, I missed to explicit push the tag.
So, now may be ok.

**Comment by cmaglie** [comment]
done
