### ISSUE TITLE
[1.9-beta] strange message during installation on xubuntu

### ISSUE THREAD

**Issue by aster94** [arduino/Arduino#7693]
hello,
i am on linux 64 bit, xubuntu

i just downloaded the build71 of the beta
`arduino-PR-beta1.9-BUILD-71 $ ./install.sh
Adding desktop shortcut, menu item and file associations for Arduino IDE...Could not parse file "/home/vincenzo/.local/share/applications/xfce4-clipman.desktop": Key file contains line ?GNOME;? which is not a key-value pair, group, or comment
Could not parse file "/home/vincenzo/.local/share/applications/xfce4-notes.desktop": Key file contains line ?GNOME;? which is not a key-value pair, group, or comment
 done!
`

then i tried run it with sudo:
`sudo ./install.sh
[sudo] password for vincenzo: 
Adding desktop shortcut, menu item and file associations for Arduino IDE...
Could not parse file "/home/vincenzo/.local/share/applications/xfce4-clipman.desktop": Key file contains line ?GNOME;? which is not a key-value pair, group, or comment
Could not parse file "/home/vincenzo/.local/share/applications/xfce4-notes.desktop": Key file contains line ?GNOME;? which is not a key-value pair, group, or comment
 done!
`

Could it be possibly related to xfce?

edit: i was wrong the installation works, the ide starts and compile correctly, i changed the title

**Comment by facchinm** [comment]
Well, the files provoking the error are part of your local installation (`/home/vincenzo/.local/share/applications/xfce4-notes.desktop`) so one of `xdg-install` or `xdg-uninstall` are failing (see https://github.com/arduino/Arduino/blob/master/build/linux/dist/install.sh#L241 for the complete code being executed).
My 2 cents: you can safely remove that files if you don't use `xfce4-clipman` or `xfce4-notes` , but it may mess up a bit with your package manager (nothing terrible anyway :slightly_smiling_face:  )
