### ISSUE TITLE
[Library Manager] Please add Esp32 Wifi implementation of SimplePacketComs

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#7698]
https://github.com/madhephaestus/Esp32SimplePacketComs

This library adds Wifi based UDP support for SimplePacketComs. Now arduinos can communicate over UDP at high speed and with clearly framed and identified commands.

Thank you!

**Comment by cmaglie** [comment]
done!

**Comment by madhephaestus** [comment]
Thank you!
