### ISSUE TITLE
how to make no install version

### ISSUE THREAD

**Issue by hznupeter** [arduino/Arduino#7701]
The arduino IDE has a no install version for non admin.How to make a no install IDE including the Esp8266.  I hope to my students can use the esp8266 easily,install the esp8266 via Board Manager cost too much time.

**Comment by per1234** [comment]
You only need to use the Arduino IDE in portable mode:
https://www.arduino.cc/en/Guide/PortableIDE

This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum (http://forum.arduino.cc/). If you need any further assistance, I'm sure we'll be able to help you with your problem over there.
