### ISSUE TITLE
win 10 registry error

### ISSUE THREAD

**Issue by brianzahra** [arduino/Arduino#7711]
Registry Error 

Path to windows DriverStore is D: when it should be drive C: 

 See below. Using Windows 10 64 bit.

Arduino Version 1.8.5

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\DriverDatabase\DriverPackages\arduino.inf_amd64_6cb1adf1bc8e1d48]
"Version"=hex:00,ff,09,00,00,00,00,00,78,e9,36,4d,25,e3,ce,11,bf,c1,08,00,2b,\
  e1,03,18,00,c0,cd,0f,4b,26,d1,01,00,00,03,00,02,00,01,00,00,00,00,00,00,00,\
  00,00
"Provider"="Arduino LLC (www.arduino.cc)"
"InfName"="arduino.inf"
"OemPath"="D:\\Windows\\System32\\DriverStore\\FileRepository\\arduino.inf_amd64_6cb1adf1bc8e1d48"
"SignerName"="Arduino LLC"
"ImportDate"=hex:f0,e0,54,48,8b,f4,d3,01
"SignerScore"=dword:0f000000
"StatusFlags"=dword:00000100
@="oem29.inf"

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\DriverDatabase\DriverPackages\arduino-org.inf_amd64_bb8d72653e2c9162]
"Version"=hex:00,ff,09,00,00,00,00,00,78,e9,36,4d,25,e3,ce,11,bf,c1,08,00,2b,\
  e1,03,18,00,40,88,a4,d7,61,d0,01,00,00,01,00,01,00,01,00,00,00,00,00,00,00,\
  00,00
"Provider"="Arduino Srl (www.arduino.org)"
"InfName"="arduino-org.inf"
"OemPath"="D:\\Windows\\System32\\DriverStore\\FileRepository\\arduino-org.inf_amd64_bb8d72653e2c9162"
"SignerName"="Arduino srl"
"ImportDate"=hex:a0,fa,1b,3a,8b,f4,d3,01
"SignerScore"=dword:0f000000
"StatusFlags"=dword:00000100
@="oem12.inf"

**Comment by facchinm** [comment]
Hi @brianzahra ,
it looks like the problem is not directly related with Arduino installation process.
When installing the drivers, we simply launch 
```
Section "Install USB driver"
    ${If} ${RunningX64}
        StrCpy $dpinst "$INSTDIR\drivers\dpinst-amd64.exe"
    ${Else}
        StrCpy $dpinst "$INSTDIR\drivers\dpinst-x86.exe"
    ${EndIf}

    DetailPrint "Installing drivers..."
    ExecWait '"$dpinst" /lm /sw /sa'
```
(from the NSIS installation script). If the wrong drive letter is picked up it could be an issue with your Windows installation. `dpinst` executables are 5 years old but I doubt they changed that much in the meantime.
