### ISSUE TITLE
[Library Manager] Request to add Escornabot EXT Library

### ISSUE THREAD

**Issue by xoan** [arduino/Arduino#7713]
Escornabot EXT (codename *"Kanoi"*) is an evolution of the Escornabot project, an open source/hardware project that aims to bring robotics and programming to children.

This library contains the basic routines you need to program it yourself directly from an sketch, as well as the main firmware (as an example of the library itself).

The URL of the Escornabot EXT library repository is https://gitlab.com/xoan/escornabot-extlib

**Comment by cmaglie** [comment]
done
