### ISSUE TITLE
[Library Manager] Please add the RF Explorer 3G+ IoT library

### ISSUE THREAD

**Issue by jcalderon09** [arduino/Arduino#7715]
We have just updated our library for MWSUB3G IoT module so could you please include it in the library manager.

https://github.com/RFExplorer/RFExplorer_3GP_IoT_Arduino

...thanks.
RF Explorer Team.

**Comment by jcalderon09** [comment]
Acepted the pull request and updated library.properties version

**Comment by cmaglie** [comment]
The library is already in the index, there is no need ask for further releases, just publish a tag on github and the new release will be automatically published within an hour.
