### ISSUE TITLE
[Library Manager] Request to add NintendoExtensionCtrl Library

### ISSUE THREAD

**Issue by dmadison** [arduino/Arduino#7717]
Hello! Please add the [NintendoExtensionCtrl](https://github.com/dmadison/NintendoExtensionCtrl) library to the libraries manager. It's a library for talking to Nintendo extension controllers (Nunchuk, Wii Classic Controller, etc.) over I²C. Thank you!

URL: https://github.com/dmadison/NintendoExtensionCtrl

**Comment by cmaglie** [comment]
Done
