### ISSUE TITLE
New library version: Timer (wiring-timer 2.5.0)

### ISSUE THREAD

**Issue by dniklaus** [arduino/Arduino#7719]
https://github.com/dniklaus/wiring-timer

Universal Timer based on Arduino millis() function, supporting OOP principles and interoperating with Arduino yield() and delay() functions.

New version 2.5.0 (https://github.com/dniklaus/wiring-timer/releases/tag/2.5.0):

- yield() not supported for ESP8266 types anymore (yield() implementation on ESP8266 not working properly)
- Example sketch and README adapted.

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So you don't need to create an issue report every time you release a new version; they'll be picked up automatically.

Your 2.5.0 is already available for installation via Library Manager.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
