### ISSUE TITLE
Request to add library https://github.com/jo-seph/SDS011_vers

### ISSUE THREAD

**Issue by jo-seph** [arduino/Arduino#7720]
https://github.com/jo-seph/SDS011_vers

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jo-seph** [comment]
added and pushed tag

**Comment by cmaglie** [comment]
done
