### ISSUE TITLE
Broken links on Blink tutorial page

### ISSUE THREAD

**Issue by kaloliaalap** [arduino/Arduino#7721]
Hello, 

When I tried to access https://www.arduino.cc/reference/en/language/functions/main/setup/ 
from the page 
https://www.arduino.cc/en/Tutorial/Blink
,  

It says access is denied. 

Sorry, If it's been already resolved and I couldn't find it.

**Comment by per1234** [comment]
Thanks for reporting this @kaloliaalap!

The correct link should be:
https://www.arduino.cc/reference/en/language/structure/sketch/setup/

The same issue also occurs on that page for the link to the `loop()` reference page:
https://www.arduino.cc/en/Reference/Loop
which redirects to:
https://www.arduino.cc/reference/en/language/functions/main/loop/
but instead should redirect to:
https://www.arduino.cc/reference/en/language/structure/sketch/loop/

**Comment by per1234** [comment]
We need to leave this open until it's fixed.

**Comment by gabru-md** [comment]
Is someone working on this issue? :sweat_smile:

**Comment by per1234** [comment]
All redirects for links on the Blink tutorial page are now working correctly for me so I'm closing this.
