### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by mgrebnev** [arduino/Arduino#7728]
I have a .ttf file and I want to make it the main font. How to set custom font in Arduino IDE?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
