### ISSUE TITLE
MacOS 'close window' terminates application

### ISSUE THREAD

**Issue by a7hybnj2** [arduino/Arduino#7730]
For MacOS

Current behavior: When you close the open windows the application terminates.

Desired behavior: When you close the open windows keep the application running as just a menu. It would still populate the 'dock' and you could still alt+tab to focus it. Then you could open or new another instance.

Many IDE's, text editors, and other applications have my 'desired behavior': mvim, sublime, atom, kicad, steam, ect...

**Comment by marcelstoer** [comment]
Not sure if this is the standard behavior with Java desktop applications on macOS but it's definitely annoying.

**Comment by kosso** [comment]
This sort of thing is certainly optional when it comes to apps built with Electron.  Java should also have that option.

**Comment by facchinm** [comment]
https://github.com/arduino/Arduino/pull/8023 should solve the issue :slightly_smiling_face:

**Comment by a7hybnj2** [comment]
I am going to close this... version 1.9 has this functionality which is totally awesome! Thanks!
