### ISSUE TITLE
[Question] 2 different configurations for astyle

### ISSUE THREAD

**Issue by Rotzbua** [arduino/Arduino#7733]
Different configuration files for astyle exists. Shouldn't they be the same?

https://github.com/arduino/Arduino/blob/master/build/shared/lib/formatter.conf
https://github.com/arduino/Arduino/blob/master/build/shared/examples_formatter.conf

Best

**Comment by facchinm** [comment]
Hi @Rotzbua ,
the formatter "in use" is formatter.conf (https://github.com/arduino/Arduino/blob/master/app/src/cc/arduino/packages/formatter/AStyle.java#L45). The other one is only used to format the examples so the rules are a bit stricter than the normal autoformatter.
