### ISSUE TITLE
Arduino what adapter page is wrong and can cause harm.

### ISSUE THREAD

**Issue by spoter368** [arduino/Arduino#7736]
The page https://playground.arduino.cc/Learning/WhatAdapter explicitly states at the bottom that the built in voltage regulator can take 20V+ DC. To quote "The Arduino's on-board regulator can actually handle up to 20V or more" This is incorrect and resulted in the loss of 2 of my arduinos including one that caught fire. I was powering at 22V. Looking at the [datasheet for the voltage regulator IC](https://www.mouser.com/datasheet/2/146/SPX1117_DS_R210_082411-52780.pdf) the absolute maximum the Uno can take is 20V. This should be fixed immediately as it is a danger to Arduino users.

**Comment by per1234** [comment]
The Arduino Playground is a publicly editable wiki. The Arduino community is responsible for the content of the Playground so it is not appropriate to create issue reports about it in this repository. I have updated the Playground page:
https://playground.arduino.cc/Learning/WhatAdapter?action=diff
