### ISSUE TITLE
Arduino Nano I2C pins still wrong on product page

### ISSUE THREAD

**Issue by Ojsh** [arduino/Arduino#7739]
Hello

There is a lack of clarity on the documentation page for Arduino Nano regarding pins designated for I2C comms. (here - https://store.arduino.cc/usa/arduino-nano)

"I2C: 4 (SDA) and 5 (SCL). Support I2C (TWI) communication using the Wire library (documentation on the Wiring website)."
Yes this paragraph follows a short discussion of Analog Pins - however for clarity, it should be made explicit that the sentence refers to pins A4 and A5. Not Digital pins 4, 5.

Could help a few people out - still see posts in forums with confusion as to why I2C isn't working w Nano boards.

Cheers

**Comment by agdl** [comment]
Done thanks

**Comment by PizzaProgram** [comment]
Agree. This picture is much easier to understand than these:
 https://store.arduino.cc/arduino-nano
 https://content.arduino.cc/assets/Pinout-NANO_latest.pdf

 (Found **I2C** Bus A4+A5 pins within 5 sec.)

Thanks for sharing!

**Comment by bmwest-wa** [comment]
the power of the internet .... I too wasted hours and started suspecting iI'm looking in the wrong place so did a search for "i2c nano problem" that took me here ...
