### ISSUE TITLE
Adding a library

### ISSUE THREAD

**Issue by Jorropo** [arduino/Arduino#7760]
I follow contributing guidelines to add this lib :
https://github.com/Jorropo/ds3231
This is a reborn of the old ds3231 made by [Rodan](https://github.com/rodan/ds3231/).

**Comment by cmaglie** [comment]
done!

**Comment by njh** [comment]
@Jorropo It looks like this repo has now been deleted. Any information about why?

**Comment by Jorropo** [comment]
@njh I was not maintaining it and there is better alternative. (the original is still available here https://github.com/rodan/ds3231/ with the same api).
