### ISSUE TITLE
Typo: Arduino Yún, not Yùn

### ISSUE THREAD

**Issue by hyiltiz** [arduino/Arduino#7763]
I hope this page is part of the "Documentation", thus this is the correct place to report this typo. If not, feel free to tell me where. 

https://www.arduino.cc/en/Products.Compare

![image](https://user-images.githubusercontent.com/3246683/42394843-91eadd34-8129-11e8-8a46-dfba4649d229.png)

**Comment by AFZL210** [comment]
Hi, im new to opensource may i try to resolve this typo bug

**Comment by per1234** [comment]
Thanks for your report @hyiltiz!

I see that the referenced page is now no longer accessible.

The only remaining occurrence of this spelling I found was on the release blog post:

https://blog.arduino.cc/2018/03/29/arduino-yun-rev-2-is-here/

I don't know that it makes sense to edit a blog post after the fact, so I will close this as resolved. 

If anyone spots an outstanding occurrence of it in other official content, please comment here and I'll investigate.
