### ISSUE TITLE
Compiler allows same identifier for #define label and function name

### ISSUE THREAD

**Issue by JesperBarfod** [arduino/Arduino#7764]
While recently, using IDE 1.8.5, reviving a project from 2014, last compiled in 2016, but probably with the 2014 version if the IDE, I got the error message, that pinin() was "not defined in the present scope".

Having forgotten that I defined the function and why, I quickly introduced the macro #define pinin digitalRead" in the start of the code and compilation worked without errors (!) despite the fact, that a function pinin(port) was actually defined later in the code. (pinin() inverts the port reading).
However program function failed (of cause) because of the duplicate and contradictory definition of pinin.

Moving the function definition of pinin() to a place in the code before the first use of the function (and removing the falsely introduced macro definition) solved the problem.

I suggest that an error is issued by the compiler if a name used in macro assignment (#define) collides with the name of a function.

To explain the error message encountered in 2018 I believe, that sometime between 2014(2016) and 1.8.5 version of the IDE a symbol table generation pass in the compiler has been modified or omitted probably for speed reasons.

Best regards

Jesper Barfod

**Comment by per1234** [comment]
The key is to avoid use of the preprocessor unless there is no other option.

The Arduino IDE just uses standard compilers so this request is outside the scope of the Arduino project.

>To explain the error message encountered in 2018 I believe, that sometime between 2014(2016) and 1.8.5 version of the IDE a symbol table generation pass in the compiler has been modified or omitted probably for speed reasons.

It sounds like a function prototype generation failure to me.
