### ISSUE TITLE
[Library Manager] UC121902-TNARX-A LCD Display

### ISSUE THREAD

**Issue by niccokunzmann** [arduino/Arduino#7774]
The UC121902-TNARX-A is an LCD display. This library allows controlling the display: printing numbers, strings and controlling the symbols on it.

I request to add it to the library manager.

Repository URL: https://github.com/niccokunzmann/UC121902-TNARX-A

Related: https://github.com/niccokunzmann/UC121902-TNARX-A/issues/3#issuecomment-403794123

**Comment by cmaglie** [comment]
Done
