### ISSUE TITLE
Wrong example code for WiFi library Simple WebServer WiFi

### ISSUE THREAD

**Issue by EffC00k** [arduino/Arduino#7775]
In this page:
https://www.arduino.cc/en/Tutorial/LibraryExamples
The example code for the Simple WebServer WiFi:
https://www.arduino.cc/en/Tutorial/SimpleWebServerWiFi
seems to be the same as the example for the WiFi Web Server:
https://www.arduino.cc/en/Tutorial/WiFiWebServer

The former is supposed to turn on/off an Arduino LED, but it sends back
the value of 5 analog inputs just like the second example.

Also, the code does work for reporting the analog inputs, but the printWifiStatus
function is never called and the IP address does not print out, making it difficult to
know the assigned IP address.

Swapping the last two lines in setup () allows the IP address to print, making it
possible to enter the address in a remote machine's web browser.

Swapped lines:
```cpp
  // you're connected now, so print out the status:
  printWifiStatus();

  server.begin();
```
I know this is obsolete hardware, but the examples should be correct.

**Comment by per1234** [comment]
Thanks for reporting this @EffC00k

The WiFi library's SimpleWebServerWiFi example does have the expected LED code so the issue is isolated to the website:
https://github.com/arduino-libraries/WiFi/blob/master/examples/SimpleWebServerWiFi/SimpleWebServerWiFi.ino

**Comment by EffC00k** [comment]
Thanks, I was able to use the github link to download the code, it works as advertised.

**Comment by per1234** [comment]
We need to leave this open until the error on the arduino.cc page has been fixed.
