### ISSUE TITLE
Assigning values in Global scope is not working [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#778]
This is [Issue 778](http://code.google.com/p/arduino/issues/detail?id=778) moved from a Google Code project.
Added by 2012-01-07T06:08:48.000Z by [fran...@franfran.com](http://code.google.com/u/113167616930128213257/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

The variable declared in the Global scope is not functional inside the loop() function. e.g.

int x = 1;
int y = x;

loop(){
  //y is not == 1
}

Once I put the line "Serial.begin(9600)" inside the setup() function, the code just works fine. e.g.

int x = 1;
int y = x;

setup(){
  Serial.begin(9600);
}
loop(){
  //y is now == 1
}

**What is the expected output? What do you see instead?**

I have create a video to demonstrate the issue:
http://www.youtube.com/watch?v=VKjBnSz1ZZs

We also has a full discussion in the Arduino forum:
http://arduino.cc/forum/index.php/topic,85745.0.html

What version of the Arduino software are you using? 
Arduino IDE 1.0

On what operating system?  
Mac OSX Lion

Which Arduino board are you using?
Arduino UNO(328)

**Please provide any additional information below.**
Full source code attached.

Thank you!

**Comment by sandeepmistry** [comment]
This seems ok now, the following sketch lights up the built-in LED on the Uno:

```arduino
int x = 1;
int y = x;

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  if (y == 1) {
    digitalWrite(13, HIGH);
  }
}
```
