### ISSUE TITLE
Why am i not able to add the Servo Library in my arduino with adafruits Wave HC library?

### ISSUE THREAD

**Issue by RMucc** [arduino/Arduino#7781]
I have tried a couple of ways to get past this annoying text that keeps showing up.

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\rjmuc\OneDrive\Documents\Arduino Codes\Skeleton Project\Combined_Skeleton_and_Voice\Combined_Skeleton_and_Voice.ino: In function 'void loop()':

C:\Users\rjmuc\OneDrive\Documents\Arduino Codes\Skeleton Project\Combined_Skeleton_and_Voice\Combined_Skeleton_and_Voice.ino:80:24: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

 playfile("PIRATESS.WAV");

                        ^

libraries\WaveHC\WaveHC.cpp.o (symbol from plugin): In function `WaveHC::readWaveData(unsigned char*, unsigned int)':

(.text+0x0): multiple definition of `__vector_11'

libraries\Servo\avr\Servo.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

but its just not enough. I am having trouble and i just need some help. I hope you can help. ;-;

**Comment by PaulStoffregen** [comment]
You're asking in the wrong place.  The forum is the place to ask questions.

But briefly, this is the error when 2 libs try to use the same timer.  It's not a bug, but a limit of the board you're using.

Again, ask for help on the forum.  This place is for reporting software defects.  The forum is for getting help with your project.
