### ISSUE TITLE
add WebServer_tng Library

### ISSUE THREAD

**Issue by franzel61** [arduino/Arduino#7785]
can you please add this library as well
https://github.com/bbx10/WebServer_tng

thanks

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by cmaglie** [comment]
@franzel61 
please reopen the issue when you're ready
