### ISSUE TITLE
please add updated https://github.com/jo-seph/SDS011_vers

### ISSUE THREAD

**Issue by jo-seph** [arduino/Arduino#7791]
TABS in keywords.txt added

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So you don't need to create an issue report every time you release a new version; they'll be picked up automatically. In fact, I see your 0.1.1 release has already been picked up.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
