### ISSUE TITLE
[Library Manager] Please add the LINE-Notify library  new version2.2

### ISSUE THREAD

**Issue by TridentTD** [arduino/Arduino#7800]
Hello

Here is a LINE-Notify library for ESP8266 & ESP32. new version 2.2
Can send message , LINE's sticker or picture to LINE application.

https://github.com/TridentTD/TridentTD_LineNotify

Best regards
TridentTD.

**Comment by cmaglie** [comment]
The library is already added, no need to ask for new releases, just make a new git tag and it will be published automatically. Our indexer checks for new releases every hour.
