### ISSUE TITLE
[Library Manager] please add MatrixMath library

### ISSUE THREAD

**Issue by eecharlie** [arduino/Arduino#7802]
Hello, this library has been available in some ad-hoc form on the Arduino wiki for some time, but I've finally cleaned it up and packaged it nicely for inclusion in the library manager.

Repo: https://github.com/eecharlie/MatrixMath

Relevant Arduino playground page (I will update): https://playground.arduino.cc/Code/MatrixMath

Anytime I post about this, I try to also mention that a newer and better library is https://github.com/tomstewart89/BasicLinearAlgebra (already available in Library Manager)

**Comment by cmaglie** [comment]
Done!
