### ISSUE TITLE
[Library Manager] Please add GoProControl library

### ISSUE THREAD

**Issue by aster94** [arduino/Arduino#7803]
link:
https://github.com/aster94/GoProControl

**Comment by per1234** [comment]
You need to do a few things before the library can be added to the Library Manager index:
- Add a `maintainer` field to library.properties
- Add a `paragraph` field to library.properties
- Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After you've done this, please comment here so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by aster94** [comment]
I did the changes, i am sorry i thought i could remove those field from the library.properties; the _include_ isn't needed?
added also a tag/release

**Comment by aster94** [comment]
edit: corrected small errors in library.properties now it should be correct

**Comment by cmaglie** [comment]
Done
