### ISSUE TITLE
[Library Manager] SerialUtil library

### ISSUE THREAD

**Issue by AlexanderLL95** [arduino/Arduino#7809]
Please add the following library to the Library Manager:

https://github.com/AlexanderLL95/SerialUtil

It's an easy to use library to send/recieve data like integers, floats, booleans, text to another Arduino.
Only a little setup is required in the setup method and the callback methods will do the rest of the work in youre sketch.

Thanks,
Alexander

**Comment by cmaglie** [comment]
Done
