### ISSUE TITLE
[Library Manager] Please add new library USBControllerLib

### ISSUE THREAD

**Issue by NicholasBerryman** [arduino/Arduino#7810]
Please add the following library:
https://github.com/NicholasBerryman/USBControllerLib

Thanks,
Nick Berryman.

**Comment by cmaglie** [comment]
Done, but there is a problem in the `library.properties`, you named the parameter `sentences` with the ending `s` but it must be `sentence`: 
https://github.com/NicholasBerryman/USBControllerLib/blob/master/library.properties#L5

and `author` has a typo (you wrote `austhor`):
https://github.com/NicholasBerryman/USBControllerLib/blob/master/library.properties#L3

To fix this:
1) edit the library.properties file to fix the error above
2) commit & push
3) remove the tag 0.9.0 tag and redo it on the new master

once done the library will be published automatically within an hour, if this don't happen reopen the issue and we will sort this out.


```
JOB 1668 - 2018/07/26 14:02:47 Scraping https://github.com/NicholasBerryman/USBControllerLib.git
JOB 1668 - 2018/07/26 14:02:49 Checking out tag: 0.8.0
JOB 1668 - 2018/07/26 14:02:49 Error syncing library: Error generating library from repo: 'author' field must be defined,'sentence' and 'url' fields must be defined
JOB 1668 - 2018/07/26 14:02:49 Checking out tag: 0.9.0
JOB 1668 - 2018/07/26 14:02:49 Error syncing library: Error generating library from repo: 'author' field must be defined,'sentence' and 'url' fields must be defined
```
