### ISSUE TITLE
[Library Manager] please add SensorFusion

### ISSUE THREAD

**Issue by aster94** [arduino/Arduino#7811]
https://github.com/aster94/SensorFusion

**Comment by per1234** [comment]
Although your repository is currently compliant with the requirements for inclusion in the Library Manager index, it was not at the time the 1.0.0 tag was created. Please either redo the 1.0.0 tag or else update the `version` value in library.properties and then create a new tag.

After doing so, please comment so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by aster94** [comment]
my bad, i must have done some mistake with git, now it is corrected

**Comment by cmaglie** [comment]
Done
