### ISSUE TITLE
Don't compile library when files are in sketch directory [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#782]
This is [Issue 782](http://code.google.com/p/arduino/issues/detail?id=782) moved from a Google Code project.
Added by 2012-01-08T04:03:21.000Z by [gooc...@top.geek.nz](http://code.google.com/u/105104457273146163885/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Have a .h and .cpp in the sketch directory with those 2 files having the same name as an Arduino library in ~/sketchbook/libraries/...
2. Include the .h from the sketch directory in the sketch with "", not <>.

What is the expected output?

Program compiled correctly as the library is not used.

What do you see instead?

IDE also compiles and links the library, which doesn't work.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

IDE 0.23 and 1.0, Linux 64bit, IDE downloaded from arduino.cc.

**Comment by ffissore** [comment]
Fixed by the introduction of the "arduino-builder"
