### ISSUE TITLE
[Library Manager] Add uEEPROMLib to Library Manager

### ISSUE THREAD

**Issue by Naguissa** [arduino/Arduino#7831]
Hello,

Following Library Manager FAQ I open this issue to request adding uEEPROMLib library to Arduino repository.

Repository URL is: https://github.com/Naguissa/uEEPROMLib

It's a library to control I2C EEPROMs. I've splitted it from uRTCLib (https://github.com/Naguissa/uRTCLib) because:

1) It can control any I2C EEPROM, not only the ones present in RTCs
2) You can wish to use an EEPROM without  any RTC, so RTC functionality is only an annoyance in this case.

Thanks.

**Comment by Naguissa** [comment]
Hello?

**Comment by cmaglie** [comment]
Done, sorry for the delay!

**Comment by Naguissa** [comment]
Thanks!

No problem. It's August, somehow normal here....
