### ISSUE TITLE
[Library Manager] Please add ArduinoESPAT library

### ISSUE THREAD

**Issue by TakumiShinoda** [arduino/Arduino#7836]
Hello!

ArduinoESPAT library can link Arduino with esp8266 by AT command.
Could you add our ArduinoESPAT library to library manager?
url: https://github.com/nyampass/ArduinoESPAT-Library

 Thanks.

**Comment by per1234** [comment]
Your library.properties is missing required fields:
- `paragraph`
- `url`

Please resolve this issue and then either create a new release/tag (after updating the `version` field in library.properties) or else redo the existing tag.

After that is done please comment here so we know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by TakumiShinoda** [comment]
Edit done!
I added url and paragraph at library.properties.

I'm sorry for taking more time, If I still have problem.
Thank you for taking time.

**Comment by cmaglie** [comment]
Done, sorry for the delay!
