### ISSUE TITLE
memory leak [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#784]
This is [Issue 784](http://code.google.com/p/arduino/issues/detail?id=784) moved from a Google Code project.
Added by 2012-01-10T08:26:14.000Z by [seb.ha...@gmail.com](http://code.google.com/u/102604635817831921940/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

In

FirmataClass::setFirmwareNameAndVersion(const char *name, byte major, byte minor)

is a 

firmwareVersionVector = (byte *) malloc(firmwareVersionCount);

There should be a corresponding free()

in a (to be created) destructor:

FirmataClass::~FirmataClass()
{
    if(firmwareVersionVector)
       free(firmwareVersionVector);
}

The contructor should get a 
firmwareVersionVector = 0;

and / or 
the line could go:

    if(firmwareVersionCount)

- Sebastian Haase

**Comment by Chris--A** [comment]
@soundanalogous
What do you think of this issue, the `firmwareVersionVector` is still left dangling in your latest proposal (https://github.com/arduino/Arduino/pull/3173).

**Comment by soundanalogous** [comment]
It is freed in the rare case that setFirmwareNameAndVersion is called a second time: https://github.com/firmata/arduino/blob/master/Firmata.cpp#L146-L147 and verified via the unit test here: https://github.com/firmata/arduino/blob/master/test/firmata_test/firmata_test.ino#L128-L136. If it's important to add a deconstructor as well I could add it and add an additional unit test.

**Comment by facchinm** [comment]
Closing as fixed
