### ISSUE TITLE
[Library Manager] Please add ArduinoThingsOfValueSDK library

### ISSUE THREAD

**Issue by kyuseok-oh** [arduino/Arduino#7842]
Hello,

Please Add ArduinoThingsOfValueSDK library to library manager.

Here is URL : https://github.com/kyuseok-oh/ArduinoThingsOfValueSDK

Thank you!!!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by kyuseok-oh** [comment]
Hello,
I just finished creating a release.
Please check it.
Thank you.

**Comment by cmaglie** [comment]
Done!
