### ISSUE TITLE
Incorrect spelling of pulseIn(), pulseInLong(), and shiftIn() on reference page

### ISSUE THREAD

**Issue by scheelsmith** [arduino/Arduino#7849]
on the arduino reference page that lists functions. three of the functions appear as pulseln(), pulselnLong(), and shiftln(), instead of pulseIn(),pulseInLong(), and shsiftIn().   Just a little confusing for a few seconds.

**Comment by per1234** [comment]
Please provide a link to the page.

**Comment by per1234** [comment]
Closing due to lack of response. I've searched arduino.cc for these terms without finding anything.

@scheelsmith if you can provide a link to the reference page I'll be happy to re-open this.
