### ISSUE TITLE
[Library Manager] Please add the EZPROM library

### ISSUE THREAD

**Issue by amirchev** [arduino/Arduino#7850]
Here is the link: https://github.com/amirchev/EZPROM

Thank you,

Aleksandr Mirchev

**Comment by cmaglie** [comment]
Done!

**Comment by roboticboyer** [comment]
Please update the Library Manager because EZPROM was updated on end of December 2018

**Comment by per1234** [comment]
@roboticboyer Library Manager shows me [all 4 releases of the library](https://github.com/amirchev/EZPROM/releases):
![Clipboard02](https://user-images.githubusercontent.com/8572152/63639835-54dc0e80-c64d-11e9-90a6-e08376e29b23.png)
