### ISSUE TITLE
[Library Manager] fix Adafruit ST7735 library

### ISSUE THREAD

**Issue by ladyada** [arduino/Arduino#7855]
hiya we renamed the library (it now is 7735 and 7789) and it got dropped from the library manager - updates don't get picked up anymore
https://www.arduinolibraries.info/libraries/adafruit-st7735-library

do we have to rename it  back or can the manager be updated for this library
https://github.com/adafruit/Adafruit-ST7735-Library

**Comment by per1234** [comment]
The indexer job can be updated to the new name. cmaglie will do it on their next run through the Library Manager requests.

**Comment by cmaglie** [comment]
Done!
