### ISSUE TITLE
Pointer that is class field is initialized with random value if instance is created via 'new'

### ISSUE THREAD

**Issue by davseitsev** [arduino/Arduino#7859]
**Steps to reproduce**:
1. Create `someclass.h` with field `pointer` without initialization
```
#include "Arduino.h"

class SomeClass
{
  public:
    SomeClass();
    void checkPointer();
    
  private:
    long* pointer;
};
```

2. Create `someclass.cpp`
```
#include "someclass.h"

SomeClass::SomeClass() {

}

void SomeClass::checkPointer() {
  if (pointer) {
    Serial.println("Pointer is not NULL");
  } else {
    Serial.println("Pointer is NULL");
  }
}
```

3. Create simple sketch where `SomeClass` instance is created via `new` keyword.
```
#include "someclass.h"

SomeClass* someClass;
long index = 0;
long* arr = new long[100]; // random code to clutter up memory

void setup() {
  Serial.begin(115200);
  while (!Serial) {}
  someClass = new SomeClass();
  Serial.println("Boot");
}

void loop() {
  if (index % 1000 == 0) {
    someClass->checkPointer();
  }
  index ++;
}
```

**Expected result**:
As pointer was not initialized we would expect following output:
```
Boot
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
...
```

**Actual result**:
Actual result is not deterministic. It depends on amound of your code and the position of the Moon.
_Sometimes_ we can see following output:
```
Boot
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
```

I added random code to the sketch and got this result.
To reproduce the issue easier we can create new instance of the class in the loop (I don't do this in my real sketch):
```
void loop() {
  if (index % 1000 == 0) {
    someClass->checkPointer();
    someClass = new SomeClass();
  }
  index ++;
}
```

This code produces following output:
```
Boot
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is NULL
Pointer is NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is not NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
Pointer is NULL
...
```

I came up with a workaround:
`long* pointer = NULL;`
But I spent a lot of time to find out the cause of the problems.

**Env:**
IDE: Arduino 1.8.5
OS: Windows 10
MC: Arduino Nano

**Comment by facchinm** [comment]
`new` doesn't memsets the memory to zero, and uninitialized variable (in C/C++) are not assured to be 0 (unlike other languages).
`long* pointer = NULL;` in the class definition is not a workaround but the right way to do achieve what you need :wink:
