### ISSUE TITLE
MKR Vidor 4000: Modifying VidorDrawLogo example doesn't result in change to displayed text

### ISSUE THREAD

**Issue by jcristine** [arduino/Arduino#7860]
Received the MKR Vidor 4000, loaded the "VidorDrawLogo" sketch (tested - OK on HDMI Monitor), modified line 50 (adding "My"): vdgfx.println("MyARDUINO");

Recomplied and uploaded - Upload = success... and, no change to the HDMI display.  Still says "ARDUINO" v. "MyARDUINO"

Anyone else have success (or failure) with this simple test?  I'm thinking it's too new and simply not done/working yet.  Also - can't find the "FPGA / IP" Arduino building blocks on the create.arduino.cc website that I've read and heard about over the past few months.

Anyone..., any success with this board?

**Comment by per1234** [comment]
There are more reports of this problem on the forum starting here:
http://forum.arduino.cc/index.php?topic=561572.msg3829978#msg3829978

> Also - can't find the "FPGA / IP" Arduino building blocks on the create.arduino.cc website that I've read and heard about over the past few months.

It's not clear what you're referring to. If you mean the web-based tool, that's not available yet but it's planned to release it by October:
https://forum.arduino.cc/index.php?topic=559800.msg3819607#msg3819607
>by october we plan to release our web based "ip assembler" which will allow you to create your own blend of peripherals by chosing which and how many ip blocks you want to include in the image.

Currently what's available is this:
https://github.com/vidor-libraries/VidorFPGA

>Anyone..., any success with this board?

Let's keep the issue tracker for specific bug reports or feature requests. General discussion or support requests are welcome on the Arduino Forum:
https://forum.arduino.cc/index.php?board=125.0

**Comment by per1234** [comment]
There has been an update from Arduino on the forum thread:
>There was some issues with the bitstream provided in the original VidorGraphics library. We've pushed an updated version to Github: https://github.com/vidor-libraries/VidorGraphics
>
>Please re-download the library and add to your sketchbook to get the fixes.

Please do this:
1. Remove the old version of the VidorGraphics library by deleting the folder `{sketchbook folder}/libraries/VidorGraphics-master`. You can find the location of your sketchbook folder in the Arduino IDE at **File > Preferences > Sketchbook location**.
1. Download the new version of the VidorGraphics library from https://github.com/vidor-libraries/VidorGraphics/archive/master.zip
1. Unzip the downloaded file.
1. Move the unzipped folder to `{sketchbook folder}/libraries`.
1. Upload your modified VidorDrawLogo sketch to your MKR Vidor 4000 board again.
1. Comment here to let us know whether that solved your problem.
1. Move the unzipped folder to

**Comment by per1234** [comment]
There has been an update from Arduino on the forum thread:
>we found the issue and are in the process of validating and releasing it. we expect to push the update on monday. the issue is that the flash needs to be programmed with a flag that enables it to use quad spi commands and vidorgraphics needs that as it runs part of the code from there. a piece of code that was supposed to do it stopped working due to a modification we did last minute and we didn't recognize it as once flash has been programmed once it'll retain the setting.

>we just pushed the new image on git. for those who are downloading it manually you have to fetch it from github.
note that now libraries have also been officially included in library manager and should also update shortly (it's an automated process).
note that the first time you load the sketch it may lock up (the flash reconfiguration takes a while). just reload a second time and from there on the board will work as intended.
let me have feedback if anyone still has trouble.

Please do this:
1. Sketch > Include Library > Manage Libraries...
1. Wait for download to finish.
1. In the "Filter your search..." box, type: "vidorgraphics".
1. Click on "VidorGraphics by Martino Facchin".
1. Click "Update".
1. Wait for update to finish.
1. Click "Close".
1. Upload your modified VidorDrawLogo sketch to your MKR Vidor 4000 board again.
1. Comment here to let us know whether that solved your problem.

**Comment by sandeepmistry** [comment]
Please see: https://forum.arduino.cc/index.php?topic=563513.0

Let's continue this discussion on the forum as needed.
