### ISSUE TITLE
[Library Manager] add AceRoutine cooperative multitasking library to the Library Manager

### ISSUE THREAD

**Issue by bxparks** [arduino/Arduino#7868]
Please add https://github.com/bxparks/AceRoutine to the library manager. Here's the summary:

sentence=A low-memory, fast-switching, cooperative multitasking library using stackless coroutines on Arduino platforms.

paragraph=Supported macros include COROUTINE(), COROUTINE_BEGIN(), COROUTINE_YIELD(), COROUTINE_DELAY(), COROUTINE_AWAIT(), COROUTINE_LOOP(), and COROUTINE_END(). Verified to work on AVR (Nano, UNO, etc), Teensy ARM, ESP8266 and ESP32. Unit tested using AUnit.

**Comment by cmaglie** [comment]
Done!
