### ISSUE TITLE
IDE scrolls right and never restores left margin [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#788]
This is [Issue 788](http://code.google.com/p/arduino/issues/detail?id=788) moved from a Google Code project.
Added by 2012-01-12T05:47:59.000Z by [a...@iredale.com.au](http://code.google.com/u/114992814728636082557/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Scroll to the right in a sketch that has long lines
2. Try to scroll back to the left
3. The text on the left will be jammed up against the left edge

**What is the expected output? What do you see instead?**
Expected, left margin (a little bit of white space). Instead, crammed left with no space.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
1.0, Mac OS X Lion, Irrelevant.

**Please provide any additional information below.**
That's all. Cheers.

**Comment by ffissore** [comment]
Works fine with latest hourly
