### ISSUE TITLE
Wishing to install Additional boards to a non-networked (Fully Offline) PC

### ISSUE THREAD

**Issue by Kintara** [arduino/Arduino#7882]
I have the Arduino IDE installed on a non-networked PC at work (all the networked ones are IT administered and they wont let anyone install anything on them - so I'm using an old Windows XP stand alone PC) and I wish to install the bits i need for board manager to list the new board (ESP8266).
I have tried downloading the json file from: http://arduino.esp8266.com/stable/package_esp8266com_index.json 
I saved it on the PC and changed the "Additional Board Manager URLs” field to point to the json file.
I restarted the IDE, but still cannot see the board listed in board manager.
What am I doing wrong and how can I get the board listed?
Many thanks
Kintara 8-)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
