### ISSUE TITLE
add library TwoWheelRobot

### ISSUE THREAD

**Issue by housewithinahouse** [arduino/Arduino#7885]
https://github.com/housewithinahouse/TwoWheelRobotLibrary

**Comment by per1234** [comment]
Your library is missing the required library.properties file. Please add one, following the specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
Then either create a new Git tag/GitHub release or else redo the existing v1.0.0 tag.

Once that's done, please comment here so we'll know we can proceed.

**Comment by housewithinahouse** [comment]
Sorry about that! I think it is all fixed now. Thank you!

**Comment by cmaglie** [comment]
Done!
