### ISSUE TITLE
Where is preferences.txt / *processing?

### ISSUE THREAD

**Issue by RobinHawk** [arduino/Arduino#7897]
Question:  Where is the processing/preferences.txt in Raspberry Pi, to adjust the window height so the Arduino IDE loads properly on Raspberry Pi 7'' Touchscreen?

___

In Arduino 1.8.5 the introduction says adjustments for screen height need to be made through the *processing directory's preferences.txt (instead of through the arduino lib preferences.txt.)

I downloaded the I3 Processing 3 -- however still can not find the preferences.txt (other than the one in the arduino-1.8.5/lib)

Also, not seeing any hidden directories using the ls -h and ls-F commands where this file might be located.

**Comment by matthijskooijman** [comment]
Which introduction says that? Can you provide a link?

Arduino was forked from processing a long time ago, but they are no longer linked. Current Arduino versions on Linux store their settings in `~/.arduino15/preferences.txt`, so I suppose that's what you need.

**Comment by RobinHawk** [comment]
matthijskooijman,

Thank you for such a quick reply.

After searching for hours, ha, I was just able to use the find tool in the 'folders' section of the operating sys to locate the preference.txt and adjust the height to 400px

-- The Arduino Team might consider adding the suggestion to the intro that lists the various locations for the file, preferences.txt, for Windows, Mac & Linux, because it saves a lot of time to search the pi directory in the find files section.
