### ISSUE TITLE
SimpleAudioFrequencyMeter Bug?

### ISSUE THREAD

**Issue by Lilyjan** [arduino/Arduino#7901]
The attached sketch is a copy of the example published in the Arduino documentation as an implementation of a 'Simple Audio Frequency Meter' at:
https://www.arduino.cc/en/Tutorial/SimpleAudioFrequencyMeter
I have simply added code to read from an analog input pin. This seems to be incompatible with AudioFrequencyMeter and causes the USB connection to the board to disconnect following a successful compilation (see attached screen-grab). The sketch can not be executed. This appears to be the case with any analog pin. I have tested with an MKRZERO (as recommended) under OS X 10, OSX 12 and Windows 7. This is associated with Issue #7895.
Is this a bug, or am I missing something really obvious?

[AFMglitch2.txt](https://github.com/arduino/Arduino/files/2299575/AFMglitch2.txt)

<img width="875" alt="afmglitch1" src="https://user-images.githubusercontent.com/15174276/44300013-e0fb7d80-a2f7-11e8-923e-510a41415dd9.png">

**Comment by facchinm** [comment]
Hi @Lilyjan .
`AudioFrequencyMeter` library configures the ACD as freerunning, so the readings are immediate and valid at any time; `analogRead` instead needs the ADC to be configured as oneshot, so when the sketch executes that instruction it gets stuck in a while loop.
I suggest you to open an issue in the proper repository (https://github.com/arduino-libraries/AudioFrequencyMeter) to properly document this behaviour.

**Comment by Lilyjan** [comment]
Thank you for this helpful response. I will do as you suggest.
