### ISSUE TITLE
Arduino serial communication doesn't work with external power supply

### ISSUE THREAD

**Issue by uwo078** [arduino/Arduino#7910]
I tried using an external power supply and my arduino serial communication doesn't work, however it does work with the usb. I searched online and found so many related issues but yet not a solved solution. Is there any solution for this problem?

**Comment by facchinm** [comment]
Hi @uwo078 ,
to try solving your issue we need a lot more information from you:
* which board are you using?
* can you post a sketch and a description of the expected behaviour so we can reproduce the issue on our side?
* what IDE version are you using?
