### ISSUE TITLE
[Library Manager] Library add request

### ISSUE THREAD

**Issue by maisonsmd** [arduino/Arduino#7914]
Requesting the addition of my library https://github.com/maisonsmd/msTask to the library manager.
This lightweight library emulates multitasking in Arduino

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by maisonsmd** [comment]
I updated them, please review!
Thank you!

**Comment by cmaglie** [comment]
Done
