### ISSUE TITLE
AT328P sketch is not uploading

### ISSUE THREAD

**Issue by AniruddhaDongare** [arduino/Arduino#7919]
I am using AT328P controller, Sketch is uploaded first time successfully on controller, when i tried to upload the second sketch it gives the error message. serial ports and controller is working fine on first sketch.

**Comment by facchinm** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
