### ISSUE TITLE
Lag when changing to File/Tools tab on macOS

### ISSUE THREAD

**Issue by 45gfg9** [arduino/Arduino#7924]
OS: macOS 10.13.6
IDE: 1.8.6
When changing between tabs, File tab causes lag. 
<img width="516" alt="2018-08-25 23 09 17" src="https://user-images.githubusercontent.com/37043529/44619630-a62bb380-a8bc-11e8-8116-f7b6cd8378b0.png">
When changing from other tabs to File tab, it will lag about a second. 
Changing to Tools tab also causes lag, but it's much shorter, about 0.1 sec. 
Other tabs Edit/Sketch/Help tabs work fine.

**Comment by MCUdude** [comment]
I'm experiencing the exact same issues. I'm using MacOS 10.12.6

**Comment by PaulStoffregen** [comment]
Random question - Are you using Teensy, or have you run the Teensyduino installer on this copy of Arduino 1.8.6?  There may be a bug in Teensyduino which adds lag to some of the menus.  I'm investigating...

Just want to confirm these are the Arduino IDE *without* Teensy's modifications.  Wouldn't want to bother the Arduino devs with something that might be my fault.

**Comment by MCUdude** [comment]
my menu is really laggy and slow without teensyduino installed. I ended up going back to 1.8.5 because it might take half a minute for the boards menu to respond. Instant spinning ball..

**Comment by 45gfg9** [comment]
Hiya, here to say I am not using Teensy.

**Comment by DrDiodac** [comment]
I have the same problem huge lags, slow down even restarting itself my Mac and after restart, kernel panic alert. 
But if I not touch menu, I can working normally.

**Comment by facchinm** [comment]
Bisecting right now, I'll notify you when I get something :wink:

**Comment by facchinm** [comment]
Found the culprit, it's Java (again) :rage: 
1.8.5 was bundled with JRE8u151 while 1.8.6 with u171 . Bisecting shows that the first problematic version is u161 but there's nothing in the release notes that catches the eye.

The slowdown exists even if I revert https://github.com/arduino/Arduino/commit/a2b5f661b85dc7591b40cdcc5d81904e5707fe2f and companion commits or compile IDE 1.8.4, so the bug lies somewhere else.

As a workaround while we investigate, I'd revert jre to u151 on nighlty builds (even if it's EOL) since it doesn't look like there are super important bugfixes between 151 and 181.

**Comment by facchinm** [comment]
@DrDiodac @45gfg9 @MCUdude would you mind testing the build that is being produced by #7935 ? Thanks!

**Comment by MCUdude** [comment]
I just downloaded and tested it. Works fine for me now! 👍🏻

**Comment by DrDiodac** [comment]
Yeah I can lead test,  just I need reading about changes which I need to do or send me please steps tips how to, and I can start quickly. 


Send from iPhone

**Comment by 45gfg9** [comment]
Thank you! Now it works as normal. No more lags. 🎉

**Comment by DrDiodac** [comment]
At first glance seems that slow down problems is solved! I do more testing but I see is better than before. Teensy 3.2 tested. 
Thank you!! 

Send from iPhone

**Comment by Vipas-ana** [comment]
[#7935](https://github.com/arduino/Arduino/pull/7935) Fixes this issue.

**Comment by 45gfg9** [comment]
Ok, so now I think I can close this issue. Thank you all!
