### ISSUE TITLE
possible error for sizeof function

### ISSUE THREAD

**Issue by theardnutcase** [arduino/Arduino#7928]
I have found a possible problem with the sizeof function.  Am I missing something?  
My code:
#define PGM_ARD_SERIAL_BAUD   57600 //set Arduino usb serial port speed

String BOX_msg_1 = "this";
String BOX_msg_2 = "where 2nd non_blank msg would be";
String BOX_msg_3 = "123456789X12345";

void setup() {
  Serial.begin(PGM_ARD_SERIAL_BAUD); //set Arduino usb serial port speed

  Serial.print(F("size of msg 1: "));
  Serial.println(sizeof(BOX_msg_1));
  Serial.print(F("size of msg 2: "));
  Serial.println(sizeof(BOX_msg_2));
  Serial.print(F("size of msg 3: "));
  Serial.println(sizeof(BOX_msg_3));
}

void loop() {
  // put your main code here, to run repeatedly:

}

//output from above:
size of msg 1: 6
size of msg 2: 6
size of msg 3: 6

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
