### ISSUE TITLE
Deletion of build files [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#793]
This is [Issue 793](http://code.google.com/p/arduino/issues/detail?id=793) moved from a Google Code project.
Added by 2012-01-15T20:00:17.000Z by [johnny.l...@gmail.com](http://code.google.com/u/110322868293530037462/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Change the "build.path" options in preferences (add it) to a path like C:\Arduino\builds\
2.Open a sketch and compile it. The builds files are now in the folder
3.Open another sketch and close it.
4. All the files are deleted in the builds folder

**What is the expected output? What do you see instead?**
Only the files created by the buildings process should be deleted. Not the one that the applications doesn't touch.
If you put a path like C:\Users\*Users*\Documents, EVERYTHING in the My documents will be deleted permanantly!!! Even the subfolders

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Version 1.0. Windows 7. But that should be a bug since version 0018, the change that we don't use the folder "applet"

**Please provide any additional information below.**
When you specify a path like this, it should create a subdir with the project name, or use an array of file name to delete only those.

**Comment by ffissore** [comment]
Closing as wontfix.
