### ISSUE TITLE
[Library Manager] Add Saleng GSM library

### ISSUE THREAD

**Issue by cdmalecdan** [arduino/Arduino#7933]
Kindly add the "Layad Circuits Saleng GSM Library":

https://github.com/layadcircuits/Saleng-GSM

This is a simplified and nonblocking implementation of AT commands for SMS for SIM900 and SIM800 and works by default with the Layad Circuits Saleng GSM Shield. Changing pins allows it to work with any SIM300/SIM900/SIM800 based board.

Thank you very much!

**Comment by cmaglie** [comment]
Done!
