### ISSUE TITLE
Attiny84 Wrong Pin Map for Programming

### ISSUE THREAD

**Issue by Solarcycle** [arduino/Arduino#7939]
When using the Arduino for programming our Attiny84A, we found that the digital pin map was wrong. It took about a month to figure out since we were in the process of developing a product and debugging a lot of other stuff. We thought we fried the chip, but when all the other hardware bugs were fixed, all the digital pins still did not work. After checking voltages on different digital pins, we found that the digital pin map is ordered incorrectly in the Arduino pin definition pins_arduino.c. It looks like the pin numbers were simply increasing going around the chip, but the digital pins are numbered backwards. We think that this was done assuming a pin order without testing it. In Arduino, it shows Pins 2-5 as D10-8 respectively, but it should be reversed:

Pin   Name
2      PCINT8
3      PCINT9
4      PCINT11
5      PCINT10
<img width="683" alt="screen shot 2018-08-22 at 5 00 20 pm" src="https://user-images.githubusercontent.com/12579966/44699738-74405b80-aa3a-11e8-8e6d-45941023fbc4.png">

**Comment by per1234** [comment]
This issue tracker is only for reporting bugs with official Arduino software. There is no official Arduino ATtiny84 variant so you're reporting this in the wrong place.
