### ISSUE TITLE
optiboot should support ATmega1284 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#794]
This is [Issue 794](http://code.google.com/p/arduino/issues/detail?id=794) moved from a Google Code project.
Added by 2012-01-16T01:02:14.000Z by [wes...@gmail.com](http://code.google.com/u/103342639718054305536/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

Several projects have appeared that use the ATmeg1284 chip (largest AVR available in a DIP; the next step up from Sanguino.)
optiboot should be modified to support this chip as well; this should involve mere makefile and #define changes that do not change the existing binaries.

http://code.google.com/p/optiboot/issues/detail?id=51

**Comment by sandeepmistry** [comment]
I'm closing and marking this as won't fix.

**Comment by WestfW** [comment]
Is Arduino EVER likely to pull in a new version of Optiboot?
A lot has changed, most in the form of added chips and features that Arduino is probably not very interested in, but there's at least one significant bugfix (not overwriting flash when EEPROM writes are requested: https://github.com/Optiboot/optiboot/issues/65 )

It ought to be possible to actually support EEPROM on the 328p class chips, though it might be necessary to change the LED behavior on startup...
