### ISSUE TITLE
narrowing conversion was warning, now is error

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#7944]
The recent upgrade from gcc 4.8 to 5.4 has turned "narrowing conversion" from a warning to an error.

Here is a library which demonstrates the problem.  Works with earlier Arduino but will not compile with 1.8.6.

https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary

I recommend adding "-Wno-error=narrowing" to the compiler flags in platform.txt for compiling .cpp files.  This will restore the gcc 4.8 behavior and allow libraries like MusicWithoutDelay to compile as they always have on prior versions of Arduino.

**Comment by chammie** [comment]
I found the same problem

**Comment by PaulStoffregen** [comment]
Tested hourly build just now.  Confirmed this is fixed.
