### ISSUE TITLE
Arduino IDE 1.8.6 "No device found" with DUE

### ISSUE THREAD

**Issue by Uup115** [arduino/Arduino#7947]
Hello,

I installed Arduino IDE 1.8.6 (Windows 7) a couple of days ago, to resolve "Rebuilding All" every time.  Good work and thanks!  Just donated $50 :-)

Unfortunately, it seems communication with the DUE board is now broken (at least intermittent).  When trying to upload a sketch to DUE, the error "No device found on com" intermittently displays.  Fidgeting with the DUE board and IDE sometimes renders a successful upload.  However, I haven't been able to find a sure-fire way to upload successfully every time.  Success rate is about 25%.  Problem occurs with both DUE USB ports:  Native and Programming.

I'm currently running Arduino IDE on three machines:

Windows 7 with IDE 1.8.6:  "No device found on com"
Linux Mint 18 with IDE 1.8.6:  "No device found on tty"
Manjaro Arch Linux with IDE 1.8.5:  Uploads successfully 100%.

**The Windows 7 machine previously had 1.8.5, which had 100% upload success rate.**  Both Linux machines have fresh installs of Arduino IDE.  The same DUE board was tested on all three machines.

Thanks and Best Regards

**Comment by facchinm** [comment]
Hi @Uup115 ,
thanks for the report. Between 1.8.5 and 1.8.6 didn't we didn't change the upload code so it looks a bit strange that a problem has appeared out of the blue.
I'd ask you to do a couple of tests:
- check if Linux Mint has ModemManager installed and eventually uninstall/disable it (if you don't need it for a real 56K modem of course :slightly_smiling_face: )
- if it still doesn't work, try running 1.8.5 on the Mint box (without installing it, only run `./arduino` from the extracted folder)
- make 100% sure to always select the right port under Tools/Port (native port may change name between different runs)

The Windows7 machine is a bit of a mystery, I'll check if I'm able to reproduce the bug.

**Comment by Uup115** [comment]
Hello @facchinm

Thanks for your quick response.  I performed all your suggestions above.  Disabling ModemManager didn't improve things.  Running ./arduino didn't help either.  Ports are properly selected as well.  Unfortunately, I've discovered the **Manjaro machine also has this issue  :-(.**  You're right, Arduino IDE probably isn't the culprit.  I suspect it's caused by "nosiy" communication or something.  Digging a little further, I found this: 

https://forum.arduino.cc/index.php?topic=148613.0

See post # 10, Updated March 2018.  It seems others are experiencing this issue.  Per @joe0815, executing the following commands, is a semi-reliable solution for Linux:

`sudo chmod 666 /dev/ttyACM0`
`stty -F /dev/ttyACM0 speed 1200 cs8 -cstopb -parenb`

After 30 minutes of back to back sketch uploads, this seems to work 100% for the Manajro machine (desktop).  However, the 2nd command must be invoked **twice before each sketch upload**, because the baud rate resets to 115200 after upload finishes.  The Mint machine (laptop), doesn't show any improvement.  Changing the baud rate, via Windows 7 (desktop machine) device manger, doesn't help either.  For now, it looks like I'll need to switch my development from Windows 7 to Manjaro.

Is it possible to set the upload baud rate inside Arduino IDE?

Thanks and Best Regards

**Comment by facchinm** [comment]
It could be a faulty board indeed.
If it's still under warranty it will be better to contact support for a replacement; otherwise I can give you some troubleshooting advice but they all require hardware modifications :slightly_smiling_face:

**Comment by Uup115** [comment]
Hello @facchinm,

Troubleshooting advice is always helpful.  Thanks!  

Best Regards

**Comment by facchinm** [comment]
Ok, closing the issue in the meantime :slightly_smiling_face: 
One of the possible causes if a missing pullup resistor on the RESET line; take a look at [this topic](http://forum.arduino.cc/index.php?topic=256771.msg2512504#msg2512504) to confirm if your board is affected :wink:

**Comment by Uup115** [comment]
Not even sure. This is what I was given to work with.  Can you tell by the photo?

![img_20180830_170529](https://user-images.githubusercontent.com/39218074/44879392-9246cf80-ac77-11e8-9c63-aae3541d5c55.jpg)

**Comment by Uup115** [comment]
So, it seems mine isn't original.  Sadly, Arduino Store is OOS.

![image](https://user-images.githubusercontent.com/39218074/44880637-0c2c8800-ac7b-11e8-851f-5b497b7d55ab.png)
