### ISSUE TITLE
Downloads page should say Mac requires 10.8 Mountain Lion

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#7959]
Please update the [downloads page](https://www.arduino.cc/en/Main/Software) to say 10.8 Mountain Lion is required for Macintosh.

Arduino 1.8.6 crashes when run on 10.7.  The hourly build and future versions will refuse to run, due to #7957.

![sc1](https://user-images.githubusercontent.com/965463/44929697-c02c2280-ad10-11e8-9e48-fe070fe97676.png)

![sc2](https://user-images.githubusercontent.com/965463/44929707-c4f0d680-ad10-11e8-8abc-686aad1e010a.png)

**Comment by facchinm** [comment]
Fixed and pushed on website, thanks :wink:
