### ISSUE TITLE
Strange issue with uploads (to Mega2560) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#797]
This is [Issue 797](http://code.google.com/p/arduino/issues/detail?id=797) moved from a Google Code project.
Added by 2012-01-19T13:16:45.000Z by [jo...@knudde.be](http://code.google.com/u/117203262105030337311/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Duplicate).

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**

When 3 exclamation marks are used in a string, uploads to Arduino Mega 2560 fail.

Example:
...
  Udp.beginPacket(BROADCAST, PORT);
  Udp.write("Heartbeat!!!");
  Udp.endPacket();
...

Always fails to upload, while 

...
  Udp.beginPacket(BROADCAST, PORT);
  Udp.write("Heartbeat!");
  Udp.endPacket();
...

Always succeeds.
(2 exclamation marks also always succeed, while 4 exclamation marks also consistently fail. I think 3 or more gives a problem.)

When the failure happens, the upload to the Arduino starts and the RX/TX leds are flashing, but then it abruptly halts, resulting in a timeout.
The USB cable needs to be unplugged to get uploads working again.

**What is the expected output? What do you see instead?**

Expected output: "Done uploading"
Observed output:

Binary sketch size: 19816 bytes (of a 258048 byte maximum)
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
...

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Arduino 1.0
Ubuntu 11.10 (GNU/Linux 3.0.0-14-generic i686)
Arduino Mega 2560 R2

**Please provide any additional information below.**

I suspect this an issue with the upload protocol where "!!!" means something special and the upload stops when these characters are sent.

**Comment by matthijskooijman** [comment]
For reference, this was a duplicate of #392.
