### ISSUE TITLE
[Library Manager] please add Sixfab_CellularIoT Library

### ISSUE THREAD

**Issue by selengalp** [arduino/Arduino#7971]
Repo : https://github.com/sixfab/Sixfab_Arduino_CellularIoT_Library
Tag: https://github.com/sixfab/Sixfab_Arduino_CellularIoT_Library/releases/tag/v1.0

**Comment by per1234** [comment]
Those links give a 404 error. Is the repository maybe set to private?

**Comment by cmaglie** [comment]
Now it's visible, maybe the problem has been fixed by the author.
I've added the library to the index.
