### ISSUE TITLE
new version of our library

### ISSUE THREAD

**Issue by Onno-Dirkzwager** [arduino/Arduino#7977]
Hi,
we just released a new version of our library: https://github.com/iotappstory/ESP-Library/releases/tag/2.0.0 and it seems like it is not getting added to the library manager.

We changed our repository name in the past https://github.com/arduino/Arduino/issues/7277 maby this has something to do with it?

Any feedback is welcome.
Regards

**Comment by SensorsIot** [comment]
Hi,
Is there any progress in this topic?
Regards
Andreas

**Comment by cmaglie** [comment]
Renames are not allowed, they need to be made by an admin.
Now I've changed the name to `IOTAppStory-ESP`.

**Comment by Onno-Dirkzwager** [comment]
Thankyou for your help!
I thought this was taken care of with #7277.
