### ISSUE TITLE
 'function' was not declared in this scope 

### ISSUE THREAD

**Issue by Brinkss** [arduino/Arduino#7986]
First time user

this is part of a sketch I am working on the first section allows it to compile,
the second part dose not allow it to compile,
the only difference I see is the extra space between 'void' and 'timer,
am I missing something. or is that not allowed ?????
If not why dose it not point to that
Arduino 1.8.7
```
void timer() { // timer timer timer timer

if(start_millis > 0 && setpoint > 0) {
new_millis = millis();
usable_millis = new_millis; - start_millis;
usable_millis = usable_millis /1000; // in seconds
}
else
usable_millis = 0;
} //End Timer
```
This statement above works
```
void  timer() { // timer timer timer timer

if(start_millis > 0 && setpoint > 0) {
new_millis = millis();
usable_millis = new_millis; - start_millis;
usable_millis = usable_millis /1000; // in seconds
}
else
usable_millis = 0;
} //End Timer
```
This causes the IDE to not allow functions to be reconised

**Comment by facchinm** [comment]
Hi @Brinkss ,
I tested your sketch and there's no bug in the prototype generation. 

What normally happens is that you may have an error in another part of the code that prevents the prototype generator to behave correctly. Please read ALL error messages (not only the last one, which is probably `No function timer() declared in this scope`) and fix them, the prototype generation will then work again.

```c++
void setup() {
  // put your setup code here, to run once:

}
long start_millis, new_millis, usable_millis;
long setpoint;

void loop() {
  // put your main code here, to run repeatedly:
  timer();
}

void    timer() { // timer timer timer timer

if(start_millis > 0 && setpoint > 0) {
new_millis = millis();
usable_millis = new_millis; - start_millis;
usable_millis = usable_millis /1000; // in seconds
}
else
usable_millis = 0;
} //End Timer
``

**Comment by Brinkss** [comment]
I have been working on this problem for quite a while, this is only a small part of the sketch I have open on 3 computers as well as notepad++, I have been checking for differences between the 3 IDE'c and Notebook++, eventually I found a saved sketch close to the up to date model, changed it until it was the same ( it would compile) as the 2 that would not compile, the only item different was this passage no copy  and pasting this function to the other IDE's was then able to get them to compile

**Comment by Brinkss** [comment]
Thanks for the help Floessie

**Comment by Trackhe** [comment]
Hey i have the same problem. i guess.
if i write
```
void functionname(){
    test();
}

void test(){
  Serial.println("hey es geht");  
}
```
--> `error: 'test' was not declared in this scope`

and if i write
```
test();

void test(){
  Serial.println("hey es geht");  
}
```
--> `error: expected constructor, destructor, or type conversion before ';' token`

what do i wrong here?
