### ISSUE TITLE
arduino nano and bluetooth pair problem

### ISSUE THREAD

**Issue by jay12341234** [arduino/Arduino#7991]
i am using arduino nano and hc-05 bluetooth for my project .
the issue is i am not  before connecting bluetooth i am able to transfer the data to arduino but after connecting tx and rx pins i am  not able to take bluetooth to the AT mode and some times it going to AT mode but when i am giving commend in serial monitor it is not responding.
the  bluetooth is working  properly because i transmitted the data by replaceing nano with uno.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
