### ISSUE TITLE
Something wrong with integer type

### ISSUE THREAD

**Issue by yurasin** [arduino/Arduino#7992]
Compiling integer varies from previous IDE version
In 1.8.6 it seems to be bad, not in range -32768..+32768
At least when compiled to Arduino Nano.

Simplest check:
void setup() {
  Serial.begin(115200);
}
void loop() {
  for (int i = 30000;; i++) Serial.println(i);
}

And another check with even more strange behavior:
void setup() {
  Serial.begin(115200);
}
void loop() {
  for (int i = 33000;; i++) Serial.println(i);
}

In version 1.6.5 everything OK.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/4511

Signed integer overflow is undefined behavior. You can't rely on any specific results.

There is a proposal that would make it behave as you expect: https://github.com/arduino/Arduino/pull/4624
