### ISSUE TITLE
Connection with Arduino Web Editor is impossible

### ISSUE THREAD

**Issue by juanneuman** [arduino/Arduino#7998]
After being working for months,  I haven´t been able to enter again Arduino Web Editor since friday. It prints Arduino/Genuino Uno has been disconnected, and immediately afterwards prints  Arduino/Genuino Uno has been connected but it never shows the editing screen.
Does somebody know what´s going on? I can´t beleive it´s just me.

**Comment by per1234** [comment]
According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor.

So I'm going to close this, but please do submit a report on the forum, after which I'm sure one of the Arduino Web Editor developers will look into the issue very soon.

**Comment by juanneuman** [comment]
Thanks.
