### ISSUE TITLE
[Library Manager] Please add MjGrove library

### ISSUE THREAD

**Issue by matsujirushi** [arduino/Arduino#8000]
Hi,

I created the library.
Could you add this to a list of libraries?
https://github.com/matsujirushi/MjGrove

Thanks.

**Comment by cmaglie** [comment]
I've added the library but you must define the `url` field in `library.properties`.

```
JOB 1762 - 2018/09/16 19:25:07 Scraping https://github.com/matsujirushi/MjGrove.git
JOB 1762 - 2018/09/16 19:25:11 Checking out tag: 1.0.0
JOB 1762 - 2018/09/16 19:25:11 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

to fix this:
1) edit your `library.properties` and define the `url` field
2) commit & push
3) delete and re-do the release tag

Once done our indexer will publish your library automatically within an hour.
