### ISSUE TITLE
please add a new library: Smart Motor Driver - SAMI

### ISSUE THREAD

**Issue by Danny24** [arduino/Arduino#8019]
Hi, 
I would like to add my new library to be available in Arduino:
https://github.com/Danny24/Smart-Motor-Driver-SAMI-Library

SAMI is a board designed to run micro gear dc motors with PID control over speed and travel distance by I2C. You can read more here: https://hackaday.io/project/158429-smart-motor-driver-for-robotics

Thanks

**Comment by cmaglie** [comment]
Done

**Comment by Danny24** [comment]
Thanks :)
