### ISSUE TITLE
Can't find the repo for contributing to Arduino built-in examples

### ISSUE THREAD

**Issue by montoyamoraga** [arduino/Arduino#8020]
Hi!
I want to contribute to the Arduino Graph example 
https://www.arduino.cc/en/Tutorial/Graph
which also lives at 
Arduino IDE => Examples => 04. Communication => Graph

I couldn't find the repository, I want to clone it and do a pull request, is that possible?
Best!

**Comment by per1234** [comment]
The example sketches are in this repository, here:
https://github.com/arduino/Arduino/tree/master/build/shared/examples
