### ISSUE TITLE
Editor bracket/brace/parenthesis matching should ignore those same characters in comments [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#803]
This is [Issue 803](http://code.google.com/p/arduino/issues/detail?id=803) moved from a Google Code project.
Added by 2012-01-25T02:43:06.000Z by [RCR...@gmail.com](http://code.google.com/u/110207018853775726441/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Put cursor after any bracket, brace or parenthesis.
2.Have an intervening comment with a mating character before
the correct mate. 
e.g.

 if (TRUE) {|<cursor here
// the editor will find this "}" as mate, rather then the one below
};

**What is the expected output? What do you see instead?**

Editor will highlight the mating character in the comment, instead of the correct mate in the code (above or below).

The editor should ignore ALL matching characters in comments. e.g. not count them when computing mate location.

This behaviour makes it harder to comment out partial blocks of code
which contain single {}[]() 

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

1.0 final, Win7 pro, N/A

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Fixed in latest hourly build
