### ISSUE TITLE
code enhancement

### ISSUE THREAD

**Issue by Heymann03** [arduino/Arduino#8033]
I'm trying to use the following code for sketch. Need some suggestions on how to make the code running for the following sketch.

//sketch of the circuit board//
![sketch_project_1_steckplatine](https://user-images.githubusercontent.com/43571346/46090778-b67fc880-c1b1-11e8-8d58-2e8f3028e87e.jpg)

//following is the code file for the above sketch//

[Transmitter_and_Receiver_source_code.zip](https://github.com/arduino/Arduino/files/2420495/Transmitter_and_Receiver_source_code.zip)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This is **NOT** an appropriate place to post this sort of thing. The appropriate place is the Arduino Forum. I'm sure we'll be able to help you over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).

**Comment by Heymann03** [comment]
Thanks for the information.
