### ISSUE TITLE
arduino --install-boards "arduino:avr:1.6.2"

### ISSUE THREAD

**Issue by czgtest** [arduino/Arduino#8040]
OS : windows10
Arduino : 1.8.7

go to C:\Program Files (x86)\Arduino and run command : arduino --install-boards "arduino:avr:1.6.2"

then I can't find board package in  ..\Arduino15\packages folder

but in Arduino 1.8.6, this command work well.

Is there any change?

**Comment by per1234** [comment]
It sounds the same as https://github.com/arduino/Arduino/issues/8034

Do you get the "Selected board is not available" error?

**Comment by czgtest** [comment]
I can't see any error print out in command line

**Comment by matthijskooijman** [comment]
You might need to run arduino_debug.exe instead of arduino.exe to see commandline (error) output.

**Comment by facchinm** [comment]
Closing as duplicate of #8034

**Comment by lsaidman** [comment]
Does 1.8.8 fix this?
