### ISSUE TITLE
Clarify Analogue Pins at https://www.arduino.cc/reference/en/language/functions/analog-io/analogread/

### ISSUE THREAD

**Issue by benpaddlejones** [arduino/Arduino#8043]
The reference has:
`Parameters
pin: the number of the analog input pin to read from (0 to 5 on most boards, 0 to 7 on the Mini and Nano, 0 to 15 on the Mega)`

Should update to include UNO analogRead/analogWrite pins are A0, A1, A2, A3, etc and also link to analogueWrite pwm documentation to prevent confusion.

**Comment by facchinm** [comment]
@per1234 should this be moved to https://github.com/arduino/reference-en ?

**Comment by per1234** [comment]
Good idea facchinm!

Moved to https://github.com/arduino/Arduino/issues/8043
