### ISSUE TITLE
IDE 1.8.7 segmentation fault

### ISSUE THREAD

**Issue by FernandoGarcia** [arduino/Arduino#8045]
Hi!

I'm changing my code to make compatible with PlatformIO and Arduino IDE and after make small changes to remove warnings about uninitialized variable I'm getting some random segmentation fault errors.

The changes that I did are insignificant just `int x, y;` to `int x = 0, y = 0;`

Now I have this error:
```
C:\Users\FERNAN~1\AppData\Local\Temp\arduino_build_730817\sketch\src\Modules/Menus.h: In function 'config_dosagem_manual':

C:\Users\FERNAN~1\AppData\Local\Temp\arduino_build_730817\sketch\src\Modules/Menus.h:1429:1: internal compiler error: Segmentation fault

 }

 ^
lto-wrapper.exe: fatal error: E:\Meus documentos\ARDUINO\arduino-1.8.7\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

e:/meus documentos/arduino/arduino-1.8.7/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status
```
And some times:

```
E:\Meus documentos\ARDUINO\arduino-1.8.7\libraries\Ethernet\src\Ethernet.cpp: In function 'begin.constprop':

E:\Meus documentos\ARDUINO\arduino-1.8.7\libraries\Ethernet\src\Ethernet.cpp:75:1: internal compiler error: Segmentation fault

 }

 ^
lto-wrapper.exe: fatal error: E:\Meus documentos\ARDUINO\arduino-1.8.7\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

e:/meus documentos/arduino/arduino-1.8.7/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status
```
After I have downloaded the IDE 1.8.3 that I was using since long time and I haven't this errors.
Also compiling this code with PIO I haven't this errors.

The code is attached.
[Ferduino Aquarium Controller.zip](https://github.com/arduino/Arduino/files/2432191/Ferduino.Aquarium.Controller.zip)

Best regards.

**Comment by per1234** [comment]
We already have two open issues regarding the Segmentation fault error with avr-gcc 5.4.0:
- https://github.com/arduino/Arduino/issues/7949
- https://github.com/arduino/Arduino/issues/7946

So I'm going to close this as a duplicate.
