### ISSUE TITLE
Warn for assignment in if() upon compilation

### ISSUE THREAD

**Issue by robzach** [arduino/Arduino#8048]
I often see students write `if (x = y)` when they mean `if (x == y)`. An understandable error; even a prof of C++ taking one of my intro classes made this same mistake in his code and wasn't able to see it.

Apparently `gcc` can be made to warn of assignments in `if` tests, by using the `-Wparentheses` flag at compilation. The warning can be avoided by using an extra pair of parentheses to demonstrate programmer's intention, i.e. `if ((x = y))`. 

[GNU's `gcc -Wparentheses` documentation.](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wparentheses)

As many users of the Arduino IDE are newer programmers and unlikely to intend assignments this way, I recommend that the warning for assignments inside of `if()` tests be made visible in the console.

**Comment by PaulStoffregen** [comment]
Did you try this in File > Preferences?

![screen](https://user-images.githubusercontent.com/965463/46321335-8fe9d500-c597-11e8-8971-24776ed010f2.png)

**Comment by robzach** [comment]
Thanks, Paul! 

I had overlooked that preference, and when I switched it to *All*, on compilation it threw exactly the right warning, helpfully painted orange to make it jump out: `warning: suggest parentheses around assignment used as truth value [-Wparentheses]`.

I'll now suggest setting that preference as one of the initial IDE setup steps for my students.
