### ISSUE TITLE
Missing information in delay() and millis documentation

### ISSUE THREAD

**Issue by iUnknwn** [arduino/Arduino#8049]
The current documentation for the `delay()`, `millis()` and other time related functions do not mention that all of the functions rely on the AVR Timer/Counter0 module. 

This can lead to unexpected behavior if a user tries to use Timer0 in their application. For example, if a user attempted to use Timer0 as a simple peak counter on the TC0 pin, and set the clock source to the external pin respectively, this would break the `delay` function.

**Comment by per1234** [comment]
This has already been requested and rejected:
https://github.com/arduino/Arduino/issues/6914

I want the documentation to be comprehensive, but it's also important for it to be beginner friendly. The decision of where that balance is reached is not mine to make.

**Comment by iUnknwn** [comment]
The concern here is not wanting to go beyond what is offered by the Arduino reference language, but that the reference language is inconsistent with delay macros in other embedded C dialects.

Atmel C, Mirochip C, and Cypress C all use software based delay loops (it's the reason many of them don't allow non-constant delay values - they're calculated by the compiler and implemented as dumb loops). As a result, this means that it's perfectly safe to call Delay and using a timer at the same time. 

In this case, the Arduino behavior is different than those other common languages. 

This isn't a request to add 'detail on the timer,' but to simply say 'this function, unlike delays in other embedded languages, relies on hardware counter resources'. That way the discrepancy is documented.
