### ISSUE TITLE
http://downloads.arduino.cc/packages/package_index.json is not updated

### ISSUE THREAD

**Issue by jandrassy** [arduino/Arduino#8062]
http://downloads.arduino.cc/packages/package_index.json doesn't contain AVR packages 1.6.22 and 1.6.23

**Comment by facchinm** [comment]
Update pushed, now package_index.json  should contain 1.6.22 and 1.6.23 to allow upgrading older installations. There's a know bug on Windows (see https://github.com/arduino/ArduinoCore-avr/issues/39 and https://github.com/arduino/Arduino/issues/7949) so anyone affected should revert to 1.6.21.

**Comment by Floessie** [comment]
@facchinm 
> There's a know bug on Windows (see arduino/ArduinoCore-avr#39 and #7949) so anyone affected should revert to 1.6.21.

Actually, at least the former was reported for Linux.

**Comment by facchinm** [comment]
@Floessie correct, I trusted my memory too much :slightly_smiling_face:
