### ISSUE TITLE
Cannot send code to arduino

### ISSUE THREAD

**Issue by finalfrontz98** [arduino/Arduino#8063]
Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Arduino/Genuino Uno"

exec: "C:\\Program Files\\WindowsApps\\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\\hardware\\tools\\avr/bin/avr-g++": file does not exist
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by facchinm** [comment]
Hi @finalfrontz98 ,
can you check if your antivirus messed up the arduino installation (or blacklisted `avr-g++` executable) ? Checking if the files exists in that folder could be enough.

**Comment by finalfrontz98** [comment]
Hi @facchinm, 
thank you for pointing out about the problem I'm facing. But how do I check if my antivirus is messing up the installation? Can you give me a thoroughly steps on how to check it? Lately, the notification of antivirus always pops up. Thank you

**Comment by facchinm** [comment]
I would tell you to take a look at the Quarantine folder of your antivirus and check if there's something in there, or whitelist Arduino installation folder and reinstall it over the broken installation. But not knowing your exact setup makes it a bit difficult to give you very precise instructions :slightly_smiling_face:
