### ISSUE TITLE
arduino 1.8.7 port greyed out error code 52. 

### ISSUE THREAD

**Issue by studiousk** [arduino/Arduino#8065]
i tried installing the drivers manually from arduino folder but it shows error code 52. Nthng is working. even tried reinstalling the arduino still not working. Please suggest solution to this problem.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
