### ISSUE TITLE
apparmor permission linux systems

### ISSUE THREAD

**Issue by kornwaretm** [arduino/Arduino#8067]
i think the apparmor profile missing permission to access tty devices. both snap.arduino-mhall119.arduino and snap.arduino-mhall119.builder. 

i added this line to both files. 
/dev/tty* rw,

**Comment by per1234** [comment]
The arduino-mhall119 snap package is a 3rd party project not affiliated with the Arduino organization so it is not appropriate to report bugs in that package here. If you install the latest official Arduino IDE build downloaded from:
https://www.arduino.cc/en/Main/Software
and find the problem also occurs with it then please comment here and I'll re-open.

**Comment by kornwaretm** [comment]
oh my bad. i'm sorry.
