### ISSUE TITLE
Arduino Zero cross serial strings with serialUSB

### ISSUE THREAD

**Issue by warriorfenixSM** [arduino/Arduino#8072]
Hi,

I try to use all serial ports in Arduino Zero with native usb port, Serial1 and SerialUSB works fine, but when i try to send a string with Serial (Serial.println("HELLO"); but instead of send throw Serial send the string thow USB. And i don't have any idea.

Please Help

**Comment by facchinm** [comment]
On the Arduino Zero the Serial object is mapped to the Programming USB port, Serial USB to Native port and Serial1 to pins 0/1 (see https://www.arduino.cc/en/Guide/ArduinoZero)
