### ISSUE TITLE
Compile error under Intel Xeon CPU E5-2630

### ISSUE THREAD

**Issue by eziya** [arduino/Arduino#8087]
Hello, 

I installed Arduino IDE at one of my PC which has Intel Xeon CPU E5-2630. (Windows7 Enterprise 64bit)
And it returns compilation errors for every examples like below. 

But if I changed Arduino version as 1.6.11 at board manager, it works without error. 
I guess that over 1.6.11 version has a compatibility issue with Intel Xeon CPU E5-2630.

[1.6.23 Error]
`
"C:\Users\kiki\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\5.4.0-atmel3.6.1-arduino2/bin/avr-gcc" -Wall -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p  -o "C:\Users\kiki\AppData\Local\Temp\arduino_build_9388/Blink.ino.elf" "C:\Users\kiki\AppData\Local\Temp\arduino_build_9388\sketch\Blink.ino.cpp.o" "C:\Users\kiki\AppData\Local\Temp\arduino_build_9388/..\arduino_cache_220929\core\core_arduino_avr_uno_fb933ce05b1df03f3b91ed6505233e1f.a" "-LC:\Users\kiki\AppData\Local\Temp\arduino_build_9388" -lm
`__vector_16' referenced in section `.vectors' of c:/users/kiki/appdata/local/arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/lib/avr5/crtatmega328p.o: defined in discarded section `.text' of wiring.c.o (symbol from plugin)

c:/users/kiki/appdata/local/arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/lib/avr5/crtatmega328p.o:(.init9+0x0): undefined reference to `main'

collect2.exe: error: ld returned 1 exit status

exit status 1
`

[1.6.11 No Error]
`
Linking everything together...
"C:\Users\kiki\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-gcc" -Wall -Os -Wl,--gc-sections -mmcu=atmega328p  -o "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/Blink.ino.elf" "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972\sketch\Blink.ino.cpp.o" "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/core\core.a" "-LC:\Users\kiki\AppData\Local\Temp\arduino_build_227972" -lm
"C:\Users\kiki\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/Blink.ino.elf" "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/Blink.ino.eep"
"C:\Users\kiki\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-objcopy" -O ihex -R .eeprom  "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/Blink.ino.elf" "C:\Users\kiki\AppData\Local\Temp\arduino_build_227972/Blink.ino.hex"
Sketch uses 0 bytes (0%) of program storage space. Maximum is 32256 bytes.
Global variables use 0 bytes (0%) of dynamic memory, leaving 2048 bytes for local variables. Maximum is 2048 bytes.
`

**Comment by facchinm** [comment]
Hi @eziya,
between 1.6.11 and 1.6.23 we updated the avr toolchain, so it's not related with your processor.
Anyway, probably your sketch overrides `main` function, which is not allowed (you can see that the sketch compiled with 1.6.11 is empty). This normally happens when you declare a variable called `main` somewhere and the whole main function gets elided. Make sure that the sketch compiled with 1.6.11 works as intended before reporting a bug :wink:

**Comment by eziya** [comment]
As I used blink example without modification, I think that there's no possibility of declaring variable called main. And blink example compiled with 1.6.11 works fine.

**Comment by facchinm** [comment]
A Blink compiled for the Uno on 1.6.11 should take
```
Sketch uses 1066 bytes (3%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.
```
The sketch you are compiling reports
```
Sketch uses 0 bytes (0%) of program storage space. Maximum is 32256 bytes. Global variables use 0 bytes (0%) of dynamic memory, leaving 2048 bytes for local variables. Maximum is 2048 bytes.
```
So you are either not compiling a blink or something is super wrong. Could you paste the whole verbose output (no only the linker phase)? Thanks
