### ISSUE TITLE
advertisement covering reference home page

### ISSUE THREAD

**Issue by jcanzler** [arduino/Arduino#8089]
Your MKR family advertisement is making it difficult to use the reference page because it is block key portions of the text and syntax.

**Comment by per1234** [comment]
Here's a screenshot of the problem:
![clipboard01](https://user-images.githubusercontent.com/8572152/46874322-be647d00-cded-11e8-8ca6-25174178c7d5.jpg)
It doesn't occur for me with Firefox, only the Chrome browser.

**Comment by per1234** [comment]
The problem no longer occurs for me after a Ctrl+F5 refresh so that makes me suspect the problem was fixed, but that the website team didn't bother to close this issue report. @jcanzler does the problem still occur for you?

**Comment by smellai** [comment]
Yes please try to clear browser cache and check if looks better
