### ISSUE TITLE
Brain dead printer function? [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#809]
This is [Issue 809](http://code.google.com/p/arduino/issues/detail?id=809) moved from a Google Code project.
Added by 2012-02-07T23:48:31.000Z by [RCR...@gmail.com](http://code.google.com/u/110207018853775726441/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.Load a sketch and have printer/network printer off line.
2. try to print File/print/ok to queue up print job for later printing
(e.g. late at night and not wanting to wake family with printer noise).
3. OR try to print with printer ON line

**What is the expected output? What do you see instead?**
Print job queued up or Printed output.

java.awt.print.PrinterException: Printer is not accepting job.
	at sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1296)
	at sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1247)
	at processing.app.Editor.handlePrint(Editor.java:2593)
blah blah 
for printer off line,

If printer ONLINE get 'Done Printing' but NO job output and no queuing.
Printer still works correctly for other programs.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
1.0, Win 7 pro, N/A

**Please provide any additional information below.**

I EXPECT to be able to queue print jobs when the printer is off line, but Arduino blows up instead of shipping data to print manager.
I also expect it to recover from this sort of error and PRINT when the printer gets put on line. It doesn't.

Other forum posts suggest I need to cut and paste to another program.
If that is the case, WHY is there a 'print' menu?
And I rather do like the syntax highlighting I would expect to get on a color printer.

**Comment by ffissore** [comment]
Works fine with latest IDE
