### ISSUE TITLE
[Library Manager] New library for TI ADS1118 ADC released.

### ISSUE THREAD

**Issue by alvaro-salazar** [arduino/Arduino#8095]
I released a new Arduino Library for "Texas Instruments ADS1118 - 16-Bit Analog-to-Digital Converter with internal Reference and Temperature Sensor".

https://github.com/denkitronik/ADS1118

It's an easy to use Arduino library for ADC Converter ADS1118.

Please add it to Arduino Library Manager.

Thanks

**Comment by cmaglie** [comment]
Done!
