### ISSUE TITLE
[Library Manager] Please add BNO055 server for SimplePacketComs library

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#8101]
https://github.com/madhephaestus/BNO055SimplePacketComs

This library adds Simple Packet Coms server of the BNO055 IMU module. The server is not platform dependant and will work with any implementation of SImplePacketComs

**Comment by madhephaestus** [comment]
@per1234 Thank you!

**Comment by cmaglie** [comment]
Done!
