### ISSUE TITLE
[Library Manager] Please add ESP32Encoder an interrupt driven encoder library for ESP32

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#8102]
https://github.com/madhephaestus/ESP32Encoder

This library uses the ESP32 interrupt system to build an interrupt driven encoder library. This library supports up to 10 full quadrature encoders on a single ESP32.

**Comment by madhephaestus** [comment]
@per1234 Thank you!

**Comment by cmaglie** [comment]
Done!
