### ISSUE TITLE
[Library Manager] USBMIDI library

### ISSUE THREAD

**Issue by gtrainavicius** [arduino/Arduino#8103]
Please add https://github.com/BlokasLabs/USBMIDI to the Library Manager.

It's a library implementing USBMIDI functionality following the familiar Serial interface, so transitioning existing MIDI code written for Serial is very straightforward. Also since v1.1.0 this library now uses V-USB to implement USBMIDI on AVR8 chips without native USB support.

Thank you!

**Comment by cmaglie** [comment]
done!
