### ISSUE TITLE
Error on Serial to Parallel Shifting-Out with a 74HC595 documentation page

### ISSUE THREAD

**Issue by bdejoly** [arduino/Arduino#8113]
seems to be some errors on the 74HC595 diagram showing false pins positions.
https://www.arduino.cc/en/Tutorial/ShiftOut

**Comment by per1234** [comment]
It would be much more helpful if you said which diagram and which pins are in error.

**Comment by per1234** [comment]
Since it sounds like this may have been a misunderstanding of how IC pinouts are represented in schematics, I'm going to go ahead and close it. If there is an error and someone can comment here with a detailed description of it, I'll be happy to reopen.
