### ISSUE TITLE
[Library Manager] Please Add Arduino-MAX17055_Driver

### ISSUE THREAD

**Issue by amperpirat** [arduino/Arduino#8114]
Please add the following to the library manager for "Arduino-MAX17055_Driver" with v1.0.1 release:
https://github.com/AwotG/Arduino-MAX17055_Driver
Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by per1234** [comment]
Since the necessary tag was never created, I'm going to go ahead and close this. If you ever feel like bringing the repository into compliance, feel free to comment here and I'll re-open.
