### ISSUE TITLE
Why Arduino WHY ?

### ISSUE THREAD

**Issue by ArduinoHateonlyacc4thiscomment** [arduino/Arduino#8120]
This so good called "Software" named Arduino IDE is literally the worst Software i will ever encounter in my entire LIFE !

Its so fucking buggy that it wont even ever fcking WORK ON ANY Computer like my HomePC, in schools, so everywhere !

If you try to connect one God damn Thing via the Right Com port, rates and so on it never EVER will start to upload the code to it even if its just the start code with setup and loop function.

So i ask myself why is ist possible that i try every Combination of any Setting i can in my lifespan and it will NEVER Recognize even A FCKING VOLTAGE thats applied to the Usb Port.

So if its possible to throm my eq outta the window and buy hole new pc and This nasty IDE works then i might change this comment to a word less rude if its not banned until then by some guys saying,

uhhhh youre just to bad at IT in a whole or dont understand anything and this other basic replies to a form of  
criticism i dont mind cause i know that this IDE wont Run for what so ever unknown broken Transistor in my CPU or so ever. so bye hope you dont have problems with that shit at all.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. You haven't provided any information that indicates a bug so I'm going to close this. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Take some deep breaths and calm down. You won't get a good response on the forum with this sort of attitude. If you just wanted to vent, then mission accomplished. But if you're interested in getting a solution to your problem then you'll need to provide precise details.
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
