### ISSUE TITLE
[Library Manager] Please add AnyRTTTL

### ISSUE THREAD

**Issue by end2endzone** [arduino/Arduino#8121]
Please add the AnyRTTTL library to the Library Manager:

https://github.com/end2endzone/AnyRtttl

Thanks.

**Comment by cmaglie** [comment]
Done!

**Comment by end2endzone** [comment]
that was fast! thank you!

**Comment by per1234** [comment]
It works for me:
![clipboard01](https://user-images.githubusercontent.com/8572152/47606574-de896400-d9c9-11e8-822e-0a71cb19d8ed.png)
You can try deleting the local library index files to make sure the Arduino IDE downloads a fresh copy. I seem to remember some problems in the past IDE versions where a corrupted download could block subsequent attempts:

1. Click the link at the line following **File > Preferences > More preferences can be edited directly in the file**.
2. Delete all files that have names starting with library.index.
3. Check Library Manager again to see if AnyRtttl now appears.
