### ISSUE TITLE
AWT-EventQueue-0 100% CPU usage

### ISSUE THREAD

**Issue by cb88** [arduino/Arduino#8126]
![profiler](https://user-images.githubusercontent.com/1026000/47368453-ac1cf580-d6af-11e8-9c6e-fdb41307f395.PNG)

This occurs right after opening up any sketch and hitting compile. On Windows 7 64bit with Arduino IDE 1.8.7, Java 8 191

Opening the menus seems to cause it to cease temporarily.

**Comment by facchinm** [comment]
Thanks for reporting! Can you try bisecting the problem (trying 1.8.7) to check if it's a regression in master? I truly hope it's not due to java u191 (just had a similar bug with u171, https://github.com/arduino/Arduino/issues/8009 )

**Comment by cb88** [comment]
Well I was having 100% CPU usages on a much older Java 8 version also and recently updated as I thought that might solve the problem. 

Also I had Arduino 1.8.3 installed and it was happening there also but didn't profile it so not sure if it is the same exact bug... it appears the same superficially though.

**Comment by cb88** [comment]
This is in 1.8.6 

![profiler-1 8 6](https://user-images.githubusercontent.com/1026000/47370794-7a5a5d80-d6b4-11e8-83c0-726bac422777.PNG)

**Comment by facchinm** [comment]
On 1.8.7 the bundled jre is u171, and the system-wide installation is not relevant. To test with u191, please download the hourly build from https://www.arduino.cc/en/Main/Software#hourly . Thanks for testing!

**Comment by cb88** [comment]
Initial testing on the nightly seems to show that it isn't happening there (though running from a folder on my desktop may be different than from the installed folder). 

![profiler-1 8 8-nightly-10-23-2018](https://user-images.githubusercontent.com/1026000/47372255-67955800-d6b7-11e8-9802-b5e8a75587b1.PNG)

**Comment by per1234** [comment]
Since this is reported to not occur in the hourly build, I'm closing as solved.
