### ISSUE TITLE
how i can solve this problem ? in LIFA_Base LabVIEWInterface.ino: note: containing loop 

### ISSUE THREAD

**Issue by Gamiy** [arduino/Arduino#8127]

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code and the **FULL** error output, using code tags (`</>` button on the toolbar).
