### ISSUE TITLE
Can we add CH340 UART driver support?

### ISSUE THREAD

**Issue by alexceltare2** [arduino/Arduino#8130]
So far the 'drivers' folder in Windows has Atmega, FTDI, Silabs and Adafruit in it. Can we also add wch.cn's CH340(G) driver as it's widely used in many boards?

**Comment by facchinm** [comment]
@alexceltare2 , CH* serial to USB converter are not being used on any official Arduino board, while all the bundled ones are needed for a board or another. Hope this answers your question :wink:
