### ISSUE TITLE
[Library Manager] Please add ACAN2517 and ACAN2517FD libraries

### ISSUE THREAD

**Issue by pierremolinaro** [arduino/Arduino#8135]
Hello,

Please, can you include my ACAN2517 and ACAN2517FD libraries (CAN driver for MCP2517FD CAN Controller):
https://github.com/pierremolinaro/acan2517FD
https://github.com/pierremolinaro/acan2517

Best regards,

Pierre Molinaro

**Comment by per1234** [comment]
Each library in the Library Manager index must have a unique `name` value in library.properties. Both of your libraries have the same `name` value: `ACAN2517`. Please change the `name` value in one of the library.properties files and then either create a new tag/release or redo the existing one.

Once you've done so, please comment here so we'll know we can proceed.

**Comment by pierremolinaro** [comment]
Sorry for the mistake. I have changed name to ACAN2517FD in the library of the same name, and make a new release.

Thanks,

Pierre Molinaro

**Comment by cmaglie** [comment]
done!

**Comment by pierremolinaro** [comment]
Thank you very much !
