### ISSUE TITLE
memory leak in SD library - IDE 1.0  [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#814]
This is [Issue 814](http://code.google.com/p/arduino/issues/detail?id=814) moved from a Google Code project.
Added by 2012-02-12T11:08:47.000Z by [rob.till...@gmail.com](http://code.google.com/u/113198963792305667520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

JGoulder reported:

When a file is opened a malloc() is performed to get memory.  When a file is closed the memory is freed. If the file object is destroyed before the file is closed, the memory is never freed.

- http://arduino.cc/forum/index.php/topic,91472.0.html -

Existing code:

File::~File(void) {
  //  Serial.print("Deleted file object");
}

JGoulder also proposed a fix:

File::~File(void) {
  close();
  //  Serial.print("Deleted file object");
}

**Comment by sandeepmistry** [comment]
Closing this, as there were no further discussions after Oct. 15, 2013.
