### ISSUE TITLE
Problems verifying and uploading code on Arduino Create website

### ISSUE THREAD

**Issue by ChrisWong12** [arduino/Arduino#8142]
Hi there,

I am a teacher using SMRAZA UNO arduino-compatible micro controllers in class.  Things have been working very well so far for the past couple of months.  I have students writing code on Arduino Create Online IDE but last week my students have repeatedly run into errors when trying to verify and upload code.  Even code that previously worked is no longer verified or uploaded to the UNO.

Here is the error message that I am receiving:

**./opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -hardware opt/arduino-builder/hardware -hardware ./opt/cores -tools opt/arduino-builder/tools -tools ./opt/tools -built-in-libraries opt/libraries/latest -logger humantags -fqbn arduino:avr:uno -build-cache /tmp -build-path /tmp/733499762/build -verbose -prefs runtime.tools.avr-gcc.path=./opt/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs runtime.tools.avrdude.path=./opt/tools/avrdude/6.3.0-arduino14 -prefs runtime.tools.arduinoOTA.path=./opt/tools/arduinoOTA/1.2.1 -libraries /tmp/733499762/custom -libraries /tmp/733499762/pinned /tmp/733499762/sketch_sep17a

Linking everything together...

lto1: fatal error: bytecode stream generated with LTO version 3.0 instead of the expected 4.1

compilation terminated.

lto-wrapper: fatal error: ./opt/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc returned 1 exit status

compilation terminated.

/home/ubuntu/opt/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: error: lto-wrapper failed

collect2: error: ld returned 1 exit status

exit status 1** 

Does anyone have any ideas?  I believe this is an issue on the Arduino create site but have not found any notices on their website.

Thank you in advance for you help,
Christopher Wong
(cwong@mail.vc.bc.ca)

**Comment by per1234** [comment]
According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor. There are already multiple reports of this bug in that forum section so I'm sure the Arduino developers will be aware of this problem. I recommend you to subscribe to those threads for news of progress in fixing it:

- http://forum.arduino.cc/index.php?topic=576588
- http://forum.arduino.cc/index.php?topic=576587
- http://forum.arduino.cc/index.php?topic=576600
