### ISSUE TITLE
Arduino IDE running on Linux shows compiler errors wrong [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#815]
This is [Issue 815](http://code.google.com/p/arduino/issues/detail?id=815) moved from a Google Code project.
Added by 2012-02-13T20:55:05.000Z by [happyhac...@temporaryemailaddress.com](http://code.google.com/u/110967142945996612259/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

>What steps will reproduce the problem?
1. Open an example, like Blink
2. Make any syntax error, like removing a semicolon in line 11
3. Klick verify button

> What is the expected output? 
1. Red bar shows the first compiler error message.
2. Compiler messages in the black area with correct line numbers.
See the attached screenshot of the Windows window.

>What do you see instead?
1. Red bar shows only "Error compiling.".
2. Compiler messages in the black area with wrong (too big) line numbers.
See the attached screenshot of the Linux window.
This issue appears only on Linux!

>What version of the Arduino software are you using? 
Issue appears since Arduino 0017 until Arduino 1.0

>On what operating system?  
Since Ubuntu 10.04 until current Ubuntu 11.10

>Which Arduino board are you using?
Several. 
Not relevant for this issue.

Greetings
Bernhard

**Comment by ffissore** [comment]
Sketch is missing a `;` after `pinMode`

**Comment by cmaglie** [comment]
The OP removed the `;` on purpose to show the problem, BTW the issue seems fixed anyway (at least on the latest hourly build it is).
