### ISSUE TITLE
ESP8266:library AsyncPing

### ISSUE THREAD

**Issue by akaJes** [arduino/Arduino#8152]
https://github.com/akaJes/AsyncPing

**Comment by per1234** [comment]
From https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format:

>Library names must contain only basic letters (A-Z or a-z) and numbers (0-9), spaces (), underscores (_), dots (.) and dashes (-). It cannot start or end with a space, and also it cannot start with a number.

This is referring to the `name` field in library.properties. Your `name` value: `AsyncPing(esp8266)` contains characters not permitted for libraries in the Library Manager index: `(` and `)`.

Please change the name to a valid value and then either create a new release/tag or else redo the existing one.

Once that's done, please comment here so we'll know we can proceed.

**Comment by per1234** [comment]
Since the necessary change was never made, I'm going to go ahead and close this issue. If you ever feel like switching to a compliant `name` value, feel free to comment here and I'll re-open.
