### ISSUE TITLE
[Library Manager] Adafruit Keypad library

### ISSUE THREAD

**Issue by deanm1278** [arduino/Arduino#8159]
https://github.com/adafruit/Adafruit_Keypad

Thanks very much!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by deanm1278** [comment]
oops, forgot! Library has now been updated.
