### ISSUE TITLE
[Library Manager] Add PIDArduino

### ISSUE THREAD

**Issue by DonnyCraft1** [arduino/Arduino#8162]
[Here](https://github.com/DonnyCraft1/PIDArduino) is my GitHub repo.

Thanks!

**Comment by per1234** [comment]
Your library.properties file is misspelled library.properies and is missing required fields. Please make your library.properties file compliant with the Arduino Library Specification and then either create a new tag/release or else redo the existing one.

After that's done, please comment here so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by DonnyCraft1** [comment]
@per1234 I renamed the file, added the required fields and released v1.0.1 with the updated code.

Thanks for the fast response!

**Comment by DonnyCraft1** [comment]
I couldn't figure out what the `architectures` field meant, so I set it to all (*). Do you have any documents explaining this?

Thanks again!

**Comment by per1234** [comment]
The `architectures` field is used for two things:
- Determine priority when multiple libraries match an `#include` directive: Explicit match > wildcard match > mismatch.
- Display a warning when the library is compiled for a board with an architecture that doesn't match the list.

I have added this information to the library specification.

Board architecture is determined by the architecture folder name of the hardware package:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#hardware-folders-structure

**Comment by DonnyCraft1** [comment]
Thank you very much! This was useful to know.

**Comment by DonnyCraft1** [comment]
Let me know if there are any further issues with my library. I'll fix it.

**Comment by cmaglie** [comment]
done!

**Comment by DonnyCraft1** [comment]
Thank you very much!
