### ISSUE TITLE
[Library Manager] Please add PVision IRCamera library

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#8185]
https://github.com/madhephaestus/PVision

This library communicates with the DF Robots IR camera and allows for user settable Wire busses, allowing for 2 or more IR Cameras at once.

**Comment by per1234** [comment]
Leading zeros are not allowed in versions, as you currently have in your library.properties:
https://github.com/madhephaestus/PVision/blob/0.0.2/library.properties#L2
```
version=0.0.01
```

Please use a [semver compliant](https://semver.org/) version number in your library.properties, then either make a new release or else redo the existing release. You should also make sure that the version matches your release version (which it does not currently).

After that's done, please comment here so we'll know we can proceed.

**Comment by madhephaestus** [comment]
I fixed this issue.

**Comment by madhephaestus** [comment]
Pull requests merged

**Comment by madhephaestus** [comment]
New version with corrections published.

**Comment by cmaglie** [comment]
done!

**Comment by madhephaestus** [comment]
@cmaglie Thank you!
