### ISSUE TITLE
DHT_sensors_libary: MCU high signal works against DHT pulldown

### ISSUE THREAD

**Issue by andreobi** [arduino/Arduino#8189]
The DHT read timing is almost right. So what is not perfect:
- MCU keeps the data line low - okay
- MCU pulls the data line high for 40us - the DHT specification say it could go down after 20us and it tries!
- ... rest is okay

So my proposal is to make a timing  change in the DHT.cpp lib

make only a short push up (5 instead of 40us)  and then wait longer (45us instead of 10us) so the sampling starts after the same 50us time and the sensor can pull down the data line after 20us.

  uint32_t cycles[80];
  {
    // Turn off interrupts temporarily because the next sections are timing critical
    // and we don't want any interruptions.
    InterruptLock lock;

    // End the start signal by setting data line high for 40 microseconds.
    digitalWrite(_pin, HIGH);
    **delayMicroseconds(5); // 5us instead of 40us**

    // Now start reading the data line to get the value from the DHT sensor.
    pinMode(_pin, INPUT_PULLUP);
    **delayMicroseconds(45);  // 45us instead of 10us**

    // First expect a low signal for ~80 microseconds followed by a high signal
    // for ~80 microseconds again.

**Comment by per1234** [comment]
This issue tracker is only to report bugs or feature requests for official Arduino projects. The DHT sensor library is a 3rd party library and so discussion of it is off-topic here. Feel free to submit your proposal to the appropriate repository.
