### ISSUE TITLE
8x8 Matrix with 2 74HC595

### ISSUE THREAD

**Issue by TDSkyz** [arduino/Arduino#8190]
Hey Everyone,

I was wondering if anyone knew of a good resource/tutorial for using a couple of 74HC595 shift registers in order to create an 8x8 LED matrix? I've seen some projects using these, but they never seem to explain it very well. So if you happen to have one bookmarked, let me know please! 

Thanks!

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests, **NOT** to request help with your project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
