### ISSUE TITLE
LOGIN: CSRF: OOPS, SOMETHING WENT WRONG, PLEASE TRY AGAIN.

### ISSUE THREAD

**Issue by Flavio-da-Brescia** [arduino/Arduino#8192]
LOGIN: CSRF: OOPS, SOMETHING WENT WRONG, PLEASE TRY AGAIN.
What is this error?

I use chrome to login to arduino create, since forever, on windows 10, lenovo pc. Yesterday I started getting this error as i try to login to open my sketches. 
I am in seriuos trouble here. I cant move past the sign in screen

**Comment by gvarisco** [comment]
Hey @Flavio-da-Brescia, thanks for contacting us. I wonder if any of your Chrome extensions is play a game here and troubling with the session cookie(s). Could you please remove your cookie set for create.arduino.cc and try again? You can also give it a try by logging-in using Incognito mode. Do let us know!

**Comment by Flavio-da-Brescia** [comment]
Ciao Gianluca,

I tried incognito mode, and it works. I then tried removing all arduino
cookies, but it wasn't working. I tried removing all extensions and it now
works. Apparently one of them was my problem.

Thank you very much. Should I take any action regarding the issue I opnened
on github?

Have a nice day.

Flavio.

**Comment by gvarisco** [comment]
Awesome, thanks for getting back to us so quickly. I'll go ahead and mark this as 'closed'. Feel free to re-open it if you encounter further issues.

Have a great day, Flavio!

**Comment by aster94** [comment]
Hello, same problem here, in my case the culprit extension was **Safe Torrent Scanner** from utorrent web which, i guess, a lot of people use this is the reason why I am writing this

**Comment by molobox** [comment]
confirmed: Same problem **Registering** and **Signing** because of **Safe Torrent Scanner** installed by (I assume) an automatic update of the immediately uninstalled **uTorrent Web**!!

**Comment by rkivanov** [comment]
Thank you aster94! I confirm that this works. It is enough to turn off Save Torrent Scanner form Google extensions (At the top right, click 3 vertical dots, then more tools, and then Extensions).
