### ISSUE TITLE
Add PhpocExpansion to Library Manager

### ISSUE THREAD

**Issue by phpoc** [arduino/Arduino#8204]
I'd like to add our arduino library which is called PhpocExpansion to Library Manager.

Here is the repository URL of it.
https://github.com/phpoc/arduino-PhpocExpansion

This library is to use [Smart Expansion Board for PHPoC (WiFi) Shield 2](https://www.phpoc.com/expansion_board_for_phpoc_shield.php).

Thank you for your support.

**Comment by cmaglie** [comment]
done!
