### ISSUE TITLE
Incorrect encoding of compiler log for Korean!

### ISSUE THREAD

**Issue by BrightLin** [arduino/Arduino#8212]
Step:
- PC language:  Simplified Chinese.
- Installed Korean font support.
- Arduino IDE language: Korean.
- Verify!

Issue:
- unknown chars at compiler log window like "???? ???? ?? ?? 444 ???(1%)? ??. ?? 32256 ???."

Please see the following images. Thanks.

![2](https://user-images.githubusercontent.com/15828392/48754677-7b8ba400-eccd-11e8-9107-b25cdb291157.png)
![1](https://user-images.githubusercontent.com/15828392/48754678-7b8ba400-eccd-11e8-8383-5f5b737f2bce.png)
![3](https://user-images.githubusercontent.com/15828392/48754679-7c243a80-eccd-11e8-96f5-efee630d7347.png)

**Comment by hanj-kim** [comment]
would you add '-Dfile.encoding=UTF8' in  arduino.l4j.ini or arduino_debug.i4j.ini file ?

![image](https://user-images.githubusercontent.com/25259908/48774905-d2659d80-ed0e-11e8-822f-e289c900f142.png)

**Comment by BrightLin** [comment]
@hanj-kim Yeah~ It works. Thank you

**Comment by feikname** [comment]
Is there any possible issue with having this option as default? If not, I'd like to suggest to add it to launch parameters of the next version.
