### ISSUE TITLE
Arduino Rfid problem

### ISSUE THREAD

**Issue by pupil01** [arduino/Arduino#8224]
i cant see my card id it tells me that : Firmware Version: 0x80 = (unknown)
Scan PICC to see UID, SAK, type, and data blocks... 
please help in can.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide enough details for us to help you.
