### ISSUE TITLE
[Library Manager] Please add arduino-async-duplex and arduino-async-modem

### ISSUE THREAD

**Issue by coddingtonbear** [arduino/Arduino#8225]
I've recently created a couple libraries that might be useful for folks interacting with devices requiring call-and-response style commands (like the `AT` commands so commonly used by GSM/LTE modems); if you wouldn't mind, could you please add the following two libraries to the Library Manager?

* https://github.com/coddingtonbear/arduino-async-modem
* https://github.com/coddingtonbear/arduino-async-duplex

Cheers!

**Comment by cmaglie** [comment]
Done!
