### ISSUE TITLE
MKR Wifi 1010 Upload

### ISSUE THREAD

**Issue by harounhajem** [arduino/Arduino#8226]
Every time i upload to your board the upload fail and windows start to update the board drivers for some reason, and it changes the port. The drivers are working and added before the upload of the sketch and also the correct port is selected. This is double checked by me. 

Is the board broken or your IDE broken? I have a feeling if this keeps up the board will eventually be bricked. I've paid 30€ for premium product but your device doesn't work.

![bild](https://user-images.githubusercontent.com/17148955/48922846-bfd39b80-eea9-11e8-89f7-418a21bf0ad5.png)

Error message log: 

```
Arduino: 1.8.5 (Windows 7), Board: "Arduino MKR WiFi 1010"

Sketch uses 10632 bytes (4%) of program storage space. Maximum is 262144 bytes.
Atmel SMART device 0x10010005 found
Device       : ATSAMD21G18A
Chip ID      : 10010005
Version      : v2.0 [Arduino:XYZ] Mar 19 2018 09:45:14
Address      : 8192
Pages        : 3968
Page Size    : 64 bytes
Total Size   : 248KB
Planes       : 1
Lock Regions : 16
Locked       : none
Security     : false
Boot Flash   : true
BOD          : false
BOR          : false
Arduino      : FAST_CHIP_ERASE
Arduino      : FAST_MULTI_PAGE_WRITE
Arduino      : CAN_CHECKSUM_MEMORY_BUFFER
Erase flash
done in 0.640 seconds

Write 10904 bytes to flash (171 pages)

SAM-BA operation failed
An error occurred while uploading the sketch

[===========                   ] 37% (64/171 pages)
[======================        ] 74% (128/171 pages)
[==============================] 100% (171/171 pages)
done in 0.066 seconds

Verify 10904 bytes of flash with checksum.
Verify successful
done in 0.017 seconds
CPU reset.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by facchinm** [comment]
Hi @harounhajem ,
what is happening is very very strange; the uploader program (`bossac`) seems to execute correctly so the reported error could be about it crashing after upload.
The serial port reenumeration is strange too but it could be related with some component installed in the PC (antivirus?)
May I ask you to enable verbose upload from File/Preferences, copy here the commandline (which will start with something like `C:\Users\yourusername\Arduino15\.....\bossac.exe`) and your pc specifications (Widnows 7 edition and patch version, installed antivirus) ?
Thanks!

**Comment by harounhajem** [comment]
I now did an successful upload of an example sketch and directly afterwards the device again got disconnected, changed COM port and  this time it never came back up as listed device. Now when i connect the device **_windows doesn't recognize_** it and says something like; _The usb-device is not recognized, recommendation: try to reconnect if this doesn't change your device is faulty._ 

I had a feeling it would end up like this since the first error turned up. I only bought this device as an assurance for not dealing with any low-level bugs so i could carry on with my development. 

Do you have any suggestions? Should i send it in? 

I'm running **Windows 10 Home** with **Arduino IDE 1.8.7** and no anti virus besides the windows builtin anti virus system. 

![bild](https://user-images.githubusercontent.com/17148955/49834153-fe1ef500-fd9b-11e8-80a5-66b98c88b013.png)

_it's in Swedish, but i says unknown usb-device(the request for device description failed)_

**Comment by facchinm** [comment]
May I ask you to try using another USB cable (or plug into another USB port)? If windows complains about descriptors it means that something is going fundamentally going wrong at an hardware level. It may also be the board itself, maybe the USB connector is not perfectly soldered; in this case I'd ask you to contact the support for a replacement.

**Comment by harounhajem** [comment]
I've spoken to Store support about replacement and they told me to reset the device, with double tap on the reset button so the orange LED starts fade. Now it works again. But what i can see in verbose upload is that the COM-port is changing.  It is found in the windows device manager on COM3
````
Sketch uses 10952 bytes (4%) of program storage space. Maximum is 262144 bytes.
Forcing reset using 1200bps open/close on port COM3
PORTS {COM3, } / {} => {}
PORTS {} / {COM5, } => {COM5, }
Found upload port: COM5
````

**Comment by per1234** [comment]
I'm glad to hear you got it working again! The port change is indeed the expected behavior. After the reset, the bootloader runs and this is enumerated to a different port. After the upload, the board should again appear at COM3.
