### ISSUE TITLE
[Library Manager] Please add Esp8266MQTTClient

### ISSUE THREAD

**Issue by plapointe6** [arduino/Arduino#8231]
Hello, I created a library that is usefull for wifi and mqtt handling with ESP's

https://github.com/plapointe6/EspMQTTClient
~~https://github.com/plapointe6/Esp8266MQTTClient~~

Thank you

**Comment by plapointe6** [comment]
Hello, my apologies !
I renamed it to EspMQTTClient : https://github.com/plapointe6/EspMQTTClient
Regards

**Comment by cmaglie** [comment]
Done
