### ISSUE TITLE
Please include the library https://github.com/mcci-catena/Catena-mcciadk in the list

### ISSUE THREAD

**Issue by terrillmoore** [arduino/Arduino#8232]
Please add MCCI's utility library to the list: https://github.com/mcci-catena/Catena-mcciadk

**Comment by cmaglie** [comment]
@terrillmoore the library name `Catena MCCI Arduino Development Kit (ADK)` contains the parenthesis `(` and `)`, we had problems in the past with that so now this is no more allowed by our policy. Please change the name of the library in library.properties and redo the release tag.

**Comment by terrillmoore** [comment]
@cmaglie thanks for your feedback. The libary.properties file was updated and the version is now v0.2.0.

**Comment by cmaglie** [comment]
done!
