### ISSUE TITLE
Can't access buttons on Preferences window on screens with vertical resolution of 600 px (again)

### ISSUE THREAD

**Issue by rin67630** [arduino/Arduino#8238]
On IDE 1.8.7 ARM  (Raspberry Pi)
The [Cancel] and [OK] buttons of the preference settings are still out of reach on screens with 600px heigth.

Please consider rearranging the 8 tick options on two rows of 4.
That should reduce the overall heigth enough to fit.

Thank you.

**Comment by PaulStoffregen** [comment]
As I suggested on #6459, you really should post a screenshot of the problem, so developers can see the problem (without the trouble of using a Raspberry Pi *and* a special/tiny monitor).  Notice just below the text entry it says "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."  That's how you put the screenshot into your message here.

**Comment by rin67630** [comment]
Here the current screen on a 1024x600 screen:
![github 8238 1](https://user-images.githubusercontent.com/14197155/49097480-1a377800-f26d-11e8-9fe3-404f5c6a8d9d.jpg)
My proposal:
![github 8238 2](https://user-images.githubusercontent.com/14197155/49097501-26bbd080-f26d-11e8-8106-931a765cfebc.jpg)
Alternatively, bringing a drawer to the window would be more universal.

**Comment by rin67630** [comment]
By the way: you don't need a Raspberry Pi and a special/tiny monitor to test: just set your screen resolution to 800x600 on your current PC and enjoy the trouble as well. 
Regards.
Laszlo

**Comment by tigoe** [comment]
I don't have strong feelings about the column layout; I'm fine with the change if it helps others. Worth mentioning that the prefs panel is one of the more accessible parts of the IDE on OSX (turn on VoiceOver using command-F5 to navigate it using the screen reader), so I wouldn't want to mess that up.

I think if you're going to change the prefs panel, it's worth considering what else you might add there, perhaps from the preferences.txt or boards.txt, etc. What are the most commonly called for additions from preferences.txt?

**Comment by cjdg** [comment]
Its happening again on 1.8.9

**Comment by cjdg** [comment]
Maybe GUI should be splitted into tabs or adding a scrolling

**Comment by facchinm** [comment]
@cjdg can you provide a screenshot? In 1.8.9 the Preference window is way  shorter than 600px
