### ISSUE TITLE
unable to upload code on Arduino Nano from Mac OS 

### ISSUE THREAD

**Issue by arnavmadan** [arduino/Arduino#8242]
hey I'm stuck in a trouble in which I'm unable to upload code on Arduino Nano from my Mac OS which is up to date both of em, what happens is the serial port isn't visible and I saw a couple of tutorials on youtube which asked to download ch340x driver nd then. run sudo nvram boot-args but the boot args wasn't permitted also I've shared the various error messages below Arduino: 1.8.7 Hourly Build 2018/10/05 11:12 (Mac OS X), Board: "Arduino Nano, ATmega328P"

Sketch uses 1760 bytes (5%) of program storage space. Maximum is 30720 bytes.
Global variables use 188 bytes (9%) of dynamic memory, leaving 1860 bytes for local variables. Maximum is 2048 bytes.
avrdude: ser_open(): can't open device "/dev/cu.wchusbserial1410": No such file or directory
Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

pls help me out cause I'm in an urgent need guys

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
