### ISSUE TITLE
No way to report issues with VidorPeripherals and VidorBoot

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#8244]
The repository title for [VidorPeripherals ](https://github.com/vidor-libraries/VidorPeripherals)and [VidorBoot ](https://github.com/vidor-libraries/VidorBoot)says:
>for issues/PR refer to https://github.com/arduino/VidorLibs

but https://github.com/arduino/VidorLibs does not exist and the issue trackers for those repositories are disabled.

It also seems silly to have a separate repository for issue reports and PRs. I can't imagine how that could be beneficial.

**Comment by facchinm** [comment]
VidorPeripherals and friend library are all generated from a common tree which was meant to be published on https://github.com/arduino/VidorLibs , but we ended up merging that repo into the RTL code at https://github.com/vidor-libraries/VidorBitstream (relevant commit https://github.com/vidor-libraries/VidorBitstream/commit/4a1d3487e108e94fbfa3b50e8d997cf69d13219c) . I'm changing the description accordingly, thanks for noticing!
