### ISSUE TITLE
Arduino Due tri-state buffer error

### ISSUE THREAD

**Issue by yujiy0713** [arduino/Arduino#8249]
Rev 03 IC10 (74LVC1G125DCK) has OE looped back to input signal. This line should be grounded to get clean signal out.

**Comment by agdl** [comment]
@yujiy0713 this is done because in this way you can use the serial externally on pins 0 and 1. If you do not plug the USB the TX is in idle (HIGH) so the buffer is disabled and so you can drive it from the other side with for example another board
