### ISSUE TITLE
[Library Manager] Please add those libraries

### ISSUE THREAD

**Issue by luisllamasbinaburo** [arduino/Arduino#8252]
Hi,

Could you please those libraries to the library manager ?
(sorry, I know they are a lot!)

https://github.com/luisllamasbinaburo/Arduino-StateMachine
https://github.com/luisllamasbinaburo/Arduino-Articulated
https://github.com/luisllamasbinaburo/Arduino-GammaCorrection
https://github.com/luisllamasbinaburo/Arduino-TimeoutTask
https://github.com/luisllamasbinaburo/Arduino-I2CScanner
https://github.com/luisllamasbinaburo/Arduino-List
https://github.com/luisllamasbinaburo/Arduino-LinkedList
https://github.com/luisllamasbinaburo/Arduino-CircularBuffer
https://github.com/luisllamasbinaburo/Arduino-ColorConverter
https://github.com/luisllamasbinaburo/Arduino-PropertyChange
https://github.com/luisllamasbinaburo/Arduino-Stopwatch
https://github.com/luisllamasbinaburo/Arduino-Countdown
https://github.com/luisllamasbinaburo/Arduino-DebounceFilter
https://github.com/luisllamasbinaburo/Arduino-Meanfilter
https://github.com/luisllamasbinaburo/Arduino-MedianFilter
https://github.com/luisllamasbinaburo/Arduino-SingleEmaFilter
https://github.com/luisllamasbinaburo/Arduino-DoubleEmaFilter
https://github.com/luisllamasbinaburo/Arduino-QuickSort
https://github.com/luisllamasbinaburo/Arduino-QuickMedian
https://github.com/luisllamasbinaburo/Arduino-Threshold

Thank you!!

**Comment by cmaglie** [comment]
Done

> (sorry, I know they are a lot!)

np, thanks for opening just one issue for all of them :-)
