### ISSUE TITLE
when will release the official version Arduino IDE 1.8.8?

### ISSUE THREAD

**Issue by czgtest** [arduino/Arduino#8254]
https://github.com/arduino/Arduino/issues/8034
--install-boards esp8266:esp8266:2.4.2 reports Selected board is not available
now I use Arduino IDE 1.8.7 and install  board or library packages in command line.
it always fail , I know this issue was fixed on #8034 
I want to know when will release the official version Arduino IDE 1.8.8.

**Comment by facchinm** [comment]
The goal is to finish merging most of the PR in https://github.com/arduino/Arduino/milestone/33 , particularly the Pluggable discovery one. It will probably take another week or two, no more than that.
