### ISSUE TITLE
Arduino Zero on Tegra TX2

### ISSUE THREAD

**Issue by bpwiselybabu** [arduino/Arduino#8256]
I am attempting to read from a serial port on Ardiono Zero. I dont see the ttyACM0 port for it. Any advice on what I can do to get Tegra TX2 to recognize the serial port on Arduino Zero?
Is this not supported?

**Comment by PaulStoffregen** [comment]
Maybe this?

https://www.jetsonhacks.com/2017/11/19/install-ttyacm-module-nvidia-jetson-tx-development-kits/

**Comment by facchinm** [comment]
As per Paul's comment, the Tegra image does not contain ttyACM modules, that must be installed separately (see also https://github.com/arduino/Arduino/issues/7302#issuecomment-394425973 for another link).
