### ISSUE TITLE
Diamex All-AVR Programmer don't work at Arduino-IDE

### ISSUE THREAD

**Issue by GitKoAlEd** [arduino/Arduino#8266]
For work with Dimex All-AVR Programmer I selected on Arduino-IDE (Version 1.8.5):
Tools/Programmer = "AVRISP mkII" and
Tools/Port ="/dev/ttyS0" Problem is; no usb-port is selectable!
Problem:
If I compile and will programme my software on to µprossor Arduino-IDE starts avrdue (e.g.):
/home/kc-aduino/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude -C/home/kc-aduino/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/etc/avrdude.conf 
-v 
-patmega328p 
-carduino 
-P/dev/ttyS0 
-b9600 
-D 
-Uflash:w:/tmp/arduino_build_251136/MacherDaachBadgeFirmware.ino.hex:i 
 
right would be:

/home/kc-aduino/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/bin/avrdude -C/home/kc-aduino/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14/etc/avrdude.conf 
-v 
-patmega328p 
-cavrisp2
-Pusb 
-D 
-Uflash:w:/tmp/arduino_build_251136/MacherDaachBadgeFirmware.ino.hex:i 

following call-parameters are wrong:
"-carduino"       right is  "-cavrisp2"
"-P/dev/ttyS0"   right is "-Pusb"
"-b9600"           not applicable 
------------------------------------------------------
if I call avrdude in a terminal window with changed parameters then it is going right!!!
Dimex-Programmer is working.
-----------------------------------------------------
I suppose that the problem is in a Arduino-IDE configure-flie like "programmers.text" 
-----------------------------------------------------
Can  somebody help to do the changes?

**Comment by per1234** [comment]
You need to do **Sketch > Upload Using Programmer** to upload to your board using an ISP programmer.
