### ISSUE TITLE
USBasp burns attiny85 from CLI but Arduino IDE fails [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#827]
This is [Issue 827](http://code.google.com/p/arduino/issues/detail?id=827) moved from a Google Code project.
Added by 2012-02-21T22:54:43.000Z by [comer.edward](http://code.google.com/u/comer.edward/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. attiny sketchbook/hardware per http://hlt.media.mit.edu/?p=1229
2. ATtiny85 selected as board in Arduino IDE
3. Upload using usbasp programmer

**What is the expected output? What do you see instead?**
Expected output is good burn as obtained with avedude from command line

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Using Arduino version 1.0 on amd64 Linux system (2.6.32-34-generic #77-Ubuntu). Using a bare ATtin85 chip connected to usbasp programmer.

**Please provide any additional information below.**

The desired target is an ATtiny85 chip running at 8MHz. In the Arduino, I select Tools->board->ATtiny85 (internal 8HMz clock). My programmer is a USBasp.

I have compiled the project code for a nano328 target for testing and it successfully uploads via the usb port.
I have compiled the project code for a ATtiny85 target and it successfully uploads via the USBasp programmer when invoked from the Command Line.
I have compiled the project code for a ATtiny85 target and it fails to upload via the USBasp programmer when invoked from Arduino IDE.

As stated above, I can successfully burn ATtiny85 chips with my USBasp programmer with avrdude from the Command Line, but using the ArduinoIDE fails with these java errors:
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:443)
    at java.lang.Integer.parseInt(Integer.java:514)
    at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:81)
    at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:66)
    at processing.app.Sketch.upload(Sketch.java:1664)
    at processing.app.Sketch.exportApplet(Sketch.java:1624)
    at processing.app.Sketch.exportApplet(Sketch.java:1578)
    at processing.app.Editor$DefaultExportHandler.run(Editor.java:2314)
    at java.lang.Thread.run(Thread.java:636)

After Googling every on-line posting that seemed to be related to similar problems, I became suspicious of the boards.txt and programmers.txt files. I have double checked them and even changed the case of USBasp to usbasp, as suggested in an old forum post, to no avail.

Additional Googling around indicates that the likely cause is Arduino's java code is finding a NULL entry for something that it is looking for in either boards.txt or programmers.txt. I have wondered it it is looking in the ~/arduino/arduino-1.0/sketchbook/hardware/attiny/boards.txt when it is getting things right but somehow reverting to the ~/arduino/arduino-1.0/hardware/arduino/boards.txt file when the java fails - an artifact bug from pre-version 0018 java that didn't look under "sketchbook/hardware" for a boards.txt, perhaps.

I wonder - is there anyone that successfully uses a usbasp programmer from with the Arduino IDE for ATtiny chips?

**Comment by per1234** [comment]
From comment # 1 at https://code.google.com/archive/p/arduino/issues/827:
>This issue can be closed, as written. I was clicking the UPLOAD button instead of selecting File->Upload_Using_Programmer. The USBasp correctly programs the ATtiny85 when selecting File->Upload_Using_Programmer.
