### ISSUE TITLE
Ard IDE Doesn't Honor Aliases on macOS in ~/Library/Aruduino15

### ISSUE THREAD

**Issue by globdesign** [arduino/Arduino#8273]
On macOS the Ard IDE doesn't resolve an alias to ~/Library/Aruduino15, making it impossible to move that folder to another drive.

**Comment by facchinm** [comment]
Hi @globdesign ,
can you explain what you mean with "alias" ? Did you try with a symlink? I'll check what happens as soon as I can replicate your exact steps :slightly_smiling_face:

**Comment by per1234** [comment]
@globdesign we're still waiting for you to provide the requested information so we can proceed with the investigation of this issue.

**Comment by per1234** [comment]
Closing due to lack of response.

@globdesign if you'll make a reply here to provide the requested information I'll be happy to re-open this issue.
