### ISSUE TITLE
can't start arduino ide 1.8.8

### ISSUE THREAD

**Issue by sachinraghav2** [arduino/Arduino#8283]
I recently downloaded Arduino ide 1.8.8. For the first time I started it, it worked fine. But after whenever I start the ide it crashes at initializing packages. I tried the arduino_debugger.exe in cmd line and it showed the following: 
<img width="527" alt="capture" src="https://user-images.githubusercontent.com/41546784/49755979-75db1a00-fcdf-11e8-9451-8cff1625de46.PNG">
thank you for the help in advance.

**Comment by facchinm** [comment]
Hi @sachinraghav2 ,
it looks like this kind of error is generated when OneCloud "ondemand" feature is enabled but the service to sync files back and forth the cloud is not running. 
Is your Arduino installation under a OneCloud synced folder? In case it is, try moving it to another location or disable ondemand sync.

**Comment by sachinraghav2** [comment]
Thank you facchinm. I indeed have an active onedrive service, I'll try to restart Arduino ide after I have disabled it. I'll post what happens, tonight.

**Comment by sachinraghav2** [comment]
> Hi @sachinraghav2 ,
> it looks like this kind of error is generated when OneCloud "ondemand" feature is enabled but the service to sync files back and forth the cloud is not running.
> Is your Arduino installation under a OneCloud synced folder? In case it is, try moving it to another location or disable ondemand sync.

No dude... Its still not working same problem is occurring. I disabled the OneDrive Services on my computer and tried running the IDE... it's still not working. Still showing the same problem.

**Comment by facchinm** [comment]
I'm still not convinced; probably onedrive already "broke" a piece of your filesystem and disabling it in not enough (see https://answers.microsoft.com/en-us/msoffice/forum/msoffice_drive-mso_win10-mso_365hp/issue-error-0x8007016a-the-cloud-file-provider-is/67bf32b6-9627-4970-ac76-58f3831c48e5 or google for `"the cloud file provider is not running"`) . 
To make sure, create a directory called `portable` inside `C:\arduino-1.8.8` . This will transform the installation into a portable one, which won't write or read any file outside that folder.
If the IDE starts, either `C:\yourusername\Documents\Arduino` or `C:\yourusername\AppData\Local\Arduino15` folder are affected by the onedrive bug.

**Comment by sachinraghav2** [comment]
Yes..  You were right. The onedrive service was already disabled on the desktop and i don't how it broke a piece from my Arduino, but the moment I started Arduino with onedrive in active status it downloaded some Java.exe files and the IDE started working. I'll also make that portable folder in the Arduino folder so that this doesn't happen again.. thank you bro..
