### ISSUE TITLE
[Library Manager] please add Programmable-Air library

### ISSUE THREAD

**Issue by tinkrmind** [arduino/Arduino#8288]
The library can be found here: https://github.com/Programmable-Air/Code

The library is for use with Programmable-Air hardware which is essentially a shield for an Arduino Nano. More about the hardware at [https://github.com/Programmable-Air/PCB](https://github.com/Programmable-Air/PCB)

**Comment by cmaglie** [comment]
You must put the content of `programmable_air` folder on the root folder of the git repository (together with LICENSE and README), this is a requirement for publishing the library on the library manager, remember also to redo the tag once done.

**Comment by tinkrmind** [comment]
Thank you for the response. I have moved the files to the root directory and updated the tag.

**Comment by cmaglie** [comment]
Still can't find `library.properties` on the `1.0.0` tag:

https://github.com/Programmable-Air/Code/tree/1.0.0

seems that you forgot to redo the tag on the master branch.

**Comment by tinkrmind** [comment]
My bad! I thought I just had to edit the release. I have issued a new release here:
https://github.com/Programmable-Air/Code/tree/1.0.1
and edited library.properties accordingly.

**Comment by cmaglie** [comment]
done!

**Comment by tinkrmind** [comment]
Yay!!
