### ISSUE TITLE
Library Manager not updating library 

### ISSUE THREAD

**Issue by tipih** [arduino/Arduino#8291]
https://github.com/tipih/NRF51_Radio_library

I have added a few new releases, but release 2.0 is not taken in, Im sure that it is something that I have done wrong, but I do not know what.

**Comment by per1234** [comment]
The reason why the Library Manager indexer didn't pick up your 0.2.0 release is that you didn't update the `version` value in library.properties before making the release:
https://github.com/tipih/NRF51_Radio_library/blob/0.2.0/library.properties#L2

**Comment by tipih** [comment]
OK, got it ! Thanks
