### ISSUE TITLE
Changing repo URLs for existing libraries in Library Manager

### ISSUE THREAD

**Issue by SoleilAtZaber** [arduino/Arduino#8294]
Hello. We are changing the names and URLs of our Arduino library repositories and want to make sure the automatic publication to the Arduino Library Manager will still work. I wasn't able to find information on how to do this so I assume it's not automated, hence this ticket.

The library names in the library.properties files are not changing.

There are two repositories being moved. At present both the old and new versions of each exist; once this ticket is closed I will archive the old ones.

https://gitlab.com/zaber-core-libs/zaber-binary-arduino.git is moving to https://gitlab.com/zaber-core-libs/zaber-binary-for-arduino.git

https://gitlab.com/zaber-core-libs/zaber-ascii-arduino.git is moving to https://gitlab.com/zaber-core-libs/zaber-ascii-for-arduino.git

Please let me know if there is anything I can do to make this happen.

**Comment by cmaglie** [comment]
Done, you can delete the old repos.

**Comment by SoleilAtZaber** [comment]
Thanks!
