### ISSUE TITLE
[Library Manager] register request: ros2arduino library

### ISSUE THREAD

**Issue by OpusK** [arduino/Arduino#8295]
https://github.com/ROBOTIS-GIT/ros2arduino

Hi, we made Arduino library for communicating with ROS2.
The library's name is ros2arduino

We have released [0.0.1](https://github.com/ROBOTIS-GIT/ros2arduino/releases).

Please add our library to Library manager.

Thank you :)

**Comment by cmaglie** [comment]
Done
