### ISSUE TITLE
[Library Manager] Add Adafruit MFRC630 library

### ISSUE THREAD

**Issue by microbuilder** [arduino/Arduino#8296]
Please add in the [Adafruit_MFRC630](https://github.com/adafruit/Adafruit_MFRC630) repo to the library manager? Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by microbuilder** [comment]
Sorry! https://github.com/adafruit/Adafruit_MFRC630/releases/tag/1.0.0

**Comment by cmaglie** [comment]
Done
