### ISSUE TITLE
[1.8.7] Serial monitor "Show timestamp" broken

### ISSUE THREAD

**Issue by cds333** [arduino/Arduino#8299]
Sometimes it works; sometimes it works randomly, inserting a timestamp every three, five or ten lines, and sometimes it doesn't work at all.

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/Arduino/issues/8055

This should be fixed in Arduino IDE 1.8.8

In the future, please test with the hourly build of the Arduino IDE before reporting a bug to make sure it hasn't already been fixed:
https://www.arduino.cc/en/Main/Software#hourly
