### ISSUE TITLE
[Library Manager] add JMASPComm library

### ISSUE THREAD

**Issue by mobinrg** [arduino/Arduino#8300]
Hi, 
I made some Arduino library for simple communicating protocol.
The library's name is JMASPComm and it request JMAFoundation library,  so I submit together them.

Please add in them repo to the library manager? Thanks!

* JMASPComm
https://github.com/mobinrg/JMASPComm

* JMAFoundation
https://github.com/mobinrg/JMAFoundation

**Comment by cmaglie** [comment]
Done!
