### ISSUE TITLE
[Library Manager] Please add AIStarter library to the Library Manager

### ISSUE THREAD

**Issue by dobotopensource** [arduino/Arduino#8303]
Hi. Can you please add AIStarter to the library manager please? Thank you!

https://github.com/dobotopensource/AIStarter

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by cmaglie** [comment]
Done!
