### ISSUE TITLE
Please insert our Library into Arduino Libraries directory

### ISSUE THREAD

**Issue by tcafiero** [arduino/Arduino#8304]
Dear Sirs,
please could you insert or Arduino Library repository URL into your directory:

https://github.com/tcafiero/NBduinoLibrary

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by cmaglie** [comment]
done!
