### ISSUE TITLE
Please add DAC7611 Library to the Library manager

### ISSUE THREAD

**Issue by souviksaha97** [arduino/Arduino#8311]
Hello! Please add this Library to the Library Manager. Thanks.
Please add it from the link down below.
https://github.com/souviksaha97/DAC7611

**Comment by souviksaha97** [comment]
Made the necessary changes. Please let me know if it works.

**Comment by cmaglie** [comment]
I've added the library to the index but the library name is not recognized by the indexer.
I see that you merged a PR made by @per1234 that solves the problem but you should update the tag v1.0 to point to the updated release, to fix this:

1) remove the v1.0 tag
2) re-do the v1.0 on the master branch

once done the library should be published automatically within an hour.

**Comment by souviksaha97** [comment]
I made the necessary changes. I hope it works. Thanks for your patience and help.
