### ISSUE TITLE
Arduino AVR boards later than 1.6.21 onwards- can't update Nano bootloader

### ISSUE THREAD

**Issue by rushilsoni** [arduino/Arduino#8327]
Cannot update Nano bootloader if version on Arduino AVR boards is newer than 1.6.21.
Nano goes into bootloop on Watchdog reset if old bootloader is used

**Comment by per1234** [comment]
Which programmer are you using?

**Comment by rushilsoni** [comment]
Using Arduino UNO in "Arduino as ISP" mode to burn the bootloader to Nano. Works fine if Arduino AVR Boards is downgraded to 1.6.21

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/8032
