### ISSUE TITLE
Basque language translation privileges 

### ISSUE THREAD

**Issue by jm-andonegi** [arduino/Arduino#8328]
Hi:

Recently we have been working in transifex with Basque language strintg. Could you give me manager privileges in that language? It would help us reviewing the strings, because now there is only one manager and he can not spend as much time as he would like working  in revisions.

My user in Transifex is jm.andonegi

Thanks!

**Comment by cmaglie** [comment]
It looks like you're already a "coordinator" but I don't see any "manager" role available the only options are:

- coordinator
- translator
- reviewer

I guess you're already at the maximum level avaiable.
