### ISSUE TITLE
[Library Manager] ported ATmega32U4-Grove-Air-quality-sensor

### ISSUE THREAD

**Issue by JCardoen** [arduino/Arduino#8331]
Hi

I have created a port for the ATmega32U4-based boards (Arduino Yun, Industrial 101 etc.) that interacts with timer interrupts in a different way. As the Grove library is licensed as Open Source I figured I could create a port.

Could you please review this and possibly publish this to the library manager? 

Github repo: https://github.com/JCardoen/ATmega32U4-Grove-Air-quality-sensor
Link to release: https://github.com/JCardoen/ATmega32U4-Grove-Air-quality-sensor/releases/tag/0.0.1

Thanks in advance.

**Comment by cmaglie** [comment]
Done!
