### ISSUE TITLE
MAX6626 Library

### ISSUE THREAD

**Issue by TamojitSaha** [arduino/Arduino#8336]
Please add the library to Arduino Library.
[Here](https://github.com/TamojitSaha/MAX6626_library) is the link to the library to be added.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by TamojitSaha** [comment]
I have created a release.
Please have a look [here](https://github.com/TamojitSaha/MAX6626_library/releases/tag/1.0.0)
If there are any recommendations or suggestions for improving the usability of library, please notify me. I would be happy to make the necessary changes.

**Comment by cmaglie** [comment]
Done!

**Comment by TamojitSaha** [comment]
Thanks @per1234 and @cmaglie
