### ISSUE TITLE
IDE 1.8.8 does not remember last sketch nor window size.

### ISSUE THREAD

**Issue by vimes666** [arduino/Arduino#8337]
I installed IDE 1.8.8 in linux mint (mate versions 18.1 and 19.1) to find that the IDE does not remember the last edited sketch when starting up.
Also it starts with a small window size no matter what the scaling settings are.
On my other pc's I am still using 1.8.5 and they are working ok. 
So I did some digging and found out that version 1.8.7 is still working fine here.
I also found that the issue remembering the last sketch is most likely caused by a reset to zero
of the last.sketch.count (in preferences.txt) at some point by the program.
I have no idea as to what could be causing the window sizing issue though.

**Comment by feikname** [comment]
Are any other settings, e.g. trying to change the font, saved just fine? If not, it might be an issue with your filesystem permissions.

**Comment by vimes666** [comment]
As far as I have checked all changes to the preferences are neatly kept in preferences.txt, except for last.sketch.count. Even the path to the correct last sketch is kept in the preferences, but IDE keeps resetting the last.sketch.count back to zero so it displays the empty sketch skelleton.

**Comment by vimes666** [comment]
update--
I just fixed the windows sizing issue by changing the values of editor.window.height.default and  editor.window.width.default in prefences.txt by hand. This setting now persists after a restart, however IDE will not remember any window resizing. I can live with that.

**Comment by vimes666** [comment]
update--
The last sketch path is not saved in the preferences, I was confused with recent.sketches.

**Comment by vimes666** [comment]
I think I have found the culprit. In this change https://github.com/arduino/Arduino/commit/e1a5be735417bbde1c2a5c85a70da7daea032233#diff-b6fda0bf6be0a53c0741a9b02ac16f37
the quit routine is tidied up. However it also deletes the call to storeScreenDimensions() and  storeSketches().
Can somebody have a look at this?

**Comment by mitag** [comment]
I made the same experiences with the IDE 1.8.8 under Windows 10. The last sketch, window position and size are no longer saved. Since I have a copy of the IDE 1.8.7 on my local server, I installed the older version again and everything is fine again.

**Comment by facchinm** [comment]
Hi @vimes666 ,
thanks for reporting. That change should leave everything unchanged since `handleQuit` already handles saving the sketch position (https://github.com/arduino/Arduino/blob/4b6b8f0c52402a6b55efdcd3cd26ea8c1c14bd59/app/src/processing/app/Base.java#L954-L959).
I'll take a closer look and get back to you.

**Comment by facchinm** [comment]
The breaking change is https://github.com/arduino/Arduino/commit/36da22c08646d8ac62245ac0b2c05bb8e009ca06 (and is only triggered when closing the IDE with the `x` and not via File/Quit). 
I'll prepare a patch immediately.

**Comment by facchinm** [comment]
I opened https://github.com/arduino/Arduino/pull/8349 to fix this; as soon as the builds are available I'd ask you to try it and report if the fix is ok.

**Comment by vimes666** [comment]
Thanks for the swift response!
I tested http://downloads.arduino.cc/javaide/pull_requests/arduino-PR-8349-BUILD-817-linux64.tar.xz just now and the problem seems to be solved :)
As for windows, I dont know, my latest working version is 98. Someone else will have to test that.
