### ISSUE TITLE
Background process "serial-discovery" runs at a continuous 100% CPU

### ISSUE THREAD

**Issue by tormodhau** [arduino/Arduino#8340]
When launching the **Arduino 1.9.0-beta** IDE build on **MacOS Mojave 10.14.1**, the background process "**serial-discovery**" is lunched by the IDE. **This process has a CPU usage of 90-100 %** - it takes up a whole CPU core until forcefully stopped. Force quitting the process does not seem to affect the behaviour of the Arduino IDE.

### Output from Activity Monitor:

<img width="778" alt="screenshot 2018-12-28 at 23 14 59" src="https://user-images.githubusercontent.com/4433808/50529795-e1065800-0af7-11e9-9bcc-a8e489c8f049.png">

**Comment by facchinm** [comment]
@tormodhau thanks for sharing this. `serial-discovery` is the new pluggable discoverer with we merged in beta to spot exactly this kind of bugs.
Can you share your configuration? How many serial ports are listed by the IDE in both the menus? Thanks a lot!
