### ISSUE TITLE
[Library Manager] Please add library TinyUPnP to the Arduino Library Manager

### ISSUE THREAD

**Issue by ofekp** [arduino/Arduino#8342]
Can you please add the library TinyUPnP to the Arduino Library Manager?
Repo: https://github.com/ofekp/TinyUPnP
Tag: https://github.com/ofekp/TinyUPnP/tree/v2.0.0

Thanks!

**Comment by cmaglie** [comment]
Done!

**Comment by ofekp** [comment]
Thank you so much!
