### ISSUE TITLE
Local offline reference uses online .js and .css files

### ISSUE THREAD

**Issue by bruvi** [arduino/Arduino#8346]
Local reference is nearly unusable with poor internet connectivity because every page has references to many external javascript libraries and stylesheets (and even makes calls to stripe.com pages)
When there is **no internet** connection, pages show up quickly and nicely even without the missing files.
When wifi signal is **poor**, calls to external files block page loading until the answer (or a timeout).
This week-end I had DNS problems ("temporary resolution failure" after 60 seconds) and each local page was taking 5-10 minutes to show up.
This is with IDE verision 1.8.[589] 
With version 1.0.5 (which is stlll the official Debian version !) everything is fine, no external file needed.

I think there should be local copies of the needed .js and .css files, or the lines loading these files coud be stripped out since pages look OK when there is no connection.

May be the same problem than issue #5787

**Comment by per1234** [comment]
Closing as no longer relevant due to https://github.com/arduino/Arduino/pull/11495
