### ISSUE TITLE
[Library Manager] Add AsyncLiquidCrystal library

### ISSUE THREAD

**Issue by paulo-raca** [arduino/Arduino#8350]
Hello,

I've create a non-blocking version of the LiquidCrystal library, which allows my code to remain responsive while it data is slowly transferred to the LCD: https://github.com/paulo-raca/Arduino_AsyncLiquidCrystal

Could you add this to a list of libraries?

Thank you.

**Comment by cmaglie** [comment]
done!

**Comment by paulo-raca** [comment]
Thank you
