### ISSUE TITLE
[Library manager] change library name #8322

### ISSUE THREAD

**Issue by fabiuz7** [arduino/Arduino#8359]
Hi,
few days ago i've created [this](https://github.com/fabiuz7/dimmable_light_esp8266_lib) library to control dimmers. It was only for esp8266, but now I've added ESP32 and AVR support, so it should be better to change the name in **Dimmable Light or Arduino**  to empathize the fact that it works for arduino IDE, supporting different platforms (modification already done in library.properties). 

Is it possible? Should I do any other modifications?

If possible, I would update the url of the library accordingly to the new library's name e.g. https://github.com/fabiuz7/dimmable_light_arduino_lib

**Comment by per1234** [comment]
Someone will make the requested name change on the next pass through the Library Manager requests.

You can change the URL also if you like. If you change the repository name in the Settings tab, GitHub will automatically redirect from the old URL, but Arduino should also probably update the URL in their Library Manager list.

**Comment by cmaglie** [comment]
Library renamed, if you want you can rename the repository too (from the github's setting page) and tell us the new URL so I can update it in the library manger.

**Comment by fabiuz7** [comment]
Thank you, the new library's URL is https://github.com/fabiuz7/Dimmable-Light-Arduino (library.properties already updated)

**Comment by fabiuz7** [comment]
Just another question/request: will you remove the old library name? I'm asking because now, if I in Arduino Library Manager, I see this:
<img width="592" alt="screenshot 2019-01-12 15 47 37" src="https://user-images.githubusercontent.com/7937648/51074606-791c4980-1681-11e9-8e71-2ada6ef7cd12.png">

That is the new and ald version, this could create confusion...

**Comment by cmaglie** [comment]
It should be ok now.
