### ISSUE TITLE
Update miniDAC library

### ISSUE THREAD

**Issue by SandeepanSengupta** [arduino/Arduino#8363]
@per1234, @cmaglie 
Please find [this](https://github.com/SandeepanSengupta/miniDAC-library/releases/tag/1.0.0) **_new_ release tag** and update it to library manager.<br/>It is for version 1.0.0.<br/>
Please find the original thread at #7063

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So you don't need to make a request every time you release a new version; they'll be picked up automatically. In fact, your 1.0.0 already has!

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by SandeepanSengupta** [comment]
Woh! That's great !!!
Thanks for letting me know @per1234
