### ISSUE TITLE
IDE Open bug ( opens multiple instances ) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#837]
This is [Issue 837](http://code.google.com/p/arduino/issues/detail?id=837) moved from a Google Code project.
Added by 2012-03-01T00:59:05.000Z by [Andrews...@gmail.com](http://code.google.com/u/105266465420001203338/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

1. Start with no IDE instances open.
2. Open IDE from start menu or short cut ( not .ino or .pde ), so it opens an empty new sketch.
3. Use the GUI button 'Open' to select one of the recently used sketches.
 At this point only one instance is running with the selected sketch open.
4. Find a .ino file anywhere on your computer, click to open it.
Now you have two copies of the first sketch open and one newly opened sketch.

**What is the expected output? What do you see instead?**
Opens two IDE instances, one of an already loaded sketch and one of the newly 'opened' sketch

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
IDE: 1.0
BOARDS: UNO, Mega
OS: Windows 7, but verified bug on Windows XP SP3

http://arduino.cc/forum/index.php/topic,92376.0.html

**Comment by ffissore** [comment]
Fixed. Now "open" always open a new window. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
