### ISSUE TITLE
My new release doesn't show library manager

### ISSUE THREAD

**Issue by selengalp** [arduino/Arduino#8372]
Hi,
My last release v1.3 on this doesn't show in Arduino library manager. I tried to delete and release again but it didn't work. Is there any solution for me?

**Comment by per1234** [comment]
The reason for this is that you didn't change the `version` value in library.properties until after the release. At the time of the release it was still `1.2`:
https://github.com/sixfab/Sixfab_Arduino_CellularIoT_App_Shield/blob/v1.3/library.properties#L2

You'll need to either create a new release, after updating `version`, or else redo the v1.3 tag.

**Comment by selengalp** [comment]
Thanks for your prompt answer.
