### ISSUE TITLE
[Library Manager]Please add the Dabble Library

### ISSUE THREAD

**Issue by mimansamaheshwari** [arduino/Arduino#8377]
Please add the Dabble Library to Library Manager - https://github.com/STEMpedia/Dabble
Tag - https://github.com/STEMpedia/Dabble/tags

**Comment by per1234** [comment]
@mimansamaheshwari did you close this issue because you no longer wish to have your library added to the Arduino Library Manager index?

**Comment by mimansamaheshwari** [comment]
Yes there are some edits in library that are suppose to be done before
publishing
it on Library Manager. Should I create the new issue or reopen the same?

**Comment by per1234** [comment]
OK, that's fine. I just wanted to make sure it hadn't been done in error. Sometimes people think that just because I added the label, it means the library was already in the index, but that is done by another member of the Arduino team.

When you're ready, you can just reopen this issue.

**Comment by mimansamaheshwari** [comment]
Ok thanks a lot for cooperation.

**Comment by mimansamaheshwari** [comment]
Please publish this library to Arduino Library manager - https://github.com/STEMpedia/Dabble
Tag - https://github.com/STEMpedia/Dabble/tags

**Comment by cmaglie** [comment]
done!
