### ISSUE TITLE
Wrong type conversion in W5100 recv_data_processing and read_data [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#838]
This is [Issue 838](http://code.google.com/p/arduino/issues/detail?id=838) moved from a Google Code project.
Added by 2012-03-01T17:37:17.000Z by [ptsne...@gmail.com](http://code.google.com/u/105599444741483035179/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

I would like to point out some dangerous or at least bad code in the methods void W5100Class::read_data and void W5100Class::recv_data_processing.

The first problem is in read_data with the volatile keywords which don't make any sense since none of the methods are executed inside interrupts.

The second problem that exists regards the use of an internal W5100 memory address as an AVR one, casting the correct uint16_t value returned by readSnRX_RD(s) into a uint8_t*. This code does not fail because coincidentally uint8_t* are 16 bit addresses but the same cannot be guaranteed for other architectures besides AVR (Leonardo?). After that casting is passed to W5100Class::read_data it is again converted to uint16_t. After that a series of (uint8_t) casts are made for no usefull reason.

That is it. If in any of my reasoning there is any need for clarification i will provide it.

Thanks
Paulo Neves

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#20
