### ISSUE TITLE
[Library Manager] Please add new library

### ISSUE THREAD

**Issue by GordonRudman** [arduino/Arduino#8380]
https://github.com/GordonRudman/ExampleArduinoLibrary

Please add the following to the library list: 
https://dev.azure.com/gordonrudman-opensource/ExampleArduinoLibrary/_git/ExampleArduinoLibrary

Thanks

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by GordonRudman** [comment]
Thanks. 
Sorry I missed that.
I've added the tag (0.0.1) now.

**Comment by cmaglie** [comment]
@GordonRudman we only support repositories on github, bitbucket or gitlab, you must move the library to one of those services...

**Comment by GordonRudman** [comment]
OK, no problem. I've changed the repo to:
https://github.com/GordonRudman/ExampleArduinoLibrary.git 

I would suggest that you start looking into supporting Microsoft Azure DevOps git repos too, as they are major/stable git repos (and offer developers many more tools). Microsoft actually even owns GitHub at this point.

PS: Thanks for the quick responses.

**Comment by GordonRudman** [comment]
Hi @per1234 @cmaglie , 

I've noticed that this library isn't available through the Arduino Library Manager yet.
So, I was just wondering if there is anything else I need to do to?

Thanks,
Gordon

**Comment by per1234** [comment]
You've now done everything required on your end. Now you only must wait.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by GordonRudman** [comment]
Great. Thanks.
Sorry for all the questions, this is just the first time I'm trying to create a public library.
I appreciate all the help.

**Comment by cmaglie** [comment]
Done
