### ISSUE TITLE
Please add a new library for the MCP7940M / MCP7940N Real-Time clocks

### ISSUE THREAD

**Issue by SV-Zanshin** [arduino/Arduino#8382]
Arduino Library to access the MCP7940M or MCP7940N Real-Time chips

The library is located at https://github.com/SV-Zanshin/MCP7940 

The library documentation / WIKI is located at https://github.com/SV-Zanshin/MCP7940/wiki

Many thanks in advance,

-Arnd.

**Comment by cmaglie** [comment]
done
