### ISSUE TITLE
Please add the new library TalkingLED, LED blinking made easy.

### ISSUE THREAD

**Issue by fabriziop** [arduino/Arduino#8384]
The library is located at https://github.com/fabriziop/TalkingLED

Many thanks,

Fabrizio

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by fabriziop** [comment]
I have just pushed tag 0.1.0. Sorry for the inconvenience.

Fabrizio

**Comment by cmaglie** [comment]
done
