### ISSUE TITLE
TSic code enhancement for supporting better accuracy of temperature sensor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#839]
This is [Issue 839](http://code.google.com/p/arduino/issues/detail?id=839) moved from a Google Code project.
Added by 2012-03-02T00:12:07.000Z by [dvt....@gmail.com](http://code.google.com/u/107615003944773251440/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

I made some minor changes for the TSic files (tsic.h and tsic.cpp) in order to support Arduino v. 1.0 and to have a 2 digit precision float numer given back by the main routine used to collect the temperature value from the tsic device.

1.)#inlude "WProgram.h" is changed to #inlude "Arduino.h" in both, tsic.h and tsic.cpp, to get compatibility with Ardunino v. 1.0
I don't know, if this has some incompatibilities issues with earlier versions of Arduino Software (<1.0).

2.) In the original library, only a int could be changed by reference as a read out, now a float is changed by reference

tsic has accuracy of up to 0.1 °C, tehrefore a float gives more precision then an int.

**Comment by per1234** [comment]
TSic is not an official Arduino library and thus this issue is not relevant to this repository.
