### ISSUE TITLE
ctags component needs updating to 64 bit for MacOS

### ISSUE THREAD

**Issue by dap35** [arduino/Arduino#8397]
Arduino v1.8.8:
This is listed under legacy 32bit code in MacOS.  This needs to get updated prior to MacOS v10.15, which reportedly removes support for 32bit legacy mode.

ctags:

  Last Used:	2018-12-22 10:43:17
  Path:	/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags
  Parent Process:	/Applications/Arduino.app/Contents/MacOS/Arduino

**Comment by SConaway** [comment]
Where is that coming from?

**Comment by dap35** [comment]
<img width="380" alt="screen shot 2019-02-26 at 10 49 34 am" src="https://user-images.githubusercontent.com/19751814/53426052-41106200-39b4-11e9-9150-5bda7ad36738.png">

In MacOS, go to the System Information tool, > Software > Legacy Software.

**Comment by SConaway** [comment]
Yes. Why is this in the app?

**Comment by dap35** [comment]
I have no clue as to why it is there.  I simply installed the application and wanted to report this so that it can be dealt with proactively.

**Comment by facchinm** [comment]
`ctags` is being used for prototype generation. It is going to be replaced by `arduino-preprocessor` in the near future, so I'd avoid recompiling it now

**Comment by Mike4U** [comment]
I'm getting warnings about other processes on MacOS 10.14.3 (18D109) in Arduino 1.8.8:
![Screen Shot 2019-03-14 at 1 59 49 PM](https://user-images.githubusercontent.com/9957897/54391304-aa090280-4661-11e9-955d-c1a9e78194bc.png)

These are all in: /Applications/Arduino.app/Contents/Java/hardware/tools/avr/

**Comment by ttimpe** [comment]
This needs fixing ASAP as the developer preview of macOS Catalina(10.15) now doesn't run any 32-bit binaries anymore.

**Comment by SConaway** [comment]
What's going on here? Arduino's the only thing keeping me on Mojave.

@facchinm @per1234

**Comment by ttimpe** [comment]
This seriously needs to be addressed very soon. It should just be a small recompile, many (if not all) tools already compile just fine.

**Comment by SConaway** [comment]
It seems to build just fine on my Mac.

**Comment by facchinm** [comment]
Everything was rebuilt to 64 bit and the resulting IDE build is here https://github.com/arduino/Arduino/pull/8976 .
Can you test it and report if everything is working fine?

**Comment by SConaway** [comment]
Unfortunately, I'm not home for the rest of the week, but as soon as I return, I'll test.

**Comment by Mike4U** [comment]
Used the link on 10.14.5 and got these 32bit.  Strangely worse than Arduino 1.8.7 which only had ctags
![Screen Shot 2019-06-25 at 9 53 54 AM](https://user-images.githubusercontent.com/9957897/60117869-ddaefa80-972f-11e9-9c14-e44fae78558c.png)

**Comment by facchinm** [comment]
@Mike4U pretty sure you are not looking at build #8976 since it ships with avr-gcc 7.3.0 and your screenshot shows 5.4.0 :wink:

**Comment by Mike4U** [comment]
@facchinm  Not sure what the About this Mac/System report above is actually doing.  If I click on the 'Applications' on the left Arduino will show up as 64 bit.  The 'Activity Monitor' application also shows it as 64 bit when it's running.  The 'Legacy Software' clicked above shows the same application (at the same location) with 32bit components inside it.

This isn't causing me any problems AFAIK, just posted for your info.

**Comment by Mike4U** [comment]
@facchinm I have older Arduino1.6.6 and 1.8.9 in a folder with-in the Applications folder.  The 8976-BUILD-869 does indeed have the air-gcc 7.3.0, not 5.4.0 as you indicated.  However the 'About this Mac->System report->Legacy Software, incorrectly shows the 1.8.9 version in the Application folder not Application/old version/ where it is.  Perhaps it's not updating from the menu.  I'll try a restart.

**Comment by Mike4U** [comment]
Restart didn't help.  I give up on debugging Apples App.  Arduino is fine.

**Comment by SConaway** [comment]
The menu doesn't update unless the offending files are removed. (I think)

**Comment by sandeepmistry** [comment]
@facchinm I think `ctags` is still 32-bit in the latest IDE download for macOS.

**Comment by facchinm** [comment]
I just downloaded 1.8.10 and can confirm it's 64 bit :wink: 
```
$ file ctags 
ctags: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Comment by sandeepmistry** [comment]
Strange, the UI shows this:

<img width="1258" alt="Screen Shot 2019-09-17 at 9 17 54 AM" src="https://user-images.githubusercontent.com/1163840/65045165-51763300-d92c-11e9-8f66-7dd3dfa640b5.png">

... but let's trust the terminal :)
