### ISSUE TITLE
[Library Manager] Please add new library

### ISSUE THREAD

**Issue by Heltec-Aaron-Lee** [arduino/Arduino#8401]
Please add the following to the library list:
https://github.com/HelTecAutomation/Heltec_ESP32

Thanks.

Aaron Lee

**Comment by Heltec-Aaron-Lee** [comment]
@per1234 Thanks for your add.

But I still can't find my library in Arduino Library manager, what can I do now?
![default](https://user-images.githubusercontent.com/32860565/51436596-fb80bb00-1cca-11e9-8570-6bff72bf84a7.png)

**Comment by per1234** [comment]
I only labeled the issue to make it easy to find in the issue tracker. Someone else is in charge of adding it to the Library Manager. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by Heltec-Aaron-Lee** [comment]
@per1234 Thank you very for your detail reply. Have a good day.

**Comment by cmaglie** [comment]
done
