### ISSUE TITLE
New Arduino Library for the LMP91000 Chemical Sensor

### ISSUE THREAD

**Issue by hoilett** [arduino/Arduino#8407]
Hi,

The library is located here: https://github.com/LinnesLab/LMP91000

I created a library for the LMP91000, a popular gas and chemical sensor that can be used to analyze glucose, potassium and other chemicals in the same way commercial glucometers work. The library contains all the necessary functions for users to get started with the device and provides relevant example code for different electrochemical sensing needs. A few users have asked about such a library in the Arduino Forum.
<https://forum.arduino.cc/index.php?topic=534773.0>
<https://forum.arduino.cc/index.php?topic=315462.0>

The LMP91000 has been used for some academic publications like "A low-cost miniaturized potentiostat for point-of-care diagnosis" by Andres Felipe DiazCruz et al. in 2014. The LMP91000 will be used in a future publication of mine as well.

The library is located here: https://github.com/LinnesLab/LMP91000.git

**Comment by cmaglie** [comment]
done
