### ISSUE TITLE
New Library: TeXie_arduino

### ISSUE THREAD

**Issue by texie** [arduino/Arduino#8411]
Hi arduino-Team,

could you please add our Lib to the LibraryManager?
https://github.com/texie/TeXie_arduino

Have a nice day!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by texie** [comment]
Oh, i missed that step. It should be fine now:
https://github.com/texie/TeXie_arduino/releases/tag/0.0.1

**Comment by cmaglie** [comment]
done
