### ISSUE TITLE
Redundant save prompt on close

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#8413]
Using Arduino IDE 1.9.0 Beta Build and Arduino IDE 1.8.9 Hourly Build 2019-01-19 11:37, Windows 10 64 bit and Linux ARM

1. Start the Arduino IDE
2. Modify the sketch.
3. Close the window. The issue does not occur if this is done via File > Quit. This must be the last IDE window open.
4. From the save prompt, click "No". The expected behavior is that the window will close but what happens instead is you get another save prompt.

The issue does not occur with Arduino IDE 1.8.8.

**Comment by facchinm** [comment]
This is the problematic commit https://github.com/arduino/Arduino/commit/2efd090e81f2b8225189d31d2b97d7265891c82a.
