### ISSUE TITLE
Contextual menu

### ISSUE THREAD

**Issue by mbm60** [arduino/Arduino#8423]
Please add copy/paste contextual menu for serial monitor's input text fields and also for library manager's searching text field. thanks...

**Comment by facchinm** [comment]
Should be straightforward when applying this https://github.com/arduino/Arduino/commit/1f9d99b699bf9330cc92d93beb1e11ddba468d17 patch to the right places :slightly_smiling_face: 
PS: PRs are accepted :wink:
