### ISSUE TITLE
CTRL-SHIFT-HOME/END not doing what I expect it to do [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#843]
This is [Issue 843](http://code.google.com/p/arduino/issues/detail?id=843) moved from a Google Code project.
Added by 2012-03-04T03:42:28.000Z by [frank.zhao.main@gmail.com](http://code.google.com/u/frank.zhao.main@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. hold down CTRL and SHIFT
2. press home or end
**3.**

**What is the expected output? What do you see instead?**

I expect to see everything selected from the current point, to the end, or the beginning of the file

Instead, it only seem to select to the end or beginning of the current line

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0 on Win7 Pro 64bit

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Fixed (at least) in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
