### ISSUE TITLE
Library manager not showing latest library.properties

### ISSUE THREAD

**Issue by nseidle** [arduino/Arduino#8435]
[This library](https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library) is displaying oddly in lib manager.

![image](https://user-images.githubusercontent.com/117102/51714224-d1dcd200-1ff1-11e9-94c9-73335113ddf4.png)

Library name and library description are wrong. Link is correct. Version drop down is not showing a few of the latest additions

I changed the library.properties version before doing a release. And I don't see any [symlinks in the repo](https://github.com/arduino/Arduino/issues/8061) that would cause it not to be picked up.

Library: https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library

Original request for inclusion: https://github.com/arduino/Arduino/issues/6225

I suspect I'm doing something wrong with our repo but I can't spot it. Sorry to bother.

**Comment by facchinm** [comment]
Hi @nseidle ,
the library engine was looking for the original name of the library (SparkFun CCS811 Breakout). I changed it to the new name and newer versions should be available soon!

**Comment by nseidle** [comment]
Fixed! Thank you!
