### ISSUE TITLE
Please add a new library for the DS1631 I2C Temperature sensor

### ISSUE THREAD

**Issue by SV-Zanshin** [arduino/Arduino#8446]
The library is located at https://github.com/SV-Zanshin/DS1631 

The description is as follows:

# DS1631 Library [![Build Status](https://travis-ci.org/SV-Zanshin/DS1631.svg?branch=master)](https://travis-ci.org/SV-Zanshin/DS1631) [![DOI](https://www.zenodo.org/badge/100991559.svg)](https://www.zenodo.org/badge/latestdoi/100991559)
<img src="https://github.com/SV-Zanshin/DS1631/blob/master/Images/DS1631.png" width="175" align="right"/> *Arduino* library for accessing the [DS1631](https://www.maximintegrated.com/en/products/analog/sensors-and-sensor-interface/DS1631.html), a thermometer with a precision up to 12 bits (0.0625°C) that uses I2C communications. The DS1361A variant differs only in that it starts continuous measurements on power-up or reset while the DS1631 and DS1731 start up in single-shot mode. The DS1631 comes in a small 8-Pin µSOP or SO package and is 3V and 5V tolerant and allows up to 8 devices to be placed on the same I2C bus. The [DS1631 datasheet](https://datasheets.maximintegrated.com/en/ds/DS1631-DS1731.pdf) describes the chip in detail.

## Description
See the individual components of the library on the wiki pages

**Comment by cmaglie** [comment]
done
