### ISSUE TITLE
Please add the new lib ModbusConfig

### ISSUE THREAD

**Issue by Warlib1975** [arduino/Arduino#8449]
Library located at https://github.com/Warlib1975/ModbusConfig

ModbusConfig library for ESP8266/ESP32/Arduino.
The library process a Modbus configuration file in JSON format.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Warlib1975** [comment]
> You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
> 
> After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.
> 
> For more information see:
> https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Done. :-)

**Comment by cmaglie** [comment]
done
