### ISSUE TITLE
Compile every time of an upload, even if no changes where made [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#845]
This is [Issue 845](http://code.google.com/p/arduino/issues/detail?id=845) moved from a Google Code project.
Added by 2012-03-05T12:17:26.000Z by [Wilfried...@gmail.com](http://code.google.com/u/104914328976362983260/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. upload or compile the sketch, the sketch will compile. OK
2. upload the sketch (again), the sketch will compile again. NOT OK.

**What is the expected output? What do you see instead?**
Only compile the sktech if changes are present.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0, board independent

**Comment by ffissore** [comment]
IDE recycles (doesn't compile) most of the files if code/options haven't changed
