### ISSUE TITLE
Library Manager question - update to new version

### ISSUE THREAD

**Issue by SV-Zanshin** [arduino/Arduino#8450]
According to the library manager, the most recent version of the https://github.com/SV-Zanshin/MCP7940 library is version 1.1.1, but the github repository has had version 1.15 since 7 days.

The "library.properties" file in GitHub for this library also refers to version 1.1.5, so I am unsure of what could be causing this problem.

Does something need to be done or changed in GitHub for the newest version of this library to be picked up the library manager?

**Comment by per1234** [comment]
The problem is that you changed the `version` value in library.properties **after** making the 1.1.5 release. At the time of the 1.1.5 release, the `version` field was still set to 1.1.1:
https://github.com/SV-Zanshin/MCP7940/blob/v1.1.5/library.properties#L2
