### ISSUE TITLE
Please add new library "Redis for Arduino"

### ISSUE THREAD

**Issue by rpj** [arduino/Arduino#8455]
This issue is to request the addition of the "Redis for Arduino" library to the Library Manager.

The overall repository URL for this library is: https://github.com/electric-sheep-co/arduino-redis

Version 2.0 (based on an earlier implementation of Redis for ESP8266 platforms) is available at this tag: https://github.com/electric-sheep-co/arduino-redis/releases/tag/2.0.3

Thank you!

**Comment by cmaglie** [comment]
done
