### ISSUE TITLE
[Library Manager] Request to add Xbox 360 Controller LEDs Library 

### ISSUE THREAD

**Issue by dmadison** [arduino/Arduino#8463]
Hello! Please add the [Xbox 360 Controller LEDs](https://github.com/dmadison/Xbox360ControllerLEDs) library to the libraries manager. It's a small library for generating LED patterns that mimic the Xbox 360 controller's LEDs. Thank you!

URL: https://github.com/dmadison/Xbox360ControllerLEDs

**Comment by cmaglie** [comment]
done!

**Comment by dmadison** [comment]
Thank you!
