### ISSUE TITLE
[Library Manager] Updating Antares ESP8266 in Library Manager

### ISSUE THREAD

**Issue by vmasdani** [arduino/Arduino#8464]
Greetings.
I have read the manual on how to update a library which is deployed on Arduino's Library Manager. It's stated that I need to push a new tag and also change the `library.properties` file and the auto indexer will check for new release every few hours. But it's been a day and the library is still stuck on 1.1.0 in the Library Manager, while it's supposed to be 1.1.2. 
[This](https://github.com/antaresdocumentation/antares-esp8266-http) is the library's link. Did I do something wrong?

**Comment by cmaglie** [comment]
No you did everything right, you just need to wait, the indexer will check for new releases every hour (it may take a bit more due to caching).
