### ISSUE TITLE
Please add my libraries to the Library Manager

### ISSUE THREAD

**Issue by bitbank2** [arduino/Arduino#8469]
2 libraries to add:

https://github.com/bitbank2/Multi_BitBang
https://github.com/bitbank2/Multi_OLED

**Comment by bitbank2** [comment]
Released both - thanks for the tip

**Comment by bitbank2** [comment]
Anything else needed to get it added?

**Comment by per1234** [comment]
Everything looks good. Now you only need to wait.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that.

**Comment by cmaglie** [comment]
done!
