### ISSUE TITLE
[Library Manager] Add Antares ESP8266 MQTT to Library manager

### ISSUE THREAD

**Issue by antaresdocumentation** [arduino/Arduino#8472]
Please add [Antares ESP8266 MQTT](https://github.com/antaresdocumentation/antares-esp8266-mqtt) to the library manager.
This is actually a migration from [here](https://github.com/vmasdani/antares-esp8266-mqtt). I have removed the tag there, so there wouldn't be duplicate libraries.

**Comment by cmaglie** [comment]
Done, I've removed the old repo too.
