### ISSUE TITLE
"Show timestamp" not in sync

### ISSUE THREAD

**Issue by marcteys** [arduino/Arduino#8477]
I am experiencing a weird issuem I don't know if the  error comes from show timestamp or the Arduino board (Arduino Uno).

When I am running this code, I am expecting to see the interval of time in ms being the same between the interval and  the timestamp. But i's not the case, I have about 35ms delay from time to  time.

```c
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
}

unsigned long lastFiredTime;

void loop() {
  // put your main code here, to run repeatedly:
  unsigned long now = millis ();
  unsigned long interval = now - lastFiredTime;
  lastFiredTime = now;

  Serial.print(now);
  Serial.print("\t");
  Serial.println(interval);
  delay(1);
}
```

Result:
```....
15:48:33.483 -> 3429	8
15:48:33.483 -> 3437	8
15:48:33.483 -> 3445	8
15:48:33.524 -> 3453	8 <----  | 8 ms but timestamp shows 40ms
15:48:33.524 -> 3463	10
15:48:33.524 -> 3472	9
15:48:33.524 -> 3480	8  
15:48:33.559 -> 3488	8  <----  | 8 ms but timestamp shows 35ms
15:48:33.559 -> 3496	8
...
```

Arduino IDE 1.8.8 on Win 10, Testes with board Arduino Nano, Uno and Node MCU

**Comment by facchinm** [comment]
Hi @marcteys, the timestamp shows the time at which the USB packet is received by the PC; since there is some buffering involved between the serial port and the serial-to-usb device it should not be taken into account if you want super precise timings.
