### ISSUE TITLE
[Library Manager] Library add request

### ISSUE THREAD

**Issue by akkoyun** [arduino/Arduino#8489]
NEW REPO: https://github.com/akkoyun/Environment

tPlease add my library to the manager

https://github.com/Noxcorp/Nox_Environment

**Comment by cmaglie** [comment]
Done!

**Comment by akkoyun** [comment]
Hi,
My library name and repo changed. Can you fix this?

New Repo: https://github.com/akkoyun/Environment

**Comment by akkoyun** [comment]
Someone can help this subject? :)

**Comment by per1234** [comment]
@akkoyun cmaglie periodically goes through all the outstanding Library Manager requests and closes them at that time. Your request will be handled on the next run and you will get a notification from GitHub at that time. So there is nothing more you need to do, other than be patient.

**Comment by cmaglie** [comment]
Done
