### ISSUE TITLE
[Library Manager] Add WiFiSpi library

### ISSUE THREAD

**Issue by JiriBilek** [arduino/Arduino#8493]
https://github.com/JiriBilek/WiFiSpi

Following info in http://forum.arduino.cc/index.php?topic=524853.msg4045180#msg4045180 I found there is a chance to add my library to Library Manager. 
The library is used for wifi communication between Arduino and ESP8266 and uses SPI bus which is more robust than often used serial.
The url is: 
https://github.com/JiriBilek/WiFiSpi
Thanks.

**Comment by cmaglie** [comment]
Done
