### ISSUE TITLE
Uploading code to the Arduino Nano

### ISSUE THREAD

**Issue by isaaclittle** [arduino/Arduino#8512]
I'm recently new to the community and so far love the Arduino and it's versatility! Have used different microcontrollers at uni and none of them are as easy to use as the Arduino. However, recently I've had some issues with uploading to my Arduino Nano. To begin with it was fine, I could write code to it on any PC I used but the other day I went to upload the latest version of my code to it and it just wouldn't work. I tried a different Nano, same issue. I tried an Uno, just out of curiosity and it worked fine. So I took my Nano to uni to try on their computers and it worked first time. 
I've noticed it that the uni is running version 1.8.5 of the IDE so I downloaded that at home I tried using that and haven't had any issue since.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
