### ISSUE TITLE
openjdk update for windows

### ISSUE THREAD

**Issue by chris3081** [arduino/Arduino#8516]
Hi Guys, any chance you could release a maintenance release for Arduino on the windows store its coming up in my AV vulnerability scans https://threats.kaspersky.com/en/vulnerability/KLA11122/?utm_source=KTS_19.0.0&utm_medium=inp&utm_campaign=en

**Comment by facchinm** [comment]
Hi @chris3081 ,
from the page you linked it looks like the vulnerability should only affect 
`Java SE 8 versions earlier than 8u151`.
Latest IDE (also on Windows store) ships with JRE 8u191; which version are you running?

**Comment by chris3081** [comment]
Post reinstall of the IDE and a clean up across the program files in each of the drive on my machine has shown it was my machine at fault. Sorry for the false alarm it was an old install and being later in the evening time I misread the drive letter.
