### ISSUE TITLE
[Library Manager] Request to add HID Buttons library

### ISSUE THREAD

**Issue by dmadison** [arduino/Arduino#8519]
Hello! Please add the [HID Buttons](https://github.com/dmadison/HID_Buttons) library to the libraries manager. It's a small library that makes it easier to use HID buttons when emulating a USB Keyboard, Mouse, or Joystick.

Thank you!

URL: https://github.com/dmadison/HID_Buttons

**Comment by cmaglie** [comment]
Done

**Comment by dmadison** [comment]
Thank you!
