### ISSUE TITLE
[Library Manager] Request to add BIP66 library

### ISSUE THREAD

**Issue by sleepdefic1t** [arduino/Arduino#8520]
Please add BIP66 to the Library Manager.

### BIP66
> ANS.1 DER Encoder/Decoder based on Bitcoin BIP66.

https://github.com/sleepdefic1t/BIP66
(latest release: https://github.com/sleepdefic1t/BIP66/releases/tag/0.2.0)

Thank you!!

**Comment by cmaglie** [comment]
done!
