### ISSUE TITLE
[Library Manager] Library add request FabGL - VGA, VT100/Ansi Terminal and PS/2 controller

### ISSUE THREAD

**Issue by fdivitto** [arduino/Arduino#8522]
VGA Controller, PS/2 Keyboard Controller, Graphics Library, Game Engine and ANSI/VT Terminal for the ESP32

Please add https://github.com/fdivitto/FabGL
(current release https://github.com/fdivitto/FabGL/releases/tag/v0.0.1 )

**Comment by cmaglie** [comment]
done!
