### ISSUE TITLE
Arduino 1.8.8 crashes when trying to open it on MacOS Mojave 10.14.3.

### ISSUE THREAD

**Issue by HunterRB** [arduino/Arduino#8533]
Arduino 1.8.8 downloaded no problem and worked the first few times then randomly started crashing when I try to open it. It will load all the way till it says "starting" then just stops. I've tried deleting it and redownloading it and also tried multiple older versions and nothing has work. Anyones help would be greatly appreciated. Thank you.

**Comment by facchinm** [comment]
Hi @HunterRB ,
can you try launching it from a Terminal as `Arduino.app/Contents/MacOS/Arduino` and paste here the console logs? Thanks

**Comment by gvarisco** [comment]
Should be _`/Applications/Arduino.app/Contents/MacOS/Arduino`_ in case you have troubles finding the folder.

**Comment by HunterRB** [comment]
Pretty new to all this and am wondering what you mean by a Terminal and console logs

**Comment by HunterRB** [comment]
Figured out and this error appeared. open -a /applications/Arduino.app/Contents/MacOS/Arduino
FSPathMakeRef(/applications/Arduino.app/Contents/MacOS/Arduino) failed with error -43.

**Comment by HunterRB** [comment]
Tried it again and it says "no such file or directory"

**Comment by HunterRB** [comment]
Tried redownloading it randomly and works fine they must've fixed the issue
