### ISSUE TITLE
Add "IKB1_Arduino" library to Library manager Arduino IDE

### ISSUE THREAD

**Issue by jcubuntu** [arduino/Arduino#8539]
Lib For IKB-1 Board 
github : https://github.com/jcubuntu/IKB1_Arduino
Thankyou

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jcubuntu** [comment]
Thank you for suggestion. I already create release and it's matches the version value in library.properties

**Comment by cmaglie** [comment]
Done
