### ISSUE TITLE
[Library manager] Please add sqlite3

### ISSUE THREAD

**Issue by tobozo** [arduino/Arduino#8541]
Hello,

can you please add this project to the library manager:

https://github.com/siara-cc/esp32_arduino_sqlite3_lib

thanks ^_^

**Comment by cmaglie** [comment]
Done

**Comment by siara-cc** [comment]
@cmaglie Hi, Thank you for adding our library.  It seems it has taken the very first release for Zip download.. Is it possible to add the latest release? https://github.com/siara-cc/esp32_arduino_sqlite3_lib/releases/tag/v1.2

![lib_mgr_ss](https://user-images.githubusercontent.com/12986780/53634769-1129be80-3c41-11e9-8875-737487009023.png)

**Comment by tobozo** [comment]
@siara-cc the Arduino Library Manager only trusts the version in your own [library.properties](https://github.com/siara-cc/esp32_arduino_sqlite3_lib/blob/master/library.properties#L2) file

**Comment by tobozo** [comment]
you'll need to create a new tag+release with the updated properties file, the Library Manager will detect it and send an update signal on next propagation (few hours)

**Comment by siara-cc** [comment]
@tobozo Thank you so much..  I have done that.

**Comment by per1234** [comment]
@siara-cc the `version` value of `v1.3` in your library.properties file [at your v1.3 release](https://github.com/siara-cc/esp32_arduino_sqlite3_lib/blob/v1.3/library.properties#L2) is not compliant with the library.properties specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

This will cause your v1.3 release to not be picked up by the Library Manager indexer job.

You can name your tags/releases however you like, but the `version` value in library.properties at the time of the tag must be compliant with the specification. It is the library.properties `version` value that will be used by Library Manager. The specification is a "relaxed semver" to allow compatibility with a wider range of versioning preferences, so this does permit the `1.3` style of versioning you appear to prefer. If you want a well defined versioning specification that is library.properties compliant, you can follow semver:
http://semver.org/

**Comment by siara-cc** [comment]
@per1234 Thank you for alerting me.  I have now corrected this problem.
