### ISSUE TITLE
Board Manager looks bad with dark theme

### ISSUE THREAD

**Issue by 532910** [arduino/Arduino#8546]
![image](https://user-images.githubusercontent.com/14617699/52883361-b772c000-317b-11e9-89b8-8aefc619c644.png)

Library manager looks better:
![image](https://user-images.githubusercontent.com/14617699/52883385-c8233600-317b-11e9-88e9-1595c7653532.png)

But really both should use dark background.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/8473
