### ISSUE TITLE
Please Add My Library

### ISSUE THREAD

**Issue by CodeKing09** [arduino/Arduino#8551]
https://github.com/CodeKing09/MorsePulseCK09

**Comment by CodeKing09** [comment]
**Thanks!**

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by per1234** [comment]
@CodeKing09 we're still waiting for you to create a release or tag in your repository so that it can be added to the Library Manager index.

Otherwise, if you no longer wish to add your library, please close this issue.

**Comment by per1234** [comment]
Closing due to lack of feedback. @CodeKing09 if you ever get around to making your repository compliant with the Library Manager requirements and want it added to the index, please comment here and I'll re-open.
