### ISSUE TITLE
Arduino IDE file paths are sometimes case sensitive

### ISSUE THREAD

**Issue by JohnBode** [arduino/Arduino#8552]
When attempting to install the ESP8266 SPIFFS uploader tool, I noticed that the  file path case must match exactly with what the Arduino IDE is expecting.  For Example, all characters must be lower case, expect ESP8266FS which must be upper case.  Anything else and the tool is removed.  I don’t know if this is caused byt he ESP8266 board firmware or Arduino, so I generalized as within the IDE.  I have seen on the forum where some had trouble installing tools.  There may be other situations where case sensitivity is causing problems.

**Comment by per1234** [comment]
I don't consider this a bug. It's just how things are when you're using a filename case-sensitive operating system. As long as the tool author provides clear installation instructions (which **Arduino ESP8266 filesystem uploader** does), there should be no problem. Any Arduino user who is advanced enough to need this tool should already have learned that case often matters.
