### ISSUE TITLE
mkr wifi 1010 pin layout

### ISSUE THREAD

**Issue by f0854** [arduino/Arduino#8553]
I can't find the Arduino wifi 1010 pin layout, where is it?

**Comment by per1234** [comment]
What do you mean by "pin layout"?

If you mean something that shows the mapping between the Arduino pin numbers and the pins on the SAMD21 microcontroller, there is one in the schematic on the "Documentation" tab of the product page:
https://store.arduino.cc/arduino-mkr-wifi-1010

However, I'd like to see Arduino add a "Pin Mapping" image to the product pages for the new boards, as was done for the classic Arduino boards:

---
![clipboard01](https://user-images.githubusercontent.com/8572152/52901564-1525fd00-31ba-11e9-93ef-925fbd358aa9.png)

**Comment by f0854** [comment]
for pin layout I mean the description of the pins (see attached), however on the 1010 wifi the descriptions on the pcb of the pins that are above the card and those that are below are different
!    
![immagine](https://user-images.githubusercontent.com/47694029/52901873-411c9f00-3209-11e9-85e3-52902da9768f.png)

**Comment by per1234** [comment]
On the MKR WiFi 1010, there are no descriptions of the pins on the silkscreen on the top of the board. There are descriptions printed on sides of the female headers and on silkscreen on the bottom. Please list the differences you've found between the top of the PCB and the bottom of the PCB.

**Comment by f0854** [comment]
I think there was a problem in assembling my mkr 1010, the descriptions printed on the sides of the female headers, on the left and right, of the card are "identical", so all the pins on the left are different from the silkscreen on the bottom  (see the attachments). Also there are pins numbered 1 to 7 that are? And the two connectors on the left and right side of the pcb are what? With my knowledge I can not use the card. I wonder: is it my fault if I can not find the documentation or so "open" the project is not and is deficient in the documentation?
Sorry for my late reply
![arduino mkr 1010 pin layout](https://user-images.githubusercontent.com/47694029/52911596-13d1fe80-32a6-11e9-9555-7a30454f83f2.JPG)
![mkr wifi 1010 pin 1-14](https://user-images.githubusercontent.com/47694029/52911597-17658580-32a6-11e9-879e-be35cccf9c06.JPG)
![mkr wifi 1010 pin 15-28](https://user-images.githubusercontent.com/47694029/52911598-1af90c80-32a6-11e9-89b6-fc35de454797.JPG)

**Comment by f0854** [comment]
Sorry, the first picture is wrong, this is the right one
![img_0079](https://user-images.githubusercontent.com/47694029/52911628-98248180-32a6-11e9-899e-490e1bcb18f8.JPG)

**Comment by per1234** [comment]
You're correct that your MKR WiFi 1010 was incorrectly assembled. Each female header should have different and correct markings but yours uses the same header on both sides so only one of the headers has the correct markings. If this is a significant problem for you and you purchased this from the [Arduino Store](https://store.arduino.cc/), you can [contact Store Support ](https://store.arduino.cc/store-support)to see what they can do about resolving the issue. If you purchased the board from someone else, then you would need to contact them instead.

**Comment by f0854** [comment]
thanks, I will contact Arduino's assistance ... nobody knows if there is official documentation somewhere? what do the numbers from zero to seven mean? What are the two side connectors and the SCL, SDA, MISO, SCK and MOSI pins that are? but above all, why is this documentation not on the arduino site?
