### ISSUE TITLE
[Library Manager] Request to add Ark Cpp-Client and Cpp-Crypto libraries.

### ISSUE THREAD

**Issue by sleepdefic1t** [arduino/Arduino#8554]
Please add Ark Cpp-Client and Ark Cpp-Crypto to the Library Manager.

---

### Ark-Cpp-Crypto
> A simple Cryptography Implementation in C++ for the Ark Blockchain.

https://github.com/ArkEcosystem/cpp-crypto
(latest release: https://github.com/ArkEcosystem/cpp-crypto/releases/tag/0.3.0-arduino)

---

### Ark-Cpp-Client
> A simple C++ API client for the Ark Blockchain.

https://github.com/ArkEcosystem/cpp-client
(latest release: https://github.com/ArkEcosystem/cpp-client/releases/tag/1.2.0-arduino)

---

Thank you!!

**Comment by cmaglie** [comment]
Done
