### ISSUE TITLE
How to make LED STRIP flash with music via motion sensor 

### ISSUE THREAD

**Issue by technicaLITTY** [arduino/Arduino#8560]
Hello hoping an amazing human can help me. I want to make use a MOTION SENSOR to make LED strips flash along to a song. I have this tutorial but was wondering if anyone can explain how to make add a motion sensor to activate the flashing LED STRIPS with the song?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. It is **not** appropriate to request assistance with your projects here. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post as much information as possible.
