### ISSUE TITLE
[Library manager] Please add this library

### ISSUE THREAD

**Issue by lovyan03** [arduino/Arduino#8566]
Hello,

can you please add this project to the library manager:

*M5Stack_OnScreenKeyboard
https://github.com/lovyan03/M5Stack_OnScreenKeyboard

*M5Stack_TreeView
https://github.com/lovyan03/M5Stack_TreeView

**Comment by cmaglie** [comment]
done

**Comment by lovyan03** [comment]
This library name has been corrected because it is incorrect.
Please update this.

M5TreeView -> M5Stack_TreeView
M5OnScreenKeyboard -> M5Stack_OnScreenKeyboard

**Comment by per1234** [comment]
Closing again because I now see there is a separate dedicated issue for the name change request: https://github.com/arduino/Arduino/issues/8736
