### ISSUE TITLE
The name of the file is not available if is out of the  tabs

### ISSUE THREAD

**Issue by SeuPay** [arduino/Arduino#8567]
When you have many files in the IDE, you do not know the name of the file when it is outside the tabs presented. Particularly annoying when using the search command and it falls into a file without a tab.
[Edited]: Found the name of the file in the upper-left corner, 
Thanks for such an amazing tool.

**Comment by per1234** [comment]
We already have a couple of issue reports on this topic so I'm going to go ahead and close it as a duplicate:
- https://github.com/arduino/Arduino/issues/1193
- https://github.com/arduino/Arduino/issues/6109

You'll be happy to know that the IDE's handling of many tabs has been improved and you can test it out if you like in the Arduino IDE Beta Build:
https://www.arduino.cc/en/Main/Software#beta
