### ISSUE TITLE
I like to add a new library

### ISSUE THREAD

**Issue by offcircuit** [arduino/Arduino#8578]
I like to add a new library:

SDHT
url: https://github.com/offcircuit/SDHT

**Comment by offcircuit** [comment]
I forgot to say hello  :)

**Comment by offcircuit** [comment]
Sorry, I had add some resources to reduce memory use (optionally)

**Comment by offcircuit** [comment]
Now, I belive it is good.

**Comment by cmaglie** [comment]
done!

**Comment by offcircuit** [comment]
How can I update my libs:
https://github.com/offcircuit/SDHT
https://github.com/offcircuit/DTime

thanks,
Helder Rodrigues
