### ISSUE TITLE
Unipolar stepper motor dead link

### ISSUE THREAD

**Issue by eightball009** [arduino/Arduino#8581]
https://www.arduino.cc/en/Tutorial/StepperUnipolar.
At the bottom of the page is a link for a .pdf . The link is broken.

**Comment by per1234** [comment]
Thanks so much for reporting the broken link @eightball009!

Here's the new URL to that file:
http://solarbotics.net/library/pdflib/pdf/motorbas.pdf

**Comment by cmaglie** [comment]
the link has been updated
