### ISSUE TITLE
[Library Manager] Add Two Transparent Graphical OLED Libraries

### ISSUE THREAD

**Issue by oclyke** [arduino/Arduino#8587]
Afternoon,

Will you please add these two libraries to the library manager? They are for the control of a transparent graphical OLED with a SSD1309 OLED driver IC.

https://github.com/sparkfun/HyperDisplay_UG2856KLBAG01_ArduinoLibrary

https://github.com/sparkfun/HyperDisplay_SSD1309_ArduinoLibrary

Thank you much!

**Comment by cmaglie** [comment]
Done
