### ISSUE TITLE
[Library Manager] Please add STM32duino library for X-NUCLEO-IKS01A3

### ISSUE THREAD

**Issue by cparata** [arduino/Arduino#8588]
Hi,
Please add to Library Manager (sensor components):

https://github.com/stm32duino/X-NUCLEO-IKS01A3
https://github.com/stm32duino/LSM6DSO
https://github.com/stm32duino/LIS2DW12
https://github.com/stm32duino/LIS2MDL
https://github.com/stm32duino/LPS22HH
https://github.com/stm32duino/STTS751

All have a release.
Thanks in advance

**Comment by cmaglie** [comment]
Done
