### ISSUE TITLE
java.lang.StackOverflowError when preprocessing broken sketch [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#859]
This is [Issue 859](http://code.google.com/p/arduino/issues/detail?id=859) moved from a Google Code project.
Added by 2012-03-15T17:11:38.000Z by [lars.j.nielsen@gmail.com](http://code.google.com/u/lars.j.nielsen@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Open the attached testcase.ino sketch.
2. Try to compile it. (Yes I know the code is gibberish)

**What is the expected output? What do you see instead?**
Expected:
For the original program, successful compilation(it compiles just fine if the Serial.println("test line is removed).
For the testcase, any error message originating from the compiler about broken source code.
Actual:
java.lang.StackOverflowError exception in some RegEx code, see errormsg-from-compiling-testcase.txt for the full output.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 1.0 and latest github version.
Win7 and Ubuntu linux.
Arduino Uno.

**Please provide any additional information below.**
The things that are commented out can not be deleted, then the process gets to the compilation stage.

**Comment by ffissore** [comment]
Commented the original issue

**Comment by ffissore** [comment]
Fixed by #3779
