### ISSUE TITLE
Update libs

### ISSUE THREAD

**Issue by offcircuit** [arduino/Arduino#8594]
How can I update my libs:
https://github.com/offcircuit/SDHT
https://github.com/offcircuit/DTime

Sorry for any inconvenience.

Thanks,
Helder Rodrigues

**Comment by per1234** [comment]
Hi. It's not clear to me what you're asking. I see that both of those libraries are already in Library Manager and that their releases are available.

If you want to create a new tag/release, the procedure is as follows:

1. Update the `version` field in library.properties to the version number that you are planning to release.
2. Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
3. Wait a couple of hours. The Arduino Library Manager indexer job will automatically pick up the new release and it will be available for installation via Library Manager.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

I'm going to go ahead and close this as resolved. If I have misinterpreted your question, please let me know and I'll re-open this issue if necessary.
