### ISSUE TITLE
Documentation for Wifi Rev2 on MacOS is wrong

### ISSUE THREAD

**Issue by tgherzog** [arduino/Arduino#8595]
Just received my Arduino Uno WiFi Rev2 and am following the [setup tutorial][tut] to install the Blink sketch using the desktop IDE (v1.8.8) on MacOS 10.14.1 Mohave.

> Installing Drivers for the Uno WiFi
> OSX
> No drivers are needed for the Arduino UNO WiFi Rev. 2 on macOSX.

Incorrect. My v1.8.8 comes with "Arduino AVR Boards" installed, which supports only "Arduino Uno WiFi." I need to use the Boards Manager to also install the "Arduino megaAVR Boards" package to add support for Rev2. WIthout it, my board options don't match the screen shots in the tutorial, and the upload fails.

[tut]: https://www.arduino.cc/en/Guide/ArduinoUnoWiFiRev2

**Comment by facchinm** [comment]
@SimonePDA can you add the board manager screenshot as for SAMD boards?
