### ISSUE TITLE
Missing pictures

### ISSUE THREAD

**Issue by eightball009** [arduino/Arduino#8605]
On the page, http://playground.arduino.cc/LCD/SC2004CSWB , the only picture that shows is a VERY large tinkercad picture all the other pictures show place holders but nothing is there.

**Comment by per1234** [comment]
Unfortunately, I could not find any replacement for the missing images even after some searching so I simply removed the broken links. The Playground content is community created so Arduino doesn't have any way to preserve off-site resources.
