### ISSUE TITLE
[Library] New library ClosedCube I2C Driver (Wrapper)

### ISSUE THREAD

**Issue by closedcube** [arduino/Arduino#8610]
Hello,

Please add new library: 

https://github.com/closedcube/ClosedCube_I2C_Arduino

Thanks and regards,
ClosedCube

**Comment by per1234** [comment]
Note that, as with https://github.com/arduino/Arduino/issues/8609, the `version` value in your library.properties file is not compliant with the [Arduino library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification). However, this repository does have previous releases that are compliant so I don't think the issue will block addition to the Library Manager index in this case. It will mean that the latest release of the library (and any other non-compliant releases that come after it) will not be available for installation via Library Manager.

**Comment by closedcube** [comment]
HI,

_version_ has been updated.

Many thanks

**Comment by cmaglie** [comment]
It seems that you renamed the library from `ClosedCube I2C driver` to `ClosedCube_I2C_Driver`, shall I keep the latter?

**Comment by closedcube** [comment]
Yes, please

Thanks

**Comment by cmaglie** [comment]
done
