### ISSUE TITLE
https://create.arduino.cc/editor NOT WORKING

### ISSUE THREAD

**Issue by 5473957320987** [arduino/Arduino#8611]
https://create.arduino.cc/editor

The online editor is not connecting to my Arduino boards.  I have tried 2 different USB cables and no change.

This is the error message that pops down from the top of the browser.  I have installed and reinstalled the Arduino Create Engine.  Hmm... Any thoughts?

**Comment by per1234** [comment]
According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor.

If you have not done so already, please post on the Arduino forum and we'll try to help you out with your problem over there. Please make sure to provide as much information as possible. I notice you say "This is the error message that pops down from the top of the browser", but then don't actually state what the error message is. That is the sort of information that is very important for us to be able to help you.
