### ISSUE TITLE
On UNO board, replace the regulator by a DC-DC module [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#862]
This is [Issue 862](http://code.google.com/p/arduino/issues/detail?id=862) moved from a Google Code project.
Added by 2012-03-18T20:53:01.000Z by [charles....@gmail.com](http://code.google.com/u/109102242930001311920/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

Replace the regulator by a DC-DC module to power up the Arduino UNO board.
This modification will increase the power efficiency of the system and avoid unnecessary heating.
In many cases, the UNO must be power supplied by 12V or 24V. For example:
- UNO is used with a motor shield and the motor requires higher voltage as 12V or 24V.
- 12V or 24V are common power supply in the field

**Comment by Avamander** [comment]
This is not IDE related?
