### ISSUE TITLE
[Library Manager] Please *RE* add BNO055 server for SimplePacketComs library (i fixed the conflicts)

### ISSUE THREAD

**Issue by madhephaestus** [arduino/Arduino#8636]
https://github.com/madhephaestus/BNO055SimplePacketComs

This library adds Simple Packet Coms server of the BNO055 IMU module. The server is not platform dependent and will work with any implementation of SimplePacketComs

This library was providing Adafruit_Sensor.h and was causing compilation conflicts. It appears it was de-listed as a result. 

https://github.com/adafruit/Adafruit_BNO055/issues/58

I have fixed the dependency issue and made a repaired release.

**Comment by madhephaestus** [comment]
The upstream Adafruit Universal Sensor library merged and released the fix on their side, and my side is compatible with it. 

https://github.com/adafruit/Adafruit_Sensor/pull/26

**Comment by cmaglie** [comment]
Done!

**Comment by madhephaestus** [comment]
@cmaglie Thank you! I do have one question, is there a way to get notified when a library one has published gets de-listed? I would have fixed this earlier if i had known it was causing issues.

**Comment by cmaglie** [comment]
There isn't an official way to get notified, cases like yours are very rare (I remember only another one) so we didn't think about a procedure.

We should have contacted you before delisting the library (via github or the email written in library.properties...) sorry about that!

**Comment by madhephaestus** [comment]
Well if its so rare i guess having one-off procedures is ok. Thanks for reinstating this :)
