### ISSUE TITLE
Add support for avrdude -Pavrdoper [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#864]
This is [Issue 864](http://code.google.com/p/arduino/issues/detail?id=864) moved from a Google Code project.
Added by 2012-03-23T01:15:08.000Z by [ajd4...@gmail.com](http://code.google.com/u/111586251362046628297/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Add support for avrdude -Pavrdoper

**Why?**
The AVR-Doper works as a HID; this lets you program devices without needing to install any drivers on windows.

Would this cause any incompatibilities with previous versions?
None.

**Comment by sandeepmistry** [comment]
Closing based on https://github.com/arduino/Arduino/pull/68#issuecomment-100923666.
