### ISSUE TITLE
[Library Manager] Please add Adafruit INA260 library

### ISSUE THREAD

**Issue by siddacious** [arduino/Arduino#8641]
Please add this new driver for the TI INA260 current and power monitor/sensor:
https://github.com/adafruit/Adafruit_INA260

Thanks!

**Comment by siddacious** [comment]
Closed because of travis issues on the adafruit side. I'll reopen when they're fixed.

**Comment by siddacious** [comment]
Ok, travis issues fixed! Please add to the library manager now.

**Comment by cmaglie** [comment]
done!

**Comment by siddacious** [comment]
Thanks :)
