### ISSUE TITLE
Change Serial Monitor font to one that is monospace. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#865]
This is [Issue 865](http://code.google.com/p/arduino/issues/detail?id=865) moved from a Google Code project.
Added by 2012-03-23T16:47:27.000Z by [lars.j.nielsen@gmail.com](http://code.google.com/u/lars.j.nielsen@gmail.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

**What change would like to see?**
Change of the font used in the serial monitor to one that is monospaced.

**Why?**
Easier to read the output, especially when it's a lot of similar output that is moving fast.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

None.

**Comment by suculent** [comment]
It still does not have lines aligned... therefore QR codes converted to ASCII do not work. Bang!
