### ISSUE TITLE
[Library manager] Please add M5StickC Libraries

### ISSUE THREAD

**Issue by zhouyangyale** [arduino/Arduino#8655]
Hi,
Please add to Library Manager

https://github.com/m5stack/M5StickC

Thanks You

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by zhouyangyale** [comment]
Now that I have modified it, can you see it?please。
thanks

**Comment by cmaglie** [comment]
Done

**Comment by zhouyangyale** [comment]
Ok thanks

发自我的 iPhone
