### ISSUE TITLE
freeBSD 12 and lastest version of arduino 

### ISSUE THREAD

**Issue by CyrilleBiot** [arduino/Arduino#8666]
Hi
I'd like to compile the latest version of arduino for freeBSD
Is there a compilation read me somewhere ?
What's the better way to do that ?
thx

**Comment by per1234** [comment]
>Is there a compilation read me somewhere ?

Here it is:
https://github.com/arduino/Arduino/wiki/Building-Arduino

**Comment by CyrilleBiot** [comment]
OK for windows and Linux, but for freeBSD specifications, no.
I'll test based on Linux dependencies...
thx
