### ISSUE TITLE
sd card interfacing using FAT32 in embedded c

### ISSUE THREAD

**Issue by vsnarkhede13** [arduino/Arduino#8667]
I am working on development board of atmega 2560 and i want to implement sd card using fat 32 in embedded programming. This is my academics project work and I need urgent assist for my query as I am running out of time. I'm able to initialize sd card and get file info for the files in sd card but I'm not able to access data of that file(file info includes only size, first_cluster).

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This is _not_ a place to ask for assistance with your project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
