### ISSUE TITLE
[Library Manager] Please include Sparkfun Qwiic Keypad Arduino Library

### ISSUE THREAD

**Issue by lewispg228** [arduino/Arduino#8673]
Please add this SparkFun Qwiic Keypad Arduino Library to the Library Manager.
https://github.com/sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library

Thanks

-Pete

**Comment by cmaglie** [comment]
mmm are you sure the link is correct?

**Comment by lewispg228** [comment]
@cmaglie Sorry about that... I forgot to make it public. Should be gtg now. Thanks for your qwiic response!

**Comment by cmaglie** [comment]
done!

**Comment by lewispg228** [comment]
Awesome. Thanks so much @cmaglie . We are very excited to see this pop up in the Arduino Library manager. Wahoo!!

**Comment by lewispg228** [comment]
Hi There,
Library Manager doesn't seem to be recognizing our releases on this library. Is there something we're doing incorrectly?

Note, our latest release was created 12 days ago, so we're assuming the manager has already attempted to update.

https://github.com/sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library/releases

Let us know and thanks!
-Pete
