### ISSUE TITLE
Error while detecting libraries included by stepper.c

### ISSUE THREAD

**Issue by brianbixby** [arduino/Arduino#8685]
I was flashing this repo (https://github.com/MarlinFirmware/Marlin) onto my Arduino, when I received the following error. 
BUG FIX: to fix this bug all i had to do was go into preferences and check display line numbers.

**Comment by facchinm** [comment]
Hi @brianbixby ,
you should probably open the issue on Marlin github repo. The "error while detecting libraries" string is a warning that most of the times doesn't affect compilation; it just tells that something went wrong during prototypes generation, which are not always mandatory.

I'm closing this one, please reopen if I missed something.
