### ISSUE TITLE
[Library Manager] Request to Change Library Name (Xbox 360 Controller LEDs)

### ISSUE THREAD

**Issue by dmadison** [arduino/Arduino#8697]
URL: https://github.com/dmadison/Xbox360ControllerLEDs

Hello,

I'd like to request to change the name of one of my libraries that is already listed in the libraries manager. The current name is "Xbox 360 Controller LED Library" and I'd like to change the name to "Xbox 360 Controller LEDs". Per the instructions [here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name), I have already changed the `library.properties` file and pushed a new release with the changed name.

Thank you!

**Comment by cmaglie** [comment]
Done!

**Comment by dmadison** [comment]
Thank you! :heart:
