### ISSUE TITLE
Please add the libraries

### ISSUE THREAD

**Issue by ArminJo** [arduino/Arduino#8705]
Hello,

I prepared 5 libraries for use as Arduino libraries and hope that they will be valuable for the Arduino community.

1. https://github.com/ArminJo/ServoEasing
2. https://github.com/ArminJo/NeoPatterns
3. https://github.com/ArminJo/PlayRtttl
4. https://github.com/ArminJo/EasyButtonAtInt01
5. https://github.com/ArminJo/Arduino-FrequencyDetector

Could you add them to your list of libraries?

Thank you.
Armin

**Comment by cmaglie** [comment]
Done!
