### ISSUE TITLE
Missing images in the website

### ISSUE THREAD

**Issue by ableu** [arduino/Arduino#8706]
Hi,

As I wanted to read three tutorials from the website, I noticed that all the images where missing (404). 
The 3 pages are : 
- <https://www.arduino.cc/en/Main/Standalone>
- <https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard>
- <https://www.arduino.cc/en/Tutorial/ArduinoISP>
But it seems they are not the only ones.   
Can you please make the images available again ?   

Thanks.

**Comment by per1234** [comment]
The images are back again now.

**Comment by ableu** [comment]
Thanks :)
