### ISSUE TITLE
attachInterrupt problem

### ISSUE THREAD

**Issue by Omar-alSuntawi** [arduino/Arduino#8711]
This code does not work correctly !

```
const byte ledPin = 13;
const byte interruptPin = 2;
volatile byte state = LOW;

void setup() {
  pinMode(ledPin, OUTPUT);
  pinMode(interruptPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(interruptPin), blink, CHANGE);
}

void loop() {
  digitalWrite(ledPin, state);
}

void blink() {
  state = !state;
}
```

which is on the Arduino Reference [https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/](url)

It seems to accidentally read random values.

**Comment by per1234** [comment]
Moved to https://github.com/arduino/reference-en/issues/575
