### ISSUE TITLE
[Library Manager]Please add Grove - 16-Channel Servo Driver(PCA9685) v0.0.1 to Library Manager.

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8718]
Github:https://github.com/Seeed-Studio/Seeed_PCA9685
Release:https://github.com/Seeed-Studio/Seeed_PCA9685/releases/tag/v1.0.0

Thanks

**Comment by Jenkinlu001** [comment]
Release:https://github.com/Seeed-Studio/Seeed_PCA9685/releases/tag/v0.0.1

thanks

**Comment by cmaglie** [comment]
done!
