### ISSUE TITLE
[Library Manager]Please add Grove - I2C High Accuracy Temp_Humi Sensor SHT35 v1.0.0 to Library Manager. 

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8719]
Github:https://github.com/Seeed-Studio/Seeed_SHT35
Release:https://github.com/Seeed-Studio/Seeed_SHT35/releases/tag/v1.0.0

Thanks

**Comment by per1234** [comment]
Hi. The `name` value in library.properties for this library (`Grove - I2C High Accuracy Temp&Humi Sensor(SHT35)`) is not compliant with the Arduino Library Specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
>Library names must contain only basic letters (A-Z or a-z) and numbers (0-9), spaces (), underscores (_), dots (.) and dashes (-). It cannot start or end with a space, and also it cannot start with a number.

Please change the `name` value to something compliant with the specification and then either update the `version` value in library.properties and create a new tag/release or else redo the existing tag/release.

After you have done this, please comment here so we'll know we can proceed.

**Comment by Jenkinlu001** [comment]
I'll update it and submit it again, thanks

**Comment by Jenkinlu001** [comment]
This is the latest:
rename:Grove - I2C High Accuracy Temp_Humi Sensor SHT35
Github:https://github.com/Seeed-Studio/Seeed_SHT35
Release:https://github.com/Seeed-Studio/Seeed_SHT35/releases/tag/v1.0.0

Thanks

**Comment by cmaglie** [comment]
done!
