### ISSUE TITLE
[Library Manager]Please add Grove - I2C Thermocouple Amplifier MCP9600 v1.0.0 to Library Manager. 

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8721]
Github:https://github.com/Seeed-Studio/Seeed_MCP9600
Release:https://github.com/Seeed-Studio/Seeed_MCP9600/releases/tag/v1.0.0

Thanks

**Comment by per1234** [comment]
Hi. I see you updated the `name` value to remove the disallowed characters, but in the latest tag, the `name` value is still non-compliant:
https://github.com/Seeed-Studio/Seeed_MCP9600/blob/v1.0.0/library.properties#L1

Please either update the `version` value in library.properties and then create a new tag/release, or else redo the existing release.

Once you have done this, please comment here so we'll know we can proceed.

**Comment by Jenkinlu001** [comment]
update Release: https://github.com/Seeed-Studio/Seeed_MCP9600/releases/tag/v1.0.0

**Comment by cmaglie** [comment]
done!
