### ISSUE TITLE
[Library Manager]Please add Grove - Laser PM2.5 Sensor HM3301 v1.0.0 to Library Manager. 

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8722]
Github:https://github.com/Seeed-Studio/Seeed_PM2_5_sensor_HM3301
Release:https://github.com/Seeed-Studio/Seeed_PM2_5_sensor_HM3301/releases/tag/v1.0.0

Thanks

**Comment by cmaglie** [comment]
done!
