### ISSUE TITLE
[Library Manager]Please add Grove - Capacitive Touch Slide Sensor CY8C40XX v1.0.0 to Library Manager. 

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8724]
Github:https://github.com/Seeed-Studio/Grove_touch_sensor_CY8C40XX
Release:https://github.com/Seeed-Studio/Grove_touch_sensor_CY8C40XX/releases/tag/v1.0.0

Thanks

**Comment by cmaglie** [comment]
done
