### ISSUE TITLE
[Library Manager]Please add Grove - Motor Driver TB6612FNG v0.0.1 to Library Manager. 

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#8726]
Github:https://github.com/Seeed-Studio/Grove_Motor_Driver_TB6612FNG
Release:https://github.com/Seeed-Studio/Grove_Motor_Driver_TB6612FNG/releases/tag/v0.0.1

Thanks

**Comment by cmaglie** [comment]
Done
