### ISSUE TITLE
[Library Manager] Add `Tasks` to Library Manager

### ISSUE THREAD

**Issue by emctague** [arduino/Arduino#8730]
https://github.com/emctague/Tasks

The library hooks into the `loop()` function, allowing objects to register themselves as 'Tasks' and have an update method called on every loop.

The main benefit of this library vs. similar ones is that it *hides itself away*:
 - nothing needs to be added to `setup()` or `loop()`, as it's done automatically
 - The `Task` class hides away the details of registering as a task, leaving those writing tasks free to worry about a single `update()` method

**Comment by cmaglie** [comment]
Done!
