### ISSUE TITLE
[Library Manager] Please Add ESP8266/ESP32 SDS011 library

### ISSUE THREAD

**Issue by dok-net** [arduino/Arduino#8735]
URL: https://github.com/dok-net/esp_sds011
This is an implementation of a driver for the SDS011 particulate matter sensor by Nova Fitness. It is designed to work with the ESPSoftwareSerial device for the ESP8266 and ESP32 SOC microcontrollers, which supports the asynchronous handling of the measurements issued by the
sensor.

**Comment by cmaglie** [comment]
done
