### ISSUE TITLE
[Library Manager] Please Update this library.

### ISSUE THREAD

**Issue by lovyan03** [arduino/Arduino#8736]
This library name in library.properties has been corrected because it is incorrect.
Please update this.

M5OnScreenKeyboard -> M5Stack_OnScreenKeyboard
https://github.com/lovyan03/M5Stack_OnScreenKeyboard

M5TreeView -> M5Stack_TreeView
https://github.com/lovyan03/M5Stack_TreeView

**Comment by cmaglie** [comment]
Done, the old libraries will disappear at the next cleanup of the cache (happens weekly).
