### ISSUE TITLE
[Library Manager] Add Sparthan libraries

### ISSUE THREAD

**Issue by d-asnaghi** [arduino/Arduino#8746]
https://github.com/project-sparthan/sparthan-gforce
https://github.com/project-sparthan/sparthan-module
https://github.com/project-sparthan/sparthan-myo

I would like to add these libraries to the Arduino Library Manager, thank you very much!

**Comment by cmaglie** [comment]
done

**Comment by d-asnaghi** [comment]
Thank you!
