### ISSUE TITLE
[Library manager] update library

### ISSUE THREAD

**Issue by TomasRoj** [arduino/Arduino#8749]
Hi,

can you please my BasicsLibrary to the latest version 1.1? Link here: https://github.com/TomasRoj/BasicsLibrary

thanks,
Tom

**Comment by per1234** [comment]
The Library Manager indexer job automatically picks up all valid releases of the libraries in the index within a couple hours of you making one. So there is no need to request an update for each release. If you check Library Manager, you'll see that the 1.1 release of your library is already available.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
