### ISSUE TITLE
Use of a variable servo name "main" does not show a code, but just a warning [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#875]
This is [Issue 875](http://code.google.com/p/arduino/issues/detail?id=875) moved from a Google Code project.
Added by 2012-04-05T15:59:53.000Z by [arvind.e...@gmail.com](http://code.google.com/u/105963763895739092378/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. Use of variable name as servo variable (might extend to general variables)

Error is expected, rather "out of range" warning is generated, code is compiled and uploaded

v1.0 on Win7, Uno

**Comment by per1234** [comment]
Closing because insufficient description of the problem makes it impossible to investigate.
