### ISSUE TITLE
[Library Manager] add VincentLim/TimerFour

### ISSUE THREAD

**Issue by photodude** [arduino/Arduino#8758]
Please consider adding https://github.com/VincentLim/TimerFour to the library manager index

This is a modification of the [PaulStoffregen/TimerThree](https://github.com/PaulStoffregen/TimerThree) Library to provide the same functionality for modifying Timer Four on supported boards

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by photodude** [comment]
@per1234, this one should also be ready to go.

**Comment by cmaglie** [comment]
done!

**Comment by photodude** [comment]
@per1234 @cmaglie Thank you
