### ISSUE TITLE
violating somme findamental rules of programming

### ISSUE THREAD

**Issue by syed-aamir** [arduino/Arduino#8762]
![programming error](https://user-images.githubusercontent.com/49398633/55721673-5948b780-5a1d-11e9-9e17-f2d27e8d575f.png)

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, and the full error output, using code tags (`</>` button on the toolbar).
