### ISSUE TITLE
[Library Manager] Add Thinger.io

### ISSUE THREAD

**Issue by alvarolb** [arduino/Arduino#8771]
Please, add the thinger.io library for the library manager. It is a library for connecting to the thinger.io open source iot platform. This library was already included, why it has been removed? what is the criteria?

Thanks!
https://github.com/thinger-io/Arduino-Library

**Comment by cmaglie** [comment]
There was a regression bug in the validation of the `name` field in the library indexer, now is fixed!

Sorry about that!
