### ISSUE TITLE
[Library Manager] Add ProtoCentral MAX86150 library

### ISSUE THREAD

**Issue by protocentralashwin** [arduino/Arduino#8773]
Please add the following library for Arduino.

https://github.com/Protocentral/protocentral_max86150_ecg_ppg

**Comment by cmaglie** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by protocentralashwin** [comment]
Sorry @cmaglie , I have created the release.

Thank you so much !

**Comment by cmaglie** [comment]
done
