### ISSUE TITLE
[Library Manager] Please add Robot Cing library

### ISSUE THREAD

**Issue by StanislavJochman** [arduino/Arduino#8780]
Source: https://github.com/RobotCing/Atmega32u4_IO
Tag: https://github.com/RobotCing/Atmega32u4_IO/releases/tag/3.0.0

Please add Robot Cing library.
Main features:
Programing robot Cing without knowlage of electronics.

Best regards
Stanislav Jochman

**Comment by cmaglie** [comment]
done
