### ISSUE TITLE
Please add NOKIA5110_TEXT library.

### ISSUE THREAD

**Issue by gavinlyonsrepo** [arduino/Arduino#8787]
Hi 

Please add NOKIA5110_TEXT library.

Source:https://github.com/gavinlyonsrepo/NOKIA5110_TEXT
Tag: https://github.com/gavinlyonsrepo/NOKIA5110_TEXT/releases/tag/1.0.0

* Name : NOKIA5110_TEXT
* Title : Library for Nokia 5110 LCD (PCD8544 controller) for the Arduino eco-system
* Description : Arduino library,  ASCII character text only (12 * 6 ) 72 characters in total, Sleep mode, minimalist. Single font. Example program(tested on UNO) uses 1874 bytes (5%) of program storage space. Maximum is 32256 bytes.
Global variables use 22 bytes (1%) of dynamic memory, leaving 2026 bytes for local variables. Maximum is 2048 bytes.

Kind regards

**Comment by cmaglie** [comment]
done
