### ISSUE TITLE
Add the StreamUtils library

### ISSUE THREAD

**Issue by bblanchon** [arduino/Arduino#8788]
Hi!

I published a new library to help Arduino users dealing with streams.
For now, it allows adding a buffer to a stream and adding log to a stream.

Here is the address:
https://github.com/bblanchon/ArduinoStreamUtils

Thank you very much for adding this to the Library Manager

Best regards,
Benoit

**Comment by cmaglie** [comment]
done

**Comment by bblanchon** [comment]
Thanks!
