### ISSUE TITLE
detachInterrupt() support missing for INT2, INT2 missing for ATmega644 [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#879]
This is [Issue 879](http://code.google.com/p/arduino/issues/detail?id=879) moved from a Google Code project.
Added by 2012-04-06T03:06:11.000Z by [drmn...@gmail.com](http://code.google.com/u/107379186338214693261/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. attachInterrupt(INT2...) on an ATmega1284
2. detachInterrupt(INT2)

or

1. attachInterrupt(INT2...) on ATmega644

**What is the expected output? What do you see instead?**
Case to detach interrupt INT2 is missing from the detachInterrupt() function. Additionally, EXTERNAL_NUM_INTERRUPTS in wiring_private.h is not correct for ATmega644.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
WInterrupts.c in current Github repository (as of 4/5/2012)

The attached files include fixes for the above issues as follows:
* WInterrupts.c: Add INT2 case to detachInterrupt()
* wiring_private.h: Detect (more smartly) EXTERNAL_NUM_INTERRUPTS for ATmega644/1284 by checking for the presence of the ISC2x bit definitions (only defined for chips with an INT2).
* (bonus) WInterrupts.c: Close Issue 831

**Comment by vicatcu** [comment]
I just submitted pull request #3221 to address this
