### ISSUE TITLE
Please add PMW3360 motion sensor library

### ISSUE THREAD

**Issue by SunjunKim** [arduino/Arduino#8790]
Hi!
I developed a new library for interfacing PMW3360 motion sensor module.

I want to add them to Library Manager.
Here's the links.

Homepage: https://github.com/SunjunKim/PMW3360
Tag: https://github.com/SunjunKim/PMW3360/releases/tag/v1.0.0

Best regards,
Sunjun.

**Comment by cmaglie** [comment]
done
