### ISSUE TITLE
[Library Manager] Please add SparkFun Qwiic Capacitive Touch Slider Arduino Library

### ISSUE THREAD

**Issue by andreadevo** [arduino/Arduino#8799]
Hi,

Please add our Qwiic Capacitive Touch Slider Arduino Library to the library manager. Here is the link: https://github.com/sparkfun/Qwiic_Capacitive_Touch_Slider_Arduino_Library

Thank you!

**Comment by per1234** [comment]
@andreadevo Hi. The link gives a 404 error. Is the repository private?

**Comment by andreadevo** [comment]
@per1234 Yes, thank you! I forgot to switch it be public. The library should now be public: https://github.com/sparkfun/Qwiic_Capacitive_Touch_Slider_Arduino_Library

**Comment by cmaglie** [comment]
done
