### ISSUE TITLE
[Library Manager] Please Add Mechatro Library

### ISSUE THREAD

**Issue by teamong** [arduino/Arduino#8823]
Motor Driver Library for L298x.
easy to drive and measure current each motor.
please add to library mamager.
thank you.
https://github.com/teamong/Mechatro

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by teamong** [comment]
Yes. I have created a first release.
thank you.

**Comment by cmaglie** [comment]
done!
