### ISSUE TITLE
[Library Manager] Please add FixedPoint_LUT to Library Manager

### ISSUE THREAD

**Issue by Pantastisch** [arduino/Arduino#8829]
Hello Arduino team,

I see that you have a long backlog of libraries to add, but I hope that you'll find the time to add this new library of mine:

Homepage: https://github.com/Pantastisch/FixedPoint_LUT
Repository: https://github.com/Pantastisch/FixedPoint_LUT.git
It should be ready to go:

  git tag
  library.properties
  examples
  keywords.txt

Thank you very much! 😊😊😊

**Comment by cmaglie** [comment]
I see no tags: https://github.com/Pantastisch/FixedPoint_LUT/tags

**Comment by Pantastisch** [comment]
Released! 
Sorry, forget that! :)

**Comment by cmaglie** [comment]
done

**Comment by njh** [comment]
@Pantastisch this is giving a 404 now.

Do you have any feedback about why you deleted your repository?
