### ISSUE TITLE
LiquidCrystal and GSM libraries missing from the Library Manager index

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#8836]
The LiquidCrystal and GSM libraries are no longer listed in the Arduino Library Manager (http://downloads.arduino.cc/libraries/library_index.json).

This has caused those libraries to not be available for use in the Arduino Web Editor.

All the other libraries bundled with the Arduino IDE are in the Library Manager index. I don't know whether any 3rd party libraries are missing.

Originally reported at:
http://forum.arduino.cc/index.php?topic=613331

**Comment by cmaglie** [comment]
For some reason the local git clone of GSM and LiquidCrystal was corrupted.
The index is being regenerated now... just the time for all the caches to refresh and the issue should be solved.
