### ISSUE TITLE
Optimization in print.cpp [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#884]
This is [Issue 884](http://code.google.com/p/arduino/issues/detail?id=884) moved from a Google Code project.
Added by 2012-04-11T11:57:21.000Z by [rob.till...@gmail.com](http://code.google.com/u/113198963792305667520/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

print.cpp contains 

```c++
size_t Print::println(void)
{
  size_t n = print('\r');
  n += print('\n');
  return n;
}
```

which can be optimized to

```c++
size_t Print::println(void)
{
   return write ("\r\n");
}
```

It is simpler and it has less call overhead.

For a background discussion, see: 
- http://arduino.cc/forum/index.php/topic,100712.0.html -

**Comment by facchinm** [comment]
Fixed with #3211
