### ISSUE TITLE
[Library Manager] Please add RotaryDial library

### ISSUE THREAD

**Issue by Harvie** [arduino/Arduino#8852]
Please add this library:
https://github.com/Harvie/RotaryDial

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Harvie** [comment]
Sorry, i've fixed the tag.

**Comment by cmaglie** [comment]
done
