### ISSUE TITLE
Reference content bundled with Arduino IDE is very outdated

### ISSUE THREAD

**Issue by per1234** [arduino/Arduino#8860]
The Arduino IDE comes with a copy of the Arduino Language Reference and some library reference pages. These are used to provide documentation accessed via **Help > Reference** and the context menu's "Find in Reference".

The Arduino Language Reference content is at least 1.5 years out of date.

The library reference pages appear to be ~2 years out of date at least, since this change made Jul 17, 2017 is not present: https://github.com/arduino/Arduino/issues/6507
I didn't check back farther than that.

Since that time, many updates, corrections, and improvements have been made to the reference content. These files should be updated on every release of the Arduino IDE.

Originally reported at:
https://forum.arduino.cc/index.php?topic=613108.msg4166197#msg4166197

**Comment by facchinm** [comment]
@per1234 the script we used to launch was  https://github.com/arduino/Arduino/blob/master/build/create_reference.pl . I think it is very outdated now and should be ported to the new reference architecture.
@cmaglie @mastrolinux @gvarisco any idea?

**Comment by gvarisco** [comment]
Tagging @arduinosocial here

**Comment by alranel** [comment]
I think we should just remove the offline version for now, and launch the online one when the reference menu item is selected.
