### ISSUE TITLE
[Board Manager] json files of board packages previously installed will be deleted after new board packages installed.

### ISSUE THREAD

**Issue by konosubakonoakua** [arduino/Arduino#8863]
I'm using Arduino IDE 1.8.9 and have ESP32 and STM32duino packages installed.
After I install the esp8266 package, `package_esp32_index.json` and `package_stm_index.json` are gone.
I have met this when I install esp32 after stm32duino got installed.
<img width="335" alt="package_folder_new" src="https://user-images.githubusercontent.com/42881610/57534251-35f18f00-7372-11e9-8408-eda2614ed83b.png">
<img width="182" alt="brd_man" src="https://user-images.githubusercontent.com/42881610/57534343-6802f100-7372-11e9-830b-51d90393f4ad.png">

I copy the backup file into this folder and old packages are back now.
<img width="337" alt="package_folder_new_fixed" src="https://user-images.githubusercontent.com/42881610/57534336-620d1000-7372-11e9-9a2c-153660a3b3cf.png">
<img width="182" alt="esp32" src="https://user-images.githubusercontent.com/42881610/57534488-b7492180-7372-11e9-8c2c-395595394d18.png">
<img width="134" alt="esp86" src="https://user-images.githubusercontent.com/42881610/57534494-bc0dd580-7372-11e9-9a77-fce9473e7bb5.png">
<img width="166" alt="stm" src="https://user-images.githubusercontent.com/42881610/57534513-c203b680-7372-11e9-97d4-f6e32b0394c0.png">

could you fix this please?

**Comment by per1234** [comment]
Please make sure that you have all three package index URLs in your **File > Preferences > Additional Boards Manager URLs**, separated by commas. If you deleted the previous URLs from that preference when you added the ESP8266 URL, it would result in the exact behavior you've experienced.

Please let me know whether that was the problem.

**Comment by konosubakonoakua** [comment]
Thank you, you are right, I try it, it works. thanks😁
