### ISSUE TITLE
Board definition for Wemos D1 R2 & Mini changed ??? in stable revision (2.5.0)

### ISSUE THREAD

**Issue by CarlierJP** [arduino/Arduino#8875]
- First config:
Windows 10 and Arduino IDE 1.8.5
Additionnal Boards: http://arduino.esp8266.com/versions/2.3.0/package_esp8266com_index.json
Wemos D1 Mini connected to Home WiFi and using analog input to read a analog Temperature sensor (LM 335).
Compile sketch and send it OTA without problem, running well.

- Second config
Windows 10 and Arduino IDE 1.8.9
Additionnal Boards: http://arduino.esp8266.com/stable/package_esp8266com_index.json  (2.5.0)
No more Wemos D1 R2 & Mini board showed ???? replaced by LILO D1 Mini ????    Are they equal ????
Compile sketch and send it OTA without problem, BUT running crazy !
  - Do a lot of retries to connect to the WiFi
  - Do a lot of read timeout when discussing with others on the network
  - (A0 pin) analog input reads are not reliable: normaly 0V->0, 3.3V->1024, 1.65V->512, but now 1.65V->+-760 and the hardware (my home heater) depending of these values runs completely odd.

- Back to the first config from my hard disk backup and problems disappear.
- Try a Mix config: IDE 1.8.5 with Boards 2.5.0 -> same problems
- Try a Mix config: IDE 1.8.9 with Boards 2.3.0 -> NO problems, WiFi OK, no more read timeout, and analog input 1.65Volts reads +-512.

- Actual config IDE 1.8.5 and boards 2.3.0 from my backup: no problems from 3 days now.

I do also a test case with a Wemos D1 Mini but disconnected from all sensors, just connect a regulated power supply of 1.65V on A0 and we read +-512 with board 2.3.0 and +-760 with board 2.5.0 !!!

**Comment by per1234** [comment]
The ESP8266 core for Arduino is a 3rd party project. Arduino does not provide support for this project.

This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide all the information that will be needed for people to help you.
