### ISSUE TITLE
[Library Manager] Please add Virtuino libraries to Library Manager

### ISSUE THREAD

**Issue by iliaslamprou** [arduino/Arduino#8882]
I want to add the following libraries to arduino library manager
https://github.com/iliaslamprou/virtuino
https://github.com/iliaslamprou/virtuinoESP
https://github.com/iliaslamprou/virtuino_stm32

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by iliaslamprou** [comment]
Thank you!

I have finished the necessary changes.
I think it is ok now
Could you add Virtuino libraries to the Library Manager?

*Best Regards*
*Ilias Lamprou*
*Virtuino Developer*

*https://virtuino.com <http://virtuino.com>*
*Play Store page*
<https://play.google.com/store/apps/developer?id=Ilias+Lamprou>



Στις Τετ, 15 Μαΐ 2019 στις 3:36 π.μ., ο/η per1234 <notifications@github.com>
έγραψε:
