### ISSUE TITLE
[Library Manager] Please add AllThingsTalk LoRaWAN SDK

### ISSUE THREAD

**Issue by vydd** [arduino/Arduino#8885]
Hello,

Please add our library to the Library Manager.

https://github.com/allthingstalk/arduino-lorawan-sdk

(Hopefully, it's ok that the latest 3.0.0 tag is not pointing to `master` - we need to do it this way in order to gracefully sync the docs after the release)

Thanks!

**Comment by cmaglie** [comment]
done

> (Hopefully, it's ok that the latest 3.0.0 tag is not pointing to master - we need to do it this way in order to gracefully sync the docs after the release)

no problem for that
