### ISSUE TITLE
Reference question

### ISSUE THREAD

**Issue by TomasRoj** [arduino/Arduino#8887]
hi,

should I also rename name of files, folder etc in the czech reference?

**Comment by per1234** [comment]
No. Please leave the file and folder names unchanged and unmoved. A great reference you can use for questions like this is the repository for the Portuguese translations of the reference, which is 100% translated:
https://github.com/arduino/reference-pt

Please open issues about the Czech translation of the Arduino Language Reference in https://github.com/arduino/reference-cs and general Language Reference issues in https://github.com/arduino/reference-en. This repository is not an appropriate place to submit issues about the Arduino Language Reference.
