### ISSUE TITLE
Does something like PEP8 exists in Arduino?

### ISSUE THREAD

**Issue by TomasRoj** [arduino/Arduino#8888]
Python has own PEP8 format for writing clean and neat code. Does something similar exists for Arduino c++?

**Comment by per1234** [comment]
Related:
- https://github.com/arduino/ArduinoCore-avr/issues/71
- https://github.com/arduino-libraries/ArduinoIoTCloud/commit/1a8d49433b85ae2037dfd43bf3ee99f9d6aa9ee3
- And in your own repository!: https://github.com/TomasRoj/OctopusLab-Library/blob/52ecd070c37f1abe268e1ef7fc32dcea9396dd2a/.travis.yml#L101-L121
