### ISSUE TITLE
obsolete library used while compiling [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#889]
This is [Issue 889](http://code.google.com/p/arduino/issues/detail?id=889) moved from a Google Code project.
Added by 2012-04-16T19:13:07.000Z by [rtnger...@gmail.com](http://code.google.com/u/113597335698330064463/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
using a obsolete library in the user library folder the compiler should produce a 'wrong library' message.
alternatively: Standard Libraries should only be read from the app library folder.

**Why?**
Now a message looks like this:
In file included from TwoPortReceive.cpp:27:
/Users/gbosch/Documents/Arduino/libraries/SoftwareSerial/SoftwareSerial.h:95: error: conflicting return type specified for 'virtual void SoftwareSerial::write(uint8_t)'
/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.h:48: error:   overriding 'virtual size_t Print::write(uint8_t)'
(a bit intimidating on users like me)

The error is caused while using a SoftwareSerial.h header file from the -obsolete- SoftwareSerial library in the user library folder. The correct library is in the app library folder.

Would this cause any incompatibilities with previous versions? 
Not likely.

If so, howcan these be mitigated?

**Comment by ffissore** [comment]
Fixed #2850 part of 1.6.4
