### ISSUE TITLE
Can't see the Japanese string for 'Cancel' when Japanese is chosen as a default language [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#890]
This is [Issue 890](http://code.google.com/p/arduino/issues/detail?id=890) moved from a Google Code project.
Added by 2012-04-18T13:32:56.000Z by [kotob...@gmail.com](http://code.google.com/u/114024383179456627909/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Milestone-1.0.2, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Launch Arduino IDE
2. Open a preference dialog
3. Can't see the Japanese string for 'Cancel'

**What is the expected output? What do you see instead?**
The label of the button should be 'キャンセル' but was shortened into 'キャン…'

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino IDE 1.0.1 rc2
Mac OS X 10.7.3 (Japanese)

**Please provide any additional information below.**

**Comment by ffissore** [comment]
Fixed a long time ago. Tested with latest hourly
