### ISSUE TITLE
Need separate settings for Serial Monitor port and Upload Port

### ISSUE THREAD

**Issue by owendelong** [arduino/Arduino#8908]
I would like to be able to upload firmware via OTA while maintaining the Serial Monitor connection to the board.

This is possible in hardware, but is a limitation of the IDE in that it has no ability to understand that the upload port and serial monitor port might not be the same.

I suggest adding a menu item for Tools called "Monitor Port" and renaming "Port" -> "Upload Port".

Any time Upload Port is changed to a Serial Port, Monitor Port would be changed to match.
If Monitor Port is changed by the user, then it would remain on the new value until the user changes Monitor Port or changes Upload Port to a Serial Port.
If Upload Port is changed to a non-serial port value for OTA, then Monitor Port would remain unchanged at the last used Serial Port.

This would facilitate debugging of sketches which implement OTA updates as well as providing more convenient and faster firmware transfers without destroying Serial debugging capabilities.

**Comment by per1234** [comment]
Now tracked at https://github.com/arduino/arduino-ide/issues/583
