### ISSUE TITLE
[Library Manager] Please add libraries

### ISSUE THREAD

**Issue by obdevel** [arduino/Arduino#8918]
Please add the following:

https://github.com/obdevel/CBUS
https://github.com/obdevel/CBUS2515
https://github.com/obdevel/CBUSconfig
https://github.com/obdevel/CBUSLED
https://github.com/obdevel/CBUSswitch

Thank you

**Comment by per1234** [comment]
In each of those repositories, you need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by obdevel** [comment]
I've now corrected this and created a 1.0.0 release for each library. Thank you.

**Comment by cmaglie** [comment]
done
