### ISSUE TITLE
EthernetClient operator==() to allow for comparison of clients. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#892]
This is [Issue 892](http://code.google.com/p/arduino/issues/detail?id=892) moved from a Google Code project.
Added by 2012-04-20T11:58:42.000Z by [Alberto....@gmail.com](http://code.google.com/u/114068981518814175934/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Ethernet

### Original description

**What change would like to see?**

In the EthernetClient is possible add a function for get the socket number?
Or if is not possible add a new function is possible expose the _sock variable to children classes?

**Why?**
Actualy if there are multiple connections open it is impossible know from wich client we are reciving data

Would this cause any incompatibilities with previous versions?
No.

In EthernetClient.cpp
uint8_t EthernetClient::getSocketNumber() {
	return _sock;
}

In In EthernetClient.h
uint8_t getSocketNumber ();

Thanks.

Alberto

**Comment by Chris--A** [comment]
The addition of `EthernetClient::operator==()` was added here: https://github.com/arduino/Arduino/commit/ca37de4ba4ecbdb941f14ac1fe7dd40f3008af75

This issue can be fully resolved with the addition of `EthernetClient::getSocketNumber()` proposed in this PR: https://github.com/arduino/Arduino/pull/3123 by @bigjohnson.

**Comment by bigjohnson** [comment]
Yes because bigjonson and Alberto are the same person...

**Comment by facchinm** [comment]
Solved by merging  c5f0815f2
