### ISSUE TITLE
Add numerical parsing functions from Stream to String as well [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#893]
This is [Issue 893](http://code.google.com/p/arduino/issues/detail?id=893) moved from a Google Code project.
Added by 2012-04-20T12:57:16.000Z by [tom.i...@gmail.com](http://code.google.com/u/102867599453860860098/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

The numeric parsing functions in Stream are useful, but they would be helpful in String as well.

**Comment by Chris--A** [comment]
Fixed.

The String library can deal with numbers.

**Comment by sandeepmistry** [comment]
Closing, as @Chris--A mentioned the String class has number conversion capabilities, including:

```c++
	long toInt(void) const;
	float toFloat(void) const;
```
