### ISSUE TITLE
[Library Manager] Adafruit_PixelDust

### ISSUE THREAD

**Issue by PaintYourDragon** [arduino/Arduino#8932]
https://github.com/adafruit/Adafruit_PixelDust

Thanks!

**Comment by cmaglie** [comment]
The library name is PixelDust or Sand?
I see that in `master` is `Adafruit PixelDust`, but in the `1.0.0` tag is `Adafruit Sand`.

I guess that the library has been renamed after tagging 1.0.0 and you want `Adafruit PixelDust`, so please:
- delete 1.0.0 tag
- redo the tag on current master

Please let me know when you're done so I can update the indexer.

**Comment by ladyada** [comment]
woops sorry! done now, 1.0.1 is Adafruit PixelDust

**Comment by ladyada** [comment]
![ezgif-1-247db949ce6f](https://user-images.githubusercontent.com/1214161/59170152-5b0d2500-8b0b-11e9-931f-c24047770dec.gif)

**Comment by cmaglie** [comment]
ok, done. Wow!
