### ISSUE TITLE
[Library Manager] Please add libraries ss_oled and BitBang_I2C

### ISSUE THREAD

**Issue by bitbank2** [arduino/Arduino#8935]
https://github.com/bitbank2/BitBang_I2C
https://github.com/bitbank2/ss_oled

**Comment by bitbank2** [comment]
Please add another Arduino library:
https://github.com/bitbank2/bb_hx1230

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file in your bb_hx1230 repository.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by bitbank2** [comment]
Added a release (thanks for the reminder)

**Comment by cmaglie** [comment]
done
