### ISSUE TITLE
Tab characters in keywords.txt cause IDE to throw exception [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#895]
This is [Issue 895](http://code.google.com/p/arduino/issues/detail?id=895) moved from a Google Code project.
Added by 2012-04-21T21:57:50.000Z by [n...@gammon.com.au](http://code.google.com/u/111479721553138312180/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

1. Edit a keywords.txt file in a library
2. Put a tab after a comment, eg. #<tab> whatever
3. Close and re-open the IDE

**What is the expected output? What do you see instead?**

First, once you have done that, a "#" symbol is now considered a keyword. That is, it is drawn in a different colour. That is not correct because a comment in the keywords.txt file should be just that: a comment.

Second, under certain circumstances, if you type a "#" at the start of the line in the IDE any text following the "#" suddenly disappears and the IDE throws a Java exception.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Version 1.0 and also 0022

Mac OS/X

Board: not relevant, this is an editing issue

**Please provide any additional information below.**

Screenshots and more information below:

http://arduino.cc/forum/index.php/topic,95903.html

http://arduino.cc/forum/index.php/topic,102326.html

Confirmed by another user who suggested the fix of changing tabs to spaces INSIDE COMMENTS in the keywords.txt file(s).

**Comment by Chris--A** [comment]
keywords.txt is entirely tab separated now. Just to ensure, I did a test:

I added the text below to my keywords.txt, and nothing happened. The IDE loaded up as normal.

```
#comment comment comment
#	comment comment comment
#comment comment comment
#		comment comment comment
#comment comment comment
#comment comment		co	mment
#comment comment comment
#co	mment comment comment
	#comment comment comment
#comment comment comment
		#comment comment comment
#comment comment comment
	#	comment comment comment
#comment comment comment
		#	comment comment comment
#comment comment comment
		#		comment comment comment
```

**Comment by ffissore** [comment]
:+1:
