### ISSUE TITLE
New Library - ESP32 EC reader and PH reader libraries from GreenPonik

### ISSUE THREAD

**Issue by MkLHX** [arduino/Arduino#8953]
Read the Issues section of the Contributing Rules at the "contributing guidelines" link above before submitting an issue report.

Ph Reader 
https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK

Ec Reader
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK

**Comment by cmaglie** [comment]
done
