### ISSUE TITLE
[Library Manager] Please add TM1638plus library

### ISSUE THREAD

**Issue by gavinlyonsrepo** [arduino/Arduino#8957]
Hi

Please add TM1638 library.

Source : https://github.com/gavinlyonsrepo/TM1638plus
Tag : https://github.com/gavinlyonsrepo/TM1638plus/releases/tag/1.0.0

Name : TM1638plus
Author: Gavin Lyons (me)
Title :TM1638plus is an Arduino library to control a TM1638 seven segment module,
Description :  Arduino library, It supports Push Buttons, LEDs, ASCII, Hexadecimal and text strings and the decimal point. Brightness control. Small optimized  Memory footprint.

Example program Memory footprint(tested on UNO):
Sketch uses 2454 bytes (7%) of program storage space. 
Global variables use 54 bytes (2%) of dynamic memory.

There already is a Tm1638 in library manger called (TM1638lite) but it lacks a number of key features.
Decimal point support , brightness control, and has a bloated memory footprint:
Sketch uses 3470 bytes (10%) of program storage space. Global variables use 163 bytes (7%) of dynamic memory. In addition the author is not maintaining project, does not respond to pull requests, issues or communication and has not updated in over a year.

Regards.

**Comment by cmaglie** [comment]
done
