### ISSUE TITLE
I would like to present a new library for Arduino containing PID controllers. Three different types of PID controllers: continuous, step, impulse. 12 additional control functions and three simulations of control loops. URL: https//github.com/KorneliusThomas/PIDcontrollersModular

### ISSUE THREAD

**Issue by KorneliusThomas** [arduino/Arduino#8961]
https://github.com/KorneliusThomas/PIDcontrollersModular

**Comment by KorneliusThomas** [comment]
I wait for comments.

**Comment by KorneliusThomas** [comment]
There is an error in library URL.
The right library URL is: https://github.com/KorneliusThomas/PIDcontrollersModular
[PIDArduinoControllersModular.pdf](https://github.com/arduino/Arduino/files/3274508/PIDArduinoControllersModular.pdf)

**Comment by per1234** [comment]
@KorneliusThomas did you want to request addition in the Arduino Library Manager index, or are you just advertising your library and asking for feedback?

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by KorneliusThomas** [comment]
I would like to add the library PIDcontrollersModular in the Arduino Library Manager.regardsKornelius

Sent from Yahoo Mail on Android 
 
  On Tue, 11 Jun 2019 at 4:34, per1234<notifications@github.com> wrote:   
@KorneliusThomas did you want to request addition in the Arduino Library Manager index, or are you just advertising your library and asking for feedback?

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by per1234** [comment]
There are a couple things you need to do before your library can be added to the Arduino Library Manager index:

1. Move the library out of the .7z file and delete the .7z file. Beyond needing to do this for Library Manager, it's doesn't make sense to put a library on GitHub inside a compressed file. GitHub automatically generates .zip files of the repository, which are accessible via the **Clone or Download > Download ZIP** button on the home page as well as for each release or tag. Having the library in a compressed file defeats all the great version control and collaborative features of Git and GitHub.
2. Make sure the library is in the root of the repository, not in a subfolder. This means the library.properties file should be in the root folder of the repository.
3. Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

**Comment by KorneliusThomas** [comment]
Hi,I have modified my repositoryaccording to your suggestions.Please check it.Is it correct now?
regardsKornelius

Sent from Yahoo Mail on Android 
 
  On Wed, 12 Jun 2019 at 13:53, per1234<notifications@github.com> wrote:   
There are a couple things you need to do before your library can be added to the Arduino Library Manager index:
   
   - Move the library out of the .7z file and delete the .7z file. Beyond needing to do this for Library Manager, it's doesn't make sense to put a library on GitHub inside a compressed file. GitHub automatically generates .zip files of the repository, which are accessible via the Clone or Download > Download ZIP button on the home page as well as for each release or tag. Having the library in a compressed file defeats all the great version control and collaborative features of Git and GitHub.
   - Make sure the library is in the root of the repository, not in a subfolder. This means the library.properties file should be in the root folder of the repository.
   - Create a release or tag that matches the version value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

**Comment by per1234** [comment]
No, it's not correct. The library must be in the root of the repository. Your repository currently has the library under the PIDcontrollersModular, which is not allowed. Please move the library up to the root of the repository and then either create a new tag/release or else redo the existing tag/release.

Once that's done, please reply here so we'll know we can proceed.

**Comment by KorneliusThomas** [comment]
Hi,I hope now is correct.regardsKornelius

Sent from Yahoo Mail on Android 
 
  On Thu, 13 Jun 2019 at 20:43, per1234<notifications@github.com> wrote:   
No, it's not correct. The library must be in the root of the repository. Your repository currently has the library under the PIDcontrollersModular, which is not allowed. Please move the library up to the root of the repository and then either create a new tag/release or else redo the existing tag/release.

Once that's done, please reply here so we'll know we can proceed.

**Comment by KorneliusThomas** [comment]
Hi,
since some time I try to adapt my library to Arduino standards.
We have exchanged few emails, but now the contact is broken.
Last time I have done few modification in the repository and send a
email to Arduino, but got no reply. Please inform me about the
status of my library.
regards 
Kornelius

**Comment by per1234** [comment]
It's fine now, that's why I removed the "Waiting for feedback" label.

One of the Arduino developers occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by KorneliusThomas** [comment]
ok. Thank you !regardsKornelius


Sent from Yahoo Mail on Android 
 
  On Thu, 20 Jun 2019 at 19:57, per1234<notifications@github.com> wrote:   
It's fine now, that's why I removed the "Waiting for feedback" label.

One of the Arduino developers occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
done

**Comment by KorneliusThomas** [comment]
Hi,
sorry, but I dont see my library in the Library Manager.
Please write me what is the state of this issue.
regards
Kornelius

**Comment by per1234** [comment]
It is in the Arduino Library Manager index:
![Clipboard01](https://user-images.githubusercontent.com/8572152/61178818-0138c880-a5ab-11e9-83b9-790cde1b05ab.png)

Please try this:

1. Open this link in your browser: http://downloads.arduino.cc/libraries/library_index.json
2. If you're using Firefox, click the "Raw Data" tab.
3. Wait for the file to load.
4. Press Ctrl + F.
5. Search the file for "PIDcontrollersModular".

Do you find an entry for "PIDcontrollersModular" in the file?

**Comment by KorneliusThomas** [comment]
Yes !
I see it. Hopfully it will have success.
I have tried to put into it all my life
experience as controller developer for Arduino users.Controllers I have writtren
were 
allready standard by a very big company and runs on many plants in the world.

Best regards
Kornelius
