### ISSUE TITLE
Arduino IDE no longer compiles on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by colinta** [arduino/Arduino#8974]
Very sad!  macOS no longer supports 32bit binaries.  I deleted my copy of Arduino IDE and reinstalled the latest version, and the error message is `.../avr/bin/avr-g++: bad CPU type in executable``

**Comment by facchinm** [comment]
@colinta , we are working on it, there will be a beta release with only 64 bits tools soon but not too soon (10.15 is still in dev preview)

**Comment by donev77** [comment]
1.9 beta works on Catalina, tested on nodemcu ESP-12E

**Comment by colinta** [comment]
Thank you all! I’ll download the beta, and test it out.

**Comment by per1234** [comment]
This isn't really about the Arduino IDE. It's about the toolchain. The ESP8266 core for Arduino uses a different toolchain, which apparently is 64 bit. That's great, but not relevant here because the ESP8266 core for Arduino is a 3rd party project.

If you use the beta build of the Arduino IDE to compile for one of the AVR boards like Arduino/Genuino Uno then you'll get the same "bad CPU type in executable" error.

**Comment by ttimpe** [comment]
Why is even still 32-Bit? 64-Bit has been standard for a decade.

**Comment by gvarisco** [comment]
@colinta hi! could you please give build 865 a try? You can download it from https://github.com/arduino/Arduino/pull/8976

**Comment by colinta** [comment]
In the latest macOS it won't let me open the app from an undientified developer, even if I override it in Security settings!  Could be a bug, there are quite a few bugs in this beta version of macOS 10.15.

**Comment by gvarisco** [comment]
@colinta could you please confirm that Gatekeeper is activated on your system? What is the output of `spctl --status`?

Indeed, we do not codesign that bundle at the moment, but in case it becomes mandatory we may have to change this behaviour and update our build scripts.

**Comment by colinta** [comment]
```
spctl --status
assessments enabled
...
sudo spctl --master-disable
```

And now I can run the IDE, so thanks for that heads up.  And my project compiled!  I had new errors that I didn't have in the prev IDE (around assigning `&PORTB` as a `uint8_t*` instead of `volatile uint8_t*`), but all good after that!  I haven't tried to actually flash my project yet; it's my keyboard and I want to test a quick blink project first.

**Comment by colinta** [comment]
In the interest of cleaning up, I'll close this issue, if I have more problems I'll let you know!  Thanks for all the help, and everyone's work on the Arduino IDE in general.

**Comment by gvarisco** [comment]
Thanks for the feedback. Still, we want it to be fully working with GateKeeper turned ON, thus we'll make sure everything works as expected and without hacks before GA ships. /cc @facchinm

**Comment by joztoz** [comment]
I still cant compile, still same bad cpu. tried all whats here mentioned and without success, please can you help me what I forgot install or disable/enable?
Thank you

**Comment by per1234** [comment]
@joztoz please post the full error message here, including the path.

**Comment by joztoz** [comment]
finally find a solution, I had to put avr files to /Users/jozefziak/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5

but had to do it manually. Now its working fine, I take avr files from arduino 865 package :)

**Comment by jakorten** [comment]
@joztoz: works really well indeed. In your console you can see one's one entire folder. I had to remove (archive) the older version though.

**Comment by CallmeSk** [comment]
Same here 'bad cpu type error' while programming NodeMCUESP82466 with macOS Catalina.

**Comment by JoenneSpreuwers** [comment]
https://youtu.be/xv1e6ZOBVfA <-- quick solve ;)
