### ISSUE TITLE
w5200 library code [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#898]
This is [Issue 898](http://code.google.com/p/arduino/issues/detail?id=898) moved from a Google Code project.
Added by 2012-04-24T14:01:19.000Z by [t...@prolectron.com](http://code.google.com/u/100426908544959980659/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Replace the current ethernet shield w5100.h and w5100.cpp files with the files attached.

Why? By removing the comment slashes on "#define W5200" in w5100.h will compile for a w5200 shield.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

None detected so far.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#18
