### ISSUE TITLE
ESPRESSIF ESP Development Board WIFi Cache Cannot Clear

### ISSUE THREAD

**Issue by mxlbb** [arduino/Arduino#8982]
The cache cannot be cleared using Scan Network and Smart Distribution Network in the Arduino sample project.
Performance: If you use these two features before the wireless LAN is not connected, then WiFi multiple scans will be the same result. The scan result is cleared only after rebooting or connecting to the wireless network again.
This bug has not been debugged with the ESPRESSIF development tool.
I hope to solve it as soon as possible, thank you!

**Comment by per1234** [comment]
The ESP8266 core for Arduino is a 3rd party project. Arduino's issue trackers are only to be used to report bugs or make feature requests for Arduino's own projects.

**Comment by mxlbb** [comment]
Who should I look for?
