### ISSUE TITLE
[Library Manager] Please add SimpleRotary

### ISSUE THREAD

**Issue by mprograms** [arduino/Arduino#8992]
SimpleRotary is a Arduino library for using basic bare-bones type rotary encoders. Usually these are the cheap ones without the breakout board.

Supports 
- Getting rotary encoder rotation direction.
 - Getting rotary select button press.
 - Getting rotary select button long press.
 - Getting rotary select button press time.
 - Basic debouncing of rotary / button.
 - Basic error correcting of out-of-sync rotational readings.
 - Use of both high and low triggers.

https://github.com/mprograms/SimpleRotary

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by mprograms** [comment]
All done.

**Comment by cmaglie** [comment]
done
