### ISSUE TITLE
Rfid 

### ISSUE THREAD

**Issue by retb** [arduino/Arduino#8999]
#include <SPI.h>
#include <MFRC522.h>
#include <Servo.h>
 Servo myservo;  
int potpin = 0;  
int val;
#define SS_PIN 10
#define RST_PIN 9
MFRC522 mfrc522(SS_PIN, RST_PIN);   

void setup() {
  Serial.begin(115200);
  SPI.begin();
  mfrc522.PCD_Init();
  Serial.println("Arduino RFID lock");
  Serial.println("");
  pinMode(LED1,OUTPUT);
   pinMode(LED2,OUTPUT);
  myservo.attach(3);
  myservo.write( 0 );
}

void loop(){
   val = analogRead(potpin); 
  if ( !mfrc522.PICC_IsNewCardPresent() ){
    return;
  }
  if ( !mfrc522.PICC_ReadCardSerial() ) {
    return;
  }
  
  String content= "";
  byte letter;
  for( byte i = 0; i < mfrc522.uid.size; i++ ){
     content.concat(String(mfrc522.uid.uidByte[i], HEX));
     if( i < mfrc522.uid.size-1 ) content+="-";
  }
  content.toUpperCase();
 Serial.println();
  Serial.println("UID tag :'" + content + "'");
  Serial.print(content);
  if( content== "55-33-2C-83")
       val = map(val, 0, 1023, 0, 150);     
  else if( content=="91-2B-D2-2F")
   
      val = map  (val, 0, 1023, 0, 60);

   myservo.write(val);                  
  delay(15); 
  }
          This is my code .i want to do my servo to rotate 0to180 when rfid scan specific tag.and rotate 0 to 60 when scan another tag.
        But the issue is .i want to change the servo pos when rfid scan once .
          The above program runs when the rfid scan the tag after removing it didn't work. Pls help by providing some codes.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This is not an appropriate place to request assistance with your project. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
