### ISSUE TITLE
[Library Manager] Please add FourteenSegDisplay library

### ISSUE THREAD

**Issue by gavinlyonsrepo** [arduino/Arduino#9003]
Hi ,

Please add "FourteenSegDisplay" library.

Source: https://github.com/gavinlyonsrepo/FourteenSegDisplay

Tag: https://github.com/gavinlyonsrepo/FourteenSegDisplay/releases/tag/1.0.0

Name: FourteenSegDisplay

Description:
 
1. An Arduino library to display data on a 14 segment alphanumeric LED display module. 
2. It requires two Daisy chained shift registers. 
3. The module was tested on a two digit LDD-F5406RI common cathode module. 
4. Library is also designed to work with common anode. 
5. Library includes ASCII font, also supports Hexadecimal input and Decimal point function. 
6. Optimized low memory footprint. 
7. It also provides a function for manually setting segments to any user defined pattern. 
8. It requires (3+N) Digital GPIO pins, where N is number of digits used.
    
Author: Gavin Lyons.
Development platform: Arduino NANO

Regards
Gavin Lyons

**Comment by cmaglie** [comment]
done
