### ISSUE TITLE
[Library Manager] New library for easy RGB LED control

### ISSUE THREAD

**Issue by alexbertis** [arduino/Arduino#9006]
Hi! I have created a library to simplify RGB LED control in Arduino. 
Please review and add my library to the list, in the category "Device Control". 
Thanks in advance.

The library repository URL: https://github.com/alexbertis/LibreriaLedRGB
The release URL: https://github.com/alexbertis/LibreriaLedRGB/releases/tag/1.0.0

**Comment by cmaglie** [comment]
done
