### ISSUE TITLE
[Library Manager] Please add Grove 6Axis_Digital_Accelerometer_Gyroscope4_ADIS16470 v1.0.0 to Library Manager

### ISSUE THREAD

**Issue by Jenkinlu001** [arduino/Arduino#9016]
Github:https://github.com/Seeed-Studio/Seeed_ADIS16470
Release:https://github.com/Seeed-Studio/Seeed_ADIS16470/releases/tag/v1.0.0

Thanks

**Comment by cmaglie** [comment]
done
