### ISSUE TITLE
Reinstallation error

### ISSUE THREAD

**Issue by adhiboy6007** [arduino/Arduino#9028]
Read the Issues section of the Contributing Rules at the "contributing guidelines" link above before submitting an issue report.
I had downloaded installed arduino in 2018.But when i try to install the newer version of the id it shows to unistall files in the old directery before installing the new on i had deleted them but i was unable to solve the issue pls help

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
