### ISSUE TITLE
[Library Manager] Add serde to Library Manager

### ISSUE THREAD

**Issue by franky47** [arduino/Arduino#9032]
Hello, I have developed a small, headers-only template library for serializing / deserializing structured data and send / receive it across Serial-compatible interfaces (HardwareSerial, SoftwareSerial, I2C, SPI etc..).

The source code is available here for review:
https://github.com/FortySevenEffects/serde

**Comment by cmaglie** [comment]
done

**Comment by franky47** [comment]
Thanks !
