### ISSUE TITLE
Please add luciansabo/GP2YDustSensor to the Library Manager

### ISSUE THREAD

**Issue by luciansabo** [arduino/Arduino#9045]
https://github.com/luciansabo/GP2YDustSensor

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by luciansabo** [comment]
Done:
https://github.com/luciansabo/GP2YDustSensor/releases/tag/v1.0.0

**Comment by cmaglie** [comment]
done
