### ISSUE TITLE
Website Documentation Error: "Setting up an Arduino on a Breadboard" page

### ISSUE THREAD

**Issue by gulloj** [arduino/Arduino#9049]
The image and text showing the orientation of the AVR programming header is backwards on the following page:   https://www.arduino.cc/en/Main/Standalone

The text says INCORRECTLY, "This image is a view from the bottom and labels each of the holes. Take note of the square as to what orientation your cable is in."  The text should say, "this image is a view from the top of (looking down on) the installed header in the PCB".  

I tried for a couple hours to make it work the way it was described in this instructional page.  I decided to try swapping the orientation of the signals in the connector and it worked immediately.

I'm using a custom PCB modeled after the Arduino Uno, using the ATMEGA328P, the AVRISP mkII programmer, and AtmelStudio 7.0.1931.

**Comment by per1234** [comment]
Thanks for reporting this error @gulloj! It seems this tutorial has been completely removed from Arduino's website so I'll close this as resolved.

For future reference, here is the archived copy on the archive.org Wayback Machine:

https://web.archive.org/web/20220201170335/https://www.arduino.cc/en/Main/Standalone
