### ISSUE TITLE
odd pointer in verify [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#905]
This is [Issue 905](http://code.google.com/p/arduino/issues/detail?id=905) moved from a Google Code project.
Added by 2012-05-04T19:50:02.000Z by [revots...@gmail.com](http://code.google.com/u/101139494515064142290/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

In writing a source I had defined several functions, later to find alternative implementations that were more effective. Having written the out the bulk of the code and then amended it to reflect these changes I went to compile. Upon compilation I received an error stating " too many arguments to function x." The compiler pointed me to a prototype, which had been changed appropriately. The actual fault was deep in the code where I had missed a call to the function which still had the old input arguments.

//prototype
int function1();     //<<<<<< this is highlighted

//main body
loop{
   ..........
   function1(x);     //<<<<<<<this is the actual fault

I would expect the actual fault to be highlighted. I managed to find the fault quickly, knowing my own changes to the code, though I would imagine people new to C may find this confusing. Especially so if such an error occurred on accident rather than from leftover code.

Arduino 1.0 on windows 7

**Comment by per1234** [comment]
I can reproduce this issue with Arduino IDE 1.0.3 but it does not occur on Arduino IDE 1.8.3 so the bug has been fixed already.
