### ISSUE TITLE
Please Add the SparkFun Qwiic RFID Arduino Library to the Library Manager

### ISSUE THREAD

**Issue by edspark** [arduino/Arduino#9050]
Hello, please add [SparkFun's Qwiic RFID Arduino](https://github.com/sparkfun/SparkFun_Qwiic_RFID_Arduino_Library) library to the library manager at your earliest convenience!

Thanks!

**Comment by per1234** [comment]
Hi. I get a 404 error from that URL. Is the repository maybe still set to private?

**Comment by edspark** [comment]
So sorry about that! It's now public...

**Comment by edspark** [comment]
Just pinging again in case my comment got lost in the shuffle @per1234 =).

**Comment by per1234** [comment]
Thanks! I have removed the "Waiting for feedback" label and so your request is now on track to be added with the next batch of libraries.

**Comment by cmaglie** [comment]
done
