### ISSUE TITLE
[Library Manager] Please add, MCP45HVX1, AT24CM01 and TCA9548A

### ISSUE THREAD

**Issue by WifWaf** [arduino/Arduino#9064]
Hey chaps,

Could you please add three libraries to the Library Manager (not sure if I need a separate issue for each)?

https://github.com/WifWaf/TCA9548A
https://github.com/WifWaf/MCP45HVX1
https://github.com/WifWaf/AT24CM01

Hopefully no errors...
Many thanks,

**Comment by cmaglie** [comment]
done
