### ISSUE TITLE
[Library Manager] Please add CoopTask - portable ESPxx/Arduino cooperative multitasking library

### ISSUE THREAD

**Issue by dok-net** [arduino/Arduino#9069]
URL: https://github.com/dok-net/CoopTask
This multitasking library offers cross-platform, cooperative single-threaded multitasking, similar to Arduino Scheduler, but in pure C++.
It works on the ESP8266 and ESP32 SOCs, as well as the Arduino Pro / Pro Mini (and probably the other Arduino boards, too).
In the current release 0.8.0 it is completely usable, areas of improvement are building a scheduler that cyclically runs the tasks, currently, this is done in loop() by lining up the run() calls for all tasks one by one, which is fine.

**Comment by cmaglie** [comment]
done
