### ISSUE TITLE
Question Regarding Abandoned Library

### ISSUE THREAD

**Issue by ameer1234567890** [arduino/Arduino#9072]
I have more of a question than an issue. What if a certain listed library seems to be abandoned by the author (no author activity for 2 years even after pull requests and issues being raised)? Is there a mechanism to remove the said library in favor of a new library with the same name, with bug fixes, new features, etc? Or rather, is a new library permissible under a name such as `Library2`? What is the best option for me, provided I am willing to maintain a new library with the said improvements?

**Comment by per1234** [comment]
Fork the library and give it a unique name. That's the best thing to do when you create a "hard fork" to prevent confusion.

I don't think Arduino wants to be in the position of deciding what is worthy of being in the Arduino Library Manager index. If a library author requests a library be added, we add it. If a library author requests their library be removed, we remove it. Anything beyond that is too much work for us.
