### ISSUE TITLE
[Library Manager] TFL-Status Library

### ISSUE THREAD

**Issue by dushyantahuja** [arduino/Arduino#9073]
Please add the following library:

https://github.com/dushyantahuja/TFL-Status

Thanks

**Comment by per1234** [comment]
Hi. I believe the lack of a `maintainer` field in your library.properties file will block admission of your library into the Library Manager index.

I submitted a pull request to resolve this issue: https://github.com/dushyantahuja/TFL-Status/pull/1

Please add this field and then either create a new tag/release or else redo the existing release.

Once that's done, please comment here so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by dushyantahuja** [comment]
Thanks a lot. I have updated the tag

**Comment by dushyantahuja** [comment]
Can you please add now.

**Comment by matthijskooijman** [comment]
Library manager updates are done periodically in bigger batches, so it might be a few more days or weeks until this is done.

**Comment by dushyantahuja** [comment]
Thanks a lot

**Comment by cmaglie** [comment]
done
