### ISSUE TITLE
Add SparkFun's Ambient Light Sensor Arduino Library to Library Manager

### ISSUE THREAD

**Issue by edspark** [arduino/Arduino#9079]
Happy Thursday,

At your earliest convenience can you add SparkFun's latest Arduino Library: [SparkFun Ambient Light Sensor Arduino Library](https://github.com/sparkfun/SparkFun_Ambient_Light_Sensor_Arduino_Library) to the library manager? 

Thanks!

**Comment by cmaglie** [comment]
done
