### ISSUE TITLE
[Library Manager] Please change name of Step_CYC10_Seven_Seg_DisplayCYC10_7_seg_display library

### ISSUE THREAD

**Issue by PulseRainmaker** [arduino/Arduino#9080]
Sorry for the inconvenience. There was a typo in the library.properties for 

https://github.com/PulseRain/Step_CYC10_Seven_Seg_Display

The initial library name is

Step_CYC10_Seven_Seg_DisplayCYC10_7_seg_display

But it should be

Step_CYC10_Seven_Seg_Display

I have fixed it in the GitHub with version 1.0.5, but it seems the library manager does not pick it up.  Could you please also change the name for me in the Library Manager?

Thanks a lot!
PulseRainmaker

**Comment by cmaglie** [comment]
done
