### ISSUE TITLE
Add SparkFun's MCP9600 Thermocouple Amplifier Arduino Library to Library Manager

### ISSUE THREAD

**Issue by FischerMoseley** [arduino/Arduino#9091]
Hello!

At your earliest convenience can you add the [SparkFun MCP9600 Arduino Library](https://github.com/sparkfun/SparkFun_MCP9600_Arduino_Library) to the library manager?

Thank you!

**Comment by FischerMoseley** [comment]
Bump!

**Comment by cmaglie** [comment]
done
