### ISSUE TITLE
[Library Manager] Adafruit fork of SdFat

### ISSUE THREAD

**Issue by ladyada** [arduino/Arduino#9092]
please add to library manager - thanx!
https://github.com/adafruit/SdFat

**Comment by per1234** [comment]
Hi. The characters `(` and `)` used in the library.properties `name` field are not allowed.

From the Arduino Library Specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format
>**name** - the name of the library. Library names must contain only basic letters (A-Z or a-z) and numbers (0-9), spaces ( ), underscores (_), dots (.) and dashes (-). It cannot start or end with a space, and also it cannot start with a number.

Please change the `name` value to something that doesn't use any disallowed characters and then either create a new release or else redo the existing release. Once that is done, please comment here so we'll know we can proceed.

**Comment by ladyada** [comment]
ahh sorry! fixed now and bumped to 1.2.1 :)

**Comment by cmaglie** [comment]
done
