### ISSUE TITLE
[Library Manager] Please Add Library : Library for GoGoBoard 

### ISSUE THREAD

**Issue by thapakorn613** [arduino/Arduino#9095]
Hello , Please add the following library to the Library Manager index:
.
https://github.com/thapakorn613/GoGoBoard-Library
.
Thanks

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by thapakorn613** [comment]
i made it , Please add my library again 
.
Thanks

**Comment by cmaglie** [comment]
done

**Comment by njh** [comment]
Hi @thapakorn613, it looks like you have deleted this library from Github.
Would you mind letting me know why?
