### ISSUE TITLE
mma7455

### ISSUE THREAD

**Issue by Nuan0523** [arduino/Arduino#9108]
Hello, I tried to use mma7455 vibration sensor which connected with UNO wifi rev2 to detect the vibration but the result always 0 , and error =1.   
My vision is 1.8.9 and the code is from
  https://playground.arduino.cc/Main/MMA7455/

Could u tell me what the problem is?  Thanks

Regards,
Nuan

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests.  This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
