### ISSUE TITLE
[Library Manager] Add ArdUAV library to Arduino Library Manager

### ISSUE THREAD

**Issue by PowerBroker2** [arduino/Arduino#9109]
Please add https://github.com/PowerBroker2/ArdUAV to the Arduino Library Manager.

**Comment by cmaglie** [comment]
done

**Comment by njh** [comment]
@PowerBroker2 it looks like this repo has now been deleted - do you have any information about why? Thanks!

**Comment by TheSkyfred** [comment]
Do you guys have a backup of this library ?
