### ISSUE TITLE
[Library Manager] Please add BackSeatDriver library

### ISSUE THREAD

**Issue by kigster** [arduino/Arduino#9110]
## Back Seat Driver

[Back Seat Driver](https://github.com/kigster/back-seat-driver) is a simple library that provides motion control semantics that are decoupled from the type of motor being used. It's a non-blocking library that with just a few callbacks can help you build robots that appear a lot smarter than they actually are, and always impress witnesses with their obstacle avoidance capabilities.

While *obstacle avoidance* is not the purpose of this library, it's a concept that's very closely related, and in fact — both examples in the library show a form of obstacle avoidance.

Below are some of the images of obstacle avoiding robots I've built that ran on this library. 

Despite using two different engine types, the same library can be used to drive either bot equally well.

#### Servo Motor Bot 

![Servo Bot](https://raw.githubusercontent.com/kigster/back-seat-driver/master/img/bot_servo.jpg)

#### DC Motors Bot 

![DC Bot](https://github.com/kigster/back-seat-driver/raw/master/img/bot_dc.jpg)

Please let me know what should I do to get this library added to the official list!

**Comment by cmaglie** [comment]
done
