### ISSUE TITLE
Is there a way of emulating mass storage with an arduino also how do I set my boards manufacturer

### ISSUE THREAD

**Issue by kai9987kai** [arduino/Arduino#9111]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide all the information that will be needed to help you, including which board you're using.
