### ISSUE TITLE
[Library Manager] Please add RV-3028-C7 library

### ISSUE THREAD

**Issue by constiko** [arduino/Arduino#9119]
Could you please add this library to the Library Manager?

https://github.com/constiko/RV-3028_C7-Arduino_Library

It's a library to communicate with the RV-3028-C7 Real Time Clock from MicroCrystal Switzerland.
Thanks!

**Comment by cmaglie** [comment]
done, sorry for the delay!

**Comment by constiko** [comment]
Thanks, no problem :)
