### ISSUE TITLE
Please add PaunaStepper Arduino Timer based Library for 28BYJ-48 motor with ULN2003 driver

### ISSUE THREAD

**Issue by kbernario** [arduino/Arduino#9125]
Dear Arduino Staff, please add PaunaStepper Library for Arduino Library.

PaunaStepper is a library for use with hobby stepper motors. It is mainly oriented to low-cost stepper such as model 28BYJ-48 5v with ULN2003 driver. The main feature that differentiates this library from similar ones is that it uses interrupts to control the steppers and can control more than one stepper in a similar way to the Servo library. This allows, for example, to control the speed and direction of the steppers at the same time as the delay () functions and serial communication without the need to constantly call an update function or use the blocking mode.

The library supports blocking and non-blocking moves, direct micro-step control, rpm settings, degrees based moves, absolute and relative moves, and multiple motors control. It comes with 4 example sketches.

Repository:
https://github.com/kbernario/PaunaStepper

Release (tag v0.0.1):
[https://github.com/kbernario/PaunaStepper/releases](https://github.com/kbernario/PaunaStepper/releases)

Thanks!

**Comment by cmaglie** [comment]
done
