### ISSUE TITLE
[Library Manager] Add uMuxOutputLib to Library Manager

### ISSUE THREAD

**Issue by Naguissa** [arduino/Arduino#9128]
Hello,

Following Library Manager FAQ I open this issue to request adding uMuxOutputLib library to Arduino repository.

Repository URL is: https://github.com/Naguissa/uMuxOutputLib

It's a simple and convenient library to multiplex outputs and be able to control a lot of elements with minimum pin requirements. One example could be controlling 100 LEDs using only 20 pins.

Thanks.

**Comment by cmaglie** [comment]
done

**Comment by Naguissa** [comment]
Thanks!
