### ISSUE TITLE
Command Line Does Not Work On Windows

### ISSUE THREAD

**Issue by weswitt** [arduino/Arduino#9132]
Using the IDE's command line interface for compiling a sketch seems to behave differently on Windows vs. Linux.

On Linux this works perfectly: "/arduino-1.8.8/arduino --board esp8266com:esp8266:d1 --pref build.path=./bin --verify ./test.ino

On Windows the equivalent does not work: "arduino.exe --board esp8266com:esp8266:d1 --pref build.path=c:\test\bin --verify c:\test\test.ino"

On Linux I receive output in the terminal window and the sketch is compiled. On Windows there is now output in the cmd window and the splash screen for the IDE is displayed. No code is compiled and no error output of any kind is provided.

Is this a bug or is this simply not expected to work on Windows?

**Comment by per1234** [comment]
From the Arduino IDE's CLI documentation:
https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc#description
>Note that on Windows, due to the diffence between GUI and console apps, that the arduino_debug.exe is the appropriate executable to use if you want to use the majority of these command line options. The arduino.exe GUI version of the launcher may perform some of the functions described below, but will not output any messages to the console, meaning it is pretty useless if you want any feedback or to be able to keep log files for automated testing, etc.
