### ISSUE TITLE
[Library Manager] GeneralPurposeMotionDetector

### ISSUE THREAD

**Issue by jcpicard32** [arduino/Arduino#9134]
Please add this library. https://github.com/graybiel-laboratory/GeneralPurposeMotionDetector

Thank you in advance for your help :).

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem:

```
JOB 2423 - 2019/08/21 09:31:10 Scraping https://github.com/graybiel-laboratory/GeneralPurposeMotionDetector.git
JOB 2423 - 2019/08/21 09:31:11 Checking out tag: 1.0.0
JOB 2423 - 2019/08/21 09:31:11 Error syncing library: .development file found, skipping
```

this file is intended to be there during development but not to be commited on git.
To fix this:

1) delete the tag `1.0.0`
2) remove `.development` file
3) commit & push
4) re-create the tag `1.0.0` on `master` branch

once done the libraries indexer should pick up the library automatically within an hour.
