### ISSUE TITLE
[Library Manager] Request to add BCL library

### ISSUE THREAD

**Issue by sleepdefic1t** [arduino/Arduino#9139]
Please add BCL to the Library Manager.

BCL
> A fork of Nayukis Bitcoin Cryptography Library. This project implements the cryptographic primitives used in the Bitcoin system, especially elliptic curve operations and hash functions. This fork adds extra package and testing functionality.

https://github.com/sleepdefic1t/bcl
https://github.com/sleepdefic1t/bcl/releases/tag/0.0.3

Thank you!!

**Comment by cmaglie** [comment]
done
