### ISSUE TITLE
 Library Manager additions: MQSensor lib An unified mq library

### ISSUE THREAD

**Issue by miguel5612** [arduino/Arduino#9146]
Please, add the MQSensorsLib library to the Arduino Library Manager. Here is the library repository:

Library URL: https://github.com/miguel5612/MQSensorsLib

Thank you!

**Comment by miguel5612** [comment]
Morning,
I made the requested correction in the branch adding now that the architecture is only AVR, thank you very much :)

**Comment by cmaglie** [comment]
done

**Comment by miguel5612** [comment]
Thanks :)
