### ISSUE TITLE
[Library Manager] Please add Kalman filter library to the library manager

### ISSUE THREAD

**Issue by rfetick** [arduino/Arduino#9172]
Hi dear developers,

I have created a Kalman filter library for Arduino and wonder if you see interest in including it in the IDE library manager.
The motivation for this library is its versatility. Indeed the current arduino Kalman filter libraries I have seen are often one-dimensional or limited to some specific cases.
However the library I developed implements the full Kalman matrix equations, and is based on the already existing "BasicLinearAlgebra" arduino library.
This might be useful for most advanced projects and complementary from the already existing Kalman filter libraries.

The project and its documentation are available at my [github/rfetick/Kalman](https://github.com/rfetick/Kalman)

Kind regards :)

**Comment by cmaglie** [comment]
done, sorry for the long delay.
