### ISSUE TITLE
[Library Manager] Please add the EnergyMeter library

### ISSUE THREAD

**Issue by elC0mpa** [arduino/Arduino#9178]
I have created an EnergyMeter library for Arduino and wonder if you see could include it in the IDE library manager.
This library is used to monitor energy meters. It uses callbacks to trigger actions each time the meter measures a certain kind of kilowatts-hour. By using this library, energy meters can be polled (less efficient approach) or can be interfaced through external interrupts (most efficient approach).

The project and its documentation are available at https://github.com/elC0mpa/EnergyMeter

Regards :)

**Comment by elC0mpa** [comment]
Hello @per1234, I would like to know if everything is right because i have been waiting for you to add my library since five days. I thought maybe the .properties file was wrong. Please answer me, I would like to know your opinion

**Comment by per1234** [comment]
Everything is fine now.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
done, sorry for the long delay.
