### ISSUE TITLE
[Library Manager] Please add Waveshare_ILI9486

### ISSUE THREAD

**Issue by ImpulseAdventure** [arduino/Arduino#9179]
Hi --

I would like to submit the [Waveshare_ILI9486](https://github.com/ImpulseAdventure/Waveshare_ILI9486) library for inclusion in the Arduino IDE Library Manager.

This library implements a GFX-style API supporting the **Waveshare Touch Shield for Arduino** (3.5" and 4" ILI9486 SPI display driver). Thank you.

**Comment by cmaglie** [comment]
done, sorry for the long delay.
