### ISSUE TITLE
[Library Manager] Please add *LSS_Library_Arduino* to the Library Manager

### ISSUE THREAD

**Issue by rbscharette** [arduino/Arduino#9181]
Hi,

I open this issue to have the *LSS_Library_Arduino* added to the Library Manager.
As far as I can tell it should be up to par with requirements for libraries 1.5 (rev 2.1).

The library can be found here: https://github.com/Lynxmotion/LSS_Library_Arduino with releases (tags) here: https://github.com/Lynxmotion/LSS_Library_Arduino/releases

Please let me know if there is anything else I need to do.

Sincerely,

**Comment by rbscharette** [comment]
Oh my. I totally missed the most obvious, huh?
[Name](https://github.com/Lynxmotion/LSS_Library_Arduino/blob/master/library.properties#L1) was updated to "Lynxmotion Smart Servo -LSS-".

Please let me know if there is anything else and thank you for your assistance!

**Comment by cmaglie** [comment]
done, sorry for the long delay.
