### ISSUE TITLE
[Library Manager] Please add "QMC5883LCompass" library to Library manager Arduino IDE.

### ISSUE THREAD

**Issue by mprograms** [arduino/Arduino#9186]
Please add QMC5883LCompass
https://github.com/mprograms/QMC5883LCompass

QMC5883LCompass is a Arduino library for using QMC5583L series chip boards as a compass.

Supports:

- Getting values of XYZ axis.
- Calculating Azimuth.
- Getting 16 point Azimuth bearing direction (0 - 15).
- Getting 16 point Azimuth bearing Names (N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW, W, WNW, NW, NNW)
- Smoothing of XYZ readings via rolling averaging and min / max removal.
- Optional chipset modes

**Comment by cmaglie** [comment]
done, sorry for the long delay.
