### ISSUE TITLE
Download errors

### ISSUE THREAD

**Issue by orvillew** [arduino/Arduino#9187]
The linux64 java./bin directory files seem to be corrupt.   They are reporter as binary and abort.
I am hoping this problem will be corrected.
      Thank you
      worich@windstream.net

**Comment by per1234** [comment]
Which download URL are you using to get the files?

**Comment by orvillew** [comment]
https://www.arduino.cc/en/Main/Donate
arduino-1.8.9-linux64.tar.xz
  this is the URL and the item downloaded.h
  the item w as downloaded, uncompressed and installed.  The resulting problem was traced to
   the java/bin subdirectory.  There could be other problems but I would have to resolve this before
  I could troubleshoot more deeply.
