### ISSUE TITLE
WIN Latest nightly build (2019/08/27 05:33): Compile not possible

### ISSUE THREAD

**Issue by harryboo** [arduino/Arduino#9189]
With the latest nightly build it is not possible to compile an example if this is set in the preferences:

compiler.cache_core=false

Error msg:
german-Das System kann den angegebenen Pfad nicht finden.
english-The system cannot find the specified path.

If i set this option to TRUE the compilation is possible.

**Comment by facchinm** [comment]
Related to `arduino-cli-inception` switch. Mabe fixed by https://github.com/arduino/arduino-builder/commit/bc2846ea5d02cddcd67cebb9261583fddc10fd91 and https://github.com/arduino/arduino-cli/pull/367but we must check with @cmaglie .
Thanks for reporting!
