### ISSUE TITLE
Offer last 7 used boards in selection menu

### ISSUE THREAD

**Issue by Harvie** [arduino/Arduino#9197]
i have several cores installed (Arduino, ESP32, ESP2866, STM32, Digispark, ....) Which means i have like 200+ boards in the menu and scrolling is slow and annoying. Most of the time i use just few of the offered boards, but the switching between them is slow because i have to scroll all the way every time.

Can you please add 7 most recently used boards and offer them immediately on top when i click on the board selection menu? (i've intentionaly chosed 7 items as UX rule of thumb for what brain can easily handle without geting cognitive overload)

![image](https://user-images.githubusercontent.com/276504/64349881-012bd680-cff8-11e9-9fd1-382d87067624.png)

**Comment by per1234** [comment]
Already done: https://github.com/arduino/Arduino/pull/8607

You can try the beta build of the Arduino IDE if you want to test it out:
https://www.arduino.cc/en/Main/Software#beta
