### ISSUE TITLE
New library

### ISSUE THREAD

**Issue by offcircuit** [arduino/Arduino#9199]
Hi,

Can I add a  library?

https://github.com/offcircuit/GPS

Thanks,
Helder Rodrigues

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by offcircuit** [comment]
Hi again,

Done,

:)
Helder Rodrigues

**Comment by offcircuit** [comment]
... now ...

**Comment by per1234** [comment]
@offcircuit I notice you closed this issue. Did you decide that you didn't want your library added to the Arduino Library Manager index after all?

**Comment by offcircuit** [comment]
hi again,

I will take abetter look at this class

Thanks,
Helder Rodrigues

**Comment by offcircuit** [comment]
Hi again,

I made some changes on the lib.

Now it is good to publish,
https://github.com/offcircuit/GPS

Thanks,
Helder Rodrigues

**Comment by cmaglie** [comment]
done
