### ISSUE TITLE
⌘-key shortcuts don't work in "Dvorak - Qwerty ⌘" Mac keyboard layout [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#920]
This is [Issue 920](http://code.google.com/p/arduino/issues/detail?id=920) moved from a Google Code project.
Added by 2012-05-25T11:04:52.000Z by [br...@semi-sentient.com](http://code.google.com/u/105002915115963821284/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, OpSys-OSX, Component-IDE

### Original description

On the Mac, there are multiple keyboard layouts for the Dvorak keyboard.  The one that I use switches back to the Qwerty layout when using the ⌘ (Command) key (partially for people who are used to those keyboard shortcuts, and partially because they're laid out well on the keyboard).  I'm sure this is low on your priority list, but it frustrates me whenever I try to use the Arduino IDE (and the Processing IDE too)

Steps to reproduce:
1. Set "Dvorak - Qwerty ⌘" keyboard layout in Mac (Under "System Preferences" -> "Language & Text" -> "Input Sources" Tab)
2. Try to copy/paste with ⌘-C and ⌘-V (end up showing sketch folder because the Qwerty K key is where the Dvorak V key is)
3. Be annoyed every time ;)

Using Arduino 1.0 on Mac OS 10.7.4.  Board is an Arduino Uno if that makes any difference.

**Comment by ffissore** [comment]
Too old and no one gave it love
