### ISSUE TITLE
[Library Manager] Please add STM32F1_RTC library

### ISSUE THREAD

**Issue by ZulNs** [arduino/Arduino#9201]
Could you please add the STM32F1_RTC library?

[Source](https://github.com/ZulNs/STM32F1_RTC)
[Tag](https://github.com/ZulNs/STM32F1_RTC/releases/tag/v1.0.0)

Description:
Allows to use the RTC functionalities of STM32F1xx based boards using external low speed oscillator. This library can be used in the STM32 Cores by STMicroelectronics as well as in the libmaple version of Arduino STM32 by Roger Clark development boards. With this library you can use the RTC device to program actions related to date and time. This library offers Islamic Hijri calendar calculations in addition to the Christian (Gregorian) calendar. Day, month, hour, minute and second parameters can be supplied with values that exceed their respective limits or supplied with negative values. Other parameters will be adjusted accordingly.

**Comment by cmaglie** [comment]
done
