### ISSUE TITLE
[Library Manager] Remove a library and add a new one.

### ISSUE THREAD

**Issue by jaean123** [arduino/Arduino#9203]
I would like to remove this library from the library manager.
https://www.arduinolibraries.info/libraries/snappy-xo-precise-movement-library

And add this library. Although the name is the same, it's a completely new but similar library. 
https://github.com/purwar2016/PreciseMovement-library

Thank you for your time.

**Comment by cmaglie** [comment]
I've added the library from @purwar2016 repository,

BTW I don't understand which library you want to remove. The library added is named `PreMo - Virtual Path Following` and there are no other libraries with the same name. Also the link you posted is broken...

**Comment by jaean123** [comment]
@cmaglie. It looks like it's resolved now. Thanks.
