### ISSUE TITLE
[Library Manager] Please add AliyunIoTSDK library

### ISSUE THREAD

**Issue by xinyu198736** [arduino/Arduino#9205]
https://github.com/xinyu198736/arduino-aliyun-iot-sdk

thanks, this is a aliyun iot library

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by xinyu198736** [comment]
i have create tag,thanks

**Comment by cmaglie** [comment]
done
