### ISSUE TITLE
Cannot recognize Arduino device in the IDE port in Macbook Pro with high sierra 10.13

### ISSUE THREAD

**Issue by hanghoo** [arduino/Arduino#9214]
My Macbook pro with high sierra 10.13 with Type-C port cannot recognize Arduino.

**Comment by dinakhalil1** [comment]
I have the same issue!
but my MacBook is updated to Mojave 10.14.6

**Comment by per1234** [comment]
Closing due to insufficient information to make an investigation.

@hanghoo  if you'll make a reply here to provide the requested information I'll be happy to re-open this issue.
