### ISSUE TITLE
[Library Manager] Add Sanke to Library Manager

### ISSUE THREAD

**Issue by Liksu** [arduino/Arduino#9216]
Hi,
Please, add my library Snake into your library manager.

Link to the repository:
https://github.com/Liksu/7SegmentsSnake

Release:
https://github.com/Liksu/7SegmentsSnake/releases/tag/v1.0

And to library.properties file:
https://raw.githubusercontent.com/Liksu/7SegmentsSnake/master/library.properties

Thank you!

**Comment by cmaglie** [comment]
done
