### ISSUE TITLE
Adding a library

### ISSUE THREAD

**Issue by gedeoncom** [arduino/Arduino#9226]
Hello,

I think I am doing this right. Could you please add the library at:
https://github.com/PaulStoffregen/FrequencyTimer2

Thank you.
Pierre

**Comment by per1234** [comment]
That library is already in the Arduino Library Manager index.

Please only request the addition of libraries for which you are the owner/maintainer of the repository or have the permission of an owner/maintainer to make the request on their behalf.

**Comment by gedeoncom** [comment]
Thank you, I am new to this process this was good information.

Pierre

:: This email is meant for you and is protected by Thor God of Thunder ::
