### ISSUE TITLE
Arduino Web Editor Compiling issue

### ISSUE THREAD

**Issue by Pranaov** [arduino/Arduino#9227]
When compiling in the web editor, it gives me an error stated:
Error reading file (/tmp/769968735/custom/tmp1556430136699217155/library.properties:0): Invalid line format, should be 'key=value'

![Annotation 2019-09-14 172940](https://user-images.githubusercontent.com/43486986/64907827-4bf2d000-d715-11e9-801c-227591fe8f99.png)

Whatever board I use, it gives me that error.
I have uninstalled all the Custom Libraries.
Whatever sketch I Compile, it gives me a reply that  it is successfully compiled even though it is known that the code is syntactically wrong.

Hope this issue is fixed.

Regards,
S. Pranaov
Username: pranaov-senthil

![Annotation 2019-07-04 065642](https://user-images.githubusercontent.com/43486986/64907795-d1c24b80-d714-11e9-8da6-7d473d58a712.png)

**Comment by per1234** [comment]
According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor.

I see you have already reported this issue on the Arduino forum back in July, so there's no need to create a new forum thread about it:
https://forum.arduino.cc/index.php?topic=624565
So I'm going to close this issue in favor of the report on the forum.

I just notified the Arduino Web Editor team about the issue.
