### ISSUE TITLE
Updating arduino removes boards.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [arduino/Arduino#9229]
When I updated the Arduino all the boards are gone and I need to install them all. How can we update the Arduino with the same boards?

**Comment by per1234** [comment]
How did you update?

Which version did you update from?

Which version did you update to?

How did you install the boards?

**Comment by a-c-sreedhar-reddy** [comment]
I installed the folder for linux and ran install.sh script.
I could not remember from which version I upgraded from.
I updated to the latest.
I installed esp32 boards using https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/debian_ubuntu.md

**Comment by per1234** [comment]
What is the folder location of your previous Arduino IDE installation?

Were you running the Arduino IDE in portable mode (https://www.arduino.cc/en/Guide/PortableIDE)?

What is the location of your sketchbook folder (File > Preferences > Sketchbook location)?

**Comment by per1234** [comment]
Closing due to lack of response.

@a-c-sreedhar-reddy if you'll provide the requested information I'll be happy to re-open this issue.
