### ISSUE TITLE
add a *.cfg (or something) file to save our setting for each *.ino sketch

### ISSUE THREAD

**Issue by Master811129** [arduino/Arduino#9235]
hello there
can you please add some config file for each sketch to save our settings?
it is very useful when you want to use ESP32 or any other core which has lot of settings
![Untitled](https://user-images.githubusercontent.com/37829730/65132206-d2f5c000-da15-11e9-8889-746eef7983db.png)

**Comment by facchinm** [comment]
This feature will be part of [arduino-cli ](https://github.com/arduino/Arduino-cli) settings, so I'd ask ou to move the issue on that repo, thanks!
