### ISSUE TITLE
[Library Manager] Please add MCreator Link library to the Library Manager

### ISSUE THREAD

**Issue by KlemenDEV** [arduino/Arduino#9244]
We have renamed our project Minecraft Link (requested here: https://github.com/arduino/Arduino/issues/8306) to MCreator Link to comply with Minecraft brand usage terms. Would it be possible to get this library readded under its new name?

New repository URL: https://github.com/Pylo/MCreatorLink

**Comment by cmaglie** [comment]
I guess you wanted to re-add this one: https://github.com/Pylo/MCreatorLinkArduino

I'm going to add `MCreator Link` from the link above, and remove `Minecraft Link`.

**Comment by cmaglie** [comment]
done

**Comment by KlemenDEV** [comment]
Yes, this is correct. Thanks!
