### ISSUE TITLE
Lillypad arduino.. Board rate

### ISSUE THREAD

**Issue by gowdetilikhith** [arduino/Arduino#9245]
How to change a bord rate to 57600
Oversight Bad Rate 57100
avrdude: stk ) po r is not responding
avrdude: stksoo getsync() attempt 1 of 10: not in sync: resp-exto
avrdude: stk 0 recv() programmer is not responding
avrdude: stk . Betsync() attempt 2 of 10: not in sync: resp-Bxfo
avrdude: ser_recv(): programmer is not responding
avrdude: stk. Getsync() attempt of 10: not in sync: resp-xf6
avrdude: stk500 recv(): programer is not responding
avrdude: stkS00 getsync attempt 4 of 10: not in sync resp-Oxf6
avrdude: stk s recv: programmer is not responding
avrdude: stks00 getsync() attempt of 10: not in sync: resp-axfs
avrdude: stk500_recv(): programmer is not responding
avrdude: stks00 getsync) attempt 6 of 10: not in sync: resp-0xf6
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500 getsync() attempt 7 of 10: not in sync: resp 0xb6
avrdude: stk500_recv(): programmer is not responding
avrdude: stksee getsync() attempt of 10: not in sync: resp-8xf
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: pesp exfo
avrdude: stk500_recv(): programmer is not responding
avrdude: stk getsync attempt 10 of 10: not in sync: esp-xf
avrdude done. Thank you

Type here to search

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide a detailed explanation of what you're trying to accomplish.

**Comment by gowdetilikhith** [comment]
Thank you ... For your suggesion
