### ISSUE TITLE
select coding-style

### ISSUE THREAD

**Issue by Master811129** [arduino/Arduino#9248]
hello there,
when i add a new sketch with arduino IDE i always have to clean the initial code and replace it with the standard C++ code (int main (void)) because it is really better (also readable for a person who works in dev C++ or Visual C++) than the non-standard arduino form.
i edited the preference of the IDE (with ms-paint😁) to demonstrate my idea.
![Annotation 2019-09-21 151917](https://user-images.githubusercontent.com/37829730/65374526-12cfd800-dca0-11e9-9f51-04f8ae8c77d4.png)
```C++
int main (void)
{
  init();//initial function for arduino eg:millis() timer

  while(1)
  {
     
  }
}
```

**Comment by per1234** [comment]
You can customize the **File > New** sketch any way you like by editing the file at `{Arduino IDE installation folder}/examples/01.Basics/BareMinimum/BareMinimum.ino`.
