### ISSUE TITLE
[Library Manager] Fix SparkFun LIS3DH library

### ISSUE THREAD

**Issue by nseidle** [arduino/Arduino#9250]
Our library is not showing up in the library manager: https://github.com/sparkfun/SparkFun_LIS3DH_Arduino_Library

Here is the [original issue request](https://github.com/arduino/Arduino/issues/5800). I suspect it is because we messed up and changed the [original lib properties](https://github.com/sparkfun/SparkFun_LIS3DH_Arduino_Library/blob/bd75851c64df3d3bda6c037756ac6492fc3c8d91/library.properties) from:

name=SparkFun LIS3DH Breakout

to

name=SparkFun LIS3DH Arduino Library

Perhaps it's because the [original request](https://github.com/sparkfun/SparkFun_LIS3DH_Arduino_Library/tree/V_1.0.0) included the tree version. Not sure. Let me know how to fix. Perhaps the easiest is to delete and re-add.

**Comment by cmaglie** [comment]
I've change the library name to `SparkFun LIS3DH Arduino Library` and removed `SparkFun LIS3DH Breakout`

**Comment by bboyho** [comment]
Thanks! The library manager can now see the different library versions. =)
