### ISSUE TITLE
[Library Manager] Please add PF library to the library manager!

### ISSUE THREAD

**Issue by Master811129** [arduino/Arduino#9252]
Hi,
Please add the https://github.com/Master811129/PF library to the manager!

Thanks.

**Comment by cmaglie** [comment]
done

**Comment by Master811129** [comment]
thank you but i release the next version on github can you update it for me?

**Comment by cmaglie** [comment]
From now on it's automatic, when you want to make a new release you must:

1. update the version in library.properties
2. commit & push
3. make another git tag

once done, the indexer will publish the new version automatically within an hour.
