### ISSUE TITLE
Library Manager additions: MQSensor update

### ISSUE THREAD

**Issue by miguel5612** [arduino/Arduino#9265]
Hi,
Please, update the MQSensorsLib library to the Arduino Library Manager. Here is the library repository:

Library URL: https://github.com/miguel5612/MQSensorsLib

this update is bassed on one issue opened by an user because need to set a new RL Value

Thank you!

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly. So you don't need to create an issue report every time you release a new version; they'll be picked up automatically.

If you check Library Manager, you'll see your 1.0.4 release is already available for installation.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by miguel5612** [comment]
Thanks :)
