### ISSUE TITLE
[Library Manager] Please add *RC_ESC* to the Library Manager

### ISSUE THREAD

**Issue by rbscharette** [arduino/Arduino#9269]
Hi,

I open this issue to have the _RC_ESC_ added to the _Library Manager_.
The library can be found here: https://github.com/RB-ENantel/RC_ESC
Releases (tags) are here: https://github.com/RB-ENantel/RC_ESC/releases

Please let me know if there is anything else I need to do.

Sincerely,

**Comment by cmaglie** [comment]
done
