### ISSUE TITLE
Move selected text in code editor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#927]
This is [Issue 927](http://code.google.com/p/arduino/issues/detail?id=927) moved from a Google Code project.
Added by 2012-05-29T11:28:06.000Z by [markausk...@gmail.com](http://code.google.com/u/117165164826702506315/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**
Drag&Drop selected text to new location feature;

**Why?**
Don't know if it's only me, but i'm doing it always in another text editor. And then i'm working with Arduino IDE i'm Draging&Droping text intuitively. It's very annoying then you release that this feature don't exist few times per day :)

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
Think no.

**Comment by ffissore** [comment]
Upcoming 1.6.5 (available with hourly builds http://www.arduino.cc/en/Main/Software#hourly) supports drag & drop
