### ISSUE TITLE
Serial reads missing last byte

### ISSUE THREAD

**Issue by ttmthuy** [arduino/Arduino#9270]
Hi,

I'm using Arduino ver1.8.10 on Win10, board Arduino/Genuino Zero (Native USB Port).
I'm using a baudrate of 57600. 
I run this program below. When viewing this on the serial monitor in the Arduino IDE,  it always reads missing last byte.

`  while (Serial.available() > 0) {
      byte id = Serial.read();
      SerialUSB.print(id, HEX);    
     }
 `
Do you have any suggestions?
Thank you.

**Comment by facchinm** [comment]
Closing here, keeping track on https://github.com/arduino/ArduinoCore-samd/issues/459
