### ISSUE TITLE
GSM.h doesn't work.

### ISSUE THREAD

**Issue by stefanbuciu** [arduino/Arduino#9279]
Hello,

I have an Arduino MKR 1400 and I wanted to make it send some SMS's if certain sensors are triggered. Sadly, just as I started, I ran into a problem: the simple fact of including the GSM.h library breaks the code. I have only the basic setup and loop functions and it still won't run. The problem is stated that "multiple libraries were found for gsm.h" and I went on google but people are facing this issue when including both GSM and some serial port library, but I'm not doing that.

**Comment by per1234** [comment]
The problem is this is causing you to use the GSM library, which is for the retired Arduino GSM Shield. That shield is completely different from the MKR GSM 1400. For the MKR GSM 1400, you need to in MKRGSM.h instead of GSM.h.
