### ISSUE TITLE
[Library Manager] Add Adeon to Library Manager

### ISSUE THREAD

**Issue by vzahradnik** [arduino/Arduino#9299]
Hello,
please add our library into your library manager.

Link to the repository:
https://github.com/JSC-electronics/Adeon

And to library.properties file:
https://github.com/JSC-electronics/Adeon/blob/master/library.properties

Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Ales-Svoboda** [comment]
Hello,
the release has been created.

Kind regards,
AS.

**Comment by cmaglie** [comment]
Done.
