### ISSUE TITLE
Add ATMega328 to avrdude.conf (in addition to ATmega328P) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#930]
This is [Issue 930](http://code.google.com/p/arduino/issues/detail?id=930) moved from a Google Code project.
Added by 2012-05-29T18:22:19.000Z by [Randall....@gmail.com](http://code.google.com/u/115969923437411526907/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-Build
### Original description

**What change would like to see?**
Add native support for the non-Pico Power version of the ATMega328.

**Why?**
Many users not concerned with power consumption would like to use the ATMega328.  The chip is cheaper and readily available.  In order to use the chip the AVRDude configuration file must be changes so it believes the ATMega328 is actually a ATMega328p.  This not apparent and should not be necessary.

Would this cause any incompatibilities with previous versions?  No.
If so, how can these be mitigated?

**Comment by per1234** [comment]
avrdude.conf already contains a definition for the ATmega328 part. The toolchain issues mentioned in the comments have also been resolved.
