### ISSUE TITLE
error when including  <avr/dtostrf.h>

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#9309]
error when including 
#include <avr/dstrtof.h>
(as suggested in https://github.com/arduino/Arduino/issues/9308#issuecomment-541160600 )

 exit status 1 avr/dstrtof.h: No such file or directory

BTW, it's rather narrow-minded to close and limit the topic at that point of discussion.

**Comment by dsyleixa** [comment]
probably a typo

#include <avr/dtostrf.h>

**Comment by dsyleixa** [comment]
but even then the error stays the same:

#include <avr/dtostrf.h>
...

:\arduino\portable\sketchbook\libraries\MPU6050\MPU6050.cpp:3308:197: error: 'dtostrf' was not declared in this scope

**Comment by cmaglie** [comment]
Did you add the suggested include in `arduino\portable\sketchbook\libraries\MPU6050\MPU6050.cpp\MPU6050.cpp`?
Probably the library has only been tested on AVR and doesn't include that file.

**Comment by dsyleixa** [comment]
no, I added it just in my code, never thought about having to add a library more than just once

**Comment by dsyleixa** [comment]
thanks, that solved it!
I appreciate this kind of constructive conversation!
