### ISSUE TITLE
ATMega328P "Breadboard config"

### ISSUE THREAD

**Issue by GlennFR** [arduino/Arduino#9313]
Hi, Been using Arduino for prototyping since 2014 and have some of my older devices still running out there at customer sites.  I have one back for upgrading, and I've come across two problems with the new (1.8.8) IDE.
**I use the 328P chip "bare bones" using the internal 8MHz crystal.**
**Problem 1** (workaround found)
In the older IDE I had my board.txt and pins_arduino.h in the old directory structure.  I converted to the new structure (_myname_/avr/...) but the pins_arduino.h file doesn't seem to be found under ../variants/_myboard_.  The workaround was to also copy the file into the global .Arduino15 directory structure.
**Problem 2**
My 328P chips were flashed with the 'OLD' bootloader.  In the new IDE I can't find any way to tell the system that it has to communicate with the OLD version (there used to be a "processors" option in the TOOLS menu...  So I'm getting `avrdude:stk500v2_ReceiveMessage(): timeout` forever and ever

Please help!

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
