### ISSUE TITLE
[Library Manager] Please add my esp32_gamepad library

### ISSUE THREAD

**Issue by bitbank2** [arduino/Arduino#9319]
Arduino team,
Please add my esp32_gamepad library to the library manager. Here's the link:

https://github.com/bitbank2/esp32_gamepad

Thanks,
Larry B.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by bitbank2** [comment]
oops - just added

**Comment by cmaglie** [comment]
done
