### ISSUE TITLE
Local reference missing some files. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#932]
This is [Issue 932](http://code.google.com/p/arduino/issues/detail?id=932) moved from a Google Code project.
Added by 2012-05-30T12:57:32.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Milestone-1.0.2, Component-Build

### Original description

The local copy of the reference is missing some files.  Looks like we need to make some additions to the create_reference.pl script that downloads it.  Attached is a list of missing files from Lukas Bestle.

**Comment by ffissore** [comment]
Worked around in 7daf13e73a28898b2b4eac17c10c2334db4df51f
