### ISSUE TITLE
[Library Manager]Please add BQ25896 library

### ISSUE THREAD

**Issue by andhieSetyabudi** [arduino/Arduino#9321]
Please add this library: https://github.com/andhieSetyabudi/BQ25896
Thanks.

**Comment by andhieSetyabudi** [comment]
excuse me, 
i just wanna ask about my lib.. 
why it still didn't shown in my arduino library manager ?? 
thanks ^^

**Comment by cmaglie** [comment]
Done, sorry for the delay.
