### ISSUE TITLE
[Library Manager] Please add GroveDriverPack library

### ISSUE THREAD

**Issue by matsujirushi** [arduino/Arduino#9349]
Hi,

I created the library.
Could you add this to a list of libraries?
https://github.com/SeeedJP/GroveDriverPack

Thanks.

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by matsujirushi** [comment]
Oh, sorry.
created.
https://github.com/SeeedJP/GroveDriverPack/releases/tag/1.4.0

**Comment by cmaglie** [comment]
Done.
