### ISSUE TITLE
Shift-backspace shouldn't forward-delete on non-Mac OS X operating systems. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#937]
This is [Issue 937](http://code.google.com/p/arduino/issues/detail?id=937) moved from a Google Code project.
Added by 2012-06-01T02:42:02.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE, OpSys-Windows, OpSys-Linux

### Original description

**What steps will reproduce the problem?**
1. Press shift-backspace (on Windows or Linux).

**What is the expected output? What do you see instead?**

The character in front of the cursor is deleted.  It should be the one behind.

**Please use labels and text to provide additional information.**

**Comment by ffissore** [comment]
Fixed in latest hourly
