### ISSUE TITLE
Tab key does nothing if editor.tabs.expand is false. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#938]
This is [Issue 938](http://code.google.com/p/arduino/issues/detail?id=938) moved from a Google Code project.
Added by 2012-06-01T02:49:40.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, OpSys-All, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Edit the preferences.txt file.
2. Set editor.tabs.expand to false.
3. Run Arduino and hit the tab key.

**What is the expected output? What do you see instead?**

Nothing happens.  It should insert a tab.

**Please use labels and text to provide additional information.**

**Comment by ffissore** [comment]
I guess this was fixed with the new editor, available since 1.6.5
