### ISSUE TITLE
let user decide optimization level instead of allways -Os

### ISSUE THREAD

**Issue by pabloandresm** [arduino/Arduino#9380]
This is a suggestion for improvement.
When you select the standard boards, let the user select the optimization level (-Ox) and debug level (-gx).

The STM32F boards do that.
Here a screenshot of what I mean by this...

![optimizationlevel](https://user-images.githubusercontent.com/10205701/67949192-0fe0d500-fbc6-11e9-9f73-6f289fe7bdfc.jpg)

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/9240
