### ISSUE TITLE
[Library Manager] Please add the TFMini-Plus-I2C library to the Library Manager.

### ISSUE THREAD

**Issue by budryerson** [arduino/Arduino#9385]
Dear Friends,

Please add this addition to the Arduino Library Manager:
https://github.com/budryerson/TFMini-Plus-I2C/releases/tag/v0.1.1

This library is designed to support the I2C communication interface mode of the Benewake TFMini-Plus time-of-flight distance sensor.

As always, your gentle guidance and/or corrections will be appreciated.

Bud Ryerson
San Francisco

**Comment by cmaglie** [comment]
Done.
