### ISSUE TITLE
[Library Manager] Please add PxMatrix Christmas Icons library

### ISSUE THREAD

**Issue by yknivag** [arduino/Arduino#9387]
Dear Arduino Team,

Could you please add my PxMatrix Christmas Icons library to the library manager?

Repository: https://github.com/yknivag/PxMatrixChristmasIcons

Release: [https://github.com/yknivag/PxMatrixChristmasIcons/releases/tag/0.0.1](https://github.com/yknivag/PxMatrixChristmasIcons/releases/tag/0.0.1)

Many thanks,

Gavin.

**Comment by yknivag** [comment]
Dear Team,

Due to an issue, I have had to release a new version...

Latest release: https://github.com/yknivag/PxMatrixChristmasIcons/releases/tag/0.0.2

Many thanks,

Gavin.

**Comment by cmaglie** [comment]
Done.

**Comment by yknivag** [comment]
Many thanks.
