### ISSUE TITLE
[Library Manager] New Library: EMUSerial

### ISSUE THREAD

**Issue by GTO2013** [arduino/Arduino#9389]
Hi,
could you please add this repo to your list: https://github.com/GTO2013/EMUSerial

Thank you!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by GTO2013** [comment]
Hi,
sorry for the late reply. I had already added a 1.0.1 tag to it, seems like something went wrong there. I created a release called 1.0.1 which matches the .property file.

**Comment by cmaglie** [comment]
Done.
