### ISSUE TITLE
[Library Manager] SI4735 Library for Arduino 

### ISSUE THREAD

**Issue by pu2clr** [arduino/Arduino#9391]
[Library Manager] SI4735 Library for Arduino 
This is a library implementation for the Silicon Labs SI4735, a DSP BROADCAST AM/FM/SW RADIO RECEIVER. Please, include it on Arduino libraries. 

Link GitHub: https://github.com/pu2clr/SI4735

**Comment by pu2clr** [comment]
I removed the release 1.0.1 and created the new release 1.0.2.  So, the first release is 1.02. Let me know if it is a problem.

**Comment by cmaglie** [comment]
No problem, library added.
