### ISSUE TITLE
[Library Manager] MCP4822 Library

### ISSUE THREAD

**Issue by SteveGdvs** [arduino/Arduino#9395]
Hello,

Can you please include this library ?

https://github.com/SteveGdvs/MCP48xx
~https://github.com/SteveGdvs/MCP4822~

Thanks.

**Comment by SteveGdvs** [comment]
I decided to change the name of the library to MCP48xx because I want to support all the devices of the MCP48xx family.

I believe there is no problem doing it, because the library has not been added yet to the Library Manager.

The new link is https://github.com/SteveGdvs/MCP48xx

Can I do this?

Thanks.

**Comment by cmaglie** [comment]
No problem, library added.
