### ISSUE TITLE
Arduino Projects Handbook

### ISSUE THREAD

**Issue by ArdinoFan** [arduino/Arduino#9400]
Good morning Sir/Mam,

I’m looking for a Arduino Projects Handbook, that can guide me through the various projects for the Arduino kit I’ve bought from Communica in South Africa. I know they had such a handbook many years ago and I’ve asked them for this book the other day I was @ Communica, but their reply was just that they don’t sell the book anymore and that I must rather go to the Arduino website. I’ve looked & searched through the website, but to no avail I’ve not found any books 📚 that can be bought from Arduino...! I need help please, thanks 🙏🏻...!

Regards,
Schalk

**Comment by per1234** [comment]
The Arduino Project book is available as part of the Arduino Starter Kit:
https://store.arduino.cc/genuino-starter-kit

For any questions you may have about the Arduino Store, please contact Arduino Store support via this form:
https://store.arduino.cc/store-support
