### ISSUE TITLE
 [Library Manager] Add uCRC16XModemLib to Library Manager

### ISSUE THREAD

**Issue by Naguissa** [arduino/Arduino#9402]
Hello,

Following Library Manager FAQ I open this issue to request adding uCRC16XModemLib library to Arduino repository.

Repository URL is: https://github.com/Naguissa/uCRC16XModemLib

It's a simple and convenient library to calculate CRC16 XModem. Specially useful when using UKHAS.org.uk site, but generic to any use.

Thanks.

**Comment by cmaglie** [comment]
Done.

**Comment by Naguissa** [comment]
Thanks!
