### ISSUE TITLE
[Library Manager] Add NoveltyDetection to Library Manager

### ISSUE THREAD

**Issue by Rotario** [arduino/Arduino#9405]
Hi,
Please add my novelty detection SVM algorithm library to Library manager.

Repo link is 
https://github.com/Rotario/noveltyDetection

Thanks!
Rowan

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem, the `paragraph` field in `library.properties` is not allowed to span over multiple lines: https://github.com/Rotario/noveltyDetection/blob/v1.0.1/library.properties#L6

To fix this:

1) edit `library.properties` file and put the `paragraph` field in one single long line.
2) commit & push
3) delete and redo the `v1.0.1` tag (so it points the the updated file)

once done the indexer should pick and publish the library automatically within an hour.
