### ISSUE TITLE
[Library Manager] Add DCD SDK Arduino library in the library manager

### ISSUE THREAD

**Issue by livein21st** [arduino/Arduino#9406]
Hi,

Please add my DCD SDK arduino library to library manager. The library allows student to connect to our IoT hub and send data.

Repository link:

https://github.com/datacentricdesign/dcd-sdk-arduino

**Comment by cmaglie** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by livein21st** [comment]
I have added the release tag for git repo! Let me know if anything else missing.

Thank you for your support.

**Comment by livein21st** [comment]
@cmaglie any updates?

**Comment by cmaglie** [comment]
Done.
