### ISSUE TITLE
[Library Manager] Add DCD SDK Arduino library (v0.0.2) in the library manager

### ISSUE THREAD

**Issue by livein21st** [arduino/Arduino#9426]
Hi,

Please add my DCD SDK arduino library (v0.0.2) to library manager. The library allows student to connect to our IoT hub and send data.

Repository link:

https://github.com/datacentricdesign/dcd-sdk-arduino

**Comment by per1234** [comment]
The library has already been added to the Library Manager index per https://github.com/arduino/Arduino/issues/9406. It is not necessary to submit a new issue for each release of the library as the Library Manager indexer picks them up automatically.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list
