### ISSUE TITLE
[Library manager] Krypton

### ISSUE THREAD

**Issue by deyyanl** [arduino/Arduino#9434]
https://github.com/oberonspace/krypton

**Comment by cmaglie** [comment]
Done.

**Comment by deyyanl** [comment]
Thank you :D Have a nice day!

**Comment by njh** [comment]
Did you decide to delete the krypton repo in the end?
What was the reason?

**Comment by deyyanl** [comment]
I don't have time to update the library and to manage it. Looking forward to make a better version at the end of the year
