### ISSUE TITLE
[Library Manager] ezButton Library

### ISSUE THREAD

**Issue by ArduinoGetStarted** [arduino/Arduino#9439]
Please add the ezButton Library to Library Manager: [https://github.com/ArduinoGetStarted/button](https://github.com/ArduinoGetStarted/button)

**Comment by ArduinoGetStarted** [comment]
thank you!

**Comment by ArduinoGetStarted** [comment]
It has been 16 hours since the library is added. But I cannot search it in library manager in Arduino IDE. I would like to ask whether there is any problem?

**Comment by per1234** [comment]
@ArduinoGetStarted your library was not added. I simply labeled the issue in preparation for the bulk add that will happen sometime within the next couple of weeks.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by ArduinoGetStarted** [comment]
I got it. Thank you for quick reply

**Comment by cmaglie** [comment]
Done.
