### ISSUE TITLE
arduino wifi rev2 "invalid value for unused bits in fuse "fuse5"

### ISSUE THREAD

**Issue by butzvarukt** [arduino/Arduino#9443]
Hi,

i'm new to github and also new to coding. actually i bought a coding game for my son (10) where had to code to finish a jump and run. Pretty cool stuff for a kid and he liked it very much. in his holiday he made a workshop where they built a weather station and we wanted to built one together.

So i bought an arduino uno wifi rev2 ATMEGA4809 and we wrote the first small program, a blink program. The code was ok but we weren't able to upload it to the board.

**avrdude: WARNING: invalid value for unused bits in fuse "fuse5", should be set to 1 according to datasheet
This behaviour is deprecated and will result in an error ibn future version
You probably want to use 0xcd instead of 0xc9 (double check with your datasheet first).**

I don't know what to do about that and i hope anybody had the same issue and can help us to solve the problem.

Thanks

**Comment by per1234** [comment]
This warning is normal and expected and does not indicate any problem. Please just ignore that warning and get back to having fun with your Uno WiFi Rev2!
