### ISSUE TITLE
[Library Manager] Cerebro educational robot

### ISSUE THREAD

**Issue by cerebro11101** [arduino/Arduino#9445]
https://github.com/cerebro11101/CerebroBoards

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by cerebro11101** [comment]
sorry :) its ready, !

**Comment by cerebro11101** [comment]
> You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
> 
> After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.
> 
> For more information see:
> https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

sorry :) its ready, !

**Comment by cmaglie** [comment]
Done.
