### ISSUE TITLE
libraries\NewPing

### ISSUE THREAD

**Issue by jdslk2016** [arduino/Arduino#9448]
Hi i am getting error When i add #include <NewPing.h> as follow can you help me

Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

Tone.cpp.o (symbol from plugin): In function `timer0_pin_port':

(.text+0x0): multiple definition of `__vector_7'

libraries\NewPing\NewPing.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "NewPing.h"
 Used: C:\Users\Administrator\Documents\Arduino\libraries\NewPing
 Not used: C:\Program
Multiple libraries were found for "Servo.h"
 Used: C:\Program
exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
