### ISSUE TITLE
[Library Manager] Is it possible to add a release that doesn't live on branch master (TeensyDMX)?

### ISSUE THREAD

**Issue by ssilverman** [arduino/Arduino#9453]
I have a new release for TeensyDMX, v3.2.1, that does not live on the `master` branch. Is it still possible for the Library Manager to find it?

The branch name is `fix-dmx-receive-in-v3.2.0`.
Project URL: https://github.com/ssilverman/TeensyDMX
Branch URL: https://github.com/ssilverman/TeensyDMX/tree/fix-dmx-receive-in-v3.2.0

**Comment by per1234** [comment]
The Library Manager indexer works from Git tags (which are automatically created by GitHub releases). The indexer doesn't care which branch the tag is created from. So as long as the tag is compliant with the [Library Manager requirements](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ), the release will be picked up.
