### ISSUE TITLE
[Library Manager] Blynk_WM

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9465]
https://github.com/khoih-prog/Blynk_WM

This is a simple WiFiManager for Blynk and ESP8266/ESP32 with or without SSL, configuration data saved in either SPIFFS or EEPROM.

Thanks

**Comment by cmaglie** [comment]
Done, sorry for the long delay

**Comment by khoih-prog** [comment]
Thanks so much. and Best Regards.
