### ISSUE TITLE
[Library Manager] - new Jpeg Decoder library for inclusion

### ISSUE THREAD

**Issue by Bodmer** [arduino/Arduino#9473]
Library can be found here:

[https://github.com/Bodmer/TJpg_Decoder](https://github.com/Bodmer/TJpg_Decoder)

The library offers high performance with low memory footprint and simple sketch interface.

Tested with TFT's and Adafruit_GFX library. Aslo works with TFT_eSPI graphics library on ESP32 and ESP8266.

Generic examples included that render jpegs from: FLASH array or SD card.

Examples for ESP32 and ESP8266 include reading a jpeg from a web URL via WiFi and rendering jpegs stored in SPIFFS.

**Comment by cmaglie** [comment]
Done, sorry for the long delay
