### ISSUE TITLE
I am a beginner and I have a problem please help me

### ISSUE THREAD

**Issue by EpitaphLUL** [arduino/Arduino#9474]
#8859 I am new at arduino, I was planning to get into it , I just need to do a school project so this is a good way to get started. I bought an arduino uno r3 and wanted to set it up. I installed the arduino software which automatically installed dome drivers for the arduino. the problem is that it doesn't have the drivers installed properly and I tried everything to make it work , i followed online guides and i have done the "device manager " and "update drivers" trick and it still didn't work.I even downloaded some other drivers online and who would have guessed...I still didn't work  . I am using windows 7 . The main problem is that without the proper driver installation my pc won't recognize the arduino and I can't upload my code . If you have any suggestions or need additional information please do not hesitate to respond . I have to finish the project before december 15th so please help me .

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/).
