### ISSUE TITLE
Serial Monitor needs an "Export output to file" option

### ISSUE THREAD

**Issue by alexceltare2** [arduino/Arduino#9479]
I've lost countless data logged in the Serial Monitor because the blasted Ctrl+A Ctrl+C doesn't function properly or I've accidentally unplugged the serial-based logging device/Arduino. So a good addition to the serial monitor would be a button to export the output as Excel, txt, or any other readable format.

**Comment by CloudFenrir** [comment]
Hello, I'll work on this feature  :smile:

**Comment by AsherThomasBabu** [comment]
Hey there developers,
I am fairly new to the source code of the Arduino IDE. I happened to want this feature myself and started working on it.

I pulled the latest version from git and `ant built` it and `ant run` the build folder as per instructions from the Wiki page. 

Building and running it the **first time** works flawlessly, But, when built for a **second time** with no changes to the files, the run fails with this message.

```
BUILD FAILED
/home/asher/Arduino/build/build.xml:140: The following error occurred while executing this line:
/home/asher/Arduino/build/build.xml:144: The following error occurred while executing this line:
/home/asher/Arduino/build/build.xml:829: exec returned: 255

Total time: 10 seconds
```

I am running it on a Linux machine, Looking forward to some help.
Thank You 
Asher

**Comment by per1234** [comment]
An alternative proposal of making copying Serial Monitor contents to the clipboard is presented at https://github.com/arduino/Arduino/issues/6906

**Comment by kvkpraneeth** [comment]
> Hey there developers,
> I am fairly new to the source code of the Arduino IDE. I happened to want this feature myself and started working on it.
> 
> I pulled the latest version from git and `ant built` it and `ant run` the build folder as per instructions from the Wiki page.
> 
> Building and running it the **first time** works flawlessly, But, when built for a **second time** with no changes to the files, the run fails with this message.
> 
> ```
> BUILD FAILED
> /home/asher/Arduino/build/build.xml:140: The following error occurred while executing this line:
> /home/asher/Arduino/build/build.xml:144: The following error occurred while executing this line:
> /home/asher/Arduino/build/build.xml:829: exec returned: 255
> 
> Total time: 10 seconds
> ```
> 
> I am running it on a Linux machine, Looking forward to some help.
> Thank You
> Asher

Hey! did you find a fix for this?

**Comment by per1234** [comment]
Now tracked at https://github.com/arduino/arduino-ide/issues/549
