### ISSUE TITLE
USB CDC (Serial) write on Leonardo is blocking. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#948]
This is [Issue 948](http://code.google.com/p/arduino/issues/detail?id=948) moved from a Google Code project.
Added by 2012-06-06T13:34:31.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core

### Original description

From Mike King on the developers list:

"Serial_::write uses the function USB_Send to send data.  USB_Send is a
blocking function.  Is there away to make the virtual serial
connection non-blocking like it was on the Uno?  I need to read from
the ADC a 1000 times per second and send the result to a computer for
processing.  I measured the virtual serial bandwidth to be between 40
and 45 kBps on the Leonardo.  I like to measure the voltage once per
1ms with the smallest "jitter."  If I use a blocking write function
then I won't be sampling the ADC a 1000 times per second."

**Comment by NicoHood** [comment]
Actually it is not blocking and this causes another issue:
https://github.com/arduino/Arduino/issues/3946

**Comment by sandeepmistry** [comment]
Closing, as @NicoHood mentioned, it does not block (anymore).
