### ISSUE TITLE
How to identify which board pins are assigned to Arduino IDE pins when there is no board preset?

### ISSUE THREAD

**Issue by mrdc** [arduino/Arduino#9480]
Hello,

I'm using some chips from Nordic which don't have a board preset in Arduino IDE, so I don't know which board pins are assigned to Arduino IDE pins. How does Arduino IDE handles pin assignments?

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
