### ISSUE TITLE
[Library Manager] Please add my library VT100

### ISSUE THREAD

**Issue by kcl93** [arduino/Arduino#9482]
Hello :)
Can you please add my VT100 library (https://github.com/kcl93/VT100) to the library manager? Thanks! It provides easy functions to control a VT100 terminal via serial commands.
Kind regards,
Kai

**Comment by cmaglie** [comment]
Done, sorry for the long delay

**Comment by kcl93** [comment]
> Done, sorry for the long delay

Thanks! No problem! :)
