### ISSUE TITLE
when I use Keyboard.h, could I press keycode instead of keyASCII？

### ISSUE THREAD

**Issue by ljq29** [arduino/Arduino#9490]
It is generally accepted that when the header file Keyboard.h is used, some control keys can be sent through the Keyboard.press (key) function. But for keys without ASCII values, such as KEYCODE_VOLUME_UP and KEYCODE_VOLUME_DOWN, how should they be sent to the host through arduino?

**Comment by facchinm** [comment]
Hi @ljq29 ,
can you reopen the issue in the right repository( https://github.com/arduino- libraries/Keyboard ) ? Thanks
