### ISSUE TITLE
[Library Manager] Please add "AllThingsTalk WiFi SDK"

### ISSUE THREAD

**Issue by epiller** [arduino/Arduino#9494]
Hello,

Please add our library to the Library Manager:
https://github.com/allthingstalk/arduino-wifi-sdk

Thank you!

**Comment by epiller** [comment]
@cmaglie Any chance to get a rough estimate when this will be published? No rush, I'm just asking so I know when I can publish our platform's updated documentation that points to Library Manager.  
Thank you so much!

**Comment by cmaglie** [comment]
Done, sorry for the long delay
