### ISSUE TITLE
[Mac] Arduino IDE will not follow an alias to the actual .ino file [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#951]
This is [Issue 951](http://code.google.com/p/arduino/issues/detail?id=951) moved from a Google Code project.
Added by 2012-06-07T17:28:08.000Z by [isw@witzend.com](http://code.google.com/u/isw@witzend.com/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**

1. Move the most recently used .ino file (the one that will be automatically opened on launch) out of the Arduino/project_name folder to some other location in the Mac's file structure, and replace it with an alias to the moved .ino file's location

2. Launch the IDE

What is the expected output?

The alias should be followed and the target .ino file opened

What do you see instead?

The alias file itself is opened by the IDE instead of it being followed to the target file

What version of the Arduino software are you using?

1.0

On what operating system?

OS X 10.6.8

Which Arduino board are you using?

N/A

**Please provide any additional information below.**

Moving the code for a finished project to some other location (say, to a folder containing all the other documentation associated with the project) is a very common thing to do, both to keep all the information for a project together and to keep the Arduino Sketch folder from becoming cluttered. Failure to properly handle aliases is very "un-Mac-like".

**Comment by ffissore** [comment]
The IDE does not support symlinks
