### ISSUE TITLE
Arduino Web Editor não abre

### ISSUE THREAD

**Issue by ProgrammerA-RootNick** [arduino/Arduino#9511]
quando tento logar na minha conta dá esse erro: LOGIN: CSRF: OOPS, SOMETHING WENT WRONG, PLEASE TRY AGAIN.
se tento logar com o google dá esse erro: LOGIN: CSRF: OOPS, SOMETHING WENT WRONG, PLEASE TRY AGAIN.
quando tento redefinir a senha dá esse erro: OOPS, SOMETHING WENT WRONG, PLEASE TRY AGAIN.

**Comment by per1234** [comment]
According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor.

Please post to the Forum in English, even if that means using Google Translate. If you prefer to use Portuguese, there is a forum board for that:
https://forum.arduino.cc/index.php?board=35.0
but note that the people most knowledgeable about the Arduino Web Editor don't monitor the Portugues board.
