### ISSUE TITLE
bugs in Arduino Mega 2560 Rev 3 pin mapping diagram

### ISSUE THREAD

**Issue by bkerin** [arduino/Arduino#9521]
The diagram on https://www.arduino.cc/en/Hacking/PinMapping2560 and also it's source in the SVG in PinMapping2560.zip contains at least these errors:

Pin 93 label has typo: TMK should be TCK
Pin 91 label is badly wrong: PF6 (ADC6/PCINT14) should be PF6 (ADC6/TDO)
Pin 90 label is badly wrong: PF7 (ADC7/PCINT15) should be PF7 (ADC7/TDI)

The Pin 93 typo appears in the table as well.  The Pin 91 and 90 entries in the table are mostly correct, but they inconsistently omit the /TDO and /TDI parts of the parenthetical multiplex notes.

There may be other errors (I haven't checked the entire diagram or table).

**Comment by SimonePDA** [comment]
The pinout originally taken from AVR datasheet has been updated, as well as the table.

Things should be now correct as they were taken from the latest datasheet.

Simone
