### ISSUE TITLE
[Library Manager] ESP32_ISR_Servo Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9522]
This simple-to-use library enables you to use 1 selectable Hardware Timer on an ESP32-based board to control 16-or-more independent servo motors. You can select a different Hardware Timer to avoid conflicting with other libraries.

 https://github.com/khoih-prog/ESP32_ISR_Servo

Thanks,

**Comment by cmaglie** [comment]
Done.
