### ISSUE TITLE
[Library Manager] ESP_DoubleResetDetector for ESP32 and ESP8266

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9536]
https://github.com/khoih-prog/ESP_DoubleResetDetector

Using this library to detect a double reset, using RTC Memory for ESP8266 and EEPROM for ESP32.
Initial Release v1.0.0 to add support for ESP32 by using EEPROM to store data.

This library is based on, modified, bug-fixed and improved from [DataCute] (https://github.com/datacute/DoubleResetDetector) to add support for ESP32.

Thanks.

**Comment by cmaglie** [comment]
Done.
