### ISSUE TITLE
[Library Manager] CERP_DF_Robot_Wireless_GamePad_V2

### ISSUE THREAD

**Issue by DBS06** [arduino/Arduino#9541]
Hello.

I made a library for the "Wireless GamePad V2.0 for Arduino" from DF-Robot (https://www.dfrobot.com/product-858.html).

Could you add this to a list of libraries?
url: https://github.com/DBS06/CERP_DF_Robot_Wireless_GamePad_V2

Thanks.

**Comment by cmaglie** [comment]
Done.
