### ISSUE TITLE
error: attempt to use poisoned "SIG_USART0_RECV" [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#955]
This is [Issue 955](http://code.google.com/p/arduino/issues/detail?id=955) moved from a Google Code project.
Added by 2012-06-10T16:26:06.000Z by [dieg...@gmail.com](http://code.google.com/u/115937133858708056470/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Core
### Original description

**What steps will reproduce the problem?**
1. Compile any sketch (.ino). I tested with Blink example.

**What is the expected output? What do you see instead?**
The compilation ends with error.

/usr/bin/avr-g++ -c -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=100 -I. -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/mega   -g -Os -w -Wall -ffunction-sections -fdata-sections -fno-exceptions /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp -o build-cli/HardwareSerial.o
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:91:41: error: attempt to use poisoned "SIG_USART0_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:101:15: error: attempt to use poisoned "SIG_USART0_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:132:15: error: attempt to use poisoned "SIG_USART1_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:145:15: error: attempt to use poisoned "SIG_USART2_RECV"
/usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp:158:15: error: attempt to use poisoned "SIG_USART3_RECV"
make: **\* [build-cli/HardwareSerial.o] Error 1

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

OS: Debian GNU/Linux unstable.

Packages:
avr-libc 1:1.8.0-2
avrdude 5.11.1-1
binutils-avr 2.20.1-2
gcc-avr 1:4.7.0-2
arduino 1:1.0.1+dfsg-2
arduino-core 1:1.0.1+dfsg-2  
arduino-mk 0.8-4

Board: Mega2560             

**Please provide any additional information below.**

**Comment by rgars** [comment]
Have just accessed Arduino software that was compiled & loaded using IDE 1.6.7 and has run successfully on a Mega 2560 for the last two years. I have just run the verification using the latest IDE 1.8.3 and get an error associated with "poisoned SIG_USART0_RECV" occurring in SerialPort.cpp.

I have read the available posts I can find, but cannot understand what I should do to solve this problem.

As the posts above suggest that the problem was solved in 2013 in avr-lib I am puzzled. I am running the Arduino IDE on OSX.

I would appreciate any suggestions.

**Comment by rgars** [comment]
Thanks for the response.

I have received a lot of help to overcome the issue. Please see:-
https://github.com/greiman/SerialPort/issues/1

The sketch is posted in Comment No 5 in SerialPort/issues/1.

Let me know if further information is required.
