### ISSUE TITLE
Deprecate Arduino-builder in favor of Arduino-cli

### ISSUE THREAD

**Issue by dcuartielles** [arduino/Arduino#9558]
Given that we now have arduino-cli which seems to be operational, I would like to see a feature on arduino-cli that would allow for it to use experimental branches of a library so that we could, at some point, deprecate arduino-builder which seems to have structural issues that haven't been reviewed for a long time (like the hardcoded /bin/avr-g++ executable)

(in the meanwhile, improve the documentation for the arduino-builder so that people learn how to use the -prefs option)

**Comment by per1234** [comment]
arduino-builder has now been deprecated: https://github.com/arduino/arduino-builder/pull/350

>I would like to see a feature on arduino-cli that would allow for it to use experimental branches of a library

The user is free to install any version of a library they like, so that is already supported.

>improve the documentation for the arduino-builder so that people learn how to use the -prefs option

Since it's deprecated, there is no need to expend effort on improving the documentation.
