### ISSUE TITLE
Avrdude call retry timeout option for boards without auto-reset [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#957]
This is [Issue 957](http://code.google.com/p/arduino/issues/detail?id=957) moved from a Google Code project.
Added by 2012-06-12T18:17:18.000Z by [karl.kan...@gmail.com](http://code.google.com/u/110338758445183782643/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

**What change would like to see?**
An option in boards.txt for when a board doesn't have auto-reset and must be reset manually. For example BOARD.upload.timeout = 5 (in seconds, 0 by default)

In Arduino IDE when clicking Upload it would look something like this:
Binary sketch size: 786 bytes (of a 7,680 byte maximum)
Waiting for reset... // calls avrdude over and over until it can transmit data
// proceed as usual

**Why?**
With a board without auto-reset (just a hardware button) one has to click "Upload" and then time the reset button press exactly right, otherwise the upload will fail.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
This wouldn't cause any problems since the default is 0 which indicates there isn't any delay between the end of the compilation, the auto-reset and uploading for boards having the auto-reset feature.

**Comment by sandeepmistry** [comment]
All official boards have auto reset. Marking this as won't fix for now.
