### ISSUE TITLE
[Library manager] rename "Adafruit LSM6DSOX" to "Adafruit LSM6DS"

### ISSUE THREAD

**Issue by ladyada** [arduino/Arduino#9570]
we'll be bumping this to 2.0.0 and renaming library
https://github.com/adafruit/Adafruit_LSM6DS
https://github.com/adafruit/Adafruit_LSM6DS/blob/master/library.properties

**Comment by cmaglie** [comment]
Done.
Done
Done..

**Comment by ladyada** [comment]
awesome, thank u! happy new year :)
