### ISSUE TITLE
[Library Manager] M62429 Volume Control Library

### ISSUE THREAD

**Issue by CGrassin** [arduino/Arduino#9572]
Hello,

I created a very simple library to support the M62429/FM62429 Serial Data Control Dual Electronic Volume (a chip to set an audio attenuation with a 2-wire serial protocol). It should be compliant with the Library Manager guidelines.

Link is here: https://github.com/CGrassin/M62429_Arduino_Library

Could it be possibly added to the Library Manager to make this component easier to use?
Thank you!

**Comment by cmaglie** [comment]
Done.
