### ISSUE TITLE
[Library Manager] J1850-VPW-Arduino-Transceiver-Library

### ISSUE THREAD

**Issue by matafonoff** [arduino/Arduino#9579]
This is an implementation of J1850VPW protocol for Arduino.

https://github.com/matafonoff/J1850-VPW-Arduino-Transceiver-Library

**Comment by per1234** [comment]
That URL gives me a 404 error. Did you maybe forget to make the repository public?

**Comment by matafonoff** [comment]
Yep, sorry! Fixed.

**Comment by matafonoff** [comment]
@per1234 Any updates here?

**Comment by per1234** [comment]
Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by matafonoff** [comment]
@per1234 , thanks for information. Looking forward to it )

**Comment by cmaglie** [comment]
Done.
