### ISSUE TITLE
[Library Manager] add SunEzy / Orion monitoring library to library manger

### ISSUE THREAD

**Issue by guglicap** [arduino/Arduino#9585]
Hi, 
I wrote this library to communicate with SunEzy / Orion inverters, I was wondering if you could add it. 
Please let me know if a name change is needed because although it doesn't start with "Arduino" the name is "arduino-pv". Thanks.

https://github.com/guglicap/arduino-pv

**Comment by per1234** [comment]
Hi @guglicap The restriction on library names starting with "Arduino" applies to any capitalization of the word. If you still want to add you library to the Arduino Library Manager index, you'll need to change the `name` value in library.properties, then either create a new release/tag (after updating the `version` value in library.properties), or redo the existing release/tag.

After doing so, please comment here so we'll know we can proceed.

**Comment by guglicap** [comment]
done, thanks for the quick reply.

**Comment by cmaglie** [comment]
Done.
