### ISSUE TITLE
[Library manager] rename "Adafruit LSM303AGR Mag" to "Adafruit LIS2MDL"

### ISSUE THREAD

**Issue by siddacious** [arduino/Arduino#9587]
We've bumped this to 2.0.0 and renamed the library from "Adafruit LSM303AGR Mag" to "Adafruit LIS2MDL"
https://github.com/adafruit/Adafruit_LIS2MDL/
https://github.com/adafruit/Adafruit_LIS2MDL/blob/master/library.properties

Please update the name in the library manager.

Thanks!

**Comment by cmaglie** [comment]
Done.
Done.

**Comment by ladyada** [comment]
awesome, thank u :)
