### ISSUE TITLE
Please add the Adafruit_SSD1306_Chart library

### ISSUE THREAD

**Issue by elC0mpa** [arduino/Arduino#9593]
I created a display library for Arduino and wonder if you could include it in the IDE library manager.
This library is used to easily draw cartesian charts in displays based on SSD1306 drivers. 
The project and its documentation are available at https://github.com/elC0mpa/Adafruit_SSD1306_Chart

Regards :)

**Comment by ladyada** [comment]
hiya please don't start the name of the library with 'Adafruit' cause adafruit didn't write/support this library :)

**Comment by elC0mpa** [comment]
Ok @ladyada, I already did it and published the library under another name

**Comment by ladyada** [comment]
thank u :)
