### ISSUE TITLE
[Library Manager] Please Change SparkFun HyperDisplay Library Names

### ISSUE THREAD

**Issue by oclyke** [arduino/Arduino#9598]
We've updated the names of our HyperDisplay libraries to be less redundant. At the same time we've also added dependencies and created the latest releases. Please update the names of these libraries so that the indexer will accept them.

Thank you!

New Name - URL
- [x] SparkFun HyperDisplay - https://github.com/sparkfun/SparkFun_HyperDisplay
- [x] SparkFun HyperDisplay ILI9163C - https://github.com/sparkfun/HyperDisplay_ILI9163C_ArduinoLibrary
- [x] SparkFun HyperDisplay SSD1309 - https://github.com/sparkfun/HyperDisplay_SSD1309_ArduinoLibrary
- [x] SparkFun HyperDisplay KWH018ST01- https://github.com/sparkfun/HyperDisplay_KWH018ST01_4WSPI_ArduinoLibrary
- [x] SparkFun HyperDisplay Transparent Graphical OLED - https://github.com/sparkfun/HyperDisplay_UG2856KLBAG01_ArduinoLibrary

**Comment by cmaglie** [comment]
Done.
