### ISSUE TITLE
 false notifications: Multiple libraries were found

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#9601]
I keep getting false notifications: Multiple libraries were found.
I have a simple sketch to demonstrate this.
There is just one library Streaming installed here, on:
D:\Albert\Documents\Arduino\libraries
I searched well on my PC and there is nowhere a second Streaming lib present.

This is the very simple sketch:
```
#include <Streaming.h>

void setup() 
{ m
}

void loop()
{ 
}
```
I
The error Multiple libraries were found for "Streaming.h" is shown
If I delete the m, the result is: compiling done, no further messages

**Comment by per1234** [comment]
I believe this was already fixed by https://github.com/arduino/arduino-cli/pull/478
