### ISSUE TITLE
WIFININA disconnect after 20minutes

### ISSUE THREAD

**Issue by SamirBoussaidi** [arduino/Arduino#9622]
Hello, Arduino MKR1010 with WIFININA and MQTT (PubSubClient) disconnected after 20min. I upgraded WIFININA and I use the last version WIFININA.

**Comment by per1234** [comment]
Hi @SamirBoussaidi. Thanks so much for reporting this.

This issue report doesn't provide sufficient information to allow an investigation. If you are still experiencing this issue, please open a new bug report in the appropriate repository, making sure to provide all the information necessary for us to reproduce the issue:
https://github.com/arduino-libraries/WiFiNINA/issues
