### ISSUE TITLE
warnings from  arduino libraries, [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#963]
This is [Issue 963](http://code.google.com/p/arduino/issues/detail?id=963) moved from a Google Code project.
Added by 2012-06-24T10:48:07.000Z by [drjohnsm...@gmail.com](http://code.google.com/u/104062620417955680065/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

verify just your basic sketch, BUT with warnings turned on.

( I have warnings turned on,as I'm trying to learn better C codding ).

I get the following  warnings,which to me look like library warnigns,
   can we get them fixed please ?

C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\HardwareSerial.cpp: In function 'void store_char(unsigned char, ring_buffer*)':
C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\HardwareSerial.cpp:82: warning: comparison between signed and unsigned integer expressions
C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\HardwareSerial.cpp: In member function 'virtual size_t HardwareSerial::write(uint8_t)':
C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\HardwareSerial.cpp:390: warning: comparison between signed and unsigned integer expressions

also

C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\Print.cpp: In member function 'size_t Print::print(const __FlashStringHelper*)':
C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\Print.cpp:44: warning: '__progmem__' attribute ignored

and

C:\Program Files\Arduino\arduino-1.0.1\hardware\arduino\cores\arduino\Tone.cpp:93: warning: only initialized variables can be placed into program memory area

**Comment by sandeepmistry** [comment]
These warnings no longer occur with the latest AVR core.
