### ISSUE TITLE
[Library Manager] Please add ESP OTA GitHub library

### ISSUE THREAD

**Issue by yknivag** [arduino/Arduino#9636]
Dear Arduino Team,

Could you please add my ESP OTA GitHub library to the library manager?

Repository: https://github.com/yknivag/ESP_OTA_GitHub

Release: https://github.com/yknivag/ESP_OTA_GitHub/releases/tag/0.0.1

Many thanks,

Gavin.

**Comment by cmaglie** [comment]
Done.

**Comment by yknivag** [comment]
Many thanks!
