### ISSUE TITLE
[Library Manager] BlynkGSM_Manager Library

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9637]
https://github.com/khoih-prog/BlynkGSM_Manager

Simple GSM shield Manager for Blynk and ESP32 / ESP8266 boards, with or without SSL, configuration data saved in SPIFFS / EEPROM.
Library is used for configuring/auto(re)connecting GSM shields to Internet and Blynk at runtime.

Thanks and Regards,

**Comment by khoih-prog** [comment]
Add library `depends` and `includes` in `library.properties`
Thanks to @per1234 reminder.

**Comment by cmaglie** [comment]
Done.
