### ISSUE TITLE
[Arduino Create Plugin] installing on debian

### ISSUE THREAD

**Issue by lostsh** [arduino/Arduino#9639]
# Instalation of Arduino Create Agent on Debian 10

Installation of the plugin does not seem to work, however, it can be noted that the process proceeds without apparent problems, and that no error messages are returned, however the plugin does not work.

Source code : [here](https://github.com/arduino/arduino-create-agent/)

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/arduino-create-agent/issues/515
