### ISSUE TITLE
 [Library Manager] Please add Audio - Adafruit Fork to the library manager

### ISSUE THREAD

**Issue by dherrada** [arduino/Arduino#9657]
Please add this library to the library manager:
https://github.com/adafruit/Audio

**Comment by per1234** [comment]
Hi @dherrada libraries added to the Library Manager index are prohibited from containing .exe files. The adafruit/Audio repository contains one at extras/wav2sketch/wav2sketch.exe.

If you still want the library added to the Library Manager index, you'll need to remove the .exe file from the repository and then either create a new tag/release or redo the existing release. You might consider adding the .exe file as an asset of the GitHub release instead. Once that's done, please comment here so we'll know we can proceed.

If you no longer want to add the library to the Library Manager index, you can go ahead and close this issue.

**Comment by dherrada** [comment]
@per1234 I've turned wav2sketch.exe into a zip archive and re-released the library. Does that work?

**Comment by per1234** [comment]
I believe so. If I'm wrong, cmaglie will let us know.

**Comment by cmaglie** [comment]
The library it's ok now, I've added it.
