### ISSUE TITLE
[Library Manager] KniwwelinoLib update repository URL

### ISSUE THREAD

**Issue by lazyzero** [arduino/Arduino#9670]
Hello,
https://github.com/kniwwelino/KniwwelinoLib

can you update the url library manager is using for KniwwelinoLib from 
https://github.com/LIST-LUXEMBOURG/KniwwelinoLib
to
https://github.com/kniwwelino/KniwwelinoLib

Thanks in advance
Christian

**Comment by cmaglie** [comment]
Done.
