### ISSUE TITLE
Despite web creator saying otherwise Fast led doesnt work on nano 33 iot.

### ISSUE THREAD

**Issue by S-A-M-J** [arduino/Arduino#9674]
Arduino web creator says its compatible but it doesnt work. However it does compile. Please fix

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar). Please also provide a detailed description of what you mean by "it doesnt work"
