### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status  exit status 1 Error compiling for board Arduino Nano.

### ISSUE THREAD

**Issue by olaray0406** [arduino/Arduino#9688]
Hello all.
i have been have this issue, 
collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Nano.
after it finish my code all that i did to stop is not working.
this is the code below.
#include <OneWire.h>
#include <DallasTemperature.h>
#include <Wire.h> 
#include <LiquidCrystal.h>
#include <NewPing.h>

#define ONE_WIRE_BUS 8 
#define motor 9  
#define trigPin  10
#define echoPin  11
#define buzzer 12

LiquidCrystal lcd(2,3,4,5,6,7);

NewPing sonar(trigPin, echoPin);
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature sensors(&oneWire); 

float duration,distance,height,volume,litre;
float Celcius=0;
float PVTemp  = Celcius; 

void setup() {
 Serial.begin(9600);
 Wire.begin();                                  // Join i2c bus
 sensors.begin();
 lcd.begin(16,2);
 pinMode(trigPin, OUTPUT);       //Define inputs and outputs
 pinMode(echoPin, INPUT);
 pinMode(motor,OUTPUT);
 pinMode(buzzer,OUTPUT);
 lcd.setCursor(2,0);
 lcd.print("FLUID VOLUME");
 lcd.setCursor(4,1);
 lcd.print("DISPLAY");
 delay(3000);             

}

void loop() {

 digitalWrite(trigPin, LOW);
 delayMicroseconds(2);
 digitalWrite(trigPin, HIGH);
 delayMicroseconds(10);
 digitalWrite(trigPin, LOW);
 pinMode(echoPin, INPUT);
 
 sensors.requestTemperatures(); 
 Celcius = sensors.getTempCByIndex(0);
 PVTemp = Celcius;
 int iterations = 5;
 duration = sonar.ping_median(iterations);
 distance = duration*0.0343/2;
 height = 16 - distance;
 volume = height*330.106375;
 litre = volume/1000;

 Serial.print("VOLUME OF FLUID: ");
 Serial.print(volume);
 Serial.print("Cubic cm ");
 Serial.print(litre);
 Serial.print("lit");
 Serial.println();

 lcd.clear();
  lcd.print("VOLUME OF FLUID");
  lcd.setCursor(0,1);
  lcd.print(volume);
  lcd.setCursor(7,1);
  lcd.write(byte(0));
  lcd.setCursor(8, 1);
  lcd.write(byte(1));
  lcd.setCursor(10,1);
  lcd.print(litre);
  lcd.print("L");
 delay(4000);
 
 if(litre < 1.3)      
 {
 digitalWrite(motor,HIGH);
 digitalWrite(buzzer,LOW);
 lcd.clear();
 lcd.print("PUMP ON");
 lcd.setCursor(0,1);
 lcd.print("MOTOR RUNNING");
 delay(1000);
 }
  else if(litre > 3.5)
 {
 digitalWrite(motor,LOW);
 digitalWrite(buzzer,HIGH);
 lcd.clear();
 lcd.setCursor(2,0);
 lcd.print("VESSEL FULL");
 lcd.setCursor(2,1);
 lcd.print("MOTOR STOPS");
 digitalWrite(buzzer, LOW);
 delay(1000);
 } 
  delay (200);
}

and the is the error message.

Arduino: 1.8.11 (Windows 10), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::validFamily(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setOneWire(OneWire*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature(OneWire*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature(OneWire*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getDeviceCount()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getDS18Count()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::validAddress(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getAddress(unsigned char*, unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::readScratchPad(unsigned char const*, unsigned char*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::readPowerSupply(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getResolution()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setWaitForConversion(bool)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getWaitForConversion()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setCheckForConversion(bool)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getCheckForConversion()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::isConversionComplete()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::millisToWaitForConversion(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::activateExternalPullup()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::deactivateExternalPullup()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setPullupPin(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature(OneWire*, unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::DallasTemperature(OneWire*, unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::writeScratchPad(unsigned char const*, unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::blockTillConversionComplete(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::requestTemperatures()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::calculateTemperature(unsigned char const*, unsigned char*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::isParasitePowerMode()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::toFahrenheit(float)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::toCelsius(float)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::rawToCelsius(int)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::rawToFahrenheit(int)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::isAllZeros(unsigned char const*, unsigned int)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::isConnected(unsigned char const*, unsigned char*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::isConnected(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getResolution(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::begin()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::requestTemperaturesByAddress(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::requestTemperaturesByIndex(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setResolution(unsigned char const*, unsigned char, bool)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setResolution(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getTemp(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getTempC(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getTempCByIndex(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getTempF(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getTempFByIndex(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getUserData(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getUserDataByIndex(unsigned char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setUserData(unsigned char const*, int)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setUserDataByIndex(unsigned char, int)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getHighAlarmTemp(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setHighAlarmTemp(unsigned char const*, signed char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::getLowAlarmTemp(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setLowAlarmTemp(unsigned char const*, signed char)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::resetAlarmSearch()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::alarmSearch(unsigned char*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::hasAlarm(unsigned char const*)'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::hasAlarm()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::processAlarms()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::setAlarmHandler(void (*)(unsigned char const*))'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature.cpp.o (symbol from plugin): In function `DallasTemperature::DallasTemperature()':

(.text+0x0): multiple definition of `DallasTemperature::hasAlarmHandler()'

libraries\Arduino-Temperature-Control-Library-master\DallasTemperature (2).cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

Multiple libraries were found for "OneWire.h"
 Used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\OneWire
 Not used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\OneWire-master
Multiple libraries were found for "DallasTemperature.h"
 Used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\Arduino-Temperature-Control-Library-master
 Not used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\milesburton-Arduino-Temperature-Control-Library-5021c28
Multiple libraries were found for "NewPing.h"
 Used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\NewPing
 Not used: C:\Users\isaia\OneDrive\Documents\Arduino\libraries\teckel12-arduino-new-ping-2ebf391d9be2
exit status 1
Error compiling for board Arduino Nano.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
