### ISSUE TITLE
[Library Manager] Add ServoESP32 library to the Library Manager

### ISSUE THREAD

**Issue by JarekParal** [arduino/Arduino#9690]
Please could you add the ServoESP32 library to the Library Manager:
https://github.com/RoboticsBrno/ServoESP32

Thank you.

**Comment by platisd** [comment]
:eyes:

(leaving a comment so to get notified once this is included :stuck_out_tongue:)

**Comment by cmaglie** [comment]
Done.

@platisd you can subscribe to the issue without posting the comment (just use the "Subscribe" button on the right column)

**Comment by platisd** [comment]
> Done.
> 
> @platisd you can subscribe to the issue without posting the comment (just use the "Subscribe" button on the right column)

That I hadn't realized. Thanks for including it in the Library Manager @cmaglie :+1:
