### ISSUE TITLE
Arduino IDE CI - automatically build and test the IDE itself

### ISSUE THREAD

**Issue by tlk** [arduino/Arduino#9697]
I noticed some Arduino IDE tests were failing when I ran them, fx #9695. Having failing tests in the code base suggests that the code base is not being tested on a regular basis. This can discourage new developers from taking advantage of existing tests and might lead to reduced software quality over time.

For remediation I suggest increasing the visibility of existing tests. There are several ways this can be done, fx Travis-CI and recently GitHub has started to offer free CI services for public repositories via GitHub Actions.

I have experimented with GitHub Actions to automatically build and test the Arduino IDE itself.

Please see PR #9696 and https://github.com/tlk/Arduino/runs/419140962 for a working example.

Thoughts?

**Comment by cmaglie** [comment]
Fixed by #9696 thank you!
