### ISSUE TITLE
IDE window doesn't release keyboard focus on XFCE

### ISSUE THREAD

**Issue by spheroidx** [arduino/Arduino#9702]
**OS: Debian (various, up to at least 9.11) x64 with XFCE4 
IDE version: various, 1.8.11 included**

Issue occurs whenever opening other windows (save dialog/serial monitor/etc or even other programs). New windows appear to be active and in focus, but the IDE will receive all keyboard input until the new window is manually selected.

I've been able to recreate this issue on several computers with various versions of the IDE and OS (although XFCE4 is a constant). Issue also occurs on a fresh install of the OS with only the IDE (and ancillary software) installed.

**Comment by facchinm** [comment]
Hi @spheroidx ,
thanks for reporting. I think it could be a java <-> XFCE specific bug but I couldn't find any similar report on the internet (and it doesn't happen on any other desktop environment). Would you mind opening an issue on XFCE mailing list or repo so they are aware? Thanks
