### ISSUE TITLE
New library - EEPROMAdapter

### ISSUE THREAD

**Issue by Wh1teRabbitHU** [arduino/Arduino#9705]
Dear administrator!

I made my first public library. You can find it on the following link:
https://github.com/Wh1teRabbitHU/EEPROMAdapter

Please add this library to the Arduino Manager index.

Thank you!

**Comment by cmaglie** [comment]
I added the library to the indexer but there is a problem: I see that you already fixed library.properties by merging https://github.com/Wh1teRabbitHU/EEPROMAdapter/pull/1 but you forget to update the git tag `1.0.1` (that in fact it points to an older version of the file https://github.com/Wh1teRabbitHU/EEPROMAdapter/blob/1.0.1/library.properties).

To fix this please:

1. Remove the current tag `1.0.1`
2. Re-do the tag on master

once done the library will be automatically published within an hour.
