### ISSUE TITLE
I2C slave_writer

### ISSUE THREAD

**Issue by privatier51** [arduino/Arduino#9708]
On page [https://www.arduino.cc/en/Tutorial/MasterReader](https://www.arduino.cc/en/Tutorial/MasterReader) the slave part should be slave_writer. The code shown is for slave_receiver, which is used in the Master Writer/Slave receiver example.

**Comment by per1234** [comment]
Closing in favor of https://github.com/arduino/Arduino/issues/9740.

Although this report came first, the other contains slightly more information. Since one of the two must be closed, I'll give the other preference.

Thanks so much for reporting this error @privatier51!
