### ISSUE TITLE
[Library Manager] Arduino-TR-064-SOAP-Library

### ISSUE THREAD

**Issue by Aypac** [arduino/Arduino#9711]
Please add the following library
https://github.com/Aypac/Arduino-TR-064-SOAP-Library

**Comment by per1234** [comment]
Hi @Aypac. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Aypac** [comment]
Oh sorry. Done that now.

**Comment by cmaglie** [comment]
Done.
