### ISSUE TITLE
A new library for Library Manager - LibAPRS_Tracker

### ISSUE THREAD

**Issue by barisdinc** [arduino/Arduino#9721]
LibAPRS_Tracker is a library for the Arduino IDE, that makes it easy to design and implemet your own APRS Tracker devices for sending out your location, telemetry, etc. The hardware is Micromodem compiant using resistor ladder on pins D4,5,6,7. The PTT pin is D3. All the AFSK modulation, AX.25 packing, and such is running transparently in the “background” in interrupts."

https://github.com/barisdinc/LibAPRS_Tracker

**Comment by cmaglie** [comment]
Done.
