### ISSUE TITLE
Unable to Run a code in Arduino Due

### ISSUE THREAD

**Issue by Malaidevan** [arduino/Arduino#9725]
I couldn't install Arduino Due Board using the device manager, hence downloaded offline and tried the steps provided online...

Arduino Due got installed but while even compiling the code got the error

> exec: "/bin/arm-none-eabi-g++": file does not exist

Please help me overcome this error

I tried the following link: https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation

**Comment by facchinm** [comment]
Hi @Malaidevan ,
you should install "Arduino SAM" core from Board manager to use the Due.
I'm closing the issue since this repo is intended just for Arduino IDE issues. If you need further help, please write on the [forum](https://forum.arduino.cc/), thanks.
