### ISSUE TITLE
[Library Manager] Please add CppPotpourri to the Library Manager

### ISSUE THREAD

**Issue by jspark311** [arduino/Arduino#9729]
https://github.com/jspark311/CppPotpourri

Thank you!

**Comment by per1234** [comment]
Hi @jspark311. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by jspark311** [comment]
Done. Sorry about the oversight.

**Comment by cmaglie** [comment]
Done.
