### ISSUE TITLE
[Library Manager] add slight_* libs

### ISSUE THREAD

**Issue by s-light** [arduino/Arduino#9731]
please add my libraries

- [x] https://github.com/s-light/slight_Fade
- [x] https://github.com/s-light/slight_ButtonInput
- [x] https://github.com/s-light/slight_RotaryEncoder
- [x] https://github.com/s-light/slight_DebugMenu
- [x] https://github.com/s-light/slight_TLC5957
- [x] https://github.com/s-light/slight_FDC1004
- [x] https://github.com/s-light/slight_LiquidCrystalDummy

to the library index.

thanks :-)
sunny greetings
stefan

**Comment by cmaglie** [comment]
Done.

**Comment by s-light** [comment]
Thanks! :-)
