### ISSUE TITLE
Arduino IDE 1.8.11 quits unexpectedly ~1 hour after opening on mac 10.15.3, no code running.

### ISSUE THREAD

**Issue by crs10** [arduino/Arduino#9732]
Ardunio IDE quits unexpectedly when program is minimized (not running) after being open for 30 mins - a couple of hours (aka does not crash right after opening). I've attached the full crash report as a pdf. 
[Arduino_Crash_report.pdf](https://github.com/arduino/Arduino/files/4172731/Arduino_Crash_report.pdf)

**Comment by crs10** [comment]
The software is also not recognizing my device even though I can run the "blink" program on the web app

**Comment by cmaglie** [comment]
Duplicate of #9747 let's follow up on there.
