### ISSUE TITLE
Arduino 1.8.11 Library Manager: Comparison method violates its original contract.

### ISSUE THREAD

**Issue by rei-vilo** [arduino/Arduino#9738]
On the Arduino 1.8.11 IDE, when calling the menu **Sketch > Include Library > Manage Libraries** and asking the list of updatable librairies, the **Library Manager** displays the following error message:

> Comparison method violates its original contract.

<img width="800" alt="Capture d’écran 2020-02-08 à 15 36 28" src="https://user-images.githubusercontent.com/951776/74087058-2c27c400-4a89-11ea-85c0-11efc32be82f.png">

+ What does it mean?
+ How to get rid of it?

Thank you!

**Comment by cmaglie** [comment]
A possible explanation is here: #9748 

May you try the pull-requrest build to see if it solves the problem?

**Comment by rei-vilo** [comment]
Thank you! `arduino-PR-9748-BUILD-918-macosx` seems to solve the issue with the Library Manager.

**Comment by BigGene** [comment]
Just had this error using Arduino IDE 1.8.13.

**Comment by MortenHofft** [comment]
I just installed the software (Arduino IDE 1.8.19 downloaded from https://www.arduino.cc/en/software) for the first time and sees this as the first thing.

<img width="796" alt="Screenshot 2022-02-08 at 20 56 09" src="https://user-images.githubusercontent.com/6759267/153065496-b0267587-cf95-4450-8fbb-310043d6b511.png">

OS: Catalina 10.15.7
