### ISSUE TITLE
[Library Manager] update repository of InfluxDb Client

### ISSUE THREAD

**Issue by tobiasschuerg** [arduino/Arduino#9744]
My influx db client (initially added in #7767) got completely rewitten and the repository name was changed as well. It's now 

https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino

Although the "old" url still forwards to the new url posted above, I'm not sure if the *Library Manager* will follow that redirect and updates will still be recognized, therefore this ticket to update the repostiory if necessary.

**Comment by cmaglie** [comment]
Done.
