### ISSUE TITLE
I'm having delayed values from the esp32 (Firebase)

### ISSUE THREAD

**Issue by nourrhibi** [arduino/Arduino#9749]
i have a esp32 card connected to firebase database realtime and i want to get 2 values from the firebase whenever there is a changed value, the problem is that i do get the values but it slows down the rest of my code, and if i remove the code where i'm getting values from the firebase, everything works just fine.
I think the fact that im always receiving data slows down the esp32 card.
so is there a solution where i can get data from Firebase whenever it changes ?

here's a sample of my code :

#include <Keypad.h>
#include <Wire.h> 
#include <WiFi.h>
#include <FirebaseESP32.h>

#define WIFI_SSID "dlink"             

                                           
#define FIREBASE_HOST "--------------------"                      
#define FIREBASE_AUTH "------------------"        

const byte ROWS = 4; //four rows

const byte COLS = 4; //three columns

char keys[ROWS][COLS] = {

  {'1','2','3','A'},

  {'4','5','6','B' },

  {'7','8','9','C'},

  {'*','0','#','D'}

};

byte rowPins[ROWS] = {14, 27, 26, 25}; //connect to the row pinouts of the keypad

byte colPins[COLS] = {33, 32, 13, 12}; //connect to the column pinouts of the keypad

Keypad keypad = Keypad( makeKeymap(keys), rowPins, colPins, ROWS, COLS );

FirebaseData firebaseData;
int pos=0;
char password[5] ="1234";
char inputKey[16];

void setup(){
   Serial.begin(115200);
  WiFi.begin(WIFI_SSID);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
 
 Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);             //connect to Database
  delay(1000);

}

void loop(){
 
    Firebase.getInt(firebaseData,"state",state);
    Serial.println(state);
    Firebase.getString(firebaseData,"Motdepasse",pass);
    Serial.println(pass);
    pass.toCharArray(password, 5);

  
char whichKey = keypad.getKey();

if(whichKey)
    {
      if(whichKey == '*' || whichKey == '#'  || whichKey =='C' )
      {
     
      Serial.println("Invalid Key!");
      }
      else if(whichKey != 'D' && whichKey != 'A')
      {
    
       inputKey[pos]=whichKey;
       Serial.println(whichKey);
       pos++;
       
      }
     

    if(whichKey =='D' && pos >0)
     { 
      Serial.println("Deleted key");
      pos--;
      inputKey[pos]=NULL;  
    
           
     }

    if(whichKey =='A')
    {
       int i=0;
       boolean test = true;
       while( pos == 4 && i<pos && test == true)
        {
          if(inputKey[i] == password[i])
          {
           i++;
          }
          else
          test =false;
       }
    }
    
   }
 
}

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
