### ISSUE TITLE
[Library Manager] new libraries

### ISSUE THREAD

**Issue by rgot-org** [arduino/Arduino#9751]
Please can you add these libraries 
https://github.com/rgot-org/TTN_M5Stack
https://github.com/rgot-org/TheThingsNetwork_esp32
thanks !

**Comment by per1234** [comment]
Hi @rgot-org. In each of the repositories, you need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by rgot-org** [comment]
i've made the release 0.0.1

**Comment by cmaglie** [comment]
Done.
