### ISSUE TITLE
[Library Manager] ESP8266_AT_Web_Server for ESP8266 AT-Command Shields

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9754]
https://github.com/khoih-prog/ESP8266_AT_WebServer

This is simple yet complete WebServer library for `AVR, Teensy, etc.` boards running `ESP8266 AT-command` shields. The functions are similar and compatible to ESP8266/ESP32 WebServer libraries to make life much easier to port sketches from ESP8266/ESP32.

The library supports 
1. WiFi Client, STA and AP mode
2. TCP Server and Client
3. UDP Server and Client
4. HTTP Server and Client
5. HTTP GET and POST requests, provides argument parsing, handles one client at a time.

**Comment by cmaglie** [comment]
Done.
