### ISSUE TITLE
[Library manager] https://github.com/adafruit/Adafruit_nRFCrypto

### ISSUE THREAD

**Issue by hathach** [arduino/Arduino#9755]
hi hi,

We have just added an new library to make the usage of ARM CryptoCell on nrf52840 easier with some initial Hashing and ECC (enough to pass DH Key authentication for LESC pairing). 

https://github.com/adafruit/Adafruit_nRFCrypto

Thank you very much

@ladyada

**Comment by cmaglie** [comment]
Done.

**Comment by hathach** [comment]
Thank you very much ☺☺
