### ISSUE TITLE
Add option to go to a line number in the IDE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#976]
This is [Issue 976](http://code.google.com/p/arduino/issues/detail?id=976) moved from a Google Code project.
Added by 2012-07-06T21:50:06.000Z by [jainh...@gammon.com.au](http://code.google.com/u/103215857083197440315/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE

### Original description

**What change would like to see?**

A dialog box (from a menu, preferably with a hot-key equivalent) that lets you "go to line X" in the IDE window.

**Why?**

Error messages list line numbers. Whilst the first error is usually highlighted, attempting to fix subsequent errors by line number reference is tedious.

Implementation should be simple, as already there must be code internally to go to a line, as it does so for the first error.

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**

No.

**Comment by ffissore** [comment]
Fixed. Fix will be available with next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by bkelly13** [comment]
It is now September 2019, four years later.  Has this feature been added?  If so, how is it used.  If not, please add it back in to the list.
1.  A ctl-something 123   keystroke sequence to go to that line number
2.  In the compile error messages, click or double click on the error line and go to that line.

Thank you for your time.

**Comment by facchinm** [comment]
`CTRL+L` exposes you a small prompt to go to a line. Click on error has been implemented in a fork but the patch was never submitted
