### ISSUE TITLE
[Library Manager] Please add four hardware driver libraries to the Library Manager

### ISSUE THREAD

**Issue by jspark311** [arduino/Arduino#9765]
- [x] [https://github.com/jspark311/Arduino-SX8634](https://github.com/jspark311/Arduino-SX8634)
- [x] [https://github.com/jspark311/Arduino-SX150x](https://github.com/jspark311/Arduino-SX150x)
- [x] [https://github.com/jspark311/Arduino-ADG2128](https://github.com/jspark311/Arduino-ADG2128)
- [x] [https://github.com/jspark311/Arduino-DS1881](https://github.com/jspark311/Arduino-DS1881)

Thank you!

**Comment by cmaglie** [comment]
Done.
