### ISSUE TITLE
Get download count of library 

### ISSUE THREAD

**Issue by AIS-DeviceInnovation** [arduino/Arduino#9774]
How to get download count of the library?

**Comment by MisterAwesome23** [comment]
Hey @AIS-DeviceInnovation 

Do you mean a download count of "AIS_NB_BC95" library in your case and want to know/log/display number of downloads?

Or is it something different altogether?

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/7265
