### ISSUE TITLE
[Library Manager] Blynk & WiFiManager for Mega/Teensy boards running ESP8266 AT shields

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9776]
https://github.com/khoih-prog/Blynk_Esp8266AT_WM

To help you to eliminate `hardcoding` your Wifi and Blynk credentials for Mega/Teensy boards running ESP8266 AT shields, and updating/reflashing every time when you need to change them. Configuration data are saved in configurable locatioon in EEPROM.

With version `v1.0.0` or later, you now can configure:

1. `Config Portal Static IP address, Name and Password.`
2. `Static IP address, Gateway, Subnet Mask and 2 DNS Servers IP addresses.`

**Comment by cmaglie** [comment]
Done.
