### ISSUE TITLE
Arduino IDE crashes if Mac lid closed and connected to ext. monitor

### ISSUE THREAD

**Issue by mdelag** [arduino/Arduino#9778]
As the title says, IDE crash occurs when shifting from open lid to closed lid and connected to external monitor and viceversa.

MacOS Catalina 10.15.3
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

**Comment by per1234** [comment]
@mdelag is it the same error reported here: https://github.com/arduino/Arduino/issues/9764?

**Comment by mdelag** [comment]
@per1234 looks like it's a similar setup.

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/Arduino/issues/9764
