### ISSUE TITLE
No client conection when static IP assigned [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#978]
This is [Issue 978](http://code.google.com/p/arduino/issues/detail?id=978) moved from a Google Code project.
Added by 2012-07-08T17:53:07.000Z by [holmess_...@yahoo.com](http://code.google.com/u/115938183122612975748/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. I have a MEGA 2560 and a Arduino Ethernet Shield. Running Arduino 1.0.1
2. I have tested with several provided "Examples" and built my own. DHCP works fine. When statically assigning addresses, the Arduino can not connect to anything. Not even on the same subnet.
**3.**

**What is the expected output? What do you see instead?**
Expect to see "Connected". I get "Connection Failed"

What version of the Arduino software are you using? 1.0.1
On what operating system? Windows XP
Which Arduino board are you using? MEGA 2560

**Please provide any additional information below.**
Changed the "telnet client" to port 80 and my Linksys Router. Works fine if I don't give an IP address (DHCP). Does not work with the IP specified. I have does this test using several differnt sketchs including one I made seen here. http://arduino.cc/forum/index.php/topic,113332.msg852735.html

I'm new at his but... I really don't think I'm doing anything wrong. If I am, PLEASE set we stright. :)

Thanks,
Scott
holmess_1231@yahoo.com

**Comment by sandeepmistry** [comment]
Closing based on @mk-git's comment, incorrect arguments where passed into ```EthernetClass::begin```.
