### ISSUE TITLE
[Library Manager] Please update MODI-library

### ISSUE THREAD

**Issue by hanj-kim** [arduino/Arduino#9784]
https://github.com/LUXROBO/MODI-Arduino/releases/tag/0.0.2

Thank you very much!

**Comment by per1234** [comment]
Hi @hanj-kim. The Arduino Library Manager indexer job regularly scans all the repositories in the index for new tags. Any new tag that meets [the requirements](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) is automatically added. In fact, I see your 0.0.2 release has already been added.

So there is no need to submit a request here for every release. Once your library has been added to the index, everything else happens automagically!
