### ISSUE TITLE
Nano EVERY mis-identified

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/Arduino#9788]
In IDE 1.8.12 there appears to be an issue with the nano every being categorised wrongly.
It is identifies as a 328 !

Global variables use 31 bytes (0%) of dynamic memory, leaving 6113 bytes for local variables. Maximum is 6144 bytes.
avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description

![2020-02-20 at 09-10-59 incorrectly identified](https://user-images.githubusercontent.com/8212730/74941647-5f3f5100-53c1-11ea-8fab-b086d5870c77.jpg)

CREATE editor does not have the issue so it seems to be confined to desktop IDE's

Using the "toneMelody" example from "digital examples" seems to express the issue well.

**Comment by BallscrewBob** [comment]
Update.
Also appears in 1.8.11
Recently updated all the cores so maybe it is a core issue ?

**Comment by facchinm** [comment]
Hi @BallscrewBob,
the part after the comma is the "additional menu" config (and it means the core is able to compile some code with ATMega328 compatibility).
You can switch back to 4809 "plain" under Tools menu

**Comment by BallscrewBob** [comment]
Just saw the 4809 option.
Switched  but same issues so guess tone examples wont run on the every.
