### ISSUE TITLE
[Library Manager] Please add DarkSkySevenDay to Library Manager

### ISSUE THREAD

**Issue by JHershey69** [arduino/Arduino#9789]
https://github.com/JHershey69/DarkSkySevenDay

**Comment by JHershey69** [comment]
push

**Comment by cmaglie** [comment]
Done. Sorry for the long delay.

**Comment by JHershey69** [comment]
Thanks! No worries on the delay.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
