### ISSUE TITLE
Add a list of recently opened files in the editor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#979]
This is [Issue 979](http://code.google.com/p/arduino/issues/detail?id=979) moved from a Google Code project.
Added by 2012-07-09T00:44:46.000Z by [ericzun...@gmail.com](http://code.google.com/u/107675318329982835686/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Component-IDE

### Original description

I have a patch that adds an item to the File menu. 

Here's a screenshot

 http://ayershome.org/users/eric/software/open-recent-screenshot.png

Forum post:

  http://arduino.cc/forum/index.php/topic,113366.0.html

**Comment by ffissore** [comment]
Fixed in latest hourly build http://www.arduino.cc/en/Main/Software#hourly
