### ISSUE TITLE
TFT Library - avr/pgmspace.h and PImage class - OLD ST7735 libs used

### ISSUE THREAD

**Issue by kevinmorrisone** [arduino/Arduino#9790]
https://www.arduino.cc/en/Reference/TFTLibrary is said to "extend the ST7735 libraries which it is based on" the TFT lib unfortunately uses old "includes" as below referencing:  pgmspace.h, io.h.

Also PImage class is broken.  

Workaround : copy the latest files listed below FROM the 7735 Adafruit library TO the TFT src <src> folder and then is ok functionality but does not resolve PImage.

GFX.h
GFX.cpp
ST7735.cpp
ST7735.h
glcdfont.c

This affects tutorial and entire library TFT and disappointing as library is "standard" and not a variant or third party but is built from.  Please make basic file changes but also PImage class needs some finesse.

**Comment by per1234** [comment]
Transferred to https://github.com/arduino-libraries/TFT/issues/23
