### ISSUE TITLE
Arduino Pro Gateway LoRa® - Offline in Arduino device manager

### ISSUE THREAD

**Issue by jQrgen** [arduino/Arduino#9791]
Problem: 
Arduino Pro Gateway LoRa is always offline in the Arduino device manager after adding S/N.

I have connected the gateway raspberry pi to a monitor, keyboard, and mouse to debug it. When pinging 8.8.8.8 in the terminal the gateways shows to have internet connectivity.

Therefore I think there is a bug in the pre-installed software.

Any directions?
Thanks

**Comment by racpra16** [comment]
Hello Jørgen,
To follow up on your case for pro-Lora gateway query
via Serial Number, can you please raise your query on support@arduino.cc for technical purpose
so that we will be in direct contact with you and help you to solve your query as soon as possible.

Thanks, 
//Rachit
