### ISSUE TITLE
Can we create multiple services with multiple characteristics in a server using BLE in Arduino IDE? If yes, how? I tried creating two services with unique UUID but i am able to only see one service

### ISSUE THREAD

**Issue by AmishaKuwarbi** [arduino/Arduino#9797]
I am using a BLE scanner to connect to my server. How can i i get at least two services with multiple characteristics?
Also, is there a specific byte size that a service can hold and each characteristic should maintain?
![ble](https://user-images.githubusercontent.com/46739282/75088608-abcb8d80-5575-11ea-893f-2fde19f90d11.jpg)

**Comment by per1234** [comment]
From your other comment, it apears you are using an ESP32. This tracker is only for problems with official Arduino software, not 3rd party software, as is used for BLE on your ESP32. So I'm going to close this as off-topic.

You're welcome to ask for help on the Arduino forum:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
