### ISSUE TITLE
[Library Manager] add SevSegShift to the Library Manager

### ISSUE THREAD

**Issue by bridystone** [arduino/Arduino#9798]
Please add my SevSegShift library to the Library Manager?
https://github.com/bridystone/SevSegShift
Latest release:
https://github.com/bridystone/SevSegShift/releases/tag/v3.4.2

It's a fork of SevSeg that adds Shift Register functionality.
In agreement with original developer he rather wants to have it as a fork.

Thanks in advance!
Jens

**Comment by cmaglie** [comment]
Done. Sorry for the long delay.
