### ISSUE TITLE
[Library Manger] Remove Arduino LoraWAN

### ISSUE THREAD

**Issue by sabas1080** [arduino/Arduino#9804]
Hello,

we have seen that our library is duplicated due to the name change that happened
Remove please **"Arduino LoraWAN by Beelan"**

<img width="806" alt="Captura de Pantalla 2020-02-25 a la(s) 15 40 51" src="https://user-images.githubusercontent.com/2874292/75290063-3c5bd500-57e5-11ea-87c9-f5efb6fa7f07.png">

Thanks.

**Comment by cmaglie** [comment]
Oh, sorry, I forget to remove the old one. Now it's done.
