### ISSUE TITLE
[Library Manager] BlynkEthernet_STM32_Manager library for STM32 boards

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9820]
https://github.com/khoih-prog/BlynkEthernet_STM32_WM

### New Releases v1.0.0

1. Add support to STM32 boards with built-in Ethernet, ENC28J60 or W5x00 Ethernet shields

- This is the new library, adding to the current Blynk_WiFiManager. It's designed to help you eliminate `hardcoding` your Blynk credentials in _STM32_ boards using with Ethernet (**Built-in, W5100, W5200, W5500, ENC28J60**, etc). It's currently not supporting SSL and can not saved config data to non-volatile memory (EEPROM, battery-saved SRAM, SPIFFS, etc.), will fix in next releases.
- You can update Blynk Credentials any time you need to change via Configure Portal. Data to be saved in configurable locations in EEPROM.

This library currently supports
1. STM32 boards with built-in Ethernet such as :
  - ***Nucleo-144 (F429ZI, F767ZI)***
  - ***Discovery (STM32F746G-DISCOVERY)***
  - ***All STM32 Boards with Built-in Ethernet***, See [How To Use Built-in Ethernet](https://github.com/khoih-prog/EthernetWebServer_STM32/issues/1)
2. ***STM32 boards (with 64+K Flash) running ENC28J60 shields***
3. ***STM32 boards (with 64+K Flash) running W5x00 shields***

**Comment by cmaglie** [comment]
Done.
