### ISSUE TITLE
Request: don't clear serial buffer when disconnecting USB or uploading new firmware

### ISSUE THREAD

**Issue by JetForMe** [arduino/Arduino#9821]
It would be nice if it was possible to keep the serial buffer contents when disconnecting the USB serial port, or when uploading new firmware. Currently, either of these actions cause the buffer to be cleared.

**Comment by per1234** [comment]
By "serial buffer", do you mean the contents of Serial Monitor? If so, this is a duplicate of https://github.com/arduino/Arduino/issues/9234, which was already fixed by https://github.com/arduino/Arduino/pull/9644.

**Comment by PaulStoffregen** [comment]
What version of Arduino are you using?

Wasn't this released in version 1.8.12?

**Comment by JetForMe** [comment]
Oh! Yes! I was on 1.8.10.
