### ISSUE TITLE
[Library Manager] Functional Vlpp Library to support many more architectures besides AVR

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9825]
https://github.com/khoih-prog/functional-vlpp

The original [vczh-libraries/Vlpp](https://github.com/vczh-libraries/Vlpp) provides common C++ construction, including string operation / generic container / linq, function templates to better support ***C++ functional programming across platforms***. 

The `functional portion` of the project was then forked and modified to be used for Arduino by [Marcus Rugger functional-vlpp library](https://github.com/marcusrugger/functional-vlpp). 

This library is forked, modified to use and tested working ***OK*** in other architectures such as ***Teensy, SAM, SAMD, stm32, eps8266, esp32***.

This library can be used as a replacement of C++11 STL `std::function`. 
For example, we can use `typedef vl::Func<void(void)> THandlerFunction` instead of `typedef std::function<void(void)> THandlerFunction` or `typedef void (*THandlerFunction)(void)`.

Its importance is the ability to be used in complicated function calls, such as private Lambda functions in Classes.

**Comment by cmaglie** [comment]
Done.
