### ISSUE TITLE
[Library Manager] Please add

### ISSUE THREAD

**Issue by peterus** [arduino/Arduino#9832]
Please add my libs to the library manager.

- [x] https://github.com/peterus/APRS-Decoder-Lib
- [x] https://github.com/peterus/APRS-IS-Lib

Thanks!
Peter

**Comment by per1234** [comment]
Hi @peterus. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by peterus** [comment]
Hi @per1234 
Sorry, totally missed to create a tag. Was creating it now ;)

**Comment by peterus** [comment]
please add https://github.com/peterus/APRS-Decoder-Lib too :)
thank you!

**Comment by cmaglie** [comment]
Done.
