### ISSUE TITLE
Add Atmega1284P support to Servo.h [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#984]
This is [Issue 984](http://code.google.com/p/arduino/issues/detail?id=984) moved from a Google Code project.
Added by 2012-07-14T13:09:37.000Z by [jcnos...@earthlink.net](http://code.google.com/u/113329122905643287979/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

What change would like to see? Please add Atmega1284P support to Servo.h.  Though it can be done manually, it could be included in an official release.

Why? The 1284P is capable of 24 servos, but defaults to 12 with the current file.

**Would this cause any incompatibilities with previous versions?  If so, how**
can these be mitigated?  Unknown...

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Servo#4
