### ISSUE TITLE
Progmem usege has different results depending on where is what defined or when what is called

### ISSUE THREAD

**Issue by andreobi** [arduino/Arduino#9845]
Hi,
I want to have a string array in the prog mem. copying the hohle string works fine. Trying to access single characters from the strings brings up different results depending on what is defined or when what is accessed.
won't work
```c++
  er(GPS_Header_table,0);
  hxt=GPS_Header_table;
  er(hxt,0);
//  er(hxt,0);
  er(hxt,1);
```
works fine
```c++
  er(GPS_Header_table,0);
  hxt=GPS_Header_table;
  er(hxt,0);
//  er(hxt,0);
//  er(hxt,1);
```
Please play around with the attached file, there are a lot of possible combinations, some of them work, some just won't. The interessing part is, that in my example there is also an influence from the call `er(hxt,1)` on the upper code?!? I realy don't know what happends there. There is also an influence if the pointer is definded localy or global.
The program was tested on an UNO.

[progmem.txt](https://github.com/arduino/Arduino/files/4300667/progmem.txt)
Regards
Andre

**Comment by WestfW** [comment]
```
const char *const GPS_Header_table[] PROGMEM = {GPS_Header_0,GPS_Header_1};
   :
    c=pgm_read_word_near((headerTab[idx])+i);
```
You need to read BOTH the pointer and the char from flash:
```
const char *p = pgm_read_word_near(&headerTab[idx]);
char p = pgm_read_byte(idx+i);
```

Some cases may work because they manage to be optimized to simple constant loads at compile time.
