### ISSUE TITLE
[Library manager] SSD1306XLED library for Attiny85 and SSD1306, SSD1315 and SSH1106 OLED screens

### ISSUE THREAD

**Issue by tejashwikalptaru** [arduino/Arduino#9849]
This library is the port of the original SSD1306XLED library from Tinusaur project with enhancement and fixes in the I2C implementation.

Library supports Atmel series like Attiny85 and OLED screens

Download: https://github.com/tejashwikalptaru/ssd1306xled

Kindly add this library to Arduino library manager, as this library is very small in footprint and supports various OLED displays based on SSD1306, SSD1315 and SSH110

**Comment by cmaglie** [comment]
Done.
