### ISSUE TITLE
[Library Manager] ESP_AT_WiFiManager for ESP8266 AT-command shields

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9854]
https://github.com/khoih-prog/ESP_AT_WiFiManager

This library is based on, modified, bug-fixed and improved from:

1. [`Tzapu WiFiManager`](https://github.com/tzapu/WiFiManager)
2. [`Ken Taylor WiFiManager`](https://github.com/kentaylor/WiFiManager)
3. [`ESP_WiFiManager`](https://github.com/khoih-prog/ESP_WiFiManager)

to support ***Teensy, SAM DUE, SAMD, STM32, etc. boards running ESP8266 AT-command shields.***

#### New in v1.0.0

- This is a Credentials / WiFi Connection Manager with fallback web configuration portal. Completely new to support ***Teensy, SAM DUE, SAMD, STM32, etc. boards running ESP8266 AT-command shields.***

**Comment by cmaglie** [comment]
Done.
