### ISSUE TITLE
[Library Manager] ESP_AT_WM_Lite for ESP8266 AT-command shields

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9859]
https://github.com/khoih-prog/ESP_AT_WM_Lite

This library is a Light Weight Credentials / WiFi Manager for ESP8266 AT shields, specially designed to support ***Teensy, SAM DUE, SAMD, STM32, etc. boards running ESP8266 AT-command shields.*** with smaller memory (64+K bytes)

The AVR-family boards (UNO, Nano, etc.) are ***not supported*** as they don't have enough memory to run Config Portal WebServer.

#### New in v1.0.0

- This is a Light-Weight Credentials / WiFi Connection Manager with fallback web configuration portal. Completely new to support ***Teensy, SAM DUE, SAMD, STM32, etc. boards running ESP8266 AT-command shields.*** with small memory (64+K bytes)

**Comment by cmaglie** [comment]
Done.
