### ISSUE TITLE
[Library Manager] Please Add Arduino TMP102 Arduino Library

### ISSUE THREAD

**Issue by bboyho** [arduino/Arduino#9872]
We've had this library out and it would be amazing if this can be added into the library manager when you have a minute. Please add the following to the library manager for the "SparkFun TMP102 Arduino Library" with v1.0.0 release:

https://github.com/sparkfun/SparkFun_TMP102_Arduino_Library

Thanks! You all are great! ^_^

**Comment by cmaglie** [comment]
Done.
