### ISSUE TITLE
[Library Manager] Remove LoRaLib

### ISSUE THREAD

**Issue by jgromes** [arduino/Arduino#9892]
Hi,

Could you please remove LoRaLib (https://github.com/jgromes/LoRaLib) from library manager? It's no longer being worked on, so I'm starting to phase it out.

Thanks!

**Comment by cmaglie** [comment]
I can't find it this library in the library index, so I'm closing this issue as "done".

Feel free to reopen if I'm missing something...

**Comment by jgromes** [comment]
That's odd, since library manager knows about it and will let me install it.
![Screenshot_1](https://user-images.githubusercontent.com/3407192/77221197-d5151480-6b47-11ea-96a7-26ed856d1dfc.png)
.

**Comment by cmaglie** [comment]
Oh now I can see it :man_facepalming:...

Ok, I've removed it for good now, if you can still see it give some time for the index cache to update.
Thanks.
