### ISSUE TITLE
Add SparkFun DE2120 Barcode Scanner Library

### ISSUE THREAD

**Issue by NPoole** [arduino/Arduino#9896]
Hello, 

Please add our Barcode Scanner library to the library manager. Link here:
https://github.com/sparkfun/SparkFun_DE2120_Arduino_Library

Thanks!

**Comment by per1234** [comment]
Hi @NPoole. I get a 404 from that link. Is the repository private?

**Comment by NPoole** [comment]
And so it was, sorry about that.

**Comment by cmaglie** [comment]
Done.
