### ISSUE TITLE
Arduino Nano 33 IoT - incorrect pin label on pin map

### ISSUE THREAD

**Issue by got879** [arduino/Arduino#9898]
Looks like there is a mistake in the Arduino Nano 33 IoT pinout PDF. 

Port PA11 is used twice. According to the schematic ~D3 should be P**B**11.
![nano33IoTpinouterror](https://user-images.githubusercontent.com/35674328/77236848-86836c80-6b7f-11ea-9ecb-41adc15a3b24.PNG)

**Comment by Rocketct** [comment]
hi all, the picture was changed in to the store, and also de downloadable PDF, I'll close the issue
