### ISSUE TITLE
Word wrapping option in the editor [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#990]
This is [Issue 990](http://code.google.com/p/arduino/issues/detail?id=990) moved from a Google Code project.
Added by 2012-07-21T14:09:56.000Z by [pedrov...@gmail.com](http://code.google.com/u/109309281595840173147/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium

### Original description

**What change would like to see?**

A option for word wrapping on editor.

**Why?**

Better visualization of code, without the need to move or adjust the view.

Thanks.

**Comment by ffissore** [comment]
Since 1.6.5, editor supports code folding. As for wrapping, you should avoid writing long lines in the first place

**Comment by ConnerMcLaughlin** [comment]
This should be reconsidered.  "...you should avoid writing long lines in the first place" assumes all arduino projects only have one contributor.  It is hard enough to keep with the coding guidelines of a community project and have a restriction like this.  Especially if you are minor contributor of the project.  A better suggestion would be to go to File->Preferences and check mark "use external editor."  Then while the Arduino IDE is still open open the project "ino" in another editor.

**Comment by palmerr23** [comment]
I agree.

When editing others' work, there is no way to control the length of the lines they write.

Here's just one line from a piece of library code I was working on today - obviously written by someone with an editor that supports text wrapping. With 4,700 lines, many like this one, editing the code to make it pretty is simply not economically viable OR going to pass through a git pull without a lot of swearing as each edited comment is validated.

`#define LL_ADC_MULTI_REG_DMA_EACH_ADC        0x00000000U                                   /*!< ADC multimode group regular conversions are transferred by DMA: each ADC uses its own DMA channel, with its individual DMA transfer settings */`

In general, well done with the Arduino IDE - most of it is smooth and effortless to use.

**Comment by gwild** [comment]
Sometimes you have to read other people's code.  Word wrap please.
