### ISSUE TITLE
Add library SAM32WiFiEsp

### ISSUE THREAD

**Issue by Enrico204** [arduino/Arduino#9901]
Hi!

I kindly ask you to add SAM32WiFiEsp, which is a fork of WiFiEsp supporting SAM32-based controllers: https://gitlab.com/Enrico204/sam32wifiesp

Regards

**Comment by cmaglie** [comment]
I've added the library to the index but there is a problem:

```
JOB 2826 - 2020/03/23 10:44:15 Checking out tag: v2.2.2-f1
JOB 2826 - 2020/03/23 10:44:15 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

you must define a value for the `url` field inside library.properties: https://gitlab.com/Enrico204/sam32wifiesp/-/blob/master/library.properties

 To fix this:

1. edit library.properties and add the value to the `url` field
2. commit & push
3. delete the `v2.2.2-f1` tag and re-do it on master

after doing so the library will be published automatically in a couple of hours.
Please comment here if you need further assistance.
