### ISSUE TITLE
[Library Manager]  Please add AnalogPin Library

### ISSUE THREAD

**Issue by RobTillaart** [arduino/Arduino#9918]
Please add https://github.com/RobTillaart/AnalogPin
Thanks!

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by RobTillaart** [comment]
Sorry, missed a tick box. Done

**Comment by cmaglie** [comment]
Done.
