### ISSUE TITLE
Function prototypes not generated for variable argument functions [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#992]
This is [Issue 992](http://code.google.com/p/arduino/issues/detail?id=992) moved from a Google Code project.
Added by 2012-07-27T17:08:51.000Z by [janar.s...@gmail.com](http://code.google.com/u/115724867442263714249/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-IDE

### Original description

**What steps will reproduce the problem?**
1. Make new Arduino project having a main file and additional ".ino" file.

2. Into additional ".ino" file insert a function definition having C style variable arguments.
void nice_func(const char *fmt, ...) 
{
  // do nothing
}

3. Now insert call to that function into main file. For example inside
loop function:
void loop()
{  
  nice_func("test", 1);
}

During compilation of the whole project Arduino gives error that
'nice_func' was not declared in this scope.

When we peek into temporary build directory then we can see that Arduino is not inserting that function prototype definition into final .cpp file.

For example if you change inside additional ".ino" file this function definition to:
void nice_func(const char *fmt, int i)
{
  // do nothing
}
and now it'll compile without errors.

It seems that file building functionality (part that is inserting prototype definitions)
inside Arduino is skipping functions having "..." inside arguments area.

I'm using Arduino 1.0.1 on WinXP x64.

**Comment by ffissore** [comment]
Please checkout this thread [1] on devs mailing list and try one of the linked IDEs. It should fix the problems reported in this issue
[1] https://groups.google.com/a/arduino.cc/forum/#!topic/developers/4X2T3rCxXWM

**Comment by ffissore** [comment]
New preprocessor tracked at #2636. Builds for testing it are available

**Comment by ffissore** [comment]
Fixed by #3779
