### ISSUE TITLE
[Library Manager] WiFiWebServer for WiFi (WiFiNINA, W101, W102, etc.) Modules/ Shields

### ISSUE THREAD

**Issue by khoih-prog** [arduino/Arduino#9921]
https://github.com/khoih-prog/WiFiWebServer

### Initial Version v1.0.0

This is simple yet complete WebServer library for `AVR, Teensy, SAM DUE, SAMD, STM32, etc.` boards running WiFi modules/shields (WiFiNINA U-Blox W101, W102, etc.). ***The functions are similar and compatible to ESP8266/ESP32 WebServer libraries*** to make life much easier to port sketches from ESP8266/ESP32.

The library currently supports these boards
1. SAM DUE
2. SAMD21 (ZERO, MKR, NANO_33_IOT, M0, M0 Pro, AdaFruit CIRCUITPLAYGROUND_EXPRESS, etc.)
3. SAMD51 (Adafruit M4 : Metro, Grand Central, ItsyBitsy, Feather Express, Trellis, Metro AirLift lite, MONSTER M4SK Express, Hallowing Express, etc. )
4. Teensy (4.0, 3.6, 3.5, 3,2, 3.1, 3.0, LC)
5. STM32F1, STM32F2, STM32F4, STM32F7

The library supports 
1. WiFi Client, STA and AP mode
2. TCP Server and Client
3. UDP Server and Client
4. HTTP Server and Client
5. HTTP GET and POST requests, provides argument parsing, handles one client at a time.

**Comment by cmaglie** [comment]
Done.
