### ISSUE TITLE
LM35 Temperature sensor

### ISSUE THREAD

**Issue by cardinalray101** [arduino/Arduino#9932]
Hello 

anyone to kindly assist, Im working on a weather station using arduino butv i only have LM35 sensor,  i have a code for DHT sensor how do i convert the DHT sensor code to suit the LM5 sensor code

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
