### ISSUE TITLE
New Library: OptocouplerDebouncer

### ISSUE THREAD

**Issue by dirkx** [arduino/Arduino#9951]
https://github.com/dirkx/OptocouplerDebouncer

# Optocoupler Debouncer

It is common to use an optocoupler to detect if there is AC power. However if you directly connect these to your Arduino/ESP32 board, without some RC damping, - you will typically get a 100 Hz pulse.

This library provides a simple way to get a 'on/off' asynchronous call when the optocoupler is directly wired to the MCU. In use at the https://makerspaceleiden.nl

**Comment by cmaglie** [comment]
Done.
