### ISSUE TITLE
New Library: MFRC522-spi-i2c-uart-async

### ISSUE THREAD

**Issue by dirkx** [arduino/Arduino#9952]
https://github.com/MakerSpaceLeiden/rfid.git
Read/Write a RFID Card or Tag using the ISO/IEC 14443A/MIFARE interface. 

Modified from the original miguelbalboa to also support I2C and UART connections and provide, in addition to normal constant polling, an option to do asynchroneous callbacks. I.e. have a function called each time that a valid swipe has happend. 

Used at the https://makerspaceleiden.nl for its door and machine management https://wiki.makerspaceleiden.nl/mediawiki/index.php/Categorie:ACNode

Renamed from MFRC522 to MFRC522-spi-i2c-uart-async to not clash with the 2016 version already in the Libraries collectoin.

https://github.com/MakerSpaceLeiden/rfid/releases/tag/1.5.1
https://github.com/MakerSpaceLeiden/rfid.git

**Comment by cmaglie** [comment]
Done.
