### ISSUE TITLE
[Library Manager] Add MovingAverage lib

### ISSUE THREAD

**Issue by AlexandreHiroyuki** [arduino/Arduino#9960]
# Moving Average Library
https://github.com/AlexandreHiroyuki/MovingAverage_ArduinoLibrary

## First stable release v1.2.1
- Implements a simple moving average class

## The latest stable release v1.3.1
- Added a new feature that allows reading the array through the operator syntax
> Example:
 `MovingAverage<int> a(10, 1); Serial.println(a[2]);`

**Comment by cmaglie** [comment]
Done.
