### ISSUE TITLE
[Library Manager] Change library name property - BQ27441

### ISSUE THREAD

**Issue by nseidle** [arduino/Arduino#9966]
Hi - We had a typo in [this repo's](https://github.com/sparkfun/SparkFun_BQ27441_Arduino_Library) name value.

The repo name on github is correct. The library.properties name= value is wrong.

New/correct name=SparkFun BQ27441 LiPo Fuel Gauge Arduino Library

The old/incorrect name had the 72 of BQ27 swapped.

Please fix so that the library can get updated in the lib manager. Thanks!

**Comment by cmaglie** [comment]
Done.

**Comment by nseidle** [comment]
That fixed it. Showing up correctly in IDE. Thanks @cmaglie!
