### ISSUE TITLE
[Library Manager] SDConfigCommand

### ISSUE THREAD

**Issue by cygig** [arduino/Arduino#9970]
Please add my library! Thank you and stay safe everyone!
Link: https://github.com/cygig/SDConfigCommand

SDConfigCommand streamlines reading settings from a config file on SD card. 

SDConfigCommand can read standardised text files stored on a SD card, parse and tokenise them into commands and values. The library can also write over existing settings but it is currently slow to do so. 

For every line on the config file this library reads, it will callback a user-specified function. The user can access the current command and values, then decide the next action, such as verifying commands and storing values in variables. With regards to writing over existing settings, user can choose one command, and the library will search for the command in the config file and replace the whole setting line with a new value. The library does not add or remove settings.

Arduino String return and parameter type is supported for beginners, C-string is also available for advanced users.

**Comment by cmaglie** [comment]
Done.
