### ISSUE TITLE
Change repository URL

### ISSUE THREAD

**Issue by DBSStore** [arduino/Arduino#9981]
https://github.com/DBSStore/DBS_Lib
I entered the wrong name and was already published. I want to change my repository URL from:
https://github.com/DBSStore/DBS_AVRIII
to:
https://github.com/DBSStore/DBS_Lib

**Comment by DBSStore** [comment]
What should I do?

**Comment by cmaglie** [comment]
I see that you changed the name in library.properties, but you should also re-do the tag that is still pointing to the previous version.

https://github.com/DBSStore/DBS_Lib/blob/master/library.properties
https://github.com/DBSStore/DBS_Lib/blob/1.0.0/library.properties   <-- still has AVRIII

Just delete and re-do the 1.0.0 tag on master.

**Comment by DBSStore** [comment]
I did

**Comment by cmaglie** [comment]
Ok, done.
