### ISSUE TITLE
New library: Birdhouse SDK

### ISSUE THREAD

**Issue by Nargott** [arduino/Arduino#9982]
Hi.

I'd like to add my library to Arduino Library Manager. It's available here: https://github.com/Nargott/birdhouse_sdk

Thanks in advance!

**Comment by per1234** [comment]
Hi @Nargott. You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Nargott** [comment]
Thanks for your advice. 
https://github.com/Nargott/birdhouse_sdk/tree/v1.0.0

**Comment by cmaglie** [comment]
Done.
