### ISSUE TITLE
File update detection bug (external editor mode) [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#999]
This is [Issue 999](http://code.google.com/p/arduino/issues/detail?id=999) moved from a Google Code project.
Added by 2012-07-31T18:54:11.000Z by [mkwi...@gmail.com](http://code.google.com/u/117518688685426805943/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open the IDE in the external editor mode.
2. Load a sketch (File -> Open)
3. Create a new sketch (File -> New)
4. Disable external editor mode
5. Update the previous sketch with the external editor
5. Go back the previous sketch and compile

**What is the expected output? What do you see instead?**
I expected the sketch to be updated in the IDE because the Arduino editor display is still grayed out like it would be when it is in the external editor mode.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino IDE 1.0.1 on Windows XP SP3 with an Arduino Uno R3

**Comment by ffissore** [comment]
Latest hourly build of the IDE shows a white background on every window when external editor mode is disabled. I guess this was fixed some time ago
