### ISSUE TITLE
Please include this library....

### ISSUE THREAD

**Issue by JPF1976** [arduino/Arduino#9990]
Please can you add this library:

https://github.com/nabontra/ServoTimer2

Thank you.

JP

**Comment by JPF1976** [comment]
Thank you, I will try and report back to you.

**Comment by JPF1976** [comment]
Hi,

Is there a reason the official website has no timer 2 functions?

**Comment by per1234** [comment]
Closing due to lack of resolution of the issues I mentioned in my previous reply.

@JPF1976 if you ever get around to making your library compliant, comment here and I'll re-open this issue.

**Comment by JPF1976** [comment]
No idea what to do, located another one. Thank you anyway though....
